### PR TITLE
Add 2023-02-28-preview.

### PR DESCRIPTION
**Pull request by bojunehsu**
# Data Plane API - Pull Request

## API Info: The Basics

* Link to engagement record issue: https://github.com/Azure/azure-rest-api-specs-pr/issues/10377

Is this review for (select one):

- [ ] a private preview
- [X] a public preview
- [ ] GA release

### Change Scope

* Internal PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/9885
* Previous Open API Doc: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/FormRecognizer/stable/2022-08-31/FormRecognizer.json
* Updates
  * New properties in the analysis output
    * Barcodes
    * Annotations
      * Tweaking definition of selection marks to make behavior more consistent.
    * Common name for keyValuePairs
    * Currency code for currency field values
    * Font/style
    * Formula
  * New properties in model output
    * Model expiration
  * New optional query parameters
    * Analyze features
    * Query fields
  * New API operations
    * Document splitting and classification operations

### CODE REVIEW

**Comment by bojunehsu** [comment]
@mikekistler I have ported over the changes from the [internal PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/9885).  Can you please approve this PR (with breaking change approval if needed)?  Thanks.

**Review by mikekistler — APPROVED** [review]
Restating approval from internal PR.

**Comment by bojunehsu** [comment]
@yangyuan Can you please merge the PR?  Thanks.

**Comment by nizi1127** [comment]
It looks goo to me.
Only one open question about tag for classifier operations.
DocumentModel tag decides by operation types, that are "Analysis", "Creation" and "Management".
But document classifier operations are group to one tag "classifier".
Is it expected?

**Review by nizi1127 — APPROVED** [review]
LGTM

**Comment by bojunehsu** [comment]
@anuchandy Can you please merge this PR?

**Pull request merged**
