### PR TITLE
Add libgit2 to custom-words.txt

### PR DESCRIPTION
**Pull request by leonard520**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by yuwzho — APPROVED** [review]

**Comment by leonard520** [comment]
@weshaggard Would you please take a look at this PR? Thanks!

**Comment by leonard520** [comment]
@weshaggard Kindly ping on this RP. Thanks.

**Comment by weshaggard** [comment]
Sorry @leonard520 I was on holiday the last couple weeks. Can you help point me at where we need to use libgit2 at?

**Comment by leonard520** [comment]
> Sorry @leonard520 I was on holiday the last couple weeks. Can you help point me at where we need to use libgit2 at?

Here it is https://github.com/Azure/azure-rest-api-specs/blob/7a929a631841e4401b7df995ce03d73af3e177f6/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2023-05-01-preview/appplatform.json#L9817

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
