### PR TITLE
[CDN] Add new API version 2024-05-01-preview for CDN

### PR DESCRIPTION
**Pull request by ChenglongLiu**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
        Refer the PR in private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753
         - Add new version 2024-05-01-preview
        - Add a new property `grpcState` in route: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753/commits/9b8b8e8e8dbc12e65a8123384d2ff34d7d298f8a
        - Add cipher suites for custom domain resource: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753/commits/d8c333d694e65e4d0da5e47d11be991c17094181
        - Add keygroup API: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753/commits/c6e8b27695045aef6e1a64f0f90a91e7e268ead1
        - Add property to support mTLS in secret and custom domain resource: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753/commits/ffc1c400c0ce9c9600801fb1347ff12089c11c47
        - Add API for classic CDN migration to AFD: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753/commits/ac9a5749d218179b7846a920f360ae18505ea1b7
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by ChenglongLiu** [comment]
Refer the PR in private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753

**Comment by razvanbadea-msft** [comment]
Removing the MergeRequested label as this PR needs to be ARMSignedOff and obtain a BreakingChange Approval before being able to be merged. To unblock this PR, follow the process at [aka.ms/brch](https://aka.ms/brch).

**Comment by ChenglongLiu** [comment]
@razvanbadea-msft This is PR move from private repo by following the process at [aka.ms/azsdk/move-pr](https://aka.ms/azsdk/move-pr). The PR in private repo already got `ARMSignedOff` and `Approved-OkToMerge` tags, refer: https://github.com/Azure/azure-rest-api-specs-pr/pull/17753

**Comment by ChenglongLiu** [comment]
The changes to the REST API definition are correcting the definition to accurately describe the service behavior,so bypass the review process by adding `BreakingChange-Approved-BugFix`.

1. 1023 - TypeFormatChanged is introdued when the reviewer ask adding `"format": "arm-id"`
2. 1025 - RequiredStatusChange and 1034 - AddedRequiredProperty are reuired change for correcting the definition to accurately describe the service behavior. The `SecretVersion` alway needed.

**Review by mentat9 — APPROVED** [review]

**Pull request merged**
