### PR TITLE
Change group name for operations path, and rename response type definition

### PR DESCRIPTION
**Pull request by bulentelmaci**
Change group name for operations path, and rename response type definition so that it does not conflict with the group name. This seems to be a common pattern in a lot of RPs and makes more sense.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by bulentelmaci** [comment]
@marstr None of the Travis CI build jobs seem to have started since I submitted this. Any known issues that require me to do something to get this going?

**Comment by bulentelmaci** [comment]
Note: No SDK was generated/published yet for this, hence the method name and response type changes will not effect any customers. I wanted to do this change before I start generating SDKs, which is the next step for us.

**Review by marstr — CHANGES_REQUESTED** [review]
Because these are in the `preview` folder, the breaking changes are not a concern.

However, it seems like the files in the PolicyInsights RP do not conform to our repository structure.

Please update this so that `PolicyStates` isn't its own Resource Type folder, the filename will do.

**Comment by bulentelmaci** [comment]
@marstr Not sure I understand the change you are requesting. These went in this repo for the first time two days ago and I was not asked to make any changes to the folder structure when reviewed. Please see https://github.com/Azure/azure-rest-api-specs/pull/2523 . Could you please sync up with @sarangan12 and/or @salameer ?

**Review by marstr — APPROVED** [review]
Chatted with @bulentelmaci offline. We agreed not to gate these changes on the paths of the files we're targeting. We'll have a follow-up meeting on Monday to talk further.

**Pull request merged**
