### PR TITLE
[correctness] updated operation type in Storage container to correct payload 

### PR DESCRIPTION
**Pull request by hiaga**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by viveksheelsingh — APPROVED** [review]
Since there is no svc behaviour chnage, and breaking chnage board has approved, approving.

**Comment by mikekistler** [comment]
@mikeharder Pls have a look at this PR. I think it should have been labeled `VersioningReviewRequired` since only compatible changes were made and with no API version change, but the bot labelled it `BreakingChangeReviewRequired`. There were no issues flagged by the BreakingChanges (Cross Version) PR check.

**Comment by mikeharder** [comment]
> @mikeharder Pls have a look at this PR. I think it should have been labeled `VersioningReviewRequired` since only compatible changes were made and with no API version change, but the bot labelled it `BreakingChangeReviewRequired`. There were no issues flagged by the BreakingChanges (Cross Version) PR check.

Check `BreakingChanges (Cross Version)` passed, but check `Swagger BreakingChanges` failed.  Given this, do you still think this PR should **not** have been lableled `BreakingChangeReviewRequired`?

**Comment by mikekistler** [comment]
In the doc you linked it says:

> The label VersioningReviewRequired denotes that your PR has a versioning issue possibly violating the [Azure Versioning and Breaking Changes Policy](https://aka.ms/AzBreakingChangesPolicy). This happens when you made a non-breaking change, aka compatible change to an API version that was already published (merged to a production branch).

The issues flagged in the `Swagger BreakingChanges` check -- added enum values and added optional property -- would be perfectly fine if done in a new api-version. They are flagged only because they were made in an existing api-version. So I do think that `VersioningReviewRequired` is the correct label.

**Comment by hiaga** [comment]
Hi @mikeharder, @mikekistler could you please help find conclusion to above discussion. We're currently blocked on this PR for some PowerShell changes

**Pull request merged**
