### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by calexan**
Adding swagger spec for RemoteApp client

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@calexan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (calebal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@calexan - Please squash your git commits http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by amarzavery** [comment]
"host": "management.azure.net",
I have never seen this before. Usually the host is "management.azure.com". Is RemoteApp a special case ?

**Comment by amarzavery** [comment]
Line 21 remove empty line
Tabbing for entire document : 2 spaces. If you are using Visual Studio then set the tabs for JSON to 2 spaces and then CTrl + A, Ctrl + K + D

**Comment by amarzavery** [comment]
Are ActivateAccountBilling and UpdateAccount long running operations. If so then you need to add the extension x-ms-long-running: true. Please check all our extensions over here and apply them wherever applicable https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md

**Comment by amarzavery** [comment]
operation TemplateImage_GetTemplateImages needs x-ms-pageable extension

**Comment by amarzavery** [comment]
We prefer a naming convention of Noun_Verb for operationId. The noun becomes an operation group and the verb is the method under the operation group
Current Operation    -> Recommended Approach  --> This is how customers will call from generated client
Operations_GetAvailableOperations --> Operations_GetAvailable --> client.Operations.GetAvailable()
Account_GetAccountInfo   --> Account_Get -> client.Account.Get()
Account_ActivateAccountBilling --> Account_ActivateBilling  -> client.Account.ActivateBilling()
TemplateImage_GetTemplateImages --> TemplateImage_List --> client.TemplateImage.List()
TemplateImage_GetTemplateImage --> TemplateImage_Get --> client.TemplateImage.Get()

**Comment by amarzavery** [comment]
Operation Collection_ListResourceGroupCollections misses the definition of resourceGroupName path paameter

**Comment by amarzavery** [comment]
Please make sure that all the description properties are well documented. There is an ongoing project to turn the swagger spec into API reference docs. The description will also turn into the documentation of your generated client. So please make sure you update all your descriptions.

**Comment by amarzavery** [comment]
Collection_GetPublishedApp missing resourceGroupName parameter

**Comment by calexan** [comment]
@amarzavery 

Get_TemplateImages isn't pageable, we restrict the number of template images they can have to ~12 or so.

ActivateBilling and UpdateAccount are not long running operations.

**Comment by amarzavery** [comment]
@calexan - I understand that Get_TemplateImages isn't pageable. However, you can add the extension with explicitly specifying nextLink: null in the extension. StorageManagement does the same thing. They only provide one page of storage accounts. The benefit is that you get a better client side API.

Take a look at the storage spec over here: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2015-06-15/swagger/storage.json#L299 

and the corresponding code in C#
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Storage/Microsoft.Azure.Management.Storage/Generated/StorageAccountsOperations.cs#L1246

```
public async Task<AzureOperationResponse<IEnumerable<StorageAccount>>> ListWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

It gives you an IEnumerable of StorageAccount objects.

//basically we flatten the value property and directly give you the array of desired objects.

**Comment by calexan** [comment]
@amarzavery 

Thanks for the tip, you should find the spec updated with it.

**Pull request merged**
