### PR TITLE
[Hub Generated] Publish private branch 'ssivathas/2023-06-01'

### PR DESCRIPTION
**Pull request by JeetendraJoshi-MSFT**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/published%2FAzure%2Fazure-rest-api-specs-pr%2Fssivathas%2F2023-06-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by JeetendraJoshi-MSFT** [comment]
The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/12428](https://github.com/Azure/azure-rest-api-specs-pr/pull/12428)

**Comment by JeetendraJoshi-MSFT** [comment]
Hi @v-jiaodi , in terms of the breaking changes they have been discussed in the following PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/12428

**Comment by v-jiaodi** [comment]
@JeetendraJoshi-MSFT The SDK azure-sdk-for-go and Avocado iare required, if not fixed or approved, they will block the PR merge.

**Comment by JeetendraJoshi-MSFT** [comment]
@v-jiaodi Now the last CI changes remaining are the SDK for powershell, this seems to always break but has been fine to approve prior. This PR does contain breaking changes and as mentioned they were approved in the previous PR. It says for the Swagger APIView to contact you: 
image
So unsure what to do on that one.

**Comment by v-jiaodi** [comment]
Add label `Approved-BreakingChange` as Mikekistler has already approved it in https://github.com/Azure/azure-rest-api-specs-pr/pull/12428

**Comment by v-jiaodi** [comment]
Add label `ARMSignedOff` as **mentat9** has already approved it in https://github.com/Azure/azure-rest-api-specs-pr/pull/12428

**Comment by v-jiaodi** [comment]
@qiaozha @msyyc @raych1 could you help to take a look at the SDK BreakingChange error in this PR? Thanks

**Comment by v-jiaodi** [comment]
> @v-jiaodi Now the last CI changes remaining are the SDK for powershell, this seems to always break but has been fine to approve prior. This PR does contain breaking changes and as mentioned they were approved in the previous PR. It says for the Swagger APIView to contact you: image So unsure what to do on that one.

@JeetendraJoshi-MSFT SDK azure-powershell error can been ignored. The Swagger APIView check has now passed.

**Review by v-jiaodi — APPROVED** [review]

**Pull request merged**
