### PR TITLE
[Hub Generated] Review request for Microsoft.CostManagement to add version stable/2019-11-01

### PR DESCRIPTION
**Pull request by paornela**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/paornela/azure-rest-api-specs/dev-cost-management-Microsoft.CostManagement-2019-11-01...master/).

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
Please go through the contribution checklist added as part of the review and mark them completed. This is a requirement before review can be continued.

**Comment by chiragg4u** [comment]
Only change is spliting the file, no ARM API review required, Removing the WaitForARMFeedback tag.

**Comment by raych1** [comment]
@paornela , can you resolve the lintDiff failures about duplicate Enum name defined?

**Comment by raych1** [comment]
Hi @changlong-liu , could you review the breaking change in python SDK? Are they caused by this PR change?

**Comment by changlong-liu** [comment]
> Hi @changlong-liu Changlong Liu FTE , could you review the breaking change in python SDK? Are they caused by this PR change?

Hi @raych1 , the breaking changes don't come from this PR.

**Comment by paornela** [comment]
@raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.

**Comment by raych1** [comment]
> @raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.

@paornela , it doesn't allow the same enum name across multiple swagger files defined in a tag in readme.md.

**Comment by paornela** [comment]
> > @raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.
> 
> @paornela , it doesn't allow the same enum name across multiple swagger files defined in a tag in readme.md.

@raych1 If this were the case, wouldn't it have flagged ExportType, TimeframeType, and more that have the same enum name across both swagger files? Also, when I re-ran the validation checks on OpenApi Hub for this latest commit, there are no lint checker errors.

**Comment by jianyexi** [comment]
> > > @raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.
> > 
> > 
> > @paornela , it doesn't allow the same enum name across multiple swagger files defined in a tag in readme.md.
> 
> @raych1 If this were the case, wouldn't it have flagged ExportType, TimeframeType, and more that have the same enum name across both swagger files? Also, when I re-ran the validation checks on OpenApi Hub for this latest commit, there are no lint checker errors.

You can't have the same enum name with different definition, The reason is  the operationType [here](https://github.com/Azure/azure-rest-api-specs/blob/e6c45ce15cc4521f884b3b0969788d40af74dccb/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1375)  has two option values while others have only one option

**Comment by paornela** [comment]
> > > > @raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.
> > > 
> > > 
> > > @paornela , it doesn't allow the same enum name across multiple swagger files defined in a tag in readme.md.
> > 
> > 
> > @raych1 If this were the case, wouldn't it have flagged ExportType, TimeframeType, and more that have the same enum name across both swagger files? Also, when I re-ran the validation checks on OpenApi Hub for this latest commit, there are no lint checker errors.
> 
> You can't have the same enum name with different definition, The reason is the operationType [here](https://github.com/Azure/azure-rest-api-specs/blob/e6c45ce15cc4521f884b3b0969788d40af74dccb/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1375) has two option values while others have only one option

@jianyexi The goal of this PR is to separate the existing Swagger costmanagement.json into 2 Swagger files without breaking anything. I see what you're saying regarding the two different definitions, but the duplicate enum name "operatorType" already existed in the original swagger before this PR [as you can see here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L2726). Since this PR did not introduce this change, I am not sure why it is blocking validation here.

**Comment by raych1** [comment]
> > > > > @raych1 I checked and the lintDiff failures about duplicate Enum name defined are incorrect as far as I can tell. The changes on this PR do not add a type with the same enum, so I'm not sure why that error is showing up. In the file costmanagment.exports.json, there is only one enum type operationType. In costmanagement.json, there are 2 operationType, but those were not implemented through this PR. Please provide guidance on how to proceed.
> > > > 
> > > > 
> > > > @paornela , it doesn't allow the same enum name across multiple swagger files defined in a tag in readme.md.
> > > 
> > > 
> > > @raych1 If this were the case, wouldn't it have flagged ExportType, TimeframeType, and more that have the same enum name across both swagger files? Also, when I re-ran the validation checks on OpenApi Hub for this latest commit, there are no lint checker errors.
> > 
> > 
> > You can't have the same enum name with different definition, The reason is the operationType [here](https://github.com/Azure/azure-rest-api-specs/blob/e6c45ce15cc4521f884b3b0969788d40af74dccb/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1375) has two option values while others have only one option
> 
> @jianyexi The goal of this PR is to separate the existing Swagger costmanagement.json into 2 Swagger files without breaking anything. I see what you're saying regarding the two different definitions, but the duplicate enum name "operatorType" already existed in the original swagger before this PR [as you can see here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L2726). Since this PR did not introduce this change, I am not sure why it is blocking validation here.

@paornela , the lintDiff failure isn't introduced by your change in this PR. It exists in current swagger file. Two values are different for this same enum name type. e.g. [value 1](https://github.com/Azure/azure-rest-api-specs/blob/39466d240538fb7d679e23b180b79d6e9ed80627/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L2722) and [value 2](https://github.com/Azure/azure-rest-api-specs/blob/39466d240538fb7d679e23b180b79d6e9ed80627/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1717) 
Regard to this PR, I will approve and merge it. However, can you create a task in backlog to fix this conflict issue in the future PR?

**Review by Zzegfried — APPROVED** [review]

**Pull request merged**
