### PR TITLE
fix schema generation failure for securityinsights

### PR DESCRIPTION
**Pull request by leniatgh**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by leni-msft** [comment]
Fixes schema generation failure:
```
2020-07-05T11:38:44.1174839Z [/home/vsts/work/1/s/generator] executing: autorest-beta --version=3.0.6274 --use=@autorest/azureresourceschema@3.0.79 --azureresourceschema --output-folder=/tmp/8ciywltrstk --tag=all-api-versions --api-version=2020-01-01 --title=none --pass-thru:subset-reducer /tmp/schm_azspc/specification/securityinsights/resource-manager/readme.md
2020-07-05T11:38:44.4805090Z AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.1, max-memory: 8192 gb]
2020-07-05T11:38:44.4815930Z (C) 2018 Microsoft Corporation.
2020-07-05T11:38:44.4816835Z https://aka.ms/autorest
2020-07-05T11:38:45.2966932Z    Loading AutoRest core      '/home/vsts/.autorest/@autorest_core@3.0.6274/node_modules/@autorest/core/dist' (3.0.6274)
2020-07-05T11:38:46.3235067Z    Loading AutoRest extension '@autorest/azureresourceschema' (3.0.79->3.0.79)
2020-07-05T11:38:53.4391585Z FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'alerts' in schema inheritance chain 
2020-07-05T11:38:53.4393943Z    at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /home/vsts/work/1/s/autorest.common/src/SchemaResolver.cs:line 158
2020-07-05T11:38:53.4395005Z    at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /home/vsts/work/1/s/autorest.common/src/SchemaResolver.cs:line 76
2020-07-05T11:38:53.4396072Z    at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /home/vsts/work/1/s/autorest.common/src/SchemaBuilder.cs:line 122
2020-07-05T11:38:53.4397306Z    at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /home/vsts/work/1/s/autorest.common/src/SchemaBuilder.cs:line 138
2020-07-05T11:38:53.4398419Z    at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /home/vsts/work/1/s/autorest.common/src/SwaggerModeler.cs:line 349
2020-07-05T11:38:53.4399475Z    at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /home/vsts/work/1/s/autorest.common/src/SwaggerModeler.cs:line 66
2020-07-05T11:38:53.4400522Z    at AutoRest.Modeler.ModelerPlugin.<ProcessInternal>d__1.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Program.cs:line 43
2020-07-05T11:38:53.4401788Z --- End of stack trace from previous location where exception was thrown ---
2020-07-05T11:38:53.4402558Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-07-05T11:38:53.4403354Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-07-05T11:38:53.4404139Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2020-07-05T11:38:53.4405303Z    at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/common/Plugins/NewPlugin.cs:line 164
2020-07-05T11:38:53.4433931Z   Error: Plugin imodeler2 reported failure.
2020-07-05T11:38:53.4804191Z Caught exception processing autogenlist entry securityinsights/resource-manager.
2020-07-05T11:38:53.4805516Z Exited with code 1
```

**Comment by weidongxu-microsoft** [comment]
Please add code owner to reviewer.

**Comment by jorgecotillo** [comment]
@alshulma can you please review this PR? the schema generation failed due to "alerts" property having different schemas: https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=11699&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d Line 1122.

**Comment by alshulma** [comment]
+Mico
________________________________

**Comment by weidongxu-microsoft** [comment]
Follow the guideline...


As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ Breaking Change Process

**Comment by leni-msft** [comment]
@weidongxu-microsoft I confirmed with breakingchange tool owner. The tool doesn't support this case yet. It's not breaking change, since the schema doesn't change.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
@leni-msft Sure, you can let him do the merge after code owner is OK with it.

The problem with that BreakingChange CI is that if it fails, I won't be able to press the merge button at all...

**Comment by ofshomro** [comment]
code owner approves changes

**Pull request merged**
