### PR TITLE
[Microsoft.AzureStackHCI] Add 2024-04-01 for StackHCI

### PR DESCRIPTION
**Pull request by priyjain358**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by priyjain358** [comment]
PR in review in private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/17717

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #27600.

**Comment by razvanbadea-msft** [comment]
The first commit needs to be an exact copy of the previous api version. All new changes should only be added in the subsequent commits. 

This is explained in detail here - https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=openapi

**Comment by priyjain358** [comment]
> The first commit needs to be an exact copy of the previous api version. All new changes should only be added in the subsequent commits.
> 
> This is explained in detail here - https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=openapi

@razvanbadea-msft With the deprecation of openapihub, we followed the instructions mentioned here: https://eng.ms/docs/products/azure-developer-experience/design/api-specs-pr/pr-move-private-to-public 
This doesn't talk about adding a base commit. You can refer to the private PR https://github.com/Azure/azure-rest-api-specs-pr/pull/17717 
Let me know if you still want me to change the commit structure. Thanks

**Comment by razvanbadea-msft** [comment]
> > The first commit needs to be an exact copy of the previous api version. All new changes should only be added in the subsequent commits.
> > This is explained in detail here - https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=openapi
> 
> @razvanbadea-msft With the deprecation of openapihub, we followed the instructions mentioned here: https://eng.ms/docs/products/azure-developer-experience/design/api-specs-pr/pr-move-private-to-public This doesn't talk about adding a base commit. You can refer to the private PR [Azure/azure-rest-api-specs-pr#17717](https://github.com/Azure/azure-rest-api-specs-pr/pull/17717) Let me know if you still want me to change the commit structure. Thanks

Services that use TypeSpec to describe their REST API must include both the TypeSpec source spec and generated OpenAPI specs in the specs repo. ( https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=typespec )

**Comment by priyjain358** [comment]
> > > The first commit needs to be an exact copy of the previous api version. All new changes should only be added in the subsequent commits.
> > > This is explained in detail here - https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=openapi
> > 
> > 
> > @razvanbadea-msft With the deprecation of openapihub, we followed the instructions mentioned here: https://eng.ms/docs/products/azure-developer-experience/design/api-specs-pr/pr-move-private-to-public This doesn't talk about adding a base commit. You can refer to the private PR [Azure/azure-rest-api-specs-pr#17717](https://github.com/Azure/azure-rest-api-specs-pr/pull/17717) Let me know if you still want me to change the commit structure. Thanks
> 
> Services that use TypeSpec to describe their REST API must include both the TypeSpec source spec and generated OpenAPI specs in the specs repo. ( https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-specs?tabs=typespec )

We are not using typespec for our service. We have two services using the same namespace Micrososft.AzureStackHCI. StackHCI is not using typespec where we are adding the new api-version.

**Comment by kazrael2119** [comment]
@priyjain358 ,please add https://github.com/Azure/azure-rest-api-specs-pr/pull/17717/files#diff-a601ee7752776b4194efc8f920940b8d42dc5b20c2c8789168b79ba74dbd1488 to this PR

**Comment by priyjain358** [comment]
> @priyjain358 ,please add https://github.com/Azure/azure-rest-api-specs-pr/pull/17717/files#diff-a601ee7752776b4194efc8f920940b8d42dc5b20c2c8789168b79ba74dbd1488 to this PR

Hi @kazrael2119, that folder is owned by the other team - StackHCIVM and as I can see they haven't added typespec yet to the main repo. We ("StackHCI") are an already GA service and are not using typespec as well as of now.

**Comment by kazrael2119** [comment]
> > @priyjain358 ,please add https://github.com/Azure/azure-rest-api-specs-pr/pull/17717/files#diff-a601ee7752776b4194efc8f920940b8d42dc5b20c2c8789168b79ba74dbd1488 to this PR
> 
> Hi @kazrael2119, that folder is owned by the other team - StackHCIVM and as I can see they haven't added typespec yet to the main repo. We ("StackHCI") are an already GA service and are not using typespec as well as of now.

@priyjain358 I mean you only need add this file
image
from the pr in private repo to this pr

**Comment by priyjain358** [comment]
> > > @priyjain358 ,please add https://github.com/Azure/azure-rest-api-specs-pr/pull/17717/files#diff-a601ee7752776b4194efc8f920940b8d42dc5b20c2c8789168b79ba74dbd1488 to this PR
> > 
> > 
> > Hi @kazrael2119, that folder is owned by the other team - StackHCIVM and as I can see they haven't added typespec yet to the main repo. We ("StackHCI") are an already GA service and are not using typespec as well as of now.
> 
> @priyjain358 I mean you only need add this file https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/azurestackhci/resource-manager/sdk-suppressions.yaml image from the RPSaaSMaster branch in private repo to this pr

Done, please have a look. @kazrael2119

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
