### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-08-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
    Alread deployed to all global regions by 08/29.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
    ASAP, 09/01.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Dear review board, I would like to clarify the failures in the CI checks.

For [SDK azure-powershell](https://github.com/Azure/azure-rest-api-specs/pull/20487/checks?check_run_id=8105779773), it happened in our previous PR [07-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/20062). From log it seems that the reason for the failure lies in the build tool `/home/cloudtest/.autorest/@autorest_powershell@3.0.491/node_modules/@autorest/powershell/dist/plugins/llcsharp-v2.js - TypeError: value.replace is not a function`. This CI used to be optional and is enabled recently.

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/20487/checks?check_run_id=8105779385), it happened in our previous PR [07-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/20062). I suppose this should be a known issue. Besides it's going to be replaced by track 2 SDK, which is expected to be GA in mid-August.

For [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/20487/checks?check_run_id=8105733273), it should be a false alert. The reported missing API [2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2019-10-27-preview/openShiftManagedClusters.json) is deprecated and removed from ARM manifest. The other one [2022-07-02-preview/fleets.json](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/fleets.json) is expected. There are no updates to this sub-rp, so it's not included in the new API as requested by the feature owner. These errors started appearing after [this update](https://github.com/Azure/avocado/pull/78) of Avocado. Would really appreciate if some mechanism could be provided to disable the alarms, cc owner @ruowan.

For [~[Staging] Service API Readiness Test](https://github.com/Azure/azure-rest-api-specs/pull/20487/checks?check_run_id=8105733424), from the log, it seems that this part of the check in this CI is still being implemented, and the requests sent by the testing process are invalid.

For [~[Staging] Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/20487/checks?check_run_id=8105733226), 
- Violation of [ProvisioningStateValidation](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/provisioning-state-validation.md), [LroLocationHeader](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/lro-location-header.md) and [XmsLongRunningOperationOptions](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/xms-long-running-operation-options.md) should be fixed by PR [#20490](https://github.com/Azure/azure-rest-api-specs/pull/20490) and PR [#20491](https://github.com/Azure/azure-rest-api-specs/pull/20491) (under review by feature owners).
- [DefinitionsPropertiesNamesCamelCase](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/definitions-properties-names-camel-case.md), I suppose there's something wrong with the scanning results.
  -  [enableCustomCATrust](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json#L3460), already exists in previous preview API [2022-07-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/managedClusters.json#L3391).
  - [capacityReservationGroupID](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json#L3547), already exists in previous preview API [2022-07-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/managedClusters.json#L3470).
  - [issuerURL](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json#L5270), already exists in previous preview API [2022-07-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/managedClusters.json#L5074).
  - [blobCSIDriver](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json#L6436), already exists in previous preview API [2022-07-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/managedClusters.json#L6211).
  - [nonResourceURLs](https://github.com/Azure/azure-rest-api-specs/blob/f6249624d2a93d0dd77669f2343f3eb746c99871/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json#L6943), already exists in previous preview API [2022-07-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-07-02-preview/managedClusters.json#L6717).

  Modifications to the above properties will lead to breaking changes on the service side

**Comment by raosuhas** [comment]
>               "$ref": "#/definitions/ListGuardrailsVersionsResponse"

The way this API is defined it will be interpreted as a call to get a collection of guardrailsVersions , which means that this needs o be defined as a collection of ARM resources (Proxy Resources ) rahter than the free form mode you are using here

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json:2923 in f624962. [](commit_id = f6249624d2a93d0dd77669f2343f3eb746c99871, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "description": "The default value is false. Outbound NAT can only be disabled if the cluster outboundType is NAT Gateway and the Windows agent pool does not have node public IP enabled."

consider updating the new boolean values to enum as described here : 

[https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html#common-issues-found-in-review)

Replace boolean/switch properties with better enum
A Boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Even if you still believe [True, False] are the correct values for a property, you should use a string enum with values [True, False] instead of boolean. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [True, False, Unknown].

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json:5997 in f624962. [](commit_id = f6249624d2a93d0dd77669f2343f3eb746c99871, deletion_comment = False)

**Comment by raosuhas** [comment]
>     "GuardrailsProfile": {

Where is definition being used ? Please remove any unused definitions 

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json:7209 in f624962. [](commit_id = f6249624d2a93d0dd77669f2343f3eb746c99871, deletion_comment = False)

**Comment by ShiqianTao** [comment]
Hi @raosuhas . Thanks for your comments.  About the boolean variable ```disableOutboundNat```: As discussed internally, we still want to keep the variable type as boolean, because it's used for disabling a feature on Windows OS, and it won't add additional values in the future. Thank you.

**Comment by matthchr** [comment]
> > ```
> >           "$ref": "#/definitions/ListGuardrailsVersionsResponse"
> > ```
> 
> The way this API is defined it will be interpreted as a call to get a collection of guardrailsVersions , which means that this needs o be defined as a collection of ARM resources (Proxy Resources ) rahter than the free form mode you are using here
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json:2923 in [f624962](https://github.com/Azure/azure-rest-api-specs/commit/f6249624d2a93d0dd77669f2343f3eb746c99871). [](commit_id = [f624962](https://github.com/Azure/azure-rest-api-specs/commit/f6249624d2a93d0dd77669f2343f3eb746c99871), deletion_comment = False)

Presumably an alternative would be to do something like we do for GET `/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/trustedAccessRoles`, which returns a list of `trustedAccessRoles` which are not themselves resources.

So if guardrails versions weren't nested under `ManagedClusters` it would be OK as well?

**Comment by raosuhas** [comment]
> > > ```
> > >           "$ref": "#/definitions/ListGuardrailsVersionsResponse"
> > > ```
> > 
> > 
> > The way this API is defined it will be interpreted as a call to get a collection of guardrailsVersions , which means that this needs o be defined as a collection of ARM resources (Proxy Resources ) rahter than the free form mode you are using here
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-02-preview/managedClusters.json:2923 in [f624962](https://github.com/Azure/azure-rest-api-specs/commit/f6249624d2a93d0dd77669f2343f3eb746c99871). [](commit_id = [f624962](https://github.com/Azure/azure-rest-api-specs/commit/f6249624d2a93d0dd77669f2343f3eb746c99871), deletion_comment = False)
> 
> Presumably an alternative would be to do something like we do for GET `/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/trustedAccessRoles`, which returns a list of `trustedAccessRoles` which are not themselves resources.
> 
> So if guardrails versions weren't nested under `ManagedClusters` it would be OK as well?

That one is incorrect as well since ideally all GET resources in ARM need to follow the ARM schema with the top level ARM properties like id, name and type. That one was probably missed during review.  This would cause issues with clients that make the assumption for these properties. If you want to keep it free form I would suggest converting it to a POST .. i.e "POST .../listguardrailversions"

Just as a side note Even for location based resources like the trustecaccessroles , there is an expectation that it has the type and name property which includes the location value. https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderRegistrationRoutingTypes.html#locationbased

**Comment by matthchr** [comment]
@raosuhas, I've forwarded you a mail where we explicitly asked about exactly this kind of API to the ARM API reviewers alias and were told that, provided the set of data is readonly (GET, no user PUT), the RP has flexibility to define it as "not a resource" and rather a static list of data.

I don't think that solves your critique of it being under ManagedCluster (or does it?). But at least _at the region level_ (like the TrustedAccessRoles API), I believe that pattern is allowed.

**Review by palma21 — APPROVED** [review]

**Pull request merged**
