### PR TITLE
Remove lt rv1 WaitForARMFeedback

### PR DESCRIPTION
**Pull request by bradrich-msft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by bradrich-msft** [comment]
automation sdk check failed.  Seems like infra issue?

2020-04-27T21:41:20.7544233Z 2020-04-27T21:41:20.753Z: [Azure/azure-sdk-for-net]/z/work/azure-sdk-for-net: git add *
2020-04-27T21:41:20.7608946Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]Exit Code: 128
2020-04-27T21:41:20.7618421Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]Error:
2020-04-27T21:41:20.7619659Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]fatal: pathspec '*' did not match any files

**Comment by bradrich-msft** [comment]
> automation sdk check failed. Seems like infra issue?
> 
> 2020-04-27T21:41:20.7544233Z 2020-04-27T21:41:20.753Z: [Azure/azure-sdk-for-net]/z/work/azure-sdk-for-net: git add *
> 2020-04-27T21:41:20.7608946Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]Exit Code: 128
> 2020-04-27T21:41:20.7618421Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]Error:
> 2020-04-27T21:41:20.7619659Z 2020-04-27T21:41:20.760Z: [Azure/azure-sdk-for-net]fatal: pathspec '*' did not match any files

Fails again at this step:
2020-04-28T16:48:56.077Z: [Azure/azure-sdk-for-net][AutoRest]    Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)

**Comment by yungezz** [comment]
why the swagger and samples deleted? this is a stable version, will be breaking changes to both restapi user and sdk user

**Comment by bradrich-msft** [comment]
> why the swagger and samples deleted? this is a stable version, will be breaking changes to both restapi user and sdk user

I was not involved in the much earlier deprecation of the API.  I agree that this API was not deprecated in an appropriate manner, but it is too late to fix that.  The API itself doesn't exist anymore and hasn't for some time.  All calls to it result in failure and because it is showing up in the spec still, it causes ARM export failures.  We need to update the specs/schema by removing this now to prevent all the failed calls coming to this no longer existant API.

**Comment by pixia** [comment]
> why the swagger and samples deleted? this is a stable version, will be breaking changes to both restapi user and sdk user
These APIs are for LTR V1 and has already been replaced by LTR V2 APIs. This deprecation was announced when we release LTR V2 (in April 2018) and we have blocked LTR V1 traffic after GA (in July 2018). There shouldn't be impact to customers to remove it.

**Review by pixia — APPROVED** [review]

**Comment by bradrich-msft** [comment]
@yungezz this PR has been waiting for 3 weeks now.  Can you please approve?

**Review by pilor — APPROVED** [review]
No functional API change in this PR.  API is apparently already gone.  This only has SDK impact.

**Pull request merged**
