### PR TITLE
fix: Unreferenced network/resource-manager/Microsoft.Network/ examples

### PR DESCRIPTION
**Pull request by nschonni**
These get flagged by Avocado. Likely just copied between versions after they got replaced or removed in newer versions

### CODE REVIEW

**Comment by number213** [comment]
Some of those examples are legit and should be added to specs instead of getting removed. I'll take a closer look tomorrow and fix that in `network-march-branch`

**Comment by nschonni** [comment]
@number213 sounds good, if you figure out which should stay, you can flag them here and I'll rebase them out

**Comment by number213** [comment]
@nschonni opened PR with fixes: https://github.com/Azure/azure-rest-api-specs/pull/5675

**Comment by nschonni** [comment]
@number213 found a few extras still unreferenced after rebasing

**Comment by number213** [comment]
@nschonni thanks for noticing, I missed them somehow (and avocado's job was green too)
Opened PR to fix them: https://github.com/Azure/azure-rest-api-specs/pull/5693

**Comment by nschonni** [comment]
@NumberByColors sounds good, i'll close this then

**Pull request closed without merging**
