### PR TITLE
Add 404 responses for HEAD on Azure Batch file properties

### PR DESCRIPTION
**Pull request by Porges**
This was causing AutoRest to generate warnings previously.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Porges__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gpollard). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by matthchr** [comment]
Hold off on merging this please.

**Comment by lmazuel** [comment]
@matthchr So I revert https://github.com/Azure/azure-sdk-for-python/pull/680 ?

**Comment by matthchr** [comment]
@lmazuel Yeah -- this change was made in error.

**Comment by matthchr** [comment]
Actually @lmazuel It would be nice to not actually merge the python stuff until this PR is merged right? Since otherwise changes to this PR could've been made which would be missed for Python right?

**Comment by lmazuel** [comment]
@matthchr This is an AutoPR (same repo, not a fork), it's why the Python SDK received the PR, normally I should receive it only when the PR is merged.
@amarzavery @devigned it was not supposed to be more strict or I missed something?

**Pull request closed without merging**
