### PR TITLE
Move swagger from private repo to public repo

### PR DESCRIPTION
**Pull request by sureleo**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360. The swagger is already checked in in RPSaaSMaster branch in private repo. This is just the effort to copy the [latest version](https://github.com/sureleo/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/azurearcdata/resource-manager) to public repo.
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@sureleo , can you paste the link of original PR in private spec repository? You should use the link there to publish that PR to public repo.

**Comment by sureleo** [comment]
@raych1 Sorry I am not aware. Here is the[ link of swagger in private repo](https://github.com/Azure/azure-rest-api-specs-pr/pull/3945).

I couldn't find the link you mentioned... is it because I am on RPSaaSMaster rather than master branch?

**Comment by sureleo** [comment]
> > @raych1 Sorry I am not aware. Here is the[ link of swagger in private repo](https://github.com/Azure/azure-rest-api-specs-pr/pull/3945).
> > I couldn't find the link you mentioned... is it because I am on RPSaaSMaster rather than master branch?
> 
> Right, rpsaasmaster branch PR doesn't have the link for publish. Above PR only has the change on the readme files. Can you paste related PRs in private repo?

[Here ](https://github.com/Azure/azure-rest-api-specs-pr/pull/3988) is the PR to master branch in Private repo. It is just copy whatever on RPSaaSMaster branch with 2020-12-08-preview and 2021-03-02-preview removed (We are planning to deprecate these api versions).

I still cannot find the publish it to public repo though... Am I missing anything?

**Comment by raych1** [comment]
> > > @raych1 Sorry I am not aware. Here is the[ link of swagger in private repo](https://github.com/Azure/azure-rest-api-specs-pr/pull/3945).
> > > I couldn't find the link you mentioned... is it because I am on RPSaaSMaster rather than master branch?
> > 
> > 
> > Right, rpsaasmaster branch PR doesn't have the link for publish. Above PR only has the change on the readme files. Can you paste related PRs in private repo?
> 
> [Here ](https://github.com/Azure/azure-rest-api-specs-pr/pull/3988) is the PR to master branch in Private repo. This is reflecting all the changes on RPSaaSMaster branch for the latest version (2021-06-01-preview). This PR and private repo PR are just copying whatever on RPSaaSMaster branch with 2020-12-08-preview and 2021-03-02-preview removed (We are planning to deprecate these api versions).
> 
> I still cannot find the publish it to public repo though... Am I missing anything?

Ok, this PR doesn't need ARM review as it just copies all the existed api version from rpsaasmaster branch to public master.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
