### PR TITLE
Onboarding IoTSpaces.

### PR DESCRIPTION
**Pull request by yojagad**
The spec was reviewed and approved on the private branch here (https://github.com/Azure/azure-rest-api-specs-pr/pull/416)

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@yojagad Hello!  Has this new API been reviewed and approved by the ARM team?

**Comment by yojagad** [comment]
@jhendrixMSFT This was approved on a private branch, attaching a link(from description) and screenshot of the same.

https://github.com/Azure/azure-rest-api-specs-pr/pull/416

image

**Comment by jhendrixMSFT** [comment]
@yojagad These folks are not part of ARM.  All new management APIs must be reviewed by ARM and the API review board.  Has this happened?

**Comment by yojagad** [comment]
@jhendrixMSFT Yup, the original PR which was reviewed and approved(in person with the Azure API review board as well) is this. https://github.com/Azure/azure-rest-api-specs-pr/pull/309

We then had to do a namespace change for which we had to submit another PR but then we were told by @ravbhatnagar that it didn't need another round of review from review board.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by yojagad** [comment]
Thank you @jhendrixMSFT !

**Pull request merged**
