### PR TITLE
attestation: fixing the segment `attestationProvider` to be `attestationProviders` which matches the API

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Using the API Version in the Portal (2020-10-01):

## API Version 2020-10-01

Using API Version 2020-10-01 and a valid AttestationProvider with this endpoint returns an error that the `attestationProvider` resource type cannot be found:

```
$ az rest --method get --uri "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-dev/providers/Microsoft.Attestation/attestationProvider/tomdevaccprov/privateEndpointConnections?api-version=2020-10-01"
Not Found({"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Attestation' for api version '2020-10-01'."}})
```

Updating this to `attestationProviders` fixes this (and correctly returns a 404 that there is no PrivateEndpointConnection for this Attestation Provider):

```
$ az rest --method get --uri "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-dev/providers/Microsoft.Attestation/attestationProviders/tomdevaccprov/privateEndpointConnections?api-version=2020-10-01"
Not Found({"error":{"code":"InvalidOperation","message":"PrivateEndpointConnection is not found."}})
```

---

## API Version 2021-06-01-preview

Using API Version 2021-06-01-preview and a valid AttestationProvider with this endpoint returns an error that the `attestationProvider` resource type cannot be found:

```
$ az rest --method get --uri "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-dev/providers/Microsoft.Attestation/attestationProvider/tomdevaccprov/privateEndpointConnections?api-version=2021-06-01-preview"
Not Found({"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Attestation' for api version '2021-06-01-preview'."}})
```

Updating this to `attestationProviders` fixes this (and correctly returns a 404 that there is no PrivateEndpointConnection for this Attestation Provider):

```
$ az rest --method get --uri "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-dev/providers/Microsoft.Attestation/attestationProviders/tomdevaccprov/privateEndpointConnections?api-version=2021-06-01-preview"
Not Found({"error":{"code":"InvalidOperation","message":"PrivateEndpointConnection is not found."}})
```

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@msyyc as above:

> Per [the original description](https://github.com/Azure/azure-rest-api-specs/pull/16355#issue-755866848) whilst this is a breaking change, the Swagger currently doesn't work - as such this isn't a breaking change as these endpoints are documented incorrectly

So this is a false positive

**Comment by msyyc** [comment]
Hi @tombuildsstuff Please follow the [bot advice](https://github.com/Azure/azure-rest-api-specs/pull/16355#issuecomment-940715012) to ask for approval from @JeffreyRichter

**Comment by tombuildsstuff** [comment]
@msyyc unfortunately I can't do that:

Screenshot 2021-11-09 at 06 02 58

@JeffreyRichter any chance you could take a look at this one? The endpoint defined in the Swagger is incorrect/doesn't exist in ARM (see [the payloads in the description](https://github.com/Azure/azure-rest-api-specs/pull/16355#issue-1023429766) above) - so this PR isn't a breaking change insofar as the endpoints defined in the Swagger have never worked

**Comment by JeffreyRichter** [comment]
Since the swagger never worked correctly, I approved this "breaking change".

**Review by msyyc — APPROVED** [review]

**Pull request merged**
