### PR TITLE
Fix python.md for loganalytics

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Review by kairu-ms — APPROVED** [review]

**Comment by 00Kai0** [comment]
Fix required parameters in python track2 sdk: https://github.com/Azure/azure-rest-api-specs/pull/12385/files

Now it's available:
```
    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'table_names': {'required': True},
        'resource_id': {'required': True},
        'type_properties_destination_type': {'readonly': True},
    }
```

**Comment by kairu-ms** [comment]
Hi @JeffreyRichter, Please review this breaking change. Thanks.

**Comment by JeffreyRichter** [comment]
Can you fix the breaking changes?
https://github.com/Azure/azure-rest-api-specs/pull/12664/checks

**Comment by 00Kai0** [comment]
Hi @JeffreyRichter, these breaking changes are inevitable. The [previous swagger changes](https://github.com/Azure/azure-rest-api-specs/pull/12385/files) failed to take effect in Python SDK. I am trying to fix it.

New changelog in python SDK has been right:
```
cmdout	[Changelog] **Breaking changes**
cmdout	[Changelog]   - Parameter table_names of model DataExport is now required
cmdout	[Changelog]   - Parameter resource_id of model DataExport is now required
```

**Comment by hohershk** [comment]
HI @00Kai0 
Why its a breaking change? 
I had a task for it.
Can you please remove the label? and approve this PR?

**Comment by 00Kai0** [comment]
Hi @hohershk , I am not sure why its a breaking change?
But it really fix the python sdk changelog.
The purpose of doing this is to make the generated SDK achieve the result you want.
And I don't have the permission to remove tags and merge them.
Thx :)

**Comment by kairu-ms** [comment]
@hohershk @00Kai0, There are breaking changes for swagger. If there's mismatch with service api, you should provide detail information for BreakingChange Review. Thanks.

**Pull request closed without merging**
