### PR TITLE
Update fields description for VectorQuery

### PR DESCRIPTION
**Pull request by pamelafox**
This PR improves the reference for the VectorizedQuery fields parameter to be clearer, especially about how to specify multiple fields.

I found three other searchindex.json documents with the same description, but I'm assuming we only need to update the most recent one? Otherwise I can update those.

cc @mattgotteiner

### CODE REVIEW

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Review by mattgotteiner — APPROVED** [review]
Thanks @pamelafox

**Comment by pamelafox** [comment]
Still relevant. Not sure if I'm supposed to do anything.

**Comment by mattgotteiner** [comment]
@alzimmermsft Can you please take a look at this?

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
