### PR TITLE
service Fabric 7.1

### PR DESCRIPTION
**Pull request by jeffj6123**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by samedder — APPROVED** [review]

**Comment by jeffj6123** [comment]
@lmazuel am I missing anything else? I checked the open api hub and it says its at review.

**Comment by lmazuel** [comment]
@jeffj6123 can you update line 28, the default API tag to 7.1 so automation can create the corresponding language PR?
Thanks!

**Comment by lmazuel** [comment]
@jeffj6123 I can't write in the PR review, the file is too big. A few comments:
- "entrypoint" has been renamed "entryPoint" in ApplicationMetricDescription. I want to confirm you actually change the JSON format and it's not case-sensitive, otherwise you'll break SDKs (they are mostly case-sensitive, only C# is not). Also, if you want to make it less breaking for customers you can add "x-ms-client-name: entrypoint", that will keep the old SDK name while updating the JSON wire name

Otherwise, LGTM, let me know your thought on entrypoint

**Comment by jeffj6123** [comment]
> @jeffj6123 I can't write in the PR review, the file is too big. A few comments:
> 
> * "entrypoint" has been renamed "entryPoint" in ApplicationMetricDescription. I want to confirm you actually change the JSON format, otherwise you'll break SDKs (they are mostly case-sensitive, only C# is not). Also, if you want to make it less breaking for customers you can add "x-ms-client-name: entrypoint", that will keep the old SDK name while updating the JSON wire name
> 
> Otherwise, LGTM, let me know your thought on entrypoint

Hey,
I can confirm this is actually a correction. It appears that previously this was the wrong casing name for that property.

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
