### PR TITLE
Adding API version 2019-01-01-preview for Microsoft.DevSpaces

### PR DESCRIPTION
**Pull request by sanar-microsoft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@sanar-microsoft could you make 2 commits? The first one is a just copy of previous version (2018-..). and the second one should contain changes between 2018 and 2019 API version. So we can review changes.

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
two commits are required for new API version.

**Comment by sanar-microsoft** [comment]
Done. There was another change that I made in this PR. There were a few example files in the existing repo that were duplicates, I've also removed them.

**Review by sergey-shandar — APPROVED** [review]

**Review by KrisBash — APPROVED** [review]
LGTM thanks

**Comment by sanar-microsoft** [comment]
Thank you :)

**Pull request merged**
