### PR TITLE
[containerservice-dev] Revert "Containerservice 2022 09 02 preview fleet (#20939)"

### PR DESCRIPTION
**Pull request by serbrech**
This reverts fleet api commit 7f9780381fb7d1140cd2a3ff6d3d2dc13d59f900.

### CODE REVIEW

**Review by FumingZhang — APPROVED** [review]

**Review by FumingZhang — APPROVED** [review]

**Comment by serbrech** [comment]
@bot agree

**Comment by serbrech** [comment]
@ruowan any fix for the CLA approval?
the pipeline show the license/cla step as approved...

**Review by ruowan — APPROVED** [review]

**Comment by ruowan** [comment]
@serbrech Recently there are some changes on cla check, so your PR is block. We have applied new setting to fix this issue. For this PR, I have asked admin to force merge.

**Pull request merged**
