### PR TITLE
DataBox : Swagger and example changes for next version of client DLL

### PR DESCRIPTION
**Pull request by saran94**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Comment by anuchandy** [comment]
Please fix example validation errors https://travis-ci.org/Azure/azure-rest-api-specs/jobs/450191674

**Comment by anuchandy** [comment]
@sarangan12 it looks like java build failed with following error:

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile
```

We had some discussion some time back about similar error, where bundler is needed to generate ruby SDK. Can you take a look?

**Comment by anuchandy** [comment]
There are validation errors, but seems an issue in the validator. Opened an issue here https://github.com/Azure/oav/issues/349#issuecomment-436391935

**Comment by anuchandy** [comment]
Requesting review from ARM, given this PR introduces two new model and couple of properties in existing model.

**Comment by anuchandy** [comment]
@saran94, please update the readme as suggested

**Comment by ravbhatnagar** [comment]
Signing off from ARM side.

**Comment by saran94** [comment]
@anuchandy HI, Updated Readme.

**Comment by anuchandy** [comment]
@saran94 looks good. Model validation failure is a known issue as i indicated in the previous comment (we have an issue tracking it).

@sarangan12, @veronicagg ruby code gen is failing, could you please take a look?

**Comment by veronicagg** [comment]
@anuchandy thx, Ruby issue looks to be https://github.com/Azure/azure-sdk-for-ruby/issues/1648, so please don't block this PR on it, I need to follow up with @sarangan12 on the status of it.

**Comment by anuchandy** [comment]
@veronicagg  thank you.

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
