### PR TITLE
Iot sites and sensor zones

### PR DESCRIPTION
**Pull request by galmoshe**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [x] Removing API(s) in stable version
- [x] Removing properties in stable version
- [x] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [x] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by erich-wang** [comment]
@galmoshe , could you please check the CI errors?

**Comment by galmoshe** [comment]
> @galmoshe , could you please check the CI errors?

@erich-wang Fixed errors, please ignore breaking change alert as this is a preview API version.

**Comment by galmoshe** [comment]
@erich-wang Any news?

**Comment by chiragg4u** [comment]
Please go through the ARM API Review Checklist. These steps are required before review can be continued.

**Comment by chiragg4u** [comment]
As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by galmoshe** [comment]
@chiragg4u As I commented before, there is a breaking change since we are in preview, The changes are backward compatible. Please review and approve.

**Comment by galmoshe** [comment]
@chiragg4u The link you provided is broken (PR review process.), can you explain "Updating API in stable version with Breaking Change Validation errors"? Couldnt find documentation regarding it.

**Comment by galmoshe** [comment]
@chiragg4u any news?

**Review by JeffreyRichter — APPROVED** [review]

**Comment by galmoshe** [comment]
@chiragg4u PR is approved, can you please complete?

**Comment by erich-wang** [comment]
@galmoshe, could you please follow:
If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

**Review by j5lim — APPROVED** [review]

**Comment by galmoshe** [comment]
@erich-wang approved by ARM, can you please approve and complete?

**Pull request merged**
