### PR TITLE
Fixes issues with CheckSkuAvailability operation

### PR DESCRIPTION
**Pull request by felixwa**
1. Changes type of skuName property from Sku to SkuName.
2. Marks some fields as required.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/1224)

### CODE REVIEW

**Comment by jianghaolu** [comment]
error: Found errors in validating the response with statusCode "200" for example in spec for operation "CognitiveServicesAccounts_GetProperties".:
 
```
{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for example in spec for operation "CognitiveServicesAccounts_GetProperties".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'object', 'string' ],
            message: 'Expected type object but found type string',
            path: [],
            description: 'Cognitive Services Account is an Azure resource representing the provisioned account, its type, location and SKU.' } ],
       message: 'Invalid body: Expected type object but found type string',
       path: [] } ] }
```

**Comment by jianghaolu** [comment]
error: Found errors in validating the response with statusCode "200" for x-ms-example "Check SKU Availability" in operation "CheckSkuAvailability_List".:
 ```
{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Check SKU Availability" in operation "CheckSkuAvailability_List".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'string', 'null' ],
            message: 'Expected type string but found type null',
            path: [ 'value', '0', 'message' ],
            description: 'Additional error message.' },
          { code: 'INVALID_TYPE',
            params: [ 'string', 'null' ],
            message: 'Expected type string but found type null',
            path: [ 'value', '0', 'reason' ],
            description: 'Reason why the SKU is not available.' } ],
       message: 'Invalid body: Value failed JSON Schema validation',
       path: [] } ] }
```

**Review by jianghaolu — CHANGES_REQUESTED** [review]
Please fix the examples after the payload definition for Sku is changed.

**Comment by felixwa** [comment]
@jianghaolu , 
For issue #1, I cannot get it when run "node cli validate-example". What tool did you use?
For issue #2, it is a known issue, the field can be a string or null. I have consulted this issue with reviewer last time and she said this is a known issue. PR: #1090 Issue: #798

**Comment by jianghaolu** [comment]
Seems like both are false alarms. Otherwise looks good to me.

**Review by jianghaolu — APPROVED** [review]

**Pull request merged**
