### PR TITLE
Updated description for the device count APIs. No breaking changes

### PR DESCRIPTION
**Pull request by jlian**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by erich-wang — APPROVED** [review]

**Comment by erich-wang** [comment]
@jlian, the merge is blocked by [model validation errors](https://dev.azure.com/azure-sdk/public/_build/results?buildId=215321&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1) which are not related to your change. The current process requires you or your team to fix model validation error before merging this PR unless you have urgent need for merging this PR.

**Review by erich-wang — CHANGES_REQUESTED** [review]
@jlian, the merge is blocked by [model validation errors](https://dev.azure.com/azure-sdk/public/_build/results?buildId=215321&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1) which are not related to your change. The current process requires you or your team to fix model validation error before merging this PR unless you have urgent need for merging this PR.

**Comment by erich-wang** [comment]
@jlian, could you address the comment above?

**Comment by jlian** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=215321&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

Says build not found

I'm not sure if we would have bandwidth to fix the errors especially since this should be just simple string update

**Review by erich-wang — APPROVED** [review]

**Comment by lirenhe** [comment]
@jlian , I found the model validation error may not related to this PR, but this is definitely an issue in the spec. Are you going to fix this problem?
If not, we could force merge this PR.

**Comment by jlian** [comment]
Honestly it's unlikely that we would. Probably just going to submit the fix along with the new api version when that comes around

**Pull request closed without merging**
