### PR TITLE
Fixed partitionIds type in EventHub

### LINKED ISSUE #413: Bug in the Event Hubs SDK
Thanks for adding the EventHub SDK recently.

I've been working on adding support for them into Terraform - and I believe I've found an SDK bug with one of the types is defined incorrectly. I'm getting the following error - (I've masked the Subscription ID for obvious reasons):

```
* azurerm_eventhub.test: eventhub.EventHubsClient#CreateOrUpdate: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type int32' JSON = '{"id":"/subscriptions/XXXXXXXXXXXXXXXXXXXX/resourceGroups/tomacctestrg/providers/Microsoft.EventHub/namespaces/th-eh-namespace/eventhubs/th-eh-test","name":"th-eh-test","type":"Microsoft.EventHub/EventHubs","location":"West US","tags":null,"properties":{"messageRetentionInDays":1,"status":"Active","createdAt":"2016-10-09T07:13:47.85","updatedAt":"2016-10-09T07:13:48.13","partitionCount":2,"partitionIds":["0","1"]}}'
```

I believe this error to be with the Partition ID's - which is returned as an array of strings and not Int's. For context the object is:

```
type Properties struct {
	CreatedAt              *date.Time   `json:"createdAt,omitempty"`
	MessageRetentionInDays *int64       `json:"messageRetentionInDays,omitempty"`
	PartitionCount         *int64       `json:"partitionCount,omitempty"`
	PartitionIds           *[]int32     `json:"partitionIds,omitempty"`
	Status                 EntityStatus `json:"status,omitempty"`
	UpdatedAt              *date.Time   `json:"updatedAt,omitempty"`
}
```

From what I can see - to route to fixing this is either:
 - Updating the SDK Definition to return an array of strings
 - Start returning integers from the API instead

As this SDK is auto-generated - I guess there'd be no point sending a PR to fix the type in this repo directly?

### PR DESCRIPTION
**Pull request by mcardosos**
Based on documentation [here](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.eventhubdescription.partitionids.aspx).
This should fix [this bug](https://github.com/Azure/azure-sdk-for-go/issues/413) in the Go SDK.
@sazeesha @jhendrixMSFT

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 
### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).
### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

---

This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/613)

### CODE REVIEW

**Comment by sazeesha** [comment]
@mcardosos this change looks good.

**Comment by mcardosos** [comment]
@amarzavery Can we merge this?

**Comment by amarzavery** [comment]
@lmazuel 
The CI is failing for python. Can you take a look ?
```
mono /tmp/tmp9oxm94qm/autorest/tools/AutoRest.exe -i /git-restapi/arm-eventhub/2015-08-01/swagger/EventHub.json -o /tmp/tmp9oxm94qm/EventHub.json -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Namespace azure.mgmt.eventhub -PackageVersion 0.1.0 -ft 2
ERROR:__main__:Command '['mono', '/tmp/tmp9oxm94qm/autorest/tools/AutoRest.exe', '-i', '/git-restapi/arm-eventhub/2015-08-01/swagger/EventHub.json', '-o', '/tmp/tmp9oxm94qm/EventHub.json', '-AddCredentials', 'True', '-CodeGenerator', 'Azure.Python', '-Header', 'MICROSOFT_MIT_NO_VERSION', '-Namespace', 'azure.mgmt.eventhub', '-PackageVersion', '0.1.0', '-ft', '2']' returned non-zero exit status 1
ERROR:__main__:Code generation failed.
AutoRest.exe -i /git-restapi/arm-eventhub/2015-08-01/swagger/EventHub.json -o /tmp/tmp9oxm94qm/EventHub.json -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Namespace azure.mgmt.eventhub -PackageVersion 0.1.0 -ft 2
FATAL: Error loading Azure.Python assembly: Could not load file or assembly 'AutoRest.Python.Azure.dll' or one of its dependencies

Traceback (most recent call last):
  File "/SwaggerToSdk.py", line 631, in <module>
    main()
  File "/SwaggerToSdk.py", line 628, in main
    args.autorest_dir)
  File "/SwaggerToSdk.py", line 544, in build_libraries
    autorest_exe_path, global_conf, local_conf)
  File "/SwaggerToSdk.py", line 162, in generate_code
    cwd=str(swagger_path))
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['mono', '/tmp/tmp9oxm94qm/autorest/tools/AutoRest.exe', '-i', '/git-restapi/arm-eventhub/2015-08-01/swagger/EventHub.json', '-o', '/tmp/tmp9oxm94qm/EventHub.json', '-AddCredentials', 'True', '-CodeGenerator', 'Azure.Python', '-Header', 'MICROSOFT_MIT_NO_VERSION', '-Namespace', 'azure.mgmt.eventhub', '-PackageVersion', '0.1.0', '-ft', '2']' returned non-zero exit status 1
```

**Comment by mcardosos** [comment]
I think @fearthecowboy knows what's happening

**Pull request merged**
