### PR TITLE
[DataFactory] validation activity

### PR DESCRIPTION
**Pull request by cesher**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/-1 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/-1/commits/68b520e5de7483dbe90fa8ca3673fcf63abb2ce9

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/-1 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/-1/commits/68b520e5de7483dbe90fa8ca3673fcf63abb2ce9

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by shahabhijeet** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5607 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5607/commits/dd80df1392aaff91701348abdb677b31edd4a7b3

**Comment by hvermis** [comment]
@sarangan12, can you please review this PR? We need it in our next release.

**Comment by sarangan12** [comment]
@cesher @hvermis The PR Looks fine to me. But, where exactly this new Model "ValidationActivity" being used? It is not being used anywhere in the swagger file. So, what is the use of this model?

**Review by sarangan12 — CHANGES_REQUESTED** [review]
@cesher @hvermis The PR Looks fine to me. But, where exactly this new Model "ValidationActivity" being used? It is not being used anywhere in the swagger file. So, what is the use of this model?

**Comment by hvermis** [comment]
@sarangan12 This type is derived from Activity type, which is used in Pipeline. 
Here's the property in PIpelines that holds all activities:
https://github.com/Azure/azure-rest-api-specs/blob/22e4440bc8d496f16dfa56d7074bb0f1d70ecaa5/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L17

**Comment by hvermis** [comment]
@sarangan12 Can you please merge this PR? We are trying to release our SDK today and this is needed.

**Review by sarangan12 — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
