### PR TITLE
Use new AutoRest CLI in order to leverage correct source locations

### PR DESCRIPTION
**Pull request by olydis**
Short-term fix to CI (as long as there are no config files)

### CODE REVIEW

**Comment by olydis** [comment]
whoops, accidentally modified assignee...

**Comment by olydis** [comment]
@veronicagg This is ready from my side! The single-line change relevant for CI is in `test/linter.js`, the other (larger) part is updating the tool we use to generate reports for the entire repo.

**Review by veronicagg — APPROVED** [review]
Change looks good. Per our conversation, let's merge it after you get the Error/Exception that's being thrown in the console fixed, so we don't confuse people.

**Comment by olydis** [comment]
Thanks @veronicagg! I've restarted CI, the log (https://api.travis-ci.org/jobs/223752226/log.txt?deansi=true) is free of `ERROR`s and stack traces. Merging! :-)

**Pull request merged**
