### PR TITLE
Customvision v2.2

### PR DESCRIPTION
**Pull request by areddish**
Updates for Custom Vision version 2.2

### CODE REVIEW

**Review by yangyuan — APPROVED** [review]

**Comment by annatisch** [comment]
Adding @ravbhatnagar to review new API version.

**Review by KrisBash — APPROVED** [review]
Signing off from ARM

**Comment by annatisch** [comment]
Hi @areddish - Just making sure that you're aware that this PR includes major breaking changes that will result in major version bumps for published SDKs - is this your intention?

**Review by annatisch — APPROVED** [review]
Thanks @areddish - the changes generally look good, although this spec is missing lots of documentation. I've left comments by some of them but descriptions are missing throughout.

**Comment by areddish** [comment]
@annatisch Yes, this is intended to be a breaking change that will result in a major version change.

I'll look into adding more descriptions

**Review by annatisch — APPROVED** [review]

**Pull request merged**
