### PR TITLE
Better representation for userassignedidentity

### PR DESCRIPTION
**Pull request by solankisamir**
### Latest improvements:
Better representation of UserAssignedIdentity object for Clients

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by solankisamir** [comment]
@njuCZ we have not released any clients using this api-version, and this is also a preview version.
Can you take a look, so that we are unblocked on client development?

**Review by ravbhatnagar — APPROVED** [review]
Signing off from ARM side

**Comment by solankisamir** [comment]
@njuCZ can you merge this PR

**Comment by akning-ms** [comment]
According to above explain for still in preview version and no client use it. so ignore breaking change fail. force merge it

**Comment by akning-ms** [comment]
python sdk fail. rerun pipeline

**Pull request merged**
