### PR TITLE
Update WebApps swagger: correct host key create/update requests

### LINKED ISSUE #14557: BadRequest when Create Or Update Host Secret (aka Api Key) for Function App
### Bug Report

- What happened?
I think the best way to describe the bug is by pointing towards a blog which explains how to circumvent this bug: https://tomaszoledzki.eu/2020/07/24/badrequest-error-function-app-create-or-update-host-secret/.

Using the Go SDK I want to create/update a Host Secret for a Function App:
```
PUT /subscriptions/<subscriptionIdRemoved>/resourceGroups/acctestRG-210526205240104071/providers/Microsoft.Web/sites/acctest-210526205240104071-func/host/default/functionKeys/default?api-version=2020-06-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.16.3 (amd64-darwin) go-autorest/v14.2.1 Azure-SDK-For-Go/v54.3.0 web/2020-06-01 HashiCorp Terraform/0.15.4 (+https://www.terraform.io) Terraform Plugin SDK/1.17.2 terraform-provider-azurerm/acc pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 18
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: bb865f8a-0e66-6eb4-14dd-43f52886532b
Accept-Encoding: gzip

{"name": "default", "value":"123234"}
```

The response is like this:

```json
{
    "Code": "BadRequest",
    "Message": "Properties object is not present in the request body.",
    "Target": null,
    "Details": [
        {
            "Message": "Properties object is not present in the request body."
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "51006",
                "MessageTemplate": "{0} object is not present in the request body.",
                "Parameters": [
                    "Properties"
                ],
                "Code": "BadRequest",
                "Message": "Properties object is not present in the request body."
            }
        }
    ],
    "Innererror": null
}
```
- What did you expect or want to happen?
I expect the Go SDK/REST API to handle this and the specification to be right, but apparently it needs a body with a `properties` wrapper, like:

```json
{
    "properties": {
        "name": "default",
        "value": "123234"
    }
}
```
- How can we reproduce it?
Create a function app and use [this](https://tomaszoledzki.eu/2020/07/25/function-app-create-or-update-host-secret/) or similar without the `properties` wrapper
- Anything we should know about your environment.
I'm trying to add a HostSecret resource for the Azure Terraform Provider

### PR DESCRIPTION
**Pull request by allenhumphreys**
fixes #14557 

This seems to be incorrect in every single WebApps API version. I have no idea if changes are accepted from the public. I'd like to get this fixed so the Go SDK can be used to create/update host keys.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by allenhumphreys** [comment]
I know this is popping up as a breaking change, but it's really just aligning the swagger with the implementation. The generated methods, at least in the Go SDK, are unusable in their current form. The API throws a 400 if the `properties` field is missing. While `name` can remain at the top level, the `value` parameter is only accepted in the properties field when one wants to set the value of the secret.

**Comment by allenhumphreys** [comment]
@msftbot i cannot remove labels

**Comment by allenhumphreys** [comment]
Are non-MS contributor changes not accepted?

**Comment by allenhumphreys** [comment]
It’s unfortunate no one looks at my issues

**Comment by allenhumphreys** [comment]
Someday, somewhere, someone might look at this

**Comment by allenhumphreys** [comment]
Hi

**Comment by alexwieseawe** [comment]
@allenhumphreys wow - hoping we can get this merged, one day.

**Comment by alexwieseawe** [comment]
@ArcturusZhang could you please take a look at this one? It's not a breaking change it's actually a fixing change

**Comment by naveedaz** [comment]
@mathewc Can you please validate this change?

**Comment by mathewc** [comment]
> @mathewc Can you please validate this change?

These changes don't look right. They end up creating the following definition for KeyInfo:

```javascript
"KeyInfo": {
      "description": "Function key info.",
      "type": "object",
      "required": [
        "properties"
       ],
      "properties": {
        "name": {
          "description": "Key name",
          "type": "string"
        },
        "properties": {
          "description": "Key properties",
          "type": "object",
          "properties": {
            "value": {
              "description": "Key value",
              "type": "string"
            }
          }
        }
      }
    }
```

Currently you can PUT the following payload format to create a key, e.g.:

***PUT /subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Web/sites/mysite/host/default/systemkeys/testkey?api-version=2021-03-01***

```javascript
{
  "properties": {
    "name":"testkey",
    "value":"abc123"
  }
}
```

So the APIs take a key payload with properties for name and value. And that's what the existing KeyInfo definition declares [here](https://github.com/Azure/azure-rest-api-specs/blob/ac0b1b1d2f6b07112a01853fd36f8a5b84b91a38/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/WebApps.json#L23308):

```javascript
"KeyInfo": {
      "description": "Function key info.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Key name",
          "type": "string"
        },
        "value": {
          "description": "Key value",
          "type": "string"
        }
      }
    }
```

**Comment by allenhumphreys** [comment]
@mathewc Thanks for looking at this. I think there might be some confusion we'll need to clear up and get to the bottom of.

The existing KeyInfo declaration is meant to be the request body of `PUT /subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Web/sites/mysite/host/default/systemkeys/testkey?api-version=2021-03-01`.

However, the existing OpenAPI definition describes a model that looks like this:

```json
{
    "name": "<keyname>", 
    "value":"<keyvalue>"
}
```

```
"KeyInfo": {
      "description": "Function key info.",
      "type": "object",
      "properties": { <~~~~ The properties of the object KeyInfo
        "name": {                <~~~ are `name`
          "description": "Key name",
          "type": "string"
        },
        "value": {                 <~~~ and `value`
          "description": "Key value",
          "type": "string"
        }
      }
    }
```
The above declaration says "An object, KeyInfo, has 2 properties, "name" and "value".

The API actually expects "Any object, KeyInfo, with 1 property, "properties"; where the property "properties" has 2 properties, "name" and "value".

```
"KeyInfo": {
       "description": "Function key info.",
       "type": "object",
       "required": [
         "properties"
        ],
       "properties": {                                    <~~~~ The properties of the object KeyInfo
         "name": {                                                   <~~~~~ are `name`
           "description": "Key name",
           "type": "string"
         },
         "properties": {.                                 <~~~~~ and an object property `properties` 
           "description": "Key properties",
           "type": "object",
           "properties": {
             "value": {                                             <~~~~ with a property `value`
               "description": "Key value",
               "type": "string"
             }
           }
         }
```

This is the change I made. And I think perhaps the confusion came in with the OpenAPI schema using "properties" in the way it does.

Ultimately, the GoSDK generates a body like, which matches the existing spec for KeyInfo:

```json
{
    "name": "<keyname>", 
    "value":"<keyvalue>"
}
```

which is wrong and leads to the generated Go SDK being **_unable to call this API_**.

Additional info from my investigation:

Using the Azure CLI, I can make this API call using `az functionapp keys set --subscription <sub> --name "app-name" --resource-group <rg> --key-type functionKeys --key-name TestTest --key-value "Value" --debug` and I can see the body looks like this:

```
{"properties": {"name": "TestTest", "value": "Value"}}
```

Now, the Open API spec I've suggested doesn't match the body generated by the Azure CLI. However, when formulating my change I actually probed the API a little. I found that `properties` is required, and `name` can appear in either the top level object or in the `properties` property. As I don't have access to the implementation, I can't really authoritatively say what is absolutely right. I can say for sure that the existing OpenAPI definition for KeyInfo is wrong.

Hopefully this information helps!

**Comment by mathewc** [comment]
Thanks for the clarification @allenhumphreys. Yes, I see what you mean now. The request body for these APIs should indeed follow an ARM resource model schema, with a "properties" member containing the key name/value properties. The problem I see with making a direct change to the spec as in this PR is that it doesn't change it at the source resource definition (our internal codebase from which we generate this swagger). So next time we auto-gen swagger and update in this repo, your changes would get overridden.

Instead, we should make the required change at the the source, so the correct swagger is generated by our tools.

**Comment by allenhumphreys** [comment]
@mathewc That makes perfect sense! I wasn't sure which direction the generation went, so I opened a PR to start a conversation hoping to get it fixed. Is there anything else I should do to help get it prioritized or picked up internally?

**Comment by mathewc** [comment]
@allenhumphreys - no there isn't anything else you need to do. You opened the issue and created a draft PR which helped everyone understand the issue. What remains is for our control plane team to fix the issue on our side, and the swagger updates would then be part of our next scheduled update.

Likely this PR should be closed at this point, and discussion going forward can happen on https://github.com/Azure/azure-rest-api-specs/issues/14557 which links here and retains all the context.

**Comment by allenhumphreys** [comment]
Thank you so much @mathewc ! I look forward to having this fixed and being able to add some key management to terraform azurerm provider in the future.!

**Comment by mathewc** [comment]
PR for swagger update is in progress on our side in our internal service repo. Will update here when progress is made.

**Comment by allenhumphreys** [comment]
I'm very thankful for that status update @matthewc ❤️

**Comment by JDECOMBE** [comment]
Hi, it seems that the changes made here haven't been propagated to the .NET SDK which still creates a body `{ "name": "<secret-name>", "value": "<secret-value>"}`.
Do I need to do anything to get it fixed (PR, specific issue, etc.) ?

**Pull request closed without merging**
