### PR TITLE
Template Specs: Dropping "Model" suffix from TemplateSpec and TemplateSpecVersion

### PR DESCRIPTION
**Pull request by stuartko**
No functionality changes... simply drops the "Model" suffix from the definitions of two existing models. Results in cleaner/more consistent SDK.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by stuartko** [comment]
FYI: The breaking change failures (model renames) are of course expected. This service is not yet released, so we are not breaking any customers.

**Comment by raych1** [comment]
Hi @stuartko , per [Retirement of Preview guidance](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsazure%2FAzureWiki%2F_wiki%2Fwikis%2FAzureWiki.wiki%2F37683%2FRetirement-of-Previews&data=02%7C01%7Cyiqiu%40microsoft.com%7C4f7e343d95044422d96308d81cde3e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637291088141691313&sdata=POFzC9U0r2ju0p0ctz0lIOQvpNxpLvUcxTJjhR5Fbd4%3D&reserved=0), products in Preview for over one year need to move to GA or retire; require CVP exemption after 1 year in preview.

**Comment by stuartko** [comment]
@raych1 : Template Specs has not entered preview (we plan to enter private preview this month), so we are not exceeding any review periods. It's currently a feature/service in development.

**Comment by raych1** [comment]
@stuartko , the api version says `2019-06-01-preview` which is a year ago. Can you have a new preview api version for template spec?

**Comment by stuartko** [comment]
@raych1 : For our initial private preview we'll use our api version we created when Template Specs was initially proposed/reviewed. Updating the API version to something more recent would be additional overhead for a superficial change. @majastrz : Can you confirm from ARM?

**Comment by majastrz** [comment]
I think this is an edge case that is not covered by that rule. Yes, the API is over a year old, but it never even entered private preview, no customers have ever been onboarded and no SDKs have been published (the feature got held up in super long discussions). I think the confusing part here is that the swagger was made public even though the feature is actually hidden behind feature flags. It should have been kept private.

I think the end state that we want here is the following:
1. 2020-06-01-preview version swagger with the changes from this PR
2. Removal of 2019-06-01-preview

Submitting the PR for number 1 will trigger breaking change detection even though it is not actually a breaking change. Which is why I think this PR should be approved. (We don't want "Model" suffixes in the swagger.) This will then unblock step 1 and then step 2 (which will also not be a breaking change because the API is not being used). Once that's the done we will be in the end state that everyone wants.

---
In reply to: [652729923](https://github.com/Azure/azure-rest-api-specs/pull/9998#issuecomment-652729923) [](ancestors = 652729923)

**Review by majastrz — APPROVED** [review]
Signed off from ARM side. Please see my comment about the phasing to get to the end state.

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
@akning-ms , the features of `Template Specs` are not exposed to public yet so this is not a real breaking change. Please have a look at the plan Marcin provided which will have a new preview api version soon. Please help force merge this PR if there's no concern.

**Pull request merged**
