### PR TITLE
Compute GalleryRP 2024-03-03 version 

### PR DESCRIPTION
**Pull request by grizzlytheodore**
ARM team, please review this PR. This version includes several features:
https://github.com/Azure/azure-rest-api-specs/pull/30504 - new operations, suppression approved, ARM review/approved
https://github.com/Azure/azure-rest-api-specs/pull/30505 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30536 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30558 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30658 - new property
https://github.com/Azure/azure-rest-api-specs/pull/31310 - minor change to error in PR above
https://github.com/Azure/azure-rest-api-specs/pull/30842 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30855 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30885 - new property
https://github.com/Azure/azure-rest-api-specs/pull/31094 - new operation
https://github.com/Azure/azure-rest-api-specs/pull/31430 - **breaking change**

Breaking change justification:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2023-07-03/communityGallery.json#L298-L308
"CommunityGalleryDisclaimer" should be "type: object" instead of "string".

In SDKs, it is automatically flattened, and the payloads send out 'string' in the payload in place of "CommunityGalleryDisclaimer"
Example: https://github.com/Azure/azure-sdk-for-net/blob/f5a45365f5560f5c6b1a542f740bd2e8ccaae584/sdk/compute/Azure.ResourceManager.Compute/src/Generated/CommunityGalleryImageData.cs#L97

I've checked with feature owners and the backend also is just a string for disclaimer, instead of nested object.
This change is to reflect the backend correctly, and fix the error made in Swagger definition

The REST API payload already expects and receives "string" for disclaimer, so there is no change in any customer experien e 

# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
unable to resolve the LintDiff issue. I am unable to identify where the error is in the change. Will you help?

**Comment by grizzlytheodore** [comment]
ARM team, please review this PR. This version includes several features: 
https://github.com/Azure/azure-rest-api-specs/pull/30504 - new operations, suppression approved, ARM review/approved 
https://github.com/Azure/azure-rest-api-specs/pull/30505 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30536 - new property 
https://github.com/Azure/azure-rest-api-specs/pull/30558 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30658 - new property
https://github.com/Azure/azure-rest-api-specs/pull/31310 - minor change to error in PR above 
https://github.com/Azure/azure-rest-api-specs/pull/30842 - new property 
https://github.com/Azure/azure-rest-api-specs/pull/30855 - new property
https://github.com/Azure/azure-rest-api-specs/pull/30885 - new property 
https://github.com/Azure/azure-rest-api-specs/pull/31094 - new operation

**Comment by razvanbadea-msft** [comment]
>             "$ref": "../../../common-types/v1/common.json#/parameters/ApiVersionParameter"

why is this not defined as a global parameter?

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:1733 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "resourceArmId": {

you can add the arm-id format

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3802 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "softDeletedArtifactType": {

can this have any string? or it can be used an enum here?


---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3806 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>           "description": "The timestamp for when the resource is soft-deleted."

you should specify the format

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3812 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "status": {

what are the possible values for this property?


---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4177 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>           "description": "This property specifies the name of the platformAttributes. It could be either source_image_publisher or source_image_offer or source_image_sku or source_image_version"

from the description it can be converted to an enum

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4198 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "executedValidations": {

you should add a x-ms-identifiers also for this array

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4114 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by grizzlytheodore** [comment]
> > ```
> >         "$ref": "../../../common-types/v1/common.json#/parameters/ApiVersionParameter"
> > ```
> 
> why is this not defined as a global parameter?
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:1733 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

All of Compute have refered to Compute defined common objects. Compute has been around longer than ARM standard objects and we utilize our own definitions at the moment. We are working on referring to ARM objects in our transition to typespec for objects that have the same definition

**Comment by grizzlytheodore** [comment]
> > ```
> >       "description": "The timestamp for when the resource is soft-deleted."
> > ```
> 
> you should specify the format
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3812 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

I added formating in description. but did you mean add "format" property?

**Comment by grizzlytheodore** [comment]
> > ```
> >     "resourceArmId": {
> > ```
> 
> you can add the arm-id format
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3802 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

addressed: https://github.com/Azure/azure-rest-api-specs/pull/31254/commits/7bcc1afec305f43608475855c7255542daae44d6

**Comment by grizzlytheodore** [comment]
> > ```
> >     "softDeletedArtifactType": {
> > ```
> 
> can this have any string? or it can be used an enum here?
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3806 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

addressed: https://github.com/Azure/azure-rest-api-specs/pull/31254/commits/eebef0637e283823838214eb6dbf4a7e4cab1d7e

**Comment by grizzlytheodore** [comment]
> what are the possible values for this property?

updated as enum: https://github.com/Azure/azure-rest-api-specs/pull/31254/commits/1dd88171a657aa0cddfc7297dd032ae86ef77673

**Comment by grizzlytheodore** [comment]
> > ```
> >       "description": "This property specifies the name of the platformAttributes. It could be either source_image_publisher or source_image_offer or source_image_sku or source_image_version"
> > ```
> 
> from the description it can be converted to an enum
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4198 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

this is read-only. the description is updated: https://github.com/Azure/azure-rest-api-specs/pull/31254/commits/b3db98a0b98bc0b8592815a78809884d807a4fc0

**Comment by grizzlytheodore** [comment]
> > ```
> >     "executedValidations": {
> > ```
> 
> you should add a x-ms-identifiers also for arrays in this definition
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4114 in [5e7c233](https://github.com/Azure/azure-rest-api-specs/commit/5e7c2335f4b3a8542748992a606ebba3e5ac3cf3). [](commit_id = [5e7c233](https://github.com/Azure/azure-rest-api-specs/commit/5e7c2335f4b3a8542748992a606ebba3e5ac3cf3), deletion_comment = False)

addressed": https://github.com/Azure/azure-rest-api-specs/pull/31254/commits/7bcc1afec305f43608475855c7255542daae44d6

**Comment by ms-bogdan-rotaru** [comment]
>         "resourceArmId": {

This is fixed, marking as resolved

---
In reply to: [2470781326](https://github.com/Azure/azure-rest-api-specs/pull/31254#issuecomment-2470781326) [](http://example.com/codeflow?ancestors=2470781326)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3802 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by ms-bogdan-rotaru** [comment]
>         "softDeletedArtifactType": {

This still requires input

---
In reply to: [2470782889](https://github.com/Azure/azure-rest-api-specs/pull/31254#issuecomment-2470782889) [](http://example.com/codeflow?ancestors=2470782889)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3806 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by ms-bogdan-rotaru** [comment]
>         "status": {

This is fixed, marking as resolved

---
In reply to: [2470787477](https://github.com/Azure/azure-rest-api-specs/pull/31254#issuecomment-2470787477) [](http://example.com/codeflow?ancestors=2470787477)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:4177 in 98b2dc9. [](commit_id = 98b2dc9aac52cac75f52d2f204f991a08bec7bf3, deletion_comment = False)

**Comment by ms-bogdan-rotaru** [comment]
@grizzlytheodore There still are some open comments, please address or close them where applicable.

**Comment by grizzlytheodore** [comment]
> > ```
> >     "softDeletedArtifactType": {
> > ```
> 
> This still requires input
> 
> In reply to: [2470782889](https://github.com/Azure/azure-rest-api-specs/pull/31254#issuecomment-2470782889)
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2024-03-03/gallery.json:3806 in [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3). [](commit_id = [98b2dc9](https://github.com/Azure/azure-rest-api-specs/commit/98b2dc9aac52cac75f52d2f204f991a08bec7bf3), deletion_comment = False)

what change does this need? I updated to enum as shown here: https://github.com/Azure/azure-rest-api-specs/pull/31254#issuecomment-2484245148

**Review by haagha — APPROVED** [review]

**Pull request merged**
