### PR TITLE
Adding deprecation note

### PR DESCRIPTION
**Pull request by sethmanheim**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sethmanheim** [comment]
#sign-off Not sure if signing off works.

**Comment by olydis** [comment]
@veronicagg is this the recommended way for deprecating properties?

**Comment by sethmanheim** [comment]
@olydis @veronicagg It's more that the property is unsupported -- we've had customer questions on it and a request to add a note to the docs.

**Comment by veronicagg** [comment]
@olydis @sethmanheim It makes sense to add a note in the description as it helps customers, and as far as I know we have no good way in swagger itself to indicate it. Hopefully in the next api-version, the property can be removed.

**Comment by sethmanheim** [comment]
@olydis @veronicagg Sounds good, can you please merge?

**Comment by sethmanheim** [comment]
@olydis @veronicagg Please make a decision on merging so we can close this PR.

**Review by olydis — APPROVED** [review]

**Comment by olydis** [comment]
@veronicagg Sounds reasonable, thanks for the info!

**Pull request merged**
