### PR TITLE
Fix Virtual Wan Point to site feature resources property names from swagger.

### PR DESCRIPTION
**Pull request by Nilambari**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by Nilambari** [comment]
The main PR for this feature which was merged :- https://github.com/Azure/azure-rest-api-specs/pull/7238
We realized that the resource property names need correction, so opening this PR. This feature is not yet released, so not used by anybody yet.

**Comment by Nilambari** [comment]
Gentle reminder! Thanks.

**Comment by number213** [comment]
Is this a bugfix? Do you need to re-release SDKs? Please fix indentation so the changes could be seen clearly and make the same change in `network-october-release`.
cc: @MikhailTryakhov

**Comment by Nilambari** [comment]
> Is this a bugfix? Do you need to re-release SDKs? Please fix indentation so the changes could be seen clearly and make the same change in network-october-release.
> cc: @MikhailTryakhov

Yes this is a bugfix and need to re-release sdks. Fixed the formating. Will open another PR for network-october-release branch as well.

**Comment by Nilambari** [comment]
Can you Please help approCan you Please help approve PR?

**Comment by Nilambari** [comment]
Other PR for October branch is merged. Can you Please help merge this PR as well?

**Comment by Nilambari** [comment]
@number213 can u help merge it? The fix is already merged for next version release.

**Comment by Nilambari** [comment]
Let me know if its ok to skip this as the fix is already merged to next version release and we are announcing release with next version swagger only.

**Comment by number213** [comment]
@Nilambari I would say we shouldn't skip this fix. Please help me ping email thread ("Swagger PR with bugfix")

**Review by zikalino — APPROVED** [review]

**Comment by Nilambari** [comment]
Who can help merge the changes? Thanks!

**Pull request merged**
