### PR TITLE
Remove new vnet parameters from official swagger

### PR DESCRIPTION
**Pull request by dnayantara**
Apologies for the number of commits. I was unable to squash them into one. The cleaning up commits page does not work.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
This new parameters were pre-emptively added to Swagger before they were deployed to the production service. There was then a design change so we are removing the new property from Swagger for now in order to avoid publishing the new property in clients. This is not a client breaking change because clients have not been published with these new properties.

**Review by jaredmoo — APPROVED** [review]

**Comment by dnayantara** [comment]
Some failures in build seem to not be associated with this change.

**Comment by salameer** [comment]
Hi @alvadb, small ping here

**Comment by alvadb** [comment]
There appears to be a breaking change.  Adding ARM for sign off.

**Comment by jaredmoo** [comment]
Not a breaking change because these properties were never actually deployed to production. We added them to Swagger in advance of production deployment.

**Comment by ravbhatnagar** [comment]
since @jaredmoo  confirmed that this was never deployed to prod, this would have never worked. So no ARM sign off needed in this case. @alvadb - please continue with your review and sign off.

**Comment by jaredmoo** [comment]
Can we get some action on this? I restarted the build and it's green

**Review by alvadb — APPROVED** [review]

**Pull request merged**
