### PR TITLE
WebApps - Add ResourceHealthMetadata.json to readme.md for SDK generation

### PR DESCRIPTION
**Pull request by nking-1**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Close then re-open to hopefully fix CI.

**Comment by Nking92** [comment]
@jhendrixMSFT Looks like the CI is fixed. My team is ready to merge if everything looks good to you. We need this as soon as possible so we can publish a new Python SDK. Thanks!

**Comment by Nking92** [comment]
@jhendrixMSFT I made an additional change to fix some problems with the generated SDK. The deleted web app model was not correct in the swagger which broke our APIs in SDKs / Powershell.

**Review by jhendrixMSFT — APPROVED** [review]
Waiting for CI to finish.

**Comment by panchagnula** [comment]
@jhendrixMSFT , I see that Linter Diff never completes & looking at the details there a some warnings reported. However, we are unable to parse if the new warning from the existing ones - can you help us identify the warning specific to this change? Thank you.

**Comment by jhendrixMSFT** [comment]
@panchagnula I spoke with the CI owners about this, it's a known issue that they're working on.  In the meantime take a look at the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/420341638) and search for ```ResourceHealthMetadata.json``` to see the warning introduced by this swagger.

**Comment by Nking92** [comment]
After reviewing the new warnings, I can say we are OK with taking the current swagger as-is. The devs for those APIs will fix them in the future. The timeline for that dev work is out of scope for our deadlines for the new SDKs, so we'd like to take this swagger update to unblock short-term work.

**Pull request merged**
