### PR TITLE
Port AppGw changes from 2018-11-01 into 2018-12-01

### PR DESCRIPTION
**Pull request by anton-evseev**
Port Application Gateway changes from https://github.com/Azure/azure-rest-api-specs/pull/4996 into 2018-12-01

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
Need to get this fix in first https://github.com/Azure/azure-rest-api-specs/pull/5013

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by number213** [comment]
@dsgouda can you please merge this? CI fails with OOM again

**Comment by number213** [comment]
@dsgouda nvm, restarting CI multiple times helped it pass. All green

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
