### PR TITLE
[Hub Generated] Review request for Microsoft.Batch to add version stable/2020-03-01

### PR DESCRIPTION
**Pull request by matthchr**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/matthchr/azure-rest-api-specs/feature%2Fmarch-2020-mgmt-swagger...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

Here's a summary of the changes:
- Added new API version `2020-03-01`.
- Added new `PrivateLinkResource` resource type, under the `BatchAccount`. 
  - Note that the shape of this resource is mandated to us by the Azure Networking team.
- Added new `PrivateEndpointConnection` resource type, under the `BatchAccount`.
  - Note that the shape of this resource is mandated to us by the Azure Networking team.
- Added new `encryption` option to the `BatchAccount`, allowing customers to configure "Customer Managed Key" encryption.
- Added new `publicNetworkAccess` property to the BatchAccount.
  - When this is `Disabled`, we will create `PrivateEndpointConnection/PrivateLinkResource's` above, which customer can use to interact with their Batch account without having a public DNS entry, via routing requests to front end only over private VNET's.
- New `DiskEncryptionConfiguration` option on pool, allowing customers to enable encryption of one or more disks on the VMs in their pool.
- [Breaking] Changed `publicIPs` on `NetworkConfiguration` to `publicIPAddressConfiguration`, a complex entity which now also allows for disabling of pool public IPs entirely.
- Various documentation improvements.
- Updated examples.

### CODE REVIEW

**Comment by sanjaiganesh** [comment]
>         "operationId": "PrivateLinkResource_ListByBatchAccount",

Plural..
PrivateLinkResources_

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:1492 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         "operationId": "PrivateLinkResource_Get",

Plural..
PrivateLinkResources_

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:1545 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         "operationId": "PrivateLinkResource_Get",

same for other new operations

---
In reply to: [593729590](https://github.com/Azure/azure-rest-api-specs/pull/8536#issuecomment-593729590) [](ancestors = 593729590)

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:1545 in 96b692e. [](commit_id = 96b692ea1dc790e28d8d494baa5b05931bd7c6b2, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>       "description": "The private link service connection state of the private endpoint connection"

some of these could be readonly?  (like status)

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:3184 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>               "$ref": "#/definitions/PrivateEndpointConnection"

Mostly, not all the (writable) properties are not patchable.. 
You may review and consider creating a separate definition used with patch to avoid accidentally making writable property patchable.

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:1730 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         }

mark this with x-ms-secret

Also, mark this x-ms-mutability: write/update and ensure secrets are not returned in GET calls.

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:2537 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         }

secrets need to be returne donly in explicit POST calls like listKeys

---
In reply to: [593732067](https://github.com/Azure/azure-rest-api-specs/pull/8536#issuecomment-593732067) [](ancestors = 593732067)

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:2537 in 96b692e. [](commit_id = 96b692ea1dc790e28d8d494baa5b05931bd7c6b2, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>           "description": "If not specified, the default value is 'enabled'.",

use "default": "" to express?  (in def of PublicNetworkAccessType)

---
Refers to: specification/batch/resource-manager/Microsoft.Batch/stable/2020-03-01/BatchManagement.json:2239 in 2ac76e8. [](commit_id = 2ac76e88ce280204869c94b8d97aeab63b655db3, deletion_comment = False)

**Comment by matthchr** [comment]
@sanjaiganesh - what is the guiding factor for you recommending plural for:
`PrivateLinkResources_` and `PrivateEndpointConnections_`?

None of the other resources in the specification use plural there - for example:
1. `Pool_` not `Pools_`
2. `BatchAccount_` not `BatchAccounts_`
3. `Certificate_` not `Certificates_`
4. `Application_` not `Applications_`
etc

Given that the rest of the specification is using singular for that piece, shouldn't we stay consistent within the specification? Otherwise our generated SDKs will be following two patterns.

**Comment by matthchr** [comment]
> some of these could be readonly? (like status)
Fixed.

Only `PrivateLinkServiceConnectionState.status` and `PrivateLinkServiceConnectionState.description`  are actually updatable. Marked all others as readonly.

**Comment by matthchr** [comment]
> mark this with x-ms-secret Also, mark this x-ms-mutability: write/update and ensure secrets are not returned in GET calls.

This is not actually a secret. It's just a path to a keyvault URL. The URL is not secret so I don't think this applies?

> secrets need to be returne donly in explicit POST calls like listKeys
Same response here - this isn't a secret it's just a URL.

**Comment by matthchr** [comment]
> use "default": "" to express? (in def of PublicNetworkAccessType)

This doesn't seem to actually generate documentation which specifies what the default is? (At least, not based on my running of AutoRest). I've left the documentation that we have, but also added the default.

**Comment by sanjaiganesh** [comment]
very much agreed on the consistency . i recall linter failures or so.. I shall follow up with SDK team to add linter checks, if they strongly feel about that.

---
In reply to: [594084860](https://github.com/Azure/azure-rest-api-specs/pull/8536#issuecomment-594084860) [](ancestors = 594084860)

**Comment by sanjaiganesh** [comment]
probably.. sure.

---
In reply to: [594091051](https://github.com/Azure/azure-rest-api-specs/pull/8536#issuecomment-594091051) [](ancestors = 594091051)

**Comment by matthchr** [comment]
@leni-msft - can you please take a look at this since ARM has approved?

**Comment by leni-msft** [comment]
> [Breaking] Changed publicIPs on NetworkConfiguration to publicIPAddressConfiguration, a complex entity which now also allows for disabling of pool public IPs entirely.

@matthchr is the change really necessary? as it would cause sdk breaking change, and release a new major version. We have concern that the sdk version bumps up too frequently, i.e., python sdk 8.0.0 was just released several months ago. So would like to confirm with you.
cc. @zikalino

**Comment by matthchr** [comment]
@leni-msft - Yes, the change is really required. It is containing a required feature for JEDI and has a ship deadline of 3/10.
We have changed this portion of the API so that in the future other changes related to IP management will be located in the new `PublicIPAddressConfiguration` object and should be nonbreaking (provided it's just a new property).

Additionally, the last breaking change of the service management plane was 2019-08-05, which was 5 months ago. It's pretty common for us to make 1-2 breaking changes a year, which this change is in-line with.

**Review by xingwu1 — APPROVED** [review]

**Comment by matthchr** [comment]
@leni-msft - Xing has approved. Please merge when you get the chance

**Pull request merged**
