### PR TITLE
Fix Lint issues in ContainerApps.json

### PR DESCRIPTION
**Pull request by Zijian-Ju**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Zijian-Ju** [comment]
> > The breaking change is introduced in previous preview version: 2022-11-01-preview. It has been approved in https://msazure.visualstudio.com/One/_workitems/edit/16986590. Seems like it is detected as we modified the same file.
> > > Hi @Zijian-Ju, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/24107&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.
> 
> @Zijian-Ju ,can you give a swagger pr link which approved the breaking change?thanks

Sure. Here is the PR: https://github.com/Azure/azure-rest-api-specs/pull/22423, Thanks

**Comment by kazrael2119** [comment]
> > > The breaking change is introduced in previous preview version: 2022-11-01-preview. It has been approved in https://msazure.visualstudio.com/One/_workitems/edit/16986590. Seems like it is detected as we modified the same file.
> > > > Hi @Zijian-Ju, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/24107&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.
> > 
> > 
> > @Zijian-Ju ,can you give a swagger pr link which approved the breaking change?thanks
> 
> Sure. Here is the PR: #22423, Thanks

I don't think this breaking is from above pr:
image

**Comment by Zijian-Ju** [comment]
> > > > The breaking change is introduced in previous preview version: 2022-11-01-preview. It has been approved in https://msazure.visualstudio.com/One/_workitems/edit/16986590. Seems like it is detected as we modified the same file.
> > > > > Hi @Zijian-Ju, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/24107&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.
> > > 
> > > 
> > > @Zijian-Ju ,can you give a swagger pr link which approved the breaking change?thanks
> > 
> > 
> > Sure. Here is the PR: #22423, Thanks
> 
> I don't think this breaking is from above pr: image

Sorry, here is the correct PR: https://github.com/Azure/azure-rest-api-specs/pull/22380. They shared the same breaking change approval,

**Comment by kazrael2119** [comment]
> > > > > The breaking change is introduced in previous preview version: 2022-11-01-preview. It has been approved in https://msazure.visualstudio.com/One/_workitems/edit/16986590. Seems like it is detected as we modified the same file.
> > > > > > Hi @Zijian-Ju, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/24107&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.
> > > > 
> > > > 
> > > > @Zijian-Ju ,can you give a swagger pr link which approved the breaking change?thanks
> > > 
> > > 
> > > Sure. Here is the PR: #22423, Thanks
> > 
> > 
> > I don't think this breaking is from above pr: image
> 
> Sorry, here is the correct PR: #22380. They shared the same breaking change approval,

add "Approved-BreakingChange" label because it has been approved from above pr

**Review by kazrael2119 — APPROVED** [review]
skip sdk breaking change review because it is not caused by this pr

**Comment by Zijian-Ju** [comment]
Hi @kazrael2119 , I am wondering what else steps are needed for merging the PR?

**Comment by kazrael2119** [comment]
> I am wondering what else steps are needed for merging the PR?

Can you fix above review? After you update it , If there are no other error or failed，it can be merged

**Comment by Zijian-Ju** [comment]
> 

May I ask which review you are referring? As the only review I can find is from you "skip sdk breaking change review because it is not caused by this pr"

**Comment by kazrael2119** [comment]
> > 
> 
> May I ask which review you are referring? As the only review I can find is from you "skip sdk breaking change review because it is not caused by this pr"

image
this one

**Comment by Zijian-Ju** [comment]
> > > 
> > 
> > 
> > May I ask which review you are referring? As the only review I can find is from you "skip sdk breaking change review because it is not caused by this pr"
> 
> image this one

Hi @kazrael2119 we are submitting this change since our PR https://github.com/Azure/azure-rest-api-specs/pull/24103 to main branch is blocked by the LROErrorContent lint issue: https://github.com/Azure/azure-rest-api-specs/pull/24103/checks?check_run_id=13679052730. We prefer to use our self-defined error response as unified one (which is  ./CommonDefinitions.json#/definitions/DefaultErrorResponse). Do you know how can we bypass this check in our PR to main branch?

Add @howang-ms , and @Juliehzl into discussion

**Comment by kazrael2119** [comment]
> 

I know , my meaning is that you should change all services' responses schema, because if you don't do that ,sdk generation will fail with duplicate schema. So if you want to use your self-defined error response, please update all service, not only ContainerApps.

**Comment by tadelesh** [comment]
> @Zijian-Ju , I know , my meaning is that you should change all services' responses schema, because if you don't do that ,sdk generation will fail with duplicate schema. So if you want to use your self-defined error response, please update all service, not only ContainerApps.
> 
> If you want to merge this pr first, and update these in #24103 later, I think it may be good too. @tadelesh , What do you think?

It will also block the merge for https://github.com/Azure/azure-rest-api-specs/pull/24103.

**Comment by Zijian-Ju** [comment]
> It will also block the merge for #24103. So, it's better to consolidate them.

Thanks @kazrael2119  for explanation. But I am a bit confused about what you mean by "So if you want to use your self-defined error response, please update all service, not only ContainerApps.". Does it mean we have to add our self-defined error response under common-types/resource-management/v5/** folder and reference that one if we would like to keep using it? Or we may still be blocked by the SDK generation even if I keep using the DefaultErrorResponse?

**Comment by kazrael2119** [comment]
> > It will also block the merge for #24103. So, it's better to consolidate them.
> 
> Thanks @kazrael2119 for explanation. But I am a bit confused about what you mean by "So if you want to use your self-defined error response, please update all service, not only ContainerApps.". Does it mean we have to add our self-defined error response under common-types/resource-management/v5/** folder and reference that one if we would like to keep using it? Or we may still be blocked by the SDK generation even if I keep using the DefaultErrorResponse?

No,  I mean you should change all ```./CommonDefinitions.json#/definitions/DefaultErrorResponse``` to your self-defined error response , like```/common-types/resource-management/v5/types.json#/definitions/ErrorResponse```  in all these service:
image
not only ContainerApps

NOTICE: If you use v5, then all versions must be v5, not some v3 and some v5

**Comment by Zijian-Ju** [comment]
> > > It will also block the merge for #24103. So, it's better to consolidate them.
> > 
> > 
> > Thanks @kazrael2119 for explanation. But I am a bit confused about what you mean by "So if you want to use your self-defined error response, please update all service, not only ContainerApps.". Does it mean we have to add our self-defined error response under common-types/resource-management/v5/** folder and reference that one if we would like to keep using it? Or we may still be blocked by the SDK generation even if I keep using the DefaultErrorResponse?
> 
> No, I mean you should change all `./CommonDefinitions.json#/definitions/DefaultErrorResponse` to your self-defined error response , like`/common-types/resource-management/v5/types.json#/definitions/ErrorResponse` in all these service: image not only ContainerApps
> 
> NOTICE: If you use v5, then all versions must be v5, not some v3 and some v5



> > > It will also block the merge for #24103. So, it's better to consolidate them.
> > 
> > 
> > Thanks @kazrael2119 for explanation. But I am a bit confused about what you mean by "So if you want to use your self-defined error response, please update all service, not only ContainerApps.". Does it mean we have to add our self-defined error response under common-types/resource-management/v5/** folder and reference that one if we would like to keep using it? Or we may still be blocked by the SDK generation even if I keep using the DefaultErrorResponse?
> 
> No, I mean you should change all `./CommonDefinitions.json#/definitions/DefaultErrorResponse` to your self-defined error response , like`/common-types/resource-management/v5/types.json#/definitions/ErrorResponse` in all these service: image not only ContainerApps
> 
> NOTICE: If you use v5, then all versions must be v5, not some v3 and some v5

Sorry my previous expression may cause some confusion. :et me clarify, I mean we would like to keep using ./CommonDefinitions.json#/definitions/DefaultErrorResponse for all of our API response. But when I did it for my new API: 
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.App/containerApps/{containerAppName}/start`
and 
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.App/containerApps/{containerAppName}/stop` It will trigger LROErrorContent lint error detected in PR https://github.com/Azure/azure-rest-api-specs/pull/24103. We are wondering can this lint error be bypassed if I keep using  `./CommonDefinitions.json#/definitions/DefaultErrorResponse`

**Pull request merged**
