### PR TITLE
[Hub Generated] Publish private branch 'eventListener'

### PR DESCRIPTION
**Pull request by Y-Sindo**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/published%2FY-Sindo%2Fazure-rest-api-specs-pr%2FeventListener...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Y-Sindo** [comment]
The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/7806](https://github.com/Azure/azure-rest-api-specs-pr/pull/7806)

**Comment by raosuhas** [comment]
>             "description": "Success."

No Content

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:650 in 0baedaf. [](commit_id = 0baedafd0267a25f54a5cee402b6e4a254ee3e3c, deletion_comment = False)

**Comment by raosuhas** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SignalRService/webPubSub/{resourceName}/customDomains/{name}": {

suggest updating the variable to be more descriptive i.e 

customdomainname vs name

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:714 in 0baedaf. [](commit_id = 0baedafd0267a25f54a5cee402b6e4a254ee3e3c, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "201": {

need to include 200 as well here for Re-PUT

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:809 in 0baedaf. [](commit_id = 0baedafd0267a25f54a5cee402b6e4a254ee3e3c, deletion_comment = False)

**Comment by raosuhas** [comment]
>         "customCertificate": {

Looks like the ResourceReference takes care of this. Please ignore the original comment

---
In reply to: [1232059202](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232059202) [](http://example.com/codeflow?ancestors=1232059202)

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:1927 in ea39b4a. [](commit_id = ea39b4a1af5580f2dddc1c313d6a4632f0f1760d, deletion_comment = False)

**Comment by raosuhas** [comment]
>         }

How does RBAC work here ? Does the user need to have permissions on the certificate to create the custom domain ?

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:1929 in 0baedaf. [](commit_id = 0baedafd0267a25f54a5cee402b6e4a254ee3e3c, deletion_comment = False)

**Comment by raosuhas** [comment]
>     "EventHubEndpoint": {

I dont see this description being used anywhere. Please remove all unused Descriptions from the file. 

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:1982 in 0baedaf. [](commit_id = 0baedafd0267a25f54a5cee402b6e4a254ee3e3c, deletion_comment = False)

**Comment by Y-Sindo** [comment]
> > ```
> > "EventHubEndpoint": {
> > ```
> 
> I dont see this description being used anywhere. Please remove all unused Descriptions from the file.
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:1982 in [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c). [](commit_id = [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c), deletion_comment = False)

`EventHubEndpoint` is a derived type of `EventListenerEndpoint`. And `EventNameFilter` is a derived type of `EventListenerFilter`. Polymorphism is used here according to https://github.com/Azure/autorest/blob/main/docs/openapi/howto/polymorphism.md

**Comment by juniwang** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SignalRService/webPubSub/{resourceName}/customDomains/{name}": {
> > ```
> 
> suggest updating the variable to be more descriptive i.e
> 
> customdomainname vs name
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:714 in [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c). [](commit_id = [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c), deletion_comment = False)

Understood. The problem for us is the swagger spec is autogenerated from source code. And the same code is used to generate multiple specs. Renaming the parameter would cause breaking changes to other specs since this name was merged already. Can we keep the current name?

**Comment by juniwang** [comment]
> > ```
> >       "201": {
> > ```
> 
> need to include 200 as well here for Re-PUT
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:809 in [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c). [](commit_id = [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c), deletion_comment = False)

For re-put requests, our RP still needs to handle it asynchorously by design. that means this API will never return 200. Do we still need to add code 200 regardless of the actual behavior?

**Comment by juniwang** [comment]
> > ```
> >     }
> > ```
> 
> How does RBAC work here ? Does the user need to have permissions on the certificate to create the custom domain ?
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2022-08-01-preview/webpubsub.json:1929 in [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c). [](commit_id = [0baedaf](https://github.com/Azure/azure-rest-api-specs/commit/0baedafd0267a25f54a5cee402b6e4a254ee3e3c), deletion_comment = False)

No. There are two different actions: `webPubSub/customCertificate/write` and `webPubSub/customDomain/write` which allows customers to define rbac separatedly.

**Comment by raosuhas** [comment]
sure, can you make a note for future to keep this format in code ?

---
In reply to: [1232785540](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232785540) [](http://example.com/codeflow?ancestors=1232785540,1232785540)

**Comment by raosuhas** [comment]
for puts both 200 and 201 is async : 
[https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put) 

Server can indicate it is processing request as a Re-PUT if it returns OK instead of Created


---
In reply to: [1232786637](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232786637) [](http://example.com/codeflow?ancestors=1232786637,1232786637)

**Comment by raosuhas** [comment]
No i mean when when you do a customdomain/write you pass in the customcertificate , how do you ensure that the calling used has permissions on the customcertificate ? Are you planning to include linked access checks ? [https://armwiki.azurewebsites.net/authorization/RBACLinkedAccessCheck.html?q=linked%20access%20check](https://armwiki.azurewebsites.net/authorization/RBACLinkedAccessCheck.html?q=linked%20access%20check)

---
In reply to: [1232788275](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232788275) [](http://example.com/codeflow?ancestors=1232788275,1232788275)

**Comment by raosuhas** [comment]
This is something we discourage since it makes it harder to read the swagger during review. 

---
In reply to: [1234402627](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1234402627) [](http://example.com/codeflow?ancestors=1234402627,1234402627)

**Comment by juniwang** [comment]
> sure, can you make a note for future to keep this format in code ?
> 
> In reply to: [1232785540](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232785540)

sure ,will do

**Comment by juniwang** [comment]
> for puts both 200 and 201 is async : https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put
> 
> Server can indicate it is processing request as a Re-PUT if it returns OK instead of Created
> 
> In reply to: [1232786637](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232786637)

I see. will add 200 to response

**Comment by juniwang** [comment]
> No i mean when when you do a customdomain/write you pass in the customcertificate , how do you ensure that the calling used has permissions on the customcertificate ? Are you planning to include linked access checks ? https://armwiki.azurewebsites.net/authorization/RBACLinkedAccessCheck.html?q=linked%20access%20check
> 
> In reply to: [1232788275](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232788275)

The person who does customdomain/write does not need a write permission to the customCertificate.  Read permission is needed. Do you think we need to enable link access check on customcertificate/read?

**Comment by mentat9** [comment]
> > No i mean when when you do a customdomain/write you pass in the customcertificate , how do you ensure that the calling used has permissions on the customcertificate ? Are you planning to include linked access checks ? https://armwiki.azurewebsites.net/authorization/RBACLinkedAccessCheck.html?q=linked%20access%20check
> > In reply to: [1232788275](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232788275)
> 
> The person who does customdomain/write does not need a write permission to the customCertificate. Read permission is needed. Do you think we need to enable link access check on customcertificate/read?

Yes, it sounds like you need the linked access read check.

**Review by live1206 — APPROVED** [review]

**Comment by Y-Sindo** [comment]
> for puts both 200 and 201 is async : https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put
> 
> Server can indicate it is processing request as a Re-PUT if it returns OK instead of Created
> 
> In reply to: [1232786637](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232786637)

Hello experts, I'd like to revert the change that adding 200 response code as this change results in a breaking change in #20272 of another resource type "SignalR". "SignalR" shares nearly the same backend implematation with "Web PubSub" and the same API for "SignalR" is already published. Adding 200 response code to "Web PubSub" also means adding to "SignalR", which is a breaking change.

**Comment by leni-msft** [comment]
> > for puts both 200 and 201 is async : https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put
> > Server can indicate it is processing request as a Re-PUT if it returns OK instead of Created
> > In reply to: [1232786637](https://github.com/Azure/azure-rest-api-specs/pull/20467#issuecomment-1232786637)
> 
> Hello experts, I'd like to revert the change that adding 200 response code as this change results in a breaking change in #20272 of another resource type "SignalR". "SignalR" shares nearly the same backend implematation with "Web PubSub" and the same API for "SignalR" is already published. Adding 200 response code to "Web PubSub" also means adding to "SignalR", which is a breaking change.

@raosuhas @mentat9 could you help review this change again ?

**Comment by leni-msft** [comment]
Adding back the ARMSignOff label, as the changes have been approved in https://github.com/Azure/azure-rest-api-specs-pr/pull/7806

**Comment by leni-msft** [comment]
@fengzhou-msft please check .net SDK generation failure

**Pull request merged**
