### PR TITLE
Update Azure SQLDB 2020-08-01-preview swagger files

### PR DESCRIPTION
**Pull request by ericshape**
Update Azure SQLDB 2020-08-01-preview swagger files.

this PR is a copy of an existing API-version to a new dated preview version (2020-08-01-preview) with no API changes. Via this PR, we will address over **147** S360 alerts about API swagger completeness.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Actually, it's not really breaking change, we just cleaned up the unused common parameters**
https://github.com/Azure/azure-rest-api-specs/pull/10994/checks?check_run_id=1421297150

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by allenjzhang** [comment]
This is a very large changeset. I assume many are copied over into the new version folder. Can you share what has changed or just simple copy. Please also fix model validations errors. We should also discuss breaking changes as well.

**Comment by ericshape** [comment]
@allenjzhang I just added you as a reviewer of the internal DSMainDev PR.

**Comment by chiragg4u** [comment]
> This is a very large changeset. I assume many are copied over into the new version folder. Can you share what has changed or just simple copy. Please also fix model validations errors. We should also discuss breaking changes as well.

While adding new version the recommendation is to copy the existing version into new directory structure for first commit and then push new changes for easy review. Please create new branch with this recommendation for faster review.

**Comment by chiragg4u** [comment]
Please go through the contribution checklist added as part of the review and mark them completed. This is a requirement before review can be continued.

**Comment by ericshape** [comment]
> Please go through the contribution checklist added as part of the review and mark them completed. This is a requirement before review can be continued.

@chiragg4u 
I have added you as the review of my internal DsMainDev PR. 
And yep, I will follow your requests and this PR is still in the progress. 

For the existing spec, nothing should've changed in any APIs, as I am just back publishing all the api under this version as per the S360 requirement. But I still need to carefully compare them then. 

I plan to schedule a meeting with @allenjzhang and you for this PR once I addressed most of the lint errors.

**Comment by ericshape** [comment]
@allenjzhang @chiragg4u 
do you know what is meaning of this error in https://dev.azure.com/azure-sdk/public/_build/results?buildId=565542&view=logs&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a&l=346 ?
```
error: 
YAMLException: unacceptable kind of an object to dump [object Error]
    at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
    at writeBlockSequence (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:521:9)
    at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:740:9)
    at writeBlockMapping (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at Object.dump (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
    at /home/vsts/work/1/s/node_modules/oav/dist/lib/validate.js:136:47 {
  reason: 'unacceptable kind of an object to dump [object Error]',
  mark: undefined
}

```
It seems the validation did not say which JSON file triggered this issue.

**Comment by allenjzhang** [comment]
> @allenjzhang @chiragg4u
> do you know what is meaning of this error in https://dev.azure.com/azure-sdk/public/_build/results?buildId=565542&view=logs&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a&l=346 ?
> 
> ```
> error: 
> YAMLException: unacceptable kind of an object to dump [object Error]
>     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
>     at writeBlockSequence (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:521:9)
>     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:740:9)
>     at writeBlockMapping (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
>     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
>     at Object.dump (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
>     at /home/vsts/work/1/s/node_modules/oav/dist/lib/validate.js:136:47 {
>   reason: 'unacceptable kind of an object to dump [object Error]',
>   mark: undefined
> }
> ```
> 
> It seems the validation did not say which JSON file triggered this issue.

Looks like it is having problems with Timezones.json as it reported after `TdeCertificates.json` and before `TransparentDataEncryption.json`. Though I took a look and didn't spot anything. Assign to Arthur to take a closer look.

BTW, Please also fix all of the other check failures. Thanks

**Comment by ericshape** [comment]
> > @allenjzhang @chiragg4u
> > do you know what is meaning of this error in https://dev.azure.com/azure-sdk/public/_build/results?buildId=565542&view=logs&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a&l=346 ?
> > ```
> > error: 
> > YAMLException: unacceptable kind of an object to dump [object Error]
> >     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
> >     at writeBlockSequence (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:521:9)
> >     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:740:9)
> >     at writeBlockMapping (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
> >     at writeNode (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
> >     at Object.dump (/home/vsts/work/1/s/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
> >     at /home/vsts/work/1/s/node_modules/oav/dist/lib/validate.js:136:47 {
> >   reason: 'unacceptable kind of an object to dump [object Error]',
> >   mark: undefined
> > }
> > ```
> > 
> > 
> > It seems the validation did not say which JSON file triggered this issue.
> 
> Looks like it is having problems with Timezones.json as it reported after `TdeCertificates.json` and before `TransparentDataEncryption.json`. Though I took a look and didn't spot anything. Assign to Arthur to take a closer look.
> 
> BTW, Please also fix all of the other check failures. Thanks

@allenjzhang 
Thanks for your help!
And yep, I am fixing the lint errors within the DSMainDev repo and then push the updated swagger files to here. I will add you and @chiragg4u as the reviewers of the internal PRs. 

@akning-ms Can you help to have a look at the weird lint errors above? Thanks!

**Comment by akning-ms** [comment]
Hi @ericshape you may need to fix model validation & semantic validation first before fix lint validation.

**Comment by akning-ms** [comment]
Hi @ericshape, can we know what is the purpose for this huge PR?  looks it is putting all of you swagger in SQL into a new version?

**Review by pilor — APPROVED** [review]
Author states this is just a copy of an existing api-version to a new dated preview version with no API changes.  No ARM review necessary (and its not realistic to be able to review all of these files without a clean iteration regardless).

**Comment by ericshape** [comment]
@akning-ms  @pilor 
Thanks for reviewing this PR. 
Yes. this PR is to bring all the old versions API spec to the latest API version: 2020-08-01-preview. Via this PR, we will address all the S360 alters about API swagger completeness.

**Comment by ericshape** [comment]
@pilor 
I rebased the PR, can you take a look again? Thanks!

**Comment by zhenglaizhang** [comment]
Hi @ericshape 

Regarding the rest api doc preview failure in https://github.com/Azure/azure-rest-api-specs/pull/10994/checks?check_run_id=1427857562 its because you are using same operation id prefix `DatabaseVulnerabilityAssessmentScans_` in 
different swagger files:
* https://github.com/ericshape/azure-rest-api-specs/blob/add_2018-09-01_preview_swaggers/specification/sql/resource-manager/Microsoft.Sql/preview/2020-08-01-preview/DatabaseVulnerabilityAssessmentScansExport.json#L25
*  https://github.com/ericshape/azure-rest-api-specs/blob/add_2018-09-01_preview_swaggers/specification/sql/resource-manager/Microsoft.Sql/preview/2020-08-01-preview/DatabaseVulnerabilityAssessmentScansExecute.json#L25

The operation id prefix is used as group name, Currently rest api docs build doesn't support use same group name cross different swagger files. **Can you help merge this two operations into single swagger file?**

**Comment by ericshape** [comment]
@zhenglaizhang 
thanks for the comment! I have addressed the API doc errors and the ApiDoc check has passed.

**Review by jamestao — APPROVED** [review]

**Review by bcham — APPROVED** [review]

**Comment by ericshape** [comment]
Can you help us to merge this PR? Thanks!
- This PR was approved by our side: James and Brian.
- The previous iteration also was approved by Chris. 
- All checks have been passed.
- All deployments are done on our side.

**Comment by akning-ms** [comment]
Found there is already a version 2020-08-01-preview in master. and include 2 files databases.json elasticPools.json.
but in this PR. the file name changed to **D**atabases.json **E**lasticPools.json.  it makes breaking change tools can not detect it.
can you clarify it is same files? if yes. can you make them name consistent.  and looks there is many changes between them.(databases.json & Databases.json) if so, then it is not simple copy. you may need a new API version .such as. 2020-11-01-preview

**Comment by ericshape** [comment]
> Found there is already a version 2020-08-01-preview in master. and include 2 files databases.json elasticPools.json.
> but in this PR. the file name changed to **D**atabases.json **E**lasticPools.json. it makes breaking change tools can not detect it.
> can you clarify it is same files? if yes. can you make them name consistent. and looks there is many changes between them.(databases.json & Databases.json) if so, then it is not simple copy. you may need a new API version .such as. 2020-11-01-preview

Yes. they are the same files. And these files in this PR also carry all the old endpoints to the new dated preview version (2020-08-01-preview).

**Pull request merged**
