### PR TITLE
Add new Azure Batch API Version 2016-07-01.3.1

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by matthchr** [comment]
Note for reviewer: If you want us to collapse commits we can do so, but we at least want to maintain two commits:
ac69696 and 1 other, since ac69696 is just copying the file from the old API version (which we left unchanged)

**Comment by John-Hart** [comment]
@matthchr jobReleaseTaskExecutionInfo has two titles (see line https://github.com/matthchr/azure-rest-api-specs/blob/13e647ea4cd6346c0b7c01eec96ff70f33e35954/batch/2016-07-01.3.1/swagger/BatchService.json#L11361).  Sorry I couldn't make the comment inline due to the size of 	01c4041.

**Comment by matthchr** [comment]
@John-Hart Wow, good eye -- will fix.

**Comment by John-Hart** [comment]
@matthchr, the credit belongs to @tbombach and his awesome linter tool

**Comment by John-Hart** [comment]
LGTM

**Pull request merged**
