### PR TITLE
[ADLA - ADLS] - Account APIs object refactor

### PR DESCRIPTION
**Pull request by ro-joowan**
* This PR does not introduce any functional changes

* This PR does introduce breaking changes
  * Object names were modified to be clearer
  * The "Account" tag for ADLA/ADLS has been changed to "Accounts"

* I moved around a lot of code and renamed a bunch of example files.  The two changes mentioned above are the only, real modifications here.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@ro-joowan Can you please point to the commit(s) and line(s) that introduce the breaking changes?  I've generated the Go SDK without and with your changes and I'm not seeing any breaking changes.

**Comment by ro-joowan** [comment]
For the breaking changes below, I pointed to the line in the raw file.

1. https://github.com/ro-joowan/azure-rest-api-specs/blob/e5d67fa8270faa02d66a3a64521f2102864b9cf6/specification/datalake-analytics/resource-manager/Microsoft.DataLakeAnalytics/stable/2016-11-01/account.json#L45

I changed Account_List to Accounts_List.  The effective change to the SDK is that when I call this operation now it's Accounts.List() as opposed to Account.List().  Not sure if this applies to Go

2. https://github.com/ro-joowan/azure-rest-api-specs/blob/e5d67fa8270faa02d66a3a64521f2102864b9cf6/specification/datalake-analytics/resource-manager/Microsoft.DataLakeAnalytics/stable/2016-11-01/account.json#L237

For the body parameter, I changed DataLakeAnalyticsAccount to CreateDataLakeAnalyticsAccountParameters.

3. https://github.com/ro-joowan/azure-rest-api-specs/blob/e5d67fa8270faa02d66a3a64521f2102864b9cf6/specification/datalake-analytics/resource-manager/Microsoft.DataLakeAnalytics/stable/2016-11-01/account.json#L337

For the body parameter, I changed DataLakeAnalyticsAccountUpdateParameters to UpdateDataLakeAnalyticsAccountParameters

**Comment by jhendrixMSFT** [comment]
Thanks for the details.  These breaking changes are in swaggers marked as stable which is discouraged as it breaks customers.  Are they absolutely necessary?

**Comment by ro-joowan** [comment]
@jhendrixMSFT Thanks for your note.  My understanding is that from an API perspective, these changes have no weight.  They affect mainly the SDKs.  Since the "stable" mark is associated with the API version and because these changes are to improve the SDK experience, through consistency, I'd like to have these changes in.  They are not necessary from a functional standpoint, but my opinion is that they are necessary for general SDK improvement.  Also, the "Account_OP to Accounts_OP" change was a recommendation from a Swagger reviewer in a past PR of mine.

**Comment by jhendrixMSFT** [comment]
> the "stable" mark is associated with the API version
I don't believe this is true.  A stable swagger means that it's done and won't incur any further changes (barring any bugs that prevent it from being usable).  It's completely legitimate to have a stable REST API but a preview swagger, it means you're still iterating on the swagger and those iterations might include breaking changes.  While we won't prevent you from making this change do note that it will break consumers of the affected surface area and we do roll up this information in monthly reports.  Please let me know how you want to proceed.
CC @salameer

**Comment by ro-joowan** [comment]
@jhendrixMSFT Samer and I had actually had a discussion on this topic, and he took your stance.  But I think we need some clarification.  Let us consider that we released a new Swagger file with a new API version with these object-refactor, breaking changes.  From an SDK perspective, the user would still face these breaking changes when they upgrade to the new SDK.  Is there a way to alleviate the customer from not experiencing the breaking changes from an SDK perspective?  If these breaking changes were at the API level, then we should release a new API version because we try to avoid API breaking changes on a stable version at all costs (barring any buys as you noted).

FYI @matt1883

**Comment by jhendrixMSFT** [comment]
Each API version is released side-by-side (sadly not all SDK languages support this yet), so releasing a new API version doesn't necessarily break existing customers.  For languages where multiple API versions are not yet supported it's OK for a new API version to introduce breaking changes.

**Comment by ro-joowan** [comment]
@jhendrixMSFT I see, thank you.  The idea that I'm trying to relay is that releasing a new API version does not provide any value for these SDK breaking changes.  We'd like to proceed please.

**Comment by jhendrixMSFT** [comment]
Yes for changes like this I agree introducing a new API version doesn't add any value.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by ro-joowan** [comment]
@jhendrixMSFT Thanks.  You made me really think about this, which was great!  👍

**Pull request merged**
