### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-09-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
    Alread deployed to all global regions by 10/03.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
    ASAP, 10/12.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Dear review board, I would like to clarify the failures in the CI checks.

For [SDK azure-powershell](https://github.com/Azure/azure-rest-api-specs/pull/21038/checks?check_run_id=8779456618), it happened in our previous PR [08-03-preview](https://github.com/Azure/azure-rest-api-specs/pull/20789). From log it seems that the reason for the failure lies in the build tool `/home/cloudtest/.autorest/@autorest_powershell@3.0.491/node_modules/@autorest/powershell/dist/plugins/llcsharp-v2.js - TypeError: value.replace is not a function`. This CI used to be optional and is enabled recently.

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/21038/checks?check_run_id=8779455771), it happened in our previous PR [08-03-preview](https://github.com/Azure/azure-rest-api-specs/pull/20789). I suppose this should be a known issue. Besides it has been replaced by track 2 SDK, released half a month ago.

For [SDK azure-sdk-for-python-track2](https://github.com/Azure/azure-rest-api-specs/pull/21038/checks?check_run_id=8779454092), would confirm with SDK owner, seems like the pipeline is not configured correctly.

For [~[Staging] Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/21038/checks?check_run_id=8779439358), 
  - Violation of [DefinitionsPropertiesNamesCamelCase](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/definitions-properties-names-camel-case.md) should be a **false alert**.
  - Violation of [ValidFormats](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/valid-formats.md) should be newly supported, will confirm with owner of this pipeline.

**Comment by matthchr** [comment]
> Violation of [ValidFormats](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/valid-formats.md) should be newly supported, will confirm with owner of this pipeline.

cc @raych1 - I thought this was enabled now? We were able to merge various other PRs with this annotation, it shouldn't be failing now should it? Example PRs: #19594, #19590, #19592

**Comment by raosuhas** [comment]
The changes in the managedcluster.json looks fine , but I am unable to review the fleets.json since the previous api version was not added in the base commit. 

Can you please update the previous api version in a commit and then update the file with the latest version again so that I can diff it to review ?

Please remove the ARMChangesRequested Label once that is done so that I can continue the review.

**Comment by raych1** [comment]
> > Violation of [ValidFormats](https://github.com/Azure/azure-openapi-validator/blob/develop/docs/valid-formats.md) should be newly supported, will confirm with owner of this pipeline.
> 
> cc @raych1 - I thought this was enabled now? We were able to merge various other PRs with this annotation, it shouldn't be failing now should it? Example PRs: #19594, #19590, #19592

The check passed in this PR.

**Comment by raosuhas** [comment]
@FumingZhang  I still do not see the previous version of the fleets.json in the commit. Please send me an email if this is not clear. You need to add the previous api version as the base commit otherwise I have no way to diff this.

**Comment by FumingZhang** [comment]
Hey @raosuhas, sorry for the confusion. Previously the base (fork from previous version 2022-07-02-preview) **and** new changes of fleets are introduced by a single commit [7f97803](https://github.com/Azure/azure-rest-api-specs/pull/21038/commits/7f9780381fb7d1140cd2a3ff6d3d2dc13d59f900), but we've reverted the change in commit [ce19d7b](https://github.com/Azure/azure-rest-api-specs/pull/21038/commits/ce19d7b8deb45aaf8e7c950baefd8efd348fa5de) and separate the base (fork from previous version 2022-07-02-preview) and new changes in two commits [ae644a9](https://github.com/Azure/azure-rest-api-specs/pull/21038/commits/ae644a9bb53f3b68cc0f387417e282d800eaaec0), [d75052e](https://github.com/Azure/azure-rest-api-specs/pull/21038/commits/d75052e4d9772a43c0f1b746bf025f933e4f79e5).

Could you please help review the latter commit [d75052e](https://github.com/Azure/azure-rest-api-specs/pull/21038/commits/d75052e4d9772a43c0f1b746bf025f933e4f79e5), which should include all the changes new to fleets. Thanks!

**Comment by serbrech** [comment]
@raosuhas

Screen Shot 2022-10-14 at 16 55 39

**Review by raych1 — APPROVED** [review]

**Pull request merged**
