### PR TITLE
Managed Instance swagger to support Authentication Metadata

### PR DESCRIPTION
**Pull request by nesavicMSFT**
Generated Managed Instance swagger to support AuthenticationMetadata property.

### CODE REVIEW

**Review by krivi37 — APPROVED** [review]
Looks good to me

**Review by jeremyfrosti — APPROVED** [review]
LGTM

**Comment by mikekistler** [comment]
Adding the Approved-BreakingChange label only to unblock merge to development branch.

**Comment by visingla-ms** [comment]
>           },

If the actual types are not known, skip putting it instead of putting it as empty.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-05-01-preview/ManagedInstances.json:1102 in e965020. [](commit_id = e9650207dcaf73cd08e0985dfbf77df7555afe4d, deletion_comment = False)

**Pull request merged**
