### PR TITLE
[Compute] New API Version 2021-08-01

### PR DESCRIPTION
**Pull request by haagha**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [x] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by haagha** [comment]
@mentat9 breaking changes were approved in a previous PR [#16099](https://github.com/Azure/azure-rest-api-specs/pull/16099)

**Comment by mentat9** [comment]
>         "getSecureVMGuestStateSAS": {

ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review).

In this case, you could do something more like this: "getSecureVMGuestState": [ None, SAS ].

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-08-01/disk.json:3033 in 5dd4670. [](commit_id = 5dd467019ce61583e6e129518fc802e95a21e7df, deletion_comment = False)

**Comment by mentat9** [comment]
@haagha, your first commit in the new PR already has edits (version changed to 2021-11-01). When adding a new API version, please carefully follow the process for constructing your PR. This is really important to help streamline the workload for ARM reviewers and handle your PR in as timely a manner as possible. The first commit should be the files from the **current API version, unmodified**. Changes (including updating the version) should go into subsequent commits.

All of that notwithstanding, to avoid another round trip, I manually diffed your PR update against the most recent API version of the disk.json file checked into the public repo. Since the changes are modest and straightforward, I'll complete the review on the current PR.

**Comment by mentat9** [comment]
> > ```
> >     "getSecureVMGuestStateSAS": {
> > ```
> 
> ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review.
> 
> In this case, you could do something more like this: "getSecureVMGuestState": [ None, SAS ].
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-08-01/disk.json:3033 in [5dd4670](https://github.com/Azure/azure-rest-api-specs/commit/5dd467019ce61583e6e129518fc802e95a21e7df). [](commit_id = [5dd4670](https://github.com/Azure/azure-rest-api-specs/commit/5dd467019ce61583e6e129518fc802e95a21e7df), deletion_comment = False)

Note, this suggestion doesn't block ARM signoff, but you should consider making a change like this.

**Comment by haagha** [comment]
@mentat9 We will make note of this for future releases, but IF Possible I would like to move forward with the current boolean type because the team wants to do a private preview soon, and making this change would require re-deployment of API and ARM manifest that could cause quite long delays. Thanks.

**Comment by haagha** [comment]
@ArcturusZhang Are these new linting rules resulting in linting errors? Is this PR ready to be merged?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang Are these new linting rules resulting in linting errors? Is this PR ready to be merged?

The linter errors can be ignored.

**Review by ArcturusZhang — APPROVED** [review]

**Comment by haagha** [comment]
@ArcturusZhang the breaking changes are from a previous PR https://github.com/Azure/azure-rest-api-specs/pull/16099 And ARM has signed off so I believe we can merge.

Here is the SDK PR https://github.com/Azure/azure-sdk-for-net/pull/25436

**Pull request merged**
