### PR TITLE
fix: documentation around default os disk size

### PR DESCRIPTION
**Pull request by alexeldeib**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify: **doc comment update. no behavior change**
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR -- **this can ship in SDKs with the next AKS API**

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by alexeldeib** [comment]
seems go sdk considers this breaking? is it really breaking? it's a doc update. I understand SDKs technically require generation but there's no user-facing change here.

**Comment by PhoenixHe-msft** [comment]
@alexeldeib The problem is autorest compose failed because you need to update all the descriptions. If there are two models with the same name but different description then autorest will fail.

**Comment by alexeldeib** [comment]
Is it possible for me to fix this? or do we ignore this type of failure? Not sure I understand what to do

**Comment by PhoenixHe-msft** [comment]
Error: '$.definitions.ContainerServiceOSDisk.description' has incompatible values (---\n>-\n OS Disk Size in GB to be used to specify the disk size for every machine in\n this master/agent pool. If you specify 0,
it will apply the default osDisk\n size according to the vmSize specified.\n,
---\n>-\n OS Disk Size in GB to be used to specify the disk size for every machine in\n this master/agent pool. Defaults to 128 if unspecified,
zero,
or negative.\n)

See lint Error https://github.com/Azure/azure-rest-api-specs/pull/12428#issuecomment-759876725 . You'd better search all the description related to this change, or SDK will fail to generate.

**Comment by alexeldeib** [comment]
> You'd better search all the description related to this change, or SDK will fail to generate.

This is what I don't understand. Do you mean to change the description in all API versions? The new description is not accurate for the four oldest API versions, the old one is correct: 2016-03-30, 2016-09-30, 2017-01-31, and 2017-07-01.

Would updating the default value of the integer field in the swagger be considered breaking as well? If we did that instead, we could align all the descriptions, but only add the correct default to the field definition, not the description.

**Comment by alexeldeib** [comment]
Just to be extremely clear: the behavior of all API versions remains the same. After 2017-07-01, AKS changed the behavior of this API. At that point the description should have been updated and we should have gone through proper review (as necessary). 

Given that we've had these APIs with the same behavior for ~3 years, I'm hoping we can consider this a doc "bug fix". There's really no change occurring, we're just updating the descriptions in the OpenAPI model to reflect reality as it has been for several years.

**Comment by ArcturusZhang** [comment]
@alexeldeib In tag `package-2020-09`, you have the description [here](https://github.com/Azure/azure-rest-api-specs/blob/2fba87a0c96903fdc500a7187d762ca83e5a9af3/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2017-07-01/containerService.json#L296) unchanged which is causing the compose error.
`specification\containerservice\resource-manager\Microsoft.ContainerService\stable\2020-09-01\managedClusters.json` has a model called `ContainerServiceOSDisk`, and `specification\containerservice\resource-manager\Microsoft.ContainerService\stable\2020-09-01\managedClusters.json` also have one called `ContainerServiceOSDisk`. These two swaggers are included by the same tag `package-2020-09`, therefore these two models must be exactly the same to make autorest work properly.
Now you might have three options to work this around:
1. make the description align with each other
2. change one of the model name
3. remove one of the swaggers out of this tag

I believe the first option is the one that makes least destruction. Option 2 introduces swagger breaking changes and SDK breaking changes (if there are any). Option 3 introduces SDK breaking changes.

And this is only for tag `package-2020-09`, autorest exits early since it gets an error when processing this tag. We have 10+ tags unchecked yet.

**Comment by alexeldeib** [comment]
thanks for pointing out the mismatch between files in the same package tag. I totally missed that it was across individual files. 🤦‍♂️ 

think that should fix it, unless I missed the same elsewhere

**Comment by alexeldeib** [comment]
this won't really be accurate, because we mix and match container service 2017-07-01 with managed clusters versions where the behavior changed. The description mismatch for example for package-2017-09 between 2017-07-01/containerService.json and 2017-08-31/managedClusters.json is correct.

I guess we should technically create a new definition, e.g. `ManagedClusterOSDisk` and have that use the new behavior description. But that is _**really**_ a breaking change on the SDK side. 

WDYT?

**Comment by PhoenixHe-msft** [comment]
Is it OK to remove the problematic tags from "batch" in readme.go.md so that will not get generated? And maybe we need to tell lint not to run some tag ...

**Comment by alexeldeib** [comment]
I think I figured out how to fix this. I can add a new version of containerservice which is a copy-paste of the current one, but align the description. Then update the generation directives for managedClusters.json version >= 2018-03-31 to use the new container service api.

**Comment by PhoenixHe-msft** [comment]
Does that fix makes sense to your team...?

**Comment by PhoenixHe-msft** [comment]
@alexeldeib close this PR for no activity. Please comment if you want to resume your work.

**Pull request closed without merging**
