### PR TITLE
Fix examples for storage default tag: package-2021-09

### LINKED ISSUE #17882: Resolve example problems for core RPs
1. compute, network, storage, resource, keyvault
2. resolve mock test failure from example problems

### PR DESCRIPTION
**Pull request by Alancere**
fix https://github.com/Azure/azure-sdk-for-go/issues/17882
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by tadelesh — APPROVED** [review]

**Review by blueww — APPROVED** [review]
LGTM

It's interesting that PR check not catch the API Version mismatch.

**Comment by blueww** [comment]
@jianyexi 

I see the .net SDK check failed for following error "Permission denied" in install autorest. 
Do you have any idea how to fix it?

> 08:12:36.849 command 	autorest --version=2.0.4421 --csharp --reflect-api-versions --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.csharp@2.3.82 --csharp-sdks-folder=/mnt/vss/_work/1/s/azure-sdk-for-net/sdk ../azure-rest-api-specs/specification/storage/resource-manager/readme.md
> 08:12:36.850 info 	Config: {"stdout":{"showInComment":{}},"stderr":{"showInComment":true,"scriptWarning":{}},"exitCode":{"showInComment":true,"result":"error"}}
> 08:12:37.122 cmdout 	[Autorest] AutoRest code generation utility [cli version: 3.0.6335; node: v14.19.1, max-memory: 8192 MB]
> 08:12:37.123 cmdout 	[Autorest] (C) 2018 Microsoft Corporation.
> 08:12:37.123 cmdout 	[Autorest] https://aka.ms/autorest
> 08:12:37.278 cmdout 	[Autorest] There is a new version of AutoRest available (3.6.1).
> 08:12:37.278 cmdout 	[Autorest]  > You can install the newer version with with npm install -g autorest@latest
> 08:12:39.383 cmdout 	[Autorest]    Loading AutoRest core      '/home/cloudtest/.autorest/@microsoft.azure_autorest-core@2.0.4421/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4421)
> 08:12:40.147 cmdout 	[Autorest]    Installing AutoRest extension '@microsoft.azure/autorest.csharp' (2.3.82)
> 08:12:43.460 cmdout 	[Autorest]    Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)
> 08:12:44.374 cmderr 	[Autorest] realpath(): Permission denied
> 08:12:44.375 cmderr 	[Autorest] realpath(): Permission denied
> 08:12:44.375 cmderr 	[Autorest] realpath(): Permission denied
> 08:12:44.624 cmderr 	[Autorest] realpath(): Permission denied
> 08:12:44.625 cmderr 	[Autorest] realpath(): Permission denied
> 08:12:44.625 cmderr 	[Autorest] realpath(): Permission denied
> 08:13:51.844 cmderr 	[Autorest] No usable version of the libssl was found
> 08:13:52.162 cmderr 	[Autorest] FATAL: csharp/simplifier - FAILED
> 08:13:52.162 cmderr W 	[Autorest] FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> 08:13:52.162 cmderr 	[Autorest] Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
> 08:13:52.254 error C 	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-net]: autorest
>

**Comment by jianyexi** [comment]
@ArcturusZhang could you give the advise for the dotnet sdk failure ?

**Comment by jianyexi** [comment]
@Alancere As synced offline, you can ignore the dot track1 SDK failure

**Comment by Alancere** [comment]
@jianyexi If there is no problem, please help me merge it

**Pull request merged**
