### PR TITLE
Add debugSetting into deployment and deploymentOperation for arm-resources

### PR DESCRIPTION
**Pull request by wenwu449**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@wenwu449__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (wenwu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@wenwu449 please do not rename exising specs whenever the API version is changed. Create a new document instead to preserve the history.

**Comment by amarzavery** [comment]
@wenwu449 - Ping ???

**Comment by wenwu449** [comment]
@stankovski @amarzavery I have changed the PR to keep old API version spec and add new API version spec. Please review and merge. Thanks

**Comment by amarzavery** [comment]
@wenwu449 
Line 24: description needs to be updated. We don't have GetLongRunninOperationStatus() anymore. This was the hydra (old codegen) way doing things. Some teams were planning to update the API reference doc and the msdn docs from the swagger specs. Hence, having crisp description everywhere is of prime importance.

**Comment by amarzavery** [comment]
Line 598: ResourceGroups_Delete update description.

**Comment by amarzavery** [comment]
Line 747: Resources_MoveResources update description

**Comment by amarzavery** [comment]
Line 1101: Why would you want to return a 204 for getting a resource under a resource group? Is that used to state that the resource does not exist in the resource group? If so then is that how it should be done. Just trying to understand, when would Resources_Get return a 204?

**Comment by amarzavery** [comment]
Line 2138: DebugSettings has only 1 property named "detailLevel". If you apply the extension ["x-ms-client-flatten" : true](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-client-flatten), then detailLevel will be flattened while deserialization and unflattened while serialization. It gives users a better experience.
Since debugsettings is being added for the first time , we can add this extension right now.

This extension could also be applied on following models but could be breaking change for client side libraries:
- PolicyAssignmentProperties
- PolicyDefinitionProperties
- DeploymentProperties
- DeploymentPropertiesExtended

**Pull request merged**
