### PR TITLE
Remove obsolete azuredata resources

### PR DESCRIPTION
**Pull request by jorgbaca**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by pilor — APPROVED** [review]
From an API standpoint this is fine since these were feature flagged.  SDK team can comment on whether removing them from swagger is the right approach

**Comment by jorgbaca** [comment]
> From an API standpoint this is fine since these were feature flagged. SDK team can comment on whether removing them from swagger is the right approach

Thank you @pilor, who from the SDK team do I need to contact for that? I see this PR has no one assigned yet.

**Comment by pilor** [comment]
> > From an API standpoint this is fine since these were feature flagged. SDK team can comment on whether removing them from swagger is the right approach
> 
> Thank you @pilor, who from the SDK team do I need to contact for that? I see this PR has no one assigned yet.

I don't know why nobody was assigned.  They have a teams channel here:  https://teams.microsoft.com/l/channel/19%3aed5e69f6edcb4a5ca5ccbfaf3fadcdf7%40thread.skype/Swagger%2520-%2520Open%2520API?groupId=da8d67c5-f19d-4799-b158-5dbbef868d49&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by akning-ms** [comment]
Hi @jorgbaca, Sorry, looks our assignment bot missed this PR. I will take care of it. few questions:
1. What languages will you be released if need? I can help ask specific sdk owner to double confirm
2. when is your last release for your sdk?
3. Looks there is only preview version for your swagger? and this preview version is existing for almost 1 year, do you have plan to have GA/stable version?

**Comment by jorgbaca** [comment]
> 1. What languages will you be released if need? I can help ask specific sdk owner to double confirm
> 2. when is your last release for your sdk?
> 3. Looks there is only preview version for your swagger? and this preview version is existing for almost 1 year, do you have plan to have GA/stable version?

Thank you @akning-ms .

1. We don't have any specific requirements yet. We'll confirm with our PM team get their input on this. If there are any ARM standards we'd also like to just follow them for now.
2. We don't know when our last release will be. It will depend on our public preview / GA release dates.
3. Yes, we plan on moving towards public preview soon, and then release a GA version by the end of the year.

**Comment by akning-ms** [comment]
Hi @jorgbaca, As ARM already Signed off this PR. it should be fine for ARM side, My questions just confirm there is no impact for exist customer as removing these APIs is kind of breaking change for existing SDK

**Comment by jorgbaca** [comment]
> My questions just confirm there is no impact for exist customer as removing these APIs is kind of breaking change for existing SDK

@akning-ms correct, there is **no** impact for any customer. Thank you!

**Pull request merged**
