### PR TITLE
swagger ase 2021 06 01 stable preview release

### PR DESCRIPTION
**Pull request by sameerpatro**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/diagnosticProactiveLogCollectionSettings/default": {

You need to implement collection GET for this type, even though it's a singleton. This is required by the ARM resource model.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:717 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/diagnosticRemoteSupportSettings/default": {

Add a collection GET endpoint for this type as well.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:820 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

This should be 201. [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put).

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:899 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>             "name": "$filter",

Removing $expand will break back-level clients won't it? This isn't an ARM issue, but might be an SDK issue.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:3843 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/SystemData"

You should consider using common types for this (../../../../../common-types\resource-management\v2\types.json#definitions/systemData).

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:5080 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/SystemData"

Consider common-types

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:5487 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/SystemData"

Consider using common-types

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:5510 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "It Contains the version.",

Maybe explain this better.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7327 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "The v2 order id.",

Unless you also have a v1 order id in the same API, I'd suggest it's clearer just to describe this property as order id.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7363 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>             "Enabled",

Maybe Allowed, Disallowed is clearer as a consent value.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7578 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>         "include": {

Encoding collections in a string should be avoided: [https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html?q=comma#plcy004-avoid-encoding-property-values-as-comma-separated-values-csv](https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html?q=comma#plcy004-avoid-encoding-property-values-as-comma-separated-values-csv)

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8506 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "MinimumTimeStamp from where logs need to be collected",

Something like "Start of the timespan of the log collection" might be a little clearer.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8498 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>         "friendlyVersionNumber": {

This property should be clarified to explain what it is.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8697 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by mentat9** [comment]
>             "WAC",

Generally avoid using acroynms: better to expand this one.

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7645 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by sameerpatro** [comment]
> > ```
> >       "202": {
> > ```
> 
> This should be 201. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:899 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)



> Removing $expand will break back-level clients won't it? This isn't an ARM issue, but might be an SDK issue.

$filter is the correct param. $expand was mentioned wrongly in previous preview API which is corrected now. It will not break anything as the actual param was corrected and swagger was incorrect.

**Comment by sameerpatro** [comment]
> > ```
> >         "name": "$filter",
> > ```
> 
> Removing $expand will break back-level clients won't it? This isn't an ARM issue, but might be an SDK issue.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:3843 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

$filter is the correct param. $expand was mentioned wrongly in previous preview API which is corrected now. It will not break anything as the actual param was corrected and swagger was incorrect.

**Comment by sameerpatro** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/diagnosticProactiveLogCollectionSettings/default": {
> > ```
> 
> You need to implement collection GET for this type, even though it's a singleton. This is required by the ARM resource model.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:717 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks. I have created a task and will prioritize it. https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/9960372

**Comment by sameerpatro** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/diagnosticRemoteSupportSettings/default": {
> > ```
> 
> Add a collection GET endpoint for this type as well.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:820 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks. I have created a task and will prioritize it. https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/9960372

**Comment by sameerpatro** [comment]
> > ```
> >       "202": {
> > ```
> 
> This should be 201. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:899 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

This is by design and need an internal discussion. I will create a a

> > ```
> >         "Enabled",
> > ```
> 
> Maybe Allowed, Disallowed is clearer as a consent value.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7578 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks for your suggestion. This may include a contract changes. hence, it would be difficult to implement it now. We will take care while adding new params. Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >     "include": {
> > ```
> 
> Encoding collections in a string should be avoided: https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html?q=comma#plcy004-avoid-encoding-property-values-as-comma-separated-values-csv
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8506 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks for your suggestion. This may include a contract changes. hence, it would be difficult to implement it now. We will take care while adding new params. Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >         "WAC",
> > ```
> 
> Generally avoid using acroynms: better to expand this one.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7645 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks for your suggestion. This may include a contract changes. hence, it would be difficult to implement it now. We will take care while adding new params. Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >       "$ref": "#/definitions/SystemData"
> > ```
> 
> Consider using common-types
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:5487 in [0226bdc](https://github.com/Azure/azure-rest-api-specs/commit/0226bdcf1892aa6cdbcb96146190f89beeb48b0f). [](commit_id = [0226bdc](https://github.com/Azure/azure-rest-api-specs/commit/0226bdcf1892aa6cdbcb96146190f89beeb48b0f), deletion_comment = False)

Thanks for your suggestion. We have created a task and would prioritize the changes soon. Thanks
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11046043

**Comment by sameerpatro** [comment]
> > ```
> >       "description": "MinimumTimeStamp from where logs need to be collected",
> > ```
> 
> Something like "Start of the timespan of the log collection" might be a little clearer.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8498 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

I have done the changes, Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >       "description": "The v2 order id.",
> > ```
> 
> Unless you also have a v1 order id in the same API, I'd suggest it's clearer just to describe this property as order id.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7363 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

I have done the changes, Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >       "description": "It Contains the version.",
> > ```
> 
> Maybe explain this better.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7327 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

I have done the changes, Thanks.

**Comment by sameerpatro** [comment]
> > ```
> >     "friendlyVersionNumber": {
> > ```
> 
> This property should be clarified to explain what it is.
> 
> Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:8697 in [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff). [](commit_id = [3d35a75](https://github.com/Azure/azure-rest-api-specs/commit/3d35a755390d5f8935412e2d2807df3f271842ff), deletion_comment = False)

Thanks for your suggestion. We have created a task and would prioritize the changes soon. Thanks
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11046043

**Comment by mentat9** [comment]
>           "description": "It Contains the version.",

This is better, but I'd suggest you get these descriptions reviewed by documentation people. This won't block ARM signoff.

---
In reply to: [929644634](https://github.com/Azure/azure-rest-api-specs/pull/16120#issuecomment-929644634) [](http://example.com/codeflow?ancestors=929644634,929644634)

---
Refers to: specification/databoxedge/resource-manager/Microsoft.DataBoxEdge/preview/2021-06-01-preview/databoxedge.json:7327 in 3d35a75. [](commit_id = 3d35a755390d5f8935412e2d2807df3f271842ff, deletion_comment = False)

**Comment by sameerpatro** [comment]
Hi @RamyasreeChakka ,

We have already created the below tasks as it would be very difficult to take them immediately and requires a wider discussion and design reviews.

Task Items created:
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11046043
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11045909

Since the tasks are created, can we get a sign off for the above PR so we don’t miss the S360 timelines. Thanks for your help.

Thanks,
Sameer

**Comment by RamyasreeChakka** [comment]
> Hi @RamyasreeChakka Ramyasree Chakka FTE ,
> 
> We have already created the below tasks as it would be very difficult to take them immediately and requires a wider discussion and design reviews.
> 
> Task Items created: https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11046043 https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/11045909
> 
> Since the tasks are created, can we get a sign off for the above PR so we don’t miss the S360 timelines. Thanks for your help.
> 
> Thanks, Sameer

@sameerpatro As per our offline discussion, I understand your APIs are already in production and you are now adding them for swagger completeness fixing S360 issues. I will sign off now as you have to meet S360 deadline. I do see you added tasks to take care of the comments in future API versions. Please address them in next versions.

**Review by qwordy — APPROVED** [review]

**Pull request merged**
