### PR TITLE
Documentation improvements to Batch Swagger spec

### PR DESCRIPTION
**Pull request by matthchr**
This is in preparation for docs going to docs.msft.com

Note that these changes have already been reviewed by @mmacy, the document writer associated with my team.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/692)

### CODE REVIEW

**Comment by amarzavery** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[batch/2016-07-01.3.1/swagger/BatchService.json, line 43 at r1](https://reviewable.io:443/reviews/azure/azure-rest-api-specs/692#-KW4W2G0aqYpgNxq01jd:-KW4W2G0aqYpgNxq01je:b-xzuv3p) ([raw file](https://github.com/azure/azure-rest-api-specs/blob/271f5ba55f7d44b02bc100422c8480de6842c054/batch/2016-07-01.3.1/swagger/BatchService.json#L43)):*
> ```JSON
>             "type": "integer",
>             "format": "int32",
>             "description": "The maximum number of items to return in the response. A maximum of 1000 applications can be returned.",
> ```

Do you also want to provide a range as a constraint?
```
"minimum": 1,
"maximum": 1000
```

---

*[batch/2016-07-01.3.1/swagger/BatchService.json, line 53 at r1](https://reviewable.io:443/reviews/azure/azure-rest-api-specs/692#-KW4Wnfmb1XecVrFRaRR:-KW4Wnfmb1XecVrFRaRS:b-sl6jrq) ([raw file](https://github.com/azure/azure-rest-api-specs/blob/271f5ba55f7d44b02bc100422c8480de6842c054/batch/2016-07-01.3.1/swagger/BatchService.json#L53)):*
> ```JSON
>             "required": false,
>             "type": "integer",
>             "format": "int32",
> ```

same as above. Do you think specifying minimum and maximum would be useful? If so, then please provide them.

---

*[batch/2016-07-01.3.1/swagger/BatchService.json, line 282 at r1](https://reviewable.io:443/reviews/azure/azure-rest-api-specs/692#-KW4XQuKzUOiUrcpo03p:-KW4XQuKzUOiUrcpo03q:b-ble3w6) ([raw file](https://github.com/azure/azure-rest-api-specs/blob/271f5ba55f7d44b02bc100422c8480de6842c054/batch/2016-07-01.3.1/swagger/BatchService.json#L282)):*
> ```JSON
>             "name": "maxresults",
>             "x-ms-client-name": "maxResults",
>             "default": 1000,
> ```

same as above. A general comment for all such scenarios.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/azure/azure-rest-api-specs/692)*

**Comment by matthchr** [comment]
@amarzavery I've done so, will send an update

**Comment by matthchr** [comment]
@amarzavery Updated

**Comment by matthchr** [comment]
Looks like Travis timed out for some reason.  @amarzavery Can you take a look?

**Pull request merged**
