### PR TITLE
Update Microsoft.Sql ARM API with "format: arm-id" where appropriate and x-ms-secret where appropriate

### PR DESCRIPTION
**Pull request by matthchr**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify: Update existing version to fix Swagger quality issue. Not sure if it's actually flagged in S360 or not.
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by matthchr** [comment]
@ericshape can you review this?

**Comment by matthchr** [comment]
Note that the breaking change tool incorrectly classifies `string` with no format to `string` with `format: "arm-id"` as breaking, but it is not actually breaking.

**Comment by matthchr** [comment]
I investigated the ModelValidation failures and they are either:
1. Issues with LROs which I didn't change.
2. Issues with samples being flagged as returning a secret when the GET returns `"storageAccountAccessKey":""`. This is the real behavior of the API so I believe the sample is correct. _Technically_ the key is not returned (it's always empty string), so possibly the ModelValidator is overly sensitive here? Or else possibly the SQL server should be updated in a future version to omit the `storageAccountAccessKey` entirely in the response body. In any case, the samples are currently correct so I didn't change them.

**Comment by matthchr** [comment]
@raych1 - can you confirm that the `x-ms-secret` annotation addition is safe, even in existing Swagger? I believe it is, as it doesn't change generated SDK types or anything like that. The breaking change detection seems fine with it, but just wanna triple check.

**Review by ericshape — APPROVED** [review]
LGTM

after @raych1 answer the question from the author, we could merge it to main branch.

**Comment by ericshape** [comment]
Interesting. Why do we meet this spelling error issue?

**Review by raych1 — CHANGES_REQUESTED** [review]
Can you fix spell check errors?

**Comment by raych1** [comment]
> I investigated the ModelValidation failures and they are either:
> 
> 1. Issues with LROs which I didn't change.
> 2. Issues with samples being flagged as returning a secret when the GET returns `"storageAccountAccessKey":""`. This is the real behavior of the API so I believe the sample is correct. _Technically_ the key is not returned (it's always empty string), so possibly the ModelValidator is overly sensitive here? Or else possibly the SQL server should be updated in a future version to omit the `storageAccountAccessKey` entirely in the response body. In any case, the samples are currently correct so I didn't change them.

If a property is annotated as `x-ms-secret`: true, then it should not return in response. If the response still has it even with empty value, please don't have it annotated as `x-ms-secret`: true.

**Comment by raych1** [comment]
@ericshape , I saw you approved this PR but still want to confirm with you will these chagnes be overridden next time when swagger is re-generates?

**Comment by matthchr** [comment]
> If a property is annotated as x-ms-secret: true, then it should not return in response. If the response still has it even with empty value, please don't have it annotated as x-ms-secret: true.

Isn't the more important determination: "Are these things secrets"? They definitely _are_ secrets.

**Comment by ericshape** [comment]
Hi @raych1, after an offline discussion with @matthchr, we will hold this PR for one more week. 
Once https://github.com/Azure/azure-rest-api-specs/pull/22285 and 2022-08-01-preview are merged to the main branch, @matthchr will rebase this PR and add related tags to the latest swagger files. 

We will create a work item to add these tags in the upstream SQL repo and make sure they are auto-generated in the next API version release.

**Comment by raych1** [comment]
> > If a property is annotated as x-ms-secret: true, then it should not return in response. If the response still has it even with empty value, please don't have it annotated as x-ms-secret: true.
> 
> Isn't the more important determination: "Are these things secrets"? They definitely _are_ secrets.

So, the fix will be in server side to remove them in response.

**Comment by matthchr** [comment]
I have updated this PR and fixed the x-ms-secret model validation errors (fixed the samples).

The other model validation errors and spelling errors I believe are unrelated to this PR.

**Comment by matthchr** [comment]
@ericshape I will send a second PR targeting the new preview version once it merges and this PR is merged. Do you have any objection to this merging now?

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
@matthchr , please fix `spellCheck` error. @ericshape , can you review again as some more commits made after you approved?

**Review by ericshape — APPROVED** [review]
LGTM

[1023 - TypeFormatChanged](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1023.md) are expected

**Comment by ericshape** [comment]
> @matthchr , please fix `spellCheck` error. @ericshape , can you review again as some more commits made after you approved?

the spellCheck error could be fixed by rebase/sync with latest main branch

**Comment by matthchr** [comment]
I rebased which in theory should fix the spellcheck errors

**Pull request merged**
