### PR TITLE
[Hub Generated] Review request for Microsoft.StorageSync to add version 2019-02-01

### PR DESCRIPTION
**Pull request by anpint**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/Azure/azure-rest-api-specs/dev-storagesync-Microsoft.StorageSync-2019-02-01).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by ankushbindlish2 — APPROVED** [review]

**Comment by veronicagg** [comment]
@anpint thanks for using OpenAPI Hub to create this PR, are you expecting to make more changes on the specs? or is it an api-version update with the same content?

**Review by veronicagg — CHANGES_REQUESTED** [review]
see question above.

**Comment by anpint** [comment]
> @anpint thanks for using OpenAPI Hub to create this PR, are you expecting to make more changes on the specs? or is it an api-version update with the same content?

We will be making additional changes to the specs. I was advised by my teammate to first create an API version update with the same content, and follow-up with another PR containing changes to the protocol.

**Comment by veronicagg** [comment]
@anpint in this case, would you want to work against a branch for your team in the repo? We can create one for you and we could review PRs against it, if you'd like. You can put all your work there, until you're ready to send it to master. 
This PR is currently against master branch and we should not merge partial work to master. 
If you're going to be the only person working on the changes, you can also keep adding commits to this PR and add [Do not merge] or [Work in Progress] to the title of the PR. 
If you have more questions, feel free to let me know. 
Thanks!

**Comment by anpint** [comment]
> @anpint in this case, would you want to work against a branch for your team in the repo? We can create one for you and we could review PRs against it, if you'd like. You can put all your work there, until you're ready to send it to master.

OpenApi Hub created this branch for us: dev-storagesync-Microsoft.StorageSync-2019-02-01. Are you suggesting that we could create PRs against that branch instead of master for incremental work?

> This PR is currently against master branch and we should not merge partial work to master.
> If you're going to be the only person working on the changes, you can also keep adding commits to this PR and add [Do not merge] or [Work in Progress] to the title of the PR.

This is my first time going through this process, and my team member who did this before (ankushbindlish2) suggested that we follow this procedure:
1. Create a PR with the new API version as a copy of the previous API version. (This is the current PR)
2. Create a second PR with the actual protocol changes.

The intention of this approach is to make it easier to review the actual protocol changes, because in this current PR, all files for the 2019-02-01 API version are being treated as new files, even though it's just a copy of the previous API version, so it will be harder to see the incremental change between the new API version, and the previous API version.

**Comment by veronicagg** [comment]
@anpint I believe we clarified this offline. If you create a branch with the updates to the api-version, that's great, then send PRs to that branch for review, so once your work is completed you can have 1 PR against master approved and merged. If you have more questions, feel free to let me know.

**Comment by veronicagg** [comment]
@anpint When you're done with changes in this PR, just let me know, thanks!

**Comment by anpint** [comment]
@veronicagg The changes for this protocol have been finalized.

**Comment by veronicagg** [comment]
@anpint thanks, could you please review the CI failures for linter? Thanks!

**Comment by anpint** [comment]
> @anpint thanks, could you please review the CI failures for linter? Thanks!

Sorry for not noticing the failures before. I wanted to define some properties in the protocol as both readonly and required, and it looks like that's not supported. I kept them as readonly.

**Comment by veronicagg** [comment]
Change looks good, this PR is composed of the new api-version with an already reviewed commit plus a few changes to the properties.
Do you still need to wait on afedyashov for review?
Are the APIs deployed? If so, I can approve and merge this PR. 
Thanks!

**Comment by anpint** [comment]
> Change looks good, this PR is composed of the new api-version with an already reviewed commit plus a few changes to the properties.
Yes, that's correct.

> Do you still need to wait on afedyashov for review?
No, we don't need to wait. Initially he was going to add some changes to the protocol, but we dicided not to make further changes.

> Are the APIs deployed? If so, I can approve and merge this PR.
Can you clarify this? Do you require having the 2019-02-01 API version already supported by our RP in production? This API version is currently making its way through our release pipeline, so it will be a few weeks before it hits production. As a general process, I would expect that swagger should be the first step in creating a new API version (so that the changes go through proper approvals before we implement them in our service). Is that not the case?

**Comment by veronicagg** [comment]
@anpint It's correct that the swagger is the first step, but we should have the APIs deployed in production before merging the PR. The reason is that once a swagger is merged in master, an SDK can get generated right away, and if the APIs are not available the SDKs won't work for customers. Hope that makes sense. 
Let me know when the APIs are deployed and I can merge this PR. Thanks!

**Comment by anpint** [comment]
> @anpint It's correct that the swagger is the first step, but we should have the APIs deployed in production before merging the PR. The reason is that once a swagger is merged in master, an SDK can get generated right away, and if the APIs are not available the SDKs won't work for customers. Hope that makes sense.
> Let me know when the APIs are deployed and I can merge this PR. Thanks!

Ok, I understand now. I'll tag this PR as "Awaiting Deployment" and update it again once we have the new API version in production.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5596 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5596/commits/007d15146f362eee3b38029e6723bf2a8c808693

**Comment by anpint** [comment]
The service code that supports this new API version is now in our Canary regions, so we would like to go ahead and complete the PR. We will be rolling out the service to all production regions in the next few weeks.

**Comment by veronicagg** [comment]
@anpint ok, great. Due to my explanation above, we should not merge and release SDKs until the APIs are in production, please let me know when that's the case, for PR merge.

**Comment by ankushbindlish2** [comment]
@veronicagg  We are already LIVE in FLIGHT regions. Please merge this change.  All SDKS would be publish only after ALL regions are LIVE.

**Review by veronicagg — APPROVED** [review]

**Pull request merged**
