### PR TITLE
[Microsoft.IoTCentral/iotApps] Removal of legacy S1 SKU, S360 Fixes, newer RP API version 2021-06-01

### PR DESCRIPTION
**Pull request by poanchen**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [x] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by poanchen** [comment]
@erich-wang PTAL and not merge the PR just yet thanks

**Comment by poanchen** [comment]
ping again.  @erich-wang PTAL. Please advice if any suggestion here?

**Comment by erich-wang** [comment]
@poanchen , could you please read and follow the section `ARM API Review Checklist` in the description? Thanks.

**Comment by poanchen** [comment]
okay @erich-wang read and updated thank!

**Comment by erich-wang** [comment]
If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

**Comment by poanchen** [comment]
There is no urgency to merge this code to master branch as our changes hasn't make it to prod yet, however, what I expect is some ARM guidance/feedback on this PR so that we don't get any surprise later on if we want to merge. Simply put, we just need some feedback or approval of the PR that is all, thank you!

**Comment by poanchen** [comment]
@erich-wang please let us know if you have any feedback to this PR. Our code changes + arm manifest is already in prod. We have also tested the newly generated SDK against both canary + prod. So we should be good to merge this swagger changes to add a new RP api version 2021-06-01. As we will have other changes coming later on, we will not trigger an update to SDK until down the road. Thanks.

**Comment by poanchen** [comment]
@akning-ms  please let us know how we can move forward and close this PR thanks

**Comment by akning-ms** [comment]
> @akning-ms please let us know how we can move forward and close this PR thanks

Hi @poanchen, Your PR is not ready for merge on below point:
1. ARM sign off refer to: ARM API Review Checklist in first comment
2. Breaking change review board approval, refer to: https://github.com/Azure/azure-rest-api-specs/pull/14311#issuecomment-894965326
due to below:

❌ 1019 - RemovedEnumValue | The new version is removing enum value(s) 'F1, S1' from the old version.
New: Microsoft.IoTCentral/stable/2021-06-01/iotcentral.json#L540:9
Old: Microsoft.IoTCentral/stable/2018-09-01/iotcentral.json#L523:9

**Comment by jorgecotillo** [comment]
Let us know if this PR still needs some feedback, it's been open for quite some time

**Comment by poanchen** [comment]
@jorgecotillo We are in the process of getting our breaking changes approved by the ARM team. Will reach out once that is approved and we should be able to merge this.

**Comment by poanchen** [comment]
@jorgecotillo @akning-ms 

Breaking changes already got approved. Please merge this PR whenever you guys see this. Thanks tons!

**Comment by poanchen** [comment]
ping again here
@jorgecotillo @akning-ms 

let me us know what else we need to do thanks!

**Comment by akning-ms** [comment]
Hi @poanchen, you may need ping ARM on call person to review if urgent as below guideline:
 If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

**Comment by poanchen** [comment]
@jorgecotillo  @akning-ms 

We don't have urgency to merge this PR but we do want to get this PR moving forward. Please take a look when you guys have time. Thanks!

**Review by j5lim — APPROVED** [review]
Approved from ARM side.

**Comment by poanchen** [comment]
@jorgecotillo  @akning-ms 

Now that we also got the ARM team approval. Can we move this forward?

**Pull request merged**
