### PR TITLE
[SQL] Databases API - propagate changes on newer versions

### PR DESCRIPTION
**Pull request by ostojicb**
This PR is an attempt to bring few swagger files to a consistent state
Here https://github.com/Azure/azure-rest-api-specs/pull/18209 we introduced changes to the older version of API (that's currently in use) - but it wasn't propagated to newer versions. So, when we eventually bump the targeted version, we'd ignore these changes.

### CODE REVIEW

**Review by ostojicb — COMMENTED** [review]
that original PR also had some `description` changes, but it looks just like it's shuffling the order of errors, correct me if i'm wrong @viparek

**Review by ericshape — APPROVED** [review]
LGTM 
please request breaking change review done.

**Comment by ostojicb** [comment]
> LGTM please request breaking change review done.

done 👍

**Comment by raych1** [comment]
@ArcturusZhang @dw511214992 @msyyc , can you check the breaking change to SDK?

**Review by raych1 — APPROVED** [review]

**Pull request merged**
