### PR TITLE
Adding ManagedInstanceVulnerabilityAssessments and ServerVulnerabilit…

### PR DESCRIPTION
**Pull request by yaakoviyun**
…yAssessments

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Comment by yaakoviyun** [comment]
@talhers  @jaredmoo

**Comment by yaakoviyun** [comment]
@hovsepm It seems that "SDK Generation - Node " job is stuck.
How can I reset it?

**Comment by lmazuel** [comment]
@hovsepm OOF sick for the rest of the week, reassign PR

**Review by annatisch — APPROVED** [review]

**Comment by annatisch** [comment]
LGTM @yaakoviyun - Do you want this merged straight away?

**Comment by yaakoviyun** [comment]
Yes please.
________________________________
מאת: annatisch <notifications@github.com>
‏‏נשלח: יום שישי 09 נובמבר 2018 00:14:46
‏‏אל: Azure/azure-rest-api-specs
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-rest-api-specs] Adding ManagedInstanceVulnerabilityAssessments and ServerVulnerabilit… (#4416)


LGTM @yaakoviyun<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaakoviyun&data=02%7C01%7Cyaiyun%40microsoft.com%7Cc57ce00cd0644e856fb808d645c797bd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773120876829343&sdata=CKjqIw5pxV570WkwCwSRLUU9KhbW6F1%2FkvW1geHgKMs%3D&reserved=0> - Do you want this merged straight away?

**Pull request merged**
