### PR TITLE
[Hub Generated] Review request for Microsoft.Network to add version stable/2019-03-01

### PR DESCRIPTION
**Pull request by disreedh**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/disreedh/azure-rest-api-specs/disreedh%2Fdev-frontdoor-Microsoft.Network-2019-03-01...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
@disreedh just noticed, this pr is to master, should be to network release branch, could you pls retarget?

**Comment by number213** [comment]
@zikalino I don't think it should go to network release branch since it's a change in `specification/frontdoor`
@MikhailTryakhov please take a look

**Comment by MikhailTryakhov** [comment]
frontdoor lives it's own lives :) so it can be merged whatever they want

**Comment by yungezz** [comment]
Hi @zikalino is this PR ok to merge? if yes, can you pls merge it?

**Review by zikalino — APPROVED** [review]

**Pull request merged**
