### PR TITLE
Remove webhook activity

### PR DESCRIPTION
**Pull request by arsunda**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by arsunda** [comment]
Removing webhook activity which was added last week, as it is still pending some testing and we want to delay the release till the next cycle

**Review by hvermis — APPROVED** [review]

**Comment by hvermis** [comment]
@praries880 These changes were made too soon, and we need to remove them for our current SDK release. Can you please merge them as soon as you can?

**Comment by hvermis** [comment]
To clarify, this a new activities that hasn't been released yet.

**Comment by praries880** [comment]
@arsunda Has the .net SDK or (any other SDK) been released with these properties in it?

**Comment by salameer** [comment]
@arsunda has the .NEt SDK been released already?

**Comment by hvermis** [comment]
@salameer No, these are brand new. We don't want them in the release that we are about to do, hence want them removed from swagger. We will add them for our next release.

**Comment by salameer** [comment]
Please note that by sending this Pull request to us you are greenlighting releases of all the SDKs and docs on this swagger and rolling back is not easy or even possible. especially if your adding to the Stable folder

ARM please review this

**Comment by salameer** [comment]
If your service is not live you shouldn't publish their spec

**Comment by hvermis** [comment]
It was added by mistake. The feature is still in testing stage.

**Comment by hvermis** [comment]
@praries880, @salameer  Please merge this as soon as you can as this is blocking our SDK release.

**Comment by arsunda** [comment]
@praries880  @salameer  This PR was checked in last week ( https://github.com/Azure/azure-rest-api-specs/pull/5007 ) . SDK release has not gone out yet, it is scheduled to go out next week. We are still pending some testing results so we do not want release it yet. We want to revert this change so that it does not go into the current release cycle.

**Review by KrisBash — APPROVED** [review]
Given the conversation context, signing off for ARM

**Comment by praries880** [comment]
@arsunda 
We take breaking changes quiet seriously. Even though this is not consumed anywhere, removing properties, API etc form stable swaggers is considered a breaking change. We are merging this change in this once instance but next time onwards cases like this will be reported to the ARM leadership.

**Pull request merged**
