### PR TITLE
{AzureSynapse} Adding sparkr enum support to SparkStatementOption

### LINKED ISSUE #25278: Add SparkR Support for SparkJob
Hello,

As described on this issue - https://github.com/Azure/azure-sdk-for-python/issues/27834
Azure Synapse Spark package support SparkR, But there is no information in enums to tell that. 

When passing the `kind = 'sparkr'` to Api, it does start a SparkR job. 

Can you please update the ENUMs and Add `sparkr` to the SparkStatementOption?

This is where we need chnage - 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/synapse/data-plane/Microsoft.Synapse/stable/2020-12-01/sparkJob.json#L1542

### PR DESCRIPTION
**Pull request by navba-MSFT**
fixes https://github.com/Azure/azure-rest-api-specs/issues/25278

Azure Synapse Analytics provides built-in R support for Apache Spark. As part of this, data scientists can leverage Azure Synapse Analytics notebooks to write and run their R code. This also includes support for [SparkR](https://spark.apache.org/docs/latest/sparkr.html)

Reference: https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-r-language

But there is no information in SparkStatementOption enums to tell that. so when passing the kind = 'sparkr' to Api, it does start a SparkR job.

this PR adds this enum to this REST API: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/synapse/data-plane/Microsoft.Synapse/stable/2020-12-01/sparkJob.json#L1542

# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by navba-MSFT** [comment]
@wonner @yanjungao718 Could you please review this PR ?

**Comment by navba-MSFT** [comment]
> @wonner @yanjungao718 Could you please review this PR ?

@wonner @yanjungao718 Please let me know if you had any updates on this.

**Comment by wonner** [comment]
@navba-MSFT please go through the breaking change review, thanks.

**Comment by navba-MSFT** [comment]
@wonner I have been asked by the breaking change review board to create a new `api-version` for the enum change. Could you please confirm if it needs a new api-version for this ?

**Comment by navba-MSFT** [comment]
> @wonner I have been asked by the breaking change review board to create a new `api-version` for the enum change. Could you please confirm if it needs a new api-version for this ?

@wonner Any updates on this ?

**Pull request closed without merging**
