### PR TITLE
Use singleton enum pattern instead of hardcoded value in paths.

### PR DESCRIPTION
**Pull request by jaredmoo**
This seems to be needed in order for `autorest --azureresourceschema` to generate the schema for that path.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
@nathannfan

**Comment by fearthecowboy** [comment]
Arg! 

We just had a conversation about this pattern yesterday in our standup.

If AutoRest isn't doing the right thing, maybe we should fix it, rather than creating single-value enums. 

(I'm assuming that you didn't necessarily want an enum here just for fun?)

I'll look into that this morning

**Comment by jaredmoo** [comment]
No I didn't do it for fun, although removing a linter warning is also nice.

**Comment by fearthecowboy** [comment]
Looked at the code. 

I see what it's doing. In order to conjure up things that it thinks are resources, it looks for parameterized URLS where the last segment is a `/{parameter}` and figures it out from that.

Hmmm. I hate to have to use a single-value enum for this, but I don't see an easy way of magicking up an unparameterized child resource.

Still looking ... please stand by...

**Comment by fearthecowboy** [comment]
I got nothing. 

I guess we'll have to take this at this, as there is no way to generate the schema otherwise. (sigh!)

**Review by fearthecowboy — APPROVED** [review]

**Comment by jaredmoo** [comment]
Thanks!

**Pull request merged**
