### PR TITLE
Release migrate microsoft.migrate/2023 09 09 preview

### PR DESCRIPTION
**Pull request by dmohanta**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information
Existing PR which is already approved:
[Release microsoft.migrate 2023-09-09-preview api versiom by dmohanta · Pull Request #30506 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/30506/files#diff-082d114eea0a501f98601de0e2ad319db2a01dc0fc39cdbbb905bd40fbbcbc69)
The initial PR was based on 2023-04-01-preview.
In the current state, new api version 2023-05-01-preview was made public preview, hence creating a new PR with base as 2023-05-01-preview

2 Additional properties which added on top of the existing PR are the following:
1. facilitiesCost under CostDetails.Properties:
"facilitiesCost": {
          "type": "number",
          "format": "float",
          "description": "The facilities cost.",
          "readOnly": true
}

2. cpuHeadroom under AvsAssessment.Properties
"cpuHeadroom": {
          "type": "number",
          "format": "float",
          "description": "CPU Headroom"
        },

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in https://github.com/Azure/azure-rest-api-specs/pull/28274

**Comment by ramoka178** [comment]
>     "ManagementSettings": {

intentional to miss vsphereManagementSettings ? Breaking changes are ok I assume ?

---
Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20107 in ccbd97d. [](commit_id = ccbd97de0667bd5c73bd670e23708ff7ba55a9fc, deletion_comment = False)

**Comment by ramoka178** [comment]
>           "description": "CPU Headroom"

Please update the description what does this float number represent. a % or anything else.

---
Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:12091 in ccbd97d. [](commit_id = ccbd97de0667bd5c73bd670e23708ff7ba55a9fc, deletion_comment = False)

**Comment by ramoka178** [comment]
>           "description": "The facilities cost.",

Update description to provide more info. cost in USD or anything else.

---
Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:18040 in ccbd97d. [](commit_id = ccbd97de0667bd5c73bd670e23708ff7ba55a9fc, deletion_comment = False)

**Comment by ramoka178** [comment]
>           "description": "The total Azure arc enabled on-premises cost assuming all on-premises infra is arc enabled.",

mentioning currency needed or will the number be adjusted based on user's geo or something ?

for all cost related fields.

---
Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20977 in ccbd97d. [](commit_id = ccbd97de0667bd5c73bd670e23708ff7ba55a9fc, deletion_comment = False)

**Comment by ramoka178** [comment]
>         "futureEsuSavingsFor4YearsIncludingAzureArc": {

this seems to be tightly bound to 4 years. what happens when the time window changes? 

Can you have two fields, stating, futureEsuSavingsIncludingAzureArc and
futureEsuSavingsIncludingAzureArcPeriodInYears 

This might make the API future proof if the time period of 4 years changes.

---
Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20986 in ccbd97d. [](commit_id = ccbd97de0667bd5c73bd670e23708ff7ba55a9fc, deletion_comment = False)

**Comment by ramoka178** [comment]
Please fix the Swagger Avocado failures as well.

**Comment by dmohanta** [comment]
> > ```
> > "ManagementSettings": {
> > ```
> 
> intentional to miss vsphereManagementSettings ? Breaking changes are ok I assume ?
> 
> Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20107 in [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc). [](commit_id = [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc), deletion_comment = False)

Yes, this is intentional and we have the Breaking Change approval for the same,

**Comment by dmohanta** [comment]
> > ```
> >       "description": "The total Azure arc enabled on-premises cost assuming all on-premises infra is arc enabled.",
> > ```
> 
> mentioning currency needed or will the number be adjusted based on user's geo or something ?
> 
> for all cost related fields.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20977 in [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc). [](commit_id = [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc), deletion_comment = False)

Business case takes currency as an input and the values as adjusted as per the selected currency. Hence no currency needed here.

**Comment by dmohanta** [comment]
> > ```
> >     "futureEsuSavingsFor4YearsIncludingAzureArc": {
> > ```
> 
> this seems to be tightly bound to 4 years. what happens when the time window changes?
> 
> Can you have two fields, stating, futureEsuSavingsIncludingAzureArc and futureEsuSavingsIncludingAzureArcPeriodInYears
> 
> This might make the API future proof if the time period of 4 years changes.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:20986 in [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc). [](commit_id = [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc), deletion_comment = False)

This is following the existing naming convention of another existing property: "esuSavingsFor4years".

**Comment by dmohanta** [comment]
> Please update the description what does this float number represent. a % or anything else.

Updated to "The facilities cost related to hosting customer workloads in a datacenter."

**Comment by dmohanta** [comment]
> > ```
> >       "description": "CPU Headroom"
> > ```
> 
> Please update the description what does this float number represent. a % or anything else.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:12091 in [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc). [](commit_id = [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc), deletion_comment = False)

updated.
"Percentage of CPU capacity reserved for processing additional workloads."

**Comment by dmohanta** [comment]
> > ```
> >       "description": "The facilities cost.",
> > ```
> 
> Update description to provide more info. cost in USD or anything else.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.Migrate/AssessmentProjects/preview/2023-09-09-preview/migrate.json:18040 in [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc). [](commit_id = [ccbd97d](https://github.com/Azure/azure-rest-api-specs/commit/ccbd97de0667bd5c73bd670e23708ff7ba55a9fc), deletion_comment = False)

Updated.
"The facilities cost related to hosting customer workloads in a datacenter."

**Comment by dmohanta** [comment]
> Please fix the Swagger Avocado failures as well.

The "MISSING_APIS_IN_DEFAULT_TAG" error is an existing issue.

**Review by v-anishrao — APPROVED** [review]

**Pull request merged**
