### PR TITLE
Add All Cosmos DB API Versions

### PR DESCRIPTION
**Pull request by shurd**
Cosmos DB allows several API versions that are identical to the "2015-04-08" version currently documented. This change adds swagger files for all of those versions to improve documentation. These files and examples are just duplicates of the other version.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by raych1** [comment]
@qiaozha , can you please light on the breaking change failures?

**Comment by raych1** [comment]
@shurd , does cosmos db service has these old api-version released? Does it have same version of SDK released? The readme.md is supposed to have the old api-version swagger referenced.

**Comment by shurd** [comment]
@raych1 Our RP does support these API versions. We created a new API version each time we had a large change in our service, but we also continued to support all schemas in all versions. We only released the one swagger version "2015-04-08" since there is no functionality difference between the API versions before "2019-08-01". The ARM team requested that we publish a swagger for all API versions we support so that auto-generated documentation lists the available API versions. We do not plan on releasing an SDK for any of these new versions because the SDK for "2015-04-08" is sufficient. I will add references to the new versions in the README file.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
