### PR TITLE
Migration APIs

### PR DESCRIPTION
**Pull request by lshai06**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
This PR captures the APIs for migration that will be exposed by Azure Site Recovery (ASR). ASR already exposes APIs for replication/failover, and we have tried to adhere closely to the same while adding support for migration as a scenario.
The overall model hierarchy of (vault -> fabric -> container) has been retained, and migration item will now fall below container. New APIs added for migration items are in line with the existing replication protected items APIs. Migration items are created by an Enable operation. Once a migration item is created, we can invoke a test migrate and cleanup on it, or a migrate and complete migration on it, to confirm that the migration is completed. The migration item can be removed/force removed by a Disable/Delete operation.
We are also exposing the put for ReplicationRecoveryServicesProviders, which we had missed earlier along with its get and delete.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@lshai06 this introduces breaking changes in a stable API version, can you please explain?

**Comment by lshai06** [comment]
@jhendrixMSFT This is not a breaking change, as none of these properties were used earlier, and was added specifically for migration scenarios, and we are just lighting up Migration as a scenario. A few of the changes had got inadvertently merged to master earlier.

**Comment by lshai06** [comment]
@jhendrixMSFT It appears that the changes are not showing up correctly in the "Files changed" tab. Please refer the CodeFlow review to check the diff of the changes. These are new APIs we are adding for migration, none of the existing APIs will break. 
Review: http://codeflow/extensions/launcher.html?server=https:%2f%2fmicrosoft.visualstudio.com%2f&projectId=4e9ae0d6-7a8d-4dd3-91c8-887ebe98162e&reviewId=2591603&projectshortname=HSDP

**Comment by jhendrixMSFT** [comment]
Changing type names introduces breaking changes, you can see that in the PR generated for the Go SDK https://github.com/Azure/azure-sdk-for-go/pull/3262/files, specifically see models.go.
Regarding the new APIs, have they been reviewed by ARM yet?

**Comment by lshai06** [comment]
@jhendrixMSFT
 For ARM review we have started a mail thread with @ravbhatnagar 

These are new APIs we are adding for migration, none of the existing APIs will break. There are naming changes for some models/properties but none of these will be breaking changes as they were not being used before and are being solely used by the new migration scenarios that we are introducing with these APIs. These models got merged inadvertently in previous PRs but they were not being used in any of the existing scenarios of ASR.

Model: IdentityInformation
•	Renamed to IdentityProviderDetails
•	Removed properties identityProviderType, certificateThumbprint
 
Model: RecoveryServicesProviderProperties
•	Removed property identityDetails of type IdentityInformation
•	Added properties authenticationIdentityDetails and resourceAccessIdentityDetails, both of type IdentityProviderDetails

Model: VMwareCbtPolicyCreationInput
•	Renamed property recoveryPointHistory to recoveryPointHistoryInMinutes

Model: VmwareCbtPolicyDetails
•	Renamed property recoveryPointHistory to recoveryPointHistoryInMinutes
•	Removed property recoveryPointThresholdInMinutes

Model: VMwareV2FabricCreationInput	
•	Removed properties keyVaultUrl, keyVaultResourceArmId
•	Added properties vmwareSiteId, migrationSolutionId

Model: VMwareV2FabricSpecificDetails	
•	Removed properties rcmServiceEndpoint, keyVaultUrl, keyVaultResourceArmId
•	Added property vmwareSiteId, migrationSolutionId

**Comment by simongdavies** [comment]
@ravbhatnagar have you started a review on this yet?

**Comment by ravbhatnagar** [comment]
Review meeting done. Service team will address some feedback.

**Comment by jhendrixMSFT** [comment]
@ravbhatnagar has this been fixed per the meeting?

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@daschult do you want to take a look at the typescript gen failure?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
