### PR TITLE
databricks: switching `parameters` to be a proper struct

### PR DESCRIPTION
**Pull request by mbfrahry**
This is a continuation of #6917 

From #6917 
```
As a part of the provisioning process, Databricks Clusters allow users to override certain values via a parameters block. Since there appears to be a fixed list of these:

customPrivateSubnetName, customPublicSubnetName, customVirtualNetworkId, enableNoPublicIp, relayNamespaceName, storageAccountName, storageAccountSkuName, vnetAddressPrefix, resourceTags, amlWorkspaceId.

from a usability perspective this would match other SDK's if these values were exposed as a native struct/class depending on the language, rather than being a generic dictionary; as such this PR changes parameters to a struct rather than a dictionary.
```

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@mbfrahry 

Please add code owner to reviewer. Also please try to pass CI as well. If you think any validation is not your fault please raise it.

**Review by KrisBash — APPROVED** [review]
I'm assuming that this is not breaking as the newly defined properties match the complete list of properties supported by the service previously? With that in mind, signing off. If this is breaking ,please expose in a new API version

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by mbfrahry** [comment]
@weidongxu-microsoft @KrisBash thanks for reviewing - the tests pass now 👍

**Pull request merged**
