### PR TITLE
[DO NOT MERGE INTO MASTER] Duplicate containerservice API version 10-01 into 11-01

### PR DESCRIPTION
**Pull request by norshtein**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

This PR add a new API version 2019-11-01. This PR just duplicates 2019-10-01 and doesn't add new property . PRs for adding new property will be send out later.
**Please DO NOT MERGE this PR into master branch, we need to create a new dev branch and merge it into dev branch**.

### CODE REVIEW

**Comment by norshtein** [comment]
Hi @anuchandy , could you help create a new dev branch and review the PR?

**Comment by norshtein** [comment]
Could other admins @jhendrixMSFT @zikalino have a look on this?

**Comment by anuchandy** [comment]
@norshtein Usually we do reviews in PR to master, including ARM review. We merge the PR once it receives sign-off from all parties and api-version gets deployed to at least one production region.

**Comment by ravbhatnagar** [comment]
Why is a new api-version being spun if no changes? Are there any behavior changes on the APIs?

**Comment by norshtein** [comment]
@ravbhatnagar This is the initial PR. Later feature owners will send PR to apply their changes in API.

**Comment by ravbhatnagar** [comment]
pretty old PR, removing ARM review labels. please re-add if you need ARM review.

**Comment by norshtein** [comment]
Legacy PR, closed.

**Pull request closed without merging**
