### PR TITLE
[Agrifood] Adding Nov 2023 Preview API version

### LINKED ISSUE #24736: [Microsoft Azure Data Manager for Agriculture - Microsoft Azure Data Manager for Agriculture] API Review
New API Review meeting has been requested.

**Service Name**: Microsoft Azure Data Manager for Agriculture - Microsoft Azure Data Manager for Agriculture
**Review Created By**: Bhargav Kansagara @bhargav-kansagara
**Review Date**: 08/01/2023 01:00 PM PT
**Onboarding Record**: https://dev.azure.com/azure-sdk/Release/_workitems/edit/12545
**PR**: 
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: 

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=f743922c-e41e-ee11-9cbe-000d3a341d27)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by bhargav-kansagara**
# Data Plane API - Pull Request
- Adding APIs for reference datasets, chemical products and farm equipment
- Updating APIs for crops and crop products

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue: https://github.com/Azure/azure-rest-api-specs/issues/24736

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2023-06-01-preview/agfood.json
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/24736

### CODE REVIEW

**Review by mikekistler — CHANGES_REQUESTED** [review]
I found a few more minor problems.

- invalid-ref error '#/definitions/DataProvider' does not exist

- Parameter name "$maxPageSize" should not begin with '$' or '@'.

- Parameter name "$skipToken" should not begin with '$' or '@'.

- A post operation should not consume 'application/merge-patch+json' content type.
    - Datasets_Publish
    - Datasets_AuthorizeAccess

- A get or delete operation must not accept a body parameter.
    - Datasets_RemoveAccess

- DatasetRecords_CreateOrUpdate response body schema `ChemicalProducts` does not match request body schema `DatabaseRecord`

**Review by mikekistler — CHANGES_REQUESTED** [review]
Thank you for the fixes. There are two other small but important changes I think are needed.

- Datasets_RemoveAccess - if you need to pass a request body for this operation then it should be a POST rather than a DELETE method.

- the maxPageSize query parameter (on 52 different operations) is described as "Maximum number of items needed (inclusive)", which by the [Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#query-options) should instead be called "top".

**Comment by bhargav-kansagara** [comment]
> Thank you for the fixes. There are two other small but important changes I think are needed.
> 
> * Datasets_RemoveAccess - if you need to pass a request body for this operation then it should be a POST rather than a DELETE method.
> * the maxPageSize query parameter (on 52 different operations) is described as "Maximum number of items needed (inclusive)", which by the [Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#query-options) should instead be called "top".

- Updated remove access API to POST API
- What would be the recommended parameter when used alongside skipToken? top or maxpagesize?

**Comment by mikekistler** [comment]
> What would be the recommended parameter when used alongside skipToken? top or maxpagesize?

Neither. `skipToken` should be sufficient all on its own.

**Comment by mikekistler** [comment]
It looks like there are a number of missing example files:
```
examples/ApplicationData_Search.json
examples/Fields_Search.json
examples/HarvestData_Search.json
examples/Parties_GeoOverlap.json
examples/PlantingData_Search.json
examples/PlantTissueAnalyses_Search.json
examples/Prescriptions_Search.json
examples/Scenes_SearchItems.json
examples/SeasonalFields_Search.json
```

These are all referenced from x-ms-examples and cause errors in the validator.

**Comment by sjanamma** [comment]
Please fix the model validations and other checks

**Review by mikekistler — APPROVED** [review]
Looks good. 👍 

The maxpagesize -> top change can be deferred to the next preview if necessary.

**Comment by jhendrixMSFT** [comment]
@JeffreyRichter has the API stewardship board reviewed/approved this?

**Comment by JeffreyRichter** [comment]
I see that @mikekistler approved it. Mike, should we/you add the signed-off label to this PR?

**Pull request merged**
