### PR TITLE
dev-Sentinel-2022-08-01-preview

### PR DESCRIPTION
**Pull request by anat-gilenson**
Please note all PRs to this branch have already been reviewed and approved by Swagger team and ARM. No need for addition ARM review.

### CODE REVIEW

**Comment by anat-gilenson** [comment]
@dw511214992 PoliCheck fails due to usage of the word "Orient". In the context it's used, it refers to positioning, which is OK according to documentation. Is there a way to exclude this check for this specific description?
image

**Review by dw511214992 — APPROVED** [review]

**Pull request merged**
