### PR TITLE
[Hub Generated] Review request for Microsoft.DataReplication to add version preview/2021-02-16-preview

### PR DESCRIPTION
**Pull request by minhsuanlee**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/minhsuanlee-azuresiterecovery-Microsoft.DataReplication-2021-02-16-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by minhsuanlee** [comment]
> * he issue link that you created in step 1 in this PR

Link to New RP Namespace Issue: https://github.com/Azure/azure-sdk-pr/issues/1220

**Comment by konrad-jamrozik** [comment]
@rkmanda I assigned you as @minhsuanlee was asking me for help with [LintDiff failures](https://github.com/Azure/azure-rest-api-specs/pull/24903/checks?check_run_id=15185244179).

**Comment by minhsuanlee** [comment]
For LintDiff errors [LroErrorContent](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-error-content.md) and [OperationsApiResponseSchema](https://github.com/Azure/azure-openapi-validator/blob/main/docs/operations-api-response-schema.md), I have taken necessary steps to locally reproduce the errors but from what I can tell, the cause of the error does not seem to be valid as our schema is already following the guidelines. I even tried copy-paste the schema from [types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json) to our swagger directly and re-run Lint validation, it still failed.

**Review by mayada83 — APPROVED** [review]
Looks good.

**Comment by konrad-jamrozik** [comment]
@mayada83 if you confirm the Swagger LintDiff failure is incorrect, please add the `Approved-LintDiff` label. If you approve this PR on behalf of the ARM team, please add the `ARMSignedOff` label. Thank you!

**Comment by minhsuanlee** [comment]
Moving to a new PR [[Hub Generated] Review request for Microsoft.DataReplication to add version preview/2021-02-16-preview #24974](https://github.com/Azure/azure-rest-api-specs/pull/24974) as Service Name has been updated from 'azuresiterecovery' to 'recoveryservicesdatareplication'

**Comment by visingla-ms** [comment]
> {

Observed that your new RP is not RPaaS based RP. Non-RPaaS RPs are not allowed, unless you have got an exception. If that's the case, please forward me the RPaaS exception email/communication for your RP.

---
Refers to: specification/azuresiterecovery/resource-manager/Microsoft.DataReplication/preview/2021-02-16-preview/azuresiterecovery.json:1 in 5ef4eea. [](commit_id = 5ef4eea5b09ea6eb26eb92f4f7a911e20e0e9d46, deletion_comment = False)

**Pull request closed without merging**
