### PR TITLE
Add Authorization Key in connection object

### PR DESCRIPTION
**Pull request by dihan0604**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dihan0604__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dihan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by DeepakRajendranMsft** [comment]
The diff says that the entire spec has changed, could we please scope it only to your change. I cant even see what your changes are.

**Comment by dihan0604** [comment]
Made it scope to only my change, please take a look

**Comment by markcowl** [comment]
@DeepakRajendranMsft please take a look

**Comment by dihan0604** [comment]
Add Nilambari since Deepak is OOF.

**Comment by Nilambari** [comment]
Looks good. Just fix formatting. Thanks!

**Pull request merged**
