### PR TITLE
Reverting EH swagger removal.

### PR DESCRIPTION
**Pull request by liamjbennett**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@liamjbennett__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@liamjbennett__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by amarzavery** [comment]
@liamjbennett - There is another PR #481 that is adding an EH spec in a separate folder named arm-eventhub. 
- Did you take a look at that PR?
- How is that PR different from your's?

**Comment by liamjbennett** [comment]
@amarzavery it doesn't. I pulled the file from the same branch ealier in the day when I seen it removed. 

Closing now.

**Pull request closed without merging**
