### PR TITLE
Remove RemoteApp specs

### PR DESCRIPTION
**Pull request by xamarsinx**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amarsi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amarsin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@amarsi - please revese the order of the commits.  Start with an up to date branch and *then* delete the folder with the spec.

**Comment by amarzavery** [comment]
@amarsi - Why do you want to remove the spec? Are you planning to replace it with a new one for the api-version "2014-09-01"?

**Comment by amarsi** [comment]
doing as mark suggested

**Pull request closed without merging**
