### PR TITLE
Add API version 2023-10-01-preview [Import]

### PR DESCRIPTION
**Pull request by pracagrawal**
# ARM (Control Plane) API Specification Update Pull Request 

> Tip: overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] [ARM review queue] (for **merge** queues, see [2])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

</details>

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

In this new API version, we add ImportType field in the request body of ImportURI API call so that users can specify the type of import. There are 2 types of supported imports currently - Azure Migrate Csv and RVTools Xlsx. Default import type is set to Azure Migrate Csv.
## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the Diagram Step 2, "ARM API changes Review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by pracagrawal** [comment]
> Hi @pracagrawal! For review efficiency consideration, when creating a new API version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

Added the base version (2023-06-06) in first commit and new version updates into successive commits.

**Comment by pareshverma91** [comment]
@pracagrawal has this api seen a review for repo [https://github.com/Azure/azure-rest-api-specs-pr](https://github.com/Azure/azure-rest-api-specs-pr)? Is this expected to be a fresh review or is it being carry forwarded from the private repo?

**Comment by pareshverma91** [comment]
@pracagrawal Could you please tend to the automated errors that were posted on the review? E.g. [https://github.com/Azure/azure-rest-api-specs/pull/27385/checks?check_run_id=20521865807](https://github.com/Azure/azure-rest-api-specs/pull/27385/checks?check_run_id=20521865807).

**Comment by pareshverma91** [comment]
On comparing these changes with the api stable/2023-06-06, it seems the references to a whole lot of examples were removed for the preview version. Is the change intentional? Could you please add back the references? The PR automated checks also call this out.

**Comment by pareshverma91** [comment]
The overall changes from the stable api-version are low and are accounted for in the examples as well. Once the example reference issue is fixed, I will be able to sign off on the PR.

15978,16001d16574
<     "ImportTypeValues": {
<       "type": "string",
<       "description": "ImportTypeValues enum.",
<       "enum": [
<         "AzureMigrateCSV",
<         "RVToolsXlsx"
<       ],
<       "x-ms-enum": {
<         "name": "ImportTypeValues",
<         "modelAsString": true,
<         "values": [
<           {
<             "name": "AzureMigrateCSV",
<             "value": "AzureMigrateCSV",
<             "description": "AzureMigrateCSV value."
<           },
<           {
<             "name": "RVToolsXlsx",
<             "value": "RVToolsXlsx",
<             "description": "RVToolsXlsx value."
<           }
<         ]
<       }
<     },
17119,17123d17691
<         },
<         "importType": {
<           "$ref": "#/definitions/ImportTypeValues",
<           "description": "Gets or sets the import type.",
<           "default": "AzureMigrateCSV"

**Comment by pracagrawal** [comment]
> @pracagrawal has this api seen a review for repo https://github.com/Azure/azure-rest-api-specs-pr? Is this expected to be a fresh review or is it being carry forwarded from the private repo?

This is a fresh review.

**Comment by pracagrawal** [comment]
> > On comparing these changes with the api stable/2023-06-06, it seems the references to a whole lot of examples were removed for the preview version. Is the change intentional? Could you please add back the references? The PR automated checks also call this out.
> 
> @pareshverma91 , on including the minimum set examples, I see errors in model validation. On speaking to the platform team regarding this issue, the suggestion was to remove the minimum set examples.

@pareshverma91 The LintDiff errors and Avocado errors are not introduced by changes in this PR. Please suppress these errors. Also, please suppress SDK azure-sdk-for-go.

**Comment by pareshverma91** [comment]
Corresponding changes have been included in the examples. The net difference in examples is quite high, because it seems that the random strings used in examples have changed. However, we are good to go with this PR. The net new differences are just above and complete.

---
In reply to: [1894930803](https://github.com/Azure/azure-rest-api-specs/pull/27385#issuecomment-1894930803) [](http://example.com/codeflow?ancestors=1894930803)

**Comment by pracagrawal** [comment]
> > > On comparing these changes with the api stable/2023-06-06, it seems the references to a whole lot of examples were removed for the preview version. Is the change intentional? Could you please add back the references? The PR automated checks also call this out.
> > 
> > 
> > @pareshverma91 , on including the minimum set examples, I see errors in model validation. On speaking to the platform team regarding this issue, the suggestion was to remove the minimum set examples.
> 
> @pareshverma91 The LintDiff errors and Avocado errors are not introduced by changes in this PR. Please suppress these errors. Also, please suppress SDK azure-sdk-for-go. #Closed

Added labels to suppress LintDiff, Avoacado and SDK azure-sdk-for-go errors.

**Comment by pareshverma91** [comment]
From [https://eng.ms/docs/products/azure-developer-experience/design/specs-pr-guides/pr-suppressions#to-suppress-given-validation-failure](https://eng.ms/docs/products/azure-developer-experience/design/specs-pr-guides/pr-suppressions#to-suppress-given-validation-failure), there isn't a way to suppress SDK azure-sdk-for-go and SDK azure-sdk-for-net-track2. From the failures, the generation itself is failing. We should be good from the author side. AzCoreIDC signoff holds.

---
In reply to: [1900071091](https://github.com/Azure/azure-rest-api-specs/pull/27385#issuecomment-1900071091) [](http://example.com/codeflow?ancestors=1900071091)

**Comment by raosuhas** [comment]
> > Hi @pracagrawal! For review efficiency consideration, when creating a new API version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).
> 
> Added the base version (2023-06-06) in first commit and new version updates into successive commits.

Can you share the commit id where you added the base commit with the 2023-06-06 version ? I went through all your commits and the file migrate,json always has the version set to 2023-10-01-preview

image

**Comment by pracagrawal** [comment]
> > > Hi @pracagrawal! For review efficiency consideration, when creating a new API version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).
> > 
> > 
> > Added the base version (2023-06-06) in first commit and new version updates into successive commits.
> 
> Can you share the commit id where you added the base commit with the 2023-06-06 version ? I went through all your commits and the file migrate,json always has the version set to 2023-10-01-preview
> 
> image

@raosuhas : 4ee5337 is the commit Id that has migrate.json file with contents of 2023-06-06 version. Here's the migrate.json file for that commit: https://github.com/Azure/azure-rest-api-specs/blob/4ee5337b05f120dbb2520b7202d9e4e08e5f7c79/specification/migrate/resource-manager/Microsoft.OffAzure/preview/2023-10-01-preview/migrate.json

**Comment by visingla-ms** [comment]
Please make sure all checks are passing for PR to be merged: https://github.com/Azure/azure-rest-api-specs/pull/27385/checks?check_run_id=20965165197.

**Comment by pracagrawal** [comment]
> Please make sure all checks are passing for PR merging: https://github.com/Azure/azure-rest-api-specs/pull/27385/checks?check_run_id=20965165197.

@visingla-ms - All the required checks are passing now and the PR is in ready to merge state.
Requesting for merge again. Please let me know if you see any concerns.

**Review by visingla-ms — APPROVED** [review]

**Pull request merged**
