### PR TITLE
Update header and query parameter for source control

### PR DESCRIPTION
**Pull request by Juliehzl**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [x] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by ramoka178** [comment]
Same comments as in the PR https://github.com/Azure/azure-rest-api-specs/pull/29536. Please answer here as well, if any other reviewer is taking a look.

**Comment by Juliehzl** [comment]
> Same comments as in the PR #29536. Please answer here as well, if any other reviewer is taking a look.

replied in https://github.com/Azure/azure-rest-api-specs/pull/29536

**Comment by ramoka178** [comment]
Please address new comments from https://github.com/Azure/azure-rest-api-specs/pull/29536

**Comment by ramoka178** [comment]
[ARMBlockingComment] If GH work flow is implicitly created on a source control creation, the deletion of source control resource should also result in deleting GH workflow . There should not be an extra query param for user to pass to clean up GH workflow.

Please schedule a slot in ARM API Review office hours that happens every day to discuss further on this.
https://eng.ms/docs/products/arm/introduction/office_hours

**Comment by xwang971** [comment]
Attended office hour and got feedbacks. Since this is in prod for 2 years. This PR can be merged now. But we would have following items to deprecate using queries in delete call and passing token in header so we want to doing following work:
 1. Migrating to using AAD token(this is already in progress)
 2. Moving query into payload body.

@suhasaraos  please let us know if there's other concern you have.

**Comment by razvanbadea-msft** [comment]
>             "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter"

For consistency, can you update also the remaining parameters to the lates version of common types?

---
Refers to: specification/app/resource-manager/Microsoft.App/preview/2024-02-02-preview/SourceControls.json:146 in 2e40914. [](commit_id = 2e4091422812f30e5bf2b59ea08b4df547ec9c6b, deletion_comment = False)

**Comment by Juliehzl** [comment]
> > ```
> >         "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter"
> > ```
> 
> For consistency, can you update also the remaining parameters to the lates version of common types?
> 
> Refers to: specification/app/resource-manager/Microsoft.App/preview/2024-02-02-preview/SourceControls.json:146 in [2e40914](https://github.com/Azure/azure-rest-api-specs/commit/2e4091422812f30e5bf2b59ea08b4df547ec9c6b). [](commit_id = [2e40914](https://github.com/Azure/azure-rest-api-specs/commit/2e4091422812f30e5bf2b59ea08b4df547ec9c6b), deletion_comment = False)

Will this cause breaking change? I think I can update for new api version instead of existing api version.

**Comment by ms-bogdan-rotaru** [comment]
@Juliehzl The check `Swagger BreakingChange` is failing.

**Comment by Juliehzl** [comment]
> @Juliehzl The check `Swagger BreakingChange` is failing.

@ms-bogdan-rotaru  we already get breaking change review and get sign off

**Review by ms-bogdan-rotaru — APPROVED** [review]

**Review by ihsanalikapahi01 — COMMENTED** [review]
Approved.

**Pull request merged**
