### PR TITLE
fix: applicationinsights delete examples

### PR DESCRIPTION
**Pull request by nschonni**
Empty schema object was passing the empty string body in examples.

### CODE REVIEW

**Comment by nschonni** [comment]
Not sure if this is OK because it does change the SDK generation

**Comment by yungezz** [comment]
it's better we can get it validated via Swagger to SDK automation v2

**Comment by nschonni** [comment]
@yungezz sorry, I don't understand. Is that an internal MS tool that you want to run? I just got the error from OAV when I was playing around.

**Comment by yungezz** [comment]
what OAV error you met? Yes I'm talking some internal tool which will run SDK autogeneration.

**Comment by nschonni** [comment]
Ah, sorry, in this case I think I searched for the empty `schema` value, because it hides the OAV error around schema missmatch
```
$ oav validate-example specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/compon 
entAnnotations_API.json -p
Validating "examples" and "x-ms-examples" in  specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentAnnotations_API.json:

 error : 
operationId: Annotations_Delete
scenario: AnnotationsDelete
source: response
responseCode: '200'
severity: 0
code: RESPONSE_SCHEMA_NOT_IN_SPEC
details:
  code: RESPONSE_SCHEMA_NOT_IN_SPEC
  id: OAV113
  message: >-
    Response statusCode "200" for operation "Annotations_Delete" has response
    body provided in the example, however the response does not have a "schema"
    defined in the swagger spec.
  position:
    line: 135
    column: 17
  url: >-
    specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentAnnotations_API.json
  title: >-
    #/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.Insights~1components~1{resourceName}~1Annotations~1{annotationId}/delete
  directives:
    PutRequestResponseScheme: .*
    ListInOperationName: .*
    PutInOperationName: .*
    XmsResourceInPutResponse: .*
    RequiredPropertiesMissingInResourceModel: .*
    BodyTopLevelProperties: .*
    EnumInsteadOfBoolean: .*
    DefinitionsPropertiesNamesCamelCase: .*
    R2066: .*
  level: error
```
I'll go file something to see if OAV should also be flagging the empty schema object

**Comment by yungezz** [comment]
from the above error seems OAV complaining about no schema. I don't think this PR should be accepted

**Comment by nschonni** [comment]
No problem, maybe the oav/avocado folks can weigh in because I could be wrong (a few similar PRs are merged) @sergey-shandar @raych1 @ruowan

**Comment by raych1** [comment]
@yungezz , recently OAV has a change to flag on mismatch issue between swagger response body and example response body. 
This PR @nschonni made is to correct the use of `shema` in response swagger definition. i.e. for `delete` operation, if response doesn't have `body` then it remove `schema` as undefined and same in example where shouldn't have `body` defined.

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
got it. thansk @raych1 for clarification. Is this PR ok to merge from OAV perspective then?

**Comment by raych1** [comment]
@yungezz , yes it's ok to merge from OAV perspective.

**Pull request merged**
