### PR TITLE
[Language API 2022-04-01-Preview] Feature conversation PII redaction

### LINKED ISSUE #17438: [Cognitive Services - Text Analytics] REST API Review for Language API for TA  (2022-04-01-preview)
•	Key contact for the review: bidishac@, rapopovi@
•	Whether this is a new or existing API: new
•	Whether or not your service already been deployed: not deployed
•	A brief description of the material to be reviewed/changed: API review for the transcription PII redaction and issue resolution detection service. 

Design Documents
[Transcription PII Spec](https://microsoft-my.sharepoint.com/:w:/p/bidishac/ES-y8c8CaepJgwChqBjxIpEBKjtJZSjig_nLD45LEP5DVA?e=Q29Rax)

[Issue Resolution Detection](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Fr%2Fteams%2FTextAnalyticsTeam%2FShared%2520Documents%2FGeneral%2FGPT-3%2FIssue%2520Resolution%2520Detection%2520Public%2520Preview%2520Spec.docx%3Fd%3Dwa944653ccf474f0bb9ed8cb798205306%26csf%3D1%26web%3D1&data=04%7C01%7CCala.Zubair%40microsoft.com%7C13ecf09149944cfcc18c08d9e13ffa11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788487172684676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g%2FfaSm%2FyYW8mxvvqAbTheVb8NwxCuP6YP3bDqPVAKCY%3D&reserved=0)

### PR DESCRIPTION
**Pull request by bidisha-c**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [x] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. <i>04-01-2022</i>
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. - <i>04-01-2022 </i>
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by bexxx** [comment]
>       "post": {

[https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1325-operation-resource](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1325-operation-resource)

Cancellation should be exposed using DELETE 

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:204 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>         "PiiEntityRecognition",

PII means something different for different law, teams, compliance rules, ... 

Consider using a more generic term like "sensitive data" to be able to be more flexible with detection of your models.

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:373 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>     "AnalyzeTextLROTaskKind": {

nit: spell out or find better name

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:383 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>         "Healthcare",

C?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:392 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>         "Healthcare",

e.g. [https://grammarist.com/spelling/healthcare/](https://grammarist.com/spelling/healthcare/)

---
In reply to: [1022919506](https://github.com/Azure/azure-rest-api-specs/pull/17513#issuecomment-1022919506) [](http://example.com/codeflow?ancestors=1022919506)

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:392 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>         "name": "AnalyzeTextLROTaskKind",

Please avoid pushing this cryptic name to SDKs and customers

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:399 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>           "type": "string"

what kind of formatting is being used for language here?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:466 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>           "description": "Offset of the recognized speech in ticks."

ticks is a terrible format to use for customers.  Could this be a iso_8601 datetime (just the time part) with 3 digits for miliseconds instead?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:511 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>         }

iso_8601?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:692 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>             "BODY_STRUCTURE",

different enum value soelling/casing style than others. required?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:1437 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>           "IPAddress",

IP Addresses are not strictly PII, but more like personal data.

Also Age is not PII, same for a birthdate. They become PII when found in combination (name, birthday, ...).

My point is, consider it not to be called PII, because this has a very strict meaning.


---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:2462 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>             "cancelled",

rest guidelines ll, azure guidelines use l.
I've created a github issue to clarify.

What is the desired spelling here?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:2844 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>             "description": "Returned offset and length values will correspond to TextElements (Graphemes and Grapheme clusters) confirming to the Unicode 8.0.0 standard. Use this option if your application is written in .Net Framework or .Net Core and you will be using StringInfo."

(I am not a native speaker); this sounds odd to me. Should it be follow/comply to/...? (pls wontfix if not applicable)

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:3220 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>             "value": "TextElements_v8",

TextElementsUnicode8
TextElementsUnicodeV8
?

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:3219 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by bexxx** [comment]
>       "type": "string",

It might help to add an example value here with the api version to auto fill this value when using swagger ui.

---
Refers to: specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json:3537 in a7342fd. [](commit_id = a7342fd6b05d88c1add301f8b0f07f03ae0e4f1c, deletion_comment = False)

**Comment by abhahn** [comment]
We should create a feature branch for the 2022-04-01-preview release of the Language API and target that branch, since we will have a number of independent features that need to go into a single Swagger.  I can help with setting this up.

**Review by mikekistler — COMMENTED** [review]
I made a quick pass and flagged a few problems / questions.

**Pull request closed without merging**
