### PR TITLE
Add Power BI Premium

### PR DESCRIPTION
**Pull request by michael-falk**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

This change introduces the swagger spec for Power BI Premium on ARM.
This introduces the following operations:
GET all capacities (in subscription)
GET all capacities (in resource group)
PUT / PATCH / GET / DELETE a single capacity

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@michael-falk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mifal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jhendrixMSFT** [comment]
Hi @michael-falk just wanted to let you know that I'll be reviewing this today.

**Comment by jhendrixMSFT** [comment]
@michael-falk I have the following feedback so far.

The list operations API is missing.  Please see https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-09-01/swagger/resources.json#L1696 for an example.

Please add example request/reponse data via x-ms-examples extension.  Please see the following commit for an example https://github.com/Azure/azure-rest-api-specs/commit/f2a9a9f1a503e8f8950bb937124c12d50a92a8a1#diff-f142889ce5637ec21cbf0a392cf10121

@amarzavery Any feedback from your side?

**Comment by jhendrixMSFT** [comment]
Hi @michael-falk any update?

**Review by salameer — CHANGES_REQUESTED** [review]
@michael-falk, this PR has been idle for a while now, kindly note that if we don't recieve a response by the 22nd of March 2017 we will be closing it

**Comment by jhendrixMSFT** [comment]
Closing due to inactivity.  Please re-open when you're ready.

**Pull request closed without merging**
