### PR TITLE
Swagger definitions for the schemas of the Event Grid events published by Azure Storage and Azure EventHub services.

### PR DESCRIPTION
**Pull request by kalyanaj**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by alvadb — CHANGES_REQUESTED** [review]
Please review the linter errors: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/316049515

**Comment by kalyanaj** [comment]
@alvadb, regarding the linter error, the error is "Error: No unique 'title' across OpenAPI definitions:", however in this case they are three separate Swagger definitions so the titles being unique is by design. (This is somewhat similar to the model of https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/readme.md where multiple swagger definition files are included in the same autorest configuration file in readme.md).

**Comment by kalyanaj** [comment]
@alvadb, can you please take a look at this PR?  Please see my comments above related to the 1 linter error. Thanks!

**Review by alvadb — APPROVED** [review]

**Comment by alvadb** [comment]
I seem to have lost permission to merge.  I will look into this and hope to get this merged tomorrow.

**Pull request merged**
