### PR TITLE
[Hub Generated] Review request for Microsoft.OffAzure to add version stable/2020-07-07

### PR DESCRIPTION
**Pull request by poshukla**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/poshukla/azure-rest-api-specs/dev-migrate-Microsoft.OffAzure-2020-07-07...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ruowan** [comment]
Hi, Pls fix Prettier check error.

**Comment by poshukla** [comment]
> Hi, Pls fix Prettier check error.

Fixed.

**Comment by majastrz** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OffAzure/MasterSites/{siteName}": {

You need paths for listing all masterSites. If this is a tracked resource, you must support list at RG scope and list at subscription scope.

---
Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:2593 in 304bf35. [](commit_id = 304bf35c2b817785bf1cc69f7a2e7eecb09d6da7, deletion_comment = False)

**Comment by majastrz** [comment]
>         "sites": {

How large does this get? Does it need to be a nested resource?

---
Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:4880 in 304bf35. [](commit_id = 304bf35c2b817785bf1cc69f7a2e7eecb09d6da7, deletion_comment = False)

**Comment by poshukla** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OffAzure/MasterSites/{siteName}": {
> > ```
> 
> You need paths for listing all masterSites. If this is a tracked resource, you must support list at RG scope and list at subscription scope.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:2593 in [304bf35](https://github.com/Azure/azure-rest-api-specs/commit/304bf35c2b817785bf1cc69f7a2e7eecb09d6da7). [](commit_id = [304bf35](https://github.com/Azure/azure-rest-api-specs/commit/304bf35c2b817785bf1cc69f7a2e7eecb09d6da7), deletion_comment = False)

Added paths for listing all masterSites at RG scope and subscription scope.

**Comment by poshukla** [comment]
> > ```
> >     "sites": {
> > ```
> 
> How large does this get? Does it need to be a nested resource?
> 
> Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:4880 in [304bf35](https://github.com/Azure/azure-rest-api-specs/commit/304bf35c2b817785bf1cc69f7a2e7eecb09d6da7). [](commit_id = [304bf35](https://github.com/Azure/azure-rest-api-specs/commit/304bf35c2b817785bf1cc69f7a2e7eecb09d6da7), deletion_comment = False)

After the introduction of master site, we plan to restrict creation of only one site per type. The sites list will be of size 4 and it will increase when we add a new site type. 
This list might increase when we support brownfield customers but the list shouldn't be in tens, not more than that.

We are storing this data in MasterSite properties as a list of strings.

**Comment by majastrz** [comment]
>     "/subscriptions/{subscriptionId}/providers/Microsoft.OffAzure/MasterSites": {

You should consider adding paging to list calls even if the service only returns everything as one page right now. (Adding paging in the future will likely be breaking changes, so getting in front of that is usually a good idea.)

This applies to listing by RG also.

---
Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:2593 in 3bc0a07. [](commit_id = 3bc0a072b20f44c5e5dd7ab1613f0800fd641021, deletion_comment = False)

**Review by majastrz — APPROVED** [review]
Signed off from ARM side. Please take a look at the paging comment I added.

**Comment by poshukla** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/providers/Microsoft.OffAzure/MasterSites": {
> > ```
> 
> You should consider adding paging to list calls even if the service only returns everything as one page right now. (Adding paging in the future will likely be breaking changes, so getting in front of that is usually a good idea.)
> 
> This applies to listing by RG also.
> 
> Refers to: specification/migrate/resource-manager/Microsoft.OffAzure/stable/2020-07-07/migrate.json:2593 in [3bc0a07](https://github.com/Azure/azure-rest-api-specs/commit/3bc0a072b20f44c5e5dd7ab1613f0800fd641021). [](commit_id = [3bc0a07](https://github.com/Azure/azure-rest-api-specs/commit/3bc0a072b20f44c5e5dd7ab1613f0800fd641021), deletion_comment = False)

Fixed 👍

**Review by ruowan — APPROVED** [review]

**Pull request merged**
