### PR TITLE
Adding x-ms-examples to Bing Web Search Swagger Spec

### PR DESCRIPTION
**Pull request by sudhansu88**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sudhansu88** [comment]
I am not sure why all these commits are showing. I want to push only latest commit and 2 changes files

**Comment by lmazuel** [comment]
Hi @sudhansu88 
You have too many commits because you need to rebase your branch.
- [Add a remote called upstream if you don't have one](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
- When you have it, from your current branch:
```shell
git fetch upstream
git rebase upstream/current #Might create conflicts you need to solve
git push --force
```

**Comment by sudhansu88** [comment]
I am not sure why there are lots of conflicts [ Even though i have never touched any of CONFLICT files in my forked branch ] and when i resolved them, its now showing 8 changed files; But i am interested only in 2 files.

WebSearch.json
SuccessfulQueryRequest.json

**Comment by lmazuel** [comment]
@sudhansu88 I think the problem is that you made several PR from your "current". When a PR is accepted, the code is squashed into on commit. When it's done, your initial branch becomes incompatible with "current". Then, you do several PRs from the same branch, you got trouble...
A good habit is to keep your "current" exactly in sync with the upstream "current", and to do PR from branches.
I will se if I can "heal" your branch

**Comment by lmazuel** [comment]
@sudhansu88 I created a Pr to replace yours:
https://github.com/Azure/azure-rest-api-specs/pull/1983

Please confirm this is what you wanted, so we merge it and close this one.

For the future, I highly suggest that you delete your fork and fork from scratch, and that in the future. Then. keep you "current" in sync with the Azure/current and do each PR from a independant branch.

**Comment by lmazuel** [comment]
Merged part of the linked PR.

**Pull request closed without merging**
