### PR TITLE
devhub: fixing the constant name to be unique

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This conflicts with the existing constant named `ManifestType`

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Waiting for someone to review this..

**Review by bfoley13 — APPROVED** [review]
Thanks for catching this!

**Comment by tianxchen-ms** [comment]
Hi @tombuildsstuff @bfoley13 there is breakingchange here, please start breakingchange review following above comment.

**Comment by tombuildsstuff** [comment]
@tianxchen-ms the current Swaggers aren't valid - so could you clarify how this is a breaking change?

**Comment by tianxchen-ms** [comment]
@tombuildsstuff you can see the CI check error

**Comment by tombuildsstuff** [comment]
@tianxchen-ms since the Swagger in `main` doesn't currently work without this, this can't be a breaking change. Once again, what's the breaking change here?

**Comment by tianxchen-ms** [comment]
Hi @JeffreyRichter could you help review the breaking change?

**Pull request merged**
