### PR TITLE
loadtest: fixing the swagger tags

### PR DESCRIPTION
**Pull request by tombuildsstuff**
These aren't tags but an object currently, but should be tags

### CODE REVIEW

**Comment by raych1** [comment]
> Hi @tombuildsstuff, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/20961&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.

can you follow above action to get breaking change review approval?

**Comment by tombuildsstuff** [comment]
@raych1 

> can you follow above action to get breaking change review approval?

This currently isn't usable, so this can't be a breaking change.. unfortunately the breaking change process isn't actionable for external users, so I believe I'm unable to follow it - are you able to advice how to get this bug fix merged?

**Comment by tombuildsstuff** [comment]
thanks for reopening this @ruowan

**Comment by raych1** [comment]
@venkatr21 , can you review this PR as you're the owner of this service?

**Comment by venkatr21** [comment]
@tombuildsstuff @raych1 Could you please check the latest swagger - https://github.com/Azure/azure-rest-api-specs/blob/891dd18a70057c2fee388573117683e6d0081bda/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json#L637

We have already made this change to the latest swagger.

**Comment by venkatr21** [comment]
@tombuildsstuff I assume these changes are for terraform. Since we have alreadt made the current PR changes to the new api version (stable - 2022-12-01), and we need terraform integration only based on our latest API and not older ones, can we discard this PR?

**Comment by raych1** [comment]
@tombuildsstuff , I close this PR as the fix is in the latest api version.  Feel free to re-open this PR if needed.

**Pull request closed without merging**
