### PR TITLE
Dev/roip/restore points

### PR DESCRIPTION
**Pull request by roipmsft**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ x] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
This feature is already available in private preview in all public regions.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
 As soon as possible.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x ] SDK of .NET (need service team to ensure code readiness)
      - [x ] SDK of Python
      - [x ] SDK of Java
      - [x ] SDK of Js
      - [x ] SDK of Go
      - [x ] PowerShell
      - x[ ] CLI
      - [x ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by roipmsft** [comment]
I have fixed all the automated errors that I can.
I believe some of the automated validation errors are not appropriate. Could someone please confirm if these errors are real errors?
Swagger LintDiff failures @RaymondCheng @ruowan :
1.	R2062 – XmsResourceInPutResponse: The 200 response model for an ARM PUT operation must have x-ms-azure-resource extension set to true in its hierarchy. Operation: 'RestorePoints_CreateOrUpdate' Model: 'RestorePoint'.
‘RestorePoint’ is a proxy-only ARM resource. Does ‘x-ms-azure-resource’ still apply to ‘RestorePoint’?

2.	R3006 – BodyTopLevelProperties: Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'RestorePoint' has extra properties ['optionalProperties,sourceMetadata,provisioningState,consistencyMode,provisioningDetails,excludeDisks'].
My service is already using this ‘RestorePoint’ model definition with these properties as top level properties for many years now. I cannot change these properties to suddenly now be nested under a top level property.

Swagger BreakingChange failed – AddedPath. Yes, I am adding new paths to this swagger. However, these paths themselves are not new to our service. Customers have been using these paths for years already. The only thing that new is that I am finally documenting these paths in Swagger.

SDK Track2 Validation failed – 
AutorestCore/Exception. I have no idea how to troubleshoot this.
PreCheck/DuplicateSchema: details":"Duplicate Schema named PurchasePlan -- properties.promotionCode: undefined =>. I did not modify this part of the swagger. I don’t know why it’s complaining that this is duplicated, when it’s not.

**Comment by jianyexi** [comment]
@roipmsft  
For R2062 – XmsResourceInPutResponse,  the proxy resource is included 
For R3026 , you can suppress it , see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process

For ❌ PreCheck/DuplicateSchema, there is another schema : https://github.com/Azure/azure-rest-api-specs/blob/ab8b721a1d7bfa4e9c54dfb4172879b31c1d0df3/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/disk.json#L1901 , but you can ignore it , as it's not newly added by this PR

**Comment by roipmsft** [comment]
> @roipmsft
> For R2062 – XmsResourceInPutResponse, the proxy resource is included
> For R3026 , you can suppress it , see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process
> 
> For ❌ PreCheck/DuplicateSchema, there is another schema :
> 
> https://github.com/Azure/azure-rest-api-specs/blob/ab8b721a1d7bfa4e9c54dfb4172879b31c1d0df3/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/disk.json#L1901
> 
> , but you can ignore it , as it's not newly added by this PR

I realiz

**Comment by roipmsft** [comment]
@jianyexi  I realized I made this PR into the wrong branch.
I have made a new PR into the correct branch.
https://github.com/Azure/azure-rest-api-specs/pull/13219

**Pull request closed without merging**
