### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by BigCat20196**
issue link: https://github.com/Azure/sdk-release-request/issues/2271

image

### CODE REVIEW

**Comment by rezmicrosoft** [comment]
Hi @BigCat20196 , thanks for this. I am kind of confused here. What the tag in "Basic Information" means? Should it be the same as the latest API version (which is 2021-10-01 for us)? If so, then I don't think it needs to be reverted to "package-2020-02" by this pr. But if not, then how could I update API version of 2020-02-14?

**Comment by msyyc** [comment]
@ArcturusZhang @qiaozha @weidongxu-microsoft For awareness

**Comment by JackTn** [comment]
Hi, @BigCat20196. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @BigCat20196. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @BigCat20196. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
