### PR TITLE
PR for new api-version: Microsoft.Cache/redis/stable/2020-12-01 [rebased + refactored]

### PR DESCRIPTION
**Pull request by TimLovellSmith**
(This PR is a redo of https://github.com/Azure/azure-rest-api-specs/pull/13937 )

This is to document the latest REST API version for redis cache.

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  Answer: [Already deployed.]
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  Answer: [When new api-version is approved.]
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR
      - [x] No, its a new version, not an update to an existing version

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s): [No]
  - Adding a new API version [Yes]
  - [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service [No]

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

-[x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. [Blocked, per Ray saying we need review]

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version 
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
Why would I still get this warning when I'm using OperationListResult from common-types?

'The response schema of operations API '/providers/Microsoft.Cache/operations' does not match the ARM specification. Please standardize the schema.
Location: Microsoft.Cache/stable/2020-12-01/redis.json#L37'

**Review by ghost — APPROVED** [review]

**Comment by TimLovellSmith** [comment]
Hmm. How come prettier fails even though I processed it with prettier?

**Comment by TimLovellSmith** [comment]
@raych1 Is this ready to merge?
All the remaining cross-version breaking change errors flagged by CI are intentional.
* We added 'int32' format on an integer array where there was none
* We made redisVersion a read-write property, to support redisVersion 6
* We refactored to use common-types Resource type definitions, which is more strict about marking properties read-only than before

❌ 1023 - TypeFormatChanged | The new version has a different format than the previous one.New: Microsoft.Cache/stable/2020-12-01/redis.json#L2262:11Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2317:11
-- | --
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L343:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2568:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L356:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2575:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L366:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2579:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L361:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2583:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L371:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2587:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L409:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2598:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'true' to 'false'.New: Microsoft.Cache/stable/2020-12-01/redis.json#L1830:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L1922:9

**Comment by raych1** [comment]
@TimLovellSmith , please get ARM review approved.

**Comment by chiragg4u** [comment]
Thanks for following the review checklist, I was able to review changes. Changes looks good, marking ARM_Signedoff.

**Comment by chiragg4u** [comment]
Please resolve warning and please  the process given @ https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review

**Comment by TimLovellSmith** [comment]
@chiragg4u Just to make sure, did you mean to add suppression rules for the remaining warnings?

**Comment by TimLovellSmith** [comment]
@raych1 OK to merge?

**Comment by raych1** [comment]
@msyyc , can you check if any potential breaking change to python sdk?

**Comment by TimLovellSmith** [comment]
@msyyc Do the python SDK changes look like good ones, or do we need to scope down the changes to something more conservative?

**Comment by msyyc** [comment]
For python, the breaking change is ok

**Review by msyyc — APPROVED** [review]

**Comment by raych1** [comment]
@TimLovellSmith , please resolve the branch conflicts.

**Comment by TimLovellSmith** [comment]
@raych1 Resolved the conflicts by rebase.

**Comment by raych1** [comment]
> @raych1 Resolved the conflicts by rebase.

@TimLovellSmith , there's [breaking change](https://github.com/Azure/azure-rest-api-specs/pull/14023#issuecomment-822969937) compare to previous stable version. It needs to get breaking change review board approval.

**Comment by TimLovellSmith** [comment]
@raych1 
As mentioned earlier,
<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">All the remaining cross-version breaking change errors flagged by CI are intentional, and I am not expecting them to actually be able to break anybody.</p><ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">We added 'int32' format on an integer array where there was none, to fix a linter warning. Is the default type when not specified in OpenAPI spec defined? Is it defined as int32? If not, I'm happy to revert that and suppress the warning as its probably the safer option, but please clarify for me. It would be great if you could further enhance the guidance for <a href="https://github.com/Azure/openapi-diff/blob/master/docs/rules/1023.md">warning 1023 here</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">We made redisVersion a read-write property, so that customers can create caches with redisVersion=6 instead of the default of 4. This is an *intentional* cross-version change so that we can *enable new functionality*. Because it was already modeled as a string, and customers have to opt-in to using the new version we don't think this is a risky change that will break people.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Lastly we refactored to use common-types 'Operation' type definitions, which are more strict about marking properties read-only than before. This results in a lot of breaking changes warnings about lines 2568-L2598, but they are *desirable* breaking changes because those properties were never actually user-writable. They are read-only properties (rest-api-wise) used only to retrieve the operation results from the server</li></ul>

❌ 1023 - TypeFormatChanged | The new version has a different format than the previous one.New: Microsoft.Cache/stable/2020-12-01/redis.json#L2262:11Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2317:11
-- | --
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'true' to 'false'.New: Microsoft.Cache/stable/2020-12-01/redis.json#L1830:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L1922:9
--|--
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L343:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2568:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L356:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2575:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L366:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2579:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L361:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2583:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L371:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2587:13
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: common-types/resource-management/v2/types.json#L409:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2598:9


</body>
</html>

**Comment by TimLovellSmith** [comment]
To simplify the scope of discussion, I've pushed new commits that minimize the breaking change errors to just `redisVersion`. I consider this to be a false positive.

More specifically, it is not a breaking change, because making formerly read-only string properties writeable, nor adding new string values to a string property are breaking changes.  They don't break the REST API, they won't break SDKs, and its unlikely to break most app logic, since most apps wouldn't have had a need to inspect the value of the specific redisVersion string they receive, since it never previously varied. Even if it does broke app logic, it was a break the app developer could have predicted just by considering the semantics of the field. Its a version string! New versions are a thing that happen.

In any case, in our API, we do need a way to model different redis versions 4 and 6, so that customers can opt-in to creating caches on redisVersion 6. And the logical way to do that is... to let them specify the redis version.  It would be weird to be doing it any other way when we have a redisVersion property defined here already.

<html>
<body>


❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'true' to 'false'.New: Microsoft.Cache/stable/2020-12-01/redis.json#L1830:9Old: Microsoft.Cache/stable/2020-06-01/redis.json#L1922:9
-- | --
⚠️ 1032 - DifferentAllOf | The new version has a different 'allOf' property than the previous one.New: Microsoft.Cache/stable/2020-12-01/redis.json#L866:13Old: Microsoft.Cache/stable/2020-06-01/redis.json#L863:13
⚠️ 1032 - DifferentAllOf | The new version has a different 'allOf' property than the previous one.New: Microsoft.Cache/stable/2020-12-01/redis.json#L2098:5Old: Microsoft.Cache/stable/2020-06-01/redis.json#L2153:5


</body>
</html>

**Comment by msyyc** [comment]
For python, the breaking change is ok. Please ignore it.

**Comment by jianyexi** [comment]
approved breaking change as it's false alarm

**Pull request merged**
