### PR TITLE
Images swagger

### PR DESCRIPTION
**Pull request by cakarata**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by tjprescott** [comment]
The diff here is pretty confusing. Other than adding ZoneResilient to various examples, has anything functional changed?

**Comment by cakarata** [comment]
> The diff here is pretty confusing. Other than adding ZoneResilient to various examples, has anything functional changed?

Not functional changes mostly examples are added to cover ZoneResillient field and some descriptions

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
Approved but I cannot merge this due to all the failing CI checks.

**Comment by tjprescott** [comment]
@cakarata please address the CI failures.

**Comment by tjprescott** [comment]
ping @cakarata

**Comment by cakarata** [comment]
@huangpf, @hyonholee, and @tjprescott I have finally resolved the CI errors could you please review it?

**Pull request merged**
