### PR TITLE
Fix Swagger definition for customDimensions - remove additionalProper…

### PR DESCRIPTION
**Pull request by alongafni**
…ties

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by alongafni** [comment]
This PR should fix issue #8633

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@alongafni I can't merge this while required checks are failing.

**Comment by alongafni** [comment]
> @alongafni I can't merge this while required checks are failing.

@tjprescott these breaking changes are what this fix is all about, and I'll explain:
The customDimensions/customMeasurements properties are basically property bags.
For some reason they were defined wrong, so they can only have a single property called "additionalProperties", while the intent was to define them as objects that may contain any type of data.
My fix changes that, removes the wrong "additionalProperties" property and lets them have any property.
Let's discuss how to get this fix merged in. Thanks!

**Review by divyajay — APPROVED** [review]

**Comment by tjprescott** [comment]
Have you reviewed the breaking change guide here?
https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html#useful-pointers

**Comment by alongafni** [comment]
Thanks for the link, I have reviewed it now.
I think this fix does not require an API version change - the response was not changed, but the swagger was defined incorrectly, and this fix will make the swagger represent the response correctly in all API versions.

**Review by johanste — APPROVED** [review]

**Comment by tjprescott** [comment]
@lmazuel can you merge this? I don't have sufficient permissions.

**Pull request merged**
