### PR TITLE
Changes to make UserTags Patching Async

### PR DESCRIPTION
**Pull request by ishaniGupta27**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by raych1** [comment]
Hi @NullMDR , SDK net and SDK Java failed by running time exceeds more than 180mins. Is it normal?

**Comment by NullMDR** [comment]
@raych1 You can ignore .net and java sdk generation now.

**Comment by raych1** [comment]
@ishaniGupta27 , it still needs ARM sign off since it's stable version change. Can you also ask code owner to sign off?

**Review by ryansbenson — COMMENTED** [review]
Technically this falls under this category in the breaking changes doc: 
"Behavior of existing API has changed
There is a functional change in what the API was doing. This will need to be determined on a case by case basis." 

I believe for this change you would have to be introduced in a new API version. Consider the case where an end user has scripted against this, when you start returning 202 you could break their script.

**Comment by ishaniGupta27** [comment]
@ryansbenson When you mention that  new API version need to be introduced, does that mean we will be providing the new behviour of the old API from the newer version onwards only. If so, I believe I have to introduce the validations in the NRP code too.

**Comment by gimotwanMSFT** [comment]
@ryansbenson   The patch operation was never quite supported for Azure Firewall before this change. It was a dummy operation that would store the tags but do nothing with it. As such there is little chance for this to break existing functionality via client scripts.  Appreciate if you could approve the change.

**Review by KrisBash — APPROVED** [review]
Signing off for ARM

**Pull request merged**
