### PR TITLE
Added Azure App Configuration event data schema.

### PR DESCRIPTION
**Pull request by jimmyca15**
This PR is to add an Event Grid schema for Azure App Configuration. There are two contained events:

* KeyValueModified
* KeyValueDeleted

### CODE REVIEW

**Review by kalyanaj — APPROVED** [review]
LGTM.

**Comment by jhendrixMSFT** [comment]
@jimmyca15 can you please resolve the merge conflict?

**Comment by jimmyca15** [comment]
@jhendrixMSFT fixed it with a rebase.

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
