### PR TITLE
Updated swagger spec for stable/2018-05-05 version

### PR DESCRIPTION
**Pull request by mahakjain314**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by praries880** [comment]
@mahakjain314 Can you kindly take care of the model validation errors [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=42833&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&taskId=43324f1f-6724-5d61-785f-f0ac9fd256a1&lineStart=26&lineEnd=26&colStart=1&colEnd=17)?

**Comment by praries880** [comment]
@mahakjain314 The PR is missing changes... seems all the changes were reverted. Do you want me to close the PR?

**Comment by mahakjain314** [comment]
@praries880 And looks like the Spellcheck which is failing is not because of the changes I made. Log mentions that it is in mediaservices specs.

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by mahakjain314** [comment]
@praries880 Can you please merge the PR?

**Review by praries880 — APPROVED** [review]

**Pull request merged**
