### PR TITLE
Dev storageimportexport microsoft.import export 2016 11 01

### PR DESCRIPTION
**Pull request by nivats**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
Hi @nivats , as identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval [request form](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes) as defined.

**Comment by raych1** [comment]
@nivats , As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined at [breaking change process](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsazure%2FAzureWiki%2F_wiki%2Fwikis%2FAzureWiki.wiki%2F37673%2FRetirements-and-Breaking-Changes&data=02%7C01%7Cyiqiu%40microsoft.com%7C4f7e343d95044422d96308d81cde3e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637291088141681319&sdata=3JSPC3xymrP7eyjXbOEIDvfYGrVwvS%2FKf4F7dIB1W7g%3D&reserved=0).

**Comment by nivats** [comment]
I have added new version of api swagger along with examples and have reverted changes from swagger and examples of previous version of API

**Comment by ravbhatnagar** [comment]
property to take microsoft managed or customer managed keys is added. Signing off from arm side.

**Review by raych1 — APPROVED** [review]

**Review by raych1 — APPROVED** [review]

**Pull request merged**
