### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to add version stable/2021-08-01

### PR DESCRIPTION
**Pull request by avjerafi**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/avjerafi/azure-rest-api-specs/dev-monitor-Microsoft.Insights-2021-08-01-public...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by avjerafi** [comment]
@raych1 
Why was this PR flagged as a Cross Version Breaking Change?
A recent identical PR, which was eventually canceled (closed) had no such validation issue:
https://github.com/Azure/azure-rest-api-specs/pull/15464/checks?check_run_id=3240021273

**Comment by avjerafi** [comment]
@raych1
The "1005 RemovePath" errors seem to be due to a case sensitive match failure, because the paths exist in both version but differ only in casing: "resourcegroup" segment name vs. "resourceGroup".

**Comment by raych1** [comment]
> @raych1
> The "1005 RemovePath" errors seem to be due to a case sensitive match failure, because the paths exist in both version but differ only in casing: "resourcegroup" segment name vs. "resourceGroup".

@jianyexi , can you have a look at this?

**Comment by filizt** [comment]
It looks like this PR is adding pagination for GET operation for scheduledQueryRules. Looks good. Signing off.

**Comment by avjerafi** [comment]
@raych1
Would it be possible to get an explanation for the "Cross-Version Breaking Change" issue?

Here a quick history of the API versions for our service:

- 2018-04-16: latest stable
- 2020-05-01-preview: introduced major changes to the data structure, aligning it with other alerting services
- 2021-02-01-preview: minor changes
- 2021-08-01: adds paging <--- this PR

Why is this new API version being compared to the latest stable? We departed from that data structure 16 months ago and our previews have all been approved. ARM templates are being exported using 2021-02-01-preview. So what is the reason that the changes from the latest _**stable**_ version are of any significance?

I'll mention again that I've already submitted (but closed before approval) a PR for this new stable 2021-08-01, and didn't get an "Cross-Version Breaking Change" validation.
https://github.com/Azure/azure-rest-api-specs/pull/15464/checks?check_run_id=3240021273
How come? This is really puzzling to me.

**Comment by avjerafi** [comment]
Adding PM @yanivlavi

**Comment by yanivlavi** [comment]
> Hi @avjerafi, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review.
> **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).
> If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/15845&days=5).
> If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback.

This change is a GA version for a series of preview API that were released over the last 1.5 years.
The new API contains breaking changes, but the goal is the align with other APIs that Azure Monitor alerts has.
This API is field tested, UX research tested, and we have over 20k rules created already in this new schema.
Please waive this check.

**Comment by raych1** [comment]
> > Hi @avjerafi, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review.
> > **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).
> > If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/15845&days=5).
> > If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback.
> 
> This change is a GA version for a series of preview API that were released over the last 1.5 years. The new API contains breaking changes, but the goal is the align with other APIs that Azure Monitor alerts has. This API is field tested, UX research tested, and we have over 20k rules created already in this new schema. Please waive this check.

@avjerafi @yanivlavi , please follow above action to get breaking change review approval.

**Comment by raych1** [comment]
@avjerafi , please resolve the conflicts. 
@ArcturusZhang  @msyyc , can you confirm on the breaking change to GO/Python SDK?

**Comment by avjerafi** [comment]
Merged from main and resolved the conflicts

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
> @ArcturusZhang Can you please approve the GO SDK?
> 
> @raych1 Is there anything else but the GO SDK approval that is blocking this PR from being approved?

@avjerafi , all looks good now, please remove `DONOTMERGE` label when you're ready to merge this PR.

**Comment by avjerafi** [comment]
@raych1 Ping. Can you please respond to my question? This PR has now become urgent. Thanks!

**Comment by raych1** [comment]
> @raych1 I've removed the DoNotMerge flag.
> 
> General question: Is the merging automatic, or do I need to notify here and so it can then be merged manually? If it's automatic, can you please tell me what is the poling interval?

@avjerafi , it's not automatic, you need to notify PR assignee.  Can you resolve the `readme.md` conflicts?

**Pull request merged**
