### PR TITLE
Fixing examples for Linter errors

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
# Data Plane API - Pull Request
Fixing examples for Linter Error. More details at - 
https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=8E6AC90A-E109-4E00-B60D-54A4B029F669
https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=B38F0B8B-1EDB-47F5-AAA0-C08FE611385F

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ x] GA release

### Change Scope
<sup> This API is already GA. - https://learn.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi
There was linter error for the examples, so fixing it as mentioned in the above mentioned Linter errors.
 </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by rahuls-microsoft** [comment]
@weshaggard The changes are in the examples as per Linter Error. More details at -
https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=8E6AC90A-E109-4E00-B60D-54A4B029F669
https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=B38F0B8B-1EDB-47F5-AAA0-C08FE611385F
We need to resolve these s360 soon. Please take a look. Thanks.

**Comment by weshaggard** [comment]
@rahuls-microsoft can you please rebase your changes on top of main currently you have some bad merging so it is impossible to read and understand what you're actually changing.

**Comment by rahuls-microsoft** [comment]
> @rahuls-microsoft can you please rebase your changes on top of main currently you have some bad merging so it is impossible to read and understand what you're actually changing.

I ran following command to get the master and merge it to current branch:

git remote add upstream     https://github.com/Azure/azure-rest-api-specs
git remote -v
git fetch upstream
git pull upstream main


git fetch
git pull

pause

git push origin
git checkout master
git merge -X theirs upstream/master
git push origin

Please let me know, if it looks fine now.
Else please suggest the command to synch with the master. Thanks for your help.

**Comment by rahuls-microsoft** [comment]
It seems like a bad merge. I will create a fresh PR.
Or suggest how to address the merge? Thanks.

**Comment by rahuls-microsoft** [comment]
It seems like a bad merge. I will create a fresh PR.
Or suggest, how to address the merge? Thanks.

**Comment by rahuls-microsoft** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/23174 - Created new PR.

**Comment by rahuls-microsoft** [comment]
How do I close this PR.?  Please ignore this PR. I have created another one .

**Comment by rahuls-microsoft** [comment]
Create another PR with clean merge - https://github.com/Azure/azure-rest-api-specs/pull/23174

**Pull request closed without merging**
