### PR TITLE
Update Microsoft.Sql ManagedInstance 2022-11-01-preview Swagger Docs

### PR DESCRIPTION
**Pull request by ilijadivljan-ms**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
N/A
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
Version update - EO March 2023.
  5. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ilijadivljan-ms** [comment]
> please copy paste arm-id corresponding change to your PR. we will add auto-generation process for them next month.
> 
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L950:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L864:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L994:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L916:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L1005:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L928:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L1098:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L1022:9

**Comment by ilijadivljan-ms** [comment]
> please copy paste arm-id corresponding change to your PR. we will add auto-generation process for them next month.
> 
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L950:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L864:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L994:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L916:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L1005:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L928:9
> ❌ 1023 - TypeFormatChanged	The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L1098:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L1022:9

Done, I copied over arm-id's manually.

**Comment by toki95** [comment]
@ericshape

**Comment by toki95** [comment]
@ericshape I don't understand why is this validation of Enum failing when we were fixing this issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34. 
image

**Comment by ericshape** [comment]
> @ericshape I don't understand why is this validation of Enum failing when we were fixing this issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34. image

if you are adding the following enum setup, it is expected.

          "x-ms-enum": {
            "name": "ProvisioningState",
            "modelAsString": true
          }

**Comment by ilijadivljan-ms** [comment]
> > @ericshape I don't understand why is this validation of Enum failing when we were fixing this issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34. image
> 
> if you are adding the following enum setup, it is expected.
> 
> ```
>       "x-ms-enum": {
>         "name": "ProvisioningState",
>         "modelAsString": true
>       }
> ```

So do we need to modify the current setup or we should ignore this break and treat it as expected? Because we primarily want to fix the 360 issue?

**Comment by ericshape** [comment]
> > > @ericshape I don't understand why is this validation of Enum failing when we were fixing this issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34. image
> > 
> > 
> > if you are adding the following enum setup, it is expected.
> > ```
> >       "x-ms-enum": {
> >         "name": "ProvisioningState",
> >         "modelAsString": true
> >       }
> > ```
> 
> @ericshape so do we need to modify the current setup or we should ignore this break and treat it as expected? Because we primarily want to fix the 360 issue?

yes. 
please make sure there is no property name change

**Comment by ilijadivljan-ms** [comment]
Following breaks are expected. 

Since last version we made following changes:

- Added new optional parameter - virtualClusterId
- Added missing HTTP 200 paths/examples for Start/Stop actions
- Added missing enum values for property provisioningState
- Added missing property x-ms-enum to resolve 360 issue

<html>
<body>


Rule | Message
-- | --
❌ 1048 - AddedXmsEnum | The new version adds a x-ms-enum extension.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
💬 1020 - AddedEnumValue | The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobExecutions.json#L567:9Old: Microsoft.Sql/stable/2021-11-01/JobExecutions.json#L567:9
💬 1020 - AddedEnumValue | The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobStepExecutions.json#L291:9Old: Microsoft.Sql/stable/2021-11-01/JobStepExecutions.json#L291:9
💬 1020 - AddedEnumValue | The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobTargetExecutions.json#L425:9Old: Microsoft.Sql/stable/2021-11-01/JobTargetExecutions.json#L425:9
💬 1020 - AddedEnumValue | The new version is adding enum value(s) 'InProgress' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
💬 1038 - AddedPath | The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L476:5
💬 1038 - AddedPath | The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L519:5
💬 1040 - AddedReadOnlyPropertyInResponse | The new version has a new read-only property 'virtualClusterId' in response that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7
💬 1045 - AddedOptionalProperty | The new version has a new optional property 'virtualClusterId' that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7


</body>
</html>
Rule	Message
❌ [1048 - AddedXmsEnum](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1048.md)	The new version adds a x-ms-enum extension.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9)
Old: [Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9)
💬 [1020 - AddedEnumValue](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1020.md)	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/JobExecutions.json#L567:9](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/JobExecutions.json#L567:9)
Old: [Microsoft.Sql/stable/2021-11-01/JobExecutions.json#L567:9](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/JobExecutions.json#L567:9)
💬 [1020 - AddedEnumValue](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1020.md)	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/JobStepExecutions.json#L291:9](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/JobStepExecutions.json#L291:9)
Old: [Microsoft.Sql/stable/2021-11-01/JobStepExecutions.json#L291:9](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/JobStepExecutions.json#L291:9)
💬 [1020 - AddedEnumValue](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1020.md)	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/JobTargetExecutions.json#L425:9](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/JobTargetExecutions.json#L425:9)
Old: [Microsoft.Sql/stable/2021-11-01/JobTargetExecutions.json#L425:9](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/JobTargetExecutions.json#L425:9)
💬 [1020 - AddedEnumValue](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1020.md)	The new version is adding enum value(s) 'InProgress' from the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9)
Old: [Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9)
💬 [1038 - AddedPath](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1038.md)	The new version is adding a path that was not found in the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L476:5](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L476:5)
💬 [1038 - AddedPath](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1038.md)	The new version is adding a path that was not found in the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L519:5](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L519:5)
💬 [1040 - AddedReadOnlyPropertyInResponse](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1040.md)	The new version has a new read-only property 'virtualClusterId' in response that was not found in the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7)
Old: [Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7)
💬 [1045 - AddedOptionalProperty](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1045.md)	The new version has a new optional property 'virtualClusterId' that was not found in the old version.
New: [Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7](https://github.com/Azure/azure-rest-api-specs/blob/2d7c8501b3f55ff588c18df16530cb5a2bcdaa82/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7)
Old: [Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7)

**Review by ericshape — APPROVED** [review]

**Comment by raych1** [comment]
> Following breaks are expected.
> 
> Since last version we made following changes:
> 
> * Added new optional parameter - virtualClusterId
> * Added missing HTTP 200 paths/examples for Start/Stop actions
> * Added missing enum values for property provisioningState
> * Added missing property x-ms-enum to resolve 360 issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34
> 
> Rule	Message
> ❌ 1048 - AddedXmsEnum	The new version adds a x-ms-enum extension.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobExecutions.json#L567:9Old: Microsoft.Sql/stable/2021-11-01/JobExecutions.json#L567:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobStepExecutions.json#L291:9Old: Microsoft.Sql/stable/2021-11-01/JobStepExecutions.json#L291:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobTargetExecutions.json#L425:9Old: Microsoft.Sql/stable/2021-11-01/JobTargetExecutions.json#L425:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'InProgress' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
> 💬 1038 - AddedPath	The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L476:5
> 💬 1038 - AddedPath	The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L519:5
> 💬 1040 - AddedReadOnlyPropertyInResponse	The new version has a new read-only property 'virtualClusterId' in response that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7
> 💬 1045 - AddedOptionalProperty	The new version has a new optional property 'virtualClusterId' that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7

Can you talk to Jeffrey or mikekistler to get breaking change review approval?

**Comment by ilijadivljan-ms** [comment]
> Following breaks are expected.
> 
> Since last version we made following changes:
> 
> * Added new optional parameter - virtualClusterId
> * Added missing enum values for property provisioningState
> * Added missing property x-ms-enum to resolve 360 issue https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=3611EA06-DC20-4131-A667-D21DC9EF2C34
> 
> Rule	Message
> ❌ 1048 - AddedXmsEnum	The new version adds a x-ms-enum extension.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobExecutions.json#L567:9Old: Microsoft.Sql/stable/2021-11-01/JobExecutions.json#L567:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobStepExecutions.json#L291:9Old: Microsoft.Sql/stable/2021-11-01/JobStepExecutions.json#L291:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'Creating, Deleting, Updating, Unknown, Accepted, Deleted, Unrecognized, Running, NotSpecified, Registering, TimedOut' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/JobTargetExecutions.json#L425:9Old: Microsoft.Sql/stable/2021-11-01/JobTargetExecutions.json#L425:9
> 💬 1020 - AddedEnumValue	The new version is adding enum value(s) 'InProgress' from the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L892:9Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L806:9
> 💬 1038 - AddedPath	The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L476:5
> 💬 1038 - AddedPath	The new version is adding a path that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L519:5
> 💬 1040 - AddedReadOnlyPropertyInResponse	The new version has a new read-only property 'virtualClusterId' in response that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7
> 💬 1045 - AddedOptionalProperty	The new version has a new optional property 'virtualClusterId' that was not found in the old version.New: Microsoft.Sql/preview/2022-11-01-preview/ManagedInstances.json#L891:7Old: Microsoft.Sql/stable/2021-11-01/ManagedInstances.json#L805:7

@JeffreyRichter @mikekistler can you please review following breaking changes report?

@ericshape to confirm that breaking change regarding x-ms-enum property is expected due to 360 issue.
cc @raych1

**Comment by ilijadivljan-ms** [comment]
@raych1 Jeffery Approved the breaking change. Do you need anything else to merge this PR?

**Comment by ilijadivljan-ms** [comment]
@raych1 please wait with merging this PR. We might need to make an additional change regarding provisioningStateEnum property.

**Comment by ilijadivljan-ms** [comment]
@raych1 please merge this PR when you get a chance. @toki95 and me reviewed everything and it was correct, no additional changes were needed.

**Pull request merged**
