### PR TITLE
Merge 2023-04-15-preview from feature branch

### LINKED ISSUE #22649: [Cognitive Service - Text Analysis for language] API Review
New API Review meeting has been requested.

**Service Name**: Azure Cognitive service for language - Text Analysis
**Review Created By**: Aurgho Bhattacharjee @aurghob
**Review Date**: 3/16/2023 4:00 PM PT
**PR**: 
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: Among others, We have multiple changes coming up for the following skills in text analytics for preview and GA API:

1. Conversational PII: 
     a. Allowing the redaction character to be configurable from '*'
    b. Change 'includeAudioRedaction' flag Name for clarity (Options: includeAudioRedactionTiming) both for GA and Preview
    c. rename 'Name' to 'Person' to match Text PII categories
    d. exclusion list 

2. NER
     i Resolution type renaming to align to CLU: for Dimension --> should be plural. 
    ii Add support for inclusion/exclusion list
    iii entity overlapping policy support 
3. PII
    i category exclusion support
    ii Allowing the redaction character to be configurable from '*'

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=60c6931f-57ad-ed11-aad1-000d3a341bd5)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by quentinRobinson**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [X] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>

Merging the Cognitive Services Language 2023-04-15-preview API into the main branch. Based off the [release-cognitiveservices-Language-2023-04-15-preview ](https://github.com/Azure/azure-rest-api-specs/blob/release-cognitiveservices-Language-2023-04-15-preview ) branch
* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/22649

### CODE REVIEW

**Comment by heaths** [comment]
@quentinRobinson is this just a rebase + merge request to main based on the old release branch, i.e. it's already been reviewed?

**Comment by heaths** [comment]
Also, please go through and fix the build errors you can. Let me know which you can't, are expected, or have questions on.

**Comment by quentinRobinson** [comment]
@heaths yes, this is just getting all the changes already reviewed in the feature branch into main. ill fix the errors

**Comment by quentinRobinson** [comment]
@heaths the LintDiff is throwing errors for the HostParametersValidation and IntegerTypeMustHaveFormat, which fixing would cause new breaking changes and the rest of the breaking changes are known and brought up in the other PRs

**Comment by quentinRobinson** [comment]
@heaths the LintDiff is throwing errors for the HostParametersValidation and IntegerTypeMustHaveFormat, which fixing would cause new breaking changes and the rest of the breaknig changes are

**Comment by heaths** [comment]
There's also a policheck failure. But fixing those other lintdiff issues 1) won't practically be breaking (@JeffreyRichter and @mikekistler FYI), and 2) breaking changes only should happen the first time where lintdiff errors will last forever and we'll always have to go through this.

**Comment by heaths** [comment]
The only breaking change that isn't a fix to the old swagger (practically the same) is the addition of a required *output* property, `assignedResources`, which is in a new version and should be acceptable.

Having reviewed the past PRs - and this PR looks correct - I'm fine with these changes but you should also go through a board review: https://aka.ms/azsdk/onboarding/restapischedule

**Review by heaths — APPROVED** [review]

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Comment by heaths** [comment]
I can vouch for the [suppression](https://github.com/Azure/azure-rest-api-specs/pull/24891/files#diff-d879a3011cf361d0ad83a26356d5d1b689bc141d8ff67567ecf72865e9258becR82-R83).

**Pull request merged**
