### PR TITLE
[Cognitive Services] Fix metadata types for Content Moderator.

### PR DESCRIPTION
**Pull request by yangyuan**
Metadata should be a dictionary. The swagger was written in a wrong way.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
Can you please update the examples to match this swagger change?  Model validation is failing, see the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/418416597).

**Comment by yangyuan** [comment]
hi @jhendrixMSFT,
It's so weird it can pass the validation locally by `oav validate-example`, how can I repeat the error locally.

**Comment by jhendrixMSFT** [comment]
I would expect ```oav validate-example``` to work.  @sergey-shandar is there something else we should be running?

**Comment by yangyuan** [comment]
@jhendrixMSFT 
Hmm.
Anyway I am trying to mitigate the issue by indicate the type as "string" instead of "object".

A little bit background, there is no breaking change in here, all previous examples should work.
I'm just trying to fix the mistakes in the swagger file. A few types should be dictionary but described with fixed fields.

**Comment by jhendrixMSFT** [comment]
Unfortunately this change is breaking (thanks for reminding me, I will add the tag).  As an example see the change in the Go SDK [here](https://github.com/Azure/azure-sdk-for-go/pull/2494).  I understand it's the right thing to do as the swagger was wrong but we still have to track it as breaking.

**Comment by yangyuan** [comment]
@jhendrixMSFT 
Hmm, seems all validations pass now.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
