### PR TITLE
Add last access time and smb multichannel feature into Aug2020 preview

### PR DESCRIPTION
**Pull request by zfchen95**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by markcowl** [comment]
@zfchen  Please fill out the checkboxes in the issue after you have followed the instructions.  You will need to clear linter errors and determine if asn ARM review is warranted.

**Comment by zfchen95** [comment]
> @ZFChen Please fill out the checkboxes in the issue after you have followed the instructions. You will need to clear linter errors and determine if asn ARM review is warranted.

Fixed

**Comment by markcowl** [comment]
@zfchen95 Per the breaing change errors, these changes require a new api-version (breaking changes are allowed in preview APIs that are < 1 year old, but only in a new api-version).

**Comment by zfchen95** [comment]
> @zfchen95 Per the breaing change errors, these changes require a new api-version (breaking changes are allowed in preview APIs that are < 1 year old, but only in a new api-version).

Please note that the new properties are added under a preview API version. There are two types of breaking changes. For additive breaking change, from what I learned, can always be added to a preview API version that was released within a year.

**Comment by markcowl** [comment]
@zfchen95 Is this a p[ublic preview or private preview?  If public preview, then a new api-version is required.  If private preview, then it seems this should go in the private repo (although if the current version is  also a private preview, we cna make an exception in this case, let me know).

**Comment by zfchen95** [comment]
> @zfchen95 Is this a p[ublic preview or private preview? If public preview, then a new api-version is required. If private preview, then it seems this should go in the private repo (although if the current version is also a private preview, we cna make an exception in this case, let me know).

Based on what I learned from the Microsoft Rest API guideline (https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#preview-versions), it is not a requirement to bump the version for adding evolutionary change. 
"Evolutionary changes may be added as needed, as long as the change is communicated broadly."
We have been using merge model for years and haven't heard any complaint from the customers about adding new properties.

**Comment by markcowl** [comment]
@zfchen95 These are not evolutionary changes, they are listed as breaking changes, which require a version change for public preview APIs. from the REST API Guidlines:

> The X integer (indicating the revision of the preview) must be incremented for all breaking changes (resulting in a new API version). Evolutionary changes may be added as needed, as long as the change is communicated broadly.

Per the breaking changes mentioned above, this is a breaking change and so, would require a version update.  I believe we can provide an exception in this case, but these rules will soon be strictly enforced, and you should take this into account when pl;anning API changes in the future.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
