### PR TITLE
Adding put and delete BMI operations to baremetalinfrastructure.json spec

### PR DESCRIPTION
**Pull request by 8Gitbrix**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [x] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dsmith111** [comment]
As a note, our RP does not support PUT or DELETE operations. However, as a requirement for GA, we need to return a response for them. The ARM team originally gave us the greenlight for only returning a "Not supported" code with a message stating the official routes needed to perform it. Which is why we do not have any 2xx responses listed.

Second, this is not a breaking change. This api version, 2023-04-06, received an exception very recently when it was created for not adding PUT/DELETE operations. This PR simply adds a formal "Not supported" response. No actual functionality with this operation has changed.

**Comment by keryul** [comment]
@konrad-jamrozik can we approve this breaking change?

**Comment by konrad-jamrozik** [comment]
> @konrad-jamrozik can we approve this breaking change?

Please follow the guidance given in this comment:
- https://github.com/Azure/azure-rest-api-specs/pull/24059#issuecomment-1553776172

**Comment by konrad-jamrozik** [comment]
> As a note, our RP does _not_ support PUT or DELETE operations. However, as a requirement for GA, we need to return a response for them. The ARM team originally gave us the greenlight for only returning a "Not supported" code with a message stating the official routes needed to perform it. Which is why we do not have any 2xx responses listed.
> 

Can you link me to the greenlight from ARM team, so I can verify?

> Second, this is not a breaking change. This api version, 2023-04-06, [received an exception](https://github.com/Azure/azure-rest-api-specs/pull/23901) very recently when it was created for not adding PUT/DELETE operations. This PR simply adds a formal "Not supported" response. No actual functionality with this operation has changed.

I looked at that PR but it is not clear to me what exception was given there, sorry. Was it given by someone from ARM team? Can you link to it?

**Comment by konrad-jamrozik** [comment]
> As a note, our RP does _not_ support PUT or DELETE operations. However, as a requirement for GA, we need to return a response for them. The ARM team originally gave us the greenlight for only returning a "Not supported" code with a message stating the official routes needed to perform it. Which is why we do not have any 2xx responses listed.
> 

Can you link me to the greenlight from the ARM team, so I can verify?

> Second, this is not a breaking change. This api version, 2023-04-06, [received an exception](https://github.com/Azure/azure-rest-api-specs/pull/23901) very recently when it was created for not adding PUT/DELETE operations. This PR simply adds a formal "Not supported" response. No actual functionality with this operation has changed.

To which of the failing checks of the breaking change it is referring to specifically? I mean the failures listed [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2786392&view=logs&j=98f87804-8e1f-5655-af02-e80aefa7aa97&t=65457206-7ab6-5966-2a2f-9ae3efa14a03&l=100).

> @konrad-jamrozik can we approve this breaking change?

Please address my questions above, thx! :)

@bdefoy @rkmanda FYI

**Review by pabowers — APPROVED** [review]

**Comment by mentat9** [comment]
> As a note, our RP does _not_ support PUT or DELETE operations. However, as a requirement for GA, we need to return a response for them. The ARM team originally gave us the greenlight for only returning a "Not supported" code with a message stating the official routes needed to perform it. Which is why we do not have any 2xx responses listed.
> 
> Second, this is not a breaking change. This api version, 2023-04-06, [received an exception](https://github.com/Azure/azure-rest-api-specs/pull/23901) very recently when it was created for not adding PUT/DELETE operations. This PR simply adds a formal "Not supported" response. No actual functionality with this operation has changed.

Note: ARM signed off on the private PR here: https://github.com/Azure/azure-rest-api-specs-pr/pull/12118.

**Comment by dsmith111** [comment]
@konrad-jamrozik now that the ARM team has responded, I'll touch on the breaking changes listed below:

**Swagger BreakingChange**: this is regarding the two operations we want to add to this API version.

**Swagger LintDiff**: Many of these errors are regarding the fact our PUT/DELETE methods do not have a valid status code. Which they should not as I've mentioned above (e.x. The delete operation is defined without a 200 or 204 error response implementation). I _can_ add it to the specs, however it could be misleading as these operations should never return a 2xx code

**Comment by konrad-jamrozik** [comment]
@keryul @dsmith111 given that @mentat9 added `ARMSignedOff` label and provided relevant context in comments, looks to me this PR is OK to be merged.

**Comment by 8Gitbrix** [comment]
Thanks. Can someone who's authorized go ahead and merge this PR? I don't have permissions.

**Comment by dsmith111** [comment]
I believe that’s up to @keryul

**Comment by keryul** [comment]
@raych1 please review the GO breaking change

**Comment by keryul** [comment]
> @keryul @dsmith111 given that @mentat9 added `ARMSignedOff` label and provided relevant context in comments, looks to me this PR is OK to be merged.

Then I'll add Approved-LintDiff label

**Comment by 8Gitbrix** [comment]
Friendly ping to get this merged

**Review by ArcturusZhang — APPROVED** [review]

**Comment by keryul** [comment]
> Hi @8Gitbrix! The automation detected breaking changes in this pull request. As a result, it added the `BreakingChangeReviewRequired` label. You cannot proceed with merging this PR until you complete one of the following action items: **ACTION ITEM ALTERNATIVE A**: Fix the breaking change. Please consult the documentation provided in the relevant validation failures. **ACTION ITEM ALTERNATIVE B**: Request approval. Alternatively, if you cannot fix the breaking changes, then you can request an approval for them. Please follow the process described in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process). **ACTION ITEM ALTERNATIVE C**: Report false positive. If you think there are no breaking changes, i.e. the validation should pass yet it fails, then please explain why in a PR comment and @ the PR assignee.

@8Gitbrix please get breaking change approval

**Comment by dsmith111** [comment]
> @keryul @dsmith111 given that @mentat9 added `ARMSignedOff` label and provided relevant context in comments, looks to me this PR is OK to be merged.

@keryul, I was under the impression this process surrounding ARM's and @konrad-jamrozik's approval was specific to the breaking change that was flagged (i.e. these PUT/DELETE operations being added to this specific version even though they do not currently exist):

image

**Comment by dsmith111** [comment]
> > As a note, our RP does _not_ support PUT or DELETE operations. However, as a requirement for GA, we need to return a response for them. The ARM team originally gave us the greenlight for only returning a "Not supported" code with a message stating the official routes needed to perform it. Which is why we do not have any 2xx responses listed.
> 
> Can you link me to the greenlight from the ARM team, so I can verify?
> 
> > Second, this is not a breaking change. This api version, 2023-04-06, [received an exception](https://github.com/Azure/azure-rest-api-specs/pull/23901) very recently when it was created for not adding PUT/DELETE operations. This PR simply adds a formal "Not supported" response. No actual functionality with this operation has changed.
> 
> To which of the failing checks of the breaking change detector are you referring to specifically? I mean the failures listed [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2786392&view=logs&j=98f87804-8e1f-5655-af02-e80aefa7aa97&t=65457206-7ab6-5966-2a2f-9ae3efa14a03&l=100).
> 
> > @konrad-jamrozik can we approve this breaking change?
> 
> Please address my questions above. I also recommend addressing the other failures. Thx! :)
> 
> @bdefoy @rkmanda FYI

Specifically flagged here where I mentioned the "new version breaking change" issue the automation detected

**Comment by konrad-jamrozik** [comment]
@rkmanda, another PR I reassigned to you that needs your attention.

**Comment by 8Gitbrix** [comment]
@rkmanda Ping to merge the PR. Thanks!

**Comment by 8Gitbrix** [comment]
Can someone help merge this?

**Comment by konrad-jamrozik** [comment]
@8Gitbrix apologies for the delay. We are dealing with large amount of PRs plus we have been making changes to the PR review process to streamline it.

You have failing requirements:
- https://github.com/Azure/azure-rest-api-specs/pull/24059/checks?check_run_id=15442575791

Please address them by following this process:
- https://github.com/Azure/azure-rest-api-specs/blob/main/.github/PULL_REQUEST_TEMPLATE/spec_pr_review_workflow_diagram.png

Thanks!

**Comment by 8Gitbrix** [comment]
@konrad-jamrozik Thanks for the reply. As David mentioned before this version 2023-04-06, [received an exception](https://github.com/Azure/azure-rest-api-specs/pull/23901)when it was created for not adding PUT/DELETE operations. Despite no breaking changes or change in functionality, do I still need to follow this guidance? I was under the impression that this issue was resolved before.

**Comment by dsmith111** [comment]
@konrad-jamrozik, can you send us or ping the reviewers responsible for handling breaking change exceptions?

From the error list you've shared;
image

We've received the ARM Signed off label it's complaining about:
image

We've received the SDK breaking change sign-off:
image

The only issue we can "address" is the breaking swagger changes:
image

However, as you can see, the entire PR comprises of these changes. Fixing it would just be deleting the PR. The change would not break any customer as the PUT/DELETE operations are modified to return a failure status code with a message officially stating the operation is not supported. While originally it just returned a failure code dictating "method not allowed". Customer's will _not_ be building off of this as it does not exist, and will not after the PR as we are not adding any functionality in. We are just adding in the message for GA compliance.

I'd appreciate being pointed to the responsible owners of general breaking changes to discuss the plan going forward.

**Comment by konrad-jamrozik** [comment]
@dsmith111 @8Gitbrix we have been improving the guidance rapidly in last few days so it is in a bit of a flux, apologies for that. You can find the current guidance here:

- https://github.com/Azure/azure-rest-api-specs/blob/1635191726c958d7a2ff573a4aa82ad84d67488f/.github/PULL_REQUEST_TEMPLATE/control_plane_template.md

You had `ARMSignedOff` but you did not have `Approve-BreakingChange` label. Because I triggered `/azp run`, automation re-ran and detected you are missing breaking change approval. As a result, it removed your ARM sign-off. ARM will have to sign-off again after you fix up your breaking changes. See the diagram I shared above, steps 1 and 2.

Re this:

> However, as you can see, the entire PR comprises of these changes. Fixing it would just be deleting the PR. The change would not break any customer as the PUT/DELETE operations are modified to return a failure status code with a message officially stating the operation is not supported. While originally it just returned a failure code dictating "method not allowed". Customer's will not be building off of this as it does not exist, and will not after the PR as we are not adding any functionality in. We are just adding in the message for GA compliance.

You must follow the breaking change process to get your claims evaluated. If breaking change board approves, they will add `Approved-BreakingChange` label and then you can proceed to get your ARM review sign-off again. Again, please refer to the guidance in the link I shared. Breaking change approval is step 1 on the diagram, and ARM review and sign-off is step 2.

Sorry for the confusion!

**Pull request closed without merging**
