### PR TITLE
[Hub Generated] Review request for Microsoft.MachineLearning to add version 2017-01-01

### PR DESCRIPTION
**Pull request by xinzouMicrosoft-zz**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/xinzouMicrosoft/azure-rest-api-specs/dev-machinelearning-Microsoft.MachineLearning-2017-01-01).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@ravbhatnagar,  @xinzouMicrosoft  sent suppression approval request, please see email with subject "Violations Suppression requested for PR (Provide PR #)", could you take a look?

**Comment by xinzouMicrosoft** [comment]
@ravbhatnagar<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fravbhatnagar&data=02%7C01%7Cxinzou%40microsoft.com%7Cb2707459caf246979a5008d69ccb2cfd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636868793787850914&sdata=xYMBtgAgve7yYxS%2Bp4QcLsB7iLt7gUJdxEjN%2BPYjqFc%3D&reserved=0>,could you take a look at my PR when you have one chance? I submitted it one week ago.
Thanks in advance!

Regards,
Xin

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5467 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5467/commits/72de60ddcaad458705af65fc59d4267aa740533f

**Review by anuchandy — APPROVED** [review]

**Review by anuchandy — APPROVED** [review]
There is no breaking change in the server side, this PR updates swagger to match with service behavior, the service side logic don’t require the properties originally marked as required in PATCH operation.

**Pull request merged**
