### PR TITLE
Review request for Microsoft.StorageSync to update 2019-02-01 with support for parallel upload and download sync status tracking

### PR DESCRIPTION
**Pull request by anpint**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by anpint** [comment]
@praries880 could you please take a look at the PR?

**Comment by praries880** [comment]
@ravbhatnagar Can you review the PR?

**Review by ankushbindlish2 — APPROVED** [review]

**Comment by ravbhatnagar** [comment]
@anpint - looks like there are breaking changes to the preview api-version. Customers on this version can be broken. Are you aware and ok with that?

**Comment by ravbhatnagar** [comment]
@praries880 - Why doesnt the breaking change tool catch the property name changes as breaking change?

**Comment by anpint** [comment]
> @anpint - looks like there are breaking changes to the preview api-version. Customers on this version can be broken. Are you aware and ok with that?

Hi Gaurav. This API version (2019-02-01) is brand-new. The current state of this branch (dev-storagesync-Microsoft.StorageSync-2019-02-01) is that it contains the new API version 2019-02-01 as a copy of the previous API version. In this PR, we are introducing the actual protocol changes that will be in this new API version.

Currently, there are no publicly released clients using this API version, so I don't think there is any breaking change issue. Please let me know if anything needs more clarification.

**Comment by ravbhatnagar** [comment]
ok, sounds good and thanks for confirming! Signing off from ARM side!

**Review by praries880 — APPROVED** [review]

**Pull request merged**
