### PR TITLE
Update language support for Ocr and ImageAnalysis skills

### PR DESCRIPTION
**Pull request by Careyjmac**
Adding new languages for our OcrSkill and ImageAnalysisSkill as we have upgraded them to use Cognitive Services Computer Vision v3.2 which supports a lot more languages for both APIs. Language lists can be found here: https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/language-support

The OcrSkill also continues to support Greek and SerbianCyrillic using [the legacy OCR API](https://westus2.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2/operations/56f91f2e778daf14a499f20d) even though they are not listed at the above link

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [X] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  Is already deployed in backend, so we can update the SDK whenever.
  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  Is already deployed in backend, so we can update the SDK whenever.
  5. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Careyjmac** [comment]
Regarding the breaking changes, sr-Cyrl and sr-Latn are both still supported, our backend accepts any casing for the language codes, so this is not actually a breaking change, just really a change to be more consistent with the cognitive services docs. We can revert back to the original casing if we have to for the SDK purposes.

For 'nb' I actually hadn't noticed until just now that that language code had changed from 'nb' to 'no'. Norwegian is still supported just with the new language code. I was able to confirm with our telemetry that no one was previously using 'nb' so this should be safe to remove. If we absolutely have to support 'nb', then it will also require a backend hotfix as this was accidentally missed when implementing the new language support previously.

**Comment by Careyjmac** [comment]
> Regarding the breaking changes, sr-Cyrl and sr-Latn are both still supported, our backend accepts any casing for the language codes, so this is not actually a breaking change, just really a change to be more consistent with the cognitive services docs. We can revert back to the original casing if we have to for the SDK purposes.
> 
> For 'nb' I actually hadn't noticed until just now that that language code had changed from 'nb' to 'no'. Norwegian is still supported just with the new language code. I was able to confirm with our telemetry that no one was previously using 'nb' so this should be safe to remove. If we absolutely have to support 'nb', then it will also require a backend hotfix as this was accidentally missed when implementing the new language support previously.

I went ahead and changes the casing on sr-Cyrl and sr-Latn after writing a test to verify they work in the backend. I'm also re-adding "nb" in the backend for now just to avoid any issues.

**Comment by Careyjmac** [comment]
Only remaining ModelValidation failure is unrelated to this change.

**Review by JeffreyRichter — APPROVED** [review]

**Review by rysweet — APPROVED** [review]

**Comment by Careyjmac** [comment]
@johanste @mikekistler I was told one of you might be able to help us override the validation and merge this? The failure is unrelated to my change and I think its just an unfortunate issue with the way our API works (the maxRunTime duration isn't formatted in iso8601 when we return it) that we are stuck with.

**Pull request merged**
