### PR TITLE
Release apimangement 2022-08 01

### PR DESCRIPTION
**Pull request by solankisamir**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
@solankisamir, could you fix all the tool check errors?  For breaking change, please follow the below process:

Action: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

**Comment by solankisamir** [comment]
@lirenhe This PR is just a group of PRs which were reviewed before already and have all the validation and Breaking change approvals

https://github.com/Azure/azure-rest-api-specs/pull/21352
https://github.com/Azure/azure-rest-api-specs/pull/21595

**Comment by zzvswxy** [comment]
Hi @solankisamir  I see 
https://github.com/Azure/azure-rest-api-specs/pull/21352
https://github.com/Azure/azure-rest-api-specs/pull/21595
But they are part of this PR. So I want to make sure are all breaking changes and Lint diff errors are reviewed. Thanks

**Comment by zzvswxy** [comment]
Another thing, as ApiReadinessCheck failed, Is service release date confirmed? can you provide? Thanks

**Comment by solankisamir** [comment]
@zzvswxy the ApiReadiness date is 2/10/2023

**Comment by zizw123** [comment]
It seems all the commits in the PR has already been reviewed before? What is new on this PR?

Please also check the lintDiff errors.

Thanks

**Comment by zzvswxy** [comment]
Hi @qiaozha @tadelesh  , can you help me to review the js and go SDK breaking changes? Thanks

**Comment by zizw123** [comment]
> It seems all the commits in the PR has already been reviewed before? What is new on this PR?
> 
> Please also check the lintDiff errors.
> 
> Thanks

Synced offline, all changes are already reviewed and released. Please track these lint errors in a workitem, when the next API version in introduced, you should fix them.

**Comment by tadelesh** [comment]
@solankisamir Please resolve the duplicate schema problem of `ProxyResource`.

**Comment by zzvswxy** [comment]
Hi @solankisamir   For duplicated-schema, here is the doc how to fix it: https://github.com/Azure/azure-rest-api-specs/wiki/Common-CI-Error#duplicated-schema

**Comment by zzvswxy** [comment]
About Lint diff, 
LroLocationHeader: https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md
image
@solankisamir  please pay attention to these errors.

**Comment by solankisamir** [comment]
@zzvswxy arm team also signed off

**Comment by zzvswxy** [comment]
Hi @solankisamir  I talk with SDK owners and LintDiff check maintainer. Their requirement are list in the comment above. They both consider the issues need to be fixed. So can you fix it? Thanks

**Comment by solankisamir** [comment]
> 

What is the problem with ProxyResource, I could not find any error logs
@zzvswxy  I have created another PR for just Linter Errors

https://github.com/Azure/azure-rest-api-specs/pull/22537

**Comment by zzvswxy** [comment]
> What is the problem with ProxyResource, I could not find any error logs

`ProxyResource` error shows in SDK generation pipeline. You can find more error info by this way:
For example, python SDK:
image
Then you can see
image
Click [View more details on Swagger Pipeline](https://dev.azure.com/azure-sdk//internal/_build/results?buildId=2167898&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691) you can find the full log.
image

About how to fix: 
SDK owner give a wiki https://github.com/Azure/azure-rest-api-specs/wiki/Common-CI-Error#duplicated-schema

This error cause both .NET/Go/Python SDK generation failed. So the SDK owners think it's necessary to fix the `ProxyResource` error.

**Comment by solankisamir** [comment]
> > What is the problem with ProxyResource, I could not find any error logs
> 
> `ProxyResource` error shows in SDK generation pipeline. You can find more error info by this way: For example, python SDK: image Then you can see image Click [View more details on Swagger Pipeline](https://dev.azure.com/azure-sdk//internal/_build/results?buildId=2167898&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691) you can find the full log. image
> 
> About how to fix: SDK owner give a wiki https://github.com/Azure/azure-rest-api-specs/wiki/Common-CI-Error#duplicated-schema
> 
> This error cause both .NET/Go/Python SDK generation failed. So the SDK owners think it's necessary to fix the `ProxyResource` error.

Ok found the issue with duplicate schema and fixed that error in the pr https://github.com/Azure/azure-rest-api-specs/pull/22537

**Comment by zzvswxy** [comment]
Hi @msyyc  @qiaozha  can you help me to review the Python and JS SDK breaking changes? Thanks

**Comment by solankisamir** [comment]
@zzvswxy how does it look after the merge? Can we merge to main branch?

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
