### PR TITLE
Swagger for Azure Data Lake Storage Gen2 (Preview)

### PR DESCRIPTION
**Pull request by ThomasMarquardt**
Azure Data Lake Storage provides storage for Hadoop and other big data workloads.

Reference: https://github.com/Azure/azure-rest-api-specs-pr/pull/503

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@ThomasMarquardt I see we have some other DataLake swaggers checked in under the following directory.
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datalake-store/data-plane/Microsoft.DataLakeStore
Is this new swagger related to them, i.e. should this be under the same subdirectory?

**Comment by ThomasMarquardt** [comment]
@seguler I followed the pattern used by other teams, and omitted the dot in Microsoft.Storage.DataLake.

**Comment by lmazuel** [comment]
@seguler I'm not sure we should check-in Swagger per ownership, but more per branding/advertising. How this will be declared here?
https://azure.microsoft.com/en-us/services/#storage

Like, when Table left Storage, it was officially renamed "CosmosDB". Will this service be renamed "Storage" and the brand DataLake disappears?

Folder should be named by customer point of view, not by Microsoft internal point of view.

**Comment by jhendrixMSFT** [comment]
@seguler if you don't want auto-generated content you need to remove the swagger-to-sdk section in the README file (lines 48-58).

**Comment by jhendrixMSFT** [comment]
@seguler Oh and when you remove these lines please be sure to replace them with a note explaining that we don't want auto-generation enabled for this swagger.

**Comment by jhendrixMSFT** [comment]
@ThomasMarquardt there are no examples included for these operations.  While this won't block the PR these kinds of omissions will show up in S360.  Is there a timeline when they'll be added?

**Comment by ThomasMarquardt** [comment]
Thanks for making the change to not publish SDKs.  I'm aware that we do not have examples.  We can address later if there is an issue.  Let's publish what we have.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
