### PR TITLE
Amalladi/extendedlocation update

### PR DESCRIPTION
**Pull request by aditimalladi**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify : Updating existing API Version to remove 400 error code from responses (default error response code has been defined with ErrorResponse Schema which can handle all unexpected/ error codes.). Removing Private Preview API Version from repo.
     

  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by aditimalladi** [comment]
@chunyu3 Can we get a review for this PR?

**Comment by chunyu3** [comment]
Hi @aditimalladi There are breaking changes in your PR (removing response code in existing api-version. You can release a new API-version for those changes. Otherwise, you need to acquire breaking change approval. Thanks

**Comment by aditimalladi** [comment]
@chunyu3 The current change is removing a error response code from the Manifest, but the default Error Response is still defined, hence for any errors of the response code(that is being removed) will continue to be handled and functionality would not change.

**Comment by aditimalladi** [comment]
### Change: 
Removing StatusCode BadRequest from error responses from Swagger

### Reason for removing:

All unexpected error codes are returned are defaulted to ErrorResponse type (as we have already specified the default schema for each operation)
Need to define a schema for errors returned so they are correctly parsed from calls to the RP

### User/Customer Impact:
Once this explicit error code is removed, 400 status codes will also default to the Default Error Schema defined and the error message returned from the RP will be parsed.

### Why is this change required
From generating the Python SDK from the older Swagger file and running CLI commands the Errors Returned from the RP were not being parsed, hence the error messages were not visible. With this change, the SDK calls do return an error message that is returned from the RP

**Review by JeffreyRichter — APPROVED** [review]

**Comment by aditimalladi** [comment]
@chunyu3 PR has been approved for Breaking Change, can I get a review?

**Comment by chunyu3** [comment]
hi @aditimalladi If the PR is approved for breaking changes, please ask 'breaking change' reviewer to label 'Approved-breakingChange' to unblock the merge. Thanks

**Comment by aditimalladi** [comment]
Hi @chunyu3 Approved Breaking Changes Tag has been added. Can this PR be reviewed?

**Pull request merged**
