### PR TITLE
[Microsoft.StorageSync] Add new cloud tiering status for 2019-10-01 protocol

### PR DESCRIPTION
**Pull request by anpint**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by ankushbindlish2 — APPROVED** [review]

**Review by pilor — APPROVED** [review]

**Comment by anpint** [comment]
@pilor Thanks for approving the changes.

**Comment by allenjzhang** [comment]
Looks like Subscription's readme.go.md is out of date and did not get updated. Could you please review the [logs](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=250564&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=530) and see if you can get automation SDK GO to pass?

**Comment by anpint** [comment]
> Looks like Subscription's readme.go.md is out of date and did not get updated. Could you please review the [logs](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=250564&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=530) and see if you can get automation SDK GO to pass?

@allenjzhang Sorry for the confusion, I didn't intend to change the subscriptions readme.md file. I reverted that change.

**Comment by anpint** [comment]
@allenjzhang Thanks for your help with this pull request. It looks like it's ready to be merged.

**Pull request merged**
