### PR TITLE
Release sentinel 2023 04 01 preview

### PR DESCRIPTION
**Pull request by samuelkuangms**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [X] new service onboarding
      - [X] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [X] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[X] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [X] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zizw123** [comment]
Please get breaking change reviewed and come back for ARM review

**Comment by nazang** [comment]
@zizw123 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/nazang/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/nazang/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/nazang/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#96607D" style='tab-interval:.5in;word-wrap:
break-word'>


<p class=MsoNormal style='mso-margin-top-alt:auto;margin-bottom:12.0pt;
line-height:normal'><span style='font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman";mso-font-kerning:0pt'>All the new
changes on this branch has been reviewed and signed off by ARM review team. <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;margin-bottom:12.0pt;
line-height:normal'><span style='font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman";mso-font-kerning:0pt'>We have 3
breaking changes flagged and we have gone through the ARM breaking change
review process, the office hour on 4/10. This is the ADO item to track the
work: <a href="https://msazure.visualstudio.com/One/_workitems/edit/17908651"
target="_blank"
title="https://msazure.visualstudio.com/one/_workitems/edit/17908651">Scenario
17908651: Cross version validation for release-Sentinel-2023-04-01-preview -
Boards (visualstudio.com)</a><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;margin-bottom:12.0pt;
line-height:normal'><span style='font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman";mso-font-kerning:0pt'>1. One is
approved by Mike.<o:p></o:p></span></p>

<p style='margin:0in'>2. Two changes on watchlist are still in review, and
following up with Mike. This breaking change was introduced on 2022-01-01
Preview by the following PR.<span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif'><o:p></o:p></span></p>

<p><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif'><a
href="https://github.com/Azure/azure-rest-api-specs/pull/18025" target="_blank"
title="https://github.com/azure/azure-rest-api-specs/pull/18025">Dev sentinel
2022 01 01 preview by anat-gilenson · Pull Request #18025 ·
Azure/azure-rest-api-specs (github.com)</a><o:p></o:p></span></p>



❌ 1025   - RequiredStatusChange | The   'required' status changed from the old version('True') to the new   version('False').   New: Microsoft.SecurityInsights/preview/2023-04-01-preview/Watchlists.json#L481:7   Old: Microsoft.SecurityInsights/stable/2023-02-01/Watchlists.json#L469:7 | 4/10 office   hour   Follow up:   provide evidence of approval from past. Hassan to follow up
-- | -- | --
❌ 1049   - RemovedXmsEnum | The new   version is missing a 'x-ms-enum' found in the old version.   New: Microsoft.SecurityInsights/preview/2023-04-01-preview/Watchlists.json#L494:9   Old: Microsoft.SecurityInsights/stable/2023-02-01/Watchlists.json#L482:9 | 4/10 office   hour   Follow up:   provide evidence of approval from past. Hassan to follow up



<p class=MsoNormal style='mso-margin-top-alt:auto;margin-bottom:12.0pt;
line-height:normal'><span style='font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman";mso-font-kerning:0pt'>&nbsp;<o:p></o:p></span></p>


</body>

</html>

**Comment by mikekistler** [comment]
Breaking changes previously approved in #22983

**Comment by zizw123** [comment]
Signing off, most commits in this PR have been signed off before, the diffs are typo fixing.

**Comment by tadelesh** [comment]
@MaryGao @msyyc could you help to review the SDK breaking changes?

**Comment by nazang** [comment]
@tadelesh @zizw123 , it seems we got all the approvals. Can we get a final approval and merge please?

**Comment by tadelesh** [comment]
Sync with js sdk owner. Approved the sdk breaking.

**Review by tadelesh — APPROVED** [review]

**Pull request merged**
