### PR TITLE
[Don't Merge] Azure Site Recovery - Replication cluster APIs

### PR DESCRIPTION
**Pull request by pradheepm**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raosuhas** [comment]
Can you please fix the various errors introduced by the PR here from the automated checks for "Swagger LintDiff": 
https://github.com/Azure/azure-rest-api-specs/pull/23281/checks?check_run_id=12260762129

**Comment by rkmanda** [comment]
Please fix the following errors showing up in the automated checks
https://github.com/Azure/azure-rest-api-specs/pull/23281/checks?check_run_id=12853628438

MUST fix
[LroErrorContent](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-error-content.md)
[LroPostReturn](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-post-return.md)
[ProvisioningStateSpecifiedForLROPut](https://github.com/Azure/azure-openapi-validator/blob/main/docs/provisioning-state-specified-for-lro-put.md)

Fixes to consider 
[PutResponseSchemaDescription](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-response-schema-description.md)

**Review by ihsanali01 — APPROVED** [review]

**Comment by rkmanda** [comment]
>           "final-state-via": "azure-async-operation"

either remove final-state-via OR specify the value as "original-uri"

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:4775 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationFabrics/{fabricName}/replicationProtectionContainers/{protectionContainerName}/replicationProtectionClusters/{replicationProtectionClusterName}/operationresults/{jobId}": {

If this is tracking the long running delete operation for /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationFabrics/{fabricName}/replicationProtectionContainers/{protectionContainerName}/replicationProtectionClusters/{replicationProtectionClusterName}

move this under 
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationFabrics/{fabricName}/replicationProtectionContainers/{protectionContainerName}

instead. This is because when the parent is deleted, the client will get a not found when polling for the operation result which is not ideal 

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:4867 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "final-state-via": "location"

specify the final schema that will be returned to the client using final-state-schema

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:5021 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "final-state-via": "location"

pl check everywhere

---
In reply to: [1515669911](https://github.com/Azure/azure-rest-api-specs/pull/23281#issuecomment-1515669911) [](http://example.com/codeflow?ancestors=1515669911)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:5021 in 0b9e7fa. [](commit_id = 0b9e7fa44ce80f5ddbd8495751568842b5ce8409, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "A2AClusterUnplannedFailoverInput": {

unused?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:8813 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "type": "string"

specify format: arm-id if this is a fully qualified resourceId

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:9188 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "type": "string"

check this everywhere

---
In reply to: [1515672065](https://github.com/Azure/azure-rest-api-specs/pull/23281#issuecomment-1515672065) [](http://example.com/codeflow?ancestors=1515672065)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:9188 in 0b9e7fa. [](commit_id = 0b9e7fa44ce80f5ddbd8495751568842b5ce8409, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "individualNodeRecoveryPoints": {

specify x-ms-identifier

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:8826 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "rpoInSeconds": {

is there are range of values that are not permissible. Specify valid range with minimum and maximum constraints

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:10262 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "lifecycleId": {

Can this not be generated by the service and mentioned a a readOnly property?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:10312 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "A2ASharedDiskIRErrorDetails": {

What does this error contract represent? We will need more scenario context to understand why the standard error contracts of ARM would not suffize.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:10358 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "failoverDirection": {

define this as an enum

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:11438 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "instanceType": {

enum?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:11459 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "ReplicationProtectionCluster": {

use the common type for ProxyResource

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:22405 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "protectionClusterType": {

enum?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:22452 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "type": "string"

format:"arm-id"

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:22470 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "protectionState": {

enum?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:22480 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "x-ms-identifiers": []

fill this with the property set that identifies a unique element in the array

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:22569 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "ServiceDefaultError": {

use the common error contract defined at 

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:23137 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "protectionState": {

enum?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-03-01/service.json:23214 in b3460cc. [](commit_id = b3460cc80b9f38c30c0e82580b7591ee66244377, deletion_comment = False)

**Pull request closed without merging**
