### PR TITLE
Create base of release-sql-Microsoft.Sql-2024-08-01-preview via Copy-ApiVersion.ps1

### PR DESCRIPTION
**Pull request by ericshape**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by rkmanda — APPROVED** [review]
:shipit:

**Comment by ericshape** [comment]
I just rebased to the latest main and push the release branch. 
it brought a lot of commits which were introduced last week.

**Comment by ericshape** [comment]
just revert the rebase from main. 
too many noise from the main branch.

**Comment by ericshape** [comment]
run 
npx prettier --write specification/sql/**/*.json
to fix the prettier pipeline.

**Pull request merged**
