### PR TITLE
[Hub Generated] Review request for Microsoft.VirtualMachineImages to add version stable/2020-02-14

### PR DESCRIPTION
**Pull request by rezmicrosoft-zz**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/rezmicrosoft/azure-rest-api-specs/dev-imagebuilder-Microsoft.VirtualMachineImages-2020-02-14...master/).

The private repo PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/1156

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by rezmicrosoft** [comment]
The private repo PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/1156

**Comment by njuCZ** [comment]
Prettier check of file `ListImageTemplatesByRg.json` failed, please fix it @rezmicrosoft

**Comment by rezmicrosoft** [comment]
> Prettier check of file `ListImageTemplatesByRg.json` failed, please fix it @rezmicrosoft

@njuCZ . I have ran prettier against all files, and `ListImageTemplatesByRg.json` has been resolved. While seems like `imagebuilder.json` is still failing, but my local prettier shows that this file is good. By the way, my prettier version is 1.19.1.

**Review by ravbhatnagar — APPROVED** [review]
SIgning off from ARM side.

**Comment by njuCZ** [comment]
@ravbhatnagar If arm team has signed off this PR, please remove the label `waitforarmfeedback` and add `armsignedoff` label

**Review by njuCZ — APPROVED** [review]

**Pull request merged**
