### PR TITLE
Update ci-fix.md: link with EngHub docs + cleanup

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
This is a PR made by the Azure SDK Engineering System team

This PR contributes to the "Migrate "OpenAPI Spec Authoring & Validation tools" to Eng Hub" task
- https://github.com/Azure/azure-sdk-tools/issues/6711

Companion PR:
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/791

### CODE REVIEW

**Review by ccbarragan — APPROVED** [review]
Thanks for updating with the new links 🚀  LGTM

**Comment by konrad-jamrozik** [comment]
Filed a bug to track spurious breaking change failure:
- https://github.com/Azure/azure-sdk-tools/issues/6851

**Pull request merged**
