### PR TITLE
[do not merge] New NRP API version. Adding Sku property for publicIPAddress and LoadBalancer

### PR DESCRIPTION
**Pull request by gmainar**
Adding Sku property for publicIPAddress and LoadBalancer

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by gmainar** [comment]
Please, review but don't merge.

**Comment by olydis** [comment]
please update the `readme.md` of NRP to contain the new API version. Just duplicate the `package-2017-06` section, and change the top most tag to `package-2017-08` as indicated here:

image

**Review by olydis — APPROVED** [review]
Please update the configuration file as described. The new features look good to me.

**Comment by olydis** [comment]
@gmainar Awesome! Of course, I wanna encourage you (= everyone involved) to take the chance and fix linter/validation problems. 🙂

**Comment by olydis** [comment]
actually, what about the `UpgradeLog.htm` that is part of this PR? missed that file before since its contents are hidden in the "Files changed" tab...

**Comment by olydis** [comment]
Will close since it is not supposed to be merged. Feel free to reopen if that changes.

**Pull request closed without merging**
