### PR TITLE
  Azure Container Instance: Add start container group API

### PR DESCRIPTION
**Pull request by xuto2**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@xito2 could you have a look live validation issues in portal?

**Comment by xuto2** [comment]
@sergey-shandar I'd love to. Do you have any instructions on how to do that?

**Comment by sergey-shandar** [comment]
@xuto2 use [this link](https://portal.azure-devex-tools.com/app/branch/xuto2/azure-rest-api-specs/master) as MSFT to check live validations.

**Review by sergey-shandar — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
