### PR TITLE
[Hub Generated] Review request for Microsoft.DataProtection to add version stable/2022-01-01

### PR DESCRIPTION
**Pull request by pratikjoshi14**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/pratikjoshi14/azure-rest-api-specs/dev-dataprotection-Microsoft.DataProtection-2022-01-01...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by xiaoxuqi-ms** [comment]
Hi @pratikjoshi14 please fix the errors of failed checks.

**Comment by mentat9** [comment]
>           }

Might want to consider factoring the operationId parameter out to the parameters section, since it's used in 3 new places. Either way, it would be nice to add a description indicating what it is, where it comes from, what format it has, etc. This isn't blocking ARM signoff, just a suggestion.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1403 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/stopProtection": {

Is there a reason that protections are stopped/resumed, whereas backups are suspended/resumed? I'd recommend consistent naming here. Unless there is a good reason that protections should be 'stop', I think 'suspend' is a better verb.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1847 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/sync": {

Any reason this isn't 'retry'? Also, how is this different from PUTting again?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1981 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "Fully qualified ARM ID of the datasource which is being recovered.",

Azure Resource Manager

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:3915 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
>         "value": {

This appears to be adding a secret to to GET payloads, which isn't allowed. If secrets need to be retrieved, it needs to be done via a separate POST action, so it can have its own RBAC separate from the rest of the resource.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5939 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
>         "value": {

Secrets need to be tagged with x-ms-secret. Ref: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret).

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5939 in 63a558f. [](commit_id = 63a558f3569129ac8b1de73c2ec71e3c68124185, deletion_comment = False)

**Comment by mentat9** [comment]
@pratikjoshi14, please add back the WaitForARMFeedback when you are ready for revisit: that will notify the current oncall that your PR is ready for revisit.

**Comment by pratikjoshi14** [comment]
> > ```
> >       }
> > ```
> 
> Might want to consider factoring the operationId parameter out to the parameters section, since it's used in 3 new places. Either way, it would be nice to add a description indicating what it is, where it comes from, what format it has, etc. This isn't blocking ARM signoff, just a suggestion.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1403 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)



> @pratikjoshi14, please add back the WaitForARMFeedback when you are ready for revisit: that will notify the current oncall that your PR is ready for revisit.

Apologies for the delay. Was on sick leave. I have started resolving comments now.

**Comment by pratikjoshi14** [comment]
> > ```
> >     "value": {
> > ```
> 
> Secrets need to be tagged with x-ms-secret. Ref: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5939 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)

It is actually a reference to secret. Like KeyVault URL. Hence it is not marked as secret.
Also it is existing change which was reviewed by ARM team. Please let me know if still there are any concerns.

**Comment by pratikjoshi14** [comment]
> > ```
> >     "value": {
> > ```
> 
> This appears to be adding a secret to to GET payloads, which isn't allowed. If secrets need to be retrieved, it needs to be done via a separate POST action, so it can have its own RBAC separate from the rest of the resource.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5939 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)

Same as the other comment:
It is actually a reference to secret. Like KeyVault URL. Hence it is not marked as secret.
Also it is existing change which was reviewed by ARM team. Please let me know if still there are any concerns.

**Comment by pratikjoshi14** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/stopProtection": {
> > ```
> 
> Is there a reason that protections are stopped/resumed, whereas backups are suspended/resumed? I'd recommend consistent naming here. Unless there is a good reason that protections should be 'stop', I think 'suspend' is a better verb.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1847 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)

Great question ! There are two reasons behind this:
1) Protection is a complex operation which consists of Backup, GC of expired data, moving data across various types of storage formats etc. Hence our product team through of Stop verb for Protection.
2) We also have another legacy RP (sort of like V1) which follows this naming and customers are already used to it. Hence we wanted to retain that format.

**Comment by pratikjoshi14** [comment]
> > ```
> >       }
> > ```
> 
> Might want to consider factoring the operationId parameter out to the parameters section, since it's used in 3 new places. Either way, it would be nice to add a description indicating what it is, where it comes from, what format it has, etc. This isn't blocking ARM signoff, just a suggestion.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1403 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)

Fair point. We did not add operationId in parameters section because this parameter is not actually passed by the user. It is returned by the service as part of locations/operation status headers which users poll on.
Please let us know if you still think it should be added to parameters section.

**Comment by pratikjoshi14** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/sync": {
> > ```
> 
> Any reason this isn't 'retry'? Also, how is this different from PUTting again?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1981 in [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185). [](commit_id = [63a558f](https://github.com/Azure/azure-rest-api-specs/commit/63a558f3569129ac8b1de73c2ec71e3c68124185), deletion_comment = False)

Thanks for the feedback. We have a master service which owns ARM based resources and some agent services which own part of the resource for example one service owns backup schedules, one service owns GC. Whenever we update resource in master service, we start syncing the same resource to agent services. If that syncing failed despite internal retries, we put the resource in a special error state indicating master service and agent are out-of-sync and a manual sync is needed.
This is a very rare scenario. We have exposed this to the user for now but the plan it to integrate this api internally with auto-heal framework to avoid manual/user intervention.
Please let us know if this approach is fine or if you have more questions.

**Comment by pratikjoshi14** [comment]
> Fully qualified ARM ID of the datasource which is being recovered

Fixed.

**Comment by pratimaupadhyay02** [comment]
@msyyc can u please review the python SDK breaking change tracking failure?

**Comment by rkmanda** [comment]
>         "description": "Sync backup instance again in case of failure\r\nThis action will retry last failed operation and will bring backup instance to valid state",

What specific operation is being referred to here?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1992 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by pratikjoshi14** [comment]
> > ```
> >     "description": "Sync backup instance again in case of failure\r\nThis action will retry last failed operation and will bring backup instance to valid state",
> > ```
> 
> What specific operation is being referred to here?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1992 in [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5). [](commit_id = [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5), deletion_comment = False)

So Backup instance has many operations like update policy, stop backups, stop GC of data. If any of these operations failed in between (lets say due to storage and network outage), leaving master service and agents out-of-sync, this operation force syncs data again between them making them consistent.

**Comment by rkmanda** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/operationStatus/{operationId}": {

Note to self: checking if the guidance here is to make this a subscription level resource

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:184 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/operationStatus/{operationId}": {

This is being done so that the customers dont have to give subscription level access to the users of the PUT operation

---
In reply to: [1043818232](https://github.com/Azure/azure-rest-api-specs/pull/17261#issuecomment-1043818232) [](http://example.com/codeflow?ancestors=1043818232)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:184 in ebe6ac3. [](commit_id = ebe6ac33f6bb6a77885cd251785b688cb8f2ad0e, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "202": {

202 is not a recommended pattern for long running PUTs. Why do you need this?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1119 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "202": {

remove. 202 for GET doesnt make sense

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1412 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by pratikjoshi14** [comment]
> > ```
> >       "202": {
> > ```
> 
> 202 is not a recommended pattern for long running PUTs. Why do you need this?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1119 in [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5). [](commit_id = [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5), deletion_comment = False)

Before doing PUT of a resource (Backup Instance), we have exposed a POST /validate API to make sure all the permissions are in place. Once POST is successful, users call PUT and it creates resource in async way by returning 201 Created.

Now a small portion of our users who are using ARM template based deployments cannot call POST API. If they called PUT directly many of their resources were getting created in failed state as PUT requires many RBACs to be properly set. It was affecting our SLA, also it was not a desired customer scenario.

So these customers wanted to do in-line validations before starting with resource creation as part of PUT only by passing a new optional flag asking for DeepValidations. Only for those users, PUT would now return 202 Accepted as resource would yet to be created.

This will not impact all existing users as by default 201 is returned.

**Comment by pratikjoshi14** [comment]
> > ```
> >       "202": {
> > ```
> 
> remove. 202 for GET doesnt make sense
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1412 in [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5). [](commit_id = [8d5d657](https://github.com/Azure/azure-rest-api-specs/commit/8d5d6577b31ab5b18b84d9cf67de1e923a01dea5), deletion_comment = False)

Thanks for catching this.. removing

**Comment by rkmanda** [comment]
>           "description": "Specifies the type of validation.",

Add some description for what each type of validation means

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:4139 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "value": {

can this be a secret? if so annotate with x-ms-secret

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5959 in 8d5d657. [](commit_id = 8d5d6577b31ab5b18b84d9cf67de1e923a01dea5, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "value": {

this was signed off in preview

---
In reply to: [1043856701](https://github.com/Azure/azure-rest-api-specs/pull/17261#issuecomment-1043856701) [](http://example.com/codeflow?ancestors=1043856701)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:5959 in ebe6ac3. [](commit_id = ebe6ac33f6bb6a77885cd251785b688cb8f2ad0e, deletion_comment = False)

**Review by rkmanda — CHANGES_REQUESTED** [review]
:clock1:

**Comment by pratikjoshi14** [comment]
> Specifies the type of validation

Changed description.

**Comment by pratikjoshi14** [comment]
> remove. 202 for GET doesnt make sense

It is get on operationsResults (location header) which expects us to return 202 for inprogress operations:
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#202-accepted-and-location-headers

**Comment by rkmanda** [comment]
>           "202": {

didnt notice this was for operationresult

---
In reply to: [1043827062](https://github.com/Azure/azure-rest-api-specs/pull/17261#issuecomment-1043827062) [](http://example.com/codeflow?ancestors=1043827062)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-01-01/dataprotection.json:1412 in ebe6ac3. [](commit_id = ebe6ac33f6bb6a77885cd251785b688cb8f2ad0e, deletion_comment = False)

**Review by rkmanda — APPROVED** [review]
:shipit:

**Comment by pratikjoshi14** [comment]
@xiaoxuqi-ms : Can you please complete the swagger PR?

**Pull request merged**
