### PR TITLE
Azure Mobile Engagement specifications

### PR DESCRIPTION
**Pull request by guperrot**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@guperrot__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (guperrot). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
As this is the first commit and the file is lengthy, the PR does not show the entire file. Hence, I am not able to comment on the specific line.

**Comment by amarzavery** [comment]
OperationId: Devices_QueryDevice seems to be a perfect candidate for pageable operations. Please look at the paging extension documentation over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Paging-x-ms-pageable). By adding this extension you will get the value property containing array of items flattened

**Comment by amarzavery** [comment]
I am sorry if I wasn't clear. I will review the PR. It's just that, since this is the first commit and the file is lengthy, the PR does not show the entire file. Hence, I will not be able to comment on the line where I find the issue. Instead, I shall be commenting here and will provide a line number or some other reference, so it is easy for you to find out the location corresponding to the comment.

**Comment by amarzavery** [comment]
Line number 24: OperationID: Devices_QueryDevice: The general format for an operationId should be {name}_{verb}. This keeps things simple and would make it easy for the end user while using intellisense. This would translate to 
```
client.Devices.QueryDevice(). 
```
However, 
```
client.Devices.Query()
```
 would be more concise.

Also, naming this operation as list instead of query would make more sense.

**Comment by amarzavery** [comment]
Line 2380: "CampaignResult" has a property state which has an enum. Please apply the extension "x-ms-enum" after reading the documentation over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum)

**Comment by amarzavery** [comment]
Line 2387 and 2391: Do you want to add `"format":"date"` for activatedDate and finishedDate properties of "CampaignResult"? Please take a look at the Open API documentation over [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#dataTypeFormat).

If you add `"format":"date"` then the generated code will accept Date objects in that language (C#, NodeJS, Python, etc.) and will perform Date validation as well.

**Comment by amarzavery** [comment]
"x-ms-enum" for "op" property of "integer-tag" and "Boolean-tag".

**Comment by amarzavery** [comment]
Line 2120: "description": "It can be either:\n* an absolute date using CCYY-MM-DD format..."
CCYY-MM-DD should this be YYYY-MM-DD or is it intentional.

**Comment by amarzavery** [comment]
Line 1953: You might want to take a look at the [extension x-ms-discriminator-value](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-discriminator-value), if that is applicable to you as your definition names have dashes in it.

**Comment by amarzavery** [comment]
line 1919: datapush-feedback.action is an enum. Check the x-ms-enum documentation and add it in the spec as per your requirement.

**Comment by amarzavery** [comment]
For the operation: Devices_GetByUserId. This is a question about the design of your service API, Is it possible that a user can have multiple devices registered (because this operation only returns information about a particular device) ?

**Comment by amarzavery** [comment]
Line 174: AppCollections_List: This should have the x-ms-pageable extension

**Comment by amarzavery** [comment]
Line 273: "operationId": "CheckAppCollectionNameAvailability". It does not have the format {noun}_{verb}. Hence this will be an operation on the client v/s an it being a part of the operation group. Ignore this comment if that is the desired behavior.

**Comment by amarzavery** [comment]
nitpick:
Line 127: userid and Line 80: deviceid should follow the same naming Convention as subscriptionId. (I uppercase)

**Comment by amarzavery** [comment]
Line 313: "operationId": "Campaigns_List", should have the extension x-ms-pageable

**Comment by amarzavery** [comment]
Line 336: kind enum should have the extension x-ms-enum

**Comment by amarzavery** [comment]
Line 400: "operationId": "Campaigns_Create", is a long running operation. It should be marked with extension ["x-ms-long-running" : true](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#longrunning). Upon adding the extension the generated code will do the polling until one of the terminal states "Success", "Failure" "Cancelled" and then return.

**Comment by guperrot** [comment]
Campaigns_Create does not support long running for now.
AppCollections list does not support pagination yet.
Those are APIs are already live in prod, the spec matches what we can support.
We'll consider those changes as part of separate work items if you don't mind ignoring those for now.

**Comment by amarzavery** [comment]
sure

**Comment by amarzavery** [comment]
It would have saved my time, if it was mentioned earlier in the PR description as I don't know much about your service and mostly reviewing the swagger spec to ensure if you are not missing any possible Azure patterns.

**Comment by guperrot** [comment]
I had no idea this was a requirement for the PR to be accepted, I am new to this ;)

**Comment by amarzavery** [comment]
Otherwise the PR looks good. 
In general, make sure that the enums are marked properly with "x-ms-enum" extension as per the documentation. Address the feedback for the PR to be merged. Once your PR is ready, please send an email to azsdkcode@microsoft.com with a request to review the PR.

**Comment by guperrot** [comment]
Hi, thanks for your review.
I'll forward this to the developer who will address the changes.

**Comment by guperrot** [comment]
userid is a special tag key.

This API is from a migrated product, capptain.com, and thus some names and case are inherited from there.
We don't want to change the casing in this API version as this would impact migrating customers from Capptain (they want to minimize changes to their code).

We are considering renaming those in future API versions.

Devices_GetByUserId: for now its a 1:1 mapping and updating userid updates the mapping.

If this changes it would in a new API version.

**Comment by guperrot** [comment]
CC in CCYY-MM-DD means century, but actually our Java server implementation calls that "yyyy-MM-dd", we should indeed change the documentation because some people don't know what CC means and it can be confusing.

**Comment by amarzavery** [comment]
awesome. LGTM

**Comment by guperrot** [comment]
Thanks!

**Pull request merged**
