### PR TITLE
[READY TO MERGE ] Migrate version to 2019-05-01 in new folder and Adding usages by VM family support

### PR DESCRIPTION
**Pull request by leizhaoPS**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by leizhaoPS** [comment]
@amarzavery , MachineLearningServices is upgrade to 2019-05-01, this PR only copy files from version "2018-11-09" to "2019-05-01" and rename the version, there is no other content changes, please help approve, as soon as it checked-in I will work on content changes for usages in another PR. Let me know if any problems, Thanks a lot!

**Comment by lmazuel** [comment]
@leizhaoPS your branch is 188 commits behind master, please merge master onto your PR to enable all bots and CI behaviors. Thanks.

**Comment by leizhaoPS** [comment]
@amarzavery , I confirmed with the team that they want publish service support for the this version first then publish swagger. I don't need merge immediately now.

**Comment by leizhaoPS** [comment]
@amarzavery, can you help add "WaitForARMFeedback" flag to the PR, and Add Kristopher Bash <krbash@microsoft.com> , Gaurav Bhatnagar <Gaurav.Bhatnagar@microsoft.com> to the reviewers. Thanks very much!

**Review by majastrz — APPROVED** [review]
Looks good.

**Comment by leizhaoPS** [comment]
@amarzavery,  @majastrz ,could you please help us merge the PR to Master as soon as possible? Our Feature is relay on this to be check-in,  Please let me know if any action I need take.

**Review by amarzavery — APPROVED** [review]

**Pull request merged**
