### PR TITLE
2017-03-01 version of Api Management Spec

### PR DESCRIPTION
**Pull request by solankisamir**
2017-03-01 Arm Compliant API Version which fixes issue
 - https://github.com/Azure/azure-rest-api-specs/issues/1060
 - https://github.com/Azure/azure-rest-api-specs/issues/893

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by fearthecowboy — CHANGES_REQUESTED** [review]
Hey @solankisamir ,

I'm seeing a lot of linting rule errors - the ARM team is getting a lot stricter with making sure that the rest specifications meet their engineering criteria.

You can install the latest autorest:

``` bash
npm install -g autorest
autorest --reset
```

and then to see the linting errors, you can run the validator on each file:

`autorest --azure-arm=true --azure-validator --input-file=.\apimanagement.json`

and it will produce a list of the issues for the rules that the ARM team has asked that the teams meet.


--- 
If you want to see the whole set, create a `readme.md` file in the same folder as the composite swagger file that contains:

~~~ markdown
# ApiManagement
    
> see https://aka.ms/autorest

This is the AutoRest configuration file for ApiManagement.



---
## Getting Started 
To build the SDK for ApiManagement, simply [Install AutoRest](https://aka.ms/autorest/install) and in this folder, run:

> `autorest`

To see additional help and options, run:

> `autorest --help`
---

## Configuration for generating APIs


---
#### Basic Information 
These are the global settings for the ApiManagement API.

``` yaml
# common 
title: ApiManagementClient
description: ApiManagement Client
tag: 2017-03-01
azure-validator: true
azure-arm: true
```


# Tag 2017-03-01

``` yaml
input-file:
    - 2017-03-01/swagger/apimanagement.json
    - 2017-03-01/swagger/apimapis.json
    - 2017-03-01/swagger/apimauthorizationservers.json
    - 2017-03-01/swagger/apimbackends.json
    - 2017-03-01/swagger/apimcertificates.json
    - 2017-03-01/swagger/apimdeployment.json
    - 2017-03-01/swagger/apimgroups.json
    - 2017-03-01/swagger/apimidentityprovider.json
    - 2017-03-01/swagger/apimloggers.json
    - 2017-03-01/swagger/apimnetworkstatus.json
    - 2017-03-01/swagger/apimopenidconnectproviders.json
    - 2017-03-01/swagger/apimproducts.json
    - 2017-03-01/swagger/apimproperties.json
    - 2017-03-01/swagger/apimquotas.json
    - 2017-03-01/swagger/apimreports.json
    - 2017-03-01/swagger/apimsubscriptions.json
    - 2017-03-01/swagger/apimtenant.json
    - 2017-03-01/swagger/apimusers.json
```
~~~

And then you can just go to that folder and run 'autorest' and it will find all the errors and list them

--- 
If you'd like to see the errors in Visual Studio Code you can install the AutoRest extension in VSCode, and then when you open the workspace to the folder with the `readme.md` file in it, you can get all the errors in the editor:

image

**Comment by fearthecowboy** [comment]
@solankisamir  NIIIIIICE! Thanks. I'm on it now

**Comment by fearthecowboy** [comment]
Howdy @solankisamir ,

The ARM guys got back to me -- the child resources are required to follow the same pattern as the top level resources, which means that the pattern for `operationId` for operations should always be: `resourcename_operation` -- and the operation should be consistently named. (`CreateOrUpdate`, `Delete`, 'List', `ListBy<PARENTRESOURCE>` )

You can be flexible on the precise naming (ie, `.../service/...` can be `Services` or `Service`  and for Child Resources, you can Include the Parent Name in the operation group if it makes it better -- `.../service/{serviceName}/products` can be `ServiceProducts`  or `Products` )

My preference is to go with no plurals in the `operationId` -- it makes it so much clearer everywhere IMO.

However, I'd be wary of prefixing them with `ApiManagement` -- given that the generated code will be in a `ApiManagement` Client anyway, I'd opt for simpler names, and let codegen do the rest.

For Example, given some resources 

``` yaml
# Top-level resource: "Services"
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}":

# operation ids
operationId="Service_CreateOrUpdate"
operationId="Service_List"
operationId="Service_Delete" 

# Child Resource: "Services/Products"
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/products/{productId}":

# operation ids
operationId="ServiceProduct_CreateOrUpdate"
operationId="ServiceProduct_ListByService"
operationId="ServiceProduct_Delete" 

#or (my preference)
operationId="Product_CreateOrUpdate"
operationId="Product_ListByService"
operationId="Product_Delete" 

# Child Resource "Services/Products/Groups"
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/products/{productId}/groups/{groupId}":

operationId="ProductGroup_CreateOrUpdate"
operationId="ProductGroup_ListByProduct"
operationId="ProductGroup_Delete" 

#or (my preference)
operationId="Group_CreateOrUpdate"
operationId="Group_ListByProduct"
operationId="Group_Delete" 

```

But for certain, you should not use the pattern `<ParentResource>_List<ChildResource>` -- that's definitely not the guidelines laid out by the ARM folks.

**Comment by salameer** [comment]
Hi @solankisamir,

If you're done with addressing the requested changes can you please changes the status of the PR to review required? or Ping @fearthecowboy

**Comment by solankisamir** [comment]
@salameer thanks for bringing this up. I am working on .NET SDK and fixing minor issues in the rest spec. Will hold onto this until Monday.

**Comment by salameer** [comment]
Thanks @solankisamir

**Comment by salameer** [comment]
Ping @solankisamir :)

**Comment by salameer** [comment]
Hello @solankisamir,

We'll be closing this due to lack of activity, please feel to open a new PR once ready

**Pull request closed without merging**
