### PR TITLE
[AKS] remove unsupported VM types

### PR DESCRIPTION
**Pull request by mboersma**
Some SKUs don't have enough RAM to support Kubernetes workloads reliably, so we're removing support for those types. This change won't accomplish that validation, but will prevent SDK users from
being led astray and trying to provision those types.

cc: @weinong

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by lmazuel** [comment]
@mboersma a few question to understand:
- was it failing all the time if people were using this?
- does the server refuses them now? If no, what the server is doing? Still trying and there is a small chance it works?

**Comment by mboersma** [comment]
@lmazuel:

> was it failing all the time if people were using this?

No, but roughly 50% of the time if a user provisioned an AKS cluster with the smaller VM types that I propose to remove here.

> does the server refuses them now?

Not today, but soon. In the next week or two, users specifying these removed VM SKUs will get a specific error about "VM not large enough for AKS," which we think is better than letting someone try and fail about half the time.

This change isn't crucial since the validation will really be done server-side, but it should keep things consistent and documentation correct.

**Review by lmazuel — APPROVED** [review]
LGTM since server will refuse them anyway

**Comment by mboersma** [comment]
> what happen to already successfully created AKS cluster with theses sizes?

They can still scale and upgrade that cluster using its existing VM type. The server-side change will only reject these sizes when creating new clusters.

**Pull request merged**
