### PR TITLE
[KeyVault] adding 7.1-preview api spec

### PR DESCRIPTION
**Pull request by schaabs**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by praries880** [comment]
@schaabs Kindly fix the following two linter errors : 

  | Rule | Location | Message
-- | -- | -- | --
1 | R3016 - DefinitionsPropertiesNamesCamelCase | 7.1/​keyvault.json:4509 | Property named: 'validation_method', for definition: 'IssuerParameters' must follow camelCase style. Example: 'validation_method'.
2 | R3016 - DefinitionsPropertiesNamesCamelCase | 7.1/​keyvault.json:4533 | Property named: 'validation_emails', for definition: 'IssuerParameters' must follow camelCase style. Example: 'validation_emails'.

**Comment by praries880** [comment]
@schaabs I see that the new types : `ValidationEmail`, 'validation_emails' and 'validation_method' were added in the 7.1 keyvault.json when compared to 7.0.

The types are not used anywhere... are you going to add new API's that refer these new types at a later point of time?

**Comment by schaabs** [comment]
@praries880 To your first comment, the linter errors were introduced because these fields are being added to a type which already uses _ delimited property names rather than camel case (The types were created before this linter rule existed).  Therefor to be consistent throughout the type these fields were added with _ delimited property names.

To your second comment the properties validation_method and validation_email are added to the  ValidationEmail is being added to the type IssuerParameters which is already used in existing APIs, and the validation_email field is a ValidationEmail array:

        "validation_emails": {
          "x-ms-client-name": "ValidationEmails",
          "type": "array",
          "description": "A list of email addresses where validation emails should be sent for specific DNS names.",
          "items": {
            "$ref": "#/definitions/ValidationEmail"
          }

**Comment by praries880** [comment]
@schaabs Since the type pre-dates the new PR, we should be fine adding a suppression for the error... kindly follow the procedure [here](https://github.com/Azure/adx-documentation-pr/wiki/Swagger-Validation-Errors-Suppression) to create a suppression.

**Comment by schaabs** [comment]
@praries880 The service team has asked me to hold off on this release as they are considering a design change.  I'm closing this PR and will reopen a new one once the changes are finalized.

**Pull request closed without merging**
