### PR TITLE
Add TypeScript arm-appconfiguration readme

### PR DESCRIPTION
**Pull request by kpajdzik**

### CODE REVIEW

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@kpajdzik do you know why JS is failling?

**Comment by kpajdzik** [comment]
> @kpajdzik do you know why JS is failling?

It seems like removing version of autorest.typescript caused the issue. We can ignore it.

**Comment by daschult** [comment]
@openapi sdkautomation rebuild

**Comment by daschult** [comment]
@openapi sdkautomation rebuild

**Comment by kpajdzik** [comment]
@openapi sdkautomation rebuild

**Pull request merged**
