### PR TITLE
[Microsoft.App] Add jijohn14 as owner

### PR DESCRIPTION
**Pull request by jijohn14**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by jijohn14** [comment]
https://github.com/jijohn14 is a public profile

**Comment by weshaggard** [comment]
image

You are marked as private which means only folks in the org can see that you are a member.

**Comment by jijohn14** [comment]
Resolved
image

**Comment by mikeharder** [comment]
> Resolved image

That's the "Microsoft" org.  You need to be public in the "Azure" org.  You still aren't.

https://github.com/orgs/Azure/people?query=jijohn14

image

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
