### PR TITLE
Swagger change for listing virtual machines in a subscription by location

### PR DESCRIPTION
**Pull request by dochung4**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [y] The title of the PR is clear and informative.
- [y] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [y] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [y] If applicable, the PR references the bug/issue that it fixes.
- [y] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [y] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [y] My spec meets the review criteria:
  - [y] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [y] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [y] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @dochung4 !
Looks good to me! But please provide x-ms-examples for your new operation. There is a ton of model you can follow in the very same files, should not be difficult :)
Thanks!

**Comment by lmazuel** [comment]
Thanks @dochung4 !
Please link all operations to their examples. For instance:
https://github.com/Azure/azure-rest-api-specs/blob/7e77af77c192a4b944c48caed5a2c53003751880/specification/compute/resource-manager/Microsoft.Compute/stable/2017-03-30/compute.json#L1267-L1271

**Comment by lmazuel** [comment]
Hi @dochung4 
Your examples does not match the Swagger description (two issues):
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/432318420

Example:
```
  code: REQUIRED_PARAMETER_EXAMPLE_NOT_FOUND
  id: OAV105
  message: >-
    In operation "VirtualMachines_ListByLocation", parameter location is
    required in the swagger spec but is not present in the provided example
    parameter values.
```
This means you need to add "location" in the paremeters section of the example

```
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - - allowExtensionOperations
  message: 'Additional properties not allowed: allowExtensionOperations'
  path: value/1/properties/osProfile
  title: /definitions/OSProfile
```
This means you example contains a node called `allowExtensionOperations` that is not described in the Swagger at all. If this node exists in the real server, please take this opportunity to add it in the right model. If this is a typo and this node does not exists in real server answer, please remove it from the example.

**Comment by lmazuel** [comment]
Side note, the PR looks good to me, I have no objection to merge once the examples errors are fixed. Thanks!

**Comment by dochung4** [comment]
allowExtensionOperations is supported from 2018-06-01, so I removed it from the example for the previous API versions. I see that allowExtensionOperations has already been added to Swagger for 2018-06-01 and above, so I believe this should resolve the issue.

**Comment by lmazuel** [comment]
Hi @dochung4 
Last issue is the `REQUIRED_PARAMETER_EXAMPLE_NOT_FOUND` I mentioned earlier and we're good to merge :)

**Comment by dochung4** [comment]
Updated "locations" to "location"

**Comment by lmazuel** [comment]
@dochung4 This is better, now the linter find the parameter. However, `{location}` is not a valid location... Please use something like `eastus` or real value.

Note that to avoid having to back back and forth with the CI, you can test your examples locally with OAV:
https://github.com/Azure/oav

But I think this time this is the last one, since the only error is a regexp matching precisely here.

**Review by lmazuel — APPROVED** [review]

**Comment by lmazuel** [comment]
Thanks @dochung4 !

**Pull request merged**
