### PR TITLE
VMware by Virtustream API 2019-08-09-preview

### PR DESCRIPTION
**Pull request by ctaggart**
This is a new API specification version based on ARM feedback in #6653. We still need to review the credentials handling on a call. Here is a list of changes:
- Get / Update the same types
- Add PrivateClouds_Update (PATCH)
- Remove PrivateClouds_AddIdentitySource, PrivateClouds_DeleteIdentitySource, PrivateClouds_AddAuthorization, PrivateClouds_DeleteAuthorization. Use PrivateClouds_Update instead.
- Follow long running async pattern for updates that return a 201 instead of a 202
- Make Clusters_List pageable
- use enums instead of booleans
- changed PrivateClouds_GetAdminCredentials to PrivateClouds_ListAdminCredentials for template deployments

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ctaggart** [comment]
@anthony-c-martin, I added an overview of changes to the description above. They are all based on feedback in #6653.

**Review by anthony-c-martin — APPROVED** [review]
Looks great to me! Thanks for incorporating all the feedback from the previous iteration.

**Comment by yungezz** [comment]
Hi @ctaggart is this PR ready to merge?

**Comment by ctaggart** [comment]
The feedback I received was that this would not be merged until the service is ready for public preview. To continue to receive feedback, I moved it to the private repository.

**Comment by ctaggart** [comment]
This VMware by Virtustream API 2019-08-09-preview is now available in all supported locations. I just released a [new version of azure-vmware-virtustream-cli-extension](https://github.com/virtustream/azure-vmware-virtustream-cli-extension/releases/tag/0.4.0) that uses this. @yungezz, I think it is ready to merge.

**Review by lmazuel — APPROVED** [review]
LGTM

**Comment by yungezz** [comment]
HI @ctaggart , since the service is public now, do you need SDK released for this PR? If yes, pls share languages you're interested at. We'll do the release then, since the pipeline need Microsoft employee's permission. Or you just want SDK generated, but not released?

**Comment by yungezz** [comment]
@ctaggart , pls communication with Microsoft team who worked with you on this service(pls ping me if you need the name) , the product is not ready for public, so we'll revert this PR in this repo. Pls continue working on private repo azure-rest-api-spesc-pr. Meanwhile, we'll looking at how to generate a private SDKs for you based on private repo's PR https://github.com/Azure/azure-rest-api-specs-pr/pull/885, but NOT releasing. Will let you know if there's any update. Meanwhile, pls ping me if any question about Swagger, SDK generation etc.

**Pull request merged**
