### PR TITLE
Change 2024-05-01 to 2024-05-01-preview

### PR DESCRIPTION
**Pull request by dw511214992**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by dw511214992** [comment]
Our team is asked to pause GA and keep preview status. So change the stable version to preview version.

**Comment by yeturis** [comment]
Please can you help us with an ETA, as we are required to share an ETA with our LT. Thanks,

**Review by mentat9 — APPROVED** [review]

**Comment by tombuildsstuff** [comment]
@dw511214992 

> The stable version is not released to customers, and there is no sdk or tools released. So, there is no impact to customers.

FWIW that may be the case for the official Azure SDKs - but there's multiple other tools and SDKs which are generated based upon this repository - so this is a breaking change for downstream tooling.

For example [`hashicorp/go-azure-sdk` shipped support for this Stable API version a month ago](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/hdinsight/2024-05-01) ([as did Pulumi by the look of it](https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/dotnet/HDInsight/V20240501)), when this Stable API Version was merged into this repository - and there's likely other users who generate from these API Definitions too.

---

@JeffreyRichter I suspect there might be an opportunity for an additional validation check to avoid a breaking change here in the future, whilst I can understand opening the PR prior to the API Version being deployed - particularly for Stable API Versions should these be merged into the `main` branch before the API is deployed/available to use (for customers, in at least an opt-in preview state)?

We had a related issue a few weeks ago for EventHub where the API definition is published but the API isn't yet deployed (https://github.com/hashicorp/go-azure-sdk/issues/976), and whilst we've got an issue to check on our side that an API Version has been deployed (https://github.com/hashicorp/pandora/issues/45) - perhaps that would make a good check in this repository too?

**Comment by JeffreyRichter** [comment]
My understanding is that the service never GA'd version 2024-05-01 and so this change would not actually break anyone consuming the service.  And this "break" was to allow the service to deploy 2024-05-01-preview which customers would be able to actually use.
Mnay service teams "believe" that the swagger is only used for SDKs/Tools but the Azure Breaking Chaange Board knows that this is not true and so we never make decisions based on the impact to SDKs/Tools. In this case, we thought no one was broken because the version has deployed live.

@dw511214992 was version 2024-05-01 ever deployed live allowing customers to use it? If so, what was done here is absolutely not allowed.

**Pull request merged**
