### PR TITLE
Update dev folder for Purview DataMap

### PR DESCRIPTION
**Pull request by yifan-zhou922**
# Choose a PR Template
It only contains the 2023-09-01 (latest version) APIs

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
According to service, this is same as https://github.com/Azure/azure-rest-api-specs/tree/main/specification/purview/data-plane/Azure.Analytics.Purview.DataMap/stable/2023-09-01

**Comment by TimLovellSmith** [comment]
@yifan-zhou922  Please fix PrettierCheck and SpellCheck

**Comment by TimLovellSmith** [comment]
@yifan-zhou922 
Did you do this?

Switch to "Preview" on this description then select one of the choices below.

[Click here](https://github.com/Azure/azure-rest-api-specs/pull/26729?expand=1&template=data_plane_template.md) to open a PR for a Data Plane API.

[Click here](https://github.com/Azure/azure-rest-api-specs/pull/26729?expand=1&template=control_plane_template.md) to open a PR for a Control Plane (ARM) API.

**Pull request closed without merging**
