### PR TITLE
MediaServices: update to specify autorest.java version

### PR DESCRIPTION
**Pull request by xseeseesee**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by BrianBlum — APPROVED** [review]
This looks good to me.

**Comment by xccc-msft** [comment]
@MyronFanQiu we just want to revert this change. Autorest version should be handled from sdk side rather than swagger side.

**Review by mmyyrroonn — APPROVED** [review]

**Comment by BrianBlum** [comment]
@MyronFanQiu does this mean that I need to add   --use=@microsoft.azure/autorest.java@2.1.90  --tag=package-2019-05-preview to a request for the java SDK?

**Comment by MyronFanQiu** [comment]
@xccc-msft Can you share the future plan? There should be a reason to choose this specific autorest version before. So how do we keep this information in the sdk side in the future?

**Comment by xccc-msft** [comment]
@BrianBlum @MyronFanQiu 
- The process will keep as it is. You don't need to change anything when requesting release for new SDK.
- We were using `autorest.java@2.1.88` to generated media services because `autorest-core/preview` picks `autorest.java@latest`(2.1.88) internally .
- We are going to update our autorest cmd then we will always use `autorest.java@preview`(for now it is 2.1.95) by default in the future.

**Pull request merged**
