### PR TITLE
StorSimple1200Series Azure Rest API Spec

### PR DESCRIPTION
**Pull request by johnemmanuelm**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by hovsepm** [comment]
Please fix syntax, semantic and CI build breaks.

**Comment by johnemmanuelm** [comment]
Hi, Fixed the build breaks and all checks are passing. Please let me know if anything else should be needed to be taken care...Thanks!

**Comment by hovsepm** [comment]
@ravbhatnagar please take a look. This is a new API version.

**Comment by ravbhatnagar** [comment]
Confirmed on email that these are all existing APIs being added to swagger now. Signing off from ARM side.

**Comment by hovsepm** [comment]
>           "nextLinkName": null

List on Managers does not support paginated results? 

---
Refers to: specification/storSimple1200Series/resource-manager/Microsoft.StorSimple/stable/2016-10-01/StorSimple.json:48 in 0f4e69b. [](commit_id = 0f4e69b18ee23314ec6e2ce63b921fed0a223281, deletion_comment = False)

**Comment by hovsepm** [comment]
@johnemmanuelm please add description to all the operations with simple meaningful description of the operation. Please keep in mind that we use that field to add description to the generated code that will help developers to understand your SDK during development.

**Comment by hovsepm** [comment]
Please add default response to all operations. Please take a look to the documentation of swagger authoring - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#default-response

**Comment by hovsepm** [comment]
>         },

same question - no paginated result for List by resource group? Please keep in mind that if in the nearest future you will change the response to support paginated return it will be a breaking change and you will need to bump up API version. 

---
Refers to: specification/storSimple1200Series/resource-manager/Microsoft.StorSimple/stable/2016-10-01/StorSimple.json:156 in 0f4e69b. [](commit_id = 0f4e69b18ee23314ec6e2ce63b921fed0a223281, deletion_comment = False)

**Comment by hovsepm** [comment]
@johnemmanuelm please add description to all the properties and objects in the Definition section. How will developers understand how to use your SDK?

**Review by hovsepm — CHANGES_REQUESTED** [review]
Please address review comments.

**Comment by johnemmanuelm** [comment]
Can you please share the steps to generate readme.md specific to StorSimple RP?

**Review by hovsepm — APPROVED** [review]

**Pull request merged**
