### PR TITLE
Webapp

### PR DESCRIPTION
**Pull request by naveedaz**
Added Property Accesibility settings for Site/SiteConfig/AppServicePlan

### CODE REVIEW

**Comment by tbombach** [comment]
Hi @naveedaz. I'll take a look at this PR today

**Comment by tbombach** [comment]
Hi @naveedaz. The Travis CI build is failing because it's trying to generate code in Python, Node and Ruby based on this PR to see if there are any problems. However, there are multiple operations that share the id "UpdateSourceControl" (lines 6297 and 6345), which is invalid in a swagger file

**Comment by tbombach** [comment]
Could you rebase this PR with the branch that you're trying to merge into? This PR seems to include commits that have already been merged and aren't relevant for these set of changes.

**Comment by yugangw-msft** [comment]
>         "x-ms-long-running-operation": true

Confirm: is this really a long running operation?

---
Refers to: arm-web/2015-08-01/swagger/service.json:14357 in ba6876d. [](commit_id = ba6876d1b7e65559c7024630fdb352fbfa9fb75e, deletion_comment = False)

**Comment by yugangw-msft** [comment]
@amarzavery @naveedaz @tbombach @haoc @LukaszStem 
When this PR is being reviewed, I would like to call out that we plan to have a separate and much smaller PR submitted for webapp/linux support, and that one is very important for cli commands work. So we would like hold on this PR and ensure it will merge after the linux one.

**Comment by LukaszStem** [comment]
The swagger spec with minor linux changes has been merged.

**Comment by naveedaz** [comment]
Sending out a new PR with per collection swagger files.

**Pull request closed without merging**
