### PR TITLE
Microsoft.TimeSeriesInsights: Fix swagger correctness issues

### PR DESCRIPTION
**Pull request by k-rush**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? N/A
  3. When you expect to publish swagger? ASAP
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by k-rush** [comment]
@akning-ms I believe 3 of the breaking changes are a false positive. While the tooling mentions I removed the `localTimeStamp` property, I simply moved it to be included in request body for PUT/PATCH for EventSources, as well as the GET/PUT/PATCH response body. This is to fix part of this relevant S360 KPI: https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=1F5C742A-8D4D-4F55-B2EB-9124B8B3C874

The other 2 are additional properties on the Operations response. This is required to fix the following Swagger Correctness S360 KPI: https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=61AD52F9-7FD8-4B91-84EF-38672D8D5B3D

I don't think either of these will have measurable negative customer impact, but I'm open to suggestions on how to mitigate any if there were to be.

**Comment by akning-ms** [comment]
Yes. looks localTimeStamp is false alarm. @jianyexi  to confirm,
But for adding  property  to fix S360 issue. it require breaking change review approval. step is:
Action: To initiate an evaluation of the breaking change, create a new intake using the template for breaking changes. Addition details on the process and office hours are on the Breaking change Wiki.

**Review by riserrad — APPROVED** [review]
Changes look good to me.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by k-rush** [comment]
@ruowan, can you please review this?

**Comment by ruowan** [comment]
Python SDK track2 failed. @msyyc help to take a look.

**Comment by RAY-316** [comment]
@k-rush I've made some changes to your branch to fix Python SDK track2 failed,  you can use it as a reference.
 * https://github.com/Azure/azure-rest-api-specs/pull/14731/commits

**Comment by k-rush** [comment]
@RAY-316 Thanks! Those changes were already made in `master` - the merge I just did should have fixed the issue

**Comment by k-rush** [comment]
@ruowan what else do I need to do to get this PR in?

**Comment by zhenglaizhang** [comment]
> @ruowan what else do I need to do to get this PR in?

@msyyc @ArcturusZhang pls help check the python & go SDK breaking changes.

**Comment by msyyc** [comment]
For python, the breaking change is permitted.

**Pull request merged**
