### PR TITLE
Updating new VirtualNetworkRules swagger with name change from VnetFirewallRules to VirtualNetworkRules

### PR DESCRIPTION
**Pull request by dnayantara**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
Why we are making this change: originally we wanted "Vnet" in order to be concise, but we noticed that network API has resources named "VirtualNetwork", e.g. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2017-03-01/swagger/virtualNetwork.json#L85 , and we decided that it would be better to harmonize our resource naming with them.

**Review by jaredmoo — APPROVED** [review]

**Comment by jaredmoo** [comment]
@nathannfan

**Comment by jaredmoo** [comment]
@lmazuel looks like "Vnet" naming was released in azure-mgmt-sql 0.6.0, so this is a breaking change for python. We didn't yet release this in .net sdk so it's not a breaking change there. The customer impact should be none because this API is not fully deployed to production yet.

**Comment by olydis** [comment]
thanks for the heads up @jaredmoo!

**Comment by olydis** [comment]
Searching for `vnet` across the spec I see:
- a type (`VnetFirewallRuleListResult`)
- parameters
- a description

Are those supposed to be updated too? 🙂

**Comment by dnayantara** [comment]
@olydis We basically just want to make sure that the Customer facing .Net SDK client code has the VirtualNetworkRules naming instead of VnetFirewallRules. Internal parameters if named different should be ok.

**Comment by dnayantara** [comment]
Spoke to @jaredmoo , we decided to make the naming changes throughout and then update. I will close this and send a new request in some time.

**Pull request closed without merging**
