### PR TITLE
Suppress RPC R3019 per discussion at https://github.com/Azure/azure-r…

### PR DESCRIPTION
**Pull request by naveedaz**
…est-api-specs/pull/2258

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by naveedaz** [comment]
@salameer, @ravbhatnagar  Can you guys help approve and merge?

**Comment by lmazuel** [comment]
Tagged @salameer @ravbhatnagar  as reviewers.

**Comment by ravbhatnagar** [comment]
Ok to suppress as we discussed on the PR. It would still be good if we have granular suppression at API level since we still want to check for this rule for new resource types. @naveedaz  - I know this would still be a lot of APIs, anyhow that can be achieved? @lmazuel - thoughts on this? Can we suppress it at resource type or model level? anyhow we can make it easier for the author of the suppression but still ensure the rule gets applied for newer types?

**Comment by lmazuel** [comment]
@fearthecowboy @olydis Any idea for what suggests @ravbhatnagar in his last comment?

**Comment by fearthecowboy** [comment]
Suppression can be very fine-grained.

With most messages, you'll see something like 
```
ERROR (BodyTopLevelProperties/R3006/RPCViolation): Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'TrafficManagerUserMetricsKeyModel' has extra properties ['key'].
    - file:///C:/tmp/hrk/specification/trafficmanager/resource-manager/Microsoft.Network/preview/2017-09-01-preview/trafficmanageranalytics.json:431:6 ($.definitions.TrafficManagerUserMetricsKeyModel.properties)
```

that last piece in parenthesis after the path can be specified to scope the suppression:

``` yaml
directive:
  # suppress just the one error
  - where: $.definitions.TrafficManagerUserMetricsKeyModel.properties
    suppress: R3006
    reason: It's an old API, will resolve in next API version
    approved-by: "@ravbhatnagar"
```

**Comment by lmazuel** [comment]
@fearthecowboy I think the question here is that doing it precisely will require a loooooooot of suppressions rule. It's why the PR is generic. But at the same time, the problem with generic rule is that this will be applied to all future Swagger :(
So is there a smart way to add a loooooooooot of suppression rules right now with precise granularity to replace the big one and allow future Swagger to be verified correctly?

**Comment by naveedaz** [comment]
@fearthecowboy @olydis @ravbhatnagar @lmazuel 
Let me know if the latest change addresses your concerns

**Comment by lmazuel** [comment]
Thanks @naveedaz . I think this address concerns from @ravbhatnagar on generic suppression. Merging!

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
