### PR TITLE
containerservice: adding support for Custom Headers

### LINKED ISSUE #2757: Add AKSHTTPCustomFeatures header support to Swagger
There are a number of issues that have been closed as duplicates of issue [6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) on the `terraform-provider-azurerm` project requesting support for custom headers to be passed to AKS.

Although the issue [6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) is still `Open` it has a [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178) that had a preposed solution for the issue that was `Closed` with the `status` `wont-fix`

@tombuildsstuff closing comment in [PR 14178](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178#issuecomment-968789798) was as follows:

"Thanks for this PR.

Taking a look through here unfortunately this isn't something we can ship in Terraform at this time for a number of reasons.

The primary one here is that these are sourced from an Environment Variable and thus aren't defined in the config - however even if we were to move these to schema fields, at this point in time these can only be set in/parsed from the HTTP Headers for the request/response.

Whilst this approach works insofar as it sends the headers, due to the volatility of the Azure API's there's no guarantee this won't change behaviourally between different versions of the Azure API - and since this isn't provided in the Azure SDK (or the Swagger which supports it) - in practice it'd be hard for us to detect that this functionality has changed.

In order to support this functionality (and implement #6793) we'd need these `Headers to be added to the Swagger for the AKS API` - at which point this'll become available in the Azure SDK (and any other tooling which uses it). Whilst that may seem like a small distinction - that means this functionality becomes covered by the ARM Deprecation policy - meaning that changes have to go through a deprecation policy such that external tooling can rely on it. `In order to get that added I'd suggest opening an issue on the AKS Repository where someone from the AKS Team should be able to get that added to the next version of the Swagger, which'd allow us to support this functionality.`

As such whilst I'd like to thank you for this contribution, until this information is exposed in the Azure Swagger (such that there's a compatibility guarantee) I'm going to have to close this PR for the moment.

Thanks!"

Can i request the Headers to be added to Swagger for the AKS API 

FYI the header that i requested a [feature](https://github.com/hashicorp/terraform-provider-azurerm/issues/15137) for is `--aks-custom-headers WindowsContainerRuntime=containerd` when creating a Windows node pool

```console
az aks nodepool add \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --os-type Windows \
    --name npwcd \
    --node-vm-size Standard_D4s_v3 \
    --kubernetes-version 1.20.5 \
    --aks-custom-headers WindowsContainerRuntime=containerd \
    --node-count 1
``

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes https://github.com/Azure/AKS/issues/2757
Unblocks https://github.com/hashicorp/terraform-provider-azurerm/issues/6793

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [x] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by matthchr** [comment]
@tombuildsstuff - thanks for the energy on this topic (and for the PR).

I'll be honest: We don't love the way we're using headers to configure feature enablement right now. It has a lot of flaws, not the least of which as you've pointed out is that it's not "officially documented" in the REST API. It also doesn't work with ARM templates, you can't always easily see what feature's you turned on after the fact, and so on (there are a lot of flaws).

I'm not sure if you've noticed but we've recently starting publishing `-preview` APIs alongside the standard ones. One of the reasons for that is we're trying to tackle this problem more holistically by letting preview features get placed into the `-preview` API in a way that solves a lot of the above problems:
1. It allows users to set and get feature enablement via all interfaces equally well (ARM templates, SDKs, CLI, etc)
2. It gives us a more clear out if that feature never makes it to GA, as opposed to the ambiguous world of headers today.

Unfortunately that means we really would like to be moving in the opposite direction here: Less headers, less support (and use) of headers, until we can eventually stop supporting them altogether (that's probably a ways off but it's the goal). Adding the headers explicitly to the API doesn't solve any of their other problems and also commits us to supporting the pattern for longer than we'd like.

**Comment by tombuildsstuff** [comment]
@matthchr I understand the desire to move away from this - but as these are supported today they should be documented in the Swagger? Future API versions can opt to remove this field once it's no longer used, but as this API Version supports this field it should be documented, as it's optional and isn't returned from the API - removing this isn't a breaking change.

cc @JeffreyRichter since I've seen this a few times and I'm wondering if there's some guidance missing from the ARM docs here?

**Comment by raych1** [comment]
@tombuildsstuff , this PR is pending for your action to move on. Either get breaking change approval or revert those changes that caused breaking.  Another action is to fix CI check failures.

**Comment by tombuildsstuff** [comment]
@raych1 this PR is waiting on the SDK/ARM Team to decide how to proceed: https://github.com/Azure/azure-rest-api-specs/pull/18232#issuecomment-1068300285

If the API no longer supports these fields as of today then that's fine and we can close this PR, since this PR is no longer up to date - but if the API still accepts these values then the Swagger should be updated to account for this, even if the intention is to deprecate/remove support for this in a future API Version (which can be done when there's no remaining features using this method).

**Comment by matthchr** [comment]
> If the API no longer supports these fields as of today then that's fine and we can close this PR, since this PR is no longer up to date - but if the API still accepts these values then the Swagger should be updated to account for this, even if the intention is to deprecate/remove support for this in a future API Version (which can be done when there's no remaining features using this method).

As of today all 4 possible usages for these headers are deprecated. No new usages are being added. It is true that existing APIs will continue accepting the headers for the k8s versions listed above until they go out of support, but given their deprecated status we believe it doesn't make sense to add them to the `stable` Swagger at this time. Headers for all of the 

@tombuildsstuff, thanks for this PR. I'm going to close it given the above status. We really appreciate the conversation that it drove here as well as internally. Please feel free to respond if you strongly disagree and we can continue the discussion. Note that https://github.com/hashicorp/terraform-provider-azurerm/issues/6793 lists a bunch of headers for various features (Gen2 Vms, Ephemeral OS, containerd, Ubuntu 18.04). None of the headers for those features are supported anymore anyway (they all don't do anything)

**Comment by Vegoo89** [comment]
> > If the API no longer supports these fields as of today then that's fine and we can close this PR, since this PR is no longer up to date - but if the API still accepts these values then the Swagger should be updated to account for this, even if the intention is to deprecate/remove support for this in a future API Version (which can be done when there's no remaining features using this method).
> 
> As of today all 4 possible usages for these headers are deprecated. No new usages are being added. It is true that existing APIs will continue accepting the headers for the k8s versions listed above until they go out of support, but given their deprecated status we believe it doesn't make sense to add them to the `stable` Swagger at this time. Headers for all of the
> 
> @tombuildsstuff, thanks for this PR. I'm going to close it given the above status. We really appreciate the conversation that it drove here as well as internally. Please feel free to respond if you strongly disagree and we can continue the discussion. Note that [hashicorp/terraform-provider-azurerm#6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) lists a bunch of headers for various features (Gen2 Vms, Ephemeral OS, containerd, Ubuntu 18.04). None of the headers for those features are supported anymore anyway (they all don't do anything)

@matthchr 
Maybe it is not the right place, but I would love to know what happend to first point:

Using GPU VHD images

Will these images be discontinued?

**Comment by katbyte** [comment]
@matthchr - existing APIs still support these, even if deprecated, so they are valid, people are using them, and should be represented in swagger

**Comment by alexeldeib** [comment]
> Using GPU VHD images

we're focusing on optimizing the vanilla images for latency. the behavior is very nearly identical today. the main other difference is the nvidia device plugin. that is relatively easy to deploy as an end-user, or if there's demand we can expose that via normal APIs separately.

for bonus points: with an expanding range of skus, we need to pivot driver version based on GPU model, which defeats the purpose of the preinstalled drivers, and actually added latency in some cases :/

**Comment by stephybun** [comment]
When will the GPU VHD image functionality be supplanted by the so called vanilla images? And by that point will all the GPU VHD images be phased out completely i.e. users will not be able to use or set them in the headers anymore?

**Pull request closed without merging**
