### PR TITLE
Add query property for Salesforce V2

### PR DESCRIPTION
**Pull request by wenqibu**
Add query property for Salesforce V2

### CODE REVIEW

**Comment by wenqibu** [comment]
The new added "query" property is optional, it will not impact existing customers.

**Comment by ms-zhenhua** [comment]
@wenqibu, Please get `BreakingChange-Approved-*` and `Versioning-Approved-*` label from Azure Breaking Changes Reviewers azbreakchangereview@microsoft.com and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

**Review by madhura-np — APPROVED** [review]

**Pull request merged**
