### PR TITLE
T2 DNS, modify readme.python.md

### PR DESCRIPTION
**Pull request by zhangyan133**
add track2 configure

### CODE REVIEW

**Review by msyyc — COMMENTED** [review]
forget to add '- repo: azure-sdk-for-python-track2' in 'readme.md'

**Comment by 00Kai0** [comment]
Retry it after merge this [pr](https://github.com/Azure/azure-sdk-for-python/pull/17232)

**Comment by chunyu3** [comment]
wait Kaihui Sun to fix the python-track2-sdk failure.

**Review by 00Kai0 — APPROVED** [review]

**Review by msyyc — APPROVED** [review]

**Pull request merged**
