### PR TITLE
Added Data Lake Path Create Bundle

### PR DESCRIPTION
**Pull request by seanmcc-msft**

### CODE REVIEW

**Comment by JeffreyRichter** [comment]
I need context as to why breaking changes should be approved.
Are the optional values being added because the service already returns them and the swagger was just wrong?
Or is the service trying to add features to an already-shipped api-version?

**Comment by seanmcc-msft** [comment]
> I need context as to why breaking changes should be approved. Are the optional values being added because the service already returns them and the swagger was just wrong? Or is the service trying to add features to an already-shipped api-version?

First off, this is not a merge to main.  We don't need to review every change I merge to stg83base.

These are optional headers that have existed for several years, they just hadn't been enabled in the service yet.

@tg-msft

**Comment by JeffreyRichter** [comment]
I don't know how to interpret the sentence. If the service didn't actually support these headers, from a customer's perspective the headers did not exist and old api-versions/swaggers cannot be changed in this way.
If the headers NOW do something, then it is Azure's policy that a new api-version with a new swaggger is REQUIRED.
The whole purpose of api-versions is to indicate when things change.

**Comment by tg-msft** [comment]
Yeah, this is just another case of iterating on the development of a new service release's swagger in a feature branch.  I agree we shouldn't be reviewing in progress PRs.  Hopefully we'll get the bot fixed soon so it stops auto-assigning folks from the API Stewardship Board.

**Review by amnguye — APPROVED** [review]

**Pull request merged**
