### PR TITLE
Communication/PhoneNumbers - Add Number Lookup API

### LINKED ISSUE #23060: [IC3 ACS Management GW] API Review
New API Review meeting has been requested.

**Service Name**: IC3 ACS Management GW
**Review Created By**: Erica Sponsler (SHE/HER)
**Review Date**: 4/11/2023 1:00 PM PT
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/23053
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: This is a new feature that would allow ACS customers to look up information about a recipient phone number before using ACS services (e.g. SMS) to contact that phone number.

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=b9ebecc9-f1c1-ed11-83ff-000d3a341bd5)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by ericasp16**
# Data Plane API - Pull Request
Add a new preview version to the Phone Numbers package and add an API for looking up phone numbers. This is a feature which will allow customers to look up recipient phone numbers before communicating with them (e.g. sending SMS).

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue: https://github.com/Azure/azure-rest-api-specs/issues/23060

Is this review for (select one):

- [X] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document: https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EeyC90-uUVJAt343sFa3T5sBlzTBcW2yEaf01rh0VZVCUQ?e=fGG4os
* Previous Open API Doc: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/PhoneNumbers/preview/2022-06-01-preview/phonenumbers.json
* Updated paths:
* /operatorInformation/:search

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/23060

### CODE REVIEW

**Review by mikekistler — APPROVED** [review]
Looks good for private preview.  But please rebase onto the most recent preview.

**Comment by ericasp16** [comment]
Breaking Changes (Cross-Version) check is failing, but all the breaking changes detected are between this version and the stable version, not the preview I used as the base for my change.  There are no breaking changes between the latest preview and this preview.

**Comment by ericasp16** [comment]
LintDiff is throwing a lot of errors and warnings, but most are existing in previous versions.  For some reason the lintdiff tool is not comparing the correct api version tags.  It is trying to compare this new preview version with the same preview version in the main branch, but as this review is to add the preview version it doesn't exist yet in the main branch and therefore all the errors and warnings are considered newly introduced.

I have manually gone through and fixed relevant warnings that my changes introduced.  The only one that should be left is one regarding support for paging which we are intentionally not adding to this endpoint as discussed and agreed to in the review.

**Comment by ericasp16** [comment]
@mikekistler I've rebased my swagger onto the latest version, and I've fixed up the PR based on the review feedback.  Can you take another look and make sure we're looking good to get this merged?  Let me know if you see anything that needs follow-up.  Thank you!
Here is the diff for the latest/most relevant commits: https://github.com/Azure/azure-rest-api-specs/pull/23053/files/58109068614bc7637c574b13218d84c49a03d3e9..dfbfd1222afb5ceb582829f90ac634f50ab37196

**Comment by mikekistler** [comment]
This PR is good to go from the API Stewardship POV. @ericasp16 is this ready to merge?

**Comment by ericasp16** [comment]
Yes, we're ready to merge.

@jhendrixMSFT as the assignee are you able to help us get this merged?  Thanks!

**Pull request merged**
