### PR TITLE
Adding the swagger spec to the right API version

### PR DESCRIPTION
**Pull request by sazeesha**

### CODE REVIEW

**Comment by sazeesha** [comment]
This the same swagger doc that is checked in the 2014-09-01 folder. But that version is incorrect. We need to check in that doc under the right API version.

**Comment by amarzavery** [comment]
@sazeesha- There are review comments in another PR. Please address that and also update that PR with the original one. It is hard to keep tab of review comments in 2 places. Btw, if the swagger doc is the same in both the api-versions then why have a new api-version?

**Comment by sazeesha** [comment]
The API version 2014-09-01 has a swagger document that actually should have been 2015-08-01.
We will be deprecating the 2014-09-01 very soon. 

Also this PR was a copy of the swagger doc that is already reviewed.  The comments the PR under 2014-09-01 will be resolved. It has nothing to do with this PR here.

**Comment by amarzavery** [comment]
Oh I see. I assumed that this doc contained Resource Queue in it as well, hence closed the PR. On another note, would you not want to add Resource Queue feature in this version of the spec as well?

**Comment by sazeesha** [comment]
I will add all other resources Queue/Topic/Subscription to this API version as soon as we are done writing it. Rahul is resolving the comments from the previous PR, once he is done I will add that along with other resources to this new API version.

**Comment by amarzavery** [comment]
cool sounds good!

**Comment by sazeesha** [comment]
Closed the pull request. Will make all the changes to the current pull request #395 resolve all the comments there and then create a new one in the right API version.

**Pull request closed without merging**
