### PR TITLE
Initial review of the swagger json for DataBox

### PR DESCRIPTION
**Pull request by kushalvms**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sarangan12** [comment]
Please resolve the errors reported at: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/359709970

**Comment by sarangan12** [comment]
@kushalvms  Did you get a chance to look at the errors?

**Comment by kushalvms** [comment]
@sarangan12 I am fixing the issues but I am facing few challenges in it. 
I am following the https://github.com/Azure/azure-powershell/blob/preview/documentation/testing-docs/using-azure-test-framework.md#new-testcredential for recording tests so that I can generate examples, but the setup is not seems to be working. I am getting: Message: System.Exception : SubscriptionList:'' retrieved for the user/spn id '', do not match with the provided subscriptionId '3c66da21-607e-49b4-8bdf-f25fbb8f705f' in connection string. Am I missing something?
I tried creating an example file for operations from other existing services(edited response) and added the reference in swagger but still getting one error: ERROR (XmsExamplesRequired/R2022/SDKViolation): Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for operations.

**Comment by kushalvms** [comment]
I have included x-ms-examples for operations api but still the linter validation is failing for this. Could anyone help me with how to fix this? I have used https://github.com/Azure/oav for generating the examples from the test result.

**Comment by kushalvms** [comment]
@sarangan12 Could you have a look and tell me what am I missing here? As I have included x-ms-examples for the operations api.
Thanks.

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
