### PR TITLE
[KeyVault] Update API tag for MHSM release

### PR DESCRIPTION
**Pull request by isra-fel**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

## What I did

- secrets.json should not be exposed so I removed it
- 2020-04-01-preview of keyvault.json is not available, so I change it back to 2019-09-01 except for managedhsm.json

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by isra-fel** [comment]
Needs key vault service team to review @riteshchitlangia1 
Thank you

**Comment by bim-msft** [comment]
Hi @isra-fel Seems `keyvault.json` and `providers.json` are existing under https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview

**Review by riteshchitlangia1 — APPROVED** [review]

**Comment by yungezz** [comment]
cc @bim-msft

**Comment by isra-fel** [comment]
@jianyexi Hi Jianye, this PR is blocked by Avocado. Can I get your approval to force merge? Thanks.

The error message says some jsons are not referenced by readme. This is expected because the APIs in those jsons are not supported yet.

**Comment by jianyexi** [comment]
> @jianyexi Hi Jianye, this PR is blocked by Avocado. Can I get your approval to force merge? Thanks.
> 
> The error message says some jsons are not referenced by readme. This is expected because the APIs in those jsons are not supported yet.

@ruowan Could you give some advises about how to fix the avocada issues?

**Comment by ruowan** [comment]
For avocado error, it reports these example files aren't referenced by swagger file. So if no needed, pls remove these example file.

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
