### PR TITLE
Jatehr consumption microsoft.consumption 2022 06 01

### PR DESCRIPTION
**Pull request by mehulviby**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by mehulviby** [comment]
@MaryGao this changes were already approved, https://github.com/Azure/azure-rest-api-specs/pull/22240

Due to some conflicts we had to revert it back. Now that the conflicts have been resolved. Can you please fasttrack this and approve it soon.

**Comment by MaryGao** [comment]
Approved it directly considering the same as https://github.com/Azure/azure-rest-api-specs/pull/22240

**Review by MaryGao — APPROVED** [review]

**Review by zedy-wj — APPROVED** [review]

**Comment by zedy-wj** [comment]
@mehulviby - Could you take a look at the merge conflicts?

**Pull request closed without merging**
