### PR TITLE
[Cognitive Services] Mark id/kind/type fields as readOnly

### PR DESCRIPTION
**Pull request by felixwa**
Mark id/kind/type fields as readOnly to make "AutoRest --azure-validator
--openapi-type=arm" happy.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by felixwa** [comment]
This PR fixes an Error (can be seen from Linter Azure bot):

Before the PR: Warning(s): 4 Error(s): 1
After the PR: Warning(s): 4 Error(s): 0

**Comment by balajikris** [comment]
Notice that this will be a breaking change for the SDKs, if you had shipped the existing schema as SDK packages. Make sure to version the newly generated packages appropriately to reflect the breaking change.

**Comment by balajikris** [comment]
while at it, can you also fix this failure in examples validation? : https://travis-ci.org/Azure/azure-rest-api-specs/jobs/268246587

**Comment by felixwa** [comment]
@balajikris , the validate-example issue (the type can be null) has been there for a while and last time @veronicagg mentioned that is because the issue of the validation tool. See: https://github.com/Azure/azure-rest-api-specs/issues/798
Since the issue is still open I don't think I can fix it now.

**Review by balajikris — APPROVED** [review]

**Pull request merged**
