### PR TITLE
chore: jsonfmt azurestack

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/azurestack/**/*.json"`

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@bganapa can you approve this PR

**Review by bganapa — APPROVED** [review]

**Comment by shahabhijeet** [comment]
Once CI passes, this PR is ready to be merged

**Comment by nschonni** [comment]
Re-opening since CI looks stuck

**Comment by nschonni** [comment]
@shahabhijeet looks like CI is happy again after re-opening

**Comment by nschonni** [comment]
@shahabhijeet ping

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
