### PR TITLE
Fix some linter errors by adding back Event Source examples.

### PR DESCRIPTION
**Pull request by sandshadow**
1. Fix some linter errors by adding back Event Source examples.
1. Update examples for GA api-version to use that api-version.
1. Update the Reade.md file so GA version is the default.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
Operation EventSources_ListByEnvironment is missing examples, is that expected?  Also there are some model validation errors with the examples, can you please take a look at the travis [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/305587690).

**Comment by jhendrixMSFT** [comment]
@sandshadow I would suggest running the model validation tool locally so you can easily iterate on these changes.
1.	Install oav using `npm install -g oav`
2.	Use `validate-example` command via `oav validate-example <spec-path>`

**Comment by sandshadow** [comment]
I added the missing example for EventSources_ListByEnvironment. Thanks for pointing that out. The remaining linter failures at this point are what I consider false positives because of inheritance in the model. 
- For the operations that return an event source, the linter doesn't consider the IoTHub event sources as valid, though it does consider the event hub event sources as valid. I think this is probably because "Microsoft.EventHub" is the default value for the kind enum.
- The "properties" property in the UpdateEventSource example is considered by the linter to be an invalid additional property because it is not defined on EventSourceUpdateParameters. But both derived EventHubEventSourceUpdateParameters and IoTHubEventSourceUpdateParameters types do define a "properties" property.

**Comment by sandshadow** [comment]
@jhendrixMSFT Thanks for the oav validate suggestion. I've fixed all the model validation errors with the examples.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
