### PR TITLE
Microsoft.AppConfiguration: Add 2020-07-01-preview API version

### PR DESCRIPTION
**Pull request by ZhijunZhao**
This PR has already been reviewed and approved in the private repo: Azure/azure-rest-api-specs-pr#1497

The PR adds new API version 2020-07-01-preview, which includes two changes comparing with version 2020-06-01.

1. Remove the listKeyValue API.
2. Add KeyValue proxy resource and GET/SET APIs for it.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ZhijunZhao** [comment]
@ChenTanyi Not sure why 'WaitForARMFeedback' label is added automatically. This PR actually has been approved by ARM team in the private repo.

**Review by ChenTanyi — APPROVED** [review]

**Comment by ChenTanyi** [comment]
@ZhijunZhao Thanks for figure out. It would be OK to merge. Please let me know when you want to merge it.

**Comment by ZhijunZhao** [comment]
Cool. We plan to release next week. So, please hold on the merge.

**Comment by ZhijunZhao** [comment]
@ChenTanyi We've finished the deployment. Can this PR be merged?  As for the LintDiff error, it's a newly added rule. If we have to fix it, we need to make code change on our service side.

**Comment by ChenTanyi** [comment]
@ZhijunZhao Is it possible to add such list operation? Will it be a large effect?

I think that a get request doesn't has corresponding list operation is strange, for `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppConfiguration/configurationStores/{configStoreName}/keyValues/{keyValueName}"`

**Comment by ZhijunZhao** [comment]
@ChenTanyi Yes, it takes efforts to add such an API to RP. I'm surprised that ARM team didn't point this out when they review the PR.

**Comment by ChenTanyi** [comment]
@jianyexi Does it matter for the `[Staging] Swagger LintDiff` failure? It seems that it was added after the CI run last time.

**Comment by jianyexi** [comment]
> @jianyexi Does it matter for the `[Staging] Swagger LintDiff` failure? It seems that it was added after the CI run last time.

It's a error from a new rule required by ARM , should also be fixed

**Comment by ChenTanyi** [comment]
> 
> It's a error from a new rule required by ARM , should also be fixed

@ZhijunZhao Could you fix this problem? Due to it is required from ARM.

**Comment by ZhijunZhao** [comment]
> > It's a error from a new rule required by ARM , should also be fixed
> 
> @ZhijunZhao Could you fix this problem? Due to it is required from ARM.

Sure. Will work on it.

**Comment by ZhijunZhao** [comment]
Reasons for asking suppression of violation `R4015 - NestedResourcesMustHaveListOperation`.

After GA, we received many customer requests that GET/SET key-values via ARM template should be supported. To achieve this, we introduce the key-value as a proxy resource so that ARM can make GET/SET key-value requests to RP and the requests are passed through to data plane.

We don't want to add the list operation for two reasons.

1. The introduction of keyValue resource is solely for ARM support. But there is no scenario that ARM could make list request for the keyValue resource. We don't want to add an API with no use case.
2. List key-values is supported by data plane. If we introduce this API to control plane, user might abuse it via management SDK. Even for GET/SET key-values, user should use the data plane SDK, instead of management SDK. We don't want to support a scenario that is not a good practice.

**Comment by jianyexi** [comment]
> Reasons for asking suppression of violation `R4015 - NestedResourcesMustHaveListOperation`.
> 
> After GA, we received many customer requests that GET/SET key-values via ARM template should be supported. To achieve this, we introduce the key-value as a proxy resource so that ARM can make GET/SET key-value requests to RP and the requests are passed through to data plane.
> 
> We don't want to add the list operation for two reasons.
> 
> 1. The introduction of keyValue resource is solely for ARM support. There is no scenario that ARM could make list request for the keyValue resource. We don't want to add an API with no use case.
> 2. List key-values is supported by data plane. If we introduce this API to control plane, user might abuse it via management SDK. Even for GET/SET key-values, user should use the data plane SDK, instead of management SDK. We don't want to support a scenario that is not a good practice.

@

> Reasons for asking suppression of violation `R4015 - NestedResourcesMustHaveListOperation`.
> 
> After GA, we received many customer requests that GET/SET key-values via ARM template should be supported. To achieve this, we introduce the key-value as a proxy resource so that ARM can make GET/SET key-value requests to RP and the requests are passed through to data plane.
> 
> We don't want to add the list operation for two reasons.
> 
> 1. The introduction of keyValue resource is solely for ARM support. There is no scenario that ARM could make list request for the keyValue resource. We don't want to add an API with no use case.
> 2. List key-values is supported by data plane. If we introduce this API to control plane, user might abuse it via management SDK. Even for GET/SET key-values, user should use the data plane SDK, instead of management SDK. We don't want to support a scenario that is not a good practice.

This rule is requested recently by ARM, @ravbhatnagar  could you confirm the suppression ?

**Comment by ZhijunZhao** [comment]
@jianyexi Should you add a need-ARM-review label so that @ravbhatnagar don't miss our comment?

**Comment by ZhijunZhao** [comment]
@ravbhatnagar could you confirm the suppression?

**Comment by ravbhatnagar** [comment]
@ZhijunZhao - what about delete API? this keyvalue resource can be created via the control plane. support for deleting it via control plane is also required.

**Comment by jimmyca15** [comment]
@ravbhatnagar these APIs are being added to our control plane purely for ARM template deployment support. There was no way to hook up the ARM template engine to our data plane. So we have to have get and create on the control plane.

For any other scenario that involves the manipulation of key-values users are **strongly** urged to use the data plane. We don't want to add APIs to our control plane for which we don't have any scenario that we would tell a user to use it for. In fact, if we added those APIs we would always ask any user not to use them. It seems counter-intuitive.

It seems that the ask here is based on a consistency point-of-view, but I think that in this case the ask would not result in a solid user story.

**Review by pilor — APPROVED** [review]

**Comment by ChenTanyi** [comment]
Please fix the conflict first.

**Review by ChenTanyi — APPROVED** [review]

**Comment by ZhijunZhao** [comment]
#sign-off

**Pull request merged**
