### PR TITLE
upgrade api version for action group, add useUnifiedSchema field to a…

### PR DESCRIPTION
**Pull request by kikicandy11**
…ctions

Also revert an incorrect change in https://github.com/RyanD1/azure-rest-api-specs/commit/39d45decf33f87ddfe651bcd6ca1d9d9c5169df2 that change the api-verion in readme.md file for existing packages

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by veronicagg — CHANGES_REQUESTED** [review]
@kikicandy11 thanks for submitting the PR. It looks like you've copied a previous api-version and just updated a few things for the new api-version. If you're planning to make more changes, it'd be great to have one commit with the original spec you copied and another one with the changes so it's easier to see them. It's recommended to use our on-boarding experience [OpenAPI Hub](http://aka.ms/openapihub) where you can indicate you'd like to create a new api version and it'll copy the files for you and make the api-version changes in the spec and examples too. 

The change to the spec looks fine. Is this new API version already deployed? 
Will you be adding the new spec and api-version to the readme.md file?

**Comment by kikicandy11** [comment]
@veronicagg I don't plan to add more change to the new api-version, this PR includes all the changes.
The new API is not in PROD yet, it's code complete.
When should I add the new spec and api-version to the readme.md file?

**Comment by veronicagg** [comment]
@kikicandy11 It should be in this PR, generally when a new api-version gets introduced, a new tag in the readme.md file gets created with the files you'd ship in the SDK for that version. (BTW, OpenAPIHub would automatically have done this for you, and you could validate it's what you intended). 
Please also edit each language readme.md file, you'll see the generated PRs for SDKs poseted as messages in this PR.
In order to merge this PR, the APIs should be deployed, so that any SDK generated out of it, works for customers. If you need to request SDK releases, please see [OpenAPI Hub - Request SDK release](https://portal.azure-devex-tools.com/app/tools/request-api-release).
Thanks!

**Comment by kikicandy11** [comment]
I merged some changes by mistake, will abandon the PR and create a new one

**Pull request closed without merging**
