### PR TITLE
Add subscriptionId field to AzureResource model

### PR DESCRIPTION
**Pull request by ityankel**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by dosegal — APPROVED** [review]

**Review by liemilyg — APPROVED** [review]

**Comment by xccc-msft** [comment]
@ityankel Can you please check if you can do the fix and pass CIs? Thanks.

cc: @akning-ms

**Comment by ityankel** [comment]
> @ityankel Can you please check if you can do the fix and pass CIs? Thanks.
> 
> cc: @akning-ms

@xccc-msft, I looked at the failed builds and they don't appear to be relevant to my changes as far as I can tell. The errors there are about missing permissions and about a property called 'alerts' which isn't part of the only definition I changed here

**Comment by akning-ms** [comment]
@nullMDR to help take a look

**Comment by NullMDR** [comment]
@qiaozha @changlong-liu Could you please help to verify why do we have such autorest failure?

[AutoRest] FATAL: System.InvalidOperationException: Found incompatible property types Object,  for property 'alerts' in schema inheritance chain 
[AutoRest] FATAL: python/imodeler1 - FAILED

**Comment by changlong-liu** [comment]
hi @ityankel , could you try to rebase to latest master? something fixed 2 days ago

**Comment by ityankel** [comment]
> hi @ityankel , could you try to rebase to latest master? something fixed 2 days ago

Thanks @changlong-liu! I merged with master and now all the automated checks are passing except SDK Python that fails due to "Error in the pull function. The remote end hung up unexpectedly" which sounds like an issue with the check itself

**Comment by changlong-liu** [comment]
hi @ityankel, it seems to be a temporary error, a re-run fixed it.

**Review by xseeseesee — APPROVED** [review]

**Pull request merged**
