### PR TITLE
add mi refresh API

### PR DESCRIPTION
**Pull request by guptanitish-ms**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, Adding an action to an existing API
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  Asap, this is blocking public preview
  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  Asap, this is blocking public preview
  6. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by v-xuto** [comment]
@guptanitish-ms Please fix CI checks errors (`LintDiff`, `PrettierCheck`), you can refer to this [comments](https://github.com/Azure/azure-rest-api-specs/pull/24093#issuecomment-1558032060) or  https://aka.ms/ci-fix on how to fix it.

**Comment by v-xuto** [comment]
@guptanitish-ms Please follow this [comment](https://github.com/Azure/azure-rest-api-specs/pull/24093#issuecomment-1558176821) added by bot to proceed with breaking change review.

**Comment by ericshape** [comment]
> @guptanitish-ms Please follow this [comment](https://github.com/Azure/azure-rest-api-specs/pull/24093#issuecomment-1558176821) added by bot to proceed with breaking change review.

it seems the breaking change in this dev branch is expected.
1. this is a dev branch for 2023-02-01-preview. given this a new API version, the breaking changes are allowed. 
2. all the breaking changes are compared against an old stable version 2021-11-01-stable. But we are working on the 2023-02-01-preview.

**Comment by ericshape** [comment]
@v-xuto we might create an internal shared doc for SQL RP to track all the common failed pipeline results. then we don't need to the pipeline owners to sign off

**Comment by v-xuto** [comment]
@JeffreyRichter Please help review the breaking change in this PR. Thanks a lot.

**Comment by ericshape** [comment]
> You have to justify all the breaking changes shown here: https://github.com/Azure/azure-rest-api-specs/pull/24093/checks?check_run_id=13706303537

@rkmanda the resource name restriction has introduced the breaking change.

**Comment by JeffreyRichter** [comment]
I'm less concerned about the constraint changes but more concerned about the removed enum value and the added x-ms-enum extension.

**Comment by ericshape** [comment]
> I'm less concerned about the constraint changes but more concerned about the removed enum value and the added x-ms-enum extension.

The stable version one exposes more internal detailed state info into the public swagger. We have reverted in the last preview version: https://github.com/Azure/azure-rest-api-specs/pull/22995 and the breaking change has been approved in this old PR.

**Comment by JeffreyRichter** [comment]
OK, I approved the PR


  *   Jeffrey Richter<https://www.linkedin.com/in/jeffrichter/> (see Architecting Distributed Cloud Apps<http://aka.ms/RichterCloudApps> & Designing HTTP APIs<https://www.youtube.com/watch?v=9Ng00IlBCtw&list=PL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65&index=1>)


Azure API Stewardship: Guidelines<https://aka.ms/azapi/guidance>  |  Review process <https://aka.ms/azapi>  |  Recordings<https://aka.ms/azapi/teams>  |  Calendar<https://aka.ms/azapi/calendar>  |  Join the Interest Group<https://aka.ms/azapi/join-interest-group>

Azure SDK Architecture: Guidelines<https://azure.github.io/azure-sdk/general_introduction.html>  |  Review process <https://aka.ms/azsdk/archreview/process>  |  Recordings<https://aka.ms/azsdk/archreview/recordings>  |  Calendar<https://aka.ms/azsdk/archreview/calendar>  |  Join the Interest Group<https://aka.ms/azsdk/archreview/join-interest-group>
________________________________

**Comment by v-xuto** [comment]
@qiaozha Please help review JS breaking change.
@tadelesh Please help review Go breaking change. 
@msyyc Please help review Python breaking change.

**Comment by v-xuto** [comment]
Same azure-sdk-for-net-track2 error as PR [#23802](https://github.com/Azure/azure-rest-api-specs/pull/23802). We can ignore the failure of .NET track 2 automation for sql all the time.
For more details, check comments [#23802 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/23802#issuecomment-1553918082).

**Review by ericshape — APPROVED** [review]

**Review by v-xuto — APPROVED** [review]

**Pull request merged**
