### PR TITLE
Managed Instance short term retention

### PR DESCRIPTION
**Pull request by v-djnisi**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
Should we update relevant tags in the readme file to have reference to this swagger? Please sync with @jaredmooif if you have questions on which tags to update.

Also Is this swagger still in progress? asking because of `[DO NOT MERGE]` in title, if so let me know once you're done with changes, so that we can also start ARM preview.

**Comment by v-djnisi** [comment]
> Should we update relevant tags in the readme file to have reference to this swagger? Please sync with @jaredmoo if you have questions on which tags to update.
> 
> Also Is this swagger still in progress? asking because of `[DO NOT MERGE]` in title, if so let me know once you're done with changes, so that we can also start ARM review.

Swagger is done, but I can't check it in because of queue freeze. I need  to let you know when I complete the code review and check this in? Regarding tags I need to sync with @jaredmoo since I am not sure.

**Comment by anuchandy** [comment]
@v-djnisi sounds good, let us know when it is ready to merge. Will do review from SDK side. Requesting ARM review.

**Comment by ravbhatnagar** [comment]
looks good. Signing off from ARM.

**Review by jaredmoo — APPROVED** [review]

**Comment by jaredmoo** [comment]
This Swagger can be merged when the API is publicly available in at least 1 production region.

The new Swagger file names can be added to readme.md when the azure-sdk-for-net change (including scenario tests) has been implemented. It's preferable to do that readme.md change in this PR.

It looks like the ETA might be a couple weeks, so we might choose to temporarily close the PR until then. However that doesn't mean you did anything wrong by opening this PR early, it was a good thing that you got ARM team's review nice and early on this so we don't have any surprises later. :)

**Comment by v-djnisi** [comment]
API is now publicly available on Pilot.

**Comment by anuchandy** [comment]
@v-djnisi what exactly pilot means? Merging PR requires service to be available in at least one production region.

**Comment by v-djnisi** [comment]
@anuchandy It is a WestCentralUS production region.

I have a question about readme.md. I can add changes to this pull request, but we want only clients for live databases for now(ManagedBackupShortTermRetention.json). Managed dropped databases clients are not generated, and they will be added in another PR, therefor adding configurable retention(ManagedRestorableDroppedDatabaseBackupShortTermRetenion.json) for them doesn't make sense right now. Is it OK to add scenario tests only for configurable backup retention on live databases, and add only that API to readme.md?

Another note, scenario tests for CBR require a managed database. I read the instructions on OneNote and it says that it needs to work regardless of subscription. That would require us to create a new resource group and a new instance. This is expensive and takes time. I saw there are tests that are running on already existing Managed Instance, is it OK for me to do the similar thing?

**Comment by jaredmoo** [comment]
Whatever features are in readme.md must have scenario tests. If some feature is not ready yet, then don't add it to readme.md.

There are scenario tests that create managed instance - see https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/SqlManagement/Sql.Tests/ManagedInstanceTestFixture.cs . This is slow but automation is critical.

**Comment by v-djnisi** [comment]
Link to the azure-sdk-for-net PR: https://github.com/Azure/azure-sdk-for-net/pull/4934

**Comment by v-djnisi** [comment]
Azure-sdk-for-net PR is approved and is waiting for this PR to be merged. Can we merge this PR now?

**Comment by v-djnisi** [comment]
@jaredmoo @anuchandy @ravbhatnagar  @hovsepm Ping!

**Comment by jaredmoo** [comment]
I have already approved.

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
