### PR TITLE
Fixed/suppressed most linter warnings/errors for Microsoft.Sql

### PR DESCRIPTION
**Pull request by jaredmoo**
Fixed all linter warnings/errors for Microsoft.Sql that do not require changes in service.

Contains major SDK breaking changes. Since I had to do a few to fix warnings, I decided to go all out and make additional changes to operation ids that are not necessary at this time but will help future-proof the sdks. This mainly involves normalizing operation ids so they more closely follow the standard "Resource_Verb" style, instead of "ParentResource_VerbChildResource" which we were using in several cases.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
Note: I added a file that contains validation warnings per commit so I could track my progress. This should be removed before final checkin.

**Comment by jaredmoo** [comment]
interested folks from sql : @nathannfan @tomapaunovic @mihymel @pixia @yaakoviyun @ranisha2

**Comment by jaredmoo** [comment]
Currently reviewing validation results from travis. Seems like autobot is broken: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090219#L645

**Comment by jaredmoo** [comment]
Warnings to fix, all example validation issues introduced by previous PRs:
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1372
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1537
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1558
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1579
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1600
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1671
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1678
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L1685
[ ] https://travis-ci.org/Azure/azure-rest-api-specs/jobs/255090218#L2466

**Comment by jaredmoo** [comment]
Should be ready to review now. Changes have been tested in .NET SDK at https://github.com/jaredmoo/azure-sdk-for-net/tree/breakingchanges

**Comment by vishrutshah** [comment]
Closing and reopening the PR to have latest fix from `current` branch for CI.

**Comment by jaredmoo** [comment]
@jhendrixMSFT build is passing now that ruby is fixed, can you review? Thanks!

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by devigned** [comment]
@salameer and @jhendrixMSFT this pull request changes an existing stable API version. It seems like the changes here should have happened in a new API version rather than breaking the older one. I'm worried about the precedent this sets for breaking changes to published libraries.   /cc @milismsft @marstr

**Comment by jhendrixMSFT** [comment]
@devigned I will defer to @jaredmoo but as I recall their SDK is in preview plus (and more importantly) the swagger didn't accurately describe the REST endpoints so the generated SDKs didn't work all that well.

**Comment by jaredmoo** [comment]
This change did not modify the REST API in any way, just the generated method names in various SDKs which are all in preview.

**Comment by devigned** [comment]
@jaredmoo I noticed that it was almost solely name changes and that was what bugged me about it. Since they are in preview, they are subject to change, but there is no good mechanism to telegraph the breaking changes to consumers. 

In this case, I think would rather these libs been greater than or equal 1.0 since they have been out for about a year and they target API versions from as old as 2014. At least if they had reached 1.0 prior to the changes, consumers of the libraries would have seen a major version increase providing them warning of the breaking nature of the changes.

Clearly, the consistency in naming is a benefit. Thank you for taking the time to improve the experience for future consumers of the service.

Hopefully, these libraries can get to 1.0 sooner than later.

**Comment by jaredmoo** [comment]
In python and .NET SDK releases I have added pypi/nuget release notes detailing the changes. Let me know if there's anything else I can do here.

**Pull request merged**
