### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-03-01

### PR DESCRIPTION
**Pull request by FumingZhang**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
    Already deployed to all global regions by 2022-04-05 and sov clouds by 2022-04-10.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
    2022-04-15
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Dear review board, I would like to clarify the failures in the CI checks. Basically, all the errors are expected and similar with the previous [03-02-preview PR](https://github.com/Azure/azure-rest-api-specs/pull/18633).

For [Cross-Version Breaking Changes](https://github.com/Azure/azure-rest-api-specs/pull/18686/checks?check_run_id=6019040764), this is introduced in PR [#18568](https://github.com/Azure/azure-rest-api-specs/pull/18568). The failure is due to removing duplicate definitions. Now they are replaced with references to common types. For more details, please refer to the [comment](https://github.com/Azure/azure-rest-api-specs/pull/18567#issuecomment-1089909123) and the [https://github.com/Azure/azure-rest-api-specs-pr/pull/6845#issuecomment-1089835682](https://github.com/Azure/azure-rest-api-specs-pr/pull/6845#issuecomment-1089835682).

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/18686/checks?check_run_id=6019060627), I suppose this should be a known issue. According to the error log, the reason for the error is the permission problem when the pipeline is executed, which has nothing to do with this PR.

For [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/18686/checks?check_run_id=6019040586), all the files ([2017-07-01/containerService.json](https://github.com/Azure/azure-rest-api-specs/blob/93398405721633a0286969a088a0bb65438fb699/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2017-07-01/containerService.json), [2017-08-31/managedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/93398405721633a0286969a088a0bb65438fb699/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2017-08-31/managedClusters.json), [2019-08-01/location.json](https://github.com/Azure/azure-rest-api-specs/blob/93398405721633a0286969a088a0bb65438fb699/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-08-01/location.json), [2019-04-30/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/93398405721633a0286969a088a0bb65438fb699/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-04-30/openShiftManagedClusters.json)) mentioned in the error log are deprecated. Currently, only managedCluster is supported by us, the rest such as containerService, openShiftManagedClusters, location, etc. are all deprecated. There were similar issues in previous [02-01 swagger PR](https://github.com/Azure/azure-rest-api-specs/pull/18324#issuecomment-1073500751), [03-02-preview swagger PR](https://github.com/Azure/azure-rest-api-specs/pull/18633#issuecomment-1094821697).

For [Swagger SDK Breaking Change Tracking](https://github.com/Azure/azure-rest-api-specs/pull/18686/checks?check_run_id=6019040938),

- For Go, JS and Python SDK, the scanned changelogs are all because the basic type has changed, replacing the `Resouce` definition once customized in swagger with the `TrackedResource` in common types, and then referencing the pure `Resouce` definition. I don't think these changes would have a directly perceptible impact on users. Could you please help confirm and approve the changes @ArcturusZhang, @qiaozha, @msyyc? Thanks!

**Review by j5lim — APPROVED** [review]
Approved from ARM side.

**Comment by FumingZhang** [comment]
I would like to re-clarify the errors about the missing APIs, from the error log, it's complaining

- {"level":"Error","code":"MISSING_APIS_IN_DEFAULT_TAG","message":"The default tag does not contain all APIs in this RP. Please make sure the missing API swaggers are in the default tag.","tag":"default","readMeUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/readme.md","jsonUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/Microsoft.ContainerService/**stable/2017-07-01/containerService.json**","**path":"/subscriptions/{}/resourceGroups/{}/providers/Microsoft.ContainerService/containerServices"**}
  - All paths under containerServices are deprecated.
- {"level":"Error","code":"MISSING_APIS_IN_DEFAULT_TAG","message":"The default tag does not contain all APIs in this RP. Please make sure the missing API swaggers are in the default tag.","tag":"default","readMeUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/readme.md","jsonUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/Microsoft.ContainerService/**stable/2017-08-31/managedClusters.json**",**"path":"/subscriptions/{}/resourceGroups/{}/providers/Microsoft.ContainerService/managedClusters/{}/accessProfiles/{}"**}
  - The path mentioned above is deprecated. Now the path is `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}/accessProfiles/{roleName}/listCredential`.
- {"level":"Error","code":"MISSING_APIS_IN_DEFAULT_TAG","message":"The default tag does not contain all APIs in this RP. Please make sure the missing API swaggers are in the default tag.","tag":"default","readMeUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/readme.md","jsonUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/Microsoft.ContainerService/**stable/2019-08-01/location.json**",**"path":"/subscriptions/{}/providers/Microsoft.ContainerService/locations/{}/orchestrators"**}
  -  The path mentioned above is still in use. However, due to the conflict of swagger definitions, we could not put this file into the latest api tag (been a long time). We need to update this api on the rp side first, and then update the corresponding swagger file. 
- {"level":"Error","code":"MISSING_APIS_IN_DEFAULT_TAG","message":"The default tag does not contain all APIs in this RP. Please make sure the missing API swaggers are in the default tag.","tag":"default","readMeUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/readme.md","jsonUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/containerservice/resource-manager/Microsoft.ContainerService/**stable/2019-04-30/openShiftManagedClusters.json**",**"path":"/subscriptions/{}/resourceGroups/{}/providers/Microsoft.ContainerService/openShiftManagedClusters/{}"**}
  - - All paths under openShiftManagedClusters are deprecated.

**Comment by FumingZhang** [comment]
Hi @chunyu3, I suppose the CI failure does not indicate a true breaking change. I've filed a false positive report with https://aka.ms/swaggerfeedback.

I'm copying the comment of [pilot PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/6845) here. cc @serbrech, @ruowan, @ArcturusZhang, @palma21, @matthchr 

> @ruowan seeking feedback on this.
> 
> detected breaking changes :
> 
> Rule | Message
> -- | --
> ❌ 1006 - RemovedDefinition | The new version is missing a definition that was found in the old version. Was 'SystemData' removed or renamed?New: Microsoft.ContainerService/preview/2022-06-02-preview/managedClusters.json#L2221:3Old: Microsoft.ContainerService/stable/2022-02-01/managedClusters.json#L2221:3
> ❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'location' renamed or removed?New: common-types/resource-management/v3/types.json#L13:7Old: Microsoft.ContainerService/stable/2022-02-01/managedClusters.json#L2287:7
> ❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'tags' renamed or removed?New: common-types/resource-management/v3/types.json#L13:7Old: Microsoft.ContainerService/stable/2022-02-01/managedClusters.json#L2287:7
> 
> `managedCluster.json` defined a local type `Resource` that was identical to the common-types v3 `TrackedResource`
> 
> I replaced its usage with the common-type TrackedResource (3 occurences):
> example : https://github.com/Azure/azure-rest-api-specs-pr/blob/cc3e90b0a9809d285262880ecf35a1d955bea10f/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-02-01/managedClusters.json#L4128
> 
> ```
> "allOf": [
>         {
>           "$ref": "#/definitions/Resource"
>         }
>       ],
> ```
> 
> becomes : 
> ```
> "allOf": [
>         {
>           "$ref": "../../../../../common-types/resource-management/v3/types.json#/definitions/TrackedResource"
>         }
> ```
> 
> I had to delete the current local Resource definition, because the TrackedResource was found to be identical by the linting.
> and the common-types contains a different definition for Resource (which is TrackedResource minus tags and location).
> this is why the breaking change detector finds 2 missing properties.
> 
> I think that this is false alarm. the API stays strictly the same, the generated code as well.

**Pull request merged**
