### PR TITLE
[Azure Search] New GA data-plane API spec for version 2019-05-06

### PR DESCRIPTION
**Pull request by bitsforthought**
We are rolling out a new GA API version for the Azure Search data plane. The Swagger specs are copied from 2017-11-11-Preview. Review commits separately to see what the deltas are from that version.

The new specs are in `stable` directories to reflect the fact that these are the first all-new data plane specs for Azure Search that cover 100% of the REST API surface area. Per our policy for API versioning, we will not introduce any breaking changes to these specs, but may introduce backward compatible changes from time to time as features come out of preview.

FYI @Yahnoosh @arv100kri @shmed @ishansrivastava90 @updixit @natinimni

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by natinimni — APPROVED** [review]
LGTM

**Review by arv100kri — APPROVED** [review]

**Comment by sarangan12** [comment]
I have reviewed this PR and changes look fine. Only the ModelValidation Job is failing. But this is a known issue. So, I will approve this PR. Since this is a data-plane API, does not require a ARM approval.

So, I will be approving and merging this PR now

**Review by sarangan12 — APPROVED** [review]

**Comment by dsgouda** [comment]
Expected Net SDK error since we don't auto generate a PR for them,

**Comment by brjohnstmsft** [comment]
@sarangan12 You've approved it, but not yet merged it. Is something blocking merging?

**Review by ishansrivastava90 — APPROVED** [review]

**Pull request merged**
