### PR TITLE
Revert "Adding a new stable API-version 2023-05-01"

### PR DESCRIPTION
**Pull request by Shashank1306s**
Reverts Azure/azure-rest-api-specs#23541

Reasons to revert back the API-version 2023-05-01

1. The swagger PR was checked in, but the API version is not present in ARM manifest.
2. There has been a chronological disorder in the API-version check-in as we have merged 2023-05-01 but 2023-04-01-preview is still in review phase.

### CODE REVIEW

**Review by live1206 — APPROVED** [review]

**Comment by tombuildsstuff** [comment]
@live1206 @Shashank1306s why was this Stable API Version removed?

This API Version's already shipped into downstream tooling ([for example this API Version has shipped into `hashicorp/go-azure-sdk`](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/dataprotection/2023-05-01)) - so unfortunately reverting this has broken our CI pipeline: https://github.com/hashicorp/pandora/actions/runs/4762723313/jobs/8465283635?pr=2412#step:4:683

My understanding is that once a Stable API Version is merged into this repository it then needs to go through the standard 3 year deprecation cycle - so could you elaborate on why this API Version's been removed suddenly, since there's no reasoning listed in this PR? cc @mikekistler

Thanks!

**Comment by live1206** [comment]
> @live1206 @Shashank1306s why was this Stable API Version removed?
> 
> This API Version's already shipped into downstream tooling ([for example this API Version has shipped into `hashicorp/go-azure-sdk`](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/dataprotection/2023-05-01)) - so unfortunately reverting this has broken our CI pipeline: https://github.com/hashicorp/pandora/actions/runs/4762723313/jobs/8465283635?pr=2412#step:4:683
> 
> My understanding is that once a Stable API Version is merged into this repository it then needs to go through the standard 3 year deprecation cycle - so could you elaborate on why this API Version's been removed suddenly, since there's no reasoning listed in this PR? cc @mikekistler
> 
> Thanks!

@tombuildsstuff AFAIK, we haven't released any SDK for this swagger version, so the stable API version is not available to the users yet. It should be safe to revert the swagger change, please let me know if I am wrong about this.

Listing the reasons from @Shashank1306s from mail thread;
             1. The swagger PR was checked in, but the API version is not present in ARM manifest yet.
             2. There has been a chronological disorder in the API-version check-in as we have merged 2023-05-01 but 2023-04-01-preview is still in review phase.

**Comment by tombuildsstuff** [comment]
@live1206 FWIW we parse the API Definition files directly (since we don't consume the AutoRest Tags as we intentionally don't want to support Composite API Versions) - so support for this API Version has already shipped on our side (see https://pkg.go.dev/github.com/hashicorp/go-azure-sdk@v0.20230420.1163422/resource-manager/dataprotection/2023-05-01).

From our side, once a Stable API Version has been merged into this repository - we consider this ready to consume by our tooling - so whilst I can understand removing a Preview API version (which IIRC should go through a ~3 month deprecation period) - removing a Stable API Version should go through the standard 3 year deprecation period AFAIK?

For the moment we can remove support for this API version on our side (since it sounds like this isn't fully deployed on the ARM side?), which is being tracked in https://github.com/hashicorp/pandora/pull/2419.

However it would be helpful for consumers of the API Definitions to have context for these removals, rather than an empty PR description without any context (which has meant we've had to spend time investigating why, rather than just working around this), particularly since this has had the `breaking-changes-approved` label added?

**Comment by mikekistler** [comment]
I agree with @tombuildsstuff that stable versions committed to the public main branch should not be pulled back or changed in any non-breaking manner without going through breaking change review.

If the service was not yet available to users then it should not have merged to main in the first place.

**Comment by live1206** [comment]
> I agree with @tombuildsstuff that stable versions committed to the public main branch should not be pulled back or changed in any non-breaking manner without going through breaking change review.
> 
> If the service was not yet available to users then it should not have merged to main in the first place.

Thanks @mikekistler for the clarification, I will be not pull back any change without breaking change review anymore and will share this with the other team members.

**Comment by live1206** [comment]
> @live1206 FWIW we parse the API Definition files directly (since we don't consume the AutoRest Tags as we intentionally don't want to support Composite API Versions) - so support for this API Version has already shipped on our side (see https://pkg.go.dev/github.com/hashicorp/go-azure-sdk@v0.20230420.1163422/resource-manager/dataprotection/2023-05-01).
> 
> From our side, once a Stable API Version has been merged into this repository - we consider this ready to consume by our tooling - so whilst I can understand removing a Preview API version (which IIRC should go through a ~3 month deprecation period) - removing a Stable API Version should go through the standard 3 year deprecation period AFAIK?
> 
> For the moment we can remove support for this API version on our side (since it sounds like this isn't fully deployed on the ARM side?), which is being tracked in [hashicorp/pandora#2419](https://github.com/hashicorp/pandora/pull/2419).
> 
> However it would be helpful for consumers of the API Definitions to have context for these removals, rather than an empty PR description without any context (which has meant we've had to spend time investigating why, rather than just working around this), particularly since this has had the `breaking-changes-approved` label added?

@tombuildsstuff 
image
The PR was merged 1 day before the reverting, so I wrongly assumed there is no down-stream dependencies. I guess `dataprotect` team were not aware of this, either. Otherwise, the reverting would not be raised in the first place.
Which RPs does your product depend on? If anything like this happen again, we could give you a heads-up. 

@mikekistler Is there a way to know the down-stream dependencies of the public swagger? I guess breaking change review board would need to evaluate the dependencies as well during the breaking change review for this case.

**Comment by live1206** [comment]
@tombuildsstuff 
Thank you for sharing the information, it's good to know about the 24-hour syncing from your side.
And I will make sure to get the comments added to PR if conversation happens in mail thread or Teams chat in the future.

**Pull request merged**
