### PR TITLE
Release microsoft.app 2023 05 02 preview

### PR DESCRIPTION
**Pull request by Juliehzl**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by Juliehzl** [comment]
All changes from https://github.com/Azure/azure-rest-api-specs/tree/release-Microsoft.App-2023-05-02-preview/specification. The only change is to merge main branch.

**Comment by zizw123** [comment]
> All changes from https://github.com/Azure/azure-rest-api-specs/tree/release-Microsoft.App-2023-05-02-preview/specification. The only change is to merge main branch.

Can you help confirm: I see 15 commits in the PR, are first 14 from already approved PR? And this is just merging to main?

**Comment by Juliehzl** [comment]
> > All changes from https://github.com/Azure/azure-rest-api-specs/tree/release-Microsoft.App-2023-05-02-preview/specification. The only change is to merge main branch.
> 
> Can you help confirm: I see 15 commits in the PR, are first 14 from already approved PR? And this is just merging to main?

Yes, all previous commit are reviewed. Only last one is to merge main

**Review by rkmanda — APPROVED** [review]

**Comment by rkmanda** [comment]
Can u point me to the specific PR where the AdditionalProperties violation was approved please?

**Comment by Juliehzl** [comment]
All these changes are added in [Adds base for updating Microsoft.App from version preview/2023-04-01-… · Azure/azure-rest-api-specs@8126c9d (github.com)](https://github.com/Azure/azure-rest-api-specs/commit/8126c9d2510d9d57478e075b57f72d34485540d6) and which is copied from previous version via OpenAPIHub.

**Comment by konrad-jamrozik** [comment]
@rkmanda if this re-run you just did won't help I'll have a look what's up.

**Comment by konrad-jamrozik** [comment]
@rkmanda some checks are stuck in queued state but the underlying pipeline is [all green](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2996642&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b) and @Juliehzl requested merge. I also see all the labels and approvals are in order. So I am going to unblock the queued stuck checks.

**Pull request merged**
