### PR TITLE
Adding a how to link for creating dataset with GeoJSON

### PR DESCRIPTION
**Pull request by tejitpabari99**
Add link to a How-to document to make dataset from GeoJSON files
Spell-correct geojson to GeoJSON

# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc: (Swagger isn't released to public yet, but can be found at path: azure-rest-api-specs/blob/main/specification/maps/data-plane/Creator/preview/2022-09-01-preview/dataset.json
* Updated paths: azure-rest-api-specs/blob/main/specification/maps/data-plane/Creator/preview/2022-09-01-preview/dataset.json

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by johanste — APPROVED** [review]

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@tejitpabari-microsoft you need to fix the model validation failures.

**Comment by tejitpabari99** [comment]
> @tejitpabari-microsoft you need to fix the model validation failures.

Not sure why its there, or how to resolve it. According to the guidelines, we have an "Operation-Location" header as part of the response model.
Could you let me know what steps I can take to resolve this.

**Comment by tjprescott** [comment]
The link describing how to fix model validation errors is here:
https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md#model-validation

It probably means your example responses don't include the required location header.

**Comment by tejitpabari99** [comment]
The [API guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#post-or-delete-lro-pattern) state that LRO should have an operation-location header, but makes no reference to "location header or azure-AsyncOperation header" as per the (validation error)[https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#lro_response_header]. 
There seems to be some discrepancy between the docs and the validation error in this case. 

Also, is this validation requirement a new addition? Since I haven't changed anything related to LRO in this PR, however, our PR for the new service version was accepted just weeks ago. We also got an exception for keeping the old LRO format to stay consistent with our other services/versions.

**Comment by tejitpabari99** [comment]
One of the devs on our team got an exception for our team for Model Validation. Here is the email confirming that:

> From: Weidong Xu <notifications@github.com>
Sent: Sunday, October 30, 2022 7:50 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: David Stanchi <David.Stanchi@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] [Hub Generated] Review request for Creator to add version preview/2022-09-01-preview (PR #20516) <br/>
Ignore BreakingChange and ModelValidation
BreakingChanges compare to 2022-09-01-preview in main and figure out several new APIs. Data-plane usually have different jsons.
ModelValidation on "LRO_RESPONSE_HEADER" only apply to ARM.

Since LRO_RESPONSE_HEADERS only apply to the ARM, as per the above email, could we ignore that for the PR?

**Comment by tjprescott** [comment]
@tejitpabari99 it would be better to forward the email to me. If the check in question is not applicable to data planes, then it should never trigger instead of producing false alarms like this.

**Comment by tejitpabari99** [comment]
> @tejitpabari99 it would be better to forward the email to me. If the check in question is not applicable to data planes, then it should never trigger instead of producing false alarms like this.

Just did!

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/21418
Filed an issue, this this failure is a bug on EngSys.

**Comment by tjprescott** [comment]
@lmazuel can you please force merge this? The ModelValidation failure is a false alarm.

**Pull request merged**
