### PR TITLE
Azure ML new API version 20210401

### PR DESCRIPTION
**Pull request by SubaMoorthy**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by allenjzhang** [comment]
@SubaMoorthy , please review Avacado error and make corrections.

**Comment by allenjzhang** [comment]
>               "$ref": "#/definitions/MachineLearningServiceError"

Would like to see you reference the standard error schema under common-types/v2

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:59 in c0959d0. [](commit_id = c0959d09b3544f8d1fa34b60d5d7e54380450c45, deletion_comment = False)

**Comment by allenjzhang** [comment]
>             "$ref": "#/parameters/APIVersionParameter"

Would like to see you reference the standard parameters under common-types/v2

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:82 in c0959d0. [](commit_id = c0959d09b3544f8d1fa34b60d5d7e54380450c45, deletion_comment = False)

**Comment by allenjzhang** [comment]
>         "operationId": "ListSkus",

Workspaces_ListSkus

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:1223 in c0959d0. [](commit_id = c0959d09b3544f8d1fa34b60d5d7e54380450c45, deletion_comment = False)

**Comment by allenjzhang** [comment]
>               "$ref": "#/definitions/PrivateEndpointConnection"

Can you reconcile this with PrivateEndpoint definitions under common-types ?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:1289 in c0959d0. [](commit_id = c0959d09b3544f8d1fa34b60d5d7e54380450c45, deletion_comment = False)

**Comment by SubaMoorthy** [comment]
> > ```
> >           "$ref": "#/definitions/PrivateEndpointConnection"
> > ```
> 
> Can you reconcile this with PrivateEndpoint definitions under common-types ?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:1289 in [c0959d0](https://github.com/Azure/azure-rest-api-specs/commit/c0959d09b3544f8d1fa34b60d5d7e54380450c45). [](commit_id = [c0959d0](https://github.com/Azure/azure-rest-api-specs/commit/c0959d09b3544f8d1fa34b60d5d7e54380450c45), deletion_comment = False)

Adding reference to common-types is causing model validation errors on location and identity properties. That's the reason decided to not use common-types reference in this version.

**Comment by varunkumta** [comment]
>         "subscriptionState": {

can you elaborate why you need to expose these properties in the workspace? there are other apis that are source of truth for this.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:2377 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "createdOn": {

please update your examples too, for all these added properties

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3226 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>                 "LoadBalancerType": {

camelCase property names please

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3317 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>                 "LoadBalancerSubnet": {

is this a subnet resource id? then it should be named loadBalancerSubnetId or similar

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3330 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>                 "isNotebookInstanceCompute": {

you should use enums instead of bools as they are more extensible. search for boolean in [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean).

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3618 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "target": {

in order to avoid having to make such changes you should be ref'ing these from common-types

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:4205 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "SynapseSpark"

don't you need to add a definition which specifies this as its x-ms-discriminator-value - like you have for the other values?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:4157 in df1a995. [](commit_id = df1a9953ffa71a1509afdcb8a12de522dfae18db, deletion_comment = False)

**Comment by joshanator** [comment]
> > ```
> >     "target": {
> > ```
> 
> in order to avoid having to make such changes you should be ref'ing these from common-types
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:4205 in [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db). [](commit_id = [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db), deletion_comment = False)

Per SubaMoorthy, "Adding reference to common-types is causing model validation errors on location and identity properties. That's the reason decided to not use common-types reference in this version."

**Comment by joshanator** [comment]
> > ```
> >             "isNotebookInstanceCompute": {
> > ```
> 
> you should use enums instead of bools as they are more extensible. search for boolean in https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3618 in [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db). [](commit_id = [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db), deletion_comment = False)

This should be done in the future. In this version we will keep as boolean to stay consistent with other instances and the code impl.

**Comment by joshanator** [comment]
> > ```
> >             "LoadBalancerSubnet": {
> > ```
> 
> is this a subnet resource id? then it should be named loadBalancerSubnetId or similar
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:3330 in [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db). [](commit_id = [df1a995](https://github.com/Azure/azure-rest-api-specs/commit/df1a9953ffa71a1509afdcb8a12de522dfae18db), deletion_comment = False)

It is different. ex: "aks-subnet"

**Comment by varunkumta** [comment]
>             },

wont these be available in the uri itself?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:6678 in 235a15e. [](commit_id = 235a15eba7774f6c8e102eef08ffa1ebb8f9e0ed, deletion_comment = False)

**Comment by joshanator** [comment]
> > ```
> >         },
> > ```
> 
> wont these be available in the uri itself?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json:6678 in [235a15e](https://github.com/Azure/azure-rest-api-specs/commit/235a15eba7774f6c8e102eef08ffa1ebb8f9e0ed). [](commit_id = [235a15e](https://github.com/Azure/azure-rest-api-specs/commit/235a15eba7774f6c8e102eef08ffa1ebb8f9e0ed), deletion_comment = False)

This matches the implementation. Im not sure why but these fields are included in the properties

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
