### PR TITLE
Network 2022 05 01

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
@msyyc  @BigCat20196 can you please review and approve it?Failed jobs don't look critical and we've skipped them previously (like camel case etc)
Pls approve in case it's possible?

**Comment by msyyc** [comment]
Hi @MikhailTryakhov I approved for python breaking. Please contact assignee to check other CI items

**Comment by lirenhe** [comment]
@tadelesh,  @qiaozha, @weidongxu-microsoft  are those SDK breaking changes expected?

**Comment by MikhailTryakhov** [comment]
Guys, can we have a meeting to discuss it quicker? It's really important to merge it ASAP

**Comment by tadelesh** [comment]
Breaking has approved from this [PR](https://github.com/Azure/azure-rest-api-specs/pull/19985). Approved for Go.

**Comment by weidongxu-microsoft** [comment]
If Jeffery approved it, what's the point whether SDK approves or not...

**Comment by lirenhe** [comment]
The breaking changes in Swagger were approved in seperate PRs.

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
