### PR TITLE
[App Service] Update swagger spec for ANT80 (#5111)

### PR DESCRIPTION
**Pull request by naveedaz**
* Update swagger spec for ANT80

* Fix some spelling errors that were reverted by previous commit

* Move certificate examples to new API version folder

* Add the 2018-02-01 certificates files back

* This change is already merged into master. Cherry-picking to ANT80  branch. 

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [X] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by naveedaz** [comment]
This PR is cherry-picking the change from https://github.com/Azure/azure-rest-api-specs/pull/5111 to ANT80 branch

**Review by nking-1 — APPROVED** [review]

**Comment by naveedaz** [comment]
@hovsepm Can you please merge?

**Review by veronicagg — CHANGES_REQUESTED** [review]
I see  model validation failures in the PR - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/495628581#L585
Are you intending to merge this cherry picked PR as-is?
Thanks!

**Comment by naveedaz** [comment]
All of those validation errors are not new. 
They are mostly missing examples.

**Comment by veronicagg** [comment]
@naveedaz I understand, just making sure you're aware.

**Comment by veronicagg** [comment]
I'm merging this to your branch since you're just bringing changes from anothe PR, be aware that Java and Node SDK generation are also failing, you can take a look at CI above, and will need to get fixed for the PR going to master. Thanks!

**Review by veronicagg — APPROVED** [review]
Approving since this is cherry picking changes from PR/commit to the team's working branch.

**Comment by naveedaz** [comment]
Thanks. :)

**Pull request merged**
