### PR TITLE
updated application gateway limits descriptions

### PR DESCRIPTION
**Pull request by tfitzmac**
Added links to limits page, based on user feedback.

### CODE REVIEW

**Comment by dsgouda** [comment]
@tfitzmac I don't think you can make these changes to older versions of the API.
@MikhailTryakhov please take a look

**Comment by MikhailTryakhov** [comment]
@dsgouda is right, there is no need to publish changes in old APIs - they'll never be delivered. Only the latest API version is in use on clients, SDKs.

**Comment by MikhailTryakhov** [comment]
closed cause there is no need to update old versions

**Comment by tfitzmac** [comment]
@MikhailTryakhov - for ARM templates, any version of the API could be used. This request specifically came from a customer trying to deploy an application gateway with an ARM template and had no information about the limits for those values. We generate documentation for many versions.

**Comment by tfitzmac** [comment]
Added PR #5186 for same change to latest version.

**Pull request closed without merging**
