### PR TITLE
Renamed CancelAddParticipant to CancelAddParticipantOperation

### PR DESCRIPTION
**Pull request by vivekmore-msft**
Renamed CancelAddParticipant to CancelAddParticipantOperation

### CODE REVIEW

**Review by huachuandeng — APPROVED** [review]

**Comment by JeffreyRichter** [comment]
Why would you append "Operation" to CancelAddParticipantOperation?
I've never seen any example in all of Azure that appends "Operation" to the action after the colon.
Seems to me it was better before this change.

**Comment by vivekmore-msft** [comment]
> Why would you append "Operation" to CancelAddParticipantOperation? I've never seen any example in all of Azure that appends "Operation" to the action after the colon. Seems to me it was better before this change.

@JeffreyRichter We updated it to fix comment from SDK review. This is bit more clear that we are cancelling existing add participant operation/request.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by jutik0** [comment]
> Why would you append "Operation" to CancelAddParticipantOperation? I've never seen any example in all of Azure that appends "Operation" to the action after the colon. Seems to me it was better before this change.

@JeffreyRichter - doublechecking on this comment. As you approved the review.  Does it mean you are OK keeping the 'operation' suffix in this case based on the explanation given by Vivek?

**Comment by JeffreyRichter** [comment]
I don't actually think it is the right thing to do but I approved it anyway.
If the original operation action is AddParticipant then I think CancelAddParticipant is the right action name to counter the first action.

**Comment by vivekmore-msft** [comment]
As per feedback by @JeffreyRichter and discussion with team we have decided to not merge this change. So closing this PR.

**Pull request closed without merging**
