### PR TITLE
[Storage] Add data plane Blob Storage swagger

### PR DESCRIPTION
**Pull request by tg-msft**
Add a swagger spec for the `2020-10-02` version of Blob Storage.

### CODE REVIEW

**Review by tjprescott — APPROVED** [review]
For all practical purposes, there is no way I can review a 12k line Swagger, so I am purely relying on the CI for this approval.

**Comment by tasherif-msft** [comment]
LGTM

**Comment by tjprescott** [comment]
You need to resolve the conflicts before this can be merged.

**Comment by tasherif-msft** [comment]
@tjprescott I have resolved the conflict

**Pull request merged**
