### PR TITLE
Update api description

### PR DESCRIPTION
**Pull request by yifan-zhou922**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by ms-bogdan-rotaru** [comment]
This cannot be merged yet as it's pending required reviews.

**Comment by yifan-zhou922** [comment]
@mikekistler, @DominikMe , could you please help review the PR? The changes are only related to documentation. Many thanks.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
approved but you have conflicts

**Pull request merged**
