### PR TITLE
DAG API 2023-02-01

### PR DESCRIPTION
**Pull request by a-lazarlazic**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. ASAP
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. ASAP
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

**We're in process of creating the template for breaking changes and contacting breaking change review folks**

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by v-xuto** [comment]
@a-lazarlazic Please fix CI checks errors (`LintDiff`, `Model validation`), you can refer to this [comments](https://github.com/Azure/azure-rest-api-specs/pull/24108#issuecomment-1559047673) or  https://aka.ms/ci-fix on how to fix it.

**Comment by visingla-ms** [comment]
>           "default": {

There are a bunch of breaking changes reported on this PR. Please get a breaking changes approval from Azure Breaking Changes Reviewers <azbreakchangereview@microsoft.com> and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/DistributedAvailabilityGroups.json:47 in f7f91c9. [](commit_id = f7f91c9f1f4f8fab0181bab7c06ee5974d2056c0, deletion_comment = False)

**Comment by visingla-ms** [comment]
>               "$ref": "#/definitions/DistributedAvailabilityGroupsCreateOrUpdateRequestBody"

Please fix the Linter Errors also.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/DistributedAvailabilityGroups.json:243 in f7f91c9. [](commit_id = f7f91c9f1f4f8fab0181bab7c06ee5974d2056c0, deletion_comment = False)

**Comment by v-xuto** [comment]
@JeffreyRichter Please help review the breaking change in this PR.

**Comment by JeffreyRichter** [comment]
A lot of properties are being removed from the last stable release. Why all these breaking changes?

**Comment by JeffreyRichter** [comment]
But these are all breaking changes for your customers. What is your team's plan to deal with all the customer issues that result from all these breaks.

-- Jeffrey
________________________________

**Comment by a-lazarlazic** [comment]
There's an item in ADO that refers to these changes: Scenario 24090062: Add new properties needed, delete unneeded for MI link get-status API (in gated preview) - Boards (visualstudio.com)<https://msazure.visualstudio.com/One/_workitems/edit/24090062>.
Does information in the item answer your question?

Lazar
________________________________

**Comment by a-lazarlazic** [comment]
friendly ping @JeffreyRichter, I'm blocked on breaking change review

**Comment by JeffreyRichter** [comment]
I approved this PR but somewhat begrudgingly as it does break your customers so you will have to make the formal announcement and keep the old api-versions working as-is for 3 years.

**Comment by a-lazarlazic** [comment]
> I approved this PR but somewhat begrudgingly as it does break your customers so you will have to make the formal announcement and keep the old api-versions working as-is for 3 years.

Thank you for reviewing @JeffreyRichter! Could you please elaborate on why the old api-versions need to exist for the next 3 years instead of 90 days you mentioned in here: [https://msazure.visualstudio.com/One/_workitems/edit/24090062](https://msazure.visualstudio.com/One/_workitems/edit/24090062)?

**Comment by JeffreyRichter** [comment]
I see breaks to api-version 2021-11-01 which is not a preview version and therefore has to run as-is for 3 years. 
The 2022-11-01-preview version needs to run as-is for 90 days.

**Comment by a-lazarlazic** [comment]
The breaking changes have been reviewed. Are there any reviews left @v-xuto?

**Comment by v-xuto** [comment]
@a-lazarlazic Please contact the `ARM team` to review this PR, and resolve their comments until they add the `ARMSignedOff` label.

**Review by ericshape — APPROVED** [review]

**Comment by a-lazarlazic** [comment]
hey @visingla-ms are you from ARM team? if so, could you please review this PR?

**Comment by mentat9** [comment]
>             "name": "ReplicationModeType",

This doesn't seem like a useful rename. How is ReplicationModeType different from ReplicationMode in any way that isn't confusing? This is just a suggestion, not a blocker.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/DistributedAvailabilityGroups.json:390 in c1cd761. [](commit_id = c1cd761d4105b54fa095ec983c5b37a588daccbc, deletion_comment = False)

**Comment by mentat9** [comment]
>         "replicaState": {

If this has a fixed set of values it should be modeled as a string enum.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/DistributedAvailabilityGroups.json:433 in c1cd761. [](commit_id = c1cd761d4105b54fa095ec983c5b37a588daccbc, deletion_comment = False)

**Comment by a-lazarlazic** [comment]
Hey @mentat9, thanks for reviewing!

I've changed the ReplicationMode -> ReplicationModeType just for it to be consistent with the type name. Names for all other properties are consistent with their type names.

Regarding the "replicaState", it indeed has a finite number of possible values. However, that number is pretty large (>30) and more states will be added as features evolve. Having that in mind, it would be hard to keep the enum up to date and consistent all the time. Also, this property is used by our tool (SSMS, which is calling this API) from where we want to get the up-to-date information and adding the enum would only slow down new features' development time. This shouldn't impact customers as this property isn't of interest to them.

Let me know if you still have any concerns.

**Comment by a-lazarlazic** [comment]
Hey @v-xuto, we got the signoff from ARM folks, are there any other reviews left?

**Comment by v-xuto** [comment]
@qiaozha Please help review JS breaking change.
@raych1 Please help review Go breaking change. 
@msyyc Please help review Python breaking change.

**Comment by v-xuto** [comment]
> Hey @v-xuto, we got the signoff from ARM folks, are there any other reviews left?

This PR currently needs to review sdk breaking change, and I have pinged them.

**Comment by v-xuto** [comment]
@qiaozha Please help review JS breaking change.
@raych1 Please help review Go breaking change.

**Review by v-xuto — APPROVED** [review]

**Pull request merged**
