### PR TITLE
Adding patch API for Configurations

### PR DESCRIPTION
**Pull request by vrdmr**
Adding spec for the new Patch operation for Automation/DscConfigurations.

-----
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by vrdmr** [comment]
Ping - @sarangan12, @fearthecowboy Could you please review this PR

**Comment by sarangan12** [comment]
1. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/355232262
2. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/355232261

Please take a look at the above errors and fix them for approval.

**Comment by sarangan12** [comment]
@vrdmr I wanted to check in if you need any help in resolving the issues. Please let me know

**Comment by vrdmr** [comment]
Hi @sarangan12 - I have other PRs out to fix the same issues - #2690, #2687 and this is one in the series of PRs to get our Linting and Model Validation issues down to 0.

**Comment by vrdmr** [comment]
For the [model issue](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/355232262), I add the example.

**Comment by vrdmr** [comment]
@sarangan12 I fixed the model validation issue. The issue was with the spec I wrote. We dont have a 201 return code, but it was added. I fixed it.

**Comment by vrdmr** [comment]
@sarangan12 Could you please take a look at this PR.

**Review by sarangan12 — APPROVED** [review]

**Comment by vrdmr** [comment]
Thanks @sarangan12

**Pull request merged**
