### PR TITLE
Fixed ActionRule's polymorphism via discriminator

### PR DESCRIPTION
**Pull request by EranGon**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by EranGon** [comment]
Note to reviewers: This PR is a do-over of https://github.com/Azure/azure-rest-api-specs/pull/10028 
The original change was overrun because of another change that was introduced at the same time

**Comment by yungezz** [comment]
hi @EranGon  does that mean this PR is fixing of Swagger: to fix previous merging conflict issue? Otherwise this is a breaking change to end users.

**Comment by EranGon** [comment]
@yungezz you are correct - this PR is fixing of merge problems that cause change #10028 to over overrun. This is not a breaking change as it's documenting the current state

**Review by yungezz — APPROVED** [review]

**Comment by EranGon** [comment]
@yungezz Thanks for approving! What's the process of merging this PR? Who's authorized to do it?

**Comment by yungezz** [comment]
> @yungezz Thanks for approving! What's the process of merging this PR? Who's authorized to do it?

hi @EranGon  for bug fixing, still need to understand customer impact. Is there existing usage on the wrong API version, does it work now?

**Comment by EranGon** [comment]
@yungezz as I've mentioned - this is a do-over of another PR that was already approved and merged, but was overrun by a later change. The original PR is here: https://github.com/Azure/azure-rest-api-specs/pull/10028 and it was approved by @akning-ms 

To copy the main comment: 
"I've reviewed the Breaking Change policy, wiki and form. I don't believe this commit is rightly considered a breaking change. Currently, there are missing fields in the responses due to a wrongly structured definition of inheritance by use of a discriminator. This PR fixes this: the only effect of this change is the returning in the response of expected fields which are currently missing. This change is aligning the behavior with the customer's current expectation."

**Pull request merged**
