### PR TITLE
Update keyvault.json

### PR DESCRIPTION
**Pull request by jlichwa**
Get Key - Version is not required parameter. Get Latest without version

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by zikalino — APPROVED** [review]

**Comment by jlichwa** [comment]
Can we merge it ?

**Comment by yungezz** [comment]
hi @zikalino, what's the status of this PR? thanks.

**Comment by akning-ms** [comment]
@zikalino @jlichwa  Can I know what is the status for this PR as it is pending a long time?  can we close it? @fengzhou-msft (Keyvault PR owner) for awareness

**Comment by jlichwa** [comment]
> @zikalino @jlichwa  Can I know what is the status for this PR as it is pending a long time?  can we close it? @fengzhou-msft (Keyvault PR owner) for awareness

My question is why we don't merge it. Or what I can do to merge it. I'm Key Vault PM and flag on key is invalid.

**Pull request merged**
