### PR TITLE
[Hub Generated] Review request for Microsoft.HealthcareApis to add version stable/2023-11-01

### PR DESCRIPTION
**Pull request by jnlycklama**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/jnlycklama-3-healthcareapis-Microsoft.HealthcareApis-2023-11-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
>           "description": "Fhir Service import configuration.",

Again you might want to check docs for consistent capitalization of Fhir/FHIR etc

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2023-11-01/healthcare-apis.json:3811 in 9577d77. [](commit_id = 9577d777190177c6e2fbfc09f8806bb7ba6454d6, deletion_comment = False)

**Review by TimLovellSmith — CHANGES_REQUESTED** [review]
:clock1:

**Comment by TimLovellSmith** [comment]
Removed ARMSignedOff because new commits came in. Adding ARMChangesRequested to reflect the open question on the encryption settings.

**Comment by jnlycklama** [comment]
> > ```
> > "Encryption": {
> > ```
> 
> I'd like to understand the differences between this definition of encryption settings, and others like
> 
> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/customermanagedkeys.json
> 
> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/resource-manager/Microsoft.Cache/stable/2023-11-01/redisenterprise.json
> 
> Do you not support using a managed identity to access the encryption key?
> 
> Or is the idea that which identity to use would be implicit?
> 
> Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2023-11-01/healthcare-apis.json:4081 in [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6). [](commit_id = [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6), deletion_comment = False)

Yes, we follow these guidelines for the schema - https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-contracts.md#customer-managed-key-encryption

But leave out `keyEncryptionKeyIdentity` for now. Our services only support a single identity attached to them, so the `identity` property on the DICOM & FHIR services is the identity that encryption will use. Declaring the `keyEncryptionKeyIdentity` as well would be setting the same identity twice and could cause confusing.

We also do not support cross-tenant CMK yet, so do not need support with the `federatedClientId` property.

**Comment by TimLovellSmith** [comment]
> > > ```
> > > "Encryption": {
> > > ```
> > 
> > 
> > I'd like to understand the differences between this definition of encryption settings, and others like
> > https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/customermanagedkeys.json
> > https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/resource-manager/Microsoft.Cache/stable/2023-11-01/redisenterprise.json
> > Do you not support using a managed identity to access the encryption key?
> > Or is the idea that which identity to use would be implicit?
> > Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2023-11-01/healthcare-apis.json:4081 in [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6). [](commit_id = [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6), deletion_comment = False)
> 
> Yes, we follow these guidelines for the schema - https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-contracts.md#customer-managed-key-encryption
> 
> But leave out `keyEncryptionKeyIdentity` for now. Our services only support a single identity attached to them, so the `identity` property on the DICOM & FHIR services is the identity that encryption will use. Declaring the `keyEncryptionKeyIdentity` as well would be setting the same identity twice and could cause confusing.
> 
> We also do not support cross-tenant CMK yet, so do not need support with the `federatedClientId` property.

I think at a minimum its probably a good idea to add the 'keyEncryptionKeyIdentity' property as supported, with all possible enum values, so that you can show callers using this API version the type of identity set with future api versions that support more identity kinds. Even if you don't actually support setting it to anything but the default, or setting the other identity kinds for now.

**Comment by jnlycklama** [comment]
> > > > ```
> > > > "Encryption": {
> > > > ```
> > > 
> > > 
> > > I'd like to understand the differences between this definition of encryption settings, and others like
> > > https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/customermanagedkeys.json
> > > https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/resource-manager/Microsoft.Cache/stable/2023-11-01/redisenterprise.json
> > > Do you not support using a managed identity to access the encryption key?
> > > Or is the idea that which identity to use would be implicit?
> > > Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2023-11-01/healthcare-apis.json:4081 in [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6). [](commit_id = [9577d77](https://github.com/Azure/azure-rest-api-specs/commit/9577d777190177c6e2fbfc09f8806bb7ba6454d6), deletion_comment = False)
> > 
> > 
> > Yes, we follow these guidelines for the schema - https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-contracts.md#customer-managed-key-encryption
> > But leave out `keyEncryptionKeyIdentity` for now. Our services only support a single identity attached to them, so the `identity` property on the DICOM & FHIR services is the identity that encryption will use. Declaring the `keyEncryptionKeyIdentity` as well would be setting the same identity twice and could cause confusing.
> > We also do not support cross-tenant CMK yet, so do not need support with the `federatedClientId` property.
> 
> I think at a minimum its probably a good idea to add the 'keyEncryptionKeyIdentity' property as supported, with all possible enum values, so that you can show callers using this API version the type of identity set with future api versions that support more identity kinds. Even if you don't actually support setting it to anything but the default, or setting the other identity kinds for now.

Wondering if this is a hard requirement or a suggestion?
 
We unfortunately were not able to get a review out sooner because we had a previous API version, 2023-09-06, that didn't get its swagger checked in until last week, and was unable to get anyone to review a draft / previous PRs which did not branch off of main. Now we are at a point where adding keyEncryptionKeyIdentity for 2023-11-01 would be very difficult, especially given the holiday freeze. And supporting multiple identities is not something in the plan to support for either service, so its a hard sell for something we may or may not do in a couple of years

**Review by TimLovellSmith — APPROVED** [review]
Approving for now for ARM, with the noted warning about future-proofness.

**Pull request merged**
