### PR TITLE
Added `enableRbacAuthorization` property to Key Vault management plane

### PR DESCRIPTION
**Pull request by msfcolombo**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@msfcolombo

Please address whether this is breaking change.

Also you might want to check whether enum would be better.

**Comment by msfcolombo** [comment]
@weidongxu-microsoft

Thanks for quick reply.

This is not a breaking change. Old clients doesn't have to specify the new property and the vault will be created as before. Old clients may also perform get-modify-patch without risk of overwriting data from new clients (if the old client removes the property, the service will not modify existing value).

We have considered enum, but this will be displayed as a checkbox in the Portal and there is no plan to support more values than yes/no. Hence a bool was considered more consistent.

I have amended with improved descriptions matching the PUT and PATCH semantics.

**Comment by msfcolombo** [comment]
>
> This is not master branch? What kind of review do you need? Do you need ARM review?


This branch was suggested by @heaths. This is intended to be included in the following PR: https://github.com/Azure/azure-rest-api-specs/pull/8301

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by heaths** [comment]
Yes, this is going into a feature branch for a final review of complete features (for preview). This is a common practice throughout Microsoft (and most GitHub projects) that OpenAPI Hub doesn't yet support.

**Pull request merged**
