### PR TITLE
[Hub Generated] Review request for Microsoft.RedHatOpenShift to add version stable/2020-04-30

### PR DESCRIPTION
**Pull request by mjudeikis**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/mjudeikis/azure-rest-api-specs/dev-redhatopenshift-Microsoft.RedHatOpenShift-2020-04-30...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by erich-wang — APPROVED** [review]

**Review by erich-wang — COMMENTED** [review]
@mjudeikis , is there any sdk released for this version of swagger spec?

**Comment by mjudeikis** [comment]
@erich-wang there is one already. How to we bump SDK version?

**Comment by mjudeikis** [comment]
@erich-wang ping, any updates on this?

**Comment by erich-wang** [comment]
@mjudeikis , adding enum values is considered as breaking change for swagger spec, please see
 https://github.com/Azure/openapi-diff/blob/master/docs/rules/1020.md

I'm waiting for arm review team feedback for this change.

**Comment by mjudeikis** [comment]
@erich-wang any way this can be waved this time? Arguments being that we are not GA and we going live only this weekend. So this is used currently only on few publicPreview clients.

**Comment by ravbhatnagar** [comment]
@mjudeikis - the api-version does not indicate its preview as it does not have a -preview suffix. can you please confirm?
modelAsString:true can be set to allow adding new values to the enum without breaking change for SDK. @erich-wang can confirm.

**Comment by mjudeikis** [comment]
@ravastra this is right, it does not indicate as we were preparing for GA with this one.
regards modelAsString, would this not cause more breaking change in the current behaviour?

**Comment by mjudeikis** [comment]
will be adding this to the next api version.

**Pull request closed without merging**
