### PR TITLE
ADT: refix .NET output path

### PR DESCRIPTION
**Pull request by drwill-ms**
I had the wrong path in my [last PR](https://github.com/Azure/azure-rest-api-specs/pull/12148). After testing (I learned how to test from my fork branch), I realized it should be the new value.

### CODE REVIEW

**Comment by drwill-ms** [comment]
I accidentally deleted my remote branch.

**Comment by drwill-ms** [comment]
I don't know why the python gate is failing. My commit does not change anything that should affect python (swagger or python-specific files). I've tried rerunning it several times, but it still fails.

**Review by leniatgh — APPROVED** [review]
The python error is same with previous PR. It's ok, and can be ignored.

**Pull request merged**
