### PR TITLE
enabling swagger to sdk for node sdk master branch

### PR DESCRIPTION
**Pull request by amarzavery**
The corresponding PR that enables this in master branch of node sdk https://github.com/Azure/azure-sdk-for-node/pull/1710

### CODE REVIEW

**Comment by amarzavery** [comment]
@lmazuel @devigned - Please review this.

**Comment by lmazuel** [comment]
I don't think you want the "-b master" parameter. Unless you want to directly push the generated commits inside "master"?
And I didn't test this case, I assumed that we always want to create a new branch, not pushing directly into master.

**Comment by devigned** [comment]
@lmazuel we may want to fail if someone specifies master :)

**Comment by amarzavery** [comment]
@lmazuel - I misunderstood the meaning for -b. After reading the help for -b I got the impression that it states "the name of destination branch, you want the changes to get merged into". Hence, I provided it.
I will remove -b switch.

**Comment by lmazuel** [comment]
Please consider https://github.com/Azure/azure-rest-api-specs/pull/249 and rebase before merging this one

**Comment by devigned** [comment]
@amarzavery please rebase

**Comment by amarzavery** [comment]
sure

**Comment by amarzavery** [comment]
@lmazuel - Can you take a look, why the PR is failing? https://travis-ci.org/Azure/azure-rest-api-specs/jobs/124613714#L237

**Pull request merged**
