### PR TITLE
Adding the structure of urlConfiguration in rewriteRuleActionSet

### PR DESCRIPTION
**Pull request by abjai**
These changes have already been approved in issue https://github.com/Azure/azure-rest-api-specs/pull/7275/ and merged as a part of September milestone. However, because of some timeline issue, we reverted these changes in September milestone. This is targetted to be released as a part of December milestone.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by anton-evseev — APPROVED** [review]
LGTM but could you please also run `prettier` to fix JSON formatting?
https://dev.azure.com/azure-sdk/public/_build/results?buildId=203587&view=logs&jobId=b56e9678-4dad-5642-289c-5530cc4dad11

**Comment by abjai** [comment]
> LGTM but could you please also run `prettier` to fix JSON formatting?
> https://dev.azure.com/azure-sdk/public/_build/results?buildId=203587&view=logs&jobId=b56e9678-4dad-5642-289c-5530cc4dad11

**Comment by abjai** [comment]
> LGTM but could you please also run `prettier` to fix JSON formatting?
> https://dev.azure.com/azure-sdk/public/_build/results?buildId=203587&view=logs&jobId=b56e9678-4dad-5642-289c-5530cc4dad11

@number213 : I am not sure why it is failing. I followed https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md to run prettier-fix for changed files and it worked fine.

Sample output:
D:\Aznet\swagger\dec19\azure-rest-api-specs>npm run prettier -- --write "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json

> azure-rest-api-specs-tests@0.1.0 prettier D:\Aznet\swagger\dec19\azure-rest-api-specs
> prettier "--write" "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json"

specification\network\resource-manager\Microsoft.Network\stable\2019-11-01\applicationGateway.json 211ms

**Comment by abjai** [comment]
@MikhailTryakhov These changes have already been approved in issue #7275 https://github.com/Azure/azure-rest-api-specs/pull/7275 and merged as a part of September milestone. Can you please approve?

**Review by v-shhatt — COMMENTED** [review]
I observed prettier check is failing..

**Comment by abjai** [comment]
> I observed prettier check is failing..
@v-shhatt v-shhatt
 I am not sure why it is failing. I followed https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md to run prettier-fix for changed files and it worked fine.

Sample output:
D:\Aznet\swagger\dec19\azure-rest-api-specs>npm run prettier -- --write "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json

azure-rest-api-specs-tests@0.1.0 prettier D:\Aznet\swagger\dec19\azure-rest-api-specs
prettier "--write" "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json"

specification\network\resource-manager\Microsoft.Network\stable\2019-11-01\applicationGateway.json 211ms

**Comment by abjai** [comment]
@number213 @v-shhatt @MikhailTryakhov Prettier is failing in this build however it is passing locally on my system.

Sample output:
D:\Aznet\swagger\dec19\azure-rest-api-specs>npm run prettier -- --write "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json

azure-rest-api-specs-tests@0.1.0 prettier D:\Aznet\swagger\dec19\azure-rest-api-specs
prettier "--write" "specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json"

specification\network\resource-manager\Microsoft.Network\stable\2019-11-01\applicationGateway.json 211ms

**Review by lirenhe — APPROVED** [review]

**Comment by NullMDR** [comment]
@abjai Please commit and push changes after running prettier

**Comment by abjai** [comment]
> @abjai Please commit and push changes after running prettier

@NullMDR : Please review the PR

**Pull request merged**
