### PR TITLE
Add version to Resource Plan

### PR DESCRIPTION
**Pull request by vivsriaus**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by vivsriaus** [comment]
@gandhiniraj @ravbhatnagar please review

**Comment by vivsriaus** [comment]
@jhendrixMSFT Can you please look into the travis CI build failure?

**Comment by jhendrixMSFT** [comment]
@lmazuel can you please take a look at the python failure?
@vivsriaus please note that there are conflicts that need to be resolved.

**Comment by lmazuel** [comment]
@fearthecowboy @olydis CI is failing because this command is failing:
```shell
Command '['/usr/local/bin/autorest', 'specification/resources/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--output-folder=/tmp/tmp28dxkadp']' returned non-zero exit status 1.
ERROR:swaggertosdk.autorest_tools:AutoRest code generation utility [version: 2.0.4225]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
[Exception] No input files provided.
```
I saw random failing of first command with this "No input files provided", when I re-start again exactly the same command it works. Any idea?

**Comment by fearthecowboy** [comment]
Can we get the conflict fixed (@marstr ? ) so I can look into this?

**Comment by vivsriaus** [comment]
@fearthecowboy conflict resolved

**Comment by fearthecowboy** [comment]
@lmazuel  -- are you sure that command works when you re-run it? I tried it, and without any default input files, it doesn't go anywhere ( regardless of `--perform-load=false`  )

**Comment by fearthecowboy** [comment]
@lmazuel  -- from what I can see, you may have to trick it when there are no default files when using `--perform-load=false` -- for the moment, you can add `--input-file=foo` or something. Since the files don't get actually loaded it will at least compose the configuration.

Filing a bug.

**Comment by lmazuel** [comment]
@fearthecowboy I was not clear:
- I see sometimes after an update Autorest saying "no input file", but the next call works. I don't know, and I was pragmatic and just continue to use it
- I didn't try on this specific PR content
I will try your hack and see if it's better

**Comment by fearthecowboy** [comment]
@lmazuel Hmmm. 'after an update` -- but always specifying `--perform-load=false` ? 

if you're getting a general "sometimes after an update, it doesn't do squat" problem, then that's a whole different issue.  

:worried:

**Comment by lmazuel** [comment]
@fearthecowboy If I find a way to reproduce this other issue, I'll tell you right away

About the problem here, you're right that with a --input-file=foo it works, I will add that and re-deploy the container.

**Comment by lmazuel** [comment]
@fearthecowboy So, the first problem is fixed. Now we hit a (related) but not same issue:
```shell
ERROR:swaggertosdk.autorest_tools:Command '['/usr/local/bin/autorest', '/git-restapi/specification/resources/resource-manager/readme.md', '--multiapi', '--python', '--python-mode=update', '--python-sdks-folder=/tmp/tmpillgyxui/sdk', '--use=@microsoft.azure/autorest.python@preview', '--version=preview']' returned non-zero exit status 1.
ERROR:swaggertosdk.autorest_tools:AutoRest code generation utility [version: 2.0.4225]
(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
   Installing AutoRest extension '@microsoft.azure/autorest.python' (preview)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
[Exception] No input files provided.
```

If you look inside the Readme, the `multiapi` tag contains a `batch` section. So I think Autorest complains for a bad reason :(

**Comment by fearthecowboy** [comment]
@lmazuel  arg... `batch` is a bit of an odd duck too; the same thing probably applies. 

I'll see what we can do to make sure that this doesn't fail like that.

**Comment by vivsriaus** [comment]
@fearthecowboy Any updates on this yet?

**Comment by fearthecowboy** [comment]
@vivsriaus I'm in the middle of reviewing another spec, as soon as I'm done that I'll see if I can't fix this.

**Comment by fearthecowboy** [comment]
@vivsriaus @lmazuel  I have a fix in CI now; it skips the `input-files` check if you specify `--perform-load=false`.

**Comment by lmazuel** [comment]
@fearthecowboy and for batch?

**Comment by lmazuel** [comment]
@vivsriaus Thanks to @fearthecowboy, we found the typo in the Readme that was causing the issue... I pushed an update in the PR, hopefully it gets fixed.

**Comment by lmazuel** [comment]
@jhendrixMSFT Travis is failing because generating the whole Resources package in Python takes more than 10 minutes :(
I think you can merge the PR, this is not a problem for me.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
