### PR TITLE
Added SoftDeleteRetentionInDays,  CustomizedRecoverable and recoverableDays

### PR DESCRIPTION
**Pull request by gdlxm**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by gdlxm** [comment]
Close and reopen it for test re-run.

**Comment by gdlxm** [comment]
Reopen it

**Comment by schaabs** [comment]
@heaths could you take a look at this and see how it fits into your swagger refactoring?

**Comment by heaths** [comment]
I think it would be best to rebase this onto my PR, though we could work it in reverse. Firste, I've already done all the split work. Second, this is on the wrong work "branch". 7.0 already GA'd, and I started a preview/7.1 work branch where this should go. Right now, though, the PR is on our private fork for reasons. I can fix it up and squash it onto this public fork if that's easier, but it would be nice if it would be reviewed prior.

**Pull request closed without merging**
