### PR TITLE
Add new OsType parameters for Microsoft.Web/availablestacks

### PR DESCRIPTION
**Pull request by balag0**

### CODE REVIEW

**Review by marstr — APPROVED** [review]
I get nervous about extending enum values inside of API Versions for the following reasons:
1. API Versions expose a mechanism for reasoning about availability between regions.
1. While this type already looks to be modeled as a string, applications will need to be retooled to expose/reason about the new options. Without changing API Version, it is hard to build tooling to identify places where the enum list has been updated.

That said, I don't think those grounds are enough to block this or any other individual PR. However, I want to make sure that this conversation is included when considering what changes warrant waiting for an API Version boundary. Better yet, trying to change the culture to one where deploying new API Versions is a lighter-weight, more common operation.

**Comment by bala16** [comment]
The response body will include the type based on the ostype query parameter.
Ex:
Microsoft.Web/availableStacks?osTypeSelected=Linux
Microsoft.Web/availableStacks?osTypeSelected=Windows

if the query parameter is skipped it is implicitly assumed to be Windows and only Windows stacks will be returned.

**Comment by naveedaz** [comment]
Are there any more concerns? Can we merge this PR?

**Comment by marstr** [comment]
Talked offline with @naveedaz, merging now.

**Pull request merged**
