### PR TITLE
Release sql microsoft.sql 2023 02 01 preview

### PR DESCRIPTION
**Pull request by jeremyfrosti**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [public repo review queue], [private repo review queue]  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue]  

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[public repo review queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AWaitForARMFeedback+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[private repo review queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AWaitForARMFeedback+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by scbedd** [comment]
I will approve and unblock this for a couple contributing reasons.

1. The [previous PR](https://github.com/Azure/azure-rest-api-specs/pull/23802) was approved and released with 320 errors. This PR actually **narrows** those errors from 320 to 302!
2. All errors in this PR are this `INVALID_TYPE` error. As far as I can tell, I believe this is an `oav` analysis issue. Specifically, I have filed a new issue against [Azure/oav](https://github.com/Azure/oav/issues/992) to cover a resolution on analysis side.

Given the above situation, I'm going to approve failing `ModelValidation` check here.

**Review by scbedd — APPROVED** [review]

**Review by ericshape — APPROVED** [review]

**Comment by jeremyfrosti** [comment]
We are seeking LintDiff approval for this PR, there are two LintDiff issues listed that are cPutRequestResponseSchemeArm

PutRequestResponseSchemeArm for Databases.json, this was approved during the commit to the release branch as it was confirmed to be a false alarm: https://github.com/Azure/azure-rest-api-specs/pull/24339

RequiredPropertiesMissingInResourceModel for IPv6FirewallRules, this has existed in that state before this PR, the file is new as it was copied from the previous version, but checking the history, there were no commits on it other than the OpenAPI initial commits: https://github.com/Azure/azure-rest-api-specs/commits/48f33ad8fdc31b0d4c91bf4972a2b3245315d33a/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/IPv6FirewallRules.json

**Comment by TimLovellSmith** [comment]
Understood its an existing issue but... what's the blocker to fixing the linter errors about 'missing properties'? Fixing it, is effectively just adding new properties in a new API version, and that is normally an OK change to do right?

**Comment by jeremyfrosti** [comment]
@TimLovellSmith It would not be adding properties in this case, the three properties are present, but 'name' is not marked as readonly. The error in question is on:
https://github.com/Azure/azure-rest-api-specs/blob/643b6da5f557cf08c8a91ee77335d941cdbed5e4/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/IPv6FirewallRules.json#L215

Which references 'ProxyResourceWithWritableName', and that references 'ResourceWithWritableName' here:
https://github.com/Azure/azure-rest-api-specs/blob/643b6da5f557cf08c8a91ee77335d941cdbed5e4/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/IPv6FirewallRules.json#L274

This would be a breaking change and not something that we want to do.

**Comment by TimLovellSmith** [comment]
@jeremyfrosti Are names *actually* writable? Or does trying to rename them in the request get ignored or turn into 400 Bad Request?

**Comment by jeremyfrosti** [comment]
@TimLovellSmith The 'name' being writable has been used in previous versions, although the reliance on it has been removed in IPv6FirewallRules.json after version 2021-11-01-preview. We still can not simply update the ResourceWithWritableName to mark the property as readonly though, this same model is used in other files such as FirewallRules.json, and making it different in IPv6FirewallRules would cause us to have two different definitions with the same name, and we can't do that. It is also used for internal functions that rely on the name being writable.

Theoretically, we can change ProxyResourceWithWritableName to ProxyResource here:
https://github.com/Azure/azure-rest-api-specs/blob/643b6da5f557cf08c8a91ee77335d941cdbed5e4/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/IPv6FirewallRules.json#L220

But that may be a breaking change for downstream client generation. If its not, the change may be possible.

Again though, does this **need** to be done for us to release our next version? This is not new to this version, and that api has had no changes in this version. It has existed for many versions before, so why are we blocking this one? This will cause a delay to our release, and that will cause us to miss deadlines on features that have been promised to our customers. If this must be blocked, we need to schedule a meeting to discuss this and understand why this is worth blocking our release and how we can expedite the change ASAP.

**Comment by TimLovellSmith** [comment]
@jeremyfrosti you're right it shouldn't really need to block feature development, I'm just trying to understand why we have these linter errors, and whether its the kind of API quality thing we can/should fix. In particular I'm puzzled about whether you are deliberately allowing the behavior today, maybe you could explain more about what 'reliance' means, while I sign thiss of...

**Comment by TimLovellSmith** [comment]
Looks like you still need to suppress the LintDiff errors if you're not fixing them before merge.
https://github.com/Azure/azure-rest-api-specs/pull/25293/checks?check_run_id=15958574056
https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md#lintdiff-validation

**Comment by kazrael2119** [comment]
this js sdk breaking is caused by this pr

**Comment by ms-henglu** [comment]
> I will approve and unblock this for a couple contributing reasons.
> 
> 1. The [previous PR](https://github.com/Azure/azure-rest-api-specs/pull/23802) was approved and released with 320 errors. This PR actually **narrows** those errors from 320 to 302!
> 2. All errors in this PR are this `INVALID_TYPE` error. As far as I can tell, I believe this is an `oav` analysis issue. Specifically, I have filed a new issue against [Azure/oav](https://github.com/Azure/oav/issues/992) to cover a resolution on analysis side.
> 
> Given the above situation, I'm going to approve failing `ModelValidation` check here.

According to this comment, I'll help adding the `Approved-ModelValidation` label.

**Comment by ms-henglu** [comment]
The one new lint diff error detected actually exists in previous version.

**Review by ms-henglu — APPROVED** [review]

**Pull request merged**
