### PR TITLE
New Api version 2020-06-15- fixing certificate put/get issues with ARM 

### PR DESCRIPTION
**Pull request by ghost**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ruowan** [comment]
Hi, pls fix CI failure.

**Comment by deepak-muniappan** [comment]
Hi,
I am getting this error on the check for SDK NET
'##[error]2020-07-27T22:39:50.118Z: Failed to run SDK Automation: Error: SDK Automation failed, {} '

Can you help me in this regard ?

Thanks
Deepak

**Comment by ravbhatnagar** [comment]
signing off from arm side.

**Review by ruowan — APPROVED** [review]

**Comment by ruowan** [comment]
You could ignore the dot net  SDK generates failure.  It's build error and no effect for downstream. LGTM, ready to merge?

**Comment by deepak-muniappan** [comment]
Hi,
My teammate made a change as a part of same api-version. It is now pushed and all the checks are passing except dot net SDK.

I am ready to merge. Please review and merge.
Thanks
Deepak

**Review by ruowan — APPROVED** [review]

**Pull request merged**
