### PR TITLE
Network november release

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [X] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [X] SDK of .NET (need service team to ensure code readiness)
      - [X] SDK of Python
      - [X] SDK of Java
      - [X] SDK of Js
      - [X] SDK of Go
      - [X] PowerShell
      - [X] CLI
      - [x] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
Hey guys, 
I had to revert network manager updates of preview version to prevent confusions from our side. Please let me know what should we mark (like what should be the latest api version???) to make it work?
better to discuss it before merge to master something :)

**Comment by msyyc** [comment]
@MikhailTryakhov There are breaking change caused by '2020-08-01' folder. Is it expected?
image

**Comment by MikhailTryakhov** [comment]
@msyyc this PR was approved by Swagger team earlier, so it's up to you to solve, is it applicable or not?
https://github.com/Azure/azure-rest-api-specs/commit/b143498cb4570023615906fdc7d8330e6d8acfe1

**Comment by MikhailTryakhov** [comment]
@msyyc https://github.com/Azure/azure-rest-api-specs/pull/13088 - @lirenhe  approved this breaking changes

**Comment by MikhailTryakhov** [comment]
Can you please help with https://github.com/Azure/azure-rest-api-specs/pull/13224/files#diff-06b33c899bdfd2b8060eff3b065641a8f1b0ac7a8188d896d9cc2965ddfb22fe
Which api version need to be used there? Was really surprised by this preview version in stable folder (was in master and caused a conflict)

**Comment by akshatkale** [comment]
> @msyyc #13088 - @lirenhe approved this breaking changes

@MikhailTryakhov  This breaking change was originally introduced in https://github.com/Azure/azure-rest-api-specs/pull/12826. I reverted this change by mistake in one of my merge so I reverted that bad commit in https://github.com/Azure/azure-rest-api-specs/pull/13088.

**Comment by MikhailTryakhov** [comment]
Looks like that PR #12826 wasn't reverted in #13088 and now we have a conflict between 08-01 (broken) and 11-01 (looks like OK) api versions

**Comment by MikhailTryakhov** [comment]
Synced up offline, so looks like the problems we have right now are from this PR: https://github.com/Azure/azure-rest-api-specs/pull/12826 
@litchiyangMSFT  your changes are breaking for already published version 08-01 and they are different from the data in 11-01

Please help to figure out ASAP
1) are these changes really needed?
2) were they published in PowerShell? if you did - we can't apply this breaking changes...
3) please sync up these changes ASAP in 11-01 and 08-01 and merge them to ```network-november-release``` branch and in ```mitryakh/network-november-release``` branch ASAP

**Comment by msyyc** [comment]
@MikhailTryakhov  The code in '2020-11-01' is same with '2020-08-01'of main branch. So it is better to keep same. 

image

**Comment by MikhailTryakhov** [comment]
@msyyc no, that's a hotfix needed (and already approved by @lirenhe) for 2020-11-01 as well. Waiting for hotfix from @litchiyangMSFT by noon (PST)

**Comment by MikhailTryakhov** [comment]
@msyyc  contacted @yanfa317  and figured out what would be with api versions, fixed it locally.
So waiting for @litchiyangMSFT fix and we'll be ready to merge

**Comment by MikhailTryakhov** [comment]
@msyyc we are done, can you please review?

**Comment by msyyc** [comment]
@ArcturusZhang what's your opinion about the breaking change caused by name-change？

**Review by jsntcy — APPROVED** [review]

**Review by lirenhe — APPROVED** [review]

**Review by msyyc — APPROVED** [review]

**Pull request merged**
