### PR TITLE
Fix the error in Api v3.1-preview.1

### PR DESCRIPTION
**Pull request by HanLiMS**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by deyaaeldeen — APPROVED** [review]
Thanks!

**Comment by mssfang** [comment]
@jhendrixMSFT can you take a look at this PR. It failed at breaking change step.

**Comment by jhendrixMSFT** [comment]
That's expected as your change is breaking in nature.  Given that this is in preview it should be ok.

Can you please fix the prettier failure?  Might simply be the missing new-line char at the end of the example file you updated.

**Comment by mssfang** [comment]
Thank you, Joel. 
@HanLiMS can you follow up this?

**Comment by HanLiMS** [comment]
> That's expected as your change is breaking in nature. Given that this is in preview it should be ok.
> 
> Can you please fix the prettier failure? Might simply be the missing new-line char at the end of the example file you updated.

@jhendrixMSFT  Thanks a lot for your review. I just updated this PR. Could you approve and merge this PR if everything looks good to you?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
