### PR TITLE
Add the missing `x-ms-skip-url-encoding` for some swagger specs

### PR DESCRIPTION
**Pull request by magodo**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [x] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by raych1** [comment]
Go SDK automation failed by below readme issue. Can you fix it or ask admin to force merge this PR?
```
06:52:21.301 cmderr E 	[generator automation-v2] [ERROR] cannot get rp and namespaces from readme 'softwareplan/resource-manager/readme.md': cannot find any `track2` section

```

**Comment by magodo** [comment]
@raych1 As the issue flagged is not introduced by this PR, I'd prefer not complicate this PR to involve not intended fixes. Do you know who is the admin that can force merge this PR?

**Comment by raych1** [comment]
> @raych1 As the issue flagged is not introduced by this PR, I'd prefer not complicate this PR to involve not intended fixes. Do you know who is the admin that can force merge this PR?

+ repo admin: @weshaggard

**Comment by magodo** [comment]
@weshaggard That said, these failures are not derived from my change, but are something exists in long term (just not analyzed by the CI). E.g. the model validation has more than 100 failures, which I might have no context about how to fix them.

**Comment by weshaggard** [comment]
@magodo it is your team that owns this spec correct? Someone should have enough context to fix or property suppress these if they aren't real issues. At the end of the day we cannot be in a place where we need to override checks for your teams spec everytime so someone needs to address these.

**Comment by magodo** [comment]
@weshaggard

> it is your team that owns this spec correct?

No.. I'm no more than a regular contributor from open source community. I just spot issues and fix them.

**Comment by weshaggard** [comment]
@magodo thanks for the context generally the service teams are the ones that are updating their specs. Do you have more context on why you are making these updates? Looks like you are also updating a number of older api versions which could potentially cause issues. We will want to have someone from the owning teams to review these changes. @rkmanda any thoughts on this change and how we might want to get owning teams to review?

**Comment by magodo** [comment]
@weshaggard The background is that we have some internal tooling that will do something similar to the swagger live validation things, but not quite the same. During the processing, we identified these issues.

**Comment by magodo** [comment]
Kindly ping @weshaggard

**Comment by weshaggard** [comment]
@magodo I'm on the EngSys/Infra team and not part of the service teams so I'm not the person to review and decide whether or not to take these changes. @rkmanda might be able to assist but he is also just part of the ARM reviewer team and I suspect you may need to figure out the correct service teams to review and accept these changes or not.

**Comment by magodo** [comment]
@weshaggard You can find some latest versions of those specs have that missing tag added, which indicates they were leaked in the ARM review and this PR just fixes that up. IMO, there should be a linter to catch those issues at the first place. Shall we have someone in the ARM team to drive this and get it merged, or shall we just leave these kinds of errors around and not touching them at all?

**Comment by weshaggard** [comment]
As I mentioned I'm not the right person to make that decision. You will need to find someone on the service teams or the ARM team with enough context to understand what we should do in these cases.

**Comment by magodo** [comment]
@rkmanda Would you please shed some insight on this PR?

**Comment by magodo** [comment]
@rkmanda Would you please look at this PR as it has been hanging for 3 months and I'm about to leave it closed if no one from the swagger team gonna review it.

**Comment by magodo** [comment]
@rkmanda Would you please look at this PR as it has been hanging for 3 months and I'm about to leave it closed if no one from the swagger team gonna review it.

**Comment by rkmanda** [comment]
> @rkmanda Would you please look at this PR as it has been hanging for 3 months and I'm about to leave it closed if no one from the swagger team gonna review it.

The PR was signed off by ARM in October. The PR review workflow diagram calls out what you should have done to request a merge which clearly hasnt been followed. Please do the needful to request merge. The turnaround time for merges is 24 hours.

**Comment by rkmanda** [comment]
The go SDK check is also failing. So pl follow the documentation to get that to green or reach out to the owners to get an approval.

**Comment by rkmanda** [comment]
Do u have permission from these different RP owners to make this change on their behalf?

**Comment by magodo** [comment]
@rkmanda Thank you for your response. The background of my PR is that we have some internal tooling that will do something similar to the swagger live validation things, but not quite the same. During the processing, we identified these issues among different specs. You can find some latest versions of those specs have that missing tag added, which indicates they were leaked in the ARM review and this PR just fixes that up. IMO, there should be a linter to catch those issues at the first place.

As mentioned above, the CI failures flagged are not introduced by this PR, but just triggered by the it. I'd prefer not complicate this PR to involve not intended fixes.

WDYT?

**Comment by magodo** [comment]
@rkmanda

**Pull request closed without merging**
