### PR TITLE
Added devcontainer for spec writers

### PR DESCRIPTION
**Pull request by raych1**
The purpose is to provide a container including all the toolset for spec writers.

### CODE REVIEW

**Comment by raych1** [comment]
@allenjzhang @weshaggard , with this PR change, when user open this repo locally in vscode it would prompt user to re-open workspace in dev container. I can get the dev container launched successfully and run the generate sdk script `/workspaces/azure-rest-api-specs/eng/scripts/TypeSpec-Generate-Sdk.ps1 /workspaces/work-dir/azure-sdk-for-net`. 

Remember to update `.devcontainer.json` locally to mount your local SDK repo folder. See the comment part in `.devcontainer.json`.

**Comment by allenjzhang** [comment]
It boots up fine with no errors. Great work!

- really lengthy first boot up (included building) (20+ mins on my laptop). Subsequent start up is 30 secs. Need to make note in the documentation.
- as TypeSpec is not installed global, I need to update the documentation to prefix command with `npx`

**Review by allenjzhang — APPROVED** [review]

**Comment by raych1** [comment]
> * really lengthy first boot up (included building) (20+ mins on my laptop). Subsequent start up is 30 secs. Need to make note in the documentation for first time experience. To help improve those, could we prebuild and publish the image to reduce the build time?

Yes, it takes me a few mins for the first-time launch. Definitely, we could pre-build the image. Let's add to backlog when adding more tool set to this Dockerfile. @weshaggard , what do you think?

> * as TypeSpec is not installed global, I need to update the documentation to prefix command with `npx`

Thanks @allenjzhang , how about adding convenient usage of the `TypeSpec-Generate-Sdk.ps1` to the document so that user can run the script simply.

**Comment by weshaggard** [comment]
If it just the build time that is the issue then yes prebuilding and publishing I'm supportive of. However it might also be the size that is the issue. Either way we should continue to make improvements to this we get more folks using it.

Should we put TypeSpec in the image instead of requiring the npx calls? I would like to have as many of the tools we need already installed and on the path in the container to make this easier for users.

**Pull request merged**
