### PR TITLE
Group DPSCertificate->List with other operations

### PR DESCRIPTION
**Pull request by mikekinsman**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@mikekinsman it's an SDK breaking change. The API is stable, and, I assume, SDK is published. Could you introduce these changes in a new API version?

**Comment by sergey-shandar** [comment]
I'm closing this PR since there is no response to my questions. @mikekinsman feel free to either reopen it or create a new PR if you think you are ready to discuss this breaking changes.

**Comment by mikekinsman** [comment]
Hey @sergey-shandar  Sorry I missed this earlier.  I work on the APEX Documentation team, I'm not a swagger author, and don't work on a service team, and don't know how to make new api versions :)  This is related to how the content generated from swagger appears out on docs.microsoft.com/rest/api.   @BryanLa do you want to consider this issue closed?

**Comment by BryanLa** [comment]
Hi @mikekinsman - I wouldn't be the right person to make the call, but would you mind posing this back to Karan on the email thread he originated? That way all of the engineering folks could weigh in as well, in addition to Karan, as they would need to make the versioning decision.

**Pull request closed without merging**
