### PR TITLE
ServiceBus: added NetworkRuleSets list API

### PR DESCRIPTION
**Pull request by v-Ajnava**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [X] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by anthony-c-martin — CHANGES_REQUESTED** [review]

**Review by anthony-c-martin — APPROVED** [review]

**Comment by raych1** [comment]
@v-ajnava, I assume the parameter of `SqlFilter` should be a request parameter which cannot have a [readonly property] (https://github.com/Azure/azure-rest-api-specs/blob/87e06617e7103a97295b2fe25f4a47990371b397/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2017-04-01/servicebus.json#L4232). The value of a readonly property is managed exclusively by the owning authority (http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3) and cannot be supplied in request.

**Comment by erich-wang** [comment]
@v-Ajnava, could you fix the semantic error as @raych1 commented?

**Comment by erich-wang** [comment]
@v-Ajnava, could you fix the semantic error as @raych1 commented?

**Comment by v-Ajnava** [comment]
@erich-wang, sorry for delay. right now, we want user to restrict user input for  'compatibilityLevel' to 20, so is it okay to, add minimum and maximum to 20 ?  we have default set to 20. I will also discuss with team here.

**Comment by erich-wang** [comment]
@v-Ajnava , using minimun and maximum LGTM.

**Comment by v-Ajnava** [comment]
@erich-wang can you please review the changes. added minimum, maximum.

**Pull request merged**
