### PR TITLE
Service Fabric Managed Clusters - API version 2023-11-01-preview

### PR DESCRIPTION
**Pull request by a-santamaria**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by a-santamaria** [comment]
for LintDiff error with have a work item to fix it this semester https://msazure.visualstudio.com/One/_workitems/edit/24841215 . but its going to take some time because we generate the swagger from an internal repo that currently cant reference the common types.


❌LroErrorContent | Error response content of long running operations must follow the error schema provided in the common types v2 and above.Location: Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json#L633 |  
-- | -- | --
❌ LroErrorContent | Error response content of long running operations must follow the error schema provided in the common types v2 and above.Location: Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json#L690 |  
❌ LroErrorContent | Error response content of long running operations must follow the error schema provided in the common types v2 and above.Location: Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json#L757 |  
❌ LroErrorContent | Error response content of long running operations must follow the error schema provided in the common types v2 and above.Location: Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json#L824


Breaking Change(Cross-Version): Those are changes we already got approval in older versions. non are introduced in this new api

**Comment by rkmanda** [comment]
Please add a suppression for the lint diff errors and provide a link to the work item in the description of the suppression

**Comment by rkmanda** [comment]
>         }

generic properties are not allowed. 

---
Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in 9adf31d. [](commit_id = 9adf31d68810a7f7202ea2bee858b97961623611, deletion_comment = False)

**Comment by rkmanda** [comment]
>         }

same for all other places.

---
In reply to: [1772094825](https://github.com/Azure/azure-rest-api-specs/pull/26178#issuecomment-1772094825) [](http://example.com/codeflow?ancestors=1772094825)

---
Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in 732e562. [](commit_id = 732e562a9043295c7056f42e7db96ec6a81aef84, deletion_comment = False)

**Comment by rkmanda** [comment]
>         }

Pl explain why you cannot define a concrete type for the property

---
In reply to: [1772106615](https://github.com/Azure/azure-rest-api-specs/pull/26178#issuecomment-1772106615) [](http://example.com/codeflow?ancestors=1772106615,1772094825)

---
Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in 732e562. [](commit_id = 732e562a9043295c7056f42e7db96ec6a81aef84, deletion_comment = False)

**Comment by a-santamaria** [comment]
> > ```
> >     }
> > ```
> 
> generic properties are not allowed.
> 
> Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611). [](commit_id = [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611), deletion_comment = False)

@rkmanda thanks for the review. We decided to go with generic object for RuntimeServiceTypeHealthPolicyMap because for historical reasons we already defined ServiceTypeHealthPolicyMap used on the upgradePolicy on ApplicationResourceProperties that way. So we created the same definition for RuntimeServiceTypeHealthPolicyMap for the app actions, but keeping them as separate definitions in case in the future the runtime definitions change, we don't want them to be tied together.

**Comment by rkmanda** [comment]
> > > ```
> > >     }
> > > ```
> > 
> > 
> > generic properties are not allowed.
> > Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611). [](commit_id = [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611), deletion_comment = False)
> 
> @rkmanda thanks for the review. We decided to go with generic object for RuntimeServiceTypeHealthPolicyMap because for historical reasons we already defined ServiceTypeHealthPolicyMap used on the upgradePolicy on ApplicationResourceProperties that way. So we created the same definition for RuntimeServiceTypeHealthPolicyMap for the app actions, but keeping them as separate definitions in case in the future the runtime definitions change, we don't want them to be tied together.
> 
> as you can see in the example https://github.com/Azure/azure-rest-api-specs/pull/26178/files#diff-bddcb320f60e156e403b253d2249de57ec774d539c6020fdb885330df6ae414a the property will look like this:
> 
> ```json
> "serviceTypeHealthPolicyMap": {
>           "VotingWeb": {
>             "maxPercentUnhealthyPartitionsPerService": 13,
>             "maxPercentUnhealthyReplicasPerPartition": 14,
>             "maxPercentUnhealthyServices": 15
>           }
>         }
> ```
> 
> That is how the service fabric runtime defines it and we couldn't model this another way than with generic type in the swagger.

Will there be any validations done on the keys of each of these dictionaries? Or will the dictionary be a pass through to your backend services? Service owned properties MUST be modeled as concrete types. If you would like to stick with your approach, pl book an ARM modeling office hours slot to discuss with the current on-call engineer. https://armwiki.azurewebsites.net/introduction/office_hours.html

**Comment by a-santamaria** [comment]
> > > > ```
> > > >     }
> > > > ```
> > > 
> > > 
> > > generic properties are not allowed.
> > > Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611). [](commit_id = [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611), deletion_comment = False)
> > 
> > 
> > @rkmanda thanks for the review. We decided to go with generic object for RuntimeServiceTypeHealthPolicyMap because for historical reasons we already defined ServiceTypeHealthPolicyMap used on the upgradePolicy on ApplicationResourceProperties that way. So we created the same definition for RuntimeServiceTypeHealthPolicyMap for the app actions, but keeping them as separate definitions in case in the future the runtime definitions change, we don't want them to be tied together.
> > as you can see in the example https://github.com/Azure/azure-rest-api-specs/pull/26178/files#diff-bddcb320f60e156e403b253d2249de57ec774d539c6020fdb885330df6ae414a the property will look like this:
> > ```json
> > "serviceTypeHealthPolicyMap": {
> >           "VotingWeb": {
> >             "maxPercentUnhealthyPartitionsPerService": 13,
> >             "maxPercentUnhealthyReplicasPerPartition": 14,
> >             "maxPercentUnhealthyServices": 15
> >           }
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That is how the service fabric runtime defines it and we couldn't model this another way than with generic type in the swagger.
> 
> Will there be any validations done on the keys of each of these dictionaries? Or will the dictionary be a pass through to your backend services? Service owned properties MUST be modeled as concrete types. If you would like to stick with your approach, pl book an ARM modeling office hours slot to discuss with the current on-call engineer. https://armwiki.azurewebsites.net/introduction/office_hours.html

ok we removed the action for now and will add it in the next api with concrete types

**Comment by rkmanda** [comment]
> > > > > ```
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > generic properties are not allowed.
> > > > Refers to: specification/servicefabricmanagedclusters/resource-manager/Microsoft.ServiceFabric/preview/2023-11-01-preview/managedapplication.json:1433 in [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611). [](commit_id = [9adf31d](https://github.com/Azure/azure-rest-api-specs/commit/9adf31d68810a7f7202ea2bee858b97961623611), deletion_comment = False)
> > > 
> > > 
> > > @rkmanda thanks for the review. We decided to go with generic object for RuntimeServiceTypeHealthPolicyMap because for historical reasons we already defined ServiceTypeHealthPolicyMap used on the upgradePolicy on ApplicationResourceProperties that way. So we created the same definition for RuntimeServiceTypeHealthPolicyMap for the app actions, but keeping them as separate definitions in case in the future the runtime definitions change, we don't want them to be tied together.
> > > as you can see in the example https://github.com/Azure/azure-rest-api-specs/pull/26178/files#diff-bddcb320f60e156e403b253d2249de57ec774d539c6020fdb885330df6ae414a the property will look like this:
> > > ```json
> > > "serviceTypeHealthPolicyMap": {
> > >           "VotingWeb": {
> > >             "maxPercentUnhealthyPartitionsPerService": 13,
> > >             "maxPercentUnhealthyReplicasPerPartition": 14,
> > >             "maxPercentUnhealthyServices": 15
> > >           }
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That is how the service fabric runtime defines it and we couldn't model this another way than with generic type in the swagger.
> > 
> > 
> > Will there be any validations done on the keys of each of these dictionaries? Or will the dictionary be a pass through to your backend services? Service owned properties MUST be modeled as concrete types. If you would like to stick with your approach, pl book an ARM modeling office hours slot to discuss with the current on-call engineer. https://armwiki.azurewebsites.net/introduction/office_hours.html
> 
> ok we removed the action for now and will add it in the next api with concrete types

I see many more properties using additionalProperties. My comment was for all such instances not just this one. Please either provide an exaplanation for why these cannot be concrete types or remove them.

**Comment by a-santamaria** [comment]
> [rkmanda](/rkmanda)

@rkmanda, but they were not introduced on this api, right? we will not change the properties we already have because that would mean breaking changes. Or am I missing a property we introduced in this new api?

**Comment by rkmanda** [comment]
managedapplication, managedcluster and nodetype all are showing up as newly added json files so its unclear to me what the new changes are. 

https://github.com/Azure/azure-rest-api-specs/pull/26178#issuecomment-1758258004

**Comment by rkmanda** [comment]
> managedapplication, managedcluster and nodetype all are showing up as newly added json files so its unclear to me what the new changes are.
> 
> [#26178 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/26178#issuecomment-1758258004)

Please come to one of our office hours and we can review this together instead of the back and forth

**Comment by a-santamaria** [comment]
> > managedapplication, managedcluster and nodetype all are showing up as newly added json files so its unclear to me what the new changes are.
> > [#26178 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/26178#issuecomment-1758258004)
> 
> Please come to one of our office hours and we can review this together instead of the back and forth. Either that or please follow the comment on how to create a PR for a new version that make the review easy

@rkmanda, please take a look at this commit https://github.com/Azure/azure-rest-api-specs/pull/26178/commits/75425205f9a43a1fddd9d0005f463a2b371459d5. I squashed all the commits that address comments in this pr so its easy to see the changes compare to the old api

**Review by zizw123 — APPROVED** [review]

**Pull request merged**
