### PR TITLE
[Hub Generated] Review request for Microsoft.Attestation to add version preview/2018-09-01-preview

### PR DESCRIPTION
**Pull request by gkostal**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/gkostal/azure-rest-api-specs/arm-tracked-resource-attestation-Microsoft.Attestation-2018-09-01-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### Description
The Microsoft.Attestation resource provider is currently in very early preview.  Currently from the ARM perspective it's a global resource provider that's routed using the "proxyOnly" routing type. In order to support multiple regions, the Microsoft.Attestation resource provider must switch to be a "tracked" ARM resource. The changes in this PR reflect the required changes we need to make to the REST protocol in order to enable the "tracked" ARM resource mode.

The changes in this PR include a breaking change to the PUT operation for the Microsoft.Attestation/attestationProviders resource type.  We have intentionally made this change to the existing api-version since customers will already encounter a breaking change when we switch the service from global to regional in the upcoming month via updating the ARM manifest.

There is one failing test in the test automation -- SDK NET.  I have verified that the cause of this failure is due to the intentional breaking change to the PUT operation.  This test failure can be considered a false positive.

### CODE REVIEW

**Comment by gkostal** [comment]
Please see initial overview.  The failure of the SDK Net test is by design due to a **by design** breaking change to the PUT operation for the existing preview api-version.  This is intentional since the service is in very early preview with a limited number of clients and customers will encounter a breaking change in the upcoming month anyhow as we migrate the service from a single global instance to multiple regional instances.

**Comment by yungezz** [comment]
hi @gkostal, thanks for the detail information about the change itself and breaking change. The change looks good to me, waiting for ARM feedback.

**Comment by yungezz** [comment]
hi @NullMDR could you pls help to look at the Python SDK failure? thanks.

**Comment by yungezz** [comment]
based on offline sync with @gkostal, the CI tests (specifically the .NET SDK) tests won't pass by design since this is a breaking change to the SDK API signature for create.  @gkostal  has  the code fix ready to go for an updated SDK.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
