### PR TITLE
Add specifications for dynanic threshold GA api

### PR DESCRIPTION
**Pull request by noferrar**
As part of moving ‘Smart Analytics’ dynamic threshold alerts to GA, this PR adds  the specification of the GA api for dynamic threshold.
The GA api is IDENTICAL to the preview api (except of the version of course).
The specification of the preview api can be found here:
azure-rest-api-specs/specification/monitor/resource-manager/microsoft.insights/preview/2017-11-01-preview/

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by noferrar** [comment]
Hi,

I will apricate it if somebody can address this PR.
The GA api is in this PR is IDENTICAL to the preview api (except of the version of course), so I assume it shouldn’t take long.

Thanks,
Noam

**Comment by annatisch** [comment]
Thanks @noferrar - I will take a look this morning

**Comment by annatisch** [comment]
@noferrar - I notice that you haven't updated the readme to include this new stable spec, so currently no SDKs will be generated with this spec. Is that your intention?

**Comment by noferrar** [comment]
Thank you @annatisch  for raising this concern.
We don’t need to generate SDK’s.
All we need is to invoke our API by our javascript code running in Ibiza through Arm.

**Comment by annatisch** [comment]
Thanks @noferrar - the spec looks okay - as you says it's identical. However if you wanted to and have a moment - now would be a great time to go through the descriptions to make them consistent in terms of starting with a capital letter, capitalizing abbreviations (e.g. 'ID') etc.... as this helps improve the quality of the [published documentation](https://docs.microsoft.com/en-us/rest/api/monitor/metricbaseline/get#baseline).  :)

**Comment by noferrar** [comment]
Hi @annatisch , I fixed to capital letters & capital abbreviations for all the descriptions. Please take a look, thanks!

**Comment by noferrar** [comment]
I noticed 2 parameters that were missing from documentation so I added them.

**Review by annatisch — APPROVED** [review]
LGTM - that you for taking the time to improve the documentation! We appreciate it :)

**Pull request merged**
