### PR TITLE
dedicatedhsm: fix invalid references in readme.md

### PR DESCRIPTION
**Pull request by ifross89**
Correct references to KeyVault in readme.md

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@schaabs please, review.

**Review by sergey-shandar — APPROVED** [review]

**Review by schaabs — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@ifross89 could you also implement ARM operations API?

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by sergey-shandar** [comment]
@ifross89 @KrisBash there's an ARM violation:

```
R3023 - OperationsAPIImplementation

Operations API must be implemented for '/providers/Microsoft.HardwareSecurityModules/operations'.
  at specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2018-10-31-preview/dedicatedhsm.json:29
```

@ifross89 If you plan to implement these operations in the future, we can merge this PR and then you will provide another PR (before this's going to stable). Another option is to suppress this error but we need justification for the design without ARM API operations.

**Comment by Zariel** [comment]
@sergey-shandar we found this issue with the specs are not a team that provides specs, the issue of not having an ARM spec existed before and was not picked up because of the invalid config that we found.

**Comment by sergey-shandar** [comment]
@veronicagg could we merge the PR?

**Comment by veronicagg** [comment]
@sergey-shandar based on the comments above, yes, makes sense to merge this PR.

**Pull request merged**
