### PR TITLE
Fix linter errors + incorrect example in 2 iotSecurity types

### PR DESCRIPTION
**Pull request by liranc**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by yungezz** [comment]
hi @liranc, this is a breaking change according to https://aka.ms/bcforapi rule, detail in https://github.com/Azure/azure-rest-api-specs/pull/11163/checks?check_run_id=1247121785. This will need breaking change review.

**Comment by liranc** [comment]
> hi @liranc, this is a breaking change according to https://aka.ms/bcforapi rule, detail in https://github.com/Azure/azure-rest-api-specs/pull/11163/checks?check_run_id=1247121785. This will need breaking change review.

@yungezz The breaking change is about changing a field's format, however the format wasn't specified previously (and has been set to `int32`). Isn't `int32` the default? Any chance this is a false positive?
We're making this change after being asked to specify a format by this ticket: https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=1CD7696F-3137-442D-98E1-3F2F7C7668AC

**Comment by yungezz** [comment]
> > hi @liranc, this is a breaking change according to https://aka.ms/bcforapi rule, detail in https://github.com/Azure/azure-rest-api-specs/pull/11163/checks?check_run_id=1247121785. This will need breaking change review.
> 
> @yungezz The breaking change is about changing a field's format, however the format wasn't specified previously (and has been set to `int32`). Isn't `int32` the default? Any chance this is a false positive?
> 
> We're making this change after being asked to specify a format by this ticket: https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=1CD7696F-3137-442D-98E1-3F2F7C7668AC

thanks for the detail. If this is the case, hi @akning-ms , what should be the process for Swagger PR to fix lint error from openApi hub validation result on existing version? and adding format to `Interger` Type property should be excluded as breaking change?

**Comment by akning-ms** [comment]
> > > hi @liranc, this is a breaking change according to https://aka.ms/bcforapi rule, detail in https://github.com/Azure/azure-rest-api-specs/pull/11163/checks?check_run_id=1247121785. This will need breaking change review.
> > 
> > 
> > @yungezz The breaking change is about changing a field's format, however the format wasn't specified previously (and has been set to `int32`). Isn't `int32` the default? Any chance this is a false positive?
> > We're making this change after being asked to specify a format by this ticket: https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=1CD7696F-3137-442D-98E1-3F2F7C7668AC
> 
> thanks for the detail. If this is the case, hi @akning-ms , what should be the process for Swagger PR to fix lint error from openApi hub validation result on existing version? and adding format to `Interger` Type property should be excluded as breaking change?

based on discussing with Jeffery, If fixing lint issue will cause breaking change, we can ignore lint failure.  In this case, if service side is default int32. Not sure whether this case is really breaking change. @JeffreyRichter to confirm

**Comment by JeffreyRichter** [comment]
A JSON number represents a floating point number where the integer range is between [2^53-1 to 2^53+1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)

Changing the integer to have a reduced range is definitely a breaking change.

**Comment by yungezz** [comment]
> A JSON number represents a floating point number where the integer range is between [2^53-1 to 2^53+1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)
> 
> Changing the integer to have a reduced range is definitely a breaking change.

thanks @JeffreyRichter . So what's suggested solution for this PR? fixing the format issue in new API version?

**Comment by JeffreyRichter** [comment]
Don't fix it; leave it as it is.

**Pull request closed without merging**
