### PR TITLE
fix: Network May Conditon -> Condition

### PR DESCRIPTION
**Pull request by nschonni**
Related to #6104

### CODE REVIEW

**Comment by number213** [comment]
I don't think this is fixed in `2019-06-01`
@MikhailTryakhov @fanymanea please take a look

**Comment by number213** [comment]
@azhao155 could you please take a look? I don't think it's fixed on the server

**Review by sergey-shandar — APPROVED** [review]

**Comment by number213** [comment]
@sergey-shandar @nschonni per email discussion with @azhao155, the typo hasn't been fixed in 2019-06-01 and there is no clear ETA yet.

**Comment by number213** [comment]
Server-side isn't fixed yet, so I'm closing this PR

**Comment by nschonni** [comment]
OK, if the fix doesn't land in this release, the failure should be suppressed in the cSpell.json like the previous versions https://github.com/Azure/azure-rest-api-specs/blob/122749a867336d87f29c36d2e64443418445a4fa/cSpell.json#L691-L696

**Pull request closed without merging**
