### PR TITLE
[Search] Rename CognitiveServices to CognitiveServicesAccount

### PR DESCRIPTION
**Pull request by bitsforthought**
Renaming some types and properties in the client programming model for Cognitive Search per Azure API Review Board feedback. This change is for Track 2 only to avoid breaking backwards compatibility of shipping SDKs (our first Track 2 SDK has not shipped yet).

FYI @arv100kri @sarangan12 

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
@sarangan12 This is blocking development of our Java SDK -- can you please review soon?

**Comment by jhendrixMSFT** [comment]
@brjohnstmsft looks like a breaking change in a spec marked as stable, is this expected?

**Comment by brjohnstmsft** [comment]
@jhendrixMSFT It is expected. This spec is probably in the wrong directory now. Here's what happened:
- The specs in stable used to be only for our .NET SDK (Track 1).
- We started work on a Track 2 Java SDK.
- At some point, the specs needed to diverge, so we copied the specs into a "track1" folder that is used to maintain the .NET SDK.
- As of now, the Java SDK hasn't been released yet, so making breaking changes here is expected, and fortunately not really breaking.

I hope this makes sense. Please let me know if you have any questions or concerns.

**Comment by brjohnstmsft** [comment]
Also, there will be more changes like this coming as we address feedback from the Azure API Review Board.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
