### PR TITLE
Created a new provider Microsoft.CostManagement and moved reports and query api documentation from Microsoft.Consumption to it 

### PR DESCRIPTION
**Pull request by shalinved**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by shalinved** [comment]
@ms-premp @marbing. Please check once.

**Comment by sergey-shandar** [comment]
@sagmor as far as I understood, these changes are API breaking changes in a stable API. All Rest API breaking changes should use new API version.

**Comment by ms-premp** [comment]
@sergey-shandar 
This is the new API-Version .. this version is not launched to public yet.. there are no SDK or CLI etc for this version yet.
So there are no breaking changes .. these all changes are new under the umbrella of a new version. This version will be declared in public namespace by end of this month.

**Comment by sagmor** [comment]
@sergey-shandar I think I'm not the right @ mention, but please let me know if I'm missing something 👍

**Comment by ms-premp** [comment]
@sergey-shandar any progress here.

**Comment by ravbhatnagar** [comment]
Looks good. These APIs have already been reviewed. Now as part of this PR, they are being moved under the costManagement RP. Just wanted to confirm if the intention is to add these to a GA api-version or preview?

**Comment by ms-premp** [comment]
Yes, @ravbhatnagar .. The intention is to add them to a new GA version… which is 2018-05-31.

**Comment by sergey-shandar** [comment]
@ms-premp we assume if it's published in this repo in the master branch under `stable` folder then it's public and some people may generate stable SDKs even without your knowledge. Removing/renaming operation paths from `2018-05-31` are Rest API breaking changes.

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@ms-premp please, let me know when the API is publicly available so I will merge it.

**Comment by ms-premp** [comment]
@sergey-shandar .. We are validating it right now ... will let you know, when validations are passing.

**Comment by ms-premp** [comment]
@sergey-shandar all validations are completed. Please merge whenever you are ready.

**Comment by ms-premp** [comment]
@sergey-shandar .. any update ?

**Comment by ms-premp** [comment]
@sergey-shandar .. any update ?

**Pull request merged**
