### PR TITLE
Remove duplicate operations

### PR DESCRIPTION
**Pull request by solankisamir**
Tag_ operations have all been moved to apimtags.json file. Removing them from apimproducts.json

Apis_ListByTags have been moved to apimapis.json, removing the file apimapisbytags.json

@dsgouda this is related to PR
https://github.com/Azure/azure-rest-api-specs/pull/2449

@vfedonkin FYI

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by solankisamir** [comment]
@marstr can you take a look? This is mostly cleanup and things we missed in older pr

**Comment by solankisamir** [comment]
@marstr a gentle ping again?
I think this scenario should be handled in the validation itself. If in a spec, you have two operations with same OperationId across multiple files and for the same readme.md, we should throw an error.
@dsgouda fyi

**Comment by solankisamir** [comment]
@mcardosos can you take a look at this? @marstr has been not responsive on the PR

**Comment by marstr** [comment]
Hey, sorry for the delay on this. I've been preoccupied with other important matters.

I'll need to spend a little time ensuring that the these are truly duplicated items. I see one of changes is a deleted file. Could you send me a link to the other copy, as well as the updated references to it? (This is likely in the `input-files` section of your service's README.

**Comment by solankisamir** [comment]
@marstr the 
- deleted file contents are present in [Apis_ListByTags](https://github.com/solankisamir/azure-rest-api-specs/blob/removeduplicateoperations/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2017-03-01/apimapis.json#L1903)
- Tag_ListProducts, Tag_DetachFromProduct, Tag_AssignToProduct, Tag_GetByProduct which is removed from apimproduct.json is present [here](https://github.com/solankisamir/azure-rest-api-specs/blob/removeduplicateoperations/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2017-03-01/apimtags.json#L1250)

**Comment by marstr** [comment]
I've verified that the Tag operations match between the ones still present in the repo, and those deleted. The only difference was the location used to reference parameters with the same names.

I am curious though, could you reiterate why the deleted file is only in your fork and what your plans are to reintroduce it?

**Comment by solankisamir** [comment]
We don't plan to reintroduce the file, the operation will stay in apimapis.json

**Review by marstr — APPROVED** [review]

**Pull request merged**
