### PR TITLE
Normalizer api specs

### PR DESCRIPTION
**Pull request by ishansrivastava90**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [x] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
   Public Preview in March 2021; Generally Available in mid-2021

  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  March, 2021
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ishansrivastava90** [comment]
@brjohnstmsft @heaths This PR mimics the one created earlier and was pending the feature to be deployed.

**Comment by brjohnstmsft** [comment]
@ishansrivastava90 Do you have a link to the other PR you mentioned?

**Comment by ishansrivastava90** [comment]
> @ishansrivastava90 Do you have a link to the other PR you mentioned?

@brjohnstmsft Here's the original PR - 
https://github.com/Azure/azure-rest-api-specs/pull/11954

**Review by bitsforthought — APPROVED** [review]

**Comment by ishansrivastava90** [comment]
@Mohit-Chakraborty  @heaths Checking in. Are there any updates on this change?

**Review by Mohit-Chakraborty — APPROVED** [review]

**Comment by Mohit-Chakraborty** [comment]
@johanste , what do you think about the breaking nature of this change?

**Comment by ishansrivastava90** [comment]
> @johanste , what do you think about the breaking nature of this change?

@Mohit-Chakraborty 
@brjohnstmsft  pointed out that this shouldn't be a breaking change since this is an optional parameter and round tripping shouldn't be affected. Is our understanding not correct.

**Comment by brjohnstmsft** [comment]
@ishansrivastava90 Per the new breaking change guidelines, this would be considered a breaking change, **if** it were in a GA version. But since this is a preview version, I'm not sure why the build is even flagging this as anything other than a warning.

**Comment by heaths** [comment]
New guidelines are that previews must be versioned and continue support for 90 days. That said, I know you've been operating this way "forever". @JeffreyRichter @johanste Search has been updating previews like this and we really haven't heard any customer complaints via the SDK. Is this okay to ignore the breaking change for adding an optional response property in a preview version?

**Comment by JeffreyRichter** [comment]
Since the guidelines are new, I've been very lenient about approving changes in previews that add fields. So, I'd approve this change

• Jeffrey Richter (see Architecting Distributed Cloud Apps<http://aka.ms/RichterCloudApps> & Designing HTTP APIs<https://www.youtube.com/watch?v=9Ng00IlBCtw&list=PL9XzOCngAkqs4m0XdULJu_78nM3Ok3Q65&index=1>)

________________________________

**Pull request merged**
