### PR TITLE
AzureStack Network Admin - Removed extraneous properties on Quota

### PR DESCRIPTION
**Pull request by deathly809**
There was a bug in which QuotaProperties was given two extra properties from a referenced definition.  I have split the referenced object into two new definitions, one which has a provisioning state (ProvisionedResource) and another which contains tenant related properties (TenantResource).  QuotaProperties now only correctly referenced ProvisionedResource.  I have also updated all resources to include the two new references.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by marstr — APPROVED** [review]
Givent that you're in `preview`, changing names, etc, is permissable.

I do want to call out here though, you're missing an important ARM operation: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/370282355#L746

Before your swagger is moved into the stable folder, you're going to have to add an "operations" path. Additionaly, you're going to need a README with tags that allow code generation into the various AutoRest supported languages. You'll see by the empty comments above that our automation is not engaged without that README.

**Comment by deathly809** [comment]
@marstr  Yeah I know.  I told the NRP team about it and they are working on it.  I actually wrote most of the code and handed it over to them but it seems they didn't finish it.

We currently do not support any language other than C# and will not add extra languages at this time.

**Comment by deathly809** [comment]
@dsgouda They added the WaitForArmFeedback.  What can I do to get this expedited?

**Comment by ravbhatnagar** [comment]
This does not need to be reviewed by ARM team since this is Azure Stack

**Comment by deathly809** [comment]
@marstr can you please merge so I can begin the SDK PR?  Thanks!

**Pull request merged**
