### PR TITLE
CI test and upgrades

### PR DESCRIPTION
**Pull request by olydis**
some improvements to CI, goals:
- ensure all jobs still do what they're supposed to do

deferred:

- use linter consistently (before momentOfThruth didn't use the same command as the linter job)
- use model & semantic validator through AutoRest so they pick up the right files, suppression works and stuff is reported consistently

### CODE REVIEW

**Comment by olydis** [comment]
@vishrutshah just to raise awareness: I'm porting over `getStatus.js` right now, but realized that it was already very broken. For example, if the linter returned with an exit code that is not 0 (that happens if there is a validation error, so pretty common!), it just printed `An error occurred while running the linter on ...`, printed the linter output to the console and did *not* add the results to the report! So the worst Swaggers would actually not make it into the report... I hope this script wasn't used for important stuff in the past, do you know more?

**Comment by olydis** [comment]
Apart from that, why is there such a horrible amount of code duplication? `momentOfTruth` and `getStatus` are 90% the same, some bugs are duplicated, some in the remaining 10%...

**Comment by vishrutshah** [comment]
@olydis You are right. `getStatus` was initially built just for gaurav but never been updated to keep up to date. I am not sure whether we need that or not. Let me find it out for you and if not used we can just keep momentOfTruth script.

**Comment by olydis** [comment]
awesome, thanks!

**Comment by olydis** [comment]
@veronicagg Where are we with using model/semantic validator through AutoRest? Would be cool to use them through AutoRest, such that:
- we're not running stuff on a per Swagger basis for one type of validation, but on a per config file for another
- we have a consistent output format (readable message, problem location, ...)

**Comment by veronicagg** [comment]
@olydis we will, I'll have an update soon (as long as I can work on it :)), at that point I can look into this script and see if it's necessary.

**Pull request merged**
