### PR TITLE
chore: jsonfmt network 2019

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/network/**/stable/2019*/**/*.json"`

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@nschonni This seems to trigger errors [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=28899) either undo changes to that directory or fix the errors if you can

**Comment by MikhailTryakhov** [comment]
@nschonni  please resolve the conflicts due to release date is tomorrow

**Comment by MikhailTryakhov** [comment]
@dsgouda  can we merge this list of a fixes as well? One known job is failed, the rest of them looks to be passed

**Comment by EvgenyAgafonchikov** [comment]
commited with --amend w/o changes to re-trigger CI

**Comment by MikhailTryakhov** [comment]
@dsgouda can you please help to merge?

**Pull request merged**
