### PR TITLE
4253190    [Microsoft.Update.Admin] Resources missing from OpenApi Spec

### PR DESCRIPTION
**Pull request by yudomsft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by kpajdzik** [comment]
If you haven't taken a look at our new onboarding experience at [OpenAPIHub](http://aka.ms/openapihub), it's a convenient way to create your PR when you're copying from an existing API version or when you're editing your existing specs. If you have any feedback or questions, feel free to use the feedback button on top of the site for help. Thanks!

**Comment by kpajdzik** [comment]
LGTM. Let's wait for ARM feedback.

**Review by KrisBash — APPROVED** [review]
LGTM

**Review by kpajdzik — APPROVED** [review]

**Comment by kpajdzik** [comment]
@yudomsft Do you want me to merge? Is the service deployed?

**Comment by yudomsft** [comment]
@kpajdzik Please merge. This API is for Azure Stack only so there is no concept of "deployed".

**Pull request merged**
