### PR TITLE
ADF: Salesforce and JSONFormat

### PR DESCRIPTION
**Pull request by smilenow**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by smilenow** [comment]
@bgold09, please help to approve this PR since we have finished the code review before.

**Review by bgold09 — CHANGES_REQUESTED** [review]
waiting on formal internal approval

**Comment by marstr** [comment]
Looks like there are Semantic errors in some of these files. Please take a look at the CI Logs in the following places (I've selected only the semantic errors associated with DataFactory Swaggers):
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L1773
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L3638
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L4265
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L4905
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L5545
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L5558
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L6185
- https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L6825

**Review by marstr — DISMISSED** [review]
Looks like there are Semantic errors in some of these files. Please take a look at the CI Logs in the following places (I've selected only the semantic errors associated with DataFactory Swaggers):

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L1773
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L3638
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L4265
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L4905
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L5545
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L5558
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L6185
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/290676590#L6825

**Comment by smilenow** [comment]
@marstr , I have looked at these CI logs, and these Semantic errors are not coming from my change. Do you mean I need to resolve all of them in this PR?
@bgold09 , I think it should be more efficient to find the feature owner to resolve these Semantic errors.

**Comment by bgold09** [comment]
@marstr we have never been blocked on such errors before, and furthermore these look like preexisting issues. Is this related to updating the version of `oav` being used in the builds? 

We can fix these, but I don't think it's appropriate to require it to merge this feature change

**Comment by marstr** [comment]
Howdy @bgold09 and @smilenow, thanks for looking into those. @veronicagg and I are looking into the errors that are coming up. We'll get back to you soon to tell you if any of these errors need to be fixed as part of this PR.

**Comment by marstr** [comment]
After reaching out to @amarzavery, it seems like there was a bug in our CI anyway. He should be redeploying shortly, and we can re-run CI. However, informally, it sounded like when he ran it locally, there were no semantic errors present in your PR or any of the files in this directory.

**Comment by veronicagg** [comment]
We updated oav tool and I restarted the semantic validation job, which is now clean. Sorry for the inconvenience and thanks for reporting the issue.

**Comment by bgold09** [comment]
@veronicagg no worries, thanks for looking into it

**Review by bgold09 — APPROVED** [review]
approved via internal item [97878](https://msdata.visualstudio.com/Azure%20Data%20Factory/_workitems/edit/97878)

**Comment by smilenow** [comment]
@marstr , could you please help to merge this PR? All checks passed and internal item has been approved.

**Review by marstr — APPROVED** [review]
I confirmed that there are no hidden changes in LinkedService.json

**Comment by marstr** [comment]
I should note, adding discriminator values can break some older clients. Do we know whether this was done as a bug fix in the Swagger or as support for new types?

**Comment by smilenow** [comment]
@bgold09 , please help to take a look at Martin mentioned issue above. In my understanding, this PR is used to support for new types.

**Comment by bgold09** [comment]
this was done to support new types

**Pull request merged**
