### PR TITLE
[Hub Generated] Review request for Microsoft.Kusto to add version stable/2020-02-15

### LINKED ISSUE #9450: Kusto: Wrong type of ReadWriteDatabaseProperties#isFollowed
ReadWriteDatabaseProperties#isFollowed must be of type `bool`, but is  of type `string`.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json#L2879

This leads to a unmarshal error within the Go library.

Bug reference: https://github.com/Azure/azure-sdk-for-go/issues/9339

### PR DESCRIPTION
**Pull request by docohe**
Fixes #9450 

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/docohe/azure-rest-api-specs/dev-azure-kusto-Microsoft.Kusto-2020-02-15...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by docohe** [comment]
@njuCZ could you please review ? This is important patch for an external customer.

**Comment by jrauschenbusch** [comment]
any update here?

**Comment by dorcohe** [comment]
> any update here?

Waiting for @njuCZ to review and approve. After that we will need to generate new clients, which will take another 3 days.

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @akning-ms could you please help us merge this PR?

**Comment by docohe** [comment]
@jrauschenbusch I've published a request to release a new version of the GO SDK
https://github.com/Azure/sdk-release-request/issues/365

It will take few more days until will be released.

**Pull request merged**
