### PR TITLE
Updated ServiceFabric spec with examples

### PR DESCRIPTION
**Pull request by juhacket**
- Added application type name, application type version, application, and service examples
- Updated cluster examples to match current API
- Fixed service resource properties model

### CODE REVIEW

**Review by alvadb — COMMENTED** [review]
It appears that there are breaking changes (https://travis-ci.org/Azure/azure-rest-api-specs/jobs/302075331). Adding Gaurav.

**Review by alvadb — CHANGES_REQUESTED** [review]
Please review the follow errors:
linter: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/302075328
model: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/302075330

**Comment by juhacket** [comment]
This is a preview version, so changes to the model are expected.

**Comment by alvadb** [comment]
Makes sense. Ignoring breaking changes.  Can you look at the linter and model errors and resolve?

**Comment by juhacket** [comment]
Linter is returning false positives based on the RP API documentation. We are explicitly using 202 status code for asynchronous operations. The new resource types are proxy-only, but are being incorrectly flagged as tracked resources. We are not able to change the camelCase style of some of the properties because they are shared with our non-ARM REST API model.

**Comment by alvadb** [comment]
Ignoring breaking changes since this is a preview version.  Will merge with linter and model issues based on @juhacket comments.

**Review by alvadb — APPROVED** [review]

**Pull request merged**
