### PR TITLE
[compute] Removing x-ms-azure-resource extension from invalid model ResourceUpdate

### PR DESCRIPTION
**Pull request by vishrutshah**
Model `ResourceUpdate` is not a valid Azure resource. It should not be marked as `x-ms-azure-resource: true`. 

cc:
@veronicagg @sarangan12

### CODE REVIEW

**Comment by veronicagg** [comment]
LGTM, @amarzavery @lmazuel @shahabhijeet @jianghaolu @jhendrixMSFT could removing the extension from the spec cause breaking changes/problems on your SDKs?

**Comment by amarzavery** [comment]
LGTM. FYI @huangpf @hyonholee

**Comment by lmazuel** [comment]
This should be fine

**Review by veronicagg — APPROVED** [review]

**Comment by vishrutshah** [comment]
Thanks for the review everyone!!

**Pull request merged**
