### PR TITLE
Adding patch operation to the swagger doc

### PR DESCRIPTION
**Pull request by samkreter**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by alvadb — DISMISSED** [review]
Please review and fix linter and model issues:
linter: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/327054782
model: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/327054783

**Comment by yolo3301** [comment]
@samkreter Please don't merge this. It seems this will cause a problem on the server side.

**Comment by samkreter** [comment]
I have updated for passing tests

**Comment by marstr** [comment]
Hey @samkreter, I noticed this PR is targeting files that don't conform to our repositories organization requirements. I submitted a new PR https://github.com/Azure/azure-rest-api-specs/pull/2338 in order to bring in back into conformance. Once that is merged into master, I'll need you to rebase your changes on top of that.

I noticed that because these files are quite in the right place, there are a few CI errors that are noted in the log, but aren't being reported. I think at least one was introduced by this PR. Take a look here for what I'm talking about:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/330097935#L693

**Review by marstr — CHANGES_REQUESTED** [review]
Hey @samkreter, I noticed this PR is targeting files that don't conform to our repositories organization requirements. I submitted a new PR #2338 in order to bring in back into conformance. Once that is merged into master, I'll need you to rebase your changes on top of that.

I noticed that because these files are quite in the right place, there are a few CI errors that are noted in the log, but aren't being reported. I think at least one was introduced by this PR. Take a look here for what I'm talking about:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/330097935#L693

**Comment by marstr** [comment]
While you work on that, I'll add the ARM folks to get their review started.

**Comment by marstr** [comment]
This PR is blocked on #2338.

**Comment by marstr** [comment]
@samkreter messaged me this morning to say that there is a separate PR that will incorporate these changes, and that this one may be closed.

**Pull request closed without merging**
