### PR TITLE
add required fields for sku object

### PR DESCRIPTION
**Pull request by QingqingYuan2**
The required fields already enforced from RP side from first day, but missed the tag in Swagger. Adding this tag to ensure customer aware of this requirement before submitting to RP and receiving provisioning errors later. 

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
@QingqingYuan2, this PR contains breaking changes, could you help to follow the process in https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes to get this breaking change approved?

**Comment by jianyexi** [comment]
The lintDiff errors are existing errors in the master branch  , so the tool always fails 
as the tool will do check on the original branch first.

Based on the result running lint locally , the PR has no new errors  now  ,so these errors can be ignored.: 
`"0 new errors / 58 new warnings",`

**Comment by QingqingYuan2** [comment]
@raych1 , based on jianyexi's comments above, can we get this merged?

**Comment by raych1** [comment]
> @raych1 , based on jianyexi's comments above, can we get this merged?

Got it, thanks @QingqingYuan2.  Hi @akning-ms, this PR is read to merge, could you help force merge this PR?

**Comment by akning-ms** [comment]
@changlong-liu  @ArcturusZhang @weidongxu-microsoft for comments SDK breaking change impact.

**Comment by weidongxu-microsoft** [comment]
Java SDK on these are all beta, so should be fine.

Require "name" on "sku" is reasonable.

One change happens to stable `Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json`. Could use some estimation on user impact.

**Comment by QingqingYuan2** [comment]
> Java SDK on these are all beta, so should be fine.
> 
> Require "name" on "sku" is reasonable.
> 
> One change happens to stable `Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json`. Could use some estimation on user impact.

This change has been approved by "Azure Services Breaking Changes Reviewers ". 

To summarize and close down this thread:
-	With the assessment that 0 customers in prod are impacted, no change to in API behavior and this change has been caught when the 1st customer is trying it (before prod) – please move forward with implementation of the swagger documentation update. This is not considered a breaking change.

**Comment by changlong-liu** [comment]
For Python, this breaking change will raise SDK major version. 
https://pypi.org/project/azure-mgmt-rdbms/#history

**Comment by ArcturusZhang** [comment]
Go SDK is always OK with breaking changes. 
In the perspective of terraform, terraform has already regarding `name` in `sku` as required, therefore there should be no impact to terraform

**Comment by QingqingYuan2** [comment]
Python SDK, we will release one version in next week anyway with our new offering. For CLI, sku.name also already a required field. As the PR indicates, there is no breaking change from API behavior. This is to fix the Swagger only.

**Pull request merged**
