### PR TITLE
Revert "[Hub Generated] Review request for Microsoft.ApiManagement to add version preview/2019-12-01-preview"

### PR DESCRIPTION
**Pull request by mmyyrroonn**
Reverts Azure/azure-rest-api-specs#8066

Merged #8066 by mistake. Create a revert PR.

### CODE REVIEW

**Review by solankisamir — APPROVED** [review]
Will go back to the end of the queue with ARM review ?

**Comment by solankisamir** [comment]
@MyronFanQiu @sanjaiganesh is looking into the merged PR. Please don't merge this until then.

**Comment by solankisamir** [comment]
@MyronFanQiu I am closing this PR, as ARM as signed off on the previous one.

**Comment by JackTn** [comment]
Hi, @MyronFanQiu. The PR has be closed for a long time and it's related branch still exist. If no further used for over 14 days, I will delete this related branch. Please tell me if you still need this branch.

**Comment by JackTn** [comment]
Hi, @mmyyrroonn. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @mmyyrroonn. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @mmyyrroonn. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
