### PR TITLE
Update for Get Application Gateway Server Variables APIs

### PR DESCRIPTION
**Pull request by nirkum18**
### Latest improvements:
<i>This is a breaking change. Get Application Gateway Server Variables APIs changes were merged in 2018-11-01. We want the APIs results to be of type List(string) rather than Dictionay(string,List)</i>
<i>Link to previous PR: https://github.com/Azure/azure-rest-api-specs/pull/4916</i>
<i></i>
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by dsgouda** [comment]
Working on some high pri .NET deliverables, reassigning

**Comment by sergey-shandar** [comment]
@nirkum18 could you also add 2018-12 tags to `python`, `ruby`, and `java`?

**Comment by sanjaiganesh** [comment]
@KrisBash  (on ARM side) shall be looking into this. This is a breaking change.

**Comment by KrisBash** [comment]
@nirkum18  I will reach out offline to understand the impacts.

**Review by KrisBash — APPROVED** [review]
I understand that these changes are necessary to align swagger spec to server behavior. Signing off from ARM

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
readme files for Go and other languages has to be fixed before merge.

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by nirkum18** [comment]
> @nirkum18 could you also add 2018-12 tags to `python`, `ruby`, and `java`?

Made changes to readme.python.md and readme.ruby.md. I see we don't have readme file for java in Network.

**Comment by jhendrixMSFT** [comment]
@sarangan12 for ruby build failure.

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@nirkum18 could you also check these errors https://travis-ci.org/Azure/azure-rest-api-specs/jobs/488714091 ?

**Comment by sarangan12** [comment]
@sergey-shandar The Linter Diff tool does not have enough memory to run in Travis CI and it is failing. As a temporary solution, I have executed the tool locally, and here is the result:


Config file: specification/network/resource-manager/readme.md

SDK Errors/Warnings
===================
Errors:    Before:  0  - After:  0
Warnings:  Before:  165  - After:  162
New SDK Errors:  0
New SDK Warnings:  0
Existing SDK Errors:  0
Existing SDK Warnings:  0

ARM Errors/Warnings
===================
Errors:    Before:  0  - After:  0
Warnings:  Before:  0  - After:  0
New ARM Errors:  0
New ARM Warnings:  0
Existing ARM Errors:  0
Existing ARM Warnings:  0

So, if you are ok with all the other things, then you can merge these changes.

**Pull request merged**
