### PR TITLE
Change the operation_id from *ListRegenerateApiKeys to RegenerateApiKeys

### PR DESCRIPTION
**Pull request by dolauli**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by dolauli** [comment]
@vrijesh  I made a fix to the spec. But CI failed because of something before my change. Would you please take a look?

**Comment by vrijesh** [comment]
@dolauli  - I will take a look tomorrow as could not get to this.

**Comment by dolauli** [comment]
@vrijesh There is another issue actually. See below, you should define the property "type" as "enum" with acceptable values. Otherwise, the user will have no idea what values they should provide for "type". And in the sample Locations_CheckNameAvailability.json, I found one possible value for type is "Microsoft.Blockchain/blockchainMembers".
```
    "NameAvailabilityRequest": {
      "description": "Name availability request payload which is exposed in the request of the resource provider.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Gets or sets the name to check.",
          "type": "string"
        },
        "type": {
          "description": "Gets or sets the type of the resource to check.",
          "type": "string"
        }
      }
    },
```

**Review by vrijesh — APPROVED** [review]
Looks good. Thanks for taking care.

**Pull request closed without merging**
