### PR TITLE
[Draft] Capacity RP Quota APIs for GA

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>
1. Capacity RP Quota APIs for GA
2. Removed AutoQuotaIncrease APIs from stable. It remains in Preview.

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@rahuls-microsoft , please remove `notreadyforreview` label when the PR is moving out of `draft` state and ready for review.

**Comment by corquiri** [comment]
There are 2 services behind Microsoft.Capacity : 
i) quota service
ii) reservation service
Each service maintains different api version but they are behind the same provider namespace.
This PR merges 2 swagger which has different API versions and generates SDK
Me and Rahul checked the generated SDK and verified that each API uses its own api-version

@raych1 do you see any issue with this structure ? having 2 services behind same namespace ?

**Comment by rahuls-microsoft** [comment]
> Comment was made before the most recent commit for PR 11195 in repo Azure/azure-rest-api-specs

I have merged the latest changes from master.

**Comment by raych1** [comment]
@rahuls-microsoft , the ARM review will be started unless you go thru and check the items in `Contribution checklist` of first comment in this PR.

**Comment by rahuls-microsoft** [comment]
@raych1 I am moving the Quota Apis from reservation folder to Quota folder to make the documentation and SDK representing Quota.
There is no change from original folder - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-07-19/quota.json 

I have removed the quota APIs from reservation folder.

But it's giving errors. The APIs were approved previously.

**Questions:**
1. How do I resolve the errors flagged?
2. Do I need to setup in other SDK repos for new SDK generation or it will be created automatically?

**Comment by raych1** [comment]
> @raych1 I am moving the Quota Apis from reservation folder to Quota folder to make the documentation and SDK representing Quota.
> There is no change from original folder - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-07-19/quota.json
> 
> I have removed the quota APIs from reservation folder.
> 
> But it's giving errors. The APIs were approved previously.
> 
> **Questions:**
> 
> 1. How do I resolve the errors flagged?
> 2. Do I need to setup in other SDK repos for new SDK generation or it will be created automatically?

@rahuls-microsoft , the [check result page](https://github.com/Azure/azure-rest-api-specs/pull/11195/checks?check_run_id=1389350810) has the information for the fix. 
Please see [FAQ](https://github.com/Azure/azure-rest-api-specs/wiki/FAQ-in-Swagger-PR-Review#SDK) for SDK instructions.

**Comment by rahuls-microsoft** [comment]
The build has started failing after merge from master.
Are other PRs having similar issues?
Please suggest how to resolve the build failures for  - sql/resource-manager
he example JSON file is not referenced from the swagger file.
readme: specification/sql/resource-manager/readme.md
json: preview/2020-08-01-preview/examples/CreateDatabaseMaintenanceConfiguration.json

**Comment by raych1** [comment]
> The build has started failing after merge from master.
> Are other PRs having similar issues?
> Please suggest how to resolve the build failures for - sql/resource-manager
> he example JSON file is not referenced from the swagger file.
> readme: specification/sql/resource-manager/readme.md
> json: preview/2020-08-01-preview/examples/CreateDatabaseMaintenanceConfiguration.json

@rahuls-microsoft , please fix the `avocado` check failures firstly. Regard to the reference issue, either reference it by `x-ms-examples` property or remove the example file if that is not used any more.

**Comment by rahuls-microsoft** [comment]
> > The build has started failing after merge from master.
> > Are other PRs having similar issues?
> > Please suggest how to resolve the build failures for - sql/resource-manager
> > he example JSON file is not referenced from the swagger file.
> > readme: specification/sql/resource-manager/readme.md
> > json: preview/2020-08-01-preview/examples/CreateDatabaseMaintenanceConfiguration.json
> 
> @rahuls-microsoft , please fix the `avocado` check failures firstly. Regard to the reference issue, either reference it by `x-ms-examples` property or remove the example file if that is not used any more.

1. It's coming **from sql/resource-manager. It's not my change. It came from merge from master.**
   What can I do about other team's update from master branch?

2. Regarding this issue - The capacity RP is shared by 2 teams - **Reservation and Quota team. So, we have different versions of API.** Similarly, compute and networking teams might have different versions of APIs based on the team schedule.
How do we address this case?

⚠️ MULTIPLE_API_VERSION | The default tag contains multiple API versions swaggers.readme: specification/reservations/resource-manager/readme.mdtag: specification/reservations/resource-manager/readme.md#tag-package-2020-10-25
-- | --

**Comment by rahuls-microsoft** [comment]
Created a new fork from master and new Pull request - https://github.com/Azure/azure-rest-api-specs/pull/11930.
I will close this pull request.

**Comment by rahuls-microsoft** [comment]
Created a new fork from master and new Pull request - #11930.
I will close this pull request.
It looks like the errors were do to bad merge from master.

**Pull request closed without merging**
