### PR TITLE
Rename metricAlert_API.json to metricAlerts_API.json

### PR DESCRIPTION
**Pull request by ColinNg**
The rename is to match the convention used elsewhere (i.e. the documentation page, and the actual API URL)

Below is the current state, where the other URLs call it metricalerts / metricAlerts, but the REST API Specs calls it metricAlert without the "s". 

Purpose | Url
---------|----
InfoUri | https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/listbysubscription 
ApiUrl | https://management.azure.com/subscriptions/{subscriptionId}/providers/microsoft.insights/metricAlerts?api-version=2018-03-01 
ApiSpecUri | https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by nschonni** [comment]
Think the README.md paths need to get updated too

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
Please update the README.md file with the new file name.

**Comment by jhendrixMSFT** [comment]
@ColinNg hello any update?

**Comment by ColinNg** [comment]
Hi @jhendrixMSFT, do you mean the readme.md at https://github.com/ColinNg/azure-rest-api-specs/blob/aa92fad7684a8b24549bcd2141e91b0610e27238/specification/monitor/resource-manager/readme.md? 

I noticed the old name is mentioned in 6 tags, all of which are in the past (i.e. `Tag: package-2018-03`). Does that mean I should also make the same changes (rename file, update ReadMe) for all those tags too?

**Comment by jhendrixMSFT** [comment]
Yes any references to the old file name will need to be updated with the new file name.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Closing due to inactivity.

**Pull request closed without merging**
