### PR TITLE
Changes chat message image url type from url to string to support DataUris

### PR DESCRIPTION
**Pull request by dersia**
# Data Plane API - Pull Request
Azure OpenAI Chat completion endpoints support Images as chat content. These are supported either as plain Uris or as DataUris. The spec has set the type of the `Url` field set to type `url`. This PR changes the type to be string. This would allow in the generated Clients to use DataUris.

For C# the type `url` is generated as `System.Uri`. `System.Uri` unfortunately is limited to only support Uris up to 64KB as you can see here:
https://github.com/Azure/azure-sdk-for-net/issues/40744
https://github.com/Azure/azure-sdk-for-net/issues/40855
https://github.com/dotnet/runtime/issues/96544
https://github.com/dotnet/runtime/issues/85164

this prevents Frameworks like Semantic Kernel that use Azure-SDK-for-NET from using the generated client to send images to Azure OpenAI.

Change:
This PR will change the type of the Url for ChatCompletions to string.

This allow https://github.com/Azure/azure-sdk-for-net/issues/40744 and https://github.com/microsoft/semantic-kernel/issues/4781 to be fixed

### CODE REVIEW

**Comment by dersia** [comment]
Attention: this will introduce a breaking change in the generated clients. I am not sure, if this can be done differently with generated clients. if there is a better way I am more than happy to adjust this PR.

**Comment by artemkoloskov** [comment]
@dersia in a [PR to Kernel](https://github.com/microsoft/semantic-kernel/pull/5008) you seem to have changed the implementation since making this PR, does this PR maybe need adjustments to reflect that? Or is the `ImageContent.ToString` will be used to map back into the `ChatMessageImageUrl.url`, so this would likely work already if merged?

**Comment by dersia** [comment]
@artemkoloskov Sorry I did not see your message earlier, somehow missed the notification.

As to answer your Question, everything is prepared on SK to make use of this once it is available. For now since the SDK publishes `System.Uri` semantic kernel cannot be changed to make use of the `.ToString()` method on `ImageContent`.
As of today SK sets `ChatMessageImageUrl.url` to `ImageContent.Url` because it needs to be `System.Uri` and there is no other way to "prepare" for it to just work once this is merged.
So a few things will happen once this is merged:

* as soon as Semantic Kernel or any other code that depends on the SDK updates to the new version that changes the type from `System.Uri` to `string` they will have a source breaking change and everyone needs to fix/adapt. 
* Once this is merged and the new version is published to nuget I will update Semantic Kernel to adopt to the change as of right now SK sets `ChatMessageImageUrl.Url` to `ImageContent.Uri`

I hope this makes clear what the steps are.
And just to mention it again, I hate for this to be a source breaking change, but I can't think of any other way to do this, since this is all autogenerated.

**Comment by artemkoloskov** [comment]
@dersia thank you, and I think sometimes breaking changes should absolutely be done, this is a very needed change.

**Comment by dersia** [comment]
I found a better and non breaking solution https://github.com/Azure/azure-sdk-for-net/pull/43093, so I will close this issue

**Pull request closed without merging**
