### PR TITLE
Name change to Cosmos DB

### PR DESCRIPTION
**Pull request by dmakwana**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by balajikris** [comment]
I'm okay with the changes made here. I'd like to understand one thing though - after this is merged and when SDK packages are regenerated, which of the following is true:

1. we generate package with a new name `azure-arm-cosmos-db` and a new version
1. we keep the same package name `azure-arm-documentdb` and version it appropriately accounting for breaking changes if any.

**Comment by balajikris** [comment]
@dmakwana -- could you answer the above question please? thanks.

**Review by balajikris — APPROVED** [review]
LGTM

**Comment by lmazuel** [comment]
@balajikris On the Python side, it's definitely a new "azure-mgmt-cosmodb" :)

**Comment by balajikris** [comment]
@dmakwana - ping.

**Comment by dmakwana** [comment]
@balajikris 

We should generate new packages with a new name and new version

**Comment by balajikris** [comment]
thanks , merging in.

**Pull request merged**
