### PR TITLE
Add "Warning" to the EP HealthStatus field

### PR DESCRIPTION
**Pull request by yirsu**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [x] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  June/July 2023
  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  June/July 2023
  6. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by yirsu** [comment]
breaking change scenario: https://msazure.visualstudio.com/One/_workitems/edit/23128392

**Comment by keryul** [comment]
> breaking change scenario: https://msazure.visualstudio.com/One/_workitems/edit/23128392

Hi @yirsu I have no permission for this work item, can you bring it to pr comment?

**Comment by yirsu** [comment]
@keryul 
<html>
<body>


Request: | Microsoft.PowerPlatform
-- | --
Scope: | API
Problem space Scenario details | We need to add a new enum value "Warning" as an allowed value for readonly property "healthStatus" to the enterprise policy resource model.  Current values: "Undetermined", "Healthy", "Unhealthy"New values: "Undetermined", "Healthy", "Warning", "Unhealthy"Note that this field is readonly to the customer, and the health check feature has not rolled out yet so there is no customer impact of adding another allowed value into the enum
Proposal for review | Add enum value "Warning" to the readonly "healthStatus" field
Business Justification: | This is needed for Power Platform CMK feature
Client Library Implication | no
Announcement date: | No announcement requested
Implementation date: | already implemented
Current Customer count: | CMK feature is under public previewHealth status feature of CMK has not rolled out yet, 0 customer
Current S500 customers: | N/A
Migration | No action for the customer. It is a read-only property consumed by other internal services.
External comms | Communication not desired.


</body>
</html>

<html>
<body>
<p style="box-sizing: border-box; font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0in; font-size: 16pt; color: rgb(30, 78, 121);">Details</p><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Name of org | Power Platform Developer and Admin Experiences
-- | --
Name of team contact | Yiran Sun
Name of service impacted | Microsoft.PowerPlatform
What is being changed? | API.
1-2 sentence detail on what is being changed | Adding enum value to a readonly property in the API swagger.
Lifecycle of the service being changed | CMK - public preview
External documentation available | Manage your customer-managed encryption key in Power Platform - Power Platform \| Microsoft Learn
Specify the Impact category (breaking change, requires downtime, seamless) | Seamless
Is this breaking change essential (security, compliance)? | feature request
Adheres to the Breaking change policy for services (36 months) | no
Are you seeking an exception to the policy | Unclear. Some doc indicates that adding/changing a readonly property is not a breaking change.
Business Justification for the exception. (reasons, timeline for approval).Note: This requires service teams to present and seek sign off from the Office of the CTO. |  
Any dependencies on Non Microsoft Technologies | no
List the Non Microsoft Technology |  

</div>

<html>
<body>
<p style="box-sizing: border-box; font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0in; font-size: 16pt; color: rgb(30, 78, 121);">Customer Impact</p><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Number of customers impacted | 0
-- | --
Number of production subscriptions impacted | 0
Number of S500/S400 impacted customers | 0
Top 10 impacted customers | N/A
Customer specific mitigation plans | N/A
Do any other products have dependency on the scope of this breaking change? | no

</div>
</body>
</html>

**Comment by keryul** [comment]
>We need to add a new enum value "Warning" as an allowed value for readonly property "healthStatus" to the enterprise policy resource model.  Current values: "Undetermined", "Healthy", "Unhealthy"New values: "Undetermined", "Healthy", "Warning", "Unhealthy"Note that this field is readonly to the customer, and the health check feature has not rolled out yet so there is no customer impact of adding another allowed value into the enum
Breaking Change approved as no customer impact

**Comment by ArcturusZhang** [comment]
Go breaking change does not come from this swagger PR, ignoring

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
