### PR TITLE
Adding required attributes to location and properties

### PR DESCRIPTION
**Pull request by bganapa**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
Hi @bganapa , changing properties as required properties in the stable version is breaking change. Can you change it with a new api version?

**Review by ionuttulai — APPROVED** [review]

**Comment by bganapa** [comment]
@raych1 This is a bug fix as in https://github.com/Azure/azure-rest-api-specs/issues/9400 , we are not changing the API

**Comment by bganapa** [comment]
@raych1 Could you please merge this? I think this issue is showing up in some review as the attached issue is old and longstanding

**Comment by raych1** [comment]
Hi @bganapa , please fix the PrettierCheck failures.

**Comment by raych1** [comment]
Thanks @bganapa , it still needs ARM sign off.

**Comment by bganapa** [comment]
@raych1 Thanks for the response. Whom should I ping for the ARM signoff? As you can see, there is no service side change, hence it is not a breaking change. We are simply fixing a bug found by the customer. If you can, I would urge you to go ahead and merge this PR as this came up in few review. Thanks for your understanding!

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
@akning-ms , can you please force merge this PR since it's a bug fix in swagger and no impact in service side?

**Pull request merged**
