### PR TITLE
Adding files and folders from previous stable version

### PR DESCRIPTION
**Pull request by ravigautam1896**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Review by ericshape — APPROVED** [review]

**Comment by ramoka178** [comment]
1. Please add the template as per https://github.com/Azure/azure-rest-api-specs/pull/29573#issue-2372227281
2. Make the first commit with the exact copy of what you have today. In the subsequent commit, make changes as needed for this PR. This way, reviewers can compare what is changing in this PR. You can choose to abondon this PR and create a new one or update the commits on this. This PR has a single commit and 669 files changed. It is impossible to review this currently.
3. Please fix the errors from Swagger LintDiff and Swagger ModelValidation if they are in the scope of this PR.

**Comment by ericshape** [comment]
@ramoka178 it seems the PR description selection is broken. I tried in "edit"/"preview" and choose control plane link, but it cannot work with multiple retries. do we know how we could get the PR description? thanks~

**Comment by ravigautam1896** [comment]
> 1. Please add the template as per [Adding files and folders from previous stable version #29573 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/29573#issue-2372227281)
> 2. Make the first commit with the exact copy of what you have today. In the subsequent commit, make changes as needed for this PR. This way, reviewers can compare what is changing in this PR. You can choose to abondon this PR and create a new one or update the commits on this. This PR has a single commit and 669 files changed. It is impossible to review this currently.
> 3. Please fix the errors from Swagger LintDiff and Swagger ModelValidation if they are in the scope of this PR.

**Comment by ravigautam1896** [comment]
> > 1. Please add the template as per [Adding files and folders from previous stable version #29573 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/29573#issue-2372227281)
> > 2. Make the first commit with the exact copy of what you have today. In the subsequent commit, make changes as needed for this PR. This way, reviewers can compare what is changing in this PR. You can choose to abondon this PR and create a new one or update the commits on this. This PR has a single commit and 669 files changed. It is impossible to review this currently.
> > 3. Please fix the errors from Swagger LintDiff and Swagger ModelValidation if they are in the scope of this PR.

1. I will add the template.
2. The first commit is just copy pasting the folders which were available in the last stable version 2021-11-01 
3. The LintDiff and swagger Model Validation errors are coming from feature teams present in SQL org, and we are infrastructure framework team responsible for releasing preview and stable version, having said that we wanted these validation flags so that we can push the feature team for the fix. we wanted the exception for these errors on this PR.

**Review by pcsin — APPROVED** [review]
:shipit:

As the PR is created against a feature branch. Please make sure to address all lint-diff, and model-validation errors when the PR is raised against `main`

**Comment by ravigautam1896** [comment]
> Can you all fix the PR description before we merge this?

The current PR description is not correct, is it? This is a control Plane PR.

**Comment by TimLovellSmith** [comment]
> > Can you all fix the PR description before we merge this?
> 
> The current PR description is not correct, is it? This is a control Plane PR.

Yes but the form is not filled in, right.

**Comment by ravigautam1896** [comment]
> > > Can you all fix the PR description before we merge this?
> > 
> > 
> > The current PR description is not correct, is it? This is a control Plane PR.
> 
> Yes but the form is not filled in, right.

done now.

**Comment by TimLovellSmith** [comment]
ModelValidation seems to be identifying some actual validation issues. Could you please review them and fix any you can? 
They might be identifying quality issues in your spec or examples.
Like I'm not sure if the additionalProperties is declared correctly here, the validation seems to think it doesn't match the examples?

[I.e. ignoring the errors is just allowing any quality issues to linger. If we aren't taking proper advantage of tools to help achieve quality, the tools are STILL incurring the costs (such as this PR analysis discussion) yet we're not getting the corresponding benefits!]

**Comment by TimLovellSmith** [comment]
> > > 1. Please add the template as per [Adding files and folders from previous stable version #29573 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/29573#issue-2372227281)
> > > 2. Make the first commit with the exact copy of what you have today. In the subsequent commit, make changes as needed for this PR. This way, reviewers can compare what is changing in this PR. You can choose to abondon this PR and create a new one or update the commits on this. This PR has a single commit and 669 files changed. It is impossible to review this currently.
> > > 3. Please fix the errors from Swagger LintDiff and Swagger ModelValidation if they are in the scope of this PR.
> > >    @ramoka178
> 
> 1. added the template.
> 2. The first commit is just copy pasting the folders which were available in the last stable version 2021-11-01
> 3. The LintDiff and swagger Model Validation errors are coming from feature teams present in SQL org, and we are infrastructure framework team responsible for releasing preview and stable version, having said that we wanted these validation flags so that we can push the feature team for the fix. we wanted the exception for these errors on this PR.

How about you loop in folks from those feature teams as needed.

**Comment by ravigautam1896** [comment]
The feature team is working on these model Validation checks and that fix is not part of this PR.

**Review by raosuhas — APPROVED** [review]

**Pull request merged**
