### PR TITLE
Renamed swagger file to ResourceHealthAlerts

### PR DESCRIPTION
**Pull request by giladsu**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by EranGon** [comment]
Please split the files to two:
1. AlertsManagement.json to contain the providers/Microsoft.AlertsManagement/operations API
2. ResourceHealthAlerts.json to contain the rest

**Comment by ArcturusZhang** [comment]
Also could we fix those broken links introduced by this renaming?

**Comment by ArcturusZhang** [comment]
Hi @giladsu if the content of this PR is solely extracting some APIs and related models to a new swagger file, it is totally fine and since the breaking change CI only checks one individual swagger file, in this case, a breaking change CI failure is expected and could be ignored.

But the current state of this PR is hard to review, we do not have a proper approach to compare whether there are any differences between the deleted part in the original swagger file and the new swagger file. Could you please rewrite the commit history of this PR, to make the first commit only contain the extraction of the new swagger and all the following commit contain the changes on the new swagger file? In this way, we could check the actually changes by selecting from the second commit to the latest commit.

**Comment by giladsu** [comment]
Done.

---
In reply to: [707677712](https://github.com/Azure/azure-rest-api-specs/pull/11164#issuecomment-707677712) [](ancestors = 707677712)

**Comment by giladsu** [comment]
Done

---
In reply to: [708877840](https://github.com/Azure/azure-rest-api-specs/pull/11164#issuecomment-708877840) [](ancestors = 708877840)

**Comment by giladsu** [comment]
Thanks @ufo54153@gmail.com.  This PR contains both a file renaming and a resource type renaming (previous resource type was never added to ARM manifest so has no usage).  I've rewritten the history such that the first commit is purely a rename of files, 2nd commit is moving operations API to a dedicated separate file, and then 3rd commit for the actual resource type renaming and file renaming in the swagger.

---
In reply to: [717007946](https://github.com/Azure/azure-rest-api-specs/pull/11164#issuecomment-717007946) [](ancestors = 717007946)

**Review by EranGon — APPROVED** [review]
:shipit:

**Review by majastrz — APPROVED** [review]
The breaking changes that got flagged aren't real. The resource type was never added to the manifest (the PR to add them to the RP manifest is waiting for approval right now). Signed off from ARM side.

**Comment by giladsu** [comment]
@ArcturusZhang what are the next steps for getting this merged.

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @giladsu it seems that the prettier is still not happy, could you please resolve this and then we could merge this PR. Thanks

**Comment by giladsu** [comment]
Hi @ArcturusZhang - fixed prettier error. Thanks.

**Pull request merged**
