### PR TITLE
Iot hub vnet swagger 2020-03-01

### PR DESCRIPTION
**Pull request by jucarpio**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by pilor** [comment]
>         "operationId": "PrivateLinkResources_Get",

Should be _List

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1729 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateLinkResources": {

you also need an individual GET API for a single privateLinkedResource

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1722 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>         }

these should be inside a "properties" object like a normal resource

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2489 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateEndpointConnections/{privateEndpointConnectionName}": {

you are missing a GET collection API that lists all privateEndpointConnections for an iotHub

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1766 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>         "operationId": "PrivateEndpointConnections_Update",

CreateOrUpdate

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1818 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>           "201": {

this should be a 202.  See [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously)

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1904 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>           "200": {

204 should be a valid response if someone attempts to delete a privateEndpointConnection that did not exist

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1910 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Comment by pilor** [comment]
>         },

are these alternates to the connection string?  What if the user provides all 3?

---
Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2678 in fecf163. [](commit_id = fecf163918c9308426ec47f741189f6876c86a41, deletion_comment = False)

**Review by pilor — CHANGES_REQUESTED** [review]
:clock1:

**Comment by jucarpio** [comment]
> > ```
> >     },
> > ```
> 
> are these alternates to the connection string? What if the user provides all 3?
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2678 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

Yes there are an alternative. If someone provides the three values then service validation will show a relevant message. There is no way to add exclusive required params (connectionString or Uri) are mandatory

**Comment by compsri** [comment]
> > ```
> >     "operationId": "PrivateLinkResources_Get",
> > ```
> 
> Should be _List
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1729 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

Although the name suggests it, the return type is not a list. It's an object. This is according to the Network teams spec for PrivateEndpoints.

**Comment by compsri** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateLinkResources": {
> > ```
> 
> you also need an individual GET API for a single privateLinkedResource
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1722 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

Return type is an object and not a list and therefore we cannot support a GET on individual items

**Comment by compsri** [comment]
> > ```
> >     }
> > ```
> 
> these should be inside a "properties" object like a normal resource
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2489 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

If this is referring to the GroupIdInformation object type in the spec, I'm not sure what's wrong with it. Can you elaborate on what you mean?

**Comment by compsri** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateEndpointConnections/{privateEndpointConnectionName}": {
> > ```
> 
> you are missing a GET collection API that lists all privateEndpointConnections for an iotHub
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1766 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

The entire list is returned as part of the top-level IotHub resource. This is according to Network team's spec for PrivateEndpoints and I've also checked a couple of other teams' Swagger spec and they do the same.

**Comment by compsri** [comment]
> > ```
> >     "operationId": "PrivateEndpointConnections_Update",
> > ```
> 
> CreateOrUpdate
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1818 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

This operation only supports Update. Creating a PrivateEndpoint can only be initiated by Network RP.

**Comment by compsri** [comment]
> > ```
> >       "201": {
> > ```
> 
> this should be a 202. See https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1904 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

Fixed in new iteration

**Comment by compsri** [comment]
> > ```
> >       "200": {
> > ```
> 
> 204 should be a valid response if someone attempts to delete a privateEndpointConnection that did not exist
> 
> Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1910 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)

Fixed in new iteration

**Comment by pilor** [comment]
> > > ```
> > >     "operationId": "PrivateLinkResources_Get",
> > > ```
> > 
> > 
> > Should be _List
> > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1729 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> 
> Although the name suggests it, the return type is not a list. It's an object. This is according to the Network teams spec for PrivateEndpoints.

You should have both a LIST and individual GET to comply with the RP contract.  See cosmos DB and SQL for examples.

**Comment by pilor** [comment]
> > > ```
> > > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateEndpointConnections/{privateEndpointConnectionName}": {
> > > ```
> > 
> > 
> > you are missing a GET collection API that lists all privateEndpointConnections for an iotHub
> > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1766 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> 
> The entire list is returned as part of the top-level IotHub resource. This is according to Network team's spec for PrivateEndpoints and I've also checked a couple of other teams' Swagger spec and they do the same.

Any individual resource GET needs a collection GET as well.  Nearly all RPs are correctly implementing the collection GET (do a search through the repo for '/privateEndpointConnections"').  Its unfortunate that Network is having RPs also put the content in the parent as that is an anti-pattern but it got out into the wild before it was caught.

**Comment by pilor** [comment]
> > > ```
> > >     }
> > > ```
> > 
> > 
> > these should be inside a "properties" object like a normal resource
> > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2489 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> 
> If this is referring to the GroupIdInformation object type in the spec, I'm not sure what's wrong with it. Can you elaborate on what you mean?

See the PrivateLinkResource definition in specification\cosmos-db\resource-manager\Microsoft.DocumentDB\preview\2019-08-01-preview\privateLinkResources.json for an example.  Only "id", "name", and "type" should be top level properties in this definition.  Everything else should be in the propertybag

**Review by pilor — CHANGES_REQUESTED** [review]
See comments.

**Comment by erich-wang** [comment]
@jucarpio , please address the comment.

**Comment by jucarpio** [comment]
> @jucarpio , please address the comment.

@erich-wang yes we are working on the comments, some of them require small changes or our service so we need to ensure that goes in first

**Comment by compsri** [comment]
> > > > ```
> > > >     "operationId": "PrivateLinkResources_Get",
> > > > ```
> > > 
> > > 
> > > Should be _List
> > > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1729 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> > 
> > 
> > Although the name suggests it, the return type is not a list. It's an object. This is according to the Network teams spec for PrivateEndpoints.
> 
> You should have both a LIST and individual GET to comply with the RP contract. See cosmos DB and SQL for examples.

Added in new iteration

**Comment by compsri** [comment]
> > > > ```
> > > > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/privateEndpointConnections/{privateEndpointConnectionName}": {
> > > > ```
> > > 
> > > 
> > > you are missing a GET collection API that lists all privateEndpointConnections for an iotHub
> > > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:1766 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> > 
> > 
> > The entire list is returned as part of the top-level IotHub resource. This is according to Network team's spec for PrivateEndpoints and I've also checked a couple of other teams' Swagger spec and they do the same.
> 
> Any individual resource GET needs a collection GET as well. Nearly all RPs are correctly implementing the collection GET (do a search through the repo for '/privateEndpointConnections"'). Its unfortunate that Network is having RPs also put the content in the parent as that is an anti-pattern but it got out into the wild before it was caught.

Added in new iteration

**Comment by compsri** [comment]
> > > > ```
> > > >     }
> > > > ```
> > > 
> > > 
> > > these should be inside a "properties" object like a normal resource
> > > Refers to: specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json:2489 in [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41). [](commit_id = [fecf163](https://github.com/Azure/azure-rest-api-specs/commit/fecf163918c9308426ec47f741189f6876c86a41), deletion_comment = False)
> > 
> > 
> > If this is referring to the GroupIdInformation object type in the spec, I'm not sure what's wrong with it. Can you elaborate on what you mean?
> 
> See the PrivateLinkResource definition in specification\cosmos-db\resource-manager\Microsoft.DocumentDB\preview\2019-08-01-preview\privateLinkResources.json for an example. Only "id", "name", and "type" should be top level properties in this definition. Everything else should be in the propertybag

Fixed in new iteration

**Comment by jucarpio** [comment]
@pilor can you please give a look after we made the requested changes?

**Review by erich-wang — APPROVED** [review]

**Review by KrisBash — APPROVED** [review]
From what I can see, feedback seems addressed for ARM

**Review by pilor — APPROVED** [review]

**Pull request merged**
