### PR TITLE
Review request for Microsoft.RecoveryServices to add version stable/2024-02-01

### PR DESCRIPTION
**Pull request by midhunpramod19**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- For help with Step 2 / "ARM review", see https://aka.ms/azsdk/pr-arm-review.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by raosuhas** [comment]
Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624

**Comment by midhunpramod19** [comment]
> Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624

Have resolved all link errors, could not resolve the last linting error([AvoidAdditionalProperties](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)) as we are inheriting an existing model. The existing model has the additionProperties field in it. What is the guidance to fix this? As it is already existing and we just inherited it.

**Comment by visingla-ms** [comment]
Please fix all the issues like Linter errors, Model Validation errors, Breaking changes etc. in your PR here.

**Comment by midhunpramod19** [comment]
> > Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624
> 
> Have resolved all link errors, could not resolve the last linting error([AvoidAdditionalProperties](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)) as we are inheriting an existing model. The existing model has the additionProperties field in it. What is the guidance to fix this? As it is already existing and we just inherited it.

Have fixed all issues except this. Need guidance on this.

**Comment by visingla-ms** [comment]
> > > Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624
> > 
> > 
> > Have resolved all link errors, could not resolve the last linting error([AvoidAdditionalProperties](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)) as we are inheriting an existing model. The existing model has the additionProperties field in it. What is the guidance to fix this? As it is already existing and we just inherited it.
> 
> Have fixed all issues except this. Need guidance on this.

Got it. Please apply for suppression for this particular one. See Additional information section above in this PR.

**Comment by visingla-ms** [comment]
>             "type": "string"

Are these VM nodes? If yes, please use [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details) here.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:9516 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "string"

Use [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details) here if it is an ARM Resource.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:9547 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             "type": "string"

Use [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details) here if it is an ARM Resource.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:9553 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "string",

Why is it not enum then?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11177 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "string",

Should this be an array here?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11187 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "string"

Should this be an enum here?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:12022 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "ClusterRecoveryPoint": {

Please use the definition of resource from here: [https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json), instead of defining all properties here.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:12390 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "recoveryPointType": {

Use enum here.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:12438 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by visingla-ms** [comment]
>       "properties": {

Same here, use TrackedResource or ProxyResource definition from common types.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:23689 in 845372a. [](commit_id = 845372a7ce28f2989aefddd8704343449fce7a10, deletion_comment = False)

**Comment by midhunpramod19** [comment]
> > ```
> > "ClusterRecoveryPoint": {
> > ```
> 
> [ARMBlockingComment] Please use the definition of resource from here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json, instead of defining all properties here.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:12390 in [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10). [](commit_id = [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10), deletion_comment = False)

Our service is currently not returning SystemData field defined in the proxy resource definition. So, we cannot use this definition.

**Comment by midhunpramod19** [comment]
> > ```
> >       "type": "string",
> > ```
> 
> Why is it not enum then?
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11177 in [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10). [](commit_id = [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10), deletion_comment = False)

These errors are thrown by other microservices, there are multiple errors which can be thrown. The management service does not keep track of them and returns these error codes as string.

**Comment by midhunpramod19** [comment]
> > ```
> >       "type": "string",
> > ```
> 
> Should this be an array here?
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11187 in [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10). [](commit_id = [845372a](https://github.com/Azure/azure-rest-api-specs/commit/845372a7ce28f2989aefddd8704343449fce7a10), deletion_comment = False)

No this is a string, Service returns a single string with all possible causes.

**Comment by midhunpramod19** [comment]
> > > > Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624
> > > 
> > > 
> > > Have resolved all link errors, could not resolve the last linting error([AvoidAdditionalProperties](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)) as we are inheriting an existing model. The existing model has the additionProperties field in it. What is the guidance to fix this? As it is already existing and we just inherited it.
> > 
> > 
> > Have fixed all issues except this. Need guidance on this.
> 
> Got it. Please apply for suppression for this particular one. See Additional information section above in this PR.

image

It mentions to ask the PR assignee to apply the suppression.

**Comment by tarsharm** [comment]
The PR has multiple LintDiff errors, can you fix them first before starting the review.

**Comment by midhunpramod19** [comment]
> > Can you please fix the newly introduced Lint errors here : https://github.com/Azure/azure-rest-api-specs/pull/27514/checks?check_run_id=20809370624
> 
> Have resolved all link errors, could not resolve the last linting error([AvoidAdditionalProperties](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)) as we are inheriting an existing model. The existing model has the additionProperties field in it. What is the guidance to fix this? As it is already existing and we just inherited it.

Need to suppress the lint diff error as already explained above. Not sure what is failing in the Swagger SDK breaking change error. Need guidance on how to fix these.

**Comment by venu-sivanadham** [comment]
>             "name": "resourceName",

I could see A parameter is defined for {resourceName} below. why can't you refer the parameter instead of defining like this every time ?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4564 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>               "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse"

consider moving to latest common-types i.e v5

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4605 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           }

you can define them as parameters in once place and ref  them where ever needed, instead of defining them every time like this.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4593 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>         "x-ms-long-running-operation": true,

add below extension for the LRO operations

"x-ms-long-running-operation-options": {
  "final-state-via": "location"
}

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4954 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           },

operation results 

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:5122 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationProtectionClusters": {

This seems to be an anti-pattern for resource List implementation.

You are trying to implement level-4 nexted resource list call at level-2 by trimming its parent resources in the URI.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:8024 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>       ],

"instanceType" already mentioned as required in ApplyClusterRecoveryPointProviderSpecificInput, no need to mention it here again.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:9482 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           "type": "array",

add "x-ms-identifier" extension, and include the property name that uniquely identifies the object in array

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:10287 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           "x-ms-identifiers": []

specify one of the A2AUnprotectedDiskDetails property that can uniquely identify the object in array. For example,

"x-ms-identifiers": ["diskLunId"]

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11239 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           "x-ms-identifiers": []

specify the identifier property name here.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:11247 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>           "type": "array",

missing x-ms-identifier is missing at multiple places, fix it for all the array properties being added in this PR.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:12409 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>         "recoveryFabricId": {

define the format as arm-id

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:23816 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by venu-sivanadham** [comment]
>     "ServiceDefaultError": {

same definition is available in common-types "ErrorDetail"
you can re-use it.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:24494 in abc63ae. [](commit_id = abc63aef6c2ac8040addc3276f2d70f84fef505e, deletion_comment = False)

**Comment by midhunpramod19** [comment]
> > ```
> >       },
> > ```
> 
> refer the guidelines for operation results.
> 
> https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#202-accepted-and-location-headers
> 
> you can also refer other RPs operation results implementation for tracking LRO operations.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:5122 in [a5f8db8](https://github.com/Azure/azure-rest-api-specs/commit/a5f8db88e71edb888c21fb90410697f22562ff60). [](commit_id = [a5f8db8](https://github.com/Azure/azure-rest-api-specs/commit/a5f8db88e71edb888c21fb90410697f22562ff60), deletion_comment = False)

Can you specify what needs to be changed here?

**Comment by midhunpramod19** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationProtectionClusters": {
> > ```
> 
> This seems to be an anti-pattern for resource List implementation.
> 
> You are trying to implement level-4 nested resource list call at level-2 by trimming its parent resources in the URI.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:8024 in [a5f8db8](https://github.com/Azure/azure-rest-api-specs/commit/a5f8db88e71edb888c21fb90410697f22562ff60). [](commit_id = [a5f8db8](https://github.com/Azure/azure-rest-api-specs/commit/a5f8db88e71edb888c21fb90410697f22562ff60), deletion_comment = False)

We want an API that lists all replicationProtectionClusters at a vault level, hence created a list API at vault level.

**Comment by midhunpramod19** [comment]
> > ```
> > "ServiceDefaultError": {
> > ```
> 
> same definition is available in common-types "ErrorDetail" you can re-use it.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:24494 in [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e). [](commit_id = [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e), deletion_comment = False)

This is not introduced in this PR, this definition exists in the swagger from before.

**Comment by midhunpramod19** [comment]
Please ignore the breaking change errors, all errors except the current linting errors will be resolved when we raise a new PR with the latest base version

**Comment by venu-sivanadham** [comment]
> > > ```
> > >         "name": "resourceName",
> > > ```
> > 
> > 
> > I could see A parameter is defined for {resourceName} below. why can't you refer the parameter instead of defining like this every time ?
> > Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4564 in [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e). [](commit_id = [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e), deletion_comment = False)
> 
> The ResourceName param defined does not have pattern defined for it, due to which we were getting linting errors if we referred it. And we cannot add pattern in the defined param as it will be a breaking change

You can provide the justification and get the breaking change approval for adding the patten in common parameter. 
The practice of defining pattern in one API and not having pattern in another API for same resource will lead to inconsistencies and also increases your swagger footprint.

**Comment by venu-sivanadham** [comment]
> > > ```
> > > "ServiceDefaultError": {
> > > ```
> > 
> > 
> > same definition is available in common-types "ErrorDetail" you can re-use it.
> > Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:24494 in [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e). [](commit_id = [abc63ae](https://github.com/Azure/azure-rest-api-specs/commit/abc63aef6c2ac8040addc3276f2d70f84fef505e), deletion_comment = False)
> 
> This is not introduced in this PR, this definition exists in the swagger from before.

I

**Comment by viveksheelsingh** [comment]
>         "responses": {

pl add 200 case for sync deletion

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4771 in 08922b0. [](commit_id = 08922b0f0aafa14d8d0efe330bf6cd02a5bafc81, deletion_comment = False)

**Comment by midhunpramod19** [comment]
> > ```
> >     "responses": {
> > ```
> 
> pl add 200 case for sync deletion
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2024-02-01/service.json:4771 in [08922b0](https://github.com/Azure/azure-rest-api-specs/commit/08922b0f0aafa14d8d0efe330bf6cd02a5bafc81). [](commit_id = [08922b0](https://github.com/Azure/azure-rest-api-specs/commit/08922b0f0aafa14d8d0efe330bf6cd02a5bafc81), deletion_comment = False)

This is a LRO delete operation. We will not be returning 200

**Pull request closed without merging**
