### PR TITLE
Bump node azure-servicefabric version to 2.0.1

### PR DESCRIPTION
**Pull request by RikkiGibson**
This should resolve the issue where we generated an incorrect GitHub link.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@autorestci rebuild azure-sdk-for-node

**Comment by dsgouda** [comment]
@amarzavery Can you take a look or reassign it someone from the Node SDK team

**Comment by RikkiGibson** [comment]
Sorry for any inconvenience :)

**Comment by RikkiGibson** [comment]
@autorestci regenerate azure-sdk-for-node

**Comment by RikkiGibson** [comment]
@AutorestCI regenerate azure-sdk-for-node

**Pull request closed without merging**
