### PR TITLE
Remove the minimum number for the option field requestBodyInspectLimitInKB

### PR DESCRIPTION
**Pull request by baoqihuang0326**
Remove the minimum value for optional field "requestBodyInspectLimitInKB". There is no breaking change introduced.

### CODE REVIEW

**Comment by keryul** [comment]
@baoqihuang0326 can you fix ModelValidation error and SemanticValidation error

**Comment by baoqihuang0326** [comment]
@keryul There is no breaking change here. This is just for removing the minimum number of an optional field which will unblock the PowerShell test.

**Comment by baoqihuang0326** [comment]
@keryul  validations passed now.

**Comment by keryul** [comment]
Breaking change isn't caused by this PR change.

**Review by ankhyk — APPROVED** [review]

**Comment by keryul** [comment]
@MikhailTryakhov can we merge it?

**Pull request merged**
