### PR TITLE
Fix checkPirvateLinkServiceVisibility in 2020-06-01

### PR DESCRIPTION
**Pull request by 00Kai0**
fix 202 in new release, #9800

### CODE REVIEW

**Comment by lirenhe** [comment]
@00Kai0, could you take a look at the check errors?

**Review by anton-evseev — APPROVED** [review]
Please ignore `NetworkValidation`

**Comment by ravbhatnagar** [comment]
Looks like a new response code (202) is being added to existing api/api-versions like 2019 versions. This is a breaking change and should only be made in a new api-version

**Comment by number213** [comment]
@ravbhatnagar this PR targets a separate branch for new API version that's going to be merged into master in July

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
As this change happens in a separate branch, this is not a breaking change so merge this PR.

**Pull request merged**
