### PR TITLE
apimanagement: flattening `document` to a proper object

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR fixes a regression in the API Management version 2019-01-01 where the field was a concrete type in the previous API version (2018-01-01), but now returns a dictionary, which makes this field less usable:

https://github.com/Azure/azure-sdk-for-go/blob/v29.0.0/services/apimanagement/mgmt/2018-01-01/apimanagement/models.go#L8710

https://github.com/Azure/azure-sdk-for-go/blob/v29.0.0/services/apimanagement/mgmt/2019-01-01/apimanagement/models.go#L9269

---

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
I'm running our test suite for API Management against the generated Go SDK to confirm this works as expected 👍

**Comment by tombuildsstuff** [comment]
I can confirm this fix fixes our broken acceptance tests (when using this commit, rather than `v29.0.0` of the Go SDK):

Screenshot 2019-05-23 at 10 17 34

**Review by solankisamir — CHANGES_REQUESTED** [review]
No, it has to be an object. When exporting swagger document scheme, it is json object, but when exporting wsdl schema, it is document.value property which contains the xml schema

**Comment by solankisamir** [comment]
Please refer to [code](https://github.com/Azure/azure-powershell/blob/8f091dabbf146f1ffc2c39795ab13618a5b66a88/src/ApiManagement/ApiManagement.ServiceManagement/Helpers/Utils.cs#L390) which will explain it to you. We will need to do something similar in the terraform sdk.

**Comment by tombuildsstuff** [comment]
@solankisamir so then shouldn't the Swagger be updated to use a [Discriminator](https://swagger.io/specification/#discriminatorObject) to expose the correct objects?

**Comment by dsgouda** [comment]
@solankisamir gentle ping

**Comment by amarzavery** [comment]
@solankisamir - Any updates on this?

**Comment by solankisamir** [comment]
@amarzavery @dsgouda I believe the autorest generator cannot generate .NET and other clients when using `anyOf` construct. That is the reason why I am against merging this PR. I have already shown @tombuildsstuff way we are handling responses in different clients.

**Comment by tombuildsstuff** [comment]
@solankisamir I might be wrong, but it seems to generate fine for other Resource Providers?

For example the following Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/stable/2016-03-01/inputs.json#L733-L792

generates the following C#/.net SDK:

https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/StreamAnalytics/Management.StreamAnalytics/Generated/Models/Serialization.cs#L20-L37
https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/StreamAnalytics/Management.StreamAnalytics/Generated/Models/JsonSerialization.cs#L23-L70

which also generates the following Go SDK structs:

https://github.com/Azure/azure-sdk-for-go/blob/master/services/streamanalytics/mgmt/2016-03-01/streamanalytics/models.go#L300-L305
https://github.com/Azure/azure-sdk-for-go/blob/master/services/streamanalytics/mgmt/2016-03-01/streamanalytics/models.go#L2867-L2872

and this conversion helper: https://github.com/Azure/azure-sdk-for-go/blob/master/services/streamanalytics/mgmt/2016-03-01/streamanalytics/models.go#L4071-L4076

As such I believe it should be possible to take this same approach here - WDYT?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @solankisamir

**Comment by solankisamir** [comment]
As discussed with autorest sdk team `x-ms-discriminator` will not resolve this issue. It was meant to be used for polymorphism case. But the response of this contract is 

`application/vnd.ms-azure-apim.swagger.definitions+json`
```
{
   "properties" : {
    "contentType": "application/vnd.ms-azure-apim.swagger.definitions+json",
    "document" : "json schema here"
    }
}
```

But for `application/vnd.ms-azure-apim.xsd+xml` or `application/vnd.oai.openapi.components+json` or `application/vnd.ms-azure-apim.wadl.grammars+xml`

```
{
   "properties" : {
    "contentType": "application/vnd.ms-azure-apim.swagger.definitions+json",
    "document" : {
          "value" : "api schema here"
         }
    }
}
```

I agree this is a weirdness in the API and I have opened an issue https://github.com/Azure/azure-rest-api-specs/issues/6372 to fix this in the next version of the API

**Comment by tombuildsstuff** [comment]
@solankisamir thanks for confirming; is there a (rough) timeframe for the next version of the API being available containing the fix?

@jhendrixMSFT since this API is going to require custom code to support it properly,  whilst we can add this to Terraform - since this affects any consumers, would it make sense for the Go SDK to handle this?

**Comment by yungezz** [comment]
hi @tombuildsstuff  @chlahav can we close the PR for now since it's not ready for review and merge,  the PR is over several months. Pls create new PR when you're ready for review and merge.

**Comment by yungezz** [comment]
Hi @tombuildsstuff @chlahav , the PR will be closed in 2 days since no update. Pls let us know if any comments.

**Pull request closed without merging**
