### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to clean up 2019-11-01-preview (under "window to fix broken")

### PR DESCRIPTION
**Pull request by TomMilos**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/TomMilos/azure-rest-api-specs/monitor%2FdataCollectionRules%2F2019-11-01%2Fcleanup...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [x] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TomMilos** [comment]
This PR includes some breaking changes to the preview API under the "Window to fix broken". The concrete list of changes includes:
1. Unmarking properties as required
2. Removing restrictions on properties (length, range, regex)
3. Switching from custom definition (e.g. ErrorResponse) and parameters to the ones defined in common-types
4. Adding properties that were not in Swagger but were being populated (workspaceId, immutableId, kind, inputDataSources)
5. Removing (extensible) enum values that are not supported yet
6. Changing one (extensible) enum value to lowercase per Linux convention (UUCP) 

Note that the service will still support payloads which use the values previously defined in the API schema and it will not break any existing data flows. This cleanup is in preparation for the first stable API release planned in coming months

**Comment by TomMilos** [comment]
@weidongxu-microsoft as the window to fix broken is coming to a close I'd appreciate quick feedback on these changes. Thanks

**Comment by weidongxu-microsoft** [comment]
This is pretty large PR with lots of breaking changes, you would need to have approval from JeffreyRichter.

@ArcturusZhang @jsntcy @msyyc Any concern on Go and Python break changes?

**Comment by TomMilos** [comment]
> This is pretty large PR with lots of breaking changes, you would need to have approval from JeffreyRichter.
@weidongxu-microsoft based on the offline thread it looks like @JeffreyRichter is OK with this change

**Comment by weidongxu-microsoft** [comment]
@TomMilos 
Yes, make sense. It seems this 2 json is never in GA version.

BTW, when it is GAed, will this 2 json be added to other 10+ jsons? If so, there might be more naming conflict when you merge them, that could be hard to handle.

**Comment by weidongxu-microsoft** [comment]
Quote Jeffrey Richter 

> In the “Window to fix broken”, we’ll accept any and all swagger changes that make the swagger more accurately reflect the actual service behavior.
> If the service doesn’t support scheduledTransferPeriod, then it should be removed from the swagger because the current swagger just never worked for the customer anyway. We’ve had a lot of these: things in the swagger that the service doesn’t support.
> 
> In addition, if the service never GA’d, we’re very lenient in changing the swagger as customers should already have the expectation that things will break during preview.

**Comment by weidongxu-microsoft** [comment]
@ArcturusZhang @jsntcy @msyyc Any concern on Go and Python break changes?

**Comment by TomMilos** [comment]
> BTW, when it is GAed, will this 2 json be added to other 10+ jsons (e.g. thoses under package-2020-03)? If so, there might be more naming conflict when you merge them, that could be hard to handle.

@weidongxu-microsoft yes, we'd want to do that. I just tried generating that and I do see conflicts, however the problem is broader as there are inconsistencies across other swaggers - e.g. some use ```ErrorResponse``` and some ```ErrorResponseCommon``` class. I think we'd want to clean it up but I think that would be a breaking change for SDK? Are we stuck with this?

Regardless, for our swagger we want to leave the full ErrorResponse definition as it accurately represents what the service returns so we want that to be documented. For SDK generation we may want to resolve conflict manually and settle for using one of the existing classes (even if it is missing some of the properties)

**Comment by TomMilos** [comment]
@weidongxu-microsoft @ArcturusZhang @jsntcy @msyyc - can we move forward with this?

**Comment by weidongxu-microsoft** [comment]
@TomMilos Ok. Let me know when you need it merged.

**Review by weidongxu-microsoft — APPROVED** [review]

**Pull request merged**
