### PR TITLE
Add specs for Network 2019-07-01

### PR DESCRIPTION
**Pull request by anton-evseev**
Copied Network specs from 2019-06-01 to 2019-07-01

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
Avocado fails with `The JSON file has a circular reference`, I haven't seen those errors before, are those new checks?
Also, this PR seems to remove Avocado from pipeline config: https://github.com/Azure/azure-rest-api-specs/pull/6978

**Comment by nschonni** [comment]
The PR is because there are 2 duplicate Avocado runs since https://github.com/Azure/azure-rest-api-specs/pull/6887
0.5.0 added the circular reference checking https://github.com/Azure/avocado/blob/master/CHANGELOG.md#050

**Comment by number213** [comment]
@nschonni strange we didn't see this error earlier. I'll investigate and see if we can fix that without introducing breaking changes.
Meanwhile, is there a way to temporary suppress this type of error?

**Comment by nschonni** [comment]
I'm not sure. You might need to open an issue on that repo to see if there is a suppression method for that. I think the suppression usually happens in the README, but I don't know how that works

**Comment by zikalino** [comment]
@number213 is it an exact copy of 2019-06-01 or are there any additional changes?

**Comment by number213** [comment]
@zikalino it's a copy of 2019-06-01 plus description update from https://github.com/Azure/azure-rest-api-specs/pull/6974

**Pull request closed without merging**
