### PR TITLE
[Hub Generated] Review request for Microsoft.DataProtection to add version preview/2023-06-01-preview

### PR DESCRIPTION
**Pull request by jeevan-gaikwad**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/jeevan-gaikwad-dataprotection-Microsoft.DataProtection-2023-06-01-preview-cmk...main/).
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jeevan-gaikwad** [comment]
This PR is created on top of existing approved PR [https://github.com/Azure/azure-rest-api-specs/pull/22359](https://github.com/Azure/azure-rest-api-specs/pull/22359) with **new api-version 2023-06-01-preview**. We're also rolling out our resource provider Backup Vault manifest with this version. Added DoNotMerge label.

**Comment by kazrael2119** [comment]
this js sdk breaking change is not caused by this pr

**Comment by jeevan-gaikwad** [comment]
Synced with previous stable version 2023-05-01. 
Base of this PR is 2023-04-01-preview hence sync with stable version 2023-05-01 also showing it as diff against main.
PR was approved by ARM team. Please review commits range: [https://github.com/Azure/azure-rest-api-specs/pull/24388/files/0d73ef4b828b72ea468a51b2bd79a90896926d2d..7a56adbf92c894faf50f54b743bdad39f83c715a](https://github.com/Azure/azure-rest-api-specs/pull/24388/files/0d73ef4b828b72ea468a51b2bd79a90896926d2d..7a56adbf92c894faf50f54b743bdad39f83c715a)

**Comment by visingla-ms** [comment]
>           "type": "string"

Should this be an enum?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:4090 in c5829d7. [](commit_id = c5829d709e41246de2737ddfbfa406e23cd561cc, deletion_comment = False)

**Review by amchandn — APPROVED** [review]

**Comment by jeevan-gaikwad** [comment]
> > ```
> > },
> > ```
> 
> Why are these operations being removed? Wouldn't these cause breaking changes to existing customers?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:1530 in [0d73ef4](https://github.com/Azure/azure-rest-api-specs/commit/0d73ef4b828b72ea468a51b2bd79a90896926d2d). [](commit_id = [0d73ef4](https://github.com/Azure/azure-rest-api-specs/commit/0d73ef4b828b72ea468a51b2bd79a90896926d2d), deletion_comment = True)

Mistakenly I had removed APIs from previous preview version 2023-04-01-preview, now added back.

**Comment by jeevan-gaikwad** [comment]
> > ```
> >       "type": "string"
> > ```
> 
> Should this be an enum?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:4090 in [c5829d7](https://github.com/Azure/azure-rest-api-specs/commit/c5829d709e41246de2737ddfbfa406e23cd561cc). [](commit_id = [c5829d7](https://github.com/Azure/azure-rest-api-specs/commit/c5829d709e41246de2737ddfbfa406e23cd561cc), deletion_comment = False)

I had removed changes from previous preview version 2023-04-01-preview, now added back and considered stable version 2023-05-01 as base.

**Comment by jeevan-gaikwad** [comment]
This PR is to introduce Encryption Settings(a.k.a CMK). This is public PR. Private repo PR is already approved [https://github.com/Azure/azure-rest-api-specs/pull/22359 with new api-version 2023-06-01-preview](url)

**Comment by jeevan-gaikwad** [comment]
Please look at this commit range to review delta(Encryption Settings for Backup vault resource) easily:
[https://github.com/Azure/azure-rest-api-specs/pull/24388/files/0ef66795af66cdd0c271d30705261b30d8f08f40..7a56adbf92c894faf50f54b743bdad39f83c715a#diff-e01730bef05f078dea17a81543f32433fd6a0abc15286484fb43dde0b93505b6](url)

**Comment by jeevan-gaikwad** [comment]
For these two failures, BaseResourceProperties is already present in stable version 2023-05-01 and this object is not part of this PR.
So, we can add the below labels.
 Approved-SdkBreakingChange-Go
 Approved-SdkBreakingChange-Python

**Comment by visingla-ms** [comment]
>           "$ref": "#/definitions/BaseResourceProperties",

I didn't understand the purpose of this field? What is being added as part of resourceProperties? I already see an objectType and resourceType fields here?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:5756 in e4a92d6. [](commit_id = e4a92d651f15314847948b40d81ca7f8e31f9d95, deletion_comment = False)

**Comment by jeevan-gaikwad** [comment]
> > ```
> >       "$ref": "#/definitions/BaseResourceProperties",
> > ```
> 
> I didn't understand the purpose of this field? What is being added as part of resourceProperties? I already see an objectType and resourceType fields here?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:5756 in [e4a92d6](https://github.com/Azure/azure-rest-api-specs/commit/e4a92d651f15314847948b40d81ca7f8e31f9d95). [](commit_id = [e4a92d6](https://github.com/Azure/azure-rest-api-specs/commit/e4a92d651f15314847948b40d81ca7f8e31f9d95), deletion_comment = False)

This change is part of stable API version
[https://github.com/Azure/azure-rest-api-specs/blob/c5829d709e41246de2737ddfbfa406e23cd561cc/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/**2023-05-01**/dataprotection.json](https://github.com/Azure/azure-rest-api-specs/blob/c5829d709e41246de2737ddfbfa406e23cd561cc/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2023-05-01/dataprotection.json)
So not sure why it was added.

**Comment by jeevan-gaikwad** [comment]
> > ```
> >       "type": "string"
> > ```
> 
> Please respond to this comment.
> 
> In reply to: [1728095105](https://github.com/Azure/azure-rest-api-specs/pull/24388#issuecomment-1728095105)
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2023-06-01-preview/dataprotection.json:4090 in [c5829d7](https://github.com/Azure/azure-rest-api-specs/commit/c5829d709e41246de2737ddfbfa406e23cd561cc). [](commit_id = [c5829d7](https://github.com/Azure/azure-rest-api-specs/commit/c5829d709e41246de2737ddfbfa406e23cd561cc), deletion_comment = False)

This change is also part of stable API version 2023-05-01
image

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2023-05-01/dataprotection.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2023-05-01/dataprotection.json)

**Comment by jeevan-gaikwad** [comment]
@rkmanda please guide about the following required labels:
image

**Review by visingla-ms — APPROVED** [review]

**Pull request merged**
