### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerRegistry to add version preview/2023-01-01-preview

### PR DESCRIPTION
**Pull request by AntonioVT**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/AntonioVT/azure-rest-api-specs/dev-containerregistry-Microsoft.ContainerRegistry-2023-01-01-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
**A: Deploy feature in canary regions by end of November 2022. Deploy feature in all public regions by Jan 2023.**

  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
**A: End of November 2022**

  5. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.
**A: This PR is for review only, please do NOT merge or automatically refresh the SDKs yet.**

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by visingla-ms** [comment]
>         "operationId": "CacheRules_GetAsync",

Why "_GetAsync" where the Get is never async?

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:69 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           },

You should use these standard types like SubscriptionIdParameter, ResourceGroupNameParameter, ApiVersionParameter, LocationNameParameter etc. from common-types. See: [https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json).

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:34 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true

Add "x-ms-long-running-operation-options": {
          "final-state-via": "location"
        }.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:286 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>               "$ref": "#/definitions/CacheRule"

You can add "Azure-AsyncOperation" in "headers" of 201 response.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:149 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true

You can add "Location" in "x-ms-long-running-operation-options" here.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:606 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>               "$ref": "#/definitions/CredentialSet"

You can add "Azure-AsyncOperation" in "headers" here in 201 response.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:740 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             },

202 is async response. It should not have response schema. Only 200 should return it.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:858 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true

You can add "Location" in "x-ms-long-running-operation-options" here.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:877 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             },

202 is async response. It should not have response schema. Only 200 should return it.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:267 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true

You can add "Location" in "x-ms-long-running-operation-options" here.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:1141 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             }

You can add "Azure-AsyncOperation" in "headers" here in 201 response.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:1753 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true

You can add "Location" in "x-ms-long-running-operation-options" here.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3102 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "array",

You should "m-ms-identifiers" for the arrays. See: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-identifiers](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-identifiers). It actually helps in identifying what is the unique property of items in that array.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3469 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "type": "array",

You should "m-ms-identifiers" for the arrays. See: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-identifiers](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-identifiers). It actually helps in identifying what is the unique property of items in that array.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3617 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "#/definitions/ProxyResource"

You should use ProxyResource type from common-types: [https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json).

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3633 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         },

See if you need to use "x-ms-secret" for username and password string types. See: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret).

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:4208 in c1e346c. [](commit_id = c1e346c5d07aa1ae3da17058f330c913ec286e29, deletion_comment = False)

**Comment by visingla-ms** [comment]
Also check a couple of linter errors mentioning"[XmsLongRunningOperationOptions](https://github.com/Azure/azure-openapi-validator/blob/main/docs/xms-long-running-operation-options.md)".

**Comment by AntonioVT** [comment]
> > ```
> >         },
> > ```
> 
> 202 is async response. It should not have response schema. Only 200 should return it.
> 
> Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:267 in [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29). [](commit_id = [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29), deletion_comment = False)

We are returning 202 on PATCH operations on a proxy resource. When you update a proxy resource, the provisioning status will change to "Updating". We have a schema because the API returns the proxy resource properties, updated provisioning status, as well as the Location/Azure-AsyncOperation link in the headers to track the operation.

I see this pattern in other services as well. I think not returning it would be a breaking change for existing APIs and new APIs wouldn't be consistent. Is this not the expected behavior?

> > ```
> >       "type": "array",
> > ```
> 
> You should "m-ms-identifiers" for the arrays. See: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-identifiers. It actually helps in identifying what is the unique property of items in that array.
> 
> Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3469 in [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29). [](commit_id = [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29), deletion_comment = False)

The array in those scenarios is related to listing proxy resources. All proxy resources have the "id" property. According to doc [x-ms-identifiers](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-identifiers), _"The default identifying property is id. You don't need to add this annotataion if there is the id property in the object model."_ 

Therefore, we didn't include this annotation. Let me know if the documentation is not up to date and I'll include "id" in the array identifiers.

> > ```
> > "ExportPipelineListResult": {
> > ```
> 
> Why definitions/types such as ExportPipelineListResult are deleted. i didn't see any resource operations being deleted in this swagger spec, only new operations being added. Were these not used earlier?
> 
> Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:3255 in [e6e9992](https://github.com/Azure/azure-rest-api-specs/commit/e6e9992d127d635fcb1fe867c1edae2d42b0e368). [](commit_id = [e6e9992](https://github.com/Azure/azure-rest-api-specs/commit/e6e9992d127d635fcb1fe867c1edae2d42b0e368), deletion_comment = True)

Definition/types such as ExportPipelineListResult haven't been deleted, they do exist. I believe Git and our swagger generation tool are not working nicely. The definitions/types might have moved from one line # to another, but they haven't been changed. 

To clarify, this Preview API version **does not** delete any existing feature, we are just **adding new features** such as Cache Rules and Credential Sets APIs.

> > ```
> >     },
> > ```
> 
> See if you need to use "x-ms-secret" for username and password string types. See: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret.
> 
> Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2023-01-01-preview/containerregistry.json:4208 in [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29). [](commit_id = [c1e346c](https://github.com/Azure/azure-rest-api-specs/commit/c1e346c5d07aa1ae3da17058f330c913ec286e29), deletion_comment = False)

The values of these fields are not technically secrets. It's not sensitive data, such as a password/key/username, but they are references to a keyvault secret uri (ie: https://myvault.vault.azure.net/secrets/mysecret). I don't think this applies to our scenario, but let me know if you think otherwise.

--

Thanks for the feedback! I'll be waiting for your response.

**Comment by AntonioVT** [comment]
I have reviewed the failed pipelines, here's my analysis.

Breaking Change(Cross-Version). on the left it's the failed rule, on the right the reason:

- **RemovedDefinition**: Removed SystemData, this definition is already referenced by "Resource" definition in types.json
- **RemovedClientParameter**: Removed ResourceGroupParameter, this definition exists in types.json -- We used "ResourceGroupParameter" and now we would use "ResourceGroup**Name**Parameter".
- **TypeFormatChanged**: References changed to ../.../types.json#/definition/... or ../.../types.json#/parameter/...
- **RemovedProperty**: Locations and tags _seems_ to be removed, however these properties are already defined in TrackResource under types.json
-  XmsEnumChanged: (?) Seems that types.json lastModifiedByType / x-ms-enum is incorrectly defined. Name is "createdByType", but it could be wrong and it should be "lastModifiedByType".

**Comment by visingla-ms** [comment]
> We are returning 202 on PATCH operations on a proxy resource. When you update a proxy resource, the provisioning status will change to "Updating". We have a schema because the API returns the proxy resource properties, updated provisioning status, as well as the Location/Azure-AsyncOperation link in the headers to track the operation.
I see this pattern in other services as well. I think not returning it would be a breaking change for existing APIs and new APIs wouldn't be consistent. Is this not the expected behavior?

I checked your existing APIs, and they are using 201 + response body, instead of 202 + response body. As per ARM RPC, 202 + no response body + location headers, is the guidance.

However, if you want to avoid stepping away from your existing APIs behavior, then, you can use 201 + response body, instead of introducing a new pattern of 202 + response body.

**Comment by AntonioVT** [comment]
> > We are returning 202 on PATCH operations on a proxy resource. When you update a proxy resource, the provisioning status will change to "Updating". We have a schema because the API returns the proxy resource properties, updated provisioning status, as well as the Location/Azure-AsyncOperation link in the headers to track the operation.
> > I see this pattern in other services as well. I think not returning it would be a breaking change for existing APIs and new APIs wouldn't be consistent. Is this not the expected behavior?
> 
> I checked your existing APIs, and they are using 201 + response body, instead of 202 + response body. As per ARM RPC, 202 + no response body + location headers, is the guidance.
> 
> However, if you want to avoid stepping away from your existing APIs behavior, then, you can use 201 + response body, instead of introducing a new pattern of 202 + response body.

I have reverted those changes. We are using the same existing API behavior, use 201 + response body for cache rule / cred set patch.

**Comment by AntonioVT** [comment]
@visingla-ms One thing I noticed is that our swagger had a parameter definition "ResourceGroupParameter". In this PR, I'm using the shared type, which is called "ResourceGroupNameParameter". **Is this considered a breaking change?**

The content of the definitions are almost similar, with the exception that ResourceGroupNameParameter has a `maxLength` property and the `description` property value is different (we had: _"The name of the resource group to which the container registry belongs."_ and the one from types.json is _"The name of the resource group. The name is case insensitive."_

I don't think this would be a breaking change, but would like to confirm with you. Thanks!

**Comment by sjanamma** [comment]
> @visingla-ms One thing I noticed is that our swagger had a parameter definition "ResourceGroupParameter". In this PR, I'm using the shared type, which is called "ResourceGroupNameParameter". **Is this considered a breaking change?**
> 
> The content of the definitions are almost similar, with the exception that ResourceGroupNameParameter has a `maxLength` property and the `description` property value is different (we had: _"The name of the resource group to which the container registry belongs."_ and the one from types.json is _"The name of the resource group. The name is case insensitive."_
> 
> I don't think this would be a breaking change, but would like to confirm with you. Thanks!

Not a breaking change

**Comment by fengzhou-msft** [comment]
@AntonioVT please resolve the conflicts and take a look at the LintDiff error.

**Comment by jaysterp** [comment]
@fengzhou-msft @visingla-ms with regards to the error
image

updating this PATCH body would result in a breaking change since these APIs have been available to customers since the `2020-11-01-preview` version. Can we get an exception?

**Comment by jaysterp** [comment]
@fengzhou-msft @visingla-ms with regard to these errors 
image

`exportPipeline` and `importPipeline` are incorrectly flagged as tracked resources. These are both proxy resources. Since they are enabled with Managed Identity, `properties.Location` is required. Please see more information in the [ARM wiki](https://armwiki.azurewebsites.net/authorization/managed_identities/MSIOnboardingProxyResource.html#other-notes). Please update this pipeline so that these MI-enabled proxy resources are not flagged as tracked.

**Comment by AntonioVT** [comment]
@fengzhou-msft Gentle ping regarding the clarifications/asks above. Thanks!

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft @visingla-ms with regard to these errors image
> 
> `exportPipeline` and `importPipeline` are incorrectly flagged as tracked resources. These are both proxy resources. Since they are enabled with Managed Identity, `properties.Location` is required. Please see more information in the [ARM wiki](https://armwiki.azurewebsites.net/authorization/managed_identities/MSIOnboardingProxyResource.html#other-notes). Please update this pipeline so that these MI-enabled proxy resources are not flagged as tracked.

@jianyexi please check @jaysterp's comment, it looks like there's a bug in determining a tracked resource in the LintDiff.

**Comment by fengzhou-msft** [comment]
@tadelesh @qiaozha please help review the breaking changes in Go and JS SDKs.

**Comment by tadelesh** [comment]
> @tadelesh @qiaozha please help review the breaking changes in Go and JS SDKs.

@fengzhou-msft There is no breaking change from `SDK azure-sdk-for-go` log. It seems there are some problems with the `Swagger SDK Breaking Change Tracking` check.

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
