### PR TITLE
Added stable 2019-10-01 api version.

### PR DESCRIPTION
**Pull request by jimmyca15**
The signed off PR for this addition can be found here in the private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/867

### CODE REVIEW

**Comment by jimmyca15** [comment]
@sergey-shandar can you lend a hand here getting this approved. We need our management SDK built so we can update CLI and what not to prepare for GA.

**Comment by nschonni** [comment]
Since it's not referenced in the README, nothing for the SDKs is being build, and that's why the Avocado job is failing

**Comment by jimmyca15** [comment]
@nschonni is that needed for merge? I don't think we did anything like that in the past and we were able to generate sdk for CLI fine.

**Comment by jimmyca15** [comment]
I added the new api version to the readme. Let me know if there's anything else blocking. Thanks.

**Comment by jimmyca15** [comment]
@nschonni @sergey-shandar 
ping. Please let me know if there is anything blocking the merge of this PR. Thanks.

**Comment by jimmyca15** [comment]
@nschonni @sergey-shandar ping. 

Our team needs this PR to be merged in. It has already been approved in the private repo as mentioned in the description. Please let me know what is blocking this from being merged in thanks.

If it is because the Avocado thing is failing please let me know. Sometimes builds block PRs sometimes they don't. Thinks.

**Comment by nschonni** [comment]
Sorry, I can't merge anything, just was pointing out how to fix (part) of the build failure. I think the remaining build failures are from example files that are not referenced from the spec file in this version

**Comment by jimmyca15** [comment]
@nschonni 
Sorry about. Thought you were reviewing this for merge :). Thanks though, I got the avocado build working, turned out to be a flub in the readme and a few missing example links.

@sergey-shandar are you able to merge this?

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
