### PR TITLE
[Hub Generated] Review request for Microsoft.MachineLearningServices to add version preview/2022-06-01-preview

### PR DESCRIPTION
**Pull request by erjms**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/dev-machinelearningservices-Microsoft.MachineLearningServices-2022-06-01-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zizw123** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}/customServices": {

Should this be named as updateCustomServices?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/machineLearningServices.json:1004 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by zizw123** [comment]
>         }

Resume is async and pause is sync, any particular reason for this?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:4089 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by zizw123** [comment]
Also noticed there's a lot of errors in the pipeline, please fix them and then remove the "ARMChangesRequested" tag, so the review can continue.

**Comment by erjms** [comment]
> Also noticed there's a lot of errors in the pipeline, please fix them and then remove the "ARMChangesRequested" tag, so the review can continue.

The remaining LintDiff and ModelValidation errors are false negatives, and were already reviewed and approved in the PRs into this staging branch:

- Swagger ModelValidation: These are all false negatives in regards to required properties marked with x-ms-secret - from the [x-ms-secret documentation](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-secret), this scenario should not have the property be present in responses. This came up in our GA PR and was approved ([see here](https://github.com/Azure/azure-rest-api-specs/pull/18645#issuecomment-1136129357)), and was also reviewed and approved in this PR into the staging branch: https://github.com/Azure/azure-rest-api-specs/pull/19740
- Swagger LintDiff: These are all false negatives and appear to be a bug with the pipeline, and were already reviewed and approved in the PR into the staging branch, see @ArcturusZhang 's [comment approving the LintDiff errors](https://github.com/Azure/azure-rest-api-specs/pull/19740#issuecomment-1184032922)

- API Readiness Check: Our manifest is currently deploying following SDP and this should resolve in a few days. In the meantime, I applied the DoNotMerge tag to this PR.

**Comment by srivatsasinha** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}/customServices": {
> > ```
> 
> Should this be named as updateCustomServices?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/machineLearningServices.json:1004 in [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d). [](commit_id = [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d), deletion_comment = False)

This endpoint is already in Public Preview and consumed by UX currently from Azure ML Studio. It won't be possible to rename now. We can track it in GA though.

**Comment by raosuhas** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}/customServices": {

Consider this feedback to make it clear that this is an operaitopn on the compute

---
In reply to: [1198640828](https://github.com/Azure/azure-rest-api-specs/pull/19842#issuecomment-1198640828) [](http://example.com/codeflow?ancestors=1198640828,1198640828)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/machineLearningServices.json:1004 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by erjms** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}/customServices": {
> > ```
> 
> Consider this feedback to make it clear that this is an operaitopn on the compute
> 
> In reply to: [1198640828](https://github.com/Azure/azure-rest-api-specs/pull/19842#issuecomment-1198640828)
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/machineLearningServices.json:1004 in [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d). [](commit_id = [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d), deletion_comment = False)

@suhasaraos Please see the reply regarding this here:
https://github.com/Azure/azure-rest-api-specs/pull/19842#issuecomment-1198876816

**Comment by raosuhas** [comment]
>             "type": "string"

please consider using ODATA for filter queries.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:3319 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>           }

again please use ODATA to model this. See here for the full example : 

[https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#982-client-driven-paging](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#982-client-driven-paging)




---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:3667 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>             "type": "string"

More details here : 

[https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#99-compound-collection-operations](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#99-compound-collection-operations)

---
In reply to: [1201638042](https://github.com/Azure/azure-rest-api-specs/pull/19842#issuecomment-1201638042) [](http://example.com/codeflow?ancestors=1201638042)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:3319 in 5011a3d. [](commit_id = 5011a3d65e822de4d3e254ea389f36a8d796b158, deletion_comment = False)

**Comment by raosuhas** [comment]
>             "type": "boolean",

across the board for this PR , please avoid using query params for operations and consider including this in the request body

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:3784 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "x-nullable": true

Consider if some of these popertiues can be modelled as enum. Clients work much better for customers if the values are modelled as enum

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:9871 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "example": "choice(50, 100)",

should these be int ? Can you please explain what choice(50,100) means ? Is that the acceptable range for your service or just the values for this "boxDetectionsPerImage" property ?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:10002 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "x-nullable": true

looks like here you have modelled it as an int 

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:10318 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>           ]

again consider using enum : ScheduleState : enabled\disabled

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:13607 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
>         },

same comment as above .. consider using enum instead of booleans

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:15124 in a464a09. [](commit_id = a464a098c1e3e13168541557bad3aa3cdc90ba6d, deletion_comment = False)

**Comment by raosuhas** [comment]
Please respond to the comments and remove the "ARMChangesRequested" label when this PR is ready for review again .

**Comment by erjms** [comment]
> > ```
> >         "type": "string"
> > ```
> 
> please consider using ODATA for filter queries.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:3319 in [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d). [](commit_id = [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d), deletion_comment = False)

Given our tight timeline for this API and the fact that our [GA stable version](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01) does not use ODATA, could we keep the PR as-is for this preview version and look into implementing ODATA for future preview/GA versions? Above all, we would like to avoid breaking changes, and avoid schedule risk given the complexities of modifying the underlying service to accommodate this change.

**Comment by erjms** [comment]
> > ```
> >         "read",
> > ```
> 
> consider using enums rather than booleans :
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=enum
> 
> Replace boolean/switch properties with better enum A Boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Even if you still believe [True, False] are the correct values for a property, you should use a string enum with values [True, False] instead of boolean. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [True, False, Unknown].
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json:11422 in [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d). [](commit_id = [a464a09](https://github.com/Azure/azure-rest-api-specs/commit/a464a098c1e3e13168541557bad3aa3cdc90ba6d), deletion_comment = False)

These features are in preview and their contracts have not solidified. Similar to my above response, could we keep them as-is in this PR, and look into updating them to enums in the next preview or GA version?

**Comment by ArcturusZhang** [comment]
Suppress LintDiff and ModelValidation because they are all known false alarms

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
