### PR TITLE
Add api version 2024-10-01-preview for Azure SignalR and Azure Web PubSub

### PR DESCRIPTION
**Pull request by bjqian**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by razvanbadea-msft** [comment]
>         "maxInboundMessageBytes": {

if there is a 1GB as default why did you not set it? like you added for aggregationWindowInSeconds

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-10-01-preview/signalr.json:3743 in beb58ba. [](commit_id = beb58bae6ea20745963ae7853c3f034e46469f15, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>           "description": "Gets or sets the Keep-Alive Interval. Optional to set.\r\nValue is in seconds.\r\nThe default value is 15 seconds.\r\nCustomers should set this value to a shorter period if they want the service to send keep-alive messages more frequently, \r\nensuring timely checks of the connection status.\r\nConversely, customers can set this value to a longer period if they want the service to send keep-alive messages less frequently, \r\nreducing network traffic, but note that it may take longer to detect a disconnection.\r\nThis interval ensures that the connection is maintained by sending periodic keep-alive messages to the client.",

same thing about adding also a default

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-10-01-preview/signalr.json:3044 in beb58ba. [](commit_id = beb58bae6ea20745963ae7853c3f034e46469f15, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>           "description": "Rules to control the client traffic",

you can specify in the description that you cant add more than 10

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-10-01-preview/signalr.json:2157 in beb58ba. [](commit_id = beb58bae6ea20745963ae7853c3f034e46469f15, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "maxInboundMessageBytes": {

same comment in this file about default attribute

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-10-01-preview/webpubsub.json:3776 in beb58ba. [](commit_id = beb58bae6ea20745963ae7853c3f034e46469f15, deletion_comment = False)

**Comment by bjqian** [comment]
> > ```
> >       "description": "Gets or sets the Keep-Alive Interval. Optional to set.\r\nValue is in seconds.\r\nThe default value is 15 seconds.\r\nCustomers should set this value to a shorter period if they want the service to send keep-alive messages more frequently, \r\nensuring timely checks of the connection status.\r\nConversely, customers can set this value to a longer period if they want the service to send keep-alive messages less frequently, \r\nreducing network traffic, but note that it may take longer to detect a disconnection.\r\nThis interval ensures that the connection is maintained by sending periodic keep-alive messages to the client.",
> > ```
> 
> same thing about adding also a default
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-10-01-preview/signalr.json:3044 in [beb58ba](https://github.com/Azure/azure-rest-api-specs/commit/beb58bae6ea20745963ae7853c3f034e46469f15). [](commit_id = [beb58ba](https://github.com/Azure/azure-rest-api-specs/commit/beb58bae6ea20745963ae7853c3f034e46469f15), deletion_comment = False)

Hi @razvanbadea-msft . In this PR review , I found a new rule:
image
It's telling us to remove the swagger default value in the patch body.  I'm confused whether or not we should mark the default value in the swagger. 😂

**Comment by bjqian** [comment]
Hi @razvanbadea-msft . 

Thanks for the clarification!  I understand the recommended approach is to use a separate model for patch if a model contains "default/required" properties.

Let me elaborate a bit on the issue:

Yes, those properties are pachable. However, the two properties in question were introduced in a model from a previous API version. Switching to a new model could potentially break existing client code.  

In our Resource Provider, the actual behavior for **default value** in the comment is as follows:  
- For **Create** operations, our RP fills in the default value if these properties are omitted. 
- For **Patch** operations, the fields are left untouched if they are not provided.  

In this way, we could avoid introducing "swagger default" in the client side. 

Thank you again for highlighting this issue! Please let us know if you'd like more details or further clarification.

**Comment by bjqian** [comment]
Hi guys, can we get merged now 😃

**Review by tadelesh — APPROVED** [review]

**Pull request merged**
