### PR TITLE
databricks: switching `parameters` to be a proper struct

### PR DESCRIPTION
**Pull request by tombuildsstuff**
As a part of the provisioning process, Databricks Clusters allow users to override certain values via a `parameters` block. Since there appears to be a fixed list of these:

> `customPrivateSubnetName`, `customPublicSubnetName`, `customVirtualNetworkId`, `enableNoPublicIp`, `relayNamespaceName`, `storageAccountName`, `storageAccountSkuName`, `vnetAddressPrefix`, `resourceTags`, `amlWorkspaceId`.

from a usability perspective this would match other SDK's if these values were exposed as a native struct/class depending on the language, rather than being a generic dictionary; as such this PR changes `parameters` to a struct rather than a dictionary.

---

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by Juliehzl** [comment]
Pls have a look at CI error. I think you should update your examples for the new swagger parameters.

**Review by ryansbenson — COMMENTED** [review]
Approved from ARMs side

**Comment by Juliehzl** [comment]
@tombuildsstuff  Please add body part for 201 response in workspacecreate example. If you want to return empty body, you sholud use `"body": ""` not `{}`.

**Comment by yungezz** [comment]
hi @tombuildsstuff @Juliehzl  what's the conclusion on this PR? is it ready for merge?

**Comment by Juliehzl** [comment]
@tombuildsstuff Can you try to make CI pass according log information?

**Comment by Juliehzl** [comment]
Looks good in general. @tombuildsstuff can you make CI pass first?

**Comment by tombuildsstuff** [comment]
@Juliehzl sure, will try and take a look today/tomorrow

**Comment by Juliehzl** [comment]
> @Juliehzl sure, will try and take a look today/tomorrow

Any update?

**Comment by Juliehzl** [comment]
@tombuildsstuff Do you have any update for this PR?

**Review by Juliehzl — APPROVED** [review]

**Comment by Juliehzl** [comment]
LGTM for specification side. But no response from @tombuildsstuff  to make CI pass. In this way, I will close this PR and @tombuildsstuff  when you are ready, feel free to reopen it.

**Pull request closed without merging**
