### PR TITLE
[Synapse] Add release tag

### PR DESCRIPTION
**Pull request by wonner**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Please review LintDiff CI errors.

**Comment by weidongxu-microsoft** [comment]
@jianyexi If you have advice for service.

It seems hard to unify the definition of Endpoint without causing breaking.

**Comment by jianyexi** [comment]
>I suggest go through the breaking change review

**Comment by weidongxu-microsoft** [comment]
@pshao25 @msyyc @qiliao123 on whether your SDK require `format: uri` on Endpoint.

Java does not require (and should work with/without it), as we had String in core. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/client/traits/EndpointTrait.java

**Comment by msyyc** [comment]
python treat `uri` as `string` so it shall not break.

**Comment by weidongxu-microsoft** [comment]
.NET override Endpoint to format=url https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/autorest.md#make-endpoint-type-as-uri

Other SDK is not affected.

**Comment by weidongxu-microsoft** [comment]
You might want to check if you need to suppress `ModelValidation`. Adding header (according to the rule) will be considered as breaking changes, that cannot happen without api-version upgrade.

**Comment by wonner** [comment]
> You might want to check if you need to suppress "ModelValidation" on LRO headers. Adding header (according to the rule) will be considered as breaking changes, that cannot happen without api-version upgrade.

I think we can fix the ModelValidation in another PR? because it's not caused by my changes.

**Review by pshao25 — APPROVED** [review]
`"format": "uri" `

is OK for .net generation.

**Comment by weidongxu-microsoft** [comment]
> I think we can fix the ModelValidation in another PR? because it's not caused by my changes.

Sure. But at least I don't have permission to merge PR with failed required CI.

**Comment by JeffreyRichter** [comment]
Approved because: In order to fix the LintDiff “AutoRest exception”: “Duplicated global non-identical parameter definitions”, I added “format”: “uri” to some parameter Endpoint. I have checked with all the SDK owners. It will not break SDK.

**Pull request merged**
