### PR TITLE
fix the hardcoding of api version for classicadmin in powershell

### PR DESCRIPTION
**Pull request by darshanhs90**
This is a fix for this hardcoding
https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClient.cs#L297

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by darshanhs90** [comment]
@mcardosos can you take a look into this,had to make a minor fix since the api version was moved to parameters section,we werent able to hardcode the api version like before[which isnt recommeded also]

**Comment by mcardosos** [comment]
@darshanhs90
To clarify (I am not familiar with Azure Powershell) How is it that moving files fixes the issue?
Is it because now files are in the wrong api version folder, and with this change they will be in the right api version folder, so it does not need to be overriden?

**Comment by darshanhs90** [comment]
@mcardosos no earlier,since we had a apiversion as follows
    "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/classicAdministrators": {
      "get": {
        "tags": [
          "ClassicAdministrators"
        ],
        "operationId": "ClassicAdministrators_List",
        "description": "Gets service administrator, account administrator, and co-administrators for the subscription.",
        "parameters": [
          {
            **"name": "api-version",
            "in": "query",**
            "required": true,
            "type": "string",
            "description": "The API version to use for this operation."
          }

which allowed us to modify the api version in sdk and powershell for all the classicadmin requests[since we had a single swagger file with 2015-07-01 version]
The reason for hardcoding it in the requests was that classicadmin api supported only 2015-06-01 and not the other API version[2015-07-01]

Hence i made this PR to fix that issue.
As we moved the api-version to Parameters section ,it doesn't allow us to pass in the api version as part of the request like earlier causing the classicadmin calls to hit the api version 2015-07-01 resulting in bad request

**Comment by mcardosos** [comment]
Oh, okok :) Moving the files is the right thing to do in this case, yes.
If in the future, you happen to have a global param you want to pass in the method, take a look here
https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-parameter-location
(However, I wound not recommend this for API version parameter).

Change LGTM. @fearthecowboy is this change good for you too? For context, the operation `ClassicAdministrators_List` that is being removed in `authorization.json`, already exists in `authorization-ClasicAdminCalls.json`

**Comment by darshanhs90** [comment]
@mcardosos anything blocking this pr to be merged?

**Review by mcardosos — APPROVED** [review]

**Comment by fearthecowboy** [comment]
I don't see a problem. @lmazuel -- you have any problem with this?

**Review by lmazuel — APPROVED** [review]

**Comment by lmazuel** [comment]
LGTM thanks @fearthecowboy :)

**Pull request merged**
