### PR TITLE
Adding Swagger example files for all of ADLA and ADLS

### PR DESCRIPTION
**Pull request by begoldsm**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### Description
There are three pending issues with this change that were already discussed with the Swagger team.  These errors are from the oav while calling "oav validate-example filesystem.json."  Every Swagger file passed these tests except filesystem.json and its example files.

1.  Because we were running into an "EQUIVALENT_PATH" error, we moved the paths into "x-ms-paths" and differentiated each path by inserting the "op" query and its associated constant string value into the path.  We ran into the following form of error for all those paths:

```
error: Found errors in validating the request for x-ms-example "Creates a directory" in operation "FileSystem_Mkdirs".:

{ code: 'REQUEST_VALIDATION_ERROR',
  message: 'Found errors in validating the request for x-ms-example "Creates a directory" in operation "FileSystem_Mkdirs".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'REQUIRED',
            message: 'Value is required but was not provided',
            path:
             [ 'paths',
               '/webhdfs/v1/{path}?op=MKDIRS',
               'put',
               'parameters',
               '0' ] } ],
       in: 'path',
       message: 'Invalid parameter (path): Value is required but was not provided',
       name: 'path',
       path: { '$ref': '$["innerErrors"][0]["errors"][0]["path"]' } } ] }
```

2.  There is currently no support for "application/octet-stream," which produced this error:
Issue: https://github.com/Azure/oav/issues/136
```
error: Found errors in validating the request for x-ms-example "Appends to the specified file, optionally first creating the file if it does not yet ex
ist. This method supports multiple concurrent appends to the file. NOTE: The target must not contain data added by Create or normal (serial) Append. Co
ncurrentAppend and Append cannot be used interchangeably; once a target file has been modified using either of these append options, the other append o
ption cannot be used on the target file. ConcurrentAppend does not guarantee order and can result in duplicated data landing in the target file" in ope
ration "FileSystem_ConcurrentAppend".:

{ code: 'REQUEST_VALIDATION_ERROR',
  message: 'Found errors in validating the request for x-ms-example "Appends to the specified file, optionally first creating the file if it does not y
et exist. This method supports multiple concurrent appends to the file. NOTE: The target must not contain data added by Create or normal (serial) Appen
d. ConcurrentAppend and Append cannot be used interchangeably; once a target file has been modified using either of these append options, the other app
end option cannot be used on the target file. ConcurrentAppend does not guarantee order and can result in duplicated data landing in the target file" i
n operation "FileSystem_ConcurrentAppend".',
  innerErrors:
   [ { code: 'INVALID_CONTENT_TYPE',
       message: 'Invalid Content-Type (application/json).  These are supported: application/octet-stream',
       path: [] } ] }
```

3.  Similarly to 2 above, there seems to be no support for returning "file" types in the response body:
Issue: https://github.com/Azure/oav/issues/136
```
error: Found errors in validating the response with statusCode "200" for x-ms-example "Opens and reads from the specified file" in operation "FileSyste
m_Open".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Opens and reads from the specified file" in operation "File
System_Open".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: undefined,
            message: 'Invalid \'type\' value: file',
            path: undefined } ],
       message: 'Invalid body: Invalid \'type\' value: file',
       path: [] } ] }
```

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by begoldsm** [comment]
@veronicagg @amarzavery could you guys take a look and help us understand why the `x-ms-path` validation examples are still failing?

**Comment by veronicagg** [comment]
issue with x-ms-paths for example validation is tracked at https://github.com/Azure/oav/issues/140

**Comment by begoldsm** [comment]
This PR is now approved for merge from the ADL team and confirmed to not cause code gen issues. Additionally, it resolves the following validation issues:
https://github.com/Azure/azure-rest-api-specs/issues/802

**Comment by veronicagg** [comment]
taking over this PR, since I've been looking into the issues

**Comment by veronicagg** [comment]
@begoldsm Even though, diff shows changes in operations, it looks to be order changes, the PR appears to contain only addition of x-ms-examples. Please let me know if that's not the case. 
Could you double check on the following:
1. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1445
2. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1515
3. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1770

Regarding linter errors, same linter errors should be coming up - so I assume you're aware of those:
Since some of the specs are data-plane and we're learning to categorize the rules, do you think the errors reported are applicable, like https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710677#L1633 ?
If you took a look at them and actually know that some of them are not applicable to data-plane, it'd be really helpful for us to know, so we could change the applicability of the rule.
Thanks!

**Review by veronicagg — CHANGES_REQUESTED** [review]
PR generally looks good, just posted a few questions, before approving. thanks!

**Comment by begoldsm** [comment]
@veronicagg I have an update:
* https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1445
  * This was a legitimate issue, which I just fixed in a new commit. Good catch!
* https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1770
  * This was a legitimate issue, caused by an accidental commit in the wrong branch. I reverted the change to the example and this should now be fixed.
* https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710682#L1515
  * This is a known issue with the validator: https://github.com/Azure/oav/issues/136

As for the readme issue in data plane (https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710677#L1633):
* LROs: There are no LROs in our data plane operations, so this is an invalid check for us.
* Camel casing rules: Unfortunately we **must** adhere to the WebHDFS specification, which itself does not honor proper camel casing rules, so our hands are tied here (AclStatus cannot be "aclStatus" because it will break webHDFS compat). I think this validation error is specific to our swagger, though, so it is still valid for all others, we would just need an exception for the filesystem.json swagger file
* Operations API requirement: This is specific to ARM, so should not be applied to data-plane swagger files (also we don't have an Operations API implemented for ARM, either, but that is a different problem 😄 ).
* TrackedResourceListByImmediateParent: this needs to be a little less strict. The parent resource is `DataLakeStoreAccount`, but our method is called `FirewallRules_ListByAccount` for brevity. So it should notice that the list operation does still adhere to the "immediate parent" model.
* EnumInsteadOfBoolean: This is showing up for the standard OData property `$count`. This is meant to be a boolean and has a very specific meaning in OData, so this should have an exception.

For the warnings I am not overly investigating since we have already discussed things like Guids and have your sign off 😄

**Review by veronicagg — APPROVED** [review]

**Pull request merged**
