### PR TITLE
[DataFactory]Add CompressionCodec property for ORC Dataset

### PR DESCRIPTION
**Pull request by TinaHu1**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@TinaHu1 
Please double check whether this added property on stable would violation "New property added to response" in https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/guestaccess.aspx?rtime=oPAFQY8Z10g&share=EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw

Also I failed to find the usage of "OrcDataset" which is affected. Could you specify?

**Comment by TinaHu1** [comment]
> @TinaHu1
> Please double check whether this added property on stable would violate "New property added to response" in https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/guestaccess.aspx?rtime=oPAFQY8Z10g&share=EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw
> 
> Also I failed to find the usage of "OrcDataset" which is affected. Could you specify?

 It has been used by "Dataset" at specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json by using "x-ms-discriminator-value".

**Comment by weidongxu-microsoft** [comment]
What about 1st question?

The point is I didn't find it in https://github.com/TinaHu1/azure-rest-api-specs/blob/orccompression/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json. Not sure if I was missing anything or not. If you are sure it is in proper use then it is fine for me.

**Comment by TinaHu1** [comment]
> What about 1st question?
> 
> The point is I didn't find it in https://github.com/TinaHu1/azure-rest-api-specs/blob/orccompression/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json. Not sure if I was missing anything or not. If you are sure it is in proper use then it is fine for me.

It should be "new property added in response", but it can not be simply treated as breaking change in ADF case, please take this PR as reference: https://github.com/Azure/azure-rest-api-specs/pull/7040, thanks.

**Comment by weidongxu-microsoft** [comment]
> > What about 1st question?
> > The point is I didn't find it in https://github.com/TinaHu1/azure-rest-api-specs/blob/orccompression/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json. Not sure if I was missing anything or not. If you are sure it is in proper use then it is fine for me.
> 
> It should be "new property added in response", but it can not be simply treated as breaking change in ADF case, please take this PR as reference: #7040, thanks.

OK. We will do the same ARMFeedback same as that PR.

**Review by KrisBash — APPROVED** [review]
LGTM

**Pull request merged**
