### PR TITLE
Added App Configuration 2019-11-01-preview resource manager API.

### PR DESCRIPTION
**Pull request by jimmyca15**
The changes in this PR were reviewed and approved here: https://github.com/Azure/azure-rest-api-specs-pr/pull/1043

### CODE REVIEW

**Comment by yungezz** [comment]
HI @jimmyca15 could you pls fix PrettierCheck in CI, fixing guideline https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#prettier-check. Thanks.

**Comment by jimmyca15** [comment]
@yungezz I have run the prettier fix command to fix the errors for our service. I did scope the fixes to only our service. Let me know if anything else is needed. Thanks.

**Review by yungezz — APPROVED** [review]
the change is reviewed and signed off by ARM/SDK team. approve it.

**Pull request merged**
