### PR TITLE
Microsoft.ProviderHub : Adding 2021-06-01-preview

### PR DESCRIPTION
**Pull request by sanjaiganesh**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [X] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by j5lim** [comment]
>         "allowNoncompliantCollectionResponse": {

Can you explain what this is for?

---
Refers to: specification/providerhub/resource-manager/Microsoft.ProviderHub/preview/2021-06-01-preview/providerhub.json:4587 in 9c92c72. [](commit_id = 9c92c726e3196a424d4399278b1f89345b0b6281, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         "allowNoncompliantCollectionResponse": {

I shall follow up with you offline

---
In reply to: [856149061](https://github.com/Azure/azure-rest-api-specs/pull/14691#issuecomment-856149061) [](http://example.com/codeflow?ancestors=856149061,856149061)

---
Refers to: specification/providerhub/resource-manager/Microsoft.ProviderHub/preview/2021-06-01-preview/providerhub.json:4587 in 9c92c72. [](commit_id = 9c92c726e3196a424d4399278b1f89345b0b6281, deletion_comment = False)

**Comment by sanjaiganesh** [comment]
>         "allowNoncompliantCollectionResponse": {

@j5lim  sent you an email . thanks.

---
In reply to: [856289172](https://github.com/Azure/azure-rest-api-specs/pull/14691#issuecomment-856289172) [](http://example.com/codeflow?ancestors=856289172,856149061,856149061)

---
Refers to: specification/providerhub/resource-manager/Microsoft.ProviderHub/preview/2021-06-01-preview/providerhub.json:4587 in 9c92c72. [](commit_id = 9c92c726e3196a424d4399278b1f89345b0b6281, deletion_comment = False)

**Review by j5lim — APPROVED** [review]
Approved from ARM side.

**Comment by zhenglaizhang** [comment]
Hi @sanjaiganesh pls help fix the swagger lint(RPaaS) and avocado failures 
besides, pls go through breaking change review process since the cross version report breaking change compared to last stable version

**Comment by sanjaiganesh** [comment]
@zhenglaizhang  There is no breaking change actually. RpaaS linter rule forced me to add provisioningState to some of the resource types in existing GA api-version. This is a trivial change and this property is already supported.

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang There is no breaking change actually. RpaaS linter rule forced me to add provisioningState to some of the resource types in existing GA api-version. This is a trivial change and this property is already supported.
> You may approve, but don't merge atm.

Hi @sanjaiganesh just a soft ping as the bot has complained no activity :) , as we synced through email, breaking change review process is required for this PR.

**Comment by sanjaiganesh** [comment]
> > @zhenglaizhang There is no breaking change actually. RpaaS linter rule forced me to add provisioningState to some of the resource types in existing GA api-version. This is a trivial change and this property is already supported.
> > You may approve, but don't merge atm.
> 
> Hi @sanjaiganesh just a soft ping as the bot has complained no activity :) , as we synced through email, breaking change review process is required for this PR.

@zhenglaizhang  I have added those properties back (subscriptionLifecycleNotificationSpecifications & templateDeploymentOptions). Could you remove the 'newapiversion..' tag ? We shall follow up on them for next GA api version.

**Comment by zhenglaizhang** [comment]
@sanjaiganesh looks like there is still one more breaking change adding optional https://github.com/Azure/azure-rest-api-specs/pull/14691#issuecomment-855171127 pls double check.

**Comment by sanjaiganesh** [comment]
> @sanjaiganesh looks like there is still one more breaking change adding optional [#14691 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/14691#issuecomment-855171127) pls double check.

@zhenglaizhang  thanks. This is actually required by all RPs marked as RPaaS, enforced by RPaaS linter rule. Also provisioningState is a supported property for all azure resources and this is not a breaking change. You have to override and approve either ways :-) let me know.

**Comment by sanjaiganesh** [comment]
btw please don't merge. @diwudd has additional changes to make/merge to this api-version.

**Comment by diwudd** [comment]
Hi There,

The PR is ready to be merged. Can you please merge it?

Thanks,

Di

**Comment by zhenglaizhang** [comment]
> Hi There, The PR is ready to be merged. Can you please merge it? Thanks, Di From: msftbot[bot] ***@***.***> Sent: Sunday, July 4, 2021 9:02 AM To: Azure/azure-rest-api-specs ***@***.***> Cc: Di Wu ***@***.***>; Mention ***@***.***> Subject: Re: [Azure/azure-rest-api-specs] Microsoft.ProviderHub : Adding 2021-06-01-preview (#14691) Hi, @sanjaiganesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsanjaiganesh&data=04%7C01%7Cwud%40microsoft.com%7C76cc34df4d6a4fdf00e008d93f051787%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637610113374753828%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nqv%2B%2BoUlewkim29ervRvy5AUNw1PjLxkjCG3IME%2FeFk%3D&reserved=0>. Your PR has no update for 14 days and it is marked as stale PR. If no further update for over 14 days, the bot will close the PR. If you want to refresh the PR, please remove no-recent-activity label. - You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F14691%23issuecomment-873617225&data=04%7C01%7Cwud%40microsoft.com%7C76cc34df4d6a4fdf00e008d93f051787%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637610113374753828%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p5EwQr0sg1ZmEgei6Dtcnwq16Zn%2BDD8iYS4s81YnWp4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFOVDVVHXRGE6PCSN76DT23TWCAYNANCNFSM46D6VA5A&data=04%7C01%7Cwud%40microsoft.com%7C76cc34df4d6a4fdf00e008d93f051787%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637610113374763777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xPBW7Tfn6RbtIv4BWRFOgQyv3xtXBlIUoAzm5kRat0M%3D&reserved=0>.

@diwudd pls help resolve the conflicts and do necessary breaking change review.

**Comment by diwudd** [comment]
This one is no longer needed as the same changes have been made with another PR. Closed it.

Thanks,

Di

**Pull request closed without merging**
