### PR TITLE
Updated swagger doc in stable with changes to ImageAnalysis skill

### PR DESCRIPTION
**Pull request by jennifermarsman**
Updated swagger doc in stable with changes to ImageAnalysis skill (new languages and visual features).  

I tested for local validation using the following commands, and both returned no errors: 
autorest --azure-validator --input-file=searchservice.json --message-format=json --openapi-type=data-plane
oav validate-spec searchservice.json

I tried to test on the [OpenAPI Hub](https://aka.ms/openapiportal).  The static validation passed, but the linter hung indefinitely when processing.  (How long is this supposed to take?)  

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by jennifermarsman** [comment]
Also note that changes were made only in the "stable" version.  Will this automatically be added into the next preview as well?  (Currently there is a preview in track1 only, and I didn't make changes there, and I'm not sure if the preview-2019-05-06 will be created from http://github.com/Azure/azure-rest-api-specs/tree/master/specification/search/data-plane/Microsoft.Azure.Search.Service/stable/2019-05-06/ OR https://github.com/Azure/azure-rest-api-specs/tree/master/specification/search/data-plane/Microsoft.Azure.Search.Service/track1/preview/2019-05-06-preview.)   @brjohnstmsft does this concern make sense?  Are you the only who will be doing this?  

Also added @Careyjmac for review, as she did the code and doc changes for this.

**Comment by brjohnstmsft** [comment]
@jennifermarsman I'll be creating the new Track 2 spec for 2019-05-06-preview by combining the result of this PR with the changes in the Track 1 preview spec, with your team's help if necessary.

**Review by bitsforthought — APPROVED** [review]
LGTM, but more SMEs should look at this

**Review by Careyjmac — APPROVED** [review]

**Comment by brjohnstmsft** [comment]
FYI @jhendrixMSFT -- This review got auto-assigned to @sarangan12, but I don't think he's around. Would you be able to review our Swagger changes (we'll have a lot more coming soon)? If not, do you know who the right person would be?

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Changes look good, are we waiting for other reviews or is this ready to merge?

**Comment by brjohnstmsft** [comment]
@jhendrixMSFT Ready to merge, thanks!

**Pull request merged**
