### PR TITLE
Fix environment patch

### PR DESCRIPTION
**Pull request by drielenr**
Environment has two properties that can be updated after resource creation: `expirationDate` and `parameters`. However, `parameters` can only be updated during CreateOrReplace and not Patch, as its update results in a LRO.

During the transition from Swagger to TypeSpec, we mistakenly indicated that both properties could be updated during the patch operation. This pull request aims to correct that.

No SDK for 2024-02-01 - when the patch operation got added - has been released, so we don't foresee any incompatibility issues. Our backend has never accepted `parameters` in the patch operation, so this change will be a fix to the [documentation ](https://learn.microsoft.com/en-us/rest/api/devcenter/developer/environments/patch-environment?view=rest-devcenter-developer-2024-02-01&tabs=HTTP#request-body)

### CODE REVIEW

**Comment by JeffreyRichter** [comment]
If you want to allow parameters to be updated, you can offer a POST-Action operation that is an LRO.
Saying that parameters is updatable via PUT means that the resource is deleted and then created (hence CreateOrREPLACE). If a v1 client PUTs over a V2+ resource, then all V2+ properties will be deleted - is this what you want?

Also, it is not acceptable to ship incorrect API contracts. You claim that it was always wrong, but this then implies that there was no testing of any of this - the service team is responsible for testing this BEFORE making the service version available to customers.

You also mention that there is no SDK but having an SDK or not is not relevant. When you publish an API contract, we produce HTTP REST documentation for csutomers to use and many Azure customers just make raw HTTP requests to services without using any SDK at all. So, breaking the contract breaks all these customers eventhough they are not using any SDK.

I think you should come to an Office Hours to discuss all of this.

**Review by ArberH — APPROVED** [review]
Looks good to me

**Comment by snehanagendra** [comment]
@JeffreyRichter - We will attend office hours today at 5pm

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Pull request merged**
