### PR TITLE
[Microsoft.StorageSync] Update 2020-03-01 and 2020-09-01 API versions to fix swagger correctness issues.

### PR DESCRIPTION
**Pull request by anpint**
Changes to 2020-09-01:
- update resource contracts to support systemData, which our service is already returning today.
- add missing defaults in put server endpoint properties for optional properties
- add missing property supportedAggregationTypes
- change innerError property to innererror to reflect what the service actually returns

Changes to 2020-03-01:
- add missing defaults in put server endpoint properties for optional properties
- add missing property supportedAggregationTypes
- change innerError property to innererror to reflect what the service actually returns

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by anpint** [comment]
@changlong-liu Please let me know if there's anything remaining to do with this PR or if it's ready to be merged. Looks like the only check that is failing is the breaking change check, and we've already received approval to make the changes.

**Comment by changlong-liu** [comment]
Hi @anpint , the approved breaking change is in swagger level, and still need to have SDK breaking review.

Adding @ArcturusZhang , @qiaozha , @msyyc  for SDK breaking change. Thanks.

**Comment by anpint** [comment]
> Hi @anpint , the approved breaking change is in swagger level, and still need to have SDK breaking review.
> 
> Adding @ArcturusZhang , @qiaozha , @msyyc for SDK breaking change. Thanks.

@changlong-liu What is "SDK breaking review"? I don't see it documented anywhere in the breaking change review process.

**Comment by changlong-liu** [comment]
Hi @anpint, it's about the breaking change on the released SDKs: https://github.com/Azure/azure-rest-api-specs/pull/17159/checks?check_run_id=4976024637

**Comment by anpint** [comment]
> Hi @anpint, it's about the breaking change on the released SDKs: https://github.com/Azure/azure-rest-api-specs/pull/17159/checks?check_run_id=4976024637

@changlong-liu I already followed the documented breaking change process which included filing an item and it included sections for the necessary SDK changes. I received approval from breaking change office hours to make the changes. This is the first time that I'm hearing of a separate SDK breaking change review process and it's not documented anywhere.

**Comment by changlong-liu** [comment]
Hi @anpint , there is SDK breaking approval requirement in the main diagram of below page:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review

**Comment by anpint** [comment]
> Hi @anpint , there is SDK breaking approval requirement in the main diagram of below page: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review

@changlong-liu thanks for sharing that. I didn't know it existed. The diagram is very helpful. I guess I will wait for the SDK breaking change review.

**Comment by changlong-liu** [comment]
Hi, @ArcturusZhang , @qiaozha , @msyyc, would you please review the SDK breaking change on Go/JS/Python. Thanks.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
