### PR TITLE
Dev datamigration microsoft.data migration 2021 06 30

### PR DESCRIPTION
**Pull request by temandr**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by temandr** [comment]
Continuation of [previous PR](https://github.com/Azure/azure-rest-api-specs/pull/14898) to adhere to the commit policy. @mentat9

**Comment by mentat9** [comment]
Thank-you @temandr. This week's oncall is @majastrz. He will work with you to complete the PR review.

**Comment by majastrz** [comment]
Is the first commit the previously approved API version? (If yes, which one?) Or is it something else?

**Comment by temandr** [comment]
> Is the first commit the previously approved API version? (If yes, which one?) Or is it something else?

It's based on the already checked in version 2018-07-15-preview. There were some changes that were done on top that API version to refactor the ConnectToSourceMySqlTaskProperties into the Tasks file as well as build fixes.

**Review by hitenjava — APPROVED** [review]

**Review by majastrz — APPROVED** [review]
I don't see any new paths in the change and this seems to be mostly centered around adding new properties and refactoring. Seems fine from ARM point of view.

**Comment by temandr** [comment]
@akning-ms These changes are ready to be checked in. What is the ETA for the completion?

**Comment by akning-ms** [comment]
Hi @temandr, you need to fix ModelValidation failure first before I can help you merge.
and one more question is:  seems it is same PR as you state in: https://github.com/Azure/azure-rest-api-specs/pull/15259#issuecomment-882967660
Can I know why you submit new PR again?  @jianyexi (preview PR assignee) for awareness 
and let us know if any difference between them. and close one of them if need.
BTW, there is some cross API version breaking change in https://github.com/Azure/azure-rest-api-specs/pull/15259/checks?check_run_id=3109698458  you may need double confirm it is correct

**Comment by akning-ms** [comment]
@zhenglaizhang for help to check why API generation fail

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang for help to check why API generation fail

Escalated to docs team, and @v-haiboz is current doing investigation.

**Comment by zhenglaizhang** [comment]
@temandr It's because you are maxing `$ref` and `allOf` and the autorest used by docs pipeline doesn't handle the case successfully. Please double check `MigrateSqlServerSqlDbTaskOutputValidationResult` and `MigrateSqlServerSqlDbTaskOutputDatabaseLevelValidationResult` schema and below is one possible fix.
image

**Comment by temandr** [comment]
@zhenglaizhang That resolved the issue, thank you! 

@akning-ms "SDK azure-resource-manager-schemas" is failing across multiple PRs due to issue in finding readme in EnterpriseKnowledgeGraph. Other than that, this is ready for check in.

**Comment by akning-ms** [comment]
> @zhenglaizhang That resolved the issue, thank you!
> 
> @akning-ms "SDK azure-resource-manager-schemas" is failing across multiple PRs due to issue in finding readme in EnterpriseKnowledgeGraph. Other than that, this is ready for check in.

@leni-msft to confirm autorest-schema generation failure.  and @temandr, seems you still not reply my question about cross API version breaking change. :)
>>BTW, there is some cross API version breaking change in https://github.com/Azure/azure-rest-api-specs/pull/15259/checks?>> check_run_id=3109698458 you may need double confirm it is correct

**Pull request merged**
