### PR TITLE
Adding new property to Peering: connection identifier.

### PR DESCRIPTION
**Pull request by rileymckenna**
This is a unique hash for each connection so we can determine when a connection is deleted or if it is updated. 
This is a property update and an API update.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by rileymckenna** [comment]
@MyronFanQiu can i get an update on this PR?

**Review by ryansbenson — APPROVED** [review]
Only 2 small changes here. 
1. The connectionIdentifier property was added to DirectConnection and ExchangeConnection. 
2. OpenRevieved was added to sessionStateV4 and ...V6 enums.

Approved from ARM's side

**Comment by MyronFanQiu** [comment]
@openapi sdkautomation rebuild

**Comment by MyronFanQiu** [comment]
LGTM. Just two small things.
- Commonly the `securityDefinitions` will appear at the begin of the file. 
- I'm not familiar with the service behavior. Three or four parameters use the `query` in the `in` filed and other field use `path`. I just want to confirm it is by design, right?
I try to re-trigger the SDK generation process, but seems like it doesn't work. Could you take a look?@daschult

**Review by mmyyrroonn — APPROVED** [review]

**Comment by daschult** [comment]
@openapi sdkautomation rebuild

**Comment by daschult** [comment]
@openapi sdkautomation rebuild

**Comment by daschult** [comment]
@rileymckenna There have been some pretty significant folder changes in the SDK repositories lately, and that's why there didn't seem to be any changes generated by our tooling. I've fixed the TypeScript output folder path, but you may want to check with the other SDK owners to get their folder paths updated as well.

**Pull request merged**
