### PR TITLE
Add Azure Batch service swagger specification

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matthchr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (matthchr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by matthchr** [comment]
It looks like the file is too large for GitHub to show it in a good view.  If you like we can coordinate some alternative way to review this file.

**Comment by amarzavery** [comment]
We have a new extension named [x-ms-client-name](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-client-name) that can be used to provide a nice client model name.

It can be used for parameters like If-Modified-Since to ModifiedSince.

This just a suggestion. Not a requirement.

**Comment by amarzavery** [comment]
most of your response headers are same. It would be nice if we define them individually in the definitions section once and refer them every where. In that way, we reduce repetition and errors.

We should do this for parameters as well. Most operation have similar parameters. However, AutoRest treats, global parameters as properties of the client. It would be nice if we had an extension `"x-ms-client-property" : true` that when applied on a global parameter would make it a property on the client (subscriptionId, apiversion). By default global parameters would have no special treatment v/s local parameters. This would reduce repetition and cause less errors.

**Comment by amarzavery** [comment]
Line 9441:
"x-ms-enum": {"name": "CertificateState" }
By default modelAsString is false, if not specified. However, it is good to specify for clarity to the person reading the spec. Just a suggestion.

**Comment by amarzavery** [comment]
Line 9581:
```
"NodeFile": { 
  "properties": { 
    "name": { 
      "type": "string", 
      "description": "Gets or sets the file path." 
    }, 
    "url": { 
      "type": "string", 
      "description": "Gets or sets the URL of the file." 
    }, 
    "isDirectory": { 
      "type": "boolean", 
      "description": "Gets or sets whether the object represents a directory." 
    }, 
    "properties": { 
      "$ref": "#/definitions/FileProperties", 
      "description": "Gets or sets the file properties." 
    } 
  }, 
  "description": "Information about a file or directory on a compute node." 
}
```
We have a new extension named [`x-ms-client-flatten`](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-client-flatten) when applied flattens child properties one level up during deserialization and unflattens them one level down during serialization. This provides a better looking client side API where the user can create or get things easily.

**Comment by amarzavery** [comment]
over all the PR looks good. Try to use the x-ms-client-flatten extension wherever possible to make the client side API look better.

Let me know, the final outcome and I shall merge the PR accordingly.

**Comment by matthchr** [comment]
@amarzavery For the `x-ms-client-flatten` comment -- we actually purposefully do not use this parameter at all.  We want the client to match the REST API as closely as possible.  If there is a problem in usability, we can update the REST API.

**Comment by matthchr** [comment]
@amarzavery For x-ms-client-name, I used it to improve the casing of some of our names (i.e. `maxresults` in the REST API becomes x-ms-client-name `maxResults`).  Other than that we want to keep the generated client as close to possible as the real API, so we didn't rename other fields such as `If-Modified-Since`

**Comment by matthchr** [comment]
@amarzavery Made the suggested modelAsString change

**Comment by matthchr** [comment]
@amarzavery You say:

> most of your response headers are same. It would be nice if we define them individually in the definitions section once and refer them every where. In that way, we reduce repetition and errors.

How do we do this?  I was under the impression this wasn't possible.

**Comment by matthchr** [comment]
@amarzavery We have finished updating with the changes you suggested (the ones which we want to do) and are ready for you to merge.

**Comment by amarzavery** [comment]
@matthchr - Please make sure that the CI passes.

**Comment by matthchr** [comment]
@amarzavery Whoops!  Let me fix that.

**Pull request merged**
