### PR TITLE
[Compute] Prepare for 2019-07-01 compute.json

### PR DESCRIPTION
**Pull request by hyonholee**
This is a preparatory PR for 2019-07-01 API version of compute.json.

compute.json and example files are just copied from 2019-03-01 folder to 2019-07-01 folder.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@hyonholee Hello. This PR contains new API version and new API call. So we should invite arm's review.

**Comment by MyronFanQiu** [comment]
@hyonholee Could you please also link the corresponding PR for 2019-03-01. It will be helpful for the review process.

**Comment by MyronFanQiu** [comment]
@anthony-c-martin In my understanding, it's just a placeholder. I agree with you that this PR should contain the full set of changes. @hyonholee

**Comment by hyonholee** [comment]
@anthony-c-martin @MyronFanQiu  we will have several PRs for 2019-07-01 versions.  How can we make them into one PR?

**Comment by hyonholee** [comment]
@anthony-c-martin @MyronFanQiu  If you suggest an initial version of 2019-07-01 API version without this placeholder PR, then I will update the PR.  Thanks.

**Comment by MyronFanQiu** [comment]
@hyonholee From my perspective, our spec repo is public to everyone, especially for the master branch. So I don't think a placeholder in master branch is right. For example, Network Team will create a separate branch as a placeholder for monthly release. I agree that a placeholder will be easy for contribution process across several teams and review process. Could we also create a special branch for this API version? @anthony-c-martin Is it ok with ARM side?

**Comment by anthony-c-martin** [comment]
@MyronFanQiu I agree with the approach that Microsoft.Network follow. As you say, merging into master is regarded as an official release, which means we wouldn't allow any real changes other than bug fixes as per the rules around releasing stable API versions.

@hyonholee take a look at https://github.com/Azure/azure-rest-api-specs/pull/7005 for an example - as you can see the changes are being merged into a release branch. Once all the changes for the API version have been agreed upon, the release branch will be merged into master, at which point the API version will be considered released.

**Pull request closed without merging**
