### PR TITLE
Gallery 2022-03-03 API release

### PR DESCRIPTION
**Pull request by Sandido**
## ARM API Information (Control Plane)

Swagger PR being merged to this branch is: https://github.com/Azure/azure-rest-api-specs/pull/20398
This PR was signed off for the breaking changes in this PR because the functionality was broken for customers so these changes will not hurt customers. 
The individual SDK owners have approved this breaking change as well.

.Net changes for this branch are here: https://github.com/Azure/azure-sdk-for-net/pull/29817/files
And the .Net changes for the new features are here: https://github.com/Azure/azure-sdk-for-net/pull/30125

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raosuhas** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/latestVersionName": {

ARM interpres this as a get on a resource collection not a single resource get .

This API looks like it shoudl be modelled with filters on the collection GET at the version level .. i.e : 

subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\LOCATION}

Any reason you are not modelling as such ?

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json:528 in 2a2df20. [](commit_id = 2a2df20f2ad8feadd37f9819ffa395fcc6ec5fba, deletion_comment = False)

**Comment by kangsun-ctrl** [comment]
> 
Hi @raosuhas ,

We actually already have an API: subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\LOCATION}

The reason why this is not the same as that the thing returning from 
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/latestVersionName"
is not a artifact 'version', it is versionName instead, that's why we are building a new API for it.

So it is not returning a resource, but a resource name that we need it later.

**Comment by mentat9** [comment]
> > 
> 
> Hi @raosuhas ,
> 
> We actually already have an API: subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\LOCATION}
> 
> The reason why this is not the same as that the thing returning from "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/latestVersionName" is not a artifact 'version', it is versionName instead, that's why we are building a new API for it.
> 
> So it is not returning a resource, but a resource name that we need it later.

@Sandido - This is still problematic from ARM perspective. You are creating a new resource type, without full CRUD support. Can you add an OData filter like
```
subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\Latest}
```
and have the client read the name from the version resource?

Either way, if you can't support the scenario with filter parameters on the version list request, then the better ARM way of doing this is with a POST action on the gallery image instance, like
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/getLatestVersionName
```
Otherwise the ARM resource model would point to supporting full CRUD on a new versionName resource type and add a filter parameter on the collection GET for latest:
``` 
List (Collection GET): /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versionNames
Singleton (GET and PUT are required, PATCH and DELETE are optional):
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versionNames/latest
```
But then, what's the point of getting a version name by giving the version name you want?

**Comment by KshitijAgrawal** [comment]
> > > 
> > 
> > 
> > Hi @raosuhas ,
> > We actually already have an API: subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\LOCATION}
> > The reason why this is not the same as that the thing returning from "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/latestVersionName" is not a artifact 'version', it is versionName instead, that's why we are building a new API for it.
> > So it is not returning a resource, but a resource name that we need it later.
> 
> @Sandido - This is still problematic from ARM perspective. You are creating a new resource type, without full CRUD support. Can you add an OData filter like
> 
> ```
> subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions?{ODATA FILTER FOR VERSION\Latest}
> ```
> 
> and have the client read the name from the version resource?
> 
> Either way, if you can't support the scenario with filter parameters on the version list request, then the better ARM way of doing this is with a POST action on the gallery image instance, like
> 
> ```
> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/getLatestVersionName
> ```
> 
> Otherwise the ARM resource model would point to supporting full CRUD on a new versionName resource type and add a filter parameter on the collection GET for latest:
> 
> ```
> List (Collection GET): /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versionNames
> Singleton (GET and PUT are required, PATCH and DELETE are optional):
> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versionNames/latest
> ```
> 
> But then, what's the point of getting a version name by giving the version name you want?

----

Hey, this ideally needs to be a GET. This shouldn't be a POST imo. 

**Background:**
We have childFanout resource type, and the list versions etc is fanned out to all regions which is not what we want in this case. Also this is not a GET on the versions itself.

**Scenario:**
Our resource hierarchy has images and images have versions. Versions can be published from different regions, and they can be "replicated" to different **target** regions. We want to enable the customer to be able to GET the effective latest version name available for use in a particular **target** region.

I don't see why the ARM is confusing this as a resource type. This is exactly the same case as GET instanceView API on the virtual machine API. Can you check how the below works, and also double check if arm will really get confused? We already tested this out in prod and it was working.
https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/instance-view?tabs=HTTP

**Comment by mentat9** [comment]
> I don't see why the ARM is confusing this as a resource type. ...

ARM isn't confusing this as a resource type: this **is** a resource type according to the Azure RPC. The resource type/instance tuple is a basic ARM contract. GET is for ARM resources which have a resource envelope with (at minimum) name, id, and type at the top-level and RP-specific properties in a property bag. Ref: https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html. GET of the resource type returns a collection of instances, and GET of a resource instance return that resource. Things that aren't ARM resources don't use GET/PUT/PATCH and should use POST instead.

The reason GET "works" is because ARM's behavior when it encounters requests that don't fit the RPC is to route the request to the RP. This allows the request to work, but it means that ARM features often don't work (or work wrong) for those APIs/types.

Your example of instanceView gives a case-in-point for following the RPC instead of replicating existing patterns. InstanceView has caused many issues for ARM because it's a resource type URI/method that's doesn't return a resource type. For example: customers think they should be able to use Azure Policy to manage it but they can't, which leads to customer confusion and frustration.

Note: this comment from @raosuhas https://github.com/Azure/azure-rest-api-specs/pull/20396#issuecomment-1235844513 calling out another RPC anti-pattern also still needs to be addressed.

Tagging @rkmanda (this week's oncall) for visibility.

**Comment by agrawalkshitij** [comment]
> > I don't see why the ARM is confusing this as a resource type. ...
> 
> ARM isn't confusing this as a resource type: this **is** a resource type according to the Azure RPC. The resource type/instance tuple is a basic ARM contract. GET is for ARM resources which have a resource envelope with (at minimum) name, id, and type at the top-level and RP-specific properties in a property bag. Ref: https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html. GET of the resource type returns a collection of instances, and GET of a resource instance return that resource. Things that aren't ARM resources don't use GET/PUT/PATCH and should use POST instead.
> 
> The reason GET "works" is because ARM's behavior when it encounters requests that don't fit the RPC is to route the request to the RP. This allows the request to work, but it means that ARM features often don't work (or work wrong) for those APIs/types.
> 
> Your example of instanceView gives a case-in-point for following the RPC instead of replicating existing patterns. InstanceView has caused many issues for ARM because it's a resource type URI/method that's doesn't return a resource type. For example: customers think they should be able to use Azure Policy to manage it but they can't, which leads to customer confusion and frustration.
> 
> Note: this comment from @raosuhas [#20396 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/20396#issuecomment-1235844513) calling out another RPC anti-pattern also still needs to be addressed.
> 
> Tagging @rkmanda (this week's oncall) for visibility.

Making a GET REST concept POST just because ARM features won't isn't the right solution.  We can't allow this to be a POST and it has to be a GET, as having this API as POST means will require write access for people to call this (readers can't), and users of images just need GET access on images to use images. 

Also, I don't think this **is** a resource type. Resource types are declared by the RP in the RP manifest according to the RPC. Also, Not all resource types require PUT/DELETE/POST etc according to RPC as RPC allows RPs to have GET only proxy resources also, via various routing types. W can register this as location based GET only proxy-resource if required (not sure if this will work).

But due to above constraints, we can't have it as POST and need to be GET. Also, philosophically and conceptually this is a GET. Today people have to list all versions, filter by replication regions, apply some other filters and find the latest on their own by doing just GETs.

**Comment by mentat9** [comment]
> > > I don't see why the ARM is confusing this as a resource type. ...
> > 
> > 
> > ARM isn't confusing this as a resource type: this **is** a resource type according to the Azure RPC. The resource type/instance tuple is a basic ARM contract. GET is for ARM resources which have a resource envelope with (at minimum) name, id, and type at the top-level and RP-specific properties in a property bag. Ref: https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html. GET of the resource type returns a collection of instances, and GET of a resource instance return that resource. Things that aren't ARM resources don't use GET/PUT/PATCH and should use POST instead.
> > The reason GET "works" is because ARM's behavior when it encounters requests that don't fit the RPC is to route the request to the RP. This allows the request to work, but it means that ARM features often don't work (or work wrong) for those APIs/types.
> > Your example of instanceView gives a case-in-point for following the RPC instead of replicating existing patterns. InstanceView has caused many issues for ARM because it's a resource type URI/method that's doesn't return a resource type. For example: customers think they should be able to use Azure Policy to manage it but they can't, which leads to customer confusion and frustration.
> > Note: this comment from @raosuhas [#20396 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/20396#issuecomment-1235844513) calling out another RPC anti-pattern also still needs to be addressed.
> > Tagging @rkmanda (this week's oncall) for visibility.
> 
> Making a GET REST concept POST just because ARM features won't isn't the right solution. We can't allow this to be a POST and it has to be a GET, as having this API as POST means will require write access for people to call this (readers can't), and users of images just need GET access on images to use images.
> 
> Also, I don't think this **is** a resource type. Resource types are declared by the RP in the RP manifest according to the RPC. Also, Not all resource types require PUT/DELETE/POST etc according to RPC as RPC allows RPs to have GET only proxy resources also, via various routing types. W can register this as location based GET only proxy-resource if required (not sure if this will work).
> 
> But due to above constraints, we can't have it as POST and need to be GET. Also, philosophically and conceptually this is a GET. Today people have to list all versions, filter by replication regions, apply some other filters and find the latest on their own by doing just GETs.

OK, thank-you. I appreciate you providing the context and reasoning on this API. @rkmanda will follow this up. Just a few final comments from me to clarify points on the ARM ask/contract:

1. Readers can be given access to POST in the manifest (action method).
2. I agree that sometimes there might be a tradeoff/tension between core ARM features and RP features, but I'm not seeing that in this case. There is an RPC-consistent way of doing what you want.
3. Only tracked resource types and top-level proxy resources are required to be declared in the manifest. Child proxy resource types are not required in the manifest but are still resource types.
4. PUT and DELETE are not required for proxy resource types, but they are required to have name, type, and id in their top-level properties. And they are required to have both a single and collection GET API.
5. Making versionName a new location-based proxy resource type should work (as I mentioned previously), but to follow the RPC it would still need to adopt the proxy resource envelope with RP specific properties in a property bag and implement both point and collection GET endpoints. This is probably more work than using POST.
6. Regarding the solution/philosophy/concepts and ARM/POST vs RP/GET tradeoff: you are saying that versionName should be retrieved by GET because version is retrieved by GET, but versionName is not a real resource type, whereas version is. This distinction matters to the platform you are adding APIs to. GET to an Azure management endpoint with resource-formatted URI is supposed to return an Azure resource (or resource collection in this case), not just any JSON that's useful for the RP and its clients. Customers and platform features depend on this basic RP behavior. The Azure RPC provides POST for APIs that don't follow that pattern: it's an action on a single resource (or at tenant level) that can take any payload and return any payload.

All of that notwithstanding, you can probably make this API work in ARM, even though it will be an outlier from the perspective of expected Azure consistency and behavior.

**Comment by KshitijAgrawal** [comment]
> > > > I don't see why the ARM is confusing this as a resource type. ...
> > > 
> > > 
> > > ARM isn't confusing this as a resource type: this **is** a resource type according to the Azure RPC. The resource type/instance tuple is a basic ARM contract. GET is for ARM resources which have a resource envelope with (at minimum) name, id, and type at the top-level and RP-specific properties in a property bag. Ref: https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html. GET of the resource type returns a collection of instances, and GET of a resource instance return that resource. Things that aren't ARM resources don't use GET/PUT/PATCH and should use POST instead.
> > > The reason GET "works" is because ARM's behavior when it encounters requests that don't fit the RPC is to route the request to the RP. This allows the request to work, but it means that ARM features often don't work (or work wrong) for those APIs/types.
> > > Your example of instanceView gives a case-in-point for following the RPC instead of replicating existing patterns. InstanceView has caused many issues for ARM because it's a resource type URI/method that's doesn't return a resource type. For example: customers think they should be able to use Azure Policy to manage it but they can't, which leads to customer confusion and frustration.
> > > Note: this comment from @raosuhas [#20396 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/20396#issuecomment-1235844513) calling out another RPC anti-pattern also still needs to be addressed.
> > > Tagging @rkmanda (this week's oncall) for visibility.
> > 
> > 
> > Making a GET REST concept POST just because ARM features won't isn't the right solution. We can't allow this to be a POST and it has to be a GET, as having this API as POST means will require write access for people to call this (readers can't), and users of images just need GET access on images to use images.
> > Also, I don't think this **is** a resource type. Resource types are declared by the RP in the RP manifest according to the RPC. Also, Not all resource types require PUT/DELETE/POST etc according to RPC as RPC allows RPs to have GET only proxy resources also, via various routing types. W can register this as location based GET only proxy-resource if required (not sure if this will work).
> > But due to above constraints, we can't have it as POST and need to be GET. Also, philosophically and conceptually this is a GET. Today people have to list all versions, filter by replication regions, apply some other filters and find the latest on their own by doing just GETs.
> 
> OK, thank-you. I appreciate you providing the context and reasoning on this API. @rkmanda will follow this up. Just a few final comments from me to clarify points on the ARM ask/contract:
> 
> 1. Readers can be given access to POST in the manifest (action method).
> 2. I agree that sometimes there might be a tradeoff/tension between core ARM features and RP features, but I'm not seeing that in this case. There is an RPC-consistent way of doing what you want.
> 3. Only tracked resource types and top-level proxy resources are required to be declared in the manifest. Child proxy resource types are not required in the manifest but are still resource types.
> 4. PUT and DELETE are not required for proxy resource types, but they are required to have name, type, and id in their top-level properties. And they are required to have both a single and collection GET API.
> 5. Making versionName a new location-based proxy resource type should work (as I mentioned previously), but to follow the RPC it would still need to adopt the proxy resource envelope with RP specific properties in a property bag and implement both point and collection GET endpoints. This is probably more work than using POST.
> 6. Regarding the solution/philosophy/concepts and ARM/POST vs RP/GET tradeoff: you are saying that versionName should be retrieved by GET because version is retrieved by GET, but versionName is not a real resource type, whereas version is. This distinction matters to the platform you are adding APIs to. GET to an Azure management endpoint with resource-formatted URI is supposed to return an Azure resource (or resource collection in this case), not just any JSON that's useful for the RP and its clients. Customers and platform features depend on this basic RP behavior. The Azure RPC provides POST for APIs that don't follow that pattern: it's an action on a single resource (or at tenant level) that can take any payload and return any payload.
> 
> All of that notwithstanding, you can probably make this API work in ARM, even though it will be an outlier from the perspective of expected Azure consistency and behavior.

Thanks for sharing your opinion! I can see where you are coming from. The ground truths are the following, I think we agree on this:
1) This is a "read"/GET API scenario
2) POST actions are "write" by-default (as confirmed byt the default permissions too)
3) Given that POST itself is outlier in rest concepts, it is possible to virtually replace all APIs with just POST-style API design.

So, the tension here is, IMHO, not between RPC and RP, but RPC and Rest-over-HTTP principles in my opinion. 

But either way, you do bring a good point of RPC providing a consistency and being the reality of azure.

By making this a post, we will have to model a read as a write, and then workaround permissions/throttling etc issues which arise later. 
Can you help us point to how to make the POST Api accessible to readers?

Since, now we are operating in less than ideal world, the reality is also that the API release (march 2023) is late by >6months due to various red-tape and process issues we encountered, and we have an internal service already implementing/waiting on this API contract to deliver the final product by 09/30. So we will do whatever can get us unblocked fast. 
So I would suggest to do the following:
1) Maybe we can continue as GET but back it out of swagger and keep the API exposed to the internal service as GET to avoid missing 9/30 deadline.
2) ARM team will help us to allow readers get access to the POST, and provide guarantees that this would not cause any throttling issues etc by being a POST/write api. Are POSTs treated different in throttling as compared to GETs?
3) Once we have this - we can support POST, move the internal team to use POST and deprecate the GET.
4) Insert this API in next swagger with POST.

Does this sound good to you, or could you please suggest a better way?
Also, Other than this API, do you see any other blockers to let the API-release go forward?

Thanks again for your help!

**Comment by rkmanda** [comment]
>               "$ref": "../../../common-types/v1/common.json#/definitions/CloudError"

change all these to v3

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json:1160 in 77e5c9c. [](commit_id = 77e5c9cd13c9b850f440ea042b790554437a1311, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "GalleryArtifactVersionSource": {

removing uri is a breaking change. Please revert this or get a breakingchanges approval

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json:2753 in 77e5c9c. [](commit_id = 77e5c9cd13c9b850f440ea042b790554437a1311, deletion_comment = False)

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
