### PR TITLE
Change type name 'TrackedResourceLocation' to 'AzureTrackedResourceLocation'

### PR DESCRIPTION
**Pull request by surashed**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by erich-wang — APPROVED** [review]

**Comment by erich-wang** [comment]
It seems the SDK schema failure has nothing to do with this PR, @akning-ms, could you force merge it?

**Comment by akning-ms** [comment]
> It seems the SDK schema failure has nothing to do with this PR, @akning-ms, could you force merge it?

It may impact ARM template, @leni-msft  to take a look

**Comment by leni-msft** [comment]
Hi @erich-wang, it's the BreakingChange failure blocking the PR merge. The schema check is not required currently.
The schema generation failure is not related with this PR. It's caused by enum name conflict in Security's swagger in other apiVersion.

**Comment by leni-msft** [comment]
@surashed pls note. Currently the failing tags (package-composite-v1, etc.) have been [excluded](https://github.com/Azure/azure-rest-api-specs/pull/10615/commits/a6be91069c94b8e574322c6aa850518bf42629d2) from schema generation scope. If your team want to generate ARM template schemas for those apiVersions, you'll need to fix the issues.

**Pull request merged**
