### PR TITLE
Added private IP prefix length to network interface resource.

### PR DESCRIPTION
**Pull request by msfcolombo**
# ARM (Control Plane) API Specification Update Pull Request 

This PR adds the `privateIPAddressPrefixLength` property to `networkInterfaces` resource, to upcoming Microsoft.Network API version 2023-11-01. The property allows customers to allocate a CIDR such as 10.0.0.16/28, instead of just a single IP address, in a network interface, subject to other validations. The new property is optional and can be absent or null on input. It won't be present in the output (response) if the customer is not using the feature. It shouldn't be a breaking change.

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [X] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [X] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [X] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

### CODE REVIEW

**Comment by msfcolombo** [comment]
pr /RequestMerge

**Comment by rkmanda** [comment]
pr /RequestMerge

**Comment by rkmanda** [comment]
The PR is introducing an optional property within the same APi version. Please make this change in a new API version. If you really need to introduce this in the same API version, please get a breaking change approval from the Breaking change review team. The conversation view has a link to the breaking change review documentation.

file:///C:/Users/rmanda/Downloads/Azure%20Versioning%20and%20Breaking%20Changes%20-%20Policy%20Definition%20V1.3.2.pdf

**Comment by msfcolombo** [comment]
> The PR is introducing an optional property within the same APi version. Please make this change in a new API version. If you really need to introduce this in the same API version, please get a breaking change approval from the Breaking change review team. The conversation view has a link to the breaking change review documentation.
> 
> file:///C:/Users/rmanda/Downloads/Azure%20Versioning%20and%20Breaking%20Changes%20-%20Policy%20Definition%20V1.3.2.pdf

@rkmanda  Upon double-checking, we verified this is not the case. Version `2023-11-01` is not on `main` branch yet, therefore this is not a breaking change. It's a new API version.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
