### PR TITLE
New API version for Azure DataProtection 2024-02-01-preview

### PR DESCRIPTION
**Pull request by vaibhav-dhingra**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- For help with Step 2 / "ARM review", see https://aka.ms/azsdk/pr-arm-review.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by ms-zhenhua** [comment]
1. please ensure that the first commit in the PR is an exact copy of the previous API version and all actual changes to the new API version are only added in subsequent commits.
2. please add the new api version into README.

After that, please remove `ARMChangesRequested` label for another review.

**Comment by vaibhav-dhingra** [comment]
For the first comment that was given here by @ms-zhenhua - the first commit is just a base commit which comprises of an exact same copy of the previous version - just with updated api versions

**Comment by ms-zhenhua** [comment]
please fix errors in https://github.com/Azure/azure-rest-api-specs/pull/27963/checks?check_run_id=22108924450

**Comment by hiaga** [comment]
rebase with latest preview and resolve issue with readme

**Comment by TimLovellSmith** [comment]
Why is it currently donotmerge?

**Comment by TimLovellSmith** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/validateForModifyBackup": {

Why this name? Would 'validateUpdate' also make sense? Is it a particular kind of update we're talking about here?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:1372 in dee7fd8. [](commit_id = dee7fd8663b8980de87f6df916c28e396eb9706e, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "type": "string",

I guess it could also have
`"format": "arm-id"`
?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:8558 in dee7fd8. [](commit_id = dee7fd8663b8980de87f6df916c28e396eb9706e, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             ]

Is this modeled on any other particular REST API?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6541 in dee7fd8. [](commit_id = dee7fd8663b8980de87f6df916c28e396eb9706e, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "CmkKekIdentity": {

Have you considered instead referencing

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/customermanagedkeys.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/customermanagedkeys.json)

?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:5867 in dee7fd8. [](commit_id = dee7fd8663b8980de87f6df916c28e396eb9706e, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             ]

Seems superficially similar to this 'infrastructureEncryption' definition, to me:

[https://github.com/Azure/azure-rest-api-specs/blob/bcecb9990214471ee523e643da76a3a7c4170d2f/specification/common-types/resource-management/v5/customermanagedkeys.json#L13](https://github.com/Azure/azure-rest-api-specs/blob/bcecb9990214471ee523e643da76a3a7c4170d2f/specification/common-types/resource-management/v5/customermanagedkeys.json#L13)

can you please explain the intended differences to me?

---
In reply to: [1977511826](https://github.com/Azure/azure-rest-api-specs/pull/27963#issuecomment-1977511826) [](http://example.com/codeflow?ancestors=1977511826)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6541 in aacd253. [](commit_id = aacd253db18d5b901a6fd4a4faa5e38960a0cb7b, deletion_comment = False)

**Comment by vaibhav-dhingra** [comment]
> Why is it currently donotmerge?

The pipelines for validations were not running and I wasn't sure hwo to trigger them. Hence added the DoNotMerge tag.
As per your question for the intended changes in this version, we are introducing new contract named GenericBackupDatasourceParameters and GenericRestoreDatasourceCriteria, and their child classes. All the other changes are taken either from the previous stable version or the previous preview version.

**Comment by vaibhav-dhingra** [comment]
@TimLovellSmith the remaining lintdiff errors that are coming up are for changes that have been present from way back. In this set of api version, we are just introducing 2 new contracts - GenericBackupDatasourceParameters and GenericRestoreDatasourceCriteria, and I don't see any exception for the new contracts that have been introduced. Can we skip the flagged issues created from already merged changes?

**Comment by TimLovellSmith** [comment]
>     "DppBaseTrackedResource": {

Instead of redefining TrackedResource, could you reference the one from common types?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6362 in 3ff2907. [](commit_id = 3ff29077f8268efcaebaf51a2007c155e1c31a54, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "DppProxyResource": {

Instead of redefining ProxyResource, could you reference the one from common types? Is there some blocker?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6435 in 3ff2907. [](commit_id = 3ff29077f8268efcaebaf51a2007c155e1c31a54, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "Error": {

This looks a lot like the ErrorResponse definition from common-types types.json. If its meant to represent a standard Azure error response, can you please reference that instead of defining your own?

Would it involve any breaking change?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6564 in 3ff2907. [](commit_id = 3ff29077f8268efcaebaf51a2007c155e1c31a54, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "$ref": "../../../../../common-types/resource-management/v4/types.json#/parameters/ApiVersionParameter"

(Consider upgrading to v5 common types)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:392 in 3ff2907. [](commit_id = 3ff29077f8268efcaebaf51a2007c155e1c31a54, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "Error": {

To be clear I think you'd want to remove references to 'CloudError' and instead use



---
In reply to: [1981653899](https://github.com/Azure/azure-rest-api-specs/pull/27963#issuecomment-1981653899) [](http://example.com/codeflow?ancestors=1981653899)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:6564 in dd76768. [](commit_id = dd76768c3ee73617ccb052775f39a0e2dc02768e, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>               "$ref": "#/definitions/OperationResource"

Looks like you should probably factor away your own definition of OperationResource and use the OperationStatus definition from commontypes types.json - unless its breaking.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2024-02-01-preview/dataprotection.json:167 in 3ff2907. [](commit_id = 3ff29077f8268efcaebaf51a2007c155e1c31a54, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
> @TimLovellSmith the remaining lintdiff errors that are coming up are for changes that have been present from way back. In this set of api version, we are just introducing 2 new contracts - GenericBackupDatasourceParameters and GenericRestoreDatasourceCriteria, and I don't see any exception for the new contracts that have been introduced. Can we skip the flagged issues created from already merged changes?

In reply to that question, I don't see any mustfix linter warnings from your changes, I think we're good to approve this anyway, after finishing manual review.

**Comment by samsaha-ms** [comment]
@vaibhav-dhingra , there are lint errors which are introduced in current PR, please fix them and remove `ARMChangesRequested` tag for further review.
https://github.com/Azure/azure-rest-api-specs/pull/27963/checks?check_run_id=22328067368
image

**Review by TimLovellSmith — APPROVED** [review]

**Pull request merged**
