### PR TITLE
Azure Communication Services Email API for GA

### LINKED ISSUE #23047: [IC3 ACS Email] API Review
New API Review meeting has been requested.

**Service Name**: IC3 ACS Email
**Review Created By**: Jorge Garcia Hirota
**Review Date**: 3/30/2023 4:00 PM PT
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/22979
**Hero Scenarios Link**: [here](https://github.com/Azure/azure-rest-api-specs/tree/2193d2ff4706dd8460f373594354dd979f8a82eb/specification/communication/data-plane/Email/stable/2023-03-31/examples)
**Core Concepts Doc Link**: Not Provided

**Description**: GA of Email service

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=d939bab0-b4c1-ed11-83ff-000d3a341bd5)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by apattath**
This PR adds the GA version of Azure Communication Services Email API. This is identical to the last public preview version that was released.

# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [x] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc: https://github.com/apattath/azure-rest-api-specs-apfork/blob/main/specification/communication/data-plane/Email/preview/2023-01-15-preview/CommunicationServicesEmail.json
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/23047

### CODE REVIEW

**Comment by JeffreyRichter** [comment]
POST /emails: send
The Operation-ID would ideally not have to be restricted to uuids only.
The default error must be the Azure error type; not "string"

GET /emails/operations/{operationId}
The docs say that operationID is "This is the ID used by the status monitor for this long running operation."
But this could be the Operation-Id value passed in by the customer too, right? It should support this.
The default error must be the Azure error type; not "string"

**Comment by apattath** [comment]
> POST /emails: send The Operation-ID would ideally not have to be restricted to uuids only. The default error must be the Azure error type; not "string"
> 
> GET /emails/operations/{operationId} The docs say that operationID is "This is the ID used by the status monitor for this long running operation." But this could be the Operation-Id value passed in by the customer too, right? It should support this. The default error must be the Azure error type; not "string"

@JeffreyRichter - the Operation-ID was restricted to be a UUID because we use it as our correlation id and an index into the database that stores the message information. Everything in our service is designed around this being a UUID and privacy has classified it as EUPI due to the restriction we've placed on it that we'll only allow UUIDs from the customer. 
As for the default error, I think you might have misunderstood. The type = string is for the "x-ms-error-code" response header, not for the response type itself. 

For the GET endpoint, yes the OperationID is the value that the customer passes in. I'll update the description to read better.
Again even for this endpoint, the type = string is actually for the response header 'x-ms-error-code', not for the error type itself.

**Comment by JeffreyRichter** [comment]
OK on the UUID.

For GET and POST, when I look at your swagger in the editor.swagger.io website, I see "default" Error with an empty JSON object {}. Maybe you're missing a default response JSON referring to the normal Azure error type?

**Comment by apattath** [comment]
> OK on the UUID.
> 
> For GET and POST, when I look at your swagger in the editor.swagger.io website, I see "default" Error with an empty JSON object {}. Maybe you're missing a default response JSON referring to the normal Azure error type?

@JeffreyRichter - not exactly sure how editor.swagger.io website links to models that are referenced from other files using a relative path, but that might be the problem. When I opened just 'communicationServicesEmail.json' on editor.swagger.io, I also see the empty json for the Error model. It seems like that was because it can't resolve the types that I've linked in my swagger that are coming from other json files using relative paths. When I look at my swagger in VSCode preview, I'm able to see the correct types as below:
image

**Comment by apattath** [comment]
> 

Also, I've updated the description of Operation-ID header now.

**Comment by apattath** [comment]
> > 
> 
> Also, I've updated the description of Operation-ID header now.

And in auto-generated SDK, it seems to be generating the models correctly.

**Review by JeffreyRichter — APPROVED** [review]

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
