### PR TITLE
Template Specs: Including "expand" parameter, TemplateSpecVersionInfo model for getting basic version info with template spec(s).

### PR DESCRIPTION
**Pull request by stuartko**
We've had a expand parameter with the possible value of "versions" in our backend for a long while, but it was not documented in the swagger as it was intended for use only through the Portal UI. Due to recent S360 flagging changes, we must now document the expand in the swagger, this PR adds the appropriate definitions to our existing swagger.

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@Tiano2017 , can you please review this PR?  
@stuartko , is this change already implemented in service side?

**Comment by stuartko** [comment]
@raych1 : Yes this is implemented/actively deployed in the service.

I see the changes required tag is present on the PR, but no changes are requested in the conversation unless I'm missing something?

**Comment by raych1** [comment]
Hi @changlong-liu , can you please have a look at this python T2 errors?
```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 45 column 5
```

**Comment by changlong-liu** [comment]
Hi @raych1 , this is a known issue in Track2 codegen.  @jsntcy and I are considering to fix it by upgrading autorest.python.

I think this PR is fine for Python Track2.

**Comment by stuartko** [comment]
@raych1 : Is this good to merge? Anything left to address from our side?

**Comment by raych1** [comment]
> @raych1 : Is this good to merge? Anything left to address from our side?

@stuartko , it looks good to me, can you please ask code owner @Tiano2017 to approve then I can merge it?

**Review by Tiano2017 — APPROVED** [review]
:shipit:

**Review by raych1 — APPROVED** [review]

**Pull request merged**
