### PR TITLE
Disable breaking change job in Network's dev branch

### PR DESCRIPTION
**Pull request by anton-evseev**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
@NullMDR @ArcturusZhang Hi.
Since Network's dev branch is created for upcoming API version, all changes to it would be considered breaking since PRs would just modify it. This would block every PR. This change is to disable breaking changes job to avoid that. Could you please comment on it? Could there be other breaking change scenarios this could let through?

**Review by raych1 — APPROVED** [review]

**Review by raych1 — COMMENTED** [review]
Hold off review since WIP.

**Comment by akning-ms** [comment]
Hi @number213, breaking change job is only detecting breaking change in same version API. sometimes, I found there is some PR in your branch to change swagger for existing API version. so I think it is useful in your branch.

**Comment by number213** [comment]
@akning-ms in this case we'll see breaking change error when we merge back into master

**Comment by akning-ms** [comment]
> @akning-ms in this case we'll see breaking change error when we merge back into master
Yes. I see, but it create more complex when review your PR into master. as I know, once your PR in branch get reviewed. PR reviewer will not pay more attention on your bigger PR into master. right? :)  suggest keep current breaking changing in your branch

**Comment by number213** [comment]
Okay, makes sense

**Pull request closed without merging**
