### PR TITLE
[IC3 ACS - Auth] <stable/2023-08-01> Remove Idempotency Swagger

### PR DESCRIPTION
**Pull request by mjafferi-msft**
# Data Plane API - Pull Request
This PR also includes the removal of the Idempotency Swagger specification, which was ultimately abandoned and never shipped due to unforeseen constraints. We deeply apologize for prematurely merging the Idempotency Swagger into the main branch.

The API version was never made public, so there is no breaking change to customers.

### CODE REVIEW

**Review by mikekistler — CHANGES_REQUESTED** [review]
You cannot rename files that have been merged to main in the public azure-rest-api-specs repo.

API versions that have been merged to main in the public repo are considered to be "released". You must create a new API version and, if necessary, deprecate the existing one through the breaking change review process.

**Comment by DominikMe** [comment]
@mikekistler The delete API version has never been running in production, there is no breaking change to customers. The swagger was checked into the repo prematurely and should never have been merged (we take this as a learning...).
Don't you think that it's better to delete a swagger of a version that never existed rather than keeping it?

**Comment by mikekistler** [comment]
If the API version has never been made public and never will be, then let's handle that separately with a PR that simply deletes that version. That will require breaking change approval and the breaking change board will, begrudgingly, approve it. Then the new API version will have a solid foundation to move forward on.

**Comment by mjafferi-msft** [comment]
@DominikMe @mikekistler Thank you for your inputs and suggestion. I have updated this PR to include only removal of Idempotency API version. Could you please review the PR and provide breaking change approval?

**Comment by mjafferi-msft** [comment]
@mikekistler Thank you for providing breaking change approval. Could you please also approve the PR (it has do not merge label assigned) if changes looks good ?

I'll update the github issue (https://github.com/Azure/azure-rest-api-specs/issues/26005) created for the review meeting with a new PR that will include addition of new scopes for token generation once this PR gets merged.

**Review by maximrytych-ms — APPROVED** [review]

**Comment by jirisofka** [comment]
@mikekistler is there anything preventing the merge of this PR from your point of view?

Thanks!

**Comment by mikekistler** [comment]
@tjprescott This PR is just removing an API version that was never deployed. We don't need API Stewardship Board approval here because there is in effect nothing to review. Please go ahead with the merge on this.

**Review by DominikMe — APPROVED** [review]

**Comment by tjprescott** [comment]
@lmazuel can you please override and merge this?

**Pull request merged**
