### PR TITLE
[Datafactory] Add annotations property to trigger

### PR DESCRIPTION
**Pull request by LijuanZ**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by hvermis — APPROVED** [review]

**Review by praries880 — APPROVED** [review]

**Comment by praries880** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by praries880** [comment]
Go SDK failed because of:
 `INFO:swaggertosdk.autorest_tools:grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/sync:
INFO:swaggertosdk.autorest_tools:	(1) failed to list versions for https://go.googlesource.com/sync: fatal: remote error: Internal Server Error`

Requested a restar of the go sdk build

**Comment by LijuanZ** [comment]
> Go SDK failed because of:
> `INFO:swaggertosdk.autorest_tools:grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/sync: INFO:swaggertosdk.autorest_tools:	(1) failed to list versions for https://go.googlesource.com/sync: fatal: remote error: Internal Server Error`
> 
> Requested a restar of the go sdk build

Hi @praries880 the PR is still blocked by SDK go build, can you help take a look?

**Comment by praries880** [comment]
@jhendrixMSFT Can you kindly kick off the Go build again? Seems me adding `@AutorestCI regenerate azure-sdk-for-go` did not work

**Comment by praries880** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@praries880 hmm it looks like the PR was created, see here https://github.com/Azure/azure-sdk-for-go/pull/4236

**Comment by praries880** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
