### PR TITLE
Update keyvault.json

### LINKED ISSUE #9432: [key vault] vaultUri in resource manager spec must be readonly
For context, a client opened an issue here: https://github.com/Azure/azure-sdk-for-python/issues/11333.

The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1107) has vaultUri defined as just a string. In order to make it readonly, a line like [this](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1160) needs to be added to its swagger definition

Seeing this for at least API version 2019-09-01.

### PR DESCRIPTION
**Pull request by jlichwa**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by heaths — APPROVED** [review]
While correct, I wonder if this will yield breaking APIs for generated clients, e.g. in C# this goes from `public virtual string VaultUri { get; set; }` to `public virtual string VaultUri { get; }`, which is a breaking change.

That said, hopefully this is easiest enough to workaround, but we may want to get @allenjzhang's opinion on this if it will cause issues for the management SDKs (though, the track 2 versions are in preview).

**Comment by jlichwa** [comment]
# #9432

**Comment by markcowl** [comment]
@jlichwa While we appreciate the correction to Swagger, this will undoubtedly cause some breaking changes in member visibility in some languages.  I don't think we should merge this.

**Comment by jlichwa** [comment]
> @jlichwa While we appreciate the correction to Swagger, this will undoubtedly cause some breaking changes in member visibility in some languages. I don't think we should merge this.

@markcowl since it is actual behavior of the service (it is read only on service side) and I was advised by engineering team to do that (@RandalliLama ) and there is issue created from SDK (https://github.com/Azure/azure-rest-api-specs/issues/9432). What are the other options, should we keep it like that forever or just postpone?

**Comment by heaths** [comment]
If a client sets it, the service will fail. It should fail with an error message that should obviously state it's read only. It could mention the docs are incorrect.

There's no data loss or other bad ramifications here, so it's probably fine to leave as-is and update the docs to say it's read-only.

**Comment by jlichwa** [comment]
> If a client sets it, the service will fail. It should fail with an error message that should obviously state it's read only. It could mention the docs are incorrect.
> 
> There's no data loss or other bad ramifications here, so it's probably fine to leave as-is and update the docs to say it's read-only.

Is in it better to "fail" fast and not let clients set it ? I can change description, but not everybody goes to documentation. It will be good to figure out how to address it in the future. If we change service to throw an error vs ignoring - that would be breaking change also.

**Comment by heaths** [comment]
> Is in it better to "fail" fast and not let clients set it ?

In general, yes. But we also have guidelines about client-side validation since that creates a tight coupling with the service and makes it hard to support multiple versions in an SDK. This is only slightly similar.

What's worse, however, is breaking customers' existing applications. Changing this to a read-only property now will do just that.

**Comment by jeking3** [comment]
@markcowl I could not tell which property changes you were referring to.  I use the python SDK and use the _attributes stanza generated by the SDK to learn which fields are read-only so I can ignore them when I am calculating a difference, so the SDK as it is without these changes breaks my logic, and the correct setting of marking the vault_uri read-only would fix this.  In particular the key vault vault_uri property.  It is provided by the server and cannot be set, so it should be read-only.  See https://github.com/Azure/azure-rest-api-specs/issues/9432 - just changing the description is insufficient.

**Comment by heaths** [comment]
[SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html#dependable) state we should not make breaking changes without strong justification. Changing a currently read-write property to read-only will be a breaking change across SDKs, especially for strongly-typed languages. Comparatively, how is setting what is treated as a read-only property to some other value breaking?

**Comment by jeking3** [comment]
Correct, because there is a bug in the existing specification that makes it look like vault_uri can be set, but it cannot.  For the python SDK, when the client sets a readonly property, the framework issues a warning.  I do not know how other language implementations behave.  Right now the property is not readonly so no warning is issued, and therefore someone would have no idea they are doing something that has no effect.  However if the property is marked readonly, it will correctly issue a warning.  So at least for the python SDK, this is _not_ a breaking change.

**Comment by heaths** [comment]
Changing a property from read-write to read-only is a breaking change in all languages. Setting it may not effectively do anything but if you make the property read-only, code will no longer compile or run (if, for example, a runtime dependency is updated in-place).

Changing the version doesn't make this less of a breaking change. Using any package manager, if the dependency is updated, older code would no longer compile without changes. We still avoid breaking changes across versions unless absolutely necessary, and so far I don't understand how setting this value rises above that bar. It won't effectively cause any issues. Is the swagger wrong? Absolutely. But does it cause an inherent and real problem?

**Comment by jeking3** [comment]
Does it cause an inherent and real problem?  Yes, however it is clear you consider it to be too minor to resolve.  It causes the python generated SDK attribute map to be incorrect, however since that map is a private variable inside generated code that I am leveraging from outside the library, and the SDK does not provide an official way to determine which fields are readonly or not using the SDK, I guess the happy medium here is to update the documentation but leave the swagger incorrect.

I can dynamically inject the right information into the library when it gets loaded and fix the problem for myself, which is what I had already done to get around this bug in the REST specification.

A change like this could be left queued up for any major version bump that may happen in the future, instead of being simply resolved with a documentation change.  At some point there will be enough substantive changes to fix this properly when something else is deemed necessary to change?

**Comment by markcowl** [comment]
Closing this PR as we all agree it should not be merged.  If you would like to track a future swagger change, I would suggest failing an issue and assigning to your team.

**Comment by jlichwa** [comment]
@markcowl why closed, I changed it to just add description.

**Comment by jlichwa** [comment]
@markcowl can we merge it? It is just updating description.

**Review by markcowl — APPROVED** [review]

**Comment by markcowl** [comment]
@jlichwa this can be merged once the checks pass

**Pull request merged**
