### PR TITLE
Remove uiDefinitionUri property from managed app responses and add new api version 

### PR DESCRIPTION
**Pull request by olsoro**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by olsoro** [comment]
@vivsriaus please review

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
Please update the [README](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/readme.md) with this new API version.

**Comment by vivsriaus** [comment]
LGTM

**Comment by olsoro** [comment]
@jhendrixMSFT - Please take a look, I've addressed your comment.

**Comment by jhendrixMSFT** [comment]
@olsoro Thanks that part looks good.  Can you please take a look at the linter and model validation failures in [CI](https://travis-ci.org/Azure/azure-rest-api-specs/builds/385853412?utm_source=github_status&utm_medium=notification), specifically the ones where PR_ONLY=true.

**Comment by olsoro** [comment]
@jhendrixMSFT  Those failures are not related to my changes, can we ignore them?

**Comment by jhendrixMSFT** [comment]
@olsoro We can but please note that the expectation is for new swaggers and/or API versions they should be linter/modeler clean, and these issues will be reported in S360.
At a minimum the [semantic validation](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/385853416) errors must be fixed.  For this issue you want to use the [x-ms-paths](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-paths) extension with a dummy query param to distinguish the two cases.  It would also be ideal to add a regex that validates the path param ID conforms to the expected pattern but that's not a blocking issue.

**Comment by jhendrixMSFT** [comment]
Here's an [example](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datalake-analytics/data-plane/Microsoft.DataLakeAnalytics/stable/2016-11-01/catalog.json#L3064) using x-ms-paths.  Since your query params are dummies to distinguish the cases omit the "op" query param.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
