### PR TITLE
Fix discriminator problem introduced by #8606

### PR DESCRIPTION
**Pull request by ArcturusZhang**
This PR fixes the discriminator problem introduced by #8606 which is blocking the SDK upgrade in `terraform-azurerm-provider` - an object has a discriminator but does not have any sub-types.

I mimicked the pattern of the swagger in the same RP, introduce three new object: `Nfs3TargetProperties`, `ClfsTargetProperties` and `UnknownTargetProperties`. They have exactly the same properties as `StorageTargetProperties` and just use to serve the discriminator.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Please do not merge this PR until the corresponding service team had a look at this and approved.

**Comment by romahamu** [comment]
Looks good, thank you.

**Review by ChenTanyi — COMMENTED** [review]
I think it should be better changed in generator rather than swagger. It is confused to add these three properties, since they are never used.

**Comment by njuCZ** [comment]
@ChenTanyi these three fields are `polymorphism` of `StorageTargetProperties` in `StorageTarget`, there is som problem with the grammar of discriminator. we are just fixing them, not add new fields

**Comment by ChenTanyi** [comment]
@njuCZ Since these three fields are exactly same, I don't think they bring any `polymorphism`. 

It is just used for fixing the generator bug, but I think generator bug should be fixed by change generator rather than swagger, since changing swagger will affect all SDK which would generate many useless fields.

**Comment by ArcturusZhang** [comment]
Please refer to [this PR](https://github.com/Azure/azure-rest-api-specs/pull/10392) as reference. This discriminator is by service team's design and exists in all the api-version, not just introduced by this PR. 
Previously this discriminator already exists but since it is not well-formed and ignored by the code generator - in this part I agree the code generator should be updated, it should throw an error rather than silently ignore the malformed discriminator.
Here I must say that the service team has approved this, which indicates this not-so-reasonable discriminator is the result what the service team would like to see. If you have more questions, please go to the internal email thread and directly raise them to the service team. Thanks

**Pull request closed without merging**
