### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to add version stable/2018-03-01

### PR DESCRIPTION
**Pull request by yashmuel**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/yashmuel/azure-rest-api-specs/dev-monitor-Microsoft.Insights-2018-03-01-yashmuel...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by mmyyrroonn — CHANGES_REQUESTED** [review]
Please remove submodule

**Comment by MyronFanQiu** [comment]
@yashmuel Do we still need this PR?

**Comment by MyronFanQiu** [comment]
@yashmuel I closed this PR and if you still need this one, feel free to reopen it.

**Comment by yashmuel** [comment]
> Please remove submodule

what do you mean remove submodule?

**Comment by yashmuel** [comment]
> > Please remove submodule
> 
> @MyronFanQiu what do you mean remove submodule?

**Comment by MyronFanQiu** [comment]
image
Please solve CI issues as well.

**Comment by yashmuel** [comment]
> image
> Please solve CI issues as well.

@MyronFanQiu removed sub module. I'm trying to pass these checks, but think i'm in deadlock.
is there someone i can consult with?

**Comment by yashmuel** [comment]
The thing is that i've created a new definition MetricAlertPropertiesPatch which i'll use in patch instead of MetricAlertProperties
and i got a "swagger breakingChange" which said that integer should has a format (which is not true for MetricAlertProperties)
so I've added "int32" format, but now getting a breakingChange that "The new version has a different format than the previous one."
not sure how can i resolve this issue, do you know a way?

**Comment by MyronFanQiu** [comment]
Copy and paste in PR comment: “As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ Breaking Change Process”

**Comment by MyronFanQiu** [comment]
https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes

**Comment by yashmuel** [comment]
> https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes

@MyronFanQiu  i can understand the breaking change thing, but i don't understand why in MetricAlertProperties definition the severity field without any format (probably created before the breaking change), but when i'm creating the new definition MetricAlertPropertiesPatch i cannot do the same?
so these breaking change process prevent me to do my change, i don't have any work around for this. 
can you think of one?

**Comment by MyronFanQiu** [comment]
> > https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes
> 
> @MyronFanQiu i can understand the breaking change thing, but i don't understand why in MetricAlertProperties definition the severity field without any format (probably created before the breaking change), but when i'm creating the new definition MetricAlertPropertiesPatch i cannot do the same?
> so these breaking change process prevent me to do my change, i don't have any work around for this.
> can you think of one?

Breaking Change Review Process is onboard recently. You can ask for the permission to merge breaking change.

**Comment by yashmuel** [comment]
@MyronFanQiu  where can i ask for this permissions?

**Comment by MyronFanQiu** [comment]
@yashmuel. Sorry about that. I missed the link. https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes

**Comment by yashmuel** [comment]
Hi @MyronFanQiu 
This change is not a breaking change, as we're only changed the Patch API which wasn't supported until now.
Currently the API is not consistent with our service.
Can we merge this PR without going through the breaking change process which not need here?

**Review by JeffreyRichter — APPROVED** [review]

**Comment by yashmuel** [comment]
@MyronFanQiu  Hey, i've got a breaking changes approval, what's next step?

**Comment by yashmuel** [comment]
@MyronFanQiu kindly ping

**Pull request merged**
