### PR TITLE
[DataFactory]Add Binary Dataset in swagger

### PR DESCRIPTION
**Pull request by TinaHu1**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by KrisBash — APPROVED** [review]
No concerns with the definitions defined, although it is unclear to me how they are used if not referenced in API request/response. I assume an enum needs to be updated in a future iteration?

**Comment by TinaHu1** [comment]
> No concerns with the definitions defined, although it is unclear to me how they are used if not referenced in API request/response. I assume an enum needs to be updated in a future iteration?

About the referenced,, we use "x-ms-discriminator-value" to extend the "Dataset", and the "Dataset" has already referenced in API request at specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json. So the newly added one can be used in API request. DataFactory always add new connector by this way because we add new connector type in high frequency.

**Comment by TinaHu1** [comment]
@praries880 Could you help merge this PR? Thanks.

**Comment by TinaHu1** [comment]
@praries880 Could you help merge this PR? We need to merge this change as soon as possible for our SDK release. Thanks!

**Review by praries880 — APPROVED** [review]

**Pull request merged**
