### PR TITLE
Update the SECP256K1 to P-256K

### PR DESCRIPTION
**Pull request by prashanthyv**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by lmazuel** [comment]
@prashanthyv you introduce a breaking change in an old version of KV data-plane.
This means that anyone using this Swagger won't be able to send "SECP256K1" on the wire anymore, but instead they can send "P-256K". Is this really what the endpoint can handle?

Note that this Swagger is still used to communicate with Azure Stack, so it cannot be changed only for documentation purposes, it has to be exact accurate truth of the behavior of "2016-10-01". So this PR means "Sending SEC256K1 was never possible ever, and it was a typo in the spec, and if you try it now it will be refused by our endpoint". Is that so?

**Comment by RandalliLama** [comment]
@lmazuel Are you really saying that we can't even update comments/docs in the swagger, with no other changes, without breaking stack?  In other words, we can't improve our existing documentation without breaking stack?

**Comment by lmazuel** [comment]
@RandalliLama Swagger is not documentation of a RestAPI, it's a description of the exact behavior of a RestAPI. We do documentation out of that, which is not exactly the same thing. If you update a "description" node, that's pure documentation. If you update a class name or class content, it has to still reflect the reality of the behavior of the endpoint. 
And it's not just Stack, we know direct users of Swaggers, and nothing force then to move to 7.0 until the API 2016-10-01 is deprecated. As long as your server support this API, Swagger needs to be truth of this endpoint.
There is syntax to still improve the documentation and still be accurate in representation, so I'm not concerned we'll find the right thing to do here. :). But it's probably not the initial PR suggestion.

@msfcolombo To rewrite what I understand (and then I can suggest the best way to do so):
In 2016-10-01, your server accepts 5 values for JsonWebKeyCurveName: "P-256", "P-384", "P-521", "SECP256K1" and "P-256K". But you want people to not use "SECP256K1", since it was preview, and it will be removed from the server at some point (undetermined yet). Your problem is that the documentation should not mention "SECP256K1" then.
Is this correct?

**Comment by msfcolombo** [comment]
@lmazuel Yes. We also don't want new versions of the client to send that value to the server. It's a breaking change from client's PoV.

**Comment by lmazuel** [comment]
@msfcolombo The approach we'd recommend with @johanste is to be transparent with customers (documentation, or Swagger users):
- Put the 5 values in the Swaggers. The correct Swagger is wrong anyway, if you support "P-256K" and it's not here.
- Change the description of "SECP256K1" to something like "This is legacy configuration preview option and should not been used. It has been removed from recent API and might be decommissioned for this API version at any time". Put the wording in good English with scary warnings :)

I think this solves all your troubles:
- This is still backward compatible, and you don't break any people
- You provide a new value P-256K for people to use
- You still doesn't confuse people who could maintain old integration and would see this option in code. This is still documented. Out of documentation, this would become a documentation problem (which is a paradox here...)
- You put in place a clear deprecation policy, in both documentation and SDK.

**Comment by prashanthyv** [comment]
@lmazuel - I don't mind updating the document to be backward compatible with respect to description. 
I'll give a new PR. 

Thanks

**Comment by lmazuel** [comment]
You don't have to do a new PR though, just update this one.

**Comment by lmazuel** [comment]
@prashanthyv update?

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by prashanthyv** [comment]
@lmazuel  - I thought Fernando already took care of this

**Comment by msfcolombo** [comment]
@prashanthyv Please drop this PR. We need to work on a different kind of change. Thanks.

**Pull request closed without merging**
