### PR TITLE
Xynoclafe/2020 06 version

### PR DESCRIPTION
**Pull request by Xynoclafe**
Adds changes from 2019-10-01 missed in the new version
- #9441 
- #9580 

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by filizt** [comment]
There are 3 changes in this PR:
* Commits https://github.com/Azure/azure-rest-api-specs/pull/9888/commits/63750020b7072feeeabb8e7250ba32139cf42dbf and https://github.com/Azure/azure-rest-api-specs/pull/9888/commits/d09f5ad988d3bf367b10745c204498452b7ca5bb are for porting over the diff between 2019-10-01 API version and 2020-10-01 API version swaggers. 
* Commit https://github.com/Azure/azure-rest-api-specs/pull/9888/commits/544ccacf4eba646206fffab2147bb6e1669c2575 is for removing the Java SDK support for the 2020-06-01 API version.

The SDKs for the new API version 2020-06-01 haven't been released yet, so these changes are not breaking changes. FYI.

**Comment by raych1** [comment]
@filizt , can you share the reason of removing Java SDK support?

**Comment by filizt** [comment]
> @filizt , can you share the reason of removing Java SDK support?

@raych1 Supporting Java SDK requires some changes to be done in the swagger but given that we don't have a hard requirement to release a Java SDK at the moment, we'd like to remove the support for it along with the changes. We can evaluate and release it, if there is a need in the future.

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
@akning-ms , the breaking change is about reverting previous changes: one is to removing JAVA SDK support in readme and the other is to revert the parameter name change which was approved in another api version. These changes doesn't have impacts on service side and only impact SDK side. Please help force merge this PR, thanks.

**Pull request merged**
