### PR TITLE
Swagger specification for Service Fabric runtime version 6.5

### PR DESCRIPTION
**Pull request by amanbha**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by amanbha** [comment]
These are not ARM APIs. These are Service Fabric runtime apis for 6.5 release

**Comment by nschonni** [comment]
@amanbha  looks like there are few small typos in the descriptions and model names https://dev.azure.com/azure-sdk/public/_build/results?buildId=49399&view=logs&jobId=eca5a1cb-f12a-57d8-9254-390bd587c201

**Comment by amanbha** [comment]
> @amanbha  looks like there are few small typos in the descriptions and model names https://dev.azure.com/azure-sdk/public/_build/results?buildId=49399&view=logs&jobId=eca5a1cb-f12a-57d8-9254-390bd587c201

Thanks, I have pushed changes to fix the typos.

**Comment by amanbha** [comment]
@jeffj6123 fyi.

**Comment by amanbha** [comment]
@nschonni, @samedder could you please approve this?

**Review by kpajdzik — APPROVED** [review]
Two things:

1. GetUnplacedReplicaInformation:
I think `"$ref": "#/parameters/ApiVersion_6-4_RequiredQueryParam"` should be changed to `"$ref": "#/parameters/ApiVersion_6-5_RequiredQueryParam"`

2. ToggleVerboseServicePlacementHealthReporting
`"$ref": "#/parameters/ApiVersion_6-4_RequiredQueryParam"` -> `"$ref": "#/parameters/ApiVersion_6-5_RequiredQueryParam"`

**Comment by amanbha** [comment]
@kpajdzik  Thanks for approving it, does it needs be blocked on an approval from @samedder or you can merge it.

**Comment by kpajdzik** [comment]
> @kpajdzik Thanks for approving it, does it needs be blocked on an approval from @samedder or you can merge it.

I can merge it. Do you want to fix two things I pointed first?

**Comment by amanbha** [comment]
> @kpajdzik Thanks for approving it, does it needs be blocked on an approval from @samedder or you can merge it.
> 
> I can merge it. Do you want to fix two things I pointed first?

@kpajdzik Those apis existed in service fabric 6.4 runtime release, but were not added to swagger specification, we are adding them to swagger spec now. The apis will work with query parameter: api-version=6.4, so please merge the PR without those suggested changes.

**Pull request merged**
