### PR TITLE
[Hub Generated] Review request for Microsoft.DigitalTwins to add version stable/2020-10-31

### PR DESCRIPTION
**Pull request by sjiherzig**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/sjiherzig/azure-rest-api-specs/dev-digitaltwins-Microsoft.DigitalTwins-2020-10-31...master/).

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by sjiherzig** [comment]
Validation tools were run, but an exception occurred when running the linter in OpenApi hub: x-ms-secret was not recognized as a valid extension when checking against the schema.

**Comment by erich-wang** [comment]
@sjiherzig, do you plan to release SDKs for this version after merging this PR? Please update readme.md if your answer is yes.

**Comment by sjiherzig** [comment]
> @sjiherzig, do you plan to release SDKs for this version after merging this PR? Please update readme.md if your answer is yes.

Thanks! I've updated the readmes accordingly.

**Comment by erich-wang** [comment]
@sjiherzig, if you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

**Comment by chiragg4u** [comment]
Changes looks good. Marked it as ARMSignedoff.

**Comment by sjiherzig** [comment]
@erich-wang What would be the next step? We're all set for merging in our changes, I think.

**Comment by erich-wang** [comment]
@sjiherzig, I'm going to merge this PR, but I noticed that the API version is 2020-10-31, please let me know if this PR is ready to merge from service team perspective.

**Comment by sjiherzig** [comment]
@erich-wang I discussed it internally, and we are ready to merge!

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
