### PR TITLE
Adding new API 2018-06-30 for automation

### PR DESCRIPTION
**Pull request by vrdmr**
### Description

Adding new API version for Automation 2018-06-30.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by vrdmr** [comment]
This change has already been approved by @ravbhatnagar in #3325. @khughes66 and I are creating a new PR with fixes to resolve the Travis issues hit the earlier PR. We'll close #3325 now.

**Comment by vrdmr** [comment]
@marstr This PR is a copy of #3325. I think the PR was too old and did not have all the changes made in Automation's spec, which were causing Travis issues. This new PR has all the changes and passes Travis.

**Comment by khughes66** [comment]
@azuresdkci , @jianghaolu : Please review asap.  This has been sitting like this for days.

**Review by vrdmr — COMMENTED** [review]
LGTM

**Review by marstr — APPROVED** [review]
Chatted offline with @khughes66, and I've verified that indeed @ravbhatnagar signed off on these changes in the former PR.

**Pull request merged**
