### PR TITLE
swagger changes for cloudservice new get calls

### PR DESCRIPTION
**Pull request by sharufbaig**
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR
This PR contains a new api defined using the Extension Resource design to support Get calls on Cloud Service networking resources.  [Design Doc Link](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoftapc-my.sharepoint.com%2F%3Aw%3A%2Fg%2Fpersonal%2Fsharufbaig_microsoft_com%2FEZBuhCit0b9FitQlTv6FhvMBdtI7Sp2RfbwjIEtMTh-Fdg&data=05%7C01%7Csharufbaig%40microsoft.com%7C2d91d8d448624ff564a808dade845652%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638066957214802007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xgTCCpIjB3SGjg%2FGuPOiOaxawvcPAOs060SPUVuUN2Q%3D&reserved=0)

[Swagger changes in private branch](https://github.com/Azure/azure-rest-api-specs-pr/pull/10818) 
What's the purpose of this PR? Check all that apply. This is **mandatory**!
  - [x] new service onboarding
  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by Joanna-Yang-Art** [comment]
Hi @sharufbaig could you please set the priority to merge this PR by 7/12? As we will complete on 7/13

**Comment by sharufbaig** [comment]
[like]  Sharuf Baig reacted to your message:
________________________________

**Comment by sharufbaig** [comment]
We need the same swagger specs as [cloudServiceNetworkInterface](https://github.com/Azure/azure-rest-api-specs/blob/release-network-Microsoft.Network-official-2023-04-01-2/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/cloudServiceNetworkInterface.jsonl) and [cloudServicePublicIpAddress](https://github.com/Azure/azure-rest-api-specs/blob/release-network-Microsoft.Network-official-2023-04-01-2/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/cloudServicePublicIpAddress.json) for the newly defined properties cloudServiceNetworkInterfaceList and clouServicePublicIpAddressList but the lintdiff asks for ResourceNameRestriction which was not defined earlier. @rkmanda so can i ignore that validation?

**Comment by sharufbaig** [comment]
Hi @Joanna-Yang-Art  i am waiting for reviews. ill complete as soon as i get it reviewd

**Comment by sharufbaig** [comment]
Hi @rkmanda  : Could you please review the changes? Thanks!!

**Comment by Joanna-Yang-Art** [comment]
@sharufbaig could you merge the PR? We are going to complete the release by 3 pm today

**Comment by raosuhas** [comment]
Can you please fix the newly introduced lintdiff errors : https://github.com/Azure/azure-rest-api-specs/pull/24726/checks?check_run_id=14968875680

**Review by rkmanda — APPROVED** [review]
:shipit:

**Pull request closed without merging**
