### PR TITLE
{Resources/resources] Fixed TagCount value property

### PR DESCRIPTION
**Pull request by mcardosos**
Related to [issue 845](https://github.com/Azure/azure-rest-api-specs/issues/845)

PTAL @amarzavery @vivsriaus @TianoMS

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by TianoMS** [comment]
The change looks good to me.

**Comment by johanste** [comment]
Agreed, changes look good. Just checking the internal process for merging a change that has a breaking change (since switching a data type of a property is a breaking change for some generated libraries - thus the breaking change label was applied). I believe the different language SDK owners are supposed to give a thumbs up after they have decided if they need to bump versions their libraries.

**Comment by TianoMS** [comment]
@johanste Thanks for pointing out. I double checked on it, and it's indeed a breaking change. Today in our SDKs we generate this property as String type. If we change it it's going to be Int type. This would potentially break applications that use our SDKs. 

Given that, we'll have to update our api-version if we want to make this change. Suggestion is to postpone this change to our next api-version update. @mcardosos let me know if you have any concern.

**Comment by johanste** [comment]
Assuming that the resource provider is currently returning a number and not a string, you shouldn't have to update the API version. What may have to be updated, though is the major version of the client management library. Not all breaking changes from the REST API perspective are breaking for generated client libraries. And some changes to the swagger document (even if they are correcting the description of the REST API for a given endpoint) are breaking to the client library. It is complicated :)

On the other hand, if the proposal is to also make a server side change to change the type of the returned data, then, yes, the API version would have to be bumped.

**Comment by TianoMS** [comment]
Service is returning a number currently. I think I get your point. We don't need to update API version, but we need to update the major version of client libraries. My question is, we automatically generate some of the client SDKs once this swagger spec is updated, is that a problem?

**Review by johanste — APPROVED** [review]

**Comment by mcardosos** [comment]
Thanks for merging :)

**Pull request merged**
