### PR TITLE
Remove vladbarosan from codeowners

### PR DESCRIPTION
**Pull request by vladbarosan**
If this gets regenerated periodically, let me know how I can avoid getting pulled in please :)

### CODE REVIEW

**Comment by vladbarosan** [comment]
@bsiegel ping ( btw I joined the azure sdk team so I presume if this regenerates automatically, all should be good )

**Comment by vladbarosan** [comment]
@shawns1  , can you help approving this please ?

**Review by bsiegel — APPROVED** [review]
:+1: :shipit: 

Please pull and rebase on latest master, squash fixups, and merge!

**Comment by vladbarosan** [comment]
There has not been any updates to the file since it was added so I think we are good to go :)

**Pull request merged**
