### PR TITLE
Fixed invalid type errors in bbox examples

### PR DESCRIPTION
**Pull request by stevemunk**
# Data Plane API - Pull Request

**NO CHANGES TO ANY API, ONLY THE CODE EXAMPLES.**

fixed invalid type errors in bbox examples and removed the suppressions in the readme files.

See [PR 27357](https://github.com/Azure/azure-rest-api-specs/pull/27357#pullrequestreview-1840050198)

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

<details>
  <summary>Checks stuck in `queued` state?</summary>
If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.  
</details>

### CODE REVIEW

**Comment by scbedd** [comment]
Hey @stevemunk I'll take a look at the new errors. Thank you very much for submitting the PR! 

Thankfully no failures on `WFS_GetFeatures`.

**Comment by stevemunk** [comment]
> Hey @stevemunk I'll take a look at the new errors. Thank you very much for submitting the PR!
> 
> Thankfully no failures on `WFS_GetFeatures`.

@scbedd, @eriklindeman: Most of the [errors](https://github.com/Azure/azure-rest-api-specs/pull/27516/checks?check_run_id=20824658208) originate in swagger files that are not even used and never will be used (all of them in the [microsoft.maps](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps/data-plane/Microsoft.Maps) directory). I think we will either have to create a readme.md file for each of these bogus swaggers and add a suppression in each of them, or if possible, convince the owners of these services to remove these files. The remaining two errors are due to the swagger incorrectly [defining the bbox parameter as a string](https://github.com/Azure/azure-rest-api-specs/blob/863f1864409eced0e3416021f375b65681999202/specification/maps/data-plane/Microsoft.Maps/Render/preview/1.0/render.json#L380), and [the example implementing it as an array of doubles](https://github.com/Azure/azure-rest-api-specs/blob/863f1864409eced0e3416021f375b65681999202/specification/maps/data-plane/Microsoft.Maps/Render/preview/1.0/examples/GetMapImage.json#L6:13).

**Comment by scbedd** [comment]
Oh boy this was a whole barrel of fun.

So it seems this API has some amount of flux in _what_ `bbox` as a parameter is defined to be. Lets take

`specification/maps/data-plane/Creator/preview/2.0/wfs.json` which corresponds to `WFS_GetFeatures.json` example. There, `bbox` is defined to be:
image

Which corresponds to the update you made in `WFS_GetFeatures.json` to make `bbox` parameter value an **array**. 

However, in the other updated examples:

- `specification/maps/data-plane/Microsoft.Maps/Render/preview/1.0/examples/GetMapImage.json`
- `specification/maps/data-plane/Microsoft.Maps/WFS/preview/2.0/examples/GetItems.json`

Which correspond to specs:

- `specification/maps/data-plane/Microsoft.Maps/Render/preview/1.0/render.json`
- `specification/maps/data-plane/Microsoft.Maps/WFS/preview/2.0/wfs.json`

`bbox` is a **string**

image

So those `bbox` parameters should be left alone.

Now, in my local testing, I've also discovered issues with `specification/maps/data-plane/Microsoft.Maps/Render/preview/1.0/render.json` OTHER THAN what is currently being thrown, so I am checking those out right now.

I'll leave a comment with the full diff of how I updated this to get it green when I have it.

**Comment by scbedd** [comment]
Ok, this gets it green. I feel like these changes make sense, but it's also changing a `spec`...even if it's very very old and unused.

image

image

image

**Review by mikekistler — APPROVED** [review]
Looks good! 👍 

Thanks for making these changes!

**Pull request merged**
