### PR TITLE
Add odatatype for Url Signing Action

### PR DESCRIPTION
**Pull request by gubalasu**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ChenTanyi** [comment]
@gubalasu is this property readonly?

**Comment by gubalasu** [comment]
> @gubalasu is this property readonly?

This is a property that the customers have to supply when they are making this call. And the value of the property is the one mentioned in the enum. I am not very sure what you meant by readonly. But I hope this answers your question

**Comment by ChenTanyi** [comment]
@gubalasu readonly means the property could only be return by service, and could not change by the client side.

Since there is only one possible value for the enum, (And could not add new enum value due to it is not modelAsString) I think it is no need for the sending by client side.

**Comment by gubalasu** [comment]
> @gubalasu readonly means the property could only be return by service, and could not change by the client side.
> 
> Since there is only one possible value for the enum, (And could not add new enum value due to it is not modelAsString) I think it is no need for the sending by client side.

We are checking for the odatatype in the Resource Provider. We do this because the action can have multiple different types. One such type is UrlSigning. For other action types we have different odatatype and they are defined seperately. So this field is a required field.

**Review by ChenTanyi — APPROVED** [review]

**Pull request merged**
