### PR TITLE
update readme for sdk generation

### PR DESCRIPTION
**Pull request by marwanad**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by marwanad** [comment]
@NullMDR any idea why the python one would fail?

**Comment by NullMDR** [comment]
@marwanad Because your readme.md has no input file for tag package-2020-09-01-only. See https://github.com/Azure/azure-rest-api-specs/pull/10636#issuecomment-682948208

**Comment by marwanad** [comment]
@NullMDR the entry is there in the base branch: https://github.com/Azure/azure-rest-api-specs/blob/dev-containerservice-Microsoft.ContainerService-2020-09-01/specification/containerservice/resource-manager/readme.md

**Comment by marwanad** [comment]
oh I see it now. I need the `-only`

**Comment by marwanad** [comment]
@NullMDR Can you take a look now? Linter is complaining for unrelated older APIs imported.

**Comment by NullMDR** [comment]
@jianyexi Could you please help to look at this issue? The unified pipeline result passed but old pipeline failed.

**Comment by jianyexi** [comment]
> @jianyexi Could you please help to look at this issue? The unified pipeline result passed but old pipeline failed.

This LintDiff  error could be ignore , as the `~[Staging] Swagger LintDiff`  has passedd

**Comment by marwanad** [comment]
@NullMDR @jianyexi if those errors can be ignored, can we get this PR merged then?

**Review by PhoenixHe-NV — APPROVED** [review]

**Pull request merged**
