### PR TITLE
Model ContainerNic refs under ContainerNicConfig as sub resources

### PR DESCRIPTION
**Pull request by Flip-Liquid**
Modelling container nic children on container nic configs as resource ids only to fix a circular reference issue.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Will merge when CIs pass

**Comment by jcgknudson** [comment]
Thanks @dsgouda

**Comment by MikhailTryakhov** [comment]
@dsgouda looks like this merge was incorrect because it was merged to ```2018-08-01``` folder instead of ```2018-10-01```
Please confirm and provide Jack with steps need to be done to revert these changes

**Comment by MikhailTryakhov** [comment]
@dsgouda  looks like there is PR with a correct fix https://github.com/Azure/azure-rest-api-specs/pull/4463/files 
so we just need to revert this merge

**Comment by jcgknudson** [comment]
@MikhailTryakhov, please see https://github.com/Azure/azure-rest-api-specs/pull/4467

**Comment by dsgouda** [comment]
@jcgknudson @MikhailTryakhov please open a PR reverting this change and i can merge it

**Pull request merged**
