### PR TITLE
updated ErrorResponse in DataExport and OperationStatuses

### PR DESCRIPTION
**Pull request by dabenhamMic**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dabenhamMic** [comment]
@markcowl we have changed the contract from custom definition error response to common ErrorResponse.
this was done in order to pass the validation tests and generate a new SDK for Microsoft.OperationalInsights.

**Comment by markcowl** [comment]
@dabenhamMic Was this done in response to an s360 issue on swagger correctness or completeness? If so, link it here, and we may be able to approve without the breaking chaneg review.

Otherwise, breaking change review is required, even for 'good' changes.  'good' changes may be approved.

**Comment by ArcturusZhang** [comment]
Hi @akning-ms could you help on this breaking change warning? This PR only replace the self-defined error model with the error model defined in common-types, which is not really a breaking change, I suppose.

**Comment by akning-ms** [comment]
> Hi @akning-ms could you help on this breaking change warning? This PR only replace the self-defined error model with the error model defined in common-types, which is not really a breaking change, I suppose.

Yes. looks a false alarm. it is due to a extra type: object in old version. + @jianyexi for awareness

**Comment by jianyexi** [comment]
> > Hi @akning-ms
> >             
> >             Arthur Ning
> >             FTE could you help on this breaking change warning? This PR only replace the self-defined error model with the error model defined in common-types, which is not really a breaking change, I suppose.
> 
> Yes. looks a false alarm. it is due to a extra type: object in old version. + @jianyexi Jianye Xi FTE for awareness

Agreed, this  change has no impact, can be approved safely.

**Comment by dabenhamMic** [comment]
@markcowl , @jianyexi , can one of you guys please approve and merge this pr?

**Comment by markcowl** [comment]
@jianyexi  Change from a locally defined schema to the common schema automatically chenges types in any language SDK.  Also, in this case, a property, 'Error' is removed from the model.  This may have been doen for good reason, but it is *a breaking change* in the api definition

**Review by JeffreyRichter — APPROVED** [review]

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE Change from a locally defined schema to the common schema automatically changes types in any strongly typed language SDK. This may have been done for good reason, but it is _a breaking change_ in the api definition

Since the autorest modeler4 can auto-corrected  the undefined type to "'type:object'"  , and the model name and its definition are not changed, why there are breaking change ?

**Pull request merged**
