### PR TITLE
Add ADF V2 Integration Runtime APIs - Fixed the model validation issues

### PR DESCRIPTION
**Pull request by zhangyd2015**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by zhangyd2015** [comment]
@jianghaolu I addressed the issues in PR 
Duplicate of #2027 
and created the new PR.

**Comment by jianghaolu** [comment]
Thank you! Just be aware this change introduces breaking changes so you would need to address them in PowerShell and CLI.

**Comment by jianghaolu** [comment]
@lmazuel Hi Laurent, Can you help me understand why this PR is failing Python validation? https://travis-ci.org/Azure/azure-rest-api-specs/jobs/308328040

**Comment by zhangyd2015** [comment]
@jianghaolu Thanks. This breaking changes was introduced by adding an enum definition, which was also suggested by the model validation. So I believe it is good to go.

**Review by jianghaolu — APPROVED** [review]

**Comment by jianghaolu** [comment]
One linter issue - https://github.com/Azure/azure-rest-api-specs/issues/2057.

**Pull request merged**
