### PR TITLE
Add a new kusto version with changes 

### PR DESCRIPTION
**Pull request by zoharHenMicrosoft**
The main changes in this PR:

Add a new version
Add a path for 'database move command'
Add a new property enablePurge for ClusterProperties

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @zoharHenMicrosoft there are too many services get changed in this pr, and I believe some of them are just format change. I suggest you revert those changes on those services that you do not want to update. We can find another way to fix the formatter CI.

**Comment by zoharHenMicrosoft** [comment]
> Hi @zoharHenMicrosoft there are too many services get changed in this pr, and I believe some of them are just format change. I suggest you revert those changes on those services that you do not want to update. We can find another way to fix the formatter CI.

**Comment by zoharHenMicrosoft** [comment]
> Hi @zoharHenMicrosoft there are too many services get changed in this pr, and I believe some of them are just format change. I suggest you revert those changes on those services that you do not want to update. We can find another way to fix the formatter CI.

done

**Comment by zoharHenMicrosoft** [comment]
Hi! any updates? :)

**Comment by ArcturusZhang** [comment]
> Hi! any updates? :)

I just sent an email to the ARM API Review team, telling them to review this PR.
In the mean time, I did not find your alias link with your github id, therefore i cannot cc you in that email.

**Comment by sanjaiganesh** [comment]
@zoharHenMicrosoft 
    
Please add one iteration with old api version and then re-paste new api version in another iteration
that helps us to see the diff and review. thanks.

**Comment by majastrz** [comment]
For future reference, please create the first commit with an exact copy of the previous API version. This way the diff is easier for the reviewer. (No need to do this now because I've already spent time manually diffing this.)

---
In reply to: [575845365](https://github.com/Azure/azure-rest-api-specs/pull/8040#issuecomment-575845365) [](ancestors = 575845365)

**Comment by majastrz** [comment]
I took a look at the swagger and it is in good shape.

I do, however, have a question about the principal assignments resource type. Have you discussed this approach with the RBAC (aka PAS) team? Are the assignments authorizing calls that go through the control plane or data plane? Would data-plane RBAC work here?

**Comment by zoharHenMicrosoft** [comment]
> I took a look at the swagger and it is in good shape.
> 
> I do, however, have a question about the principal assignments resource type. Have you discussed this approach with the RBAC (aka PAS) team? Are the assignments authorizing calls that go through the control plane or data plane? Would data-plane RBAC work here?

@lucygoldbergmicrosoft related to your assignment?

**Comment by lucygoldbergmicrosoft** [comment]
@zoharHenMicrosoft, all principal assignments related API are already approved and merged into the previous versoin (2019-11-09).

**Comment by majastrz** [comment]
> @zoharHenMicrosoft, @majastrz , all principal assignments related API are already approved and merged into the previous versoin (2019-11-09).

Makes sense. I must have missed it when diffing.

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by zoharHenMicrosoft** [comment]
please re-check after the following additions:
1. renaming version (from December2019 to February2020)
2. merging https://github.com/Azure/azure-rest-api-specs/pull/8006/files (already approved) to the stable version

**Comment by zoharHenMicrosoft** [comment]
please notice that customers are waiting for this, so I would appreciate it if you could respond as soon as possible, thanks!!

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @zoharHenMicrosoft please let me know when this PR is ready to merge. I will remove the DoNotMerge tag and merge this PR.

**Comment by ArcturusZhang** [comment]
Hi @zoharHenMicrosoft since there is no update for quite a long time, I will close this PR for now. If you would make more update on this PR, please feel free to reopen this then.

**Comment by zoharHenMicrosoft** [comment]
> Hi @zoharHenMicrosoft since there is no update for quite a long time, I will close this PR for now. If you would make more updates on this PR, please feel free to reopen this then.

please reopen, as I just added a few more changes :) thanks!

**Comment by zoharHenMicrosoft** [comment]
@ArcturusZhang Hi! can you reopen this PR, please?

**Comment by zoharHenMicrosoft** [comment]
please notice that customers are waiting for this, so I would appreciate it if you could respond as soon as possible, thanks!! @ArcturusZhang @majastrz

**Comment by ravbhatnagar** [comment]
the changes in the other PR have been approved by ARM and the only other change here is to rename the api-version. signing off from ARM side on this.

**Comment by ArcturusZhang** [comment]
> please notice that customers are waiting for this, so I would appreciate it if you could respond as soon as possible, thanks!! @ArcturusZhang @majastrz

Sorry about the delay. and would you please resolve the last comment that @ravbhatnagar just left? Or please let me know you have already resolved that.

**Comment by zoharHenMicrosoft** [comment]
> > please notice that customers are waiting for this, so I would appreciate it if you could respond as soon as possible, thanks!! @ArcturusZhang @majastrz
> 
> Sorry about the delay. and would you please resolve the last comment that @ravbhatnagar just left? Or please let me know you have already resolved that.

Hi! can you please clarify what is the issue I should resolve? as we indeed wish to rename this version, and it seems we pass all tests and requirements :). @ravbhatnagar  @ArcturusZhang

**Comment by ArcturusZhang** [comment]
> > > please notice that customers are waiting for this, so I would appreciate it if you could respond as soon as possible, thanks!! @ArcturusZhang @majastrz
> > 
> > 
> > Sorry about the delay. and would you please resolve the last comment that @ravbhatnagar just left? Or please let me know you have already resolved that.
> 
> Hi! can you please clarify what is the issue I should resolve? as we indeed wish to rename this version, and it seems we pass all tests and requirements :). @ravbhatnagar @ArcturusZhang

SOrry about this that I just re-read @ravbhatnagar 's comment and it turns out that I mis-understand his meanings then. I will merge this as soon as the CI passes.

**Pull request merged**
