### PR TITLE
CloudServiceRP Version 2022 04 04 release

### PR DESCRIPTION
**Pull request by grizzlytheodore**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
What does it mean by: Switch to "Preview" on this description then select one of the choices below.?

@ArcturusZhang

**Comment by raosuhas** [comment]
This PR is not ready for review. Please follow the processes correctly and update all the template questions. If you set the template and checkboxes correctly the waitforarmfeedback will be automatically applied by the bot.

**Comment by raosuhas** [comment]
This PR has not been created correctly. The first commit needs to be the previous api version and the new changes should only be added in the subsequent commits. This is explained in detail here (If using Open API which is recommended) https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version or here(For manual process) : https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/83/Manual-Process-Adding-new-API-version . Please remove the "ARMChangesRequested" tag once you have fixed this issue.

**Comment by grizzlytheodore** [comment]
> This PR has not been created correctly. The first commit needs to be the previous api version and the new changes should only be added in the subsequent commits. This is explained in detail here (If using Open API which is recommended) https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version or here(For manual process) : https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/83/Manual-Process-Adding-new-API-version . Please remove the "ARMChangesRequested" tag once you have fixed this issue.

@raosuhas 
first commit is indeed setting up the branch for this new release. There are some other commits because in this iteration of releases we are cleaning up the compute swagger files by: 
- breaking up swagger files by resources 
- updating all the example file names to be consistent 

And also since this branch was created, compute had three releases: 2022-01-03, 2022-03-01, 2022-03-02, and it is a difficult task to keep them all synced. 
And the ARM team's ask of having 1 commit as a branch set up and commits following to be only new features being added for this version is a very difficult task to achieve with all the moving parts in compute. 
I understand that this is to make the review process easier, so I have listed out the 2 PRs that were merged to this branch that are the only new features being added to this version: 
https://github.com/Azure/azure-rest-api-specs/pull/19361
https://github.com/Azure/azure-rest-api-specs/pull/19311

I believe that the difficulty of having the commit history to the ARM team's requirement far outweighs the difficulty added to the review process by the presense of few 'unnecessary' commits. Especially with the PRs I have listed out for you. Please allow an exception

**Comment by zizw123** [comment]
> 

I will need to know what changes are new so that I can review those part, without creating the changes properly I can't tell for sure and it will be hard to go over everything line by line. Can you put all the older changes in a few commits, and  add new commit on top of that, so that I can just review the diff from the older commit to the new change?

**Comment by grizzlytheodore** [comment]
@zizw123 seriously question, is there an easy/suggested way to do that? or do you expect a new branch to be created following @raosuhas 's links? 

as a side note, from the very start, every release, we are aware of the ARM review and we do our best to have our commits organized, but again, with all the moving parts, it is very difficult.

**Comment by zizw123** [comment]
> @zizw123 seriously question, is there an easy/suggested way to do reorganize commits? or do you expect a new branch to be created following @raosuhas 's links?
> 
> as a side note, from the very start, every release, we are aware of the ARM review and we do our best to have our commits organized, but again, with all the moving parts, it is very difficult.

You can create a new branch with the proper commit order and send that as a new PR. That should be easier. The only reason why we are asking for these is that we get a lot of reviews and it's really not ideal to us to go over line by line for every files.

**Comment by grizzlytheodore** [comment]
okay I just tried to use the tools but we will not be able to use this for the following reasons (that I've wrote above already):
from the last CloudService version, 2021-03-03, we cleaned up

**Comment by grizzlytheodore** [comment]
PR is moved to https://github.com/Azure/azure-rest-api-specs/pull/19468 for better commit history. Please review/approve @zizw123

**Pull request closed without merging**
