### PR TITLE
reverted methods removal

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
added missed Vpn gateway methods...

### CODE REVIEW

**Comment by dsgouda** [comment]
@MikhailTryakhov what is the intention behind this change, the changes were merged in the last PR, you will have to go through the whole cycle of dotnet sdk code generation and publishing the package now.
How did we miss this piece?

**Comment by MikhailTryakhov** [comment]
@dsgouda  we had a breaking changes approval for another peace of code and I've made mistake.

not sure where this removal from... Whole cycle is OK...

**Comment by dsgouda** [comment]
@azuresdkci Test this please

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
