### PR TITLE
Updating doc strings and flattening parameters for Azure Batch spec

### PR DESCRIPTION
**Pull request by brnleehng**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brnleehng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brhoan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by lmazuel** [comment]
@annatisch
This commit breaks the Python SDK, since the OperationId has changed:
https://travis-ci.org/Azure/azure-sdk-for-python/builds/126792125

Since the Batch SDK is already published, it's up to you.

@annatisch, if this is intended, could you fork this branch:
https://github.com/AutorestCI/azure-sdk-for-python/tree/RestAPI-master

And do a PR with the test fixes please?

**Comment by lmazuel** [comment]
Thank you :)

**Comment by annatisch** [comment]
Hi @brnleehng ,
Was the change to the add_application response type a bug in the spec rather than a change in the server? It seems so, as the recording still deserializes correctly.
Also, I gather we decided we're okay introducing the breaking changes to account operations?

@lmazuel ,
I've fixed the tests so I'll PR once we've confirmed the above.
Thanks! :)

**Comment by lmazuel** [comment]
@annatisch Any news here?

**Pull request merged**
