### PR TITLE
[Hub Generated] Review request for Microsoft.DesktopVirtualization to add version preview/2022-04-01-preview

### PR DESCRIPTION
**Pull request by nakranimohit0**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/nakranimohit0/azure-rest-api-specs/dev-desktopvirtualization-Microsoft.DesktopVirtualization-2022-04-01-preview...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [x] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zizw123** [comment]
>             "$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter"

Consider if you can use v3 type, same for the rest of the changes 

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:574 in c702287. [](commit_id = c7022873a6169016866457abf2305623d108df58, deletion_comment = False)

**Comment by zizw123** [comment]
>           "type": "boolean",

Consider if you can use enum over boolean: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:5777 in c702287. [](commit_id = c7022873a6169016866457abf2305623d108df58, deletion_comment = False)

**Review by dallinlmag — APPROVED** [review]

**Comment by nakranimohit0** [comment]
> > ```
> >         "$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter"
> > ```
> 
> Consider if you can use v3 type, same for the rest of the changes
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:574 in [c702287](https://github.com/Azure/azure-rest-api-specs/commit/c7022873a6169016866457abf2305623d108df58). [](commit_id = [c702287](https://github.com/Azure/azure-rest-api-specs/commit/c7022873a6169016866457abf2305623d108df58), deletion_comment = False)

@zizw123 Thanks for the feedback. I didn't find any differences between v1 and v3 for API version parameter. I'm happy to do it but I'm wondering if this is considered a breaking change for the SDK generation ?

**Comment by nakranimohit0** [comment]
> > ```
> >       "type": "boolean",
> > ```
> 
> Consider if you can use enum over boolean: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:5777 in [c702287](https://github.com/Azure/azure-rest-api-specs/commit/c7022873a6169016866457abf2305623d108df58). [](commit_id = [c702287](https://github.com/Azure/azure-rest-api-specs/commit/c7022873a6169016866457abf2305623d108df58), deletion_comment = False)

@zizw123 So, I tested this with PowerShell, pushing out a boolString to backend is fine i.e. boolString (`"True"`) -> bool (`true`) is successful. However, since backend will always return bool (not a boolString), PowerShell fails to parse or convert bool (`true`) -> boolString (`"True"`)

**Comment by rkmanda** [comment]
>         "timeZone"

Please go thru all cross version breaking changes and fix them. Adding a required property in a new API version constitutes a breaking change. If the original API is still in preview this is fine but in this case the previous API version is a stable version so pl work with the breaking changes reviewers and get an exception

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:5396 in 9132664. [](commit_id = 9132664bdc2f2a2d00f1253794924f4033d45caf, deletion_comment = False)

**Comment by nakranimohit0** [comment]
> > ```
> >     "timeZone"
> > ```
> 
> Please go thru all cross version breaking changes and fix them. Adding a required property in a new API version constitutes a breaking change. If the original API is still in preview this is fine but in this case the previous API version is a stable version so pl work with the breaking changes reviewers and get an exception
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:5396 in [9132664](https://github.com/Azure/azure-rest-api-specs/commit/9132664bdc2f2a2d00f1253794924f4033d45caf). [](commit_id = [9132664](https://github.com/Azure/azure-rest-api-specs/commit/9132664bdc2f2a2d00f1253794924f4033d45caf), deletion_comment = False)

@rkmanda Although, none of the previous API versions required this property. This property has always been required in the backend. i.e. Backend has always been returning BadRequest (HTTP 400) with an error message stating that the property is required.

**Comment by rkmanda** [comment]
>         "timeZone"

This was clarified. The previous API version was also preview and all changes are for a feature that is not GA'd yet

---
In reply to: [1162515235](https://github.com/Azure/azure-rest-api-specs/pull/18607#issuecomment-1162515235) [](http://example.com/codeflow?ancestors=1162515235,1162515235)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-04-01-preview/desktopvirtualization.json:5396 in 9132664. [](commit_id = 9132664bdc2f2a2d00f1253794924f4033d45caf, deletion_comment = False)

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
