### PR TITLE
Adding SCVMM version 2024-06-01.

### PR DESCRIPTION
**Pull request by kartikverma020**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by ramoka178** [comment]
>         }

These are missing in the examples, say VirtualMachineInstances_Update_MaximumSet_Gen.json, 

please update.

---
Refers to: specification/scvmm/resource-manager/Microsoft.ScVmm/stable/2024-06-01/scvmm.json:4224 in aeab608. [](commit_id = aeab608ee4fed8e42f8b49cbf6f02086340958b0, deletion_comment = False)

**Comment by ramoka178** [comment]
Please have a base commit, that has the exact copy of the existing apiversion details. 
We can then compare the existing version to the incoming change (from the last commit ) and can look at the changes. 

It is tough to go by what you have in the scvmm.json file alone here, which did not have  any base commit that points to existing version,

**Comment by kartikverma020** [comment]
> > ```
> >     }
> > ```
> 
> These are missing in the examples, say VirtualMachineInstances_Update_MaximumSet_Gen.json,
> 
> please update.
> 
> Refers to: specification/scvmm/resource-manager/Microsoft.ScVmm/stable/2024-06-01/scvmm.json:4224 in [aeab608](https://github.com/Azure/azure-rest-api-specs/commit/aeab608ee4fed8e42f8b49cbf6f02086340958b0). [](commit_id = [aeab608](https://github.com/Azure/azure-rest-api-specs/commit/aeab608ee4fed8e42f8b49cbf6f02086340958b0), deletion_comment = False)

Need more information on this. As far as I can understand you are asking about provisioningAction which is a guest agent property and is present in files such as GuestAgents_Create_MaximumSet_Gen.json. Please clarify if there is some gap in understanding.

**Comment by kartikverma020** [comment]
> Please have a base commit, that has the exact copy of the existing apiversion details. We can then compare the existing version to the incoming change (from the last commit ) and can look at the changes.
> 
> It is tough to go by what you have in the scvmm.json file alone here, which did not have any base commit that points to existing version,

The existing API version is 2023-10-07 which is there in public:main. This PR introduces a new version 2024-06-01 for which new folders were created. First commit c137555 (Updating readme to add information about 2024-06-01) contains the base version.Please note that after this commit another change was introduced in existing api version (2023-10-07) (https://github.com/Azure/azure-rest-api-specs/pull/29490) changes for which were pulled from the main in this current PR.

**Comment by kartikverma020** [comment]
Creating new PR with base commit.

**Pull request closed without merging**
