### PR TITLE
chore: jsonfmt batch

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/batch/**/*.json"`

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
This change is really good, but the PR is hard to review.
I would suggest you close this PR and re-open multiple PRs for each RP separately which are easy to review and if there are any model/linter failures, it will be easy to fix them as well.

**Comment by nschonni** [comment]
@shahabhijeet you can toggle the "ignore whitespace diffs" option to see the few places were it wasn't just changing the indenting. This was just an automated cleanup of the JSON files to match EditorConfig settings, so any preexisting failures would need to be fixed by the product owner

**Comment by nschonni** [comment]
@shahabhijeet ping

**Comment by nschonni** [comment]
@jhendrixMSFT can you help land this?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
