### PR TITLE
Rename Insights client to Monitor

### PR DESCRIPTION
**Pull request by lmazuel**
Discussed with the Monitor team, but of course needs confirmation here :)

FYI @gucalder @amarzavery @olydis

### CODE REVIEW

**Review by gucalder — COMMENTED** [review]
Sorry, I did not find a way to write comments closer to the source.

The name change is Ok, but didn't we also have issues with the folder name? It is usually confused with app insights. Then we receive PRs to this folders, but their are intended to go to app insights.

If only changing the name of the package itself is enough, then I'll do the changes in the SDKs as soon as this is checked in.

It is a breaking change to the SDKs. I think we might need to warn the customers and wait several iterations, unless we can hide the change in the SDKs so that PowerShell, CLI, etc. do not see any change.

**Comment by vishrutshah** [comment]
@lmazuel Changes looks good. I'd agree with you guys that changing the folder name "arm-insights" to "arm-monitor" and "insights" to "monitor" makes sense but I am fine if we do it now or afterwards as well.

**Comment by kirthik** [comment]
@vishrutshah : Is this ready to be merged?

**Comment by vishrutshah** [comment]
@kirthik I'd wait until we have approval from @gucalder. 

@lmazuel What do you think? And what did you decide on renaming folder? I am fine with afterwards as well.

**Comment by lmazuel** [comment]
@vishrutshah I think the folders should be renamed at the same time, this way if a CI or a script is using this Swagger, it will break before generating a new client name (that has a risk to do not be seen). I discussed it in separate email thread with @gucalder . I agree only @gucalder is able to confirm the folder renaming and the merging of this PR. I will be happy to rename the folders in this PR directly if we have the "go" for it.

**Comment by vishrutshah** [comment]
@gucalder Could you please provide us confirmation on the renames?

**Comment by kirthik** [comment]
@gucalder : Could you please respond to @vishrutshah's question?

**Comment by gucalder** [comment]
This PR is covered by https://github.com/Azure/azure-rest-api-specs/pull/936. 
So this can be closed without merge. I am going to keep Insights as it is until we remove it at some point in time.

**Pull request closed without merging**
