### PR TITLE
Release machinelearningservices microsoft.machine learning services 2023 08 01 preview

### PR DESCRIPTION
**Pull request by kseager**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/release-machinelearningservices-Microsoft.MachineLearningServices-2023-06-01-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
@kseager please can you follow the process guidance and get BreakingChanges reviewed before seeking ARM review feedback.

>If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
you must follow the [breaking changes process](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1).

**Comment by kseager** [comment]
FYI ARM reviewer: All of the changes in this PR have been previously ARM approved. This PR is a batching of API changes so we can introduce the version into main as a unit

**Comment by TimLovellSmith** [comment]
>         },

to help avoid cyclic dependecies between jsons, which seems to be giving the tools conniptions...

for all these types shared between your mfe.json and machineLearningServices.json, could you please move them to a Definitions section in a separate json?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/machineLearningServices.json:3385 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "$ref": "./mfe.json#/definitions/RecurrenceFrequency"

to help avoid cyclic dependecies between jsons, which seems to be giving the tools conniptions...

for all these types shared between your mfe.json and machineLearningServices.json, could you please move them to a Definitions section in a separate json?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/machineLearningServices.json:3481 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "$ref": "./mfe.json#/definitions/RecurrenceSchedule"

to help avoid cyclic dependencies between jsons, which seems to be giving the tools conniptions...

for all these types shared between your mfe.json and machineLearningServices.json, could you please move them to a Definitions section in a separate json?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/machineLearningServices.json:3500 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           }

to help avoid cyclic dependencies between jsons, which seems to be giving the tools conniptions...

for all these types shared between your mfe.json and machineLearningServices.json, could you please move them to a Definitions section in a separate json?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:37 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           }

to help avoid cyclic dependencies between jsons, which seems to be giving the tools conniptions...

for all these types shared between your mfe.json and machineLearningServices.json, could you please move them to a Definitions section in a separate json?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:322 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "$ref": "machineLearningServices.json#/parameters/PaginationParameter"

cross-json dependency

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:321 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "$ref": "machineLearningServices.json#/parameters/WorkspaceNameParameter"

cross-json dependency

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceFeatures.json:41 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "$ref": "machineLearningServices.json#/parameters/WorkspaceNameParameter"

cross-json dependency

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:3386 in d97207a. [](commit_id = d97207a38747c5174455721b93cd2b2c67200618, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
...or at least make sure the dependencies are unidirectional

**Comment by TimLovellSmith** [comment]
(@rkmanda this here was an instance of spectral blowing up because of the cyclic dependencies.)

**Comment by kseager** [comment]
Leaving a separate comment to address Tim's overall comment regarding the circular reference. Thank you for flagging this, it's too bad it this wasn't caught earlier during the API review where it was introduced. As a result, we will need to put in more time then has been allotted for this API review (to change the reference and then go through the associated breaking change review etc). We have logged a work item targeting the next API release: https://msdata.visualstudio.com/Vienna/_workitems/edit/2688911

**Comment by kseager** [comment]
PRs Currently Merged:
https://github.com/Azure/azure-rest-api-specs/pull/25090
https://github.com/Azure/azure-rest-api-specs/pull/24769
https://github.com/Azure/azure-rest-api-specs/pull/25375
https://github.com/Azure/azure-rest-api-specs/pull/25372
https://github.com/Azure/azure-rest-api-specs/pull/25616
https://github.com/Azure/azure-rest-api-specs/pull/25754
https://github.com/Azure/azure-rest-api-specs/pull/25814
https://github.com/Azure/azure-rest-api-specs/pull/25785

Coming soon/WIP Approval/Merge:
https://github.com/Azure/azure-rest-api-specs/pull/25593
https://github.com/Azure/azure-rest-api-specs/pull/25532
https://github.com/Azure/azure-rest-api-specs/pull/25780
https://github.com/Azure/azure-rest-api-specs/pull/25819

**Comment by visingla-ms** [comment]
> Leaving a separate comment to address Tim's overall comment regarding the circular reference. Thank you for flagging this; it's too bad it wasn't caught earlier during the API review where it was introduced. As a result, we will need to put in more time then has been allotted for this API review (to change the reference and then go through the associated breaking change review etc). I have logged a work item targeting the next API release: https://msdata.visualstudio.com/Vienna/_workitems/edit/2688911

@kseager There are only 3 references of mfe.json from machinelearningservices.json file, it should be easy to update these to fix circular references, making it unidirectional. Please make the changes.

**Comment by kseager** [comment]
> > Leaving a separate comment to address Tim's overall comment regarding the circular reference. Thank you for flagging this; it's too bad it wasn't caught earlier during the API review where it was introduced. As a result, we will need to put in more time then has been allotted for this API review (to change the reference and then go through the associated breaking change review etc). I have logged a work item targeting the next API release: https://msdata.visualstudio.com/Vienna/_workitems/edit/2688911
> 
> @kseager There are only 3 references of mfe.json from machinelearningservices.json file, it should be easy to update these to fix circular references, making it unidirectional. Please make the changes.


I have this PR's which is approved and will be merged soon: https://github.com/Azure/azure-rest-api-specs/pull/25870
to fix this request

**Comment by visingla-ms** [comment]
> {

Please fix the Linter error here.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceRP.json:1 in 779b18a. [](commit_id = 779b18ac7c79acec24f7d4113623bffb38866dc0, deletion_comment = False)

**Comment by kseager** [comment]
> > {
> 
> Please fix the Linter error and Avocado error here.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceRP.json:1 in [622126d](https://github.com/Azure/azure-rest-api-specs/commit/622126d9ef31d033e00625e8108fcd5ddad90521). [](commit_id = [622126d](https://github.com/Azure/azure-rest-api-specs/commit/622126d9ef31d033e00625e8108fcd5ddad90521), deletion_comment = False)

1) Avocado has been pre-approved: 
https://github.com/Azure/azure-rest-api-specs/pull/25372
Konrad Jamrozik has already previously approved it

2) Linting error: I have already gotten agreement from the dev associated with this service to add in the change. However because it will require service code to support the update API he has requested more time to accommodate the change
https://msdata.visualstudio.com/Vienna/_workitems/edit/2702298

**Comment by visingla-ms** [comment]
>     reason: LRO does not return 200.

Please put a specific path in the swagger (otherwise it might suppress all such errors in all swaggers in future), where this suppression applies and also, add work item link in the reason here.

---
Refers to: specification/machinelearningservices/resource-manager/readme.md:46 in 779b18a. [](commit_id = 779b18ac7c79acec24f7d4113623bffb38866dc0, deletion_comment = False)

**Comment by kseager** [comment]
> > ```
> > reason: LRO does not return 200.
> > ```
> 
> Please put a specific path in the swagger (otherwise it might suppress all such errors in all swaggers in future), where this suppression applies and also, add work item link in the reason here.
> 
> Refers to: specification/machinelearningservices/resource-manager/readme.md:46 in [779b18a](https://github.com/Azure/azure-rest-api-specs/commit/779b18ac7c79acec24f7d4113623bffb38866dc0). [](commit_id = [779b18a](https://github.com/Azure/azure-rest-api-specs/commit/779b18ac7c79acec24f7d4113623bffb38866dc0), deletion_comment = False)

We've added it to this PR
https://github.com/Azure/azure-rest-api-specs/pull/25532

**Comment by visingla-ms** [comment]
One changes from this PR get merged into this PR, then, please move it to ARM Review Queue: https://github.com/Azure/azure-rest-api-specs/pull/25532.

**Comment by kseager** [comment]
updated to this PR instead: https://github.com/Azure/azure-rest-api-specs/pull/25941 for linting error suppression

**Comment by kseager** [comment]
> (@rkmanda this here was an instance of spectral blowing up because of the cyclic dependencies.)

circular reference was fixed here [August-2023-preview fix circular reference by kseager · Pull Request #25870 · Azure/azure-rest-api-specs · GitHub](https://github.com/Azure/azure-rest-api-specs/pull/25870)

**Comment by ragovada** [comment]
Could you please merge the PR in this link first:   https://github.com/Azure/azure-rest-api-specs/pull/26007

**Review by sjanamma — APPROVED** [review]
APPROVED

**Pull request merged**
