### PR TITLE
Changes to support Azure Disk Encryption & Accelerated Networking

### PR DESCRIPTION
**Pull request by sriramvu**
Azure Site Recovery (ASR) service has enhanced Azure to Azure (A2A) provider feature support for VMs with encrypted disks and also with accelerated networking.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please update corresponding examples

**Comment by sriramvu** [comment]
@dsgouda: Azure Site Recovery (ASR) service supports 10+ providers (almost same set of operations each getting distinguished by instanceType in request & response). 

All the existing examples are with only one provider _HyperV to Azure (E2A)_ and the current changes are with _Azure to Azure (A2A)_ provider. 

Can you please suggest how can we go for updating examples for these specific changes (and in general in future)?

PS: we have AzurePowerShell guiding documentations, sharing one for A2A provider : https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-powershell

**Comment by dsgouda** [comment]
Usually examples are generated from live examples of the REST service traffic. If it is not possible to generate such examples here, that won't be a blocker here

**Comment by dsgouda** [comment]
Talked to @sriramvu since this model is not a part of any PUT/POST request, we can skip marking the properties as readonly for now

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
