### PR TITLE
Add 201 response to AppServicePlans_CreateOrUpdate

### LINKED ISSUE #3648: AppServicePlans_CreateOrUpdate is missing 201 reponse
The definitions on [1] and [2] have responses with 200 and 202 statuses. But the API also returns 201 as seen in terraform-providers/terraform-provider-azurerm#917.

[1] https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/AppServicePlans.json
[2] https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/AppServicePlans.json

### PR DESCRIPTION
**Pull request by pietro**
Fixes #3648.

### CODE REVIEW

**Comment by annatisch** [comment]
Thanks for the fix @pietro!
The changes look good - however there are quite a few model validation errors for these two specs. Most of them are unrelated to your changes - however it would be great if you could fix up the errors related to the two samples you've updated (these 3 errors apply to the same sample in both API versions):
```
error : 
operationId: AppServicePlans_CreateOrUpdate
scenario: Create or Update App Service plan
source: response
responseCode: '200'
errorDetails:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - - mdmId
      - currentNumberOfWorkers
      - currentWorkerSize
      - numberOfWorkers
      - workerSize
  message: >-
    Additional properties not allowed:
    mdmId,currentNumberOfWorkers,currentWorkerSize,numberOfWorkers,workerSize
  path: properties
  jsonUrl: >-
    specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/examples/CreateOrUpdateAppServicePlan.json

error : 
operationId: AppServicePlans_CreateOrUpdate
scenario: Create or Update App Service plan
source: response
responseCode: '201'
errorDetails:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - - mdmId
      - currentNumberOfWorkers
      - currentWorkerSize
      - numberOfWorkers
      - workerSize
  message: >-
    Additional properties not allowed:
    mdmId,currentNumberOfWorkers,currentWorkerSize,numberOfWorkers,workerSize
  path: properties
  jsonUrl: >-
    specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/examples/CreateOrUpdateAppServicePlan.json

 error : 
operationId: AppServicePlans_CreateOrUpdate
scenario: Create or Update App Service plan
source: response
responseCode: '202'
errorDetails:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - - mdmId
      - currentNumberOfWorkers
      - currentWorkerSize
      - numberOfWorkers
      - workerSize
  message: >-
    Additional properties not allowed:
    mdmId,currentNumberOfWorkers,currentWorkerSize,numberOfWorkers,workerSize
  path: properties
  jsonUrl: >-
    specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/examples/CreateOrUpdateAppServicePlan.json
```

If you felt like knocking out any of the other remaining example validation errors that would be bonus brownie points ;)
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/448024117

**Comment by pietro** [comment]
@annatisch Thanks for the review. I'll look into the errors and I'll try to update the models to match the examples.

**Comment by annatisch** [comment]
Thanks @pietro - but please confirm whether it's the models or the examples that need to be updated.

**Comment by pietro** [comment]
@annatisch the models need to be updated. I'm adding the properties and their types, but I'm skipping the description.

**Comment by pietro** [comment]
> Please do not skip the description - even if it is simplistic for now

I'll add them soon.

> I see you are not yet a member of the Azure GitHub org - can you please join?

Sure, can you send me the invite?

**Comment by annatisch** [comment]
Thanks @pietro - please join through aka.ms/azuregithub :)

**Comment by pietro** [comment]
@annatisch I tried to join but I got this error:

> Selected user account does not exist in tenant 'Microsoft' and cannot access the application 'SOME_UUID' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

Maybe I can't join because I'm not a MSFT employee?

**Comment by annatisch** [comment]
Ah - sorry @pietro - I assumed you were with MSFT.
In that case I will need to bring in the service team to validate these PR changes.

**Comment by amarzavery** [comment]
@naveedaz - Can you please review the changes in the PR? They are from an external contributor.

**Comment by sarangan12** [comment]
@naveedaz - Can you please review the changes in the PR? They are from an external contributor.

**Comment by pietro** [comment]
@naveedaz I removed the commits that added the legacy properties.

**Comment by sarangan12** [comment]
@naveedaz What is the plan for this PR? Are you planning to approve this?

**Review by naveedaz — APPROVED** [review]

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
