### PR TITLE
Added optional deliveryReportTimeoutInSeconds to smsSendOptions.

### LINKED ISSUE #27068: [IC3 ACS Telco Messaging Front-end ] Add optional parameter validityPeriodSeconds API Review
New API Review meeting has been requested.

**Service Name**: IC3 ACS Telco Messaging Front-end 
**Review Created By**: Vitalie Besliu
**Review Date**: 01/18/2024 08:00 AM PT
**Onboarding Record**: 
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/27067
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**:  [Message Expiration Settings.docx](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EUnncxP-cG9GswYfXPPbeBkBv6dKrt3xjrA1QF8mG9SNEQ?e=seHbdt)

**Description**: 
Discussed with DevEx team on  [Internal Review](https://teams.microsoft.com/l/message/19:345a57dbe24740eaaf554236a5926109@thread.skype/1701964912142?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e9c1fc3-39df-4486-a26a-456d80e80f82&parentMessageId=1701964912142&teamName=Azure%20Communication%20Services&channelName=API%20and%20Design%20Discussions&createdTime=1701964912142). 
Main conclusion: **Team to schedule ARB review for the new field and will also clarify below questions during the review**
* The new field affects both
** How long we keep the msg and keep retrying
** How long we wait for the delivery report
* Suggested names were: _processingTimeoutSeconds_, _deliveryTimeoutSeconds_ - pick one of those and add description/docs on what the semantics are
** Current description already explains this well
* Logistical GA questions
** Team wants to GA asap 
** Should a new API version be created or can this field be added to an existing one? -> create new version
** Can GA be done without public preview? -> no, but will double-check

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=0ce5a7f3-e899-ee11-be37-000d3a3411c3)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by besh2014**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue: https://github.com/Azure/azure-rest-api-specs/issues/27068

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc: SMS GA  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Sms/stable/2021-03-07/communicationservicessms.json.
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

<details>
  <summary>Checks stuck in `queued` state?</summary>
If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.  
</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/27068

### CODE REVIEW

**Review by mikekistler — CHANGES_REQUESTED** [review]
Azure's versioning policy requires that any change to a GA or public preview API version, breaking or not, be made in a new api-version.

Please create a new api-version for this change.

**Comment by besh2014** [comment]
> Azure's versioning policy requires that any change to a GA or public preview API version, breaking or not, be made in a new api-version.
> 
> Please create a new api-version for this change.

@mikekistler Thanks. Added new version.

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Comment by besh2014** [comment]
@jhendrixMSFT do I understand right that you are the assigned person who is in charge to merge the pr to master? if yes, could you please merge, thank you.

**Pull request merged**
