### PR TITLE
Add v3.0 swagger

### PR DESCRIPTION
**Pull request by Basma-Emara**

### CODE REVIEW

**Comment by Basma-Emara** [comment]
@DavidLiCIG can you take a look at this PR
and help me to figure out why the sdk tests fail?

**Comment by kayousef** [comment]
> @DavidLiCIG can you take a look at this PR
> and help me to figure out why the sdk tests fail?

@DavidLiCIG & @yangyuan I don't understand what tests are running here? How do we run SDK tests although the CI pipeline is not fully integrated with the respective repos AFAIK?

**Comment by yangyuan** [comment]
Hi @Basma-Emara, this is a new version.
To make the review easier, can you provide a list of breaking changes from previews version?
Also have you went though the review with Azure API review board?

**Comment by Basma-Emara** [comment]
Hi Yang,

Sorry for the late reply. Currently we are on an ongoing thread to get the approval from the azure API review board
I attached the difference between the previous version and the current version.
Also there are some APIs that we removed which are:

  *   POST /apps/{appId}/versions/{versionId}/hierarchicalentities
  *   POST /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}/children
  *   POST /apps/{appId}/versions/{versionId}/compositeentities
  *   PUT /apps/{appId}/versions/{versionId}/entities/{entityId}
  *   PUT /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}

Thanks,
Basma

**Comment by Basma-Emara** [comment]
Hi Yang,

we got the approval from the Azure API Review Board.
Can you please yake a look at this PR so that we can close on this.

Thanks,
Basma

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Basma Emara
Sent: Monday, September 30, 2019 5:34:44 PM
To: Azure/azure-rest-api-specs <reply@reply.github.com>; Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-rest-api-specs] Add v3.0 swagger (#7299)


Hi Yang,



Sorry for the late reply. Currently we are on an ongoing thread to get the approval from the azure API review board

I attached the difference between the previous version and the current version.

Also there are some APIs that we removed which are:

  *   POST /apps/{appId}/versions/{versionId}/hierarchicalentities
  *   POST /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}/children
  *   POST /apps/{appId}/versions/{versionId}/compositeentities
  *   PUT /apps/{appId}/versions/{versionId}/entities/{entityId}
  *   PUT /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}



Thanks,

Basma

**Comment by Basma-Emara** [comment]
@Yang Any updates?

**Comment by Basma-Emara** [comment]
Kind Reminder :)

**Review by yangyuan — APPROVED** [review]

**Comment by Basma-Emara** [comment]
We got the azure board approval and I sent the email to @yangyuan

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
APIBoard signed off via email, by John Gossman & Johan Stenberg.

**Pull request merged**
