### PR TITLE
[MixedReality] Version Iteration for new Releases

### PR DESCRIPTION
**Pull request by jiasli**
Merge #8848 to `master`.

### CODE REVIEW

**Review by XiangyuL-Microsoft — APPROVED** [review]
@akning-ms I've tried to create my own Pull Request to merge our branch to master, unfortunately, it seems that the change is duplicated with this one and it automatically jump to this. I just approve this PR. Is it possible for you to force merge it? Thank you very much.

**Comment by leni-msft** [comment]
Hi @XiangyuL-Microsoft , you need to fix ModelValidation error to get this PR merged. If you don't have permission to update `Azure-MixedReality` branch, you can create a branch in your fork repo, then create new PR and close this one.

**Comment by XiangyuL-Microsoft** [comment]
@leni-msft @akning-ms I just reviewed the Model Validation Errors and I must claim that it seems the Model Validation may have a defect. If you look at the errors, it just complain our resource definition containing a not-allowed property 'tag' and lacking a property 'location'. It sounds weird since our resource definition is simply derived from "/common-types/resource-management/v1/types.json#/definitions/TrackedResource",  in which both tags and location are defined according to ARM RPC Contract. Could you please help have a look at this issue, please?

**Comment by leni-msft** [comment]
@XiangyuL-Microsoft It should be `tags` (lower case `t`). And the `location` parameter is required, but not present in the example.
```
--- a/specification/mixedreality/resource-manager/Microsoft.MixedReality/preview/2020-04-06-preview/examples/remote-rendering/Patch.json
+++ b/specification/mixedreality/resource-manager/Microsoft.MixedReality/preview/2020-04-06-preview/examples/remote-rendering/Patch.json
@@ -5,7 +5,8 @@
     "accountName": "MyAccount",
     "api-version": "2020-04-06-preview",
     "remoteRenderingAccount": {
-      "Tags": {
+      "location": "eastus2euap",
+      "tags": {
         "heroine": "juliet",
         "hero": "romeo"
       }
```

**Comment by leni-msft** [comment]
@XiangyuL-Microsoft Seems there's more similar MV errors, e.g., in examples of spatial-anchors.json. Please fix them to pass the checks.

**Pull request merged**
