### PR TITLE
Updating Managed Identity type enum with space to make it consistent with RP behaviour

### PR DESCRIPTION
**Pull request by gorandom**
I am adding a new version for common-types in order to update the ManagedIdentityType enum value with a space from "SystemAssigned,UserAssigned" to "SystemAssigned, UserAssigned"
This new format with space is auto generated when serializing the Enum using Newtonsoft Json converter.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
@gorandom This would be easier to review if it was one commit to copy v3 managedidentity.json to v4, then another to make the change

**Comment by gorandom** [comment]
@TimLovellSmith now the commits are split.

**Comment by gorandom** [comment]
@Azure/arm-api-review-board Can you please review this PR?

**Comment by TimLovellSmith** [comment]
@gorandom Sorry, I didn't actually mean we should add the other v4 files. Just managedidentity.json should be fine since we're not going to make any breaking change for anything else.

If you could also include the change to reference this v4/managedidentity.json from latest redis swagger that you are proposing to do along with this to fix the S360 issues, that should also help the reviewers with clarify the breaking-ness of this change from an API reviewing perspective for ARM / SDK.

**Comment by gorandom** [comment]
@TimLovellSmith removed the unmodified files.

The latest redis swagger is not yet merged into main, so we don't have to worry about breaking change or s360 at this point.

**Comment by RamyasreeChakka** [comment]
@gorandom - Which RP behavior are you trying to make consistent?

**Comment by gorandom** [comment]
@RamyasreeChakka We have implemented Managed Identity in Redis RP and the RP response value of the ManagedIdentityType enum "SystemAssigned, UserAssigned" had space.
So we wanted to define the same in swagger also.
Since the existing common types doesn't have the space, I have created this PR to add a new version with space.
Which we will use in our redis.json

I have also found many other modules use that value with space in their swagger definition.
For Example:
https://github.com/Azure/azure-rest-api-specs/blob/a42f1b58607091c4f255ead152a8ef323fa0b280/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L11794
https://github.com/Azure/azure-rest-api-specs/blob/a42f1b58607091c4f255ead152a8ef323fa0b280/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/network.json#L211

I have also found some of them use without space.

We wanted feedback from the ARM team on, if we can use this format with space going forward and make it consistent across all other modules as well by adding it to common types.

**Comment by gorandom** [comment]
Additional info on that.
There is a discussion on this topic in stackoverflow https://stackoverflow.microsoft.com/questions/235713
Which says that when Arm calls each RP, the type will be "SystemAssigned, UserAssigned" for any format of the actual request.

**Comment by RamyasreeChakka** [comment]
> Additional info on that. There is a discussion on this topic in stackoverflow https://stackoverflow.microsoft.com/questions/235713 Which says that when Arm calls each RP, the type will be "SystemAssigned, UserAssigned" for any format of the actual request.

@gorandom Thanks for additional info. Signed off from ARM side.

**Review by TimLovellSmith — APPROVED** [review]
I'm fine with this change, as I don't think it breaks any consumers of our service, and there isn't clear guidance on whether spaces are OK or breaking in enumerations.

**Comment by gorandom** [comment]
@akning-ms Can you check and merge this PR?

**Review by raych1 — APPROVED** [review]

**Comment by forteddyt** [comment]
@gorandom, where is `types.json` and `privatelinks.json`?

**Pull request merged**
