### PR TITLE
[Hub Generated] Review request for Microsoft.AlertsManagement to add version preview/2019-05-05-preview

### PR DESCRIPTION
**Pull request by avjerafi**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/avjerafi/azure-rest-api-specs/dev-alertsmanagement-Microsoft.AlertsManagement-2019-05-05-preview...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by ChenTanyi — APPROVED** [review]
please fix ci error

**Comment by avjerafi** [comment]
Is there anything I can/should do to expedite the approval of this breaking change?

**Comment by ChenTanyi** [comment]
@avjerafi you need to fix the prettier check, please refer to the first comment. 

For breaking change, please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by avjerafi** [comment]
I've reviewed the Breaking Change policy, wiki and form. I don't believe this commit is rightly considered a _breaking_ change.  Currently, there are missing fields in the responses due to a wrongly structured definition of inheritance by use of a discriminator. This PR fixes this: the only effect of this change is the returning in the response of expected fields which are currently missing. This change is _aligning_ the behavior with the customer's current expectation.

**Comment by ChenTanyi** [comment]
@avjerafi You need to ask API Review Board @adrianhall to review. If it is emergent, please ask @akning-ms (ankun.ning@microsoft.com) for approve the breaking change.

Meanwhile, please fix the prettier check first. Otherwise, it could not be merged.

**Comment by avjerafi** [comment]
@akning-ms Following our mail correspondence, please approve this breaking change

**Comment by akning-ms** [comment]
approved breaking change as it is fixing bug in swagger, and this preview version plan to GA at the end of 2020

**Pull request merged**
