### PR TITLE
BatchAI. API spec 2018-03-01

### PR DESCRIPTION
**Pull request by AlexanderYukhanov**
These changes were reviewed in https://github.com/Azure/azure-rest-api-specs-pr/pull/396

Changes:

1. Job level mounting
2. Environment variables with secret values
3. Performance counters settings
4. Reporting of job specific path segment
5. Support for subfolders in list files api
6. Usage and limits reporting
7. Allow to specify caching type for NFS servers
8. Support for custom images
9. Added pyTorch toolkit support
10. Renamed EnvironmentSetting to EnvironmentVariable

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by mcardosos** [comment]
Hello @AlexanderYukhanov !
Question, is this based on an already existing API version?

**Comment by AlexanderYukhanov** [comment]
Yes, it's based on our public preview version. These changes were already reviewed and signed off on azure-rest-api-specs-pr, please take a look at https://github.com/Azure/azure-rest-api-specs-pr/pull/396.

**Comment by mcardosos** [comment]
For documenting this PR:
This PR is based on already existing PR in https://github.com/Azure/azure-rest-api-specs-pr/pull/396
Most of the time. the PR would be exactly the same as the one on the private repo, however, this PR also includes some modifications.
- `stdOutErrPathSuffix` property was added to `SetupTask` definition.
- `appInsightsDestination` property in `PerformanceCountersSettings` definition changed name to `appInsightsReference`, and now is a required property.
- `AppInsightsDestination` definition changed name to `AppInsightsReference`. It also added the `component` required property.

This changes make sense to me and CI is happy, so approved :D

**Review by mcardosos — APPROVED** [review]

**Comment by mcardosos** [comment]
@AlexanderYukhanov is this service already live?

**Comment by AlexanderYukhanov** [comment]
It's already in public preview with the previous API version.

**Comment by mcardosos** [comment]
I mean this API version, is it already GA?

**Comment by AlexanderYukhanov** [comment]
No, this new API which should go in GA soon

**Comment by mcardosos** [comment]
@AlexanderYukhanov ping us when it is GA so we can merge :)

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-libraries-for-java

**Pull request merged**
