### PR TITLE
[Hub Generated] Review request for Microsoft.ResourceGraph to add version 2019-04-01

### PR DESCRIPTION
**Pull request by chiragg4u**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/chiragg4u/azure-rest-api-specs/dev-resourcegraph-Microsoft.ResourceGraph-2019-04-01).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by chiragg4u** [comment]
@demyanenko can you please review these changes.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5519 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5519/commits/21cb93209ba4c7e2e632feec5a3925c8e6e2cf2a

**Review by sarangan12 — APPROVED** [review]

**Comment by demyanenko** [comment]
> @demyanenko can you please review these changes.

Looks good to me.

**Review by majastrz — APPROVED** [review]
Manually reviewed diff between preview and the new stable folders. The only difference are API versions and minor string changes.

**Pull request merged**
