### PR TITLE
Fix two types (integer instead of number) in InformationProtectionPolicies.json

### PR DESCRIPTION
**Pull request by bashahee**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by bashahee** [comment]
@markcowl Hi, this PR contains a fix of types.
As the corresponding SDK clients are already published, and they need to be fixed once this PR is merged, can we please merge the PR ASAP?

**Comment by bashahee** [comment]
@markcowl Kind ping.

**Comment by bashahee** [comment]
@markcowl Can we please merge this PR?

**Review by markcowl — APPROVED** [review]

**Comment by markcowl** [comment]
need to fix the model validation error as secified here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=363378&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=25

**Review by markcowl — CHANGES_REQUESTED** [review]
Issues showing inb model validation of the examples, please correct: https://dev.azure.com/azure-sdk/public/_build/results?buildId=363378&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=25

**Comment by bashahee** [comment]
@markcowl Hi, thanks for the review, errors were fixed.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
