### PR TITLE
ProximityPlacementGroup definition update for colocation status

### PR DESCRIPTION
**Pull request by aspand**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by hyonholee** [comment]
Hi, why LintDiff failed with this error? 'SubResourceWithColocationStatus' is not a top level definition.  The definition is used only inside of 'ProximityPlacementGroupProperties' definition.

2019-12-17T22:12:06.5291570Z Potential new ARM errors
2019-12-17T22:12:06.5292078Z ========================
2019-12-17T22:12:06.5299404Z R2020 - RequiredPropertiesMissingInResourceModel
2019-12-17T22:12:06.5301075Z Model definition 'SubResourceWithColocationStatus' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.
2019-12-17T22:12:06.5302080Z   at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:5912
2019-12-17T22:12:06.5302654Z 
2019-12-17T22:12:06.5303393Z R3006 - BodyTopLevelProperties
2019-12-17T22:12:06.5304634Z Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'SubResourceWithColocationStatus' has extra properties ['colocationStatus'].
2019-12-17T22:12:06.5305532Z   at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:5918

**Review by hyonholee — APPROVED** [review]

**Review by zikalino — APPROVED** [review]

**Comment by akning-ms** [comment]
R3006 - BodyTopLevelProperties
Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'SubResourceWithColocationStatus' has extra properties ['colocationStatus'].
  at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:5918
Add ARM team to confirm as it break R3006 Lint Rule

**Comment by aspand** [comment]
> R3006 - BodyTopLevelProperties
> Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition 'SubResourceWithColocationStatus' has extra properties ['colocationStatus'].
> at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:5918
> Add ARM team to confirm as it break R3006 Lint Rule

SubResourceWithColocationStatus is not a top level properties.  hyonholee  is already added a comment for the same

**Comment by pilor** [comment]
The `SubResource` model is incorrectly labeled as `x-ms-azure-resource`.  Thus, the linter is treating it as a resource and expecting it to follow those conventions.  Since your new definition inherits from it it inherits that condition as well.

**Review by pilor — APPROVED** [review]

**Pull request merged**
