### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version stable/2023-05-01

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/FumingZhang-containerservice-Microsoft.ContainerService-2023-05-01...main/).
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. 06/08.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. ASAP.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
For [Breaking Change(Cross-Version)](https://github.com/Azure/azure-rest-api-specs/pull/24379/checks?check_run_id=14124928343), the violated rule [1011 - AddingResponseCode](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1011.md) is caused by the change in commit [a2ddb53](https://github.com/Azure/azure-rest-api-specs/pull/24379/commits/a2ddb53376bb6f561928229c8fb3afadbc93d2a4), which fixed the violated rule [PutResponseSchemaDescription](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-response-schema-description.md) in CI [Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/24379/checks?check_run_id=14124759884) (based on commit https://github.com/Azure/azure-rest-api-specs/pull/24379/commits/e7cd9011e6e54a34e7beba3486ff6058dedd239b). Will seek approval from breaking change review board first and continue with the ARM review afterwards.

**Comment by FumingZhang** [comment]
For CI failures [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/24379/checks?check_run_id=14124928667), it's **expected** as the reported missing API originates from four files
  - [aks/stable/2017-07-01/containerService.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2017-07-01/containerService.json), which is deprecated and replaced by AKS (managedClusters).
  - [aks/stable/2017-08-31/managedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2017-08-31/managedClusters.json), the missing API (`.../managedClusters/{}/accessProfiles/{}`) is deprecated and replaced by [ListClusterUserCredentials](https://docs.microsoft.com/rest/api/aks/managedclusters/listclusterusercredentials) or [ListClusterAdminCredentials](https://docs.microsoft.com/rest/api/aks/managedclusters/listclusteradmincredentials) according to the need.
  - [aks/stable/2019-08-01/location.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2019-08-01/location.json), the missing API (`.../locations/{}/orchestrators`) is deprecated, and has been replaced by a new API `/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/kubernetesVersions` in [2023-03-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-03-01/managedClusters.json#L115) and [2023-03-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-03-02-preview/managedClusters.json#L115).
  - [aks/stable/2019-04-30/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2019-04-30/openShiftManagedClusters.json), which is deprecated and replaced by [redhatopenshift](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/redhatopenshift/resource-manager).

**Comment by v-xuto** [comment]
@FumingZhang  Please fix CI checks errors (`Avocado`), you can refer to this [comments](https://github.com/Azure/azure-rest-api-specs/pull/24379#issuecomment-1583894550) or  https://aka.ms/ci-fix on how to fix it.

**Comment by FumingZhang** [comment]
Hey @v-xuto, the missing APIs are all deprecated as what I've explained in [comment](https://github.com/Azure/azure-rest-api-specs/pull/24379#issuecomment-1583963777).

[MISSING_APIS_IN_DEFAULT_TAG](https://github.com/Azure/avocado/blob/main/README.md#missing_apis_in_default_tag)

> Level: ERROR
> 
> The default tag should contain all APIs. The API path `${0}` is not in the default tag. Please make sure the missing API swaggers are in the default tag.
> 
> To fix this error. You should add the missing API swaggers to the default tag. **If the missing API swaggers are deprecated, in this case this error could be ignored.**

**Comment by v-xuto** [comment]
> Hey @v-xuto, the missing APIs are all deprecated as what I've explained in [comment](https://github.com/Azure/azure-rest-api-specs/pull/24379#issuecomment-1583963777).
> 
> The same error is approved by PR assignee in a sibling [PR #24245](https://github.com/Azure/azure-rest-api-specs/pull/24245#issuecomment-1571456186) which adds the new preview API version 2023-05-02-preview.
> 
> [MISSING_APIS_IN_DEFAULT_TAG](https://github.com/Azure/avocado/blob/main/README.md#missing_apis_in_default_tag)
> 
> > Level: ERROR
> > The default tag should contain all APIs. The API path `${0}` is not in the default tag. Please make sure the missing API swaggers are in the default tag.
> > To fix this error. You should add the missing API swaggers to the default tag. **If the missing API swaggers are deprecated, in this case this error could be ignored.**

Avocado errors are confirmed by the PR authors that's expected and can be ignored.

**Comment by v-xuto** [comment]
@JeffreyRichter Please help review the `breaking change` in this PR.

**Comment by v-xuto** [comment]
@FumingZhang Please contact the `ARM team` to review this PR. If you don't know how to contact `ARM team`, you can check the third of the `ARM API Review Checklist` in the [first comment](https://github.com/Azure/azure-rest-api-specs/pull/24379#issue-1749025968).

**Review by v-xuto — APPROVED** [review]

**Pull request merged**
