### PR TITLE
Add deprecation message for EA pricesheets download

### PR DESCRIPTION
**Pull request by jayati-tehri**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by jayati-tehri** [comment]
Updating current rest api docs to add a missed property and adding deprecation message note.

**Comment by mentat9** [comment]
@jayati-tehri - Please choose the template at the top and fill it out. This is required to get your PR reviewed.

**Comment by jayati-tehri** [comment]
> @jayati-tehri - Please choose the template at the top and fill it out. This is required to get your PR reviewed.

I have tried that even while creating the PR, but clicking on the link doesn't change anything for me

**Comment by jayati-tehri** [comment]
> > @jayati-tehri - Please choose the template at the top and fill it out. This is required to get your PR reviewed.
> 
> I have tried that even while creating the PR, but clicking on the link doesn't change anything for me

@mentat9 Create a new PR https://github.com/Azure/azure-rest-api-specs/pull/31049

**Pull request closed without merging**
