### PR TITLE
[LUIS] Adding app version settings APIs to swagger file.

### PR DESCRIPTION
**Pull request by LanaShafik**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by mohabghanem** [comment]
@yangyuan Please have a look at this PR

**Review by yangyuan — APPROVED** [review]

**Comment by hovsepm** [comment]
@LanaShafik what is the difference between `VersionSettingObject` and `VersionSettingUpdateObject` models? they seems to have the same fields. Can this be merged into one?

**Comment by LanaShafik** [comment]
@hovsepm 
They are the two different objects in the code base:
public class AppVersionSettingObject
    {
        [JsonIgnore]
        public Guid AppVersionId { get; set; }

        [JsonProperty("name")]
        public string Key { get; set; }

        [JsonProperty("value")]
      }

public class SettingUpdateObject
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

So, one contains the app version id while the does not.

**Comment by hovsepm** [comment]
@LanaShafik my question is not about `AppVersionSettingObject` object. I'm asking about `VersionSettingObject` and `VersionSettingUpdateObject` objects. What are their differences?

**Comment by hovsepm** [comment]
@LanaShafik here is what you have in your swagger:
```
    "VersionSettingObject": {
      "description": "Object model of an application version setting.",
      "type": "object",
      "properties": {
        "name": {
          "description": "The application version setting name.",
          "type": "string"
        },
        "value": {
          "description": "The application version setting value.",
          "type": "string"
        }
      }
    },
    "VersionSettingUpdateObject": {
      "description": "Object model of an application version updated setting.",
      "type": "object",
      "properties": {
        "name": {
          "description": "The application version setting name.",
          "type": "string"
        },
        "value": {
          "description": "The application version updated setting value.",
          "type": "string"
        }
      }
    }
```

**Comment by hovsepm** [comment]
@mohabghanem I need more explanation. What do you mean by `their attributes will differ`? If there is a filed that you want to stay read-only (i.e. clients will not send it back to server) you should rather mark those fields as `"readOnly": true`. Otherwise please explain what will be different in these two objects in the future. 

According to your swagger changes `VersionSettingObject` will be used in `Settings_List` method and `VersionSettingUpdateObject` will be used in `Settings_Update` method. What I read from this is that you will have List and Update calls to the server from the client. Now from the developer point of view to accomplish some kind of their scenario they will have to List all the settings (through List) and may need to update some of them. And now for update after list call they will **have to copy all the fields** from the object retrieved from List call, modify whatever they need and send a new object to Server through Update call. I do not think forcing developers to implement Clone functionality for list/update scenario is a good approach.

**Comment by LanaShafik** [comment]
@hovsepm 
please check the updates.

**Review by hovsepm — APPROVED** [review]

**Pull request merged**
