### PR TITLE
[Azure Portal] Rename one portal cmdlet parameter

### PR DESCRIPTION
**Pull request by YalinLi0312**
Globally rename the parameter from "dashboardName" to "name" in az portal.
Related cli extension PR: https://github.com/Azure/azure-cli-extensions/pull/1428 
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by RodgeFu** [comment]
@fengzhou-msft , i remember you mentioned --dashboard-name should be used instead of --name. could you help to check whether this change is fine? you can find the CLI change introduced at "azure-cli-extensions" comment block above. thanks.

**Comment by YalinLi0312** [comment]
Do you mean this [comment](https://github.com/Azure/azure-cli-extensions/pull/1428#discussion_r399900326)? I think we agreed on using --name/-n in cmdlet, while @fengzhou-msft prefer using dashboard_name in function's parameter inside file _params.py. And the rename in cmdlet has been approved( [portal design spec](https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience-Redmondteam/EcKysBANIBdLnovagQfjeNMBiWcxaNhbRFT_umPSYn5IRg?e=Jyb4An)). 
The portal extension customization right now is based on the cmdlet rename codegen result, pls let me know if I need to change the portal extension to the codegen result without cmdlet rename.

**Comment by fengzhou-msft** [comment]
@YalinLi0312 is right. The generated code should be like `c.argument('dashboard_name', options_list=['--name','-n'])`. However, the configuration would not lead to the right code. We should change the `alias` instead of `name`. @qiaozha submitted a PR to add the options in  generated code and also the support for configuration. 

Let's wait for the release of a new autorest.az. This should be handled automatically. If anything wrong, we can then add the configuration like [this](https://github.com/Azure/autorest.az/pull/333/files#diff-18dc7663b1cbe50c9f22d4162b301b03R20-R27).

**Comment by RodgeFu** [comment]
@YalinLi0312 , the support should have been in the beta release below, please give it a try and let us know if there is more issues. thanks.
https://github.com/Azure/autorest.az/releases/tag/1.3.4b2

**Comment by YalinLi0312** [comment]
Thanks Rodge, I have tried this pre-release version, LGTM. Will close this RP.

**Pull request closed without merging**
