### PR TITLE
CSharp namespace for resource-manager, move data-plane API specs to resource-manager, remove UsageMetrics API from the spec

### PR DESCRIPTION
**Pull request by gucalder**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.

Fixing issues
•#1837: [Monitor] The namespace for C# code of resource-manager folder is incorrect  fix cSharp namespace for resource-manager,
•#1838: [Monitor] Move the specs in the folder data-plane to the resource-manager folder : move data-plane API specs to resource-manager,
•#1839: remove UsageMetrics API from the spec

- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
Related PR https://github.com/Azure/azure-rest-api-specs/pull/1840.

**Comment by sergey-shandar** [comment]
@gucalder could you login to Travic-CI, at least once, so we start the CI?

**Comment by gucalder** [comment]
I just did. Travis responded this: We've successfully synchronized your details from GitHub.
We will redirect you to your profile in a few seconds.

**Comment by sergey-shandar** [comment]
@gucalder thanks. It looks like the CI is triggered after I reopened the PR.

**Comment by gucalder** [comment]
Great. Thank you!

**Comment by gucalder** [comment]
The errors reported are known:
- Three are due to a incorrect firing of a rule when checking "odata.type" property for polymorphic types.
- The other error is that we are missing the PATCH in one of our APIs. The team in charge has planned to specify it (it is already implemented in their backend) in November/December if I am not wrong.

**Comment by lmazuel** [comment]
@sergey-shandar Any concerns here? I need a new SDK for Python and CLI (FYI @troydai )

**Comment by sergey-shandar** [comment]
@gucalder the changes are LGTM. Have you tried to generate C# SDK with this changes?

**Comment by lmazuel** [comment]
I generated the code from the branch:
https://github.com/Azure/azure-sdk-for-python/pull/1563

Seems good to me, I see no obvious reason to do not merge.

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
