### PR TITLE
Add Automanage resource provider preview

### PR DESCRIPTION
**Pull request by abhinav-ghai**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by abhinav-ghai** [comment]
1 Lint error, I believe tool is catching it incorrectly since we have an extension provider resource type for Microsoft.Compute:

PathResourceProviderMatchNamespace
The last resource provider 'Microsoft.Automanage, Microsoft.Compute' doesn't match the namespace.

**Review by majastrz — APPROVED** [review]
Reviewed delta between the already approved PR (https://github.com/Azure/azure-rest-api-specs-pr/pull/1283) and this one and it looks good to me. Signed off from ARM side.

**Comment by fengzhou-msft** [comment]
@abhinav-ghai please fix the [LintDiff error](https://github.com/Azure/azure-rest-api-specs/pull/10344#issuecomment-668898139).

**Comment by abhinav-ghai** [comment]
> @abhinav-ghai please fix the [LintDiff error](https://github.com/Azure/azure-rest-api-specs/pull/10344#issuecomment-668898139).

I think this error is caught incorrectly by tool. This path is for a extension resource type which will have two provider names in correct order. The tool is incorrect in marking this as error.

**Comment by fengzhou-msft** [comment]
@raych1 can you help to take a look at the LintDiff error in this PR. According to @abhinav-ghai's comments above, it should not be an error.

**Comment by raych1** [comment]
@abhinav-ghai , can you refer to [rule4018](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r4018-operationsapiresponseschema) for the fix on lintDiff failures? /CC @jianyexi

**Comment by raych1** [comment]
@jianyexi , lintDiff passed in unified pipeline run. Can you advise on this PR merge?

**Pull request merged**
