### PR TITLE
Rename property in sample ContosoWidgetManager

### PR DESCRIPTION
**Pull request by mikeharder**
- Aligns with naming guidelines
- Continuation of #23757

### CODE REVIEW

**Review by JeffreyRichter — APPROVED** [review]

**Comment by mikeharder** [comment]
@weshaggard: Do you know how the breaking change notifications should be handled, give this is only a sample?

**Comment by JeffreyRichter** [comment]
Since it is just a sample, make all the breaking changes you wat - who cares?

**Comment by mikeharder** [comment]
> Since it is just a sample, make all the breaking changes you wat - who cares?

Yes, I can override the branch protections and just merge, but I was wondering if there is a better process?

**Comment by weidongxu-microsoft** [comment]
Please check ModelValidation CI. You need to update the sample (of this sample) as well, e.g. https://github.com/Azure/azure-rest-api-specs/blob/6474e383d60b518fa1919ca65921ffcddf4dcb6e/specification/contosowidgetmanager/data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview/examples/Widgets_ListWidgetsSample.json

**Review by tjprescott — APPROVED** [review]

**Comment by mikeharder** [comment]
> Please check ModelValidation CI. You need to update the sample (of this sample) as well, e.g. https://github.com/Azure/azure-rest-api-specs/blob/6474e383d60b518fa1919ca65921ffcddf4dcb6e/specification/contosowidgetmanager/data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview/examples/Widgets_ListWidgetsSample.json

Should I update the `examples` in a text editor, or are these `examples` generated by a tool that I can re-run to re-generate the examples?

@weshaggard: How did you generate the `examples` the first time?

**Comment by weshaggard** [comment]
>@weshaggard: How did you generate the examples the first time?

I didn't create them originaly but at any rate yes we have to manually maintain those files.

**Comment by mikeharder** [comment]
> > @weshaggard: How did you generate the examples the first time?
> 
> I didn't create them originaly but at any rate yes we have to manually maintain those files.

I manually updated the examples, but I noticed there are two copies of the examples under the following folders.  Can one of these be deleted?

- `specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview`
- `specification/contosowidgetmanager/data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview`

**Comment by weshaggard** [comment]
It is my understanding the ones under the swagger directory get copied there as part of the tsp compile step that runs the autorest emitter.

**Comment by weidongxu-microsoft** [comment]
> I manually updated the examples, but I noticed there are two copies of the examples under the following folders. Can one of these be deleted?
> 
> * `specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview`
> * `specification/contosowidgetmanager/data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview`

Yeah, basically this `examples-directory` options tells typespec-autorest to read the example from typespec project and copy it to swagger folder.
https://github.com/Azure/azure-rest-api-specs/blob/cdbbf043ab2e4f4b3736099e716410eb62622348/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml#L18

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
