### PR TITLE
Add Batch API version 2017-09-01.6.0

### PR DESCRIPTION
**Pull request by matthchr**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by matthchr** [comment]
Reviewers, please ignore the first 2 commits "Add new API version" and "Update to use the new API version string" as they are just copying the existing specification and updating version strings. Look at the commits following that. (Especially the "Add new features to Swagger specification" one)

**Comment by anuchandy** [comment]
@matthchr thanks! Adding WaitForARMFeedack label since this is a new API version. @ravbhatnagar as matthchr mentioned see the commit  "Add new features to Swagger specification" for the new features added in this api version.

**Comment by matthchr** [comment]
@anuchandy This is a data plane Swagger specification, not an ARM spec, so ARM doesn't need to be involved I don't think.

**Comment by anuchandy** [comment]
@matthchr thanks for clarifying, removed the label.

**Comment by anuchandy** [comment]
@matthchr there are few [errors](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/278000332) reported by linter due to the violation of https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-automated-guidelines.md#r3014-bodypropertiesnamescamelcase

Since this is a new api version can we fix them?

```
publicFQDN -> publicFqdn
inboundNATPools -> inboundNatPools
userCPUTime -> userCpuTime
```

[It seems linter is not giving correct suggestion]

\\cc @kirthik, @alvadb

**Comment by matthchr** [comment]
@anuchandy, While I technically agree that those suggestions are good, we didn't fix them for these reasons:

1. At this point we have had those names for quite some time (years in some cases), and it takes a service change to change these things.
2. Given that is a breaking change that can negatively impact customers, we generally have preferred not to fix "nitpicky" naming things like that in existing APIs because it will just cause distress to downstream customers who end up having to fix these little things here and there when they upgrade.

So we aren't planning on fixing any of those naming issues for old properties. For new properties we will strive to avoid hitting these naming issues though.

**Comment by anuchandy** [comment]
@matthchr fine, taking this PR. (Just FYI - In our automated monthly reports these violations will appear, but seems you have proper justifications in case review board arise concerns)

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
