### PR TITLE
[Hub Generated] Review request for Microsoft.ApiManagement to add version preview/2019-12-01-preview

### PR DESCRIPTION
**Pull request by solankisamir**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/apim-2019-12-01-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by NullMDR** [comment]
Please update readme.md

**Comment by solankisamir** [comment]
@NullMDR .net sdk might require some breaking changes in the SchemaContract definition, as we had put in custom implementation there. So the failure is expected.

**Comment by NullMDR** [comment]
@isra-fel Another .net generation failure FYI. From log I guess it's related to the dotnet project settings.

@solankisamir Everything else looks good to me. You can fix the prettier check by following https://aka.ms/AA6h31t

**Comment by isra-fel** [comment]
Got it. I'm fine with .net SDK

**Comment by solankisamir** [comment]
@NullMDR @isra-fel created a clone of this PR https://github.com/Azure/azure-rest-api-specs/pull/8066, as I couldn't edit changes in this branch.

**Pull request closed without merging**
