### PR TITLE
Fix `identity` in servicebus swagger

### LINKED ISSUE #10379: The `identity` in service bus namespace is wrong
Problematic swagger: https://github.com/Azure/azure-rest-api-specs/blob/6ea6ec5c1685147b140f3991d1f7145d1ca124d2/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2018-01-01-preview/servicebus-preview.json#L1001

The `identity` is expected to be in the root level of the request body, but now it is in the `properties` level.

Justification: I have tried the following request:
```
PUT https://management.azure.com/subscriptions/REDACTED/resourceGroups/group1/providers/Microsoft.ServiceBus/namespaces/test-namespace?api-version=2018-01-01-preview
```
with the body
```
{
    "location": "westus2",
    "properties": {
        "zoneRedundant": false
    },
    "sku": {
        "name": "Premium",
        "tier": "Premium",
        "capacity": 1
    },
    "tags": {
        "source": "terraform"
    },
    "identity": {
        "type": "SystemAssigned"
    }
}
```
works fine, and get the response:
```
{
    "sku": {
        "name": "Premium",
        "tier": "Premium",
        "capacity": 1
    },
    "id": "/subscriptions/REDACTED/resourceGroups/group1/providers/Microsoft.ServiceBus/namespaces/test-namespace",
    "name": "test-namespace",
    "type": "Microsoft.ServiceBus/Namespaces",
    "location": "West US 2",
    "tags": {
        "source": "terraform"
    },
    "identity": {
        "principalId": "REDACTED",
        "tenantId": "REDACTED",
        "type": "SystemAssigned"
    },
    "properties": {
        "zoneRedundant": false,
        "provisioningState": "ActivatingIdentity",
        "metricId": "85b3dbca-5974-4067-9669-67a141095a76:test-namespace",
        "createdAt": "2020-08-07T06:19:16.72Z",
        "updatedAt": "2020-08-07T06:19:16.72Z",
        "serviceBusEndpoint": "https://test-namespace.servicebus.windows.net:443/",
        "status": "Activating"
    }
}
```

Please note in this working example, the `identity` is in the root level rather than as defined in the swagger - in the `properties` level. But if I change my request body by moving the `identity` block into `properties`, the created namespace will not have an identity.

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-rest-api-specs/issues/10379

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Please do not merge this PR until the service team approves this.

**Review by v-Ajnava — APPROVED** [review]
Approved, its bug fix.

**Comment by erich-wang** [comment]
@ArcturusZhang, is this PR ready to merge?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang, is this PR ready to merge?

Yes, the service team has approved this change, Please go ahead and merge this fix.

**Pull request merged**
