### PR TITLE
fix: Microsoft.Sql model validation errors

### PR DESCRIPTION
**Pull request by nschonni**
- Remove "description" not it schema
- Remove empty "body" for RESPONSE_SCHEMA_NOT_IN_SPEC errors
- IsAzureMonitorTargetEnabled -> isAzureMonitorTargetEnabled
- "State" -> "state"
- emailAccountAdmins "true" -> true
- Add 202 response for RestorePoints_Create
- password -> certPassword for ManagedInstanceTdeCertificates_Create and TdeCertificates_Create

### CODE REVIEW

**Review by jaredmoo — APPROVED** [review]

**Comment by NullMDR** [comment]
@openapibot sdkautomation rebuild

**Comment by nschonni** [comment]
Found a few in the other sql verions, I'll try and add them to this PR

**Comment by nschonni** [comment]
@jaredmoo I pushed updates to the preview specs in a separate commit if you want to take a look. I can also split those off to another PR if you prefer

**Comment by NullMDR** [comment]
@openapibot sdkautomation rebuild

**Review by michaeljqzq — APPROVED** [review]

**Pull request merged**
