### PR TITLE
Microsoft.Sql - Added data sync to package-2015-05-preview

### PR DESCRIPTION
**Pull request by ScottHolden**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by balajikris** [comment]
@ScottHolden - I assume those specs were reviewed and merged earlier? this PR is about adding those to readme so that autorest generates SDKs for them?

**Comment by jaredmoo** [comment]
Thanks for the contribution Scott!

I have been holding off on adding Swagger files to readme.md until we have a PR to add scenario tests to azure-sdk-for-net. Otherwise we get into a tricky situation where one feature might have tests implemented be ready to ship in azure-sdk-for-net (and other clients) but the release could get blocked by another unrelated feature not having scenario tests yet.

Do you have a particular need for data sync and advisor SDK support in an app you are working on?

**Comment by ScottHolden** [comment]
Hey guys,
Sorry for the lack of info in the pull request.

Basically need to use data sync via the .Net Sql Management Client, I just included 'advisors' while I was there. Happy to remove it and trim it back down to just data sync :)

We have been using the data sync client via a fork with these changes for a little while, wanted to pull them back in so we can jump back onto the official release train :)

I'm half way through writing data sync scenario tests for the azure-sdk-for-net Management.Sql, I'll put in a pull request over there when I'm done and link it back to this pull request.

Let me know if you need any more info :)

**Comment by jaredmoo** [comment]
That sounds wonderful! Yes please remove advisors for now.

In case it is helpful, there are scenario tests that were written for the old non-swagger-based sdk at https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Sql/Sql.Tests/ScenarioTests/Sql2.DataSyncScenarioTest.cs . The test setup code will be very different but it should be possible to adapt the overall scenario and some of the logic there.

Please let me know if you have any questions or issues with writing the SDK test.

**Comment by jaredmoo** [comment]
Looks good, I will approve this when I approve the corresponding azure-sdk-for-net change. :)

**Comment by balajikris** [comment]
Rock on guys! Looks like I have nothing much to do here, other than merge when @jaredmoo signs off after looking at the SDK change :-) Thanks both of you!

**Comment by ScottHolden** [comment]
Corresponding azure-sdk-for-net pull request can be found at:
https://github.com/Azure/azure-sdk-for-net/pull/3558

**Comment by jaredmoo** [comment]
I approve Azure/azure-sdk-for-net#3558 so I also approve this.

**Review by balajikris — APPROVED** [review]

**Comment by balajikris** [comment]
Thanks @ScottHolden and @jaredmoo

**Pull request merged**
