### PR TITLE
Add Get All Policies under Subscription in Version 2022-05-01.

### PR DESCRIPTION
**Pull request by neelesh06**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by neelesh06** [comment]
This PR is adding the missing subscription level GET policies API. this is not changing any parameter and not touching any existing API. No breaking change for the customer. Code already support the Subscription level GET api.

**Comment by qiaozha** [comment]
@neelesh06 Could you help fix those lintDiff, semantic, model validation errors ?

**Comment by qiaozha** [comment]
@JeffreyRichter Could you help take a look at the breaking change ? Thanks

**Comment by JeffreyRichter** [comment]
I see a new path being added: https://github.com/Azure/azure-rest-api-specs/pull/22393/checks?check_run_id=11055506302
This requires a new api-version and then it will not be considered a breaking change.

**Comment by neelesh06** [comment]
@JeffreyRichter here we are just adding a new missing GET API on subscription level. this API does not break any existing api's. we are not adding new parameter or adding any new value for the parameter. this API implementation is already present in the RP. This is just new api publishing. Does this still consider as breaking change. This will not affect any customer calls or any of their template.

**Comment by JeffreyRichter** [comment]
Azure's formal versioning policy is that ANY change to an API contract **_requires_** a new api-version. This avoid having multiple versions of a single api-version which customers can't rationalize about.

**Comment by neelesh06** [comment]
I agree on when any api contract change than it needs new api version because customers' needs to change their template and scripts. but here we are not changing any api contract. We are just adding new api (whose implementation is already present in the RP). On this change there is no effect on customer running the template or scripts. It is Subscription level get that was missed in last PR.

**Comment by JeffreyRichter** [comment]
Adding a new path IS changing the contract - it now has a new path that it didn't have before.
So, if a customer asks: Which api-version has this new path then some version of 2022-05-01 does and some version of 2022-05-01 doesn't. This is confusing for customers (and Azure Customer Support) and because we optimize for the customer experience, Azure's formal policy is to not allow this and this is why our repo tooling is flagging your PR as breaking our policy.

**Comment by neelesh06** [comment]
Appreciate your time Actually this was asks from customers as well as supports that we do not have subscription level GET api in the same version (this is one of the required GET api) although we have implementation of this api in RP. If we can support this GET api in the same version, then we can avoid customers to upgrade the version and if they really need the new api then they will just add in the same version. Their existing scripts and template will not get affected.  I understand that the tool is robust and check all the conditions, but can you please review this and check if this can be added in the same version?

**Comment by JeffreyRichter** [comment]
You're asking me to violate azure's policy and I don't feel comfortable doing that. If the customer has to change their code to call this new path anyway, then it is trivial for them to also change the api-version.

**Comment by neelesh06** [comment]
Sorry @JeffreyRichter, I am not asking to violate the policy, but this scenario is little unique where we are not changing any existing API's contract. we are only adding new API that RP already supported, and we are only publishing that to customer. I was asking to just review the swagger and scenario and see if this can qualify as non-breaking change. I talked to some of the API reviewer before raising this PR and they said this may qualify for the non-breaking change.

**Comment by JeffreyRichter** [comment]
Was this path added after 2022-05-01 shipped or did 2022-05-01 ALWAYS have this path as part of it? If the former, then your service team should not have done this as this violates Azure's policy. If the latter, then the swagger should never have been published missing the path but I can approve it.

**Comment by neelesh06** [comment]
@JeffreyRichter, thanks for reconsideration. We have this path available before we shipped the 2022-05-01. It was missed to add this GET API in our last publishing of swagger.

**Review by qiaozha — APPROVED** [review]

**Pull request merged**
