### PR TITLE
enableHttpCorrelationHeaders property is added to the Diagnostic entity

### PR DESCRIPTION
**Pull request by promoisha**
Please, do not merge yet.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by praries880** [comment]
@azuresdkci add to whitelist

**Review by praries880 — APPROVED** [review]
Looks good to me

**Comment by praries880** [comment]
@promoisha Has this change been through an ARM/API review?

**Comment by praries880** [comment]
@veronicagg Can you help merge this change in? I do not have permissions to merge stuff into the branch.

**Comment by promoisha** [comment]
@praries880 @veronicagg folks, like I mentioned in the description, please, do not merge it yet!

**Comment by veronicagg** [comment]
@promoisha I've edited the title to indicate that we shouldn't merge yet. thx.

**Comment by promoisha** [comment]
@veronicagg could you merge the PR now? Thanks! :)

**Comment by promoisha** [comment]
@veronicagg, @praries880 Friendly ping to merge the PR, thanks!

**Pull request merged**
