### PR TITLE
Update informationProtectionPolicies.json

### PR DESCRIPTION
**Pull request by ranisha2**
Update informationProtectionPolicies.json
- Fix PUT: Missing parameter
- Add missing parameters to the sensitivity label and information type

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by bashahee** [comment]
@weidongxu-microsoft can this PR be merged?

The existing swagger is invalid, hence the failures in this PR's tests. Moreover, existing SDK clients are not usable now, so we need this swagger merged in order to update SDK clients package with working clients.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
@bashahee

I will email arm review on this, with your reason here (this is still a needed step). Then I will ask PM to force merge.

**Comment by bashahee** [comment]
Thanks @weidongxu-microsoft for the help!

**Review by pilor — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
@akning-ms Can you help merge this?

BreakingChange is due to existing swagger is invalid (hence this PR).

**Pull request merged**
