### PR TITLE
ServiceBus : Added trustedServiceAccessEnabled optional property in Networkrulesets fix for ICM 203561654

### PR DESCRIPTION
**Pull request by v-Ajnava**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by v-Ajnava** [comment]
PR is fix for : https://portal.microsofticm.com/imp/v3/incidents/details/203561654/home

**Comment by v-Ajnava** [comment]
Hi @ArcturusZhang , can you please review the PR. its a fix for : https://portal.microsofticm.com/imp/v3/incidents/details/203561654/home

**Comment by ArcturusZhang** [comment]
Hi @v-Ajnava this PR looks good to me.

But there is a problem that this PR introduces a breaking change to a stable api-version, could you please follow the breaking change review process as documented in this [doc](http://aka.ms/AzBreakingChangesPolicy)?

**Comment by v-Ajnava** [comment]
> Hi @v-Ajnava this PR looks good to me.
> 
> But there is a problem that this PR introduces a breaking change to a stable api-version, could you please follow the breaking change review process as documented in this [doc](http://aka.ms/AzBreakingChangesPolicy)?

we have done the similar change in the Eventhub Service : https://github.com/Azure/azure-rest-api-specs/pull/10327

**Comment by ArcturusZhang** [comment]
Hi @v-Ajnava there is a big difference between this PR and the merged PR for eventhub: the eventhub PR is introducing breaking changes to a *preview* api-version, but this PR is intorducing breaking changes to a *stable* PR

**Comment by v-Ajnava** [comment]
> Hi @v-Ajnava there is a big difference between this PR and the merged PR for eventhub: the eventhub PR is introducing breaking changes to a **preview** api-version, but this PR is intorducing breaking changes to a **stable** PR
> The breaking change review policies is more strict when breaking changes are introduced to a stable api-version. Please follow the policy to make a review request. Thanks

here is the PR to split the swagger and make similar changes as Event Hub: https://github.com/Azure/azure-rest-api-specs/pull/10071.

**Comment by v-Ajnava** [comment]
Hi @ArcturusZhang , can you please help getting this reviewed by AzureAPIBorad.

**Comment by v-Ajnava** [comment]
Hi @ArcturusZhang , PR https://github.com/Azure/azure-rest-api-specs/pull/10071 is merged and now the new property is in 2018-preview API version. can you please review the PR.

**Comment by ArcturusZhang** [comment]
Hi @v-Ajnava please follow the process documented here: https://microsoft.sharepoint.com/teams/azureecosystem/servicerings/Shared%20Documents/Breaking%20Changes/Azure%20Breaking%20Changes%20Program%20Definition-%20V1.0.pdf

**Comment by v-Ajnava** [comment]
> Hi @v-Ajnava please follow the process documented here: https://microsoft.sharepoint.com/teams/azureecosystem/servicerings/Shared%20Documents/Breaking%20Changes/Azure%20Breaking%20Changes%20Program%20Definition-%20V1.0.pdf

Seems like I donth access to the document, I have requested for access.

**Comment by ArcturusZhang** [comment]
Hi @v-Ajnava do we have any update on the breaking change review?

**Comment by ArcturusZhang** [comment]
Hi, @v-Ajnava any updates?

**Comment by ArcturusZhang** [comment]
Hey @v-Ajnava do we have any update on this?

**Comment by ArcturusZhang** [comment]
Hey @v-Ajnava do we have any update on this PR?

**Pull request closed without merging**
