### PR TITLE
currentOrchestratorVersion is a read-only property

### PR DESCRIPTION
**Pull request by wenxuan0923**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [x] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by wenxuan0923** [comment]
Hi @dw511214992 , the breaking change is caused by adding the missed `readOnly = true` to the field 
currentOrchestratorVersion, which is already exist in the stable version 2022-04-02. I am trying to make the preview version to be aligned with it. Any user attempt to set the field in any way will get rejected.

**Comment by matthchr** [comment]
@dw511214992 - I think what @wenxuan0923 said above is correct, but missing a key detail.

This PR should not require API breaking change review because the actual behavior of our API for the `2022-03-02-preview` and `2022-04-02-preview` apis is that this field cannot be changed. Changes to this field are ignored by the RP. This has been the case since those APIs were released. We just missed marking it as `readOnly` in the Swagger and are correcting it. 

The field has always been readonly in actuality. We just missed putting it into Swagger and @wenxuan0923 is correcting that.

**Comment by dw511214992** [comment]
@matthchr there are many sdks generated from swagger. If the property is changed to readOnly, there will be breaking changes in sdk side. So, I think you still need to follow the action for breaking change review. thanks

**Comment by matthchr** [comment]
@dw511214992 - if the bug in the Swagger had been we had an incorrectly named field (which didn't work at all), we could correct it, right? The SDK is incorrect and doesn't reflect the actual service API. This is getting flagged when we correct it in a future API: https://github.com/Azure/azure-rest-api-specs/pull/19086/checks?check_run_id=6449944854 (cross version breaking changes).

There's going to be a break no matter how we slice it _in the SDK_. But the API isn't breaking. The API review process is for breaks to the API. There is no API break here. We're correcting a "bug" in the Swagger.

**Comment by matthchr** [comment]
As mentioned in chat we possibly could avoid merging this PR and bypass the cross-version-breaking-change check when our next PR lands? @FumingZhang might be able to comment if that would work or not. We should do one or the other though because the Swagger isn't actually reflecting the real behavior of the API currently.

**Comment by dw511214992** [comment]
@matthchr will this PR be merged? If yes, please go head with breaking change review. thanks

**Pull request closed without merging**
