### PR TITLE
fix(metricAlert_API): add missing properties to web test metric alert…

### PR DESCRIPTION
**Pull request by adibiton**
… (#7907)

* fix(metricAlert_API): add missing properties to web test metric alert

* docs(metricAlert_API): change properties description

* fix(metricAlert_API): remove templateType from webtest metric alert rules

* fix(metricAlert_API): change subscription description

* fix(metricAlert_API): prettier checks

* fix(): lint warnings

* fix(): lint warnings

* fix(): run prettier

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by vigaur** [comment]
Please trigger validations for these changes since modal validations are already fixed but validations have not triggered yet

**Comment by adibiton** [comment]
@vigaur - model validation run successfully

**Comment by raych1** [comment]
@adibiton , please fix the avocado CI check failures.

**Comment by adibiton** [comment]
Model validation fails due to a bug (#468)

**Comment by adibiton** [comment]
@MyronFanQiu Can you please merge this PR?

**Review by mmyyrroonn — APPROVED** [review]

**Comment by MyronFanQiu** [comment]
@raych1 Could you confirm the OAV bug? If we cannot pass the CI, we need your help to force merge it. @NullMDR could you check SDK automation? error messages are like 
```
Error: Plugin imodeler1 reported failure.',
```

**Comment by raych1** [comment]
> @raych1 Could you confirm the OAV bug? If we cannot pass the CI, we need your help to force merge it. @NullMDR could you check SDK automation? error messages are like
> 
> ```
> Error: Plugin imodeler1 reported failure.',
> ```

@MyronFanQiu , OAV failure is a known issue. @NullMDR , we can force merge this PR once you sign off SDK automation, thanks.

**Comment by NullMDR** [comment]
@adibiton Seems like you have some swagger issue here. You have several ```x-ms-enum``` with name ```AggregationType``` but with different value list. You can view sdk generation logs in comments above. You can check files in tag ```package-2018-03``` to fix this error.

**Comment by ArcturusZhang** [comment]
Hi @adibiton There are at least two enum definitions with the same name `AggregationType` with different values in tag `package-2018-03`. I have located the following two of them (there may be more based on other language's SDK generation log):
1. https://github.com/Azure/azure-rest-api-specs/blob/cd030278d173aa0c662d69b99400af509938a7ce/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metricDefinitions_API.json#L137
1. https://github.com/Azure/azure-rest-api-specs/blob/cd030278d173aa0c662d69b99400af509938a7ce/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json#L804

**Comment by adibiton** [comment]
@ArcturusZhang @NullMDR is adding the missing value ('none') enough? or should i change the x-ms-enum property "modelAsString" to true in order to align the defs?

**Comment by MyronFanQiu** [comment]
@adibiton Hello. I saw another PR open, what's the status of this PR?

**Comment by adibiton** [comment]
@MyronFanQiu I'm closing this PR since i can't push to this branch - all the changes will be pushed from  https://github.com/Azure/azure-rest-api-specs/pull/7920

**Pull request closed without merging**
