### PR TITLE
DomainServices: Add default value for newly added "SyncScope" property

### PR DESCRIPTION
**Pull request by jihochang**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jihochang** [comment]
The default value was not added at the time we added the new api-versions last month. We are correcting the incorrect swagger.

This is causing the S360 violation for Swagger correctness as well. 

https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=2F2EC6D4-5760-465E-BAFF-3E6DD45DA30F

**Comment by jihochang** [comment]
@msyyc - Please give us an update on how we can proceed with the merge. This is fixing a missing swagger spec new property default value.

**Comment by jihochang** [comment]
@msyyc - We need an update on this. We will escalate to ARM team this week because our S360 violation will go red.

**Comment by msyyc** [comment]
Hi @mikekistler, Could you help review the swagger breaking change ? https://github.com/Azure/azure-rest-api-specs/pull/22476/checks?check_run_id=11144569062. Thanks!

**Comment by mikekistler** [comment]
Approved. -Mike

From: Yuchao Yan ***@***.***>
Date: Thursday, February 9, 2023 at 5:43 PM
To: Azure/azure-rest-api-specs ***@***.***>
Cc: Mike Kistler ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-rest-api-specs] DomainServices: Add default value for newly added "SyncScope" property (PR #22476)

Hi @mikekistler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikekistler&data=05%7C01%7Cmikekistler%40microsoft.com%7C328ec08c50f048cb251008db0b082feb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638115902021590018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dR%2FyEC11nFAMEh%2F2hoCGdAxMuq2hSkqcRKlWAVr7b7k%3D&reserved=0>, Could you help review the swagger breaking change ? https://github.com/Azure/azure-rest-api-specs/pull/22476/checks?check_run_id=11144569062<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F22476%2Fchecks%3Fcheck_run_id%3D11144569062&data=05%7C01%7Cmikekistler%40microsoft.com%7C328ec08c50f048cb251008db0b082feb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638115902021590018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bagDg7T8EWqS%2FHrmgdFBTKJ1UJd2bA3Aps1XunkXp2s%3D&reserved=0>. Thanks!

**Comment by jihochang** [comment]
Thank you Mike for approving the change.

@msyyc - Can you help us merge the change in?

**Review by msyyc — APPROVED** [review]

**Pull request merged**
