### PR TITLE
Fix problematic inheritance structure in security

### LINKED ISSUE #11155: Security setting models have problematic inheritance structure
The settings API returns a model [`Setting`](https://github.com/Azure/azure-rest-api-specs/blob/ffc3a5f4098468a2f476dc6580fba998d817c0dd/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L175), but this model is identical to [`SettingResource`](https://github.com/Azure/azure-rest-api-specs/blob/ffc3a5f4098468a2f476dc6580fba998d817c0dd/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/settings.json#L202) which has a discriminator. 

This extra (and redundant) inheritance structure has nullified the code generator to correctly detect the discriminator within this model and has caused [this issue](https://github.com/Azure/azure-sdk-for-go/issues/12724) in azure-sdk-for-go

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-rest-api-specs/issues/11155 and https://github.com/Azure/azure-sdk-for-go/issues/12724

Brief explanation of the issue:

`Setting` inherit from `SettingResource` and does not introduce any new properties, therefore `Setting` and `SettingResource` are identical. The GET and PATCH API are using `Setting` as their return type.
`SettingResource` has a discriminator, hence `Setting` should also acquire that discriminator.
But the modeler does not detect the discriminator in `Setting` inherited from `SettingResource`. Therefore the generated SDKs (at least for go SDK) do not have the polymorphism in the return value of GET and Update function which is causing problem and cannot be worked around.

In this PR, I just removed the inheritance between `Setting` and `SettingResource`, using `SettingResource` to replace everywhere using `Setting` previously. And since `Setting` is not referenced anywhere after this change, it is removed too. 
Speaking of the result, since `Setting` and `SettingResource` are identical, this should be not changing anything.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by yungezz** [comment]
The change makes sense from SDK level. While add service owner @chlahav  @giromm2ms @liranc to review this again, since not  sure whether it's Setting and SettingResource has hierarchy at service side, and has potential extending plan: properties on Settings not on SettingResource

**Comment by yungezz** [comment]
> The change makes sense from SDK level. While add service owner @chlahav @giromm2ms @liranc to review this again, since not sure whether it's Setting and SettingResource has hierarchy at service side, and has potential extending plan: properties on Settings not on SettingResource

hi @chlahav @giromm2ms @liranc could you pls help to look at the PR from service perspective?

**Review by giromm2ms — APPROVED** [review]
It seems ok.
Please verify that all other checks are not broke.
Do not merge unless it is on steady state

**Comment by giromm2ms** [comment]
@eliagrady , please double-check

**Review by yungezz — APPROVED** [review]

**Comment by eliagrady** [comment]
We're missing tests verifying this change

**Comment by ArcturusZhang** [comment]
Hi @eliagrady could you be more specific?

**Comment by eliagrady** [comment]
> Hi @eliagrady could you be more specific?

I meant an SDK gen with tests working - but this looks ok from IMHO

**Review by eliagrady — APPROVED** [review]
Looks ok - AlertSuppressionSetting is defined and unused, but other than that, it looks fine

**Pull request merged**
