### PR TITLE
[Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-01-01

### PR DESCRIPTION
**Pull request by ampravinr**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/ampravinr/azure-rest-api-specs/dev_UcddDownloads-consumption-Microsoft.Consumption-2019-01-01...master).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5877 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5877/commits/45e46f360dfdf03eb905bba30e2fd2c552b7f697

**Comment by dsgouda** [comment]
startrbuild

**Comment by dsgouda** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5888 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5888/commits/262372c41613e81aa2dcd88a95fb62a396f1a7d3

**Review by veronicagg — CHANGES_REQUESTED** [review]
Please review model validation failures at https://dev.azure.com/azure-sdk/public/_build/results?buildId=20146&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&taskId=43324f1f-6724-5d61-785f-f0ac9fd256a1&lineStart=64&lineEnd=65&colStart=1&colEnd=1

**Comment by veronicagg** [comment]
Still see some failures at https://dev.azure.com/azure-sdk/public/_build/results?buildId=22822. You can check your file using the tool at https://portal.azure-devex-tools.com/app/tools/static-validation/static/errors/default if you'd like.

**Comment by veronicagg** [comment]
@ampravinr thanks for fixing the examples issues. The PR is still pending ARM team's approval, please follow up with them for sign-off. FYI - @RyanBensonMSFT who was reviewing your other PR.

**Comment by ampravinr** [comment]
@veronicagg - as per our talk with Arm folks. This is not something we can do for a GA version. We are planning seperate changes for GA version. So I am abandoning these changes for now.

**Comment by ampravinr** [comment]
Hi Veronica,

Thanks a lot with all the help on this.

We had a discussion with Arm folks on this and unfortunately this change is not something we can do on a GA version. So I will be abandoning these changes on this version - stable/2019-01-01.

Note: I closed the PR from my side hoping that will abandon all the merge and the PR. Please let me know if that is not the case.

Thanks,
Praveen Radhakrishnan

**Pull request closed without merging**
