### PR TITLE
[Network] Exposing http2 flag on Application Gateway

### PR DESCRIPTION
**Pull request by akshaysngupta**
### Description
This PR exposes the http2 flag on appgw.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@akshaysngupta have you ship the any SDK for this API version?

**Comment by akshaysngupta** [comment]
@sergey-shandar We didn't ship any change in SDK in September.
Also, I asked Deepak said that I should move to the next version, October. I have updated the PR for the version update.

**Comment by sergey-shandar** [comment]
@akshaysngupta it looks like there is a merge problem. 147 files changed.

**Comment by sergey-shandar** [comment]
@akshaysngupta ok, now I understand, it's completely new API version. In this case, I think, this PR should be reviewed only after https://github.com/Azure/azure-rest-api-specs/pull/1726.

**Comment by sergey-shandar** [comment]
@akshaysngupta @DeepakRajendranMsft Because it's a new API version and it may have more changes to it before it's shipped, I would propose the next workflow:
1. make a branch `Networking-V2017-10-01`
1. enable CI on the branch
1. make PRs against this branch
1. merge to the `current` branch when it's ready.

**Comment by sergey-shandar** [comment]
@akshaysngupta @DeepakRajendranMsft I'm closing this PR, please open a new one against https://github.com/Azure/azure-rest-api-specs/tree/Network-2017-10-01

**Pull request closed without merging**
