### PR TITLE
Publishing latest changes in KV protocol

### PR DESCRIPTION
**Pull request by dragav**
This swagger update contains several updates in the KV service protocol V20161001:
- adding support for recoverable deletion ("soft-delete") of KeyVault entities (vaults and in-vault objects)
- adding support for backing up/restoring KeyVault secrets
- exposing support for additional JWK signature algorithms

### CODE REVIEW

**Review by fearthecowboy — CHANGES_REQUESTED** [review]
I didn't see much off the top of my head; I'm in the middle of resetting my desktop--I was going to run it thru the command-line once more to see if there's anything else I thought needed addressing.  I should have any other comments by tomorrow morning.

**Comment by dragav** [comment]
I agree on the redundancy of 'summary' and 'description'; in some cases, it's downright painful to come up with a description that is comprehensively more detailed than the summary. However, some of these changes are passed on to me via our docs team, and my understanding is that both fields are needed for a proper documentation to be generated.

Thanks for reviewing.

**Comment by fearthecowboy** [comment]
@dragav -- Hmm. I was under the impression that `description` is "really required" and `summary` is "kinda required". I'll chat with Brady when I see him next.

**Review by fearthecowboy — APPROVED** [review]

**Comment by dragav** [comment]
Would it be possible to let this through? I'm sure we can address any minor comment- or documentation-related issue in a subsequent revision. Thanks.

**Pull request merged**
