### PR TITLE
Fix rp cop

### PR DESCRIPTION
**Pull request by wenjlu-lgy**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by wenjlu-lgy** [comment]
@bganapa Could you please check this?

**Comment by bganapa** [comment]
@fengzhou-msft The API surface is specific to Azure stack Admin endpoint .These are not exposed in Azure at all. These APIs does not go thru ARM API Review. I removed the WaitForArmFeedback tag.
Could you please help us show how we can fix the validation errors?

**Comment by fengzhou-msft** [comment]
@bganapa Please check error details on ADO [log](https://dev.azure.com/azure-sdk/public/_build/results?buildId=219582&view=logs&jobId=eca5a1cb-f12a-57d8-9254-390bd587c201&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a) and you should be able to see which line has what issue.

**Comment by bganapa** [comment]
@wenjlu-lgy to look in to the errors

**Comment by bganapa** [comment]
@wenjlu-lgy Could you please look in to this?

**Comment by bganapa** [comment]
@fengzhou-msft  This should be good to merge now. Thanks!

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
