### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerInstance to add version stable/2021-03-01

### PR DESCRIPTION
**Pull request by novinc**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/novinc/azure-rest-api-specs/dev-containerinstance-Microsoft.ContainerInstance-2021-03-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by novinc** [comment]
Justification for breaking change:
The property type was set incorrectly. Anyone attempting to use it would run into an error. This simply fixes it.

**Comment by PhoenixHe-msft** [comment]
@novinc Please submit for breaking change review and bring your justification there, then I could merge this PR after you got approval.

**Comment by novinc** [comment]
> @novinc Please submit for breaking change review and bring your justification there, then I could merge this PR after you got approval.

Thanks, I have sent the instructions to our PM. Although I understand the need for this review process it seems a bit excessive for this case as the current swagger is broken and anyone attempting to use the broken parts of the model would run into errors from our control plane. Given this fact, it's fair to say the customer impact of this "breaking" change is close to zero.

**Comment by PhoenixHe-msft** [comment]
@novinc We need a formal process in swagger review to make sure the merged breaking change do really has near to zero impact to customer, or we need to kick off another process for breaking change update. We appreciate your understanding.

**Comment by chiragg4u** [comment]
ARM API review is not required for this PR, please follow the process given @ https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review

**Comment by PhoenixHe-msft** [comment]
@novinc Please reopen and submit breaking change review if you want to merge this PR.

**Pull request closed without merging**
