### PR TITLE
Merge Network-2018-05-01 to master

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
Merged updates from Network May branch to master

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
Hi @dsgouda could you please approve merging to the master branch?

**Review by dsgouda — APPROVED** [review]
LGTM, waiting for a couple of CI builds to pass before merging.

**Comment by MikhailTryakhov** [comment]
@dsgouda passed!

**Comment by dsgouda** [comment]
@sarangan12 the ruby builds seem to be failing PTAL, won't bock on this PR though

**Pull request merged**
