### PR TITLE
Add 2020-04-01 API specification for Microsoft.Peering

### PR DESCRIPTION
**Pull request by psanapathi**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by psanapathi** [comment]
Spec diff: https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYXN0ZXIvc3BlY2lmaWNhdGlvbi9wZWVyaW5nL3Jlc291cmNlLW1hbmFnZXIvTWljcm9zb2Z0LlBlZXJpbmcvcHJldmlldy8yMDIwLTAxLTAxLXByZXZpZXcvcGVlcmluZy5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL3BzYW5hcGF0aGkvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYXN0ZXIvc3BlY2lmaWNhdGlvbi9wZWVyaW5nL3Jlc291cmNlLW1hbmFnZXIvTWljcm9zb2Z0LlBlZXJpbmcvc3RhYmxlLzIwMjAtMDQtMDEvcGVlcmluZy5qc29uIn0=

**Comment by erich-wang** [comment]
@psanapathi , please fix the **Avocado** error in CI per https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md

**Comment by psanapathi** [comment]
> @psanapathi , please fix the **Avocado** error in CI per https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md

Fixed

**Comment by rileymckenna** [comment]
az run

**Comment by rileymckenna** [comment]
azrun

**Comment by rileymckenna** [comment]
@openapibot sdkautomation rebuild

**Review by majastrz — APPROVED** [review]
Manually did the diff between 2020-01-preview and this version. Looks good to me. Signed off from ARM.

**Comment by psanapathi** [comment]
@erich-wang ARM has signed off. Please let me know if anything else needs to be done.

**Pull request merged**
