### PR TITLE
Fixing 'CreateOption' in 2016-04-30-preview Compute swagger to Pascal casing

### PR DESCRIPTION
**Pull request by waynekuo**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@waynekuo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (wkuo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by olydis** [comment]
Could you please address the messages you can find [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/202400321) - where possible (see the `WARNING`s). Those parameters should really get descriptions at least ;-)

**Comment by olydis** [comment]
Please fix the paths
 - `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets/{name}` and `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets/{availabilitySetName}`
- `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{name}` and `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}`

...by merging them. This is illegal Swagger otherwise.

**Comment by waynekuo** [comment]
Thanks for looking at this, @olydis . I don't think I can address those warnings. Firstly, they're unrelated to my change, and secondly, after consulting with @huangpf, if we fix the duplicate path issue, it will cause breaking changes in CLI generation.

**Comment by huangpf** [comment]
Not just CLI; anything that depends on the name in the spec, will take it as a breaking change.

**Comment by olydis** [comment]
Whether they are related to your change or not make no difference - if you provide **descriptions** for parameters (I get that you probably can't address the other warnings) it just makes **all** derived products better.

Regarding the renaming: Of course I don't expect you to break anything because of this, but that's where `x-ms-client-name` comes in. Add `"x-ms-client-name": "<current name>"` to the affected parameters and the merge will have no observable effects.

**Comment by amarzavery** [comment]
@huangpf 
How will it cause breaking changes in anything? The method signature (return type and the type of the parameters accepted by the method) does not change.
Even the sequence of parameters for every operation remains the same. Since when the _"name of the parameter"_ is considered a breaking change?

All we are asking is: to remove duplicate paths as that is a semantically incorrect swagger.

**Comment by amarzavery** [comment]
It should be a simple fix for the xplat cli code gen tool. I dont see it to be breaking in any way.

And if indeed the change in the name of the parameter is significant then please use the x-ms-client-name extension.

**Comment by huangpf** [comment]
Changes on named parameters are indeed breaking changes, therefore, in our perspective, the proper way is to handle it in a new task.

**Comment by olydis** [comment]
@huangpf any chance you can implement the changes requested? I want to restate again that there are even *descriptions* missing which is not acceptable.

**Review by olydis — CHANGES_REQUESTED** [review]
give descriptions, deduplicate Swagger paths

**Comment by huangpf** [comment]
@olydis Do you mean the description for these enums, or something else? I think there is a simple description field ```"description": "The create option."```.

Our position is that the check-in validation was not there before, so it's a new task to us. @waynekuo's task is to fix the enum strings, and he's not the owner to fix other issues.

Is it feasible to take this change, and we track the overall fix in another item?

**Comment by olydis** [comment]
No, as mentioned and linked to in my initial comment, there are parameter descriptions missing. This is the list:

	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/{version}/get/Parameters[1]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/{version}/get/Parameters[2]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/{version}/get/Parameters[3]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/{version}/get/Parameters[4]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/get/Parameters[1]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/get/Parameters[2]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/get/Parameters[1]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/get/Parameters[2]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/get/Parameters[3]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/get/Parameters[5]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmextension/types/{type}/versions/get/Parameters[6]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions/get/Parameters[6]
	Path: #/Paths/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions/get/Parameters[7]

**Comment by olydis** [comment]
This is a very basic and fundamental quality issue and should really be addressed with this very PR.

**Comment by salameer** [comment]
@huangpf and  @waynekuo

Can you please act on this, we will have to close this PR if it is still inactive by the end of week.

Apologies for the push but we're trying to bring  down the opened idle PRs across the whole repo

**Pull request closed without merging**
