### PR TITLE
[AgriFood] Adding Nov 2022 API version

### LINKED ISSUE #20886: [AgriFood Platform] API Review
New API Review meeting has been requested.

**Service Name**: Azure AgriFood Platform
**Review Created By**: Bhargav Kansagara
**Review Date**: 10/5/2022 9:30 PM PT
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/21001
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: Booking slot for review of Nov API version
## Added Fields
- Crop Entity – breedingMethods(string), Measurements(Dictionary(string: measure)) 
- Season Entity – geographicIdentifier(string) 
- CropVariety Entity – trait(string), relativeMeasurements(Measure), treatments(Array(strings)) 
- Boundary Entity – type(string), crs(string), centroid(GeoJson), bbox(GeoJson)
- Source(string) field in Farmer/Farm/Field/Seasonal Field/Boundary/Crop/Crop variety/Season/Attachment
- CreatedBy(string) and ModifiedBy(string) in all entities

## Removed Fields -  
- primaryBoundaryId in fields and seasonal fields 
- isPrimary flag in boundary  

## Changes in Controller - 
- Migrate from Farmer to Party in all controllers 
- Change CropVariety to CropProduct 

## Changes pending from last review
- $maxPageSize to maxPageSize and $skipToken to skipToken
- value is now required in pageable response
- Adding default response for ImageProcessing_GetRasterizeJob
- camelCase parameters for Attachments_CreateOrUpdate  and InsightAttachments_CreateOrUpdate
- Removing default from provider
- Fixing datetime examples
- Removing `additionalProperties: {}`
- Marking code and message as required in Error schema
- Patch operations should consume 'application/merge-patch+json' content type (pending)
- All 202 responses should include an “Operation-Location” response header (pending)

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=4ba062fe-503e-ed11-9db0-0022480b4cff)

### PR DESCRIPTION
**Pull request by bhargav-kansagara**
# Data Plane API - Pull Request
## Added Fields
- Crop Entity – breedingMethods(string), Measurements(Dictionary(string: measure)) 
- Season Entity – geographicIdentifier(string) 
- CropVariety Entity – trait(string), relativeMeasurements(Measure), treatments(Array(strings)) 
- Boundary Entity – type(string), crs(string), centroid(GeoJson), bbox(GeoJson)
- Source(string) field in Farmer/Farm/Field/Seasonal Field/Boundary/Crop/Crop variety/Season/Attachment
- CreatedBy(string) and ModifiedBy(string) in all entities
- measure renamed to measurements in prescription & crop
- acreage renamed to area in boundary

## Removed Fields -  
- primaryBoundaryId in fields and seasonal fields 
- isPrimary flag in boundary
- boundaryIds list in field & seasonal field
- avgYields etc from seasonal field

## Changes in Controller - 
- Migrate from Farmer to Party in all controllers 
- Change CropVariety to CropProduct 

## Changes pending from last review
- $maxPageSize to maxPageSize and $skipToken to skipToken
- value is now required in pageable response
- Adding default response for ImageProcessing_GetRasterizeJob
- camelCase parameters for Attachments_CreateOrUpdate  and InsightAttachments_CreateOrUpdate (currently case insensitive)
- Removing default from provider from scenes get & put APIs
- Fixing datetime examples
- Removing `additionalProperties: {}`
- Marking code and message as required in Error schema
- Patch operations should consume 'application/merge-patch+json' content type (pending) (start a thread)
- All 202 responses should include an “Operation-Location” response header (pending) (change it once supported by the clients)

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue: https://github.com/Azure/azure-rest-api-specs/issues/20886

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2021-07-31-preview/agfood.json
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by mikekistler — CHANGES_REQUESTED** [review]
The validators are currently failing because you have not created the "examples" directory and populated with the examples referenced in the REST API def.  Please fix.

**Comment by mikekistler** [comment]
The Spectral linter is reporting many issues with your REST API definition. Please run the Spectral linter as described in the [CONTRIBUTING.md](https://github.com/Azure/azure-rest-api-specs/blob/main/CONTRIBUTING.md#coding-style) file and address these issues where appropriate.

Spectral may issue messages for cases that warrant inspection but not necessarily changes, so use your judgement in addressing the Spectral output.

**Comment by weidongxu-microsoft** [comment]
1.	Response body has “status” and one of its possible value is “Failed”. If it is “Failed”, is it still a 200 status code (which is unusual), or 400 status code (which does not use this body model)?
2.	“startTimeHours”, “endTimeHours” and “duration” seems for specific provider. What’s the plan if there is more providers in future and they requires different style of time range inputs?
3.	If backend has “x-ms-response-latency” for customer, it should be defined in Swagger (I am not sure that I understand the meaning of “for tracking purpose”, tracking for us or for customer?).
4.	Name of model "WeatherDataForPassthrough" sounds strange. Why not just “WeatherData”?
5.	Lots of “string” properties seems better be extensible enum, including “dayOfWeek”, “dayOrNight” in response, and “units” in request. (I am not sure if it follows certain standards, e.g. feel unfamiliar with “units” be “e”/”m”/”h”/”s”; and I think review from Mark already mention about “dayOfWeek”)

Possible error:

This should not be an array of “Locations”. I assume it should be just “Locations”.
```json
        "locations": {
          "description": "List of locations along with corresponding weather data.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Locations"
          }
        },
```

**Comment by mikekistler** [comment]
A couple more comments:
- All 202 responses should include an “Operation-Location” response header.
- LRO put should return 201 not 202.
- maxpagesize parameter must be named "maxpagesize" (all lowercase). Also recommend removing the default and max values so that your service can determine a proper value dynamically. Why force a minimum of 10? Suppose the user really only wants the first element?
- Don't specify minLength or maxLength on "readOnly" properties. (createdBy, modifiedBy in ApplicationData)
- "Attachments_CreateOrUpdate" takes a form parameter "eTag" with description "The ETag value to implement optimistic concurrency.".  But eTags should not be set by the client - they are computed by the service.

**Comment by bhargav-kansagara** [comment]
Hi Mike, can we make those changes in the next API version?

**Comment by mikekistler** [comment]
I think you can defer these changes to the next API version _if_ you are planning another preview version.  If this is your final preview before GA then I think you should make the changes in this version.

**Comment by bhargav-kansagara** [comment]
No, we will have at least one more preview version

**Review by mikekistler — APPROVED** [review]
This looks good for preview but will need changes and new review before GA.

**Comment by mikekistler** [comment]
Breaking change is approved because the prior API version was not yet in public preview.

**Comment by mikekistler** [comment]
@weidongxu-microsoft The service team has made some fixes but would like approval to move forward with the understanding that they will address the remaining concerns in their next preview version. If this is acceptable, could you please approve the PR so that we can merge?

**Comment by weidongxu-microsoft** [comment]
Only review for diff from 2021-07-31-preview (and issue description)

nit
- inconsistent on "area" / "acreage" https://github.com/Azure/azure-rest-api-specs/blob/d9240a766d0e4bd9d245f3030a85af3f782c66d9/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2022-11-01-preview/agfood.json#L1334-L1347 (several instances)

my previous comment still holds, but as this is preview, you can try and break if necessary.
- “startTimeHours”, “endTimeHours” and “duration” seems for specific provider. What’s the plan if there is more providers in future and they requires different style of time range inputs?

---

Curious on operationId "Farms_CreateCascadeDeleteJob". This seems to be a PUT to delete or start delete some resources? (this pattern is on existing APIs)

**Review by weidongxu-microsoft — APPROVED** [review]
Approved.

Let Travis or me know when plan to merge.

**Comment by bhargav-kansagara** [comment]
@weidongxu-microsoft yes, we want to merge this right away.

I have noted your comments and we will take care of them in the next preview version.

**Comment by bhargav-kansagara** [comment]
Thanks a lot @weidongxu-microsoft!!

**Pull request merged**
