### PR TITLE
[Portal Generated] Review request for Microsoft.ADHybridHealthService to add version 2014-01-01

### PR DESCRIPTION
**Pull request by binilkk**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/binilkk/azure-rest-api-specs/dev-adhybridhealthservice-Microsoft.ADHybridHealthService-2014-01-01-binilkk).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by praries880** [comment]
@azuresdkci test this please

**Comment by praries880** [comment]
ill close and re-open the PR for it to pick up changes in : https://github.com/Azure/azure-rest-api-specs/pull/4893

**Comment by praries880** [comment]
@binilkk can you sync your branch with upstream master to pull in the fix for https://github.com/Azure/azure-rest-api-specs/pull/4893? this will fix the java build error

**Comment by binilkk** [comment]
Sure.

**Review by praries880 — APPROVED** [review]

**Pull request merged**
