### PR TITLE
[Hub Generated] Review request for Microsoft.CostManagement to add version preview/2022-10-01-preview

### PR DESCRIPTION
**Pull request by thramu**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/thramu/azure-rest-api-specs/dev-cost-management-Microsoft.CostManagement-2022-10-01-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by rkmanda** [comment]
>     "/{scope}/providers/Microsoft.CostManagement/settings": {

What are the different scopes at which you intend to expose this?

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1291 in c80b1cc. [](commit_id = c80b1cc522f20681a8ac100352e29a6fc0a9b162, deletion_comment = False)

**Comment by rkmanda** [comment]
>     "/{scope}/providers/Microsoft.CostManagement/settings": {

Its better to make the scopes explicitly defined if you know what they are. The only case where a generic "{scope}" makes sense is when defining an extension resource which could extend any other resource path. Is that the case here?

---
In reply to: [1244883323](https://github.com/Azure/azure-rest-api-specs/pull/20685#issuecomment-1244883323) [](http://example.com/codeflow?ancestors=1244883323)

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1291 in b98fc23. [](commit_id = b98fc23fa5c15c55a9a33027ec61f32b63724d36, deletion_comment = False)

**Comment by thramu** [comment]
> > ```
> > "/{scope}/providers/Microsoft.CostManagement/settings": {
> > ```
> 
> What are the different scopes at which you intend to expose this?
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1291 in [c80b1cc](https://github.com/Azure/azure-rest-api-specs/commit/c80b1cc522f20681a8ac100352e29a6fc0a9b162). [](commit_id = [c80b1cc](https://github.com/Azure/azure-rest-api-specs/commit/c80b1cc522f20681a8ac100352e29a6fc0a9b162), deletion_comment = False)

@rkmanda : We have added the allowed scopes in the description. The allowed scopes are:
Subscription/{subscriptionId}
BillingAccounts/{BillingAccountId}
BillingAccounts/{BillingAccountId}/BillingProfiles/{BillingProfileId}

**Comment by rkmanda** [comment]
>           "201": {

how about 200 for updated?

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1363 in 679abc3. [](commit_id = 679abc3c4d5c9ddb712010e1504808f126212af2, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "x-ms-client-flatten": true,

do not flatten the properties as flattening at this level will violate the envelope definition for proxy resources

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2901 in 679abc3. [](commit_id = 679abc3c4d5c9ddb712010e1504808f126212af2, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "preferContainerTags": {

consider making it an enum instead of bool

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2928 in 679abc3. [](commit_id = 679abc3c4d5c9ddb712010e1504808f126212af2, deletion_comment = False)

**Comment by thramu** [comment]
> > ```
> >       "x-ms-client-flatten": true,
> > ```
> 
> do not flatten the properties as flattening at this level will violate the envelope definition for proxy resources
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2901 in [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2). [](commit_id = [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2), deletion_comment = False)

Updated:
[[Hub Generated] Review request for Microsoft.CostManagement to add version preview/2022-10-01-preview by thramu · Pull Request #20685 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/20685/commits/eac81a700f50e792540a73f8a33269583aefe49f)

**Comment by thramu** [comment]
> > ```
> >       "201": {
> > ```
> 
> how about 200 for updated?
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1363 in [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2). [](commit_id = [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2), deletion_comment = False)

Updated: [[Hub Generated] Review request for Microsoft.CostManagement to add version preview/2022-10-01-preview by thramu · Pull Request ](https://github.com/Azure/azure-rest-api-specs/pull/20685/commits/c73d532097bd458d79a34d2255590ed6499a1b11)[#20685 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/20685/commits/c73d532097bd458d79a34d2255590ed6499a1b11)

**Comment by thramu** [comment]
> > ```
> >     "preferContainerTags": {
> > ```
> 
> consider making it an enum instead of bool
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2928 in [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2). [](commit_id = [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2), deletion_comment = False)

Will discuss the same with PM and consider this feedback in the upcoming version.

**Comment by rkmanda** [comment]
>           "$ref": "#/definitions/TagInheritanceProperties",

model this using the discriminator pattern to allow other types to be returned in future

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2902 in 679abc3. [](commit_id = 679abc3c4d5c9ddb712010e1504808f126212af2, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "$ref": "#/definitions/TagInheritanceProperties",

[https://azure.github.io/autorest/extensions/#x-ms-discriminator-value](https://azure.github.io/autorest/extensions/#x-ms-discriminator-value)

---
In reply to: [1244907011](https://github.com/Azure/azure-rest-api-specs/pull/20685#issuecomment-1244907011) [](http://example.com/codeflow?ancestors=1244907011)

---
Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2902 in b98fc23. [](commit_id = b98fc23fa5c15c55a9a33027ec61f32b63724d36, deletion_comment = False)

**Comment by thramu** [comment]
> > ```
> >       "$ref": "#/definitions/TagInheritanceProperties",
> > ```
> 
> https://azure.github.io/autorest/extensions/#x-ms-discriminator-value
> 
> In reply to: [1244907011](https://github.com/Azure/azure-rest-api-specs/pull/20685#issuecomment-1244907011)
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2902 in [b98fc23](https://github.com/Azure/azure-rest-api-specs/commit/b98fc23fa5c15c55a9a33027ec61f32b63724d36). [](commit_id = [b98fc23](https://github.com/Azure/azure-rest-api-specs/commit/b98fc23fa5c15c55a9a33027ec61f32b63724d36), deletion_comment = False)

Updated: https://github.com/Azure/azure-rest-api-specs/pull/20685/commits/bc7ddb5514c1639135e58f2b5dba1a61aec86eca

**Comment by arusing** [comment]
> > ```
> >     "preferContainerTags": {
> > ```
> 
> consider making it an enum instead of bool
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:2928 in [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2). [](commit_id = [679abc3](https://github.com/Azure/azure-rest-api-specs/commit/679abc3c4d5c9ddb712010e1504808f126212af2), deletion_comment = False)

There are only two possible values for this field, hence it was proposed as a boolean.

I will share the use case.
The usage information at cost management is grained at resource level. Cost-analysis for these resources can be pivoted around the tags associated with those resources. Billing admins cannot really tag all the resources 'individually' with tags, so they prefer to tag the subscription (container) and expect that all the resources under it are tagged automatically. Cost-management is doing that work for them. Now a situation arises when same tag-names with different values are defined at the subscription(container) as well as at the resource level. We have to pick just one of them, and hence we ask Billing Admins to state their preference: prefer container tag (subscription) or not(resource).
There would never be a third value.

**Comment by arusing** [comment]
> > ```
> > "/{scope}/providers/Microsoft.CostManagement/settings": {
> > ```
> 
> Its better to make the scopes explicitly defined if you know what they are. The only case where a generic "{scope}" makes sense is when defining an extension resource which could extend any other resource path. Is that the case here?
> 
> In reply to: [1244883323](https://github.com/Azure/azure-rest-api-specs/pull/20685#issuecomment-1244883323)
> 
> Refers to: specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-10-01-preview/costmanagement.json:1291 in [b98fc23](https://github.com/Azure/azure-rest-api-specs/commit/b98fc23fa5c15c55a9a33027ec61f32b63724d36). [](commit_id = [b98fc23](https://github.com/Azure/azure-rest-api-specs/commit/b98fc23fa5c15c55a9a33027ec61f32b63724d36), deletion_comment = False)

Spot on with assumption.
Yes, this is an extension resource. 
Currently behind Microsoft.Billing RP. But soon would be found behind other RPs as well. [Support for ManagementGroup RP is being costed]

**Comment by rkmanda** [comment]
fair enough

---
In reply to: [1244959382](https://github.com/Azure/azure-rest-api-specs/pull/20685#issuecomment-1244959382) [](http://example.com/codeflow?ancestors=1244959382,1244959382)

**Review by arusing — APPROVED** [review]

**Review by jordan13game — APPROVED** [review]

**Pull request merged**
