### PR TITLE
[HDInsight] Added support for ADLS type Gen 2

### PR DESCRIPTION
**Pull request by wawon-msft**
We allow users to specify a file system during cluster creation for ADLS Gen 2 storage accounts. We do not expect this to be a breaking change, as this is an additional optional property that is not mutable after the initial PUT.

---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
Thanks @wawon-msft!
The change looks good - but this spec has a large number of linter errors:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/401955763

Is there a plan to resolve or seek suppression for these errors?

**Review by annatisch — APPROVED** [review]

**Comment by wawon-msft** [comment]
@annatisch These should have been resolved in the new API version.

**Comment by annatisch** [comment]
Thanks @wawon-msft - which new API version?
The errors seem to be occurring in both `2015-03-01-preview` and `2018-06-01-preview`.

**Comment by wawon-msft** [comment]
2018-06-01-preview is the new API version, which should have no errors. I couldn't find any linter errors for 2018-06-01-preview in the job that you linked, only warnings. Could you paste the errors that you're see?
Thanks.

**Comment by annatisch** [comment]
Thanks @wawon-msft - my apologies you're quite right - I missed the distinction. 
I will merge.

Though it would be good if you chatted to @ravbhatnagar about getting suppression approved for the errors in the old API given that they have already been fixed in the new API - as this will help to clean up the CI  :-)

**Comment by wawon-msft** [comment]
@annatisch That sounds good. I'll follow up with him.

**Pull request merged**
