### PR TITLE
Adding compute 2021-04-01 version

### PR DESCRIPTION
**Pull request by grizzlytheodore**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [x] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
@pilor i had to close this PR: https://github.com/Azure/azure-rest-api-specs/pull/14939 but ARM approval there. 

Needed to added one more feature (Capacity Reservation for Vm/Vmss.  Non-breaking change) to this one.

**Comment by grizzlytheodore** [comment]
'PublicIPAddressSku' related breaking changes were added to the 2021-03-01 version and approved by Jeffrey Richter. Shown here: #14782

**Comment by grizzlytheodore** [comment]
the only breaking change this PR as a whole adds is 'PublicIPAddressSku' related breaking change which was first added to the 2021-03-01 version and approved by Jeffrey Richter. Shown here: #14782

other changes in this PR are adding new API endpoints, adding new properties, and some descriptions being changed which are not considered breaking change for new API version.

**Comment by pilor** [comment]
What was the source PR for the additional change?  Or has it not had its own review already?

**Comment by grizzlytheodore** [comment]
@pilor these two PR's are added to this one 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



https://github.com/Azure/azure-rest-api-specs/pull/15058
--
https://github.com/Azure/azure-rest-api-specs/pull/15070



</div>


</body>

</html>

**Comment by pilor** [comment]
> @pilor these two PR's are added to this one
> 
> ## #15058
> #15070

Those did not go through API review.  @jorgecotillo is the reviewer this week and can review the deltas that are coming from those new changes

**Comment by grizzlytheodore** [comment]
@jorgecotillo  please review!

**Comment by jorgecotillo** [comment]
>         "sku"

just making sure that sku is the only required property, can you please confirm?


---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:9180 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>     "version": "2021-04-01"

Just want to confirm that your base api-version is 2021-03-01, is it correct?

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:6 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by grizzlytheodore** [comment]
> > ```
> >     "sku"
> > ```
> 
> just making sure that sku is the only required property, can you please confirm?
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:9180 in [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9). [](commit_id = [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9), deletion_comment = False)

@jorgecotillo  confirmed

**Comment by grizzlytheodore** [comment]
> > ```
> > "version": "2021-04-01"
> > ```
> 
> Just want to confirm that your base api-version is 2021-03-01, is it correct?
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:6 in [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9). [](commit_id = [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9), deletion_comment = False)

we took the 2021-03-01 compute.json and added new features that are added for 2021-04-01. Is that what you mean what base api-version?

**Comment by jorgecotillo** [comment]
>       "put": {

just making sure this is not an async operation right? otherwise please mark it with: x-ms-long-running-operation

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4076 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>       "patch": {

Please make sure to follow our async patch spec: [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#updating-using-patch](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#updating-using-patch) you have to return a 202 Accepted first

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4484 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by hari-bodicherla** [comment]
>         "sku"

yes @jorgecotillo . The sku is a required property. other properties are optional

---
In reply to: [876731943](https://github.com/Azure/azure-rest-api-specs/pull/15100#issuecomment-876731943) [](http://example.com/codeflow?ancestors=876731943,876731943)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:9180 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by hari-bodicherla** [comment]
>       "patch": {

I am not seeing any resource api following the pattern where we are returning 202 for patch requets. is this rule newly added @jorgecotillo .  we always return as 200 status as OK for update and patch operations. 
Sample reference is 

 "patch": {
        "tags": [
          "VirtualMachineScaleSetExtensions"
          
 "patch": {
        "tags": [
          "AvailabilitySets"
          
  ProximityPlacementGroups

---
In reply to: [878422055](https://github.com/Azure/azure-rest-api-specs/pull/15100#issuecomment-878422055) [](http://example.com/codeflow?ancestors=878422055,878422055)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4484 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by hari-bodicherla** [comment]
>       "put": {

This is not an async operation since this is created and updated internall with in CRP operation layer itself.

---
In reply to: [878417500](https://github.com/Azure/azure-rest-api-specs/pull/15100#issuecomment-878417500) [](http://example.com/codeflow?ancestors=878417500,878417500)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4076 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>       "patch": {

Those APIs might not be following the latest RPC doc I pasted here, it's been there for a couple of years now.

---
In reply to: [878513192](https://github.com/Azure/azure-rest-api-specs/pull/15100#issuecomment-878513192) [](http://example.com/codeflow?ancestors=878513192,878422055)

---
Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4484 in 7bd871c. [](commit_id = 7bd871c7fd8f7a0930ad7035115b629b0ac722a9, deletion_comment = False)

**Comment by grizzlytheodore** [comment]
> > ```
> >   "patch": {
> > ```
> 
> Those APIs might not be following the latest RPC doc I pasted here, it's been there for a couple of years now.
> 
> In reply to: [878513192](https://github.com/Azure/azure-rest-api-specs/pull/15100#issuecomment-878513192)
> 
> Refers to: specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json:4484 in [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9). [](commit_id = [7bd871c](https://github.com/Azure/azure-rest-api-specs/commit/7bd871c7fd8f7a0930ad7035115b629b0ac722a9), deletion_comment = False)

202 response has been added. 
let us know if anything else needs to be updated. Otherwise, please approve!

**Comment by jorgecotillo** [comment]
Signed off from ARM side

**Comment by grizzlytheodore** [comment]
@ArcturusZhang ready to be merged !

**Comment by grizzlytheodore** [comment]
@ArcturusZhang  there's two breaking changes in this PR: 
"PublicIPAddressSku" related breaking change was approved and merged to 2021-03-01 here: #14782
"RestorePoint" related breaking change was approve and merged to 2021-03-01 here: https://github.com/Azure/azure-rest-api-specs/pull/14638

Other Cross-Version Breaking changes flagged are from comparing to 2016 version

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
