### PR TITLE
[Hub Generated] Publish private branch 'dev-maintenance-Microsoft.Maintenance-2023-04-01'

### PR DESCRIPTION
**Pull request by KalpeshChavan12**
Reverts Azure/azure-rest-api-specs#23923

Original PR  merged accidently. Please copy all lables from below PR
https://github.com/Azure/azure-rest-api-specs/pull/23832

### CODE REVIEW

**Comment by Wzb123456789** [comment]
@KalpeshChavan12 Marked `DoNotMerge` label, does this PR need to merge?

**Comment by KalpeshChavan12** [comment]
> @KalpeshChavan12 Marked `DoNotMerge` label, does this PR need to merge?

Can you please merge PR

**Comment by KalpeshChavan12** [comment]
@rkmanda

Can you please merge PR

**Comment by KalpeshChavan12** [comment]
> @KalpeshChavan12 Marked `DoNotMerge` label, does this PR need to merge?

Yes, please merge PR

**Comment by KalpeshChavan12** [comment]
@Wzb123456789, @ArcturusZhang 

Can you merge PR

**Comment by rkmanda** [comment]
Please get the suppressions reviewed by the current ARM API reviewer on-call

**Comment by KalpeshChavan12** [comment]
> Please get the suppressions reviewed by the current ARM API reviewer on-call

@rkmanda 

Original PR has signoff: https://github.com/Azure/azure-rest-api-specs/pull/23832

it was reverted because we want to get it merge end of june https://github.com/Azure/azure-rest-api-specs/pull/23923
Now we want to get merge it can you please check old PR.

**Comment by KalpeshChavan12** [comment]
| Linter Rule | Details |
| -- | -- |
| **PathForPutOperation**  :  False +ve, Applicable for tracked resource only configurationassignments is proxy resource | Subscription or resource group is passed in request body.``` MRP allow put/get/delete operation for following resource, microsoft.maintenance/configurationassignment is proxy resource and it can be at any level. MRP are allowing customer to control maintenance for all(vms) resources under subscription/resourcegroup. e.g. `/subscriptions/42c974dd-2c03-4f1b-96ad-b07f050aaa74/resourcegroups/testgroup/providers/microsoft.maintenance/configurationassignments/testdyngroup1` , `/subscriptions/42c974dd-2c03-4f1b-96ad-b07f050aaa74/ /providers/microsoft.maintenance/configurationassignments/testdygroup1`|
| **DeleteResponseBodyEmpty** | Suppression warning to avoid breaking changes. Action Item: MRP Need to fix schema changes for existing resource type |
| **PathContainsResourceType** : Action Item : ARM need to review guideline | Suppression warning to avoid breaking changes. We change path it will introduce breaking changes in CLI/Powershell/.Net SDK e.g. Current PATH in swagger `/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/{applyUpdateName}`, Expected path (e.g. for Microsoft.compute/virtualmachine type) `/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.compute/virtualmachine/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/{applyUpdateName}` | 
| **TrackedResourcePatchOperation**: False +ve |Suppression warning to avoid breaking changes. What cause linter error `"patch": {"tags": [ "MaintenanceConfigurations" ], "summary": "Patch configuration record", { "name": "configuration", "in": "body", "description": "The configuration", "required": true, "schema": { "$ref": "#/definitions/MaintenanceConfiguration" } }`. Same schema used for put and patch operation. *Why Supressed* : No changes in existing schema, schema changes will introduced braking changes. |
| **SubscriptionsAndResourceGroupCasing** |	Suppression warning to avoid breaking changes |
| **PathResourceProviderNamePascalCase** | Suppression warning to avoid breaking changes |
| **RequestSchemaForTrackedResourcesMustHaveTags**: False +ve | ConfigurationAssignments is proxy resource at subscription/resourceGroup level.
| **ResourceNameRestriction** |	Maintenance RP accept any string, no special restriction required.|
| **PutResponseSchemaDescription** | No documentation changes.
| **DeleteOperationAsyncResponseValidation** | MRP Not support Async opearation
| **PutResponseSchemaDescription** | No documentation changes. Action Item: Create follow up PR to update doc |
|**LroLocationHeader** | No async operation supported by Mantenance RP. Lor suppress required if we fix linter error then it will break dot net sdk behaviour because arm send 202 without location e.g. Response Payload. No Lro location header exist. ``` { "RequestUri": "/subscriptions/eee2cef4-bc47-4278-b4f8-cfc65f25dfd8/resourcegroups/dotnetsdkeastus2euap/providers/Microsoft.Maintenance/configurationAssignments/dotnetsdktestassignment01?api-version=2023-04-01","RequestMethod": "DELETE", "RequestBody": "", "RequestHeaders": { "x-ms-client-request-id": [ "cc1b2a54-8a08-463a-9d3b-0f3f651af17d"],"Accept-Language": ["en-US"],"User-Agent": ["FxVersion/6.0.1623.17311","OSName/Windows","OSVersion/Microsoft.Windows.10.0.22621","Microsoft.Azure.Management.Maintenance.MaintenanceManagementClient/1.5.0.0"]},"ResponseHeaders": {"Cache-Control": ["no-cache"],"Pragma": ["no-cache"],"x-ms-request-id": [""],"x-ms-ratelimit-remaining-subscription-deletes": ["14996"],"x-ms-correlation-request-id": ["841d3e50-d1ff-4bd1-ad7b-20ed0a35a72b"],"x-ms-routing-request-id": ["EASTUS2EUAP:20230505T135954Z:841d3e50-d1ff-4bd1-ad7b-20ed0a35a72b"],"Strict-Transport-Security": ["max-age=31536000; includeSubDomains"],"X-Content-Type-Options": ["nosniff"],"Date": ["Fri, 05 May 2023 13:59:54 GMT"],"Expires": ["-1"],"Content-Length": ["0"]},"ResponseBody": "","StatusCode": 202 }``` |
|**LroErrorContent** | No async operation supported by Mantenance RP. Lro suppress required if we fix linter error then it will break dot net sdk behavior because arm send 202 without location No Async operation supported by MRP please refer above row for response. |
| **LroExtension** | No Async operation supported by MRP |

**Comment by KalpeshChavan12** [comment]
@rkmanda 
I have removed recommended suppression and remove 202 status code

**Comment by KalpeshChavan12** [comment]
> @rkmanda I have removed recommended suppression and remove 202 status code

Any Updates?

**Review by rkmanda — APPROVED** [review]
:shipit:

**Pull request merged**
