### PR TITLE
Integration Account api spec

### PR DESCRIPTION
**Pull request by pankajsn**
Integration Account api specs for Logic App with composite client to support two API versions.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pankajsn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pankajsn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by fearthecowboy** [comment]
Hey @pankajsn,

Very nice spec. Very clean :)

The only thing I wanted to mention is when you have a `$ref` with a sibling `description property` : 

ie: 

``` javascript 
    "EdifactFramingSettings": {
            "type": "object",
            "properties": {
               // ... snipped for berevity ...
                "characterSet": {
                    "$ref": "#/definitions/EdifactCharacterSet",
                    // LOOK HERE
                    // This description should really be in the definition at "#/definitions/EdifactCharacterSet" 
                    "description": "Gets or sets EDIFACT one-way receive agreement."
                },
            }
               // ... snipped for berevity ...
        },

// ... snipped for berevity ...
  "EdifactCharacterSet": {
            "type": "string",
             // LOOK HERE
             // description should really go here
            "enum": [
                "NotSpecified",
                "UNOB",
                "UNOA",
                "UNOC",
                "UNOD",
                "UNOE",
                "UNOF",
                "UNOG",
                "UNOH",
                "UNOI",
                "UNOJ",
                "UNOK",
                "UNOX",
                "UNOY",
                "KECA"
            ],
            "x-ms-enum": {
                "name": "EdifactCharacterSet",
                "modelAsString": false
            }
        },
```

At this point, if you're getting the right generated code, I wouldn't worry too much today, however, in the near future, the forthcoming linter tool will pick these up as warnings.  _(hmm. perhaps we should make it so the linter can auto-fix stuff like that)_

Other than that

Looks Good To Me ™️ 

Unless @amarzavery  finds anything, good to merge.

**Comment by fearthecowboy** [comment]
Hey @pankajsn,

Oh yeah,  @amarzavery   mentioned one thing we'd like to see fixed -- 

Remove the `Gets or sets` text from the properties, the code generator will add that on languages where that's appropriate.

**Comment by pankajsn** [comment]
This is fixed.

Regards,
~Pankaj

**Pull request merged**
