### PR TITLE
Sm long running operation

### PR DESCRIPTION
**Pull request by stevemunk**
# Data Plane API - Pull Request
Made long-running operation references consistent. Changed the following to "long-running operation":

"long-running request": 31 times in 18 different files
"long-running process": 2 times in 1 file
"long running request": 2 times in 2 different files
"long running operation": 2 times in 1 file
"long running process": 18 times in 12 different files

### CODE REVIEW

**Comment by ismael-ms** [comment]
Hi @anuchandy, could you please help us understand why ModelValidation is now suddenly showing 336 Errors? It appears that the issues are not due to the changes from this PR, as I see the same errors when executing ModelValidation locally on the main branch. Since we haven't touched most of these docs in months, are these false positives from new validation checks?

**Comment by ismael-ms** [comment]
Hi @anuchandy, @scgbear, @MushMal, just a gentle ping for guidance on how we can move forward in this PR with the immense amount of ModelValidation errors that exist on main already. Thank you.

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
@ismael-ms  I looked at the PR, and I see it's all about improving the documentation. Can you fix the merge conflict so we can merge these doc changes?

I'll check with the tools owners on the flagged validation errors unrelated to these changes; if any action is needed in the swagger, we can have a work item to address it separately.

**Comment by ismael-ms** [comment]
> @ismael-ms I looked at the PR, and I see it's all about improving the documentation. Can you fix the merge conflict so we can merge these doc changes?
> 
> I'll check with the tools owners on the flagged validation errors unrelated to these changes; if any action is needed in the swagger, we can have a work item to address it separately.

@anuchandy Thank you for being understanding and for the review! I have now resolved the merge conflict.

**Pull request merged**
