### PR TITLE
Add missing private endpoint connection properties

### PR DESCRIPTION
**Pull request by mattgotteiner**
* Add missing properties `groupId` and `provisioningState` to the 2022-09-01 control plane swagger

### CODE REVIEW

**Comment by mattmsft** [comment]
@arv100kri

**Review by arv100kri — COMMENTED** [review]
LGTM in general

Don't you need to update examples and such when you are modifying swagger?

**Comment by mattmsft** [comment]
> LGTM in general
> 
> Don't you need to update examples and such when you are modifying swagger?

We don't need to update the example for this API right now - we are still in a dev branch

**Review by tjacobhi — APPROVED** [review]

**Comment by enjaimes** [comment]
Hello @bexxx , @BlackRider97

Could you provide advice on how to deal with the "license/cla" status that is missing for this PR to be merged? 
This is something we've never seen before, and it is blocking our release.

**Comment by enjaimes** [comment]
Any feedback on the above question? @AzureRestAPISpecReview 

This "license/cla" issue is blocking our release of the new api version.

**Pull request merged**
