### PR TITLE
Add missing displayName and domains properties to response of Tenants_List call

### PR DESCRIPTION
**Pull request by cormacpayne**
### Description

Partial fix for issue https://github.com/Azure/azure-rest-api-specs/issues/6468 -- the model object returned from the `Tenants_List` call in the `subscriptions.json` spec for ARM is missing a few properties (as outlined in the linked issue), and this change is adding two missing properties (`displayName` and `domains`) to this object in the latest stable API version for this spec.

CC: @Tiano2017 @ravbhatnagar -- would you mind taking a look at this change?

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by cormacpayne** [comment]
@zikalino @Tiano2017 @ravbhatnagar gentle ping 😀

**Comment by zikalino** [comment]
@cormacpayne looks good in general. just doing a few checks :-)

**Comment by zikalino** [comment]
@cormacpayne I have actually tried **GET /tenants** using api_version 2018-06-01, and I didn't get these properties, so I think I would like to verify what's the reason.

```
        "response": [
            {
                "id": "/tenants/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            }
        ],
        "url": "/tenants",```

@Tiano2017 @ravbhatnagar could you check that?

**Comment by Tiano2017** [comment]
@zikalino I did it just now.. and could see "domains" in the response.

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
@stankovski is it ok to merge?

**Comment by cormacpayne** [comment]
@stankovski any update?

**Review by chiragg4u — APPROVED** [review]
Thanks Cormac for these changes. :)

**Review by stankovski — APPROVED** [review]

**Comment by cormacpayne** [comment]
@zikalino @stankovski is this OK to merge?

**Pull request merged**
