### PR TITLE
Revert "update-typescript.md"

### PR DESCRIPTION
**Pull request by qiaozha**
Reverts Azure/azure-rest-api-specs#17182

### CODE REVIEW

**Review by dw511214992 — APPROVED** [review]

**Comment by JackTn** [comment]
Hi, @qiaozha. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @qiaozha. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @qiaozha. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
