### PR TITLE
Classify changes

### PR DESCRIPTION
**Pull request by v-sodsou**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by v-sodsou** [comment]
@sergey-shandar Could you please review this PR. We have schema change in our API response so I have modified the same in specification file.

Thanks
Sonali Dsouza

**Comment by sergey-shandar** [comment]
@v-sodsou Are you aware that this is SDK breaking changes? Which means, in some cases, your customers will need to rewrite their programs for new SDK.

**Comment by v-sodsou** [comment]
@sergey-shandar we intend to roll out new version of sdk. Could you please suggest how to proceed on handling new changes to api and rolling it out with new sdk version.

**Comment by sergey-shandar** [comment]
@v-sodsou if you have changes in Rest-API, I would suggest to use new API version. See https://github.com/Azure/azure-rest-api-specs/#getting-started

**Comment by sergey-shandar** [comment]
@v-sodsou I'm closing the PR. You can still either open a new PRs (probably with new API version) or reopen this one if you would like to discuss breaking changes in the same API version.

**Pull request closed without merging**
