### PR TITLE
Updating Data Classification Swaggers.

### PR DESCRIPTION
**Pull request by bashahee**
This PR updates Data Classification swagger files and examples. This is not a breaking change, as reference to these files was not present in the readme.me file, hence clients were not generated yet.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by veronicagg — CHANGES_REQUESTED** [review]
CI is failing syntax and semantic checks, please take a look at those first, so the other tools can properly execute. If you need help, please let me know. Thanks!

**Comment by bashahee** [comment]
@veronicagg Automation for azure-sdk-for-java is failing since I added  - ./Microsoft.Sql/preview/2017-03-01-preview/sensitivityLabels.json under package-pure-2017-03-preview in the readme.md file.

**Comment by veronicagg** [comment]
@bashahee there's probably a class name that's duplicated in that version when you add the file, so it's colliding on SDK generation - "Duplicate File Generation".
@anuchandy could you help with Java SDK generation for ./Microsoft.Sql/preview/2017-03-01-preview/sensitivityLabels.json under package-pure-2017-03-preview ?

**Comment by veronicagg** [comment]
@jaredmoo do you want to look at/approve this PR? 
@bashahee have the changes and new files been reviewed by ARM team?
Apart from Java generation, rest looks good to me.

**Review by veronicagg — CHANGES_REQUESTED** [review]
See comments inline.

**Comment by bashahee** [comment]
@veronicagg I am not introducing new APIs, these APIs are already in production. I am updating swagger files in order to generate SDK clients, as part of my work on implementing PowerShell Cmdlets.
No source code was changed, apart from modifying examples.

**Review by jaredmoo — APPROVED** [review]

**Comment by bashahee** [comment]
@veronicagg Can this PR be merged now?

**Comment by anuchandy** [comment]
@bashahee Identified an issue in java codegen and created an issue here https://github.com/Azure/autorest.java/issues/323. 

However fixing it requires some time, meantime to unblock your PR, I've updated readme Java section and opened this PR https://github.com/bashahee/azure-rest-api-specs/pull/1, could you merge it?

**Comment by veronicagg** [comment]
@bashahee I was waiting on the java code gen issue, please take a look at the PR suggested by @anuchandy , if it makes sense to you to do the rename to avoid collisions, please merge that in, and I'll approve/merge this PR. Thanks!

**Review by veronicagg — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
