### PR TITLE
Fix Swagger Correctness.

### PR DESCRIPTION
**Pull request by bowen5**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [x] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@bowen5 , could you paste the ADO work item for the S360 KPI for reference? Thanks.

**Comment by bowen5** [comment]
> @bowen5 , could you paste the ADO work item for the S360 KPI for reference? Can you share the reason why it doesn't need to refresh SDK/CLI? Thanks.

Here yo go https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8187806. What I did in this PR is 1. add default values in def, which I suppose no need SDK/CLI change as server side is already behaving like those default values? 2. add def in old preview version payload, which new latest SDK/CLI they are already using new version payload and already contains those changes.

**Comment by raych1** [comment]
> > @bowen5 , could you paste the ADO work item for the S360 KPI for reference? Can you share the reason why it doesn't need to refresh SDK/CLI? Thanks.
> 
> Here yo go https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8187806. What I did in this PR is 1. add default values in def, which I suppose no need SDK/CLI change as server side is already behaving like those default values? 2. add def in old preview version payload, which new latest SDK/CLI they are already using new version payload and already contains those changes.

@bowen5 , is there any update for the breaking change review request?

**Comment by raych1** [comment]
@bowen5 , I double checked all the issues and these are not fixed yet. Would you like to have them fixed in this PR?
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=958A283D-0381-4C34-A790-52F670D3826C
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=0C6BA34E-565E-4145-932B-987E048BCF0D
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=6CB0D123-B082-4E26-9FCC-B25854DECDFB
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=CAF67AE2-8D16-4197-B387-D67C84C8031C

**Review by raych1 — APPROVED** [review]

**Pull request merged**
