### PR TITLE
[Azure Analysis Services] Replace config object with uri string

### PR DESCRIPTION
**Pull request by taiwu**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by taiwu** [comment]
Refer to https://github.com/Azure/azure-rest-api-specs/pull/1296
Since the original backupConfiguration is not in used, no need to bump the version.

**Comment by taiwu** [comment]
@vishrutshah Could you please take a look?

**Comment by vishrutshah** [comment]
Hi @taiwu, 

@jhendrixMSFT would be looking the PR. @jhendrixMSFT Please refer the previous conversation on https://github.com/Azure/azure-rest-api-specs/pull/1296 to get the context. 

Thanks!

**Comment by jhendrixMSFT** [comment]
I'm reviewing this today.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by taiwu** [comment]
Thanks!

**Comment by sergey-shandar** [comment]
@taiwu I'm just curious. Is there a reason why we change old swagger if we have a new one. These kind of changes are API breaking changes.

**Comment by sergey-shandar** [comment]
@ravbhatnagar This's SDK breaking changes. Even if the removed optional property and type are never used by server, it breaks existing client code. Should we revert, add these types back?

**Pull request merged**
