### PR TITLE
Logic IA Session fix error response

### PR DESCRIPTION
**Pull request by daviburg**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [X] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by vishrutshah** [comment]
Please also update respective `x-ms-examples` so that model validation can pass:  https://travis-ci.org/Azure/azure-rest-api-specs/jobs/207548176

Also, we'd request you to look for all the errors cought by linter and fix them for better quality swagger. 
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/207548174

**Review by vishrutshah — CHANGES_REQUESTED** [review]
same as above comment. [Github made me write this forcefully otherwise i cannot request change :P]

**Comment by daviburg** [comment]
x-ms-example fixed, pending build validation.
For the existing lint errors, I will look into fixing them but we should consider doing that in a separate PR.

**Comment by daviburg** [comment]
lint's "ListOperationNamingWarning", "Operation foo must be one of: bar" and "Tracked Resource failing validation is: Workflow" are breaking change requests. We cannot do that in current published version, it would have to be taken in a major revision.

Regarding:
"code": "ArmResourcePropertiesBag",
    "message": "Top level property names should not be repeated inside the properties bag for ARM resource \"Resource\". Properties [id, name, type, location, tags] conflict with ARM top level properties. Please rename these.",
    "jsonref": "arm-logic/2016-06-01/swagger/logic.json#/definitions",

"Workflow": {
      "type": "object",
      "properties": {
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/WorkflowProperties",
          "description": "The workflow properties."
        }
      },

What's the proper way to define the "properties" standard property of ARM resource entity?

BooleanPropertyNotRecommended warning: the RP model is already public with these Booleans for a while. It would not be wise to do a breaking change now.

I'll look into fixing DefinitionsPropertiesNamesCamelCase
@tonytang-microsoft-com

**Comment by vishrutshah** [comment]
@daviburg If'd like to fix the linter errors separately, let me know i can open issue and assign it to you. That way we can unblock this PR if'd prefer. Let us know. Thanks!

**Comment by daviburg** [comment]
Opening specific issues for the different kind of lint errors on this existing file. Here's the first: https://github.com/Azure/azure-rest-api-specs/issues/994

**Comment by daviburg** [comment]
Here is the second for which we will need guidance: https://github.com/Azure/azure-rest-api-specs/issues/995

**Comment by daviburg** [comment]
Third issue for patch operation missing on Integration Account types: https://github.com/Azure/azure-rest-api-specs/issues/997

**Comment by daviburg** [comment]
Please unblock this review as issues have been opened for remaining linter errors in the existing swagger. This PR does not introduce any new linter error.

**Review by vishrutshah — APPROVED** [review]

**Pull request merged**
