### PR TITLE
Update autorest emitter to 0.42.1

### PR DESCRIPTION
**Pull request by timotheeguerin**

### CODE REVIEW

**Review by mikeharder — APPROVED** [review]

**Comment by mikeharder** [comment]
@timotheeguerin: I will probably need to force-merge this due to https://github.com/Azure/azure-sdk-tools/issues/7657

**Comment by timotheeguerin** [comment]
> @timotheeguerin: I will probably need to force-merge this due to [Azure/azure-sdk-tools#7657](https://github.com/Azure/azure-sdk-tools/issues/7657)

Ran `pwsh ./eng/scripts/TypeSpec-Validation.ps1 -CheckAll` and doesn't seem to be any diff so wouldn't expect it to fail here, so should be good I think when that pass

**Comment by konrad-jamrozik** [comment]
@mikeharder additions of `PipelineBotTrigger` are the solution to: https://github.com/Azure/azure-sdk-tools/issues/7657

**Pull request merged**
