### PR TITLE
Remove version 2020-01-01 of security alert policies for Orcas

### PR DESCRIPTION
**Pull request by ayeletshpigelman**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by QingqingYuan2 — APPROVED** [review]

**Comment by erich-wang** [comment]
It seems you're removing APIs from stable version, please check [Breaking Change Policy](http://aka.ms/bcforapi).

**Comment by ArcturusZhang** [comment]
Hi @erich-wang to clarify, this PR is not actually removing something - it is replacing an API in higher API version by a lower API version. Well I am not quite sure this is breaking changes or not. At least the breaking changes CI says no

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Supersedes https://github.com/Azure/azure-rest-api-specs/pull/10474

**Comment by akning-ms** [comment]
> Hi @erich-wang to clarify, this PR is not actually removing something - it is replacing an API in higher API version by a lower API version. Well I am not quite sure this is breaking changes or not. At least the breaking changes CI says no

FYI, breaking changes CI tools have a known issue: it will be report a break change in the case of deleting a swagger file

**Comment by ayeletshpigelman** [comment]
Hi @erich-wang, This PR removes swagger files of APIs which were not exposed in the manifest. Therefore customers don’t use them. Moreover, these APIs didn’t add any new functionality.
According to Jeffrey Richter, this is not a breaking change. can you please review?

**Comment by lirenhe** [comment]
Per the discussion with API review board, 2020-01-01 version has not been enabled so approve the revert back the changes.

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
