### PR TITLE
chore: jsonfmt hdinsight

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/hdinsight/**/*.json"`

### CODE REVIEW

**Comment by kpajdzik** [comment]
Merge conflicts.

**Comment by nschonni** [comment]
@kpajdzik if you want to re-open this I can rebase it instead of creating a new PR

**Comment by kpajdzik** [comment]
> @kpajdzik if you want to re-open this I can rebase it instead of creating a new PR

Ok, works for me as well :) Thanks!

**Comment by nschonni** [comment]
Thanks, I'll need you to reopen it before I can rebase. Force pushing to a closed PR means it can't be re-opened

**Comment by nschonni** [comment]
@kpajdzik I've rebased and force pushed the branch

**Review by kpajdzik — APPROVED** [review]

**Comment by kpajdzik** [comment]
@jhendrixMSFT, Could you merge? This PR includes only white-space changes.

**Pull request merged**
