### PR TITLE
1566145 new property added to publicipaddress list<iptag>, disableroutegrouppropagation on rout…

### PR DESCRIPTION
**Pull request by skomarag**
…etable

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by veronicagg** [comment]
@skomarag should this PR be againstNetwork-2017-10-01 branch? (https://github.com/Azure/azure-rest-api-specs/tree/Network-2017-10-01) 
@DeepakRajendranMsft is this part of the set that was coming towards the feature branch?

**Comment by veronicagg** [comment]
A lot of the content is probably copied from the previous API version, please follow the contribution guidelines (liked from the checklist in the PR) https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure to make different commits for reviewing. If you're expecting to move it to the other branch, please have a PR first to commit a new version with the same contents as the previous version, for merging and then send following PRs on top, so changes/additions can be more clearly reviewed. Thanks!

**Review by veronicagg — CHANGES_REQUESTED** [review]
See my previous comments/questions.

**Comment by veronicagg** [comment]
Additionally, please review json compliance, PR is failing CI due to syntax check.

**Comment by veronicagg** [comment]
@skomarag any updates on this PR? This PR will get closed due to inactivity by tomorrow, thanks.

**Comment by neaggarwMS** [comment]
+Murilo, Sandhya

Sandhya,
Can you update the status on this thread?

Thanks
Neha

**Comment by veronicagg** [comment]
@skomarag Closing PR, please review comments above and submit a new PR when you're back to this. Thanks!

**Pull request closed without merging**
