### PR TITLE
Update KeyVault enums to have shorter names.

### PR DESCRIPTION
**Pull request by xirzec**
Created from: https://github.com/Azure/azure-sdk-for-js/issues/5883

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Review by heaths — CHANGES_REQUESTED** [review]
This would be a breaking change for generated track 1 code. For track 2 code, we already shortened these names prior to GA, in pretty much the ways you changed them below.

**Comment by akning-ms** [comment]
Hi @xirzec , is this PR still need as it is idle for a long time?

**Review by heaths — APPROVED** [review]
LGTM

**Comment by xirzec** [comment]
I'm not sure if this is still worth doing or not. @schaabs ?

**Pull request closed without merging**
