### PR TITLE
feature/cognitiveservices/openai, model Completion for response body

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
All SDK would required a named model for response body. Hence make a model for `Completion` response body; an alias `CompletionResponse` for the whole response (includes headers).

---

It could also relate to issue on `getEffectiveModelType` https://github.com/microsoft/cadl/issues/1511

---

In original Cadl source (`Completion` model includes header):
cadl-autorest works because it uses [getEffectivePayloadType](https://github.com/Azure/cadl-azure/blob/b61e319/packages/cadl-autorest/src/openapi.ts#L763), which would directly use `Completion` model (as it is not anonymous), and then in final schema output [remove the header property](https://github.com/Azure/cadl-azure/blob/b61e319/packages/cadl-autorest/src/openapi.ts#L1373-L1375).

# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@lmazuel

Let me know if this change is acceptable. Personally I feel we should always provide a clean model for response body, as almost all SDK need to generate a class/model/type for response body.

**Comment by weidongxu-microsoft** [comment]
Alternatively, if we don't want this PR, emitter can add this "remove non-payload property" logic (for all SDKs).
https://github.com/Azure/cadl-azure/blob/main/packages/cadl-autorest/src/openapi.ts#L1365-L1367

**Comment by nguerrera** [comment]
Permalink for relevant cadl-autorest code since that non-oermalink is already off by a few lines, I think:

https://github.com/Azure/cadl-azure/blob/b86f3fe67848d72e4bd532124538a820ca851a8f/packages/cadl-autorest/src/openapi.ts#L1373-L1375

**Comment by nguerrera** [comment]
Whenever reviewing a model with an @header (or @path, @query, etc.), it's important to ask "does this property *logically* belong to this model?". Is `"apim-request-id"` logically part of a `Completion`? I suspect not. So the Cadl should be changed along the lines of your PR unless I'm mistaken about that.

We have had a lot of debate about the cases where a logical model has header/path/query property that does logically belong and how to handle it or even whether DPG should support this at all. But before diving into the debate, it's best to use a real example that actually has logically well-factored Cadl. One thing I will say is that a client generator is not required to mimic OpenAPI. OpenAPI would simply be incorrect to put a header in the body schema. That's against the definition of the body schema. But a client generator has more freedom. It's only absolute constraint is that it emits code that works and that could involve a single class that transmits some of its properties in headers and some in the body, which if the Cadl followed the only-if-logical would probably be the right thing to do.

**Comment by nguerrera** [comment]
(Deleted some comments that were meant to go on https://github.com/microsoft/cadl/issues/1511)

**Pull request closed without merging**
