### PR TITLE
Update tspconfig.yaml

### PR DESCRIPTION
**Pull request by haolingdong-msft**
namespace review: https://github.com/Azure/azure-sdk-pr/issues/1929

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
Check if you need to add `service-name`

**Comment by weidongxu-microsoft** [comment]
Also examples-directory

https://github.com/Azure/azure-rest-api-specs/tree/main/documentation/onboard-dpg-in-sdkautomation/java

**Review by XiaofeiCao — APPROVED** [review]

**Pull request merged**
