### PR TITLE
Revert "Fix Blob Quick Query XML elements to align with service and documentation."

### PR DESCRIPTION
**Pull request by amnguye**
Reverts Azure/azure-rest-api-specs#14688

There's either a bug in the service or the documentation.

### CODE REVIEW

**Comment by amnguye** [comment]
Closing PR, the changes made from that this PR is trying to revert are fine and correct.

**Comment by JackTn** [comment]
Hi, @amnguye. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @amnguye. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @amnguye. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by amnguye** [comment]
@JackTn Feel free to the delete the branch. Thanks.

**Pull request closed without merging**
