### PR TITLE
VPN Client Protocols for Virtual Network Gateways

### PR DESCRIPTION
**Pull request by henry416**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by henry416** [comment]
FYI existing spec (2017-06-01) gives error on SDK generation for some reason

**Comment by olydis** [comment]
which error are you referring to?

**Comment by henry416** [comment]
@olydis I am using the arm-network 2017-06-01 rest API to generate code using AutoRest in the azure-sdk-for-net project. It gives error saying RouteFilterPropertiesFormat swagger elements are undefined.

**Comment by henry416** [comment]
Nevermind, found the problem was with the linking json

**Comment by olydis** [comment]
>             "name": "resourceGroupName",

could you please extract this parameter definition to reduce duplication and simplify the editing experience? See [https://github.com/Azure/azure-rest-api-specs/blob/a9062535ffde91b5f6f77a7215d606b75a52a04f/arm-recoveryservicesbackup/2016-06-01/swagger/registeredIdentities.json#L73](https://github.com/Azure/azure-rest-api-specs/blob/a9062535ffde91b5f6f77a7215d606b75a52a04f/arm-recoveryservicesbackup/2016-06-01/swagger/registeredIdentities.json#L73) for an example (note the `x-ms-parameter-location`)

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:48 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>             "description": "Request successful. The operation returns a list of VirtualNetworkGateway resources.",

general comment: don't repeat names of models or methods in documentation (here: `VirtualNetworkGateway`). There is no guarantee that these names turn out the same way in generated code (they really don't), so customers may be confused by this. Try using generic, natural language for descriptions.

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:196 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>         "description": "The Put VirtualNetworkGatewayConnectionSharedKey operation sets the virtual network gateway connection shared key for passed virtual network gateway connection in the specified resource group through Network resource provider.",

same as above: very technical sounding description. Why is "Put" upper case? In this case, I'd actually just say something like "Sets the virtual network gateway ...". No need to restate the obvious.

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:587 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>             "description": "Parameters supplied to the Begin Set Virtual Network Gateway connection Shared key operation throughNetwork resource provider."

this description is not very user friendly

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:610 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "description": "The private IP allocation method. Possible values are: 'Static' and 'Dynamic'.",

don't restate possible values in the description if you have provided an `enum` definition. Needless duplication of information.

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:937 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "description": "The provisioning state of the public IP resource. Possible values are: 'Updating', 'Deleting', and 'Failed'."

shouldn't this simply be an enum instead?

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:958 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>       "description": "Properties of VirtualNetworkGatewayIPConfiguration"

this description has no value.

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:961 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by henry416** [comment]
I'm a bit confused I'm not familiar with any of those elements. Did you mistake this PR with someone else?

**Comment by olydis** [comment]
>           "description": "The provisioning state of the VirtualNetworkGateway resource. Possible values are: 'Updating', 'Deleting', and 'Failed'."

why isn't this an enum?

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1049 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "description": "The provisioning state of the VPN client root certificate resource. Possible values are: 'Updating', 'Deleting', and 'Failed'."

enum?

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1063 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "description": "VpnClientRootCertificate for virtual network gateway."

provides no value

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1143 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>         },

what are those properties supposed to mean? As a customer, I had no clue what these are for.
Please provide good descriptions for these. Furthermore: Are these property names really what your service expects/returns? If so, note that you can override the names generated in code using `x-ms-client-name` to provide better user experience (see [https://github.com/Azure/azure-rest-api-specs/blob/b00eb20e6c13b2b4d0f607bd230a642d410ff584/arm-storage/2017-06-01/swagger/storage.json#L593](https://github.com/Azure/azure-rest-api-specs/blob/b00eb20e6c13b2b4d0f607bd230a642d410ff584/arm-storage/2017-06-01/swagger/storage.json#L593))

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1466 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "description": "The authorizationKey."

at least out a space in there...

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1456 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Comment by olydis** [comment]
>           "$ref": "#/definitions/VirtualNetworkGatewayPropertiesFormat"

the property `properties` is required, yet none of it's properties are. What does your service do, if I pass an empty object?

---
Refers to: arm-network/2017-06-01/swagger/virtualNetworkGateway.json:1333 in 067e817. [](commit_id = 067e817c2496bf8ccaed9fbd2d3e1eb5bbfd6a69, deletion_comment = False)

**Review by olydis — CHANGES_REQUESTED** [review]
@henry416 I'm aware that some of my requests are not directly related to your PR, however some of them are low hanging fruits regarding customer experience. Hence, it would be nice if you could do a quick run fixing any issue you can. I just wanted to raise some quality concerns about this file, whoever is responsible for the corresponding sections should be aware of those 🙂

**Comment by henry416** [comment]
@olydis I wish to separate this PR from any QOL changes to avoid overlapping scopes and time constraints. Opened a PR exclusively for QOL fixes here: https://github.com/Azure/azure-rest-api-specs/pull/1331

**Comment by olydis** [comment]
@henry416 very cool, thanks!

**Review by olydis — APPROVED** [review]

**Pull request merged**
