### PR TITLE
Initial commit of the DevTestLab spec

### PR DESCRIPTION
**Pull request by iouri-s**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iouri-s__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (iouris). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
General Comment: Indentation:  2 spaces. If you are using VS, set indentation for json to 2 spaces.
Then Select ALL + Ctrl + K + D.

**Comment by amarzavery** [comment]
Why do you have square brackets in Model definition names? Just curious to know.
> "#/definitions/ResponseWithContinuation[Lab]"

**Comment by amarzavery** [comment]
General comment: Please provide proper description for parameters of every operation. I hardly see it any where. The description becomes the client library documentation and MSDN REST API documentation, if the API is intended to be there.

**Comment by amarzavery** [comment]
Please remove "deprecated": false from all the operations. Its default value is false and serves no purpose.

**Comment by amarzavery** [comment]
Is "ArtifactSource_CreateOrUpdateResource" a long running operation?
If so, then please apply the extension `"x-ms-long-running" : true`. You can take a look at the documentation over here: https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-long-running-operation

**Comment by amarzavery** [comment]
General comment: It would be nice to provide a different name than "body" to body parameters.
For example in "VirtualMachine_ApplyArtifacts",the parameter name "body" could have been "ArtifactInstallProperties"

**Comment by amarzavery** [comment]
CostSettinProperties.provisioningState should have enum values. Usually, all the RPs have that as an enum. Just pointing it out to your notice. It is perfectly fine if it needs to be simple string in this scenario.

**Comment by amarzavery** [comment]
Description for model properties in the definitions section.

**Comment by iouri-s** [comment]
I see the build validation is failing on the $schema properties that we added for ease of authoring. I can definitely remove this, but wouldn't you want to support it?

**Comment by iouri-s** [comment]
@amarzavery 

Not all RPs use enum. We can consider switching, but that would be a risky change in the codebase without any change in the OM since we still want to surface it as a string in the API

    "RedisReadableProperties": {
      "properties": {
        "provisioningState": {
          "type": "string",
          "description": "Redis instance provisioning status"
        },

**Comment by amarzavery** [comment]
@iouri-s - We have a schema, that contains the swagger schema and the schema for all the extensions.
Our tests run the swagger doc, against that schema. Hence, the schema in the swagger doc is not required.

The schema that we use is found here https://github.com/Azure/autorest/blob/master/schema/swagger-extensions.json

**Comment by iouri-s** [comment]
The latest commit implements most of the feedback. The swagger spec is produced entirely by Swashbuckle and there was no way to suppress the emission of deprecated: false property. I had to remove it by hand (if Ctrl-H qualifies as "by hand"). The square brackets are the default representation of generic types by Swashbuckle. All of the operations and their parameters now contain documentation. Documenting the model is going to take a little longer. Does it have to be fully documented from the very first merge?

**Comment by amarzavery** [comment]
@iouri-s - Description for model types helps as that forms the basis for documentation of method parameters (if used in body) or responses. Client library reference docs of different languages will reflect that content. Take a look at this example for node sdk  http://azure.github.io/azure-sdk-for-node/azure-arm-resource/latest/Deployments.html#createOrUpdate. Customers find this useful.

That being said, it is fine to not have it in the first version. However, please make sure to fix this as soon as possible.

**Pull request merged**
