### PR TITLE
Update databaseVulnerabilityAssessments.json

### PR DESCRIPTION
**Pull request by michaelelleby**
Updated storageContainerSasKey explaining that both read and write access is required in the SAS token.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [N/A] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [N/A] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [N/A] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by jaredmoo — APPROVED** [review]

**Comment by raych1** [comment]
@michaelelleby, can you fix the CI check failures?

**Comment by raych1** [comment]
@qiaozha , can you have a look at JS SDK failures and give suggestions for the fix? @michaelelleby , can you look at the CI check failures and fix them?

**Comment by qiaozha** [comment]
@michaelelleby hi, it seems that you have several files defined "storageContainerSasKey", but you've only changed the description of  this file specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessments.json which cause inconsistency. you may change the description of  other files that have "storageContainerSasKey" definition to the same as this file. 
Also, duplicate definitions may cause SDK generation failure.

**Comment by raych1** [comment]
@michaelelleby, can you please follow the guidelines @qiaozha provided to fix the failures?

**Review by raych1 — CHANGES_REQUESTED** [review]
@michaelelleby , please follow Qiaoqiao's guidance to fix the check failures, thanks.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
