### PR TITLE
Scheduler Spec for API version 2016-03-01

### PR DESCRIPTION
**Pull request by pinwang81**
Adding Scheduler Swagger Spec for API version 2016-03-01.

### CODE REVIEW

**Comment by amarzavery** [comment]
Line 1555: Naming convention - api-version parameter. Take a look at other specs for example: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2015-06-15/swagger/storage.json#L840

**Comment by amarzavery** [comment]
Line 121: "operationId": "JobCollections_CreateOrUpdate", seems to be a long running operation.

Please take a look at this extension : https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-long-running-operation

**Comment by amarzavery** [comment]
Line 383: Jobs_CreateOrUpdate: Looks like this is also a long running operation

**Comment by pinwang81** [comment]
Fixed api-version name convention.
JobCollections_CreateOrUpdate and Jobs_CreateOrUpdate are not long running operations.

**Comment by amarzavery** [comment]
So what happens when the user gets a 201? How does he get to know that the request finally got a 200 ?

**Comment by pinwang81** [comment]
201 is Created.

**Comment by amarzavery** [comment]
Line 673: "name": "$top",
"description": "the number of job history to request, in the of range [1..100]."
If you wish you can add validation constraints for min and max.

Click on this link https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-fields-2 and scroll up a little once the page is loaded

**Comment by amarzavery** [comment]
I know that 201 is created. What I am interested in knowing is this
- How does he get to know that the request finally got a 200 ?

**Comment by pinwang81** [comment]
The meaning of 201 and 200 are in the description.  If you create, you get 201 and if you update, you get 200.

**Pull request merged**
