### PR TITLE
Add Extended location to Microsoft.Compute VM, VMSS & Image resources

### PR DESCRIPTION
**Pull request by srinath9795**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by srinath9795** [comment]
Adding support for the new “extendedLocations” ARM property. Specs here:

1.  [ARM Edge Location Design](https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/Doc.aspx?sourcedoc=%7B7178262A-BC22-49C9-80C4-3A12D7C9B03B%7D&file=ARM%20Edge%20Location%20Design.docx&wdLOR=cC515FAB5-6C4D-4BFF-A210-9970E2B1C3AD&action=default&mobileredirect=true&CID=D913F4B2-7DCA-41A8-96C8-3AA28CF29DDC)

2. [Extending Azure location](https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/Doc.aspx?sourcedoc=%7B61F76676-CE74-4D86-BCFA-61929F5F7CB7%7D&file=Extending%20Azure%20location.docx&action=default&mobileredirect=true&CID=199316B5-3AB5-4104-8DA2-2E9B2E615E58&wdLOR=cE3229FAF-34C5-422F-A380-84F6B852D39D)

Introducing the new top property “extendedLocation” which is a complex property with its own “type” and “name” properties. Presumably there will be other extended location types, but its not clear which ones will have relevance to Microsoft.Compute. Currently the only type that is supported in “EdgeZone”.

We previously updated the swagger spec with extendedLocations to a private repo ([PR Link](https://github.com/Azure/azure-rest-api-specs-pr/pull/1579)), but, making it public now as AKS has a dependency on the public SDK.

**Review by rafaelrruiz — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Please fix the linter error according to the log message. To verify locally, you can follow the [fix guide](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#linter-validation).

As identified in the automated checks there are breaking changes, please review [Policy for Breaking Changes](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes) and request an approval .

**Comment by fengzhou-msft** [comment]
@srinath9795 any update?

**Comment by fengzhou-msft** [comment]
Close idle PR. Please feel free to reopen it and continue the work if you still need it.

**Pull request closed without merging**
