### PR TITLE
Approved 2020-06 API version to support Live Metrics token generation.

### PR DESCRIPTION
**Pull request by tokaplan**
_**Note to reviewers**_: this change has already been approved in private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/1401

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by tokaplan** [comment]
**_Note to reviewers:_** this change has already been approved in private repo: Azure/azure-rest-api-specs-pr#1401

**Review by mmyyrroonn — APPROVED** [review]
Approved since it's already reviewed in private repo

**Comment by MyronFanQiu** [comment]
@tokaplan Hi. Could you please change `readme.python.md` as well?

**Comment by tokaplan** [comment]
@MyronFanQiu do I have to do all changes that I did in _readme.md_ in _readme.python.md_, or just add the _package-preview-2020-06-only_ tag defined in _readme.md_ into _batch_ section in _readme.python.md_ and that's it?
I don't really understand what those files are all about :)

**Comment by MyronFanQiu** [comment]
Based on my knowledge, you just need to add the package-preview-2020-06-only tag defined in readme.md into batch section in readme.python.md and that's it. But let me invite owner to confirm. @qiaozha Could you take a look at this PR? These files are used for all SDKs.

**Comment by tokaplan** [comment]
@MyronFanQiu ok so I made the change you pointed out, I'll make it differently if we hear from someone. One last thing - I'm seeing prettier errors, and it doesn't tell me what's wrong - just tells me to run prettier on my own. I was able to npm install prettier, but it doesn't have a swagger plugin out of the box, so I don't know where to get it and how to run it. Is fixing this issue a prerequisite for merging? If yes, then can you please let me know how to do it? I've seen the instruction, but it doesn't work for me - it tells me to run npm from under node.js console in Windows, and node.js explicitly doesn't allow me to run npm.

**Comment by qiaozha** [comment]
> Based on my knowledge, you just need to add the package-preview-2020-06-only tag defined in readme.md into batch section in readme.python.md and that's it. But let me invite owner to confirm. @qiaozha Could you take a look at this PR? These files are used for all SDKs.

That's correct. no need to define the tag again in readme.python.md

**Comment by qiaozha** [comment]
> @MyronFanQiu ok so I made the change you pointed out, I'll make it differently if we hear from someone. One last thing - I'm seeing prettier errors, and it doesn't tell me what's wrong - just tells me to run prettier on my own. I was able to npm install prettier, but it doesn't have a swagger plugin out of the box, so I don't know where to get it and how to run it. Is fixing this issue a prerequisite for merging? If yes, then can you please let me know how to do it? I've seen the instruction, but it doesn't work for me - it tells me to run npm from under node.js console in Windows, and node.js explicitly doesn't allow me to run npm.

@NullMDR may be able to help here.

**Comment by tokaplan** [comment]
@MyronFanQiu ok I managed to run _prettier_ locally and fixed issues. There are SDK checks failing, but I can't find anything relevant to my change, looks like internal tooling errors. Please let me know if we can merge at this point and how to proceed with the manifest change.

**Comment by MyronFanQiu** [comment]
@pilor Hi. Could you please approve this PR on behalf of ARM team since you approved the private PR.

**Review by pilor — APPROVED** [review]

**Pull request merged**
