### PR TITLE
Add new tag for app insights with GA swaggers

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Comment by vutran01** [comment]
> tag: package-2023-10-01-only

should also make this the default tag to use when sdks are published/generated

---
Refers to: specification/applicationinsights/resource-manager/readme.md:43 in b96b0f7. [](commit_id = b96b0f7b27c3494b64306fe7fda0a04f968f53fc, deletion_comment = False)

**Comment by vutran01** [comment]
> tag: package-2023-10-01-only

also, componentLinkedStorageAccounts_API is not in the new tag, is it being removed?

---
In reply to: [2077635389](https://github.com/Azure/azure-rest-api-specs/pull/28843#issuecomment-2077635389) [](http://example.com/codeflow?ancestors=2077635389)

---
Refers to: specification/applicationinsights/resource-manager/readme.md:43 in b96b0f7. [](commit_id = b96b0f7b27c3494b64306fe7fda0a04f968f53fc, deletion_comment = False)

**Comment by JoshLove-msft** [comment]
> > tag: package-2023-10-01-only
> 
> should also make this the default tag point to the new tag (package-2024-04-25-only) when sdks are published/generated
> 
> Refers to: specification/applicationinsights/resource-manager/readme.md:43 in [b96b0f7](https://github.com/Azure/azure-rest-api-specs/commit/b96b0f7b27c3494b64306fe7fda0a04f968f53fc). [](commit_id = [b96b0f7](https://github.com/Azure/azure-rest-api-specs/commit/b96b0f7b27c3494b64306fe7fda0a04f968f53fc), deletion_comment = False)

I did initially but there was a failure that said the default tag must have all paths present. The new tag removed a preview swagger so that we can ship a stable version of the library.

**Comment by JoshLove-msft** [comment]
> > tag: package-2023-10-01-only
> 
> also, componentLinkedStorageAccounts_API is not in the new tag, is it being removed?
> 
> In reply to: [2077635389](https://github.com/Azure/azure-rest-api-specs/pull/28843#issuecomment-2077635389)
> 
> Refers to: specification/applicationinsights/resource-manager/readme.md:43 in [b96b0f7](https://github.com/Azure/azure-rest-api-specs/commit/b96b0f7b27c3494b64306fe7fda0a04f968f53fc). [](commit_id = [b96b0f7](https://github.com/Azure/azure-rest-api-specs/commit/b96b0f7b27c3494b64306fe7fda0a04f968f53fc), deletion_comment = False)

It is still in preview and the goal here is to have a stable tag to ship a stable version of the client library.

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
