### PR TITLE
Fixing GetServerVariables APIs for 2018-11-01

### PR DESCRIPTION
**Pull request by nirkum18**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/-1 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/-1/commits/

**Comment by dsgouda** [comment]
Please disregard `Automation for azure-sdk-for-net ` failures, known issues with Autorest running out of memory

**Comment by salameer** [comment]
@nirkum18 these are breakihg changes on a stable version. adding @MikhailTryakhov 

why are you introducing these to a version that we've already published SDKs for?

**Comment by nirkum18** [comment]
> @nirkum18 these are breakihg changes on a stable version. adding @MikhailTryakhov
> 
> why are you introducing these to a version that we've already published SDKs for?

The changes in 2018-11-01 are not in sync with the changes in succeeding versions and have a bug in them. This PR is raised to fix them.

**Comment by number213** [comment]
@dsgouda Mikhail is on vacation
I've checked 2018-11-01 with ARM client, looks like Nirmal's change is correct

```
PS C:\Users\v-anevse> ARMClient.exe get /subscriptions/947d47b4-7883-4bb9-9d85-c5e8e2f572ce/providers/Microsoft.Network/applicationGatewayAvailableServerVariables?api-version=2018-11-01
[
  "request_query",
  "client_ip",
  "client_port",
  "client_user",
  "http_method",
  "request_uri",
  "http_version",
  "ciphers_used",
  "ssl_connection_protocol",
  "http_status",
  "request_scheme",
  "sent_bytes",
  "server_name",
  "server_port",
  "ciphers_supported",
  "client_tcp_rtt",
  "content_length",
  "content_type",
  "host",
  "ssl_enabled",
  "add_x_forwarded_for_proxy",
  "query_string",
  "received_bytes"
]
PS C:\Users\v-anevse> ARMClient.exe get /subscriptions/947d47b4-7883-4bb9-9d85-c5e8e2f572ce/providers/Microsoft.Network/applicationGatewayAvailableRequestHeaders?api-version=2018-11-01
[
  "A-IM",
  "Accept",
  "Accept-Charset",
  "Accept-Encoding",
  "Accept-Language",
  "Accept-Datetime",
  "Access-Control-Request-Method",
  "Access-Control-Request-Headers",
  "Authorization",
  "Cache-Control",
  "Connection",
  "Content-Length",
  "Content-MD5",
  "Content-Type",
  "Cookie",
  "Date",
  "Expect",
  "Forwarded",
  "From",
  "Host",
  "If-Match",
  "If-Modified-Since",
  "If-None-Match",
  "If-Range",
  "If-Unmodified-Since",
  "Max-Forwards",
  "Origin",
  "Pragma",
  "Proxy-Authorization",
  "Range",
  "Referer",
  "TE",
  "User-Agent",
  "Upgrade",
  "Via",
  "Warning",
  "X-Requested-With",
  "DNT",
  "X-Forwarded-For",
  "X-Forwarded-Host",
  "X-Forwarded-Proto",
  "Front-End-Https",
  "X-Http-Method-Override"
]
PS C:\Users\v-anevse> ARMClient.exe get /subscriptions/947d47b4-7883-4bb9-9d85-c5e8e2f572ce/providers/Microsoft.Network/applicationGatewayAvailableResponseHeaders?api-version=2018-11-01
[
  "Access-Control-Allow-Origin",
  "Access-Control-Allow-Credentials",
  "Access-Control-Expose-Headers",
  "Access-Control-Max-Age",
  "Access-Control-Allow-Methods",
  "Access-Control-Allow-Headers",
  "Accept-Patch",
  "Accept-Ranges",
  "Age",
  "Allow",
  "Alt-Svc",
  "Cache-Control",
  "Connection",
  "Content-Disposition",
  "Content-Encoding",
  "Content-Language",
  "Content-Length",
  "Content-Location",
  "Content-MD5",
  "Content-Range",
  "Content-Type",
  "Date",
  "Delta-Base",
  "ETag",
  "Expires",
  "IM",
  "Last-Modified",
  "Link",
  "Location",
  "P3P",
  "Pragma",
  "Proxy-Authenticate",
  "Public-Key-Pins",
  "Retry-After",
  "Server",
  "Set-Cookie",
  "Strict-Transport-Security",
  "Trailer",
  "Transfer-Encoding",
  "Tk",
  "Upgrade",
  "Vary",
  "Via",
  "Warning",
  "WWW-Authenticate",
  "X-Frame-Options",
  "Content-Security-Policy",
  "X-Content-Security-Policy",
  "X-WebKit-CSP",
  "X-Powered-By",
  "X-XSS-Protection"
]
```

**Comment by number213** [comment]
Resolved conflicts, @sergey-shandar please take a look

**Comment by sergey-shandar** [comment]
@number213 I would like to make sure that ARM team is aware about these changes.

**Comment by KrisBash** [comment]
> @number213 I would like to make sure that ARM team is aware about these changes.

Thanks. As this change is aligning client spec to current server behavior, no further concerns from ARM side.

**Pull request merged**
