### PR TITLE
Remove AzureDataLakeStoreCosmosStructuredStreamDataset since it's internal only

### PR DESCRIPTION
**Pull request by wuchunchunt19**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by wuchunchunt19** [comment]
Hi reviewer(s), this dataset model is accidentally added last time.  
It's actually internal only, and should not be exposed to external customers. External customers have no way to leverage it either, so it won't break anything if we roll it back now.
Thank your for your review :)

**Comment by anuchandy** [comment]
@wuchunchunt19 could you point to the PR in which this was introduced?

**Comment by wuchunchunt19** [comment]
@anuchandy , it's this one:
https://github.com/Azure/azure-rest-api-specs/pull/5218

**Comment by wuchunchunt19** [comment]
@anuchandy Could you please help review this change? Thanks!

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
