### PR TITLE
Ryanosh desktopvirtualization microsoft.desktop virtualization 2023 04 06 preview

### PR DESCRIPTION
**Pull request by ryanosh**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [X] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. 05/2023
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. 04/2023
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [X] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [X] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[X] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [X] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [X] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zizw123** [comment]
>           "201": {

x-ms-long-running-operation for 201?

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-04-06-preview/desktopvirtualization.json:2397 in c3df004. [](commit_id = c3df0044d5cbe7b7e1c9e98cf10ad1e91508b754, deletion_comment = False)

**Comment by ryanosh** [comment]
> > ```
> >       "201": {
> > ```
> 
> x-ms-long-running-operation for 201?
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-04-06-preview/desktopvirtualization.json:2397 in [c3df004](https://github.com/Azure/azure-rest-api-specs/commit/c3df0044d5cbe7b7e1c9e98cf10ad1e91508b754). [](commit_id = [c3df004](https://github.com/Azure/azure-rest-api-specs/commit/c3df0044d5cbe7b7e1c9e98cf10ad1e91508b754), deletion_comment = False)

This is not a long running operation, the 201 response is because it is required for a PUT

**Comment by ryanosh** [comment]
> > > ```
> > >       "201": {
> > > ```
> > 
> > 
> > x-ms-long-running-operation for 201?
> > Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-04-06-preview/desktopvirtualization.json:2397 in [c3df004](https://github.com/Azure/azure-rest-api-specs/commit/c3df0044d5cbe7b7e1c9e98cf10ad1e91508b754). [](commit_id = [c3df004](https://github.com/Azure/azure-rest-api-specs/commit/c3df0044d5cbe7b7e1c9e98cf10ad1e91508b754), deletion_comment = False)
> 
> Didn't finish going through the PR, think many of these are already captured in the lint error, please see if you can fix them and we can continue the review from there.

@zizw123 I resolved these errors. Of the remaining Lint and [staging] Lint, I am not sure which ones need to be resolved and which ones are warnings. Most of the errors are due to legacy behavior of our parameters.

**Comment by sjanamma** [comment]
Please fix all the Swagger LintDiff and Staging Swagger LintDiff errors. Please fix all the items under **[must fix]The following errors/warnings are introduced by current PR:** section

**Comment by ryanosh** [comment]
> Please fix all the Swagger LintDiff and Staging Swagger LintDiff errors. Please fix all the items under **[must fix]The following errors/warnings are introduced by current PR:** section

I have fixed all of the applicable errors. regarding the remaining LintDiff errors:

- ResourceNameRestriction, all of these errors refer to the 'hostPoolName' parameter which was previously existing and is in use by other resources. Chaning the parameter would break existing behavior
- ResourceMustReferenceCommonTypes, I emailed the ArmReviewers about this. Our resources reference the "Resource" common type, I am curious whether it is strictly necessary to reference the "ProxyResource" type instead
- GetCollectionOnlyHasValueAndNextLink, this validator is incorrect. The lines that are referenced are individual GET operations, not collection GET
- LROPostReturn,  I also emailed the armReviewers about this. We return 204 for these operations which is acceptable according to the async api reference. It seems to me that the validator is inaccurate
- LROPostFinalStateViaProperty, this validator calls for the operation to have final-state-via azure-async-operation, and directly conflicts with PostOperationAsyncResponseValidation which requires final-state-via location
-

**Comment by sjanamma** [comment]
>           "200": {

200 doesnt need to return async headers


---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-04-06-preview/desktopvirtualization.json:2882 in 730087c. [](commit_id = 730087ce33f8e035ec3594ce2e659142fce7dea4, deletion_comment = False)

**Pull request closed without merging**
