### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-02-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. 03/15 for all global regions, 03/18 for all sov clouds.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. 03/16
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
For the [error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1420256&view=logs&j=22cb5f76-5058-5a9d-2377-d04e5451a5f2&t=75f8d99b-764d-5b43-90d5-e9f774389f08&l=16) occurred in the Swagger Avocado check, it seems to be a new rule added recently. There is a [tag](https://github.com/Azure/azure-rest-api-specs/blob/dev-containerservice-Microsoft.ContainerService-2022-02-02-preview/specification/containerservice/resource-manager/readme.md#tag-package-2019-10-27-preview) for the swagger file (preview/2019-10-27-preview/openShiftManagedClusters.json) in readme.

**Comment by mentat9** [comment]
@FumingZhang - Please completely fill out the submission form, including Contribution Checklist and the entire ARM API Review Checklist section. Be sure to study the required materials and attest to that by checking the box. This is required for ARM review.

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ApiVersionParameter"

Recommend getting this from common-types v3/types.json. Same comment applies to other new APIs in this file.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2247 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/SubscriptionIdParameter"

Recommend getting this from common-types v3/types.json. Same comment applies to other new APIs in this file.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2250 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/CloudError"

Recommend using ErrorResponse from common-types v3/types.json if possible. Same comment applies to other new APIs in this file.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2263 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ResourceGroupNameParameter"

Recommend getting this from common-types v3/types.json. Same comment applies to other new APIs in this file.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2292 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "azureKeyVaultKms": {

Suggest azureKeyVault, leaving out acronym/abbreviation.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5763 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "enabled": {

ARM recommends string enum over boolean, ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review). Suggest activeState: { Enabled, Disabled } or similar.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5787 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/SystemData",

Recommend getting this from common-types v3/types.json.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5869 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/Resource"

Recommend using TrackedResource definition from common-types v3/types.json. If you use that definition, you will also get systemData automatically.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5881 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "managedClusterPropertiesReadOnly": {

managedClusterSnapshotDetails?

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5937 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "enableRbac": {

Recommend string enum, e.g. accessControl: { RoleBased, None }.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5957 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ResourceNameParameter"

resourceName is a very generic parameter name. Recommend using managedClusterSnapshotName or snapshotName. Same comment applies to other new APIs in this file as well.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2337 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by mentat9** [comment]
@FumingZhang - I reviewed your PR from ARM perspective and left some comments.

**Comment by FumingZhang** [comment]
Thanks for the review.
I've updated the following definitions in PR [#18206](https://github.com/Azure/azure-rest-api-specs/pull/18206).

- ApiVersionParameter
- SubscriptionIdParameter
- ResourceGroupNameParameter
- SystemData
- Resource

As for the suggestion about `CloudError`, if change it directly to `ErrorResponse `, it will introduce a breaking change (rename) in the definition, so a compromise solution is to just update the property definition in it, would this be acceptable?

**Comment by FumingZhang** [comment]
Hi @bingosummer, could you please help resolve the comments about kms?
> "azureKeyVaultKms": {
> "enabled": {

**Comment by FumingZhang** [comment]
Hi @zqingqing1, could you please help resolve the comments about mc snapshot?
> managedClusterPropertiesReadOnly
> enableRbac

**Comment by karataliu** [comment]
> > ```
> >     "azureKeyVaultKms": {
> > ```
> 
> Suggest azureKeyVault, leaving out acronym/abbreviation.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5763 in [38acb70](https://github.com/Azure/azure-rest-api-specs/commit/38acb700f6404444facbfec04d0dd850a00cd6e7). [](commit_id = [38acb70](https://github.com/Azure/azure-rest-api-specs/commit/38acb700f6404444facbfec04d0dd850a00cd6e7), deletion_comment = False)

Thanks we did evaluate this and discussed in our team API review meeting, we are trying to avoid acronym as possible.
Here the property stands for `key management system` using AzureKeyVault. And the property is under `securityProfile` property. We consider the term `Kms` has no ambiguity under that context.
See [project](https://github.com/Azure/kubernetes-kms)

**Comment by karataliu** [comment]
> > ```
> >     "enabled": {
> > ```
> 
> ARM recommends string enum over boolean, ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. Suggest activeState: { Enabled, Disabled } or similar.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5787 in [38acb70](https://github.com/Azure/azure-rest-api-specs/commit/38acb700f6404444facbfec04d0dd850a00cd6e7). [](commit_id = [38acb70](https://github.com/Azure/azure-rest-api-specs/commit/38acb700f6404444facbfec04d0dd850a00cd6e7), deletion_comment = False)

Thanks, this is to align with all other `enabled` property which already present in this API model. That property is designated to have true/false value only. And we prefer to keep the boolean type.

**Comment by mentat9** [comment]
@FumingZhang - Please work with this week's oncall (@raosuhas) to complete ARM review of your PR

**Comment by FumingZhang** [comment]
The following is the reply of the feature owner of `managedclustersnapshots` to the review comment
```
1. managedClusterPropertiesReadOnly, this is already defined in our data model, and couldn't be changed to "managedClusterSnapshotDetails"
2. "enableRbac" -> Recommend string enum, e.g. accessControl: { RoleBased, None }. This is the properties has been used for a while for mc.  don't want to re-define it
```

**Comment by FumingZhang** [comment]
@jianyexi could you please help trigger the pipelines again? It seems that they got stuck.

**Review by jianyexi — APPROVED** [review]

**Comment by raosuhas** [comment]
>             "$ref": "#/parameters/ResourceNameParameter"

Please fix 

---
In reply to: [1065786197](https://github.com/Azure/azure-rest-api-specs/pull/18150#issuecomment-1065786197) [](http://example.com/codeflow?ancestors=1065786197,1065786197)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2337 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by raosuhas** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedclustersnapshots/{resourceName}": {

As chris has pointed out can you please update these values from {resourcename} to an actual value like {managedclustersnapshotname}

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:2319 in 81c594c. [](commit_id = 81c594c727f41c49d0ecf730635f77eef2345956, deletion_comment = False)

**Comment by raosuhas** [comment]
>         "azureKeyVaultKms": {

As chris has suggested , can you please update this name ? the kms suffix is not descriptive enough and is confusing to read

---
In reply to: [1065786063](https://github.com/Azure/azure-rest-api-specs/pull/18150#issuecomment-1065786063) [](http://example.com/codeflow?ancestors=1065786063,1065786063)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-02-02-preview/managedClusters.json:5763 in 38acb70. [](commit_id = 38acb700f6404444facbfec04d0dd850a00cd6e7, deletion_comment = False)

**Comment by matthchr** [comment]
> As chris has suggested , can you please update this name ? the kms suffix is not descriptive enough and is confusing to read

Jumping in here (@karataliu feel free to chime in as well).

This field is _not_ a reference to a `keyVault`, at least not directly. It would be confusing to just say `keyVault` here because this is a reference to a KMS wrapper provided by Azure (that happens to use KeyVault). It is a reference to a specific open-source project called [Azure/kubernetes-kms](https://github.com/Azure/kubernetes-kms), which is itself an implementation of [Kubernetes KMS](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers).

We discussed expanding this fully internally but decided not to because _none of the open source projects to which we're referring do so either_. We wanted to be consistent with what the projects/solutions are actually called, and in the Kubernetes community they are called `kms` (unexpanded).

**Pull request merged**
