### PR TITLE
Adding examples for all operations.

### PR DESCRIPTION
**Pull request by manaas-microsoft**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by balajikris** [comment]
@manaas-microsoft - can you please describe the change? Is it all just adding examples or do you have changes to the actual spec as well? If you're updating the spec, please describe that change.

**Comment by manaas-microsoft** [comment]
@balajikris Hi, it is just adding the examples, and for that the x-ms-examples related line in the spec. No other updation. Just one more thing, the travis build has passed, but the semantic validation failed (https://api.travis-ci.org/jobs/248509808/log.txt?deansi=true) for the swagger. I am just debugging that. Will fix and add one more commit.

**Comment by balajikris** [comment]
_status:_ examples validation still fails and @manaas-microsoft is working on it.

**Comment by salameer** [comment]
@manaas-microsoft, can you please update on the status? 

We will have to close this PR due to inactivity unless you have an ETA for  i :)

**Comment by fearthecowboy** [comment]
ATTENTION REQUIRED.
-------------

We have changed the `default` branch in the `azure-rest-api-specs` repository to use the branch labeled `current`.

This PR is opened against the `master` branch.

You have two options: 
1. Keep this PR open, and complete the review process as normal, and once this PR is merged against the `master` branch, we (@olydis & @fearthecowboy)  will create a PR against the current branch and make any updates required to work in the newly reorganized default branch.  

2. Close this PR and create a new one. That would mean pulling in the changes from the new default branch `current` moving any files and switching to the configuration-based layout.  (You are more than welcome to choose option 2, but I don't expect anyone to do that)

Either way, the work you are currently doing against the previous default branch `master` will be the last PR against that branch that we will accept and all new PRs will go against the new default branch  `current`.

If you have any questions or concerns, ping @fearthecowboy or @olydis (or go ask on the `#swagger` channel in slack) ASAP and we can help you thru the process.

**Comment by manaas-microsoft** [comment]
@salameer @balajikris Have added all the examples(the missing response body for status code 200/204). It took sometime as the number of examples were more and for 200/204 the oav example generator needed some local changes :)

**Review by balajikris — APPROVED** [review]

**Comment by fearthecowboy** [comment]
Merging to `master` -- this should show up in `current` sometime tomorrow.

**Comment by balajikris** [comment]
thanks, both for merging and for porting over, @fearthecowboy

**Pull request merged**
