### PR TITLE
[Synapse] Update allowed range for nodeCount

### PR DESCRIPTION
**Pull request by idear1203**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

When auto-scale is enabled, minimum node count can be 0. This change aims to fix the issue.

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by idear1203** [comment]
@raych1 , the validation fails because we changed a constraint (Remove minimum/maximum setting for a parameter). The reason to change the constraint is that in some cases the parameter is not required and the current constraint is too strict and cause the operation failure. Now we remove the constraint, so I suppose from users' standing point, this change is actually not a breaking change.

**Comment by raych1** [comment]
@idear1203 , this api version is in preview for almost a year, is there any plan for GA?

**Comment by idear1203** [comment]
> @idear1203 , this api version is in preview for almost a year, is there any plan for GA?

Hi @raych1 , the Synapse service was just announced public preview in May this year. So the API and SDK are still in early stage.

**Review by pilor — APPROVED** [review]
:shipit:

**Comment by raych1** [comment]
@akning-ms , this is a preview version api change which removes the minimum/maximum constraints from a integer type of property. It will not impact the customer side and neither break current SDK. Please help force merge this PR, thanks.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
