### PR TITLE
[Microsoft.DevCenter] Add 2023-09-01-preview dataplane version

### LINKED ISSUE #25340: [DevCenter - Microsoft Dev Box] API Review
New API Review meeting has been requested.

**Service Name**: DevCenter - Microsoft Dev Box
**Review Created By**: Chris Miller
**Review Date**: 08/30/2023 09:00 AM PT
**Onboarding Record**: https://dev.azure.com/azure-sdk/Release/_workitems/edit/10882
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/25335
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: Adding a 2023-09-01-preview dataplane API for the DevCenter resource provider.

Relevant commits: https://github.com/Azure/azure-rest-api-specs/pull/25335/files/d2f98bb4fe2b15cf21009aa7ec2c25d71e8b7a6d..f1b886532a28aae136c7dafc9d20a0edf96967ac

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=bc0cb5a1-4d3c-ee11-bdf4-000d3a340e5b)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by chrissmiller**
# Data Plane API - Pull Request
Introducing a displayName property for project, pool, and environment type resources. This mirrors a change on our control plane spec, so that we can surface these properties on the dataplane and improve discoverability/interpretability of these resource types.

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:
- devbox.json: Pool displayName
- devcenter.json: Project displayName
- environments.json: EnvironmentType displayName 

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/25340

### CODE REVIEW

**Comment by chrissmiller** [comment]
**Breaking Change Alerts**:
-  Runtime exception is a known bug tracked by https://github.com/Azure/azure-sdk-tools/issues/6526
- AddedRequiredProperty alerts are due to required properties which were added on response-only models in our previous preview API (2023-07-01-preview). They are not new in this version.

**Comment by chrissmiller** [comment]
**Breaking Change Alerts**:
-  Runtime exception is a known bug tracked by https://github.com/Azure/azure-sdk-tools/issues/6526
- AddedRequiredProperty alerts are due to required properties which were added on response-only models in our previous preview API (2023-07-01-preview). They are not new in this version.

**Comment by weidongxu-microsoft** [comment]
We probably still need the context on `AddedRequiredProperty`. It is current preview api-version, so we may ignore the error. But when you move this preview to stable, that still a break from previous stable.

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #24291

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Approved. If no one have opinion in a few days, I will add the label and merge it.

**Comment by weidongxu-microsoft** [comment]
@chrissmiller 

I've merged the PR. I am not sure if meeting schedule would automatically be cancelled. Would you cancel it, if not cancelled automatically. So that the slot could be potentially used by other team.

**Pull request merged**
