### PR TITLE
Remove Cognitive Services Anomaly Detector Node.js package

### PR DESCRIPTION
**Pull request by kpajdzik**

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5530 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5530/commits/b6ca30d14bff638a0fefcda52e6d831af933255e

**Review by ghost — APPROVED** [review]

**Comment by kpajdzik** [comment]
@sarangan12, Could you investigate Ruby failures? Thanks!

**Comment by jhendrixMSFT** [comment]
@sarangan12 can you please take a look?

**Comment by kpajdzik** [comment]
@sarangan12 ping :)

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
