### PR TITLE
[HDInsight] Support encryption in transit feature:

### PR DESCRIPTION
**Pull request by aim-for-better**
Support encryption in transit feature: 
- Add a property when creating a cluster

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
Please go through the checklist added as part of the review and mark them completed.

**Comment by aim-for-better** [comment]
> Please go through the checklist added as part of the review and mark them completed.

Done

**Comment by chiragg4u** [comment]
As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

Also I see other issues with the swaggers
Item #1:  Version 2015-03-01-preview is over 12 months old.  It needs to be retired.  Please provide your plan to retire this API version.
Item #2: You have a “stable preview” – this is not allowed.  It’s either preview or GA.  Please provide your plan to correct this error.
Item #3: You do not have a GA released version of the API, yet your service is GA.  Please provide your plan to correct this.

**Comment by ravbhatnagar** [comment]
Removing the WaitForARMFeedback label. Adding new properties dont require ARM sign off going forward.

**Comment by aim-for-better** [comment]
> As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)
> 
> Also I see other issues with the swaggers
> Item #1: Version 2015-03-01-preview is over 12 months old. It needs to be retired. Please provide your plan to retire this API version.
> Item #2: You have a “stable preview” – this is not allowed. It’s either preview or GA. Please provide your plan to correct this error.
> Item #3: You do not have a GA released version of the API, yet your service is GA. Please provide your plan to correct this.

We have sent related email about this  breaking change to your team. @deshriva  will follow the issue you proposed.

**Comment by leni-msft** [comment]
@aim-for-better Although it's a preview version, but it's been over several years old. So it may break existing users. pls clarify if it's really necessary to introduce the breaking change.

**Comment by aim-for-better** [comment]
> @aim-for-better Although it's a preview version, but it's been over several years old. So it may break existing users. pls clarify if it's really necessary to introduce the breaking change.

There is no impact in customers, for create api: this property is optional, for get api, this property won't be returned if the cluster doesn't specify the property when creating cluster.

**Comment by aim-for-better** [comment]
> > @aim-for-better Although it's a preview version, but it's been over several years old. So it may break existing users. pls clarify if it's really necessary to introduce the breaking change.
> 
> There is no impact in customers, for create api: this property is optional, for get api, this property won't be returned if the cluster doesn't specify the property when creating cluster.

**Review by leniatgh — APPROVED** [review]

**Comment by akning-ms** [comment]
Hi @aim-for-better, Can you confirm it is stable version for Microsoft.HDInsight/stable/2018-06-01-preview? as it is in stable folder.
I remember we discussed this before. it will cause lots of confuse. you may need a plan to fix it. and also if it is a stable. it will be a breaking change which need API review board approval.

**Comment by aim-for-better** [comment]
> Hi @aim-for-better, Can you confirm it is stable version for Microsoft.HDInsight/stable/2018-06-01-preview? as it is in stable folder.
> I remember we discussed this before. it will cause lots of confuse. you may need a plan to fix it. and also if it is a stable. it will be a breaking change which need API review board approval.

Hi @akning-ms ,I have sent you an email about this. I am so sorry about the confusing api verison.

**Pull request merged**
