### PR TITLE
Add personalizer v1.1-preview.1 swagger for SDK 

### PR DESCRIPTION
**Pull request by ormichae**
1. Purpose of the update is to generate an SDK for a new Personalizer API version (v1.1preview.1)
2. Will be offered in public preview starting after Build
3.  We will publish the swagger before the build conference

### CODE REVIEW

**Review by sharathmalladi — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@PhoenixHe-msft I think the `ConstraintIsWeaker` failure is a false-positive.  I'm not sure who owns this tool, can you please route?

**Comment by PhoenixHe-msft** [comment]
@jianyexi to confirm the cross api breaking change result.

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE to confirm the cross api breaking change result.

This is allowed in new api version, please ignore it.

**Comment by jhendrixMSFT** [comment]
@jianyexi are you saying this isn't a false positive?  If so, can you please update the wiki with a description for this case as it's not clear why this specific change was flagged.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
