### PR TITLE
Per collection Swagger plus multiple changes to conform to fluent SDK conventions and bug fixes

### PR DESCRIPTION
**Pull request by naveedaz**
1. Add per collection API version support
2. Add per collection swagger file support
3. Order swagger definitions and paths
4. Add missing descriptions to models
5. Bug fixes:
   - https://github.com/Azure/azure-rest-api-specs/issues/431
   - https://github.com/Azure/azure-rest-api-specs/issues/432
   - https://github.com/Azure/azure-rest-api-specs/issues/433
   - https://github.com/Azure/azure-rest-api-specs/issues/434
   - https://github.com/Azure/azure-rest-api-specs/issues/435
   - https://github.com/Azure/azure-rest-api-specs/issues/436
   - https://github.com/Azure/azure-rest-api-specs/issues/443
   - https://github.com/Azure/azure-rest-api-specs/issues/473
   - https://github.com/Azure/azure-rest-api-specs/issues/474
   - https://github.com/Azure/azure-rest-api-specs/issues/475
### PR information
- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).
### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [x] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by tbombach** [comment]
General comment: in the future, could you add a Swashbuckle customization to remove `deprecated: false` (since it's the default)? I think omitting default values makes it easier for Swagger files to be consumed in general (even if it won't have a functional difference)

**Comment by tbombach** [comment]
In https://github.com/naveedaz/azure-rest-api-specs/blob/1e97be15076e600610d10be3ebb1d33f137b01d9/arm-web/2016-03-01/AppServiceCertificateOrders.json#L284:

Could you expand this description? I'm not sure what CSM stands for

**Comment by tbombach** [comment]
We're starting to ask for more descriptive/useful descriptions (e.g. https://github.com/naveedaz/azure-rest-api-specs/blob/1e97be15076e600610d10be3ebb1d33f137b01d9/arm-web/2016-03-01/AppServiceCertificateOrders.json#L333 could provide more information about the parameter). I think before we block your PR, I'd like to provide some slides from the documentation team that go into what they ask for. Let's plan on doing a doc quality pass in a future PR

**Comment by naveedaz** [comment]
Added an issue to track removal of sections that are repeated and have default values. https://github.com/Azure/azure-rest-api-specs/issues/601

**Comment by naveedaz** [comment]
@tbombach For Documentation, we have been trying to enlist help from technical writers to clean it up and make it useful and descriptive. However, those resources were pulled into different projects, once we have them back we can address documentation issues more thoroughly. In the meantime, please do fwd the slides.

**Comment by tbombach** [comment]
@naveedaz Re: documentation - yes, I definitely understand. I want to bring up these kinds of issues for awareness that we want to tackle them, but we'll focus on getting this PR merged based for the scope of the fixes you listed (I'm through about half of the files right now)

**Comment by tbombach** [comment]
In https://github.com/naveedaz/azure-rest-api-specs/blob/1e97be15076e600610d10be3ebb1d33f137b01d9/arm-web/2016-03-01/AppServiceCertificateOrders.json#L324, the ResourceGroupName parameter is defined each time it's used in an operation. You can define it in the global parameters section and use [x-ms-parameter-location: 'method'](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-parameter-location) so that it's a method parameter anywhere it's referenced, not a property on the service client

If you'd rather fix that in a future PR (if it's outside the scope for this one), please open an issue for tracking it. It's not something that would prevent me from merging this one, and it might take a fair amount of work to change it for all specs

**Comment by naveedaz** [comment]
Thanks @tbombach. This PR is kind of a big reset, so future PRs should be smaller and more contained.

**Comment by tbombach** [comment]
@naveedaz Is it helpful to include comments for these issues in this PR as I see them? I understand that the goal of this one isn't to fix all of these issues, so I'd like to provide this info to you in an easy way for you to consume for later PRs. I'd be happy to open issues myself if that saves you some time

**Pull request merged**
