### PR TITLE
EventGrid - Add api-version 2020-10-01-preview

### PR DESCRIPTION
**Pull request by batrived**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
>         "kubernetesBrokerArmId": {

Should this map to extendedLocation to simplify what is the target?

---
Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-10-01-preview/EventGrid.json:8358 in 8836e35. [](commit_id = 8836e350476af21786f51e8d1e02a113f3d9b94c, deletion_comment = False)

**Comment by batrived** [comment]
> > ```
> >     "kubernetesBrokerArmId": {
> > ```
> 
> Should this map to extendedLocation to simplify what is the target?
> 
> Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-10-01-preview/EventGrid.json:8358 in [8836e35](https://github.com/Azure/azure-rest-api-specs/commit/8836e350476af21786f51e8d1e02a113f3d9b94c). [](commit_id = [8836e35](https://github.com/Azure/azure-rest-api-specs/commit/8836e350476af21786f51e8d1e02a113f3d9b94c), deletion_comment = False)

We have designed it with 1:N mapping of CustomLocations to KubernetesBroker in mind. Although, customLocation is not needed in Topic when kubernetesBrokerArmId is present but CustomLocations team asked to put it here as well as ARM is going to do some validations based on the customLocation property on the resource.

**Comment by chiragg4u** [comment]
We discussed this scenario in the ARM API Review board and with ARC team and here is our recommendation
1. Microsoft.EventGrid/kubernetesBrokers should map to ARC Cluster Extension, which is being modeled to capture the extension configuration and shows up as an extended location. 
2. This will simplify your Topic/EventSubscription configuration as you don't need extra parameter like kubernetesBrokerArmId, as the extendedLocation property signifies the target for these objects.
Please note that this model allows multiple extensions can be modeled as part of the custom location, which allow customer to club multiple Azure services into one custom location.
Gaurav Bhatnagar is the next week oncall and will be sharing more details and provide more guidance.

**Comment by ravbhatnagar** [comment]
No activity for a long time. please re-add ARM feedback label if you need a review from ARM. removing to reduce noise.

**Pull request closed without merging**
