### PR TITLE
[Hub Generated] Review request for Microsoft.NotificationHubs to add version preview/2023-10-01-preview

### PR DESCRIPTION
**Pull request by jessHuh**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/jessHuh-notificationhubs-Microsoft.NotificationHubs-2023-10-01-preview-fcm...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by rkmanda** [comment]
>           "description": "Not used and deprecated since API version 2023-01-01-preview",

pl provide an explanation why this is being changed

---
Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2132 in 8a1deb5. [](commit_id = 8a1deb534e31ac60d5e60abb214ecea0de3fac30, deletion_comment = False)

**Comment by rkmanda** [comment]
>           }

should this be an enum?

---
Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2420 in 8a1deb5. [](commit_id = 8a1deb534e31ac60d5e60abb214ecea0de3fac30, deletion_comment = False)

**Comment by rkmanda** [comment]
>           },

should this be an enum?

---
Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2467 in 8a1deb5. [](commit_id = 8a1deb534e31ac60d5e60abb214ecea0de3fac30, deletion_comment = False)

**Comment by kmiecikt** [comment]
> > ```
> >       "description": "Not used and deprecated since API version 2023-01-01-preview",
> > ```
> 
> pl provide an explanation why this is being changed
> 
> Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2132 in [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30). [](commit_id = [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30), deletion_comment = False)

We changed the description already in the previous API version.
This input parameter was never recognized by our service, and was added back in 2017 by mistake. Because removing it would be a breaking change, and the previous API version had already too many changes, for now we just updated the description and we will start the formal ARM deprecation process in one of the new API versions.

**Comment by jessHuh** [comment]
> Please address or respond to feedback from the ARM API reviewer. When you are ready to continue the ARM API review, please remove the `ARMChangesRequested` label. This will notify the reviewer to have another look. If the feedback provided needs further discussion, please use this Teams channel to post your questions - [aka.ms/azsdk/support/specreview-channel](https://aka.ms/azsdk/support/specreview-channel). Please include `[ARM Query]` in the title of your question to indicate that it is ARM-related.

We are following Azure Monitor schema managed by Shoebox manifest team. 
https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=/src/Core/Provider/Shoebox/Manifest/schema.json&version=GBdev&line=202&lineEnd=203&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

```
 "supportedTimeGrainTypes": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "$comment": "Allowed time grain: 1 min, 5 min, 15 min, 30 min, 1 hour, 6 hour, 12 hour, 1 day"
              },
```

This is the Shoebox manifest team's schema which we need to apply: https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=%2Fsrc%2FCore%2FProvider%2FShoebox%2FManifest%2Fschema.json&version=GBdev&_a=contents
[schema.json - Repos (visualstudio.com)](https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=%2Fsrc%2FCore%2FProvider%2FShoebox%2FManifest%2Fschema.json&version=GBdev&_a=contents)

**Comment by jessHuh** [comment]
> > ```
> >       }
> > ```
> 
> should this be an enum?
> 
> Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2420 in [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30). [](commit_id = [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30), deletion_comment = False)

We are following Azure Monitor schema managed by Shoebox manifest team. 
https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=/src/Core/Provider/Shoebox/Manifest/schema.json&version=GBdev&line=433&lineEnd=434&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

```
"categoryGroups": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "$comment": "Log category groups(tags), such as default, all, security etc.,"
              }
```

This is the Shoebox manifest team's schema which we need to apply: https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=%2Fsrc%2FCore%2FProvider%2FShoebox%2FManifest%2Fschema.json&version=GBdev&_a=contents
[schema.json - Repos (visualstudio.com)](https://msazure.visualstudio.com/One/_git/AzureUX-Insights-MonRP?path=%2Fsrc%2FCore%2FProvider%2FShoebox%2FManifest%2Fschema.json&version=GBdev&_a=contents)

**Comment by zizw123** [comment]
>           "description": "Not used and deprecated since API version 2023-01-01-preview",

This is not being answered, also if the parameter is deprecated since 2023-09-01 do you still need it here?

---
In reply to: [1786284079](https://github.com/Azure/azure-rest-api-specs/pull/26443#issuecomment-1786284079) [](http://example.com/codeflow?ancestors=1786284079)

---
Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2132 in 8a1deb5. [](commit_id = 8a1deb534e31ac60d5e60abb214ecea0de3fac30, deletion_comment = False)

**Comment by zizw123** [comment]
> > > ```
> > >       "description": "Not used and deprecated since API version 2023-01-01-preview",
> > > ```
> > 
> > 
> > pl provide an explanation why this is being changed
> > Refers to: specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/preview/2023-10-01-preview/notificationhubs.json:2132 in [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30). [](commit_id = [8a1deb5](https://github.com/Azure/azure-rest-api-specs/commit/8a1deb534e31ac60d5e60abb214ecea0de3fac30), deletion_comment = False)
> 
> We changed the description already in the previous API version. This input parameter was never recognized by our service, and was added back in 2017 by mistake. Because removing it would be a breaking change, and the previous API version had already too many changes, for now we just updated the description and we will start the formal ARM deprecation process in one of the new API versions.

In theory this description will not need to be changed right? Why updating API version also requires changing when this was deprecated?

**Comment by zizw123** [comment]
non-blocking comment, sign off the PR, and you can fix the description if needed

**Review by raosuhas — APPROVED** [review]

**Pull request merged**
