### PR TITLE
[Hub Generated] Review request for Microsoft.AlertsManagement to add version stable/2019-03-01

### PR DESCRIPTION
**Pull request by assing**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/assing/azure-rest-api-specs/dev-alertsmanagement-Microsoft.AlertsManagement-2019-03-01...master).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by assing** [comment]
@ravbhatnagar Can you please review this PR?

**Comment by ravbhatnagar** [comment]
no major changes. This is moving from -preview to GA api version. Signing off from ARM side.

**Comment by assing** [comment]
@praries880 Can you please merge this PR?

**Comment by praries880** [comment]
@dsgouda can you take a look a the .net failure?

**Comment by dsgouda** [comment]
@praries880 This is an expected error, please disregard

**Review by praries880 — APPROVED** [review]

**Pull request merged**
