### PR TITLE
aesthetic changes

### PR DESCRIPTION
**Pull request by arolshan**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by yungezz** [comment]
Hi @arolshan Has the `2019-09-01-preview` service public? If yes, then changing paths is breaking change, pls do it in a new version. The change itself looks good.

**Comment by arolshan** [comment]
Hi,
How is this breaking change? Changing case does not affect path in any way. The old path and the new one are equivalent.
Best, Arik.

**Comment by arolshan** [comment]
Hi @Catherine Zhu<mailto:yungez@microsoft.com>,
Can you please clarify how is changing case, a breaking change? The old path and the new path are equivalent.
Please review again 😊?
Thanks, Arik.

**Comment by yungezz** [comment]
make sense.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
