### PR TITLE
Prepare folder split to add new RP under Microsoft.RedHatOpenshift namespace

### PR DESCRIPTION
**Pull request by petrkotas**
Move ARO to the subfolder to enable addition
of next rp.# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary>Click here to see the details of Step 1, Breaking Changes review</summary>

If you are in purview of Step 1 of the diagram, follow the [Breaking Changes review process].  
**IMPORTANT!** This applies even if you believe your PR was mislabeled, for any reason, including tool failure.
</details>

<details> 
<summary>Click here to see the details of Step 2, ARM review</summary>

See https://aka.ms/azsdk/pr-arm-review.
</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [x] Other, please clarify:
    - split the namespace folder in order to prepare the addition of the new RP under the same namespace
    - change is non breaking, only moving into subfolder

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[Breaking Changes review process]: https://aka.ms/brch

### CODE REVIEW

**Comment by msyyc** [comment]
Hi @petrkotas I am only Python SDK owner and I am OK for this change. For other review support, please seek help in [teams channel](https://teams.microsoft.com/l/channel/19%3a0351f5f9404446e4b4fd4eaf2c27448d%40thread.skype/API%2520Spec%2520Review?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by ramoka178** [comment]
Should the read me files be under RP folder instead of a subfolder ?

**Comment by ramoka178** [comment]
Could you check and fix the Typespec validation errors https://github.com/Azure/azure-rest-api-specs/pull/28599/checks?check_run_id=23483087627

**Comment by petrkotas** [comment]
Hi @ramoka178 I have checked them and cannot fix those. The errors are pointing out the openapi was not generated from typespec, which is correct. There openapi definitions belong to old service, which is not required to onboard typespec at this moment. We do plan to move though. We have item in the backlog for the migration to typespec. As I mentioned in my previous, comment these openapi files are not new, they are moved between folders.

**Comment by ramoka178** [comment]
> Hi @ramoka178 I have checked them and cannot fix those. The errors are pointing out the openapi was not generated from typespec, which is correct. There openapi definitions belong to old service, which is not required to onboard typespec at this moment. We do plan to move though. We have item in the backlog for the migration to typespec. As I mentioned in my previous, comment these openapi files are not new, they are moved between folders.

Could you add a suppression in that case ? Roopesh Manda, Evan Hissey are managing the suppression approval. They can be reached once the suppression is added 
https://eng.ms/docs/products/azure-developer-experience/design/specs-pr-guides/pr-suppressions#typespec-requirement-check

**Comment by petrkotas** [comment]
Hi @rkmanda or @MSEvanhi may I ask to help with accepting the suppression for typespec required on this PR? The ARO is a brownfield project that does not require typespec at this moment. We are aware of the future requirement and will move at some point. Thank you.

**Comment by TimLovellSmith** [comment]
I've marked this ARMSignedOff as I assume there's no real reason it requires ARM review - nothing changing except paths right? @petrkotas

**Comment by petrkotas** [comment]
This is correct @TimLovellSmith. We are making room for another RP under the same namespace. The files did not change in reality, only moved and updated relative path to common-types.

**Comment by konrad-jamrozik** [comment]
> Hi @TimLovellSmith may I ask you for help understanding the last event? I am confused as to why the label ArmSignedOff was removed from this PR, if I did not change. Thank you.

@petrokas sorry it was a tooling bug. I fixed it. Please follow:

- https://github.com/Azure/azure-rest-api-specs/pull/28599#issuecomment-2039484706
- [aka.ms/azsdk/specreview/merge](https://aka.ms/azsdk/specreview/merge)

**Review by madhura-np — APPROVED** [review]

**Comment by petrkotas** [comment]
Dear reviewer, is there anything I can do to help with merging? I see some checks are failing again, although they were passing just days ago. Like typespec Requirement, which I suppressed and it is now not working.

**Comment by mentat9** [comment]
@petrkotas - Please refresh to fix merge failures.

**Comment by petrkotas** [comment]
I have rebased but the error is persisting. I believe explicit approval must happen for typespec suppression.  I have reach out to Roopesh and Evan .

**Pull request merged**
