### PR TITLE
Update output-folders to generate in _generated.

### PR DESCRIPTION
**Pull request by tjprescott**
This change to the readmes will allow you to generate your _generated folder while leaving any custom written code in-place.

### CODE REVIEW

**Comment by daniel-rocha** [comment]
Hi @tjprescott I am fine with the change but the pipeline is failing to generate the SDK, is that ok?

**Review by daniel-rocha — APPROVED** [review]

**Comment by tjprescott** [comment]
Yeah, trying to get to the bottom of that one. It definitely does generate. I love CI...

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/21737

Per discussion with @msyyc, the `automation_generate.py` script is intended for management plane, and should not block the build or the PR. @lmazuel can you merge this?

**Comment by tjprescott** [comment]
I think this pipeline will pass once you have committed your first version of each SDK to the Python SDK repo.

**Pull request merged**
