### PR TITLE
Fix errors in ddosCustomPolicy.json

### PR DESCRIPTION
**Pull request by anton-evseev**
Porting https://github.com/Azure/azure-rest-api-specs/pull/5008 to Network's release branch

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
CI keeps failing with OutOfMemory error

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@sarangan12 Could you have a look lintdiff problem?

**Comment by number213** [comment]
@sergey-shandar @sarangan12 could you please take a look? We have other PRs blocked by this issue

**Comment by sergey-shandar** [comment]
@MikhailTryakhov could you review the PR please?

**Comment by MikhailTryakhov** [comment]
@sergey-shandar @number213  we don't need modifications for older api versions.. looks like changes merged are made for ```2018-11-01``` only, not for december? why?

**Pull request merged**
