### PR TITLE
Fixes for linting errors on gateway resources

### PR DESCRIPTION
**Pull request by yushwang**
(1) wrong resource name
(2) wrong resource reference in the reponse
(3) missing SubResource reference

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by veronicagg** [comment]
PR looks good. 
@sergey-shandar is looking into the CI issue with the PR, external to this change.
 I've labeled the PR with potential-SDK-breaking-changes, since the name change on the reference will cause that. 
If you need approval from ARM for a linter violation, please follow up with @ravbhatnagar .

**Comment by sergey-shandar** [comment]
CI is fixed, There are still some problems with examples.

**Comment by sergey-shandar** [comment]
@ravbhatnagar breaking changes in stable API. AFAIK, the old spec didn't properly describe the service API.

**Review by MikhailTryakhov — COMMENTED** [review]
Need approval from ARM side to have it merged

**Comment by dsgouda** [comment]
@sergey-shandar @veronicagg if the service was incorrectly described in the swagger, the service itself hasn't changed only the spec is being changed here. This will cause breaking changes to the generated sdks but that is acceptable if I am not wrong.
Do we still need @ravbhatnagar 's approval here?

**Comment by veronicagg** [comment]
@dsgouda since there were ARM violations @yushwang was already talking to @ravbhatnagar about them. If ARM team does not reply in the next 24 hours and owners of the PR want it to be merged anyway, you can merge without ARM's explicit approval.

**Comment by ravbhatnagar** [comment]
Looks good!

**Comment by MikhailTryakhov** [comment]
@dsgouda  approval received

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@dsgouda I think, we still need ARM approval. At least, ARM team is aware about these changes.

**Pull request merged**
