### PR TITLE
Fix ARMViolations for Microsoft.Solutions

### PR DESCRIPTION
**Pull request by zjpjack**
Fix ARMViolations for Microsoft.Solutions

### CODE REVIEW

**Comment by zjpjack** [comment]
@marstr Can you please take a look at this validation error? It is not related with my change. It seems that in the file, we have path "/{applianceId}" and "/{applianceDefinitionId}", and validation thinks they are the same path.

**Comment by marstr** [comment]
Seems like this must be a long-standing issue, as running a `git log` on this file only shows the activity of me creating it in December as part of a refactor. Because you're not introducing that error, I'm not going to block this PR on that failure.

**Review by marstr — APPROVED** [review]
In general, making properties optional after they're required can break what we code-gen. However, because this is in the `preview` folder, we do not block on breaking changes.

**Comment by marstr** [comment]
@sergey-shandar, is this a known issue?

**Comment by ravbhatnagar** [comment]
Signing off from ARM side.

**Comment by zjpjack** [comment]
@marstr Thanks, please merge this PR.

**Pull request merged**
