### PR TITLE
[DataFactory]Fix a typo for binary sink

### PR DESCRIPTION
**Pull request by TinaHu1**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by TinaHu1** [comment]
This should not be a risk change, test for SDK has already worked for "writeSetting", it is just a typo error, see the test payload in line 4112 of https://github.com/Azure/azure-sdk-for-net/blob/192d01dd78d4243ed0dbb097f59e444ff98604d6/sdk/datafactory/Microsoft.Azure.Management.DataFactory/tests/JsonSamples/PipelineJsonSamples.cs, the test has already passed.

**Comment by Juliehzl** [comment]
@NullMDR Do you know why CI hasn't been completed for a day?

**Comment by NullMDR** [comment]
Bug in CI. Waiting for engineering team to fix it.

**Comment by TinaHu1** [comment]
@NullMDR @Juliehzl Do you know what's the ETA of the fixing? Or re-create the pull request may solve this problem? I need to merge it by end of tomorrow, since we have an deadline for SDK/powershell release.

**Comment by NullMDR** [comment]
@yungezz CI actually passed and blocked by the known issue about sync. Please help to merge

**Comment by yungezz** [comment]
just to double confirm, @TinaHu1 is this PR to fix a bug in Swagger file, otherwise it will be a breaking change.

**Comment by TinaHu1** [comment]
@Juliehzl Could you help review this PR? Thanks a lot.

**Comment by TinaHu1** [comment]
> just to double confirm, @TinaHu1 is this PR to fix a bug in Swagger file, otherwise it will be a breaking change.

Yes, it is a bug fix.

**Comment by yungezz** [comment]
CI tasks passed in Azure Pipeline, detail pls see https://dev.azure.com/azure-sdk/public/_build/results?buildId=87546&view=results.

**Pull request merged**
