### PR TITLE
[Hub Generated] Review request for Microsoft.DesktopVirtualization to add version preview/2022-10-14-preview

### PR DESCRIPTION
**Pull request by alec-baird**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/alec-baird/azure-rest-api-specs/dev-desktopvirtualization-Microsoft.DesktopVirtualization-2022-10-14-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by visingla-ms** [comment]
>             "$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter"

Why some are using v1 common-types and others are using v3? All should be using v3 common-types. It's applicable for other newly added operations also.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:268 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           },

Put should also have 201 response for "Create" operation. 200 is for Update.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:429 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           },

Add 201 response also.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:3511 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             "$ref": "../../../../../common-types/resource-management/v2/privatelinks.json#/definitions/PrivateEndpointConnection"

Use v3 common-types here.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:3714 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             "$ref": "../../../../../common-types/resource-management/v2/privatelinks.json#/definitions/PrivateEndpointConnection"

Use v3 common-types here.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:4127 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/systemData"

Use v3 common-types here and below for all.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:6249 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "../../../../../common-types/resource-management/v1/types.json#/definitions/Resource"

Use v3 common-types here.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-10-14-preview/desktopvirtualization.json:6288 in 90693cf. [](commit_id = 90693cf59f7ec7267045c46b5272f0cd9b97fc5d, deletion_comment = False)

**Comment by visingla-ms** [comment]
Added some feedback comments. Please check. When you get Linter issues also fixed along with these, remove ARMChangesRequired label, for ARM API Reviewers to review the changes.

**Comment by alec-baird** [comment]
> Added some feedback comments. Please check. When you get Linter issues also fixed along with these, remove ARMChangesRequired label, for ARM API Reviewers to review the changes.

I was told by Xiaoxu Qi (the reviewer) and Jianye Xi to not implement the pattern changes to fix the linter errors and that they will approve merge with that error.

**Comment by alec-baird** [comment]
In response to the 201 responses, we received an explanation and exemption to not have 201 responses when we originally merged this in this PR: https://github.com/Azure/azure-rest-api-specs/pull/14258
Feel free to review it to read up on the discussion and problem discussed. :)

**Comment by alec-baird** [comment]
Changing some of the v2 to v3 caused breaking changes, so I was unable to change to the newest version.

**Comment by sjanamma** [comment]
> Changing some of the v2 to v3 caused breaking changes, so I was unable to change to the newest version.

can you please let us know what were those changes?

**Comment by alec-baird** [comment]
> > Changing some of the v2 to v3 caused breaking changes, so I was unable to change to the newest version.
> 
> can you please let us know what were those changes?

These 2 commits were the changes I had to make to avoid sdk errors:
https://github.com/Azure/azure-rest-api-specs/pull/21700/commits/7b6ec7bec1b5e3ea88742b535c64b0319369824b
https://github.com/Azure/azure-rest-api-specs/pull/21700/commits/d06673c869ed2657510c2bb83791f8c85d7909dc

**Review by sjanamma — APPROVED** [review]
Approved based on the comments provided by @alec-baird

**Comment by xiaoxuqi-ms** [comment]
Discussed with @jianyexi , it is OK to approve this Linter errors

**Comment by xiaoxuqi-ms** [comment]
@qiaozha and @ArcturusZhang , Could you help to review SDK breaking changes? Many thanks

**Review by ArcturusZhang — COMMENTED** [review]
A property `migrationRequest` is removed. We should go through breaking change review through this because it impacts all the SDKs.

**Comment by alec-baird** [comment]
> A property `migrationRequest` is removed. We should go through breaking change review through this because it impacts all the SDKs.

Do you have a moment to chat about this? basically we had the same sdk breaking change in our previous stable version that we made earlier in the year. This is the same breaking change as shown there, and it was approved. (shown here: https://github.com/Azure/azure-rest-api-specs/pull/20683 )

**Comment by ArcturusZhang** [comment]
> > A property `migrationRequest` is removed. We should go through breaking change review through this because it impacts all the SDKs.
> 
> Do you have a moment to chat about this? basically we had the same sdk breaking change in our previous stable version that we made earlier in the year. This is the same breaking change as shown there, and it was approved. (shown here: #20683 )

Thank you! I see it has been approved in this PR: https://github.com/Azure/azure-rest-api-specs/pull/20683
Then I am OK with it

**Pull request merged**
