### PR TITLE
Add enableTcpReset property to load balancer

### PR DESCRIPTION
**Pull request by dumahesh-msft**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by lmazuel — APPROVED** [review]
LGTM, but could you update one of the examples with this new field? Thanks,

**Comment by dumahesh-msft** [comment]
Updated examples with the new property.

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by ravbhatnagar** [comment]
Adding a settable property to existing stable API-version can result in unintentional behavior for the customers. Say this property was set using portal or template, and then someone using the older version of the SDK GETs the resource. This property will be ignored by the client since it did not understand it. Now the PUT comes on this resource which does not have this property in the request body. What happens to the state of this property on the server?

**Comment by lmazuel** [comment]
@ravbhatnagar This API is not in prod yet (note the base branch is a work-in-progress branch).
However, I remember seeing you discussing about boolean properties, it was mostly why I wanted to see what you think.

**Comment by dumahesh-msft** [comment]
@ravbhatnagar Like @lmazuel mentioned, this API is not prod yet. I'm adding a new property to the next API that will be published.

**Comment by ravbhatnagar** [comment]
Signing off! @dumahesh-msft - Bools are typicaly not recommended since they are not vry descriptive and does not allow for future expansion of states that can be supported. A string enum works better in most cases. Something for you to consider.

**Comment by dumahesh-msft** [comment]
Thanks @ravbhatnagar! Will definitely keep it in mind for the future.

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
