### PR TITLE
[Hub Generated] Review request: Enhanced A2ARecoveryPointDetails with "disks"

### PR DESCRIPTION
**Pull request by sriramvu**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/sriramvu/azure-rest-api-specs/dev-recoveryservicessiterecovery-Microsoft.RecoveryServices-2018-07-10).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by dsgouda** [comment]
@sriramvu Please join the Azure org on github [here](aka.ms/azuregithub)

**Comment by sriramvu** [comment]
> @sriramvu Please join the Azure org on github here



> @sriramvu Please join the Azure org on github here

Seems we are already part of Azure Org.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@veronicagg  where do we ask partners to sign the CLA.

**Comment by dsgouda** [comment]
@sriramvu please sign the CLA [here](https://cla.opensource.microsoft.com/Azure)

**Comment by sriramvu** [comment]
> @sriramvu please sign the CLA here

1) The given link erroring out with: _CLA assistant 404 FileNotFound_
2) This PR is an incremental change for https://github.com/Azure/azure-rest-api-specs/pull/5207 - why this explicit signing is required for this?

**Comment by veronicagg** [comment]
@sriramvu @dsgouda could you try closing/reopening the PR, to see if the CLA job restarts? I'm not sure why this has happened a few times. @sergey-shandar do you know why this is failing?

**Pull request merged**
