### PR TITLE
Dev storageimportexport microsoft.import export 2016 11 01

### PR DESCRIPTION
**Pull request by nivats**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by nivats** [comment]
I have added new version of api swagger along with examples and have reverted changes from swagger and examples of previous version of API

**Comment by ravbhatnagar** [comment]
Looks like this is dupe of https://github.com/Azure/azure-rest-api-specs/pull/10124 
@nivats please confirm.

**Comment by njuCZ** [comment]
@nivats could you please confirm this PR is still valid? If not, I am gonna close it.

**Comment by nivats** [comment]
Hi Gaurav,

I will close this PR as original PR has been merged and this stayed as duplicate it seems.

Thanks
Nishu Vats

**Pull request closed without merging**
