### PR TITLE
[Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-10-01

### PR DESCRIPTION
**Pull request by zachraMSFT**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/zachraMSFT/azure-rest-api-specs/dev-consumption-Microsoft.Consumption-2019-10-01-RI...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zachraMSFT** [comment]
The breaking changes represent a mistake in existing documentation, these properties were always required.

**Comment by leni-msft** [comment]
@zachraMSFT pls fix PrettierCheck error. Here's how: https://aka.ms/ci-fix

**Comment by zachraMSFT** [comment]
@leni-msft Updated to resolve the issue

**Comment by leni-msft** [comment]
@zachraMSFT Per newest process, since there is breaking change to stable version, please follow Azure Breaking changes approval request form as defined at [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by zachraMSFT** [comment]
There is no breaking change. The API has not changed, the documentation was incorrect, and following the old version exactly would always give an error.

**Comment by leni-msft** [comment]
@zachraMSFT please clarify the impact to customers if not modifying the swagger. And have you released any sdk for this version?

**Comment by zachraMSFT** [comment]
The impact to customers is that if they submit a request without these required parameters today, they will get a 400 response because the swagger was not properly generated for this documentation. No, we have not released an sdk.

**Pull request merged**
