### PR TITLE
Merge Network 2017-11-01 to master

### PR DESCRIPTION
**Pull request by chandrasekarsrinivasan**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@chandrasekarsrinivasan as far as I understood, the PR is a merge from `Network-2017-11-01` to 'master'. 
@mazuel could you check why Python CI is failing?

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by sergey-shandar** [comment]
@ravbhatnagar a new Network API version (2017-11-01).

**Review by marstr — CHANGES_REQUESTED** [review]
Over the holidays, we made some changes to this repository. One of which is requiring that each API Version be categorized explicitly as either `stable` or `preview`. To do this, the API Version folder must be placed in a folder corresponding to the names mentioned above.  You'll be able to see what I'm taking about here:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network

To read more about what happened over the holidays, please find our wiki page: https://github.com/Azure/azure-rest-api-specs/wiki/December-2017-Refactoring

Please move the files added in this PR to match the new format. Thanks!

edit: ordering

**Comment by chandrasekarsrinivasan** [comment]
@sergey-shandar Yes

**Comment by chandrasekarsrinivasan** [comment]
@marstr Moved files to stable folder

**Review by marstr — APPROVED** [review]
My approval speaks only to the location of these changes. The actual changes in this PR are still subject to the normal process and @sergey-shandar's judgement.

**Comment by chandrasekarsrinivasan** [comment]
@sergey-shandar Can you please help close on this?

**Comment by sergey-shandar** [comment]
@ravbhatnagar could you review the merge PR?

**Comment by lmazuel** [comment]
@lmazuel tag myself to get notifications (@sergey-shandar you made a typo ;))

**Comment by ravbhatnagar** [comment]
Reviewed this in person. The only feedback from ARM side was to make ipTagType property as an enum. It would improve the usability of the API and developers can deterministically code against it. Specially considering the case when new values will be supported by the service for this. Currently only 2 are supported but more will be supported in future. So it makes it hard for developers using the API know when new values get added or what new values are supported. 
Making it an enum helps in both the cases where the supported values in an api-version will be known. These dont have to searched in the documentation. And then when new values are supported, they get added to a new api-version again improving the usability. 
@chandrasekarsrinivasan is going to circle back with his team on whether they want to model this as an enum.

**Comment by chandrasekarsrinivasan** [comment]
@ravbhatnagar  - I had a discussion with my team members @avijitgupta  and @murilogr. The advantages of having an enum is that we will have better usability and the disadvantages is that we will have new API versions when we have changes to it. Then, we discussed and we see that we will have additions to this. Hence, we decided not to go with enum.

**Review by sergey-shandar — APPROVED** [review]
LGTM.

**Pull request merged**
