### PR TITLE
Revert node public ip support from 2019-04-01 model.

### PR DESCRIPTION
**Pull request by JunSun17**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by dsgouda — COMMENTED** [review]
This is a breaking change on a stable version. Were the SDKs published for this API version?

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6053 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6053/commits/ff48f1da36bc6e20487d8b9337d3fec6ca40d154

**Comment by JunSun17** [comment]
> This is a breaking change on a stable version. Were the SDKs published for this API version?

How can I check if the SDK has been published? If so, the intention here is still to push out this change and re-publish the SDK again.

**Comment by xizhamsft** [comment]
@dsgouda, I have not started the API release process yet.

**Review by dsgouda — APPROVED** [review]
LGTM. Approved since no SDKs have been published yet

**Comment by veronicagg** [comment]
I just checked the SDKs and couldn't find the property that was reverted in this PR in them, so should not cause issues on the SDKs.

**Pull request merged**
