### PR TITLE
Peering api 2021-06-01

### PR DESCRIPTION
**Pull request by renuka-raju**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. **_Upcoming Release_**
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
Please ensure you've reviewed following guidelines including ARM resource provider contract and REST guidelines. Estimated time (4 hours). This is required before you can request review from ARM API Review board.

**Comment by chiragg4u** [comment]
Thanks for copying older version in the first commit, It helped me review the changes efficiently. I reviewed the changes. Changes looks good, marking ARM_Signedoff.

**Comment by uslava77** [comment]
[Open API Hub comparison with 2021-01-01 peering.json](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYXN0ZXIvc3BlY2lmaWNhdGlvbi9wZWVyaW5nL3Jlc291cmNlLW1hbmFnZXIvTWljcm9zb2Z0LlBlZXJpbmcvc3RhYmxlLzIwMjEtMDEtMDEvcGVlcmluZy5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL3JlbnVrYS1yYWp1L2F6dXJlLXJlc3QtYXBpLXNwZWNzL2Jsb2IvcGVlcmluZ0FQSS0yMDIxLTA2LTAxL3NwZWNpZmljYXRpb24vcGVlcmluZy9yZXNvdXJjZS1tYW5hZ2VyL01pY3Jvc29mdC5QZWVyaW5nL3N0YWJsZS8yMDIxLTA2LTAxL3BlZXJpbmcuanNvbiJ9)

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Approving for changes in `readme.go.md`

**Comment by akning-ms** [comment]
There is few Linter error about system data. do you have plan to support system data?

**Comment by uslava77** [comment]
Hi @akning-ms , thanks for your review, the CheckServiceProviderAvailability was changed back so it is not a breaking change. We do not plan to support systemData for this API version, but we will plan for future API. @renuka-raju will reply with justification for the other breaking changes.

**Comment by uslava77** [comment]
Correction: path CheckServiceProviderAvailability rename to checkServiceProviderAvailability is required, as it is s360 linting violation

**Comment by uslava77** [comment]
Hi @akning-ms , for each breaking change here are the relevant s360 items:
[Linter Error R3021](https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=1B3CF2E5-668F-4D9C-938B-4FB8E4667F63)  
[ROUNDTRIP_ADDITIONAL_PROPERTY](https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=22BF6EE2-EF0A-46B2-AEDF-36565E705BE4) 
[ROUNDTRIP_INCONSISTENT_PROPERTY](https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=639A5B31-6B31-47F4-9F83-1A781B05367F) 
Expected impact is minimal on end-user experience (ReadOnly changes with no impact, and camel-case change for checkServiceProviderAvailability used mostly by internal code on Portal side).

**Pull request merged**
