### PR TITLE
Updated Description for the DiffDiskPlacement property.

### PR DESCRIPTION
**Pull request by hari-bodicherla**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by hari-bodicherla** [comment]
Hi, Added few minor documentation changes that are missing for the DiffDiskPlacement from the PR
https://github.com/Azure/azure-rest-api-specs/pull/8847

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
hi @hari-bodicherla is the PR ready to merge?

**Comment by hari-bodicherla** [comment]
@yungezz I was waiting for resolving comments from Sameer. I just resolved the comments. please merge this PR if needed.

**Comment by hari-bodicherla** [comment]
@yungezz , I got few more comments to resolve. I will let you know once it is ready to merge. Thanks.

**Comment by hari-bodicherla** [comment]
@smotwani , Updated the Swagger. Please have a look . Thanks

**Review by smotwani — APPROVED** [review]

**Comment by hari-bodicherla** [comment]
@yungezz . I just got approval from the reviewers. please merge this PR if you dont have any comments to add. Thanks

**Pull request merged**
