### PR TITLE
ARM-HDInsight composite specs with examples.

### PR DESCRIPTION
**Pull request by pulkittomar**
Changes do not include:
1. null specification for each data member. Some members may support
nulls, but as per spec we haven't validated those.
2. Data format validation. We have to validate that all date strings
follow the pattern as expected. Current date format patterns fail to
validate dates in hdinsight api response, so we have removed the date
check for now.
3. We have added readonly to most properties, but we need to validate
those properties again.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sarangan12** [comment]
Review in progress. I will provide the updates soon.

**Comment by sarangan12** [comment]
Please fix the errors reported here. 

[PR1076_Errors.txt](https://github.com/Azure/azure-rest-api-specs/files/891612/PR1076_Errors.txt)

**Comment by pulkittomar** [comment]
@sarangan12 I have fixed some of the errors. For rest of the errors we will need an exception.

**Comment by sarangan12** [comment]
@pulkittomar 

Please send a mail to Gaurav & Samer requesting exception. Please list the issues for which you need exception with reasoning.

**Comment by sarangan12** [comment]
Clearning the assignee to be reassigned

**Comment by matt1883** [comment]
@pulkittomar no longer needs an exception for the capitalization changes, I believe. He made changes to address the related errors earlier today.

@sarangan12 Are there any other changes that need to be made to this PR that _do not_ require changes to the service's REST API?

**Pull request closed without merging**
