### PR TITLE
Adding requirement that localNetworkGatewayName have at least one cha…

### PR DESCRIPTION
**Pull request by marstr**
…racter.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
This PR is to address issue Azure/azure-sdk-for-go#576. [The relevant Swagger Spec Section is 5.2.2](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.2).

**Comment by jhendrixMSFT** [comment]
@Nilambari do you have any comments?  Also is there a max length that should be added?

**Comment by marstr** [comment]
Ping @Nilambari

**Review by Nilambari — APPROVED** [review]
LGTM.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
