### PR TITLE
tooling: removing the auto-close bot

### LINKED ISSUE #19098: Remove the auto-close PR bot
Whilst I can understand the desire to close stale PR’s, unfortunately that Service Teams aren’t actively reviewing PR’s leads to a pretty hostile contribution experience with the auto-close bot.

A few examples:

* https://github.com/Azure/azure-rest-api-specs/pull/17987#issuecomment-1066131357
* https://github.com/Azure/azure-rest-api-specs/pull/18269#issuecomment-1086897732
* https://github.com/Azure/azure-rest-api-specs/pull/18232#issuecomment-1086897773

I’d suggest removing the auto-close PR bot, since it’s pretty user-hostile - or at least providing an external means of escalating PR’s if the Service Teams don’t have time to review them.

Two of the three examples above could be repro’d by using the API, so I’m not sure why the Service Team needs to be involved specifically there?

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This commit fixes #19098 by removing the auto-close bot.

Whilst I can understand that Service Teams maybe unable to review all Pull Requests in a timely manner, unfortunately I've had a number of Pull Requests at this point which end up with me posting every 2 weeks to keep the Pull Request open:

* https://github.com/Azure/azure-rest-api-specs/pull/17987#issuecomment-1066131357
* https://github.com/Azure/azure-rest-api-specs/pull/18269#issuecomment-1086897732
* https://github.com/Azure/azure-rest-api-specs/pull/20961#issuecomment-1312764448
* https://github.com/Azure/azure-rest-api-specs/pull/21291#issuecomment-1312764141

Whilst this does mean there'll be more Pull Requests open until the Service Team can take a look at them - removing this user hostile bot improves the contribution experience.

### CODE REVIEW

**Comment by ruowan** [comment]
Hi, @tombuildsstuff Thanks for your contribution.  Are you from azure or open source community?  This changes may have some impact on our review process. Could you help to show more background here?

**Comment by tombuildsstuff** [comment]
@ruowan perhaps the bot could be updated to ping the Service Team every 2 weeks instead, or a label as you've suggested to allow a team to manually work through the list and ping the teams through another channel (to do the same thing) - rather than trying to close the PR?

To be honest I don't think there should be a difference between internal and external PR's here, else it's easy for the external ones to get ignored with a separate process? Ultimately we're all working towards the same goal of trying to ensure the Swagger data is correct so that folks can make use of it/the services :)

**Comment by ruowan** [comment]
I helped ping service team on teams channel.  We will sync up with our PR assignee to know and help route such customer contributed PR.

**Comment by akning-ms** [comment]
Based on Ruoxuan's comment, Should we close this PR. @tombuildsstuff

**Comment by tombuildsstuff** [comment]
@akning-ms 

> Based on Ruoxuan's comment, Should we close this PR. @tombuildsstuff

Whilst I appreciate that @ruowan has been running a few of the PR's down, unfortunately this PR is still necessary since the auto-close bot is causing significant amount of work for third-party contributors, for example:

Screenshot 2022-12-09 at 09 06 01

Screenshot 2022-12-09 at 09 06 17

As such, what's needed to merge this PR?

**Comment by ruowan** [comment]
@tombuildsstuff I created an alternative PR. With this change, our bot will not mark the customer-reported PR as stale.

**Comment by akning-ms** [comment]
Hi @tombuildsstuff, Since Ruoxuan have new PR to fix your issue in PR#21837,  can you confirm & close this PR ?

**Comment by ruowan** [comment]
@tombuildsstuff I have applied fix. Bot will check whether the PR has customer-reported label. And for customer-reported PRs, our bot won't close them.

**Comment by akning-ms** [comment]
> @tombuildsstuff I have applied fix. Bot will check whether the PR has customer-reported label. And for customer-reported PRs, our bot won't close them.

And will also not give any comment to reminder any more for new or old PR as above screenshot Tom pasted in above, right?

**Comment by tombuildsstuff** [comment]
@ruowan I've seen a number of fixes closed over the years from both external contributors and Microsoft employees from this - so unfortunately this also affects PR's without the `customer-reported` label, so I think that needs to be taken into account too?

**Comment by akning-ms** [comment]
> @ruowan I've seen a number of fixes closed over the years from both external contributors and Microsoft employees from this - so unfortunately this also affects PR's without the `customer-reported` label, so I think that needs to be taken into account too?

Hi @tombuildsstuff, this is by design to improve review efficiency as PR assignee have to spend some time monitor these inactive PRs. for PR author, it is also easy to reopen it if the PR is still need.  but you are right, this may not fit for the PRs(customer-reported), that is why Ruoxuan changed the bot setting to ignore this kind of PRs.

**Comment by akning-ms** [comment]
Hi @tombuildsstuff, I am closing it for now as not get your further response, pls free to reopen if need.

**Comment by tombuildsstuff** [comment]
@akning-ms @ruowan here's 3 more PRs, this time from Microsoft employees that are valid and fix real issues in the API (by updating the Swagger to reflect the API behaviour) that have been closed by the bot as the Service Team hasn't responded within the SLA:

https://github.com/Azure/azure-rest-api-specs/pull/27524
https://github.com/Azure/azure-rest-api-specs/pull/25435
https://github.com/Azure/azure-rest-api-specs/pull/25142

Whilst I agree with you that the underlying issue here is that Service Team should be more responsive so these don't get auto-closed - they're not - so removing this behaviour would be a significant quality of life improvement versus just closing these out.

I can see that this behaviour now lives in another file, so if it's helpful I'm happy to open a new PR to fix that - but can you confirm when this problematic behaviour will be removed?

Thanks!

**Pull request closed without merging**
