### PR TITLE
S360

### PR DESCRIPTION
**Pull request by LeoVannelli**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
@LeoVannelli Your PR needs Breaking Change Review.

**Comment by LeoVannelli** [comment]
I have finished reviewing the changes and requested s360 exceptions for those issues that remain. Those changes that can be made should be done now. Per the discussion during the breaking change discussions to bundle all the breaking changes in one request this has all those I could identify. This should be the final change for review.

I am requesting help completing this PR getting signoff on the remaining breaking issues that appear to be due to the tools flagging incorrectly. It also appears that the checks are blocked on linting tests failing to run.

**Comment by akning-ms** [comment]
@jianyexi or @zhenglaizhang for help on Linter issue

**Comment by jianyexi** [comment]
@LeoVannelli  Because of the limit of the max size of one github comment , the lint diff  result did not show normally . According to the CI log , the following are linting errors that needs to fix:
R3023 - OperationsAPIImplementation
Operations API must be implemented for '/providers/Microsoft.Insights/operations'.
  at specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/subscriptionDiagnosticsSettings_API.json:38

R3023 - OperationsAPIImplementation
Operations API must be implemented for '/providers/Microsoft.Insights/operations'.
  at specification/monitor/resource-manager/Microsoft.Insights/stable/2014-04-01/autoscale_API.json:38

R4007 - DefaultErrorResponseSchema
the default error response schema does not correspond to the schema documented at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content.
  at specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/activityLogs_API.json:65

R4007 - DefaultErrorResponseSchema
the default error response schema does not correspond to the schema documented at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content.
  at specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/activityLogs_API.json:65

R4007 - DefaultErrorResponseSchema
the default error response schema does not correspond to the schema documented at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content.
  at specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/activityLogs_API.json:65

R4007 - DefaultErrorResponseSchema
the default error response schema does not correspond to the schema documented at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content.
  at specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/activityLogs_API.json:65

R4007 - DefaultErrorResponseSchema
the default error response schema does not correspond to the schema documented at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content.

**Comment by LeoVannelli** [comment]
The lint errors appear to be an issue, the r4007 errors require exceptions since making the change would break the existing customers. The R3023 errors are also false since we do not have operations api specific for those versions. We don't have every api at every version, we have only revered versions of an api when it changes.

**Comment by LeoVannelli** [comment]
I looked at these errors and they do not look fixable.

Errors:
R3023 - OperationsAPIImplementation

We don't have implementations of the operations api for every api version. We only rev the api versions when the contracts changed. Due to the nature of the Microsoft.Insights namespace it is not possible to have all api's updated when a version updates.

R4007 - DefaultErrorResponseSchema

This error is a breaking change for us, if we make it we also have to change the server side to conform. It also breaks existing customers. We are still using the V1 contracts for all legacy api's not v2. I have requested exceptions for these in s360.

Who can help us with this? To get it thru.

Once this is done can we also get help with getting it committed since we do not have permission to.

**Comment by akning-ms** [comment]
@LeoVannelli, for OperationsAPIImplementation failure. you can refer to other tag in readme to add below
- Microsoft.Insights/stable/2015-04-01/operations_API.json

I will approve the Linter rule for R4007. 

@leni-msft to help confirm autorest.schema failure

**Review by leniatgh — APPROVED** [review]

**Pull request merged**
