### PR TITLE
[Hub Generated] Review request for Microsoft.SqlVirtualMachine to add version preview/2017-03-01-preview

### PR DESCRIPTION
**Pull request by yareyes**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/yareyes/azure-rest-api-specs/yadi-updateswagger...master/:tab?).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by yareyes** [comment]
@sarangan12 One of the checks is failing because it does not recognize words from different swaggers - and the word BYOL from our CLI. This is an expected acronym, BYOL (Bring your own license). 

Could you help us merging this code to start the publishing process from openApiHub?

**Review by sarangan12 — APPROVED** [review]

**Comment by sarangan12** [comment]
@yareyes I am fine with the changes. But please be aware that these are breaking changes and thus needs an ARM review. Added the label for that.

**Comment by sanjaiganesh** [comment]
The only property that is changed is sqlImageSku, which is now made 'writable'. 
As it is not a required property, this should be fine. Not a breaking change.

**Comment by yareyes** [comment]
@sarangan12 could we please merge this PR?

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
