### PR TITLE
Remove Interface Endpoint from released API versions

### PR DESCRIPTION
**Pull request by rupalivohra**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by dsgouda** [comment]
@MikhailTryakhov PTAL I don't think we can deprecate/discontinue services altogether

**Comment by rupalivohra** [comment]
InterfaceEndpoints is being renamed. It has only been in private preview so far.
We have already had this approved by ARM (forwarding the email chain to you, Deepak).

**Comment by dsgouda** [comment]
@veronicagg looks like the builds are failing for code generation and since this is a resource renaming, it might require some additional work at the SDKs end.
Could you please tag the SDK owners so that they can take a look.

**Comment by veronicagg** [comment]
@jhendrixMSFT @lmazuel @sarangan12 @daschult @jianghaolu this PR is removing a file, which will get renamed. Even though the spec was in "stable", the author of this PR is indicating the service was in private preview. SDK generation is failing for some of the languages, could you take a look? Thanks!

**Comment by KrisBash** [comment]
These APIs need to follow standard deprecation policy, as they are publicly available and in stable API versions. .

**Comment by rupalivohra** [comment]
@KrisBash - we've discussed this via email already. Although it's in the stable branch, these resources have only been used in private preview features.

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
hi @rupalivohra 
there is no need to make changes in older api versions (like ```2018-08-01```, ```2018-09``` etc) 
currently we're working on ```2018-12-01``` version. but unfortunately it's already published and we can accept only additive changes for this month branch. we're still waiting for newer API because of NRP release delays, so to add breaking changes we need to wait for a newer version next month :( 

Also not quite sure why do we remove this feature? Won't it break one of KPIs (like swagger completeness)

**Comment by jianghaolu** [comment]
@veronicagg Thanks Veronica for looping me in. This change is OK for Java.

**Comment by MikhailTryakhov** [comment]
@rupalivohra  @KrisBash  please figure out were ARM changes requested or not? without progress here we'll have to close this PR and publish swagger without presented changes

**Comment by MikhailTryakhov** [comment]
branch is closed, closing PR. please retarget on newer monthly branch when it's ready

**Comment by salameer** [comment]
@rupalivohra please link the retargeted PR

**Pull request closed without merging**
