### PR TITLE
chore: Remove FrontDoor non-autorest READMEs

### PR DESCRIPTION
**Pull request by nschonni**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by zikalino** [comment]
@nschonni network related prs shouldn't be done against master, instead pls use one of the network release branches

**Comment by nschonni** [comment]
Looking at the history on the folder I don't think these usually go into those branches https://github.com/Azure/azure-rest-api-specs/commits/master/specification/frontdoor/resource-manager since it's not under specification/network/

**Comment by zikalino** [comment]
@nschonni sorry, my mistake!

**Comment by nschonni** [comment]
No worries, it's not really obvious to me with network does that either

**Comment by yungezz** [comment]
Hi @zikalino @nschonni any update on this PR?

**Comment by nschonni** [comment]
No, I think the bot didn't assign a reviewer to this PR

**Comment by nschonni** [comment]
Reopening to see if the bot will assign a reviewer

**Comment by yungezz** [comment]
I dont think those file should be deleted. those files contain useful information to users. Does the name `readme.md` cause a problem to autorest? if yes, just renaming it.

**Review by yungezz — CHANGES_REQUESTED** [review]
as commented.

**Comment by nschonni** [comment]
> those files contain useful information to users

These don't get exposed to users, if that's the target audience, then https://github.com/MicrosoftDocs/azure-docs/tree/master/articles/frontdoor would probably be a better place

> Does the name `readme.md` cause a problem to autorest? if yes, just renaming it

Yes, they trigger Avocado checks

**Pull request closed without merging**
