### PR TITLE
Update RecoveryServices MD file

### PR DESCRIPTION
**Pull request by lmazuel**
@olydis @fearthecowboy 

I work on the integration of MD files in my CI system and RecoveryServicesBackup has one (thanks @DheerendraRathor). This PR contains some update I think are interesting to update files, and maybe to use a convention for future files:

- Prefix the language specific "output-folder" by root "output-folder", in order to be able to change the root folder of generation. Note that I don't separe them with a "/" on purpose, so without root "output-folder" this is doing the same thing that right now.
- In Python "package-name" should only be used on creation. For update it should not been used. So I make it conditional.

If you think this is interesting, we might update a pattern file for future people no? What do you think?

Thanks!

Laurent

### CODE REVIEW

**Comment by DheerendraRathor** [comment]
LGTM 👍

**Comment by balajikris** [comment]
all validation checks passed, from my end - a 👍

**Review by DheerendraRathor — APPROVED** [review]

**Comment by fearthecowboy** [comment]
@lmazuel I'm good with this; 

We've got configuration files for everything in the reorg branch, we'll have to make sure these settings get placed in those files.

**Review by balajikris — APPROVED** [review]

**Comment by balajikris** [comment]
@lmazuel -- shall i go ahead and merge this or are we waiting for something?

**Comment by salameer** [comment]
Hi @balajikris,

I believe you can go ahead and merge

**Comment by lmazuel** [comment]
Just for closure, sorry @balajikris I missed your message :/. Thanks for the merge!

**Pull request merged**
