### PR TITLE
added links for application gateway limits

### PR DESCRIPTION
**Pull request by tfitzmac**
Added links to Application Gateway limits for property descriptions

### CODE REVIEW

**Comment by dsgouda** [comment]
@MikhailTryakhov is the january release already merged?

**Comment by dsgouda** [comment]
@number213  @MikhailTryakhov should this be included in the January release

**Comment by number213** [comment]
@dsgouda release has been merged into master today, I think it's okay to retarget this PR to master and merge it

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by tfitzmac** [comment]
Is it preferable for me to change the target branch, or resubmit as new PR on master?

**Comment by dsgouda** [comment]
I can retarget the PR, that would be easier

**Comment by dsgouda** [comment]
Retargeting caused a large number of merge conflicts, @tfitzmac it would make sense to just open a new PR at this point, please make sure you target master with it.

**Pull request closed without merging**
