### PR TITLE
added suppressions

### PR DESCRIPTION
**Pull request by gatneil**

### CODE REVIEW

**Comment by gatneil** [comment]
@salameer I took a shot at suppressing the linter validations we discussed, but I believe I'm doing it wrong. Based on the examples [here](https://github.com/Azure/autorest/tree/97b68250afd96111f79047e24e22eeb82a30426f/src/autorest-core/test/variations/suppressions#suppressions) of using $..path["..."], I tried using $..definitions["..."]["..."], which I'm not sure is supposed to work. But then again, the number of errors did go down (albeit by much fewer than the number of suppressions I added). Is this a valid way to suppress? Also, I tried looking through the travis CI build logs, but I couldn't find the list of errors the linter is still reporting. How can I see the list to confirm that the validations are being suppressed properly?

**Comment by jhendrixMSFT** [comment]
@gatneil So the linter and modeler results are both green in CI so it seems to me that the correct thing is happening.  Are you talking about the number of errors reported by the bot and pasted in this issue?

**Comment by gatneil** [comment]
@jhendrixMSFT yup! It looks like the number of errors went down from 39 to 33, but I was expecting the suppressions to reduce the errors even more...is there a way to see which errors the linter is still finding? (ideally in the build logs or some other way that doesn't involve installing VS Code - I do my edits from a headless linux machine...)

**Comment by jhendrixMSFT** [comment]
@amarzavery I'm told you understand this azure bot.  Does it not honor suppressions?

**Comment by jhendrixMSFT** [comment]
@gatneil OK after an offline discussion with the AutoRest folks the format of the suppressions was incorrect.  I believe I have this fixed now and am waiting for CI.

**Comment by gatneil** [comment]
17 suppressions, 17 fewer errors! Love it :). Thanks for the help! #sign-off

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
