### PR TITLE
Adding Azure Media Services version 2018-06-01-preview version

### PR DESCRIPTION
**Pull request by quintinb**
Changes from the 2018-03-30-preview version include:

1. Add AlternativeMediaId to StreamingLocator and to the LiveEvent preview.
2. Add CorrelationData to the Job entity to allow customers to supply data that will be echoed in the forthcoming JobCompletedEvent.
3. Change Type of ContentKeys in StreamingLocatorProperty from StreamingLocatorUserDefinedContentKey to StreamingLocatorContentKey.  This allows the ContentKeyId information to be available when a user creates a StreamingLocator even for ContentKeys created by MediaServices.
4. Rename CustomLicenseAcquisitionUrlTemplate to CustomKeyAcquisitionUrlTemplate for EnvelopeEncryption.

### CODE REVIEW

**Review by marstr — APPROVED** [review]
When comparing the two API Versions, there aren't many changes. Nothing jumped out as troublesome.

**Comment by ravbhatnagar** [comment]
Signing off from ARM

**Comment by marstr** [comment]
@quintinb, are these changes publicly available and ready for me to merge?

**Comment by marstr** [comment]
Ping @quintinb

**Comment by marstr** [comment]
Closing as stale. Ping this thread if it should be re-opened or submit a new PR.

**Comment by quintinb** [comment]
Can this be merged now please?

**Pull request merged**
