### PR TITLE
[iothub] add 200 to responses of IoT Hub create/update API

### PR DESCRIPTION
**Pull request by xscript**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [x] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.
IoT Hub create/update API is a long running operation.
When using generated Python SDK to create IoT Hub, 200 will be returned
when quering operation results. Then error will be thrown because 200 is
not a valid response. This commit is intended to fix this issue.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/657)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@xscript__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kevinzha). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by xscript** [comment]
CI failed due to connection timeout when downloading latest AutoRest (see below snapshot).
Could anyone with write access to trigger the build again? Thanks!
 
image

**Comment by amarzavery** [comment]
@xscript - There is already an open PR https://github.com/Azure/azure-rest-api-specs/pull/593 for changes to IOTHUB spec by @rkmanda. There are some other changes that he has to make. Can all these changes be made in a single PR?

**Comment by xscript** [comment]
As long as the fix gets in, I am all right with it. My concern is more about the timeline. Looks like PR [https://github.com/Azure/azure-rest-api-specs/pull/593](https://github.com/Azure/azure-rest-api-specs/pull/593) hasn't been followed up for a while. That's why I create this PR in the first place.
I'm working on the IoT command module in Azure CLI 2.0, and kind of blocked by this bug. 
Do you guys have any timeline? Any plan to update the generated Python SDK?

BTW, if you have time, please also take a look at issue [https://github.com/Azure/autorest/issues/1528](https://github.com/Azure/autorest/issues/1528) here. It is also a bug we meet when using IoT Hub management SDK. But not sure what should be  the correct fix.

Really appreciate your help! :smiley:

---
In reply to: [257908201](https://github.com/Azure/azure-rest-api-specs/pull/657#issuecomment-257908201) [](ancestors = 257908201)

**Comment by amarzavery** [comment]
@xscript - Please sync up with @rkmanda from your team w.r.t the status of #593

**Comment by xscript** [comment]
I am not in the same team with @rkmanda . Do you know his alias? Couldn't find email address from his GitHub profile.

---
In reply to: [258055815](https://github.com/Azure/azure-rest-api-specs/pull/657#issuecomment-258055815) [](ancestors = 258055815)

**Comment by xscript** [comment]
Close this PR per sync with @rkmanda . Will add comments in #593 .

**Pull request closed without merging**
