### PR TITLE
[ACR] Improve and fix descriptions

### PR DESCRIPTION
**Pull request by djyou**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by fearthecowboy** [comment]
Looks ok to me.

Although CI is failing for unrelated reasons.. I've restarted a job to see if it's transient.

**Comment by djyou** [comment]
@fearthecowboy Can you please suggest what is failing the CI? The logs were not clear to me ...

**Comment by fearthecowboy** [comment]
@lmazuel -- do you know why we're seeing the failure : 

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/270933651#L1437

We're seeing stuff like:

``` haskell
FATAL: Error: '$.paths["/subscriptions/{subscriptionId}/providers/Microsoft.ContainerRegistry/checkNameAvailability"].post.parameters' has incomaptible values (---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - '2017-03-01'
- $ref: '#/parameters/SubscriptionIdParameter'
- name: registryNameCheckRequest
  in: body
  description: The object containing information for the availability request.
  required: true
  schema:
    $ref: '#/definitions/RegistryNameCheckRequest'
, ---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - 2017-06-01-preview
- $ref: '#/parameters/SubscriptionIdParameter'
- name: registryNameCheckRequest
  in: body
  description: The object containing information for the availability request.
  required: true
  schema:
    $ref: '#/definitions/RegistryNameCheckRequest'
).
```

I don't see how the string ` 2017-06-01-preview` is even getting in there -- it isn't in the swagger file at all. 

I'm unable to reproduce this locally with the latest autorest preview (1.9.6) :

``` bash

autorest --output-folder=c:/tmp/acr/ --azure-arm=true --input-file=https://raw.githubusercontent.com/djyou/azure-rest-api-specs/0fcc14be21f468a4509229cc619b902c6dc3b23d/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/2017-03-01/containerregistry.json --license-header=MICROSOFT_MIT_NO_VERSION --namespace=azure.mgmt.containerregistry.v2017_03_01 --payload-flattening-threshold=2 --python

```

doesn't give me any errors...

**Comment by djyou** [comment]
`2017-06-01-preview` is the api-version of one of the swagger files, but the only change in the file was to remove a `the` in the description.

**Comment by lmazuel** [comment]
@fearthecowboy we're killed by that: https://github.com/Azure/autorest/issues/2449 :(

**Review by fearthecowboy — COMMENTED** [review]
LGTM
:+1:

I'm going to merge this, CI is failing because of a bug that's fixed in autorest 2.0

**Review by fearthecowboy — APPROVED** [review]
Approving

**Pull request merged**
