### PR TITLE
Introducing capabilities to DatabaseAccount resource

### PR DESCRIPTION
**Pull request by dmakwana**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
Howdy, this looks straight forward. However, given that this is adding a property, it is potentially a breaking change.

**Review by marstr — COMMENTED** [review]
I've confirmed that there are no new Linter or model errors introduced with this PR, even though CI is failing with the PR_ONLY=true flag.

My approval is pending sign-off from the ARM team.

**Comment by lmazuel** [comment]
@dmakwana @marstr Looking at the Python PR I got, there was massive issues with the previous PR:
https://github.com/Azure/azure-rest-api-specs/pull/2052

All the latest parameter in the file are not defined as `"x-ms-parameter-location": "method",` as they should (filterParameter, usageFilterParameter, databaseRidParameter, collectionRidParameter, regionParameter).

This needs to be fixed asap, would be nice if we can take this PR as an opportunity to fix it, or if you can do a parallel PR with this fix.

**Comment by dmakwana** [comment]
@marstr Since we're adding a property and not removing one, all existing API's will still work. This is not a breaking change

@lmazuel I've applied the x-ms-parameter-location fixes. Let me know if there's anything else

**Comment by ravbhatnagar** [comment]
@dmakwana - 2 things -
1. A new property is getting added. If the api-version is not rev'd, it has the potential to cause unintentional updates to this property. Customer A sets some value for the capabilities using portal. Customer B gets the resource using current SDK which has no knowledge of this property. hence it ignores this.  Customer B does a PUT from the SDK. Now the resource on the server which had the capabiities set will be wiped out since the next PUT that came does not have this property in the payload.
2. capabiities should most likely be an enum to help customers with knowing what the possible values are.

**Comment by ravbhatnagar** [comment]
Discussed this offline with Pankaj and Digvijay.  The service side behavior is that this property value is immutable. So if it has been set once, it cant be changed. So the scenario where it can get accidently overwritten is not possible. CosmosDB team has agreed to start versioning such changes going forward. Signing off on this based on the above two factors.

**Review by marstr — APPROVED** [review]

**Comment by marstr** [comment]
@dmakwana, are these changes publicly available and ready to merged into the public `master` branch?

**Comment by dmakwana** [comment]
@marstr the changes are publicly available

**Pull request merged**
