### PR TITLE
Orphan property removed

### PR DESCRIPTION
**Pull request by VitaliyKurokhtin**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by VitaliyKurokhtin** [comment]
This is not an API change of any sort, merely correcting documentation to match real world since removed property was exposed by mistake and does not affect anything.

**Comment by anuchandy** [comment]
seems javascript job is failing, restarted the job.

**Comment by anuchandy** [comment]
Requested ARM Review since the pr removes property from stable api-version.

**Comment by ravbhatnagar** [comment]
This is a breaking change in a stable API-version. Why do you want to remove this property?

**Comment by VitaliyKurokhtin** [comment]
Because this property was never functional. It does present on one of the internal contracts that we use to pass information from controller to custom formatter, so it never makes it's way to the client. Due to some refactoring it slipped to public documentation, but it does nothing if you send it in PUT/PATCH and we never actually return it in JSON response.

**Comment by yungezz** [comment]
Hi @VitaliyKurokhtin @ravbhatnagar  any update on this PR? can it be merged?

**Comment by yungezz** [comment]
@VitaliyKurokhtin are you still on this PR? is it ok to close if you're not working on it anymore?

**Comment by VitaliyKurokhtin** [comment]
There is nothing to do. As I said earlier we're removing orphan non functional property. Still sending this property will not result in an error, and it was never returned. So this is not breaking by any means.

**Comment by yungezz** [comment]
> There is nothing to do. As I said earlier we're removing orphan non functional property. Still sending this property will not result in an error, and it was never returned. So this is not breaking by any means.

hi @ravbhatnagar  could you pls label `ARMSignedOff` then I'll merge the PR if above makes sense to you?

**Review by KrisBash — APPROVED** [review]
With the understanding that this is aligning swagger to server behavior, signing off for ARM

**Review by anuchandy — APPROVED** [review]

**Comment by yungezz** [comment]
CI passed in azure pipeline https://github.com/Azure/azure-rest-api-specs/pull/6844/checks?check_run_id=183465797.

**Pull request merged**
