### PR TITLE
Remove duplication section of recoveryservicesiterecover/..../service.json MigrateToAad section

### PR DESCRIPTION
**Pull request by mikekinsman**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by salameer** [comment]
@mikekinsman why are you referencing the Stable spec within the Preview Spec, for ex:

-           "$ref": "../2015-10-31/definitions.json#/parameters/SubscriptionIdParameter"
 +           "$ref": "../../stable/2015-10-31/definitions.json#/parameters/SubscriptionIdParameter"

in the preview files:

nager/Microsoft.Automation/preview/2017-05-15-preview/softwareUpdateConfiguration.json

**Comment by marstr** [comment]
Howdy, thanks for bearing with us here, @mikekinsman.

Looking through, it seems like this is a duplicate of #2200 and #2199, is that correct? If so, I think we'll close this out and merge the other two independently to keep history a little bit more clear.

Thanks!

-Martin

**Comment by marstr** [comment]
> @salameer says:
why are you referencing the Stable spec within the Preview Spec

While it's not a best practice, it is something that happens a lot. Mike didn't introduce that behavior, it was something that was already here. For the sake of mitigating the issues we're running into, I think that we should close this copy of his changes out, and merge #2200 ASAP.

**Comment by marstr** [comment]
Closing this now that I've merged #2200.

**Pull request closed without merging**
