### PR TITLE
Marketplace version 2023-01-01

### PR DESCRIPTION
**Pull request by saviesacov**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update? **new API version**
  2. When are you targeting to deploy the new service/feature to public regions? **start SDP 20/2/23**
  3. When do you expect to publish the swagger? **March 2023**
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ X] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [X ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ X] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [X ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [X ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by saviesacov** [comment]
1. The change is adding POST method to an exist API
2. The first commit it's a base commit
3. Next week we will update manifest so 'operations' API will support the new version 2023-01-01 too.

**Comment by zizw123** [comment]
>         }

add x-ms-pageable for pagination

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2023-01-01/Marketplace.json:905 in 13a140e. [](commit_id = 13a140e55ee1119578555bf252249c91f9587bf0, deletion_comment = False)

**Comment by saviesacov** [comment]
Hello @zizw123 ,
Thanks for noticing the pagination issue, just fixed.

**Comment by rkmanda** [comment]
>       "post": {

post action cannot be defined on a resource collection. it has to be on a specific instance of a resource or at a provider level

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2023-01-01/Marketplace.json:866 in 5be8555. [](commit_id = 5be85550dee6312ce287666c1226e2b78a4f0a79, deletion_comment = False)

**Comment by rkmanda** [comment]
>       "post": {

Looks like you are wanting to implement a filter on the get collection call. Please define odata filters on the GET API to achieve this.

---
In reply to: [1434249331](https://github.com/Azure/azure-rest-api-specs/pull/22527#issuecomment-1434249331) [](http://example.com/codeflow?ancestors=1434249331)

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2023-01-01/Marketplace.json:866 in 92d957f. [](commit_id = 92d957f933f4c0ff42c49624d16de529a481273b, deletion_comment = False)

**Comment by saviesacov** [comment]
> > ```
> >   "post": {
> > ```
> 
> post action cannot be defined on a resource collection. it has to be on a specific instance of a resource or at a provider level
> 
> Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2023-01-01/Marketplace.json:866 in [5be8555](https://github.com/Azure/azure-rest-api-specs/commit/5be85550dee6312ce287666c1226e2b78a4f0a79). [](commit_id = [5be8555](https://github.com/Azure/azure-rest-api-specs/commit/5be85550dee6312ce287666c1226e2b78a4f0a79), deletion_comment = False)

**Comment by saviesacov** [comment]
Hi @rkmanda , thank you for the comments 👍 
Please help me to clarify how to handle gaps: 
1. If we will return a list of "#/definitions/OfferProperties" without the resource structure details, is it ok?
2. About Get vs. Post: we haven't used odata filters; in this case, there is a difference in the response structure between two calls (get & post). Post with an empty body will not equal to get. How do you suggest handling in the level of odata filters?

Thanks,
Savi

**Comment by gupele** [comment]
Hi @rkmanda 
The call is not OData as the contexts that we use are not part of the Model and also since we need to process and intersect the data in our database with data we fetch from Catalog.

**Comment by pilor** [comment]
As has been called out above.  The path you are using is not valid for a POST action.  See the valid scopes for POST actions here:  https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#resource-action-requests

I agree that this should be a $filter on the GET collection call if possible OR a POST actoin like "/providers/Microsoft.Marketplace/privateStores/{privateStoreId}/collections/{collectionId}/listOffers"

**Comment by saviesacov** [comment]
Hello @pilor , thanks for the feedback.
As you suggested, we set it as post action with different action name:
"/providers/Microsoft.Marketplace/privateStores/{privateStoreId}/collections/{collectionId}/mapOffersToContexts"

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
