### PR TITLE
Adding support for HTTP2 to Web Apps

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Based on the information in this article, I believe this is correct: https://blogs.msdn.microsoft.com/appserviceteam/2018/04/13/announcing-http2-support-in-azure-app-service/

@mcardosos @marstr @jhendrixMSFT I also added support for generating the missing `2018-02-01` Web SDK - although in my limited testing that appears to be broken due to Invalid Swagger, so I can revert this if needed:

```
* azurerm_app_service_plan.test: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'eastus' and API version '2018-02-01' for type 'serverFarms'. The supported api-versions are '2017-08-01, 2016-09-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2014-11-01, 2014-06-01, 2014-04-01, 2014-04-01-preview'. The supported locations are 'centralus, northeurope, westeurope, southeastasia, koreacentral, koreasouth, westus, eastus, japanwest, japaneast, eastasia, eastus2, northcentralus, southcentralus, brazilsouth, australiaeast, australiasoutheast, westindia, centralindia, southindia, canadacentral, canadaeast, westcentralus, ukwest, uksouth, westus2, msftwestus, msfteastus, msfteastasia, msftnortheurope, eastus2stage, eastasiastage, centralusstage, northcentralusstage, francecentral'."
```

---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
I've integrated the result of this into Terraform and I can confirm the result looks good to us:

```
$ acctests azurerm TestAccAzureRMAppService_http2Enabled
=== RUN   TestAccAzureRMAppService_http2Enabled
--- PASS: TestAccAzureRMAppService_http2Enabled (98.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm       98.568s
```

**Comment by mcardosos** [comment]
Hello @tombuildsstuff !
Thanks for submitting a PR :) We will take a look at this
@lukaszstem @naveedaz @nking92

**Comment by naveedaz** [comment]
@tombuildsstuff I am trying to understand why you want to add http20Enabled property to the MigrateMySqlStatus object. The http20Enabled property already exists on SiteConfig, at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/CommonDefinitions.json#L2180.

**Comment by marstr** [comment]
Ping @tombuildsstuff.

Do you have any insight for me and @naveedaz here?

**Comment by tombuildsstuff** [comment]
@marstr sorry, missed this ping.

@naveedaz apologies, you're right - I'd searched for this but missed it. We're now using this field and as such I'll close this PR

**Pull request closed without merging**
