### PR TITLE
add cli.md for serialconsole

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by qiaozha** [comment]
@00Kai0  why are you add this readme.cli.md file?

**Comment by NullMDR** [comment]
@00Kai0 Any update? Any context for this PR?

**Comment by 00Kai0** [comment]
@N-Usha , @qiaozha this cli.md is used for generating test. doc [here](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/generating-integration-test.md)

**Comment by qiaozha** [comment]
> @N-Usha , @qiaozha this cli.md is used for generating test. doc [here](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/mgmt/generating-integration-test.md)

If you are not intend to merge this PR at this moment, Add `DoNotMerge` tag in the PR. The same for the other PRs you've filed. After it's ready to merge, you can remove the `DoNotMerge` tag. assign them to @zikalino or @changlong-liu

**Review by zikalino — APPROVED** [review]

**Review by zikalino — APPROVED** [review]

**Pull request merged**
