### PR TITLE
Added logic apps operations

### PR DESCRIPTION
**Pull request by alexkarcher-msft**
Added logic apps operations that are proxied through the web apps RP. I'm not sure why this PR is showing deletions. Neither of my commits remove any existing stuff from the definition. I think it's just the diff tool getting a bit confused as I insert stuff in the middle of the file?

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify `I am adding routes for logic apps that are proxied directly from the RP front end into customer's running apps, so they are not added in the normal swagger generation step`
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. `The functionality is already live`
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. `We will publish in the ANT97 release this PR is open against`
4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@alexkarcher-msft there is huge diff in webapps.json.
Make sure it is sorted up, then add ARM review.

**Comment by alexkarcher-msft** [comment]
@weidongxu-microsoft I have sorted through all of the PR validation errors that appear to be unique to my additions. Let me know how to add ARM for review.

**Comment by weidongxu-microsoft** [comment]
@alexkarcher-msft
You should not change package-lock.json

I've no idea why there is 10k+ change on webapps.json. But if you are ready, just check " Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest." checkbox in description.

Due to this huge change on webapps.json, I would need Navy's approval for this PR as well (or we might mess his branch).

**Comment by alexkarcher-msft** [comment]
Whoops, forgot to revert package-lock before sending the prettier updates. Will check those boxes and get the review underway.
I'm not quite sure why my ~5k lines added to web-apps.json with no deletions is showing up as a 10k+ diff with a ton of deletions. It's a mystery we can all ponder together this April.

**Review by rarayudu — APPROVED** [review]

**Comment by edwin-msft** [comment]
@weidongxu-microsoft Seems like the wait for ARM review tag was added 20 days ago and it was not reviewed. Should @alexkarcher-msft remove and re-add the tag to retrigger the review process?

**Comment by weidongxu-microsoft** [comment]
@edwin-msft 
Please see https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1098561987
You can email the group to notify them.

**Comment by edwin-msft** [comment]
Thank you for the information, @weidongxu-microsoft 

@alexkarcher-msft Can you please email ([armapireview@microsoft.com](mailto:armapireview@microsoft.com)) as per Weidong's instructions? https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1098561987

**Comment by alexkarcher-msft** [comment]
Sent an email for review. Thanks for the clarification.

**Comment by zizw123** [comment]
>           "nextLinkName": null

This does not have a nextLink?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:21784 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by zizw123** [comment]
>           "nextLinkName": null

Same question here, no nextLink?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22144 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by zizw123** [comment]
>           "202": {

202 is used for async, should this post call be a async operation?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22581 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by zizw123** [comment]
>           },

Same here, is this post async or sync?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22695 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by alexkarcher-msft** [comment]
> > ```
> >       "202": {
> > ```
> 
> 202 is used for async, should this post call be a async operation?
> 
> Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22581 in [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f). [](commit_id = [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f), deletion_comment = False)


For this run workflow action, the underlying workflow is something created by the customer and can be async or synchronous depending on how they've configured their workflow.

**Comment by alexkarcher-msft** [comment]
> > ```
> >       },
> > ```
> 
> Same here, is this post async or sync?
> 
> Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22695 in [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f). [](commit_id = [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f), deletion_comment = False)

For the resubmit action, it's a bit of a confusing operation to document. In order to call this API you need to have all the same context you need to get the run status. After you resubmit the run, the status of that run can then be checked using the same trigger name, history name, etc.

Is there anything explicit you're looking to have added to indicate that it's an async operation?

**Comment by alexkarcher-msft** [comment]
> > ```
> >       "nextLinkName": null
> > ```
> 
> Same question here, no nextLink?
> 
> Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22144 in [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f). [](commit_id = [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f), deletion_comment = False)

Good catch with both of these! I've updated these two and a few other instances where that value was missing.

**Comment by jorgecotillo** [comment]
>         "x-ms-pageable": {

Generally POST APIs are for actions, there are exceptions where you can return item(s) when you are aggregating datasources to construct a response and this process takes more than 2 seconds (at which point it becomes an async API). Also, using list*** prefix and POST method means that you can enable ARM Template support (e.g. listSecrets), is this your intention? also, are you paginating the result?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:21716 in fd01151. [](commit_id = fd011516eac6508d47c66d353c5a4251ef5e4ea1, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>         "x-ms-pageable": {

Same as above, are you planning on paginating the response?

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:21926 in fd01151. [](commit_id = fd011516eac6508d47c66d353c5a4251ef5e4ea1, deletion_comment = False)

**Comment by alexkarcher-msft** [comment]
> > ```
> >     "x-ms-pageable": {
> > ```
> 
> Generally POST APIs are for actions, there are exceptions where you can return item(s) when you are aggregating datasources to construct a response and this process takes more than 2 seconds (at which point it becomes an async API). Also, using list*** prefix and POST method means that you can enable ARM Template support (e.g. listSecrets), is this your intention? also, are you paginating the result?
> 
> Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:21716 in [fd01151](https://github.com/Azure/azure-rest-api-specs/commit/fd011516eac6508d47c66d353c5a4251ef5e4ea1). [](commit_id = [fd01151](https://github.com/Azure/azure-rest-api-specs/commit/fd011516eac6508d47c66d353c5a4251ef5e4ea1), deletion_comment = False)

Hi Jorge, 

I checked in the code and those APIs are not currently returned paged results. However, the source APIs that they are proxying are also listed as pageable. I notice that that doesn't seem to then be translated into our documentation. However, I'm fine removing that annotation if it's causing problems. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json#L1923

For the POST, I couldn't find anyone with any idea of why that endpoint is POST instead of GET. It has been like that since 2016, and is already interfacing with very mature portal code. If it is a problem I can make a work item to look at updating the API for both our older original RP and this newer proxied version.
Right now we're just looking to document what's already been deployed to production, as it's already been in production for years with no documentation or SDK/CLI support.

**Comment by weidongxu-microsoft** [comment]
@zizw123

I think it is the recommended to add `x-ms-pageable` with `nextLink=null` to those APIs that could potentially be pageable in future, especially for SDK (as adding `x-ms-pageable` would be breaking changes to SDK).

Though if service know there will never be such pagination in future, they are no necessary.

**Comment by alexkarcher-msft** [comment]
@weidongxu-microsoft 

Sweet! In that case I'd love to keep the pageable links in there, as we may add that functionality in the future. We have `"nextLinkName": "nextLink"` instead of `nextLink:null`, but that is consistent though out the whole WebApps.json definition.

**Comment by mentat9** [comment]
>           "202": {

+1, you need x-ms-long-running-operation if this method is async. If it's sync, the status code should be 200 or 204.

---
In reply to: [1119056748](https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1119056748) [](http://example.com/codeflow?ancestors=1119056748,1119056748)

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22581 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by mentat9** [comment]
>           },

+1, x-ms-long-running-operation if async, remove 202 if sync.

---
In reply to: [1119056792](https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1119056792) [](http://example.com/codeflow?ancestors=1119056792,1119056792)

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22695 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by mentat9** [comment]
> > > ```
> > >       "202": {
> > > ```
> > 
> > 
> > 202 is used for async, should this post call be a async operation?
> > Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22581 in [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f). [](commit_id = [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f), deletion_comment = False)
> 
> For this run workflow action, the underlying workflow is something created by the customer and can be async or synchronous depending on how they've configured their workflow.

Does your API implement the standard ARM async pattern when the customer workflow is async? If so, you need to mark the method with the x-ms-long-running-operation extension and implement the operationStatuses or operationResults APIs. Ref: https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#asynchronous-api-reference and https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation.

**Comment by mentat9** [comment]
> > > ```
> > >       },
> > > ```
> > 
> > 
> > Same here, is this post async or sync?
> > Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22695 in [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f). [](commit_id = [6926d75](https://github.com/Azure/azure-rest-api-specs/commit/6926d7553fad0cfe979d9202a84157d2a227972f), deletion_comment = False)
> 
> For the resubmit action, it's a bit of a confusing operation to document. In order to call this API you need to have all the same context you need to get the run status. After you resubmit the run, the status of that run can then be checked using the same trigger name, history name, etc.
> 
> Is there anything explicit you're looking to have added to indicate that it's an async operation?

I replied earlier in both non-quoted and quoted comment,s duplicating here so it doesn't get overlooked. You need x-ms-long-running-operation to describe the standard Azure async pattern. Previous comment included links to the wiki that describe it in detail.

**Comment by mentat9** [comment]
@alexkarcher-msft - I revisited ARM review comments and found a few still unaddressed. I expanded on those to help clarify. To respond back, please apply the WaitForARMFeedback label again.

**Comment by alexkarcher-msft** [comment]
Hi @mentat9 ,

Added x-ms-long-running to those two async API calls. For this entire PR, we are proxying an API that is already in production and already has its own ARM approved definition deployed here: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01

If you need additional functional updates we can create a work item on our side and work to get funding to make those changes. Since updates will apply to both routes this API is surfaced, it will likely involve breaking changes to existing customers.

At this time I'd like to document what we have and circle back around after the fact and make any updates to our API surface.

**Comment by mentat9** [comment]
>           "202": {

I think you still need an additional 200 or 204 here. The API must return a final result that isn't 202, right? However, based on your other comments that this is to document an existing production API, I won't withhold ARM approval. ARM review is to apply principles to new APIs. Anything that improves the fidelity of specs for APIs already in production is welcome.

---
In reply to: [1145535311](https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1145535311) [](http://example.com/codeflow?ancestors=1145535311,1119056748)

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:22581 in 6926d75. [](commit_id = 6926d7553fad0cfe979d9202a84157d2a227972f, deletion_comment = False)

**Comment by mentat9** [comment]
>         "x-ms-pageable": {

FYI, I don't think x-ms-pageable actually does anything for POST methods.

---
In reply to: [1132478586](https://github.com/Azure/azure-rest-api-specs/pull/18604#issuecomment-1132478586) [](http://example.com/codeflow?ancestors=1132478586,1132478586)

---
Refers to: specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json:21716 in fd01151. [](commit_id = fd011516eac6508d47c66d353c5a4251ef5e4ea1, deletion_comment = False)

**Comment by mentat9** [comment]
> Hi @mentat9 ,
> 
> Added x-ms-long-running to those two async API calls. For this entire PR, we are proxying an API that is already in production and already has its own ARM approved definition deployed here: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01
> 
> If you need additional functional updates we can create a work item on our side and work to get funding to make those changes. Since updates will apply to both routes this API is surfaced, it will likely involve breaking changes to existing customers.
> 
> At this time I'd like to document what we have and circle back around after the fact and make any updates to our API surface.

@alexkarcher-msft - Thank-you for the additional context. Given that your goal is to match this spec to APIs already in production, ARM recommendations are mostly moot. I've left a couple more comments related to that goal (final status code for one of the POST methods, and x-ms-pageable on POST), but ARM signoff really shouldn't be needed here. I've removed the WaitForARMFeedback label.

**Review by naveedaz — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
I should be able to merge after conflict resolved.

**Comment by alexkarcher-msft** [comment]
Thanks for the heads up! Resolved merge conflicts

**Comment by alexkarcher-msft** [comment]
@weidongxu-microsoft , feel free to merge whenever you have a chance :)

**Pull request merged**
