### PR TITLE
Change statusMessage property to wildcard type.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
The statusMessage can be a string or a JSON object, so model it as a
wildcard type.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/azure-rest-api-specs/issues/2355.

**Comment by jhendrixMSFT** [comment]
@vivsriaus can you please confirm this change applies to all API versions?

**Comment by vivsriaus** [comment]
@jhendrixMSFT thanks for making this change. Will this be considered a breaking change in SDK? How does the generated code look with these changes? 

I'll confirm if this can apply to all API versions today.

**Comment by jhendrixMSFT** [comment]
@vivsriaus By luck this doesn't introduce any breaking changes while formalizing the behavior (see the linked issue for the details).

**Comment by jhendrixMSFT** [comment]
@sarangan12 can you please take a look at the Ruby build failure?

**Review by vivsriaus — APPROVED** [review]
thanks for making this change!

**Comment by sarangan12** [comment]
Reason for the Ruby CI Failure:

The root cause of this issue is this PR: https://github.com/Azure/azure-rest-api-specs/pull/2469 This basically moved a folder to a different location. But, the swagger_to_sdk expects it in the old place. https://github.com/Azure/azure-sdk-for-ruby/blob/master/swagger_to_sdk_config.json#L1214 which is causing the error. I would recommend you to go ahead and merge it for now (if there are no other issues). I will fix the config

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
