### PR TITLE
[Hub Generated] fix RangeObject property types in Maps Creator preview/2.0

### PR DESCRIPTION
**Pull request by ambientlight**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/ambientlight/azure-rest-api-specs/fix%2Fmaps-Creator-2.0-featurestate-RangeObject...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [X] Fix property types in Map Creator's featurestate RangeObject definition
  2. When you are targeting to deploy new service/feature to public regions? 
  **Services are already deployed. This fixes the inconsistency with the actual response json returned.**
  3. When you expect to publish swagger?
  **ASAP**
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
  No data-plane SDKs are onboarded yet, so no refresh required.

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [X] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate):
**Submitted new intake**: https://msazure.visualstudio.com/One/_workitems/edit/10449739

### CODE REVIEW

**Comment by ambientlight** [comment]
@jhendrixMSFT: This swagger breaking change fixes the inconsistency in the definition of RuleObject against Rule originally from [StyleRule.cs:L73](https://dev.azure.com/msazure/One/_git/Azure-Maps-MDP?path=%2Fsrc%2FFramework%2FFeatureStateStore%2FDatamodel%2FStyleRule.cs&version=GBmaster&line=73&lineEnd=74&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

This has popped up when testing golang SDK for subsequent onboarding since json parser is strict and will fail when string are encountered when float64 are expected: https://github.com/Azure/azure-sdk-for-go/commit/71dd086cdceb52d41488adac3abffaf9b677de96

**Comment by daniel-rocha** [comment]
@jhendrixMSFT can we please approve and merge this PR? It is blocking SDK generation now. Thanks!

**Comment by jhendrixMSFT** [comment]
@johanste is the breaking change acceptable?

**Comment by jhendrixMSFT** [comment]
@ambientlight is this to make the swagger consistent with what the service sends over the wire?

**Comment by daniel-rocha** [comment]
@jhendrixMSFT I think @johanste is familiar with the process Azure Maps is going through to adopt this new process of SDK generation, but I'll let him answer. @ambientlight is an engineer in my team and he's on vacation this week, but I can confirm that this is the case. 

This is the actual documentation of the API payload sent down the wire: https://docs.microsoft.com/en-us/rest/api/maps/v2/feature-state/list-stateset

``` 
"keyName": "s2",
            "type": "number",
            "rules": [
              {
                "range": {
                  "minimum": null,
                  "maximum": null,
                  "exclusiveMinumum": null,
                  "exclusiveMaximum": "50"
                },
                "color": "#343deb"
              }
```

**Comment by ambientlight** [comment]
@ambientlight is this to make the swagger consistent with what the service sends over the wire?

Yes, exactly that, RangeObject will contain string properties in response (not floating-point numbers).

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Thanks for confirming.  Once the magic `Approved-BreakingChange` label is added by @johanste I can merge.

**Comment by johanste** [comment]
This is addressing an incorrect description of the service. Not an actual service API breaking change (no changes to the service API)

**Pull request merged**
