### PR TITLE
Removed unused fields from ActionType and added range for priority

### PR DESCRIPTION
**Pull request by sushantsingh**
This product is not released to public yet i.e. there are no real customers other than internal test subscriptions. This was already approved by ARM in this [PR](https://github.com/Azure/azure-rest-api-specs/pull/6343) but since I did get to resolving the merge errors in time, the issue got closed.
I did not see any option to open it again, so I am creating a new PR with the exact same commits

**What is in the PR?**
Removed some unused fields from ActionType
Removed the following which we don't plan to support anymore for the preview release

redirectUrl
customBlockResponseStatusCode
customBlockResponseBody
customBlockResponseBody

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by lirenhe** [comment]
@sushantsingh, there are a couple of check errors, could you address those issues?

**Review by KrisBash — APPROVED** [review]
Signing off for ARM on the basis of this being not publicly exposed and previously reviewed.

**Comment by lirenhe** [comment]
@sushantsingh, there are a couple of check errors, could you address those issues?  And as the PR has been there for a while, if it is not needed anymore, please let me know if I could directly close this.

**Comment by lirenhe** [comment]
Close this one as there is no response from PR owner for more than 3 weeks.  @sushantsingh, if you still need this PR, feel free to reopen it.

**Pull request closed without merging**
