### PR TITLE
June API version for ASR

### PR DESCRIPTION
**Pull request by prsadhu-ms-idc**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by rkmanda** [comment]
>           "additionalProperties": {

why not just declare an array. What is the need for additionalProperties?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:12684 in a054788. [](commit_id = a0547883baa6ab5b4169ace7156becebb2f2fc1e, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "targetBootDiagnosticStorageAccountSAS": {

Is this truly a secret? or just the storage account name? If it is a secret, it doesnt make sense to include it in the response to a get, put, patch operations. You need a separate POST action to provide this information to customers.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:18920 in a054788. [](commit_id = a0547883baa6ab5b4169ace7156becebb2f2fc1e, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "additionalProperties": {

Usage of additionalProperties is not allowed. Can you define this as a concrete type instead? if not can you explain why this needs to be a loose dictionary?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:12684 in a054788. [](commit_id = a0547883baa6ab5b4169ace7156becebb2f2fc1e, deletion_comment = False)

**Comment by prsadhu-ms-idc** [comment]
> > ```
> >       "additionalProperties": {
> > ```
> 
> Usage of additionalProperties is not allowed. Can you define this as a concrete type instead? if not can you explain why this needs to be a loose dictionary?
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:12684 in [a054788](https://github.com/Azure/azure-rest-api-specs/commit/a0547883baa6ab5b4169ace7156becebb2f2fc1e). [](commit_id = [a054788](https://github.com/Azure/azure-rest-api-specs/commit/a0547883baa6ab5b4169ace7156becebb2f2fc1e), deletion_comment = False)

Resolved.

**Comment by prsadhu-ms-idc** [comment]
> > ```
> >     "targetBootDiagnosticStorageAccountSAS": {
> > ```
> 
> Is this truly a secret? or just the storage account name? If it is a secret, it doesnt make sense to include it in the response to a get, put, patch operations. You need a separate POST action to provide this information to customers.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:18920 in [a054788](https://github.com/Azure/azure-rest-api-specs/commit/a0547883baa6ab5b4169ace7156becebb2f2fc1e). [](commit_id = [a054788](https://github.com/Azure/azure-rest-api-specs/commit/a0547883baa6ab5b4169ace7156becebb2f2fc1e), deletion_comment = False)

Removed.

**Comment by singhabh27** [comment]
@rkmanda, can you please review the remaining changes.

**Comment by mentat9** [comment]
>         "state": {

Please model state as a string enum, assuming it has a fixed set of values.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11931 in 10fe9d5. [](commit_id = 10fe9d56940a694a82d31338b9c14d1da58ed5c5, deletion_comment = False)

**Comment by mentat9** [comment]
>         "dataStore": {

Name for a collection should be plural, e.g. dataStores.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11965 in 10fe9d5. [](commit_id = 10fe9d56940a694a82d31338b9c14d1da58ed5c5, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "A value indicating the datastore.",

Should mention the collection.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11966 in 10fe9d5. [](commit_id = 10fe9d56940a694a82d31338b9c14d1da58ed5c5, deletion_comment = False)

**Comment by singhabh27** [comment]
> > ```
> >     "isCheckSumResyncCycle": {
> > ```
> 
> Recommend modeling two-valued properties as enum instead of boolean. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> 
> In this case, maybe something like checksumState: { Syncing, Valid } or similar.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:24293 in [3ffa445](https://github.com/Azure/azure-rest-api-specs/commit/3ffa445f97bc08fabfc169bff42bb8c178152cc6). [](commit_id = [3ffa445](https://github.com/Azure/azure-rest-api-specs/commit/3ffa445f97bc08fabfc169bff42bb8c178152cc6), deletion_comment = False)

We are using the 

> > ```
> >     "operationName": {
> > ```
> 
> If this property takes a fixed set of values, recommend modeling it as a string enum.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:24381 in [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5). [](commit_id = [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5), deletion_comment = False)

We want to keep this property as String.

**Comment by singhabh27** [comment]
> > ```
> >     "operationName": {
> > ```
> 
> If this property takes a fixed set of values, recommend modeling it as a string enum.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:24381 in [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5). [](commit_id = [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5), deletion_comment = False)

We want to keep this property as String.

**Comment by singhabh27** [comment]
> > ```
> >     "state": {
> > ```
> 
> Please model state as a string enum, assuming it has a fixed set of values.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11931 in [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5). [](commit_id = [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5), deletion_comment = False)

As per our design, we want to keep it as String.

**Comment by singhabh27** [comment]
> > ```
> >     "dataStore": {
> > ```
> 
> Name for a collection should be plural, e.g. dataStores.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11965 in [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5). [](commit_id = [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5), deletion_comment = False)

Done.

**Comment by singhabh27** [comment]
> > ```
> >       "description": "A value indicating the datastore.",
> > ```
> 
> Should mention the collection.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:11966 in [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5). [](commit_id = [10fe9d5](https://github.com/Azure/azure-rest-api-specs/commit/10fe9d56940a694a82d31338b9c14d1da58ed5c5), deletion_comment = False)

Done.

**Comment by singhabh27** [comment]
> > ```
> >     "isCheckSumResyncCycle": {
> > ```
> 
> Recommend modeling two-valued properties as enum instead of boolean. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> 
> In this case, maybe something like checksumState: { Syncing, Valid } or similar.
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-06-01/service.json:24293 in [3ffa445](https://github.com/Azure/azure-rest-api-specs/commit/3ffa445f97bc08fabfc169bff42bb8c178152cc6). [](commit_id = [3ffa445](https://github.com/Azure/azure-rest-api-specs/commit/3ffa445f97bc08fabfc169bff42bb8c178152cc6), deletion_comment = False)

We use ASR bool converter in our service code. Example of existing case:
image
Keep it in same way.

**Comment by prsadhu-ms-idc** [comment]
We will be completing the failing checks.

**Comment by singhabh27** [comment]
@rkmanda, can you please review the latest 2 commits.

**Comment by prsadhu-ms-idc** [comment]
Hi @rkmanda, please approve.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
