### PR TITLE
Adding ServerManagement API spec

### PR DESCRIPTION
**Pull request by fearthecowboy**
Aka, SMT or RSMT

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@fearthecowboy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (garretts). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L65

Regex pattern in the description can be added as a validation and the generated client will assert that on the values provided by the user. https://github.com/Azure/autorest/blob/master/AutoRest/TestServer/swagger/validation.json#L32

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L78
A generic comment: Please provide default response in the responses section. 

Default will be treated as an error. If you provide the schema of the error object in the default then the responses will be deserialized accordingly.

Please read the  documentation on responses carefully over here https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Responses and make changes accordingly.

**Comment by amarzavery** [comment]
As you have 200 and 201 documented in the responses, for Gateways_create, is it a long running operation? If so, then please add the extension "x-ms-long-running".

**Comment by amarzavery** [comment]
Is Node_Update a long running operation? https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L437

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L826 - Looks like this is long running. Extension?

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1233

Do you want this to be of DateTime format?

**Comment by amarzavery** [comment]
General Comment: Bunch of places have todo in the description. Please make sure to update it accordingly
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1262

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1307

Adding min and max constraints?

List of constraints supported by swagger:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-fields-2 

Click on the link above and scroll up a little to see all the constraints

**Comment by amarzavery** [comment]
Just a suggestion, Although the name suggests that memory is in MB, it would be nice if the description also states it.
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1303

**Comment by amarzavery** [comment]
Question mark in the description. Is the spec stating or asking?
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1370

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1382


> The autoUpgrade property gives the flexibility to gateway to auto upgrade itself. If properties value not specified, then we assume autoUpgrade = never.

How about the following?

> "The autoUpgrade property gives the flexibility to gateway to auto upgrade itself. Default value 'off'."

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1569

"A multipart numeric~~a~~ version"

**Comment by amarzavery** [comment]
Description for "pssession", "command", "completed"

https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1639

**Comment by amarzavery** [comment]
properties of these definitions PowerShellCommandResult, PromptFieldDescription are not documented.

Being crisp on documentation goes a long way. This will be turned into client side documentation and there is an effor by a team to convert swagger specs into REST API docs on msdn. Hence, description becomes even more important.

**Comment by amarzavery** [comment]
Please provide an example of the time stamp format in the description wherever it is used.
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L1551

**Comment by amarzavery** [comment]
Body parameters can be better named then body. This could be named as GatewayParameters
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L68

**Comment by amarzavery** [comment]
https://github.com/fearthecowboy/azure-rest-api-specs/blob/master/arm-servermanagement/2015-07-01-preview/servermanagement.json#L69

x-ms-client-flatten extension - brings the child properties of the object one level up (flattens).

when you apply this on the body parameter itself, it will flatten the body (GatewayParameters)  completely resulting in more required/optional parameters (based on how they are specified in GatewayParameters).

It is fine to do that. I was curious to know, if that was intentional?

**Comment by fearthecowboy** [comment]
> re: Regex pattern 

Oh, cool. I never found that before. Awesome, fixing...

> As you have 200 and 201 documented in the responses, for Gateways_create

Fixed. 

> Is Node_Update a long running operation 

Fixed

> Please provide default response in the responses section.

Fixed. :)

> Looks like this is long running. Extension?

Fixed 

> Do you want this to be of DateTime format?

Fixed

>  Bunch of places have todo in the description.  

Reaaaaaly thought I had caught those. Sorry. :(

> Adding min and max constraints?

Fixed

> Question mark in the description. Is the spec stating or asking?

Too many lattés while editing error. :coffee: 

> How about the following?

Now, I distinctly remember fixing that. :hammer: 

> A multipart numerica 

Fixed.

> Body parameters can be better named then body.

I figured since I was flattening them, that didn't really get exposed, but I fixed them

> Please provide an example of the time stamp format in the description wherever it is used.

Is using `format: date-time` sufficient?

> x-ms-client-flatten extension - I was curious to know, if that was intentional?

Yes, I originally had it without that, but it was a miserable pain in the butt to use, so I flattened them. It feels a lot more natural when coding against the API this way.

> Being crisp on documentation goes a long way.  (PowerShellCommandResult, PromptFieldDescription)

Yeah, I realize that-- I didn't write the original API doc that I was handed to do this (and it turns out that it wasn't complete or accurate), and some of those fields I just recently found in empirical testing and had to go back to get more detail.  I put them in so that we'd be able to get the values back, and over the next couple weeks, I was going to go walk thru the implementation code and see what the heck they were for.

As it is, it's a stretch of vivid imagination that much of this API is useful from an automation perspective;  large parts of it are really implementation details for the Portal itself. That being said, I'm attempting to expose as much as I can that could feasibly be used :)

Gimme a couple of hours to finish running this thru my tests, and I'll submit an updated PR including the fixes.

**Comment by fearthecowboy** [comment]
Updated to address feedback.

**Comment by amarzavery** [comment]
@fearthecowboy - The changes look good to me.

Providing the format: date-time should be sufficient enough.

One last thing,please make sure that the tabs are set to 2 spaces for json docs. If you are using Visual Studio then after setting the tabs to 2 spaces, you can select all and then press Ctrl + K + D. That should format it correctly.

**Comment by fearthecowboy** [comment]
> re: 2 spaces 

Funny story: I uh, never actually looked at the JSON even once. I used the swagger.io editor, and worked in YAML the whole time, and just used 'download json' ... after that my local build script picks it up and puts it in the right spot :)

Strange that the tool didn't go with 2 space tabs, given that's what YAML uses ...

**Comment by fearthecowboy** [comment]
Indentation changed to 2 spaces in latest commit

**Pull request merged**
