### PR TITLE
Introduce price sheet and market place to Swagger, update budget API

### PR DESCRIPTION
**Pull request by bgsky**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@bgsky can you please send a PR with better commits? It looks PR is based on the `current` branch, I would suggest following to make both SDK and ARM review effective.

1. Create a branch in your fork based on the upstream `master` (which already has 2018-01-31 version of consumption.json spec)
2. Create first commit that contains the changes specific to consumption.json file and have a commit message explaining the changes
3. Create second commit with new Budget.json file and it’s operation examples
4. Create third commit with new PriceSheet.json file and it’s operation examples
5. Send a PR

**Review by anuchandy — CHANGES_REQUESTED** [review]
Please see the comment about cleaning the commits.

**Comment by bgsky** [comment]
Thanks for suggestions. I will abandon this pull request, reorganize commits, and send another one.

**Comment by anuchandy** [comment]
@bgsky thank you, once you open the PR please ping me (or email me), I will assign it to myself and try to unblock you ASAP.

**Comment by ms-premp** [comment]
@anuchandy, are you recommending separate swagger files for separate operations ? Like one swagger file per operation/api ?
In the past, it looks like it was recommended to use one file and that’s why existing consumption.json has operations for usagedetails and reservedinstances. We followed the same pattern and now adding budgets, pricesheet and marketplace operations to same file. The new version has new operations along with old operations and old operations we do not have any change. 
Please confirm or are we missing some thing here ?
We are under the impression that this way will help us with other Rest docs, SDK and CLI generation based on just one consumption.json file and not separate multiple files for each operation.

**Comment by sandeepnl** [comment]
My understanding of Anu's comment is to make commits logically separated and have detailed description in the commit message. The budgets.json and pricesheets.json he has mentioned are the example files that can come in as separate commits
@bgsky Please restart the PR by using master branch and did you pull the latest from upstream before the PR? seems like there are some conflicts. Please do so if not done yet

**Comment by anuchandy** [comment]
@sandeepnl thank you for clarifying. You're right, as you said what I mean is having logically separated commits. For instance, In the current PR if we go to "Changed Files", "consumption.json" file appear as a totally NEW file, but when looked into the master branch noted that it is already existing for the same api version. 

@ms-premp It's my bad that I misinterpret budgets.json and pricesheets.json as spec. As @sandeepnl mentioned, all i'm requesting is having a new PR based on the `master` branch (instead of `current`) with logically separate the commits.

**Comment by anuchandy** [comment]
No need to put the examples `budgets.json, pricesheets.json` in separate commit I asked so thinking they are specs.

**Comment by ms-premp** [comment]
Thanks @anuchandy and @sandeepnl .. make sense .. we will proceed as suggested.

**Comment by bgsky** [comment]
Due to the conflicts caused by commits across operations introduced, we will close this pull request, and introduce a new one.

**Pull request closed without merging**
