### PR TITLE
Review request for Microsoft.ContainerService/aks to add version stable/2024-05-01

### PR DESCRIPTION
**Pull request by FumingZhang**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by FumingZhang** [comment]
For failed CI [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/29535/checks?check_run_id=26632006060), only the last one is introduced in this new API version, `locations/{}/osOptions/default` is exactly the API path that is going to be deprecated and has received breaking change approval.

The rest already existed in the past (e.g., [202**3**-05-01](https://github.com/Azure/azure-rest-api-specs/pull/24379#issuecomment-1583963777)),
- [aks/stable/2017-07-01/containerService.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2017-07-01/containerService.json), which is deprecated and replaced by AKS (managedClusters).
- [aks/stable/2017-08-31/managedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2017-08-31/managedClusters.json), the missing API (`.../managedClusters/{}/accessProfiles/{}`) is deprecated and replaced by [ListClusterUserCredentials](https://docs.microsoft.com/rest/api/aks/managedclusters/listclusterusercredentials) or [ListClusterAdminCredentials](https://docs.microsoft.com/rest/api/aks/managedclusters/listclusteradmincredentials) according to the need.
- [aks/stable/2019-08-01/location.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2019-08-01/location.json), the missing API (`.../locations/{}/orchestrators`) is deprecated, and has been replaced by a new API `/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/kubernetesVersions` in [2023-03-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-03-01/managedClusters.json#L115) and [2023-03-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-03-02-preview/managedClusters.json#L115).
- [aks/stable/2019-04-30/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a2ddb53376bb6f561928229c8fb3afadbc93d2a4/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2019-04-30/openShiftManagedClusters.json), which is deprecated and replaced by [redhatopenshift](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/redhatopenshift/resource-manager).

image

**Comment by ramoka178** [comment]
Please confirm that https://eng.ms/docs/products/arm/rpaas/decommissioning/resource_type_deprecation is followed for removing the "/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/osOptions/default" API

**Comment by FumingZhang** [comment]
> Please confirm that https://eng.ms/docs/products/arm/rpaas/decommissioning/resource_type_deprecation is followed for removing the "/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/osOptions/default" API

Hey @ramoka178, we are not completely removing this resource type `locations/osOptions`, instead we are simply no longer supporting it in API versions starting with 2024-05-01 and I think this wiki may not be applicable.

**Comment by TimLovellSmith** [comment]
Still needs  BreakingChange-JavaScript-Sdk-Suppression-Approved

**Comment by FumingZhang** [comment]
Want to do another round of ARM review as we added a change in #29653 at the last minute

**Comment by TimLovellSmith** [comment]
@FumingZhang  Cool. Just one question about that: Is it a good idea having none by default?
Wouldn't being "secure by default" be a better idea?

**Review by madhura-np — APPROVED** [review]

**Pull request merged**
