### PR TITLE
Expose new SKUs for VMSS VPN and ER gateways

### PR DESCRIPTION
**Pull request by ritwikbasu**
Expose new SKUs for VMSS VPN and ER gateways

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by MikhailTryakhov — APPROVED** [review]
LGTM

**Comment by ravbhatnagar** [comment]
ARM review not needed. Looks like modelAsString is set to true. Question for SDK team - can SDK handle new enum values added to same api-version? @dsgouda

**Comment by dsgouda** [comment]
@ravbhatnagar in the SDK world (at least for C#) API versions need not always match the actual sdk version. So yes, one could technically bring in changes to the same API version and regenerate code for it. However, if for the sdk itself it could mean breaking changes which means RPs need to bump their versions and re publish their packages.
Hope this clarifies.
@shahabhijeet for further context.

**Comment by ritwikbasu** [comment]
@dsgouda, @shahabhijeet - Yes that is exactly what I planned to do. This is technically not a breaking change since we are not changing any API, nor removing any existing values. We are just adding new SKUs to the already existing ones that can be used by customers.

I plan to bump up the minor version of the Network SDK package to publish this change.

Please let me know if you see any issues with that.

**Comment by dsgouda** [comment]
@sergey-shandar please review and merge this PR at your convenience

**Review by sergey-shandar — COMMENTED** [review]
Approved.

**Pull request merged**
