### PR TITLE
Oracle.Database. Version 2023-09-01 stable

### PR DESCRIPTION
**Pull request by v-maksymm**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by v-maksymm** [comment]
This stable version completely based on already [merged Preview version ](https://github.com/Azure/azure-rest-api-specs/pull/29305) without any changes

**Comment by qiaozha** [comment]
> This stable version completely based on already [merged Preview version ](https://github.com/Azure/azure-rest-api-specs/pull/29305) without any changes

Should we make sure those preview PR comments are resolved before stable version PR merged ?

**Comment by ms-bogdan-rotaru** [comment]
> > This stable version completely based on already [merged Preview version ](https://github.com/Azure/azure-rest-api-specs/pull/29305) without any changes
> 
> Should we make sure those preview PR comments are resolved before stable version PR merged ?

Please take a decision whether you will be addressing those comments or not.

**Comment by v-maksymm** [comment]
@qiaozha @ms-bogdan-rotaru Thank you for your comments! We have to take these fixes for the next stable version to respect our GA date for first stable release.

**Comment by MSEvanhi** [comment]
@v-maksymm please follow the instructions to remove the 'ARMchangesrequested' abel from the PR so this gets requested. Nobody will review this until that's followed!

**Comment by kazrael2119** [comment]
please fix sdk tsp generation failure
image

**Comment by v-maksymm** [comment]
> @v-maksymm please follow the instructions to remove the 'ARMchangesrequested' able from the PR so this gets requested. Nobody will review this until that's followed!

Hi @MSEvanhi, I found out that I don't have permission to remove labels in azure-rest-api-spec (I have it for private repo).
I requested permission last week and still waiting for request approval.

**Comment by v-maksymm** [comment]
> please fix sdk tsp generation failure image

Fixed

**Comment by josefree** [comment]
Please ensure to respond the feedback to your TypeSpec in the PR of https://github.com/Azure/azure-rest-api-specs/pull/29305

**Comment by v-maksymm** [comment]
> Please ensure to respond the feedback to your TypeSpec in the PR of #29305

Hi @josefree thank you for your comment!
As I addressed comment earlier in that PR. We have to take these fixes for the next stable version to respect our GA date for first stable release. They are not critical for Oracle.Database RP operation.

**Comment by raych1** [comment]
Approved Go Sdk breaking change as this is the first GA version.

**Review by mentat9 — APPROVED** [review]

**Pull request merged**
