### PR TITLE
Add cg profile api v2

### PR DESCRIPTION
**Pull request by shivg7795**
Add CGProfile API specifications in a new version

### CODE REVIEW

**Comment by raosuhas** [comment]
can you please fix the Lint diff errors : https://github.com/Azure/azure-rest-api-specs/pull/30874/checks?check_run_id=31188511734

**Comment by raosuhas** [comment]
>           "$ref": "#/definitions/Resource"

use the tracked resource definition from common types and remove all other top level definitions from the object

---
Refers to: specification/containerinstance/resource-manager/Microsoft.ContainerInstance/preview/2024-11-01-preview/containerInstance.json:3348 in 9e43e2e. [](commit_id = 9e43e2e2afa147bdb377acb7b5b75f7099023401, deletion_comment = False)

**Comment by raosuhas** [comment]
>     "NGroupIdentity": {

use commontypes definition

---
Refers to: specification/containerinstance/resource-manager/Microsoft.ContainerInstance/preview/2024-11-01-preview/containerInstance.json:3353 in 9e43e2e. [](commit_id = 9e43e2e2afa147bdb377acb7b5b75f7099023401, deletion_comment = False)

**Comment by shivg7795** [comment]
> > ```
> >       "$ref": "#/definitions/Resource"
> > ```
> 
> use the tracked resource definition from common types and remove all other top level definitions from the object
> 
> Refers to: specification/containerinstance/resource-manager/Microsoft.ContainerInstance/preview/2024-11-01-preview/containerInstance.json:3348 in [9e43e2e](https://github.com/Azure/azure-rest-api-specs/commit/9e43e2e2afa147bdb377acb7b5b75f7099023401). [](commit_id = [9e43e2e](https://github.com/Azure/azure-rest-api-specs/commit/9e43e2e2afa147bdb377acb7b5b75f7099023401), deletion_comment = False)

The JSON is required by internal customers to see the swagger UI. Hence the references are limited to this file only. For future when we make this to public stable version then we can make these references to common types.

**Comment by raosuhas** [comment]
Can you please fix the newly introduced Lintdiff warnings : https://github.com/Azure/azure-rest-api-specs/pull/30874/checks?check_run_id=32564480702

**Comment by raosuhas** [comment]
could you also please fix the older comments I had provided before restarting the ARM review ?

**Pull request closed without merging**
