### PR TITLE
Add 2023-06-01-preview for Web PubSub

### PR DESCRIPTION
**Pull request by zackliu**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  In 2 month
  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  In 1 month
  6. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zackliu** [comment]
@ArcturusZhang The breaking changes are the same with previous preview version https://github.com/Azure/azure-rest-api-specs/pull/22948 So I think they have the same reason, and we can ignore them. Could you help to take a look

**Comment by ms-zhenhua** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SignalRService/signalR/{resourceName}/replicas/{replicaName}/skus": {

please also implement individual GET:
[https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html#plcy008-support-a-collection-get-and-individual-get-for-child-resource-types-even-singletons](https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html#plcy008-support-a-collection-get-and-individual-get-for-child-resource-types-even-singletons)

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-06-01-preview/signalr.json:1600 in 69df78f. [](commit_id = 69df78fe51252adb2dc6135d0dc3ef95cf94f638, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SignalRService/webPubSub/{resourceName}/replicas/{replicaName}/skus": {

please also implement individual GET:
[https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html#plcy008-support-a-collection-get-and-individual-get-for-child-resource-types-even-singletons](https://armwiki.azurewebsites.net/api_contracts/guidelines/policy.html#plcy008-support-a-collection-get-and-individual-get-for-child-resource-types-even-singletons)


---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-06-01-preview/webpubsub.json:1823 in 69df78f. [](commit_id = 69df78fe51252adb2dc6135d0dc3ef95cf94f638, deletion_comment = False)

**Comment by zackliu** [comment]
@ms-zhenhua This is a special API only for autoscale not a child resource. The individual api is not necessary for this api. It's also common practice for other services. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#enumerating-skus-for-an-existing-resource

**Comment by ms-zhenhua** [comment]
> @ms-zhenhua This is a special API only for autoscale not a child resource. The individual api is not necessary for this api. It's also common practice for other services. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#enumerating-skus-for-an-existing-resource

@zackliu - make sense. Will sign off after breaking change approved.

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #22948

**Comment by zackliu** [comment]
@ms-zhenhua Breaking changes approved

**Comment by zackliu** [comment]
@raych1 I think the sdk breaking changes are the same as https://github.com/Azure/azure-rest-api-specs/pull/22948#issuecomment-1477325611

**Comment by zedy-wj** [comment]
@msyyc - Please help check the python breaking changes.

**Comment by zedy-wj** [comment]
@qiaozha - Please help check the JS breaking changes.

**Comment by zackliu** [comment]
@zedy-wj Could you add person who can approve .net breaking changes.

**Comment by zedy-wj** [comment]
> @zedy-wj Could you add person who can approve .net breaking changes.

No need to process here, approved.

**Comment by zackliu** [comment]
@rkmanda Anything more that I need to do to merge this PR?

**Review by rkmanda — APPROVED** [review]
:shipit:

**Pull request merged**
