### PR TITLE
Adding Microsoft.DevSpaces Rest API spec 2018-06-01-preview

### PR DESCRIPTION
**Pull request by sanar-microsoft**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@sanar-microsoft has this been reviewed by ARM and the API review board?

**Comment by sanar-microsoft** [comment]
@jhendrixMSFT This RP was renamed from Microsoft.ConnectedEnvironment to Microsoft.DevSpaces and we had an API review meeting before the rename. @ravbhatnagar from ARM team has reviewed this new spec after the rename. There is also another PR in the private repo with -privatepreview suffix that got approved(PR #481 in private repo).

**Comment by jhendrixMSFT** [comment]
Thanks for the context this helps.  The service is publicly deployed?  You mentioned a rename, does this mean there is another swagger that needs to be deprecated?

**Comment by jhendrixMSFT** [comment]
Is the public preview service deployed?  I ask because the expectation is that when a swagger is merged into the public repo it's immediately ready for consumption by externals.

**Comment by sanar-microsoft** [comment]
No, the service is still deployed with old api-version. We still need to add this api-version to our manifest.

**Comment by jhendrixMSFT** [comment]
Got it.  Please update this PR once the service has been deployed.  I've updated the title to include "DO NOT MERGE" until it's ready.

**Comment by salameer** [comment]
HI @jhendrixMSFT this is clear from ARM, Please go ahead and merge @sanar-microsoft confirms that the service has been deployed

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
