### PR TITLE
Added the allowed values to $select, $expand and $filter queries unde…

### LINKED ISSUE #9130: Availability Set documentation error
https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/listbysubscription

```
GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/availabilitySets?api-version=2019-07-01&$expand=virtualMachines\$ref
```
I suspect this example has mistakes. I try it and get an error:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "The request URL is not valid.",
    "target": "$expand"
  }
}
```
If I change "\\" to "/", it works.
```
GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/availabilitySets?api-version=2019-07-01&$expand=virtualMachines/$ref
```

### PR DESCRIPTION
**Pull request by srcharug**
this fixes #9130

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Would it be too much for a fix of issue #9130 which is only complaining that the examples are not correct by changing those parameters from string to enum?
And this would introduce a lot of breaking changes in the downstream SDKs (parameter type changed from string to an enum type). 
Furthermore, I suppose the service may support more filter in the future, if we convert these into enums, when the service supports more filters in the future, you will have to add more entries for the enum and introduce breaking changes to the swagger in the meantime.
Could it just work to just modify the corresponding examples but leave the swaggers unchanged?

**Comment by srcharug** [comment]
As we need to mention the allowed values for the clarification of the customers, can we include them in the description without changing the type of the parameters?

@avirishuv Could you please clarify?

**Comment by avirishuv** [comment]
The intent of this proposed swagger update is simply to explain to customers how can they use the parameters $expand, $select, $filter, and what are allowed values for these. 
No changes needed on the type of parameters itself, but we just need to clearly document the usage & allowed values. Hope that helps, @srcharug

**Comment by srcharug** [comment]
Thanks for the clarification @avirishuv . Then, I will just make the changes to the description which does not effect the test cases/examples.

**Review by hyonholee — APPROVED** [review]

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @srcharug could you please also go through those examples?
For instance [this one](https://github.com/Azure/azure-rest-api-specs/blob/c51395497f99c4a7e0c4441cf245c7452693929d/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/examples/ListAvailabilitySetsInASubscription.json#L5), the value of `"$expand": "virtualMachines\\$ref"` seems it does not make much sense.

**Review by ArcturusZhang — CHANGES_REQUESTED** [review]
Hi @srcharug could you please also go through those examples?
For instance this one, the value of "$expand": "virtualMachines\\$ref" seems it does not make much sense.

And if you do not mind, I also modified the PR description to make this PR can fix the corresponding issue.

**Comment by srcharug** [comment]
Hi @ArcturusZhang, when we query for instance view of VMs in VMSS, we can apply combinations of $select and $expand fields to get different views of VMInstances. 
For example, if $select=instanceView&$expand=instanceView we get instance view of VMs,
if $expand=instanceView we get full view of VMs.

**Comment by ArcturusZhang** [comment]
Hi @srcharug I am suggesting we should also use "service-acceptable" parameters in the corresponding examples in addition to this change, for instance [this example](https://github.com/Azure/azure-rest-api-specs/blob/3adf23e0e1c74017dac7a500e0a10dddbb6c81c2/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/examples/ListAvailabilitySetsInASubscription.json#L5), and actually this was the file the original issue was complaining about.

And the same situation may happen to the examples of other api-versions, please change them too.

**Comment by srcharug** [comment]
I made the suggested changes. I was not able to understand that when you mentioned about the examples earlier

**Review by ArcturusZhang — APPROVED** [review]
LGTM 👍  thanks!

**Pull request merged**
