### PR TITLE
PDS APIs for GA.

### PR DESCRIPTION
**Pull request by pansharm-ms**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [x] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by heaths** [comment]
Here's a diff of the swagger from the previous preview:

```patch
 {
   definitions: {
     AccountModelBase: {
-      description: "Represents a purview account."
+      description: "Details of the purview account governing the requested resource."
       properties: {
         gatewayEndpoint: {
-          description: "Purview account gateway endpoint."
+          description: "Endpoint of the Purview account. This will be used by the RPs to call Purview APIs."
         }
         id: {
-          description: "Id of the purview account."
+          description: "ID of the Purview account."
         }
         location: {
-          description: "Region where purview account is created."
+          description: "Location (Region) of the Purview account."
         }
         name: {
-          description: "Name of the purview account."
+          description: "Name of the Purview account."
         }
         tenantId: {
-          description: "Tenant id of the purview account."
+          description: "Tenant ID of the Purview account."
         }
       }
     }
     Consent: {
-      description: "Consent information related to a resource."
+      description: "Consent information for the resource governed by purview."
       properties: {
         excludedScopes: {
-          description: "Child scopes that need to be excluded (optional)."
+          description: "List of scopes opted out of this consent."
         }
       }
     }
     DatasourcePreferencesResponse: {
-      description: "Provides the consent information for a data source."
+      description: "Response model for datasource preference API."
       properties: {
         frequency: {
-          description: "This represents the frequency at which the RPs will check for consent information."
+          description: "This is the timespan at which the RPs call this API at regular intervals."
         }
       }
     }
     ErrorModel: {
-      description: "Represents the error model."
+      description: "Default error model."
       properties: {
         code: {
-          description: "Service error code."
+          description: "Error code."
+          minLength: 1
         }
         details: {
-          description: "Granular errors (if any)."
+          description: "Error details."
         }
         message: {
+          minLength: 1
         }
         target: {
-          description: "Detailed error message."
+          description: "Error description."
         }
       }
     }
     ErrorResponseModel: {
-      description: "Represents the error response model."
+      description: "Default error response model."
     }
     PolicyElement: {
-      description: "Represents a policy element."
+      description: "Represents a policy, policy set or attribute rule."
       properties: {
         id: {
-          description: "Id of the policy element."
+          description: "ID of the policy element."
+          minLength: 1
         }
         kind: {
+          minLength: 1
         }
         updatedAt: {
+          minLength: 1
         }
       }
+      required: [
+        "id"
+        "kind"
+        "updatedAt"
+        "version"
+      ]
     }
     PolicyElementEventModel: {
-      description: "Represents a policy element event model."
+      description: "Represents the policy element event model."
       properties: {
         eventType: {
+          minLength: 1
         }
         id: {
-          description: "Id of the policy element."
+          description: "ID of the policy element."
+          minLength: 1
         }
         kind: {
+          minLength: 1
         }
         updatedAt: {
+          minLength: 1
         }
       }
+      required: [
+        "eventType"
+        "id"
+        "kind"
+        "updatedAt"
+        "version"
+      ]
     }
+    PolicyEventsResponseUpdated: {
+      description: "Response model for policy delta fetch API."
+      properties: {
+        syncToken: {
+          description: "This sync token represents the latest checkpoint for policies. Client need to pass this value while fetching subsequent delta changes."
+          minLength: 1
+          type: "string"
+        }
+        value: {
+          description: "List of policy elements."
+          items: {
+            $ref: "#/definitions/PolicyElementEventModel"
+          }
+          type: "array"
+        }
+      }
+      required: [
+        "syncToken"
+      ]
+      type: "object"
+    }
-    PolicyEventsResponse: {
-      description: "Represents the response for policy events API."
-      properties: {
-        count: {
-          description: "Count of elements in payload."
-          format: "int32"
-          type: "integer"
-        }
-        elements: {
-          description: "List of created/updated policy elements."
-          items: {
-            $ref: "#/definitions/PolicyElementEventModel"
-          }
-          type: "array"
-        }
-        syncToken: {
-          description: "Sync token represents the checkpoint upto which this policy elements list is updated. Client need to store this value and keep updating if PDS returns a new value. Call this API with the most recent value received."
-          type: "string"
-        }
-      }
-      type: "object"
-    }
+    PolicyResponseUpdated: {
+      description: "Response model for policy bulk fetch API."
+      properties: {
+        nextLink: {
+          description: "Link to fetch next set of policy elements."
+          type: "string"
+        }
+        syncToken: {
+          description: "This sync token represents the latest checkpoint for policies. Client need to pass this value while fetching subsequent delta changes using policy-events API."
+          type: "string"
+        }
+        value: {
+          description: "List of policy elements."
+          items: {
+            $ref: "#/definitions/PolicyElement"
+          }
+          type: "array"
+        }
+      }
+      type: "object"
+    }
-    PolicyResponse: {
-      description: "Represents the response for policy fetch API."
-      properties: {
-        count: {
-          description: "Count of elements in payload."
-          format: "int32"
-          type: "integer"
-        }
-        elements: {
-          description: "List of policy elements."
-          items: {
-            $ref: "#/definitions/PolicyElement"
-          }
-          type: "array"
-        }
-        nextLink: {
-          description: "Link with skip token to fetch next set of records. This is used in case of pagination."
-          type: "string"
-        }
-        syncToken: {
-          description: "Sync token represents the checkpoint upto which this policy elements list is updated. Client need to pass this value while fetching records using policyEvents API."
-          type: "string"
-        }
-      }
-      type: "object"
-    }
     Properties: {
-      description: "Consent properties."
+      description: "Consent details."
       properties: {
         dataUseGovernance: {
-          description: "Consent for data use governance."
+          description: "This value indicates whether the resource is enabled for data use governance."
         }
       }
     }
     Scanner: {
-      description: "Represents the collection of consent information for scanning service."
+      description: "Consent information for scanner service."
       properties: {
         classification: {
-          description: "Consent for classification discovery."
+          description: "This value indicates whether the resource is enabled for classification discovery."
         }
         metadata: {
-          description: "Consent for metadata discovery."
+          description: "This value indicates whether the resource is enabled for metadata discovery."
         }
       }
     }
   }
   info: {
-    version: "2022-11-01-preview"
+    version: "2023-01-01"
   }
   paths: {
     /datasource-preferences: {
       get: {
-        description: "Get Datasource Preferences for a given scope."
+        description: "Get Datasource Preferences for given scope."
         parameters: [
           {
-            description: "Scope."
+            description: "Id for any resource managed by Purview."
           }
-          {
-            description: "Is call from a Gondor client."
-            in: "query"
-            name: "isProjectGondor"
-            type: "boolean"
-          }
           ...
         ]
         responses: {
           default: {
-            description: "An unexpected error occurred"
+            description: "Error"
           }
         }
       }
     }
     /policy-elements: {
       get: {
         parameters: [
           {
-            description: "Scope."
+            description: "Id for any resource managed by Purview."
           }
           {
-            description: "The API Version."
+            description: "The PDS API Version."
           }
           {
-            description: "Optional value to filter policies based on hierarchy of resources. It is of type enum with possible values: AtScope, ChildrenScope, None, All"
+            description: "Filter supporting full OData syntax."
           }
         ]
         responses: {
           200: {
             schema: {
-              $ref: "#/definitions/PolicyResponse"
+              $ref: "#/definitions/PolicyResponseUpdated"
             }
           }
           default: {
-            description: "An unexpected error occurred"
+            description: "Error"
           }
         }
         x-ms-pageable: {
-          itemName: "elements"
         }
       }
     }
     /policy-events: {
       get: {
         parameters: [
           {
-            description: "Scope."
+            description: "Id for any resource managed by Purview."
           }
           {
-            description: "The sync token."
+            description: "This sync token represents the latest checkpoint for policies. Client need to pass this value while fetching subsequent delta changes."
           }
           ...
         ]
         responses: {
           200: {
             schema: {
-              $ref: "#/definitions/PolicyEventsResponse"
+              $ref: "#/definitions/PolicyEventsResponseUpdated"
             }
           }
           default: {
-            description: "An unexpected error occurred"
+            description: "Error"
           }
         }
       }
     }
   }
 }
```

Based on this, I see no reason not to sign off except that this PR targets main (BTW: always a good idea to create a separate topic branch since I see you changed `main` in your fork). Is this API ready? Going into `main` effectively means "done". See our [walkthrough](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/630/Walkthrough-Creating-a-new-service-specification-in-a-team).

**Review by heaths — CHANGES_REQUESTED** [review]
Mainly a question: should this really be targeting `main`? See my other comment for context.

**Comment by JeffreyRichter** [comment]
For consistency, we prefer Id instead of ID - perhaps this change can be made without breaking (at least in documentation).

**Comment by pansharm-ms** [comment]
> For consistency, we prefer Id instead of ID - perhaps this change can be made without breaking (at least in documentation).

Hi @heaths, @JeffreyRichter,
I have fixed the case for ID - changed it to Id at all places.

As far as branch is concerned, I am putting all changes in main as of now as I am the only person working on this. Also I will delete this repo once this branch is merged.

Please let me know if this is fine.

**Review by pansharm-ms — COMMENTED** [review]
Hi @heaths,

As far as branch is concerned, I am putting all changes in main as of now as I am the only person working on this. Also, I will delete this repo once this branch is merged.

Please let me know if this is fine.

**Comment by heaths** [comment]
> Hi @heaths,
> 
> As far as branch is concerned, I am putting all changes in main as of now as I am the only person working on this. Also, I will delete this repo once this branch is merged.
> 
> Please let me know if this is fine.

@pansharm-ms hat almost answers my question. Since you're the only one working on this, is the idea that you're done once this PR is merged? A feature branch is still a recommendation if your changes for a new version are _not_ "one and done". Once a spec is in main, it's meant to be immutable (there's some exceptions like for correctness, but should be rare).

**Pull request closed without merging**
