### PR TITLE
Fix for <a> tags that break documentation.

### PR DESCRIPTION
**Pull request by twitchax**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 
### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).

---

This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/610)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aaronroney__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by fearthecowboy** [comment]
I thought we were just going to remove links to MSDN completely?

**Comment by aaronroney** [comment]
Yes, we will be doing that, but not quite yet.

In the meantime, these links actively look bad in the documentation.

**Comment by amarzavery** [comment]
@fearthecowboy, @lmazuel - Any idea on why the CI is failing?

**Comment by fearthecowboy** [comment]
@azuresdkci  retest this please

**Comment by fearthecowboy** [comment]
@amarzavery I bumped the autorest version to fix it. Sorry, my fault.

**Comment by fearthecowboy** [comment]
Try and rerun the tests now.

**Comment by twitchax** [comment]
Can we re-run the build?

**Comment by fearthecowboy** [comment]
Yes yes it is my fault I will fix it in the morning sorry

...



On Thu, Oct 20, 2016 at 7:21 PM -0700, "Amar Zavery" <notifications@github.com<mailto:notifications@github.com>> wrote:


@fearthecowboy<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffearthecowboy&data=02%7C01%7Cgarretts%40microsoft.com%7C6c1e36150fc94690041008d3f958eeb2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636126132758343744&sdata=8Md66KOq9MxQ9jc1UXRc9yoVLy9XWHlDtiRQ7qSbdWU%3D&reserved=0>, @lmazuel<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmazuel&data=02%7C01%7Cgarretts%40microsoft.com%7C6c1e36150fc94690041008d3f958eeb2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636126132758343744&sdata=074b%2F4Hz9K31QGU2WXZJdUNFJIFIDO20nnINDr2UC9s%3D&reserved=0> - Any idea on why the CI is failing?

-

**Pull request merged**
