### PR TITLE
[ACS][Chat] Common SDK Version Bump

### PR DESCRIPTION
**Pull request by jpeng-ms**
# Data Plane API - Pull Request

We are updating the common SDK version in the swagger of an upcoming GA release.

## API Info: The Basics

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [X] GA release

### Change Scope

Common SDK version bump

### Viewing API changes

N/A

### Suppressing failures

N/A

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by mikekistler — COMMENTED** [review]
We generally discourge changing API definitions that have been merged to main, particularly GA versions.

You mention in the PR description that there are plans for an upcoming GA release -- it would be better to simply include this change with the other changes for that new release.

**Comment by jpeng-ms** [comment]
> We generally discourge changing API definitions that have been merged to main, particularly GA versions.
> 
> You mention in the PR description that there are plans for an upcoming GA release -- it would be better to simply include this change with the other changes for that new release.

Thank you @mikekistler we don't have a timeline for next GA release and since common SDK encourages us to use latest model as soon as possible we decided to update the current GA since we haven't officially release it yet (tentative release date is at the end of Q1 - Late March). Sorry for the confusion and we will keep in mind next time

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
