### PR TITLE
Correct the enum value for express route port macsec cipher

### PR DESCRIPTION
**Pull request by magodo**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [x] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by kairu-ms** [comment]
@magodo is it a s360 issue?

**Review by kairu-ms — APPROVED** [review]

**Comment by josefree** [comment]
@magodo could you attach the Swagger KPI ADO issue or links to error details, so that PR assignee can know the PR is addressing what issue.

**Comment by magodo** [comment]
@josefree No ADO issue for this, how do I create one?

**Comment by kairu-ms** [comment]
@MikhailTryakhov Please ask service team to confirm and review this change.

**Comment by magodo** [comment]
<details open>
<summary>GET https://management.azure.com/subscriptions/x-x-x-x/resourceGroups/mgd-erp/providers/Microsoft.Network/ExpressRoutePorts/magodo-erp?api-version=2020-05-01 HTTP/2.0</summary>
<pre>
{
    "id": "/subscriptions/x-x-x-x/resourceGroups/mgd-erp/providers/Microsoft.Network/expressRoutePorts/magodo-erp",
    "identity": {
        "type": "userAssigned",
        "userAssignedIdentities": {
            "/subscriptions/x-x-x-x/resourceGroups/mgd-erp/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mgd-identity": {}
        }
    },
    "location": "westus2",
    "name": "magodo-erp",
    "properties": {
        "allocationDate": "Saturday, January 9, 2021",
        "bandwidthInGbps": 10,
        "encapsulation": "Dot1Q",
        "etherType": "0x8100",
        "links": [
            {
                "id": "/subscriptions/x-x-x-x/resourceGroups/mgd-erp/providers/Microsoft.Network/expressRoutePorts/magodo-erp/links/link1",
                "name": "link1",
                "properties": {
                    "adminState": "Disabled",
                    "connectorType": "LC",
                    "interfaceName": "xe-0/1/9:1",
                    "macSecConfig": {
                        "cakSecretIdentifier": "...",
                        "cipher": "GcmAes256",
                        "cknSecretIdentifier": "..."
                    },
                    "patchPanelId": "F1-C2-R13-A - P12",
                    "provisioningState": "Failed",
                    "rackId": "F01C01-AH115",
                    "routerName": "exr01.cbr20"
                },
                "type": "Microsoft.Network/expressRoutePorts/links"
            },
            {
                "id": "/subscriptions/x-x-x-x/resourceGroups/mgd-erp/providers/Microsoft.Network/expressRoutePorts/magodo-erp/links/link2",
                "name": "link2",
                "properties": {
                    "adminState": "Disabled",
                    "connectorType": "LC",
                                  "interfaceName": "xe-0/1/9:1",
                    "macSecConfig": {
                        "cipher": "GcmAes128"
                    },
                    "patchPanelId": "F1-C3-R3-A - P12",
                    "provisioningState": "Failed",
                    "rackId": "F01C01-AH116",
                    "routerName": "exr02.cbr20"
                },
                "type": "Microsoft.Network/expressRoutePorts/links"
            }
        ],
        "mtu": "1500",
        "peeringLocation": "CDC-Canberra",
        "provisionedBandwidthInGbps": 0.0,
        "provisioningState": "Failed",
        "resourceGuid": "x-x-x-x"
    },
    "tags": {},
    "type": "Microsoft.Network/expressRoutePorts"
}      
</pre>
</details>

The problematic field is `cipher`.

**Review by kairu-ms — CHANGES_REQUESTED** [review]
This enum also exists in other api-versions. We should double check.

**Comment by magodo** [comment]
@kairu-ms The newer versions have the correct enum values.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by kairu-ms** [comment]
@MikhailTryakhov Can you ask service team to verify the response value in different api-versions. Thanks.

It's already fixed in new api-versions.
image

But for previous api-versions the value is still 'gcm-aes-128'
image

**Comment by kairu-ms** [comment]
I fond someone already create a [issue](https://github.com/Azure/azure-rest-api-specs/issues/7569) for this. Hi @naveenchekuri, can your checkout it?

**Comment by magodo** [comment]
@kairu-ms Would you please reopen this PR?

**Comment by magodo** [comment]
👀

**Comment by magodo** [comment]
@kairu-ms What is the review progress of this PR?

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
