### PR TITLE
fix: close EnterpriseKnowledgeGraph go fence

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@jhendrixMSFT I think this was a problem before, but I'm not sure why it still fails

**Comment by jhendrixMSFT** [comment]
Here's the relevant failure info from the build.
`
FATAL: System.InvalidOperationException: codegen for preview swagger Microsoft.EnterpriseKnowledgeGraph/preview/2018-12-03/EnterpriseKnowledgeGraphSwagger.json must be under a preview subdirectory
`
The output path was wrong due to incorrect tags.  Should be fixed now.

**Comment by nschonni** [comment]
Thanks @jhendrixMSFT! Looks like 2 files are being put under a double "preview" folder in the PR https://github.com/Azure/azure-sdk-for-go/pull/5192/files#diff-38e13a7f4d93f4d084cbbdfdc56733c7

**Comment by jhendrixMSFT** [comment]
The double-preview folder is a known issue with the preview profile.  It was designed before we moved preview packages under the preview directory.  :(

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
