### PR TITLE
[Hub Generated] Review request for Microsoft.Help to add version preview/2023-09-01-preview

### PR DESCRIPTION
**Pull request by sahilpwr**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/sahilpwr-help-Microsoft.Help-2023-09-01-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
We are adding new preview version for our DiscoverySolutions. We are changing the contract for Discovery Solutions in 2023-09-01-preview version with respect to the current stable version 2023-06-0.

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by sahilpwr** [comment]
This PR is exactly same as the PR https://github.com/Azure/azure-rest-api-specs-pr/pull/14344 opened for private repo. We already got breaking change approval for private repo PR.  @JeffreyRichter @mikekistler can you please approve the breaking change for public repo as well?

**Comment by sahilpwr** [comment]
@AzureRestAPISpecReview This PR is exactly same as the PR https://github.com/Azure/azure-rest-api-specs-pr/pull/14344 opened for private repo. Can we get approval for Public repo as well?

**Comment by mentat9** [comment]
@sahilpwr - You need to address the SDK breaking change labels before your PR can merge. See links/instructions in the first comment above.

**Comment by sahilpwr** [comment]
@AzureRestAPISpecReview  We opened [swagger PR](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F25604&data=05%7C01%7Csahilpawar%40microsoft.com%7Cf0dee447aa774399b7a908dbb9137f37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638307265644166682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oAj8q0YiF0FazC%2FBBbE%2FGNWnl7xYGd00eL8HbQMc%2FGw%3D&reserved=0) in public repo for 2023-09-01-preview version and we got ARM signoff. After signoff we added a field ‘[Guidance](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2Fc2956263c4068dd778cf56e257c0b1391bc234bf%2Fspecification%2Fhelp%2Fresource-manager%2FMicrosoft.Help%2Fpreview%2F2023-09-01-preview%2Fhelp.json%23L1530&data=05%7C01%7Csahilpawar%40microsoft.com%7Cf0dee447aa774399b7a908dbb9137f37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638307265644166682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a%2BfWqWaaPHhySYagpQTlRxLk7wEtPv3wapCFD%2Fe7cH0%3D&reserved=0)’ in the contract. 
Please let us know if we need to review the PR again before we merge to master.

**Comment by visingla-ms** [comment]
> @AzureRestAPISpecReview We already got ARM signoff. After signoff we added a field ‘[Guidance](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2Fc2956263c4068dd778cf56e257c0b1391bc234bf%2Fspecification%2Fhelp%2Fresource-manager%2FMicrosoft.Help%2Fpreview%2F2023-09-01-preview%2Fhelp.json%23L1530&data=05%7C01%7Csahilpawar%40microsoft.com%7Cf0dee447aa774399b7a908dbb9137f37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638307265644166682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a%2BfWqWaaPHhySYagpQTlRxLk7wEtPv3wapCFD%2Fe7cH0%3D&reserved=0)’ in the contract. Please let us know if we need to review the PR again before we merge to master.

It is fine, as I just checked new changes.

**Review by visingla-ms — APPROVED** [review]

**Comment by sahilpwr** [comment]
@visingla-ms @AzureRestAPISpecReview  how long does it take for documentation to go live after merge?

**Pull request merged**
