### PR TITLE
Release new version of DBE API - SKU changes

### PR DESCRIPTION
**Pull request by anponnet**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/202/Overall-Process-of-AME-Onboarding) for the workflow.
- [x] [Validation tools](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/84/Swagger-Validation-tools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/FAQ.md).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process]( https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review).

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
This PR is exposing /availableSKUs API. This ideally should align with the /skus API owned by ARM. but there are certain challenges/limitations in the current SKU API which are needed by this team. So, the path we have taken is to explore how ARM can address those limitations in a reasonable time frame. and then the RP will snap to the common/consistent SKU API. Having this in preview version is to make it easier to transition. 
This was discussed with Vlad/Gaurav and DBE team. Signing off from ARM side.

**Comment by yungezz** [comment]
hi @anponnet could  you pls fix CI failure?  then I'll merge the PR.

**Comment by yungezz** [comment]
ping @anponnet for update.

**Comment by yungezz** [comment]
hi @anponnet  are you still on this PR? could you pls fix CI failure?

**Comment by yungezz** [comment]
ping @anponnet

**Comment by anponnet** [comment]
@yungezz : I have fixed all the errors and checks are successful now. Can you please approve the PR? sorry for not addressing it for long. We were held up with some other work

**Comment by yungezz** [comment]
checked commits after ARMSignoff, they're new enum value adding, readme fixing. merge the PR.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
