### PR TITLE
Fixed required properties in TrafficAnalyticsProperties: networkWatce…

### PR DESCRIPTION
**Pull request by irrogozh**
…hr.json

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
@sergey-shandar I'm not sure if that's a breaking change. This is the diff for Net SDK based on this PR: https://github.com/number213/azure-sdk-for-net/commit/b1941744922e0c4f39163e09eae2c22e2e53079d
With other SDKs it should be fine too, since they are multi-API

**Comment by number213** [comment]
@anthony-c-martin could you please review this PR from ARM's side?

**Comment by number213** [comment]
@KrisBash could you please review this from ARM team's side?

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by number213** [comment]
Rebased PR to include fixes for CI that were merged into `network-august-branch` recently
@sergey-shandar, can we remove `potential-sdk-breaking-change` since ARM team approved this PR? It doesn't look like this PR will cause any breaking changes

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
