### PR TITLE
Review request for Microsoft.ContainerService to add version preview/2021-11-01-preview

### PR DESCRIPTION
**Pull request by bcho**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by bcho** [comment]
Hi @ArcturusZhang @akning-ms could you help review and merge this pr?  I think the .net and go sdk breaking change are known issues, right?

**Comment by mentat9** [comment]
>           "type": "boolean",

ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review).

Best approach is to choose a better property (e.g. isolationType: { "None", "Namespace" }). This type of property is easier for customers to understand and use. 

You can also have a string enum with True and False values which is still better than boolean, since enums allow adding values later without requiring a new API version.


---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3786 in aaaee72. [](commit_id = aaaee72c35ee915a88bedc71edd914f6fbe6507d, deletion_comment = False)

**Comment by mentat9** [comment]
>         "oidcIssuerProfile": {

ARM prefers acronyms to be spelled out unless very commonly known (e.g. IP, Url). In this case openIdConnectIssuerProfile would be preferred.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3769 in aaaee72. [](commit_id = aaaee72c35ee915a88bedc71edd914f6fbe6507d, deletion_comment = False)

**Comment by mentat9** [comment]
>         "enabled": {

If you spec this as string enum, it would allow for future values, e.g. status: [ Active, Disabled, FailoverOnly ] (not sure that value makes sense, but you get the idea) without an API version change. Not required, just a suggestion to consider.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:4452 in aaaee72. [](commit_id = aaaee72c35ee915a88bedc71edd914f6fbe6507d, deletion_comment = False)

**Comment by mentat9** [comment]
>     "CapacityReservationGroupID": {

Are these ARM Ids, or something specific to AKS?

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:5620 in aaaee72. [](commit_id = aaaee72c35ee915a88bedc71edd914f6fbe6507d, deletion_comment = False)

**Comment by bcho** [comment]
> > ```
> >       "type": "boolean",
> > ```
> 
> ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review.
> 
> Best approach is to choose a better property (e.g. isolationType: { "None", "Namespace" }). This type of property is easier for customers to understand and use.
> 
> You can also have a string enum with True and False values which is still better than boolean, since enums allow adding values later without requiring a new API version.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3786 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)

@Anumita could you help answer this? But for this question, I think it's similar to other properties in the managed cluster profile like `enableRBAC` / `enablePodSecurityPolicy` that, we just want to use a boolean here.

**Comment by bcho** [comment]
> > ```
> > "CapacityReservationGroupID": {
> > ```
> 
> Are these ARM Ids, or something specific to AKS?
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:5620 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)

@tonche could you help answer this?

**Comment by bcho** [comment]
> > ```
> >     "enabled": {
> > ```
> 
> If you spec this as string enum, it would allow for future values, e.g. status: [ Active, Disabled, FailoverOnly ] (not sure that value makes sense, but you get the idea) without an API version change. Not required, just a suggestion to consider.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:4452 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)

For the OIDC issuer feature, we only allowed user to toggle from disabled to enable, therefore, a boolean type is enough here.



> > ```
> >     "oidcIssuerProfile": {
> > ```
> 
> ARM prefers acronyms to be spelled out unless very commonly known (e.g. IP, Url). In this case openIdConnectIssuerProfile would be preferred.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3769 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)

I think for this case, we still want to use OIDC and `oidcIssuerProfile` here, because it's a very commonly known term under the usage context.

**Comment by tonche** [comment]
> 

This is an ARM resourceID

**Comment by tonche** [comment]
> 

This is an ARM resourceID with the following format:
"subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/CapacityReservationGroup/{CapacityReservationGroupName}"

**Comment by bcho** [comment]
> > ```
> > "CapacityReservationGroupID": {
> > ```
> 
> Are these ARM Ids, or something specific to AKS?
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:5620 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)

Quoting Tong's reply in below:

> > 
> 
> This is an ARM resourceID with the following format: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/CapacityReservationGroups/{CapacityReservationGroupName}"

**Comment by Anumita** [comment]
> > > ```
> > >       "type": "boolean",
> > > ```
> > 
> > 
> > ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review.
> > Best approach is to choose a better property (e.g. isolationType: { "None", "Namespace" }). This type of property is easier for customers to understand and use.
> > You can also have a string enum with True and False values which is still better than boolean, since enums allow adding values later without requiring a new API version.
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3786 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)
> 
> @Anumita could you help answer this? But for this question in generally, I think it's similar to other properties in the managed cluster profile like `enableRBAC` / `enablePodSecurityPolicy` that, we just want to use a boolean here.

Hey #mentat9 , For enableNamespaceResources we only allow user to toggle between false/true. It is similiar to the other boolean types in the profile like enableRbac / enablePodSecurity so we can go with boolean

**Comment by mentat9** [comment]
> > 
> 
> This is an ARM resourceID with the following format: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/CapacityReservationGroups/{CapacityReservationGroupName}"

Got it. Please consider using the property name capacityReservationGroupResourceId to disambiguate the term "ID".

**Comment by mentat9** [comment]
> > > ```
> > >       "type": "boolean",
> > > ```
> > 
> > 
> > ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review.
> > Best approach is to choose a better property (e.g. isolationType: { "None", "Namespace" }). This type of property is easier for customers to understand and use.
> > You can also have a string enum with True and False values which is still better than boolean, since enums allow adding values later without requiring a new API version.
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3786 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)
> 
> @Anumita could you help answer this? But for this question in generally, I think it's similar to other properties in the managed cluster profile like `enableRBAC` / `enablePodSecurityPolicy` that, we just want to use a boolean here.

Sure, I get it.This won't block ARM signoff. Please consider moving toward enums vs. booleans as you evolve your APIs.

**Comment by mentat9** [comment]
> > > ```
> > >     "enabled": {
> > > ```
> > 
> > 
> > If you spec this as string enum, it would allow for future values, e.g. status: [ Active, Disabled, FailoverOnly ] (not sure that value makes sense, but you get the idea) without an API version change. Not required, just a suggestion to consider.
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:4452 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)
> 
> For the OIDC issuer feature, we only allow user to toggle from disabled to enable, therefore, a boolean type is enough here.
> 
> > > ```
> > >     "oidcIssuerProfile": {
> > > ```
> > 
> > 
> > ARM prefers acronyms to be spelled out unless very commonly known (e.g. IP, Url). In this case openIdConnectIssuerProfile would be preferred.
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2021-11-01-preview/managedClusters.json:3769 in [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d). [](commit_id = [aaaee72](https://github.com/Azure/azure-rest-api-specs/commit/aaaee72c35ee915a88bedc71edd914f6fbe6507d), deletion_comment = False)
> 
> I think for this case, we still want to use OIDC and `oidcIssuerProfile` here, because it's a very commonly known term under the usage context.

This won't block ARM signoff.

**Comment by mentat9** [comment]
@bcho, I left some comments. One item still active: please take a look.

**Comment by tonche** [comment]
> > > 
> > 
> > 
> > This is an ARM resourceID with the following format: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/CapacityReservationGroups/{CapacityReservationGroupName}"
> 
> Got it. Please consider using the property name capacityReservationGroupResourceId to disambiguate the term "ID".

I checked the Capacity Reservation Group's RestAPI spec, they also use ID for resource ID.

CapacityReservationGroup
Specifies information about the capacity reservation group that the capacity reservations should be assigned to.

Currently, a capacity reservation can only be added to a capacity reservation group at creation time. An existing capacity reservation cannot be added or moved to another capacity reservation group.

CAPACITYRESERVATIONGROUP
Name	Type	Description
id	        string       Resource Id

Can we still use capacityReservationGroupID? Otherwise, we have to change both Swagger API and RP side code.

**Comment by bcho** [comment]
@mentat9 could you help review above reply? Thanks!

**Comment by raosuhas** [comment]
Hi Tong 

I would strongly suggest to do the rename. When customers write ARM templates to deploy resources , we would like them to have a consistent naming conventions across the board so that it makes it easy for them . When writing an ARM template it is much clearer that the full resource id is required to be passed in this case. Especially since in these cases , the customer would only get the error after the template has deployed and failed. If there are resources not following this pattern then it is a mistake and should be fixed or could be due to legacy reasons. This is a small change that can help customer usage a lot. 

That said I am adding the arm signed off since this is not something we would block the review on. You can still fix it and then it commit this checkin with my sign off.

---
In reply to: [997664596](https://github.com/Azure/azure-rest-api-specs/pull/17104#issuecomment-997664596) [](http://example.com/codeflow?ancestors=997664596,997664596)

**Comment by bcho** [comment]
> Hi Tong
> 
> I would strongly suggest to do the rename. When customers write ARM templates to deploy resources , we would like them to have a consistent naming conventions across the board so that it makes it easy for them . When writing an ARM template it is much clearer that the full resource id is required to be passed in this case. Especially since in these cases , the customer would only get the error after the template has deployed and failed. If there are resources not following this pattern then it is a mistake and should be fixed or could be due to legacy reasons. This is a small change that can help customer usage a lot.
> 
> That said I am adding the arm signed off since this is not something we would block the review on. You can still fix it and then it commit this checkin with my sign off.
> 
> In reply to: [997664596](https://github.com/Azure/azure-rest-api-specs/pull/17104#issuecomment-997664596)

Thanks for your review! I think Tong will address this issue in GA API. For now, we want to move forward with current fields as we had finished the rollout in our end.

--------

@akning-ms / @ArcturusZhang could you help review and merge this pr to main branch? Thanks in advance!

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
