### PR TITLE
typo: frontdoor/resource-manager/Microsoft.Network

### PR DESCRIPTION
**Pull request by nschonni**
- ruleset -> rule set
- Double word "the"

### CODE REVIEW

**Comment by dsgouda** [comment]
@eschwabe Please review

**Review by eschwabe — APPROVED** [review]

**Comment by eschwabe** [comment]
> @eschwabe Please review

LGTM

**Comment by nschonni** [comment]
@eschwabe did you mean to close this?

**Comment by eschwabe** [comment]
@nschonni Nope. Sorry about that.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
