### PR TITLE
Add InferencePools resource to 2024-10-01-preview 

### PR DESCRIPTION
**Pull request by paledger**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [x] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [X] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [X] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by paledger** [comment]
Waiting for this PR to help with presenting scoped changes better: https://github.com/Azure/azure-rest-api-specs/pull/30540

My changes are represented by this contract change PR: https://dev.azure.com/msdata/Vienna/_git/vienna/pullrequest/1455945?_a=files

**Comment by razvanbadea-msft** [comment]
>               "environmentId": {

is his of arm-id format?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:18601 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>                   "additionalProperties": {

Use of additionalProperties is not allowed for properties owned by the service. The only time its ok to use it is when the properties are pass thru (user defined) and not subject to any validations. Please make this an array or provide an explanation for why you need this.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:18609 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>               "modelId": {

is the url format applicable here?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:18637 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>                       "description": "The Two Sample Kolmogorov-Smirnov Test (two-sample Kâ€“S) metric."

is this intended? 

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:22123 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>                       "description": "The Two Sample Kolmogorov-Smirnov Test (two-sample Kâ€“S) metric."

is this as intended

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:22224 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>               "properties": {

Use of additionalProperties is not allowed for properties owned by the service. The only time its ok to use it is when the properties are pass thru (user defined) and not subject to any validations. Please make this an array or provide an explanation for why you need this.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:23228 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>           "post": {

shouldnt this be a get?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:9898 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>                       "$ref": "./examples/Workspace/InferenceGroup/getStatus.json"

are the example files added?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:9951 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by paledger** [comment]
> > ```
> >           "environmentId": {
> > ```
> 
> is his of arm-id format?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:18601 in [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b). [](commit_id = [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b), deletion_comment = False)

This is expected to be in Azure Machine Learning asset ID format. I updated the examples to show what this format looks like. For environment id: azureml://registries/test-registry/models/enginefeed/versions/1. For model id, it is similar: azureml://registries/test-registry/models/modelabc/versions/1

**Comment by paledger** [comment]
> > ```
> >                   "$ref": "./examples/Workspace/InferenceGroup/getStatus.json"
> > ```
> 
> are the example files added?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:9951 in [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b). [](commit_id = [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b), deletion_comment = False)

Added examples

**Comment by paledger** [comment]
> > ```
> >       "post": {
> > ```
> 
> shouldnt this be a get?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:9898 in [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b). [](commit_id = [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b), deletion_comment = False)

For GetStatus APIs and for the DeltaModel APIs (modify, getStatus, listDeltaModels), we use POST because it is not just a state DB call. It requires an action for us to compute the current status of the resource. There is a chance it will take longer than the ARM GET call requirement. I used this for some reference: https://armwiki.azurewebsites.net/rpaas/rpaasextensionapi.html#extensions-available-for-post-action

**Comment by paledger** [comment]
> additionalProperties



> > ```
> >           "properties": {
> > ```
> 
> Use of additionalProperties is not allowed for properties owned by the service. The only time its ok to use it is when the properties are pass thru (user defined) and not subject to any validations. Please make this an array or provide an explanation for why you need this.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:23228 in [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b). [](commit_id = [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b), deletion_comment = False)

These properties are immutable dictionary that user provides, it is completely pass-through and we do no validation on it. This is a standard for Azure Machine Learning resources, to have this pass-through property bag.

**Comment by paledger** [comment]
> The Two Sample Kolmogorov-Smirnov Test (two-sample Kâ€“S) metric.

These descriptions were not added in my changes, they already existed.

**Comment by razvanbadea-msft** [comment]
> > The Two Sample Kolmogorov-Smirnov Test (two-sample Kâ€“S) metric.
> 
> These descriptions were not added in my changes, they already existed.

this is from interation 1
image

**Comment by razvanbadea-msft** [comment]
Swagger SemanticValidation failed with missing example file.

**Comment by razvanbadea-msft** [comment]
>                   "additionalProperties": {

This can be converted in an array

---
In reply to: [2355480161](https://github.com/Azure/azure-rest-api-specs/pull/30531#issuecomment-2355480161) [](http://example.com/codeflow?ancestors=2355480161)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:18609 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>               "properties": {

ARM is trying to reduce instances of unschematized APIs to make it easier for consumers of those APIs to understand them and use them reliably, not to mention provide better support in the various SDKs.

You should attend ARM modeling office hours to see if there are better options for you use case scenario

---
In reply to: [2355511204](https://github.com/Azure/azure-rest-api-specs/pull/30531#issuecomment-2355511204) [](http://example.com/codeflow?ancestors=2355511204)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:23228 in 7cb9771. [](commit_id = 7cb977146e827079ef65b84d46fab8040ed44a7b, deletion_comment = False)

**Comment by paledger** [comment]
> Swagger SemanticValidation failed with missing example file.

Updated, SemanticValidation and ModelValidation passing

**Comment by paledger** [comment]
> > ```
> >           "properties": {
> > ```
> 
> ARM is trying to reduce instances of unschematized APIs to make it easier for consumers of those APIs to understand them and use them reliably, not to mention provide better support in the various SDKs.
> 
> You should attend ARM modeling office hours to see if there are better options for you use case scenario
> 
> In reply to: [2355511204](https://github.com/Azure/azure-rest-api-specs/pull/30531#issuecomment-2355511204)
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/mfe.json:23228 in [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b). [](commit_id = [7cb9771](https://github.com/Azure/azure-rest-api-specs/commit/7cb977146e827079ef65b84d46fab8040ed44a7b), deletion_comment = False)

OK I updated to what you recommended IList<KeyValuePair<string, string>>, including examples.

**Comment by razvanbadea-msft** [comment]
You need to fix the Swagger PrettierCheck for some example files. I will sign this off to speed things up as we discussed in office hours, but be aware that for merging the check must be fixed first.

**Review by raushan2016 — APPROVED** [review]

**Review by ZhidaLiu — APPROVED** [review]

**Pull request merged**
