### PR TITLE
add network 2019-02-01 to Go SDK

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by vladbarosan** [comment]
seems the CI is failling for Go as it needs more memory

**Comment by jhendrixMSFT** [comment]
I suspect this is due largely to the number of packages being built for network.  @MikhailTryakhov                                         are all of the packages being built still supported?

**Review by vladbarosan — APPROVED** [review]

**Comment by vladbarosan** [comment]
@sarangan12  , @sergey-shandar  can we increase the memory allowed here ?

**Comment by jhendrixMSFT** [comment]
We can add more memory for now but it's an arms-race.  If we need to support an ever-growing list of batches then I think changes will need to be made in autorest.  @fearthecowboy can you please comment on this?

**Comment by jhendrixMSFT** [comment]
Oh right this is coming from the container that builds the SDK.  @lmazuel how do we increase the available memory?

**Comment by fearthecowboy** [comment]
You can set an environment variable: `NODE_OPTIONS=--max-old-space-size:16384` and you will give AutoRest some breathing room.

We're working on a longer-term solution

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT 👋🏻 out of interest is it possible to re-run this generator? whilst this has been merged it's not appeared in the Go SDK (master/latest) from what I can tell

**Comment by jhendrixMSFT** [comment]
It's there in v28.0.0.  There was a problem with generation in the PR due to the container running out of memory so it was generated/added in a separate commit.
https://github.com/Azure/azure-sdk-for-go/tree/master/services/network/mgmt/2019-02-01/network

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT 🤦‍♂ sorry/thanks - I was checking the Networking SDK for something that's in the DNS SDK; I'll send a PR to generate the missing SDK

**Pull request merged**
