### PR TITLE
ApiManagement : 2024-05-01 stable api-version release

### PR DESCRIPTION
**Pull request by solankisamir**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by ramoka178** [comment]
To confirm: I do not see any swagger changes in the PR. Its only an API version bump. Is this the expectation of the PR ?

**Comment by solankisamir** [comment]
> To confirm: I do not see any swagger changes in the PR. Its only an API version bump. Is this the expectation of the PR ?

Yes, no changes in api surface. We just want to release a stable api-version now.

**Comment by solankisamir** [comment]
> Hi @solankisamir, please rename the SkuType in apigateway.json(please use a more appropriate name), it conflicts with the one in [apimdeployment.json](https://github.com/Azure/azure-rest-api-specs/blob/apimanagement-2024-05-01-release/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimdeployment.json#L930), their enumeration values ​​are inconsistent.
> 
> The following places need to be modified:
> 
> * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L391
> * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L570
> * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L614

@Alancere The 2 skuType are for different top level resources. 

One is for `Microsoft.ApiManagement/service` and other is for `Microsoft.ApiManagement/gateways`

**Comment by Alancere** [comment]
> > Hi @solankisamir, please rename the SkuType in apigateway.json(please use a more appropriate name), it conflicts with the one in [apimdeployment.json](https://github.com/Azure/azure-rest-api-specs/blob/apimanagement-2024-05-01-release/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimdeployment.json#L930), their enumeration values ​​are inconsistent.
> > The following places need to be modified:
> > 
> > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L391
> > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L570
> > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L614
> 
> @Alancere The 2 skuType are for different top level resources.
> 
> One is for `Microsoft.ApiManagement/service` and other is for `Microsoft.ApiManagement/gateways`

Understood, but `SkuType` has the same name under Microsoft.ApiManagement, which will cause one of the enum values ​​to be incomplete when generating the Go SDK.

**Comment by solankisamir** [comment]
> > > Hi @solankisamir, please rename the SkuType in apigateway.json(please use a more appropriate name), it conflicts with the one in [apimdeployment.json](https://github.com/Azure/azure-rest-api-specs/blob/apimanagement-2024-05-01-release/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimdeployment.json#L930), their enumeration values ​​are inconsistent.
> > > The following places need to be modified:
> > > 
> > > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L391
> > > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L570
> > > * https://github.com/Azure/azure-rest-api-specs/blob/035cd70ebdb9c27ab9d965c995667cff217fd150/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apigateway.json#L614
> > 
> > 
> > @Alancere The 2 skuType are for different top level resources.
> > One is for `Microsoft.ApiManagement/service` and other is for `Microsoft.ApiManagement/gateways`
> 
> Understood, but `SkuType` has the same name under Microsoft.ApiManagement, which will cause one of the enum values ​​to be incomplete when generating the Go SDK.

@Alancere I have renamed one of the SkuType variables. But I could not locate the exception stack in any of the pipelines. How did you identify this?

**Comment by kazrael2119** [comment]
> * SkuType

@solankisamir same issue in https://github.com/Azure/azure-rest-api-specs/blob/234890335602a07555815b66aa334a848800f445/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/definitions.json#L8302-L8312 and https://github.com/Azure/azure-rest-api-specs/blob/234890335602a07555815b66aa334a848800f445/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/apimgatewayConfigConnections.json#L247-L265

**Comment by solankisamir** [comment]
@kazrael2119 I have fixed the issue in the newer resource, `apigatewayconfigConnection` to avoid conflict. Can you please take a look again?

**Comment by solankisamir** [comment]
@kazrael2119 did you notice any other issues?

**Comment by solankisamir** [comment]
@weidongxu-microsoft can you please take a look at the SDK breaking change for Java? We are blocked

**Review by VitaliyKurokhtin — APPROVED** [review]

**Review by vidishamsft — APPROVED** [review]

**Review by bjmcabee — APPROVED** [review]

**Pull request merged**
