### PR TITLE
New spec for api-version 2017-03-15-preview

### PR DESCRIPTION
**Pull request by sw47**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR. 

Note, there were some errors produced by Validation tools but I don't believe they applicable since my change is very minor (only added Features property on the Workspace for new the api-version, we need the new version because ARM requires the new version). I mainly referenced work done from following PR: https://github.com/Azure/azure-rest-api-specs/pull/662.

### CODE REVIEW

**Comment by sw47** [comment]
@haitch - please review

**Comment by anuchandy** [comment]
@sw47 Please see our contribution guideline section  https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure, this will make the review process faster.

1.	Copy over all the files from `2015-11-01-preview` to `2017-03-15-preview` folder.
2.	Commit this change as `git commit -n “Initial commit”
3.	Now make changes that are relevant for new api-version `2017-03-15-preview`
4.	Now commit the changes “Changes for new api version 2017-03-15-preview”
5.	Push the changes to your fork (git push origin <branch-name>)
6.	Send a PR

**Review by anuchandy — CHANGES_REQUESTED** [review]
Please see the comments.

**Comment by sw47** [comment]
@anuchandy  - addressed the comment. Closing this PR, please refer to this one one: https://github.com/Azure/azure-rest-api-specs/pull/1791

**Pull request closed without merging**
