### PR TITLE
Fixed S360 issues related to ARM & SDK swagger linting errors for Microsoft.Solutions.

### PR DESCRIPTION
**Pull request by vayada**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by JeffreyRichter — APPROVED** [review]

**Comment by vayada** [comment]
@raych1,  Can you please check this and approve if no comments. As changes in this PR were flagged as breaking change so i have already discussed with Jeffrey for breaking change and he approved it.

Changes in this PR were made to fix S360 issues available [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Finfras360details.azurewebsites.net%2Fdefault%3FerrorId%3D4D2357C0-F4D8-480A-A77E-076822CFD9A3&data=02%7C01%7CVarun.Yadav%40microsoft.com%7C75573c3c7b0f4e48641808d85aa028d0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637358991223546255&sdata=qiyqPbfHVNomAlGaKRMVcuPH%2FPc7j%2BP9dddsBbdYxIo%3D&reserved=0).

**Comment by raych1** [comment]
> @raych1, Can you please check this and approve if no comments. As changes in this PR were flagged as breaking change so i have already discussed with Jeffrey for breaking change and he approved it.
> 
> Changes in this PR were made to fix S360 issues available [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Finfras360details.azurewebsites.net%2Fdefault%3FerrorId%3D4D2357C0-F4D8-480A-A77E-076822CFD9A3&data=02%7C01%7CVarun.Yadav%40microsoft.com%7C75573c3c7b0f4e48641808d85aa028d0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637358991223546255&sdata=qiyqPbfHVNomAlGaKRMVcuPH%2FPc7j%2BP9dddsBbdYxIo%3D&reserved=0).
@vayada, the lintDiff failures also need to be fixed since they're also recorded as lint KPI.

**Comment by raych1** [comment]
@jianyexi , can you double check if lintDiff failures are ok to ignore in this PR?

**Comment by vayada** [comment]
> > @raych1, Can you please check this and approve if no comments. As changes in this PR were flagged as breaking change so i have already discussed with Jeffrey for breaking change and he approved it.
> > Changes in this PR were made to fix S360 issues available [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Finfras360details.azurewebsites.net%2Fdefault%3FerrorId%3D4D2357C0-F4D8-480A-A77E-076822CFD9A3&data=02%7C01%7CVarun.Yadav%40microsoft.com%7C75573c3c7b0f4e48641808d85aa028d0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637358991223546255&sdata=qiyqPbfHVNomAlGaKRMVcuPH%2FPc7j%2BP9dddsBbdYxIo%3D&reserved=0).
> > @vayada, the lintDiff failures also need to be fixed since they're also recorded as lint KPI.

I have already fixed all S360 issues reported till now. These lintdiff failures are not S360 issues for us now. So, can you please check it.

**Comment by raych1** [comment]
@ArcturusZhang , could you check if the SDK Go failures?

**Comment by ArcturusZhang** [comment]
@raych1 The Go Generation failure should be good to ignore - I have made some changes to the bad output-folders and this is a false alarm which would be resolved very soon

**Review by raych1 — APPROVED** [review]

**Pull request merged**
