### PR TITLE
Delete 2022-03-01 api version

### PR DESCRIPTION
**Pull request by wngjian4814**
Delete the dataplane 2022-03-01 preview api version.

We have issued a notification to customers and started populating the azure-deprecating header for 90 days of notice ending.

This preview API version doesn't last 1 year.

### CODE REVIEW

**Comment by wngjian4814** [comment]
We are going to remove 2022-03-01 preview API, so I deleted that folder directly. I'm not sure why I got a **Swagger Breaking Change** alert. @mikekistler, @chrissmiller, If you have a chance, would greatly appreciate your review for the breaking change alert.

**Comment by mikekistler** [comment]
Preview versions can stop working 90 days after a newer API version is released. It's not necessary to delete the API version from the repo, but there's nothing to say you can't, so I've added Approved-BreakingChange.

**Comment by wngjian4814** [comment]
Thanks @mikekistler, truly appreciate your help!

**Comment by wngjian4814** [comment]
@stewartadam , would appreciate to take a look, thanks!

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
