### PR TITLE
Update Azure Database Migration Service to add Managed Instance target

### PR DESCRIPTION
**Pull request by hitenjava**
Corresponding pull request for the private repo - https://github.com/Azure/azure-rest-api-specs-pr/pull/391

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@hitenjava  It looks like there is a previous version [`2017-11-15-preview`] of the new swagger `datamigration.json` [`2018-03-15-preview`]. 

In order to make the review effective and to ensure a clean repo commit history can you follow below steps? [This step is documented in our contribution guidelines, you can find this link is pasted in the checklist of every PR, see [this](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure) section of contribution guidline ]


0. Close this PR
1.	Copy over ALL the files from [2017-11-15-preview](https://github.com/hitenjava/azure-rest-api-specs/tree/d01963cd1e4cc998e6458c7d0fb0d47f8956b221/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2017-11-15-preview) to `2018-03-15-preview` directory.
2.	Commit this change as `git commit -n "Copying over 2017-11-15-preview files to 2018-03-15-preview"`
3.	Now make changes that are relevant for new api-version `2018-03-15-preview`. In your case, you will have to simply overwrite the files with the changes that you made (since you would have them saved.)
4.	Now commit the changes `git commit -m "Changes for new API version 2018-03-15-preview"`
5.	Push the changes to your fork (`git push origin <branch-name>`)
6.	Send a PR to `master` from your fork

This way both ARM and SDK reviewers can go to second commit and see the update specific to new api-version. Just make sure the second commit shows the diff correctly.

@sergey-shandar FYI as you reviewed this in the private repo.

**Comment by anuchandy** [comment]
@hitenjava sorry for the inconvience, but i'm just trying to ensure your RPs swagger will continue to have a clean commit history, which will help all of us in future to track what changes went in for new api versions. 

Once you open the PR, will jump in and unblock you ASAP.

**Comment by hitenjava** [comment]
@anuchandy - That makes sense. It is a good suggestion.

**Comment by anuchandy** [comment]
@hitenjava i'm closing this PR as we agreed on having a new PR that conforms to above requirements.

**Pull request closed without merging**
