### PR TITLE
Introduce API version 2020-06-01

### PR DESCRIPTION
**Pull request by naveedaz**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
Please review Linter errors and warnings. Specific errors below.

❌ R3016 - DefinitionsPropertiesNamesCamelCase | Property named: 'trigger_url', for definition: 'FunctionSecrets' must follow camelCase style. Example: 'trigger_url'.New: Microsoft.Web/stable/2020-06-01/WebApps.json#L21924
-- | --
❌ R4005 - UniqueXmsEnumName | Must not have duplicate name of x-ms-enum extension , make sure every x-ms-enum name unique. The duplicate x-ms-enum name is managedserviceidentitytypeNew: Microsoft.Web/stable/2020-06-01/WebApps.json#L20350
❌ R4005 - UniqueXmsEnumName | Must not have duplicate name of x-ms-enum extension , make sure every x-ms-enum name unique. The duplicate x-ms-enum name is managedserviceidentitytypeNew: Microsoft.Web/stable/2020-06-01/WebApps.json#L22391

**Comment by naveedaz** [comment]
@chiragg4u The issue below is not a new issue. It existed in previous API version too. The property is not owned by the App service control plane but the functions runtime. The API surface just fwds the request. 
Property named: 'trigger_url', for definition: 'FunctionSecrets' must follow camelCase style. Example: 'trigger_url'.New: Microsoft.Web/stable/2020-06-01/WebApps.json#L21924

**Comment by chiragg4u** [comment]
Please review all linter errors and warnings.

**Comment by weidongxu-microsoft** [comment]
`DefinitionsPropertiesNamesCamelCase` can be suppressed if it is maintained by function app service. Though it still better to @ them so that they know about it, and can schedule possible fix in next version (or better, even in this same version).

**Comment by naveedaz** [comment]
@mathewc The ask here is to change the property name from trigger_url to triggerUrl in the /admin/host/synctriggers fx runtime API. Please add a tracking item for future work. 

@weidongxu-microsoft I will add a suppression to unblock for now.

**Comment by naveedaz** [comment]
@weidongxu-microsoft @chiragg4u Please review and merge.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Change
https://github.com/Azure/azure-rest-api-specs/compare/8f60822e7d75ce9ceba1269bb6da1ba74149c562..d16b3c43b15d03e41172dda4ca0d110d61c7454f?expand=1

**Comment by chiragg4u** [comment]
While adding new version the recommendation is to copy the existing version into new directory structure for first commit and then push new changes for easy review.

**Comment by chiragg4u** [comment]
Looks like you've just copied the files into new version in this case no formal review required. In case there are changes where you require ARM API review please update the PR with the above recommendation for easy review,

**Pull request merged**
