### PR TITLE
Fix discriminator issues in storagecache 2020-03-01

### PR DESCRIPTION
**Pull request by ArcturusZhang**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Please do not merge this PR until the service team approved this. Thanks

**Comment by romahamu** [comment]
Looks good, thank you.

**Review by lirenhe — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
@ArcturusZhang and others

It's a bit concerning to see a breaking change in a stable version of Open API specs without any explanation. Would you be so kind as to explain why this change was made and what was the process of approving the breakage?

**Comment by ArcturusZhang** [comment]
Hi @mikhailshilkov this breaking change is to revert one problematic breaking change introduced by #8606 .

In this PR, we nullified the problematic part - which is a breaking change when introduced in, and hence to get rid of it will cause another breaking change.

If we compare the content in this PR with a version before PR #8606, there should be no breaking changes.

**Pull request merged**
