### PR TITLE
Fix AppInsights x-ms-parameter-location

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by lmazuel** [comment]
@d3r3kk We added some rules in our CI, and now `"x-ms-parameter-location"` is a required parameter for all global parameter.
I tried to fix the Swagger to fix the CI, but would appreciate if you confirm this is the correct fix in your scenario.
Thank you!

**Comment by d3r3kk** [comment]
This looks correct to me, let me ask the experts on the team if they can look at it to confirm.

**Comment by lmazuel** [comment]
@AutorestCI help

**Comment by lmazuel** [comment]
@AutorestCI regenerate

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Comment by lmazuel** [comment]
Got SKype approval from @frankguodongchen as well, merging

**Pull request merged**
