### PR TITLE
Updated VNet Gateways operations: Fix for #4642

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@EvgenyAgafonchikov could you update your branch with the latest changes from `network-february-release` ?

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
@EvgenyAgafonchikov  why do you make changes in old api versions (like ```2018-11-01```). this is not needed, please revert

**Comment by EvgenyAgafonchikov** [comment]
@MikhailTryakhov, per issue description it is required for older API versions too, please review https://github.com/Azure/azure-rest-api-specs/issues/4642

**Comment by MikhailTryakhov** [comment]
@EvgenyAgafonchikov but we never do fixes in older version. please apply to the latest only, no need to apply changes to the previous one. please revert

**Comment by EvgenyAgafonchikov** [comment]
Hi @lmazuel, could you please share the reason for updating older API versions or is it good to update the latest only?
SDKs for older API version are unlikely to be generated, so changes wouldn't be shared this way.

**Comment by lmazuel** [comment]
@EvgenyAgafonchikov SDK for old versions are generated at each release for most language (Python, Go, Ruby, etc.), to support Azure Stack or national cloud that don't use the latest API version. Also, we have customers that sticks API version (this is a parameter in the constructor for these languages).

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@MikhailTryakhov let me know about your decision.

**Review by MikhailTryakhov — APPROVED** [review]

**Comment by EvgenyAgafonchikov** [comment]
@sergey-shandar, approval from @MikhailTryakhov was received, please take a look.

**Comment by MikhailTryakhov** [comment]
closed due to milestone was missed. please retarget to newer monthly branch when it's ready

As for fixes applied, we're currently decided to make hotfixes (not parameters renaming) in all the older API versions because of Azure Stack first of all

@lmazuel  can you please help with the latest Azure Stack API version in use? That might be minimal API version to update...

**Comment by sergey-shandar** [comment]
@EvgenyAgafonchikov @MikhailTryakhov could we update `nework-march-release` to the latest canges?

**Comment by number213** [comment]
@sergey-shandar opened PR to sync NRP branch: https://github.com/Azure/azure-rest-api-specs/pull/5464

**Comment by sergey-shandar** [comment]
@number213 For some reason it still shows a lot of irrelevant changes, such as changes in `travic-CI`.

**Comment by sergey-shandar** [comment]
@EvgenyAgafonchikov @number213  could we also update the branch to the latest changes from `network-march-release`?

**Comment by number213** [comment]
@sergey-shandar rebased this PR, please take a look

**Pull request merged**
