### PR TITLE
[T2] compute - duplicated schemas

### PR DESCRIPTION
**Pull request by 00Kai0**
@zikalino compute is fixed.

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @00Kai0 could you please fix the CI failures? 
Since in this PR, a lot of properties are referencing the definition elsewhere, some inconsistency of description are also introduced. This is blocking the generation of go SDK. Could you please also fix this?

**Comment by 00Kai0** [comment]
@ArcturusZhang ok, This dup schems problem needs to be discussed. Now just keep this pr opening.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang ok, This dup schems problem needs to be discussed. Now just keep this pr opening.

I tagged this PR "Do not merge". Please let me know if there are any updates about this.

**Comment by zikalino** [comment]
@ArcturusZhang I think this PR should be ok to merge. I have generated Python SDK with and without change, and it doesn't cause any differences in generated SDK.
Seems Go SDK is failing due to some other reason.

**Comment by ArcturusZhang** [comment]
Well, I am not sure why this happens....
Hi @jhendrixMSFT could you please take a look at the failure of go SDK generation?

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang here's a snippet from the error log, the TL;DR is there's duplicate definitions of a type with mismatched description.  I didn't look through the entire log so I don't know if this is the only type.  Also note this isn't unique to Go as the error comes from the Autorest front-end.

```
[AutoRest] Failure during batch task - {"tag":"package-2018-10-01"} -- Error: '$.definitions.WindowsConfiguration.properties.enableAutomaticUpdates.description' has incompatible values (---
[AutoRest]   -
[AutoRest]   Indicates whether virtual machine is enabled for automatic Windows updates.
[AutoRest]   Default value is true. 

 For virtual machine scale sets, this property
[AutoRest]   can be updated and updates will take effect on OS reprovisioning.
[AutoRest] , ---
[AutoRest] Indicates whether virtual machine is enabled for automatic updates.
[AutoRest] )..
[AutoRest]   Error: '$.definitions.WindowsConfiguration.properties.enableAutomaticUpdates.description' has incompatible values (---
[AutoRest]   -
[AutoRest]   Indicates whether virtual machine is enabled for automatic Windows updates.
```

**Comment by ArcturusZhang** [comment]
Yeah, actually I do not quite find the other description that is conflicting with the one in `specification\compute\resource-manager\Microsoft.Compute\stable\2018-10-01\compute.json\#definitions\WindowsConfiguration\enableAutomaticUpdates`, could you please give us some guide about this here? @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
The tag being built is `package-2018-10-01` which includes several swaggers.  My guess is that at least two of them define a type named `WindowsConfiguration` that are almost identical sans the description of `enableAutomaticUpdates`.

**Comment by ArcturusZhang** [comment]
> The tag being built is `package-2018-10-01` which includes several swaggers. My guess is that at least two of them define a type named `WindowsConfiguration` that are almost identical sans the description of `enableAutomaticUpdates`.

Well I did some search on this, but found that no other file in the `input-file`s of tag `package-2018-10-01` has declaration of `WindowsConfiguration`.
But tag `package-2018-10-01` is referencing `Microsoft.Compute/stable/2018-06-01/gallery.json`
and `Microsoft.Compute/stable/2018-06-01/disk.json`, the file [compute.json](https://github.com/00Kai0/azure-rest-api-specs/blob/bfd8230c3ce3c38f2d1ef84a376f1f68153ffaed/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json#L5932) in the same directory has the definition of `WindowsConfiguration` with the same description the error message said. The weird part is that this file is not referenced by this tag.
Could you please have a closer look why this happens? I have no clue why this happens, and why this happens with the changes brought by this PR...

**Comment by jhendrixMSFT** [comment]
My guess is it's an artifact of building with the `--multiapi` switch.  Can you try building the tag by itself to see if the issue repros?

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT seems it reports the same issue:

```
❯ autorest --go --use="@microsoft.azure/autorest.go@~2.1.145" --verbose --tag="package-2018-10-01" --go-sdk-folder=C:\Users\dapzhang\go\src\github.com\Azure\azure-sdk-for-go\ --version=previous --use-onever .\specification\compute\resource-manager\readme.md
AutoRest code generation utility [cli version: 3.0.6187; node: v12.14.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\dapzhang\.autorest\@microsoft.azure_autorest-core@2.0.4413\node_modules\@micros
oft.azure\autorest-core\dist' (2.0.4413)
   Including configuration file 'file:///C:/Users/dapzhang/Documents/workspace/azure-rest-api-specs/specification/compu
te/resource-manager/readme.go.md'
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.145->2.1.145)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
FATAL: swagger-document/compose - FAILED
FATAL: Error: '$.definitions.WindowsConfiguration.properties.enableAutomaticUpdates.description' has incompatible value
s (---
  -
  Indicates whether virtual machine is enabled for automatic Windows updates.
  Default value is true. <br><br> For virtual machine scale sets, this property
  can be updated and updates will take effect on OS reprovisioning.
, ---
Indicates whether virtual machine is enabled for automatic updates.
).
Process() cancelled due to exception : '$.definitions.WindowsConfiguration.properties.enableAutomaticUpdates.descriptio
n' has incompatible values (---
  -
  Indicates whether virtual machine is enabled for automatic Windows updates.
  Default value is true. <br><br> For virtual machine scale sets, this property
  can be updated and updates will take effect on OS reprovisioning.
, ---
Indicates whether virtual machine is enabled for automatic updates.
).
  Error: '$.definitions.WindowsConfiguration.properties.enableAutomaticUpdates.description' has incompatible values (--
-
  -
  Indicates whether virtual machine is enabled for automatic Windows updates.
  Default value is true. <br><br> For virtual machine scale sets, this property
  can be updated and updates will take effect on OS reprovisioning.
, ---
Indicates whether virtual machine is enabled for automatic updates.
).
```

**Comment by ArcturusZhang** [comment]
Thanks @jhendrixMSFT !

Hi @00Kai0 could you please align the description in 2018-06-01/compute.json to match the 2018-10-01 version? This should resolve this issue.

**Comment by ArcturusZhang** [comment]
Hi @00Kai0 do we have any updates on this?

**Comment by 00Kai0** [comment]
@ArcturusZhang aligned.

**Comment by zikalino** [comment]
closing this as i want to rebase and merge

**Pull request closed without merging**
