### PR TITLE
Improve the description for VM redeploy operation

### PR DESCRIPTION
**Pull request by dochung4**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by Juliehzl — APPROVED** [review]

**Review by Juliehzl — CHANGES_REQUESTED** [review]
Can you make CI check pass first?

**Comment by dochung4** [comment]
> Can you make CI check pass first?

Hi Julie, by CI check, are you referring to public.rest-api-specs check that failed?

It failed because of the following error:

Following response status codes "200" for operation "Images_CreateOrUpdate"
    were present in the swagger spec, however they were not present in
    x-ms-examples. Please provide them.

We have a separate bug filed to add an example for Images_CreateOrUpdate, and someone else in my team will work on it soon. Meanwhile, since this PR only updates the description, in my opinion, the missing example for Images_CreateOrUpdate should not be a blocker for this PR. But please let me know if you think otherwise.

**Review by Juliehzl — APPROVED** [review]

**Comment by Juliehzl** [comment]
Hi @dochung4, I have approved from swagger specification side. It will be better for your team member to contribute to this PR and make CI agree. If you have very urgent deadline to make this PR merged, you need to create an issue and assign yourself or your team member  to track this problem.

**Comment by dochung4** [comment]
> Hi @dochung4, I have approved from swagger specification side. It will be better for your team member to contribute to this PR and make CI agree. If you have very urgent deadline to make this PR merged, you need to create an issue and assign yourself or your team member to track this problem.

Hi @Juliehzl, I added examples, and I believe all checks are passing now. Can you please help merging the PR, if you don't have further comments?

**Pull request merged**
