### PR TITLE
Updating tspconfig so I can emit Go using tsp-client

### PR DESCRIPTION
**Pull request by richardpark-msft**

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]
Go emitter config only

**Comment by jianingwang123** [comment]
Please update the tspconfig to the correct one.

**Comment by l0lawrence** [comment]
> Please update the tspconfig to the correct one.

Could you point us to where to find the correct format?

**Comment by wanlwanl** [comment]
> Could you point us to where to find the correct format?
@l0lawrence Please refer to the configuration for tspconfig at https://github.com/chidozieononiwu/azure-sdk-for-go/wiki/Generate-Go-Mgmt-SDK-from-Typespec. The documentation is still being continuously improved. If you need further assistance, feel free to reach out to @raych1.

**Pull request merged**
