### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService to add version 2019-02-01

### PR DESCRIPTION
**Pull request by xizha162**
Here is the list of PRs merged into the dev branch after review:

[AKS] add availabilityZones to agent pool profile 
https://github.com/Azure/azure-rest-api-specs/pull/5120

including orchestratorVersion and provisioning state for agent pool
https://github.com/Azure/azure-rest-api-specs/pull/5156

including apiServerAuthorizedIPRanges
https://github.com/Azure/azure-rest-api-specs/pull/5286

mark the new features as PREVIEW in description
https://github.com/Azure/azure-rest-api-specs/pull/5310

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/Azure/azure-rest-api-specs/dev-containerservice-Microsoft.ContainerService-2019-02-01).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by xizhamsft** [comment]
@praries880 Please merge the dev branch back to master. All the changes are already reviewed and signed off when merging to the dev branch. Thanks.

**Comment by praries880** [comment]
@xizhamsft can you kindly link the PR for the merge into the dev branch?

**Comment by xizhamsft** [comment]
@praries880, added the links to the PR merged into the dev branch. Please let me know if I am not doing it right.

**Review by praries880 — APPROVED** [review]

**Comment by praries880** [comment]
@xizhamsft Based on the previous PRs being ARM reviewed I have removed the ARM review required flag. You are good to go.

**Comment by mboersma** [comment]
I would have appreciated an opportunity to review this before it was merged. @xizhamsft please include me as a reviewer on any changes to the AKS Swagger.

**Pull request merged**
