### PR TITLE
[CognitiveServices] enable Bing Search/CustomSearch products to specify Endpoint

### PR DESCRIPTION
**Pull request by yangyuan**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Comment by yangyuan** [comment]
Please hold for internal review with Bing teams.

**Comment by yangyuan** [comment]
approved by SpellCheck (wenjinz) offline.
Waiting for Bing Search team

**Comment by praries880** [comment]
@azuresdkci add to whitelist

**Comment by praries880** [comment]
@yangyuan marking this as in review as the bing search team is yet to sign off on this.

**Comment by yangyuan** [comment]
Get approved by Bing Search.
Hi @praries880, we are good to proceed.

**Review by sudhansu88 — APPROVED** [review]

**Review by praries880 — APPROVED** [review]

**Pull request merged**
