### PR TITLE
Typespec for Analyze-Documents

### PR DESCRIPTION
**Pull request by bidisha-c**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by heaths** [comment]
Are all these breaking changes to the same version what actually shipped in production and are just corrections? This is why it's best to spec out your service first, have it reviewed, then deploy it. If that's not feasible in some cases, you really should create a new version. Even for previews, breaking changes are bad for customers.

**Comment by weidongxu-microsoft** [comment]
Is this PR for migrating the Swagger to TypeSpec?

**Comment by bidisha-c** [comment]
@weidongxu-microsoft yes this PR is migrating from swagger to typespec.

**Comment by bidisha-c** [comment]
@heaths, there are no updates to the API we shipped for analyze-docments in 2023-11-15-preview version. We are basically just trying to migrate from swagger to typespec. Some of these breaking changes are just due to the migration and a few are bugs which @aurghob is working on fixing.

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft yes this PR is migrating from swagger to typespec.

However, there is real schema change (besides naming etc.) that exists in your PR.
E.g.
before https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/preview/2023-11-15-preview/analyzedocuments.json#L1977-L1998
after https://github.com/Azure/azure-rest-api-specs/blob/7eb0aadf3d260ca853c047b6c3f1df87e9c20a1c/specification/cognitiveservices/data-plane/Language/preview/2023-11-15-preview/analyzedocuments.json#L1052-L1066

It is really hard to be sure that there is no API change in 2023-11-15-preview

**Comment by aurghob** [comment]
Hi, 
For some context, The previous swagger PR https://github.com/Azure/azure-rest-api-specs/pull/30026 was merged last week. 
The PR before https://github.com/Azure/azure-rest-api-specs-pr/pull/15838, was reviewed in November 2023 and approved 2 weeks ago but was released as a private preview API.

As for the checks:
I went through all the breaking changes. Some of them I have explained below but also made sure to compare against our Lan guage.AnalyzeText and Language.Conversations typespec.
There are a few (4-8) bugs in the swagger as well which the typespec corrects. Ideally, this should have been a bug fix to the swagger and are consistent with the existing text api but since we were able to add Typespec, we're fixing it here. Please let me know if you'd like a swagger bug fix first separately instead.
In some cases, for example, ExtractiveSummarizationSortingCriteria : my understanding is that with typespec, the way some of the objects are configured have changed and thus it generates the swagger as we see. Please note that the swagger file on this PR is entirely autogenerated.

Going by category of breaking changes below:

1006 - ExtractiveSummarizationSortingCriteria is present and is present directly instead of being referenced.
PiiDomain- is a bug - should be domain
RedactionCharacter and StringIndexType are now directly defined instead of separately referenced. Same will show up in 1017.
1008- Operation Ids are autogenerated by typespec. This has to be changed.
1017 - All the references that are erroring are now directly used objects.
1020 - bug - has to be added.
1022 - staying consistent with analyze-text and analyze-conversations. (Please refer main.tsp in Language.AnalyzeText) No additional properties used. They were empty before as well.
1023- bug : changed to int32 and made consistent. Rest are also for consistency.
1026 - Types are better defined here than previously.

1030 - Did not understand 
1036 - Did not understand, was not removed.

1042 -  For the first one, parameter or has changed and is now more consistent with analyze-text and analyze-conversations. all the other ordering issues are incorrectly detected. The parameters are in the same order and are directly defined now instead of being referred separately.
1045- Was missed and is a bug. Consistent with current input.(double check) - have more questions. change description. Its not auto language detection. SummaryLength and query is already present in the API and this is to make sure that the parameter is present as part of the swagger and typespec. 
1048 - values is present as documentation - better than before.
1049 - x-ms-enum is still present. Not sure I understand the error.
1050 - Similar to analyze-text and analyze-conversations. Have kept the definition consistent.

**Comment by weidongxu-microsoft** [comment]
## 1008

Operation ID can be maintained as e.g.
```
interface AnalyzeDocuments {
  op cancelJob(...);
}
```

## 1030

Seems a bug in old Swagger.

It should have `"discriminator": "kind"` in `AnalyzeDocumentsLROResultsKind`.

## 1033

What about this?

**Comment by aurghob** [comment]
> **1008**
> Operation ID can be maintained as e.g.

Keeping as is : we don't want to change it back. This format is consistent across analyzeText and analyzeConversations now.
We understand it will break the format of the current swagger but we want to use this for upcoming swaggers. Also - we have done the same for analyze-text


> **1030**
> Seems a bug in old Swagger.
>
> It should have "discriminator": "kind" in AnalyzeDocumentsLROResultsKind.

It should be the other way round.  AnalyzeDocumentsLROResults did not have a discriminator and we added it. It's similarly structured in analyze text and analyze conversations.
Same applied for items as it references AnalyzeDocumentsLROResults.

> **1033**
> What about this?

**The new version is missing a property found in the old version. Was 'results' renamed or removed?**
Afaik, the way it is structured with the new swagger is again consistent with analyze-text and analyze-conversations.
This seems to be more correct than the structure before. 'results' is defined in the different results kinds as expected.

**Review by quentinRobinson — APPROVED** [review]

**Pull request merged**
