### PR TITLE
[Traffic Manager] Adding new Realtime User Metrics (RUM) preview feature.

### PR DESCRIPTION
**Pull request by allencal**
[Traffic Manager] Adding new Realtime User Metrics (RUM) preview feature.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
@allencal - Looks good after incorporating the changes we discussed over IM. I think this key is not a secret and so should be fine to be returned in the response of GET/PUT. Please correct me if I am wrong on this. ARM signs off assuming the key is not a secret.

**Comment by sarangan12** [comment]
@allencal

Please check the warning here: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269723978#L677 This seems simple enough to be fixed. Can you please fix it?

Also, the errors at https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269723979 and https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269723980 must be fixed for approval. 

Please fix them and update the PR

**Comment by sarangan12** [comment]
@allencal The errors are still not fixed. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269808463

**Comment by allencal** [comment]
Fixed, new commit created.

Thanks,
Allen

**Comment by sarangan12** [comment]
Debugging what the incompatible error is.  Will update the PR soon

**Comment by sarangan12** [comment]
There are 2 errors. One is related to Ruby. This is a known issue. Also, one related to python. I am suspecting this is due to latest changes in autorest and not related to swagger. I am approving this PR for merge and unblock the user

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
