### PR TITLE
[Hub Generated] Review request for Microsoft.AzureStackHCI to add version preview/2020-03-01-preview

### PR DESCRIPTION
**Pull request by mbialecka**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/mbialecka/azure-rest-api-specs/dev-azurestackhci-Microsoft.AzureStackHCI-2020-03-01-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mbialecka** [comment]
The previous spec version was approved in the private repo:
https://github.com/Azure/azure-rest-api-specs-pr/pull/1102
https://github.com/Azure/azure-rest-api-specs-pr/pull/1206

Changes introduced in this PR:
* New values for `status` enum
* Updated examples

**Comment by mbialecka** [comment]
@xccc-msft Is there anything I need to do to move the process to completion?

**Comment by chiragg4u** [comment]
Please go through the contribution checklist added as part of the review and mark them completed to confirm that you’ve gone through the required documentation.

**Comment by mbialecka** [comment]
@xccc-msft Please help with resolving linter errors. I've requested suppression for "R3020 - PathResourceProviderNamePascalCase". I don't know what I am missing with "R4007 - DefaultErrorResponseSchema".

**Comment by xccc-msft** [comment]
@akning-ms @NullMDR Can you please advise how to resolve the errors? Thanks.

**Comment by mbialecka** [comment]
@xccc-msft I the fixed linter errors but now avocado fails. Please advise how to proceed. I need to complete this as soon as possible.

**Comment by xccc-msft** [comment]
@mbialecka Any reason you removed the `WaitForARMFeedback`? It's required to wait for ARM review as you are adding new service/APIs.

**Comment by akning-ms** [comment]
@mbialecka, the avocado error can be ignore as it is common file. but just noticed the Python & JS &  Java SDK generation fail which may what you need. you can see here: https://github.com/Azure/azure-rest-api-specs/pull/10115#issuecomment-657801419
@NullMDR to help to take a look

**Comment by mbialecka** [comment]
@xccc-msft I confirmed with ARM that a new review is not needed as it was completed in the private repo (I linked to the previous PRs in the private repo). Since avocado error can be ignored, can you merge in the PR?

**Review by xseeseesee — APPROVED** [review]

**Pull request merged**
