### PR TITLE
[Hub Generated] Review request for Microsoft.Authorization to add version preview/2022-05-01-preview

### PR DESCRIPTION
**Pull request by veseshad92**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/veseshad92-authorization-Microsoft.Authorization-2022-05-01-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. Already deployed in our service.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. immediare
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following: Already approved with aRM.
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mumoryan** [comment]
@keryul and @stankovski hi could we get some help with reviewing this pull request? Many thanks

**Comment by keryul** [comment]
@mumoryan can you fix errors with required label?

**Comment by mumoryan** [comment]
@keryul I took this item over from a teammate. I tried to push a commit to this PR but got 403 unauthorized at `git push`. Are there pre-requisites to contribute to this repo?

For the other two breaking changes that I do not have a fix for, could you answer the following?
1. Swagger Avocado: These failures do not make sense to me. The new api preview version is taking after GA versions. Would you be able to help me understand if this is a tooling bug?
2. Swagger LintDiff: Any Put MUST contain 200 and 201 return codes.
We do not return 200. This seem to be a new rule? What's the proper way to handle this?

**Comment by keryul** [comment]
> 

@konrad-jamrozik can you help answer these questions?

**Comment by keryul** [comment]
> @keryul I took this item over from a teammate. I tried to push a commit to this PR but got 403 unauthorized at `git push`. Are there pre-requisites to contribute to this repo?
> 
> For the other two breaking changes that I do not have a fix for, could you answer the following?
> 
> 1. Swagger Avocado: These failures do not make sense to me. The new api preview version is taking after GA versions. Would you be able to help me understand if this is a tooling bug?
> 2. Swagger LintDiff: Any Put MUST contain 200 and 201 return codes.
>    We do not return 200. This seem to be a new rule? What's the proper way to handle this?

@konrad-jamrozik can you help answer these questions?

**Comment by konrad-jamrozik** [comment]
@mumoryan

Re:

> Swagger LintDiff: Any Put MUST contain 200 and 201 return codes.
We do not return 200. This seem to be a new rule? What's the proper way to handle this?

The [rule name](https://github.com/Azure/azure-rest-api-specs/pull/23941/checks?check_run_id=13934924920) is a hyperlink to the [TSG](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-response-schema-description.md). Please follow the guidance there. If you have any further questions how to address it, please reach out to @rkmanda.

**Comment by konrad-jamrozik** [comment]
@mumoryan

Re:

> Swagger Avocado: These failures do not make sense to me. The new api preview version is taking after GA versions. Would you be able to help me understand if this is a tooling bug?

Please expand the Avocado failures view here:
- https://github.com/Azure/azure-rest-api-specs/pull/23941#issuecomment-1544744246

and click through the rule name hyperlinks. They provide troubleshooting guides. If they are unclear, let me know what is unclear about them.

image

**Comment by mumoryan** [comment]
@rkmanda Could you help me with the following
Swagger LintDiff: Any Put MUST contain 200 and 201 return codes.
We simply do not have a 200 response. This seem to be a new rule? What's the proper way to handle this check?

**Comment by konrad-jamrozik** [comment]
@mumoryan for the azure-sdk-for-go check, [there are runtime exceptions](https://github.com/Azure/azure-sdk-tools/issues/6323) you should ignore for now (sorry about that!), but I see there errors I think you should address:

```
06:00:17.329 cmderr     [generator automation-v2] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Permission' (2 differences):
06:00:17.329 cmderr     [generator automation-v2]   - properties.condition: {"$ref":"#/components/schemas/schemas:142","description":"The conditions on the role definition. This limits the resources it can be assigned to. e.g.: @Resource[Microsoft.Storage/storageAccounts/blobServices/containers:ContainerName] StringEqualsIgnoreCase 'foostoragecontainer'","readOnly":true} => <none>
06:00:17.329 cmderr     [generator automation-v2]   - properties.conditionVersion: {"$ref":"#/components/schemas/schemas:143","description":"Version of the condition. Currently the only accepted value is '2.0'","readOnly":true} => <none>; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
```

Search for

```
error   |
```

to find all such occurrences.

**Comment by konrad-jamrozik** [comment]
@mumoryan for the Avocado error of kind `NOT_LATEST_API_VERSION_IN_DEFAULT_TAG`:

Error like this:

[NOT_LATEST_API_VERSION_IN_DEFAULT_TAG](https://github.com/Azure/avocado/blob/master/README.md#NOT_LATEST_API_VERSION_IN_DEFAULT_TAG)

The default tag does not contains the latest API version. Please make sure the latest api version swaggers are in the default tag.
readme: [specification/authorization/resource-manager/readme.md](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/readme.md)
json: [Microsoft.Authorization/preview/2020-10-01-preview/EligibleChildResources.json](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-10-01-preview/EligibleChildResources.json)

occurs because:
- The latest API version for which `EligibleChildResources.json` appears is 2020-10-01-preview.
- In the README (which is AutoRest config), the "Basic information" section has `tag: package-2022-05-01-preview` meaning the default tag is `package-2022-05-01-preview`
- In the same README we can see:
  ```
  # Tag: package-2022-05-01-preview
  These settings apply only when --package-2022-05-01-preview is specified on the command line.
  
  input-file:
    
    - Microsoft.Authorization/stable/2015-07-01/authorization-ClassicAdminCalls.json
    - Microsoft.Authorization/stable/2015-07-01/authorization-ElevateAccessCalls.json
    - Microsoft.Authorization/stable/2022-04-01/authorization-DenyAssignmentCalls.json
    - Microsoft.Authorization/stable/2022-04-01/authorization-ProviderOperationsCalls.json
    - Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json
    - Microsoft.Authorization/preview/2022-05-01-preview/authorization-RoleDefinitionsCalls.json
    - Microsoft.Authorization/preview/2022-05-01-preview/common-types.json
    - Microsoft.Authorization/preview/2021-12-01-preview/authorization-AccessReviewCalls.json
    - Microsoft.Authorization/stable/2020-10-01/EligibleChildResources.json
    - Microsoft.Authorization/stable/2020-10-01/RoleAssignmentSchedule.json
    - Microsoft.Authorization/stable/2020-10-01/RoleAssignmentScheduleInstance.json
    - Microsoft.Authorization/preview/2022-04-01-preview/RoleAssignmentScheduleRequest.json
    - Microsoft.Authorization/stable/2020-10-01/RoleEligibilitySchedule.json
    - Microsoft.Authorization/stable/2020-10-01/RoleEligibilityScheduleInstance.json
    - Microsoft.Authorization/preview/2022-04-01-preview/RoleEligibilityScheduleRequest.json
    - Microsoft.Authorization/stable/2020-10-01/RoleManagementPolicy.json
    - Microsoft.Authorization/stable/2020-10-01/RoleManagementPolicyAssignment.json
    ```

Observe the presence of:
`Microsoft.Authorization/stable/2020-10-01/EligibleChildResources.json`
but absence of
`Microsoft.Authorization/preview/2020-10-01-preview/EligibleChildResources.json`.

The lack of the last one is the problem.

**Comment by konrad-jamrozik** [comment]
@mumoryan for the Avocado error `MISSING_APIS_IN_DEFAULT_TAG`

> [MISSING_APIS_IN_DEFAULT_TAG](https://github.com/Azure/avocado/blob/master/README.md#MISSING_APIS_IN_DEFAULT_TAG)
>
> The default tag should contain all APIs. The API path `/subscriptions/{}/resourcegroups/{}/providers/Microsoft.Authorization/permissions` is not in the default tag. Please make sure the missing API swaggers are in the default tag.
readme: [specification/authorization/resource-manager/readme.md](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/readme.md)
json: [Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json)

We are dealing with the same README / AutoRest config as here:
- https://github.com/Azure/azure-rest-api-specs/pull/23941#issuecomment-1585085436

Observe the `Tag: package-2022-05-01-previe` has only one occurrence of `authorization-RoleDefinitionsCalls.json`:

```
- Microsoft.Authorization/preview/2022-05-01-preview/authorization-RoleDefinitionsCalls.json
```

Now looking at:

[Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json)
and
[Microsoft.Authorization/preview/2022-05-01-preview/authorization-RoleDefinitionsCalls.json](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/preview/2022-05-01-preview/authorization-RoleDefinitionsCalls.json)

We can see the stable one [has](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json#L37):
`"/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Authorization/permissions": {`

while the preview [has](https://github.com/Azure/azure-rest-api-specs/blob/4973679b7112a53d31251b13abcf5329684732aa/specification/authorization/resource-manager/Microsoft.Authorization/preview/2022-05-01-preview/authorization-RoleDefinitionsCalls.json#L37):

`"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Authorization/permissions": {`

The difference is in capitalization: `resourcegroups` vs `resourceGroups`.

**Comment by raych1** [comment]
@JeffreyRichter , can you please review the breaking change?

**Comment by JeffreyRichter** [comment]
You have to justify the removed path shown here: https://github.com/Azure/azure-rest-api-specs/pull/23941/checks?check_run_id=14258455436

**Comment by mumoryan** [comment]
@JeffreyRichter The latest breaking change does not remove any paths. Are you looking at a previous run? https://github.com/Azure/azure-rest-api-specs/pull/23941/checks?check_run_id=14258455204

**Comment by JeffreyRichter** [comment]
So that is a breaking change. What will happen to customers that were using /{roleId}?disambiguation_dummy when they adopt the new api-version?

**Comment by mumoryan** [comment]
We have 0.07% of total GET role definition calls that are using this pattern than the standard get by ID pattern. I'm adding this API to the preview version so that it is consistent with the GA version.

**Comment by JeffreyRichter** [comment]
I don't understand. Today you have the /{roleId}?disambiguation_dummy and some customers might be using it.
Tomorrow, you want to remove this and then any customers using this will be forced to modify their code - this is the definition of a breaking change and Azure doesn't want to break its customers. If you really want to do this, then you must have a great justification for doing so. I'm waiting to hear what that is.

**Comment by mumoryan** [comment]
Hi @JeffreyRichter the problem is resolved! Can I have a review for the swagger breakingchange?

**Comment by keryul** [comment]
@raych1 please review the GO breaking change
@qiaozha please review the JS breaking change
@msyyc please review the Python breaking change

**Comment by keryul** [comment]
> @keryul Um...if you don't mind me asking, do all of these issues need to be reviewed? And each by a different person? So far this PR has been changed hands by about 5 or 6 reviewers over a month already. Why is this process so cumbersome? Is there any room for optimization? 😊
> 
> Why weren't these reviews mentioned when I first took over this PR ~2 weeks ago?

yes, every error check has its owner, and they should be reviewed at the end of review to prevent other commits from affecting SDK breaking change checks

**Review by raych1 — APPROVED** [review]

**Pull request merged**
