### PR TITLE
Updates for Batch Management 2020-03 API version

### PR DESCRIPTION
**Pull request by matthchr**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by matthchr** [comment]
This API version has not had SDKs published for it yet (we were waiting for these changes to be merged).

The following two changes are additions required for JEDI:
```
Info 1040 - AddedReadOnlyPropertyInResponse - The new version has a new read-only property 'privateEndpointConnections' in response that was not found in the old version.
Info 1040 - AddedReadOnlyPropertyInResponse - The new version has a new read-only property 'requiredZoneNames' in response that was not found in the old version.
```

The following changes are corrects to errors in the specification (these properties were always required, we just didn't specify correctly). Also note, since these properties were only added on an object which is returned from GETs, it's documentation as required is just an FYI that the server will always return it.
```
Error 1034 - AddedRequiredProperty - The new version has new required property 'status' that was not found in the old version.
Error 1034 - AddedRequiredProperty - The new version has new required property 'status' that was not found in the old version.
```

Please let me know what we should do to silence the errors in the PR gate.

**Review by KrisBash — APPROVED** [review]
LGTM. I understand this to not be breaking as SDKs have not shipped

**Comment by matthchr** [comment]
@erich-wang  - since SDKs have not yet shipped for this API version, I believe these breaking changes should be okay -- can you advise on what we can do to flag these changes as okay for the purposes of CI?

**Comment by erich-wang** [comment]
> @erich-wang - since SDKs have not yet shipped for this API version, I believe these breaking changes should be okay -- can you advise on what we can do to flag these changes as okay for the purposes of CI?

Approve the breaking change since there's no sdk released for this version.

@matthchr , please fix ModelValidation error https://dev.azure.com/azure-sdk/public/_build/results?buildId=347822&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

**Comment by matthchr** [comment]
@erich-wang I fixed the model validation failures (sorry about missing that before).

**Comment by erich-wang** [comment]
@matthchr , I send email to swagger team to look into the model validation error.

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
