### PR TITLE
[DO NOT MERGE] cdn new version 2022 01 01 preview

### PR DESCRIPTION
**Pull request by priyadmurugan**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.

The new APIs that are added are internal APIs and the target for Private preview is Jan/Feb 2022. Please do not merge these APIs as they have not been implemented yet. 
Note: The new changes are done on top of a new version release for CDN (2021-06-01) which is not yet merged into main.

  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.

January/February 

  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
@priyadmurugan, set this PR to Open and send email to the current ARM API Review oncall when you are ready for ARM review.

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cdn/profiles/{profileName}/policies/{policyName}/applyPolicy": {

Did you consider modelling this API as a "policy application" or "policy assignment" resource where PUT applies the policy, and GET returns the application (including current provisioning state). It looks like you are supporting POST async operation results, which is good, but once they go away, a client doesn't have a way to discover what's been applied. Modeling it as a resource type would allow clients to enumerate all of the applications that have been made with a given policy. It would also allow applying policies in a deployment template, which isn't possible if it's done with POST.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2386 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "provisioningState": {

This should be a string enum with a fixed set of values. The  required states are terminal { Succeeded, Failed, Canceled }. Other [non-terminal only] states may be added. Ref: [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put).

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6716 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "resourceState": {

What does this property add on top of provisioningState? You can add "Creating" and "Deleting" to provisioningState, and use "Succeeded" instead of "Active".

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6702 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>     "PolicyParameters": {

It doesn't look like this needs to be separate from definitions/Policy. Generally ARM APIs should support a GET, modify, PUT pattern, which means that PUT should accept (and return) the same type as returned by GET (it's fine to ignore the state property/properties on PUT input).

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6723 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>         "customerConfig": {

Does this need to be an opaque blob? It's generally much better to schematize these wherever possible. This gives you automatic support for ARM features like ARG and Azure Policy. That won't be possible with a free-form blob. Even if only part of it can be schematized, it's better. Free-form blobs basically create a an API contract that isn't analyzable, managed, or versioned by ARM.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6635 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Current async model doesn't use 202. Use 200/201 + provisioningState. Ref: [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put).

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2313 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>           "200": {

IIUC, you are supporting async POST. If so, you need to return 202 for accepted status.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2433 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Requires x-ms-long-running-operation.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2313 in 38f20d3. [](commit_id = 38f20d38d5b15ac6361116f8828b25b1aee808b7, deletion_comment = False)

**Comment by priyadmurugan** [comment]
> > ```
> >     "provisioningState": {
> > ```
> 
> This should be a string enum with a fixed set of values. The required states are terminal { Succeeded, Failed, Canceled }. Other [non-terminal only] states may be added. Ref: https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put.
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6716 in [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7). [](commit_id = [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7), deletion_comment = False)



> > ```
> >     "customerConfig": {
> > ```
> 
> Does this need to be an opaque blob? It's generally much better to schematize these wherever possible. This gives you automatic support for ARM features like ARG and Azure Policy. That won't be possible with a free-form blob. Even if only part of it can be schematized, it's better. Free-form blobs basically create a an API contract that isn't analyzable, managed, or versioned by ARM.
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6635 in [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7). [](commit_id = [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7), deletion_comment = False)

**Comment by priyadmurugan** [comment]
> > ```
> >     "customerConfig": {
> > ```
> 
> Does this need to be an opaque blob? It's generally much better to schematize these wherever possible. This gives you automatic support for ARM features like ARG and Azure Policy. That won't be possible with a free-form blob. Even if only part of it can be schematized, it's better. Free-form blobs basically create a an API contract that isn't analyzable, managed, or versioned by ARM.
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:6635 in [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7). [](commit_id = [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7), deletion_comment = False)

CustomerConfig was intentionally kept as opaque blob as the API we are implementing is more of a transport layer than a parse layer.

**Comment by priyadmurugan** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cdn/profiles/{profileName}/policies/{policyName}/applyPolicy": {
> > ```
> 
> Did you consider modelling this API as a "policy application" or "policy assignment" resource where PUT applies the policy, and GET returns the application (including current provisioning state). It looks like you are supporting POST async operation results, which is good, but once they go away, a client doesn't have a way to discover what's been applied. Modeling it as a resource type would allow clients to enumerate all of the applications that have been made with a given policy. It would also allow applying policies in a deployment template, which isn't possible if it's done with POST.
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2386 in [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7). [](commit_id = [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7), deletion_comment = False)

@mentat9 : Here Policy is a new resource that we are adding. I am not sure if I understand the first line correctly. Could you please elaborate that. On a related note, Is there a limit on the payload size for a PUT vs POST operation?

**Comment by mentat9** [comment]
> > > ```
> > > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cdn/profiles/{profileName}/policies/{policyName}/applyPolicy": {
> > > ```
> > 
> > 
> > Did you consider modelling this API as a "policy application" or "policy assignment" resource where PUT applies the policy, and GET returns the application (including current provisioning state). It looks like you are supporting POST async operation results, which is good, but once they go away, a client doesn't have a way to discover what's been applied. Modeling it as a resource type would allow clients to enumerate all of the applications that have been made with a given policy. It would also allow applying policies in a deployment template, which isn't possible if it's done with POST.
> > Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2386 in [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7). [](commit_id = [38f20d3](https://github.com/Azure/azure-rest-api-specs/commit/38f20d38d5b15ac6361116f8828b25b1aee808b7), deletion_comment = False)
> 
> @mentat9 : Here Policy is a new resource that we are adding. I am not sure if I understand the first line correctly. Could you please elaborate that. On a related note, Is there a limit on the payload size for a PUT vs POST operation?

IIUC, when the applyPolicy POST action is called, your RP has to store something that indicates that policy A has been applied to resource R. I'm suggesting modeling that association as a resource type (e.g. Microsoft.Cdn/profiles/policyAssignments). PUT creates it (applies the policy), GET retrieves it, collection GET lists all of them, DELETE removes it, etc. This would require naming this association, but that feels like a more complete way of applying a policy to a resource. Otherwise how does a client discover what a policy has been applied to, or stop applying a policy to something that it was previously applied to? Also, if your customers want to apply policies in ARM templates, it must be done through PUT. ARM templates can't perform POST actions. Since my suggestion didn't make sense initially, I'm probably misunderstanding something about the intended operation of the API. Hopefully this will help clarify how I'm thinking about it.

**Comment by priyadmurugan** [comment]
> resourceState

@mentat9 : Thanks for the clarification. The API that we are creating will be used by another internal team to apply policy through ARM. So the customer for our API is the internal team. The new resource that we created is called 'Policy'. this resource will not be created through the Azure portal. As you suggested, we can remove POST action and use PUT to basically apply the policy. But to go with this change, I have a couple of clarifications. If we go with PUT instead of POST, then Policy resource would have both '**ServiceType**' and '**CustomerConfig**' as their property, so that when the customer does a PUT on **policy** we use the **customerConfig** json blob to apply that policy. Is this a correct appraoch and to go with this change, what's the limitation on the payload size for the PUT action   and what are the additional validations we need to take care?

**Comment by mentat9** [comment]
> > resourceState
> 
> @mentat9 : Thanks for the clarification. The API that we are creating will be used by another internal team to apply policy through ARM. So the customer for our API is the internal team. The new resource that we created is called 'Policy'. this resource will not be created through the Azure portal. As you suggested, we can remove POST action and use PUT to basically apply the policy. But to go with this change, I have a couple of clarifications. If we go with PUT instead of POST, then Policy resource would have both '**ServiceType**' and '**CustomerConfig**' as their property, so that when the customer does a PUT on **policy** we use the **customerConfig** json blob to apply that policy. Is this a correct appraoch and to go with this change, what's the limitation on the payload size for the PUT action and what are the additional validations we need to take care?

ARM payload size limit is 8Mb. Stepping back for a minute, you have CRUD APIs for a policy type. These APIs create, retrieve, update and delete an ARM resource type named "policy". Couple of questions about your design:
1. If I create a policy, but do nothing else, will it be enforced anywhere, or is it just a rule that's available for me to use in the future?
2. Can a single policy be applied to multiple different resources/contexts/scenarios?
3. What exactly does the POST action "applyPolicy" do?

**Comment by priyadmurugan** [comment]
> > > resourceState
> > 
> > 
> > @mentat9 : Thanks for the clarification. The API that we are creating will be used by another internal team to apply policy through ARM. So the customer for our API is the internal team. The new resource that we created is called 'Policy'. this resource will not be created through the Azure portal. As you suggested, we can remove POST action and use PUT to basically apply the policy. But to go with this change, I have a couple of clarifications. If we go with PUT instead of POST, then Policy resource would have both '**ServiceType**' and '**CustomerConfig**' as their property, so that when the customer does a PUT on **policy** we use the **customerConfig** json blob to apply that policy. Is this a correct appraoch and to go with this change, what's the limitation on the payload size for the PUT action and what are the additional validations we need to take care?
> 
> @priyadmurugan, ARM payload size limit is 8Mb. Stepping back for a minute, you are adding CRUD APIs for a policy type. These APIs create, retrieve, update and delete an ARM resource type named "policy". Couple of questions about your design:
> 
> 1. If I create a policy, but do nothing else, will it be enforced anywhere, or is it just a rule that's available for me to use in the future?
> 2. Can a single policy be applied to multiple different resources/contexts/scenarios?
> 3. What exactly does the POST action "applyPolicy" do?


@mentat9: Earlier we were planning to do CRUD on **policy** resource and use **applypolicy** POST action on **policy** resource to apply the policy (json blob) on profile resource. I was trying to understand if we can use PUT on policy itself to perform functionality which **applypolicy** POST action would have done. Is that possible? Also, the  reason we went with POST action **applyPolicy** is to overcome the ARM payload size limitation. As per my understand there is no limit on the payload size for POST action. Is that right? I have answered your questions below:

> 1. If I create a policy, but do nothing else, will it be enforced anywhere, or is it just a rule that's available for me to use in the future?
This policy would be a resource that will be created with PUT action and then  used to call **applyPolicy**  POST action to apply policies to the profile.

> 2. Can a single policy be applied to multiple different resources/contexts/scenarios?
We have 1-1 mapping between policy and profile (parent resource)

> 3. What exactly does the POST action "applyPolicy" do?

It applies the json blob which is the policy on the profile resource.

**Comment by priyadmurugan** [comment]
> > > > resourceState
> > > 
> > > 
> > > @mentat9 : Thanks for the clarification. The API that we are creating will be used by another internal team to apply policy through ARM. So the customer for our API is the internal team. The new resource that we created is called 'Policy'. this resource will not be created through the Azure portal. As you suggested, we can remove POST action and use PUT to basically apply the policy. But to go with this change, I have a couple of clarifications. If we go with PUT instead of POST, then Policy resource would have both '**ServiceType**' and '**CustomerConfig**' as their property, so that when the customer does a PUT on **policy** we use the **customerConfig** json blob to apply that policy. Is this a correct appraoch and to go with this change, what's the limitation on the payload size for the PUT action and what are the additional validations we need to take care?
> > 
> > 
> > @priyadmurugan, ARM payload size limit is 8Mb. Stepping back for a minute, you are adding CRUD APIs for a policy type. These APIs create, retrieve, update and delete an ARM resource type named "policy". Couple of questions about your design:
> > 
> > 1. If I create a policy, but do nothing else, will it be enforced anywhere, or is it just a rule that's available for me to use in the future?
> > 2. Can a single policy be applied to multiple different resources/contexts/scenarios?
> > 3. What exactly does the POST action "applyPolicy" do?
> 
> @mentat9: Earlier we were planning to do CRUD on **policy** resource and use **applypolicy** POST action on **policy** resource to apply the policy (json blob) on profile resource. I was trying to understand if we can use PUT on policy itself to perform functionality which **applypolicy** POST action would have done. Is that possible? Also, the reason we went with POST action **applyPolicy** is to overcome the ARM payload size limitation. As per my understand there is no limit on the payload size for POST action. Is that right? I have answered your questions below:
> 
> > 1. If I create a policy, but do nothing else, will it be enforced anywhere, or is it just a rule that's available for me to use in the future?
> >    This policy would be a resource that will be created with PUT action and then  used to call **applyPolicy**  POST action to apply policies to the profile.
> 
> > 2. Can a single policy be applied to multiple different resources/contexts/scenarios?
> >    We have 1-1 mapping between policy and profile (parent resource)
> 
> > 3. What exactly does the POST action "applyPolicy" do?
> 
> It applies the json blob which is the policy on the profile resource.

@mentat9 : I have removed post action and will be implementing it as you suggested with put approach.

**Comment by mentat9** [comment]
>       "put": {

This method still needs the x-ms-long-running-operation extension if it's using the async pattern.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-01-01-preview/cdn.json:2255 in b410f4c. [](commit_id = b410f4cc407d6a7ab7ba16ea05a4da3d7d64e917, deletion_comment = False)

**Comment by mentat9** [comment]
@priyadmurugan, I reviewed the latest iterations and it looks good, modulo one comment. Also, for future reference, you can get a faster turnaround from ARM review on PR updates that cross into the next week if you tag or directly ping the current oncall when you are ready for re-review (the labels are also good, but sometimes get overlooked across the next week handoff/transition).

**Comment by priyadmurugan** [comment]
> @priyadmurugan, I reviewed the latest iterations and it looks good, modulo one comment. Also, for future reference, you can get a faster turnaround from ARM review on PR updates that cross into the next week if you tag or directly ping the current oncall when you are ready for re-review (the labels are also good, but sometimes get overlooked across the next week handoff/transition).

@mentat9 : I have addressed your PR review comments. My new version is based of 2021-06 version which was merged after I created PR and I see that there are few changes there that are missing in my new version. Would you suggest me to update them manually or probably create a new PR by having first commit with that version, followed by my changes?

**Comment by mentat9** [comment]
> > @priyadmurugan, I reviewed the latest iterations and it looks good, modulo one comment. Also, for future reference, you can get a faster turnaround from ARM review on PR updates that cross into the next week if you tag or directly ping the current oncall when you are ready for re-review (the labels are also good, but sometimes get overlooked across the next week handoff/transition).
> 
> @mentat9 : I have addressed your PR review comments. My new version is based of 2021-06 version which was merged after I created PR and I see that there are few changes there that are missing in my new version. Would you suggest me to update them manually or probably create a new PR by having first commit with that version, followed by my changes?

Go ahead and make the new PR exactly as you described. Include a link back to this PR in your comments when/after you submit the new PR.

**Comment by priyadmurugan** [comment]
Closing this PR, as there is another PR open for the same changes; https://github.com/Azure/azure-rest-api-specs/pull/17539

**Pull request closed without merging**
