### PR TITLE
Key Vault 7.4-preview to 7.4-preview.1

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
I fixed the spelling error for new versions once and for all (until refactored again), but I can't exempt the double slash issue that is handled by the service. I did open https://github.com/Azure/oav/issues/660 to track, however.

**Comment by heaths** [comment]
@ShivangiReja what do you make of https://github.com/Azure/azure-rest-api-specs/pull/15900/checks?check_run_id=3499038989 ?

**Comment by ShivangiReja** [comment]
>@ShivangiReja what do you make of https://github.com/Azure/azure-rest-api-specs/pull/15900/checks?check_run_id=3499038989 ?

@zhenglaizhang there is an issue in SDK automation.

[Fatal error: packageFolderFromFileSearch not configured and could not be found in legacy config](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1079495&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=768)

Could you please look into that?

**Comment by ShivangiReja** [comment]
>@ShivangiReja what do you make of https://github.com/Azure/azure-rest-api-specs/pull/15900/checks?check_run_id=3499038989 ?

@heaths `SDK azure-sdk-for-net-track2` step is for track-2 C# SDK automation. If anything changes in the swagger for a partucular version, this step generates code based on the changes in the swagger and creates a PR in azure-sdk-for-net repo.

@zhenglaizhang there is an issue in SDK automation and didn't seem like C# issue.

[Fatal error: packageFolderFromFileSearch not configured and could not be found in legacy config](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1079495&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=768)

Could you please look into that?

**Comment by heaths** [comment]
> @heaths `SDK azure-sdk-for-net-track2` step is for track-2 C# SDK automation. If anything changes in the swagger for a partucular version, this step generates code based on the changes in the swagger and creates a PR in azure-sdk-for-net repo.

@ShivangiReja only 1 package in KV gets generated from swagger. What is actually happening in our repo? Is it just running `dotnet build /t:GenerateCode` or what?

**Comment by ShivangiReja** [comment]
>@ShivangiReja only 1 package in KV gets generated from swagger. What is actually happening in our repo? Is it just running dotnet build /t:GenerateCode or what?

@heaths It runs [Automation-Sdk-Generate.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Automation-Sdk-Generate.ps1) script where it takes changed readme files as an input, update the autorest.md files, generate code and return [this](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Automation-Sdk-Generate.ps1#L127) output. After that, we have a common script which creates a PR beased on input and output returned by [Automation-Sdk-Generate.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Automation-Sdk-Generate.ps1) script.

**Comment by heaths** [comment]
@ShivangiReja that raises some questions:

1. Shouldn't updating our autorest.md files only happen against changes in "main"? Based on conversations with @JeffreyRichter and @johanste changes in release branches are not final nor supported - not until they merge into main whether in the "preview" or "stable" folders.
2. Whether merged into main or not, we don't necessarily want to take every update if more are expected. I appreciate generating the SDK with any swagger updates, but you said a PR is created presumably to commit those changes. Can we simply reject and close those if we don't want them yet?

**Comment by ShivangiReja** [comment]
>@ShivangiReja that raises some questions:

> 1. Shouldn't updating our autorest.md files only happen against changes in "main"? Based on conversations with @JeffreyRichter and @johanste changes in release branches are not final nor supported - not until they merge into main whether in the "preview" or "stable" folders.
> 2. Whether merged into main or not, we don't necessarily want to take every update if more are expected. I appreciate generating the SDK with any swagger updates, but you said a PR is created presumably to commit those changes. Can we simply reject and close those if we don't want them yet?

@heaths When the PR in specs repo merges, it will create a PR in azure-sdk-for-net based on the changes in the swagger. This is just a convenience layer and if you don't want to merge that PR into main, you can simply close it.

@weshaggard can add more details here.

**Comment by heaths** [comment]
> @heaths When the PR in specs repo merges, it will create a PR in azure-sdk-for-net based on the changes in the swagger. This is just a convenience layer and if you don't want to merge that PR into main, you can simply close it.

Fair enough, but service teams may be iterating on a swagger often. Seems that should only trigger for merges into "main" since only those swaggers are actually supported. Multiple feature and/or release branches could also be running in parallel which would really complicate the SDK repos.

/cc @weshaggard @JeffreyRichter @johanste

**Comment by heaths** [comment]
@JeffreyRichter @jhendrixMSFT this isn't actually a breaking change. When I created the branch I forgot to specify ".1" in case they merge to main and want to iterate on a ".2". The branch was *just* created by me yesterday.

**Comment by weshaggard** [comment]
The question about only creating PRs based on the target branch is an interesting one. @zhenglaizhang what is the general workflow there? Does it always create a PR targeting a matching branch as the specs repo or does it always target main or is there some other logic?

**Comment by zhenglaizhang** [comment]
> > @ShivangiReja what do you make of https://github.com/Azure/azure-rest-api-specs/pull/15900/checks?check_run_id=3499038989 ?
> 
> @heaths `SDK azure-sdk-for-net-track2` step is for track-2 C# SDK automation. If anything changes in the swagger for a partucular version, this step generates code based on the changes in the swagger and creates a PR in azure-sdk-for-net repo.
> 
> @zhenglaizhang there is an issue in SDK automation and didn't seem like C# issue.
> 
> [Fatal error: packageFolderFromFileSearch not configured and could not be found in legacy config](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1079495&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=768)
> 
> Could you please look into that?

Per our discussion in team, I am wondering why there is https://github.com/heaths/azure-rest-api-specs/tree/keyvault-7.4-preview.1/specification/keyvault/data-plane#basic-information default tag, and swagger is also updated, but no any c# code generated.  

SDK automation fails due to the empty package result, this is a bug in SDK automation, and I have opened one item to track and will complete the fix next week. 

And if it's good behavior that Automation-Sdk-Generate.ps1 doesn't generate any C# code, we can just ignore the .net track2 failure in this PR.

**Comment by zhenglaizhang** [comment]
> The question about only creating PRs based on the target branch is an interesting one. @zhenglaizhang what is the general workflow there? Does it always create a PR targeting a matching branch as the specs repo or does it always target main or is there some other logic?

The general flow is described in https://github.com/Azure/azure-rest-api-specs/tree/main/documentation/sdkautomation#sdk-automation-workflow.

there are 2 phases:
1. During spec repo PR phase, it open one preview PR in SDK repo fork https://github.com/AzureSDKAutomation/azure-sdk-for-go/pull/57 
2. When the spec repo PR merged, it will create release PR in the official SDK repo. https://github.com/AzureSDKAutomation/azure-sdk-for-go/pull/57

The 2nd phase, we currently only enables for merging PR to main branch, for other development branch like this PR base branch, release PR won't be created.

**Comment by jhendrixMSFT** [comment]
@heaths is this ready for merge?

**Comment by heaths** [comment]
@zhenglaizhang, except for Azure.Security.KeyVault.Administration, we don't use code generation for C#. But that one still is generated, so not sure why it's not getting picked up.

@jhendrixMSFT apart from that issue, yes, it's ready to merge. I don't see any reason to hold it.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@lmazuel could you please merge?

**Comment by zhenglaizhang** [comment]
@akning-ms please help remove required check `public.rest-api-specs (Syntax) ` for this branch as it has been deprecated.

**Pull request merged**
