### PR TITLE
Fix typo in common private links definition for actionsRequired

### PR DESCRIPTION
**Pull request by akning-ms**
### Changelog:
- Fixed typo actionRequired --> actionsRequired in common privatelinks.json
- Restore storage.json to use seperate privatelinks.json as it is hard to fix in server side
Background:
   - Requested by StorageSync team.
   - Currently only Storage and StorageSync team is referring to this common definition

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Juliehzl** [comment]
Add @priyaananthasankar for awareness,

**Review by ankushbindlish2 — APPROVED** [review]

**Review by allenjzhang — COMMENTED** [review]
Do we really want to fork a privateLink file into Storage again?

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Many example files needs to be updated to fix validation errors.

**Comment by akning-ms** [comment]
> Many example files needs to be updated to fix validation errors.

No need, as storage will keep actionRequired by using seperating privatelinks.json. @allenjzhang

**Comment by akning-ms** [comment]
> Do we really want to fork a privateLink file into Storage again?

Yes. refer to mail, that is a choose from Priyaranjan as it is hard to change in server  code. @priyapansrp to confirm

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
