### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version preview/2024-03-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/FumingZhang-containerservice-Microsoft.ContainerService-2024-03-02-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary>Click here to see the details of Step 1, Breaking Changes review</summary>

If you are in purview of Step 1 of the diagram, follow the [Breaking Changes review process].  
**IMPORTANT!** This applies even if you believe your PR was mislabeled, for any reason, including tool failure.
</details>

<details> 
<summary>Click here to see the details of Step 2, ARM review</summary>

See https://aka.ms/azsdk/pr-arm-review.
</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[Breaking Changes review process]: https://aka.ms/brch

### CODE REVIEW

**Comment by FumingZhang** [comment]
For the failure in [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/28612/checks?check_run_id=23548875713),
- `openShiftManagedClusters` related API paths from [aks/preview/2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/3116b3d1b1d498b79f81ac5904ce3fef5be4e0a3/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2019-10-27-preview/openShiftManagedClusters.json) are deprecated
- `fleets` related API paths from [aks/preview/2022-09-02-preview/fleets.json](https://github.com/Azure/azure-rest-api-specs/blob/3116b3d1b1d498b79f81ac5904ce3fef5be4e0a3/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2022-09-02-preview/fleets.json) are supported, but are published as a separate SDK, see [specification/containerservice/resource-manager/Microsoft.ContainerService/fleet/readme.md](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/fleet/readme.md)

image

**Comment by raosuhas** [comment]
>         "operationId": "LoadBalancers_Rebalance",

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/post-operation-id-contains-url-verb.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/post-operation-id-contains-url-verb.md)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:3836 in 19d06fc. [](commit_id = 19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee, deletion_comment = False)

**Comment by raosuhas** [comment]
>         }

Please review all the newly added properies in this PR and see if these can be represented as enums instead of booleans : 

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:8826 in 19d06fc. [](commit_id = 19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee, deletion_comment = False)

**Comment by raosuhas** [comment]
>         "allowServicePlacement": {

enum instead of boolean

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:9875 in 19d06fc. [](commit_id = 19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee, deletion_comment = False)

**Comment by nilo19** [comment]
Can we make those checks in the check-in pipeline? This will save a lot of engineering time.

**Comment by snguyen64** [comment]
> > ```
> >     }
> > ```
> 
> Please review all the newly added properies in this PR and see if these can be represented as enums instead of booleans :
> 
> https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:8826 in [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee). [](commit_id = [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee), deletion_comment = False)

hi,
for advanced networking.observability
we have discussed that boolean is the better route for our api. We are using enablement field to turn on/off our addon and we are tying our features into the aks sku tiers - different aks skus = different features. I don't see any value in changing the boolean to an enum here.
we also had some discussion here: [Advanced Networking - Overview (azure.com)](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/628111/Advanced-Networking)

**Comment by nilo19** [comment]
> > > ```
> > >     }
> > > ```
> > 
> > 
> > Please review all the newly added properies in this PR and see if these can be represented as enums instead of booleans :
> > https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:8826 in [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee). [](commit_id = [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee), deletion_comment = False)
> 
> hi, for advanced networking.observability we have discussed that boolean is the better route for our api. We are using enablement field to turn on/off our addon and we are tying our features into the aks sku tiers - different aks skus = different features. I don't see any value in changing the boolean to an enum here. we also had some discussion here: [Advanced Networking - Overview (azure.com)](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/628111/Advanced-Networking)

I also don't see the benefit of using string to replace boolean. In this way I need an extra conversion from bool to string in our code and this is not meaningful. Boolean appears to be a more concise choice for me.

**Comment by nilo19** [comment]
> > ```
> >     "operationId": "LoadBalancers_Rebalance",
> > ```
> 
> https://github.com/Azure/azure-openapi-validator/blob/main/docs/post-operation-id-contains-url-verb.md
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:3836 in [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee). [](commit_id = [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee), deletion_comment = False)

Can you suggest a operation id? Another error would be hit if change to `LoadBalancers_RebalanceLoadBalancers`.

**Comment by matthchr** [comment]
They likely want it to be called `ManagedCluster_RebalanceLoadBalancers` because it's hanging off of the managedCluster rather than a LoadBalancer?

**Comment by ramoka178** [comment]
> They likely want it to be called `ManagedCluster_RebalanceLoadBalancers` because it's hanging off of the managedCluster rather than a LoadBalancer?

This can work

**Comment by ramoka178** [comment]
>         "operationId": "LoadBalancers_Rebalance",

Try matthchr's suggested operationId

---
In reply to: [2060107330](https://github.com/Azure/azure-rest-api-specs/pull/28612#issuecomment-2060107330) [](http://example.com/codeflow?ancestors=2060107330)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:3836 in 19d06fc. [](commit_id = 19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee, deletion_comment = False)

**Comment by ramoka178** [comment]
> > > > ```
> > > >     }
> > > > ```
> > > 
> > > 
> > > Please review all the newly added properies in this PR and see if these can be represented as enums instead of booleans :
> > > https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md
> > > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:8826 in [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee). [](commit_id = [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee), deletion_comment = False)
> > 
> > 
> > hi, for advanced networking.observability we have discussed that boolean is the better route for our api. We are using enablement field to turn on/off our addon and we are tying our features into the aks sku tiers - different aks skus = different features. I don't see any value in changing the boolean to an enum here. we also had some discussion here: [Advanced Networking - Overview (azure.com)](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/628111/Advanced-Networking)
> 
> I also don't see the benefit of using string to replace boolean. In this way I need an extra conversion from bool to string in our code and this is not meaningful. Boolean appears to be a more concise choice for me.

Standard guidance is: replace boolean/switch properties with a more meaningful enum whenever possible.
A boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated].
Note: do NOT define a 'boolean enum' with two values 'True and False'. This might be easier to 'extend' in terms of types, but semantically its confusing, and no better than a boolean.

Since its a strong suggestion, please review and confirm from your side.

+ you can always compare enum to enum in code

**Comment by snguyen64** [comment]
> > > > > ```
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > Please review all the newly added properies in this PR and see if these can be represented as enums instead of booleans :
> > > > https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md
> > > > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-03-02-preview/managedClusters.json:8826 in [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee). [](commit_id = [19d06fc](https://github.com/Azure/azure-rest-api-specs/commit/19d06fcc530ac8b83e6452a26db4aa2e7a0cbbee), deletion_comment = False)
> > > 
> > > 
> > > hi, for advanced networking.observability we have discussed that boolean is the better route for our api. We are using enablement field to turn on/off our addon and we are tying our features into the aks sku tiers - different aks skus = different features. I don't see any value in changing the boolean to an enum here. we also had some discussion here: [Advanced Networking - Overview (azure.com)](https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/628111/Advanced-Networking)
> > 
> > 
> > I also don't see the benefit of using string to replace boolean. In this way I need an extra conversion from bool to string in our code and this is not meaningful. Boolean appears to be a more concise choice for me.
> 
> Standard guidance is: replace boolean/switch properties with a more meaningful enum whenever possible. A boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated]. Note: do NOT define a 'boolean enum' with two values 'True and False'. This might be easier to 'extend' in terms of types, but semantically its confusing, and no better than a boolean.
> 
> Since its a strong suggestion, please review and confirm from your side.
> 
> * you can always compare enum to enum in code

I see the value of enum overall, but for advanced network observability,  we only want to use this field to turn our feature on or off. The different features will be determined from ask cluster sku, so I don't think this feature will have any value from updating it to enum as stated. 
If this is blocking the api, then we can update it, but we don't plan on having other states such as "deallocated" or "suspended". Pretty much we only want a simple on/off for observability

**Comment by nilo19** [comment]
For a property with only two possible values, a boolean data type is the most suitable choice. Changing it to a string enum would introduce unnecessary complexity.

**Comment by TimLovellSmith** [comment]
@ramoka178 want to mark this PR approved based on your review or does it need further review?

**Review by ramoka178 — APPROVED** [review]
approved

**Pull request merged**
