### PR TITLE
chore: Add jsonfmt to CI

### PR DESCRIPTION
**Pull request by nschonni**
From the first commit, you can see what it will look like when it flags something https://github.com/Azure/azure-rest-api-specs/runs/158157607 and https://dev.azure.com/azure-sdk/public/_build/results?buildId=59285&view=logs&j=dd0cd357-d1b7-5790-a9ca-02e6141fdcee&t=f0dc0e92-0db8-5392-c719-0529f3430b64&l=18

### CODE REVIEW

**Comment by nschonni** [comment]
@sergey-shandar @jhendrixMSFT since most of the formatting PRs are landed, I figure it might be ok to introduce this again. I added a commit that finishes off the formatting changes, althought it is a cross a few APIs. Figure that doesn't matter since it is only whitespace changes, so generating the SDK shouldn't be needed

**Comment by erich-wang** [comment]
@nschonni , could you please fix CI errors first?
@sergey-shandar @jhendrixMSFT, do you have any comments?

**Comment by erich-wang** [comment]
one concern is that **caarlos0/jsonfmt** is maintained by individual and it may break

**Comment by jhendrixMSFT** [comment]
To me it looks good however I'm not super-familiar with the CI pipeline so @sergey-shandar will have to review that part.

**Comment by nschonni** [comment]
> @nschonni , could you please fix CI errors first?

I'll rebase again, but there is now #6529 6530 and #6531, but non of them have model validation errors (it was just blueprint)


> one concern is that **caarlos0/jsonfmt** is maintained by individual and it may break

Sure, maybe there is something else you'd prefer, but I found this was fast and pretty simple ([code-wise](https://github.com/caarlos0/jsonfmt/blob/master/main.go)). Looks like the author is also the maintainer for goreleaser, but I'm not sure if this tool is part of that large project or not.

**Comment by nschonni** [comment]
@erich-wang you can probably unselect the other reviews since they were added by CODEOWERS for files no longer included in the PR. Maybe add @sergey-shandar though

**Comment by erich-wang** [comment]
@nschonni , thank you for your contribution. Just discussed with @sergey-shandar, we suggested to remove jsonfmt job first from this PR because of legal issue.

**Comment by nschonni** [comment]
Not sure if it understand what the legal issue is? I did notice that they didn't explictly add the MIT license in the repo, but only the metadata, so I opened an issue for that

**Comment by erich-wang** [comment]
legal issue is one concern. Docker image maintained by individual is also unacceptable because:
1. That kind of docker image is black box to us, we can't take the risk
2. Individual may update/delete the docker image from hub without notification

**Comment by erich-wang** [comment]
@nschonni , do you plan to create new PR or update this PR to remove jsonfmt job? I'll close this PR if it is the former.

**Comment by nschonni** [comment]
A license has now been added to the repo (I believe that covers your legal concern). I'll swap over to Snap on a Ubunutu image if you have concerns with Docker.

**Comment by nschonni** [comment]
Sent a separate PR for the model validation in #6576

**Comment by erich-wang** [comment]
As I mentioned before, we're not going to depend on bits maintained by individual, which definitely introduces risk, .e.g somehow the individual delete the bits or update the bits with break change. So please remove the job for now, we may find out a feasible way later.

**Comment by nschonni** [comment]
@erich-wang what is an acceptable tool for you then? The CI is the important bit, since the diffs get getting introduced in the manual swagger generation.

>  we're not going to depend on bits maintained by individual, which definitely introduces risk

Is it because it isn't published to a repository? There are several things in package.json that are under individuals accounts

**Comment by erich-wang** [comment]
IMO, we should use the tool introduced by well known organization/company/person. We don't want to introduce any unnecessary risk into the CI.

> @erich-wang what is an acceptable tool for you then? The CI is the important bit, since the diffs get getting introduced in the manual swagger generation.
> 
> > we're not going to depend on bits maintained by individual, which definitely introduces risk
> 
> Is it because it isn't published to a repository? There are several things in package.json that are under individuals accounts

**Comment by nschonni** [comment]
The author is a well known enough that they are one of the early GH sponsored developers https://github.com/users/caarlos0/sponsorship as they created the main release automation tool for the GoLang ecosystem

**Comment by erich-wang** [comment]
@nschonni, if the person somehow delete the release (by accidentally), how should we handle it?

**Comment by nschonni** [comment]
@eric-wang, that's a good question. 2 ways I can see to protect against that if you think it might happen:
1. Store the .deb file in Azure DevOps artifacts instead of downloading from the GitHub release.
2. Build your own docker container and push it to your teams Azure Container Registry

**Comment by erich-wang** [comment]
> @eric-wang, that's a good question. 2 ways I can see to protect against that if you think it might happen:
> 
> 1. Store the .deb file in Azure DevOps artifacts instead of downloading from the GitHub release.
> 2. Build your own docker container and push it to your teams Azure Container Registry

Thank you, @nschonni. Could you help to create one issue to track the change request?

**Comment by erich-wang** [comment]
@nschonni , I just created new issue [Add Json format check to CI](https://github.com/Azure/azure-rest-api-specs/issues/6873) to track the request, and I'll close this PR tomorrow, please let me know if any concern.

**Pull request closed without merging**
