### PR TITLE
documentation updates

### PR DESCRIPTION
**Pull request by giromm2ms**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [X] I have reviewed the [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/202/Overall-Process-of-AME-Onboarding) for the workflow.
- [x] [Validation tools](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/84/Swagger-Validation-tools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/FAQ.md).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [X] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process]( https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review).

### CODE REVIEW

**Comment by giromm2ms** [comment]
Most of the changes are from our documentation team to rewrite some descriptions.
Yet, there is 1 change that might affect SDK creation which is the change of operation from secureScoreControlDefinitions_List to SecureScoreControlDefinitions_List

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by leni-msft** [comment]
@giromm2ms could you explain why you need change the operationId?

**Comment by giromm2ms** [comment]
There was a casing issue and I wanted to align it to be consistent with all other operation ids

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by leni-msft** [comment]
@giromm2ms got it. Which SDK are you going to release? I'd like to invite the sdk owners to review the breaking change.

**Comment by giromm2ms** [comment]
All, mainly python so we can wrap it with CLI and PS

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by leni-msft** [comment]
> operationId secureScoreControlDefinitions_List to SecureScoreControlDefinitions_List

@zikalino could you confirm the breaking change is ok with you?

**Comment by zikalino** [comment]
i don't think breaking changes here are caused by this PR, i think they were caused by another PR that was already merged. so this pr should be ok to merge

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
This rename:

operationId secureScoreControlDefinitions_List to SecureScoreControlDefinitions_List

Doesn't affect Python SDK, as these operations were not included in previous release

**Pull request merged**
