### PR TITLE
BREAKING CHANGE: Adl object refactor

### PR DESCRIPTION
**Pull request by begoldsm**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### Description
This PR addresses the following issues by restructuring our object models, which is a **breaking change**
* https://github.com/Azure/azure-rest-api-specs/issues/928
* https://github.com/Azure/azure-rest-api-specs/issues/772

Specifically we have done the following:
* Break up `JobInformation` into `CreateJobParameters`, `JobInformationBasic` and `JobInformation`
* Break up `DataLakeAnalyticsAccount` and `DataLakeAnalyticsAccountProperties` into those and Basic 
Versions
* Break up `DataLakeStoreAccount` and `DataLakeStoreAccountProperties` into those and Basic Versions

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by begoldsm** [comment]
@veronicagg this PR should address the validation issues that were opened previously. Can you take a look and help confirm? Is there something I need to run to ensure this fixes those issues?

**Comment by begoldsm** [comment]
@olydis is looking into why CI is failing here. It looks like it isn't properly running against Node 8 instead of Node 6. I will restart CI once it is fixed.

**Comment by olydis** [comment]
So it seems that Travis always picks up the config from the very branch you're trying to merge, even if it wasn't touched. I.e. it doesn't perform a git merge before getting that file... I've rebased your PR (#1433) and it works, so we can take it from there.

**Comment by olydis** [comment]
@begoldsm Model validation errors: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/254655271

**Review by olydis — APPROVED** [review]

**Pull request merged**
