### PR TITLE
Container Registries Data-plane API 07/2019 

### PR DESCRIPTION
**Pull request by estebanreyl**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.  **_- Definitely tried it, I am not certain it worked correctly however as it output no errors and I know there are some warnings from other validation tools._**

As a note a few linting issues could not be resolved as they are intrinsic in handling compatibility with docker's own expectations for registry API's I will also be following up in email as described in https://github.com/Azure/adx-documentation-pr/wiki/Swagger-Validation-Errors-Suppression

Preview Release for ACR data-plane API specification
This should be a fully functional release to address: https://github.com/Azure/azure-rest-api-specs/issues/6457 . 

Changes:
 + Added Put and Delete operations for v2/<name>/manifests/<reference>
 + Added oauth2 paths
 + Added support for V2 Manifests
 + Added improved and valid example files
 + Added appropriate security and host definitions

Bugfixes:
 + Cleaned up the entire swagger file re-using parameters and definition references
 + Fixed multiple improper response codes and incorrect parameters/return values

All paths have been verified and the generated client has been tested as well in C#. This should ideally lead to a release of a fully functioning .NET SDK.

As an edit we have decided to additionally add support for Go in this preview of our SDK

### CODE REVIEW

**Review by erich-wang — CHANGES_REQUESTED** [review]

**Comment by erich-wang** [comment]
@estebanreyl, sorry for late response. To speed up review, could you reorganize the PR: the first commit is copied from previous version, it is 2018-08-10 in your case, then make change based on first commit, in this way the reviewer could ignore APIs which are same as previous version and only focus on new/changed APIs, thanks.

**Comment by estebanreyl** [comment]
@erich-wang Do you mean as in just adding the original file (copy pasted to its new location) as the first commit so one can do a diff from there on? I could try rebasing  from there on and add that in if that will help at all? Nonetheless this swagger is based on a fork of a fork which was originally quite distant from the original. Ill try that out this afternoon and update.

**Comment by johanste** [comment]
This API is already in production. No need for a Azure REST API review board to review.

**Comment by erich-wang** [comment]
@estebanreyl , one question from @johanste:

And to verify, the casing changes for the model types are intentional?

**Comment by estebanreyl** [comment]
> @estebanreyl , one question from @johanste:
> And to verify, the casing changes for the model types are intentional?

Do you mean in the parameters area? I think that was just an effort to make them match the same style as those under definitions. I do realize I missed a couple however. Should those all be lowercased? I am happy to change them if that is the case.

**Comment by erich-wang** [comment]
> > @estebanreyl , one question from @johanste:
> > And to verify, the casing changes for the model types are intentional?
> 
> Do you mean in the parameters area? I think that was just an effort to make them match the same style as those under definitions. I do realize I missed a couple however. Should those all be lowercased? I am happy to change them if that is the case.

@johanste to response

**Comment by johanste** [comment]
If you are going to change things for consistency, I'd prefer it to end up being 100% consistent. But it also looks like the parameters were not referenced (at least not from this file) in the previous version of the swagger. Either way, for a preview, this is not a strict requirement - especially since it is changing parameter reference model names (as opposed to the name of the actual parameter changing)

**Comment by estebanreyl** [comment]
@johanste I'll make a note and include it in the upcoming next release or fix it now if there is anything else stopping this from going through. Is there anything else I should look into?

**Comment by estebanreyl** [comment]
@johanste , @erich-wang Any chance we get an update on what we are missing if anything here so we can proceed with this one?

**Comment by johanste** [comment]
I'm good. @erich-wang ?

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
