### PR TITLE
Azure Event Grid: Add support for 2021-06-01-preview swagger

### PR DESCRIPTION
**Pull request by ahamad-MS**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

Add support for 2021-06-01-preview swagger

NOTE. This swagger was already reviewed and approved by ARM team and available in private repro here: https://github.com/Azure/azure-rest-api-specs-pr/pull/3437

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [X] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
 
Already in Central US Euap; Remaining regions ends Monday: 6/14/2021

  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
ASAP, Moday 6/14/2021 as we are promising customer for feature availablility and tests blocked on availability of ARM Manifest in all regions (hence, the need for public swagger ASAP) in public repo.

NOTE. This swagger was already reviewed and approved by ARM team and available in private repro here: https://github.com/Azure/azure-rest-api-specs-pr/pull/3437

  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [X] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

NOTE. This swagger was already reviewed and approved by ARM team and available in private repro here: https://github.com/Azure/azure-rest-api-specs-pr/pull/3437

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
For easy review, Per ARM guide in first comment:
 **Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.**

**Comment by ahamad-MS** [comment]
@akning-ms I added previous preview API version 2020-10-15-preview as a baseline for commit #2 and then reapply the new code in commit #1

Can you plz help with the Swagger Avocado failure? it is false positive due to applying the old api version files in commit #2.. I am not able to rerun this test and the missing file is already there now.

Also, I am not able to understand the failure in python track 2 .. We did not change anything in swagger in topic (this is existing code/definition_

**Review by Kishp01 — APPROVED** [review]

**Comment by akning-ms** [comment]
For avocado, guess you can fix it by removing preview/2021-06-01-preview/examples/PartnerRegistrations_List.json
as you removed the path

**Comment by akning-ms** [comment]
@msyyc  to help on why track2 python sdk gen failure

**Comment by akning-ms** [comment]
As ARM reviewed in private repo. so it is not need here

**Comment by msyyc** [comment]
@ahamad-MS There is breaking change in the new content compared with older swagger. Is it necessary?
info	[Changelog] **Breaking changes**
info	[Changelog]
info	[Changelog]   - Removed operation PartnerRegistrationsOperations.list
info	[Changelog]   - Model PartnerNamespaceUpdateParameters has a new signature

**Comment by ahamad-MS** [comment]
Hello @msyyc ... Thanks for looking into this .. Short answer  : yes necessary..

Please note: that this swagger was already reviewed and approved by ARM team and available in private repro here: Azure/azure-rest-api-specs-pr#3437

Regarding:
1. Removed operation PartnerRegistrationsOperations.list --> This is not implemented functionality (We actually return not implemented error in case anyone called it). Our design POV had changed and this method is not considered anymore. Hence, we are removing this functionality to remove any confusion.

2.  Model PartnerNamespaceUpdateParameters has a new signature ---> this is necessary to accomodate for the new private link related parameters. Also, this PATCH call was not implemented before from service side and was always returning Not implemented. This will be the first time we implement this method with the correct/needed parameters.
thanks

**Pull request merged**
