### PR TITLE
[Hub Generated] Review request for Microsoft.Devices to add version stable/2021-02-01

### PR DESCRIPTION
**Pull request by artemrd**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/artemrd/azure-rest-api-specs/dev-deviceprovisioningservices-Microsoft.Devices-2021-02-01...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify - fixing an issue in existing API.
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet. - Feb 2021
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. - Feb 2021
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [x] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
Hi @artemrd, For lint failure, to keep consistent, we can suppress R4007 - DefaultErrorResponseSchema
For  R4009 - RequiredSystemDataInNewApiVersions, as it is required by ARM, we can suppress in this version.
But you may have a plan to support it in the future.  @jianyexi to help guide you how to suppress it if you need.
BTW, can you help review first comment in PR and fill the info you have to provide more context for your PR purpose?

**Comment by artemrd** [comment]
Ok, sounds good. How can I suppress these errors?

**Comment by weidongxu-microsoft** [comment]
You can refer to some other services e.g. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/readme.md#suppression

Again, this seems a complete new api-version and also adding new APIs. Please check `What's the purpose of the update?` section accordingly. This PR will not get reviewed until the basic intention is correct.

**Comment by artemrd** [comment]
What do you recommend if we need to fix a bug, but can't change existing methods behavior to not break customers which already use them in their workflows? We decided to mark existing methods as deprecated and introduce new ones. Implementation refactoring to support new features is not feasible at this point. We'll have a separate task to make our API compatible with the requirements.

**Comment by weidongxu-microsoft** [comment]
This PR added a new 2020-02-01 api-version, and call it a bug fix...

By standard procedure, the 2020-02-01 get reviewed and approved, then service get onboard.

I do not block PR nor your suppression. I just want to point out that this should not ever happen again. API first, then implementation.

**Comment by artemrd** [comment]
What do you recommend for bug fixes which change behavior? Use existing API version?

**Comment by weidongxu-microsoft** [comment]
Firstly, I do not see what exactly is the "bug fix" in this PR. What I saw is adding a new API via https://github.com/Azure/azure-rest-api-specs/pull/12284/commits/fb1344e1ef679b8602f3f58dd053994897207db0, and a deprecate of an old API. This still is adding new API, and you need involve **ARM review** on this.

Secondly, I can understand that fixing the response schema (R4007) could be a behavior change and one be cautious about it. But why adding the "systemData" (R4009) is behavior change? Adding new read-only property to existing schema is not even breaking changes in same api-version.

**Pull request closed without merging**
