### PR TITLE
Fix: Capacity is a mandatory Property

### PR DESCRIPTION
**Pull request by solankisamir**
### Latest improvements:
- This is a preview version of the API and capacity property on the Resource is actually mandatory in this version. This PR is just for fixing the mistake in the spec.

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by ravbhatnagar — APPROVED** [review]
signing off from ARM side.

**Comment by solankisamir** [comment]
@njuCZ can you merge this PR?

**Comment by akning-ms** [comment]
It is fine for breaking change fail as it is in preview version and no client use it.  but need to fix modal validation fail:  caused by changing capacity from not required to required.  need to change related  example file to add the property

**Comment by solankisamir** [comment]
@njuCZ fixed the issue with model validation. Thanks

**Comment by solankisamir** [comment]
@akning-ms can you take a look at this Pr? Almost ready to merge.

**Comment by solankisamir** [comment]
@njuCZ @akning-ms @allenjzhang can you unblock us?

**Comment by solankisamir** [comment]
@njuCZ any update blocking this?

**Pull request merged**
