### PR TITLE
Added Extended location property to Microsoft.Compute VM, VMSS & Image Resources and edgeZone parameter for image discovery APIs

### PR DESCRIPTION
**Pull request by pavanrachapudy**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by pavanrachapudy** [comment]
Adding support for the new “extendedLocations” ARM property. Specs here:
1. [ARM Edge Location Design](https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/Doc.aspx?sourcedoc=%7B7178262A-BC22-49C9-80C4-3A12D7C9B03B%7D&file=ARM%20Edge%20Location%20Design.docx&wdLOR=cC515FAB5-6C4D-4BFF-A210-9970E2B1C3AD&action=default&mobileredirect=true&CID=D913F4B2-7DCA-41A8-96C8-3AA28CF29DDC)
2. [Extending Azure location](https://microsoft.sharepoint.com/:w:/r/teams/azureresourcemanagerteam/_layouts/15/Doc.aspx?sourcedoc=%7B61F76676-CE74-4D86-BCFA-61929F5F7CB7%7D&file=Extending%20Azure%20location.docx&action=default&mobileredirect=true&CID=199316B5-3AB5-4104-8DA2-2E9B2E615E58&wdLOR=cE3229FAF-34C5-422F-A380-84F6B852D39D)

Introducing the new top property “extendedLocation” which is a complex property with its own “type” and “name” properties. Presumably there will be other extended location types, but its not clear which ones will have relevance to Microsoft.Compute. Currently the only type that is supported in “EdgeZone”.

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
hi @PhoenixHe-msft could you pls help to look at SDK Net task failure? thanks. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=583024&view=logs&j=b6885ff5-5b63-57e7-07bc-9d8d90d734f1&t=edefe71f-a8fe-52c2-c45d-59609a33c1f2

**Comment by yungezz** [comment]
hi @pavanrachapudy is this PR ready to merge? SDK NET failure isn't a required CI task

**Comment by DwayneNeed** [comment]
> hi @PhoenixHe-msft could you pls help to look at SDK Net task failure? thanks. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=583024&view=logs&j=b6885ff5-5b63-57e7-07bc-9d8d90d734f1&t=edefe71f-a8fe-52c2-c45d-59609a33c1f2

Seems to be related to run commands?

- ScenarioTests/VMRunCommandsTests.cs(111,25): error CS0246: The type or namespace name 'VirtualMachineRunCommand' could not be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
- ScenarioTests/VMRunCommandsTests.cs(136,25): error CS0246: The type or namespace name 'VirtualMachineRunCommandUpdate' could not be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
- ScenarioTests/VMRunCommandsTests.cs(146,51): error CS0246: The type or namespace name 'VirtualMachineRunCommand' could not be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
- ScenarioTests/VMRunCommandsTests.cs(146,98): error CS0246: The type or namespace name 'VirtualMachineRunCommand' could not be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
- ScenarioTests/VMRunCommandsTests.cs(176,63): error CS0246: The type or namespace name 'VirtualMachineRunCommandInstanceView' could not be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
-

**Comment by pavanrachapudy** [comment]
@yungezz Updated the existing PR with image discovery APIs for edge zone as well. It will be great if you can review this as well.

**Comment by yungezz** [comment]
> @yungezz Updated the existing PR with image discovery APIs for edge zone as well. It will be great if you can review this as well.

sure. this latest change adding new APIs, will add `WaitForARMFeedback` to get ARM reviewing.

**Review by pilor — APPROVED** [review]

**Comment by PhoenixHe-msft** [comment]
@DwayneNeed It's related to test project build failure. I think you can ignore this now.

**Comment by yungezz** [comment]
hi @pavanrachapudy , is this PR ready to merge, that means service change is on Prod already.

**Comment by yungezz** [comment]
> hi @pavanrachapudy , is this PR ready to merge, that means service change is on Prod already.

ping for update.

**Review by Sandido — APPROVED** [review]

**Pull request merged**
