### PR TITLE
 Adding swagger changes for GET and LIST replicationEligibilityResults API

### PR DESCRIPTION
**Pull request by punit-bhatt**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by punit1396** [comment]
This extension type API has already been approved by the ARM team.
The API validates if a VM can be protected or not. Thus, the results are read only. As you can see, all the properties are readOnly.

**Comment by punit1396** [comment]
LintDiff tests are failing with the following error

R2059 - UniqueResourcePaths
**Multiple resource providers are not allowed in a single spec. More than one the resource paths were found: 'Microsoft.RecoveryServices, Microsoft.Compute'**.

But since this is an extension routing type API, the uri will contain 2 providers.

**Comment by punit1396** [comment]
ModelValidation tests are failing due to older properties checked in probably before the model validation started running. The errors have nothing to do with the properties added in this PR.
We have a work item open for the same but that has been getting delayed indefinitely. Will take it up and open a PR for the same by the end of this week.

**Comment by punit1396** [comment]
Have suppressed the UniqueResourcePaths error type. Having another spec wouldn't have worked because either of the specs will have 2 providers in it leading to the same issue.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
