### PR TITLE
[Hub Generated] Review request for Microsoft.CostManagement to add version stable/2019-11-01

### PR DESCRIPTION
**Pull request by sashahdo**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/sashahdo/azure-rest-api-specs/dev-cost-management-Microsoft.CostManagement-2019-11-01...master/).

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by sashahdo** [comment]
the Grouping property is not supported in Forecast API, this change is to remove the property from Forecast. Hence the detected breaking change

**Comment by erich-wang** [comment]
do you mean the `grouping` is never supported in the API?  The change is just to align with API?

**Comment by sashahdo** [comment]
> do you mean the `grouping` is never supported in the API? The change is just to align with API?

yes. grouping is never supported. This change is indeed just to align with API

**Comment by erich-wang** [comment]
@sashahdo, if user calls the modified API with providing `grouping` value, will your service ignore `grouping` value or return failure?  If it is latter, this is break change for our customers, and you may need follow the [policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/54469/Getting-Started)

**Comment by sashahdo** [comment]
> @sashahdo, if user calls the modified API with providing `grouping` value, will your service ignore `grouping` value or return failure? If it is latter, this is break change for our customers, and you may need follow the [policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/54469/Getting-Started)

@erich-wang, the API itself has not been modified. Our service ignores the `grouping` value.

**Comment by erich-wang** [comment]
As this PR is introducing breaking change for Java/Python SDKs, so I'm going to close this PR, please let us know if any concern.

**Comment by sashahdo** [comment]
> As this PR is introducing breaking change for Java/Python SDKs, so I'm going to close this PR, please let us know if any concern.

This change is identical to the one in 2020-06-01, which you approved.
Why treat this PR differently?

**Comment by sashahdo** [comment]
I see that this introduces a breaking change for java/python sdks, so what's the appropriate course of action here?
The `grouping` property is not and has never been supported by forecast.

**Comment by erich-wang** [comment]
> I see that this introduces a breaking change for java/python sdks, so what's the appropriate course of action here?
> The `grouping` property is not and has never been supported by forecast.

To avoid the breaking change for existing SDKs users, we prefer to keep the property and add proper description.
As to version 2020-06-01, there's no SDKs for it, that is why we approve it.

**Comment by erich-wang** [comment]
@sashahdo, I'm going to close this PR because of breaking change to existing SDKs, please let us know if any concern.

**Comment by erich-wang** [comment]
Close this PR as no feedback from @sashahdo, please send me email if you have any further question.

**Pull request closed without merging**
