### PR TITLE
EventHub: Reverting the breaking changes of property and definition name changes

### PR DESCRIPTION
**Pull request by v-Ajnava**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

Reverting the changes done in PR https://github.com/Azure/azure-rest-api-specs/pull/958, as we will be taking these changes next RP version. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by v-Ajnava** [comment]
Reverting the changes done in PR #958, as we will be taking these changes next RP version.

**Comment by vishrutshah** [comment]
I see that @anudeepsharma & @anuchandy were involved in the approval process of the PR #958. It'd be great if you could please review this PR and make sure they are covering all the things that were pushed into the previous PR? Thanks!

**Review by vishrutshah — CHANGES_REQUESTED** [review]
@v-Ajnava when reverting already checked-in changes, we'd expect you use `git revert {commit-hash}` command and send a PR for only those changes. That'd make things simple and easier to review between what is being reverted and what is being updated by you intentionally. Please do that. Thanks!

**Comment by v-Ajnava** [comment]
@vishrutshah, reverted the commits and added the examples. please review  and let know your comments. Thanks !!

**Comment by vishrutshah** [comment]
Closing this PR as as @v-Ajnava will create new PR with "ONE" commit for the changes in swagger  + "ONE" commit with adding other "x-ms-examples". Thanks @v-Ajnava for your co-operation. Appreciate it. Thanks

**Pull request closed without merging**
