### PR TITLE
[Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01

### PR DESCRIPTION
**Pull request by solankisamir**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/solankisamir/azure-rest-api-specs/apim_2019-01-01...master).

fixes issues
- https://github.com/Azure/azure-rest-api-specs/issues/1881
- https://github.com/Azure/azure-rest-api-specs/issues/2570

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by solankisamir** [comment]
@shahabhijeet do you know why the .NET SDK generation failed? I do have a couple of breaking changes in the OperationId.

**Comment by solankisamir** [comment]
@KrisBash @sergey-shandar can you review this new apiversion spec?

**Review by KrisBash — APPROVED** [review]
Changes lgtm

**Review by promoisha — APPROVED** [review]

**Comment by solankisamir** [comment]
@sergey-shandar a gentle ping on this!

**Review by sergey-shandar — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@solankisamir .NET SDK is failing to compile due to the following compile error, meaning SDK is not getting generated properly with your new Spec.
I don't think this spec can be merged in it's current form.

Customization\Models\SubscriptionContract.cs(18,48): error CS1061: 'SubscriptionContract' does not contain a definition for 'ProductId' and no accessible extension method 'ProductId' accepting a first argument of type SubscriptionContract' could be found (are you missing a using directive or an assembly reference?) [D:\myFork\sdkForNet\master\src\SDKs\ApiManagement\Management.ApiManagement\Microsoft.Azure.Management.ApiManagement.csproj]
Customization\Models\SubscriptionContract.cs(20,33): error CS1061: 'SubscriptionContract' does not contain a definition for 'ProductId' and no accessible extension method 'ProductId' accepting a first argument of type 'SubscriptionContract' could be found (are you missing a using directive or an assembly reference?) [D:\myFork\sdkForNet\master\src\SDKs\ApiManagement\Management.ApiManagement\Microsoft.Azure.Management.ApiManagement.csproj]
Customization\Models\SubscriptionContract.cs(31,48): error CS1061: 'SubscriptionContract' does not contain a definition for 'UserId' and no accessible extension method 'UserId' accepting a first argument of type 'SubscriptionContract' could be found (are you missing a using directive or an assembly reference?) [D:\myFork\sdkForNet\master\src\SDKs\ApiManagement\Management.ApiManagement\Microsoft.Azure.Management.ApiManagement.csproj]
Customization\Models\SubscriptionContract.cs(33,33): error CS1061: 'SubscriptionContract' does not contain a definition for 'UserId' and no accessible extension method 'UserId' accepting a first argument of type 'SubscriptionContract' could be found (are you missing a using directive or an assembly reference?) [D:\myFork\sdkForNet\master\src\SDKs\ApiManagement\Management.ApiManagement\Microsoft.Azure.Management.ApiManagement.csproj]

**Comment by solankisamir** [comment]
@shahabhijeet yes, we have made breaking changes in the SubscriptonContract, and the customization would need to be updated.

**Pull request merged**
