### PR TITLE
Correct parameter name and configuration for Radius server for VPNGat…

### PR DESCRIPTION
**Pull request by ritwikbasu**
…eways

Correct parameter name and configuration for Radius server for
VPNGateways

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by veronicagg** [comment]
@ritwikbasu is this a bug fix? or is the service changing? Looks like the properties are moved to another model and renamed, so it's a breaking change. 
@ravbhatnagar please take a look.

**Review by veronicagg — CHANGES_REQUESTED** [review]
change is small, but it's a breaking change so posted some questions.

**Comment by ritwikbasu** [comment]
This is a bug fix - the person who wrote the initial changes was unaware of the mapping conventions between rest-api and NRP contract names and used the incorrect parameter names and the incorrect structure.

Also, this feature is currently under development and has not been exposed to customers yet. This issue was caught in our powershell testing for this same feature and hence the bugfix.

**Comment by veronicagg** [comment]
@ritwikbasu thanks for clarifying, also based on our offline conversation the service is deployed, behind a feature flag.

**Review by veronicagg — APPROVED** [review]

**Pull request merged**
