### PR TITLE
Application gateway Identity and Keyvault support

### PR DESCRIPTION
**Pull request by akshaysngupta**
This PR adds support for identity and keyvault on Application Gateway.

1) Managed Identity is top-level property defined by the MSI team which is supported by ARM and NRP (release 110).
2) For Keyvault support, SslCertificate and TrustedRootCertificate sub resource in AppGW have keyVaultSecretId field which will have secretId (url) to a secret or certificate object in keyvault. The above mentioned identity will be used to authenticate to keyvault.

Reference code:
CRP: https://github.com/Azure/azure-rest-api-specs/pull/3183/files
Datalake: https://github.com/Azure/azure-rest-api-specs/blob/1c4c94911c840bcab2e7e7541433713f9de4a819/specification/datalake-store/resource-manager/Microsoft.DataLakeStore/stable/2016-11-01/account.json#L1518

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jianghaolu** [comment]
@akshaysngupta You didn't add 386 files, did you? :)

I think the api version should be 2018-10-01? Can you please double check?

**Comment by jianghaolu** [comment]
You might want to sync with upstream/network-november-release.

Also, in the future, if you are the first one to create a new API version, please do so from here https://portal.azure-devex-tools.com/app/branch/create and create 2 commits. The first commit for copying the old API version without modifying anything and the additions in the second commit. Thank you!

**Comment by hassanbabaie** [comment]
@akshaysngupta Just checking as I noticed your commit, is this to add authenticated access for Application Gateway protected/fronted applications? We've been waiting for this feature so it would be good to know if it might be coming.

Thanks

hass

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
@akshaysngupta  as I mentioned before offline, november branch is for 2018-10-01 api version, not for 2018-11-01, so you have NOT to add 2018-11-01 for november branch. please wait for december :) 
I see [do not merge], but not sure why to create this PR now? You'll have tens of merge conflicts in a month with this PR

**Comment by akshaysngupta** [comment]
@MikhailTryakhov I have updated the PR.
@hassanbabaie this is allow Application Gateway to fetch/rotate certificates using keyvault.

**Comment by akshaysngupta** [comment]
@ravbhatnagar Can you take a look ?

**Review by jianghaolu — APPROVED** [review]

**Review by MikhailTryakhov — APPROVED** [review]

**Pull request merged**
