### PR TITLE
Marketplace miberezi 2020

### PR DESCRIPTION
**Pull request by MiriBerezin**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ruowan** [comment]
Why do you change the type?

**Comment by MiriBerezin** [comment]
Hi @Ruoxuan Wang<mailto:Ruoxuan.Wang@microsoft.com>

As part of fixing S360 items I changed this swagger spec and I by mistake I put string instead of Boolean.

I got s360 item on that.

Thanks!

Miri

**Comment by ruowan** [comment]
But your PR introduces breakingChange. Pls see comments https://github.com/Azure/azure-rest-api-specs/pull/11543#issuecomment-722224460. And follow breakingChange policy

**Comment by MiriBerezin** [comment]
I already had a thread with @Renhe Li<mailto:Renhe.Li@microsoft.com> and breaking changes team ( attached email thread on that)
We understand that those breaking changes are required and @Renhe Li<mailto:Renhe.Li@microsoft.com> approved the prev PR

This is only a small fix above those changes.

I hope this is clear now

   Miri

**Comment by ruowan** [comment]
What's your previous PR. I could refer to this.

**Comment by MiriBerezin** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/11279<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F11279&data=04%7C01%7CMiri.Berezin%40microsoft.com%7Cb92bf3f05bc54bb9ff3608d87c216adb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637395830304618872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yWuLO%2Fz%2FY0zX2oaztitqIV5GNcVGM4I6RuEhGG2jpH4%3D&reserved=0>

**Review by ruowan — APPROVED** [review]

**Pull request merged**
