### PR TITLE
[Hub Generated] Review request for Microsoft.RecoveryServices to add version stable/2023-02-01

### PR DESCRIPTION
**Pull request by shesamian**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/shesamian-recoveryservicessiterecovery-Microsoft.RecoveryServices-2023-02-01...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>         "extendedLocationMappings": {

Does this have a fixed set of values? If so, it should be modeled as a string enum.

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/service.json:11655 in ad65e7c. [](commit_id = ad65e7cf20a4140e13ef60800b3776f1e29d478f, deletion_comment = False)

**Comment by mentat9** [comment]
>         "locationDetails": {

Model as enum?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/service.json:11659 in ad65e7c. [](commit_id = ad65e7cf20a4140e13ef60800b3776f1e29d478f, deletion_comment = False)

**Comment by shesamian** [comment]
@mentat9
`extendedLocationMappings` and `locationDetails` are not enums, unfortunately. They are expressions as strings.

This is what a sample URL look like:

```
https://management.azure.com/Subscriptions/ffc37441-49e9-4291-a520-0b2d4972bb99/resourceGroups/rec-svc-ez-canary/providers/Microsoft.RecoveryServices/vaults/rec-svc-vault-test/replicationFabrics/asr-a2a-default-eastus2euap?%24filter=ZoneToZoneMappings eq %27true%27 and ExtendedLocationMappings eq %27true%27 and LocationDetails eq %27true%27&api-version=2023-02-01
```

**Comment by mentat9** [comment]
> @mentat9 `extendedLocationMappings` and `locationDetails` are not enums, unfortunately. They are expressions as strings.
> 
> This is what a sample URL looks like:
> 
> ```
> https://management.azure.com/Subscriptions/ffc37441-49e9-4291-a520-000000000000/resourceGroups/rec-svc/providers/Microsoft.RecoveryServices/vaults/rec-svc-vault-test/replicationFabrics/asr-a2a?%24filter=ZoneToZoneMappings eq %27true%27 and ExtendedLocationMappings eq %27true%27 and LocationDetails eq %27true%27&api-version=2023-02-01
> ```

Right, but you don't want to allow 'locationDetails' eq 'gzornoplatt'. If you spec these as string enum (locationDetails { true, false } with modelAsString: true) the format will be the same, but the only allowed values will be true/false. Ref: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-enum.

**Comment by shesamian** [comment]
@mentat9  Thank you so much for the feedback. I think I fixed it. I appreciate your feedback/review.

**Comment by mentat9** [comment]
>         "extendedLocationMappings": {

Thank-you for making this change. This approach would work, but in retrospect it's not an improvement on unrestricted string. My recommendation was intended to model just the query parameter values alone as an enum (e.g. extendedLocationMappingValue: {true, false}). Putting the entire query expression as an enum value is problematic (e.g. whitespace variations, casing on the property name and operators, etc.). Breaking these values down to components will required more spec work (and I'm not sure it would work with x-ms-odata). If you prefer to revert back to unrestricted string, it's fine.

---
In reply to: [1457290377](https://github.com/Azure/azure-rest-api-specs/pull/22930#issuecomment-1457290377) [](http://example.com/codeflow?ancestors=1457290377,1457290377)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/service.json:11655 in ad65e7c. [](commit_id = ad65e7cf20a4140e13ef60800b3776f1e29d478f, deletion_comment = False)

**Comment by mentat9** [comment]
>         "locationDetails": {

Need to break these down so only the values are enum (see my other comment). Otherwise, you can revert back to unrestricted string for the whole query parameter.

---
In reply to: [1457290402](https://github.com/Azure/azure-rest-api-specs/pull/22930#issuecomment-1457290402) [](http://example.com/codeflow?ancestors=1457290402,1457290402)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/service.json:11659 in ad65e7c. [](commit_id = ad65e7cf20a4140e13ef60800b3776f1e29d478f, deletion_comment = False)

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
Let me know if it's ready to merge.

**Comment by shesamian** [comment]
@raych1 it is ready to be merged. Thank you so much for the review

**Pull request merged**
