### PR TITLE
Remove routingConfigNfv

### PR DESCRIPTION
**Pull request by rutuja-s**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - _Fixing the Routing Configuration property for NVA connection. This API is not publicly available yet and this change should not have any cx impact_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by rutuja-s** [comment]
NVA connection (just another virtual wan connection) is an Nfvrp resource as opposed to other connections in virtual wan (VPN, Express route etc) which are Nrp resources. RoutingConfigurationNfv was a new definition added as a Nfvrp version of already existing definition of RoutingConfiguration (used by Nrp resources) in the Swagger. The difference in this definition is as below: 

Existing Routing configuration has reference ‘#definitions/SubResource’ which uses property name ‘Id’ and the result is looks like below :
```
routingConfiguration": {
            "associatedRouteTable": {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualHubs/virtualHub1/hubRouteTables/hubRouteTable1"
            },

```
 and Nfvrp version of Routing configuration was intended to have this same same property named as ResourceUri instead of id as below:
```
"routingConfiguration": {
            "associatedRouteTable": {
              "resourceUri": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualHubs/virtualHub1/hubRouteTables/hubRouteTable1"
            },
```

To achieve this, we introduced a new definition in previous API versions which would allow this change from id -> resourceUri
```
"RoutingConfigurationNfvSubResource": {
      "type": "object",
      "properties": {
        "resourceUri": {
          "type": "string",
          "description": "Resource ID."
        }
      },
      "description": "Reference to RouteTableV3 associated with the connection."
    },
```


However, in recent reviews and discussions for NVA connection, it was decided to have same Routing configuration property for all the connections to have consistency across them so that portal/terraform or anyone else using rest doesn’t need different automation based on connection type. This would also providing consistent results to the customers. In order to have this consistency, I’ve removed RoutingConfigurationNfv and used RoutingConfiguration instead which is now being flagged as a breaking change in 2023-06-01.

On the customer impact side, NVA connection feature is not yet enabled and hence we do not have any active users that would be impacted by this change.

**Comment by Joanna-Yang-Art** [comment]
@rutuja-s Please get your PR merged before code freeze date 10/12

**Comment by rutuja-s** [comment]
@Joanna-Yang-Art many failing checks above are not due to the change introduced in this PR. Should this be overridden?

**Comment by Joanna-Yang-Art** [comment]
> rutuja-s
Could you try rerun failed tests? If still didn't work please reach out to ARM or swagger team to provide the feedback
Swagger: [renhe.li@microsoft.com](mailto:renhe.li@microsoft.com); [raychen@microsoft.com](mailto:raychen@microsoft.com)

**Comment by Joanna-Yang-Art** [comment]
@rutuja-s Please get your PR reviewed and merged by ARM team by NRP code freeze date 10/12. NRP won't help review any swagger PRs, ARM does

**Review by scbedd — APPROVED** [review]
Super leery of approving this, but I don't see another option to quickly unblock.

I've asked the owning team to link the issue created to actually address the failures as a comment on this PR.

**Comment by rkmanda** [comment]
pl address the model validation failures and request merge after that is addressed

**Comment by rutuja-s** [comment]
thanks @scbedd. Created a work item for the owning team to follow up on this: https://msazure.visualstudio.com/One/_workitems/edit/25472863

**Comment by rutuja-s** [comment]
@rkmanda , @scbedd helped with the approval for model validation failures. Can you please help us with necessary approvals/merge?

**Comment by scbedd** [comment]
> pl address the model validation failures and request merge after that is addressed

I defer to Roopesh's decisions here. He is the true arbiter.

**Comment by rutuja-s** [comment]
@rkmanda, as additional info to ignore ModelValidation failures for this PR :- our service is **not on RPaaS**

**Comment by azgcloudev** [comment]
vwan model validatione errors on release 2023-05 are addressed in changes in PR #25449 

The PR still block due to lint diff errors.

**Comment by rutuja-s** [comment]
@rkmanda, the validation failure part is owned by the vwan team and is being worked on actively as a separate work item as mentioned by @azgcloudev above

**Comment by ms-zhenhua** [comment]
please fix error in https://github.com/Azure/azure-rest-api-specs/pull/25962/checks?check_run_id=17623740675. Then rerun /pr RequestMerge

**Review by ms-zhenhua — APPROVED** [review]

**Comment by Joanna-Yang-Art** [comment]
@rutuja-s please request ARM to get the PR merged as soon as possible. NRP don't help review and approve PRs

**Comment by rutuja-s** [comment]
@rkmanda can you please help with the pr merge? I have all the necessary approvals

**Comment by rkmanda** [comment]
waiting for all checks to pass

**Comment by rutuja-s** [comment]
@rkmanda any update on this merge?

**Comment by rkmanda** [comment]
azp /run

**Comment by rkmanda** [comment]
automated checks are stuck, waiting for those to finish

**Comment by rkmanda** [comment]
Pl get help from the API spec review channel to get unblocked on these stuck checks you can tag Konrad Jamrozik in your post

**Pull request merged**
