### PR TITLE
[arm-authorization] Adding / before providers

### PR DESCRIPTION
**Pull request by vishrutshah**
Seems suspicious to not have `/` int he path. 

Feel free to comment if you have any prior knowledge on why it may be right.

### CODE REVIEW

**Comment by johanste** [comment]
Have we released any SDKs based on this swagger? The change looks good to me, but if we have actual working SDKs, then this may break their usage...

**Comment by vishrutshah** [comment]
@johanste Seems like we have released .NET sdk.

Reference: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Authorization/Microsoft.Azure.Management.Authorization/Generated/RoleAssignmentsOperations.cs#L128
Test: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Authorization/Authorization.Tests/Tests/Permissions.ScenarioTests.cs#L125

**cc:**
@shahabhijeet / @markcowl Do we know whether this is working as expected or did we have some patch to make this work?

**Comment by veronicagg** [comment]
@vishrutshah change looks good to me too, let's figure out the answers to the questions brought up above, if there are no breaking issues to SDKs then, let's do it. I wonder why this type of thing is not caught at some point (code generation or tests), since the URL looks incorrect.

**Review by veronicagg — COMMENTED** [review]
left a comment inline.

**Comment by veronicagg** [comment]
@vishrutshah any updates?

**Comment by vishrutshah** [comment]
@shuagarw Could you please throw some light on this one? Thanks!

**Comment by vishrutshah** [comment]
@veronicagg I've also sent an internal email so let's wait for couple of days and see. Thanks for reminding on this one!

**Comment by vishrutshah** [comment]
Here is the response:

> Hi Vishrut,
I agree that the missing “/” looks like a typo. The Swagger specs were not written by my team. So I am not sure how well they have been tested.
Our PowerShell cmdlets are still using the .NET SDK generated from Hydra specs.
 
@veronicagg @johanste @ravbhatnagar Based on response looks like a bug...Thoughts?

**Comment by veronicagg** [comment]
@vishrutshah I agree, it looks like bug. It also appears that the team is not using Swagger to generate SDKs, right? If so, I think it's safe to make the change (as it's currently not being picked up by anything). 
I'll approve and you can decide to merge based on the answer to this last question and/or others' thoughts.

**Comment by veronicagg** [comment]
Please check CI as well.

**Review by veronicagg — APPROVED** [review]

**Comment by lmazuel** [comment]
@veronicagg @vishrutshah @johanste There is a Python package that uses this file, and the SDK is used in the CLI. So @johanste , up to you to tell us if it will break your CLI :)

Otherwise looks like a bug anyway, so I'm ok too

**Comment by lmazuel** [comment]
@johanste a rapid grep shows me you use this package in azure-cli-acs and azure-cli-role, but you don't use this specific method.

**Comment by johanste** [comment]
The CLI should be ok.

**Comment by vishrutshah** [comment]
Let's wait for final confirmation from @shuagarw who is a dev from the team. @shuagarw Could you please confirm? Thanks!

**Comment by shuagarw** [comment]
@rbacask for FYI
The sdk generated by these specs is not used in powershell, but used by node js cmdlets. I hope it is working there as of now and changing it will break the contract there. Will try to dig more, how is it used there. May be it is expecting/appending a '/' in the end.

**Comment by vishrutshah** [comment]
@shuagarw Any updates on this one?

**Comment by shuagarw** [comment]
@vishrutshah I think this is a good change. I checked in azure-xplat-cli and looks like this api is not called from the cmdlets, so should be good.

**Pull request merged**
