### PR TITLE
On boarding Solutions to latest stable API version

### PR DESCRIPTION
**Pull request by ariklin**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ariklin** [comment]
This PR is about copying existing APIs from preview to stable with no changes in the logic.

Please don't merge this PR when it's finished to be reviewed, we will merge it once we'll be ready at our side.

**Comment by weidongxu-microsoft** [comment]
@ariklin

Maybe you would like to put the reference of the approved PR on preview to the description, so ARM would just check there and quickly response.

**Comment by ravbhatnagar** [comment]
Signing off from ARM side.

**Review by chlahav — APPROVED** [review]

**Comment by ariklin** [comment]
@weidxu, please advise, any idea why SDK Python failed check keeps failing? will appreciate if you can point in the right direction.

**Comment by weidongxu-microsoft** [comment]
@ariklin 

Currently it is a success?

**Comment by ariklin** [comment]
> @ariklin
> 
> Currently it is a success?

@weidongxu-microsoft - Please advise, test are failing again for some reason, will appreciate your guidance here. We would like to complete this PR if possible.

**Comment by weidongxu-microsoft** [comment]
@ariklin

Automation on CI is updated constantly, so an updated CI might find problem previous not found. I've run it again, could you take a look on the problem reported?

**Comment by ariklin** [comment]
@weidongxu-microsoft - please advise, what am I missing here?

**Comment by ariklin** [comment]
@weidongxu-microsoft - Hope we are good now, please advise.

**Comment by weidongxu-microsoft** [comment]
@ariklin Seems to be good. I will retry it if the last one `automation - sdk (SDK Python)` still hangs.

Let me know when you need to merge.

**Comment by ariklin** [comment]
@weidongxu-microsoft, please merge, thank you for your help.

**Pull request merged**
