### PR TITLE
typo: botservice

### PR DESCRIPTION
**Pull request by nschonni**
Double word "service"

### CODE REVIEW

**Comment by michaeljqzq** [comment]
Please fix CI tasks

**Comment by nschonni** [comment]
@michaeljqzq I'm not an MS employee, so I'm not sure what the correct fixes are for the `READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST` errors. I've PR'd model validation fixes before, but this case it could either be an issue with the example or with the spec, and i'm not someone that could make that call

**Comment by michaeljqzq** [comment]
The `Bots_Create` operation is a put operation, and in the example it includes the property `id` which is defined as readOnly in the spec. This is not allowed

**Comment by nschonni** [comment]
@michaeljqzq I'm just making a documentation change here. I can't fix service issues in this PR as I'm not a Microsoft employee

**Comment by michaeljqzq** [comment]
@sergey-shandar Could you help merge this PR? Although the model validation failed, the changes here have nothing to do with that part

**Comment by michaeljqzq** [comment]
@carlosscastro Hi, I saw you were the first contributor for the swagger file. Are you still working with that? Could you see and try fixing the model validation error in the examples? Thanks

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
