### PR TITLE
[Hub Generated] Review request for Microsoft.NotificationHubs to add version stable/2023-09-01

### PR DESCRIPTION
**Pull request by kmiecikt**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/kmiecikt-notificationhubs-Microsoft.NotificationHubs-2023-09-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #24072

**Comment by kmiecikt** [comment]
@rkmanda: the stable version in this PR is exactly the same as already-approved API version `2023-01-01-preview` (https://github.com/Azure/azure-rest-api-specs/pull/24072).

The linter / Avocado errors are either reported for previous versions (not updated in the PR), or also appeared in the previous PR and cannot be fixed without adding breaking changes.

We will update the RP manifest next week. Is there any other action needed?

**Comment by ms-henglu** [comment]
Please fix the `Swagger Avocado` and `Swagger LintDiff`.

**Comment by kmiecikt** [comment]
> Please fix the `Swagger Avocado` and `Swagger LintDiff`.

The Swagger Avocado errors & warnings are incorrect - they are reported for older API version and files that did not change in this Pull Request.

The remaining LintDiff errors cannot be fixed without introducing breaking changes. The same set of errors was already approved in the [PR for `2023-01-01-preview`](https://github.com/Azure/azure-rest-api-specs/pull/24072/checks?check_run_id=14547496785).

**Comment by ms-henglu** [comment]
LintDiff previously reviewed and approved in https://github.com/Azure/azure-rest-api-specs/pull/24072

**Comment by kazrael2119** [comment]
this js sdk breaking is caused by base apiversion not this one.

**Comment by kmiecikt** [comment]
Hi @rkmanda. Is there any other approval we need before completing the PR?

**Comment by ms-henglu** [comment]
Hi @kmiecikt , please get the following errors fixed or approved.

❌ Swagger Avocado
❌ Approved-SdkBreakingChange-Python

**Comment by kmiecikt** [comment]
> Hi @kmiecikt , please get the following errors fixed or approved.
> 
> ❌ Swagger Avocado ❌ Approved-SdkBreakingChange-Python

Hi @ms-henglu.

The Swagger Avocado errors are false positives - they are reported for files from previous version, not changes in this PR (please take a look at comments above).

How can we approve the Python breaking changes?  It was approved for version '2023-01-01-preview`, which is exactly the same as the stable one we try to add now.

**Comment by ms-henglu** [comment]
Here's the [list](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750) of sdk breakign changes and other checks approvers.

**Comment by msyyc** [comment]
Approved for python sdk breaking:
image

**Comment by kmiecikt** [comment]
@ms-henglu

All reported errors / warnings were approved. Is there anything else we have to do before completing this PR?

**Comment by ms-henglu** [comment]
> @ms-henglu
> 
> All reported errors / warnings were approved. Is there anything else we have to do before completing this PR?

Please get the Avocado error approved label, you could find the contact from the [list](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750).

**Review by mentat9 — APPROVED** [review]

**Pull request merged**
