### PR TITLE
Add new source controls properties

### PR DESCRIPTION
**Pull request by sanchitmehta**
This PR Adds new properties for Source Controls APIs

### CODE REVIEW

**Comment by xwang971** [comment]
Can we update examples as well

**Comment by kazrael2119** [comment]
@msyyc @tadelesh @qiaozha ,please help review sdk breaking changes, thanks

**Review by kazrael2119 — DISMISSED** [review]

**Review by xwang971 — APPROVED** [review]

**Comment by xwang971** [comment]
@kazrael2119 Hi, can we get approval please? The examples have been added

**Comment by kazrael2119** [comment]
@sanchitmehta ,please fix ModelValidation error

**Comment by sanchitmehta** [comment]
@kazrael2119 realized the example was wrong and I fixed it

**Review by kazrael2119 — APPROVED** [review]
skip sdk breaking change review beacuse they are not from this PR

**Pull request merged**
