### PR TITLE
replacing modified swagger files in V20230201 after adding new controllers for Sql Data Classification APIs

### PR DESCRIPTION
**Pull request by pmahanandire**
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [x] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Review by jeremyfrosti — APPROVED** [review]
LGTM

**Comment by kazrael2119** [comment]
this js sdk breaking is not caused by this pr

**Comment by tombuildsstuff** [comment]
@pmahanandire thanks for this PR - I've taken a look into importing this one and it appears there's still a couple of references to the older constant name which are causing us issues:

* https://github.com/pmahanandire/azure-rest-api-specs/blob/0a58e97bb58d5e878b628511a0b29111bd184e95/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/SensitivityLabels.json#L279-L292
* https://github.com/pmahanandire/azure-rest-api-specs/blob/0a58e97bb58d5e878b628511a0b29111bd184e95/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/ManagedDatabaseSensitivityLabels.json#L282-L296

In addition it appears there's an issue with the new `IPv6 FirewallRule` model, where the name includes a space - whilst we can look into working around that from our side, I'm not sure if that's valid Swagger/OpenAPI, so I'm not sure if that also needs addressing there too? https://github.com/pmahanandire/azure-rest-api-specs/blob/0a58e97bb58d5e878b628511a0b29111bd184e95/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/IPv6FirewallRules.json#L215

---

On a related note, we're noticing the same issues with these particular constants also exist for the Synapse service too, I understand that's a separate Resource Provider, but I'm unclear if SQL and Synapse are maintained by different teams / who we'd need to reach out to in order to get that one fixed, does the SQL Team own that Resource Provider too?

---

Tagging a couple of upstream issues on our side, so we can cross-reference this:

* SQL: https://github.com/hashicorp/pandora/issues/2842
* Synapse: https://github.com/hashicorp/pandora/issues/1508

 cc @WodansSon for info

**Comment by pmahanandire** [comment]
@tombuildsstuff, could you please elaborate on the issues caused by the older constant name, because after this change, the enum names and the values they take are consistent.

**Comment by WodansSon** [comment]
@pmahanandire, I have linked @tombuildsstuff PR(#26303) to fix the remaining issue for Pandora SDK import.

**Pull request merged**
