### PR TITLE
Fix some of the error in ARM swagger spec

### PR DESCRIPTION
**Pull request by chidmdxx**
Specifically fixing the following comments

Mark properties as 'readonly' | ManagementLockObject in Microsoft.Authorization spec   PolicyDefinition in Microsoft.Authorization   spec   DeploymentExtended in Microsoft.Resources spec   ResourceGroup in Microsoft.Resources spec   TagValue in Microsoft.Resources spec   TagDetails in Microsoft.Resources spec   ResourceLink in Microsoft.Resources spec
-- | --

Add x-ms-azure-resource extension to response models | 'Deployments_CreateOrUpdate' Model: 'DeploymentExtended''ResourceGroups_CreateOrUpdate' Model: 'ResourceGroup''Tags_CreateOrUpdateValue' Model: 'TagValue''ResourceLinks_CreateOrUpdate' Model: 'ResourceLink'
-- | --

Update description | Microsoft.Resources   2017-05-10/resources.json:2857:62017-05-10/resources.json:2818:10
-- | --

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by olydis** [comment]
@ravbhatnagar some violations resolved, but technically a breaking change

**Review by vivsriaus — APPROVED** [review]
Thanks Rachid!

**Comment by ravbhatnagar** [comment]
@olydis - Is the breaking change comment for readonly true change or for the x-ms-azure-resource extension addition? I think it may be due to the readyonly one, but wanted to confirm. If its that, it should be fine since these properties were never settable and the service would fail the request.

**Comment by olydis** [comment]
@ravbhatnagar Indeed, they were related to the `readOnly` change, but I agree about that being fine (assuming that it's exactly the properties that caused failure 😃 )

**Comment by ravbhatnagar** [comment]
@olydis -Thanks for confirming.
Signing off from ARM side.

**Review by olydis — APPROVED** [review]

**Pull request merged**
