### PR TITLE
Compute 2021 03 API release

### PR DESCRIPTION
**Pull request by Sandido**
Update: moved to this PR for the required commit history format: https://github.com/Azure/azure-rest-api-specs/pull/14223

This PR is to release the new version of Compute, 2021-03-01.

This release consists of these PR, all of which have been reviewed before:

1. Deep Deletion: https://github.com/Azure/azure-rest-api-specs/pull/13657
2. Scheduled Events: https://github.com/Azure/azure-rest-api-specs/pull/13351
3. PatchSetting Assessment mode: https://github.com/Azure/azure-rest-api-specs/pull/13468
4. Network Interface Config :https://github.com/Azure/azure-rest-api-specs/pull/13449  (Required and received ARM signoff)
5. Patchsetting Description : https://github.com/Azure/azure-rest-api-specs/pull/13509
6. RestorePoint: https://github.com/Azure/azure-rest-api-specs/pull/13219 (Required and received ARM signoff)
7. UserData: https://github.com/Azure/azure-rest-api-specs/pull/13220
8. https://github.com/Azure/azure-rest-api-specs/pull/14191 
9. https://github.com/Azure/azure-rest-api-specs/pull/14197 

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Sandido** [comment]
The .Net SDK PR check error was introduced by this PR: https://github.com/Azure/azure-rest-api-specs/pull/14095/files
It is not related to my changes in this PR.

**Comment by Sandido** [comment]
The breaking change compared to the 2016 version is not a valid failure. 
The breaking change compared to the 2012 version (the enum constraint weakening) was approved in this PR: #13220

**Comment by Sandido** [comment]
The APIDocPreview error is expected. 
The error can be resolved after this swagger version releases and I update https://github.com/Azure/azure-docs-rest-apis/blob/a3471166348cdcb19ecff2bba982523939796784/mapping.json#L1156 

This also occurred in the 2012-12-01 release and the Doc team advised this post-release fix.

**Comment by Sandido** [comment]
The ARM team also reviewed the 2 PRs in this release that need ARM signoff.

**Review by yungezz — APPROVED** [review]
each PR Is reviewed seperated in compute feature branch

**Review by yungezz — APPROVED** [review]

**Comment by chiragg4u** [comment]
Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.

**Comment by Sandido** [comment]
@chiragg4u , apologies for not having that setup.
The Commits that were used to setup the branch for the new version are:

https://github.com/Azure/azure-rest-api-specs/pull/14121/commits/d5b214613e6e983c750234c1291acf385d2f0363
https://github.com/Azure/azure-rest-api-specs/pull/14121/commits/e45d32a312256daa40281f16c2a460f99b3f7073
https://github.com/Azure/azure-rest-api-specs/pull/14121/commits/840f44ef1014b803627ebf644c819dfd1144939a
https://github.com/Azure/azure-rest-api-specs/pull/14121/commits/134aa5823a723c8add0a973b7740a943ef61ef91
https://github.com/Azure/azure-rest-api-specs/pull/14121/commits/29a5ff6e6b017c80430e568099ebf9cd90b8df98

The changes merged with new features for this release are listed in the initial PR comment as separate PRs.

**Comment by chiragg4u** [comment]
If you want to get faster review please follow the recommended pattern. I won't be able to review this PR in current form, sorry!

---
In reply to: [829242309](https://github.com/Azure/azure-rest-api-specs/pull/14121#issuecomment-829242309) [](http://example.com/codeflow?ancestors=829242309,829242309)

**Review by chiragg4u — CHANGES_REQUESTED** [review]
:clock1:

**Comment by JackTn** [comment]
Hi, @Sandido. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @Sandido. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @Sandido. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
