### PR TITLE
fix: storagesync model validation errors

### PR DESCRIPTION
**Pull request by nschonni**
- Remove empty body
- Remove empty "properties"

### CODE REVIEW

**Comment by lirenhe** [comment]
@nschonni , I saw a couple of validation error for this PR, could you take a look?

**Comment by nschonni** [comment]
@lirenhe I removed the spec changes so the model validation should be happy. When the spec doesn't get touched, the CI doesn't run the model validation, but the errors are still there

**Comment by NullMDR** [comment]
@openapibot sdkautomation rebuild

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
@ankushbindlish2, please take a look at this PR.

**Pull request merged**
