### PR TITLE
Dev kubernetesconfiguration microsoft.kubernetes configuration 2019 11 01 preview

### PR DESCRIPTION
**Pull request by NarayanThiru**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by arrownj — APPROVED** [review]
LGTM

**Comment by NarayanThiru** [comment]
Since the changes have been approved, can this be merged, so that the SDKs can be generated?

**Comment by NarayanThiru** [comment]
@arrownj can you merge these changes or do you know who can do the merge?  I asked in the ARM Teams channel; and was told to reach out to the SDK reviewer.

**Comment by ArcturusZhang** [comment]
Hi @NarayanThiru this PR looks really familiar to me... it is basically the same thing as [this PR](https://github.com/Azure/azure-rest-api-specs/pull/8951) and since some additional things have been changed in this RP, you may need to revert the changes on `readme.md` and `readme.go.md` before this can be merged

**Comment by NarayanThiru** [comment]
Hi @ArcturusZhang, you are right.  It is the same one as the other PR.  And the only change I made compared to that PR was to remove x-ms-parameter-location property from the api-version property ([commit](https://github.com/Azure/azure-rest-api-specs/pull/9170/commits/f6a96016765310305ca1a418ba2dc290fef567a9)).  I used OpenAPI Hub, as suggested, since I needed the SDKs (specifically Python SDK) to be re-generated.  And it automatically added it to this PR.  I would very much want to use the other PR as the base; but note sure how to.  Can you pl. advise?

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang, you are right. It is the same one as the other PR. And the only change I made compared to that PR was to remove x-ms-parameter-location property from the api-version property ([commit](https://github.com/Azure/azure-rest-api-specs/pull/9170/commits/f6a96016765310305ca1a418ba2dc290fef567a9)). I used OpenAPI Hub, as suggested, since I needed the SDKs (specifically Python SDK) to be re-generated. And it automatically added it to this PR. I would very much want to use the other PR as the base; but note sure how to. Can you pl. advise?

Well, I believe this should be somehow a bug of open api hub, it should use a new branch rather than reuse the old branch without fetch the new changes on master.

The changes in `readme.go.md` is made by me after the previous PR was merged, and the changes in `readme.md` is made by a bot after every PR got merged. Therefore I believe we need to keep those changes.

Could we make a new commit to revert them?

**Comment by NarayanThiru** [comment]
Thanks for catching these @ArcturusZhang .  I fixed these two readme files by inserting the lines that were removed; and pushed the changes.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
