### PR TITLE
[Hub Generated] Review request for Microsoft.Security to add version preview/2020-03-01-preview

### PR DESCRIPTION
**Pull request by kfbehar**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/kfbehar/azure-rest-api-specs/dev-security-Microsoft.Security-2020-03-01-preview-2...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
@kfbehar - since a new type is being added, it may be quicker to do the review over a meeting. PLease set something up with armapireview.

**Review by majastrz — APPROVED** [review]
I'm not sure why the meeting label was added to this PR as the changes don't require it. In any case, I signed off from ARM side.

**Comment by fengzhou-msft** [comment]
@kfbehar what's the status of this PR? Do you still need to merge it?

**Comment by kfbehar** [comment]
> @kfbehar what's the status of this PR? Do you still need to merge it?

Yes, please :)

**Comment by fengzhou-msft** [comment]
@kfbehar Can you resolve the conflicts and fix the errors for the required CI? You can follow https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md

**Comment by fengzhou-msft** [comment]
@kfbehar any update?

**Comment by fengzhou-msft** [comment]
Close idle PR. Please feel free to reopen it and continue the work if you still need it.

**Pull request closed without merging**
