### PR TITLE
July 2023 API Version for Azure Data Manager for Agriculture

### PR DESCRIPTION
**Pull request by archanac866**
# Data Plane API - Pull Request

## Added Fields

- geometry(GeoJson) : added in Fields, SeasonalFields, Zones, Prescription, PlantTissueAnalyses, ApplicationData, HarvestData, PlantingData, TillageData
- associatedResource {type(string), id(string)}: added in ApplicationData, HarvestData, PlantingData, TillageData, SensorMapping, SensorEvents, Scenes, BiomassJob, SoilMoistureJob, SensorPlacementJob

## Removed Fields

- boundaryId : field removed in SeasonalFields, Zones, Prescription, SensorMapping, SensorEvents, Scenes, BiomassJob, SoilMoistureJob, SensorPlacementJob
- operationBoundaryId, associatedBoundaryId : field removed in ApplicationData, HarvestData, PlantingData, TillageData
- Enum is changed so that it cannot take Boundary as resourcetype in Insights, Attachments, InsightAttachments
- Removed attachmentLinks from response in ApplicationData, HarvestData, PlantingData, TillageData, PlantTissueAnalyses

## Changes in Controller

- Removed Boundary controller
- Removed Weather controller
- Removed List , ListByParty APIs in Fields, SeasonalFields, Zones, Prescription, PlantTissueAnalyses, ApplicationData, HarvestData, PlantingData, TillageData
- Added Search API in Fields, SeasonalFields, Zones, Prescription, PlantTissueAnalyses, ApplicationData, HarvestData, PlantingData, TillageData
- Added Overlap API in Party, to find overlapping area between two resources.

Is this review for (select one):

- [ ] a private preview
- [X] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2023-06-01-preview/agfood.json
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
The swagger is too big to comment inline.

For `OverlapResource`, would you check if `partyId`, `resourceType`, `resourceId` is `required`?

**Comment by archanac866** [comment]
@weidongxu-microsoft We have added the resourceType and resourceId as part of response so that the customer will know the area belongs to which resource and also for the future when the array size can be more than 2, then we will resturn the list of resource IDs with their corresponding areas to make it more readable.

**Comment by weidongxu-microsoft** [comment]
@archanac866 

What I mean, is please double check the properties in `OverlapResource`. If any are required for user to fill in request body, make it "required".

**Comment by weidongxu-microsoft** [comment]
Please wait for confirmation from author that backend ready, before merge.

**Review by mikekistler — APPROVED** [review]
For preview this is probably fine, but there are many minor issues in the API that should be addressed before the first GA.

- maxpagesize parameter must be named "maxpagesize" (all lowercase). There are many occurrences of this.

- maxpagesize parameter should not have a default value. Also many occurrences.

- OperationId "Parties_PostOverlap" should not contain HTTP verb (Post)

- Schema names are too generic and contain "throwaway" words like "response" and metadata.

-  Properties in response-only schemas should not be marked as readOnly true. Many occurrences of this.

You should consider doing these as soon as possible, to minimize disruption later.

**Comment by mikekistler** [comment]
`Parties_GeoOverlap` looks fine. Could have also be `Parties_ComputeOverlap`.

**Pull request merged**
