### PR TITLE
Add data connector kinds AzureAdvancedThreatProtection and MicrosoftDefenderAdvancedThreatProtection.

### PR DESCRIPTION
**Pull request by roherzbe**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by roherzbe** [comment]
Nir Gafni, please approve.

**Comment by nschonni** [comment]
You can also add the acronyms to https://github.com/Azure/azure-rest-api-specs/blob/master/custom-words.txt if you want to use them

**Comment by roherzbe** [comment]
@nschonni Thanks for the comment :)
Added to custom-words and updated SecurityInsights.json accordingly. 
Waiting for your approve.

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by roherzbe** [comment]
@michaeljqzq  @nschonni 
ARM approved :) back to you

**Review by michaeljqzq — APPROVED** [review]

**Pull request merged**
