### PR TITLE
Improve Network's examples

### PR DESCRIPTION
**Pull request by anton-evseev**
* Responses for LoadBalancer with Basic SKU don't have `outboundRules` property so removed it from examples
* Added missing read-only properties like `type` and `etag` to LoadBalancer's examples & specs
* Removed read-only fields from VPN Gateway's example for PUT

---

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
Please ignore error in `NetworkValidation`, it's not related to this PR, it failed due to NuGet not being able to resolve dependencies. I've already reported this error to SDK & Azure PowerShell teams.

```
D:\a\1\s\Out\azure-powershell\src\Network\Network\Network.csproj : error NU1605: Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.20 to 2.3.19. Reference the package directly from the project to select a different version.  [D:\a\1\s\Out\azure-powershell\src\Network\Network.sln]
```

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@number213 what about your JS SDK issue?

**Comment by number213** [comment]
@tjprescott doesn't look like error is related to changes in PR.

```
INFO:swaggertosdk.autorest_tools:  Error: Unable to resolve package 'foo@@microsoft.azure/autorest.typescript'. 
ERROR:swaggertosdk.autorest_tools:Command '['/usr/local/bin/autorest', '/git-restapi/specification/network/resource-manager/readme.md', '--license-header=MICROSOFT_MIT_NO_VERSION', '--typescript', '--typescript-sdks-folder=/tmp/tmph_u9ld91/azure-sdk-for-js', '--use=@microsoft.azure/autorest.typescript']' returned non-zero exit status 1.
```

I think this is the step that was removed by @sergey-shandar (https://github.com/Azure/azure-rest-api-specs/pull/6391)

**Comment by tjprescott** [comment]
@number213 it is still failing. @sergey-shandar it is okay to merge this with the JS SDK failing?

**Comment by kpajdzik** [comment]
> @number213 it is still failing. @sergey-shandar it is okay to merge this with the JS SDK failing?

Yes, go ahead.

**Comment by number213** [comment]
@kpajdzik yes, failures are because spellchecker's config with exceptions in this branch is out of sync with master, this PR doesn't introduce any new errors

**Pull request merged**
