### PR TITLE
Rename networkAcls to NetworkRuleSet.

### PR DESCRIPTION
**Pull request by JasonYang-MSFT**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by fearthecowboy** [comment]
@JasonYang-MSFT  Sorry for the delay -- I've been trying to fix some CI issues.

This is just some simple renames? I'm assuming that there isn't an SDK release with the current version yet that we're going to break?

**Comment by JasonYang-MSFT** [comment]
This will break current version of .net SDK. But only break the feature that is still in preview.

**Comment by tjprescott** [comment]
The Python SDK also contains the current version with "network_acls"  cc/ @lmazuel

**Comment by lmazuel** [comment]
So technically it's broken in Python as well, and since the ApiVersion is not released as preview, the Python package was released as stable.
That being said, in this particular case:
- This was released 15 days ago 
- I doubt people are using it at the SDK, there is no samples, but maybe CLI does ( @tjprescott ?)
- If users use the dict syntax as input, this is not breaking

So we might just release that a "bug fix" like "sorry we didn't mean to use that name". But it's on the border, once a Swagger is in master, the point is that **it is** stable. Otherwise the Swagger has nothing to do on master.

**Comment by tjprescott** [comment]
The CLI does, but it's still on a branch in my fork. I can just fix up the references before I issue a PR.

**Comment by lmazuel** [comment]
@JasonYang-MSFT The point here is you can't say just "This will break current version of Storage RP .Net SDK. But only break the feature that is still in preview."

First, sorry but it's really a C#-focused sentence, note that this Swagger is used in Java, Ruby, NodeJS, Python and GO. You break **all** of them.

Second, the Swagger is commited in *master* on the *public* repo for *2 months*, for an ApiVersion that does not contain *preview*. We have no way to determine the "preview-ness" of this Swagger. Please in this situation do an email or something to SDK teams in general (not only C#), to explain that we should not integrate the change, or make it clear that it's preview.

FYI @johanste

**Comment by johanste** [comment]
@salameer, @kirthik, one more example where having the ability to do a "soft" rename (deprecate previous name) could be very helpful.

**Comment by lmazuel** [comment]
@johanste That would be awesome! @mayurid, this is what I meant yesterday talking about "deprecate in Autorest".

**Comment by kirthik** [comment]
Agreed that having a deprecation mechanism is important. @fearthecowboy is working on a proposal which he will be sharing soon.

**Comment by JasonYang-MSFT** [comment]
@lmazuel Thanks for the advice. I have just sent the email to notify the situation.

**Comment by fearthecowboy** [comment]
This PR renames a model class, which is something that I didn't represent.

Lemme generate out the code before/after and see how that plays out.

**Comment by fearthecowboy** [comment]
Well, this will definitely be a breaking change in existing SDKs -- even if we had the ability to rename properties/methods implemented in AutoRest at this point, this PR changes a **model type**, and there ain't no power in the 'verse that can export an alias of a class.

**Comment by lmazuel** [comment]
@fearthecowboy You know an alias to a class is possible in Python right? ;)

**Comment by fearthecowboy** [comment]
@lmazuel  "First, sorry but it's really a python-focused sentence"

<ducks>

😆 

Yeah, yeah...

**Comment by fearthecowboy** [comment]
If I merge this, it's gonna be a binary breaking change everywhere. Which means a major version bump pretty much across the board. Is that what we want? Can the change wait for the next API Version bump?

@johanste @lmazuel @kirthik  -- Any dissension?

**Comment by lmazuel** [comment]
@fearthecowboy I know... Ok to merge anyway from me.

**Comment by kirthik** [comment]
@markcowl,@twitchax - Are you ok with this change from PowerShell perspective?

**Comment by salameer** [comment]
OKaaay lovely People,

Given all the risks and large impact that we have from the opration name, the safest thing here would be to rename on the next API version of this swagger to avoid breaking changes on all generated SDKs

**Comment by JasonYang-MSFT** [comment]
As far as I checked out, correct me if I have missed anything, python, .net and NodeJS have this feature, which will cause breaking. 
For Java, Go and Ruby, this feature is not included for now, in which case no breaking to them. But if we rename on the next API version, they will also be impacted in that time. 

For PowerShell, "NetworkRuleSet" is already used in its parameters.
For CLI, as @tjprescott mentioned, changes are still in his fork repo currently.

So in my opinion, rename it now may have smaller breaking impact  other than rename on the next API version. @salameer What do you think about this idea?

**Comment by JasonYang-MSFT** [comment]
Any ideas? @fearthecowboy @salameer @markcowl @twitchax @DanBehrendt

**Comment by kirthik** [comment]
@JasonYang-MSFT - I am not sure how this would affect PowerShell but could you get an ack from Powershell folks - @markcowl (Mark Cowlishaw) and @twitchax (Aaron Roney). Once they ack on this change, we can merge.

**Comment by kirthik** [comment]
We got ack that this change does not break PowerShell. Given Python team signed off, @fearthecowboy I think we are ok to merge.

**Comment by JasonYang-MSFT** [comment]
Thanks all for your cooperation.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
