### PR TITLE
[Compute] Create a folder for compute 2018-04-01 API version

### PR DESCRIPTION
**Pull request by hyonholee**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by jianghaolu — APPROVED** [review]
New API with minor changes. Approved from SDK side.

**Comment by lmazuel** [comment]
@hyonholee Do you authorize me to update this PR with the correct updated Readme?
If not, could you be do this.
Thank you.

**Comment by hyonholee** [comment]
@lmazuel  No, please do not update readme.md file.  This is a preliminary PR for upcoming API.  We still want to generate a client library from 2017-12-01 version, but Networking team asked us to create 2018-04-01 folder in order to send their PR for modifying compute.json file.  When CRP enables 2018-04-01 API, the networking team will test the 2018-04-01 API with their update and then update the readme.md file.

**Comment by lmazuel** [comment]
Thanks for the headups @hyonholee :)
All SDK owners, FYI @shahabhijeet @marstr @sarangan12 @amarzavery

**Comment by lmazuel** [comment]
@hyonholee After thinking about it, we usually don't check-in Swagger that are not ready for prod in "master". This creates documentation issue, and some customers are using directly the Swaggers. I think we should use a feature branch `compute-2018-04` for that. This allows Network team to work on that as well (they used to feature branch). Thoughts?
@salameer for guidance.
Thanks!

**Comment by hyonholee** [comment]
@lmazuel Thanks for feedback.
@salameer Could you create compute-2018-04 branch and redirect this PR to there?

**Comment by hyonholee** [comment]
Thanks, could you merge this PR if there is no more issue?  Our team will send more PR to compute-2018-04 branch.  Thanks.

**Comment by lmazuel** [comment]
@jianghaolu is fine with the content, and I double-checked with @salameer, so merging.
@ravbhatnagar FYI

**Pull request merged**
