### PR TITLE
New swagger version - Add new rules API to privatestore

### PR DESCRIPTION
**Pull request by tomercigler**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>         "x-ms-pageable": {

This looks like a mistake, since there is no response payload. x-ms-pageable doesn't work on POST actions anyway, AFAIK.

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:905 in a129502. [](commit_id = a12950206627190cad541e23c95bff7266f6ca26, deletion_comment = False)

**Comment by mentat9** [comment]
>       "post": {

Removing the GET method is a cross-version breaking change. You'll need to get this reviewed by the breaking change board. I'll add the BreakingChangReviewRequired label - instructions will be in PR comments.

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:921 in a129502. [](commit_id = a12950206627190cad541e23c95bff7266f6ca26, deletion_comment = False)

**Comment by tomercigler** [comment]
Hi @mentat9 , thank you very much for your great review.
About the Breaking changes - this is a new API (you can see that i added that in that PR) so it can be breaking change.
About the second comment - fix, thanks again!

**Comment by tomercigler** [comment]
Hi @lirenhe ,
I see that AVOCDO test failed - as far i understand - it's related to readme file.
I can see readme file in marketplace directory but it's looks like auto generated file.
How can I generate that file? there is any documentation for avocado test and readme file?
Thanks!

**Comment by lirenhe** [comment]
@tomercigler,  could you fix the tool check errors in the PR? thanks

**Comment by rkmanda** [comment]
>       "post": {

Its still unclear why the dropping of GET API is not flagging a breaking change. Working with the author offline

---
In reply to: [1241287930](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1241287930) [](http://example.com/codeflow?ancestors=1241287930,1241287930)

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:921 in a129502. [](commit_id = a12950206627190cad541e23c95bff7266f6ca26, deletion_comment = False)

**Comment by tomercigler** [comment]
> > ```
> >   "post": {
> > ```
> 
> Its still unclear why the dropping of GET API is not flagging a breaking change. Working with the author offline
> 
> In reply to: [1241287930](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1241287930)
> 
> Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:921 in [a129502](https://github.com/Azure/azure-rest-api-specs/commit/a12950206627190cad541e23c95bff7266f6ca26). [](commit_id = [a129502](https://github.com/Azure/azure-rest-api-specs/commit/a12950206627190cad541e23c95bff7266f6ca26), deletion_comment = False)

Hi Roopesh,

Thank you for you review.

As I wrote before - You can see that I changed from get to post in the same PR -

That mean - I added this API "queryRules" in commit number 1 (in the same PR).
Then, I found that API should be post instead get so I pushed another commit (in the same unmerged PR) to fix that.
That is the reason it's no ta braking change.

**Comment by rkmanda** [comment]
>       "post": {

The first iteration already had some changes related to the API version which is causing the confusion

---
In reply to: [1249807738](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1249807738) [](http://example.com/codeflow?ancestors=1249807738,1241287930)

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:921 in a129502. [](commit_id = a12950206627190cad541e23c95bff7266f6ca26, deletion_comment = False)

**Comment by rkmanda** [comment]
>         },

x-ms-pageable is only applicable with a GET collection call. Please remove. If you want to make this a pageable response make this verb a GET

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:948 in f8db30b. [](commit_id = f8db30b435e339236bdf4923e5e609e6a8f14fab, deletion_comment = False)

**Comment by tomercigler** [comment]
Hi, after talking with @rkmanda ,
I decide to change my branch and PR to :
1) first commit is a clear clone from the current stable version (2022-03-01)
2) second commit is all my changes for the current version.

**Comment by mentat9** [comment]
>       "post": {

It looks like this should be implemented by as part of the existing PUT method on the collection instance (or a new PATCH). You've added the "appliedRules" property to the CRUD payloads for privateStores/collections, so you should support updating that property as part of the regular CRUD methods. If you do that, you don't need to add this POST.

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:873 in e8d4dee. [](commit_id = e8d4dee30cee197a1c60bfade124c775849c336d, deletion_comment = False)

**Comment by mentat9** [comment]
>       "post": {

Can the client just GET the collection resource and access the appliedRules property, instead of adding this POST that [apparently] does the same thing?

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:918 in e8d4dee. [](commit_id = e8d4dee30cee197a1c60bfade124c775849c336d, deletion_comment = False)

**Comment by mentat9** [comment]
>         },

+1

x-ms-pageable doesn't work for POST. You should remove it.

---
In reply to: [1254190054](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1254190054) [](http://example.com/codeflow?ancestors=1254190054,1254190054)

---
Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:948 in e8d4dee. [](commit_id = e8d4dee30cee197a1c60bfade124c775849c336d, deletion_comment = False)

**Comment by tomercigler** [comment]
> > ```
> >     },
> > ```
> 
> +1
> 
> x-ms-pageable doesn't work for POST. You should remove it.
> 
> In reply to: [1254190054](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1254190054)
> 
> Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:948 in [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d). [](commit_id = [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d), deletion_comment = False)

Fixed, thanks

**Comment by tomercigler** [comment]
> > ```
> >   "post": {
> > ```
> 
> It looks like this should be implemented by as part of the existing PUT method on the collection instance (or a new PATCH). You've added the "appliedRules" property to the CRUD payloads for privateStores/collections, so you should support updating that property as part of the regular CRUD methods. If you do that, you don't need to add this POST.
> 
> Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:873 in [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d). [](commit_id = [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d), deletion_comment = False)



> > ```
> >   "post": {
> > ```
> 
> Can the client just GET the collection resource and access the appliedRules property, instead of adding this POST that [apparently] does the same thing?
> 
> Refers to: specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2022-09-01/Marketplace.json:918 in [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d). [](commit_id = [e8d4dee](https://github.com/Azure/azure-rest-api-specs/commit/e8d4dee30cee197a1c60bfade124c775849c336d), deletion_comment = False)

About these 2 other comments.
First, thank you for your review!
We checked your comments and we decide to leave it as it is because:
1) we are using that same way in other resources and API (all items approved, offers ...).
2) we want to be more flexible with the user and give an option to get rules only in case that we don't need collection with all the fields.
3) Our backend already after architecture, writing, testing, review and basically the swagger this is the last point we have left to finish this task.

I see that there is new test failing - braking changes - something with enum changed, i checked that with few tools and im 100% sure that i didn't change that. Can you please help me understand what is the root cause?
thanks!

**Comment by mentat9** [comment]
> About these 2 other comments.
First, thank you for your review!
We checked your comments and we decide to leave it as it is because:

> we are using that same way in other resources and API (all items approved, offers ...).
we want to be more flexible with the user and give an option to get rules only in case that we don't need collection with all the fields.
Our backend already after architecture, writing, testing, review and basically the swagger this is the last point we have left to finish this task.

It's not that it's wrong to add needed POST APIs, it's that it's not a good practice to have overlapping APIs. The feedback here is based on current ARM design and guidelines. There are 1000s of Azure APIs added over the past 8 years. These vary in degree of compliance with current guidelines: the past is not a guide to the future. I understand that making changes is hard: I'm not blocking ARM signoff on this.

Two asks:
1. Please use this feedback and track ARM guidance for future API designs.
2. Please don't make your swagger check-in the final step in your process: it should be done as soon as possible in your API development in order to allow feedback and adjustments.

**Comment by tomercigler** [comment]
Hi @mentat9 
Thank you for your review.
I read and understood the things, I will make sure to pass them on to the rest of the team.
I saw that you didn't approve the PR, are we waiting for something else or is it a mistake?

**Comment by raych1** [comment]
> Hi @mentat9 , thank you very much for your great review. About the Breaking changes - this is a new API (you can see that i added that in that PR) so it can be breaking change. About the second comment - fix, thanks again!
> 
> BTW we added more 1 API change, can you check that please?

@tomercigler , see the details of [`cross version breaking change details`](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1236367361) which needs to get breaking change review approval.

**Comment by raych1** [comment]
> > Hi @mentat9 , thank you very much for your great review. About the Breaking changes - this is a new API (you can see that i added that in that PR) so it can be breaking change. About the second comment - fix, thanks again!
> > BTW we added more 1 API change, can you check that please?
> 
> @tomercigler , see the details of [`cross version breaking change details`](https://github.com/Azure/azure-rest-api-specs/pull/20577#issuecomment-1236367361) which needs to get breaking change review approval.

I sampled checked the failures but seems they're false alarm. @jianyexi , can you confirm?

**Comment by mentat9** [comment]
> Hi @mentat9 Thank you for your review. I read and understood the things, I will make sure to pass them on to the rest of the team. I saw that you didn't approve the PR, are we waiting for something else or is it a mistake?

@tomercigler - Sorry, I think you are right: I intended to sign off but didn't for whatever reason. One more thing to say about POST APIs (vs. GET/PUT/PATCH payloads) is that ARM features like Azure Policy and template deployments don't work with POST. That's the fundamental reason we favor putting as much capability into the CRUD resource model as possible. Customers expect to be able to use these basic ARM features, so when you ship APIs that bypass this functionality, it creates friction and frustration for them.

**Comment by lirenhe** [comment]
The cross version breaking changes seem to be the false alarm.  No action needed

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
