### PR TITLE
[Language][Generate-Question-Answers] maxQACount instead of maxResultCount

### PR DESCRIPTION
**Pull request by sahithikkss**
maxQACount instead of maxResultCount as "result" is parent container object's name

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by sahithikkss** [comment]
@heaths , could you please review and approve this minor change in parameter name?

**Review by JeffreyRichter — APPROVED** [review]

**Comment by sahithikkss** [comment]
@JeffreyRichter thank you. Would you please merge as well?

**Comment by JeffreyRichter** [comment]
I never merge; your assignee merges @tianxchen-ms

**Comment by sahithikkss** [comment]
@tianxchen-ms, please merge

**Comment by sahithikkss** [comment]
@lmazuel could you please merge?

**Pull request closed without merging**
