### PR TITLE
[Quantum] Data Plane 2022-09-12-preview host

### PR DESCRIPTION
**Pull request by chuanqixu**
# Data Plane API - Pull Request

Background:

I tested that the base URL of Azure Quantum data plane API seems not correct.
The Azure region should be added to the base URL.

This can be found in azure-quantum python module [azure.quantum.Workspace._create_client()](https://github.com/microsoft/qdk-python/blob/main/azure-quantum/azure/quantum/workspace.py):

```python
def _create_client(self) -> QuantumClient:
    endpoint = BASE_URL(self.location)
    logger.debug(
        f"Creating client for: subs:{self.subscription_id},"
        + f"rg={self.resource_group}, ws={self.name}, frontdoor={endpoint}"
    )

    client = QuantumClient(
        credential=self.credentials,
        subscription_id=self.subscription_id,
        resource_group_name=self.resource_group,
        workspace_name=self.name,
        endpoint=endpoint,
        user_agent=self.user_agent
    )
    return client
```

Here, the end point is defined as:

```python
BASE_URL = (
    lambda location: BASE_URL_FROM_ENV
    or f"https://{location}.quantum.azure.com/"
)
```

Changes:

I changed "host" to "x-ms-parameterized-host" so that the Azure region at the beginning of the base URL can be formated with parameters, and then add one parameter for the API specifying the Azure region.
Also, I added this parameter to all examples with "eastus", though the examples may use different Azure regions.

Also, I tried "Try it" button on [Azure REST API documentation](https://learn.microsoft.com/en-us/rest/api/azurequantum/dataplane/jobs/list?tabs=HTTP), but it cannot successfully get the response.

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by chuanqixu** [comment]
I am very sorry for my misoperation that requests many other reviewers!
Please ignore this PR. Thank you very much!

**Comment by chuanqixu** [comment]
@microsoft-github-policy-service agree

**Review by xinyi-joffre — APPROVED** [review]

**Comment by xinyi-joffre** [comment]
It would be great to take this PR! @anuchandy, is there a way to bypass the CredScan failure? It's a false positive, since the sas tokens are not real sas tokens. It's just part of the existing samples.

**Pull request merged**
