### PR TITLE
Removing monitoring hana instance API

### PR DESCRIPTION
**Pull request by pabowers**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by persiaAziz-zz — APPROVED** [review]

**Review by Caiyeon — APPROVED** [review]

**Review by PakDLiu — APPROVED** [review]

**Review by AprilZhaoWY — APPROVED** [review]
LGTM.

Question: are there CLI commands depending on the spec? If so, would deleting the spec break the CLI?

**Comment by pabowers** [comment]
@AprilZhaoWY, yes, this call will also need to be removed from the CLI extension. Once the Python SDK is generated here, and the corresponding python PR is merged, then I will update our CLI extension.

**Comment by AprilZhaoWY** [comment]
> @AprilZhaoWY, yes, this call will also need to be removed from the CLI extension. Once the Python SDK is generated here, and the corresponding python PR is merged, then I will update our CLI extension.

I see. I just thought of another scenario: After we delete the monitoring spec and RP code, people who have an older version of our CLI extension will always fail when running the monitoring commands. In that case, are we breaking our SLA on the CLI extension? Or do we state we only support the latest version?@PakDLiu

**Comment by pabowers** [comment]
@AprilZhaoWY true, but the only people that have the monitoring features enabled are on our team anyway

**Review by tniek — APPROVED** [review]

**Review by jovillas — APPROVED** [review]

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
