### PR TITLE
Add api-version 2024-08-01-preview for Azure SignalR and Azure Web PubSub

### PR DESCRIPTION
**Pull request by bjqian**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by bjqian** [comment]
According to https://github.com/Azure/openapi-diff/blob/master/docs/rules/1025.md, the breaking change is a false alarm.
The **required** is removed in new api version.
_This is considered a breaking change in the same api-version but **not breaking in new api-version** ._

**Comment by bjqian** [comment]
## API TEST ERROR REPORT FOR WEBPUBSUB<br>
|Rule|Message|
|---|---|
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: WebPubSubReplicas_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3203
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: WebPubSub_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3987
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: WebPubSub_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3987
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: WebPubSub_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3987
|[OPERATION_NOT_TEST](about:blank)|**message**: **WebPubSubReplicas_List** opeartion is not test.<br>**opeartion**: WebPubSubReplicas_List<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "ProvisioningState" cannot be sent in the request.<br>**opeartion**: WebPubSubPrivateEndpointConnections_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3174
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "groupIds" cannot be sent in the request.<br>**opeartion**: WebPubSubPrivateEndpointConnections_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L3062
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "id" cannot be sent in the request.<br>**opeartion**: WebPubSubPrivateEndpointConnections_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L14
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "name" cannot be sent in the request.<br>**opeartion**: WebPubSubPrivateEndpointConnections_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L20
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "type" cannot be sent in the request.<br>**opeartion**: WebPubSubPrivateEndpointConnections_Update<br>**location**: /specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/webpubsub.json#L25

**Comment by bjqian** [comment]
## API TEST ERROR REPORT FOR SIGNALR<br>
|Rule|Message|
|---|---|
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: SignalRReplicas_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L2862
|[OBJECT_MISSING_REQUIRED_PROPERTY](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#OBJECT_MISSING_REQUIRED_PROPERTY)|**message**: Missing required property: location.<br>**opeartion**: SignalR_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L3410
|[OPERATION_NOT_TEST](about:blank)|**message**: **SignalRReplicas_List** opeartion is not test.<br>**opeartion**: SignalRReplicas_List<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "ProvisioningState" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L2833
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "groupIds" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L2721
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "id" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L14
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "name" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L20
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "systemData" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L502
|[READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST)|**message**: ReadOnly property "type" cannot be sent in the request.<br>**opeartion**: SignalRPrivateEndpointConnections_Update<br>**location**: /specification/signalr/resource-manager/Microsoft.SignalRService/preview/2024-08-01-preview/signalr.json#L25

**Comment by bjqian** [comment]
## API TEST ERROR REPORT<br>
|Rule|Message|
|---|---|

## Coverage Report
|Operation|Tested properties|Total properties|Coverage|
|---|---|---|---|
All|126|126|100.0%|
|SignalRSharedPrivateLinkResources_Delete|0|0|100.0%|
|SignalR_Get|0|0|100.0%|
|SignalR_ListSkus|0|0|100.0%|
|SignalRCustomDomains_List|0|0|100.0%|
|SignalR_ListKeys|0|0|100.0%|
|SignalRCustomCertificates_List|0|0|100.0%|
|SignalRCustomDomains_CreateOrUpdate|2|2|100.0%|
|SignalRReplicaSharedPrivateLinkResources_Get|0|0|100.0%|
|SignalR_CheckNameAvailability|2|2|100.0%|
|SignalR_Update|46|46|100.0%|
|SignalR_Delete|0|0|100.0%|
|SignalRSharedPrivateLinkResources_Get|0|0|100.0%|
|Operations_List|0|0|100.0%|
|SignalRPrivateEndpointConnections_Update|4|4|100.0%|
|SignalR_ListReplicaSkus|0|0|100.0%|
|SignalRCustomCertificates_Get|0|0|100.0%|
|SignalRCustomCertificates_Delete|0|0|100.0%|
|SignalRPrivateEndpointConnections_Delete|0|0|100.0%|
|SignalRReplicaSharedPrivateLinkResources_CreateOrUpdate|4|4|100.0%|
|SignalRPrivateLinkResources_List|0|0|100.0%|
|SignalR_ListBySubscription|0|0|100.0%|
|SignalR_Restart|0|0|100.0%|
|SignalRPrivateEndpointConnections_List|0|0|100.0%|
|SignalRReplicaSharedPrivateLinkResources_List|0|0|100.0%|
|SignalR_ListByResourceGroup|0|0|100.0%|
|SignalRReplicas_List|0|0|100.0%|
|SignalR_RegenerateKey|1|1|100.0%|
|SignalRPrivateEndpointConnections_Get|0|0|100.0%|
|SignalRSharedPrivateLinkResources_CreateOrUpdate|4|4|100.0%|
|SignalRReplicas_Delete|0|0|100.0%|
|SignalRCustomCertificates_CreateOrUpdate|3|3|100.0%|
|SignalRReplicas_Get|0|0|100.0%|
|SignalRReplicas_Update|7|7|100.0%|
|SignalRCustomDomains_Delete|0|0|100.0%|
|SignalRReplicas_CreateOrUpdate|7|7|100.0%|
|SignalRReplicas_Restart|0|0|100.0%|
|SignalRSharedPrivateLinkResources_List|0|0|100.0%|
|Usages_List|0|0|100.0%|
|SignalR_CreateOrUpdate|46|46|100.0%|
|SignalRCustomDomains_Get|0|0|100.0%|

**Comment by bjqian** [comment]
## API TEST ERROR REPORT<br>
|Rule|Message|
|---|---|

## Coverage Report
|Operation|Tested properties|Total properties|Coverage|
|---|---|---|---|
All|121|121|100.0%|
|WebPubSubPrivateEndpointConnections_Get|0|0|100.0%|
|WebPubSubReplicas_CreateOrUpdate|7|7|100.0%|
|WebPubSubCustomCertificates_Delete|0|0|100.0%|
|WebPubSubHubs_Get|0|0|100.0%|
|WebPubSub_Delete|0|0|100.0%|
|WebPubSubReplicas_Restart|0|0|100.0%|
|WebPubSubSharedPrivateLinkResources_Get|0|0|100.0%|
|WebPubSub_Get|0|0|100.0%|
|WebPubSubReplicas_List|0|0|100.0%|
|WebPubSubHubs_List|0|0|100.0%|
|WebPubSubReplicas_Delete|0|0|100.0%|
|WebPubSubSharedPrivateLinkResources_CreateOrUpdate|4|4|100.0%|
|WebPubSub_ListBySubscription|0|0|100.0%|
|WebPubSubHubs_CreateOrUpdate|15|15|100.0%|
|WebPubSubCustomDomains_List|0|0|100.0%|
|WebPubSubPrivateEndpointConnections_Update|4|4|100.0%|
|WebPubSub_CreateOrUpdate|36|36|100.0%|
|WebPubSubCustomDomains_Get|0|0|100.0%|
|WebPubSub_RegenerateKey|1|1|100.0%|
|WebPubSubCustomCertificates_Get|0|0|100.0%|
|WebPubSub_CheckNameAvailability|2|2|100.0%|
|WebPubSubPrivateLinkResources_List|0|0|100.0%|
|WebPubSubPrivateEndpointConnections_Delete|0|0|100.0%|
|WebPubSubReplicaSharedPrivateLinkResources_Get|0|0|100.0%|
|WebPubSubSharedPrivateLinkResources_List|0|0|100.0%|
|WebPubSubSharedPrivateLinkResources_Delete|0|0|100.0%|
|WebPubSub_Update|36|36|100.0%|
|WebPubSubHubs_Delete|0|0|100.0%|
|WebPubSubReplicas_Get|0|0|100.0%|
|WebPubSub_ListReplicaSkus|0|0|100.0%|
|WebPubSubReplicaSharedPrivateLinkResources_CreateOrUpdate|4|4|100.0%|
|WebPubSub_Restart|0|0|100.0%|
|WebPubSubCustomCertificates_List|0|0|100.0%|
|WebPubSub_ListSkus|0|0|100.0%|
|WebPubSub_ListByResourceGroup|0|0|100.0%|
|WebPubSub_ListKeys|0|0|100.0%|
|WebPubSubCustomCertificates_CreateOrUpdate|3|3|100.0%|
|WebPubSubCustomDomains_CreateOrUpdate|2|2|100.0%|
|WebPubSubCustomDomains_Delete|0|0|100.0%|
|Usages_List|0|0|100.0%|
|Operations_List|0|0|100.0%|
|WebPubSubReplicaSharedPrivateLinkResources_List|0|0|100.0%|
|WebPubSubPrivateEndpointConnections_List|0|0|100.0%|
|WebPubSubReplicas_Update|7|7|100.0%|

**Review by ms-henglu — APPROVED** [review]

**Pull request merged**
