### PR TITLE
[T2] workloadmonitor

### PR DESCRIPTION
**Pull request by msyyc**
https://github.com/Azure/sdk-release-request/issues/888
--

### CODE REVIEW

**Comment by juliaweingart** [comment]
Hi, to fix the SDK errors blocking merging, should I open another PR? Or can I update here on your branch?

**Comment by juliaweingart** [comment]
It looks like the failing check is because I named one of my model definitions "Monitor" in the swagger. This created an ambiguous reference in .Net since "Monitor" is already defined in the System.Threading library. Since this is a language-specific name, I would like to transform this client name when I generate the csharp client. I have attempted this with this code, but it isn't working locally when I generate the csharp client:
 
### Tag: package-2020-01-13-preview and csharp

These settings apply only when `--tag=package-2020-01-13-preview --csharp` is specified on the command line.
Please also specify `--csharp-sdk-folder=<path to the root directory of your azure-sdk-for-go clone>`.

``` yaml $(tag) == '2020-01-13-preview' && $(chsarp)
output-folder: $(csharp-sdks-folder)/workloadmonitor/Microsoft.Azure.Management.WorkloadMonitor/src/Generated
directive:
  - from: Microsoft.WorkloadMonitor.json
    where: $.definitions.Monitor
    transform: $['x-ms-client-name'] = 'HealthMonitor'
```

Do you know what I am doing wrong here?

**Review by changlong-liu — APPROVED** [review]

**Review by juliaweingart — APPROVED** [review]

**Comment by msyyc** [comment]
Could you help fix the pipeline failure of SDK Net? @changlong-liu

**Comment by changlong-liu** [comment]
Hi @msyyc , sorry I don't have knowledge of .Net SDK

Hi @msyyc, @ArcturusZhang ,
For discussion: I think the reported failure have no relation with this PR. I don't have permission to merge PR, would you help on merge this PR?

**Pull request merged**
