### PR TITLE
Updating Path Create in DataLakeStorage.json

### PR DESCRIPTION
**Pull request by carlotaguruceaga**
Updating Path Create in DataLakeStorage.json to include container policy fix restriction enforcing container encryption policy to be matching

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Do not merge yet. Wait for review from service from Sean.

**Review by seanmcc-msft — COMMENTED** [review]
What is the purpose of this PR?  Is this supposed to be for update public rest documentation?

**Review by seanmcc-msft — CHANGES_REQUESTED** [review]
I am not sure of the purpose of this PR, but this is not the correct file to be editing.

**Review by seanmcc-msft — CHANGES_REQUESTED** [review]
I am not sure what the purpose of this PR is, but this is not the correct file to be editing.

**Comment by carlotaguruceaga** [comment]
@seanmcc-msft  Create another PR with the correct file https://github.com/Azure/azure-rest-api-specs/pull/27418

**Pull request closed without merging**
