### PR TITLE
[Azure Maps] Add the boundingBox type to Search

### PR DESCRIPTION
**Pull request by alankashiwa**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - **Add the definition for `boundingBox` inside `Address` for generated code to properly deserialize.**
  2. When are you targeting to deploy the new service/feature to public regions? **Service already in production**
  3. When do you expect to publish the swagger? **ASAP**
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

### CODE REVIEW

**Comment by alankashiwa** [comment]
Hi, @tjprescott! We encountered one untyped object in the Search API.
This PR is to add the type for it so the generated client can properly deserialize it.

You can refer to the Python API view for it: [SearchResultAddress: bounding_box](https://apiview.dev/Assemblies/Review/0ab748be5297432eaf27d512e2d1b998#azure.maps.search.models.SearchResultAddress)

Thanks!

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@lmazuel can you merge this? It won't let me. `automation_generate.sh` is meant for management plane swaggers. 

cc/ @msyyc

**Comment by alankashiwa** [comment]
> @lmazuel can you merge this? It won't let me. `automation_generate.sh` is meant for management plane swaggers.
> 
> cc/ @msyyc

@tjprescott thanks for the review!

Hi @lmazuel, @msyyc!  Can you help us merge this? :)

**Comment by msyyc** [comment]
@alankashiwa we will try to fix ci failure of python soon.

**Comment by alankashiwa** [comment]
@msyyc Thanks for fixing the CI!
@tjprescott The pipeline is rerun by Yuchao. Are you able to merge the PR now?

**Pull request merged**
