### PR TITLE
New api version for redis 2018-03-01

### LINKED ISSUE #1347: [Redis] Internal Network API Bug
:wave: howdy!

I've been trying to add support for Redis on the Internal Subnets to Terraform.

Creating a Redis instance on an Internal Subnet works great, however there's a bug in the API when deleting it:

```
DELETE /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Cache/Redis/acctestRedis21?api-version=2016-04-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp-Terraform-v0.9.8
Accept-Encoding: gzip
```

which returns:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Mon, 26 Jun 2017 09:48:09 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Length: 0
```

Querying for the Redis Cache at this point then returns a 404:
```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Cache/Redis/acctestRedis21?api-version=2016-04-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp-Terraform-v0.9.8
Accept-Encoding: gzip

[DEBUG] AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Cache/Redis/acctestRedis21?api-version=2016-04-01:
HTTP/1.1 404 Not Found
Content-Length: 152
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 26 Jun 2017 09:48:10 GMT
Expires: -1
Pragma: no-cache

{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Cache/Redis/acctestRedis21' under resource group 'acctestRG-21' was not found."}}
```

Thus, it appears safe to delete the Subnet:
```
DELETE /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Network/virtualNetworks/acctestnw-21/subnets/testsubnet?api-version=2017-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp-Terraform-v0.9.8
Accept-Encoding: gzip
```

However attempting to delete the Subnet at this point returns an error:

```
2017/06/26 10:48:10 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Network/virtualNetworks/acctestnw-21/subnets/testsubnet?api-version=2017-03-01:
HTTP/1.1 400 Bad Request
Content-Length: 285
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 26 Jun 2017 09:48:10 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0

{
  "error": {
    "code": "InUseSubnetCannotBeDeleted",
    "message": "Subnet testsubnet is in use by /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-21/providers/Microsoft.Cache/Redis/acctestRedis21 and cannot be deleted.",
    "details": []
  }
}
```

From what I can see this is a bug in the Redis API which is exposing the Redis Cache as deleted when it's really still kicking around. Would it be possible to fix this bug in the API so that the Redis Cache is returned in a `Deleting` state until it's deleted like the other resources do?

Thanks!

### PR DESCRIPTION
**Pull request by TimLovellSmith**
Fixes  #1347. Redis RP now supports long-running delete operation with this api version.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
Please feel free to review, but do not accept this pull request yet.

**Review by mcardosos — CHANGES_REQUESTED** [review]
Hello @TimLovellSmith !
Changes in the swagger itself look good. However there are some [example validation errors](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/348414765#L772)

**Comment by tombuildsstuff** [comment]
hey @TimLovellSmith 

Out of interest does this API version include fixes for https://github.com/Azure/azure-rest-api-specs/issues/1347 and https://github.com/Azure/azure-rest-api-specs/issues/1499?

Thanks!

**Comment by TimLovellSmith** [comment]
@tombuildsstuff  #1347 yes, it is intended it will (api spec is done here, but server fixes are not yet rolled out). #1499 no, although I believe that is purely a server bug and won't require a new api version. If #1499 is still happening for you could you get me some more details in that bug's thread? I've had trouble tracking down what is going on there.

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by TimLovellSmith** [comment]
@mcardosos This PR is now ready to be accepted!
//cc jhendrixMSFT

**Comment by mcardosos** [comment]
Great!
@TimLovellSmith question, is this already deployed?

**Comment by TimLovellSmith** [comment]
@mcardosos 
Yes, you can now call the new api-version in public Azure

**Review by mcardosos — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-libraries-for-java

**Pull request merged**
