### PR TITLE
Update GraphQuery location property readOnly=false

### PR DESCRIPTION
**Pull request by xuzhang3**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/202/Overall-Process-of-AME-Onboarding) for the workflow.
- [x] [Validation tools](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/84/Swagger-Validation-tools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/FAQ.md).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process]( https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review).

### CODE REVIEW

**Comment by NullMDR** [comment]
@xuzhang3 Do you have any background of this change?

**Comment by xuzhang3** [comment]
> @xuzhang3 Do you have any background of this change?

Property marked with `readOnyl` will be removed in custom `json.Marshal`.  This parameter is  required  for back-end service and can not be ignored.   

Marked with `readOnly` code:
```go
func (gqup GraphQueryUpdateParameters) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	if gqup.Tags != nil {
		objectMap["tags"] = gqup.Tags
	}
	if gqup.ETag != nil {
		objectMap["eTag"] = gqup.ETag
	}
	if gqup.GraphQueryPropertiesUpdateParameters != nil {
		objectMap["properties"] = gqup.GraphQueryPropertiesUpdateParameters
	}
	return json.Marshal(objectMap)
}
```

Remove `readOnly` :
```go
func (gqup GraphQueryUpdateParameters) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})
	if gqup.Tags != nil {
		objectMap["tags"] = gqup.Tags
	}
        if gqup.Location != nil {
		objectMap["location"] = r.Location
	}
	if gqup.ETag != nil {
		objectMap["eTag"] = gqup.ETag
	}
	if gqup.GraphQueryPropertiesUpdateParameters != nil {
		objectMap["properties"] = gqup.GraphQueryPropertiesUpdateParameters
	}
	return json.Marshal(objectMap)
}

```

**Comment by NullMDR** [comment]
@xuzhang3 Do you need to mark it as required?

**Comment by xuzhang3** [comment]
> @xuzhang3 Do you need to mark it as required?

How to mark it as required?

**Comment by xuzhang3** [comment]
@OlhaTkachenko @demyanenko
Can you help review this PR?

**Review by chiragg4u — APPROVED** [review]
Can we update the description to clarify this is a global object and only global value is acceptable.

**Comment by NullMDR** [comment]
@xuzhang3 Is this PR ready be to merged?

**Comment by xuzhang3** [comment]
> @xuzhang3 Is this PR ready be to merged?

Ready!

**Comment by NullMDR** [comment]
@akning-ms Please help to merge this PR with breaking change approved. It's a swagger bugfix.

**Pull request merged**
