### PR TITLE
Mitryakh/network 2022 01 01

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
Monthly release of Azure Networking for new api version 2022-01-01

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [X] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
No need for ARM review due to this PR contains ~10 PRs which were already reviewed and approved by ARM

**Comment by lirenhe** [comment]
@AndriiKalinichenko, there are a couple of prettier check errors which I believe is related to your PR, could you follow this guide to fix it?  [HowToFix](https://aka.ms/AA6h31t)

**Comment by MikhailTryakhov** [comment]
@lirenhe looks like at least part of the failures are happened repeatadly and not a blocker at all (like VMSS api version)

**Comment by MikhailTryakhov** [comment]
@lirenhe is that all to be merged? Actually can you please approve, but not merge yet, due to the manifest update still going on, we need to wait until June, 25

**Comment by lirenhe** [comment]
> @lirenhe is that all to be merged? Actually can you please approve, but not merge yet, due to the manifest update still going on, we need to wait until June, 25

There are still code style errors, and for the cross version breaking change,   @raych1 , i didn't see the breaking change approved in https://github.com/Azure/azure-rest-api-specs/pull/19299,  is this expected?

**Comment by lirenhe** [comment]
> @lirenhe is that all to be merged? Actually can you please approve, but not merge yet, due to the manifest update still going on, we need to wait until June, 25

@MikhailTryakhov, there are code style issues reported in, can someone from your team to fix it?
@openapi-pipeline-app
Swagger PrettierCheck Failing after 5m — Swagger PrettierCheck failed
Required
[Details](https://github.com/Azure/azure-rest-api-specs/pull/19412/checks?check_run_id=6880601079)

**Comment by MikhailTryakhov** [comment]
@AndriiKalinichenko can you please help with examples code style fixes? 

https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#prettier-check - how to fix.
List of files with issues: https://github.com/Azure/azure-rest-api-specs/pull/19412/checks?check_run_id=6880601079

**Comment by MikhailTryakhov** [comment]
PR with fix is provided 
[Fix prettier errors for Virtual Hub Router Scale Units by AndriiKalinichenko · Pull Request #19462 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/19462)

**Comment by MikhailTryakhov** [comment]
@lirenhe what do you think about PR now? :)

**Comment by MikhailTryakhov** [comment]
That's a work for a creator of this PR
[Gizachew-Eshetie](https://github.com/Gizachew-Eshetie) can you please do it ASAP?

My strong recommendation: if we have breaking changes introduce in the PR like that, we'll need to request this approval reviewing that, not on this stage...

**Comment by raych1** [comment]
> That's a work for a creator of this PR [Gizachew-Eshetie](https://github.com/Gizachew-Eshetie) can you please do it ASAP?
> 
> My strong recommendation: if we have breaking changes introduce in the PR like that, we'll need to request this approval reviewing that, not on this stage...

I totally agree on this though it's missed in the original PR.

**Comment by MikhailTryakhov** [comment]
Guys @lirenhe @raych1 looks like it's approved already. We're ready to merge

**Comment by MikhailTryakhov** [comment]
@raych1  @lirenhe  can you please approve?

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
