### PR TITLE
Refactor to host specs in preview/stable folders.

### PR DESCRIPTION
**Pull request by marstr**
This is in an effort to differentiate more clearly the Open API Specs
that are ready for public consumption, and those that should be treated
as a preview or in development. Simply treating the presence of the
suffux `-preview` on an API Version is insufficient, because the status
of the Swagger itself may be preview, while the API Version is release
quality.

---

The normal checklist is omitted because this relates to the shape of the repository, and not the actual Swaggers themselves.

### CODE REVIEW

**Comment by marstr** [comment]
Tagged reviewers:

My primary request from you is to help identify miscategorized API Versions. If there's something you know of, that should be in `stable` or `preview` folder, but is not: please let me know here and I'll make the correction.

**Comment by marstr** [comment]
Given the holiday status, I'm assuming none of the reviewers are going to get a chance to look at this. I'm using my administrator privileges in this repo to merge this in.

**Comment by austinlparker** [comment]
hey, this seems to break the azure cli, it's got references to the old URL's. do you know if there's a new version of that or something?

**Comment by jesse-welch** [comment]
Verified as resolved here: https://github.com/Azure/azure-cli/issues/5178

**Comment by marstr** [comment]
Thanks for bringing this to our attention, @austinlparker. Sorry for any inconvenience this caused.

**Pull request merged**
