### PR TITLE
licenseKey is option properties and should be removed from required

### PR DESCRIPTION
**Pull request by liubing-microsoft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by raych1 — COMMENTED** [review]
@liubing-microsoft , is there any example to cover the related API that references this model?

**Comment by liubing-microsoft** [comment]
> @liubing-microsoft , is there any example to cover the related API that references this model?

This model is used to add some extra configurations during IR Provision.  Does the example you mentioned above mean the payload of the IR provision which use this model?

**Comment by raych1** [comment]
> > @liubing-microsoft , is there any example to cover the related API that references this model?
> 
> This model is used to add some extra configurations during IR Provision. Does the example you mentioned above mean the payload of the IR provision which use this model? @raych1

I mean x-ms-example used to test the API.

**Comment by liubing-microsoft** [comment]
> > > @liubing-microsoft , is there any example to cover the related API that references this model?
> > 
> > 
> > This model is used to add some extra configurations during IR Provision. Does the example you mentioned above mean the payload of the IR provision which use this model? @raych1
> 
> I mean x-ms-example used to test the API.

NO, we don't have x-ms-example. Is it mandatory even if we just want to remove one properties?

**Review by raych1 — APPROVED** [review]
It's recommended to add examples for each Api.

**Pull request merged**
