### PR TITLE
Remove Get GlobalCommunicationsSite API from Orbital AODG APIs

### PR DESCRIPTION
**Pull request by nathank527**
Get on an Individual AODG GlobalCommunicationSite resulted in an UnsupportedResourceOperation error due to the specific API using a fanout API which is unsupported by ARM.

### CODE REVIEW

**Comment by nathank527** [comment]
## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [x] Other, please clarify:
    - Removing a Failing API from our spec. This API has no customers and should have never made it into this repo. 
## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

**Review by raosuhas — APPROVED** [review]

**Pull request merged**
