### PR TITLE
[Cogs Face] Overall Refinement (renaming, refactoring, bug fixing, reference refining)

### PR DESCRIPTION
**Pull request by lebronJ**
Hi,

I am a member of Face SDK team, focusing on Cogs Face API. This PR is mainly to improve the Face API Swagger file by (See [comment](https://github.com/Azure/azure-rest-api-specs/pull/2192#issuecomment-353377739) below for details)
1) Renaming for better understanding
2) Refactoring object types (by extracting shared parameters/definitions and using inheritance) 
3) Fixing existing bugs
4) Refining SDK references

This PR is based on @DavidLiCIG 's former version and has been reviewed internally with teammates @huxuan by generating .NET SDK to check the outcome SDK structure and validate all unit tests.

### CODE REVIEW

**Comment by huxuan** [comment]
Confirmed for the internal review. And review process can be referred here: lebronJ/azure-sdk-for-net#1

**Comment by lebronJ** [comment]
Detailed major changes in this PR:
1. Extract shared `faceUserData`, `faceListId`, `personGroupId`, `personId` and `persistedFaceId` as request parameter
2. Extract `NameAndUserDataContract` as 
  a) request body for creating/updating `person`/`personGroup/faceList` and
  b) base class of `person`/`personGroup/faceList`
3. Fix wrong nullable types
4. Correct/Refine comments
5. Rename and refactor object types for better understanding:
  a) `Person`, `PersonGroup`, `PersonGroupPerson`, `FaceList`, `PersistedFace`, `DetectedFace`
  b) `VerifyFaceToFaceRequest` and `VerifyFaceToPersonRequest`
  c) Remove trailing `Properties` for face attributes (eg. `FacialHairProperties` to `FacialHair`)
6. Extract shared `Confidence` and `Level` for number threshold of `[0-1]`
7. Fix incorrect examples

**Review by DavidLiCIG — APPROVED** [review]
Looks good!

**Comment by lebronJ** [comment]
Force push to rebase onto master branch

**Comment by fearthecowboy** [comment]
A couple content-type mismatches in examples:  https://travis-ci.org/Azure/azure-rest-api-specs/jobs/324014381#L679

**Comment by huxuan** [comment]
Hi @fearthecowboy, the content type error should be a known issue as explained here https://github.com/Azure/azure-rest-api-specs/pull/2166#issuecomment-352654081.

> The content type errors have to do with Azure/oav#136 (Azure/oav#167)

**Review by fearthecowboy — APPROVED** [review]

**Comment by fearthecowboy** [comment]
@huxuan Ah, right thanks! (FYI, in follow up PRs, we should probably note that in the PR comment ahead so that the next reviewer (aka 'future @fearthecowboy') knows. 

😁

**Comment by fearthecowboy** [comment]
If y'all are happy, I'm happy, so I can merge anytime. OK to Merge?

**Comment by DavidLiCIG** [comment]
Hi

Yes, please proceed with the merge.

Thanks!
David
________________________________

**Comment by huxuan** [comment]
@fearthecowboy Gotcha, will do it in the following pull requests. @lebronJ just for reminder~Good Job, man.

**Pull request merged**
