### PR TITLE
[Hub Generated] Review request for Microsoft.DesktopVirtualization to add version  preview/2023-07-07-preview

### PR DESCRIPTION
**Pull request by alec-baird**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/alec-baird-desktopvirtualization-Microsoft.DesktopVirtualization-2023-07-07-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by alec-baird** [comment]
@rkmanda , adding a pattern to this parameter that has already been used in multiple places causes breaking changes, can we get an exception for the pattern check?

**Comment by maririos** [comment]
You need to follow one of these options in order to continue the PR review process: https://github.com/Azure/azure-rest-api-specs/pull/24747#issuecomment-1633293182

**Comment by alec-baird** [comment]
> You need to follow one of these options in order to continue the PR review process: [#24747 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24747#issuecomment-1633293182)

But it doesn't have any breaking changes, or am I missing something?

**Comment by visingla-ms** [comment]
>           "$ref": "#/definitions/ScalingPlanPersonalScheduleProperties"

Can all the properties from this resource definition be patched? Please ensure to use only patch-able properties in the PATCH request payload.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-07-07-preview/desktopvirtualization.json:6690 in 3bb7888. [](commit_id = 3bb7888e9223b0b7a85ea7f053e6123fca7b3049, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "../../../../../common-types/resource-management/v1/types.json#/definitions/ProxyResource"

There is a mixed use of v1, v2 and v3 common types in newly introduced APIs and resource definitions. Please use only v3 common types here.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-07-07-preview/desktopvirtualization.json:6721 in 3bb7888. [](commit_id = 3bb7888e9223b0b7a85ea7f053e6123fca7b3049, deletion_comment = False)

**Comment by dallinlmag** [comment]
@visingla-ms 

I reviewed the code from your comment regarding the patch properties, and for this resource, all of the property fields are patchable. 

I changed the common-types to V3 for the new scaling api and it caused breaking changes. How would you like us to proceed here?

**Comment by alec-baird** [comment]
@visingla-ms, we are trying to meet a deadline to get this PR published, is there any way you can take a look at this soon and provide feedback? It unfortunately had that label issue which caused it to be stale for over 2 weeks. Thanks so much!

**Comment by zizw123** [comment]
> @visingla-ms, we are trying to meet a deadline to get this PR published, is there any way you can take a look at this soon and provide feedback? It unfortunately had that label issue which caused it to be stale for over 2 weeks. Thanks so much!

Please work with breaking change team to see if this can be approved as it is, and also fix the lintDiff error https://github.com/Azure/azure-rest-api-specs/pull/24747/checks?check_run_id=15491289872

Other part looks good to me

**Comment by alec-baird** [comment]
> > @visingla-ms, we are trying to meet a deadline to get this PR published, is there any way you can take a look at this soon and provide feedback? It unfortunately had that label issue which caused it to be stale for over 2 weeks. Thanks so much!
> 
> Please work with breaking change team to see if this can be approved as it is, and also fix the lintDiff error https://github.com/Azure/azure-rest-api-specs/pull/24747/checks?check_run_id=15491289872
> 
> Other part looks good to me

Adding v3 caused the breaking change as advised earlier in PR. Ideally we don't use v3 and cause any breaking changes. The only LintDiff error is also unable to be corrected because it would cause breaking changes as well. Please let us know if we can revert back to v1 types here as well as get a LintDiff exception. @zizw123

**Comment by ms-zhenhua** [comment]
> > > @visingla-ms, we are trying to meet a deadline to get this PR published, is there any way you can take a look at this soon and provide feedback? It unfortunately had that label issue which caused it to be stale for over 2 weeks. Thanks so much!
> > 
> > 
> > Please work with breaking change team to see if this can be approved as it is, and also fix the lintDiff error https://github.com/Azure/azure-rest-api-specs/pull/24747/checks?check_run_id=15491289872
> > Other part looks good to me
> 
> Adding v3 caused the breaking change as advised earlier in PR. Ideally we don't use v3 and cause any breaking changes. The only LintDiff error is also unable to be corrected because it would cause breaking changes as well. Please let us know if we can revert back to v1 types here as well as get a LintDiff exception. @zizw123

Why add a `pattern` will cause breaking change? Could you define a new parameter structure for the new API path?
https://github.com/Azure/azure-openapi-validator/blob/main/docs/resource-name-restriction.md

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
