### PR TITLE
[Hub Generated] Review request for Creator to add version preview/2022-09-01-preview

### LINKED ISSUE #17312: [Maps - Styling] REST API Review for Azure Maps Styling Service
Service Name: Azure Maps Styling Service

Key contact for the review: Xubin Zhuge(@Xubin Zhuge) / James Jonghan Park(@James Jonghan Park)

The changes contain both existing APIs(Tileset) and new APIs(StyleRecipe, StyleSet)

The service is deployed, but the proposed changes are still in progress.

What changed in this PR:
 - We create a new 2022-01-01-preview version API for Tileset, StyleSet and StyleRecipe under Creator
- We extended our exising Tileset API with Tileset Recipe ingested, and we also added Tileset Recipe GET and Validation API.
- We added two new set of APIs StyleSet and StyleRecipe which are our new APIs

Custom Styling Design doc: 

https://microsoft.sharepoint.com/:w:/t/MicrosoftMapsGeospatialTeam/EUyAGqR7R4pJoIXkXQdlQcAB7SPLJQImjNS0eQGp8xathQ?e=eccr4D

### PR DESCRIPTION
**Pull request by zhugexubin**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/zhugexubin/azure-rest-api-specs/dev-maps-Creator-xubin-2022-09-01-preview...main/).
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by zhugexubin** [comment]
This is the issue associated with this PR: https://github.com/Azure/azure-rest-api-specs/issues/17312

**Comment by tjprescott** [comment]
@zhugexubin has the API review board been scheduled for this new version?

**Comment by zhugexubin** [comment]
> @zhugexubin has the API review board been scheduled for this new version?

@tjprescott  We already finished the API review board process and fixed all the comments from the board there.

**Comment by zhugexubin** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/17312 This is the issue created with API Review board for the swagger changes.

**Comment by tjprescott** [comment]
@zhugexubin I'm confused because this is the PR that issue links to: https://github.com/Azure/azure-rest-api-specs/pull/18584

This API version is 8 months later.

**Comment by zhugexubin** [comment]
> @zhugexubin I'm confused because this is the PR that issue links to: #18584
> 
> This API version is 8 months later.

Right, since we decided to change public preview API version from 2022-01-01-preview to 2022-09-01-preview, that's why I created another PR for the new version.

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
