### PR TITLE
added 202 response for vault deletion to preview mgmt plane swaggers

### PR DESCRIPTION
**Pull request by iscai-msft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by heaths — CHANGES_REQUESTED** [review]
What about 2019-09-01?

**Comment by iscai-msft** [comment]
> What about 2019-09-01?

I've already made the changes to 2019-09-01 in my other pr that has fixed all the stable versions: https://github.com/Azure/azure-rest-api-specs/pull/8284/files.
A little gross that they're separate though.

**Comment by heaths** [comment]
Ah, thanks. Approving.

**Review by heaths — APPROVED** [review]

**Comment by heaths** [comment]
You could ignore (or fix*) the [ENUM_MISMATCH](https://dev.azure.com/azure-sdk/public/_build/results?buildId=253882&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=94) error. Basically, it should still be the old 2015 version. As for the other two failures, these might be related to your change. Could you correct those?

**Pull request merged**
