### PR TITLE
default EnableHttpsTrafficOnly to TRUE

### PR DESCRIPTION
**Pull request by changlong-liu**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
this is a breaking change for preview customers since the default value has changed. ARM team is not reviewing property changes going forward. hence removing this label.

**Comment by blueww** [comment]
@ravbhatnagar 
For "ARM team is not reviewing property changes going forward. hence removing this label."
Do you mean ARM team will will depends on the CI check to validate the property changes?

For "property changes" won't be reviewed by ARM team, does that include :
1. Add new properties to exist API
2. Remove exist properties
3. Change type, name, default value of exist API?

Is there any doc for what will be reviewed by ARM team, and what will not?

**Comment by changlong-liu** [comment]
Hi @blueww , 
Refer to the API guideline: https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#api-changes-that-require-a-version-change, security-reason change is an exception for update api version.

Keeping supportsHttpsTrafficOnly==False is a security hole for the customer.

Since this is a fix for security issue in old version, would you help to review this PR from service point of view?  Thanks.

**Comment by blueww** [comment]
@changlong-liu

If ARM review board and OneSDK team both agree on the PR, I don't have more concern on it.
Anyway, this is a breaking change to SDK, we also need to upgrade a major version to add this change to SDK.

**Comment by changlong-liu** [comment]
Thanks @blueww , add @akning-ms @qianwens for OneSDK team.

Hi @blueww ,  SDK don't have exactly the same rule on breaking change with api level.

**Comment by blueww** [comment]
@changlong-liu 
We should upgrade a major version for SDK when there's a breaking change, to inform user the breaking, and avoid surprise on the breaking.

**Comment by changlong-liu** [comment]
Hi @blueww , would you tell more about why this is a breaking change in SDK level?  
Changing input default value should not thought as breaking in SDK.

**Comment by blueww** [comment]
@changlong-liu 
For why this is a swagger breaking ,please check with ARM review board and OneSDK team.

For why this is a SDK breaking, consider:
A user have an application to create storage account with default setting, then do dataplane operation on the created storage account with http.
- Before the change , the created storage account will have "supportsHttpsTrafficOnly" as false, so everything works well.
- After the change, the created storage account will have "supportsHttpsTrafficOnly" as true, the user's application will fail to run dataplane operation with http.

If the swagger PR can merge, I am OK with release SDK for that, and will upgrade a major SDK version.

**Comment by changlong-liu** [comment]
Hi @blueww, Thanks for detail introduction. 

I agree we should add changelog to notice the end user for this change.
But I think this is more about a side effect, not a breaking change for azure-mgmt-storage itself.   It's arguable to add a changelog like this in SDK point of view:
~~~
*** Breaking change ***
default value for supportsHttpsTrafficOnly changed to True
~~~
because it actually breaking no StorageAccount operation in azure-mgmt-storage.

I will prefer something like below:
~~~
***Features***
default value for supportsHttpsTrafficOnly changed to True, take care of your HTTP only code in azure-storage. 
~~~

**Comment by changlong-liu** [comment]
Synced in email thread.
Since this is currently not required by MSRC/security teams, close this PR.

**Pull request closed without merging**
