### PR TITLE
Updating Response codes

### PR DESCRIPTION
**Pull request by sranthar**
Removing 404 not found response codes as we have removed that from the code.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by bganapa — APPROVED** [review]

**Comment by bganapa** [comment]
@sranthar validations are failing as you need to remove the 404 from examples as well

**Comment by majastrz** [comment]
>         "responses": {

Since you're fixing responses, you should also add a `default` response to all operations that points to the standard error response definition in common-types. ([https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content))

---
Refers to: specification/azsadmin/resource-manager/network/Microsoft.Network.Admin/preview/2015-06-15/Quotas.json:45 in ffa095c. [](commit_id = ffa095c67616cd75fbb597ac707f4c8554d1b437, deletion_comment = False)

**Comment by majastrz** [comment]
Added a comment. Please take a look.

**Comment by erich-wang** [comment]
@sranthar , please address the comment.

**Comment by majastrz** [comment]
>         "responses": {

We discussed and this will be deferred to a later PR.

---
In reply to: [606267856](https://github.com/Azure/azure-rest-api-specs/pull/8866#issuecomment-606267856) [](ancestors = 606267856)

---
Refers to: specification/azsadmin/resource-manager/network/Microsoft.Network.Admin/preview/2015-06-15/Quotas.json:45 in ffa095c. [](commit_id = ffa095c67616cd75fbb597ac707f4c8554d1b437, deletion_comment = False)

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by erich-wang** [comment]
@sranthar, please fix the error in CI check. More error detail is available at https://dev.azure.com/azure-sdk/public/_build/results?buildId=337365&view=results.

**Comment by erich-wang** [comment]
Close it as it is duplicate to #8961 per @sranthar.

**Pull request closed without merging**
