### PR TITLE
Add new ApiVersion 2019-03-01 and add optional flag 'skipShutdown' for existing Poweroff API

### PR DESCRIPTION
**Pull request by vamuzumd**
1. Changed readme.md to add new ApiVersion 2019-03-01 tag package. 
2. Cloned a new folder for 2019-03-01 from 2018-10-01 and made version replacements. 
3. Added skipShutdown changes for PowerOff Api in 2019-03-01 compute.json for CRP and VMSS.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5713 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5713/commits/7459d4fc2dc1bd3ca41d0fb108055b9e764528a5

**Review by anuchandy — CHANGES_REQUESTED** [review]
Could you please use https://portal.azure-devex-tools.com/app to create the PR. You can choose “Create OpenAPI sepcs”, where you should be able to choose previous api-version as the base for this new api-version. The tool will create a branch in your fork, with necessary initial commits. Then you can add a commit on the top with your change that adds skipShutdown optional flag, this will speed up both ARM and SDK review, since reviewers can go to last commit and just see what exactly changed in the new api-version.

**Comment by vamuzumd** [comment]
> Could you please use https://portal.azure-devex-tools.com/app to create the PR. You can choose “Create OpenAPI sepcs”, where you should be able to choose previous api-version as the base for this new api-version. The tool will create a branch in your fork, with necessary initial commits. Then you can add a commit on the top with your change that adds skipShutdown optional flag, this will speed up both ARM and SDK review, since reviewers can go to last commit and just see what exactly changed in the new api-version.

I don't think that is needed as there is  already another pull requests making ApiVersion change which is on the verge of completion and I am piggybacking on this change.
https://github.com/Azure/azure-rest-api-specs/pull/5492

**Comment by anuchandy** [comment]
@KrisBash, @ravbhatnagar please review addition of optional query parameter to VM shutdown API.

**Review by KrisBash — APPROVED** [review]
LGTM

**Review by anuchandy — APPROVED** [review]
LGTM. no changes in readme file ("diff settings" -> Hide whitespace changes")

**Pull request merged**
