### PR TITLE
Azure Networking 2021-08-01 release of monthly branch

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [X] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  >> It's already deployed
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  >> 4/2
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR
No, it's a new version created

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [X] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@MikhailTryakhov , can you fix CI check failures?

**Comment by MikhailTryakhov** [comment]
@raych1 
Swagger Avocado
known issue from VMSS related resources - approved to be there.

I'm investigating Swagger LintDiff, regarding to them I'm really confused
1) https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/firewallPolicy.json#L2145 **"The default value is not one of the values enumerated as valid for this element."**
didn't get it. Also the job worked well in the latest PR to change firewallPolicy

2) Inline/anonymous models must not be used, instead define a schema with a model name in the 'definitions' section and refer to it. This allows operations to share the models.
Location: [Microsoft.Network/stable/2021-08-01/network.json#L221](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/network.json#L221) 

Can you please clarify, is it related to the double type property is there? in lines 220 and 222

3) Resource provider naming must follow the pascal case. Path: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines/{virtualmachineIndex}/networkInterfaces'
Location: [Microsoft.Network/stable/2021-08-01/vmssNetworkInterface.json#L37](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/vmssNetworkInterface.json#L37)

would fix

4) The last resource provider 'Microsoft.Compute' doesn't match the namespace.
Location: [Microsoft.Network/stable/2021-08-01/cloudServiceNetworkInterface.json#L37](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/cloudServiceNetworkInterface.json#L37)

Compute is approved for these files

5)I'll investigate description regarding the latest [DefaultErrorResponseSchema](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/openapi-authoring-automated-guidelines.md#R4007)

**Comment by MikhailTryakhov** [comment]
@raych1  @lirenhe 
please help to find would a fix be enough? Also we can sync up to determine list of workitems for teams to assign tasks for them

**Comment by thebenwaters** [comment]
@raych1 is there a way to retrigger the failed sdk generations? We're trying to develop powershell and azure-cli features in parallel to openapi changes

**Comment by raych1** [comment]
@thebenwaters , I want to confirm with you for [Avocado inconsistent api version failures](https://github.com/Azure/azure-rest-api-specs/pull/18440/checks?check_run_id=5861529292) you just copy those two swaggers from previous api version folder and keep the legacy api version, right?

**Comment by jianyexi** [comment]
> @raych1 Swagger Avocado known issue from VMSS related resources - approved to be there.
> 
> I'm investigating Swagger LintDiff, regarding to them I'm really confused
> 
> 1. https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/firewallPolicy.json#L2145
>     **"The default value is not one of the values enumerated as valid for this element."**
>    didn't get it. Also the job worked well in the latest PR to change firewallPolicy
> 2. Inline/anonymous models must not be used, instead define a schema with a model name in the 'definitions' section and refer to it. This allows operations to share the models.
>    Location: [Microsoft.Network/stable/2021-08-01/network.json#L221](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/network.json#L221)
> 
> Can you please clarify, is it related to the double type property is there? in lines 220 and 222
> 
> 3. Resource provider naming must follow the pascal case. Path: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines/{virtualmachineIndex}/networkInterfaces'
>    Location: [Microsoft.Network/stable/2021-08-01/vmssNetworkInterface.json#L37](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/vmssNetworkInterface.json#L37)
> 
only 1 is a must fix, the others are optional to fix
> for 1:  the default value is not needed here, you can remove it to fix, this rule also ensure all default value and enum must exist both or not 
  for 2: correct, 
  for 3:  it's regarding to 'microsoft.Compute' , the first character should be capital

**Comment by MikhailTryakhov** [comment]
@[jianyexi](https://github.com/jianyexi)  can you please confirm can it be merged as an exception?

**Comment by MikhailTryakhov** [comment]
@thebenwaters  can you plesae help with 1)? 
for 1: the default value is not needed here, you can remove it to fix, this rule also ensure all default value and enum must exist both or not

[azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/firewallPolicy.json](https://github.com/Azure/azure-rest-api-specs/blob/6541d305880d1cf580496adc01f55197a01e992c/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/firewallPolicy.json#L2145)

Line 2145 in [6541d30](https://github.com/Azure/azure-rest-api-specs/commit/6541d305880d1cf580496adc01f55197a01e992c)

 "name": "api-version",

**Comment by MikhailTryakhov** [comment]
@raych1  can you please merge it now?

**Comment by MikhailTryakhov** [comment]
Hey @raych1 looks much better now, can we merge it?

**Review by raych1 — APPROVED** [review]

**Pull request merged**
