### PR TITLE
Update CasesAggregations spec

### PR DESCRIPTION
**Pull request by landau07**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by landau07** [comment]
Can you please assit with understand what was wrong with the PR? in local the autorest tool pass the tests

**Comment by praries880** [comment]
@landau07  here is the model validation job [failure log](https://dev.azure.com/azure-sdk/public/_build/results?buildId=19481&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&taskId=43324f1f-6724-5d61-785f-f0ac9fd256a1&lineStart=846&lineEnd=847&colStart=1&colEnd=1)

You need to fix the examples or the spec... both need to specify the property as the same type.

**Comment by praries880** [comment]
@landau07 Where is the new type `CaseAggregation` used?

**Comment by praries880** [comment]
@landau07 
There are some model validations that you need to fix in the swagger : https://dev.azure.com/azure-sdk/public/_build/results?buildId=19644&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&taskId=43324f1f-6724-5d61-785f-f0ac9fd256a1&lineStart=31&lineEnd=32&colStart=1&colEnd=1

Kindly look at them and fix the issues.

**Comment by praries880** [comment]
@landau07  pinging back....

**Comment by praries880** [comment]
@landau07 Will you or someone form your team be working on the PR in the next few days? If not, we can close this one and you can open another once when you are ready for the review.

**Comment by landau07** [comment]
Closing this PR and adding it again in new PR from Dor Segal PR with the rest of the fixes

**Pull request closed without merging**
