### PR TITLE
[Azure Maps] Route: Swagger improvement for SDK generation [Hub Generated]

### PR DESCRIPTION
**Pull request by alankashiwa**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/alankashiwa/azure-rest-api-specs/dev-maps-DEM-1.0...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [x]  To improve swagger for generated clients from [this review in ApiView](https://apiview.dev/Assemblies/Review/904055845aae43f78db8e9a450bd26a0)
  2. When are you targeting to deploy the new service/feature to public regions? **Services already deployed.**
  3. When do you expect to publish the swagger? **ASAP**
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published. **No data-plane SDKs are onboarded yet, so no refresh is required.**

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [x] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

### CODE REVIEW

**Review by daniel-rocha — CHANGES_REQUESTED** [review]
This is the first batch of changes. There may be more after codegen testing.

**Comment by daniel-rocha** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/e677d790cbf4cf56f7e224de6dfae119cde87fee/specification/maps/data-plane/Route/preview/1.0/route.json#L1432 

Incorrect parameter, needs to be a collectionFormat csv as usual. With number / double.

**Comment by alankashiwa** [comment]
> https://github.com/Azure/azure-rest-api-specs/blob/e677d790cbf4cf56f7e224de6dfae119cde87fee/specification/maps/data-plane/Route/preview/1.0/route.json#L1432
> 
> Incorrect parameter, needs to be a collectionFormat csv as usual. With number / double.

Thanks! Updated with `collectionFormat` with `number/double`.

**Comment by alankashiwa** [comment]
> Please review all uses of "number" that either contain no format or format "float". All need to be converted to double.

Thanks! I spotted several more fields and replace them with `double`. (Backend vertified)

**Review by daniel-rocha — APPROVED** [review]

**Comment by daniel-rocha** [comment]
@tjprescott I think this is ready for a review. One comment of mine about getRouteDirections and getRouteDirectionsWithAdditionalParameters is that there's no good way to name the latter, and they have similar functionality, so we'll collapse them into an Options class in the SDK.

**Review by tjprescott — CHANGES_REQUESTED** [review]
Minor comments (questions) but overall looks good.

**Comment by tjprescott** [comment]
> @tjprescott I think this is ready for a review. One comment of mine about getRouteDirections and getRouteDirectionsWithAdditionalParameters is that there's no good way to name the latter, and they have similar functionality, so we'll collapse them into an Options class in the SDK.

I agree that there's no good way. The convenience layer will almost certainly (if other SDKs are a guide) use the POST and ignore the GET, or in any case using the "get_foo" naming, so it would probably be fine to leave "post_foo" since it will just be in the generated layer. It's also fine to go with what's in this PR.

**Comment by alankashiwa** [comment]
@tjprescott I've addressed those naming issues. Please take a look and let me know whether these changes are appropriate. If they are good then this PR can be merged too :)

**Review by alextts627 — APPROVED** [review]

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
