### PR TITLE
Updated swagger docs in stable and track1\preview with changes to ImageAnalysis skill

### PR DESCRIPTION
**Pull request by jennifermarsman**
Updated swagger docs in stable and track1\preview with changes to ImageAnalysis skill (new languages and visual features)

This is just a swagger change that did not change the SDK, as per Bruce's instructions.  Data plane API.  

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
@lmazuel I'm assuming you're the designated Swagger reviewer for this PR. Please be aware that no client libraries have been shipped yet that depend on this spec (shipped libraries depend on specs in the "track1" folder), so breaking changes are not a concern here.

**Review by bitsforthought — COMMENTED** [review]
@jennifermarsman The changes look fine to me (not being a skillset SME), but I know @arv100kri had some opinions on whether the various enums used in skills should be extensible or not.

**Review by bitsforthought — CHANGES_REQUESTED** [review]
Somehow it looks like you've added commits from master to your PR that aren't just merge commits. Please recreate your PR from a topic branch (i.e. -- not `jennifermarsman:master`) after applying your changes on top of `Azure:master`.

**Comment by jennifermarsman** [comment]
Closing this pull request and opening new one for this change: https://github.com/Azure/azure-rest-api-specs/pull/8371

**Pull request closed without merging**
