### PR TITLE
2021-04-01-preview to add private link support

### PR DESCRIPTION
**Pull request by walrusmcd**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - [ ] Adding new API(s)
  - [x] Adding a new API version
  - [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - [ ] Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by walrusmcd** [comment]
Note:   the linting failure is on systemData not being present.   these are for the 4 new endpoints that return privatelink objects.   Since I'm returning the built in types, how do we proceed?    these built in types (v1 and v2) don't support systemData today.  [Here ](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v2/privatelinks.json)is the v2 type for private link.

**Comment by mentat9** [comment]
>           "default": {

Add x-ms-error-response

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2021-04-01-preview/desktopvirtualization.json:2481 in d63f2a3. [](commit_id = d63f2a32bc86087076826324aef7a3ccabf2abed, deletion_comment = False)

**Comment by mentat9** [comment]
>           "200": {

Successful PUT response code should be 201. 200 is also OK when PUT did nothing.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2021-04-01-preview/desktopvirtualization.json:2615 in d63f2a3. [](commit_id = d63f2a32bc86087076826324aef7a3ccabf2abed, deletion_comment = False)

**Comment by mentat9** [comment]
>           "200": {

Change this to 201 (or add 201 in addition).

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2021-04-01-preview/desktopvirtualization.json:2839 in d63f2a3. [](commit_id = d63f2a32bc86087076826324aef7a3ccabf2abed, deletion_comment = False)

**Comment by mentat9** [comment]
I'm not sure how to handle the linter error related to systemData (vs. using common types). Could you post a stackoverflow question about this? After posting, also email a link to your SO question to Azure Resource Manager RP API Review <armapireview@microsoft.com>. Info on posting ARM questions to SO: https://armwiki.azurewebsites.net/troubleshooting/stackoverflow_guide.html?q=stackoverflow

**Comment by mentat9** [comment]
> Note: the linting failure is on systemData not being present. these are for the 4 new endpoints that return privatelink objects. Since I'm returning the built in types, how do we proceed? these built in types (v1 and v2) don't support systemData today. [Here ](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v2/privatelinks.json) are the v2 types for private link. None of those objects have systemData in them. and I cannot modify those core system types.

Note that system data doesn't go in the property bag. Would something like this work?
```
    "PrivateEndpointConnection": {
      "description": "Private endpoint connection resource",
      "type": "object",
      "properties": {
        "systemData": {
          "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/SystemData"
        }
        "properties" {
          "$ref": "../../../../../common-types/resource-management/v2/privatelinks.json#/definitions/PrivateEndpointConnectionProperties"
        }
      }
    }
```
Then reference in response:

```
        "responses": {
          "200": {
            "description": "Successfully retrieved the connection.",
            "schema": {
              "$ref": "#/definitions/PrivateEndpointConnection"
            }
          },
```

**Comment by walrusmcd** [comment]
@mentat9 thanks for the review !  on the put responses.   i thought put had a couple of responses:   201 (if created) and 200 or 204 (if an existing resource was updated) .  [(rfc here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)) .   this is a funny verb since private link mandates this to be a PUT.   and also mandates that it cannot be done to create the object.   they have another flow for creating the objects .  this PUT here is only valid for updates.   in that case, do you recommend 200 or 204?   i had been using 200's in the case of an update to an existing object.

**Comment by walrusmcd** [comment]
@mentat9 you know what would be awesome.   if systemData is desired for all arm object responses, could v2 of types for /defintions/Resource include it ?  then all objects would get it.   I'm going to try that idea you have there to see if i can somehow "add" system data to a core shared type that doesn't have it.

**Comment by mentat9** [comment]
> @mentat9 thanks for the review ! on the put responses. i thought put had a couple of responses: 201 (if created) and 200 or 204 (if an existing resource was updated) . [(rfc here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)) . this is a funny verb since private link mandates this to be a PUT. and also mandates that it cannot be done to create the object. they have another flow for creating the objects . this PUT here is only valid for updates. in that case, do you recommend 200 or 204? i had been using 200's in the case of an update to an existing object.

ARM requires create to be done by PUT with a 201 status code response. 200 is allowed when PUT updates an existing resource. 204 is only used when DELETE is attempted for a non-existent resource or for PATCH if the resource is not returned in the payload. I haven't heard that private link cannot be created via PUT. How are you creating them?

**Comment by mentat9** [comment]
>           "200": {

This resource is created in another RP, so you are correct to return only 200.

---
In reply to: [833255246](https://github.com/Azure/azure-rest-api-specs/pull/14258#issuecomment-833255246) [](http://example.com/codeflow?ancestors=833255246,833255246)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2021-04-01-preview/desktopvirtualization.json:2615 in d63f2a3. [](commit_id = d63f2a32bc86087076826324aef7a3ccabf2abed, deletion_comment = False)

**Comment by datr93** [comment]
@erich-wang can you pls take a look. This pr is priority!

**Comment by erich-wang** [comment]
@datr93, could you please fix LintDiff error first?

**Comment by walrusmcd** [comment]
@erich-wang i have the final lint errors fixed.  It took some massaging to make systemData work in the (pre)existing shared types.    Private Link v2 shared types didn't expose sharedData , so I worked through some hoops to help it expose shared data.    All ready for sign off.  thank you !

**Comment by walrusmcd** [comment]
hi @erich-wang , just checking on this one.    is there any new feedback?  or can we progress to the next stage towards merging.  thanks !!

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
