### PR TITLE
WebApps - Add BackupName to backup API models

### PR DESCRIPTION
**Pull request by nking-1**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
Context: The type "BackupItem" has a "name" property in addition to the one it inherit from the it's base type "ProxyOnlyResource". This PR re-names the derived type's "name" property to "backupName".

From SDK side, when a type that derive from ARM base type has a property name conflicting with property from the base type, code-generator renames derived type's property. In this case a prefix "BackItem" will be used, so the property name become "BackupItemName". e.g. [Java](https://github.com/Azure/azure-libraries-for-java/blob/4ae923aac0554e4bc3e17d015fcd7073bc91d8f1/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/BackupItemInner.java#L46), [C-Sharp](https://github.com/Azure/azure-sdk-for-net/blob/babc1a6d94e97ecfe0ee7aa2984a05c9c9bbbcb7/src/SDKs/WebSites/Management.Websites/Generated/Models/BackupItem.cs#L116). The changes in this PR is a breaking change, hence generated SDK's version needs to be bumpedup accordingly.


This is breaking change from the REST API side as well (Renaming property name in a stable api-version). hence requesting ARM review here.

**Comment by Nking92** [comment]
We are ok with making a breaking SDK change. We have to make a major version update anyway. This PR was actually intended to make a workaround for other breaking changes, since the "name" property has already been removed from BackupRequest in an earlier PR. I made the same change to BackupItem here so that it will have the same workaround as BackupRequest.

**Comment by anuchandy** [comment]
@Nking92 thanks for providing more info. Could you share the previously merged PR which fixes the same `name` issue in `BackupRequest` model?

**Comment by Nking92** [comment]
Hi @anuchandy, I checked and the `name` property was removed in the new 2018-02-01 API version. Here's that PR: https://github.com/Azure/azure-rest-api-specs/pull/2802. Since it was removed in a new version, it wasn't actually a breaking change.

For my change here where I removed `name` from `BackupItem`, I actually only set that property be ignored from our generated swagger. It still exists and is used by our backend, so any clients of our REST API will continue to work as expected. I think the main concern would be breaking the SDKs, but they are already far overdue for a major version update anyway.

**Comment by anuchandy** [comment]
thanks @Nking92. I see that [BackupRequest::name](https://github.com/Azure/azure-rest-api-specs/blob/e418225e3be1ce960bf4da2d3b7132a1d5b8e166/specification/web/resource-manager/Microsoft.Web/stable/2016-08-01/WebApps.json#L15067) property in previous api-version got removed when the new api-verison [2018-02-01](https://github.com/Azure/azure-rest-api-specs/blob/e418225e3be1ce960bf4da2d3b7132a1d5b8e166/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json#L17209) was introduced.

In this PR we have two changes:
     1. Introducing a new property in `BackupRequest` model with name `backupName`. 
     2. Renaming `BackupItem::name` to `backItem::backupName`
  
@ravbhatnagar can you please take a look from ARM side?

**Comment by Nking92** [comment]
@ravbhatnagar Thanks for the review. Would only adding a new property for `BackupRequest` be ok? I have reverted the change that renames `BackupItem::Name` to `BackupItem::BackupName`.

**Comment by ravbhatnagar** [comment]
@Nking92 - I was referring to that change only in my earlier comment. Take the case where this property was exposed in the current api-version and got set using the portal. And earlier version of the client SDK which is tied to the current api-version GETs the resource, makes some other changes to the properties, and PUTs the resource back. Now since the SDK did not understand this property, it will ignore it on the GET. And so this property wont be present in the request body on the PUT. Now your service may wipe the earlier set value of this property since it was not present in the request. 
This is an unintentional update since the client ignore certain properties. So same SDK version causes behavior change in the same APi. 
Anyway, its your call after this. Not sure how the service handles PUT when some properties are not present in the payload, does it override or ignore.
Signing off from ARM side.

**Comment by anuchandy** [comment]
thank you @ravbhatnagar. @Nking92 let me know if you still want to make this change in the existing api version. As Gaurav pointed this change can cause existing SDK to behave differently than it used to be (of course depending on whether the service overwrite or ignore the value during PUT).

**Comment by Nking92** [comment]
@anuchandy I did some testing and I think we'll be ok. If the new property isn't present in the PUT request, the API will use the old property as expected. The new property does take precedence over the old property when it is present, though.

Signing off with OK to merge

**Comment by panchagnula** [comment]
@anuchandy can you please merge this PR please - we want to get our SDK changes rolling as well & we need this PR to be merged. Thank you.

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
