### PR TITLE
Add stable version 2024-03-01 for Azure SignalR and Azure Web PubSub

### PR DESCRIPTION
**Pull request by bjqian**
The api is the same as 2024-01-01-preview

### CODE REVIEW

**Comment by bjqian** [comment]
Both the SDK breaking changes and ARM breaking changes are caused by switching the common type which is false positive and have been approved in previous PR.

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #22948

**Comment by MaryGao** [comment]
Approved JS breakings considering it is introduced by common types upgrading.

**Comment by msyyc** [comment]
Approved for python since it is caused by upgrade of common types.

**Review by ms-henglu — APPROVED** [review]

**Pull request merged**
