### PR TITLE
Bringing conformance to the Disk version used in root tags.

### PR DESCRIPTION
**Pull request by marstr**
@dashult discovered the discrepancy between the tags `package-2018-06` and `package-2018-06-exclude-gallery`. The difference is causing the modeler to choke on duplicate type definitions for the TypeScript and Node.js generators.

This is related to #3854

---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
The missing examples causing the linter step of CI to fail should have been introduced by @carissasun in PR #3854.

@carissasun, would you like to add those examples and push them to [my branch](https://github.com/marstr/azure-rest-api-specs/tree/diskVerDiscrepancy), or shall I open an issue to track getting them added?

**Comment by lmazuel** [comment]
@marstr That's funny, because if you look at the linter of #3854, it's clean:
https://github.com/Azure/azure-rest-api-specs/runs/17100940

**Comment by marstr** [comment]
> That's funny, because if you look at the linter of #3854, it's clean

It's because the default tag (`package-2018-06-exclude-gallery`) didn't include any references to disk at the updated API Version. :) The linter didn't run over any tag that included that file, so it didn't notice the missing examples.

**Comment by carissasun** [comment]
What's the problem here? I built the project on my local branch and the build didn't complain

**Comment by marstr** [comment]
> @carissasun says:
> What's the problem here? I built the project on my local branch and the build didn't complain

The build wouldn't be a problem, but the linter will complain that we lose test coverage of this API. The linter was only executing over the default tag, `package-2018-06-exclude-gallery`; therefore before this PR it was using the old API Version of disk for testing. When I upgraded the version of disk, the linter discovered that the examples for disk 2018-06-01 are missing and should have been included in #3854.

**Comment by hyonholee** [comment]
@marstr Could you also update the default tag from package-2018-06-exclude-gallery to package-2018-06
?  Now gallery is public preview, and we want to add gallery to official client library.

**Comment by hyonholee** [comment]
@marstr Actually, the default tag is just updated by another PR.  You can ignore my previous comment.  Thanks.

**Comment by marstr** [comment]
I'm going to go ahead and merge this PR. However, the examples should be added at some point.

**Pull request merged**
