### PR TITLE
Disambiguate names for HashiCorp

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
ModelValidation errors are unrelated, and seemingly new as of a couple months ago. /cc @raych1. As for the BreakingChanges validation, I discussed this with @johanste and @JeffreyRichter as non-breaking so long as we transform them back for any autorest generators. I'm following up with the SDK teams as well as Azure CLI and Azure PowerShell as well.

**Review by vcolin7 — APPROVED** [review]
LGTM.

On a slightly separate note: do we only need to disambiguate for enums? I've seen error types in these Key Vault spec files share the same name when generating with Autorest for like `Error`, `KeyVaultError`, and the like. I understand these come from `common.json` but these could become problematic if we made them public models (we currently write a manual convenience layer on top). If we were to ever make the Key Vault libraries to be fully auto-generated we could get around it by using Autorest transformations but I'm not sure if other code generators can do the same.

**Comment by heaths** [comment]
@vcolin7 I would assume it's because the customer is merging all documents together, despite each besides _common.json_ being a separate swagger / OpenAPI v2 document. Thus in those cases, any models defined in _common.json_ would only appear once. Even outside of autorest, any code generators treating each swagger document separately would only define any `$ref`s like the `Error` models once in scope so that scenario works out as well.

For now, we should keep these renames focused on only what's problematic. Eventually when we convert the service definitions to Cadl, each standalone document will be in a separate subdirectory.

**Comment by aristosvo** [comment]
Thanks @heaths et al! Great to have things moving to a working solution, teamwork makes the dream work!!🚀🎉

**Pull request merged**
