### PR TITLE
[acr] update default package tag and PrivateEndpointConnection resource for containerregistry

### PR DESCRIPTION
**Pull request by adewaleo**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by adewaleo** [comment]
@djyou @northtyphoon @zikalino, does this look good to you?

The removed fields are inherited from the proxyresource definition. 

So the only breaking change is that id, name and type are now readonly and that PrivateEndpointConnection inherits from proxyresource for the purpose of typing.

**Comment by adewaleo** [comment]
PR looks good to me, although not sure what is causing this example [error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=320453&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=27).

"[Breaking changes](https://dev.azure.com/azure-sdk/public/_build/results?buildId=320453&view=logs&j=08b5038d-1e84-5877-88da-859df8312b69&t=c1978ecd-fc8a-5291-6d7a-7dd459d8b50f&l=595)" are because PrivateEndpointConnection now inherits from ProxyResource.

**Review by zikalino — APPROVED** [review]

**Pull request merged**
