### PR TITLE
Use azure-sdk-for-net-track2 for validation

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Review by tjprescott — COMMENTED** [review]
Is it expected/intended that this PR is _failing_ azure-sdk-for-net-track2?

**Comment by heaths** [comment]
No. I've got an email out on this and just CC'd you.

**Comment by heaths** [comment]
And since you responded first, I'm going to reassign the other two changes (all in different branches) to you. Congrats. 🙂

**Comment by heaths** [comment]
@lmazuel the second attempt after @ShivangiReja's changes seems to have worked, but I'm not sure why it didn't update the checks: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1519441&view=logs&j=f5934c1f-9ec9-5119-b2dd-43d5040d4468

Could you help merge this?

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
