### PR TITLE
add hybridcompute track2 config

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by zhenglaizhang** [comment]
@00Kai0 fyi, the java sdk gen failure is known issue and fix will be released soon

**Comment by zhenglaizhang** [comment]
@changlong-liu help take a look at the python breaking change?

**Comment by msyyc** [comment]
@zhenglaizhang it's ok for python

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang Zhenglai Zhang FTE it's ok for python

great @msyyc pls help approve the PR to unblock the merging

**Review by msyyc — APPROVED** [review]

**Comment by msyyc** [comment]
> > @zhenglaizhang
> >             
> >             Zhenglai Zhang
> >             FTE Zhenglai Zhang FTE it's ok for python
> 
> great @msyyc Yuchao Yan FTE pls help approve the PR to unblock the merging

done

**Pull request merged**
