### PR TITLE
[Resources] Add expressionEvaluationOptions property to swagger

### PR DESCRIPTION
**Pull request by filizt**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@filizt , is this change already implemented in service side?

**Comment by raych1** [comment]
@Tiano2017 , can you please review this PR?

**Comment by filizt** [comment]
> @filizt , is this change already implemented in service side?

Yes, it's implemented. It's active for at least 6 months now, we're getting the swagger up to date.

**Comment by filizt** [comment]
> @Tiano2017 , can you please review this PR?

Is @Tiano2017 listed as a reviewer? I don't think he reviews swagger PRs anymore. @anthony-c-martin would that be you who would review the PRs?

**Comment by anthony-c-martin** [comment]
> > @Tiano2017 , can you please review this PR?
> 
> Is @Tiano2017 listed as a reviewer? I don't think he reviews swagger PRs anymore. @anthony-c-martin would that be you who would review the PRs?

I think there are multiple reviews needed on each PR:
1. ARM API review board (@Azure/arm-api-review-board).
2. SDK reviewers (@Azure/swagger-specs-pull-request-approvers).
3. Whoever has been listed in [CODEOWNERS](https://github.com/Azure/azure-rest-api-specs/blob/183db615e7e870d12668972c874897f095fe256c/CODEOWNERS#L61) for the directory being modified.

@Tiano2017 is showing up because of (3), meaning you'll still need sign-off from (1) & (2). Not totally sure on the best way to handle CODEOWNERS because the directory is shared among multiple teams with no simple way to break it up. @raych1 any suggestions?

**Comment by raych1** [comment]
> > > @Tiano2017 , can you please review this PR?
> > 
> > 
> > Is @Tiano2017 listed as a reviewer? I don't think he reviews swagger PRs anymore. @anthony-c-martin would that be you who would review the PRs?
> 
> There are multiple reviews needed on each PR:
> 
> 1. ARM API review board (@Azure/arm-api-review-board).
> 2. SDK reviewers (@Azure/swagger-specs-pull-request-approvers).
> 3. Whoever has been listed in [CODEOWNERS](https://github.com/Azure/azure-rest-api-specs/blob/183db615e7e870d12668972c874897f095fe256c/CODEOWNERS#L61) for the directory being modified.
> 
> @Tiano2017 is showing up because of (3), meaning you'll still need sign-off from (1) & (2). Not totally sure on the best way to handle CODEOWNERS because the directory is shared among multiple teams with no simple way to break it up. @raych1 any suggestions?

Yes,  @Tiano2017 @rajshah11 @vivsriaus are displayed as code owner of `resources` folder.  This PR change is to align with the service implementation, so it needs one of the code owner to sign off.

**Review by tjprescott — APPROVED** [review]

**Comment by raych1** [comment]
@filizt , can you please ask one of code owner to review the PR and sign off?

**Review by Tiano2017 — APPROVED** [review]
:shipit:

**Review by raych1 — APPROVED** [review]

**Pull request merged**
