### PR TITLE
Changes for 2024-12-15-preview

### PR DESCRIPTION
**Pull request by rohkuma-microsoft**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by mentat9** [comment]
@rohkuma-microsoft - Please select and fill out the appropriate PR template above.

**Comment by rohkuma-microsoft** [comment]
> @rohkuma-microsoft - Please select and fill out the appropriate PR template above.

I click on the link to open PR for a Control Plane (ARM) API above, but nothing happens.

**Comment by rohkuma-microsoft** [comment]
> PR for a Control Plane (ARM) API

HI, this PR is for "PR for a Control Plane (ARM) API". Cannot select the template above for some reason. Hence commenting it here (This was suggested to me in API review office hours)

**Comment by MUHAMMADIHSANALIKAP** [comment]
MUHAMMAD IHSAN ALI.
image.ihsanalikapahi.io.MUHAMMADIHSAN.MUHAMMAD.
[DAYONE_JOURNAL]().Pdf Downloads-1.Downloads-2.Documents-28!/IHSAN KAPAHI.IO@GROUPS.HAKIMBIBI67A.COM.1.2.3.4.5.6.7.8.9.10.11.12.13.#CODE.

**Review by Kishp01 — APPROVED** [review]

**Comment by Kishp01** [comment]
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```

**Comment by a-hamad** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by Kishp01 — APPROVED** [review]

**Comment by Kishp01** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Pull request merged**
