### PR TITLE
DNS Resolver Release 2023-07-01-Preview with new DNS Security Policy feature

### PR DESCRIPTION
**Pull request by jamesvoongms**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

The PR adds a new version for the DnsResolver API Spec, most notably adding a new json containing an upcoming feature for DNS Security Policy. It also changes the existing API spec to use common types v5 from v2.

Private-Repository PRs:
https://github.com/Azure/azure-rest-api-specs-pr/pull/14085
https://github.com/Azure/azure-rest-api-specs-pr/pull/15020
https://github.com/Azure/azure-rest-api-specs-pr/pull/15737
https://github.com/Azure/azure-rest-api-specs-pr/pull/16191
https://github.com/Azure/azure-rest-api-specs-pr/pull/19685 (Currently in review)

  - [ ] New resource provider.
  - [X] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [X] Other, please clarify:
    - Additional of new API spec for new feature DNS Security Policy that will reside alongside our existing API DNS resolver

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [X] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [X] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by jamesvoongms** [comment]
Hi team,

I have attached the private-repo PRs that have been signed off by ARM. The one remaining PR is currently causing a breaking change failure to be flagged due to changing from v2 to v5 of the common types usage. However looking at the common types, it looks like the only difference is the additional of the "format" key.

eg.
The new version has a different format 'arm-id' than the previous one ''.
New: [common-types/resource-management/v5/types.json#L14:9](https://github.com/Azure/azure-rest-api-specs-pr/blob/f0dbd37a9a06578ba6e73773816a11fc5331bdaf/specification/common-types/resource-management/v5/types.json#L14:9)
definitions.AzureEntityResource.properties.id
Old: [common-types/resource-management/v2/types.json#L14:9](https://github.com/Azure/azure-rest-api-specs-pr/blob/main/specification/common-types/resource-management/v2/types.json#L14:9)

**Comment by ms-bogdan-rotaru** [comment]
Your branch is out-of-date with base branch, please merge with base branch before requesting merge.

**Comment by jamesvoongms** [comment]
@ms-bogdan-rotaru , I have now merged in master, can you help approve?

**Review by jotrivet — APPROVED** [review]
Approving import of previously reviewed changes in https://github.com/Azure/azure-rest-api-specs-pr/tree/release-dnsresolver-Microsoft.Network-2023-07-01-preview to public

**Pull request merged**
