### PR TITLE
[Hub Generated] Add new api version 2023-05-01 for Microsoft.App

### PR DESCRIPTION
**Pull request by Juliehzl**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by Juliehzl** [comment]
This version is based on 2023-04-01-preview without any other change

**Comment by Juliehzl** [comment]
@JeffreyRichter could you help review the PR? this is a new api version which is same with 2023-04-01-preview

**Comment by visingla-ms** [comment]
Please fix the Avocado errors.

**Comment by kazrael2119** [comment]
this js breaking is not caused by this pr

**Comment by Juliehzl** [comment]
> Please fix the Avocado errors.

@visingla-ms the files I changed is for api version 2023-05-01, but the avocado error is for [Microsoft.App/stable/2022-10-01/ConnectedEnvironments.json](https://github.com/Azure/azure-rest-api-specs/blob/a30bc7a38a0cfdd514477ca0eb803d463f670a73/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ConnectedEnvironments.json), which I do not have any change in this PR. And it is confused for error reported. Could you guide me how to fix?

**Review by rkmanda — APPROVED** [review]

**Review by rkmanda — APPROVED** [review]

**Comment by konrad-jamrozik** [comment]
> > Please fix the Avocado errors.
> 
> @visingla-ms Vikas Singla FTE the files I changed is for api version 2023-05-01, but the avocado error is for [Microsoft.App/stable/2022-10-01/ConnectedEnvironments.json](https://github.com/Azure/azure-rest-api-specs/blob/a30bc7a38a0cfdd514477ca0eb803d463f670a73/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ConnectedEnvironments.json), which I do not have any change in this PR. And it is confused for error reported. Could you help check if pipeline report is correct and guide me how to fix?

Unfortunately, the Avocado error is correct.

The problem is as follows:

Observe that the API path:

`/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.App/connectedEnvironments/{connectedEnvironmentName}`

is present in [stable/2022-10-01/ConnectedEnvironments.json](https://github.com/Azure/azure-rest-api-specs/blob/a30bc7a38a0cfdd514477ca0eb803d463f670a73/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ConnectedEnvironments.json#L100C5-L100C146)

Hence the default API version, 2023-05-01, also must have this API path. The current API version has this path, in [stable/2023-05-01/ConnectedEnvironments.json](https://github.com/Azure/azure-rest-api-specs/blob/a30bc7a38a0cfdd514477ca0eb803d463f670a73/specification/app/resource-manager/Microsoft.App/stable/2023-05-01/ConnectedEnvironments.json#L100C6-L100C145)

`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.App/connectedEnvironments/{connectedEnvironmentName}`

These paths are not the same. The difference is in capitalization: the old path has `resourcegroups` while the new path has `resourceGroups`.

**Pull request merged**
