### PR TITLE
Fix miss spelling property name and case sensitive

### PR DESCRIPTION
**Pull request by LingyunSu**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by LingyunSu** [comment]
@bganapa @JesusAlvarezTorres

**Review by bganapa — APPROVED** [review]

**Comment by MyronFanQiu** [comment]
@LingyunSu Hi. Because you do such change in the preview version, it's fine. Could you revolve the conflicts first?

**Review by bganapa — APPROVED** [review]

**Comment by bganapa** [comment]
@MyronFanQiu Resolved the conflicts. It is actually a bug fix that we must take. Thanks!

**Comment by MyronFanQiu** [comment]
@LingyunSu Hello. If you make sure that you want such change, please add suppression in the readme.file to fix LintDiff. For the Spellcheck, please add these words into https://github.com/Azure/azure-rest-api-specs/blob/master/custom-words.txt. Please double check the change.

**Comment by MyronFanQiu** [comment]
Such change may cause problems for SDK generation. externalDNSIPAddress01 will be external_d_n_s_i_p_address01 in some SDKs.

**Comment by MyronFanQiu** [comment]
Can you share the context about this PR?

**Comment by bganapa** [comment]
@MyronFanQiu our admin RP response for this api comes with the json format externalDNSIPAddress01, so we are in need of matching that in swagger without ignoring the case.
We ship only azure powershell/.Net SD for these azure stack administrator APIs. We do not foresee any need of shipping any other SDKs for these AZURESTACK admin specific APIs. Note that these APIs don't exist in azure. It seems like the guidance is the RP response should have got externalDnsIpAddress01 instead of externalDNSIPAddress01. Is there any doc on this guidance?(I dont see it here https://github.com/Azure/azure-resource-manager-rpc)  . This change is needed for our ignite release and we are out of time to make the change at the RP code. I suggest lets merge this one to fix the powershell issue and we will track an issue internally to change the RP code if needed. Hope that makes sense

**Comment by MyronFanQiu** [comment]
@bganapa Hello. If you make sure that you want such change, please add suppression in the readme.file to fix LintDiff. For the Spellcheck, please add these words into https://github.com/Azure/azure-rest-api-specs/blob/master/custom-words.txt. 

Fix CI so that I can merge it.

**Comment by LingyunSu** [comment]
@bganapa @MyronFanQiu new custom words added.

**Comment by MyronFanQiu** [comment]
@LingyunSu please add suppression in the readme.file to fix LintDiff.

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu our admin RP response for this api comes with the json format externalDNSIPAddress01, so we are in need of matching that in swagger without ignoring the case.
> We ship only azure powershell/.Net SD for these azure stack administrator APIs. We do not foresee any need of shipping any other SDKs for these AZURESTACK admin specific APIs. Note that these APIs don't exist in azure. It seems like the guidance is the RP response should have got externalDnsIpAddress01 instead of externalDNSIPAddress01. Is there any doc on this guidance?(I dont see it here https://github.com/Azure/azure-resource-manager-rpc) . This change is needed for our ignite release and we are out of time to make the change at the RP code. I suggest lets merge this one to fix the powershell issue and we will track an issue internally to change the RP code if needed. Hope that makes sense

@yungezz Service team want to change two names for the case sensitive. Could you please confirm this change?  This change is needed for the ignite release.

**Comment by yungezz** [comment]
hi @MyronFanQiu it make sense. I'm ok to merge it.

**Comment by MyronFanQiu** [comment]
@LingyunSu Hello. Add suppression in readme.md for LintDiff and I can merge it~

**Comment by LingyunSu** [comment]
@MyronFanQiu @vikasnav @JesusAlvarezTorres @bganapa after many tries, finally, I am there. :)

**Comment by MyronFanQiu** [comment]
@LingyunSu Thanks very much!

**Pull request merged**
