### PR TITLE
new api version 20180101 and adding two fields in appgw

### PR DESCRIPTION
**Pull request by azhao155**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by azhao155** [comment]
@veronicagg Please take this pr

**Review by veronicagg — CHANGES_REQUESTED** [review]
PR looks good to me, it's based on commits that have been reviewed in feature branch, plus an additional one that just changes some formatting. 
Need to wait on confirmation from Network team for approval of a new api-version in master.
@DeepakRajendranMsft

**Comment by veronicagg** [comment]
Approving PR, please do not merge until Networking team confirms they'd like to see this in master.

**Review by veronicagg — APPROVED** [review]

**Comment by marstr** [comment]
There were some merge conflicts before the change in base branch. `current` and `master` are advancing together now, and as per the updated policy, I've retargeted this PR at the `master` branch.

**Review by marstr — CHANGES_REQUESTED** [review]
Before this PR is merged, it must be refactored to meet the new Repo requirement of having each API version folder being placed in either a `stable` or `preview` directory. Keep in mind, any relative paths must also be updated.

**Comment by marstr** [comment]
More information on the refactoring I'm referring to can be found here: https://github.com/Azure/azure-rest-api-specs/wiki/December-2017-Refactoring

**Comment by marstr** [comment]
Howdy folks, I'm taking a look now. I have a couple of outstanding questions yet before this is ready to be merged:
1. This PR seems to be causing some breaking changes in the older API versions supported by the Python SDK, as seen [here](https://github.com/Azure/azure-sdk-for-python/commit/60fc6dfef3b3561ac5bfc4135cb073b78dec67df). I'll need to sync up with @lmazuel to understand if this is really due to this PR, or if these are expected changes caused by the generator. (I suspect it is okay, because I don't see similar issues in the Go SDK.) Expect another reply within the next few hours on this front.
1. I'm surprised that we're managing the `2017-11-01` release tags with this PR. Is there a dependency between the two that makes this necessary, or is it just being opportunistic? Either way is fine, I just want to make sure I understand.

**Comment by azhao155** [comment]
@marstr 
1. I saw it has passed two checks, and able to merge, so i will wait for your reply.
2. I try to merge everything latest from master:latest into my branch and thus got this 2017-11 tag, i think it should be fine.

**Review by DeepakRajendranMsft — APPROVED** [review]

**Review by marstr — APPROVED** [review]
> @marstr says:
This PR seems to be causing some breaking changes in the older API versions supported by the Python SDK, as seen here. I'll need to sync up with @lmazuel to understand if this is really due to this PR, or if these are expected changes caused by the generator. (I suspect it is okay, because I don't see similar issues in the Go SDK.) Expect another reply within the next few hours on this front.

@lmazuel is not available today. However, @annatisch helped to track down the cause of Python changes that made me hesitant. We determined that the changes are introduced by other PRs, which were already merged in. For that reason, with the approval of @DeepakRajendranMsft, I'm willing to certify that I cannot identify new issues since @veronicagg signed off.

**Comment by marstr** [comment]
Offline, I've reached out to @DeepakRajendranMsft, and he and the rest of the networking team are ready for these changes to be incorporated into `master`.

**Pull request merged**
