### PR TITLE
[DO NOT MERGE] httpCorrelationProtocol property was added to diagnostic entity

### PR DESCRIPTION
**Pull request by promoisha**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@promoisha Hi. This PR add new property into a stable version. Besides, the field is required. So we should firstly wait for ARM feedback.
https://github.com/Azure/azure-rest-api-specs/blob/0737a4885a5e2e367458c99e4fa6c079fca7b35e/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimapis.json#L2668-L2672

**Comment by solankisamir** [comment]
> @promoisha Hi. This PR add new property into a stable version. Besides, the field is required. So we should firstly wait for ARM feedback.
> https://github.com/Azure/azure-rest-api-specs/blob/0737a4885a5e2e367458c99e4fa6c079fca7b35e/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimapis.json#L2668-L2672

@MyronFanQiu I don't see this property as being required in the Diagnostic entity contract. The only required property is `loggerid`

**Comment by MyronFanQiu** [comment]
> > @promoisha Hi. This PR add new property into a stable version. Besides, the field is required. So we should firstly wait for ARM feedback.
> > https://github.com/Azure/azure-rest-api-specs/blob/0737a4885a5e2e367458c99e4fa6c079fca7b35e/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimapis.json#L2668-L2672
> 
> @MyronFanQiu I don't see this property as being required in the Diagnostic entity contract. The only required property is `loggerid`

@solankisamir Hello. My mistake. What I want to say is that the property `DiagnosticContract` is required. This PR add a new property into a required field in a stable version. I understand `httpCorrelationProtocol` is optional. This PR looks good to me. However, recently we are under transition process, any property or API change in the stable version should involve arm for review.

**Comment by promoisha** [comment]
@MyronFanQiu who should I ping to expedite approval?

**Comment by MyronFanQiu** [comment]
@promoisha Let me try. 😃 @sanjaiganesh Hello, could you please review this PR?

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by promoisha** [comment]
@sanjaiganesh Friendly ping on looking into this PR.

**Comment by promoisha** [comment]
@Azure/arm-api-review-board could someone take a look at the PR? Thanks!

**Review by ryansbenson — COMMENTED** [review]
This constitutes a breaking change and requires a new api version. 

Take a look at the section for 'New property added to response'
https://microsoft.sharepoint.com/:w:/t/azureresourcemanagerteam/EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw?rtime=FuqbLiIH10g

**Comment by MyronFanQiu** [comment]
@promoisha Hi. Are you creating a new api-version? How to deal with this PR?

**Comment by MyronFanQiu** [comment]
@promoisha Hello. Any update for this PR?

**Comment by yungezz** [comment]
hi @promoisha  are you still on this PR? Is it ok to close the PR since no update over month? Pls create new PR or reopen when you're ready for reviewing and merging

**Comment by MyronFanQiu** [comment]
@promoisha Hello. Since this PR has not been updated for more than one month. I will close this PR first. If you need this PR in the future, please feel free to reopen it and ping me.

**Pull request closed without merging**
