### PR TITLE
[Hub Generated] Review request for Microsoft.ApiManagement to add version preview/2018-06-01-preview

### PR DESCRIPTION
**Pull request by solankisamir**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/solankisamir/azure-rest-api-specs/fix_cachefilter...master/).

Fix for https://github.com/Azure/azure-rest-api-specs/issues/6713

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by solankisamir** [comment]
@MyronFanQiu fyi

**Comment by MyronFanQiu** [comment]
@solankisamir Thanks!

**Comment by NullMDR** [comment]
@openapi sdkautomation rebuild

**Comment by MyronFanQiu** [comment]
@openapi sdkautomation rebuild

**Comment by daschult** [comment]
@openapibot sdkautomation rebuild

**Comment by daschult** [comment]
@openapibot sdkautomation rebuild

**Comment by daschult** [comment]
@openapibot sdkautomation rebuild

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
