### PR TITLE
[Hub Generated] Review request for Microsoft.Workloads to add version preview/2022-11-01-preview

### PR DESCRIPTION
**Pull request by gargankit-microsoft**
Changes for v2022-11-01-preview. ***All individual PRs have ARM review and Breaking change signoffs before getting merged in Private repo***. So, re-review should not be required.

***Breaking change Explanation for removed properties***: [See this Comment](https://github.com/Azure/azure-rest-api-specs/pull/22207#issuecomment-1385119342)
**Avocado Explanation**: [See this Comment](https://github.com/Azure/azure-rest-api-specs/pull/22207#issuecomment-1385125991)

### Common
- added security defination to commonTypes.json (https://github.com/Azure/azure-rest-api-specs-pr/pull/8858)

### SapVirtualInstance
- Added a new supported payload for sapVirtualInstance/PUT API, for detecting the SAP Software Installation (https://github.com/Azure/azure-rest-api-specs-pr/pull/8991)
- Added support for SAP Trans Fileshare configs (https://github.com/Azure/azure-rest-api-specs-pr/pull/9200)
- Added SAP SID as property for HANA provider (https://github.com/Azure/azure-rest-api-specs-pr/pull/9462)
- Added support for LB and storage details changes (https://github.com/Azure/azure-rest-api-specs-pr/pull/9464)
- Added DiskConfiguration Optional Property (https://github.com/Azure/azure-rest-api-specs-pr/pull/9874)
- Instance level start stop support for ASCS and App Instance (https://github.com/Azure/azure-rest-api-specs-pr/pull/9105)
- Instance level start stop support for DB Instance (https://github.com/Azure/azure-rest-api-specs-pr/pull/9608)
- Added endpoint to get the details about the last execution of a particular type of operation (https://github.com/Azure/azure-rest-api-specs-pr/pull/9570)
- Added vmDetails array to SapApplicationServerProperties (https://github.com/Azure/azure-rest-api-specs-pr/pull/9873)
- Modify Output Structure to add disk customization (https://github.com/Azure/azure-rest-api-specs-pr/pull/10381)
- Added resource name customization support (https://github.com/Azure/azure-rest-api-specs-pr/pull/10550)

### Monitors
- Added sapSid property in os, hana providers (https://github.com/Azure/azure-rest-api-specs-pr/pull/9085)
- Added support for secure communication (https://github.com/Azure/azure-rest-api-specs-pr/pull/9081)
- Adding new Endpoint for Storing SPOG Config (https://github.com/Azure/azure-rest-api-specs-pr/pull/9366)

### PhpWorkloads
- Removed PHP Resource Type files and swagger references (https://github.com/Azure/azure-rest-api-specs-pr/pull/8858)

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/gargankit-microsoft-workloads-Microsoft.Workloads-2022-11-01-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. ***Early Feb 2023***
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. ***Early Feb 2023***
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here. ***Want to refresh***

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by gargankit-microsoft** [comment]
<h1 style='margin:0in;font-family:Calibri;font-size:16.0pt;color:#1E4E79'
lang=en-US>Breaking change Explanation (Removed Properties)</h1>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt' lang=en-US>&nbsp;</p>

<div style='direction:ltr'>



Message | Original PR | Change | Handled in service
-- | -- | -- | --
The new version is   missing a property found in the old version. Was 'diskConfigurations' renamed   or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2781:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2252:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from Array to a Disctionary, renamed to volumeConfigurations | Y
The new version is   missing a property found in the old version. Was 'virtualMachineId' renamed   or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L3939:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L3155:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/9873 | Moved   to vmDetails[].virtualMachineId | Y
The new version is   missing a property found in the old version. Was 'storageDetails' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L3939:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L3155:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/9873 | Moved   to vmDetails[].storageDetails | Y
The new version is   missing a property found in the old version. Was 'hardStop' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L3552:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2792:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/9105 | Original   param was unused in service, removed it and replaces with another param named   'softStopTimeoutSeconds'. | Y
The new version is   missing a property found in the old version. Was 'volume' renamed or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}] | Y
The new version is   missing a property found in the old version. Was 'diskType' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].diskTier | Y
The new version is   missing a property found in the old version. Was 'diskCount' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].count | Y
The new version is   missing a property found in the old version. Was 'diskSizeGB' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].sizeGB | Y
The new version is   missing a property found in the old version. Was 'diskIopsReadWrite' renamed   or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].iopsReadWrite | Y
The new version is   missing a property found in the old version. Was 'diskMBpsReadWrite' renamed   or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].mbpsReadWrite | Y
The new version is   missing a property found in the old version. Was 'diskStorageType' renamed or   removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/SAPVirtualInstance.json#L2763:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/SAPVirtualInstance.json#L2214:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/10381 | Restructured   from diskConfigurations[].volume to volumeConfigurations[{KEY}].sku.name | Y
The new version is   missing a property found in the old version. Was 'dbSslCertificateUri'   renamed or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/monitors.json#L1168:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/monitors.json#L941:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/9081 | Renamed   to sslCertificateUri | Y
The new version is   missing a property found in the old version. Was 'sapSslCertificateUri'   renamed or removed?   New: Microsoft.Workloads/preview/2022-11-01-preview/monitors.json#L1224:7   Old: Microsoft.Workloads/preview/2021-12-01-preview/monitors.json#L997:7 | https://github.com/Azure/azure-rest-api-specs-pr/pull/9081 | Renamed   to sslCertificateUri | Y

**Comment by gargankit-microsoft** [comment]
### Avocado Explanation


|     Message                                                                                                                                                                                                                                                                                                                                                                                                          |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|     The   default tag should contain all APIs. The API path /subscriptions/{}/providers/Microsoft.Workloads/phpWorkloads is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/phpWorkloads.json                                                    |
|     The   default tag should contain all APIs. The API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.Workloads/phpWorkloads is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/phpWorkloads.json                                  |
|     The   default tag should contain all APIs. The API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.Workloads/phpWorkloads/{} is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/phpWorkloads.json                               |
|     The   default tag should contain all APIs. The API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.Workloads/phpWorkloads/{}/wordpressInstances is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/phpWorkloads.json            |
|     The   default tag should contain all APIs. The API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.Workloads/phpWorkloads/{}/wordpressInstances/default is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/phpWorkloads.json    |
|     The   default tag should contain all APIs. The API path /subscriptions/{}/providers/Microsoft.Workloads/skus is not in the default tag. Please   make sure the missing API swaggers are in the default tag.     readme: specification/workloads/resource-manager/readme.md     json: Microsoft.Workloads/preview/2021-12-01-preview/skus.json                                                                    |

**Original PR**: https://github.com/Azure/azure-rest-api-specs-pr/pull/8858
**Change**: This RP had 3 RTs that have different release cycles. While 2 RTs are planning for 2nd Public preview release in Feb 23 and GA in March 23, 3rd RP (PhpWorkloads) is yet to announce even Public preview. Because of this, it'll be incorrect to take PhpWorkloads to second public preview version/GA along with other 2.To overcome this, We are working with RPaaS to support alternate folder structure as mentioned in [Spec Folder Structure for Service Group](https://github.com/Azure/azure-rest-api-specs#folder-structure-for-service-group) in feature request [Feature 15314796: Support for RT level swagger structure - Boards (azure.com)](https://dev.azure.com/msazure/One/_workitems/edit/15314796) so that all RTs can have separate release cycles. Till then, we must remove PhpWorkloads related swagger changes from other 2 RTs further releases.

**Comment by raych1** [comment]
@gargankit-microsoft , the previous PR targeting RPSaaSMaster branch doesn't have the breaking change review approval. Please go thru the review process to get approval.

**Comment by gargankit-microsoft** [comment]
> @gargankit-microsoft , the previous PR targeting RPSaaSMaster branch doesn't have the breaking change review approval. Please go thru the review process to get approval.

https://github.com/Azure/azure-rest-api-specs-pr/pull/8858 has ARM approvals, I have added PRs with respective breaking change approvals in [this comment](https://github.com/Azure/azure-rest-api-specs/pull/22207#issuecomment-1385119342) with individual explanation of changes

**Comment by raych1** [comment]
> > @gargankit-microsoft , the previous PR targeting RPSaaSMaster branch doesn't have the breaking change review approval. Please go thru the review process to get approval.
> 
> [Azure/azure-rest-api-specs-pr#8858](https://github.com/Azure/azure-rest-api-specs-pr/pull/8858) has ARM approvals, I have added PRs with respective breaking change approvals in [this comment](https://github.com/Azure/azure-rest-api-specs/pull/22207#issuecomment-1385119342) with individual explanation of changes

I checked some PRs in that comment, none of them got `approved-breakingchange` label. The reason is those PRs didn't get labelled with `breakingchangereivewrequired`.

**Comment by gargankit-microsoft** [comment]
> > > @gargankit-microsoft , the previous PR targeting RPSaaSMaster branch doesn't have the breaking change review approval. Please go thru the review process to get approval.
> > 
> > 
> > [Azure/azure-rest-api-specs-pr#8858](https://github.com/Azure/azure-rest-api-specs-pr/pull/8858) has ARM approvals, I have added PRs with respective breaking change approvals in [this comment](https://github.com/Azure/azure-rest-api-specs/pull/22207#issuecomment-1385119342) with individual explanation of changes
> 
> I checked some PRs in that comment, none of them got `approved-breakingchange` label. The reason is those PRs didn't get labelled with `breakingchangereivewrequired`.

Here are the PRs tagged with `approved-breakingchange`
- https://github.com/Azure/azure-rest-api-specs-pr/pull/9366
- https://github.com/Azure/azure-rest-api-specs-pr/pull/9081
- https://github.com/Azure/azure-rest-api-specs-pr/pull/10550

Below got approvals for breaking change for Python and JS SDK
- https://github.com/Azure/azure-rest-api-specs-pr/pull/9608

**Comment by raych1** [comment]
Let's wait for ARM approval.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
