### PR TITLE
fix to demonstrate codeflow.

### PR DESCRIPTION
**Pull request by erickson-doug**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 
### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).
### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@erickson-doug__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (douge). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
please create your own fork and send PRs from your fork to the master branch of this repo.

**Comment by erickson-doug** [comment]
>         "description": "Updates the current state of the specified Analysis Services server",

Fix this Doug

---
Refers to: arm-asazure/2016-05-16/swagger/asazure.json:155 in 364cc0e. [](commit_id = 364cc0ee66ebc694c088b06b10eae260656c3282, deletion_comment = False)

**Comment by erickson-doug** [comment]
>             "description": "Name of the Analysis Services server"

Please make sure ALL of your descriptions have a closing period, otherwise, it will look poor on docs.microsoft.com!

---
Refers to: arm-asazure/2016-05-16/swagger/asazure.json:131 in 364cc0e. [](commit_id = 364cc0ee66ebc694c088b06b10eae260656c3282, deletion_comment = False)

**Pull request closed without merging**
