### PR TITLE
Microsoft.OperationalInsights: Typo, upper case and other minor corrections.

### PR DESCRIPTION
**Pull request by dulikvor**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by Dudi119** [comment]
@MyronFanQiu How i can over come the breaking changes stuff, property was removed with intention.

**Comment by Dudi119** [comment]
hi @MyronFanQiu, how i can overcome the "breaking changes" issue:
message: "The new version is missing a property found in the old version. Was 'dataSourceType' renamed or removed?",

the property was removed with intention, it shouldn't be with in the request content in the context of Linked Storage Accounts upsert operation.

**Comment by MyronFanQiu** [comment]
@Dudi119 Can you share the context with us? You just want to remove the data source type since it's already provided through another parameter. Is it correct? I think using a special `create` model for put method is not best practice. The response should be same with the input.

**Comment by MyronFanQiu** [comment]
If you don't need to send data source type, you can mark it `read_only`

**Comment by Dudi119** [comment]
Just to comment - there are no users to this feature, its still under integration, the official document is not even visible to customers.

**Review by mmyyrroonn — APPROVED** [review]

**Comment by MyronFanQiu** [comment]
> Just to comment - there are no users to this feature, its still under integration, the official document is not even visible to customers.

Hi @akning-ms. This field is redundant since there is a separate parameter to set it. And service team confirm that no users are using it. So it's not a real breaking changes. Could you please help force merge this one?

**Pull request merged**
