### PR TITLE
add spec for waf global options

### PR DESCRIPTION
**Pull request by azhao155**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by azhao155** [comment]
Please check maxRequestBodySize and RequestBodyCheck in the applicationGateway.json

**Review by veronicagg — CHANGES_REQUESTED** [review]
@azhao155 could you provide a bit more context on the PR? 
I see that it's adding a new API version, and probably copying most files from the previous, could you please follow https://github.com/Azure/azure-rest-api-specs/blob/current/.github/CONTRIBUTING.md#filenames-and-folder-structure making separate commits, one with the existing content and next with the changes? this will help with the review. 
Is the work expected to be completed in this PR, or will you have more people contributing to it? (asking in case you need a branch to work on them)

**Comment by veronicagg** [comment]
@azhao155 have the changes been reviewed by ARM team already? are the changes already deployed to ARM?
@ravbhatnagar head-up on changes needing review for this PR.

**Comment by veronicagg** [comment]
Please sync with folks on your team who we've worked with before @DeepakRajendranMsft @murilogr @joannakleong @dedhar 
Since this is a new api-version being created, please let us know if you need a branch to work on the changes for the full version. 
When is this api-version with all the changes expected to be in production?

**Comment by ravbhatnagar** [comment]
This is hard to review in this state as I cant identify what has changed. please make separate commits as pointed above.

**Pull request closed without merging**
