### PR TITLE
Cognitive Services 2022-03-01

### PR DESCRIPTION
**Pull request by yangyuan**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
March 2nd
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
March 2nd
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by yangyuan** [comment]
@xiaoxuqi-ms 

Curently the pipeline detected breaking change:

❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.

I wonder if this is false alarm.

What really happen is:
We are adding a new dynamicThrottlingEnabled property to CallRateLimit. Which is not readonly.
So we removed readonly from CallRateLimit and apply readonly to all other properties in CallRateLimit.

**Comment by jorgecotillo** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CognitiveServices/accounts/{accountName}/models": {

How are models created? I assume these are proxy resources - meaning, your RP generates them? If that's the case your response needs to follow proxy definition see here: [https://github.com/Azure/azure-rest-api-specs/blob/bb4175d29020cfff55f1d9087c2a5a89765067dc/specification/common-types/resource-management/v2/types.json#L85](https://github.com/Azure/azure-rest-api-specs/blob/bb4175d29020cfff55f1d9087c2a5a89765067dc/specification/common-types/resource-management/v2/types.json#L85) and you also need to model a single GET. An example of this API can be found here: [https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274](https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274) notice /logs and /log/default (singleton).

---
Refers to: specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2022-03-01/cognitiveservices.json:670 in a894a33. [](commit_id = a894a331491839aca2d9c597b537171987bda704, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>     "AccountModel": {

since this seems to be a proxy resource you are missing: id, name and type properties.

---
Refers to: specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2022-03-01/cognitiveservices.json:3014 in a894a33. [](commit_id = a894a331491839aca2d9c597b537171987bda704, deletion_comment = False)

**Comment by xiaomin-ms** [comment]
> 



> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CognitiveServices/accounts/{accountName}/models": {
> > ```
> 
> How are models created? I assume these are proxy resources - meaning, your RP generates them? If that's the case your response needs to follow proxy definition see here:
> 
> https://github.com/Azure/azure-rest-api-specs/blob/bb4175d29020cfff55f1d9087c2a5a89765067dc/specification/common-types/resource-management/v2/types.json#L85
> 
> and you also need to model a single GET. An example of this API can be found here:
> https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274
> 
> notice /logs and /log/default (singleton).
> Refers to: specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2022-03-01/cognitiveservices.json:670 in [a894a33](https://github.com/Azure/azure-rest-api-specs/commit/a894a331491839aca2d9c597b537171987bda704). [](commit_id = [a894a33](https://github.com/Azure/azure-rest-api-specs/commit/a894a331491839aca2d9c597b537171987bda704), deletion_comment = False)

Models are not created from control plane. I think this is very like the SKUS, I don't think current SKUs API for all RP is inherited from Proxy definition.

**Comment by jorgecotillo** [comment]
ARM has the concept of proxy and tracked resources, returning 'models' as non-ARM resource is not a common pattern.

**Comment by j5lim** [comment]
> > ARM has the concept of proxy and tracked resources, returning 'models' as non-ARM resource is not a common pattern.
> 
> Hi @[jorgecotillo](https://github.com/jorgecotillo)
> 
> As I explained in email, model is not designed to be a proxy resource. It's some kind of service level metadata, like Sku.
> 
> The scenario is very similar with `commitmentTiers`, which is also not a proxy resource. Similar to commitmentTiers, models doesn't have any direct affiliation with Account. In future we plan to enable location based list models operation.
> 
> It doesn't make much sense to make it a proxy resource under Account. In fact it's not compatible to be a proxy resource:
> 
> * Just like Sku, name in model does not ensure uniqueness. Models can have same name with different versions.
> 
> I understand that this might not be a common ARM pattern, but considering the fact we already have similar design exists. Is it possible that you approve this?

I'm okay with returning models as metadata, but if it does not have any affiliation with accounts, can you move it to the top level (e.g. .../providers/Microsoft.CognitiveServices/accountModels)?

**Comment by yangyuan** [comment]
We understand that we can have a subscription level API. In fact we were planning to include a subscription location based API. But time is not right, we decided to release that in later versions.

Just like Skus APIs. The models APIs under account will returns models available for this account. Also custom models added from data plane will be added in addition to system models, so we do need this account level list models to be exists.

**Review by j5lim — APPROVED** [review]
Approved from ARM side with suggestions.

**Comment by xiaoxuqi-ms** [comment]
Hi @ArcturusZhang , could you help to review this PR?

**Review by xiaoxuqi-ms — APPROVED** [review]

**Pull request merged**
