### PR TITLE
[Hub Generated] Review request for Microsoft.Billing EA Auth to version preview/2019-10-01-preview

### PR DESCRIPTION
**Pull request by msft-adrianma**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/msft-adrianma/azure-rest-api-specs/adrianma-2019-Ea-Auth...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by wilcobmsft — APPROVED** [review]

**Comment by chiragg4u** [comment]
There are breaking changes, Please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by chiragg4u** [comment]
Please go through the checklist added as part of the review and mark them completed.

**Comment by chiragg4u** [comment]
Reviewed the changes it looks ok to me.

Signing off based on Adrian Hall's review.

**Review by chiragg4u — APPROVED** [review]
:shipit:

**Comment by msft-adrianma** [comment]
@xccc-msft  can you please merge this PR.

**Comment by xccc-msft** [comment]
@msft-adrianma For now, I cannot merge for two reasons:
- This PR is to add new version, we need ARM review and sign off
- The merge button is disabled as CI fails

**Comment by msft-adrianma** [comment]
@xccc-msft  , I already have ARM review signoff from @chiragg4u as these are evolutionary changes and not breaking.
What do we need to do to get CI to pass given that arm has signed off on the changes.

**Comment by xccc-msft** [comment]
@chiragg4u Can you please update the label if you already sign off from ARM end? Thanks.
@msft-adrianma You may check the `Details` bottom for why they are failing.

**Comment by msft-adrianma** [comment]
@xccc-msft  the check for breaking change is failing. We discussed the changes with Arm review team, and here is the response below. What needs to be done to bypass the checks?
Output from conversation:

Because the PUT operation (starting at line 4769) is a NET NEW operation, and the input model is also NET NEW content, this is an EVOLUTIONARY change.

Evolutionary changes are allowed in preview versions without a version bump and no user concerns.  

Recommendation is that the NEXT preview version conform to the preview versioning guidelines (add a .N to the end) if required.

Based on this description, change is APPROVED.

**Comment by xccc-msft** [comment]
@msft-adrianma The failures come from `BreakingChange` and `LintDiff`. We might need help from @akning-ms.

**Comment by msft-adrianma** [comment]
@akning-ms  can you advise on how we can proceed with the merge. We got approval for the changes from the arm team for the preview apis. I dont understand the lint errors. I see the pre-existing usage for next link already in the json.

**Comment by akning-ms** [comment]
@msft-adrianma , Yes, you may need to fix 9 Lintdiff failure as below :
R2025 - NextLinkPropertyMustExist
The property 'nextLink' specified by nextLinkName does not exist in the 200 response schema. 
Please, specify the name of the property that provides the nextLink. If the model does not have the nextLink property then specify null.
  at specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:3764
refer to How to fix?

**Comment by akning-ms** [comment]
For EVOLUTIONARY api added, suggest to add some tag e.g.  [EXPENIMENTAL]  in description. this will also show on API document for customer to better understand. thoughts?

**Comment by msft-adrianma** [comment]
@akning-ms I have fixed the sdk lintdiff issue. For the breaking change, it is already in the preview version so adding experimental is not needed. This is already signed off by the ARM team.
We need to enable this in arm manifest to unblock internal testing.

**Pull request merged**
