### PR TITLE
[DataFactory] Add GlobalParameters and update waitTimeInSeconds in WaitActivity

### PR DESCRIPTION
**Pull request by kangtao**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by arsunda** [comment]
@qianwens Can you have a look at this PR?
Not sure why the SDK test is failing, we were able to generate the SDK and create a PR for it:
https://github.com/Azure/azure-sdk-for-net/pull/11872/

**Review by qianwens — APPROVED** [review]

**Comment by qianwens** [comment]
> @qianwens Can you have a look at this PR?
> Not sure why the SDK test is failing, we were able to generate the SDK and create a PR for it:
> [Azure/azure-sdk-for-net#11872](https://github.com/Azure/azure-sdk-for-net/pull/11872)

There is an issue in .Net SDK code generator for DataFactory that I have asked .Net SDK code gen team to investigate. There is breaking change in your PR that you updated the data type of existing property, please help add justification for the breaking change in this PR. 
@akning-ms to help force merge this PR.

**Comment by arsunda** [comment]
Hi,

We are updating the data type of existing property 'waitTimeInSeconds' from integer to object which will still allow integer type (non-breaking change). This change it to allow this property to be an expression as well as an integer.

@akning-ms

**Comment by akning-ms** [comment]
> Hi,
> 
> We are updating the data type of existing property 'waitTimeInSeconds' from integer to object which will still allow integer type (non-breaking change). This change it to allow this property to be an expression as well as an integer.
> 
> @akning-ms

Hi @arsunda As breaking change result, https://github.com/Azure/azure-rest-api-specs/pull/9362#issuecomment-635211752 .there is also new property added. it is expected?

**Comment by arsunda** [comment]
@akning-ms 

> > Hi,
> > We are updating the data type of existing property 'waitTimeInSeconds' from integer to object which will still allow integer type (non-breaking change). This change it to allow this property to be an expression as well as an integer.
> > @akning-ms
> 
> Hi @arsunda As breaking change result, [#9362 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/9362#issuecomment-635211752) .there is also new property added. it is expected?

@akning-ms Yes, we are also adding a new optional property 'GlobalParameters'

**Comment by arsunda** [comment]
@akning-ms Ping on this. Anything else needed to check this in?

**Pull request merged**
