### PR TITLE
Update API version in VMSS' specs

### PR DESCRIPTION
**Pull request by anton-evseev**
Applying changes from https://github.com/Azure/azure-rest-api-specs/pull/6692 and https://github.com/Azure/azure-rest-api-specs/pull/6916 to release branch

VMSS specs have their own API version independent from the rest of Network specs. This PR updates it to the latest one.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
@number123, network validation failed.

**Comment by number213** [comment]
All fixed, CI's green
@yungezz please merge

**Comment by yungezz** [comment]
hi @number123, this is a breaking change. Just to double confirm with you and @MikhailTryakhov

**Comment by number213** [comment]
@yungezz No SDK has been published based on `2019-07-01`, I'm not sure how it would be a breaking change

**Comment by yungezz** [comment]
> @yungezz No SDK has been published based on `2019-07-01`, I'm not sure how it would be a breaking change

got it. merged.

**Pull request merged**
