### PR TITLE
readme.java.md for AppPlatform, add directive to change map value type

### PR DESCRIPTION
**Pull request by XiaofeiCao**
To avoid breaking change in convenience layer code.

generated code: https://github.com/Azure/azure-sdk-for-java/pull/35553/files

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
You may need to check with service, whether they need to do it in their ADO.

> Hi @XiaofeiCao, this service has enabled Service API Toolset. All spec updates MUST be initiated from service ADO project repo, so that to guarantee it to be the source of truth., please review this pull request if it's intentional or reject it if it's not expected. Normally, all the specification or example changes should start with PR created in ADO.
> 
> * You can refer to [Service API Toolset Introduction](https://aka.ms/shiftleft) for details.
> * Please contact service focal  contacts or [Service API Toolset Support Channel](https://teams.microsoft.com/l/channel/19%3a133dc9afa7c14d46a095e135092d05bb%40thread.skype/Shift%2520Left%2520Support?groupId=a5e9b41d-1b0a-471d-a170-8ce202fa30b1&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) if need further help.

**Comment by v-xuto** [comment]
@qiaozha Please help review JS breaking change.

**Comment by XiaofeiCao** [comment]
Service will initialize PR from their ADO repo. Close this one.

**Comment by XiaofeiCao** [comment]
According to service, we can get this PR merged.

**Comment by weidongxu-microsoft** [comment]
No need for JS breaking change review. The PR only change Java option, won't affect JS.

**Pull request merged**
