### PR TITLE
NetApp RP minor update and validation fixes

### PR DESCRIPTION
**Pull request by leonardbf**
Removed obsolete Mount Target Delete operation.
Fixed autorest pagination warnings.
(NetApp ticket NFSAAS-1505)

### CODE REVIEW

**Comment by hovsepm** [comment]
>       ],

Why is these parameters outside "get" method? Could you please fix it as well? Otherwise we have breaking change error notification which blocks merge.

---
Refers to: specification/netapp/resource-manager/Microsoft.NetApp/preview/2017-08-15/netapp.json:82 in 4535ffb. [](commit_id = 4535ffbe9b0b3be960171b9c8efcdb042f34ce64, deletion_comment = False)

**Comment by hovsepm** [comment]
>         }

same thing here, parameters should be under method

---
Refers to: specification/netapp/resource-manager/Microsoft.NetApp/preview/2017-08-15/netapp.json:126 in 4535ffb. [](commit_id = 4535ffbe9b0b3be960171b9c8efcdb042f34ce64, deletion_comment = False)

**Comment by hovsepm** [comment]
Couple of warnings - removing an operation and marking return values as paginated will be a breaking change in strongly typed languages however since the swagger is in preview folder we do not block merge. Please confirm that it is ok for you to break customers code.

**Comment by leonardbf** [comment]
> Couple of warnings - removing an operation and marking return values as paginated will be a breaking change in strongly typed languages however since the swagger is in preview folder we do not block merge. Please confirm that it is ok for you to break customers code.

Yes, the removal of the operation is ok and is because it is no longer present in the application.
The pagination (forcing null) was added because without this block the autorest validation was producing warnings, e.g. `Based on the response model schema, operation 'Operations_List' might be pageable. Consider adding the x-ms-pageable extension`

**Review by hovsepm — APPROVED** [review]

**Pull request merged**
