### PR TITLE
[T2] compute

### PR DESCRIPTION
**Pull request by zikalino**
This is based on:

https://github.com/Azure/azure-rest-api-specs/pull/9095

- removes duplicated schemas
- rebased

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Still we have some field un-aligned..... please check the log of go SDK generation for more details...

**Comment by ArcturusZhang** [comment]
Go SDK generation passed 👍

**Comment by fengzhou-msft** [comment]
@zikalino @hyonholee do we still need this PR?

**Comment by fengzhou-msft** [comment]
Close idle PR. Please feel free to reopen it and continue the work if you still need it.

**Comment by JackTn** [comment]
Hi, @zikalino. The PR has be closed for a long time and it's related branch still exist. If no further used for over 14 days, I will delete this related branch. Please tell me if you still need this branch.

**Comment by JackTn** [comment]
Hi, @zikalino. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
