### PR TITLE
Adding support to the LogicApps Workflow Run Delete operation (New).

### PR DESCRIPTION
**Pull request by aalevato**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by aalevato** [comment]
Related to https://github.com/Azure/azure-rest-api-specs/pull/5755 - as suggested, I will abandon the other PR once this once gets merged. Thanks.

**Comment by aalevato** [comment]
None of the "check errors" pointed above are on parts of the code that I touched. The code in master already has the "model validation issues" being raised.

**Comment by ArcturusZhang** [comment]
Hi @aalevato , has the ARM team viewed this api change?

**Comment by aalevato** [comment]
Hi Arcturus, they haven't. This API was implemented (and has been in production) since the beginning of the year. The first PR I sent for it was back on May. We're changing our processes as for future API changes to go through the ARM team review, but this one was made before it. Like I said, however, we're referring to an API which is already in production for almost 6 months now.

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang , they haven't. This API was implemented (and has been in production) since the beginning of the year. The first PR I sent for it was back on May. We're changing our processes as for future API changes to go through the ARM team review, but this one was made before it. Like I said, however, we're referring to an API which is already in production for almost 6 months now.

If the ARM team hasn't reviewed these changes, we should wait for them to respond. I will write an email to them if they do not show up till tomorrow

**Comment by yungezz** [comment]
hi @aalevato could you pls fix model validation error? the error message is self explains. Pls ping us if  you have difficult on meanings of error. Those errors will be every of  your future PRs if not fixed.

**Comment by aalevato** [comment]
@yungezz I said before - the errors appearing on the check are for different files. They were already there before my changes (can you run a check on the current master to see it?). It's not the intention of this PR to fix the other files. Can we please move on already? I don't want us dropping in the same infinite bucket as before and wait for months.

**Comment by yungezz** [comment]
@aalevato yes the modelvalidation is from existing codes in the swagger file. While it will be there in every future PR on this swagger file? Do your team have any plan to fix it? Besides this, this PR is pending on ARM review. After ARM signed off, feel free to ping us for PR merging.

**Comment by aalevato** [comment]
@ArcturusZhang we still didn't hear back from ARM. Can we please move forward with it? This process had been going already for several months, and the users are eager to use the API (which is already in production) but can't do so because they want to see it on the swagger first.

**Review by anthony-c-martin — APPROVED** [review]

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
