### PR TITLE
Added swagger files for MySQL Flexible Server preview

### PR DESCRIPTION
**Pull request by Suna-MS**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
This was signed off for POstGreSQL RP recently and its the same changes for the MySQL RP. Signing off from ARM side.

**Review by weidongxu-microsoft — APPROVED** [review]
LGTM. Let me know when you need it merged.

**Comment by Suna-MS** [comment]
@weidongxu-microsoft , this PR is ready for merge.

**Comment by weidongxu-microsoft** [comment]
@NullMDR Hi Phoenix, any idea of the LintDiff?
https://dev.azure.com/azure-sdk/public/_build/results?buildId=484091&view=logs&jobId=688669d0-441c-57c3-cf6d-f89a22ccfa5d&j=688669d0-441c-57c3-cf6d-f89a22ccfa5d&t=923b5a90-e462-5994-c166-86509c6bf5f2

This seems not an error (`DB`)
```
{\n' +
  '  "type": "error",\n' +
  '  "code": "PathResourceProviderNamePascalCase",\n' +
  `  "message": "Resource provider naming must follow the pascal case. Path: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBforMySQL/servers/{serverName}/keys/{keyName}'",\n` +
  '  "id": "R3020",\n' +
  '  "validationCategory": "ARMViolation",\n' +
  '  "providerNamespace": false,\n' +
  '  "resourceType": false,\n' +
  '  "sources": [\n' +
  '    "file:///home/vsts/work/1/s/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2020-01-01/DataEncryptionKeys.json:18:2 ($.paths)"\n' +
  '  ],\n' +
  '  "jsonref": "file:///home/vsts/work/1/s/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2020-01-01/DataEncryptionKeys.json:18:2 ($.paths)",\n' +
  '  "json-path": "file:///home/vsts/work/1/s/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2020-01-01/DataEncryptionKeys.json:18:2 ($.paths)"\n' +
  '}\n' +
```

Not sure about this one.
```
  Error: '$.definitions.Sku.properties.name.description' has incompatible values (---\n" +
  '  -\n' +
  '  The name of the sku, typically, tier + family + cores, e.g. B_Gen4_1,\n' +
  '  GP_Gen5_8.\n' +
  ', ---\n' +
  'The name of the SKU. Ex - P3. It is typically a letter+number code\n' +
  ').]'
```

**Comment by weidongxu-microsoft** [comment]
@Suna-MS

Lint does not allow provider name as DBforMySQL.
It requires camelCase like DbForMysql
@akning-ms I am not sure whether this is the correct requirement.

For now I guess you had to suppress it, if this requirement is correct. https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process
@jianyexi for guidance

**Pull request merged**
