### PR TITLE
Adding 200 response in CreateOrUpdate api

### PR DESCRIPTION
**Pull request by juniwang**
Adding 200 response in CreateOrUpdate API

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by juniwang** [comment]
Can one of the admin merge this PR? since it's approved already

**Comment by erich-wang** [comment]
@akning-ms, could you please take a look why CI was not complete for long time? I rerun some times.

**Comment by akning-ms** [comment]
Hi @erich-wang, Yes, It is known issue recently for github. @NullMDR  filled a ticket for this.  in the mean time, actually the validation already finished, you can check the result by click tab 'check'

**Comment by NullMDR** [comment]
@juniwang You can mitigate this issue by adding a new empty commit

**Comment by erich-wang** [comment]
@akning-ms , please force this PR, the breaking change is for correctness and to align with real service behavior, sign off.

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
