### PR TITLE
Modifying the summary response to contain the field on which summary is done

### PR DESCRIPTION
**Pull request by dukum**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dukum** [comment]
Explanation for the breaking changes:

Rule | Message | Reason
-- | -- | --
❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'summary' renamed or removed?New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | No existing users of the API will be impacted. The property has been renamed. The changes in service corresponding to earlier property has not been merged.
❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'summary' renamed or removed?New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | Same as above.
❌ 1041 - AddedPropertyInResponse | The new version has a new property 'summaryCollection' in response that was not found in the old version.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | No existing users of the API will be impacted. The earlier property has been renamed to this new property. The changes in service corresponding to the earlier property has not been merged yet, so no impact on the users..

**Review by xseeseesee — APPROVED** [review]

**Comment by dukum** [comment]
Breaking Change explanantion:

Rule | Message | Reason
-- | -- | --
❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'summary' renamed or removed?New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | No existing users of the API will be impacted. The property has been renamed. The changes in service corresponding to earlier property has not been merged.
❌ 1033 - RemovedProperty | The new version is missing a property found in the old version. Was 'summary' renamed or removed?New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | Same as above.
❌ 1041 - AddedPropertyInResponse | The new version has a new property 'summaryCollection' in response that was not found in the old version.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1526:7Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1509:7 | No existing users of the API will be impacted. The earlier property has been renamed to this new property. The changes in service corresponding to the earlier property has not been merged yet, so no impact on the users..

**Comment by dukum** [comment]
@xccc-msft I have provided the justification of the breaking change. No user of the API will be impacted as the reference with which the current change is breaking was not released by our service. Can you please merge the PR now.

**Comment by xccc-msft** [comment]
@dukum We have to wait for the approval. After that I can help merge.

**Comment by dukum** [comment]
@xccc-msft This is a false positive breaking changes. I have provided the reasons in the earlier comment. As suggested in the 'openapi-workflow-bot' comment I have reported to the Swagger Tooling Team. Since this is a false positive case, we will not require a breaking change review.

_If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ma/swaggerfeedback_

**Comment by xccc-msft** [comment]
> @xccc-msft This is a false positive breaking changes. I have provided the reasons in the earlier comment. As suggested in the 'openapi-workflow-bot' comment I have reported to the Swagger Tooling Team. Since this is a false positive case, we will not require a breaking change review.
> 
> _If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ma/swaggerfeedback_

cc: @akning-ms

**Comment by akning-ms** [comment]
Hi @dukum, It looks it is not false alarm for breaking change. your MoveCollectionProperties model is changed. not only the property name changed from Summary to SummaryCollection, and also Summary and Summary collection content also changed.
As seems version 2019-10-01-preview already merged for some time, can you give us more info why it is no customer impact.
e.g is there any SDK released based on this api. or your service is GA?

**Comment by dukum** [comment]
Hi @akning-ms. Our service is not yet GA. The changes for adding the summary was done as a part of pr https://github.com/Azure/azure-rest-api-specs/pull/11052 but the 
corresponding service side changes were not released. Then in service we decided to change the model and raised this pr. So for the earlier property name summary, and the content of summary and summaryCollection, no user was using them as the service side changes were never released.

**Comment by akning-ms** [comment]
Thanks. Since the service is not GA yet. I approved the breaking change

**Comment by dukum** [comment]
hi @xccc-msft. can you please help merge this change. the breaking change is now approved.

**Pull request merged**
