### PR TITLE
[Merge on Jan 31st] [ADLA - ADLS] - KPI Swagger/ARM Validation for Account APIs

### PR DESCRIPTION
**Pull request by ro-joowan**
* **PLEASE DO NOT MERGE AFTER APPROVAL**.  I would like to confirm a couple of things before merging, but I wanted to start the review ASAP.

* To ease the review, please view the changes through individual commits (hopefully that helps).  This is because the last two commits move a lot of code around (which was much needed for code clarity/organization)

* This work is to pass Swagger/ARM validation (autorest --azure-validator)

* There are no functional changes in this commit -- mainly refactoring of objects to clarify the user experience: creating explicit objects for PUT/PATCH and making objects from GET to be read-only

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by jianghaolu — APPROVED** [review]

**Review by simongdavies — APPROVED** [review]

**Comment by salameer** [comment]
@ro-joowan should this be merged now? 

if so @jianghaolu kindly move forward with it

**Comment by ro-joowan** [comment]
@salameer Got piled with some other urgent tasks lately... @jianghaolu I'll update here when complete.

**Comment by jianghaolu** [comment]
Jan 31st?

**Comment by ro-joowan** [comment]
@jianghaolu That is the hopeful date

**Comment by ro-joowan** [comment]
@jianghaolu, Please merge! :)

@salameer, FYI

**Comment by ro-joowan** [comment]
@lmazuel Should I be concerned about the error above with Autorest?

**Pull request merged**
