### PR TITLE
[Azure Stack] Updates to Azs.AzureBridge.Admin spec

### PR DESCRIPTION
**Pull request by viananth**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by bganapa — APPROVED** [review]

**Comment by bganapa** [comment]
These are fixes to the existing swagger specs to the admin API surface of Azurestack. This API surface is consumed only thru powershell in azurestack. None of these are really breaking changes

**Comment by viananth** [comment]
@markcowl, Mark, could you please take a look at this PR? The lintDiff errors are mostly pascalcase errors (reported wrong, CI issue): 

> Resource provider naming must follow the pascal case. Path: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureBridge.Admin/activations/{activationName}/products/{productName}'

Breaking changes are for autorest generation config. @bganapa FYI

**Comment by markcowl** [comment]
@bganapa The breakign changes look like real breakign changes (for example, resourceGroup -> resourceGroupName).  If these are intentional, then they are OK.

rerunning lintdiff

**Comment by bganapa** [comment]
@markcowl Thanks. Yes the change is intentional, we are taking many breaking changes as bug fixes
In the following URI Path, Calling it as resourceGroupName is the standard everywhere. We had the option of either renaming it in the generator metadata or fix it for all in the spec.  
resourcegroups/{resourceGroup} 

We decided to do the breaking change in the spec as our admin specs are still in 'preview'

**Comment by bganapa** [comment]
@viananth as mark mentioned above
for the linter errors, please suppress these in your readme.md file.

**Comment by markcowl** [comment]
@viananth Ping?  Need to suppress the linter errors and I can merge this as an approved breaking change.

**Comment by markcowl** [comment]
@viananth good sample of suppressions here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/readme.md

**Comment by viananth** [comment]
@markcowl, I fixed the lint and model errors. Could you pls merge this PR? Thanks!

**Comment by viananth** [comment]
@markcowl, Mark, Fixed lint errors. Could you pls merge this PR? Thanks!

**Pull request merged**
