### PR TITLE
2020-10-01 Peering Rest api specs

### PR DESCRIPTION
**Pull request by swetha-anantharajaiah**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
>             "name": "peeringLocation",

What is this location? Does it maps to Azure locations?

---
Refers to: specification/peering/resource-manager/Microsoft.Peering/stable/2020-10-01/peering.json:28 in eda7f35. [](commit_id = eda7f357b3184cd3e81ab9a6d280e97dd44315c2, deletion_comment = False)

**Comment by chiragg4u** [comment]
>             "required": true,

How will use discover this required parameter?
Normally in the API we allow discoverability for e.g. listSubscription, listProviders, listTypes, ListSubTypes etc. Can these be modeled like subType for other type like Peering or PeeringLocations?

---
Refers to: specification/peering/resource-manager/Microsoft.Peering/stable/2020-10-01/peering.json:31 in eda7f35. [](commit_id = eda7f357b3184cd3e81ab9a6d280e97dd44315c2, deletion_comment = False)

**Comment by swetha-anantharajaiah** [comment]
> peeringLocation

No, this does not map to AzureRegion. We have PeeringLocation as top level resource already and ListPeeringLocations exist

**Comment by swetha-anantharajaiah** [comment]
> > ```
> >         "required": true,
> > ```
> 
> How will user discover this required parameter?
> Normally in the API we allow discoverability for e.g. listSubscription, listProviders, listTypes, ListSubTypes etc. Can these be modeled like subType for other type like Peering or PeeringLocations?
> 
> Refers to: specification/peering/resource-manager/Microsoft.Peering/stable/2020-10-01/peering.json:31 in [fea2f00](https://github.com/Azure/azure-rest-api-specs/commit/fea2f00eef1ed2aa583303b9ff5097ea90d471f7). [](commit_id = [fea2f00](https://github.com/Azure/azure-rest-api-specs/commit/fea2f00eef1ed2aa583303b9ff5097ea90d471f7), deletion_comment = False)

We do have ListPeeringLocations

**Comment by chiragg4u** [comment]
>     "/subscriptions/{subscriptionId}/providers/Microsoft.Peering/cdnPeeringPrefixes": {

please model the API as 
/subscriptions/<subId>/providers/Microsoft.Peering/peeringServiceLocations/<peeringLocation>/cdnPeeringPrefixes


---
Refers to: specification/peering/resource-manager/Microsoft.Peering/stable/2020-10-01/peering.json:19 in eda7f35. [](commit_id = eda7f357b3184cd3e81ab9a6d280e97dd44315c2, deletion_comment = False)

**Comment by swetha-anantharajaiah** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/providers/Microsoft.Peering/cdnPeeringPrefixes": {
> > ```
> 
> please model the API as
> /subscriptions//providers/Microsoft.Peering/peeringServiceLocations//cdnPeeringPrefixes
> 
> Refers to: specification/peering/resource-manager/Microsoft.Peering/stable/2020-10-01/peering.json:19 in [eda7f35](https://github.com/Azure/azure-rest-api-specs/commit/eda7f357b3184cd3e81ab9a6d280e97dd44315c2). [](commit_id = [eda7f35](https://github.com/Azure/azure-rest-api-specs/commit/eda7f357b3184cd3e81ab9a6d280e97dd44315c2), deletion_comment = False)

We dont have Get_PeeringLocation hence cannot add this as a child resource to PeeringLocation. PeeringServiceLocation is a different resource and is not related to cdnPeeringPrefixes

**Review by markcowl — APPROVED** [review]
Looks good as soon as the ci passes

**Comment by markcowl** [comment]
Removing the c-breaking-changes-python tag, as verified there is no difference in the Error schema in this pr from previousversion

**Pull request merged**
