### PR TITLE
Fixed lint errors due to operation name casing.

### PR DESCRIPTION
**Pull request by jimmyca15**
Fixed Lint errors opened against us due to camel case requirement.

Error link: https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=4C7CE83D-5C8A-4CC2-9B04-79598BD42425

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @jimmyca15 could you also resolve the error schema error reported in LintDiff?

**Comment by ArcturusZhang** [comment]
Hi @jimmyca15 this PR introduces breaking changes to a stable api-version and a preview api-version  for over 1 year, therefore this PR has to follow our [breaking change review policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes) and [retirement of preview policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews).

Could you please follow the steps in this [breaking change review process](https://microsoft.sharepoint.com/teams/azureecosystem/servicerings/Shared%20Documents/Breaking%20Changes/Azure%20Breaking%20Changes%20Program%20Definition-%20V1.0.pdf)?

**Comment by jimmyca15** [comment]
@ArcturusZhang 

If this is a breaking change should we even fix it or is there a process to get excluded from the Lint check for casing because these are old API versions?

**Comment by ArcturusZhang** [comment]
Hi @jimmyca15 we do not recommend suppressing these lint errors. Since this fix causes breaking changes, usually we just remain the old api-version unchanged and only fix these errors in a new api-version (which has applied to network RP with a same operation path casing problem.

But if you really want to fix this in the same api-version rather than introducing a new api-version with these errors fixed, you will have to follow the breaking change review process in the doc I provided above. In this process, the breaking change review team will need to evaluate how much impact this change will introduce and decide whether to approve this breaking change or reject.

**Comment by jimmyca15** [comment]
@ArcturusZhang Oh okay, so if I'm understanding this correctly the lint error that I linked in the PR description only applies if the latest API version has this error. If we add a preview API version (which we are in the process of doing) with this fix will it resolve the error?

**Comment by ArcturusZhang** [comment]
Hi @jianyexi could you please help me on this question?

**Comment by jianyexi** [comment]
> @ArcturusZhang Oh okay, so if I'm understanding this correctly the lint error that I linked in the PR description only applies if the latest API version has this error. If we add a preview API version (which we are in the process of doing) with this fix will it resolve the error?

Right, it's feasible.

**Comment by jimmyca15** [comment]
Closing this PR since we are adding a preview API version and we will fix the issue from that version forward.

**Pull request closed without merging**
