### PR TITLE
Sql job agent

### PR DESCRIPTION
**Pull request by jaredmoo**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@jaredmoo You still iterating on this?

**Comment by jaredmoo** [comment]
The API will not be live for a little while (i.e. at least a couple weeks) and there will be a few minor tweaks before then. How should we handle this?

**Comment by jhendrixMSFT** [comment]
I'm fine with letting it linger until ready.  Has ARM already reviewed this?

**Comment by jhendrixMSFT** [comment]
@jaredmoo Has this been reviewed by ARM already?

**Comment by jaredmoo** [comment]
Sorry, missed your question earlier :) it has not been explicitly approved by ARM team

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by jhendrixMSFT** [comment]
@jaredmoo We still waiting for this to be merged?  Also there is a merge conflict that needs to be resolved.

**Comment by jaredmoo** [comment]
Yes, this feature has been delayed. We will message when it's ready to be merged. Thanks :)

**Comment by jaredmoo** [comment]
@jhendrixMSFT the API is not public yet, but I am going on vacation soon and I want to avoid having too much work in-flight. So I have removed the new file from readme.md. This way we can get the swagger checked in but not included in SDKs yet. I am removing "do not merge" tag.

**Comment by jhendrixMSFT** [comment]
@jaredmoo Sounds good, can I then assume that the remaining model validation failures will be addressed when the file is added back to the readme?

**Comment by jaredmoo** [comment]
This model validation error is a validator bug:

```
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Create or update a credential" in operation "JobCredentials_CreateOrUpdate".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'ONE_OF_MISSING',
            params: [],
            message: 'Data does not match any schemas from \'oneOf\'',
            path: [ 'properties' ],
            inner: 
             [ { code: 'OBJECT_MISSING_REQUIRED_PROPERTY',
                 params: [ 'password' ],
                 message: 'Missing required property: password',
                 path: [ 'properties' ],
                 description: 'Properties of a job credential.' },
               { code: 'INVALID_TYPE',
                 params: [ 'null', 'object' ],
                 message: 'Expected type null but found type object',
                 path: [ 'properties' ] } ] } ],
       message: 'Invalid body: Data does not match any schemas from \'oneOf\'',
       path: [] } ] }
```

Password is a required write-only parameter. Because it is write-only, the validator should not be checking it for null in responses.

Taking a look at the other errors.

**Comment by jaredmoo** [comment]
The other model errors were legit and I have fixed them. Should be good to merge now.

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
