### PR TITLE
Add track2 config to servicebus

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by markcowl** [comment]
@00Kai0 Do you still need this PR open?  Will have to close at end of next week if no response.

**Comment by markcowl** [comment]
closing for lack of response

**Comment by 00Kai0** [comment]
@markcowl ,sorry for no response. It was chinese holiday.

**Comment by 00Kai0** [comment]
It's ready to be reviewed. @changlong-liu

**Review by markcowl — APPROVED** [review]

**Pull request merged**
