### PR TITLE
[Blueprint] Remove length limitation from RG name and location properties

### PR DESCRIPTION
**Pull request by filizt**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Not sure whether it counts as API change. Let me know if you need ARM review.

**Comment by filizt** [comment]
> Not sure whether it counts as API change. Let me know if you need ARM review.

It shouldn't require an ARM review. The properties updated in this PR didn't need to be strict with their values length to start with. We're just fixing that.

**Comment by weidongxu-microsoft** [comment]
@filizt

Got it. I will ignore the ConstraintChanged in BreakingChange CI since it is intended as fix.

Could you fix the PrettierCheck CI, then we can merge it.

**Comment by weidongxu-microsoft** [comment]
> > Not sure whether it counts as API change. Let me know if you need ARM review.
> 
> It shouldn't require an ARM review. The properties updated in this PR didn't need to be strict with their values length to start with. We're just fixing that.

@akning-ms Hello Arthur would you help merge? The breaking change is due to fix on wrong spec.

**Pull request merged**
