### PR TITLE
Add missing private link fields for CDN version 2020-04-15

### PR DESCRIPTION
**Pull request by fore5fire**
Please note that this change modifies an API version that is not yet in use by any customers.

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lsmith130** [comment]
@akning-ms please review this. From what I can tell, the check failures are all because this is a breaking change, but we haven't yet released this API version.

**Comment by akning-ms** [comment]
LGTM, I will merge if ARM sign it off, @NullMDR for check python SDK failure

**Comment by NullMDR** [comment]
@akning-ms The python codegen failure is a known issue for incorrect config. We've fixed it today.

**Comment by ravbhatnagar** [comment]
Removing ARM Feedback label since ARM review board will not be reviewing property level changes going forward.

**Comment by akning-ms** [comment]
Hi @lsmith130 Can you fix ModelValidation validation failure?

**Pull request merged**
