### PR TITLE
[Azure Search] Adding examples to latest data plane specs

### PR DESCRIPTION
**Pull request by bitsforthought**
Note that the Azure Search data plane API docs are not currently generated from Swagger, but we plan to enable this eventually. These examples are just to satisfy the Swagger validator in the meantime.

FYI @Yahnoosh @mhko @chaosrealm 

@Yahnoosh Please validate analyzer-related examples.
@mhko Please validate synonym-related examples.
@chaosrealm Please validate indexer-related examples.

Thanks!

-----

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
Hi @Yahnoosh @mhko and @chaosrealm,  Bruce requested your review for analyzer-related, synonym-related and indexer-related examples in this PR. can you guys take a look at these areas?

**Comment by chaosrealm** [comment]
LGTM

**Comment by mhko** [comment]
Changes for synonyms LGTM

**Review by Yahnoosh — APPROVED** [review]
:shipit:

**Review by Yahnoosh — APPROVED** [review]

**Review by anuchandy — APPROVED** [review]

**Review by anuchandy — CHANGES_REQUESTED** [review]
There are some model validation errors while validating the examples. can you please take a look?
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/339756295

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
@brjohnstmsft  thank you, merging this. The other (allowed) errors reported by validation tool does not look like issue with search examples. I will report this to tool owners.

**Pull request merged**
