### PR TITLE
Billing RP spec changes for GTM FieldLed-Go-Big

### PR DESCRIPTION
**Pull request by asarkar84**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by asarkar84** [comment]
Updated listInvoiceSectionsWithCreateSubscriptionPermission from GET to POST in this new iteration.

**Comment by majastrz** [comment]
>       "post": {

POST on a collection URI in ARM is considered an anti-pattern. Is it possible to use PUT to create a billing role assignment on the billing account?

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:3346 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Comment by majastrz** [comment]
>       "post": {

Same collection POST issue here.

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:3431 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Comment by majastrz** [comment]
>       "post": {

Same collection POST issue here.

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:3519 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Comment by majastrz** [comment]
>           "enum": [

You will need to specify the x-ms-enum extension. Also, you will need to use the modelAsString: true setting to make the linter happy.

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:4311 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Comment by majastrz** [comment]
>           "enum": [

This applies to all the enums in here.

---
In reply to: [517489699](https://github.com/Azure/azure-rest-api-specs/pull/6661#issuecomment-517489699) [](ancestors = 517489699)

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:4311 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Comment by majastrz** [comment]
>   "swagger": "2.0",

A few of the CI checks are failing. You'll need to fix the failure (the assigned SDK reviewer can help).

---
Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:2 in 18ddcc3. [](commit_id = 18ddcc39fcfd708b9e9b939215b78b9c982ff11e, deletion_comment = False)

**Review by majastrz — CHANGES_REQUESTED** [review]
I added a few comments for the remaining issues.

Also, there are a lot of breaking changes in the API. I assume this is intentional, but how are you planning to deal with that? (If it was discussed with prior reviewers, I don’t have that context ☹.)

**Comment by asarkar84** [comment]
> > ```
> >       "enum": [
> > ```
> 
> You will need to specify the x-ms-enum extension. Also, you will need to use the modelAsString: true setting to make the linter happy.
> 
> Refers to: specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json:4311 in [18ddcc3](https://github.com/Azure/azure-rest-api-specs/commit/18ddcc39fcfd708b9e9b939215b78b9c982ff11e). [](commit_id = [18ddcc3](https://github.com/Azure/azure-rest-api-specs/commit/18ddcc39fcfd708b9e9b939215b78b9c982ff11e), deletion_comment = False)

Sure. Done.

**Comment by asarkar84** [comment]
@majastrz I have incorporated the comments provided. Please take a look.

Regarding BillingRoleAssignments actions,  I just rolled back to a new path with createBillingRoleAssignment action. That is what we had in previous version.

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
