### PR TITLE
[DO NOT MERGE]Adding userassigned identities for the compute

### PR DESCRIPTION
**Pull request by shail2208**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [y ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ y] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ y] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by pilor** [comment]
>     "version": "2020-02-02"

you already have a newer api-version in 2020-03-01.  Why introduce an older api-version?  That api-version will need these changes as well, if it has already been published you'd need to create a new api-version > 2020-03-01

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-02-02/machineLearningServices.json:6 in e2f8ef1. [](commit_id = e2f8ef1e85939ce1bbcea1358e2108c98f552ef4, deletion_comment = False)

**Review by pilor — CHANGES_REQUESTED** [review]
:clock1:

**Comment by shail2208** [comment]
@pilor The newer api-version was published by mistake before making manifest changes. The newer version is not live yet. We will modify the latest version to base upon "2020-02-02" once it is ready to go live.

**Comment by pilor** [comment]
> @pilor The newer api-version was published by mistake before making manifest changes. The newer version is not live yet. We will modify the latest version to base upon "2020-02-02" once it is ready to go live.

That should be done in this PR.  You shouldn't check in an older api-version with the newer one not supporting the features that the older one is adding.  From an API standpoint everything is fine but you need to clean up your swagger specs.

**Review by pilor — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @shail2208 please let me know when this is ready to merge.

**Comment by ArcturusZhang** [comment]
Hi @shail2208 any updates? It has been quite a long time...

**Pull request closed without merging**
