### PR TITLE
Swagger changes for new features

### PR DESCRIPTION
**Pull request by singhabh27**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by singhabh27** [comment]
@erich-wang  can you please clarify the breaking change?

**Comment by erich-wang** [comment]
> @erich-wang can you please clarify the breaking change?

@singhabh27, adding optional parameters are considered as breaking change per [breaking change policy](https://aka.ms/AzBreakingChangesPolicy)

**Comment by singhabh27** [comment]
@ erich-wang,it is for a feature that we already exposed via REST API (Tagging feature)?

**Comment by erich-wang** [comment]
> @ erich-wang,it is for a feature that we already exposed via REST API (Tagging feature).

@singhabh27, in general you should get approval in this repo first and then deploy change into service side. 
Even the change has been deployed into service side, you still need go thru the process per [breaking change policy](https://aka.ms/AzBreakingChangesPolicy), but it will be approved easier, please state that the change is for swagger correctness.

**Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).</br> If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ma/swaggerfeedback.

**Comment by erich-wang** [comment]
@singhabh27, is this PR still valid, we're going to close this PR by end of Feb 5 if no response from your side, thanks.

**Comment by erich-wang** [comment]
Close this PR as there's no response from @singhabh27 for long time, please reopen this PR or create a new PR if necessary, thanks.

**Pull request closed without merging**
