### PR TITLE
EventHub: added $skip and $top to list calls

### PR DESCRIPTION
**Pull request by v-Ajnava**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@v-Ajnava It depends on the language.  For Go these new params are added to the method signature, see https://github.com/Azure/azure-sdk-for-go/blob/19d431608e56bb5b77c3a47a56f04d40c355d962/services/eventhub/mgmt/2017-04-01/eventhub/consumergroups.go#L305 for an example (we have a work item to avoid this problem).

**Comment by jhendrixMSFT** [comment]
@v-Ajnava Any update?

**Comment by v-Ajnava** [comment]
@jhendrixMSFT ,  actually the Service Bus PR is merged with same optional $skip and $top properties. 
adding @sazeesha and @dsouzaarun, can you please suggest on this.

**Comment by sazeesha** [comment]
@jhendrixMSFT, for a collection with query param our service returns max of 100 resources at a time with a nextLink to the next set of resources. For our Clients to function correctly we need to add the optional skip and top query param.  For the GO client what is the timeline to fix it?

**Comment by jhendrixMSFT** [comment]
@sazeesha At present there is no timeline to change the Go codegen for this issue.  We won't prevent you from making this change, I just wanted to raise awareness that this is a breaking change for Go (I don't know if it is for any other languages).

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
