### PR TITLE
Move Batch swagger specification to right place

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by matthchr** [comment]
@amarzavery I am not sure how this change managed to make CI fail, since if you look at the commit all it does is move the existing JSON file into a subdirectory, there were no changes to the file at all.

**Comment by amarzavery** [comment]
That is weird

**Comment by matthchr** [comment]
The issue is that your travis test doesn't check subfolders without the swagger name in them:
`var globPath = path.join(__dirname, '../', '/**/swagger/*.json');`

**Comment by matthchr** [comment]
I'll fix whatever issues there are and update

**Comment by amarzavery** [comment]
which is correct. Because we expect the file to be inside the swagger folder.

**Comment by amarzavery** [comment]
Last property of a json object should not have a comma.
Bunch of nested objects around line 11965 have a comma after the last property "description"

**Comment by matthchr** [comment]
@amarzavery Fixed.  Thanks!

**Pull request merged**
