### PR TITLE
Service Bus 2018-preview: Added Namespace OperationsID API

### PR DESCRIPTION
**Pull request by v-Ajnava**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [X] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by ryansbenson — COMMENTED** [review]
Same comments as:
https://github.com/Azure/azure-rest-api-specs/pull/8101

If you could combine these PRs it would be easier to review and iterate on this.

**Comment by NullMDR** [comment]
@v-Ajnava Any update on this PR?

**Comment by v-Ajnava** [comment]
@NullMDR  and @ryansbenson developer is working on implementing the comments.

**Comment by NullMDR** [comment]
@v-Ajnava Any more update on this PR?

**Comment by ravbhatnagar** [comment]
no response from PR owner for a long time. removing ARM review labels.

**Comment by NullMDR** [comment]
Close PR due to inactivity. @v-Ajnava please reopen it if you still want to merge it.

**Pull request closed without merging**
