### PR TITLE
Adding SQL managedDatabases swagger for API v2018-06-01-preview

### PR DESCRIPTION
**Pull request by misosic-msft**
Adding SQL managedDatabases swagger and examples for API version 2018-06-01-preview

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by misosic-msft** [comment]
I've run autorest validation and got the following:
image

1st, 3rd and 4th are already present in version 2017-03-01-preview of managedDatabases swagger.
For the 2nd warning, restoreDetails is always a single resource. Can we override this warning and skip implementing List?

**Comment by michaeljqzq** [comment]
WARNING is not required to be fixed. But I see there's some error in semantic validation: 'internal error: Failed to load a reference file specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/examples/CompleteManagedRestore.json. (Error: ENOENT: no such file or directory
Please confirm

**Review by michaeljqzq — APPROVED** [review]

**Comment by michaeljqzq** [comment]
I added the `DoNotMerge` tag since the title. Do you have a timeline for the PR to merge?

**Comment by misosic-msft** [comment]
> I added the `DoNotMerge` tag since the title. Do you have a timeline for the PR to merge?

Changes for this API are already being rolled out to Production so it can be merged right away if everything looks good.

**Comment by misosic-msft** [comment]
@michaeljqzq @jaredmoo Can this PR be merged?

**Pull request merged**
