### PR TITLE
Azure Language Summarization November 2023 Preview Features

### PR DESCRIPTION
**Pull request by dhung-msft**
# Data Plane API - Pull Request

Add parameters for new public features:
1. Query-based extractive summarization
2. Custom aspect conversation summarization

This is a re-submission of #25817 to try and resolve some validation issues and ease diff visualization
 
## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document: https://microsoft-my.sharepoint.com/:p:/p/dahung/EdHa42sBGZdIuT4mADFxG0wBk2UdajKDnR5ONCPiDT47BA?e=ke8JlB
* Previous API Spec Doc: https://microsoft.sharepoint.com/:w:/t/TextAnalyticsTeam/EcYf7VnUDBNNl8YCBFOBDWEB6KWE5UquOqUl4xugDZ0rig?e=gCu24H
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by heaths** [comment]
Please go through the check failures - click on Details, read through it, and if more information is needed click on the Azure Pipelines link at the bottom.

**Review by heaths — CHANGES_REQUESTED** [review]
@dhung-msft why did you open a new PR when there's already #25817?

If this PR is adding more features, your team needs to be targeting a feature branch until done, *then* merge to `main`. This workflow is laid out in our [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/699/Walkthrough-Creating-a-new-service-specification).

I can't review this until I better understand how this compares to that PR.

Note that merging to `main` means an API is done. There's little to no changing it after that, based on our [Breaking Changes policy](https://aka.ms/AzBreakingChangesPolicy).

**Comment by dhung-msft** [comment]
> @dhung-msft why did you open a new PR when there's already #25817?
> 
> If this PR is adding more features, your team needs to be targeting a feature branch until done, _then_ merge to `main`. This workflow is laid out in our [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/699/Walkthrough-Creating-a-new-service-specification).
> 
> I can't review this until I better understand how this compares to that PR.
> 
> Note that merging to `main` means an API is done. There's little to no changing it after that, based on our [Breaking Changes policy](https://aka.ms/AzBreakingChangesPolicy).

This PR/branch is just for a cleaner commit log so diffs can be visualized more easily (I reference this in our e-mail thread). This PR doesn't actually need to be reviewed/merged; for some reason I don't have a "Mark as draft" button available

**Comment by dhung-msft** [comment]
Found the draft button finally

**Comment by heaths** [comment]
> This PR/branch is just for a cleaner commit log so diffs can be visualized more easily (I reference this in our e-mail thread). This PR doesn't actually need to be reviewed/merged; for some reason I don't have a "Mark as draft" button available

This just complicates the review process. We already have a lot of comments / feedback on the other PR. PRs kick off a bunch of other processes, looping in reviews as needed which may not be the same people, which causes even more confusion. Any problem with closing this one?

**Comment by dhung-msft** [comment]
> > This PR/branch is just for a cleaner commit log so diffs can be visualized more easily (I reference this in our e-mail thread). This PR doesn't actually need to be reviewed/merged; for some reason I don't have a "Mark as draft" button available
> 
> This just complicates the review process. We already have a lot of comments / feedback on the other PR. PRs kick off a bunch of other processes, looping in reviews as needed which may not be the same people, which causes even more confusion. Any problem with closing this one?

No problem closing it, just take a look at [this commit](https://github.com/Azure/azure-rest-api-specs/pull/26515/commits/847d48516238bf3c855a63573cf26a5180535bc0) for diffs

**Comment by konrad-jamrozik** [comment]
@dhung-msft @heaths apologies, by mistake I made changes to the dhung-msft:dahung/nov2023preview branch while trying to reproduce some of the issues with the checks running on this PR. I force-pushed reversal of my changes, but this resulted in this PR getting automatically closed by GitHub.

@dhung-msft can I kindly ask you to verify that the branch dhung-msft:dahung/nov2023preview is still in correct state (i.e. that I didn't inadvertently delete anything) and if so, reopen the PR or submit a new one?

Again, huge apologies!

**Pull request closed without merging**
