### PR TITLE
typo: servicebus/resource-manager/Microsoft.ServiceBus

### PR DESCRIPTION
**Pull request by nschonni**
- Porperties -> Properties
- SKU capitalization
- reponse -> response
- authorizatio -> authorization
- Tpoic -> Topic
- namespce -> namespace
- authorizationrule -> authorization rule
- Autorization -> Authorization
- Regenrate -> Regenerate
- Namepsace -> Namespace
- envokes -> Invokes
- enties -> entities
- SqlFilter capitalization
- Corelation -> Correlation
- neeeds -> needs
- deatils -> details
- acrchive -> archive
- pairning -> pairing

### CODE REVIEW

**Comment by hovsepm** [comment]
reassigning to @veronicagg since I do not have permission to merge "failing" PR. However this PR does not change anything real in the swaggers.

**Comment by veronicagg** [comment]
@anuchandy any thoughts on why Java SDK generation is failing?

**Comment by salameer** [comment]
Hi @nschonni  again thank you for all of you contributions !!!

I have a question, Are you running some sort of tool to format and edit Vocab?

**Comment by nschonni** [comment]
I rebased since the java issue was fixed in #4626

**Comment by nschonni** [comment]
@hovsepm @veronicagg this isn't failing since the java generation was fixed. Any thing else to change?

**Review by veronicagg — APPROVED** [review]
looks good to merge

**Pull request merged**
