### PR TITLE
Updated new api version from 05-01 to 05-02

### PR DESCRIPTION
**Pull request by pauld-msft**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
```
Container Apps needed to create another api version "2023-05-01" that will be release before this, so we needed to update this so that there were no naming conflicts.
```

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by pauld-msft** [comment]
@Wzb123456789 is there a better way that I can update the API version? Container Apps needed to create another api version `"2023-05-01"` that will be released before this version, so we needed to update this so that there were no naming conflicts.

**Comment by raosuhas** [comment]
> @Wzb123456789 is there a better way that I can update the API version? Container Apps needed to create another api version `"2023-05-01"` that will be released before this version, so we needed to update this so that there were no naming conflicts.

@pauld-msft  Is the PR for the previous api version already available ? Can you please share that one so that we can chronologially review it and check the diffs across each version  ?

**Comment by raosuhas** [comment]
> > @Wzb123456789 is there a better way that I can update the API version? Container Apps needed to create another api version `"2023-05-01"` that will be released before this version, so we needed to update this so that there were no naming conflicts.
> 
> @pauld-msft Is the PR for the previous api version already available ? Can you please share that one so that we can chronologially review it and check the diffs across each version ?

Also the target branch says that this is the release branch for 05-01-preview .. is that expected ?

**Comment by pauld-msft** [comment]
> > @Wzb123456789 is there a better way that I can update the API version? Container Apps needed to create another api version `"2023-05-01"` that will be released before this version, so we needed to update this so that there were no naming conflicts.
> 
> @pauld-msft Is the PR for the previous api version already available ? Can you please share that one so that we can chronologially review it and check the diffs across each version ?

@raosuhas - pull request where this version was introduced: https://github.com/Azure/azure-rest-api-specs/pull/23697

Once the `05-01-2023` api version is released (which it [isn't yet](https://github.com/Azure/azure-rest-api-specs/tree/release-app-Microsoft.App-2023-04-01-preview)), I am planning on merging those changes into this branch.

**Comment by pauld-msft** [comment]
> > > @Wzb123456789 is there a better way that I can update the API version? Container Apps needed to create another api version `"2023-05-01"` that will be released before this version, so we needed to update this so that there were no naming conflicts.
> > 
> > 
> > @pauld-msft Is the PR for the previous api version already available ? Can you please share that one so that we can chronologially review it and check the diffs across each version ?
> 
> Also the target branch says that this is the release branch for 05-01-preview .. is that expected ?

Its expected for now, but I was planning on pushing to the [new branch](https://github.com/Azure/azure-rest-api-specs/tree/release-app-Microsoft.App-2023-05-02-preview) in the near future

**Comment by pauld-msft** [comment]
@raosuhas - i don't seem to have permissions to, but do you think that you could name this branch to `release-app-Microsoft.App-2023-05-02-preview`, while keeping all the branch restrictions the same?

**Pull request closed without merging**
