### PR TITLE
[Maps] Review request for to add version Render preview/2.1

### PR DESCRIPTION
**Pull request by chgennar**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/chgennar/azure-rest-api-specs/dev-maps-Microsoft.Maps-2.0-copyrights...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chgennar** [comment]
Note: July 5th release date for these new docs.

**Comment by tjprescott** [comment]
@chgennar I'm somewhat confused. The title says you are adding a new API version, but you checked the box for updating an existing version for a new feature. Can you clarify which scenario is correct?

**Comment by chgennar** [comment]
> @chgennar I'm somewhat confused. The title says you are adding a new API version, but you checked the box for updating an existing version for a new feature. Can you clarify which scenario is correct?

Sorry TJ, I initially thought this was an update to the current version but the tooling informed me that adding new APIs requires a version update. I corrected the form.

**Comment by chgennar** [comment]
Release Information: We'll be deploying these APIs the last week of June and want the documentation to go live July 5th.

**Comment by chgennar** [comment]
@tjprescott, do these changes require a review by the Architecture Board?

**Comment by tjprescott** [comment]
@chgennar if you don't meet any of the criteria in the breaking change section of the issue template, then no I don't think you need Arch Board review. @johanste correct me if I'm wrong.

**Comment by tjprescott** [comment]
@chgennar you will need to address the LintDiff failures though.

**Comment by johanste** [comment]
@tjprescott, we are finding the right set of people to address this. It is a special case where an existing REST API is "re-described" to better fit autorest/codegen and thus goes outside the "normal" process flow.

**Comment by chgennar** [comment]
@tjprescott The LintDiff errors are caused by a difference in description for the security definition of `azure_auth`. 

The expected description is:
```
Azure Active Directory OAuth2 Flow
```

Azure Maps' description is:
```
These are the [Azure Active Directory OAuth2](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-overview)  Flows. When paired with [Azure Role Based Access](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview)  control it can be used to control access to Azure Maps REST APIs. Azure Role based access controls are used to designate access to one or more Azure Maps resource account or sub-resources. Any user, group, or service principal can be granted access via a  built in role or a custom role composed of one or more permissions to Azure Maps REST APIs.\n\nTo implement scenarios we recommend viewing [authentication concepts](https://aka.ms/amauth). In summary, this security definition provides a solution  for modeling application(s) via objects capable of access control on specific APIs and scopes.\n\n#### Note\n* This security definition **requires** the use of the `x-ms-client-id` header to indicate which Azure Maps resource the application is requesting access to.  This can be acquired from the [Maps management API](https://aka.ms/amauthdetails).\n* The `Authorization URL` is specific to the Azure public cloud instance. Sovereign clouds have unique Authorization URLs and Azure Active directory configurations. \n* The Azure role based access control is configured from the [Azure management plane](https://aka.ms/amrbac) via Azure portal, Powershell, CLI, Azure SDKs, or REST APIs.\n* Usage of the [Azure Maps Web SDK](https://aka.ms/amaadmc) allows for configuration based setup of an application for multiple use cases.\n* Currently Azure Active Directory [v1.0](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison) tokens are supported.
```

Azure Maps uses the same description for `azure_auth` across all specs. We have some people working internally on updating our specs to follow best practices and align with the expectations of these checks. Is it possible to bypass or ignore some of these errors for this PR?

**Comment by markweitzel** [comment]
Meeting with API Stewardship board on 6-29-21. All changes approved.

**Review by markweitzel — APPROVED** [review]
API Stewardship Board on 6-29-21. Reviewed and approved.

**Comment by chgennar** [comment]
@tjprescott, is this PR able to be merged? We were hoping to have the documentation for these new APIs to go live the week of July 6th.

**Comment by chgennar** [comment]
@anuchandy,

I believe @tjprescott is OOO currently. Is this PR able to be merged in?

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@lmazuel could you merge this PR? CI failures are being worked on in another PR.

**Pull request merged**
