### PR TITLE
Remove the 2020-10-01-preview REST API version for redisEnterprise

### PR DESCRIPTION
**Pull request by TimLovellSmith**
1. The purpose is to cleanup obsolete rest api specifications. This is NOT a breaking change because this old *preview* api-version is  no longer used by anyone, now that the GA api-version is available, so we are really just removing old documentation and tidying up existing SDKs here.

2. Service-side api-version deprecation is pending removal any-time-now.

3. This swagger update can be published immediately.

4. If SDKs appear to support old preview REST API versions (such as GO and maybe RUBY), an update to them is desirable, i.e. unpublishing of old SDK versions, or publishing of new versions which don't mention the old API-version may be appropriate!

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify: deleting an old preview api version
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet. (See above)
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. (See above)
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [x] SDK of Go
      - [x] SDK of Ruby
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
Is Go SDK broken? I don't think this PR should have caused this error.

```
cmderr	[main.go] [ERROR] cannot open file /home/vsts/work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/services/classic/management/affinitygroup/CHANGELOG.md: open /home/vsts/work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/services/classic/management/affinitygroup/CHANGELOG.md: no such file
```...

**Review by greenms — APPROVED** [review]

**Comment by akning-ms** [comment]
Hi @TimLovellSmith , my few questions in line:

The purpose is to cleanup obsolete rest api specifications. This is NOT a breaking change because this old preview api-version is no longer used by anyone, now that the GA api-version is available, so we are really just removing old documentation and tidying up existing SDKs here.
>> how can we ensure nobody to use this existing version?  e.g you said it is already released with GO or Ruby SDK.
>> @ArcturusZhang to confirm
Service-side api-version deprecation is pending removal any-time-now.
>> will this version still support in service side for some time after swagger removed
>> according retirement policy, preview version need 3 months notice period to customer. refer to: https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews

**Comment by greenms** [comment]
It has not been released with Ruby SDK.  Here are all of the releases that use this old API version:
**GO**: https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/redisenterprise/mgmt/2020-10-01-preview/redisenterprise
**Python**: https://pypi.org/project/azure-mgmt-redisenterprise/1.0.0b1/
**.NET**: https://www.nuget.org/packages/Microsoft.Azure.Management.RedisEnterprise/1.0.0-preview
**PowerShell**: https://www.powershellgallery.com/packages/Az.RedisEnterpriseCache/0.1.0

There are newer releases for all 4 of the above that use our newest API version, so customer can upgrade.

**Comment by akning-ms** [comment]
Hi @TimLovellSmith, if in this case, recommend you keep this API version swagger. it is not block you to release new SDK version based on new GA API version.  ping me in teams if you need further discussion

**Comment by TimLovellSmith** [comment]
@akning-ms 
>how can we ensure nobody to use this existing version? e.g you said it is already released with GO or Ruby SDK.

I queried the ARM logs a while back. Nobody was using it. Also, that api-version won't work any more, we're turning it off!

But that isn't even the important part for deciding whether to take this PR. The important part to notice for deciding whether to accept this PR is to consider is our desire that people no longer know about the old api version, and e.g. *try* to use the SDK.

We want them to avoid people seeing that it still *looks like* an officially supported version. I.e. the point of this PR is to get docs updated, and SDKs removed, to block any incoming flow of new people trying to come in and use an old, deprecated api version, as part of us really finishing deprecating it.

>it is not block you to release new SDK version based on new GA API version. ping me in teams if you need further discussion

You are right, this PR doesn't block us for anything. But we would like to do it soon if possible. This is part of our work to clean up the old api-version, which we are in the process of removing. Getting it done will reflect on the accuracy and up-to-date-ness of Microsoft's documentation.

**Comment by ArcturusZhang** [comment]
It is OK for Go SDK because the removed package is a preview one, and we have another package for this RP as a replacement

**Pull request closed without merging**
