### PR TITLE
Media Services Resource Provider API refresh

### PR DESCRIPTION
**Pull request by BrianBlum**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/740)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BrianBlum__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brianbl). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by fearthecowboy** [comment]
Hi @BrianBlum 

Before we start reviewing your PR, can I ask that you ensure that you've run thru the steps in the checklist at the top of this PR and check off that you've completed all the steps?

Thanks!

**Comment by BrianBlum** [comment]
Hi @fearthecowboy 
I have reviewed the checklist. I reached out to Amar earlier this week about squashing commits, but didn't hear back so I did left the commits as is. Did you have a specific concern?

**Comment by fearthecowboy** [comment]
@BrianBlum  no, nothing specific, but  we've had a rash of people sending us a PR, without doing the basic checks, and we end up going thru the process of verifying things that are explained in the guidelines.

This has started to put a heavier burden on the reviewers so, we've added the PR checklist and are starting to require that it's completed before we start reviewing, in an attempt to make sure that we're not doing the work that the tools are there to avoid 😄 

Once you've checked off all the items, I can assign it to a reviewer and we can get thru the process as quick as we can.

**Comment by amarzavery** [comment]
Status update: Examples in the spec, passed the model validator check
```
D:\sdk\openapi-validation-tools>node validate.js example https://raw.githubusercontent.com/Azure/azure-rest-api-specs/27aeb8bf538fb2846c4f71afa78a7304e182996e/arm-mediaservices/2015-10-01/swagger/media.json --json

> Validating "examples" and "x-ms-examples" in https://raw.githubusercontent.com/Azure/azure-rest-api-specs/27aeb8bf538fb2846c4f71afa78a7304e182996e/arm-mediaservices/2015-10-01/swagger/media.json:


> No Errors were found.

> Detailed Validation Result:

{ validityStatus: true,
  'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/27aeb8bf538fb2846c4f71afa78a7304e182996e/arm-mediaservices/2015-10-01/swagger/media.json':
   { validityStatus: true,
     operations:
      { MediaService_CheckNameAvailability:
         { 'example-in-spec':
            { parameters:
               { CheckNameAvailabilityInput:
                  { isValid: true,
                    result: 'The example for body parameter CheckNameAvailabilityInput with reference #/definitions/CheckNameAvailabilityInput in operation "MediaService_CheckNameAvailability" is valid.' } },
              responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_CheckNameAvailability" is valid.' } } } },
        MediaService_ListByResourceGroup:
         { 'example-in-spec':
            { responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_ListByResourceGroup" is valid.' } } } },
        MediaService_Get:
         { 'example-in-spec':
            { responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_Get" is valid.' } } } },
        MediaService_Create:
         { 'example-in-spec':
            { parameters:
               { MediaService:
                  { isValid: true,
                    result: 'The example for body parameter MediaService with reference #/definitions/MediaService in operation "MediaService_Create" is valid.' } },
              responses:
               { '201':
                  { isValid: true,
                    result: 'The example for response with statusCode "201" in operation "MediaService_Create" is valid.' } } } },
        MediaService_Delete: {},
        MediaService_Update:
         { 'example-in-spec':
            { parameters:
               { MediaService:
                  { isValid: true,
                    result: 'The example for body parameter MediaService with reference #/definitions/MediaService in operation "MediaService_Update" is valid.' } },
              responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_Update" is valid.' } } } },
        MediaService_RegenerateKey:
         { 'example-in-spec':
            { parameters:
               { RegenerateKeyInput:
                  { isValid: true,
                    result: 'The example for body parameter RegenerateKeyInput with reference #/definitions/RegenerateKeyInput in operation "MediaService_RegenerateKey" is valid.' } },
              responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_RegenerateKey" is valid.' } } } },
        MediaService_ListKeys:
         { 'example-in-spec':
            { responses:
               { '200':
                  { isValid: true,
                    result: 'The example for response with statusCode "200" in operation "MediaService_ListKeys" is valid.' } } } },
        MediaService_SyncStorageKeys:
         { 'example-in-spec':
            { parameters:
               { SyncStorageKeysInput:
                  { isValid: true,
                    result: 'The example for body parameter SyncStorageKeysInput with reference #/definitions/SyncStorageKeysInput in operation "MediaService_SyncStorageKeys" is valid.' } } } } } } }

> Validation Complete.

D:\sdk\openapi-validation-tools>
```

**Review by amarzavery — APPROVED** [review]

**Comment by BrianBlum** [comment]
Thanks Amar!

**Comment by lmazuel** [comment]
@amarzavery @BrianBlum This PR broke the SDK because name_availability is incorrect.
Format returned by service:
```json
{"NameAvailable":true,"Reason":null,"Message":null}
```

This PR incorrectly changed from NameAvailable to nameAvailable in the Swagger.

**Comment by BrianBlum** [comment]
Sorry Laurent,

The updated API was supposed to be released, but there was a delay.

I’ll submit a new PR to revert the name until we release the SDK.

**Review by Shahinbagerzadsaid — CHANGES_REQUESTED** [review]
Alibagerzadsaid8@gmail.com

**Comment by ihsanali01** [comment]
> [Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/896

Thanks for helpping me out of this problem. I really am very thankful to you all including "GitHub's Team, Microsoft's Teams, Microsoft's Azure & Team".
Grateful to you all.
Regards,
#ihsan-ihsan@ihsanalikapahi.io,
#ihsan@ihsanalikapahi.io(0),
#MUHAMMADIHSANALI,
#IH.
[image]=[image]=[image].

**Pull request merged**
