### PR TITLE
typo: Microsoft.ApiManagement

### PR DESCRIPTION
**Pull request by nschonni**
- reponse -> response
- succesfully -> successfully
- Successfull -> Successful
- Double word "the"
- GeoGraphy -> geography
- secconds -> seconds
- agregation -> aggregation
- succesful -> successful
- HttpStatusCode.Unauthorize -> HttpStatusCode.Unauthorized
- fullfilled -> fulfilled
- specificied -> specified
- productid -> productId
- appplying -> applying
- assosiated -> associated
- Storename -> StoreName
- Managemet -> Management
- outcoming -> outgoing
- queruering -> querying
- Countery -> Counter
- Subsctions -> Subscriptions
- groupid -> groupId
- subid -> subscriptionId
- dignostic -> diagnostic
- settigs -> settings
- concent -> consent
- fescription -> description
- Reconect -> Reconnect

### CODE REVIEW

**Comment by nschonni** [comment]
Tried adding the fixes for #4595 to see if that was the solution for "Breaking Changes" failing. Didn't seem to help so I can rebase out the commit if you want

**Comment by nschonni** [comment]
Removed all changes to "Microsoft.ApiManagement/stable/2017-03-01/apimapis.json" since it was failing the Breaking Change tests. I'll leave that for #4595

**Review by solankisamir — APPROVED** [review]
Looks good

**Review by hovsepm — APPROVED** [review]

**Comment by nschonni** [comment]
@hovsepm @solankisamir does it makes sense that there was nothing for the Java SDK built?

**Comment by hovsepm** [comment]
@nschonni Java build may not be properly configured in some services.

**Comment by nschonni** [comment]
@hovsepm thanks for clarifying!

**Pull request merged**
