### PR TITLE
[EventHub] Readme pkg Tag Updated

### PR DESCRIPTION
**Pull request by schaudhari6254888**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by schaudhari6254888** [comment]
According to [rule](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md#3-readme-tag-to-be-released), your Readme Tag is package-2024-01, but in [readme.md](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager#basic-information) it is still package-2024-05-preview, So I am modifying the readme.md file, because it is blocking the SDK generation

**Comment by raosuhas** [comment]
no arm review required here

**Review by raosuhas — APPROVED** [review]

**Pull request merged**
