### PR TITLE
Downgraded the version of ManagedInstances to generate .Net SDK for sql/resource manager

### PR DESCRIPTION
**Pull request by guptaayush007**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by guptaayush007** [comment]
It's a PR for Control Plane (ARM) API, not sure why i'am not able to update the template.

**Review by ericshape — APPROVED** [review]

**Comment by rkmanda** [comment]
Please wait for the ARM review to get over and request a merge after you see an ARMSignedOff label against the PR

**Comment by guptaayush007** [comment]
since i'am unable to modify the description above, posting the link to my previous similar PR https://github.com/Azure/azure-rest-api-specs/pull/28976 , which had similar changes

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
