### PR TITLE
Remove generation settings from swagger

### PR DESCRIPTION
**Pull request by mcardosos**
cc @olydis

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by salameer** [comment]
@mcardosos can you give a bit more context on why are you suggesting these changes?

@kirthik  and @jianghaolu  if we decide to go with these changes, should we be contacting the infrastructure insights folks about it?

**Comment by salameer** [comment]
I guess also @jianghaolu  and @mcardosos what would be the impact of that?

**Comment by mcardosos** [comment]
@salameer Currently this settings cause incorrect generated code for the go SDK (they override the arguments I pass to autorest). This settings should be included in the md file instead.

**Comment by mcardosos** [comment]
Looking at this more closely, the only setting that truly affects codegen for Go is the namespace setting. Still, I think this settings belong in the config file.

**Review by jianghaolu — APPROVED** [review]

**Pull request merged**
