### PR TITLE
Remove 4xx responses and change schema to file

### PR DESCRIPTION
**Pull request by vrdmr**
Removing the 4xx response codes and changing the schema from string to file to unblock the SDK serialization issue.
FYI: @najams @shahabhijeet 

----
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by hovsepm** [comment]
@vrdmr could you provide some context on what does it mean "unblock the SDK serialization issue."? As for current status of your PR - you are introducing breaking changes to stable API version.

**Comment by hovsepm** [comment]
@vrdmr the issue you pointed out in Slack channel is about "2017-05-15-preview" version - why do you have breaking changes in version 2015-10-31 which is marked as stable and I assume was shipped?

**Comment by vrdmr** [comment]
@hovsepm The #2466 PR made the changes in bot 2015-10-31 (Runbooks) and 2017-05-15-preview (Jobs) resources. For the `GetContent` call in the `runbooks.json` resource, the change was added in #2466 ([Link to Blame](https://github.com/Azure/azure-rest-api-specs/blame/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json#L83)).

**Comment by vrdmr** [comment]
Ping @hovsepm.

**Comment by hovsepm** [comment]
@vrdmr I'm asking about service response changes - in many places your change removes 409 return codes. These are new breaking changes in the existing stable API version.

**Comment by vrdmr** [comment]
@hovsepm Yes, we are removing 409 here and other places as in the SDKs, they are being returned as successful and not generating exceptions, which they should. This was caught by @dsgouda in the [AzureSDK PR](https://github.com/Azure/azure-sdk-for-net/pull/4521#discussion_r199641076). We do want exceptions being thrown for an error case, whereas currently, it would not raise for any.

**Comment by hovsepm** [comment]
@vrdmr you do realize that there are many applications that are already shipped using API version 2015-10-31 that do use 409 as return code and have some logic to handle that return codes. Changing it to throw an exception will cause breaks for any patch in the code that will use latest generated SDK. I'd strongly suggest to change return types to exception only in the new/preview API version.

**Comment by vrdmr** [comment]
@hovsepm Updated the Spec. Could you please review and merge this PR.

Thanks,
Varad

**Comment by hovsepm** [comment]
@vrdmr please fix model validation errors:
```
[]
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get Job Output" in operation "Job_GetOutput".:\n',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ],
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: 
   [ { code: 'RESPONSE_VALIDATION_ERROR',
       id: 'OAV108',
       message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get Job Output" in operation "Job_GetOutput".',
       innerErrors: 
        [ { code: 'INVALID_RESPONSE_BODY',
            errors: 
             [ { code: 'INVALID_TYPE',
                 params: [ 'file', 'string' ],
                 message: 'Expected type file but found type string',
                 path: [] } ],
            message: 'Invalid body: Expected type file but found type string',
            path: [] } ] } ],
  [Symbol(message)]: '{"code":"RESPONSE_VALIDATION_ERROR","id":"OAV108","message":"Found errors in validating the response with statusCode \\"200\\" for x-ms-example \\"Get Job Output\\" in operation \\"Job_GetOutput\\".:\\n","innerErrors":[{"code":"INVALID_RESPONSE_BODY","errors":[{"code":"INVALID_TYPE","params":["file","string"],"message":"Expected type file but found type string","path":[]}],"message":"Invalid body: Expected type file but found type string","path":[]}],"level":"error"}' }
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get Job Runbook Content" in operation "Job_GetRunbookContent".:\n',
  innerErrors: 
   [ { code: 'INVALID_CONTENT_TYPE',
       message: 'Invalid Content-Type (text/powershell).  These are supported: application/json',
       path: [] },
     { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ],
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: 
   [ { code: 'RESPONSE_VALIDATION_ERROR',
       id: 'OAV108',
       message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get Job Runbook Content" in operation "Job_GetRunbookContent".',
       innerErrors: 
        [ { code: 'INVALID_CONTENT_TYPE',
            message: 'Invalid Content-Type (text/powershell).  These are supported: application/json',
            path: [] },
          { code: 'INVALID_RESPONSE_BODY',
            errors: 
             [ { code: 'INVALID_TYPE',
                 params: [ 'file', 'string' ],
                 message: 'Expected type file but found type string',
                 path: [] } ],
            message: 'Invalid body: Expected type file but found type string',
            path: [] } ] } ],
  [Symbol(message)]: '{"code":"RESPONSE_VALIDATION_ERROR","id":"OAV108","message":"Found errors in validating the response with statusCode \\"200\\" for x-ms-example \\"Get Job Runbook Content\\" in operation \\"Job_GetRunbookContent\\".:\\n","innerErrors":[{"code":"INVALID_CONTENT_TYPE","message":"Invalid Content-Type (text/powershell).  These are supported: application/json","path":[]},{"code":"INVALID_RESPONSE_BODY","errors":[{"code":"INVALID_TYPE","params":["file","string"],"message":"Expected type file but found type string","path":[]}],"message":"Invalid body: Expected type file but found type string","path":[]}],"level":"error"}' }
{ AssertionError [ERR_ASSERTION]: swagger "specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/job.json" contains model validation errors.
    at Context.<anonymous> (/home/travis/build/Azure/azure-rest-api-specs/test/model.js:20:16)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook draft content" in operation "RunbookDraft_GetContent".:\n',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ],
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: 
   [ { code: 'RESPONSE_VALIDATION_ERROR',
       id: 'OAV108',
       message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook draft content" in operation "RunbookDraft_GetContent".',
       innerErrors: 
        [ { code: 'INVALID_RESPONSE_BODY',
            errors: 
             [ { code: 'INVALID_TYPE',
                 params: [ 'file', 'string' ],
                 message: 'Expected type file but found type string',
                 path: [] } ],
            message: 'Invalid body: Expected type file but found type string',
            path: [] } ] } ],
  [Symbol(message)]: '{"code":"RESPONSE_VALIDATION_ERROR","id":"OAV108","message":"Found errors in validating the response with statusCode \\"200\\" for x-ms-example \\"Get runbook draft content\\" in operation \\"RunbookDraft_GetContent\\".:\\n","innerErrors":[{"code":"INVALID_RESPONSE_BODY","errors":[{"code":"INVALID_TYPE","params":["file","string"],"message":"Expected type file but found type string","path":[]}],"message":"Invalid body: Expected type file but found type string","path":[]}],"level":"error"}' }
{ code: 'RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE',
  id: 'OAV111',
  message: 'Following response status codes "200" for operation "RunbookDraft_ReplaceContent" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.',
  innerErrors: undefined,
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '{"code":"RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE","id":"OAV111","message":"Following response status codes \\"200\\" for operation \\"RunbookDraft_ReplaceContent\\" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.","level":"error"}' }
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Create or update runbook draft" in operation "RunbookDraft_ReplaceContent".:\n',
  innerErrors: 
   [ { code: 'RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE',
       id: 'OAV111',
       message: 'Following response status codes "200" for operation "RunbookDraft_ReplaceContent" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.',
       innerErrors: undefined,
       level: 'error',
       [Symbol(level)]: 'error',
       [Symbol(message)]: '{"code":"RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE","id":"OAV111","message":"Following response status codes \\"200\\" for operation \\"RunbookDraft_ReplaceContent\\" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.","level":"error"}' } ],
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: 
   [ { code: 'RESPONSE_VALIDATION_ERROR',
       id: 'OAV108',
       message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Create or update runbook draft" in operation "RunbookDraft_ReplaceContent".',
       innerErrors: 
        [ { code: 'RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE',
            id: 'OAV111',
            message: 'Following response status codes "200" for operation "RunbookDraft_ReplaceContent" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.',
            innerErrors: undefined,
            level: 'error',
            [Symbol(level)]: 'error',
            [Symbol(message)]: '{"code":"RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE","id":"OAV111","message":"Following response status codes \\"200\\" for operation \\"RunbookDraft_ReplaceContent\\" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.","level":"error"}' } ] } ],
  [Symbol(message)]: '{"code":"RESPONSE_VALIDATION_ERROR","id":"OAV108","message":"Found errors in validating the response with statusCode \\"200\\" for x-ms-example \\"Create or update runbook draft\\" in operation \\"RunbookDraft_ReplaceContent\\".:\\n","innerErrors":[{"code":"RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE","id":"OAV111","message":"Following response status codes \\"200\\" for operation \\"RunbookDraft_ReplaceContent\\" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.","level":"error"}],"level":"error"}' }
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook content" in operation "Runbook_GetContent".:\n',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ],
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(splat)]: 
   [ { code: 'RESPONSE_VALIDATION_ERROR',
       id: 'OAV108',
       message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook content" in operation "Runbook_GetContent".',
       innerErrors: 
        [ { code: 'INVALID_RESPONSE_BODY',
            errors: 
             [ { code: 'INVALID_TYPE',
                 params: [ 'file', 'string' ],
                 message: 'Expected type file but found type string',
                 path: [] } ],
            message: 'Invalid body: Expected type file but found type string',
            path: [] } ] } ],
  [Symbol(message)]: '{"code":"RESPONSE_VALIDATION_ERROR","id":"OAV108","message":"Found errors in validating the response with statusCode \\"200\\" for x-ms-example \\"Get runbook content\\" in operation \\"Runbook_GetContent\\".:\\n","innerErrors":[{"code":"INVALID_RESPONSE_BODY","errors":[{"code":"INVALID_TYPE","params":["file","string"],"message":"Expected type file but found type string","path":[]}],"message":"Invalid body: Expected type file but found type string","path":[]}],"level":"error"}' }
```

**Comment by hovsepm** [comment]
@vrdmr ignore the error.

**Review by hovsepm — APPROVED** [review]

**Pull request merged**
