### PR TITLE
Adding 7.2-preview version

### PR DESCRIPTION
**Pull request by vasanthrajams**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by Lusitanian** [comment]
as discussed, rbac + aes + full backup/restore should be included in this PR - those things should subsequently be removed from 7.1. then we're in good shape :)

**Comment by heaths** [comment]
I forgot to add in my task list, also modify data-plane/readme.md to add this 7.2-preview package as well. Use the 7.1-preview as a template (but add, don't replace).

**Review by heaths — CHANGES_REQUESTED** [review]
Also, you'll need to add an exemption to cSpell.json in the root. Find the 7.1-preview exemption I did. It can't be fixed, as that would be a breaking change.

**Review by heaths — CHANGES_REQUESTED** [review]
The 7.1 version is missing. The remove branch is not correct. Did you pull from origin before rebasing this but then push the old branch?

**Review by heaths — APPROVED** [review]
Changes look good now, but do not merge until we take an update from the dev-keyvault-Microsoft.KeyVault-7.1 branch.

**Comment by heaths** [comment]
Actually, we can merge this before the 7.1-preview changes and just put those into the 7.2-preview branch when ready (soon). Let me reach out to the admins since we can't work around or fix the modelvalidation errors.

**Pull request merged**
