### PR TITLE
ServiceBus: Added 2 properties to Subscription

### PR DESCRIPTION
**Pull request by v-Ajnava**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@ravbhatnagar - the PR adds two new properties to an existing model in a released api version. Please take a look.

**Comment by ravbhatnagar** [comment]
New settable properties should be added in a new api-version.

**Comment by anuchandy** [comment]
@v-Ajnava any response for @ravbhatnagar comment?  the two new properties `forwardTo` and `forwardDeadLetteredMessagesTo` are something user can set, which is a breaking change, those should be introduced as part of new api version.

**Comment by v-Ajnava** [comment]
@anuchandy, will discuss with Arun and will let you know. an FYI,  Properties added in Subscription entity in the current PR were missed in the Previous PR https://github.com/Azure/azure-rest-api-specs/pull/2029 were we have added these in Queue entity, which is merged.

**Comment by anuchandy** [comment]
@simongdavies, please refer the email from @salameer with subject "RE: Question on this GitHub review comment", can you sign-off from ARM side?

**Comment by anuchandy** [comment]
@v-Ajnava, @arundsouza, @salameer -  Merging this PR based on the email discussion ["RE: Question on this GitHub review comment", From: Arun Dsouza].

In Service Bus land, queue and topic-subscription are symmetrical. The properties `forwardTo` and `forwardDeadLetteredMessagesTo` already exists for queue resource and it is wired to not have them for subscription resource. This PR ensure topic-subscription is on par with queue.

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
Bypassing ARM review due to no response to avoid delaying the service team. ARM team feel free to follow up with Swagger author for any future comments

**Pull request merged**
