### PR TITLE
[AKS] Swagger Bugfix: upgradeNodeImageVersion should be an agent pools operation

### PR DESCRIPTION
**Pull request by gtxistxgao**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

"Upgrade Node Image Version" API is under "Managed Clusters" tab, which is wrong as it is an agent pool only operation. So it should be in "Agent Pools" tag. The python SDK also put it under "ManagedClustersOperations".

I made a mistake in the swagger PR that put a "ManagedClusters" before it. https://github.com/Azure/azure-rest-api-specs/pull/10294

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by NullMDR** [comment]
@gtxistxgao Is there any SDK related to these API versions?

**Comment by marwanad** [comment]
There are published Go and python SDKs for that. 

I think this should classify as a bug fix and not a breaking change.

**Comment by changlong-liu** [comment]
Hi @gtxistxgao  Python SDK have been released as stable:https://pypi.org/project/azure-mgmt-containerservice/9.4.0/

This PR will bring breaking change in SDK, I don't think we can do this unnecessary change in a released stable SDK.

**Comment by gtxistxgao** [comment]
> Hi @gtxistxgao Python SDK have been released as stable:https://pypi.org/project/azure-mgmt-containerservice/9.4.0/
> 
> This PR will bring breaking change in SDK, I don't think we can do this unnecessary change in a released stable SDK.

This is not an unnecessary change. The operation stays in a different operation client in python API. It will bring potential risk to customer's implementation when they upgrade to a later version SDK when we corrected this bug. The node image upgrade is still a preview feature at this point. We can generated a 9.4.1 version as bug fix.

**Comment by marwanad** [comment]
@NullMDR can you help take a look and merge the PR?

**Comment by changlong-liu** [comment]
> his point. We

Hi @gtxistxgao , @marwanad ,
I don't deny to merge this PR if service side think it's necessary. But the coming Python SDK should be 10.0.0 for below reasons:
   1. It will break customer code. 
   2. it's already in a stable api-version/SDK version.

**Comment by PhoenixHe-msft** [comment]
Discussed offline. Python SDK will bump major version

**Review by PhoenixHe-NV — APPROVED** [review]

**Pull request merged**
