### PR TITLE
[Cognitive Services - Language - Text API] Enable resolutions for Named Entity Recognition

### LINKED ISSUE #20051: [Cognitive Services - Language - Text API] <2022-10-01-preview>
Service name: Azure Cognitive Service for Language
Key contact for the review:

- Model-Version fallback strategy override - Mikael Sitruk <mikael.sitruk@microsoft.com>
- LD Script Detection - Parag Agrawal <paragag@microsoft.com>
- LD runner up languages - DRI TBD
- [CT] OOS - Nourhan Farid <nourhanfarid@microsoft.com>
- KPE update (minor, position and importance ranking - maxKPE) - Yash Oswal <Yash.Oswal@microsoft.com>
- Abstractive Text Summarization - Yuantao Wang <yuantw@microsoft.com>
- API Contract change to support deprecation message as warning - Lakshmanan Ramu Meenal <Lakshmanan.Ramu@microsoft.com>
- Adding quota error codes in response and retry header - Nourhan Farid <nourhanfarid@microsoft.com>
- Async Job Deletion - Abby Hartman <Abigail.Hahn@microsoft.com>
- [Auto LD] renaming the 'detectedLanguage' attribute in result to something more generic (like: 'languageCode') - Nourhan Farid <nourhanfarid@microsoft.com>
- [Auto LD] Include the detected language even in case of unsupported language error for tasks - Nourhan Farid <nourhanfarid@microsoft.com>

Whether this is a new or existing API: Existing API
Whether or not your service already been deployed: Yes
A brief description of the material to be reviewed/changed: We are adding new features for the October API, including Model-Version fallback strategy override, LD Script Detection, LD runner up languages, [CT] OOS, KPE update (minor, position and importance ranking - maxKPE), Abstractive Text Summarization, API contract change to support deprecation message as warning, Adding quota error codes in response and retry header, Async job deletion, [Auto LD]  renaming the 'detectedLanguage' attribute in result to something more generic (like: 'languageCode'), and [Auto LD] Include the detected language even in case of unsupported language error for tasks

A link to the PR/issue in the azure-rest-api-specs (public)  or azure/azure-rest-api-specs-pr (private) repo
PR: #20371

### PR DESCRIPTION
**Pull request by bidisha-c**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue: https://github.com/Azure/azure-rest-api-specs/issues/20051

Is this review for (select one):

- [ ] a private preview
- [X] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by abhahn — APPROVED** [review]
LGTM!

**Review by heaths — APPROVED** [review]
Verified the deleted and added are exactly the same.

**Review by deyaaeldeen — APPROVED** [review]
@bidisha-c should the output of PII also updated from the plain entities to the new ones?

**Comment by bidisha-c** [comment]
> @bidisha-c should the output of PII also updated from the plain entities to the new ones?

No for now resolutions are only being added for NER. For PII it might not be essential to resolve to a PII entity to a normalized value as the objective of the service is to detect the PII and redact PII.

**Pull request merged**
