### PR TITLE
monitor/dataCollectionRules add facilityNames enum

### PR DESCRIPTION
**Pull request by teowa**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

</details>

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - Add enum value, Intentionally sent wrong value in facility Name the API will return all the possible values:
```
2023-11-27T03:15:06.981Z [DEBUG] provider.terraform-provider-azapi_v1.10.0: Nov 27 03:15:06.981439 Request: ==> OUTGOING REQUEST (Try=1)
   PUT https://management.azure.com/subscriptions/<sub-id>/resourceGroups/dcr-rg/providers/Microsoft.Insights/dataCollectionRules/dcr?api-version=2019-11-01-preview
   Accept: application/json
   Authorization: REDACTED
   Content-Length: 820
   Content-Type: application/json
   User-Agent: HashiCorp Terraform/1.5.5 (+https://www.terraform.io) Terraform Plugin SDK/2.8.0 terraform-provider-azapi/v1.10.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
   X-Ms-Correlation-Request-Id: 81234077-63ba-dad3-c4fe-265bf96af33c
   --------------------------------------------------------------------------------
{"location":"westus","properties":{"dataFlows":[{"destinations":["VMInsightsPerf-Logs-Dest"],"streams":["Microsoft-InsightsMetrics"]},{"destinations":["VMInsightsPerf-Logs-Dest"],"streams":["Microsoft-ServiceMap"]}],"dataSources":{"performanceCounters":[{"counterSpecifiers":["\\VmInsights\\DetailedMetrics"],"name":"VMInsightsPerfCounters","samplingFrequencyInSeconds":60,"streams":["Microsoft-InsightsMetrics"]}],"syslog":[{"facilityNames":["alerts"],"logLevels":["*"],"name":"testsyslog","streams":["Microsoft-Syslog"]}]},"description":"Data collection rule for VM Insights.","destinations":{"logAnalytics":[{"name":"VMInsightsPerf-Logs-Dest","workspaceResourceId":"/subscriptions/<sub-id>/resourceGroups/dcr-rg/providers/Microsoft.OperationalInsights/workspaces/wt-example-workspace"}]}}}
   --------------------------------------------------------------------------------: timestamp=2023-11-27T03:15:06.981Z
2023-11-27T03:15:08.943Z [DEBUG] provider.terraform-provider-azapi_v1.10.0: Nov 27 03:15:08.942161 Response: ==> REQUEST/RESPONSE (Try=1/1.960605724s, OpTime=1.960655824s) -- RESPONSE RECEIVED
   PUT https://management.azure.com/subscriptions/<sub-id>/resourceGroups/dcr-rg/providers/Microsoft.Insights/dataCollectionRules/dcr?api-version=2019-11-01-preview
   Accept: application/json
   Authorization: REDACTED
   Content-Length: 820
   Content-Type: application/json
   User-Agent: HashiCorp Terraform/1.5.5 (+https://www.terraform.io) Terraform Plugin SDK/2.8.0 terraform-provider-azapi/v1.10.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
   X-Ms-Correlation-Request-Id: 81234077-63ba-dad3-c4fe-265bf96af33c
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Api-Supported-Versions: REDACTED
   Cache-Control: no-cache
   Content-Length: 412
   Content-Type: application/json
   Date: Mon, 27 Nov 2023 03:15:07 GMT
   Expires: -1
   Pragma: no-cache
   Request-Context: REDACTED
   Strict-Transport-Security: max-age=31536000; includeSubDomains
   X-Cache: REDACTED
   X-Content-Type-Options: nosniff
   X-Ms-Client-Request-Id: 20117a16-bc34-4b37-88c6-a989764f59f9
   X-Ms-Correlation-Request-Id: 81234077-63ba-dad3-c4fe-265bf96af33c
   X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: REDACTED
   X-Ms-Request-Id: e9c3510a-bc0d-488c-84ac-bc99a42bd7dd
   X-Ms-Routing-Request-Id: JAPANEAST:20231127T031507Z:c75e2e15-c15b-422c-842d-3e0a2fab4679
   X-Msedge-Ref: REDACTED
   --------------------------------------------------------------------------------
{"error":{"code":"InvalidPayload","message":"Data collection rule is invalid","details":[{"code":"InvalidDataSource","message":"'Facility Names' item 0 must have one of the allowed values: auth,authpriv,cron,daemon,kern,lpr,mail,mark,news,syslog,user,uucp,ftp,ntp,audit,alert,local0,local1,local2,local3,local4,local5,local6,local7,clock,nopri,*.","target":"Properties.DataSources.Syslog[0].FacilityNames[0]"}]}}

```

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the Diagram Step 2, "ARM API changes Review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

</details>

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by teowa** [comment]
@kazrael2119, do you know who to at for `Swagger BreakingChange` approval, the PR don't have the `BreakingChangeReviewRequired` tag.

**Comment by kazrael2119** [comment]
> @kazrael2119, do you know who to at for `Swagger BreakingChange` approval, the PR doesn't have the `BreakingChangeReviewRequired` tag.

please ask breaking change review board to get approval, I think this should be approved by them first because breaking change check got error

**Comment by ms-henglu** [comment]
Please get a breaking changes approval from Azure Breaking Changes Reviewers <azbreakchangereview@microsoft.com> and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

**Review by ms-henglu — APPROVED** [review]

**Pull request merged**
