### PR TITLE
[Hub Generated] Review request for Microsoft.BotService to add version preview/2021-05-01-preview

### PR DESCRIPTION
**Pull request by zhixzhan**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/zhixzhan/azure-rest-api-specs/dev-botservice-Microsoft.BotService-2021-05-01-preview-zhixzhan...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [x] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zhixzhan** [comment]
Suppose to fix S360 issues:
 
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=32BC3A6E-EC4B-4FB5-9FE0-1975C1881A29
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=C3FBCE39-1504-449E-A6F5-9A565D831F11
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=345D0740-2265-4B4A-BABE-CD649E4AFF6D
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=F7618D5A-ADCB-4D21-B163-94BA8FE5E6FF
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=0303D533-C334-4880-8559-5585B7C32C7A
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=5F6882E3-5338-492B-8CA4-530981DE1423
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=59D80C39-3BF8-40E7-8D19-BD8850356206
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=8FB25EF9-930E-415E-B22F-6972D33566B2  (partial)
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=DF2D614F-C81C-406C-BF53-74173A336EE5
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=A7FDE068-6FAE-4756-B2C1-5DAE70CC86BF
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=DBE18089-CBB4-4D11-9B72-A9BDF5F82C2C
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=DDC42693-69BC-4C0C-B73E-D0FED3DAE640  (partial)
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=5EE8EF8E-8B05-4DB8-88B6-2324A37DEF12

**Comment by chunyu3** [comment]
@zhixzhan The changes break the Test in azure-sdk-for-net repo which cause 'SDK azure-sdk-for-net' check fail. would you please update the tests? thanks

**Comment by zhixzhan** [comment]
Hi @chunyu3, I think the failure will always happen when breaking change detected compared to other merged PR.

**Comment by msyyc** [comment]
approve for python breaking change.

**Review by chunyu3 — APPROVED** [review]

**Pull request merged**
