### PR TITLE
Updating managed database swagger

### PR DESCRIPTION
**Pull request by v-djnisi**
### Latest improvements:
I am currently working on restorable dropped databases for Managed Instance. I noticed that swagger on azure-rest-api-specs is outdated compared to the swagger we have on our enlistment. 

This swagger contains restorableDroppedDatabaseId as property, which is necessary for my PowerShell feature.

</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@v-djnisi this feature is already live?

**Comment by v-djnisi** [comment]
Yes, there was a PR for restorable dropped databases on MI couple of months ago. However since this only affects .Net clients, and since they weren't a priority nobody from team noticed this disparity. My guess is that we forgot to add ManagedDatabases swagger to the RestorableDropped PR. Hope this isn't a problem.

**Comment by v-djnisi** [comment]
Clicked Close by mistake, sorry.

**Comment by jhendrixMSFT** [comment]
No worries just want to make sure the functionality is available before merging.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
