### PR TITLE
Add CODEOWNERS entry for FarmBeats

### PR DESCRIPTION
**Pull request by mikekistler**
This PR adds an entry to the CODEOWNERS file for the AgriFood/FarmBeats service.

### CODE REVIEW

**Comment by mikekistler** [comment]
@akning-ms @raych1 @lirenhe Could someone please merge this PR or request changes?

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
@mikekistler, could you follow https://github.com/microsoft/ContributorLicenseAgreement/issues/54#issuecomment-1279359244 to solve the 'license/cla' issue?  This is currently blocking the merge of this PR.  thanks

**Comment by mikekistler** [comment]
@lirenhe What is the "license/cla" issue? The PR check is showing successful:

image

**Comment by lirenhe** [comment]
> @lirenhe What is the "license/cla" issue? The PR check is showing successful:


The merging is blocked.

image

**Pull request merged**
