### PR TITLE
DevTestLabs version 2016-05-15

### PR DESCRIPTION
**Pull request by iouri-s**

### CODE REVIEW

**Comment by markcowl** [comment]
@iouri-s you will want to check out :  https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-odata

for operatiosn that use odata queries.  There is some nice OM for generating query strings using Linq expressions in .Net and some other languages.

**Comment by markcowl** [comment]
>                         "name": "$filter",

consider using x-ms-odata, see: [https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-odata](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-odata)

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:21 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by iouri-s** [comment]
@markcowl - we _are_ using x-ms-odata

**Comment by markcowl** [comment]
>                         "type": "integer",

Description

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:31 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                         "type": "string"

Description

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:38 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "Lab_ListBySubscription",

This will eventually become documentation, so please provide a description of exactly what is is the user is listing.

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:15 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "Lab_ListByResourceGroup",

same comment

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:61 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                         "type": "integer",

Parallel comments on each of these - I know these are standard parameters, but this becomes stand-alone documentation for the REST APIs.

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:84 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "ArtifactSource_List",

More descriptive as to what artifact sources are.

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:114 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "Artifact_GenerateArmTemplate",

nice!

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:293 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                         "required": true,

Do examples make sense in the description?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:316 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "tags": [ "ArtifactSource" ],

Is this an asynchronous PUT?Should it be decorated with x-ms-long-running?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:392 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "Cost_GetResource",

Additional description.  Description of cost and scope of cost.

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:539 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                         "required": true,

??  what is meant by the name of the cost?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:562 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "operationId": "CustomImage_List",

More detail, what kind of custom images?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:584 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                 "tags": [ "Formula" ],

Not asynchronous?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:940 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by iouri-s** [comment]
@markcowl ; Re: correctness of the API - it is 100% correct, because we are using it extensively in product code. Everything that should be marked as asynchronous is marked as asynchronous.

**Comment by markcowl** [comment]
>                     "type": "string"

Is this a guid? a human-readable name? an example might help to illustrate.

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:3010 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>                     "type": "string"

One last example of where descriptions need more detail - you should be able to tell more from the description than from the name of the property, especially in cases like this where it is unclear what the contents of this string might look like, for those learning the API

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:3037 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
>     },

Additional detail.  What kinds of resources does the client manage.  Why would you want to use it?

---
Refers to: arm-devtestlabs/2016-05-15/swagger/DTL.json:7 in e87abac. [](commit_id = e87abacaaf83ce3f968c19c48af10f7eb8a2fcec, deletion_comment = False)

**Comment by markcowl** [comment]
@iouri-s ignore the comments about x-ms-odata, I didn't read down far enough in the first operation.  I marked a couple of places where an operation might be asynchronous (long running), just wanted you to verify that this was not the case.

Also, in general, additional detail in the descriptiosn is desirable - these specs are becoming documentation for all of the sdks (used for intellisense, javadocs, etc.) and will also become rest api documentation, so having good descriptions is important.

**Comment by iouri-s** [comment]
Re: Additional detail. What kinds of resources does the client manage. Why would you want to use it?

Here's what the Compute client has to say about itself.

    "description": "The Compute Management Client.",

DevTestLab is not any worse than that venerable library.

This is a machine-generated spec and we do not have the resources to add and maintain fine-tuned descriptions or examples at this point. We have already added descriptions to all operations and their parameters, as well as models, and will continue to make incremental changes, in accordance to the needs of our business and our customers. The preview spec was published some time ago and was accepted with the exact same content. Now this commit is blocking our release process. Please do not hold this merge unless there are real show-stopping issues. 
The customers are expected to know DevTestLab's domain model and we will not be explaining what a "custom image" or a "formula" is in the operation descriptions. Same goes for "cost" - which is just another resource type. While I agree that in English, "name of a cost" sounds funny, it is just the name of a resource, just as much as "name of a lab" is. Resource names are decided by the PO and cannot be changed at this point.

**Comment by amarzavery** [comment]
@iouri-s - Mark has a valid point with accurate description. That helps users of the sdk and people who look at the MSDN REST API specs. The decision to provide examples is upto you. I see the point where the example can become obsolete very soon. 

We are taking this up with all the services to make sure that description is present and is good enough to convey the information to the end user. 

As you mentioned that the swagger spec is autogenerated, it would be easy for you to document the server side code so that swashbuckle can take all that goodness in the swagger spec.

For now we can merge this PR. However, please make sure that description is provided at each and every place and the description provides enough information about the artifact.

**Pull request merged**
