### PR TITLE
Adding action rule preview version

### PR DESCRIPTION
**Pull request by roramc**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by veronicagg — CHANGES_REQUESTED** [review]
@roramc Since you mentioned this files were reviewed before, could you point to the previous PR where this was reviewed? 
.Net failure in CI happens because that job does not support new RPs, so I will ignore that one. 
There's a failure in syntax job, which was fixed by us in this [commit](https://github.com/Azure/azure-rest-api-specs/commit/ec343353a7e76c01d145888f462c5ab6289881c2#diff-b474f495c8582ac5f92778a42ae814fa), could you update your branch with the latest from master to get this change so CI can re-run?

**Comment by roramc** [comment]
> @roramc Since you mentioned this files were reviewed before, could you point to the previous PR where this was reviewed?
> .Net failure in CI happens because that job does not support new RPs, so I will ignore that one.
> There's a failure in syntax job, which was fixed by us in this [commit](https://github.com/Azure/azure-rest-api-specs/commit/ec343353a7e76c01d145888f462c5ab6289881c2#diff-b474f495c8582ac5f92778a42ae814fa), could you update your branch with the latest from master to get this change so CI can re-run?

I have pulled the latest from master and updated the branch.
[](https://github.com/Azure/azure-rest-api-specs/pull/4955) - this is the previous PR. The new one is just adding a new version and addition of some more fields. Please look at the files changed section, those are the only new files added.

**Review by veronicagg — CHANGES_REQUESTED** [review]
@roramc thanks for clarifying. Based on your comments it looks like you're copying from a previous API version 2018-11-02-privatepreview and making updates to it, is that correct? The diff is hard to see it'd be good if you could commit first the old api version and make the updates in the following commits. We provide a onboarding experience via http://aka.ms/openapihub that would help you make and update like this easier. 
Since it's a new API version, I've requested ARM team to review. Have you reviewed these changes with them already?
I see that you're making parameter changes to existing APIs, removing a bunch of operations and adding discriminator type?

**Comment by veronicagg** [comment]
@roramc Please update https://github.com/Azure/azure-rest-api-specs/tree/13a53e71df342794e9cfeab21f6a2740be6300bf/specification/alertsmanagement/resource-manager/readme.md file to include this file in a new tag.

**Comment by veronicagg** [comment]
PR https://github.com/Azure/azure-rest-api-specs/pull/5750 was opened instead of this one, so closing this one. Thanks!

**Pull request closed without merging**
