### PR TITLE
[DataFactory] Changing arguments to object to support oneOf - this will allow param…

### PR DESCRIPTION
**Pull request by hvermis**
…eterization

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by anuchandy** [comment]
@hvermis this seems a SDK breaking change, marked with "Breaking Change Tag". Since over the wire service returns new types (not just arrays), I've requested "ARM Review".

**Comment by hvermis** [comment]
It's not breaking since the type is being changed to object, which means anything can get assigned to it.

**Comment by ravbhatnagar** [comment]
@hvermis  it seemed like earlier you allowed an array of these objects but now only allow single object. If I am reading the change correctly. Can you confirm?

**Comment by hvermis** [comment]
@ravbhatnagar Anything can be assigned to object, that also includes array of objects. So now both an Expression and array can be assign to it, while before only array could be assigned.

**Comment by hvermis** [comment]
@ravbhatnagar Can you please take a look at my response?

**Comment by ravbhatnagar** [comment]
Signing off from ARM side.

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
