### PR TITLE
Migrate to Typespec for Language Text API

### PR DESCRIPTION
**Pull request by quentinRobinson**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by heaths** [comment]
Where did a lot of these files come from? Did you merge main into your topic branch? It's not evident from the commits.

**Comment by quentinRobinson** [comment]
> Where did a lot of these files come from? Did you merge main into your topic branch? It's not evident from the commits.

I didnt want to merge all of main that would be too many files, so I merged only the files from the eng/ and package files to bring in the latest typespec settings.  it should be commit ed5cdf43fea85441358b2d2afb0f8dd7c651c795

**Comment by heaths** [comment]
Since you're the only one working on this, perhaps it would be better to rebase on upstream/main instead.

To make things easier, I also think these intermediate reviews may not be necessary unless you have questions. Ultimately, what matters is that the wire format is the same. How you get there matters less for brownfield (existing) services, though a final review to watch out for any glaring issues would be good.

It's otherwise hard to compare if what you have is correct w.r.t. the existing wire format because too much is missing/different at any one point until the TypeSpec(s) for the swagger(s) you're migrating is (mostly) done.

What do you think of that? Since you're targeting a feature branch, we could make it so you don't *need* a review if you want to push changes upstream to the feature branch.

**Comment by quentinRobinson** [comment]
I am also trying to get our team to review this PR to make sure everything looks right to them as well

**Pull request closed without merging**
