### PR TITLE
[NEED ARM SIGN-OFF] Adding new API version for ComputeInstance preview

### PR DESCRIPTION
**Pull request by ramagott**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

Spec changes in this PR were already approved by ARM reviewers in the below PR. We are moving the changes to preview from stable.
https://github.com/Azure/azure-rest-api-specs/pull/7323

### CODE REVIEW

**Review by leizhaoPS — APPROVED** [review]
Approved since this is the code migrate from stable folder to preview version and no new design changes, just file copies

**Comment by yungezz** [comment]
there're new changes in this PR comparing with PR #7323 , such as new paths and new definitions, below are some. So need ARM review again.
`"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/features"`
`/subscriptions/{subscriptionId}/providers/Microsoft.MachineLearningServices/workspaces/skus`.

**Comment by ramagott** [comment]
> there're new changes in this PR comparing with PR #7323 , such as new paths and new definitions, below are some. So need ARM review again.
> `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/features"`
> `/subscriptions/{subscriptionId}/providers/Microsoft.MachineLearningServices/workspaces/skus`.



> there're new changes in this PR comparing with PR #7323 , such as new paths and new definitions, below are some. So need ARM review again.
> `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/features"`
> `/subscriptions/{subscriptionId}/providers/Microsoft.MachineLearningServices/workspaces/skus`.

Above mentioned changes were already published in version 2020-01-01. You can compare with https://github.com/Azure/azure-rest-api-specs/tree/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-01-01 to find the real changes.

**Comment by ravbhatnagar** [comment]
part of the changes here have already been signed off here - https://github.com/Azure/azure-rest-api-specs/pull/7323.
New APis to start and stop computes resource type has been added.  SIgning off from ARM side.

**Comment by yungezz** [comment]
hi @ramagott is this PR ready to merge? thanks.

**Comment by ramagott** [comment]
> hi @ramagott is this PR ready to merge? thanks.

We need to upload ARM manifest to support this version. I will let you know once we are ready. Please add the DoNotMerge label.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
