### PR TITLE
{storage pool} add properties required

### PR DESCRIPTION
**Pull request by Juliehzl**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by blueww — APPROVED** [review]
I am OK with the change.
But consider there are other issues of the swagger, I would suggest ask feature team to raise a PR include all fix.  (like update Diskpool can't update subnet and availablityZone, but the 2 properties are required in update)

**Review by harshivcodes — APPROVED** [review]

**Comment by harshitha-akkaraju** [comment]
> I am OK with the change.
> But consider there are other issues of the swagger, I would suggest ask feature team to raise a PR include all fix. (like update Diskpool can't update subnet and availablityZone, but the 2 properties are required in update)

@blueww in swagger we made these fields required during an update so as to not create a different json structure just for the DiskPool update.

We also figured that the customer would have to do a GET on a diskPool resource before doing an UPDATE -- so these fields would be correctly populated in the GET response payload. But yeah, I can see cases where this might not be true.

What's the convention that other RPs follow? I was looking at compute's swagger specs for virtual machines and they don't have many required fields in the VirtualMachineProperties, yet the RP does validation. Can we follow the same model too?

**Comment by blueww** [comment]
@harshitha-akkaraju

As the SDK, and PSH/CLI code mostly will be auto generated from swagger, the swagger definition normally should be exact aligned with Server behavior, or the SDK/PSH/CLI might not work well.

In this case, if Put and Patch method accept difference parameters, you should define different object for Put/Patch Parameters.
Such as create/Update Storage account accept different parameters, so storage swagger defines different object for the 2 API parameter:

- Storage Account Create parameter: https://github.com/Azure/azure-rest-api-specs/blob/52e55d2f2af9d1e5bf0d65a592cfeb5705801fbf/specification/storage/resource-manager/Microsoft.Storage/preview/2020-08-01-preview/storage.json#L2502
- Storage Account Update parameter: https://github.com/Azure/azure-rest-api-specs/blob/52e55d2f2af9d1e5bf0d65a592cfeb5705801fbf/specification/storage/resource-manager/Microsoft.Storage/preview/2020-08-01-preview/storage.json#L3181

Besides that, server behavior should also be aligned. Such as, if  an API accept a parameter, user should  can change the parameter to a valid value with the API (don't need to keep same as current value on server).

And the Operation ID should be aligned with what the API really do: like patch has operation ID as "***_Update",  then it should can update all valid input defined in the swagger.

**Comment by jianyexi** [comment]
@Juliehzl Since there is breaking change in your PR,  you should follow the Action in https://github.com/Azure/azure-rest-api-specs/pull/11895#issuecomment-737090562 to get approval first.

**Comment by Juliehzl** [comment]
@lirenhe the wrong swagger would influence codeGen, but the change would trigger swagger breaking change tool although there is no SDK/PSH/CLI released.

**Comment by akning-ms** [comment]
Can you confirm whether this service is GA/Public preview or not? if not , then it is not required to breaking change review.
and recommend to have this change in private repo. can you also put a preview PR which introduced this swagger error to evaluate impact.

**Comment by akning-ms** [comment]
@msyyc @jsntcy @ArcturusZhang @weidongxu-microsoft @ChenTanyi  SDK owner for awareness this issue and block any SDK release for Storage Pool before these issue resolved

**Comment by msyyc** [comment]
> @msyyc Yuchao Yan FTE @jsntcy Yu Chen FTE @ArcturusZhang Dapeng Zhang FTE @weidongxu-microsoft Weidong Xu FTE @ChenTanyi Tanyi Chen FTE SDK owner for awareness this issue and block any SDK release for Storage Pool before these issue resolved

For python, the breaking change is caused by https://github.com/Azure/azure-rest-api-specs/pull/11718, not this one.

**Comment by ArcturusZhang** [comment]
No changes on go SDK

**Comment by Juliehzl** [comment]
This pr is not needed because the change is included in https://github.com/Azure/azure-rest-api-specs/pull/12391

**Pull request closed without merging**
