### PR TITLE
Add back examples

### PR DESCRIPTION
**Pull request by gatneil**

### CODE REVIEW

**Comment by gatneil** [comment]
This PR adds back the Compute create examples that were originally introduced in https://github.com/Azure/azure-rest-api-specs/pull/1575 and temporarily removed in https://github.com/Azure/azure-rest-api-specs/pull/1885 due to some bugs. This PR adds back fixed versions and will enable autogeneration of Compute REST API documentation.

**Comment by gatneil** [comment]
@anuchandy looking at the failing autorest ruby step in the CI pipeline, it looks like there was some issue in validating checksums:

Failed to install or start extension '@microsoft.azure/autorest.ruby' (3.0.20)
  Error: Package '@microsoft.azure/autorest.ruby' - '3.0.20' failed to install:
  sha1-9bJOsXkUqtDo0tpYFkIESmCI2QU= integrity checksum failed when using sha1: wanted sha1-9bJOsXkUqtDo0tpYFkIESmCI2QU= but got sha1-7Bl8dIknUaVbKZQTwoPYv5e/JgI=. (1769472 bytes)

Any ideas on how to fix/workaround?

Also, @olydis as FYI: this PR adds back the create examples we temporarily removed previously :)

**Comment by anuchandy** [comment]
@sarangan12 can someone from ruby team take a look at ruby build failure?

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
FYI: @gatneil, @sarangan12 ruby step passed after restarting the job.

**Pull request merged**
