### PR TITLE
Add DeviceStreams properties to IoTHub and modify RoutingTwin object …

### PR DESCRIPTION
**Pull request by ankurkul**
…for new preview API

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by ankurkul** [comment]
@hovsepm  : Can we hold on to merge this PR until we have sign off from Infra team of IoTHub. I cannot find a way to add that constraint.

**Comment by hovsepm** [comment]
@ankurkul please ping me directly when your PR will be ready to merge. In the mean time could you take a look and fix Syntax Validation errors?

**Comment by ankurkul** [comment]
@hovsepm : Sure, will ping you once this PR is ready for checkin. Meanwhile, I have fixed the syntax errors in the swagger.

**Comment by hovsepm** [comment]
@ankurkul are you still working on this PR?

**Comment by ankurkul** [comment]
@hovsepm : Yes, still working on the PR.

**Comment by hovsepm** [comment]
@ankurkul this PR is stale for almost 2 month. I'm going to close this PR by the end of today if it will not be in the [Good to be merged state]. Please reopen when you will be ready for merge.

**Comment by ankurkul** [comment]
Re-opening PR since we are ready to merge now.

**Comment by ankurkul** [comment]
@hovsepm I cannot seem to re-open this PR. Do u have permissions to reopen this PR?

**Comment by hovsepm** [comment]
@ankurkul just create a new one from the same branch.

**Pull request closed without merging**
