### PR TITLE
DDOS protected IP flag for public IP

### PR DESCRIPTION
**Pull request by mancgupta**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by lirenhe** [comment]
@mancgupta, please fix the error reported by code check tools.

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
@mancgupta, could you take a look at 'NetworkValidation' error?

**Comment by mancgupta** [comment]
> @mancgupta, could you take a look at 'NetworkValidation' error?

Yes, I'm looking

**Comment by mancgupta** [comment]
@lirenhe NetworkValidation error was coming due to invalid reference of a tag. 
2020-01-02T22:53:06.7302801Z error: cannot lock ref 'refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>': Unable to create 'D:/a/1/s/.git/refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>.lock': Invalid argument


I have removed the invalid refs from the git. How can I rerun the checks?

**Comment by mancgupta** [comment]
@lirenhe Error is coming due to a tag reference.

2020-01-02T22:53:06.7302801Z error: cannot lock ref 'refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>': Unable to create 'D:/a/1/s/.git/refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>.lock': Invalid argument

"**refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>**"

I think we need to remove this tag but I don't have permission to do so.

**Comment by lirenhe** [comment]
> @lirenhe Error is coming due to a tag reference.
> 2020-01-02T22:53:06.7302801Z error: cannot lock ref 'refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-': Unable to create 'D:/a/1/s/.git/refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-.lock': Invalid argument
> "refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-"
> I think we need to remove this tag but I don't have permission to do so.

@mancgupta,  could you let us know what action to take? If you want us to delete some item, could you provide the link to it?

**Comment by mancgupta** [comment]
> > @lirenhe Error is coming due to a tag reference.
> > 2020-01-02T22:53:06.7302801Z error: cannot lock ref 'refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-': Unable to create 'D:/a/1/s/.git/refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-.lock': Invalid argument
> > "refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-"
> > I think we need to remove this tag but I don't have permission to do so.
> 
> @mancgupta, could you let us know what action to take? If you want us to delete some item, could you provide the link to it?

Not sure who created this tag, but it doesn't seem like a valid one and throwing the exception. We need to remove this tag.

image

git push --delete origin "refs/tags/openapi-baselineTag-dev-marketplace-Microsoft.Marketplace-<version>"
image

**Pull request merged**
