### PR TITLE
RMS - Adding changes to fix the correctness validation issues.

### PR DESCRIPTION
**Pull request by punit-bhatt**
Missing properties -
1 - LB Nat rules in NIC IP ResourceSettings.
2 - NSG reference in Subnet Resource Settings.
3 - Public IP reference in NIC IP Resource Settings.

Case correction - fqdn instead of fQDN in PublicIPResourceSettings.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by punit1396** [comment]
Resource mover service is still in public preview and the changes in question are in reply to the Live Validation Correctness failures. These properties have been a part of the service since before our public preview started (August'20).
These aren't breaking changes.

**Review by innosam — APPROVED** [review]

**Comment by punit1396** [comment]
@leni-msft 
Could you review this PR?

**Comment by leni-msft** [comment]
@punit1396 since there's a breaking change error, pls follow the process to request approval. Also, follow the guide https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/405/Window-to-Fix-Broken , so that it would be more likely to be approved.

**Comment by punit1396** [comment]
@leni-msft 
Have received the following mail regarding swagger correctness issues being allowed in the same version and not being considered Breaking Changes till end of January.

_Hello! If you are receiving this message, it's because you are listed as a PM Owner contact or Dev Owner contact for a service with an ARM RP Namespace onboarded in Service Tree. This message is intended for the overall ARM RP Namespace Contact and this metadata value is blank for your service or services in Service Tree. To help us target future ARM RP-related communication, please follow these instructions to update the ARM Namespace Contact field with the correct alias(es). You can view all Service Tree contact information in one place in this report to ensure the contact information for your service(s) and RP is accurate._

_There are some updates about Swagger Tooling and PR Review process worth your attention._

*_Window to Fix Broken_*

_In order to drive higher Swagger Correctness, with agreement of Azure Breaking Change Board, and Azure SDKs/CLIs teams, we decide to open a window for service teams to “fix broken” with current version.  Which means you are able to fix some Swagger Correctness issues, like OBJECT_ADDITIONAL_PROPERTIES, INVALID_RESPONSE_CODE, ROUNDTRIP_ADDITIONAL_PROPERTY, etc., in the version with issues,  no more require of creating a new version to accommodate breaking changes with fixes.  However, the window is only available by the end of January 2021.  After January, all breaking changes must be justified.  There is further guidance available in this wiki Window to Fix Broken - Overview (azure.com).  If any further question, please reach out to me or Swagger KPIs Communication <swaggerkpiscomm@microsoft.com>._

**Comment by leni-msft** [comment]
@punit1396 The process didn't change, you will still need request approval from breaking change team.

**Comment by punit1396** [comment]
@leni-msft have removed the breaking changes. Could you take a look?

**Pull request merged**
