### PR TITLE
Update CDN default api version to 2020-04-15.

### PR DESCRIPTION
**Pull request by fore5fire**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Let me know if the lint error can be fixed. Or it would need code owner's help.

**Comment by lsmith130** [comment]
@weidongxu-microsoft, these linter errors are existing issues that are getting flagged as new because of the change in API version, and fixing them is beyond the scope of this PR. Can we merge this PR and plan to fix those issues in a future PR?

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft, these linter errors are existing issues that are getting flagged as new because of the change in API version, and fixing them is beyond the scope of this PR. Can we merge this PR and plan to fix those issues in a future PR?

@akning-ms Hello Arthur, are you OK to merge it? No change in spec, all lint issue is existing ones.

**Comment by akning-ms** [comment]
Hi @lsmith130, Can I know why you change this default tag to new version? it is for release SDK? if yes. suggest you to fix the lint error first. otherwise, it will cause more impact for customer if change after sdk release. as fix the linter error may change breaking change

**Comment by lsmith130** [comment]
@akning-ms, I've fixed the warnings that can be done reasonably, and the errors are saying that the error response format doesn't match the standard, which is incorrect. Our error format does match the standard, and changes to the error format would be a breaking change for all existing resource types.

The only remaining warnings that cannot be fixed later are the warnings that enums should be used as booleans, but because these warnings were not enforced before merging the original PR that introduced them, we've already done substantial engineering effort on the assumption that the boolean fields are acceptable. Can we move forward with this PR or do I need to convince my team to make updates to multiple accepted API versions and redo work in our RP that is already tested and working?

**Comment by akning-ms** [comment]
Thanks for clarify, @lsmith130  make sense, LGTM if you have plan to fix it.

**Pull request merged**
