### PR TITLE
Enable TryPlannedBeforeForcedFailover for SQL DB Failover Group

### PR DESCRIPTION
**Pull request by subhrob**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by subhrob** [comment]
Breaking changes details:
Both the typeFormatChanged issue is due to https://github.com/Azure/azure-rest-api-specs/commit/c3daf5a8d294e2cfe91307286d7c58f6311b4c89#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c

I will update that accordingly.

AddingRequiredParameter is necessary as a new request body is introduced for the controller.

**Comment by ericshape** [comment]
> Breaking changes details: Both the typeFormatChanged issue is due to [c3daf5a#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c](https://github.com/Azure/azure-rest-api-specs/commit/c3daf5a8d294e2cfe91307286d7c58f6311b4c89#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c)
> 
> I will update that accordingly.
> 
> AddingRequiredParameter is necessary as a new request body is introduced for the controller. FailoverGroupForceFailoverAllowDataLoss accepts a request body having a boolean TryPlannedBeforeForcedFailover
> 
> Customers can continue to use their existing APIs with the older version. The DSMainDev code takes care of the backward compatibility so even with the latest version, there is no need for the customer to add the request body. It is actually optional.
> 
> I investigated the ModelValidation failures and they are due to Issues with LROs which I didn't change.

the breaking change from that PR is expected. their changes are from ARM side.

**Review by ericshape — APPROVED** [review]

**Comment by subhrob** [comment]
Update to ModelValidation failures
LRO and OBJECT_MISSING_REQUIRED_PROPERTY: no changes from my side.
REQUIRED_PARAMETER_EXAMPLE_NOT_FOUND : FailoverGroupForceFailoverAllowDataLoss.json will continue to function without the request body. A new example has been added as part of this PR which gives the example for the new parameter.

**Comment by ericshape** [comment]
> Update to ModelValidation failures LRO and OBJECT_MISSING_REQUIRED_PROPERTY: no changes from my side. REQUIRED_PARAMETER_EXAMPLE_NOT_FOUND : FailoverGroupForceFailoverAllowDataLoss.json will continue to function without the request body. A new example has been added as part of this PR which gives the example for the new parameter.

it seems you need to fix all the ModelValidation errors.

**Comment by ericshape** [comment]
feel free to ask the swagger team about the optional parameter field. but I am guessing it has to be a breaking change.

**Comment by ericshape** [comment]
and please also update the example fix in DSMainDev repo.

**Review by ericshape — APPROVED** [review]
approve but please response my comments above.

**Comment by subhrob** [comment]
Hi @raych1 

Could you please review this PR:

Cross version breaking changes details:

The typeFormatChanged issue is due to https://github.com/Azure/azure-rest-api-specs/commit/c3daf5a8d294e2cfe91307286d7c58f6311b4c89#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c


AddingRequiredParameter is necessary as a new request body is introduced to a POST API.
API calls via ARM template will be backward compatible and necessary checks are placed in code.

However, is there any means by which we can make the newly added request body, not a required parameter?

https://github.com/Azure/azure-rest-api-specs/blob/77578dbf048219caf705bd557447b62d824c9bdb/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json#L378

**Comment by raych1** [comment]
> Hi @raych1
> 
> Could you please review this PR:
> 
> Cross version breaking changes details:
> 
> The typeFormatChanged issue is due to [c3daf5a#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c](https://github.com/Azure/azure-rest-api-specs/commit/c3daf5a8d294e2cfe91307286d7c58f6311b4c89#diff-4d7ad3d3168d96418afd7be9ba62554894cbc088b1df95be51c3ca35b32ac15c)
> 
> AddingRequiredParameter is necessary as a new request body is introduced to a POST API. API calls via ARM template will be backward compatible and necessary checks are placed in code.
> 
> However, is there any means by which we can make the newly added request body, not a required parameter?
> 
> https://github.com/Azure/azure-rest-api-specs/blob/77578dbf048219caf705bd557447b62d824c9bdb/specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json#L378

Please refer to the [comment](https://github.com/Azure/azure-rest-api-specs/pull/22673#issuecomment-1433348663) to get breaking change approval.

**Comment by subhrob** [comment]
The change introduces a new controller, tryPlannedBeforeForcedFailover for a third type of failover

The behavior is similar to already existiing ones like forceFailoverAllowDataLoss and failover, with slight modifications.

**Comment by ericshape** [comment]
it seems you need to fix the required pipeline: 


❌ PostOperationAsyncResponseValidation | An async POST operation must set long running operation options 'x-ms-long-running-operation-options'
-- | --

**Comment by ericshape** [comment]
Please add arm-id and other fields which have already been in the old version:


❌ 1023 - TypeFormatChanged | The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json#L684:9Old: Microsoft.Sql/stable/2021-11-01/FailoverGroups.json#L604:9
-- | --
❌ 1023 - TypeFormatChanged | The new version has a different format than the previous one.New: Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json#L567:11Old: Microsoft.Sql/stable/2021-11-01/FailoverGroups.json#L500:11

arm-id and other fields were added manually last week by ARM/Security team. We will add them into our swagger generation process next month. thus we need to match the old version manually in this API version.

**Comment by subhrob** [comment]
> PostOperationAsyncResponseValidation


@ericshape 
How do we fix this?
`[LongRunningOperation(LongRunningOperationAttribute.AyncOperationOption.AsyncOperation)]` ?

Also how about the LroLocationHeader  and the Pattern ResourceNameRestriction .
For now, i have changed the swagger file, but how do i generate the correct thing automatically

**Review by ericshape — APPROVED** [review]

**Comment by mentat9** [comment]
@subhrob - Please recreate your PR using this guidance:

_Adding a new API version
-[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version)._

Also, when you resubmit, be sure you also fill out the **ARM API Review Checklist** section of the submission form.

**Comment by mentat9** [comment]
@subhrob - Just noticed your PR is going to an aggregation branch, removed my earlier comment.

**Comment by mentat9** [comment]
>       "properties": {}

ARM recommends against the empty/unschematized object pattern. Recommend you remove this.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json:647 in 4199eb4. [](commit_id = 4199eb4bfcec74048edfeb7d32d8f8f2880e3877, deletion_comment = False)

**Comment by mentat9** [comment]
@subhrob - Please complete the ARM API Review Checklist.

**Comment by subhrob** [comment]
> > ```
> >   "properties": {}
> > ```
> 
> ARM recommends against the empty/unschematized object pattern. Recommend you remove this.
> 
> Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json:647 in [4199eb4](https://github.com/Azure/azure-rest-api-specs/commit/4199eb4bfcec74048edfeb7d32d8f8f2880e3877). [](commit_id = [4199eb4](https://github.com/Azure/azure-rest-api-specs/commit/4199eb4bfcec74048edfeb7d32d8f8f2880e3877), deletion_comment = False)

@mentat9 , Thank you for reviewing. Made the changes.

**Comment by mentat9** [comment]
>             "$ref": "../../../common/v1/types.json#/parameters/SubscriptionIdParameter"

Recommend moving to newest common types (v5) for new swagger code.

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/FailoverGroups.json:375 in 5fdbec9. [](commit_id = 5fdbec92736788e6b270b45f3bb0f69ff310700d, deletion_comment = False)

**Comment by mentat9** [comment]
@subhrob - Signed off for ARM with comments.

**Pull request merged**
