### PR TITLE
added response for policy assignment delete

### PR DESCRIPTION
**Pull request by tfitzmac**
Fixing in response to #1351 

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by vishrutshah — CHANGES_REQUESTED** [review]
@tfitzmac Should this bug be also fixed in the previous API versions of `policy` for Azure Stack?

**Comment by tfitzmac** [comment]
@vishrutshah - I guess, so but I am not sure. I added it to fix the documentation, but we only publish the latest version. Which version does Stack use?

**Comment by vishrutshah** [comment]
@tfitzmac Hmm I am even not sure which version the stack uses but let me check around today and see. If you get any insights into that let us know as well :)

**Comment by vishrutshah** [comment]
@tfitzmac We are still in the process of finalizing the guidelines around Azure Stack for SDKs/CLIs, we are good here. Thanks!

**Review by vishrutshah — APPROVED** [review]

**Pull request merged**
