### PR TITLE
Add DNS 2017-09-01 Swagger for CAA Record Support

### PR DESCRIPTION
**Pull request by nkindberg**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by nkindberg** [comment]
These changes were already reviewed by @sergey-shandar in the private repo. Just moving everything as-is to the public repo.

**Comment by veronicagg** [comment]
@nkindberg thanks for letting us know. @sergey-shandar could you confirm this and if so, approve and merge this PR? thanks!

**Comment by sergey-shandar** [comment]
@veronicagg https://github.com/Azure/azure-rest-api-specs-pr/pull/156

**Review by sergey-shandar — APPROVED** [review]

**Comment by elyscape** [comment]
This does not appear to have been added to the SDKs for [Ruby] or [Go]. Both of them have support for the 2016-04-01 API but no newer.

[Ruby]: https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_dns/lib
[Go]: https://github.com/Azure/azure-sdk-for-go/tree/v12.0.0-beta/services/dns/mgmt

**Comment by elyscape** [comment]
This is also the case for the Java [SDK] and [Library].

[SDK]: https://github.com/Azure/azure-sdk-for-java/blob/v1.3.0/azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/DnsManagementClientImpl.java#L192
[Library]: https://github.com/Azure/azure-libraries-for-java/blob/v1.5.0/azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/DnsManagementClientImpl.java#L192

**Comment by veronicagg** [comment]
@elyscape that's correct for Ruby, this PR wasn't merged at the time we shipped spec updates to dns package. We're expecting to update packages based on specs for Ruby ~mid-Jan. If you need this one earlier, please let us know. - FYI @sarangan12

**Comment by elyscape** [comment]
@veronicagg Good to know. I personally only need a newer one for Go, but while I was source-diving I figured I'd check on the other SDKs. My need isn't particularly time-critical, but I wanted to make sure that it hadn't fallen off the radar.

**Pull request merged**
