### PR TITLE
Storage STG 85/86

### PR DESCRIPTION
**Pull request by seanmcc-msft**
**This is not a breaking change**

In some cases, storage features are implemented with a service version, but not activated until late.  That is what happened here.

**This is not a breaking change**

### CODE REVIEW

**Comment by tg-msft** [comment]
The [diff for Blobs](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYWluL3NwZWNpZmljYXRpb24vc3RvcmFnZS9kYXRhLXBsYW5lL01pY3Jvc29mdC5CbG9iU3RvcmFnZS9wcmV2aWV3LzIwMjEtMDgtMDYvYmxvYi5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL2Jsb2IvYzA0MjJmZjM5NGNkNDdiNzc2YWQxZjg5NzYyMzNhZmZlOGE2Nzg5MS9zcGVjaWZpY2F0aW9uL3N0b3JhZ2UvZGF0YS1wbGFuZS9NaWNyb3NvZnQuQmxvYlN0b3JhZ2UvcHJldmlldy8yMDIxLTEyLTAyL2Jsb2IuanNvbiJ9) looks fine, but I'm concerned about the encoded string change in the [diff for Files](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYWluL3NwZWNpZmljYXRpb24vc3RvcmFnZS9kYXRhLXBsYW5lL01pY3Jvc29mdC5GaWxlU3RvcmFnZS9wcmV2aWV3LzIwMjEtMDYtMDgvZmlsZS5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL2Jsb2IvYzA0MjJmZjM5NGNkNDdiNzc2YWQxZjg5NzYyMzNhZmZlOGE2Nzg5MS9zcGVjaWZpY2F0aW9uL3N0b3JhZ2UvZGF0YS1wbGFuZS9NaWNyb3NvZnQuRmlsZVN0b3JhZ2UvcHJldmlldy8yMDIxLTEyLTAyL2ZpbGUuanNvbiJ9).

How is changing `Name` from a simple `string` into an object not a breaking change?

**Comment by seanmcc-msft** [comment]
> The [diff for Blobs](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYWluL3NwZWNpZmljYXRpb24vc3RvcmFnZS9kYXRhLXBsYW5lL01pY3Jvc29mdC5CbG9iU3RvcmFnZS9wcmV2aWV3LzIwMjEtMDgtMDYvYmxvYi5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL2Jsb2IvYzA0MjJmZjM5NGNkNDdiNzc2YWQxZjg5NzYyMzNhZmZlOGE2Nzg5MS9zcGVjaWZpY2F0aW9uL3N0b3JhZ2UvZGF0YS1wbGFuZS9NaWNyb3NvZnQuQmxvYlN0b3JhZ2UvcHJldmlldy8yMDIxLTEyLTAyL2Jsb2IuanNvbiJ9) looks fine, but I'm concerned about the encoded string change in the [diff for Files](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYWluL3NwZWNpZmljYXRpb24vc3RvcmFnZS9kYXRhLXBsYW5lL01pY3Jvc29mdC5GaWxlU3RvcmFnZS9wcmV2aWV3LzIwMjEtMDYtMDgvZmlsZS5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL2Jsb2IvYzA0MjJmZjM5NGNkNDdiNzc2YWQxZjg5NzYyMzNhZmZlOGE2Nzg5MS9zcGVjaWZpY2F0aW9uL3N0b3JhZ2UvZGF0YS1wbGFuZS9NaWNyb3NvZnQuRmlsZVN0b3JhZ2UvcHJldmlldy8yMDIxLTEyLTAyL2ZpbGUuanNvbiJ9).
> 
> How is changing `Name` from a simple `string` into an object not a breaking change?

Previous, Name could be something like this:

`<Name>fileName</Name>`

Now, Name could look like this:

`<Name Encoded="true">file%EF%BF%BF</Name>`

The `Encoded` XML attribute was added to the `Name` element.

**Comment by tg-msft** [comment]
Got it - thank you for the clarification.  I'm not as used to thinking through XML evolution as JSON.

**Review by tg-msft — APPROVED** [review]
The changes look good

**Comment by tg-msft** [comment]
I added the Approved-BreakingChange label as it's not really a break.

**Pull request merged**
