### PR TITLE
[Cdn] Add new preview API: 2023-07-01-preview

### PR DESCRIPTION
**Pull request by jessicl-ms**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [X] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. **July 2023**
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. **July 2023**
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [X] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[X] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [X] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by JackTn** [comment]
@jessicl-ms  pls check validation and fix them https://github.com/Azure/azure-rest-api-specs/pull/24387#issuecomment-1585491643 refer to https://github.com/Azure/azure-rest-api-specs/pull/24387#issuecomment-1585494110

**Comment by zizw123** [comment]
> Hi, @jessicl-ms, For review efficiency consideration, when creating a new api version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Or you could onboard [API spec pipeline](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline)

Please also follow this to update the PR

**Comment by jessicl-ms** [comment]
> > Hi, @jessicl-ms, For review efficiency consideration, when creating a new api version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Or you could onboard [API spec pipeline](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline)
> 
> Please also follow this to update the PR

@zizw123 I fixed my commit history. You should find 3 commits as of now: 
 * Copy latest stable version 2023-05-01 to preview directory
 * Rename that copy to 2023-07-01-preview version
 * Changes relevant to new preview api version and all api validation fixes.

**Comment by jessicl-ms** [comment]
@zizw123 Addressing current failures separately in comments below:

**Comment by jessicl-ms** [comment]
This preview API version contains api for preview feature UrlSigningKey. This feature was previously present in cdn.json API definition in Private Preview state. We have already notified customers currently using the previous APIs about breakings changes (<20 total customers). The previous definition in cdn.json was also for a different resource SKU. The current changes are specifically targeted for afdx.json definitions for customers using Azure Frontdoor Standard/Premium SKU. There should be no overlap between the previous and future customers using this preview feature.

Breaking Change (Cross-Version) 
* The validation pipeline shows this error. I'm not sure how to resolve it. Please advise!
 `"new":"https://github.com/Azure/azure-rest-api-specs/blob/87428d4c15b9ace4427ab68a762c46b623e4d26b/specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json",
"old":"https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2023-05-01/afdx.json",
"details":"Command failed: node "/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.54/common/temp/node_modules/.pnpm/https://github.com/Azure+oad@0.10.4/node_modules/autorest/dist/app.js" --v2 --input-file=specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json --output-artifact=swagger-document.json --output-artifact=swagger-document.map --output-file=new --output-folder=/tmp\nFATAL: swagger-document/emitter - FAILED\nFATAL: Error: Error retrieving '$.definitions.UrlSigningAction.type' (Error: Trying to retrieve 'type' from mapping that contains no such key)\n Error: Error retrieving '$.definitions.UrlSigningAction.type' (Error: Trying to retrieve 'type' from mapping that contains no such key)\n"`

Swagger SDK Breaking Change Tracking:
* I had copied over cdn.json and cdnwebapplicationfirewall.json from 2023-05-01 version. There should not be any changes to these files. However, the validation pipeline is identifying changes to those resources. Why is that?

**Comment by jessicl-ms** [comment]
**Swagger Model Validation**:
* Error Discriminator_Value_Not_Found is looking for `Discriminator value "UrlSigningRule" not found` in [preview/2023-07-01-preview/examples/Rules_Create_AfdUrlSigningAction.json](https://github.com/Azure/azure-rest-api-specs/blob/87428d4c15b9ace4427ab68a762c46b623e4d26b/specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/examples/Rules_Create_AfdUrlSigningAction.json). However, that value is present. Is there a different place I need to put it?
* Error Missing_Resource_Id says `id is required to return in response of GET/PUT resource calls but not being provided`. These example files are for cdn.json API definitions which have not been changed in this PR. Can these be ignored?

**Comment by jessicl-ms** [comment]
**Swagger LintDiff**
* Is there a way around Error PutRequestResponseSchemeArm? We do not want a PATCH API available for this resource. `A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'KeyGroups_CreateUpdate' Request Model: 'parameters[5].schema' Response Model: 'responses[200].schema'
Location: [Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635](https://github.com/Azure/azure-rest-api-specs/blob/87428d4c15b9ace4427ab68a762c46b623e4d26b/specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635)`
* What kind of error response is error LroErrorContent looking for? This new resource is suing the same lro error we are using for other preexisting operations.

**Comment by jessicl-ms** [comment]
**SDK azure-sdk-for-net-track2, SDK azure-powershell**

Do these validations only succeed if all other validations are succeeding?

**Comment by JackTn** [comment]
@jessicl-ms Thanks for explanations .  @rkmanda are these errors can be acceptable?

**Comment by rkmanda** [comment]
> **Swagger LintDiff, ~[Staging] Swagger LintDiff**
> 
> * Is there a way around Error PutRequestResponseSchemeArm? We do not want a PATCH API available for this resource. `A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'KeyGroups_CreateUpdate' Request Model: 'parameters[5].schema' Response Model: 'responses[200].schema' Location: [Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635](https://github.com/Azure/azure-rest-api-specs/blob/87428d4c15b9ace4427ab68a762c46b623e4d26b/specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635)`
> * What kind of error response is error LroErrorContent looking for? This new resource is suing the same lro error we are using for other preexisting operations.
> * Is Error DeleteResponseCodes saying I need to remove 200 response from delete API?




The failure for [PutRequestResponseSchemeArm](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-request-response-scheme-arm.md) is a false alarm. Please apply a suppression for it.
The failure for [LroErrorContent](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-error-content.md) can be fixed by switching to the use of the standard error definition for ARM - https://github.com/Azure/azure-rest-api-specs/blob/8b70e81ab1b526c468b5dbd68affd30595cfc329/specification/common-types/resource-management/v5/types.json#L302C1-L303C1

Also fix the warnings to use common types so that you are making use of the common type definitions - [ParameterNotUsingCommonTypes](https://github.com/Azure/azure-openapi-validator/blob/main/docs/parameter-not-using-common-types.md)

[DeleteResponseCodes](https://github.com/Azure/azure-openapi-validator/blob/main/docs/delete-response-codes.md)
A long-running delete must not return a 200 status code. It MUST return a 202 accepted when the delete request is accepted and a long running workflow is initiated for the delete operation. It MUST also return a 204 if the resource does not exist.

**Comment by rkmanda** [comment]
>           "202": {

PUT must not return a 202

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3685 in 8b70e81. [](commit_id = 8b70e81ab1b526c468b5dbd68affd30595cfc329, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "final-state-via": "azure-async-operation"

remove this, you dont need to specify the final-state-via

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3705 in 8b70e81. [](commit_id = 8b70e81ab1b526c468b5dbd68affd30595cfc329, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "200": {

remove. Async delete only needs to respond with 202 or 204

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3737 in 8b70e81. [](commit_id = 8b70e81ab1b526c468b5dbd68affd30595cfc329, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "$ref": "./cdn.json#/definitions/ProxyResource"

use common-types

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:4616 in 8b70e81. [](commit_id = 8b70e81ab1b526c468b5dbd68affd30595cfc329, deletion_comment = False)

**Comment by mikekistler** [comment]
I opened an issue for the failure in the breaking changes PR check. I also manually compared adfx.json with the prior version and saw no potential breaking changes.

**Comment by ChenglongLiu** [comment]
Marked this pull request as draft as there is some more work need to do

**Comment by jessicl-ms** [comment]
> > ```
> >       "final-state-via": "azure-async-operation"
> > ```
> 
> remove this, you dont need to specify the final-state-via for control plane APIs
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3705 in [e804d9d](https://github.com/Azure/azure-rest-api-specs/commit/e804d9deaedf7ca9365aaae37e282802c29b446e). [](commit_id = [e804d9d](https://github.com/Azure/azure-rest-api-specs/commit/e804d9deaedf7ca9365aaae37e282802c29b446e), deletion_comment = False)

Removed

**Comment by jessicl-ms** [comment]
> > ```
> >       "200": {
> > ```
> 
> remove. Async delete only needs to respond with 202 or 204
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3737 in [8b70e81](https://github.com/Azure/azure-rest-api-specs/commit/8b70e81ab1b526c468b5dbd68affd30595cfc329). [](commit_id = [8b70e81](https://github.com/Azure/azure-rest-api-specs/commit/8b70e81ab1b526c468b5dbd68affd30595cfc329), deletion_comment = False)

Removed

**Comment by jessicl-ms** [comment]
> > ```
> >       "202": {
> > ```
> 
> PUT must not return a 202
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3685 in [8b70e81](https://github.com/Azure/azure-rest-api-specs/commit/8b70e81ab1b526c468b5dbd68affd30595cfc329). [](commit_id = [8b70e81](https://github.com/Azure/azure-rest-api-specs/commit/8b70e81ab1b526c468b5dbd68affd30595cfc329), deletion_comment = False)

Request to this API are async and may not complete immediately. We have been using 202 to indicate that the operation was accepted and initiated. Could we keep 202 as PUT response?

**Comment by jessicl-ms** [comment]
Swagger Avocado errors are from files owned by other feature teams. I had rebased with Azure:main, but the error still show up. Please advise on how to resolve or if these errors can be bypassed.

Link to errors: https://github.com/Azure/azure-rest-api-specs/pull/24387/checks?check_run_id=15892581865

**Comment by jessicl-ms** [comment]
Swagger ModelValidation errors are also in files unrelated to this PR. The file cdn.json is owned by our team, but is for a different customer SKU that will not be using the urlsigning key feature being introduced in 2023-07-01-preview. The remaining errors are in files owned by other feature teams.

Link to errors: https://github.com/Azure/azure-rest-api-specs/pull/24387/checks?check_run_id=15892582087

**Comment by jessicl-ms** [comment]
Swagger SemanticValidation errors are in files owned by different teams. Please advise on how to bypass. 

Link to errors: https://github.com/Azure/azure-rest-api-specs/pull/24387/checks?check_run_id=15892582133

**Comment by jessicl-ms** [comment]
> > **Swagger LintDiff, ~[Staging] Swagger LintDiff**
> > 
> > * Is there a way around Error PutRequestResponseSchemeArm? We do not want a PATCH API available for this resource. `A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'KeyGroups_CreateUpdate' Request Model: 'parameters[5].schema' Response Model: 'responses[200].schema' Location: [Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635](https://github.com/Azure/azure-rest-api-specs/blob/87428d4c15b9ace4427ab68a762c46b623e4d26b/specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json#L3635)`
> > * What kind of error response is error LroErrorContent looking for? This new resource is suing the same lro error we are using for other preexisting operations.
> > * Is Error DeleteResponseCodes saying I need to remove 200 response from delete API?
> 
> The failure for [PutRequestResponseSchemeArm](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-request-response-scheme-arm.md) is a false alarm. Please apply a suppression for it. image

Suppression has been added to our readme.md

**Comment by TimLovellSmith** [comment]
>Swagger Avocado errors are from files owned by other feature teams. I had rebased with Azure:main, but the error still show up. Please advise on how to resolve or if these errors can be bypassed.

I'm not sure why you got so many errors. However I'm a little curious about this claim:

>Swagger ModelValidation errors are also in files unrelated to this PR. The file cdn.json is owned by our team, but is for a different customer SKU that will not be using the urlsigning key feature being introduced in 2023-07-01-preview. The remaining errors are in files owned by other feature teams. Please advise on how to resolve or bypass.

>Link to errors: https://github.com/Azure/azure-rest-api-specs/pull/24387/checks?check_run_id=15892582087

So simplistic question, if its in the swagger file you're changing, shouldn't we try to address any model validation errors? For instance, if you did have a problem with a different customer SKU, but you're adding urlsigning feature, won't you want them to work together in the future, and so want to figure out how to design the API that way, so that we don't get errors when they're potentially combined, or SDKs are generated which have to work with both of them but the compiler is in ignorance of all the domain constraints?

**Comment by TimLovellSmith** [comment]
Are these inter-preview-version breaking changes intended?

>⚠️ 1011 - AddingResponseCode	The new version adds a response code '202'.
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L392:11
⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'canMigrate' renamed or removed?
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'defaultSku' renamed or removed?
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'errors' renamed or removed?
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'migratedProfileResourceId' renamed or removed?
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L3022:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2991:7
⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'errors' renamed or removed?
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L3022:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2991:7
⚠️ 1044 - XmsLongRunningOperationChanged	The new version has a different 'x-ms-longrunning-operation' value than the previous one.
New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L354:7
Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L354:7

**Comment by TimLovellSmith** [comment]
By ARMChangesRequested I mainly mean please clarify. :)

**Comment by TimLovellSmith** [comment]
[And the changes to review are just supposed to be between commits number 2 and 3, is that right?]

**Comment by jessicl-ms** [comment]
> Are these inter-preview-version breaking changes intended?
> 
> > ⚠️ 1011 - AddingResponseCode	The new version adds a response code '202'.
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L392:11
> > ⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'canMigrate' renamed or removed?
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
> > ⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'defaultSku' renamed or removed?
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
> > ⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'errors' renamed or removed?
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L2883:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2871:7
> > ⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'migratedProfileResourceId' renamed or removed?
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L3022:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2991:7
> > ⚠️ 1033 - RemovedProperty	The new version is missing a property found in the old version. Was 'errors' renamed or removed?
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L3022:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L2991:7
> > ⚠️ 1044 - XmsLongRunningOperationChanged	The new version has a different 'x-ms-longrunning-operation' value than the previous one.
> > New: Microsoft.Cdn/preview/2023-07-01-preview/cdn.json#L354:7
> > Old: Microsoft.Cdn/preview/2022-11-01-preview/cdn.json#L354:7

These differences are by design. The 2023-07-01-preview version in this PR is based on 2023-05-01 stable version. The features in 2022-11-01-preview have already been moved into 2023-05-01 stable version. However, they were removed in 2023-05-01 stable version to fix PS/CLI issues. Here is the commit: https://github.com/Azure/azure-rest-api-specs/commit/baa84c2856db44c1d8f00d1d296d66118a998fd3.

**Comment by jessicl-ms** [comment]
> [And the changes to review are just supposed to be between commits number 2 and 3, is that right?]

Yes, the changes to review are primarily commit number 3 "Update to new api and rebase all api validation fixes." I have been merging additional changes into this commit.

**Comment by jessicl-ms** [comment]
> > Swagger Avocado errors are from files owned by other feature teams. I had rebased with Azure:main, but the error still show up. Please advise on how to resolve or if these errors can be bypassed.
> 
> I'm not sure why you got so many errors. However I'm a little curious about this claim:
> 
> > Swagger ModelValidation errors are also in files unrelated to this PR. The file cdn.json is owned by our team, but is for a different customer SKU that will not be using the urlsigning key feature being introduced in 2023-07-01-preview. The remaining errors are in files owned by other feature teams. Please advise on how to resolve or bypass.
> 
> > Link to errors: https://github.com/Azure/azure-rest-api-specs/pull/24387/checks?check_run_id=15892582087
> 
> So simplistic question, if its in the swagger file you're changing, shouldn't we try to address any model validation errors? For instance, if you did have a problem with a different customer SKU, but you're adding urlsigning feature, won't you want them to work together in the future, and so want to figure out how to design the API that way, so that we don't get errors when they're potentially combined, or SDKs are generated which have to work with both of them but the compiler is in ignorance of all the domain constraints?

Fair point. I'll see if I can resolve the ModelValidation errors coming from cdn.json. The reason I would prefer not to is because those errors are in files that are for preexisting APIs that not added or changed in this PR, so I assume it had previously passed validation.

**Comment by sjanamma** [comment]
>             "description": "OK. Creation or update succeeded.",

200 is returned only for updates. Description can be updated to say Update successful

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-07-01-preview/afdx.json:3674 in c7d75d7. [](commit_id = c7d75d7f5c41491360e8f0087e774988de694da8, deletion_comment = False)

**Comment by sjanamma** [comment]
@jessicl-ms - Please address the review comments. Adding ARMChangesRequested tag

**Comment by kazrael2119** [comment]
this js breaking is caused by :https://github.com/Azure/azure-rest-api-specs/pull/24164

**Comment by jessicl-ms** [comment]
> [kazrael2119](/kazrael2119)

**Comment by jessicl-ms** [comment]
> @jessicl-ms , please fix duplicate schema issue for Go sdk failure.
> 
> ```
> warning | PreCheck/DuplicateSchema | Duplicate Schema named 'DeliveryRuleAction' (6 differences):
> 01:29:23.777 cmderr 	[generator automation-v2]   - discriminator: {"propertyName":"name"} => <none>
> 01:29:23.777 cmderr 	[generator automation-v2]   - properties: {"name":{"x-ms-enum":{"name":"DeliveryRuleAction","modelAsString":true},"$ref":"#/components/schemas/DeliveryRuleAction","description":"The name of the action for the delivery rule."}} => <none>
> 01:29:23.777 cmderr 	[generator automation-v2]   - required: ["name"] => <none>
> 01:29:23.777 cmderr 	[generator automation-v2]   - type: "object" => "string"
> 01:29:23.777 cmderr 	[generator automation-v2]   - enum: <none> => ["CacheExpiration","CacheKeyQueryString","ModifyRequestHeader","ModifyResponseHeader","UrlRedirect","UrlRewrite","UrlSigning","OriginGroupOverride","RouteConfigurationOverride"]
> 01:29:23.777 cmderr 	[generator automation-v2]   - x-ms-enum: <none> => {"name":"DeliveryRuleAction","modelAsString":true}
> ```

#raych1 The error mislead me to think the duplicate was DeliveryRuleAction object, but upon close inspection, I found the duplicate object and removed it. There are still errors showing, but they are not in the namespaces/APIs owned by team. This is an issue I've posted about in the General API teams channel.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
