### PR TITLE
New VPN Client Protocol

### PR DESCRIPTION
**Pull request by henry416**
Added one new VPN client protocol enum

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
Hi, you need use the latest branch Network-2018-06-01
and same named fodler. Please make your PR to the 2018-06-01 instead of May one, not to master.

[Link to one note](
https://microsoft.sharepoint.com/teams/WAG/AzureNetworking/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#Swagger%20-%3e%20SDK%20-%3e%20PowerShell&section-id={96F7B95B-A378-4CA5-903B-C88F894873EF}&page-id={71B816ED-DAE5-4907-94D8-DE7EE13278A0}&end)

**Comment by henry416** [comment]
@MikhailTryakhov I have moved the commit and retargeted the branch to 2018-06-01.
Will this allow production rollout at the end of June? Or is there an earlier one I can use?

**Comment by MikhailTryakhov** [comment]
@henry416  it would be done in time

**Review by MikhailTryakhov — APPROVED** [review]

**Review by MikhailTryakhov — COMMENTED** [review]
@henry416  sorry are your changes with correct indents?

**Comment by henry416** [comment]
@MikhailTryakhov Indented

**Comment by henry416** [comment]
@MikhailTryakhov When will SDK be generated?

**Pull request merged**
