### PR TITLE
Added SoftDeleteRetentionInDays,  CustomizedRecoverable and recoverableDays

### PR DESCRIPTION
**Pull request by gdlxm**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by heaths — CHANGES_REQUESTED** [review]
It's not just a question of `git rebase`, but actually making these changes in the preview/7.1/keyvault.json swagger file. 7.0 already shipped and preview/7.0 shouldn't exist, according to the swagger review guidelines.

**Review by heaths — CHANGES_REQUESTED** [review]
7.0 has shipped. You need to make your changes on the preview/7.1/keyvault.json file.

**Comment by tjprescott** [comment]
Resolve requested changes and failing CI.

**Comment by heaths** [comment]
This is the wrong PR anyway and should be closed. The files needed to go elsewhere (7.0 already shipped). I'll let @gdlxm close their own PR, though.

**Pull request closed without merging**
