### PR TITLE
Renamed BuildTask to FileTask and RunTask to EncodedTask in Azure Container registry Build GA swagger

### PR DESCRIPTION
**Pull request by mnltejaswini**
We have renamed some of the data models to reflect the data they represent. The example files are updated to reflect the new data models. There is no other change in the API. 

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by mnltejaswini** [comment]
@jhendrixMSFT  The SDKs for this swagger haven't yet merged in, It is still in development phase. So is it still a breaking change?

**Comment by jhendrixMSFT** [comment]
@mnltejaswini Merging a swagger into this repo is considered a release event (we have already released an SDK for this swagger in the Go programming language).  In addition, this swagger is in a ```stable``` directory.

**Comment by mnltejaswini** [comment]
@jhendrixMSFT  I see, thank you. Although the SDKs are available, the API is not yet available and exposed in ARM. so there aren't any potential customers

**Comment by jhendrixMSFT** [comment]
@mnltejaswini When will the API be available?  We should never merge a swagger into the public repo if the backing APIs aren't available.

**Comment by mnltejaswini** [comment]
@jhendrixMSFT  They will be available by 9/4

**Comment by jhendrixMSFT** [comment]
@johanste @ravbhatnagar do we leave this swagger until the release date?

**Comment by johanste** [comment]
@jhendrixMSFT - yes. We should update the title to include a [DO NOT MERGE] with this information included.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
