### PR TITLE
Add directives for Python object deserialization

### PR DESCRIPTION
**Pull request by alexeldeib**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by alexeldeib** [comment]
The schema of "table" object in the response should be array of array of "any" value type, but is actually array of array of strings. AFAIK, autorest still doesn't have a way to do this that is universal to all clients. On a per language basis I've looked at how to address this. For Python we can model this as an "object" type, producing the desired wildcard behavior.

Also overriding the client name. It's outdated branding, see also my comment in https://github.com/Azure/azure-rest-api-specs/pull/3269#discussion-diff-196604146R28

@lmazuel FYI

**Comment by hovsepm** [comment]
@lmazuel @annatisch could one of you take this PR? I have no idea about python directives.

**Comment by lmazuel** [comment]
@alexeldeib Sounds good to me!

@amarzavery @sarangan12 This is designed for "not strong types language" like Python and might interest you as well for NodeJS / Ruby. Maybe TS @RikkiGibson . This change a model type from "string" to "object" to keep the value in the JSON "as-is" and don't stringify it.

**Comment by RikkiGibson** [comment]
Ah, so does this transform make it so you don't just get a string of JSON-encoded data, but instead get the raw object tree returned by JSON.parse or the equivalent in the particular language?

**Comment by lmazuel** [comment]
@RikkiGibson correct. Because it can be integer, float, string, etc. exact types depends (I think of it as "excel cell content" analogy). Type is basic types enough so just showing the raw JSON value is enough.

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
