### PR TITLE
Sync from master. Improved code style

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
- Merged 2019-02-01 changes from master
- Updated 2019-04-01 basing on https://github.com/Azure/azure-rest-api-specs/pull/5783
- Fixed code style: trailing spaces, TABs -> spaces
- Fixed some indentation

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by MikhailTryakhov — APPROVED** [review]

**Comment by EvgenyAgafonchikov** [comment]
@sergey-shandar, @dsgouda, could you please take a look?
CI failures seem to come from search, datafactory, not network.

**Comment by dsgouda** [comment]
@EvgenyAgafonchikov Not sure I understand the purpose of this PR. Can't you simply create the April branch with latest master instead of merging this PR.
@MikhailTryakhov PTAL

**Comment by EvgenyAgafonchikov** [comment]
@dsgouda, I believe we already have April branch (set as target) and possible there are some changes merged, so we may miss changes recreating from master.
This PR also contains some code style issues fixes (two last commits).

**Comment by dsgouda** [comment]
Errors look unrelated to Network

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
