### PR TITLE
Move Microsoft.Managment definitions to their own folder

### PR DESCRIPTION
**Pull request by tjegbejimba**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>
Linked [Issue](https://github.com/Azure/azure-rest-api-specs/issues/11038)
Also solves name validation issued [here](https://github.com/Azure/azure-rest-api-specs/issues/13136)
### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
@tjegbejimba , could you fix the `avocado` errors?

**Comment by xiaoxuqi-ms** [comment]
@tjegbejimba there are still some errors, could  you fix the linting errors, prettierCheck errors? then we can move on to process breaking change issues.

**Comment by anthony-c-martin** [comment]
@xiaoxuqi-ms These APIs belong to `Microsoft.Resources`, not `Microsoft.Management`, and should not be moved to the `Microsoft.Management` folder. If the linter is incorrectly detecting them as owned by `Microsoft.Management`, then we need to fix the linter.

**Comment by majastrz** [comment]
> @xiaoxuqi-ms These APIs belong to `Microsoft.Resources`, not `Microsoft.Management`, and should not be moved to the `Microsoft.Management` folder. If the linter is incorrectly detecting them as owned by `Microsoft.Management`, then we need to fix the linter.

100% agree with this. The APIs in questions are operating on the resource type `Microsoft.Resources/deployments` at the management group level (which is of type `Microsoft.Management/managementGroups`). As @anthony-c-martin said, these belong in the swagger for `Microsoft.Resources` and not `Microsoft.Management`.

**Comment by xiaoxuqi-ms** [comment]
> @xiaoxuqi-ms These APIs belong to `Microsoft.Resources`, not `Microsoft.Management`, and should not be moved to the `Microsoft.Management` folder. If the linter is incorrectly detecting them as owned by `Microsoft.Management`, then we need to fix the linter.

@tjegbejimba , as @anthony-c-martin mentioned, since the operations do not belong to Miscrosoft.Management, is there any particular reason to move the operations to the folder of Miscrosoft.Management? And I believe that it is should be the owner of the apis who should move the apis to the proper folder.

**Comment by tjegbejimba** [comment]
@allenjzhang, as @anthony-c-martin, @majastrz, and @xiaoxuqi-ms mentioned,  would it make more sense to fix the linter errors caused by the deployment operations at management scope vs moving them into their own folder?

**Comment by tjegbejimba** [comment]
Instead of moving management operations, linter issues will be suppressed for existing operations

**Pull request closed without merging**
