### PR TITLE
Add missing nextLink fields to types returned from pageable operations.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@gatneil This fixes SDK generation for this API version (it's broken without this change), could you please take a look?

**Comment by gatneil** [comment]
I agree with these changes but would also want a quick review from @huangpf or @hyonholee. If they approve, I can include this set of changes in a PR into the CPlat swagger

**Comment by jhendrixMSFT** [comment]
Any update?  @gatneil @huangpf @hyonholee

**Comment by jhendrixMSFT** [comment]
@veronicagg @lmazuel would you two mind taking a quick look at this PR?  I'm also curious how Ruby and Python generations work with this swagger considering it is malformed.

**Comment by lmazuel** [comment]
@jhendrixMSFT For Python, if the pageable extension is used, we assume that the property is called "NextLink" ([code](https://github.com/Azure/autorest.python/blob/74a42527834672bbf98efc93755d785ae2db0708/src/azure/TransformerPya.cs#L96)).

However, I dislike the description that is C# oriented. Python for instance does not generate "ListNext()" (we use a protocol iterator that makes this useless). RestAPI documentation will also be misleading. I would suggest make this description more "pure".

**Comment by jhendrixMSFT** [comment]
@lmazuel I just copy/pasted the description from newer swagger but I agree that it has a C# bias.
@amarzavery do you have anything to add here?  The Go generator isn't as lenient as Python so the missing nextLink field means we fail to generate an SDK for this swagger.

**Comment by huangpf** [comment]
We were told every spec change needs to be associated with a C# test. Where is it?

**Review by huangpf — CHANGES_REQUESTED** [review]
Need associated C# tests.

**Comment by jhendrixMSFT** [comment]
@huangpf there is no need to update a test as this is fixing a bug that other generators work around (i.e. the end result is identical, I generated the .NET SDK without and with this change and there is no change).

**Comment by huangpf** [comment]
Sure, that sounds fine. But just for auto-validation's context, there should be a validation step, or something, to auto-show us what you described -- identical C# code.

@veronicagg @lmazuel @amarzavery Thoughts?

**Comment by jhendrixMSFT** [comment]
It should also be fixed in the linter so that bugs like this never make it into swagger.

**Comment by huangpf** [comment]
@jhendrixMSFT I understand & agree with the intention, I'm just asking on behalf of the 1st tier C# code contributors, what's the programmatic way to determine if C# code will be broken or not.

**Comment by jhendrixMSFT** [comment]
Does the C# SDK even use this API version any more?  It's quite old and last I heard they don't yet support multiple API versions.

**Comment by huangpf** [comment]
I'm not sure, thus I'm asking how we can make sure the C# repo won't be affect by this change:
```https://github.com/Azure/azure-sdk-for-net```

It's probably fine to talk or comment thru this, but I'm looking for a "robotic" way to tell, maybe here by some trigger to run the playback tests across repo?

**Comment by jhendrixMSFT** [comment]
@shahabhijeet can you answer @huangpf question?

**Comment by huangpf** [comment]
@hyonholee @alpon FYI

**Comment by veronicagg** [comment]
@jhendrixMSFT regarding your question on code generation for Ruby, we will generate code, but the model won't contain next link, therefore trying to accessing it at runtime will fail. Here's how our model mapper looks https://locations.maggianos.com/washington/bellevue/10455-ne-8th-st./delivery/, I'd expect this to fail - https://github.com/Azure/azure-sdk-for-ruby/blob/e5f570c5270d7b82308b0a7c52879616daf8b76c/management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/list_usages_result.rb#L45

**Comment by veronicagg** [comment]
@jhendrixMSFT regarding linter validation, I would have expected this rule [NextLinkPropertyMustExist](https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-automated-guidelines.md#r2025-nextlinkpropertymustexist) (Ref to [code for this rule](https://github.com/Azure/azure-openapi-validator/blob/42ae8eedab0a3894443966e4513fd28ae5aa77d8/src/dotnet/OpenAPI.Validator/Validation/Extensions/NextLinkPropertyMustExist.cs#L11)) to report the issue, was it not being reported?

**Comment by veronicagg** [comment]
@jhendrixMSFT @huangpf FYI - to generate the code for C# and look for differences, you could use our VS Code extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest to open the spec and use the code generation feature (button on the status bar at the bottom) to show you the generated code - you could then make changes to the spec, re-run generation; then compare outputs.

**Comment by huangpf** [comment]
@veronicagg Can this diff lookup be part of the PR validation here? It's not efficient to request developers for specific languages to cross-validate all others. Thanks.

**Comment by veronicagg** [comment]
@huangpf yes, I expect we will be hooking up something like this starting the new year, we already have a tool running for some of the languages (swagger_to_sdk) which creates a PR on language SDK repos with the changes submitted in the specs repo (this repo) - it currently happens at merge (for python, ruby and node) and we're looking to extend it for pushes to PRs and all languages. 
@marstr will be working on this.
@shahabhijeet may have specific context for C#.
FYI - @salameer

**Comment by shahabhijeet** [comment]
@huangpf there isn't an automated way to test C# tests with a change applied to previous version.
You will have to generate the SDK and test it with the tests.

**Comment by huangpf** [comment]
@shahabhijeet Is it feasible for you to build a more comprehensive validation mechanism, so PRs can be validated across different SDK client libraries? Self-generating & tests will be error prone and not scalable.

**Comment by shahabhijeet** [comment]
@huangpf are you suggesting a way to validate spec PRs against SDK tests?

**Comment by huangpf** [comment]
@shahabhijeet I think you can consider that -- it's because the (current) main concern of service teams (CRP/DiskRP etc.) are C# & PS.

**Comment by jhendrixMSFT** [comment]
@shahabhijeet can you please confirm that this old API version spec isn't the one used in the C# SDK?  Per our offline conversation that appears to be the case.  For SDKs that support multiple (all) API versions (which I believe C# does not) this spec is *broken* and generating broken code.

**Comment by jhendrixMSFT** [comment]
@huangpf Looking at the props file it looks to me that the C# SDK doesn't use this API version.
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/AzSdk.RP.props
@shahabhijeet can you confirm?  I'd like to get this merged as this is blocking building this API version for Go.

**Comment by huangpf** [comment]
@jhendrixMSFT Then why adding it to an old spec, why not the new one and all current ones?

**Comment by jhendrixMSFT** [comment]
@huangpf This has been fixed in newer specs.  The Go SDK (and others) builds packages for *all* API versions, this one is broken and needs to be fixed.

**Comment by jhendrixMSFT** [comment]
Ping @huangpf, this has been lingering and I'd like to get this merged.

**Comment by huangpf** [comment]
+@hyonholee

I don't think our concern is addressed yet -- if any spec is affecting our latest C# SDK, how can we know?

Can you or @shahabhijeet create an associated task to follow up with the ask here to figure out a way to PR-validate different SDKs, other than code reviews?

**Comment by jhendrixMSFT** [comment]
Regarding if a spec affects the latest C# SDK you have to look at the [props file](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/AzSdk.RP.props) used to when generating that part of the SDK to see the API version.  I don't know of a better way, maybe @shahabhijeet does.

Regarding automated testing of other SDKs, I worked with @sergey-shandar on a prototype of this last year, it has been put on hold due to higher priorities.  I don't know when this work will resume, maybe Sergey does.

**Comment by jhendrixMSFT** [comment]
I've opened issue https://github.com/Azure/azure-rest-api-specs/issues/2270 to track updating the specs repo CI with more comprehensive validation.  Any other feedback?

**Comment by huangpf** [comment]
LGTM. Thanks @jhendrixMSFT

**Review by marstr — APPROVED** [review]

**Pull request merged**
