### PR TITLE
[Hub Generated] Review request for Microsoft.Batch to add version stable/2020-05-01

### PR DESCRIPTION
**Pull request by jafreck**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/jafreck/azure-rest-api-specs/dev-batch-Microsoft.Batch-2020-08-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
Hi @jafreck, Can you help fix Avocado validation failure first?

**Comment by chiragg4u** [comment]
Please go through the contribution checklist added as part of the review and mark them completed. This is a requirement before review can be continued.

**Comment by jafreck** [comment]
@chiragg4u The contribution checklist has been updated.

@akning-ms can you clarify the ask here?

**Comment by jafreck** [comment]
@akning-ms My request to rerun the Avocado validation appears to not be working.

**Comment by akning-ms** [comment]
> @akning-ms My request to rerun the Avocado validation appears to not be working.

Can I know why re-run it? seems you did not make change to your swagger. you can also refer to below guide to run it locally to find hwo to fix it? https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#avocado
@ruowan to further help if you need.  and also pls fix PrettierCheck refer to above  doc

**Comment by akning-ms** [comment]
Hi @jafreck, Pls let us know if any help need to fix validation error. if PR is not ready for review. move it to draft or label it NotReadyForReview.

**Pull request closed without merging**
