### PR TITLE
Fixed error with return results and removed unsupported operation.

### PR DESCRIPTION
**Pull request by deathly809**
I was returning the wrong object in multiple places.  I also removed an unsupported operation that the RP PM told me about.  I have changed and tested change in C#.

### CODE REVIEW

**Comment by deathly809** [comment]
@sarangan12 Could you take a gander?

**Comment by deathly809** [comment]
@sergey-shandar There are no breaking changes because we have not released anything and in addition the changes I made was because they did not work in the first place.

**Comment by salameer** [comment]
@deathly809 just to point out here, if there's an earlier version that has been merged on our side, potentially anyone can generate an SDK for it, so it's not necessarily a breaking change for the officially released SDK but indicates that the changes in the swagger are breaking changes from the previous states that was checked in, does that make sense?

**Comment by deathly809** [comment]
@salameer Sure, but if they are using it their code won't ever work.  So I don't know what it would be breaking.

**Comment by salameer** [comment]
Agreed, Breaking changes usually mean that the interface for an SDK or Behavior will change.

So Breaking changes are Sometime Good and introduce fixes :) 

In your case it wont really change anything but it simply informs whoever already generated from your  swagger that changes are coming. 

What's  probably recommended going forward is to avoid introducing  Swaggers that are expecting breaking changes and major changes to the Current branch for a specific API version and only submit it their when the swagger is complete and correctly representing the service

I hope this helped :)

**Comment by deathly809** [comment]
@salameer  When I did my original pull request I was told by all RPs involved that what I had was good.  Then later the owner of the RP said that two operations don't actually exist.  Do you have an estimate on how long will it take before I know this will be accepted?  The C# has already been accepted and I am about to do the PS PR.

**Review by sergey-shandar — APPROVED** [review]
It's potential breaking changes for SDK (api-version is **2016**). But everything else looks good for me.

**Review by sameralameer — APPROVED** [review]
Given that you mentioned that these operation don't exist I'll take your word on it. Normally we have to get ARMs approval for reviewing removal of operations but like I said if the  RP owner says they're not their :) then we'll approve from our side. Adding @ravbhatnagar for visibility and please Gaurav let us new if we need to pull back here

**Comment by salameer** [comment]
Given that you mentioned that these operation don't exist I'll take your word on it. Normally we have to get ARMs approval for reviewing removal of operations but like I said if the RP owner says they're not their :) then we'll approve from our side. Adding @ravbhatnagar for visibility and please Gaurav let us new if we need to pull back here

**Comment by salameer** [comment]
Hi @deathly809 

To provide a very precise estimate, I would say the ETA will be exacly: -9 Minutes Ago LOL

**Comment by deathly809** [comment]
@salameer Thanks.  I can forward you the email where the RP said to remove them if you need.

**Pull request merged**
