### PR TITLE
[DO NOT MERGE] Add Premium to EventHub SKU name and tier enums

### PR DESCRIPTION
**Pull request by nyaghma**
This PR updates the Eventhub SKU name and tier enums (both modeled as string) by adding "Premium" to the allowed values. 

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by erich-wang** [comment]
Remove `WaitForARMFeedback` label as modifying properties does not need ARM review.

**Comment by erich-wang** [comment]
@nyaghma, could you explain why do you add label `DoNotMerge`, is this PR ready for review?

**Comment by nyaghma** [comment]
@erich-wang I'm sending this PR to make sure the changes that I've made to the API are not being considered as breaking changes (referring to this [document](https://microsoft.sharepoint.com/:w:/t/azureresourcemanagerteam/EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw?e=xEcppo)). Since the required changes in the backend are not complete yet, I added the label DoNotMerge. We need to know if a new API version would be required for the proposed API changes or not in order to complete our backend development.

**Comment by erich-wang** [comment]
Adding new enum value is considered as breaking change per https://github.com/Azure/openapi-diff/blob/master/docs/rules/1020.md

**Comment by nyaghma** [comment]
@erich-wang Is this true even for the Enums that are modeled as string? The document I shared says adding value to Enum is non-breaking if it's modeled as string in the swagger. The link you shared doesn't specifically talk about the "modeledAsString" Enums, so I'm wondering if there is an exception for this type of Enums or the document I referred to is out of date.

**Comment by erich-wang** [comment]
@nyaghma, you're right, it is not considered as breaking change if modelAsString is set as true. I just talked with AME swagger team to update the rules, thanks.

**Review by erich-wang — APPROVED** [review]

**Comment by erich-wang** [comment]
@nyaghma , please let us know when it is ready to merge, thanks.

**Comment by erich-wang** [comment]
@nyaghma, what is current status for this PR? I'll close this PR within 5 biz days if no response from you, thanks.

**Comment by erich-wang** [comment]
@nyaghma, I'm closing this PR as there's no response from your side for long time, please reopen this PR if necessary, thanks.

**Pull request closed without merging**
