### PR TITLE
Brooklyn Ignite Swagger changes

### PR DESCRIPTION
**Pull request by ritwikbasu**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by ritwikbasu** [comment]
@nalinrajgupta, @maiqbal11, @Nilambari, @gsumit10 - this is the combined Swagger PR. Please check if all of your changes have been incorporated here.

**Comment by sergey-shandar** [comment]
@ravbhatnagar new operations

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
There are some errors in examples which could be introduced before this PR. You can see the problems here https://travis-ci.org/Azure/azure-rest-api-specs/jobs/421857838 . @ritwikbasu could you fix these issues?

**Comment by sergey-shandar** [comment]
@ritwikbasu please, resolve conflicts.

**Comment by ritwikbasu** [comment]
Fixed merge conflicts and error examples for VnetGateway and S2S.

**Comment by ravbhatnagar** [comment]
some changes in this PR dont seem to have been reviewed in person. Working with @ritwikbasu to go over those. Specially availableDelegations.

**Comment by ravbhatnagar** [comment]
After talking with Ritwik, it Looks like there are a bunch of unrelated changes that are been shown on this PR due to pulling the upstream branch. This PR should only be for APIs related to virtualWAN and example file updates. ARM has already reviewed and signed off on those. So once the PR is fixed to show only the relevant changes, this is good from ARM side. @sergey-shandar  FYI.

**Comment by ritwikbasu** [comment]
We have resolved all comments. Can someone please merge this PR?

**Comment by sergey-shandar** [comment]
@ritwikbasu there are still some model validation errors https://travis-ci.org/Azure/azure-rest-api-specs/jobs/425920005. Could you fix it?

**Comment by ritwikbasu** [comment]
@sergey-shandar Fixed issues. Please review.

**Comment by sergey-shandar** [comment]
https://travis-ci.org/Azure/azure-rest-api-specs/builds/426894074

**Comment by MikhailTryakhov** [comment]
@sergey-shandar  looks like job provided is passed. can we merge this PR?

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
