### PR TITLE
Adding patch support for SQR API

### PR DESCRIPTION
**Pull request by abversqr**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
Thanks @abversqr - is this API already live/public?

**Comment by annatisch** [comment]
@abversqr - your github account is not currently in the Azure org - can you please add it?

**Comment by abversqr** [comment]
```
Thanks @abversqr - is this API already live/public?
```
@annatisch Yes, API is already public. This PR is just to add support of PATCH

**Comment by msvijayn** [comment]
Linked to issue #[8760](https://github.com/MicrosoftDocs/azure-docs/issues/8760)

**Comment by annatisch** [comment]
@abversqr - your last commit broke the CI:
Duplicated model name with non-identical definition

**Review by ravbhatnagar — APPROVED** [review]
Looks good!

**Comment by annatisch** [comment]
Hi @abversqr - The CI issue here is due to a bug fix in autorest core that was recently rolled out to prevent conflicting models in SDK generation (not Python only, it’s cross-language).

If two files that are in the same “tag” in the Readme defines the same model name Foo, both objects have to be exactly (at the comma level) the same, or they have to be a reference to an external common file.
This cannot be suppressed with a suppression, this is required to be fixed since it’s a critical bug.
 
The fix is simple, either make sure all models that are described in several files are exactly the same, or ref an external model.

**Comment by abversqr** [comment]
Hi @annatisch , I have fixed model name issue. Please have a look

**Pull request merged**
