### PR TITLE
python sdk configuration in powerbidedicated

### PR DESCRIPTION
**Pull request by zikalino**

### CODE REVIEW

**Comment by NullMDR** [comment]
Hi @zikalino there are some conflict. Do you want to resolve or close this PR?

**Comment by NullMDR** [comment]
@zikalino Do you still want this PR?

**Comment by NullMDR** [comment]
@zikalino I'll close this PR if you do not respond

**Comment by JackTn** [comment]
Hi, @zikalino. The PR has be closed for a long time and it's related branch still exist. If no further used for over 14 days, I will delete this related branch. Please tell me if you still need this branch.

**Comment by JackTn** [comment]
Hi, @zikalino. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
