### PR TITLE
Fix AMA swagger for completeness. R3007

### PR DESCRIPTION
**Pull request by vayada**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by vayada** [comment]
This fix is being made for following S360 for swagger completeness.
https://portal.azure-devex-tools.com/amekpis/linting/detail?errorId=721D62A4-4696-4718-A8E1-3CC05D1AAA7A

**Comment by vayada** [comment]
@leni-msft Can you please review this PR. This is for fixing S360 issues.

**Comment by leni-msft** [comment]
@jianyexi please help reivew this PR fixing Lint R3007 PutGetPatchResponseSchema

**Review by jianyexi — APPROVED** [review]

**Comment by leni-msft** [comment]
@vayada please request breaking change approval following Action in https://github.com/Azure/azure-rest-api-specs/pull/20667#issuecomment-1244931406 . and fix the Lint(RPaaS) error

**Comment by leni-msft** [comment]
@tadelesh please help check go sdk breaking changes

**Comment by vayada** [comment]
> @vayada please request breaking change approval following Action in [#20667 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/20667#issuecomment-1244931406) . and fix the Lint(RPaaS) error

@leni-msft  RPaaS Linter errors are false alarm as agreed with RPaaS team. As you can see this is not coming from current change. We have exception for this since starting. 
I will request Breaking Change Approval for this.

**Comment by tadelesh** [comment]
> @tadelesh please help check go sdk breaking changes

Will review after breaking change arch review.

**Comment by vayada** [comment]
@tadelesh Breaking Change ARCH review wants you to review first. So, can you please do that.

**Comment by tadelesh** [comment]
> @tadelesh Breaking Change ARCH review wants you to review first. So, can you please do that.

The Go breaking is from this old [PR](https://github.com/Azure/azure-rest-api-specs/pull/19826). @leni-msft I don't know how to handle the swagger breaking from this PR, could you help?

**Comment by leni-msft** [comment]
@josefree Could you give guidance here? This PR is to fix S360 Lint error, and may cause breaking changes to both API and SDK.

**Comment by tadelesh** [comment]
Approved for Go breaking as it is caused by this [PR](https://github.com/Azure/azure-rest-api-specs/pull/19826).

**Comment by leni-msft** [comment]
@vayada Go SDK breaking changes have been approved, please request BC board review

**Pull request closed without merging**
