### PR TITLE
[Blueprints] Add a new example file for using user-assigned MSI 

### PR DESCRIPTION
**Pull request by filizt**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by filizt** [comment]
@jhendrixMSFT I looked at the failing jobs. We had the same failures in our previous PR and they were suppressed and the PR was merged. You can find it here: https://github.com/Azure/azure-rest-api-specs/pull/5872. 

These failures are specifically around the ParameterValueBase property and its polymorphic relation to ParameterValue. It seems like the model validation tool is not seeing this relationship and complaining that the "value" parameter in the request examples are not complaint. What would be a recommended way to solve this issue? 

Please let me know if we can also suppress these failures for this PR. I can create a separate PR to fix the above mentioned issue that causes some of the checks to fail.

**Comment by shahabhijeet** [comment]
@sergey-shandar can you comment on the above comment about model validation "potentially" showing false negatives.

**Comment by sergey-shandar** [comment]
@filizt In OpenAPI 2.0 if `additionalProperties` are not specified, then they are not allowed. If the [ParameterValueBase](https://github.com/Azure/azure-rest-api-specs/blob/4a0ddd1dcb2a14fd045d06c318c48821be900366/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintAssignment.json#L404) is a polymorphic type, please use `"additionalProperties": { "type": ... }`.

**Comment by filizt** [comment]
> @filizt In OpenAPI 2.0 if `additionalProperties` is not specified, then additional properties are not allowed. If the [ParameterValueBase](https://github.com/Azure/azure-rest-api-specs/blob/4a0ddd1dcb2a14fd045d06c318c48821be900366/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintAssignment.json#L404) is a polymorphic type, please use `"additionalProperties": { "type": ... }`.

@sergey-shandar I am not sure if I understand how "additionalProperties" will fix the issue here. Adding @majastrz to help explain a bit more.

**Comment by majastrz** [comment]
> > @filizt In OpenAPI 2.0 if `additionalProperties` is not specified, then additional properties are not allowed. If the [ParameterValueBase](https://github.com/Azure/azure-rest-api-specs/blob/4a0ddd1dcb2a14fd045d06c318c48821be900366/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintAssignment.json#L404) is a polymorphic type, please use `"additionalProperties": { "type": ... }`.
> 
> @sergey-shandar I am not sure if I understand how "additionalProperties" will fix the issue here. Adding @majastrz to help explain the issue a bit more.

@sergey-shandar, we're basically looking for the best way to model the following JSON:
```
"parameter": {
  "foo": {
    "value": 42
  },
  "bar": {
    "reference": {
       ...
    }
  }
}
```
The parameter value should either be have a `reference` or `value` property set, but (ideally) not both. One workaround I can think of is just to create a `ParameterValue` definition in the swagger with both `value` and `reference` properties as optional, but I'm hoping you can recommend some better solution.

**Comment by filizt** [comment]
@shahabhijeet Can we suppress the checks and merge the changes? We would not want to hold the PR since the issue discussed here is not new and is not caused by the change in this PR. I can create a separate item in the repo's "Issues" section to discuss this issue in detail. Let me know if you want me to go ahead and create a new issue.

**Comment by shahabhijeet** [comment]
@sergey-shandar  will be the right person who can answer the question about supression.

**Comment by sergey-shandar** [comment]
@majastrz for OpenAPI 2.0 it is the way. Create a type that has two optional properties. Open-API 3.0 should support `"oneOf"` but we don't support 3.0 yet.

**Comment by sergey-shandar** [comment]
@filizt @majastrz could you create a new PR and we will merge this?

**Comment by filizt** [comment]
> @filizt @majastrz could you create a new PR to fix model validation issues and we will merge this?

Created the following PR to follow up on a fix for the model validation errors: https://github.com/Azure/azure-rest-api-specs/pull/6394

Can you merge this one please?

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/6297

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
