### PR TITLE
Spec fixed to reflect new examples property

### PR DESCRIPTION
**Pull request by VitaliyKurokhtin**
There was a change in our API version 2021-01-01-preview that was not documented, this PR addresses the issue. To be clear, there is no behavior change on our side, remoted property "sample" is ignored under 2021-01-01-preview API version, instead new property was added - "examples". Changes are already deployed (quite some time ago).

PR is to fix documentation and SDKs.

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by solankisamir — APPROVED** [review]

**Comment by VitaliyKurokhtin** [comment]
@leni-msft, could you help me understand what needs to be done to move this forward? We've got approval for breaking change. Two errors that I see are:
- LintDiff: "The schema 'ParameterExamplesContract' is considered an object but without a 'type:object', please add the missing 'type:object'" that is not true. When schema has no type defined it is effectively may be anything - we accept any valid JSON value in our API. What is the way to handle that?
- Breaking change tracking - we already have approval

**Comment by leni-msft** [comment]
@VitaliyKurokhtin To fix it, add `"type": "object"` to `ParameterExamplesContract`

**Comment by VitaliyKurokhtin** [comment]
@leni-msft, but that is not the same. `{"type":"object"}` will only allow objects, but not values like 5, or "string". Where as `{}` does allow everything. You can easily repo this here: https://www.jsonschemavalidator.net
image
image

**Comment by leni-msft** [comment]
@VitaliyKurokhtin Absolutely. If it's your intention to make `ParameterExamplesContract` to accept number or any other primitive types, you can suppress the LintRule in readme(see https://aka.ms/SwaggerSuppressionRequest). Otherwise, define it as `object`.

**Comment by VitaliyKurokhtin** [comment]
@leni-msft, I got approval and added suppression. Any way to merge it now?

**Review by jianyexi — APPROVED** [review]

**Pull request merged**
