### PR TITLE
Port of API updates from the 2017-09-01 version

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
This ports changes from https://github.com/Azure/azure-rest-api-specs/pull/1832 to 2017-10-01 version

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
Howdy @EvgenyAgafonchikov, thanks for porting these changes. I've evaluated the PR that you linked, and verified that the changes seem to be the same. Is there any concern that some of the updates would be incompatible or inapplicable to the earlier API Version?

**Comment by EvgenyAgafonchikov** [comment]
@marstr this is just copy of the previous API version to have new features in both versions after Network-2017-10-01 would be merged. So I think there would be no compatibility concerns/additions

**Comment by DeepakRajendranMsft** [comment]
@marstr please approve if everything is good. we this way we can merge the 10-01 version to current asap

**Comment by marstr** [comment]
Seems reasonable to me! Given that these changes match the original, I'm comfortable approving.

**Review by marstr — APPROVED** [review]
This matches previously approved changes.

**Comment by EvgenyAgafonchikov** [comment]
+Updated readme.md to include missing file

**Comment by marstr** [comment]
Is this ready for merge @EvgenyAgafonchikov?

**Comment by EvgenyAgafonchikov** [comment]
@marstr, yes, it's ready

**Pull request merged**
