### PR TITLE
Rename Firewall Policy child resource RuleGroup to RuleCollectionGroup

### PR DESCRIPTION
**Pull request by saisujithreddym**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>

Changes:
We had to revert the PR: https://github.com/Azure/azure-rest-api-specs/pull/9045 and https://github.com/Azure/azure-rest-api-specs/pull/9246 for the april release as we did not have the backend support. We are making the same PRs merged together against the may branch now

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by mmyyrroonn — APPROVED** [review]
Just want to confirm. We have done this once for 2020-04-01 before. Didn't we copy the latest version for 2020-05-01?

**Comment by saisujithreddym** [comment]
@MyronFanQiu The PR for the 2020-04-01 was reverted for the new naming and the other pr was closed before merging. So we do not have these changes for 2020-04-01

**Comment by number213** [comment]
FYI this would cause breaking change in Net SDK

**Review by anton-evseev — APPROVED** [review]

**Comment by saisujithreddym** [comment]
For the dnat rules changes: We are aware that this would be a breaking change and we have very limited numbers of users who uses dnat rules in the firewall policy right now. 

For the name changes in the firewall policy: This change will not be breaking once the nrp manifest is out to support 2020-05-01. We have the backend changes to give the response in the new schema starting 2020-05-01.

Moreover this feature is in preview and not GA. We are fine with answering the limited number of users who might encounter the issues.

**Comment by MyronFanQiu** [comment]
@number213 Please let me know when it's ok to merge. I think it's a big breaking change for .Net SDK.

**Comment by MyronFanQiu** [comment]
@chiragg4u Could you take a look at this PR?

**Comment by saisujithreddym** [comment]
@number213 @MyronFanQiu Please let me know if there is any update on this. I think it's ok to merge this as we will be making corresponding changes for the clients like powershell which are using the sdk soon.

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by saisujithreddym** [comment]
@number213 @MyronFanQiu Can you please merge this PR. I have the approval from ARM

**Comment by number213** [comment]
@MyronFanQiu  please merge

**Pull request merged**
