### PR TITLE
Fix SDK breaking change in 2017-10-01 DNS Swagger

### PR DESCRIPTION
**Pull request by nkindberg**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@nkindberg Hello!  I'm not sure what you mean by "fix breaking change" here, could you please clarify?

**Comment by nkindberg** [comment]
This PR is to fix an unintended SDK breaking change when we added this Swagger in PR #2558 

In order to support Zones_Update we changed "location" to not be required which resulted in Zone object constructor having the parameters moved around.

I am reverting that change to make location required again and then creating a separate specification for Zone update requests.

Also adding suppressions for linter errors which were approved by ARM.

@mcardosos can you help review this since you already have the context from the original changes?

**Review by mcardosos — CHANGES_REQUESTED** [review]
Also using the linter rule names is better for humans :D

**Review by mcardosos — APPROVED** [review]
Looks good from suppressions side. Anything to add @jhendrixMSFT  ?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
