### PR TITLE
[Hub Generated] Review request for Microsoft.Media to add version preview/2019-05-01-preview and stable/2018-07-01

### PR DESCRIPTION
**Pull request by BrianBlum**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/BrianBlum/azure-rest-api-specs/dev-mediaservices-Microsoft.Media-2019-05-01-preview...master/:tab?).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by BrianBlum** [comment]
Will review the issues with the examples in subsequent PRs

**Review by tjprescott — APPROVED** [review]
No model or semantic validation errors introduced by this change. The linter could not run.

**Comment by tjprescott** [comment]
Can't merge this due to the failing checks.

**Comment by BrianBlum** [comment]
@AutorestCI the failure in the first check is a exception thrown by the diff tool. Is there anything I can do to resolve that?
Thanks

**Comment by BrianBlum** [comment]
@tjprescott Any idea why [files aren't being passed to autorest](https://dev.azure.com/azure-sdk/public/_build/results?buildId=49925&view=logs&jobId=957f396e-b28a-53c4-b5bb-b8c6d959bd2d&taskId=142feabb-6d02-5968-caa1-f5b3c04c5cae&lineStart=128&lineEnd=135&colStart=1&colEnd=70)?

**Comment by tjprescott** [comment]
@BrianBlum I'm not sure. I mentioned your PR in the Swagger reviewers channel to see if someone else has an idea.

**Comment by BrianBlum** [comment]
Thanks @tjprescott

**Comment by BrianBlum** [comment]
@AutorestCI generate azure-sdk-for-net

**Comment by BrianBlum** [comment]
@AutorestCI regenerate azure-sdk-for-net

**Comment by BrianBlum** [comment]
@tjprescott I found the bad package tag in the readme.md. And there was a typo in a description that was causing a failure in csharp generation.

**Comment by BrianBlum** [comment]
@tjprescott Thanks Travis.

**Pull request merged**
