### PR TITLE
{VirtualWan} {HubRouteTables} : Fix parameter type

### PR DESCRIPTION
**Pull request by nagula-ritvika**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by shyamshd** [comment]
This change done for 2020-05-01 contains one more additional change for VirtualHubEffectiveRouteEffectiveRouteList-
https://github.com/Azure/azure-rest-api-specs/commit/402ad4a20a97eefb52d35c6bb61022d2ae29206e

Please make sure that it gets to any forward versions .. in case it has branched out to a network-july / network-august etc. and comes back into master.

**Comment by allenjzhang** [comment]
This is a breaking change on a stable version of API. Per new guidelines, it is not allowed.

**Comment by nagula-ritvika** [comment]
@allenjzhang : when the new folder for 06-01 was created a PR which included these fixes was missed and now our PS cmdlets are broken. this is not a new breaking change that is being introduced but rather just manually adding back the missed changes.

https://github.com/Azure/azure-rest-api-specs/pull/9839 - this was the original PR which fixed the api versions 04-01 and 05-01 and was checked in to the master branch.

**Comment by chiragg4u** [comment]
Marking ARM approved based on the PR #9839 and the changes are same.
Please make sure that there is no customer impact for these changes.

**Comment by nagula-ritvika** [comment]
Thank you very much, we are actually broken without these changes. @chiragg4u Do you who can help merge this in ?

**Comment by nagula-ritvika** [comment]
@lirenhe @v-shhatt - can you please help with this PR

**Review by allenjzhang — COMMENTED** [review]
**SDKs have been released**. These constitute both swagger and SDK breaking change. You would need **Breaking change board** to sign off on this.

**Comment by shyamshd** [comment]
Allen,

Didn't Chirag already approve it? Also, please note that this shouldn't
qualify as a breaking change. The current swagger and powershell are broken
for Virtual Wan route table commands and the change is trying to fix it.
The older 05-01 api version already has the change, but 06-01 api version
is broken because the change was not correctly carried over to the 06-01
swagger folder. We don't quite understand how it landed up in that state,
probably a question you might be able to help answer.

Request you to merge the change ASAP. This is blocking some of the
powershell deployments.

Thanks,
Shyam

**Review by allenjzhang — APPROVED** [review]

**Comment by allenjzhang** [comment]
Thanks for the explanation. There is now a lot of focus been put on breaking changes that cause customer pain points. Hence the increased scrutiny.

**Comment by nagula-ritvika** [comment]
@shyamshd @allenjzhang thank you very much !
How/who do we reach out to for the new sdk build ?

**Pull request merged**
