### PR TITLE
Adding isIPv6Enabled argument for server

### PR DESCRIPTION
**Pull request by LeiWang3**
This argument is to enable IPv6 firewall rules features when user is creating a new server

### CODE REVIEW

**Comment by v-xuto** [comment]
@LeiWang3 Please follow this [comment](https://github.com/Azure/azure-rest-api-specs/pull/23967#issuecomment-1547134670) added by bot to proceed with breaking change review.

**Comment by ihsanali01** [comment]
Thanks for sharing this information with me. I'm grateful but please proceed further to make sure all these are taken care of before anything happens at final destination.

**Comment by v-xuto** [comment]
@JeffreyRichter Please help review the breaking change in this PR.

**Review by ericshape — CHANGES_REQUESTED** [review]
it is not allowed. please close this PR.

**Pull request closed without merging**
