### PR TITLE
Added featuresmode to spec

### PR DESCRIPTION
**Pull request by emmanuelrobles**
# Data Plane API - Pull Request

FeaturesMode is not on the search index spec, This PR adds it, one thing to keep in mind is that is show as in preview in the azure portal, [link](https://docs.microsoft.com/en-us/rest/api/searchservice/preview-api/search-documents)

## API Info: The Basics

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
No paths were updated, only change was add featuresMode to azure search index spec

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
add parameter requires new api-version

**Comment by emmanuelrobles** [comment]
> 



> add parameter requires new api-version

Thats something that is already supported on 2021-04-30 Preview, I dont see it in the spec file, maybe it was not added by mistake or it is not meant to be added since its on preview, if thats the case we can close the PR :)

image

**Comment by weidongxu-microsoft** [comment]
Add @Mohit-Chakraborty as owner

**Comment by emmanuelrobles** [comment]
> Add @Mohit-Chakraborty as owner

Not sure how to do that, sorry

**Comment by weidongxu-microsoft** [comment]
> Not sure how to do that, sorry

No problem. It just requires that internal procedure to fix the swagger, so we need approval from service owner (and maybe they need to drive the fix as well).

@arv100kri @bleroy

**Comment by emmanuelrobles** [comment]
> 



> > Not sure how to do that, sorry
> 
> No problem. It just requires certain internal procedure to fix the swagger (as it affect doc and SDK, etc.), so we need approval from service owner (and maybe they need to drive the fix as well).
> 
> @arv100kri @bleroy

Ohh, thanks, for the fix if we update this schema we could re-generate the code for the sdk, i was playing around with the sdk first and that's how I landed here :joy:, if this goes trough i can create a PR for the sdk as well

**Pull request closed without merging**
