### PR TITLE
Updating existing CRR APIs and protection APIs

### PR DESCRIPTION
**Pull request by pratimaupadhyay02**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by pratimaupadhyay02** [comment]
Created this new scenario for breaking change approval https://msazure.visualstudio.com/One/_workitems/edit/8668612

**Review by JeffreyRichter — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @pratimaupadhyay02 this PR breaks the autorest generation for tag package-2017-07, please provide a fix for this. Thanks.

Error messages:

FATAL: swagger-document/compose - FAILED
FATAL: Error: '$.definitions.BackupResourceConfig.properties.storageModelType.enum' has incompatible values (---
- Invalid
- GeoRedundant
- LocallyRedundant
- ZoneRedundant
- ReadAccessGeoZoneRedundant
, ---
- Invalid
- GeoRedundant
- LocallyRedundant
).
Process() cancelled due to exception : '$.definitions.BackupResourceConfig.properties.storageModelType.enum' has incompatible values (---
- Invalid
- GeoRedundant
- LocallyRedundant
- ZoneRedundant
- ReadAccessGeoZoneRedundant
, ---
- Invalid
- GeoRedundant
- LocallyRedundant
).
Failure during batch task - {"tag":"package-2017-07"} -- Error: '$.definitions.BackupResourceConfig.properties.storageModelType.enum' has incompatible values (---
- Invalid
- GeoRedundant
- LocallyRedundant
- ZoneRedundant
- ReadAccessGeoZoneRedundant
, ---
- Invalid
- GeoRedundant
- LocallyRedundant
)..
  Error: '$.definitions.BackupResourceConfig.properties.storageModelType.enum' has incompatible values (---
- Invalid
- GeoRedundant
- LocallyRedundant
- ZoneRedundant
- ReadAccessGeoZoneRedundant
, ---
- Invalid
- GeoRedundant
- LocallyRedundant
).

**Comment by pratimaupadhyay02** [comment]
@ArcturusZhang raised this PR to fix the above issue https://github.com/Azure/azure-rest-api-specs/pull/11888

**Pull request merged**
