### PR TITLE
Security Center: update pricings version in dotnet tag

### PR DESCRIPTION
**Pull request by Ihab-Zhaika**

### CODE REVIEW

**Review by GalGoldi72 — APPROVED** [review]

**Comment by sjanamma** [comment]
removing MergeRequested tag, so that, it can go back to ARM reviewers' queue. PR has not been signed off.

**Review by eliagrady — APPROVED** [review]
LGTM

**Comment by Ihab-Zhaika** [comment]
@sjanamma Can you please merge ?

**Pull request merged**
