### PR TITLE
Remove iotsecurity apis from public repo

### PR DESCRIPTION
**Pull request by HassanBadir**
we have no customers that use our APIs, and want to take them off the public repo.

### CODE REVIEW

**Review by JeffreyRichter — APPROVED** [review]

**Review by rkmanda — APPROVED** [review]
:shipit:

**Comment by rkmanda** [comment]
Please post on the TypeSpec channel to fix the Typespec validation

**Comment by mikeharder** [comment]
The failure in check "TypeSpec Validation" is a false positive bug in the tool.  I approve merging this PR despite the failing check.

**Review by visingla-ms — APPROVED** [review]

**Pull request merged**
