### PR TITLE
Fix Automation swagger spec errors in the AutomationAccount and Webhook areas

### PR DESCRIPTION
**Pull request by AnatoliB**
Fixing the following errors in the Automation swagger spec:

- (PatchBodyParametersSchema/R2016/RPCViolation): Properties of a PATCH request body must not be required. PATCH operation: 'AutomationAccount_Update' Model Definition: 'AutomationAccountUpdateParameters' Property: 'properties'
- (PatchBodyParametersSchema/R2016/RPCViolation): Properties of a PATCH request body must not be required. PATCH operation: 'Webhook_Update' Model Definition: 'WebhookUpdateParameters' Property: 'name'
- (XmsResourceInPutResponse/R2062/RPCViolation): The 200 response model for an ARM PUT operation must have x-ms-azure-resource extension set to true in its hierarchy. Operation: 'Webhook_CreateOrUpdate' Model: 'Webhook'

The intent of this PR is to address these errors only. The entire Automation swagger spec contains other errors, and they will be addressed by separate PRs.

---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@AnatoliB are you aware that this may introduce SDK breaking changes for such languages like C#, Java, Go?

**Review by D1v38om83r — APPROVED** [review]

**Comment by AnatoliB** [comment]
@sergey-shandar Currently we (Automation team) are in the process of releasing the Autorest generated client to the public and do not have any external users. Also, our Autorest-SDKs are in preview mode currently to help us fix such issues. Thus, this change should not be a problem.

**Comment by sergey-shandar** [comment]
@AnatoliB Thank you, it's good to know that this is preview. I assume, the file path should be `.../preview/2015-10-31/definitions.json` instead of `.../stable/2015-10-31/definitions.json`.

@marstr Do you know why this is in the `stable` folder?

**Comment by marstr** [comment]
If there are no external customers, moving it into `preview` is the appropriate course of action.

**Comment by vrdmr** [comment]
Hi @marstr/@sergey-shandar

We are in the process of generating a new SDK using Swagger spec (https://github.com/Azure/azure-sdk-for-net/pull/3992), which would be in the preview, where it (SDK) will be promoted out of preview when our PowerShell cmdlets and internal testing tools would be migrated.

But our API for 2015-10-31 is stable (https://github.com/Azure/azure-resource-manager-schemas/tree/master/schemas/2015-10-31) and are public. The changes that @AnatoliB is doing is to fix the linting issues with the spec such that it complies with the service. If there are any service changes, which require a major API change, we would be adding that change in the preview/2017-05-15-preview version itself.

Please let me know if you have any questions or suggestions for fixing the linter issues in the existing spec.

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
@vrdmr thank you for the context. In this case, I would suggest not to introduce the changes in the old API version if they can bring SDK breaking changes. 

1. Making a property optional (removing from `required`) is a breaking change for some programming languages, for example C#.
1. I'm not sure about `"x-ms-azure-resource": true`. It may introduce breaking changes for some programming languages.

Definetly this changes should be in the new API version but it doesn't make much sense to introduce SDK breaking changes for your customers.

Let me know, if there are other reasons (except fixing linter errors/warning) to introduce the changes in the stable API.

**Comment by AnatoliB** [comment]
My understanding from conversations with @vrdmr is that:
1. The web service API is stable and public, and this spec does not introduce any change.
2. The SDK based on this swagger spec has never been officially released yet.

So, any existing web service client will continue working against (1) as it is still communicating with exactly the same service, and it is not even aware of (2). @sergey-shandar, are you talking about someone who could take the published swagger spec and generate his own SDK from the spec? Does this mean that changing the swagger spec at this location effectively means publishing an SDK, and this is how we should treat it for all changes?

**Comment by vrdmr** [comment]
Hey @sergey-shandar,

> Definetly this changes should be in the new API version but it doesn't make much sense to introduce SDK breaking changes for your customers.
Our swagger-based SDK is still in [preview stage](https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/3.0.0-preview) and contains many breaking changes. We released the preview SDK last month and are cleaning up the Specs before we can promote the SDK to a stable version.

Please let me know if you have any other questions.

cc: @marstr, @AnatoliB, @D1v38om83r

**Comment by AnatoliB** [comment]
Hi @sergey-shandar,

We need to close on this soon, as we are trying to fix all the swagger validation errors within the next few days, so I will appreciate your help very much.

Please note that there are multiple other PRs with similar changes coming from our team, and some of them have already been committed.

My previous point was that this may not be a breaking change in our context. But here is another question: **what if we do want to make a breaking change?** Is this not allowed under any circumstances, or there is an authority that could actually make this call? What I observed previously was that a reviewer would just point out a potential breaking change, and then approve the PR after the author acknowledges the issue. So, is this decision up to the Automation team?

**Comment by sergey-shandar** [comment]
Hi @AnatoliB. We assume that if RestAPI is published before as stable then people have freedom to generate stable API for any programming language. Including Microsoft official SDKs, for example for Python, Ruby, JavaScript, Go etc. For example, there's an official Microsoft stable NuGet package  https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/2.0.4 which is using **the same API version 2015-10-03**. So making changes in this swagger file will introduce SDK breaking changes for stable SDK for the same API version. We are trying hard eliminate such breaking changes.

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
Since this API version is used in stable SDKs (NuGet 2.0.4), I would suggest not to make the SDK breaking changes. In particular, making properties optional are SDK breaking changes.

**Comment by sergey-shandar** [comment]
@AnatoliB 

> My previous point was that this may not be a breaking change in our context. But here is another question: what if we do want to make a breaking change?

It's always better to make the SDK and server side breaking changes in a new API version if the current one already publicly available.

>Is this not allowed under any circumstances, or there is an authority that could actually make this call? 

There could be some exception, for example, bugs in API etc.

>What I observed previously was that a reviewer would just point out a potential breaking change, and then approve the PR after the author acknowledges the issue. So, is this decision up to the Automation team?

At the end, it's your service customers who may suffer. We can still approve this but we have to be sure that you understand all consequences. Is there a strong reason why you would like to introduce SDK breaking changes in the same API version?

**Comment by vrdmr** [comment]
The changes done in this PR reflect the Service and we are updating the specification to keep it updated. Also,

> For example, there's an official Microsoft stable NuGet package https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/2.0.4 which is using the same API version 2015-10-03. So making changes in this swagger file will introduce SDK breaking changes for stable SDK for the same API version.

The 2.0.4 API was generated from Hyak from the [last PR ](https://github.com/Azure/azure-sdk-for-net/pull/3424)done in SDK/Master.

**Comment by vrdmr** [comment]
Ping. Can you please take a look at this PR? Thanks.

**Comment by sergey-shandar** [comment]
@vrdmr we need ARM approval for this. @ravbhatnagar could you have a look, it's really simple change.

**Comment by ravbhatnagar** [comment]
Looks good.

**Comment by vrdmr** [comment]
@sergey-shandar Could you please approve and merge this change. Thanks.

**Review by sergey-shandar — APPROVED** [review]

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Pull request merged**
