### PR TITLE
#8187884: Swagger Correctness: MICROSOFT.PORTAL(Azure Portal (IbizaFx))

### PR DESCRIPTION
**Pull request by AKachan0v**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by AKachan0v** [comment]
PR doesn't contain breaking changes since there was no changes on the code side, so it is just fix the definition to the real results  
 (original swagger definition contained some mistakes that doesn't satisfy the real responses):
- 404 doesn't contain body;
- Code in error response has integer (not the string) type;

**Comment by PhoenixHe-msft** [comment]
@JeffreyRichter Please help to review. Thanks.

**Review by JeffreyRichter — COMMENTED** [review]
•	Adding a 404 response may be a breaking change because customer code never expected this before and now it may be showing up
•	Changing the type of an integer (adding "format": "int32",) is breaking. Some client libraries for some languages may have used int64 before and now the client library might use int32. Customer code that used to pass an int64 will now no longer compile. To maintain backward compatibility, you can delete the new "format": "int32", lines and just leave the swagger as it was.

**Comment by AKachan0v** [comment]
> • Adding a 404 response may be a breaking change because customer code never expected this before and now it may be showing up
> • Changing the type of an integer (adding "format": "int32",) is breaking. Some client libraries for some languages may have used int64 before and now the client library might use int32. Customer code that used to pass an int64 will now no longer compile. To maintain backward compatibility, you can delete the new "format": "int32", lines and just leave the swagger as it was.

Hi @JeffreyRichter,

As I mentioned above - there were no changes in the back end code, so if the responses that back end sends to client are not changed too. So if customer code was created depending on original swagger definition - it would just not properly handle this 2 cases and point of the PR is to update the swagger definition to make it equal to the real response.

**Comment by JeffreyRichter** [comment]
Above, you say: "PR doesn't contain breaking changes since there was no changes on the code side". However, this is not Azure's definition of breaking change. Azure has 2 goals: 

1. Existing customer code should not break as the service changes. Since the service isn't changing, you are achieving this goal.
2. Customers should not have to change their code in order to adopt a new service api-version OR a client library. Many swagger changes, DO impact client libraries preventing customers from simply taking a new version of the client library and building/testing against it. Any change to Swagger that breaking client libraries IS a breaking change and adding the format is int32 WILL breaking client libraries.

**Comment by AKachan0v** [comment]
> 2. Customers should not have to change their code in order to adopt a new service api-version OR a client library. Many swagger changes, DO impact client libraries preventing customers from simply taking a new version of the client library and building/testing against it. Any change to Swagger that breaking client libraries IS a breaking change and adding the format is int32 WILL breaking client libraries.

Hey @JeffreyRichter,
I see your point, just want to be sure that the current client library doesn't really comply the current back end responses and we don't hear any complains about it.
So it looks like that there either no users of these APIs (beside the portal) or these users doesn't care about these particular cases (or somehow already handle it manually)...

I see there 3 options for fix:

**1. We consider that these "breaking changes" are not very breaking and pass them in.**

PROS:
- Users get fixed client libraries;
- Future versions of the Swagger definition will depends on the fixed one;
- Our team close the S360 task;

CONS:
- Since there is no update in the version users may not know that they need client library;


**2. We get exception for S360 for the current API versions and introduce new versions of API with these "breaking changes".**

PROS:
- Users get fixed client libraries;
- Future versions of the Swagger definition will depends on the fixed one;
- Our team close the S360 task (though it could be longer due exception process);

CONS:
- Since we introduce new version all users will need to update their code for new version of client libraries even if they didn't care about these cases before;


**3. We update the back end service to satisfy current Swagger definition.**

PROS:
- Our team close the S360 task;

CONS:
- Users, who manually handle the current difference between client libraries and the real response, will have to update code;
- Our APIs start to behave differently (at this moment all of them have similar error responses).

We definitely would like to avoid the p3, so formally choice is going between p1 and p2 (or probably you may have other suggestions).
So what would be your recommendation in this case?

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
