### PR TITLE
GraphRBAC

### PR DESCRIPTION
**Pull request by lmazuel**
Work in progress, creating PR to get automation and CI

### CODE REVIEW

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Review by blasian — APPROVED** [review]
looks good to me

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
