### PR TITLE
[media] Fix "sync_keys" and "regenerate_key"

### PR DESCRIPTION
**Pull request by lmazuel**
- Regenerate_key does not return MediaService:
https://msdn.microsoft.com/en-us/library/azure/mt750386.aspx
- Add "required" to keytype in "sync_keys":
https://msdn.microsoft.com/en-us/library/azure/mt750388.aspx

@amarzavery @BrianBlum for review

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/654)

### CODE REVIEW

**Review by BrianBlum — APPROVED** [review]
Need to also trim the comma after "OK"

**Review by amarzavery — APPROVED** [review]

**Comment by lmazuel** [comment]
@johanste There is no breaking change here:
- "regenerate_keys" does not return anything, Python would have returned an invalid object at best, CloudError at worst
- "keyType" is required, trying to call without it raise a CloudError

**Comment by johanste** [comment]
@lmazuel, switching a property from not required to required *may* be a breaking changes in some languages. We are just spinning up the breaking change review/notification process, and as of now, we are applying the tag if we think that something could be breaking in an SDK. Meaning we do expect false positives at the moment. 

However, we very much appreciate your confirmation that this will not be breaking for the Python SDK :)

**Comment by lmazuel** [comment]
Adding "id" as required for "sync"
https://msdn.microsoft.com/en-us/library/azure/mt750386.aspx

**Comment by lmazuel** [comment]
@amarzavery @johanste @BrianBlum FYI:
- To be precise about impact on the Python SDK, adding "required" changes a CloudError (refused by the RestAPI after the calls) to a "TypeError: missing parameters" (with no RestAPI calls). I don't call this "breaking change", since this doesn't change working code.
- I tested all operations and made a Python PR: https://github.com/Azure/azure-sdk-for-python/pull/855

**Comment by amarzavery** [comment]
@BrianBlum - I think the changes made in this PR are also made in https://github.com/Azure/azure-rest-api-specs/pull/698. Hence, I think it will be safe to close this PR and let the other one get merged with all the changes.

**Pull request closed without merging**
