### PR TITLE
[Hub Generated] [SiteRecovery] Review request for Microsoft.RecoveryServices to add version stable/2021-04-01

### PR DESCRIPTION
**Pull request by imshashwataggarwal**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/imshashwataggarwal/azure-rest-api-specs/dev-recoveryservicessiterecovery-Microsoft.RecoveryServices-2021-04-01...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify: This PR has no other changes than an API version change, done to prevent S360 violations. 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by pilor** [comment]
>   "swagger": "2.0",

this file has become too large to review properly (github won't even show the diff).  In the next PR for this service please split these APIs up into separate swagger specs

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:2 in 5ffc70e. [](commit_id = 5ffc70e31e422e3221922c3ceb46ce717c979fb9, deletion_comment = False)

**Comment by pilor** [comment]
>             "name": "$filter",

an individual GET should not have a $filter.  Did you intend this to be on the collection GET?

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:469 in 5ffc70e. [](commit_id = 5ffc70e31e422e3221922c3ceb46ce717c979fb9, deletion_comment = False)

**Comment by imshashwataggarwal** [comment]
> > ```
> >         "name": "$filter",
> > ```
> 
> an individual GET should not have a $filter. Did you intend this to be on the collection GET?
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:469 in [5ffc70e](https://github.com/Azure/azure-rest-api-specs/commit/5ffc70e31e422e3221922c3ceb46ce717c979fb9). [](commit_id = [5ffc70e](https://github.com/Azure/azure-rest-api-specs/commit/5ffc70e31e422e3221922c3ceb46ce717c979fb9), deletion_comment = False)

These were already present in earlier versions as well. This PR just changes the API version to prevent S360 violation. No other changes with respect to API or model/properties is done.

**Comment by pilor** [comment]
>             "name": "$take",

this should be "$top" ([https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#response-3](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#response-3)).  Applies to all the occurences of "takeToken" as well

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:2527 in 5ffc70e. [](commit_id = 5ffc70e31e422e3221922c3ceb46ce717c979fb9, deletion_comment = False)

**Comment by pilor** [comment]
>         "x-ms-long-running-operation": true,

the VaultSetting resource needs a properties.provisioningState property if it is going to support async PUT.  [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creating-or-updating-resources-asynchronously](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creating-or-updating-resources-asynchronously)

---
Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:7707 in 5ffc70e. [](commit_id = 5ffc70e31e422e3221922c3ceb46ce717c979fb9, deletion_comment = False)

**Comment by imshashwataggarwal** [comment]
> > "swagger": "2.0",
> 
> this file has become too large to review properly (github won't even show the diff). In the next PR for this service please split these APIs up into separate swagger specs
> 
> Refers to: specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-04-01/service.json:2 in [5ffc70e](https://github.com/Azure/azure-rest-api-specs/commit/5ffc70e31e422e3221922c3ceb46ce717c979fb9). [](commit_id = [5ffc70e](https://github.com/Azure/azure-rest-api-specs/commit/5ffc70e31e422e3221922c3ceb46ce717c979fb9), deletion_comment = False)

Ok, we will split the file next time we introduce an API version

**Comment by imshashwataggarwal** [comment]
@ruowan, can you please merge

**Comment by ruowan** [comment]
Hi, This PR has breaking change. Pls go through breaking change review.

**Comment by imshashwataggarwal** [comment]
Hi @ruowan, this PR is adding no change other than API version number change, which is done to overcome S360 violations. 

The breaking changes are shown due to following reason: 

- Another team (Azure Backup) while introducing version 2021-03-01 (to prevent S360 violation), had by mistake had copied it from 2018-07-10 via Hub instead of the latest stable version at that time, i.e., 2021-02-10.

- Note: 2021-03-01 was just a version change (2018-07-10 to 2021-03-01 in this case) done to prevent S360 violations. It didn't have any other changes.

We have already got breaking change team's approval on another PR. This needs to go before that PR to prevent S360 violations.


Breaking change approval: https://msazure.visualstudio.com/One/_workitems/edit/10209988
PR for 2021-06-01 with approval: https://github.com/Azure/azure-rest-api-specs/pull/14794

**Review by ruowan — APPROVED** [review]

**Pull request merged**
