### PR TITLE
Auto merge

### PR DESCRIPTION
**Pull request by csmengwan**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 
### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](../documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).
### Quality of Swagger
- [x] I have read the [contribution guidelines](./CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] Validation errors from the [Linter extension for VS Code](../documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [x] The spec follows the patterns described in the [Swagger good patterns](../documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by amarzavery** [comment]
@csmengwan - There are no files to review. I see that you did a merge commit. Did you manually create the PR or it was a side effect of something.

**Comment by csmengwan** [comment]
I manually created this.

**Comment by amarzavery** [comment]
But there are no files to review. Should I close this?

**Comment by csmengwan** [comment]
I think this is due to branch change (auto rest => master).
Can you merge the pull request so I don't have to clean and checkout the repo again?

**Comment by amarzavery** [comment]
nope. Please sync with upstream master and you should be good.

**Comment by amarzavery** [comment]
Whenever you are working on something, please create a feature branch on your fork, so that you dont end up in this situation.

**Pull request closed without merging**
