### PR TITLE
Microsoft.ApiManagement : Release api-version 2021-04-01-preview

### PR DESCRIPTION
**Pull request by solankisamir**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by VitaliyKurokhtin — APPROVED** [review]

**Comment by solankisamir** [comment]
@chunyu3  can you please approve and merge this PR?

**Comment by chunyu3** [comment]
> @chunyu3 can you please approve and merge this PR?

Hi @solankisamir please fix the CI failure first, and the PR is to release a new API version, it need ARMReview (that is  why there is the label 'WaitForArmFeedback' ).  Only only all those CI failures are resolved and reviewed by ARM, the PR can be merged.

**Review by RamyasreeChakka — APPROVED** [review]
:shipit:

**Comment by solankisamir** [comment]
@ArcturusZhang we are hitting the same issue with Linter as we hit in https://github.com/Azure/azure-rest-api-specs/pull/15115
which you had merged. 

Can you please help unblock this PR too? A lot of downstream activities are blocked because of this.

**Comment by ArcturusZhang** [comment]
I made some investigation (which is complicated to find), and I found the root cause.
The reason that we have this error is that modeler of autorest will try to merge models with the same name that are referenced in your swaggers. The error message says you have two schemas with the name `Resource` but with different description, therefore autorest cannot merge them and throw this error.
We have a definition of schema with the name `Resource` here: https://github.com/Azure/azure-rest-api-specs/blob/3ea06ac10a073222cc66faa383eb2298181f39be/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2021-04-01-preview/apimanagement.json#L124
The other definition of the schema `Resource` is actually defined here: https://github.com/Azure/azure-rest-api-specs/blob/3ea06ac10a073222cc66faa383eb2298181f39be/specification/common-types/resource-management/v2/types.json#L9
This `Resource` in common-types is also referenced in your swagger, because you reference the `PrivateLinkResource` from common-types here: https://github.com/Azure/azure-rest-api-specs/blob/3ea06ac10a073222cc66faa383eb2298181f39be/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2021-04-01-preview/apimprivatelink.json#L320, and `PrivateLinkResource` is defined in common-types and it also references the `Resource` in common-types.
Above is the reason why this happens and how this happens.
To solve this linter issue, please remove the definition of `Resource` [here](https://github.com/Azure/azure-rest-api-specs/blob/3ea06ac10a073222cc66faa383eb2298181f39be/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2021-04-01-preview/apimanagement.json#L124) and use the `Resource` definition from common-types in where previously references your own `Resource`.

**Comment by solankisamir** [comment]
@chunyu3 the linter issue is gone now. Can you please review this again and help merge it?
Thanks @RupengLiu

**Comment by solankisamir** [comment]
@VitaliyKurokhtin we would need signoff from Breaking change reviewers for deprecating the `samples` property from `RepresentationContract`, which got removed as part of PR - https://github.com/Azure/azure-rest-api-specs/pull/14836

See run https://github.com/Azure/azure-rest-api-specs/pull/15832/checks?check_run_id=3594297851

According to @chunyu3 that is blocking merging this PR

**Comment by solankisamir** [comment]
@chunyu3 we already got the exception as part of the PR - https://github.com/Azure/azure-rest-api-specs/pull/15377

Do we need to request a new one?

**Comment by VitaliyKurokhtin** [comment]
Same question to @JeffreyRichter. We've already been through breaking change of replacing "sample" property with examples here #15377. This is the next version of our API should we got through breaking change process again?

**Comment by JeffreyRichter** [comment]
When I look here: https://github.com/Azure/azure-rest-api-specs/pull/15832/checks?check_run_id=3594297851
I see lots of breaking changes. What is the justification for these breaks?

**Comment by solankisamir** [comment]
@JeffreyRichter I can only see 1 breaking change

image

**Comment by JeffreyRichter** [comment]
Technically, the type changes are also breaking but we tend to allow changes from nothing to object.

But removing a property is breaking.

**Comment by VitaliyKurokhtin** [comment]
Here is timeline:
- In 2020-12-01 we have property "sample".
- in 2021-01-01-preview it was removed by #15377 (breaking change)
- In this 2021-04-01-preview automation compares it to previous stable (2020-12-01) and sees same breaking change from second point.

How should we handle multiple consecutive -preview versions where each has same breaking change?

**Comment by JeffreyRichter** [comment]
OK, I approved the PR. I dont' think there is a way to stop getting flagged with breaking changes until this comes out of preview.

**Comment by chunyu3** [comment]
Contact with @zhenglaizhang , we can ignore 'swagger ApiDocPreview' failure since apimanagement can re configure operation group in their prod rest doc generation.

**Pull request merged**
