### PR TITLE
Add commontypes/resource-management/v3/managedidentity

### PR DESCRIPTION
**Pull request by TimLovellSmith**
This has models for managed identity as it should be in the PUT request / GET responses for services supporting both SystemAssignedIdentity and UserAssignedIdentity.

Reviewers! You can check validation tools run OK on a PR that actually references these definitions, here:
https://github.com/Azure/azure-rest-api-specs/pull/15828

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. N/A
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. N/A
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by pilor — APPROVED** [review]

**Comment by TimLovellSmith** [comment]
@akning-ms Look OK to merge?

**Comment by akning-ms** [comment]
Thanks @TimLovellSmith, for contribute this PR.  few questions:
1.  should we leave previous identify as it in v3:
     https://github.com/Azure/azure-rest-api-specs/blob/33435f865c597af5cfc6bc7a6ade8b81c9e1002a/specification/common-types/resource-management/v3/types.json#L233
     or at least add None?
2.  Notice there is some service only support SystemAssigned. not UserAssigned, can they still use common type?

**Comment by TimLovellSmith** [comment]
@akning-ms We can't really add `None` to the previous `identity` definition because it has the enumeration `"modelAsString": false` and so it is a breaking change. :-(

Services that only support SystemAssigned *could* use the common type that understands both identity types. But, if they choose to do this then the RP MUST explicitly reject all PUT and PATCH requests with userAssignedIdentity _while it is unsupported_. The main reason RPs might prefer doing it this way would be to design for compatibility with _future_ api-versions, where they plan to support both systemAssigned or userAssigned identity. (Same deal for services which only support UserAssigned today but might support SystemAssinged in the future.)

Of course, I hope that all services that support SystemAssigned or UserAssigned could use the new common type definitions in their future api-versions.

The best alternatives to using the new common type are 
* keep doing whatever you already have in your last api-version, to minimize churn, this would be a sensible option for services that don't support both identity types, and e.g. only support userAssignedIdentity, or support systemAssignedIdentity but also the enumeration value 'None'.
* use the existing "identity" type in "v3/types.json". System assigned identity can be removed using their REST API by sending PUT requests that delete the whole `identity` property, if that scenario is required.

By the way does everyone like the definition names here? I have started to worry that I might not have put enough thought into this ones:
"ManagedServiceIdentity"
"ManagedServiceIdentityType"

/cc @pilor

**Comment by TimLovellSmith** [comment]
Updated answer: given the authoring rule

'An OpenAPI(Swagger) spec MUST NOT define operations or properties or parameters for functionalities that are not currently supported by the service in the given api-version. The primary goal of the spec is that it MUST correctly and completely represent the underlying REST API. For example, NetworkInterface.ipConfigurations is described as a collection. However, it does not support adding more than one IP configuration'

then any service not actually supporting both should NOT use the type which appears to support both for now.

**Comment by TimLovellSmith** [comment]
Looks like the latest requirement for SystemAssignedIdentity is that all MSI-enabled RPs must support identity type "None".

This seems like a good reason to me for us to create an updated `identity` type definition, and give it a different name (SystemAssignedServiceIdentity and an enum SystemAssignedServiceIdentityType?), or a new version of 'identity' (v4).

**Comment by TimLovellSmith** [comment]
@pilor Could I get a sanity check on the new changes too? 
@akning-ms Do my answers above look OK? Anything else we should consider to make the APIs better going forward?

**Comment by akning-ms** [comment]
> @pilor Chris Eggert FTE Could I get a sanity check on the new changes too?
> @akning-ms Arthur Ning FTE Do my answers above look OK? Anything else we should consider to make the APIs better going forward?

Yes. saw you already added SystemAssignedServiceIdentityType, so the PR LGTM. if Chris confirmed your question. I can merge it.
BTW, v3 is just created recently. roughly check. there is only RP is using v3

**Comment by pilor** [comment]
Yes, looks good

**Comment by TimLovellSmith** [comment]
@akning-ms Looks like we are ready to merge. Yes v3 is pretty new.

I imagine that we can get to a more consistent user-friendly SDK fast enough by encouraging as many RPs as possible to use the latest (now v3) common types in their current and future PRs for new api-versions...

I'd say its initially OK to accept exception requests for concerns about churn or compatibility - but then to gradually be less permissive, as we become are more confident that the definitions are good, and enough time has been allowed to address other issues or consolidate changes to minimize perception of churn.

**Comment by TimLovellSmith** [comment]
@akning-ms Thanks for the feedback and merge!

**Comment by TimLovellSmith** [comment]
@pilor Thanks for the review!

**Pull request merged**
