### PR TITLE
changing host to management.azure.com aligning with other specs

### PR DESCRIPTION
**Pull request by bganapa**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by allenjzhang** [comment]
Model validation failed. Please review error log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=241818&view=logs&j=d2a54e27-891b-5b91-4b1b-0c6d3d820755&t=4db5f656-3b59-5661-54ad-d4645c211b0f&l=462

**Review by allenjzhang — APPROVED** [review]

**Comment by bganapa** [comment]
There are still few errors, I will look at them tomorrow

**Comment by allenjzhang** [comment]
Please correct following errors:

Invalid JSON:
[https://dev.azure.com/azure-sdk/public/_build/results?buildId=245617&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=442](url)
[https://dev.azure.com/azure-sdk/public/_build/results?buildId=245617&view=logs&j=f10f5372-40ed-54fc-caa4-b1cb5bd1252b&t=d3b2b841-a93b-5fa5-47c3-d8c4f6eae6e3&l=32](url)

Model validation error:
[https://dev.azure.com/azure-sdk/public/_build/results?buildId=245617&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=442](url)

Run prettier-fix tool to fix formatting issues:
[https://aka.ms/AA6h31t ](url)

**Review by rakku-ms — APPROVED** [review]
looks good to me

**Pull request merged**
