### PR TITLE
[Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-10-01

### PR DESCRIPTION
**Pull request by zachraMSFT**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/zachraMSFT/azure-rest-api-specs/dev-consumption-Microsoft.Consumption-2019-10-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by zachraMSFT** [comment]
@tjprescott Can you help get this completed? Would like to finish this month if possible so we can close our work items.

**Comment by tjprescott** [comment]
@zachraMSFT our SDK team only reviews data plane Swagger. For management plane SDKs, you want to reach out to @yungezz

**Review by ravbhatnagar — APPROVED** [review]
Signed off from ARM side.

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
Pending the investigation of SDK generation error.

**Pull request merged**
