### PR TITLE
Added support for dropped databases on Managed Instance

### PR DESCRIPTION
**Pull request by v-djnisi**
### Latest improvements:
<i>Adding dropped database, as well as short term retention for dropped databases to readme.me. API for both of these is in prod for quite some time. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by v-djnisi** [comment]
Here are scenario tests: `https://github.com/Azure/azure-sdk-for-net/pull/5107`

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
This change introduces a new ARM violation, see the task result [here](https://github.com/Azure/azure-rest-api-specs/pull/4953/checks?check_run_id=43183371).  This either needs to be fixed or ARM team to provide an approval for suppression.

**Comment by KrisBash** [comment]
@v-djnisi The arm validation error concerns the lack of a PATCH api on the restorableDroppedDatabases. A PATCH API is required on all tracked resources, which is why this resource has been flagged. Note, the linting runs on all files in the commit, not just the changed files - which is why this is being flagged on an existing file. I notice that there is no PUT api for this resource type. Can the user not create/update this resource? If that is the case, I think it would make sense to request a suppression for this validation error. Is this something you can comment on?

**Comment by v-djnisi** [comment]
Correct, this resource can't be created or updated. Once database is dropped it transitions to dropped databases, and it's only purpose is to provide data and backups so that we can restore it afterwards if necessary.

**Review by KrisBash — APPROVED** [review]
Signing off from ARM. For this specific case, a suppression should be requested given the nature of the resource

**Comment by v-djnisi** [comment]
Anything required from me, regarding the suppression?

**Comment by jhendrixMSFT** [comment]
@v-djnisi yes please send an email to `armpm` and `adxsr` with a request for the suppression along with an explanation.

**Comment by v-djnisi** [comment]
Added suppression.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
