### PR TITLE
fix: vmwarecloudsimple missing body in examples

### PR DESCRIPTION
**Pull request by nschonni**
Previously wasn't flagged by oav.
It also uncovered other issues

### CODE REVIEW

**Comment by nschonni** [comment]
Right now, with OAV 0.19 the following errors are flagged when the "body" is added back
```
$ oav validate-example specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimpl 
e.json -p
Validating "examples" and "x-ms-examples" in  specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json:

 error : 
operationId: dedicatedCloudNode_ListBySubscription
scenario: ListDedicatedCloudNodes
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - nodesCount
  message: 'Missing required property: nodesCount'
  path: value/0/properties/nodesCount
  title: '#/definitions/DedicatedCloudNodeProperties'
  description: Properties of dedicated cloud node
  position:
    line: 2222
    column: 37
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListDedicatedCloudNodes.json
  jsonPath: '$.value[0].properties.nodesCount'
  similarPaths:
    - value/1/properties/nodesCount
  similarJsonPaths:
    - '$.value[1].properties.nodesCount'

 error : 
operationId: skusAvailabilityWithinRegion_List
scenario: ListAvailabilities
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - unit
  message: 'Additional properties not allowed: unit'
  path: value/0/unit
  title: '#/definitions/SkuAvailability'
  description: SKU availability model
  position:
    line: 2713
    column: 24
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListAvailabilities.json    
  jsonPath: '$.value[0].unit'
  similarPaths:
    - value/1/unit
  similarJsonPaths:
    - '$.value[1].unit'

 error : 
operationId: skusAvailabilityWithinRegion_List
scenario: ListAvailabilities
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - name
  message: 'Additional properties not allowed: name'
  path: value/0/name
  title: '#/definitions/SkuAvailability'
  description: SKU availability model
  position:
    line: 2713
    column: 24
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListAvailabilities.json    
  jsonPath: '$.value[0].name'
  similarPaths:
    - value/1/name
  similarJsonPaths:
    - '$.value[1].name'

 error : 
operationId: skusAvailabilityWithinRegion_List
scenario: ListAvailabilities
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - currentValue
  message: 'Additional properties not allowed: currentValue'
  path: value/0/currentValue
  title: '#/definitions/SkuAvailability'
  description: SKU availability model
  position:
    line: 2713
    column: 24
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListAvailabilities.json    
  jsonPath: '$.value[0].currentValue'
  similarPaths:
    - value/1/currentValue
  similarJsonPaths:
    - '$.value[1].currentValue'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - skuName
  message: 'Additional properties not allowed: skuName'
  path: value/0/skuName
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].skuName'
  similarPaths:
    - value/1/skuName
  similarJsonPaths:
    - '$.value[1].skuName'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - skuId
  message: 'Additional properties not allowed: skuId'
  path: value/0/skuId
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].skuId'
  similarPaths:
    - value/1/skuId
  similarJsonPaths:
    - '$.value[1].skuId'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - resourceType
  message: 'Additional properties not allowed: resourceType'
  path: value/0/resourceType
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].resourceType'
  similarPaths:
    - value/1/resourceType
  similarJsonPaths:
    - '$.value[1].resourceType'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - dedicatedPlacementGroupName
  message: 'Additional properties not allowed: dedicatedPlacementGroupName'
  path: value/0/dedicatedPlacementGroupName
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].dedicatedPlacementGroupName'
  similarPaths:
    - value/1/dedicatedPlacementGroupName
  similarJsonPaths:
    - '$.value[1].dedicatedPlacementGroupName'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - dedicatedPlacementGroupId
  message: 'Additional properties not allowed: dedicatedPlacementGroupId'
  path: value/0/dedicatedPlacementGroupId
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].dedicatedPlacementGroupId'
  similarPaths:
    - value/1/dedicatedPlacementGroupId
  similarJsonPaths:
    - '$.value[1].dedicatedPlacementGroupId'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - dedicatedAvailabilityZoneName
  message: 'Additional properties not allowed: dedicatedAvailabilityZoneName'
  path: value/0/dedicatedAvailabilityZoneName
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].dedicatedAvailabilityZoneName'
  similarPaths:
    - value/1/dedicatedAvailabilityZoneName
  similarJsonPaths:
    - '$.value[1].dedicatedAvailabilityZoneName'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_ADDITIONAL_PROPERTIES
details:
  code: OBJECT_ADDITIONAL_PROPERTIES
  params:
    - dedicatedAvailabilityZoneId
  message: 'Additional properties not allowed: dedicatedAvailabilityZoneId'
  path: value/0/dedicatedAvailabilityZoneId
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].dedicatedAvailabilityZoneId'
  similarPaths:
    - value/1/dedicatedAvailabilityZoneId
  similarJsonPaths:
    - '$.value[1].dedicatedAvailabilityZoneId'

 error : 
operationId: UsagesWithinRegion_List
scenario: ListUsages
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - currentValue
  message: 'Missing required property: currentValue'
  path: value/0/currentValue
  title: '#/definitions/Usage'
  description: Usage model
  position:
    line: 2792
    column: 14
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListUsages.json
  jsonPath: '$.value[0].currentValue'
  similarPaths:
    - value/1/currentValue
  similarJsonPaths:
    - '$.value[1].currentValue'

 error : 
operationId: dedicatedCloudNode_ListByResourceGroup
scenario: ListRGDedicatedCloudNodes
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - nodesCount
  message: 'Missing required property: nodesCount'
  path: value/0/properties/nodesCount
  title: '#/definitions/DedicatedCloudNodeProperties'
  description: Properties of dedicated cloud node
  position:
    line: 2222
    column: 37
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/ListRGDedicatedCloudNodes.json
  jsonPath: '$.value[0].properties.nodesCount'
  similarPaths:
    - value/1/properties/nodesCount
    - value/2/properties/nodesCount
  similarJsonPaths:
    - '$.value[1].properties.nodesCount'
    - '$.value[2].properties.nodesCount'

 error : 
operationId: dedicatedCloudNode_Get
scenario: GetDedicatedCloudNode
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - nodesCount
  message: 'Missing required property: nodesCount'
  path: properties/nodesCount
  title: '#/definitions/DedicatedCloudNodeProperties'
  description: Properties of dedicated cloud node
  position:
    line: 2222
    column: 37
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonPosition:
    line: 14
    column: 23
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/GetDedicatedCloudNode.json 
  jsonPath: $.properties.nodesCount

 error : 
operationId: dedicatedCloudNode_CreateOrUpdate
scenario: CreateDedicatedCloudNode
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - nodesCount
  message: 'Missing required property: nodesCount'
  path: properties/nodesCount
  title: '#/definitions/DedicatedCloudNodeProperties'
  description: Properties of dedicated cloud node
  position:
    line: 2222
    column: 37
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonPosition:
    line: 31
    column: 23
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/CreateDedicatedCloudNode.json
  jsonPath: $.properties.nodesCount

 error : 
operationId: dedicatedCloudNode_Update
scenario: PatchDedicatedCloudNode
source: response
responseCode: '200'
severity: 0
code: OBJECT_MISSING_REQUIRED_PROPERTY
details:
  code: OBJECT_MISSING_REQUIRED_PROPERTY
  params:
    - nodesCount
  message: 'Missing required property: nodesCount'
  path: properties/nodesCount
  title: '#/definitions/DedicatedCloudNodeProperties'
  description: Properties of dedicated cloud node
  position:
    line: 2222
    column: 37
  url: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/vmwarecloudsimple.json
  directives: {}
  jsonPosition:
    line: 20
    column: 23
  jsonUrl: >-
    specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/PatchDedicatedCloudNode.json
  jsonPath: $.properties.nodesCount
```
/cc @tenmozes if you want to take this over

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
@nschonni OAV in CI passed. Do you run it offline?

**Comment by nschonni** [comment]
Yeah, and CI doesn't currently test when only the example file is touched and not the spec

**Comment by yungezz** [comment]
> Yeah, and CI doesn't currently test when only the example file is touched and not the spec

thank you for clarification. will track the issue.

**Comment by yungezz** [comment]
> > Yeah, and CI doesn't currently test when only the example file is touched and not the spec
> 
> thank you for clarification. will track the issue.

once concern on this change is that, if those OAV error not fixed before azure team updating vmware swagger files next time, they will confused why nothing changed in samples but CI failed. Will you help to fix those OAV error too?

**Comment by nschonni** [comment]
OAV will be failing the next time they touch this either way. I can't fix the remaining errors because I'd need to know about the service to do that

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
