### PR TITLE
adding package 2019-06 to python multipackage build

### PR DESCRIPTION
**Pull request by zikalino**

### CODE REVIEW

**Comment by NullMDR** [comment]
@openapibot regenerate

**Comment by NullMDR** [comment]
@openapibot sdkautomation regenerate

**Comment by NullMDR** [comment]
@openapibot sdkautomation rebuild

**Comment by yungezz** [comment]
hi @zikalino  before we adding this tag into package, could you pls confirm with service team to understand context and let them aware of the change? thanks.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
