### PR TITLE
Azure VM Image Builder: Adding support for Customer Managed Key

### PR DESCRIPTION
**Pull request by sumit-kalra**
Azure VM Image Builder: Adding support for Customer Managed Key for encryption at rest

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### API Change Reasoning
The change introduces optional 'Customer Managed Key' fields to the resource. This key will be used for performing second level of encryption using a key that resides completely with the customer. This is required to meet various compliance requirements.

### Breaking Change Explanation
In this PR, the Azure VM Image Builder RP has added optional 'customer managed key' field to the request and response, which is a breaking change by definition.  
However, this change is not considered breaking for the service due to the fact that the service does not support GET-PUT semantics. In other words, the service does NOT allow a PUT on a pre-existing resource. The only way to make major changes to the resource is to submit a completely new resource to the service.  Also, the service supports very limited PATCH semantics that would not end up overwriting the 'customer managed key' fields due to SDK mismatch. Due to this, the addition of this field will not cause existing customer image templates to fail to be created (PUT) or fail to be run (POST).  
Further, the Azure VM Image Builder RP service is still in preview.

### CODE REVIEW

**Comment by sumit-kalra** [comment]
Hi @ruowan  
Regarding the breaking change; I have included an explanation in the original/first comment. Can you please take a look and let me know if there are any more questions?  
Thanks!

**Comment by ruowan** [comment]
Good. LGTM.

**Review by ruowan — APPROVED** [review]

**Comment by ruowan** [comment]
some reasons from breakingChange review board

Adding an optional return property is not allowed without an api-version change for many reasons:
        1. Some programming language deserializers throw if a new property comes across the wire that the client library has no field for it in the structure/class that you’re trying to deserialize into.
	 2. Some customer use schema validation tools to validate the data being sent across the wire complies with the schema. If the services sends data that doesn’t match the old schema, then the client’s validation fails.
	 3. If the service sends a new property to an old client, the old client discards the property and the client cannot send the new property back to the service later. Depending on the operation and the meaning of this property, this results in data loss/corruption.
         4. A customer can’t look at a service version and know if they can expect the new property or not. For example, if a customer hits V1 of a service in the public cloud, the property may be there but if they hit V1 of the service in a government cloud or on an Azure Stack Hub system, then the property may not be there. So, there is no clear relationship between the service version and the new property which makes documentation invalid and also makes it hard for customers and Azure customer support to help customers diagnose issues.

**Comment by sumit-kalra** [comment]
Since this breaking change can impact SDK users; we have decided to not proceed with it.
Hence abandoning this PR.

**Pull request closed without merging**
