### PR TITLE
[ASR][V2A-RCM] Add new properties and provider specific models for V2A RCM.

### PR DESCRIPTION
**Pull request by imshashwataggarwal**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by imshashwataggarwal** [comment]
This PR adds V2A-RCM specific request-response models and new optional properties. Since, all the examples have HyperV provider details, so adding these properties/models to examples is not required.

**Review by ChenTanyi — APPROVED** [review]

**Comment by ChenTanyi** [comment]
@imshashwataggarwal Please also add code owner for review.

**Comment by imshashwataggarwal** [comment]
Adding @DevBaburaj, @anmolbhatia289

**Comment by ChenTanyi** [comment]
@NullMDR Could you take a look at the JS automation?

**Comment by NullMDR** [comment]
@qiaozha Could you please help on this generation failure:

[npmPack] src/models/mappers.ts(17143,3): error TS2300: Duplicate identifier ''ProviderSpecificFailoverInput.InMageRcm''.

**Comment by imshashwataggarwal** [comment]
@NullMDR Can you please merge this pr, given JS automation isn't a required check?

**Comment by ChenTanyi** [comment]
@imshashwataggarwal Could you ask the two people you mentioned to review first?

**Comment by anmolbhatia289** [comment]
Hey @ChenTanyi , internal review within the team is already done.

**Comment by qiaozha** [comment]
@NullMDR  @imshashwataggarwal  The JS SDK generation failure is because the swagger have two different subclasses `InMageRcmTestFailoverInput`, `InMageRcmUnplannedFailoverInput` of `ProviderSpecificFailoverInput` but with the same x-ms-discriminator-value `InMageRcm`. I don't think that's allowed.

**Comment by NullMDR** [comment]
@jianyexi to add a new lint rule that don't allow same discriminator value

**Comment by NullMDR** [comment]
@imshashwataggarwal Please fix the same discrinimator value problem

**Comment by imshashwataggarwal** [comment]
@NullMDR We have separate classes for these subclasses: `InMageRcmTestFailoverInput`, `InMageRcmUnplannedFailoverInput` instead of a common class `ProviderSpecificFailoverInput` in rhe service code. However, if we add them to current swagger version, it will lead us to change it for all providers and that will be a breaking change (rename of properties). 

We plan to add that in the next api version. As for now, since JS automation is an optional check, so can you please approve this PR?

**Comment by ChenTanyi** [comment]
@NullMDR Is it OK to merge? Or is it a serious problem in this change?

**Comment by qiaozha** [comment]
> @NullMDR We have separate classes for these subclasses: `InMageRcmTestFailoverInput`, `InMageRcmUnplannedFailoverInput` instead of a common class `ProviderSpecificFailoverInput` in rhe service code. However, if we add them to current swagger version, it will lead us to change it for all providers and that will be a breaking change (rename of properties).
> 
> We plan to add that in the next api version. As for now, since JS automation is an optional check, so can you please approve this PR?

@imshashwataggarwal I am confused, this swagger change is added by you only in this PR which shouldn't have been generated in the SDK, why would it cause other api-version's breaking change?

**Comment by qiaozha** [comment]
Juat confirmed with other languages SDK owners, This the same discriminator value of different subclasses sharing the same parent class should also report error. Therefore, I don't think we should merge it. @NullMDR

**Comment by imshashwataggarwal** [comment]
@NullMDR can you please review now. I have fix the same discriminator value issue.

**Comment by ChenTanyi** [comment]
SDK Net generation is successful, just authentication fail.
@imshashwataggarwal It is OK to merge since all CI pass. Please let me know when you want to merge.

image

**Comment by imshashwataggarwal** [comment]
@ChenTanyi Please merge.

**Pull request merged**
