### PR TITLE
Update fabricbot.json

### PR DESCRIPTION
**Pull request by ruowan**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by weshaggard** [comment]
@ruowan there will need to be a few more updates to this once @mikekistler see, https://github.com/Azure/azure-rest-api-specs/pulls/mikekistler

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Pull request merged**
