### PR TITLE
chore: Move Spellcheck to regular pipeline

### PR DESCRIPTION
**Pull request by nschonni**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by Juliehzl** [comment]
@NullMDR  I think you should take a look at the pipeline file to check the logic change.

**Comment by NullMDR** [comment]
@yungezz How do you think about this change?

**Comment by yungezz** [comment]
`spellcheck` is not ready to be moved to prod pipeline, before setting up proper configuration. there're lots of known failure, such as https://dev.azure.com/azure-sdk/public/_build/results?buildId=100800&view=logs&j=eca5a1cb-f12a-57d8-9254-390bd587c201&t=be275096-42fe-5449-ec4b-01c6f327d2b3&l=19.  it will be too verbose to filter out  words like 'opencontainer'.

**Comment by yungezz** [comment]
hi @nschonni , thanks for the contributions. as mentioned above, suggest to close the PR. let us know if any comments.

**Comment by nschonni** [comment]
@yungezz those are examples where the words just need to be added to the dictionary. Most new APIs don't run into that issue anymore since the dictionary has been built up. Words like "opencontainer" also aren't flagged when they are camelCase
This PR is failing because another PR was landed with a spellcheck failure of "TSVE" was landed in #7100

**Comment by nschonni** [comment]
One thing I think I haven't done well with the setup is the instructions. Does adding something in here make sense https://github.com/Azure/azure-rest-api-specs/tree/master/documentation or do your authors mostly look at your internal sharepoint docs?

**Comment by NullMDR** [comment]
@yungezz I agree with @nschonni . Since the dictionary is already built up, maintaining this task and make it mandatory is not a big effort. Currently SpellCheck failed because some recent PR breaks the check. We can ask the service team to fix it. I suggest to make SpellCheck required for PR because it could improve the swagger spec's quality and avoid bug caused by spelling. We can add some documentation for this SpellCheck. And IMO we can merge this PR and mark it mandatory after the service team fix the error.

Another concern for @nschonni : currently we don't use the latest version of spellcheck. Maybe we can test the new version of spellcheck in pre production pipeline afterwards?

**Comment by nschonni** [comment]
Think https://github.com/Azure/azure-rest-api-specs/pull/7132 just needs to land to get it green again.


> currently we don't use the latest version of spellchec

The package.json isn't the latest, but it is the latest in the lock file

**Comment by NullMDR** [comment]
I suggest to watch the new pipeline for one more week to make sure it's stable, then we can merge this PR.

**Review by PhoenixHe-NV — APPROVED** [review]

**Pull request merged**
