### PR TITLE
Updated NIC DNS settings with readonly flags

### LINKED ISSUE #1278: [Network] Issues with NetworkInterface DNS Settings
The help text for dnsServers says: "Use 'AzureProvidedDNS' to switch to azure provided DNS resolution."

However, when I actually do that, I get an error that says:
`DnsServer value AzureProvidedDNS specified for network interface nic1 is not a valid IPAddress.`

Supplying a null value results in an error as well. I have to supply an empty list to get the desired behavior. 

Also, it seems that internalDomainNameSuffix is a read-only property but not marked as such in Swagger. As a result it appears settable in the SDKs but the service ignores the value.  internalFqdn and appliedDnsServers might also be read-only, though I didn't try them.

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
Waiting for @DeepakRajendranMsft to confirm other changes (https://github.com/Azure/azure-rest-api-specs/issues/1278#issuecomment-323290993)

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by balajikris** [comment]
LGTM so far, I'll look again if you push another commit. If you are done and want me to merge, let me know.

**Comment by balajikris** [comment]
I assume SDKs based on this version have not shipped? Otherwise, this'd be a breaking change.

**Comment by salameer** [comment]
Hi Balaji, They've  released a .Net SDKbuttI'm assuming that @DeepakRajendranMsft will betaking careof regenerating and versioning appropriately. This is a new API version

**Comment by balajikris** [comment]
Got it -- thanks.

**Review by balajikris — APPROVED** [review]

**Comment by salameer** [comment]
@EvgenyAgafonchikov  and @DeepakRajendranMsft, what's the plan here?

**Comment by balajikris** [comment]
ping @EvgenyAgafonchikov -- What's the status here, Is this good to merge?

**Comment by EvgenyAgafonchikov** [comment]
Waiting for @DeepakRajendranMsft answer in related issue thread: https://github.com/Azure/azure-rest-api-specs/issues/1278.
As alternative way we could merge these changes for now and send separate PR if required for other workitems. I've dropped issue reference in the PR comment to keep related issue open in case of merging.

**Comment by veronicagg** [comment]
@EvgenyAgafonchikov are there any updates? plans on this PR?

**Comment by EvgenyAgafonchikov** [comment]
@veronicagg I've checked `internalDomainNameSuffix` property and the resulting value in the created resource doesn't depend on the value sent from client. So I've added readOnly there.

However the description seems to be confusing in this case: [link](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/networkInterface.json#L609). This phrase
> Even if internalDnsNameLabel is not specified

makes you to think that you could specify this value. Also, I created NIC that is not connected to any VM and it has some generated value for this property: `0nby3ez5uftulfs3fd4qr0wolf.d--x.internal.cloudapp.net` that seems to be different from what description says

Who is appropriate person to ask if this description up to date and what it should be now, if not?

**Comment by veronicagg** [comment]
@EvgenyAgafonchikov the best option would be a PM from your team that understands the service well, do you know who that person may be?

**Comment by salameer** [comment]
@Evgeny Ping :)

We will close this PR if there's no response over the next couple of days :)

adding @DeepakRajendranMsft  for FYI

**Comment by salameer** [comment]
Closing as recommended by @DeepakRajendranMsft

**Pull request closed without merging**
