### PR TITLE
Add missing properties for api version 2020-02-02-preview of securityAlertPolicies

### PR DESCRIPTION
**Pull request by ayeletshpigelman**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [x] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ericshape** [comment]
please fix the validation errors triggered by your example files in the DSMainDev repo firstly. Then you can update in this github PR.

**Comment by akning-ms** [comment]
and also let me know why add new properties in a existing version. it is required a new API version if it is adding a new feature,

**Comment by ayeletshpigelman** [comment]
@ericshape - I fixed the errors in DsmMainDev
@akning-ms - I am doing this change becuase of many CRIs we got for this API version. These properties don't apply a new behavior. They exist in the previous versions of these APIs (2017-03-01-preview for servers and managed instances and 2018-06-01-preview for databases). We tried to remove these settings, but got a lot of CRIs of customers complaining on this change, therefore we want to return the properties that exist in the previous versions. Moreover, this API was published less than one year ago, and since it is a preview version we can add these properites. please approve this change

**Comment by akning-ms** [comment]
> @ericshape - I fixed the errors in DsmMainDev
> @akning-ms - I am doing this change becuase of many CRIs we got for this API version. These properties don't apply a new behavior. They exist in the previous versions of these APIs (2017-03-01-preview for servers and managed instances and 2018-06-01-preview for databases). We tried to remove these settings, but got a lot of CRIs of customers complaining on this change, therefore we want to return the properties that exist in the previous versions. Moreover, this API was published less than one year ago, and since it is a preview version we can add these properites. please approve this change

Thanks, few more questions, Can I know  the PR#  which removed these properties?  and CRIs of customer complaining is from SDK?  BTW, you may need to remove the package-lock.json in this PR.

**Comment by ericshape** [comment]
> > @ericshape - I fixed the errors in DsmMainDev
> > @akning-ms - I am doing this change becuase of many CRIs we got for this API version. These properties don't apply a new behavior. They exist in the previous versions of these APIs (2017-03-01-preview for servers and managed instances and 2018-06-01-preview for databases). We tried to remove these settings, but got a lot of CRIs of customers complaining on this change, therefore we want to return the properties that exist in the previous versions. Moreover, this API was published less than one year ago, and since it is a preview version we can add these properites. please approve this change
> 
> Thanks, few more questions, Can I know the PR# which removed these properties? and CRIs of customer complaining is from SDK? BTW, you may need to remove the package-lock.json in this PR.

@ayeletshpigelman I have replied to the comments in your DSMain PR and tag @akning-ms in the comment as well.

**Comment by ayeletshpigelman** [comment]
@ericshape - I added the changes to version 2020-11-01-preview and version 2020-08-01-preview as well
@akning-ms - The pr of removing these settings in the new version is: https://github.com/Azure/azure-rest-api-specs/pull/9565
CRIS for example: https://portal.microsofticm.com/imp/v3/incidents/details/217576651/home
I also sent you over email 2 other examples

**Comment by ericshape** [comment]
LGTM
1. the breaking changes are expected. it seems because @ayeletshpigelman would like to add these features to V5 SDK. The version of v5 SDK I will merge is based on 2020-08-01 preview. 
2. lintDiff throws an exception. I think it is fine in that the exception is systemData. cc: @akning-ms 
3. .NET sdk test is failed due to @xaliciayang has not updated the test in .NET repo. It is expected.

**Comment by akning-ms** [comment]
@jianyexi to check why there is exception for Linter, this error can not be skipped, as it stops the linter validation

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE to check why there is exception for Linter, this error can not be skipped, as it stops the linter validation

The  `systemData` is referenced by https://github.com/Azure/azure-rest-api-specs/blob/26a8083f016be439122fe390dacd27a5b7ef2649/specification/sql/resource-manager/Microsoft.Sql/preview/2020-11-01-preview/ServerDevOpsAudit.json#L225  , but is conflict with the systemData at  :
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L441

please use the latter one

**Comment by ayeletshpigelman** [comment]
@jianyexi - I don't under the explanation. ServerDevOpsAudit.json is not owned by me. In my files I used the following ref: "$ref": "../../../../../common-types/resource-management/v1/types.json#/definitions/systemData"
which leads to the file you suggested to use.
If there is a problem with ServerDevOpsAudit.json please fix this, but it is not related to my changes.
@akning-ms - Appreciate your approval, we got another CRI regarding this during the weekend. Customers are waiting for the fix
thank you

**Comment by ericshape** [comment]
> @jianyexi - I fixed the lint diff
> @akning-ms - Appreciate your approval, we got another CRI regarding this during the weekend. Customers are waiting for the fix
> thank you

@ayeletshpigelman  @jianyexi 
please use the SQL specific systemData: https://github.com/Azure/azure-rest-api-specs/blob/47b422a4d1ea9f4736739a4a6a19d4a8a2fe54d9/specification/sql/resource-manager/common/v1/types.json#L100
1. the systemData filed in all SQL DB APIs is a dummy. we did not impl it. I think Jenny has let all the ARM reviewers know it. 
2. the SQL DB specific common file is different from the global common one. We have a lot of specific enum values which global one does not support.

**Review by akning-ms — APPROVED** [review]

**Pull request merged**
