### PR TITLE
 Security: 2017-08-01-preview - Introduce IoT security groups resource

### PR DESCRIPTION
**Pull request by galmicrosoft**
* Add the relevant resource definitions
* Add get, put, delete, list operations

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by nschonni** [comment]
Should it be camel cased to "AllowList" and "DenyList"?

**Comment by hovsepm** [comment]
@galmicrosoft who do you want to add as reviewer?

**Comment by galmicrosoft** [comment]
> @galmicrosoft who do you want to add as reviewer?

chlahav
Thank!

**Comment by ravbhatnagar** [comment]
This is been reviewed over skype by ARM team. There are a couple of pending questions.

**Comment by galmicrosoft** [comment]
I pushed another iteration with the required fixes.
Can someone please approve / review?
Thanks :)

**Review by KrisBash — APPROVED** [review]
Changes look good, thanks

**Comment by jhendrixMSFT** [comment]
@galmicrosoft there is still a `DoNotMerge` label on the PR, is it safe to remove?

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by galmicrosoft** [comment]
> @galmicrosoft there is still a `DoNotMerge` label on the PR, is it safe to remove?

@jhendrixMSFT no, we want to check that everything works with feature flag (requiredFeatures in the manifest)

**Comment by jhendrixMSFT** [comment]
@galmicrosoft hello any update?

**Comment by galmicrosoft** [comment]
> @galmicrosoft hello any update?

Hey @jhendrixMSFT, we're still testing out the new feature so we should keep the DoNotMerge label for now. I'll update when we can continue.

**Comment by jhendrixMSFT** [comment]
@galmicrosoft hello any update?  Also there's a merge conflict that needs to be resolved.

**Comment by jhendrixMSFT** [comment]
@galmicrosoft ping

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5564 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5564/commits/f9b170f7556bba155d5055b271a88c6d243aceae

**Comment by galmicrosoft** [comment]
> @galmicrosoft ping

Hi,

I updated the PR (sync from master)
The avocado test is failing with error: 
/home/vsts/work/1/s/specification/security/resource-manager
code: UNREFERENCED_OPEN_API_FILE
message: The OpenAPI file is not referenced from the readme file.
readMeUrl: /home/vsts/work/1/s/specification/security/resource-manager/readme.md
openApiUrl: >-
  /home/vsts/work/1/s/specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/examples/JitNetworkAccessPolicies/InvokeJitNetworkAccessPolicy_example.json

But I didn't touch this file or any files related to this resource...
We can remove the DoNotMerge label and merge when possible

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
