### PR TITLE
Updating SiteAuthSettings

### PR DESCRIPTION
**Pull request by mkarmark**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@mkarmark Adding read-write properties in stable is usually a breaking change. It is better to provide explanation in description (ARM review likely need that too).

**Comment by mkarmark** [comment]
New fields are added to `SiteAuthSettings`. However, they are already supported by the APIs so aren't creating any breaking changes. The new enum value is added to the end of the enum variable so doesn't break the existing enum values.

**Review by naveedaz — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Follow the guideline... (however this is a fix on previously incorrect swagger)

As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ Breaking Change Process

**Comment by mkarmark** [comment]
> Follow the guideline... (however this is a fix on previously incorrect swagger, and AME here is trying to fix that)
> 
> As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ Breaking Change Process

@weidongxu-microsoft  Can you please redirect me to where I can find the approval request form?

**Pull request closed without merging**
