### PR TITLE
Update MDs for Python

### PR DESCRIPTION
**Pull request by lmazuel**
@olydis @fearthecowboy 
I think this is accurate to what I need to make this work.

I have to double the tag for the namespace, but I guess it's ok? (even if verbose)

Note that I didn't test yet, because I wanted to give you an idea as fast as possible, but there should be only typo at worst.

FYI @johanste

### CODE REVIEW

**Review by olydis — APPROVED** [review]
LGTM! However, I think it might make more sense to move the python specific namespaces down to the python specific settings - I mean it's a tradeoff: either everything related to the same package is grouped or everything related to the same programming language is grouped. I'd prefer the latter since it brings the non-codegen specific settings (that 90% of the people looking at this file care about) closer together.

**Comment by lmazuel** [comment]
@olydis Just did it, and group together Python.

However, seems to me that the headers level are not the best we can do, see how it looks:
https://github.com/lmazuel/azure-rest-api-specs/blob/reorg/specification/compute/resource-manager/readme.md

I'm sure exactly what to change.

**Comment by olydis** [comment]
@lmazuel nice, agree regarding header level, will revise and update the entire repo accordingly, don't worry about it for now 🙂

**Comment by lmazuel** [comment]
Checklist for me of MD I need to review to be ready:

- [ ] GraphRBAC
- [ ] Monitor
- [ ] Network
- [ ] SQL
- [ ] Webapp

**Comment by lmazuel** [comment]
@olydis I made all the Composites file I use, except Network. For Network, I just made basics at the end and still need to add some namespace information, but I think I understand you will update it soon, so probably I should wait a little.

**Comment by olydis** [comment]
@lmazuel Sweet, today I will sync the latest changes made to Network

**Comment by lmazuel** [comment]
@olydis So I made a few testing (as you saw :)) and except the "title" issue so far so good. So ready to merge for me.
If you can just merge this before merging reorg to master, would be nice, otherwise I will have to reopen the PR to the new master (but that's not that hard at worst, no worries).
Thanks!!!

**Review by olydis — APPROVED** [review]

**Comment by olydis** [comment]
@lmazuel Thanks! `title` on top level works "now", but I have to confess that I forgot merging my PR until this midnight... so it didn't make it into the nightly. Maybe we'll publish a nightly today since we also wanna test CI ;-)

**Pull request merged**
