### PR TITLE
Adding changes for Distributed Node info list along with new API version 2023 04 01 for RecoveryServicesBackup

### PR DESCRIPTION
**Pull request by chandrikagonuguntla**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>         "isProtectable": {

ARM recommends string enums over booleans. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review). They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).

This AzureVmWorkloadProtectableItem type highlights another reason: a vector of booleans is harder to use. This object has isAutoProtectable, isAutoProtected, and isProtectable creating 8 combinations and is confusing to use. Using an enum is easier to understand and helps eliminate invalid combinations. I'd suggest something like:
protectability: { None, Manual, Auto }
currentProtection: { None, Manual, Auto } 

---
Refers to: specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json:10121 in 35fde2b. [](commit_id = 35fde2bfec81598a849f6a9194dc08994c8872d4, deletion_comment = False)

**Comment by chandrikagonuguntla** [comment]
> > ```
> >     "isProtectable": {
> > ```
> 
> ARM recommends string enums over booleans. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> 
> This AzureVmWorkloadProtectableItem type highlights another reason: a vector of booleans is harder to use. This object has isAutoProtectable, isAutoProtected, and isProtectable creating 8 combinations and is confusing to use. Using an enum is easier to understand and helps eliminate invalid combinations. I'd suggest something like: protectability: { None, Manual, Auto } currentProtection: { None, Manual, Auto }
> 
> Refers to: specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json:10121 in [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4). [](commit_id = [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4), deletion_comment = False)

@mentat9 This is an existing property and has been in the GAed data contract since long time. I'm fixing a Swagger compliance issue by adding this in this version.Changing the type of this property would be a much bigger change in our services and clients. Noted the comment about enum/boolean for future reference. Could you please review the other set of changes. Also the Avocado is expected to fail for RecoveryServicesBackup because we have the swagger for both active and passive stamps.

**Comment by chandrikagonuguntla** [comment]
> > > ```
> > >     "isProtectable": {
> > > ```
> > 
> > 
> > ARM recommends string enums over booleans. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> > This AzureVmWorkloadProtectableItem type highlights another reason: a vector of booleans is harder to use. This object has isAutoProtectable, isAutoProtected, and isProtectable creating 8 combinations and is confusing to use. Using an enum is easier to understand and helps eliminate invalid combinations. I'd suggest something like: protectability: { None, Manual, Auto } currentProtection: { None, Manual, Auto }
> > Refers to: specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json:10121 in [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4). [](commit_id = [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4), deletion_comment = False)
> 
> @mentat9 This is an existing property and has been in the GAed data contract since long time. I'm fixing a Swagger compliance issue by adding this in this version.Changing the type of this property would be a much bigger change in our services and clients. Noted the comment about enum/boolean for future reference. Could you please review the other set of changes. Also the Avocado is expected to fail for RecoveryServicesBackup because we have the swagger for both active and passive stamps.

@mentat9 could you please review this

**Comment by mentat9** [comment]
> > > > ```
> > > >     "isProtectable": {
> > > > ```
> > > 
> > > 
> > > ARM recommends string enums over booleans. Generally enums make better properties than booleans. They are more descriptive and flexible while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They allow values other than just true/false and support description strings. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> > > This AzureVmWorkloadProtectableItem type highlights another reason: a vector of booleans is harder to use. This object has isAutoProtectable, isAutoProtected, and isProtectable creating 8 combinations and is confusing to use. Using an enum is easier to understand and helps eliminate invalid combinations. I'd suggest something like: protectability: { None, Manual, Auto } currentProtection: { None, Manual, Auto }
> > > Refers to: specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json:10121 in [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4). [](commit_id = [35fde2b](https://github.com/Azure/azure-rest-api-specs/commit/35fde2bfec81598a849f6a9194dc08994c8872d4), deletion_comment = False)
> > 
> > 
> > @mentat9 This is an existing property and has been in the GAed data contract since long time. I'm fixing a Swagger compliance issue by adding this in this version.Changing the type of this property would be a much bigger change in our services and clients. Noted the comment about enum/boolean for future reference. Could you please review the other set of changes. Also the Avocado is expected to fail for RecoveryServicesBackup because we have the swagger for both active and passive stamps.
> 
> @mentat9 could you please review this

Please follow the instructions in this comment to hand your PR back to ARM review: https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1571220480. Current ARM review on-call will revisit.

**Comment by JackTn** [comment]
@chandrikagonuguntla  check the avocado validation error `[MULTIPLE_DEFAULT_TAGS]`  https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1567088021 and try to fix it refer to https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1569926384

**Comment by JackTn** [comment]
@tadelesh  @qiaozha  help to check sdk breaking change. Approved if it's OK.

**Comment by tadelesh** [comment]
Go breaking changes are introduced in: https://github.com/Azure/azure-rest-api-specs/pull/23600, not related with this PR.

**Comment by chandrikagonuguntla** [comment]
> @chandrikagonuguntla check the avocado validation error `[MULTIPLE_DEFAULT_TAGS]` [#24210 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1567088021) and try to fix it refer to [#24210 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1569926384)

@jacktn Avocado is expected to fail for recoveryservicesbackup because we have swagger for both passive and active stamps hence 2 defaults.

**Comment by chandrikagonuguntla** [comment]
@JackTn Could you please check comment https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1588638862 and sign off on the PR

**Comment by JackTn** [comment]
> > @chandrikagonuguntla check the avocado validation error `[MULTIPLE_DEFAULT_TAGS]` [#24210 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1567088021) and try to fix it refer to [#24210 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1569926384)
> 
> @JackTn Avocado is expected to fail for recoveryservicesbackup because we have swagger for both passive and active stamps hence 2 defaults.

approve avocado

**Comment by JackTn** [comment]
> @JackTn Could you please check comment [#24210 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1588638862) and sign off on the PR

@msyyc  take a look on this pr and help merge it, Thanks

**Comment by chandrikagonuguntla** [comment]
@msyyc please check comment https://github.com/Azure/azure-rest-api-specs/pull/24210#issuecomment-1590595838 and help with the merge

**Review by msyyc — APPROVED** [review]

**Pull request merged**
