### PR TITLE
DO NOT MERGE : Personalizer : Address API review board comments

### PR DESCRIPTION
**Pull request by dwaijam**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

azure-sdk-for-net PR -  https://github.com/Azure/azure-sdk-for-net/pull/6149

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6142 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6142/commits/b6773748e0c30c76beff38201c206a593b7542c9

**Comment by dsgouda** [comment]
startbuild

**Review by devigned — APPROVED** [review]
The applicationId changes look great; good use of default.

LGTM

**Comment by praries880** [comment]
@dwaijam  Kindly resolve the merge conflicts

**Comment by ravbhatnagar** [comment]
dataplane APIs, not ARM review needed @praries880  -FYI  since ARM does not need to review data plane APIs, "WaitForARMFeedback" is not required.

**Comment by praries880** [comment]
@dwaijam  kindly take care of the merge conflicts. Also, do you have a rough timeline by when the PR will be ready to merge?

**Review by yangyuan — APPROVED** [review]

**Review by yungezz — CHANGES_REQUESTED** [review]
pls fix CI failure and resolve conflicts

**Comment by Juliehzl** [comment]
@dwaijam Please resolve all conflicts first. In this way, CI can work again.

**Comment by yungezz** [comment]
@dwaijam  are you  still on this PR? can you pls resolve conflict? Or close the PR and reopen it when you're ready for reviewing?

**Comment by yungezz** [comment]
@dwijam can we close the PR for now since  the PR is over 4 months without updating, there're lots of conflict with latest code base already. Pls create new PR when you're ready for review and merge.

**Comment by yungezz** [comment]
close it for now since the PR is quite old, and no response from author either on github or from email.

**Pull request closed without merging**
