### PR TITLE
Add examples for sql mi remove maintenance configuration

### PR DESCRIPTION
**Pull request by kukislav**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify 
        - Add more examples 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? March 2020
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by kukislav** [comment]
These two failing pipelines do not seem to be caused by my changes. I have checked all parameters and they are not related to my examples.

**Comment by ericshape** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/13390#issuecomment-796915564

yes. I will fix the v3 and v2 errors of the private endpoint issue as I fixed in v4: https://github.com/Azure/azure-rest-api-specs/pull/13325/files

**Review by ericshape — APPROVED** [review]
LGTM

**Comment by ericshape** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/13404
fixing the validation errors. 
@kukislav if you would like, feel free to pick up my change in https://github.com/Azure/azure-rest-api-specs/pull/13404 to your PR and unblock.

**Comment by ericshape** [comment]
@kukislav 
can you add/update 2020-11-01 example files?

**Comment by kukislav** [comment]
> #13404
> fixing the validation errors.
> @kukislav if you would like, feel free to pick up my change in #13404 to your PR and unblock.

I looked at your PR but doesn't seem like you fixed the failing pipelines there? I can even rebase my PR once you merge yours no worries.

**Comment by kukislav** [comment]
> @kukislav
> can you add/update 2020-11-01 example files?

Added relevant file. Now the pipelines are stuck for some reason. Can you check/retry them?

> 
> And please also fix the issue from #13406 https://github.com/Azure/azure-rest-api-specs/pull/13406/checks?check_run_id=2099011725
> in DSMain and swagger repo.
> 
> Rule	Message
> ❌ OBJECT_MISSING_REQUIRED_PROPERTY	Missing required property: locationUrl: Microsoft.Sql/preview/2020-11-01-preview/ManagedInstances.json#L962
> ❌ OBJECT_ADDITIONAL_PROPERTIES	Additional properties not allowed: maintenanceConfigurationIdUrl: Microsoft.Sql/preview/2020-11-01-preview/ManagedInstances.json#L962
> ❌ OBJECT_ADDITIONAL_PROPERTIES	Additional properties not allowed: maintenanceConfigurationIdUrl: Microsoft.Sql/preview/2020-11-01-preview/ManagedInstances.json#L993

I see that you already made a PR, I approved it.

**Comment by akning-ms** [comment]
Hi @kukislav. pls help fix the conflict first

**Comment by kukislav** [comment]
> Hi @kukislav. pls help fix the conflict first

I rebased on upstream branch.

**Comment by ericshape** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/13404#issuecomment-799897677

Hi @dw511214992 and @akning-ms, 
I check the log and find these exceptions are from the checker plug-in, not from this PR. 
https://dev.azure.com/azure-sdk//internal/_build/results?buildId=786048&view=logs&j=93811faa-026e-5426-72ec-2dc2b400fa28&t=90dbba77-51b8-56f4-d754-25d1039bad39

Can you help to take a look? If the issue is not from this PR, can you help to review and merge? Thanks!

**Pull request merged**
