### PR TITLE
Release Master to branch 2022-06-01-preview

### PR DESCRIPTION
**Pull request by yanfa317**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by yanfa317** [comment]
Hi, @msyyc, can you help us to approve this PR so that our branch can be updated with lastest main ? Thanks!

**Comment by msyyc** [comment]
> Hi, @msyyc, can you help us to approve this PR so that our branch can be updated with lastest main ? Thanks!

Why don't you merge `main` into target branch directly?

**Comment by yanfa317** [comment]
@msyyc, since I have no authorization to do it, can you help us to do it? We just need to make sure the branch is sync with latest main branch. Thanks!

**Comment by msyyc** [comment]
> @msyyc, since I have no authorization to do it, can you help us to do it? We just need to make sure the branch is sync with latest main branch. Thanks!

@akning-ms Could you help merge it? Even though the PR contains so many files, it is just sync operation with main branch. (I can't help update target directly since it is protected branch):
image

**Comment by akning-ms** [comment]
Can I know what the reason to do this?  I am afraid it will cause issue when you submit PR against main from this release branch if I force merge it.  I think you can create another release branch via openapi hub

**Comment by yanfa317** [comment]
@akning-ms Can you help us? Thanks!

**Comment by akning-ms** [comment]
Hi @yanfa317 , As I said, I am afraid you can not create correct PR to main from this release-branch after my force merge, do you have any PR alredy merged into the branch?

**Comment by yanfa317** [comment]
Hi, @akning-ms  Thanks so much for merging this. But since this PR has been delayed for long time, it is behind main branch again. Can you help us to merge the lastest main branch in to this branch? Thanks!

**Pull request merged**
