### PR TITLE
Adding Media Services Event Grid schema

### PR DESCRIPTION
**Pull request by jonpayne**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@jonpayne from the description what I understand is - this model represents the schema of event that media-services internally send to event grid when it is enabled. From customers point of view, the way they use is, they use event grid data plane to retrieve the event in string/json format and then uses this model to deserialize the string to POJO. is my understanding correct?

**Comment by jonpayne** [comment]
@anuchandy This is the schema for the events Media Services will send to customers, via Azure Event Grid. The documentation for these events is here:
https://docs.microsoft.com/en-us/azure/media-services/latest/media-services-event-schemas?toc=%2fazure%2fevent-grid%2ftoc.json
@kalyanaj can provide more details.

**Review by kalyanaj — COMMENTED** [review]
@jonpayne , can you please add a reference to this JSON file in the eventgrid/data-plane/readme.md file? As an example, you can look at other existing publishers such as ContainerRegistry or ServiceBus.

**Comment by kalyanaj** [comment]
@anuchandy , to answer your previous question:  Yes, customers can create an event subscription in EventGrid to subscribe to these events (e.g. an Azure Function can be the destination of this event subscription). Once the event JSON is received there, it can be deserialized into an "EventGridEvent", and the Data portion of the EventGridEvent can be deserialized using the new model that @jonpayne has added in this PR.

**Review by kalyanaj — COMMENTED** [review]
Also, it will be great to use the same directory structure convention used by other existing publishers.

**Review by kalyanaj — APPROVED** [review]
LGTM.

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
