### PR TITLE
Update metrics API limit descriptions

### PR DESCRIPTION
**Pull request by ToddKingMSFT**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by rakeshrana44 — APPROVED** [review]

**Comment by ToddKingMSFT** [comment]
Can I get a bypass on all of these? As you can see I've only updated descriptions, that should not be failing any model validation etc checks.

**Comment by ToddKingMSFT** [comment]
Hmmm I think lintdiff is failing due to this error
2024-12-02T18:03:58.3631646Z Count of AutoRest exceptions found in the LintDiff stdout or stderr: 6. Context: swagger: specification/monitor/resource-manager/readme.md, beforeOrAfter: before, tag: package-2021-05-metrics, lintDiffStdoutAndStderr.length: 189094.

Specifically these 2 errors:
{
  "type": "AutoRest exception",
  "message": "Ref '#/parameters/MetricNamesParameter' is not referencing a valid location. paths,/{resourceUri}/providers/Microsoft.Insights/metricBaselines,get,parameters,1",
  "readmeUrl": "https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/readme.md",
  "tag": "package-2021-05-metrics",
  "context": "before"
},
{
  "type": "AutoRest exception",
  "message": "Ref '#/parameters/MetricNamespaceParameter' is not referencing a valid location. paths,/{resourceUri}/providers/Microsoft.Insights/metricBaselines,get,parameters,2",
  "readmeUrl": "https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/readme.md",
  "tag": "package-2021-05-metrics",
  "context": "before"
},

I fixed these in my PR, and don't get these anymore locally but I think lint diff is hitting them when running against the checked in code.
I'm not sure how to resolve that, I think I'll need another bypass for that.

**Comment by ToddKingMSFT** [comment]
posted request for help to API Spec Review channel to get help bypassing this lint diff error

**Comment by mikeharder** [comment]
> posted request for help to API Spec Review channel to get help bypassing this lint diff error

This was fixed yesterday:

https://github.com/Azure/azure-rest-api-specs/pull/30787/files#diff-264accec1b0fe201eedacac26baaf709a64bed776778f36992c08265ac4b6165L644

If you merge latest main into your branch, your PR should be unblocked from the LintDiff crash.  You might need to fix or suppress other (non-crash) errors.

**Review by anirudhcavale — APPROVED** [review]

**Review by rakeshrana44 — APPROVED** [review]

**Review by Haiying-MSFT — APPROVED** [review]
Doc change only. Approve.

**Review by rakeshrana44 — APPROVED** [review]
Doc change approved

**Pull request merged**
