### PR TITLE
[Hub Generated] Review request for Microsoft.Billing to add version preview/2019-10-01-preview

### PR DESCRIPTION
**Pull request by supriyam-dev**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/supriyam-dev/azure-rest-api-specs/dev-billing-Microsoft.Billing-2019-10-01-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
Please fix PrettierCheck

**Review by wilcobmsft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Reminder sent to ARM review a few days ago, but no response. ARM response in this 2 weeks seems late.

**Comment by weidongxu-microsoft** [comment]
@supriyam-dev 

Appears that ARM team no longer reviewing the PRs. Let me know when it need merged.

**Comment by supriyam-dev** [comment]
> @supriyam-dev
> 
> Appears that ARM team no longer reviewing the PRs. Let me know when it need merged.

@weidongxu-microsoft : Please merge this. thanks!

**Pull request merged**
