### PR TITLE
RoundTrip additional property and object additional property S360 fix by adding defaults and renaming respectively

### PR DESCRIPTION
**Pull request by dhawal777**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dhawal777** [comment]
Updating common properties across all version to avoid S360 in any version. Thanks

**Comment by allenjzhang** [comment]
@dhawal777 , please review model validation errors. Looks like it is missing `dataDestinationType` in the example files for `destinationAccountDetails`.

**Comment by dhawal777** [comment]
> @dhawal777 , please review model validation errors. Looks like it is missing `dataDestinationType` in the example files for `destinationAccountDetails`.

Thanks @allenjzhang, Fixed Those. I need one more suggestion. Across all version I need to set default for a         "notificationPreference" property in contactDetails, which is array whose item is a reference. I didn't found any document with such example, How to achieve that. Kindly guide, Thanks

**Comment by dhawal777** [comment]
Hi @allenjzhang, I think PR is Paused in CI pipeline or something. Is anything to address. Thanks

**Comment by dhawal777** [comment]
Also @allenjzhang,  Can I take SystemData changes with this PR in 2020-11-01 version, as it is raised as LINT S360 on our service.

**Comment by dhawal777** [comment]
Hi @zhenglaizhang @allenjzhang , Kindly suggest if anything can be done on above queries, so that we can close few S60 post taking the suggestions and merging the PR. Thanks

**Comment by allenjzhang** [comment]
Waiting on feedback on the casing change.  Otherwise looks fine.

**Review by JeffreyRichter — APPROVED** [review]

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
