### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerInstance to add version stable/2019-12-01

### PR DESCRIPTION
**Pull request by novinc**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/novinc/azure-rest-api-specs/dev-containerinstance-Microsoft.ContainerInstance-2019-12-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [x] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by fengzhou-msft — APPROVED** [review]

**Review by chiragg4u — COMMENTED** [review]
Changes looks good. Any reason for creating 2019-12-01 version? why note 2020-07-01?

**Comment by novinc** [comment]
We’ve had this api version for a while but never got around to actually releasing the spec/clients for it since it was punted in priority. We would have to make code changes to rename it so I kept the name.

**Review by chiragg4u — APPROVED** [review]
Approved.

**Comment by novinc** [comment]
Thanks, @fengzhou-msft could you merge this when you get the chance?

**Pull request merged**
