### PR TITLE
add the list and cancel database operations

### PR DESCRIPTION
**Pull request by jiawang003**
request to add the new list and cancel database operations under 2017-03-01-preview, run autorest validation without issue

### CODE REVIEW

**Review by jianghaolu — APPROVED** [review]

**Review by jaredmoo — APPROVED** [review]

**Comment by ravbhatnagar** [comment]
Looks fine. Just one thing - Do you need an API to get a single operation - /operations/operationid as well?

**Comment by ravbhatnagar** [comment]
@jiawang003 @jaredmoo FYI on above comment. Else looks good.

**Comment by jiawang003** [comment]
customer need to find OperationId first. no need for now

**Comment by ravbhatnagar** [comment]
Ok, just wanted to bring to your notice in case you missed. Looks good.  ARM sign off.

**Pull request merged**
