### PR TITLE
[Hub Generated] fix host parametrization in all non-Creator Maps Clients

### PR DESCRIPTION
**Pull request by ambientlight**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/ambientlight/azure-rest-api-specs/fix%2Fmaps-parametrized-host...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [x] All Maps clients had `x-ms-parameterized-host` applied, while only Maps - Creator clients needs such parametrization arising from **data sovereignty** requirement, as creator stores and manages customer data. This fixes redundant parametrization for non-creator swagger specs.
  2. When you are targeting to deploy new service/feature to public regions? **Services are already deployed.**
  3. When you expect to publish swagger? **ASAP**
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
  No data-plane SDKs are onboarded yet, so no refresh required.

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate):
**Submitted new intake:** https://msazure.visualstudio.com/One/_workitems/edit/10450031

### CODE REVIEW

**Review by evaou — APPROVED** [review]

**Comment by daniel-rocha** [comment]
Hi @tjprescott as @ambientlight explained in the other PRs, this isn't really a breaking change, just fixing the Swagger to match what the production APIs look like. Can you please approve and merge this? It's blocking our SDK generation. Thanks!

**Comment by daniel-rocha** [comment]
@johanste can you do the breaking change review here too, please? Thanks!

**Comment by tjprescott** [comment]
@ambientlight @daniel-rocha have any SDKs been released with the previous version of the API?

**Comment by ambientlight** [comment]
@tjprescott: no Azure Maps REST sdks have been released yet.

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@lmazuel can you merge this WIP? No SDKs have been released with this Swagger.

**Pull request merged**
