### PR TITLE
fixing overwritting issue

### PR DESCRIPTION
**Pull request by azhao155**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by azhao155** [comment]
https://github.com/Azure/azure-rest-api-specs/commit/1497fea6c9d835fbca362997f94301a22a8fc48e
have overwritten some changes in Oct and Nov version, this is the fix.

**Comment by marstr** [comment]
Usurping this PR because I have some context. I hope you don't mind, @olydis!

**Comment by marstr** [comment]
@azhao155, I have some homework for you. Could you please find me the most recent API Version/commit with these changes that you are looking to replicate into this API Version? Bonus points if you can find me the PRs which introduced the changes that you're re-applying here. It'll help me speed up the process of reviewing, and maybe help us skip some of the process to get these in ASAP.

**Comment by azhao155** [comment]
@marstr 
the 1101 under stable folder should contain all the changes, and the following are the changes i made and corresponding PR:

  https://github.com/Azure/azure-rest-api-specs/pull/2203   
LoadBalancerCreateWithInboundNatPool.json
PublicIpAddressGet.json
PublicIpAddressList.json
loadBalancer.json
publicIpAddress.json
														   
 https://github.com/Azure/azure-rest-api-specs/pull/2223   
NetworkWatcherConnectionMonitorCreate.json
NetworkWatcherConnectionMonitorGet.json
NetworkWatcherConnectionMonitorList.json
NetworkWatcherConnectionMonitorQuery.json
NetworkWatcherConnectionMonitorStart.json
NetworkWatcherConnectionMonitorStop.json
networkWatcher.json
														   
https://github.com/Azure/azure-rest-api-specs/pull/2276	   
RouteFilterRuleCreate.json
RouteFilterRuleGet.json
RouteFilterRuleListByRouteFilter.json	
RouteFilterRuleUpdate.json
routeFilter.json

**Comment by marstr** [comment]
Thanks @azhao155, I'll start taking a look at that now.

**Comment by marstr** [comment]
I've confirmed that, other than version number strings, the following addition is the only difference between `master`'s 2017-11-01 API Version and @azhao155's 2018-01-1 API Version.

```
"requestBodyCheck": { 
          "type": "boolean", 
           "description": "Whether allow WAF to check request Body." 
}, 
"maxRequestBodySize": { 
           "type": "integer", 
           "format": "int32", 
           "maximum": 128, 
           "exclusiveMaximum": false, 
           "minimum": 8, 
           "exclusiveMinimum": false, 
           "description": "Maxium request body size for WAF."
```

**Review by marstr — APPROVED** [review]

**Pull request merged**
