### PR TITLE
Data Factory: fixed readme, added java readme

### PR DESCRIPTION
**Pull request by iscai-msft**

### CODE REVIEW

**Comment by zikalino** [comment]
@iscai-msft could you give some more details on the purpose of the fixes in readme file?
Seems like the resulting change is huge and in addition CI here seems to be failing: https://github.com/Azure/azure-sdk-for-java/pull/3084

**Comment by iscai-msft** [comment]
@zikalino I realize the file changes seem big but in actuality there isn't much change, I just decomposed the Java section into a separate readme for readability and fixed the namespace of datafactory in java from datafactoryv2 to just datafactory.

You are right, it does seem to be failing the azure-sdk-for-java CI but I checked and that's because of an autorest error which I've filed an issue for, and shouldn't be due to the readme changes.

Hope this answers your questions!

**Review by zikalino — APPROVED** [review]
yes, looks good

**Comment by zikalino** [comment]
@zhangyd2015 ok to merge?

**Comment by zhangyd2015** [comment]
> @zhangyd2015 ok to merge?

@hvermis to add comments.

**Review by hvermis — APPROVED** [review]

**Pull request merged**
