### PR TITLE
Improve AKS Swagger documentation

### PR DESCRIPTION
**Pull request by matthchr**
This change has already been merged in master for the 2021-05-01 API version.
See PR #14934

### CODE REVIEW

**Comment by matthchr** [comment]
Note: The spellcheck errors are fixed in master (I added the words to the known-words txt file) but didn't port that change here. merging master into this branch would resolve those problems (rather than making them twice).

**Comment by PhoenixHe-msft** [comment]
@matthchr Would you want us help to merge from master to your dev branch to resolve the issue?

**Comment by matthchr** [comment]
is there any downside to merging master to the branch? if not, might be a good idea just for the spellcheck errors?

**Comment by matthchr** [comment]
I ported my additions to custom-words.txt from my previous PR. The flagged spelling problems should be resolved now.

**Comment by matthchr** [comment]
@PhoenixHe-msft - can this be merged now?

**Review by kaiqzhan — APPROVED** [review]

**Review by PhoenixHe-NV — APPROVED** [review]

**Pull request merged**
