### PR TITLE
Added missing PATCH verbs to existing endpoints

### PR DESCRIPTION
**Pull request by gatneil**

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
These patch operations violate RPC guidelines, here's an example.
```
"Properties of a PATCH request body must not be required. PATCH operation: 'AvailabilitySets_Update' Model Definition: 'Resource' Property: 'location'",
```
You can find the complete log in the Travis job [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/268577180).
For an example of how this should work take a look at what the SQL team did in [this](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/sql/resource-manager/Microsoft.Sql/2014-04-01/servers.json) swagger doc.

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
RPC violations in new operations need to be cleaned up.

**Comment by gatneil** [comment]
@ravbhatnagar @jhendrixMSFT for the PUTs, location is of course required; however, for PATCHes, location is not (thus your comment). Currently the Resource definition has location required. So one way to remedy this is to create a new definition like "ResourceForPatch" that is the same but has location not required. The issue with that, though, is that we'll have to duplicate every definition built on top of "Resource" so that the PATCH version of the API can use the correct PATCH definition (e.g. PATCH of AvailabilitySet will call "AvailabilitySetForPatch", which will call "AvailabilitySetPropertiesForPatch" which call "ResourceForPath"). This seems like it would be counter to the purpose of Swagger, so I'm guessing there's a better way to do this? :)

**Comment by ravbhatnagar** [comment]
@gatneil - Is every property for all the resource types updatable? All the proxy resources should not have a location and for all the tracked ones, I guess having separate models for put and patch is the only way I know. Adding some other SDK folks who may have input on this - @amarzavery , @veronicagg

**Comment by jhendrixMSFT** [comment]
@ravbhatnagar Yes I believe you're correct that having separate models is the way to fix this (it's what the SQL team did).

**Comment by jhendrixMSFT** [comment]
@gatneil Will you be able to update the model to properly handle patch operations?  Also there are some linter and model validation errors, see the following travis logs.
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269413006
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269413008
It might be easier to run the validation locally, that way you can quickly iterate on these issues before updating the PR.  Here are the instructions.
https://github.com/Azure/adx-documentation-pr/blob/master/tools/tools.md

**Comment by gatneil** [comment]
At this point, probably not; I'll close the PR for now and re-visit later :)

**Pull request closed without merging**
