### PR TITLE
Azure Event Grid Control Plane 2024-06-01-preview API Version

### PR DESCRIPTION
**Pull request by a-hamad**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary>Click here to see the details of Step 1, Breaking Changes review</summary>

If you are in purview of Step 1 of the diagram, follow the [Breaking Changes review process].  
**IMPORTANT!** This applies even if you believe your PR was mislabeled, for any reason, including tool failure.
</details>

<details> 
<summary>Click here to see the details of Step 2, ARM review</summary>

See https://aka.ms/azsdk/pr-arm-review.
</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[Breaking Changes review process]: https://aka.ms/brch

### CODE REVIEW

**Comment by a-hamad** [comment]
hello @tadelesh Can you please help review this PR and resolve the remaining issues?

I addressed all new Lintdiff issues and remaining ones seems to be tool related issues are they are flagging existing resources that are not part of the new PR and the same issues were identified earlier in previous PR as tool related issue.

Also, how can we get ARM review done faster for us to unblock ARM Manifest rollout?

**Comment by raosuhas** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventGrid/namespaces/{namespaceName}/topics/{topicName}/eventSubscriptions/{eventSubscriptionName}/getFullUrl": {

why is this modelled as a post action rather than just a property on the eventsubscriptions or a separate child resource ? 

Generally in ARM we prefer to use GET operations even for static information since otherewise this information is not accessible via templates\ARG \ Azure policy etc if you make it a POST

---
Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2024-06-01-preview/EventGrid.json:11644 in 7d72b3b. [](commit_id = 7d72b3beefa4a6e6a2de56405946f225c3958328, deletion_comment = False)

**Comment by raosuhas** [comment]
>             "description": "Name of the event subscription to be created. Event subscription names must be between 3 and 64 characters in length and use alphanumeric letters only.",

reducing the size is a breaking change. would this cause existing subscriptionname > 64 chars to stop working ? Are you doing any validation here ?

---
Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2024-06-01-preview/EventGrid.json:4509 in 7d72b3b. [](commit_id = 7d72b3beefa4a6e6a2de56405946f225c3958328, deletion_comment = False)

**Comment by raosuhas** [comment]
You also seem to have a few newly introduced lintdiff warnings: https://github.com/Azure/azure-rest-api-specs/pull/28631/checks?check_run_id=23719490736 could you please fix those as well ?

**Comment by a-hamad** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventGrid/namespaces/{namespaceName}/topics/{topicName}/eventSubscriptions/{eventSubscriptionName}/getFullUrl": {
> > ```
> 
> why is this modelled as a post action rather than just a property on the eventsubscriptions or a separate child resource ?
> 
> Generally in ARM we prefer to use GET operations even for static information since otherewise this information is not accessible via templates\ARG \ Azure policy etc if you make it a POST
> 
> Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2024-06-01-preview/EventGrid.json:11644 in [7d72b3b](https://github.com/Azure/azure-rest-api-specs/commit/7d72b3beefa4a6e6a2de56405946f225c3958328). [](commit_id = [7d72b3b](https://github.com/Azure/azure-rest-api-specs/commit/7d72b3beefa4a6e6a2de56405946f225c3958328), deletion_comment = False)

We are following same pattern for all other post calls for getFullUrl in existing resource model. This was requirement from ARM team before as full Url will contain secret hence it is not returned in normal get call

example:
- "/{scope}/providers/Microsoft.EventGrid/eventSubscriptions/{eventSubscriptionName}/getFullUrl": 

https://github.com/Azure/azure-rest-api-specs/blob/72d10f1095250a21e4a1f08005980e3b95a01035/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-12-15-preview/EventGrid.json#L4297

- /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventGrid/partnerTopics/{partnerTopicName}/eventSubscriptions/{eventSubscriptionName}/getFullUrl": 

 https://github.com/Azure/azure-rest-api-specs/blob/72d10f1095250a21e4a1f08005980e3b95a01035/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-12-15-preview/EventGrid.json#L4686

**Comment by a-hamad** [comment]
> > ```
> >         "description": "Name of the event subscription to be created. Event subscription names must be between 3 and 64 characters in length and use alphanumeric letters only.",
> > ```
> 
> reducing the size is a breaking change. would this cause existing subscriptionname > 64 chars to stop working ? Are you doing any validation here ?
> 
> Refers to: specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2024-06-01-preview/EventGrid.json:4509 in [7d72b3b](https://github.com/Azure/azure-rest-api-specs/commit/7d72b3beefa4a6e6a2de56405946f225c3958328). [](commit_id = [7d72b3b](https://github.com/Azure/azure-rest-api-specs/commit/7d72b3beefa4a6e6a2de56405946f225c3958328), deletion_comment = False)

No impact on existing event subscription and no change in this limit.. This is just updating the summary/description with correct value as the older limit was a typo. there is no change in RP service s it was already doing right thing.

**Comment by a-hamad** [comment]
> You also seem to have a few newly introduced lintdiff warnings: https://github.com/Azure/azure-rest-api-specs/pull/28631/checks?check_run_id=23719490736 could you please fix those as well ?

Addressed. thanks.

**Comment by a-hamad** [comment]
@raosuhas Thanks for the review. We addressed all the comments and labeled the PR with Waiting for ARM feedback. Kindly re-review the changes. thanks

**Comment by raosuhas** [comment]
> @raosuhas Thanks for the review. We addressed all the comments and labeled the PR with Waiting for ARM feedback. Kindly re-review the changes. thanks

Thanks @a-hamad . The comments sound good to me. For the suppressions could you please add suppressions for specific paths : 

https://eng.ms/docs/products/azure-developer-experience/design/specs-pr-guides/pr-suppressions
image

**Comment by a-hamad** [comment]
thank @raosuhas . suppression updated to include path. thx

**Review by ramoka178 — APPROVED** [review]
Approving to merge

**Pull request merged**
