### PR TITLE
[Hub Generated] Review request for Microsoft.Cache to add version preview/2020-10-01-preview

### PR DESCRIPTION
**Pull request by greenms**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/greenms/azure-rest-api-specs/dev-redisenterprise-Microsoft.Cache-2020-10-01-preview...master/).

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by greenms** [comment]
@akning-ms Need this breaking change to remove any potential confusion with having database operations split between two different operationId prefixes.  This change consolidates the database operations to a single operationId prefix.

**Comment by akning-ms** [comment]
> @akning-ms Need this breaking change to remove any potential confusion with having database operations split between two different operationId prefixes. This change consolidates the database operations to a single operationId prefix. No known customers are using this Swagger spec at this point, so there shouldn't be any customer impact to mitigate.

Thanks, I see, BTW, Did you request any SDK release based on this swagger?

**Comment by greenms** [comment]
@akning-ms I will request updates to the GO SDK and the .NET SDK after this gets approved.  Both are based on this Swagger. 
 Thanks.

**Comment by greenms** [comment]
I created this intake work item https://msazure.visualstudio.com/One/_workitems/edit/8815494

**Comment by TimLovellSmith** [comment]
@akning-ms The breaking changes are to fix inconsistencies in the type/operation names and resulting documentation we found in this preview api's initial auto-generated-SDK / doc releases. For these inconsistencies, it was much easier to spot them in the generated docs than in the swagger. Is there any way we could have got linter errors for these? Maybe more consistency rules about operation names for actions on same resource type, with resource type inferred from resource uri, would help.

**Review by JeffreyRichter — APPROVED** [review]

**Review by TimLovellSmith — APPROVED** [review]

**Comment by zhenglaizhang** [comment]
relabeling *Approved-BreakingChange* to retrigger botlogic to mark the *Swagger BreakingChange* status as neutral to unblock PR merging

**Pull request merged**
