### PR TITLE
Add mysql and postgresql swagger specs

### PR DESCRIPTION
**Pull request by Suna-MS**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by Suna-MS** [comment]
The swagger specs are already existing in private repo: azure-rest-api-specs-pr/arm-rdbms, just copy them to the public repo and split to two folder.

**Comment by fearthecowboy** [comment]
@Suna-MS If you're ready for me to review this can you make sure you've completed the checklist. 

The validator only found a couple of issues (well, the same one for each)


`WARNING (PutRequestResponseScheme/R2017/SDKViolation): ` A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT.
If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'Servers_CreateOrUpdate' Request Model: 'ServerForCreate' Response Model: 'Server'
 arm-postgresql/2017-04-30-preview/swagger/postgresql.json:38:6 

and 


`WARNING (PutRequestResponseScheme/R2017/SDKViolation): ` A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT.
If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: 'Servers_CreateOrUpdate' Request Model: 'ServerForCreate' Response Model: 'Server'

arm-mysql/2017-04-30-preview/swagger/mysql.json:38:7

which is really just trying to say, is it possible to reuse the models from GET and PUT so that the model class that's used can be passed from one to the other.

**Review by fearthecowboy — DISMISSED** [review]
Complete checklist to have review started

**Comment by balajikris** [comment]
@Suna-MS - when this is merged, please ping me for node-sdk related work. someone already hand-generated the SDK by working against the spec from the private repo and had that checked in to azure-sdk-for-node. we'd have some work (minimal I'd expect) to keep regeneration pipeline going for node after this spec gets merged here.

**Comment by salameer** [comment]
switching to @balajikris since @fearthecowboy is OOF

@Suna-MS  can you please respond to the feedback here?

**Comment by Suna-MS** [comment]
I have talked with @fearthecowboy offline about the two warnings reported by AutoRest Linter, they are all known issues for us:  When creating a server, we need to provide CreateMode which can be “Default” or “PointInTimeRestore”, and with different properties in request body for each mode. Following the guide, we make it as discriminator, but in our response body, we don’t return CreateMode (it is only required in request body). Thus, if we make the request body schema the same as its 200 response schema, there will be deserialization error in python SDK (and also other SDKs) because discriminator will be marked as required. So we have to define two schemas for PUT request and PUT response (GET). 
@balajikris, any other comments?

**Comment by balajikris** [comment]
```
Complete checklist to have review started
```

@Suna-MS -- can you please take care of the above comment.

**Comment by balajikris** [comment]
Adding @ravbhatnagar for ARM related guidance as this spec is being checked in for the first time into the public repo.

**Comment by balajikris** [comment]
_Status:_ Spec looks great from our automated tools' perspective, except for the one warning explained above. Performing manual review.

**Review by balajikris — CHANGES_REQUESTED** [review]
1. Just double checking here - are we keeping the `-preview` in the version? Is that the right version.

1. For both postgres and mysql specs - lines 898, 936, 1031, 1104 and everywhere else there is a "Minimum" constraint defined, Should there also be a "Maximum" limit defined? This may apply on a case-by-case basis, please review those lines and make changes if needed.

1. For both postgres and mysql specs, at lines 292 (firewallRuleName), 471 (databaseName), 650 (configurationName). these are re-defined for each get/put/delete method. Please extract them out to the global params section and re-use them.
While I pointed out at 3 examples, there may be more such cases, please review the spec and fix them at all places.

**Comment by balajikris** [comment]
Spec looks neat. Suggested few minor changes above.

**Comment by Suna-MS** [comment]
@balajikris, for your comments: 
1. azure mysql and postgres are still in public review, so "-preview" is required in version.
2. we have not finalized the maximum limitation until now, so not add it for StorageMB and capacity.
3. fixed in new commit,

**Review by balajikris — APPROVED** [review]

**Comment by balajikris** [comment]
LGTM, pulling this in.

**Comment by balajikris** [comment]
@fearthecowboy -- Just an FYI, that I had to dismiss your earlier "Requested changes" review feedback, as github won't let me merge with it. 😄 I've reviewed the specs per @salameer 's reassignment of this PR and things look good to me.

**Comment by balajikris** [comment]
@tombuildsstuff @krancour - FYI, I know you were looking forward to this PR. this is now merged and language SDKs should start coming up soon.

**Comment by tombuildsstuff** [comment]
Awesome! Thanks @balajikris :)

**Pull request merged**
