### PR TITLE
[Do Not Merge] Adding support for UserAssignedIdentities

### PR DESCRIPTION
**Pull request by shail2208**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [y ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ y] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ y] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by allenjzhang** [comment]
Looks like this is work in progress with failures in validation pipeline. Added DoNotMerge tag. 
Please review failures. Once fixed please comment to resume process.

**Comment by majastrz** [comment]
>           "description": "For future use - The client id of the identity which will be used to access key vault.",

If we are not using the property, it shouldn't be included. When we need it, you can add a new API version that includes it.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-02-01/machineLearningServices.json:3260 in 4040b22. [](commit_id = 4040b22580ee69ab5a67d433fa5bde3f957c8f71, deletion_comment = False)

**Review by majastrz — CHANGES_REQUESTED** [review]
I added a comment. Please take a look.

**Comment by majastrz** [comment]
> > ```
> >       "description": "For future use - The client id of the identity which will be used to access key vault.",
> > ```
> 
> If we are not using the property, it shouldn't be included. When we need it, you can add a new API version that includes it.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-02-01/machineLearningServices.json:3260 in [4040b22](https://github.com/Azure/azure-rest-api-specs/commit/4040b22580ee69ab5a67d433fa5bde3f957c8f71). [](commit_id = [4040b22](https://github.com/Azure/azure-rest-api-specs/commit/4040b22580ee69ab5a67d433fa5bde3f957c8f71), deletion_comment = False)

Discussed over Teams. The property was already there.

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by allenjzhang** [comment]
@shail2208 Hi, its been a while. Do you still plan to submit this PR? If so, can you resolve all conflicts and ensure checks are passing? Once you are ready again, please add label `ReadyForSDKReview` or ping me directly on Teams. Thanks.

**Comment by allenjzhang** [comment]
Closing PR as feature team is putting this on hold..

**Pull request closed without merging**
