### PR TITLE
[Nginx] make the operation id from Create to CreateOrUpdate

### PR DESCRIPTION
**Pull request by limingu**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by msyyc** [comment]
Hi @JeffreyRichter The change will cause breaking for SDK. Could you help review it?

**Comment by JeffreyRichter** [comment]
What is motivating this break? Why is it necessary to break all the SDK customers?

**Comment by limingu** [comment]
> What is motivating this break? Why is it necessary to break all the SDK customers?

@JeffreyRichter this is feedback from F5 who owns NGINX service. They think the method name 'Create' is not very clear to the customers. 'CreateOrUpdate' will be more clear. The SDK was released only a few weeks ago. It won't break many customers.

**Comment by JeffreyRichter** [comment]
Azure's policy is to not break customers and this change is gratuitous. Also, a PUT is actually create it replace (not update). You can add text to the documentation that this Create method can also be used to replace the resource.

**Comment by msyyc** [comment]
> Azure's policy is to not break customers and this change is gratuitous. Also, a PUT is actually create it replace (not update). You can add text to the documentation that this Create method can also be used to replace the resource.

@weidongxu-microsoft @ArcturusZhang @tadelesh @qiaozha What's your opinion about the potential breaking for SDK?

**Comment by weidongxu-microsoft** [comment]
Java SDK is in preview, also we wrap the "PUT" method so it does not break in this particular case (after this change, SDK would add an "update" code flow https://github.com/azure-sdk/azure-sdk-for-java/pull/2115/files#diff-d229328808a3fcca9ddd38b48a57d48c8bf0fb8e83d01840dc51817fe6105be0).

Since there is no PATCH method on this certificate resource, the rename kind of make sense. Though the only justification of the change would be that it only affect SDK and SDK only released a few months back.

**Comment by JeffreyRichter** [comment]
I'm curious: How many months does an SDK have to be available before we would decide not to break customers?

**Comment by weidongxu-microsoft** [comment]
Maybe it is backend's responsibility to show from ARM telemetry data that none of the GA SDK ever called the endpoint in question (aka, "PUT" to "/providers/Nginx.NginxPlus/nginxDeployments/{deploymentName}/certificates/{certificateName}")?

ARM data has userAgent, so it should be possible and not hard.

**Comment by msyyc** [comment]
Hi @ArcturusZhang @qiaozha Please help review SDK breaking

**Comment by tadelesh** [comment]
@JeffreyRichter Regarding it will cause Go major version pump, could you help to approve?

**Comment by JeffreyRichter** [comment]
Do we have to make this change? What if this function was always called Create she we just change the documentation to say that it can also update? 

By the way, PUT means create or replace while PATCH means create or update.

**Comment by bangbingsyb** [comment]
> Do we have to make this change? What if this function was always called Create she we just change the documentation to say that it can also update?
> 
> By the way, PUT means create or replace while PATCH means create or update.

Hi @JeffreyRichter 

I think the main goal for this PR is to make our operation naming convention consistent - for example, in our PUT config API, we have "CreateOrUpdate" operation ID while we have "Create" in PUT deployment/certificate. This will cause inconsistent SDK user experience.
 
The service is going to GA in Nov, while the SDK has not been announced so that we don't expect much customer impact.

**Comment by JeffreyRichter** [comment]
OK then. I approved this because no customers would actually be broken since no SDKs were ever produced.

**Comment by tadelesh** [comment]
Approved for Go SDK breaking. The package `[sdk/nginx/armnginx/v1.0.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/nginx/armnginx)` seems not imported by any other libs yet.

**Review by msyyc — APPROVED** [review]

**Pull request merged**
