### PR TITLE
Adding typespec package for liftr base

### PR DESCRIPTION
**Pull request by nikhgup**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

Copy of this PR https://github.com/Azure/azure-rest-api-specs/pull/29569
By Mistake pushed wrongs commits while resolving conflicts

### CODE REVIEW

**Comment by timotheeguerin** [comment]
Can this package metadata be updated(repo url, bug url, etc.), there is also no README. And same comment as @mikeharder we can't actually get access to the url you linked.

Where can user find docs on this?

**Comment by nikhgup** [comment]
@timotheeguerin this package will be used for Liftr team to write typespecs for multiple RPs, we own. Code is part of ADO repo which is private. Let me ask admin to add you to SG to get the access of repo.

**Comment by timotheeguerin** [comment]
> @timotheeguerin this package will be used for Liftr team to write typespecs for multiple RPs, we own. Code is part of ADO repo which is private. Let me ask admin to add you to SG to get the access of repo. cc: @allenjzhang

Is it useful to have a dedicated package then vs just sharing some code in the spec repo across your Rps?

**Comment by allenjzhang** [comment]
> Can this package metadata be updated(repo url, bug url, etc.), there is also no README. And same comment as @mikeharder we can't actually get access to the url you linked.

@nikhgup, Tim has a point. Since Liftr-xxx are public package now on npm, it should have basic readme info. Right now [it has none](https://www.npmjs.com/package/@azure-tools/typespec-liftr-base). 

In addition, now with Liftr lite self-serve model, you really should consider to have a documentation page to document the typical usages. I don't even mind helping you host it under TypeSpec azure website under Libraries section  `Libraries\Liftr\[liftr-base|liftr-storage|liftr-data]`.

I suggest:
- add basic readme and publish a new version
- resolve the conflict and update the PR.

**Comment by nikhgup** [comment]
@allenjzhang will open another PR as not sure after rebase why these many commits are being pushed. Will add readme and upgrade the npm package version.
cc: @timotheeguerin

**Comment by timotheeguerin** [comment]
Please don't try to recreate PRs like that we loose the conversations.
You can force push back to this branch in the same way you would have created a new pr.

**Pull request closed without merging**
