### PR TITLE
Rename CostManagement 2018-09-01-preview to 2018-08-01-preview

### PR DESCRIPTION
**Pull request by ariehf**
Rename CostManagement 2018-09-01-preview to 2018-08-01-preview. 
Change requested by @ravbhatnagar

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
@ariehf - were any SDKs published using the old api-version. If not, good from ARM side.

**Comment by ariehf** [comment]
The CostManagement team have not published an SDK using the old api-version

**Review by marstr — APPROVED** [review]
Given that this is in the preview folder, the fact that this is a breaking change is immaterial.

**Comment by marstr** [comment]
@ariehf, are you ready for me to merge this?

**Comment by ariehf** [comment]
Yes

**Pull request merged**
