### PR TITLE
ManagedInstance api for restoredDroppableDatabases (restoredDroppableManagedDatabases)

### PR DESCRIPTION
**Pull request by dejandundjerski**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by anuchandy — CHANGES_REQUESTED** [review]
@dejandundjerski it seems there is json semantic error, See the error in the CI output https://travis-ci.org/Azure/azure-rest-api-specs/jobs/415859628

**Comment by dejandundjerski** [comment]
@anuchandy , I've fixed the error and validation is now passing.

**Comment by anuchandy** [comment]
@dejandundjerski thanks for fixing the semantic error. I see "don't merge" in title, is it because you have more changes coming or service is not yet in production?

**Comment by dejandundjerski** [comment]
Service is not yet in production. ETA for production is 3 weeks.

**Comment by dejandundjerski** [comment]
Tested the change on stage. Returned results as expected:

PS C:\Users\dejandu> Get-AzureRmResource -ResourceId /subscriptions/8cfb8b62-bcd6-4713-89ad-18097f75cc5b/resourceGroups/clperftesting_sneu_rg/providers/Microsoft.Sql/managedInstances/stlazitest/restorableDroppedDatabases -ApiVersion 2017-03-01-preview


Name              : cdb15000,131793381718870000
ResourceId        : /subscriptions/8cfb8b62-bcd6-4713-89ad-18097f75cc5b/resourceGroups/clperftesting_sneu_rg/providers/Microsoft.Sql/managedInstances/stlazitest/restorableDroppedDatabases/cdb15000,131793381718870000
ResourceName      : stlazitest/cdb15000,131793381718870000
ResourceType      : Microsoft.Sql/managedInstances/restorableDroppedDatabases
ResourceGroupName : clperftesting_sneu_rg
Location          : northeurope
SubscriptionId    : 8cfb8b62-bcd6-4713-89ad-18097f75cc5b
Properties        : @{databaseName=cdb15000; creationDate=2018-08-03T08:51:39.463Z; deletionDate=2018-08-21T15:16:11.887Z}
...



PS C:\Users\dejandu> Get-AzureRmResource -ResourceId "/subscriptions/8cfb8b62-bcd6-4713-89ad-18097f75cc5b/resourceGroups/clperftesting_sneu_rg/providers/Microsoft.Sql/managedInstances/stlazitest/restorableDroppedDatabases/cdb15000,131793381718870000" -ApiVersion 2017-03-
01-preview


Name              : cdb15000,131793381718870000
ResourceId        : /subscriptions/8cfb8b62-bcd6-4713-89ad-18097f75cc5b/resourceGroups/clperftesting_sneu_rg/providers/Microsoft.Sql/managedInstances/stlazitest/restorableDroppedDatabases/cdb15000,131793381718870000
ResourceName      : stlazitest/cdb15000,131793381718870000
ResourceType      : Microsoft.Sql/managedInstances/restorableDroppedDatabases
ResourceGroupName : clperftesting_sneu_rg
Location          : northeurope
SubscriptionId    : 8cfb8b62-bcd6-4713-89ad-18097f75cc5b
Properties        : @{databaseName=cdb15000; creationDate=2018-08-03T08:51:39.463Z; deletionDate=2018-08-21T15:16:11.887Z}

**Comment by dejandundjerski** [comment]
This api is expected to land on Canary on 8/23 + two weeks for whole production

**Comment by dejandundjerski** [comment]
@anuchandy , @ravbhatnagar - what should be my next step with this request?

**Comment by dejandundjerski** [comment]
API has landed on canary, pilot and initial. Remaining on heavy and geo1 and geo2 regions.

**Comment by dejandundjerski** [comment]
@anuchandy , @ravbhatnagar - are we fine now to do the merge? thanks in advance, Dejan

**Comment by dejandundjerski** [comment]
@anuchandy , @ravbhatnagar , folks are we good to proceed with merge now? Thanks in advance, Dejan

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
@dejandundjerski merging this. you can update the readme when you are ready to release the SDK 
cc. @jaredmoo

**Pull request merged**
