### PR TITLE
[Hub Generated] Review request for Microsoft.KeyVault to update key permissions for 2021-06-01-preview.

### PR DESCRIPTION
**Pull request by adarce**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/adarce/azure-rest-api-specs/dev-keyvault-Microsoft.KeyVault-2019-09-01...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [x] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
**ETA: 2021-10-27**

  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
End of October, or early November.

  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [x] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zhenglaizhang** [comment]
@jianyexi could you help take a look at the breaking change failure, looks like unexpected and looks hard to undestand

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE could you help take a look at the breaking change failure, looks like unexpected and looks hard to undestand

Approved, as it's caused by existing conflict among the swaggers in the folder: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01

**Review by heaths — COMMENTED** [review]
Are those values actually supported with those api-versions, though? Anyone generating code could send those, and if not that would be a breaking change. It's generally not a good practice to backport changes. Was this to fix some actual problem?

**Comment by jlichwa** [comment]
@heaths  I have similar concerns. We should not backport changes even for extensible enums.

**Comment by adarce** [comment]
> Are those values actually supported with those api-versions, though? Anyone generating code could send those, and if not that would be a breaking change. It's generally not a good practice to backport changes. Was this to fix some actual problem?
>
> I have similar concerns. We should not backport changes even for extensible enums. But is seems like that happen for soft-delete purge permissions - I don't think that was right thing to do. From Dev Experience that could be confusing when they point to specific version.

Currently, the AKV service supports the same set of permissions across all API versions (and this PR was an attempt to fix this discrepancy). For context, back when AKV added permissions for purge/recover, the concern was potential data loss for customers using older clients. For example, consider a vault that is initially created with PurgeKey permission via the latest client, and then the customer happens to use an older client to add a GetKey permission. When parsing the GetVault response from the server, the older client would ignore the PurgeKey permission (since the older API version doesn't recognize the new value). After updating the list of key permissions in-memory, the older client would then submit a PUT request to the server that would completely replace all permissions (so it would add GetKey, but unintentionally remove PurgeKey).

One option here is to keep the ApiVersion-agnostic behaviour in the service (so that all API versions continue to support all permissions), but only update the latest API versions in this Swagger spec PR. Customers using SDKs are unlikely to notice the discrepancy (since by default SDKs only use the latest ApiVersion), but we could document the discrepancy for customers who are directly using REST APIs. @heaths and @jlichwa : What do you think?

**Comment by heaths** [comment]
That scenario is still problematic if the client doesn't regenerate their client library, thus the service needs to handle that. This is also why all request/response enums should be marked `modelAsString: true` in swagger and clients should respect that, or they cause their own data loss.

See https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#enums--sdks-client-libraries and https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#use-extensible-enums

**Comment by adarce** [comment]
> That scenario is still problematic if the client doesn't regenerate their client library, thus the service needs to handle that. This is also why all request/response enums should be marked `modelAsString: true` in swagger and clients should respect that, or they cause their own data loss.
> 
> See https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#enums--sdks-client-libraries and https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#use-extensible-enums

Got it. I've updated my PR so that it only updates the most recent preview API version.

**Review by jlichwa — APPROVED** [review]

**Comment by adarce** [comment]
@zhenglaizhang : Given that all concerns have been addressed, could you merge this PR please?

**Comment by heaths** [comment]
Adding @lmazuel who can merge with (expected) validation errors.

**Comment by heaths** [comment]
Never mind, @lmazuel. It wasn't a required check so I could.

**Pull request merged**
