### PR TITLE
remove unnecessary bool enums

### PR DESCRIPTION
**Pull request by iscai-msft**
no point in having these bool enums, also causing issues in generated code

see https://github.com/Azure/autorest.python/issues/847 for generated code issue

### CODE REVIEW

**Review by 00Kai0 — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]

**Review by leniatgh — COMMENTED** [review]
@iscai-msft We do have a LintRule [R3018 EnumInsteadOfBoolean](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3018-enuminsteadofboolean) to encourage defining boolean as enum.

**Comment by iscai-msft** [comment]
interesting @leni-msft, wasn't aware of that. However, the rule does state that you should only make it an enum if there will be more than 2 values possible. Since this is just `true` or `false`, we should stick to `type: boolean`.

```
the intent is to consider if there could be more than 2 values possible for the property in the future or not. If the answer is no, then a boolean is fine
```

**Comment by jsntcy** [comment]
@NarayanThiru, please help review the changes for `Kubernetesconfiguration`.
@roytan-microsoft, please help review the changes for `MixedReality`.

**Comment by NarayanThiru** [comment]
Hey @iscai-msft, why this change must be made now?  I don't understand what tool/process is breaking/broken and why it cannot handle enums - can you explain?

Since this is a breaking change, do I own the breaking change process to get this approved?  We have our GA release in <2 months and are focused on that - so I cannot take up any additional work.  Actually, can this wait for a few weeks?  Asking, since I will be creating a new api-version for GA - end of Jan/early Feb, and can include this change as part of that.

**Comment by roytan-microsoft** [comment]
@iscai-msft I have already made changes to those files in these commits:

https://github.com/Azure/azure-rest-api-specs/commit/19bb2801da4a2d167c74335ad0b84ae3a3ac8a18
https://github.com/Azure/azure-rest-api-specs/commit/4844fe08bfd144edbb52ecb8ae56b687ed578b74

**Comment by iscai-msft** [comment]
@NarayanThiru boolean enums do not work in python as a language, so Python code is broken here. It might also cause issues in other languages. 

@roytan-microsoft it looks lke your PRs don't contain fixes for `EnableHelmOperatorDefinition` in 2020-10-01 in kubernetes. Do you mind if I just go ahead with merging this PR since it's targeted to removing all bool enums?

**Review by NarayanThiru — APPROVED** [review]

**Comment by roytan-microsoft** [comment]
@iscai-msft EnableHelmOperatorDefinition is not under the MixedReality namespace. For the mixedreality change, it should be a noop for us, so I'm ok with that.

**Comment by iscai-msft** [comment]
@roytan-microsoft i'll remove the mixed reality code from this pr as you'll merge the code yourself. My apologies, I thought you also worked in the kubernetes namespace. thanks!

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
