### PR TITLE
[FaceAPI] Mark the user-defined name as mandatory when creating FaceL…

### PR DESCRIPTION
**Pull request by TFR258**
…ists

This should fix issue reported here: https://github.com/Azure/azure-sdk-for-net/issues/4594

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by TFR258** [comment]
Hi @lebronJ ,
Can you help review this change?

**Comment by zikalino** [comment]
@TRF258 This is not a right approach to mark the field as mandatory.
Pls check how Python SDK changes will look like:
https://github.com/Azure/azure-sdk-for-python/pull/7046/files
I have to do some checks and will get back to you with a suggestion of proper solution.

**Review by zikalino — APPROVED** [review]
we need to fix it

**Review by zikalino — CHANGES_REQUESTED** [review]
approved by mistake above -- implementation needs to be changed

**Comment by TFR258** [comment]
Hi @zikalino , Were you able to find any alternative for this change?

Thanks,
Tom

**Comment by TFR258** [comment]
Hi @zikalino , 

Any update on this PR?
Thanks,
Tom

**Review by yangyuan — APPROVED** [review]

**Pull request closed without merging**
