### PR TITLE
remove x-ms-azure-resource to have workspacwe/workspacepatch/datasour…

### PR DESCRIPTION
**Pull request by VeryEarly**
…ce properly inherited from parent class

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@ArcturusZhang @qiaozha @isra-fel  Could you please review this PR?

**Comment by ArcturusZhang** [comment]
Currently this RP does not have a config for go SDK consuming the impacted api-version, therefore I cannot tell whether this change has impacts to go SDK.

@VeryEarly could you please add a multiapi entry to the [readme.go.md](https://github.com/Azure/azure-rest-api-specs/blob/cdd2fe4016ac4eb2da8761f7df3e9775bb34bdb0/specification/operationalinsights/resource-manager/readme.go.md) file with this new tag `package-2020-03-preview`?

**Comment by VeryEarly** [comment]
> Currently this RP does not have a config for go SDK consuming the impacted api-version, therefore I cannot tell whether this change has impacts to go SDK.
> 
> @VeryEarly could you please add a multiapi entry to the [readme.go.md](https://github.com/Azure/azure-rest-api-specs/blob/cdd2fe4016ac4eb2da8761f7df3e9775bb34bdb0/specification/operationalinsights/resource-manager/readme.go.md) file with this new tag `package-2020-03-preview`?

done

**Comment by qiaozha** [comment]
> @ArcturusZhang @qiaozha @isra-fel Could you please review this PR?

Does the service want to onboard CLI ? what do you want from me?

**Review by isra-fel — APPROVED** [review]
LGTM

**Review by ArcturusZhang — APPROVED** [review]
LGTM

**Pull request merged**
