### PR TITLE
[Anomaly Detector] Rename operations and fix path casing

### PR DESCRIPTION
**Pull request by joheredi**
* Rename operations for client libraries
* Fix casing in changePoint path

### CODE REVIEW

**Comment by pakrym** [comment]
Partial duplicate of https://github.com/Azure/azure-rest-api-specs/pull/10546

**Review by conhua — APPROVED** [review]

**Comment by joheredi** [comment]
> Partial duplicate of #10546

Thanks @pakrym, is #10546 ready to merge? Once it is merged I'll rebase master

**Comment by pakrym** [comment]
>Thanks @pakrym, is #10546 ready to merge? Once it is merged I'll rebase master

It is but I'm not sure why the last CI check is not passing.

**Review by johanste — APPROVED** [review]
The changes look good. I did not verify that the renames were consistently applied - but my assumption is that the linter rules/validation would have caught any missing references that would need to be renamed.

**Comment by johanste** [comment]
The breaking changes are intentional and will only affect preview libraries.

**Review by conhua — APPROVED** [review]

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
