### PR TITLE
[Azure DevCenter] Update operation groups to improve SDK codegen

### PR DESCRIPTION
**Pull request by chrissmiller**
# Data Plane API - Pull Request
Updating operation grouping and specifying method location for SDK generation, based on guidance from the SDK Architecture Board. These updates do not impact any APIs, only operation groups and parameter location for one parameter to improve generated code. 

## API Info: The Basics
* Link to engagement record issue: N/A

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
- Updates to operation groups and parameter location for SDK generation
- Removing two $top parameters from GET APIs. These were mistakenly added, and our API has never supported $top for any GET APIs.

Updates to operation IDs are to group use-cases by client, per guidance from the SDK board.
Updates to ProjectNameParameter are to indicate that in one client this will be a method parameter, while on the other clients it will be a client parameter because those clients will not act across projects. Again, this will only impact codegen.
Updates to $top parameters are to reflect the actual support of the API and remove the parameter from generated code.

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by chrissmiller** [comment]
Hi @jhendrixMSFT , 

I've provided justification below for the changes. I'm not certain if this is a valid breaking change flag -- the removed top parameters were never valid/accepted by our service, since they are on GET operations, and the operation ID breaking change is for generated code, but we are basing/releasing our generated SDKs off of the new operation IDs from this PR, per request from the SDK board, so I don't see any potential customer impact from these changes. Please let me know if this requires filing an issue, and if the process is different given that we are in preview.

Justification:
- Top parameter removal: Both these top parameters are on GET operations. They were mistakenly included in the spec, and have never been accepted by our API. Our service has always ignored these parameters, so removal results in no change for customers, and use of the parameters is not a valid scenario (since the GET will always return 1 or 0 items). 
- Operation ID renaming: These changes were requested by the SDK Architecture board. They asked that we restructure our operation IDs to better follow convention and to group operations into logical client groupings, rather than grouping by resource to improve customer experience with languages that produce multiple clients (such as .NET). This spec will be used for our initial SDK releases, and we have not previously generated any code using the old spec (so there are no related breaking changes for Azure SDKs released by our service). 

We also have a linting issue from the new operation IDs. This is because with the clients encompassing multiple resources, so an operation ID such as `Environments_GetEnvironment` is required to explicitly show the resource being fetched, and distinguish it from other GETs on the same client such as `Environments_GetCatalogItem`. This is based off of the SDK architecture board guidance on naming. Please let me know if there is any issue here.

**Comment by weidongxu-microsoft** [comment]
None of the SDK is released, hence changing on "OperationId" should be fine (as long as SDK arch board is fine with their SDK).

However the removal of "top" parameter would require approval from Jeffrey. Please see https://github.com/Azure/azure-rest-api-specs/pull/21086#issuecomment-1276540988

**Comment by JeffreyRichter** [comment]
I can approve the breaking change about top since the nservice supported it. 
The problem here is that top gets documented and SDKs expose it. If top then gets removed, then customer code that tried to set opt is now broken. 
The service team MUST validate their swaggers better before we publish them to avoid these gratuitous breaking changes which impact docs, SDKs, and tools (PowerShell/CLI) - the ripple effect of these breaks is enormous.

**Review by weidongxu-microsoft — APPROVED** [review]
I think none of the SDK is released, all is in preparation and hence many changes to operationId. Chris could confirm.

Though MSDoc might indeed generated the doc from swagger.

**Comment by chrissmiller** [comment]
Thanks Jeffrey and Weidong -- confirming that none of the SDKs have been released yet (and all the ones in review are based off of this updated spec). We have taken this as an opportunity to improve our review process for our spec, and introduced some additional gates to pull requests with spec changes during spec development to prevent issues like the mistaken top param from being introduced into future API versions.

**Pull request merged**
