### PR TITLE
Service Bus: BYOK Bug Fix - added missing Identity in Create Namespace 

### PR DESCRIPTION
**Pull request by v-Ajnava**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by v-Ajnava** [comment]
We have added BYOK support in PR : https://github.com/Azure/azure-rest-api-specs/pull/10071, here the Create Namesapce - PUT call missed the Identity property. In PATCH operation Identity Property was updated in the previous PR. (10071)

**Comment by v-Ajnava** [comment]
@lirenhe , can you please review the PR. its fix for identity property missed in PR : https://github.com/Azure/azure-rest-api-specs/pull/10071. This is bug and BYOK will not work for CreateNamespace - PUT call, fix is in this PR.

**Review by markcowl — APPROVED** [review]

**Review by markcowl — CHANGES_REQUESTED** [review]
@v-Ajnava Is this a change in service behavior, or was the previous swagger incorrect?  Because this is a preview API, breaking changes would be allowed, but would require a new api-version in the case of a service behavior change.  If this is a correction, then I can approve the breaking change

**Comment by markcowl** [comment]
@v-Ajnava Please respond or will have to close this next week.

**Comment by v-Ajnava** [comment]
@markcowl , sorry for delay, This is correction for BYOK support in create namespace.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
