### PR TITLE
CSharp namespace for resource-manager, move data-plane API specs to resource-manager, remove UsageMetrics API from the spec

### PR DESCRIPTION
**Pull request by gucalder**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
Fixing issues
- #1837 fix cSharp namespace for resource-manager,
- #1838 : move data-plane API specs to resource-manager,
- #1839: remove UsageMetrics API from the spec

**Comment by sergey-shandar** [comment]
@ravbhatnagar 
- moving from data-plane to resource-manager
- changing namespace
- removing specs

**Comment by sergey-shandar** [comment]
@gucalder what is the migration plan and impact for our customers?

**Comment by sergey-shandar** [comment]
@shawns1 do you know why CI is not triggered for the PR?

**Comment by sergey-shandar** [comment]
For CI references https://github.com/Azure/azure-rest-api-specs/pull/1846

**Comment by shawns1** [comment]
@sergey-shandar CI seems to be working fine.  Travis ran the build.

**Comment by gucalder** [comment]
I am moving data-plane to resource-manager because some teams are generating SDKs for languages we do not handle (like Java,) and their work started with resource-manager only. Those teams assume that any call specified in the data-plane folder does not go through ARM, but in our case that is not true: all our calls go through ARM. So we are conveying an incorrect message by separating the calls into folders. Other than history there are not many reasons to keep the two folders separated.

In terms of impact the migration will remove one client. Until today we have two clients that are doing the same: calling our servers via ARM. Now there will be only one client with all the calls.
The calls themselves won't change.

**Comment by gucalder** [comment]
The other two changes, one is a bug, i.e.: incorrect namespace, visible only after the generation of code. It will impact the users of the SDK (.Net only,) but we cannot leave that value incorrect for that. BTW: our SDK .net is still in "preview" state, so this kind of changes are still possible.
The other change, i.e. deprecation of one API, has been announced for months already in PowerShell, and no one is using that API anymore.

**Comment by sergey-shandar** [comment]
@shawns1 thanks. It was not showing any CI in the PR and I couldn't find the job in Travis-CI. So I had to reopen the PR but it didn't help. It looks like magic.

**Comment by sergey-shandar** [comment]
@gucalder 
1. what is the migration plan and impact for our customers?
1. could you solve merge conflicts?

**Pull request closed without merging**
