### PR TITLE
netapp: removing the large integer validation

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Whilst this is helpful in some situations - this means that it's not
possible to build the NetApp SDK on 32 bit platforms

Fixes:

```
6 errors occurred:
--> freebsd/arm error: exit status 2
GNUmakefile:8: recipe for target 'compile' failed
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int

--> openbsd/386 error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int

--> linux/386 error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int

--> freebsd/386 error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int

--> linux/arm error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int

--> windows/386 error: exit status 2
Stderr: # github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/pools.go:72:87: constant 4398046511104 overflows int
vendor/github.com/Azure/azure-sdk-for-go/services/netapp/mgmt/2019-06-01/netapp/volumes.go:74:99: constant 107374182400 overflows int
```

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
I also submitted an [issue](https://github.com/Azure/autorest.go/issues/181) in `autorest.go` repo, since this may be a generator bug.

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff we have a [fix](https://github.com/Azure/autorest.go/pull/183) for this in autorest.go.
When that fix is applied, this issue should be resolved.

**Comment by tombuildsstuff** [comment]
@ArcturusZhang thanks that also works 👍 

From our side I've got broader questions around the validation within the CreateOrUpdate method - since I feel like it'd be more useful as an extension method on the struct itself - but that's a question for another day :)

For the moment I'll close this issue in favour of https://github.com/Azure/autorest.go/pull/183

Thanks!

**Pull request closed without merging**
