### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version stable/2023-06-01

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/dev-containerservice-Microsoft.ContainerService-2023-06-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by msyyc** [comment]
@FumingZhang There are so many breaking changes in [Python SDK for new api version](https://github.com/Azure/azure-rest-api-specs/pull/24581/checks?check_run_id=14544609688). Are  they expected?

**Comment by FumingZhang** [comment]
Hi @msyyc, it seems that the breaking change is about to have all models/operations exclusive to the preview API removed.

- The reasonable part is that starting from this API release, we will first merge the PR of the stable API, so the current python readme does not contain the tag of the 06 preview API.
- But the unreasonable part is that the python SDK supports multiple APIs, and the previous preview APIs are still included, so compared with the released version 24.0.0 (latest stable 05-01 (default), latest preview 05-02-preview), these two API versions are still included (I could confirm this with the draft PR), just add a new stable API 06-01 (new default).

I guess there is something wrong with the detection?

**Comment by msyyc** [comment]
> Operation ManagedClustersOperations.begin_delete no longer has parameter ignore_pod_disruption_budget

Some breaking like `Operation ManagedClustersOperations.begin_delete no longer has parameter ignore_pod_disruption_budget` is caused by comparing 2023-06-01 with 2023-05-02-preview. Maybe I could optimize changelog to make sure comparision between stable api-version. By the way, when will you add the parameter of preview api version to stable api version?

**Comment by FumingZhang** [comment]
> > Operation ManagedClustersOperations.begin_delete no longer has parameter ignore_pod_disruption_budget
> 
> Some breaking like `Operation ManagedClustersOperations.begin_delete no longer has parameter ignore_pod_disruption_budget` is caused by comparing 2023-06-01 with 2023-05-02-preview. Maybe I could optimize changelog to make sure comparision between stable api-version. By the way, when will you add the parameter of preview api version to stable api version?

I've updated the python readme to include preview API tag in a sibling branch [FumingZhang-containerservice-Microsoft.ContainerService-2023-06-02-preview](https://github.com/Azure/azure-rest-api-specs/tree/FumingZhang-containerservice-Microsoft.ContainerService-2023-06-02-preview). I'll rebase from main once this PR is merged to resolve the conflict on readme and have both stable (2023-06-01) and preview (2023-06-02-preview) API included.

**Comment by mentat9** [comment]
>           "type": "boolean",

Please consider moving to string enum for these kinds of properties. ARM review prefers enum over booleans for many reasons. Booleans are convenient for API developers, but enums are more convenient for API clients. You could use something similar to verticalPodScaleBehavior: { Auto, Manual }. Ref: [https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices](https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices).

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-06-01/managedClusters.json:6242 in f88cf2c. [](commit_id = f88cf2c76f497645634dafa7d14534f24c69aec7, deletion_comment = False)

**Comment by matthchr** [comment]
> > ```
> >       "type": "boolean",
> > ```
> 
> Please consider moving to string enum for these kinds of properties. ARM review prefers enum over booleans for many reasons. Booleans are convenient for API developers, but enums are more convenient for API clients. You could use something similar to verticalPodScaleBehavior: { Auto, Manual }. Ref: https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-06-01/managedClusters.json:6242 in [f88cf2c](https://github.com/Azure/azure-rest-api-specs/commit/f88cf2c76f497645634dafa7d14534f24c69aec7). [](commit_id = [f88cf2c](https://github.com/Azure/azure-rest-api-specs/commit/f88cf2c76f497645634dafa7d14534f24c69aec7), deletion_comment = False)

@mentat9 - AKS uses enabled booleans all over for enabling optional features (sometimes called Addons) and keeping this a boolean matches the pattern used in the rest of the API. Here are a few examples: [#1](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L4549), [#2](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5677), [#3](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5727).

We're in agreement that enum > boolean, but there is also value in consistency of user experience and we have a ton of this pattern elsewhere in the API and tend to value providing consistency of user experience even if it means that our ability to expand these values capabilities is reduced. In general (and you can see in this instance as well) these enabled flags are in a complex type, so if we needed to say expand and offer different modes, we can do so by adding an additional enum at that time: `enabled: true|false` and `mode: A|B`.

**Comment by mentat9** [comment]
> > > ```
> > >       "type": "boolean",
> > > ```
> > 
> > 
> > Please consider moving to string enum for these kinds of properties. ARM review prefers enum over booleans for many reasons. Booleans are convenient for API developers, but enums are more convenient for API clients. You could use something similar to verticalPodScaleBehavior: { Auto, Manual }. Ref: https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices.
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-06-01/managedClusters.json:6242 in [f88cf2c](https://github.com/Azure/azure-rest-api-specs/commit/f88cf2c76f497645634dafa7d14534f24c69aec7). [](commit_id = [f88cf2c](https://github.com/Azure/azure-rest-api-specs/commit/f88cf2c76f497645634dafa7d14534f24c69aec7), deletion_comment = False)
> 
> @mentat9 - AKS uses enabled booleans all over for enabling optional features (sometimes called Addons) and keeping this a boolean matches the pattern used in the rest of the API. Here are a few examples: [#1](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L4549), [#2](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5677), [#3](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5727).
> 
> We're in agreement that enum > boolean, but there is also value in consistency of user experience and we have a ton of this pattern elsewhere in the API and tend to value providing consistency of user experience even if it means that our ability to expand these values capabilities is reduced. In general (and you can see in this instance as well) these enabled flags are in a complex type, so if we needed to say expand and offer different modes, we can do so by adding an additional enum at that time: `enabled: true|false` and `mode: A|B`.

@matthchr - Thank-you for considering this request. Please keep the idea in mind for future evolution of your RPs APIs. I've signed off for ARM.

**Comment by FumingZhang** [comment]
Hey @rkmanda, the PR has been signed off by ARM, and there's no required CI failing. Does this mean it meets the bar to be merged? If so, I would like to submit the SDK release request first and keep it open until the service is ready. Please **DO NOT** merge the PR at this moment, thanks!

**Comment by FumingZhang** [comment]
The service is ready in public cloud, please help merge the PR ASAP @rkmanda

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
