### PR TITLE
Microsoft.data protection

### PR DESCRIPTION
**Pull request by mayankagg9722**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [x] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jorgecotillo** [comment]
>           "200": {

According to our RPC, async delete operations return either 204 or 200, as seen [here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously) what's the motivation to have 200 and 204 as responses ?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1042 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by mayankagg9722** [comment]
> > ```
> >       "200": {
> > ```
> 
> According to our RPC, async delete operations return either 204 or 200, as seen [here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously) what's the motivation to have 200 and 204 as responses ?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1042 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

Can you please elaborate what is wrong with this behavior? During "Sync" operations (resource is not provisioned) it can return 200 (if it is deleted) or 204 (if resource doesn't exist anymore) and for async operations (resource is provisioned) it can return 202 and delete can happen asynchronously. 
Please let us know if there is any issue with this?

**Comment by jorgecotillo** [comment]
> > > ```
> > >       "200": {
> > > ```
> > 
> > 
> > According to our RPC, async delete operations return either 204 or 200, as seen [here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously) what's the motivation to have 200 and 204 as responses ?
> > Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1042 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)
> 
> Can you please elaborate what is wrong with this behavior? During "Sync" operations (resource is not provisioned) it can return 200 (if it is deleted) or 204 (if resource doesn't exist anymore) and for async operations (resource is provisioned) it can return 202 and delete can happen asynchronously.
> Please let us know if there is any issue with this?

I guess you meant to say returns 200 if the resource is being deleted right? which means when the delete operation is happening your provisioningState goes into a non-terminal state like "Deleting" and once is deleted the call returns 204, is this what your service is doing? If yes, then what you have is ok, just making sure

**Comment by mayankagg9722** [comment]
> > > > ```
> > > >       "200": {
> > > > ```
> > > 
> > > 
> > > According to our RPC, async delete operations return either 204 or 200, as seen [here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously) what's the motivation to have 200 and 204 as responses ?
> > > Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1042 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)
> > 
> > 
> > Can you please elaborate what is wrong with this behavior? During "Sync" operations (resource is not provisioned) it can return 200 (if it is deleted) or 204 (if resource doesn't exist anymore) and for async operations (resource is provisioned) it can return 202 and delete can happen asynchronously.
> > Please let us know if there is any issue with this?
> 
> I guess you meant to say returns 200 if the resource is being deleted right? which means when the delete operation is happening your provisioningState goes into a non-terminal state like "Deleting" and once is deleted the call returns 204, is this what your service is doing? If yes, then what you have is ok, just making sure

**Current behavior:** 
1) We are sending 202 with location header and not changing the provisioning state. 
2) We are sending 204 in case if resource is already deleted (instead of 404). As this is a success/valid scenario.

Can you confirm verify that in case of deletion, should we update provisioning state and send 200 status code with location header OR not update provisioning state and send 202 with location header?

**Comment by jorgecotillo** [comment]
@mayankagg9722 For delete async operations follow the RPC doc I mentioned previously:

https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#delete-resource-asynchronously

It explains what are the appropriate responses, it seems like in your case you are returning 202 (Accepted) then 204 (NoContent), but your swagger shows 200 and 204, please update your async call responses according to our RPC.

**Comment by jorgecotillo** [comment]
>           "202": {

A get call returns 200 OK response, please see [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#get-resource) 202 and 201 are usually referenced on long running operations) and [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-resource-format)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:94 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>           "202": {

Same as above, no async calls on Gets

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:459 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>         "operationCategory": {

If this is a well-known set of values. model them as enum instead.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1948 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>         "restoreType": {

Please revisit all your properties and make sure to model as enum those with a well-known set of values.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1971 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>           "202": {

also you do not need swagger for urls that are only returned as Location/Azure-AsyncOperation headers

---
In reply to: [775401622](https://github.com/Azure/azure-rest-api-specs/pull/12814#issuecomment-775401622) [](ancestors = 775401622)

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:94 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "/subscriptions/{subscriptionId}/providers/Microsoft.DataProtection/locations/{location}/operationStatus/{operationId}": {

why do you need operationStatus and operationResults?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:115 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/operationResults/{operationId}": {

you should unify all your async operation gets under 1 resource type - usually locations/operationResults or similar

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:423 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>               "$ref": "#/definitions/BackupVaultResource"

if you decide to keep and document this url - it should not return a BackupVaultResource, but as OperationResource

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:456 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>               "Location": {

you don't need both Location and Azure-AsyncOperation, just one

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1024 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupJobsExport": {

exportBackupJobs

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1656 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>             "$ref": "#/parameters/VaultName"

there is no request body - how does the user specify where to export to?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1674 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "version": "2020-01-01-alpha",

should this be 2021-01-01-alpha? update examples too

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:4 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "identityUrl": {

I don't see this as a supported field in the identity schema in common-types or in the ARM code, are you sure this works?

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2971 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "CloudError": {

you should refer to this from common-types instead of defining your own

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2739 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>           "204": {

if you need a long running delete, you should have a 202 as well

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:350 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "FeatureValidationRequestBase": {

this and FeatureValidationResponseBase are identical, also I don't think you need to use discriminators for this scenario. I would suggest just having two different FeatureValidationRequest and FeatureValidationResponse schemas

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:3183 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>               "$ref": "#/definitions/ClientDiscoveryResponse"

use schema from common-types instead

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:604 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "DatasourceSet": {

this seems to be identical to "DataSource"

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2836 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "dataSourceSetInfo": {

remove - if this is same as above

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2332 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>         "resourceID": {

do you need all 5 resource properties? just id and location should be good enough right? you can derive the rest from the id. Also consider having the location as readonly, so it is set only by the service and not customers

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2809 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "UserFacingError": {

use the ErrorDetail from common-types if possible, and add more properties to it if required

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:4021 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by varunkumta** [comment]
>     "AzureBackupJob": {

this object has 27 properties - consider refactoring and grouping them into smaller objects eg - dataSource, operation, policy and progress related sub-objects

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1879 in abcd60d. [](commit_id = abcd60d9f0eae431796cdc770532a60639d43b0d, deletion_comment = False)

**Comment by mayankagg9722** [comment]
> get call returns 200 OK

We have fixed this now.

**Comment by mayankagg9722** [comment]
> > ```
> >       "202": {
> > ```
> 
> A get call returns 200 OK response, please see [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#get-resource) 202 and 201 are usually referenced on long running operations) and [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-resource-format)
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:94 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)



> > ```
> >       "202": {
> > ```
> 
> A get call returns 200 OK response, please see [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#get-resource) 202 and 201 are usually referenced on long running operations) and [this](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-resource-format)
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:94 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

this is now fixed

**Comment by mayankagg9722** [comment]
> > ```
> >       "202": {
> > ```
> 
> also you do not need swagger for urls that are only returned as Location/Azure-AsyncOperation headers
> 
> In reply to: [775401622](https://github.com/Azure/azure-rest-api-specs/pull/12814#issuecomment-775401622) [](ancestors = 775401622)
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:94 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

Thanks for the comment. But this is already reviewed in the private repo and if we do this change now our existing client may break.

**Comment by mayankagg9722** [comment]
> > ```
> > "AzureBackupJob": {
> > ```
> 
> this object has 27 properties - consider refactoring and grouping them into smaller objects eg - dataSource, operation, policy and progress related sub-objects
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1879 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

image


> > ```
> > "AzureBackupJob": {
> > ```
> 
> this object has 27 properties - consider refactoring and grouping them into smaller objects eg - dataSource, operation, policy and progress related sub-objects
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1879 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

Thanks but the same contract goes to LA(log analytics) where they expect same hierarchy.

**Comment by mayankagg9722** [comment]
> > ```
> > "UserFacingError": {
> > ```
> 
> use the ErrorDetail from common-types if possible, and add more properties to it if required
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:4021 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We wanted to keep it different as there are some scenarios where we might need to add different properties in future and this was done in private repo after review handling cases that might come in future.

**Comment by mayankagg9722** [comment]
> > ```
> >     "resourceID": {
> > ```
> 
> do you need all 5 resource properties? just id and location should be good enough right? you can derive the rest from the id. Also consider having the location as readonly, so it is set only by the service and not customers
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2809 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

These may or may not be ARM resources, so in those cases if it is non-ARM resource resource id will not resolve to other required information.

**Comment by mayankagg9722** [comment]
> > ```
> >     "dataSourceSetInfo": {
> > ```
> 
> remove - if this is same as above
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2332 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We wanted to keep it different as there are some scenarios where we might need to add different properties in future and this was done in private repo after review handling cases that might come in future.

**Comment by mayankagg9722** [comment]
> > ```
> >           "$ref": "#/definitions/ClientDiscoveryResponse"
> > ```
> 
> use schema from common-types instead
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:604 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We wanted to enhance this and keep it different as there are some scenarios where we might need to add different properties in future and this was done in private repo after review handling cases and also can break existing clients.

**Comment by mayankagg9722** [comment]
> > ```
> > "FeatureValidationRequestBase": {
> > ```
> 
> this and FeatureValidationResponseBase are identical, also I don't think you need to use discriminators for this scenario. I would suggest just having two different FeatureValidationRequest and FeatureValidationResponse schemas
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:3183 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We wanted to enhance this and keep it different as there are some scenarios where we might need to add different properties in future and this was done in private repo after review handling cases and also can break existing clients.

**Comment by mayankagg9722** [comment]
> > ```
> > "CloudError": {
> > ```
> 
> you should refer to this from common-types instead of defining your own
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:2739 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We wanted to enhance this and keep it different as there are some scenarios where we might need to add different properties in future and this was done in private repo after review handling cases and also can break existing clients.

**Comment by mayankagg9722** [comment]
> /VaultNa

We are returning a downloadable file.

**Comment by mayankagg9722** [comment]
> > ```
> >           "Location": {
> > ```
> 
> you don't need both Location and Azure-AsyncOperation, just one
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:1024 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

We need to have both to support our old clients and this was already reviewed in private repo and may break our clients now.

**Comment by mayankagg9722** [comment]
> > ```
> >           "$ref": "#/definitions/BackupVaultResource"
> > ```
> 
> if you decide to keep and document this url - it should not return a BackupVaultResource, but as OperationResource
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:456 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

OperationResource is returning operation status and for this operation result object is returned as it was a sync call

**Comment by mayankagg9722** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/operationResults/{operationId}": {
> > ```
> 
> you should unify all your async operation gets under 1 resource type - usually locations/operationResults or similar
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:423 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

There are different bodies for operation result and we wont be able to return different objects with the same payload and it will lead to polymorphism. So, we have to keep it different.

**Comment by mayankagg9722** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/providers/Microsoft.DataProtection/locations/{location}/operationStatus/{operationId}": {
> > ```
> 
> why do you need operationStatus and operationResults?
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2020-01-01-alpha/dataprotection.json:115 in [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d). [](commit_id = [abcd60d](https://github.com/Azure/azure-rest-api-specs/commit/abcd60d9f0eae431796cdc770532a60639d43b0d), deletion_comment = False)

Operationresult is used for old clients and operationstatus is used portal and this was already reviewed in private repo and may break existing clients

**Comment by mayankagg9722** [comment]
I have made all other changes for other comments you put, please review it once.

**Comment by varunkumta** [comment]
can you please specify which apis/models have not been reviewed before or have changed since the last review - so I can focus on those

**Comment by mayankagg9722** [comment]
> can you please specify which apis/models have not been reviewed before or have changed since the last review - so I can focus on those

I have only made the changes for API version and to fix the comments you mentioned above. So, please take a look for the fixes of the APIs mentioned in the comments as those are the only ones which got changed.

**Comment by akning-ms** [comment]
Based on talk with Sumit as below, I will force merge this PR in branch first to unblock

[1:05 PM] Sumit Malhotra (BACKUP)
    GO SDK is an issue we were tracking....
    since this is in our branch 
    we will raise a seperate PR when all our changes are merged here
    and ready to ship SDK to master branch 
    before that we will get that fixed 
    we are not planning to ship any sdk out of this ... we need to get the .net sdk and powershell ready and hence wanted to merge these  
    so we can have a baseline and other developers can get their apis reviewed on top of baseline
    after all changes are done, we will go to master branch and will fix the GO sdk issues 

@allenjzhang  for awareness

**Pull request merged**
