### PR TITLE
Microsoft.NetworkCloud 2024-06-01-preview for public

### PR DESCRIPTION
**Pull request by bryan-strassner**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by bryan-strassner** [comment]
Private azure-rest-api-specs-pr related PRs:
This version (2024-06-01-preview):

https://github.com/Azure/azure-rest-api-specs-pr/pull/18537

Intermediate private preview versions:
(2024-05-01-preview):
https://github.com/Azure/azure-rest-api-specs-pr/pull/18113
(2024-03-01-preview):
https://github.com/Azure/azure-rest-api-specs-pr/pull/17224
(2023-12-01-preview):
https://github.com/Azure/azure-rest-api-specs-pr/pull/16516,
https://github.com/Azure/azure-rest-api-specs-pr/pull/16856,
https://github.com/Azure/azure-rest-api-specs-pr/pull/17104

**Comment by ramoka178** [comment]
>           "final-state-schema": "#/definitions/OperationStatusResult",

the version present here is the same as common types in v5 and is present in the previous apiversion.
Why not keep the same  ?

Same in other places where it change from previous api version.

---
Refers to: specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2024-06-01-preview/networkcloud.json:758 in 41af73d. [](commit_id = 41af73df7a7627aa100c4f618c11a72989bc4bcd, deletion_comment = False)

**Comment by ramoka178** [comment]
>           "description": "The remaining appliance-based storage in GB available for workload use. Measured in gibibytes.",

this is GiB right? . property name having GB will be confusing to Customers as name is suggesting its in gigabytes.

Same in other places where gibibytes are being expected, but the name has GB in it .

---
Refers to: specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2024-06-01-preview/networkcloud.json:8215 in 41af73d. [](commit_id = 41af73df7a7627aa100c4f618c11a72989bc4bcd, deletion_comment = False)

**Comment by bryan-strassner** [comment]
> present here is the same as common types in v5 and is present in the previous apiversion.

The version here includes additional properties that are not present on the common version, and shifts all async operations to use the extended version.  Because of SDK/CLI build considerations, and the need to expose the new properties, the common version is insufficient.  Please see discussion on the private repo PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/18537

**Comment by bryan-strassner** [comment]
> > ```
> >       "description": "The remaining appliance-based storage in GB available for workload use. Measured in gibibytes.",
> > ```
> 
> this is GiB right? . property name having GB will be confusing to Customers as name is suggesting its in gigabytes.
> 
> Same in other places where gibibytes are being expected, but the name has GB in it .
> 
> Refers to: specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2024-06-01-preview/networkcloud.json:8215 in [41af73d](https://github.com/Azure/azure-rest-api-specs/commit/41af73df7a7627aa100c4f618c11a72989bc4bcd). [](commit_id = [41af73d](https://github.com/Azure/azure-rest-api-specs/commit/41af73df7a7627aa100c4f618c11a72989bc4bcd), deletion_comment = False)

This change was made along the way in our private api changes. The use of the description to be specific is the compromise that we made, to minimize the breaking change. 

Prior approved PRs for reference:
[Microsoft.NetworkCloud 2024-06-01-preview by bryan-strassner · Pull Request #18537 · Azure/azure-rest-api-specs-pr (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F18537&data=05%7C02%7Cbstrassner%40microsoft.com%7Cf2682bb3d43a432e8d1408dc95321317%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549289523938449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BbPua%2FytP4MJtmkIWah17Owc0CXY%2BcymgfnL8FaMxTs%3D&reserved=0)
[Microsoft.NetworkCloud 2024-05-01-preview version by bryan-strassner · Pull Request #18113 · Azure/azure-rest-api-specs-pr (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F18113&data=05%7C02%7Cbstrassner%40microsoft.com%7Cf2682bb3d43a432e8d1408dc95321317%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549289523943801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=oeNPI8RlC1HVhFRXE%2BxwOuJV6ScBYin%2BbDIc3MfdAxM%3D&reserved=0)
[[Microsoft.NetworkCloud] 2024-03-01-preview by bryan-strassner · Pull Request #17224 · Azure/azure-rest-api-specs-pr (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F17224&data=05%7C02%7Cbstrassner%40microsoft.com%7Cf2682bb3d43a432e8d1408dc95321317%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549289523949197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=iJ8x7eRY%2FFLrCsbYXnVSe%2FuFEY1uPfflhWi4mfIfn%2FA%3D&reserved=0)
[Microsoft.NetworkCloud introduction of 2023-12-01-preview API changes by bryan-strassner · Pull Request #16516 · Azure/azure-rest-api-specs-pr (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F16516&data=05%7C02%7Cbstrassner%40microsoft.com%7Cf2682bb3d43a432e8d1408dc95321317%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549289523954673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xbKWqbEHlfNzAuLD%2FRm8ry%2Bk5%2Ba73S1GeVeFD6spaQY%3D&reserved=0)
[Microsoft.NetworkCloud 2023-10-01-preview API Introduction by bryan-strassner · Pull Request #14822 · Azure/azure-rest-api-specs-pr (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F14822&data=05%7C02%7Cbstrassner%40microsoft.com%7Cf2682bb3d43a432e8d1408dc95321317%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549289523960092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=7eBlL0OrZZnGXos3NZeNeFmLZ8T%2F7ahvxV%2FaO%2FkxL4A%3D&reserved=0)

**Comment by bryan-strassner** [comment]
This approved PR is being held for merging until software releases are in place to properly support it ~ 2024-08-20

**Review by mbashtovaya — APPROVED** [review]

**Review by priyamshet — APPROVED** [review]

**Pull request merged**
