### PR TITLE
[Hub Generated] Review request for Microsoft.SecurityInsights to remove unused endpoints under Settings

### PR DESCRIPTION
**Pull request by laithhisham**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/laithhisham/azure-rest-api-specs/removeUnusedOnboardingEndpoints...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify - **fixing swagger - removing unused endpoints which where recently added due to design change. These endpoints are not used by customers.**
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet. **ASAP - no date since it is not a new feature**
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. **ASAP**
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable or public preview version with Breaking Change Validation errors - **Removing newly added endpoints due to design change. These endpoints are not used yet so no impact is expected to customers.**
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by laithhisham** [comment]
@ArcturusZhang 
This PR is removing newly added endpoints due to design change (the settings/onboard and settings/offboard endpoints). 
These endpoints are not used yet so no impact is expected to customers. These endpoints are being replaced with a completely new resource type instead.

We verified the traffic in ARM logs to make sure that these endpoints are not reached and they indeed are.
The only request there is a test one we did at the early stages of deployment (notice that it is to one of our test workspaces contoso55).

https://armprod.kusto.windows.net/ARMProd?query=H4sIAAAAAAAEAG2QT0sDMRTE74Lf4ZFTK62k9SZUkLK2OewfNulBL5LuvnZzSFJf3qqIH961ggsizG1%2bMwyzZT6p0ETvwrHGlx4Tp8uLT3jrkBCMyjNt7vMK7qC1jOw8TpZyuZjLm7lcGClvz3qajhm2dESuMcWeGqwovroWCVYrELla16UuH8y1zta7WplHVWi12RotYCzohkk5chfbc6gqtRGjG09Ill0MhfUDaxMInRmjio0Wf0fsyEETA1sXBiyGfbTUCoj0v384%2fADfNan33pL7QBjIZ2%2ffJ79fzOBq%2bgUoG0VhNwEAAA%3d%3d&web=0

HttpIncomingRequests
| where TIMESTAMP > datetime(2021-03-01T00:00:00Z)
| where targetResourceProvider == "MICROSOFT.SECURITYINSIGHTS" 
| where httpMethod == "POST"
| where operationName has "SETTINGS"
| where targetUri contains "onboard" or targetUri contains "offboard"
| summarize arg_max(TIMESTAMP, *)

TIMESTAMP | PreciseTimeStamp | Deployment | Role | RoleInstance | Level | ProviderGuid | ProviderName | EventId | Pid | Tid | TaskName | ActivityId | subscriptionId | correlationId | principalOid | principalPuid | tenantId | authorizationSource | authorizationAction | operationName | httpMethod | hostName | targetUri | userAgent | clientRequestId | clientSessionId | clientIpAddress | clientApplicationId | apiVersion | contentLength | serviceRequestId | durationInMilliseconds | httpStatusCode | exceptionMessage | errorCode | failureCause | errorMessage | RowKey | SourceNamespace | SourceMoniker | SourceVersion | referer | commandName | parameterSetName | contentType | contentEncoding | armServiceRequestId | organizationId | activityVector | locale | realPuid | altSecId | additionalProperties | targetResourceProvider | targetResourceType | RoleLocation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2021-04-05 06:27:41.2860752 | 2021-04-05 06:27:41.2860752 | 63e1d6d1e71c4dd1b306ce2eb74f54c8 | Frontdoor.Web.razzle | Frontdoor.Web.razzle_IN_1 | 4 | 6a309439-9c04-49f6-b5cf-9a8e78d56b11 | Microsoft-WindowsAzure-Frontdoor | 33 | 20252 | 18548 | HttpIncomingRequestEndWithClientFailure | 43118953-2667-4c71-9226-b40b3528ac68 | 3c1bb38c-82e3-4f8d-a115-a7110ba70d05 | 43118953-2667-4c71-9226-b40b3528ac68 | 3a8ab325-b2e0-4131-8919-0133f0d9e9c9 | 100320003588F670 | 72f988bf-86f1-41af-91ab-2d7cd011db47 | RoleBased | Microsoft.SecurityInsights/settings/action | POST/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.OPERATIONALINSIGHTS/WORKSPACES/PROVIDERS/MICROSOFT.SECURITYINSIGHTS/SETTINGS/ | POST | management.azure.com | https://management.azure.com:443/subscriptions/3c1bb38c-82e3-4f8d-a115-a7110ba70d05/resourceGroups/contoso55-eus/providers/Microsoft.OperationalInsights/workspaces/contoso55/providers/Microsoft.SecurityInsights/settings/onboard?api-version=2021-03-01-preview | PostmanRuntime/7.26.10 |   |   | 89.139.104.72 | c44b4083-3bb0-49c1-b47d-974e53cbdf3c | 2021-03-01-preview | 114 | 43118953-2667-4c71-9226-b40b3528ac68 | 1942 | 412 |   |   |   |   |   | csmFranceSouthRPF | MdsResourceStackRPFFranceSouth | Ver23v0 | <null> |   |   | application/json; charset=utf-8 |   | f5fc3c8a-78e9-49fe-88c8-e041d819b371 |   | IN |   | 100320003588F670 |   | {"x-ms-open-telemetry-activity-id":"00-2ff1b405b3f7ba4a81c90d770ec7a91b-1ffdc8e06a8b1b4a-01","x-ms-open-telemetry-trace-state":"","x-ms-home-tenant-id":"72f988bf-86f1-41af-91ab-2d7cd011db47","x-ms-tls-version":"Tls12","authorization-action-bag":"{\"primaryAction\":\"Microsoft.SecurityInsights/settings/action\"}"} | MICROSOFT.SECURITYINSIGHTS | SETTINGS | France South

**Comment by filizt** [comment]
@laithhisham the process requires that any breaking change go through the breaking change approval process described here: https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes?anchor=process. After the breaking change approval ARM review board will review the API changes.

**Comment by laithhisham** [comment]
> @laithhisham the process requires that any breaking change go through the breaking change approval process described here: https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes?anchor=process. After the breaking change approval ARM review board will review the API changes.

@filizt Thanks for letting me know. Done, here's the WI: https://msazure.visualstudio.com/One/_workitems/edit/9963295
I thought it might be not required since it is a new feature which is still not used at all by customers so no customer impact is expected.

**Comment by filizt** [comment]
Changelog states that the paths being deleted are not being used by customers. Signing off from ARM side.

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
