### PR TITLE
[Hub Generated] Review request for Microsoft.ConnectedVMwarevSphere to add version preview/2023-03-01-preview

### PR DESCRIPTION
**Pull request by aronip**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/aronip-connectedvmware-Microsoft.ConnectedVMwarevSphere-2023-03-01-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [public repo review queue], [private repo review queue]  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue]  

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[public repo review queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AWaitForARMFeedback+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[private repo review queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AWaitForARMFeedback+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AIDCDevDiv+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by aronip** [comment]
For the below lintDiff errors:

<html>
<body>


Rule | Message | Related RPC [For API reviewers]
-- | -- | --
❌ GetCollectionOnlyHasValueAndNextLink | Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224 |  
❌ LroPostReturn | 200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4403 | RPC-Post-V1-03
❌ LroPostReturn | 200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4460 | RPC-Post-V1-03
❌ LroPostReturn | 200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4506 | RPC-Post-V1-03
❌ GetCollectionOnlyHasValueAndNextLink | Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578 |  
❌ GetCollectionOnlyHasValueAndNextLink | Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720 |  
❌ TopLevelResourcesListBySubscription | The top-level resource 'VirtualMachineInstance' does not have list by subscription operation, please add it.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L6093 | RPC-Get-V1-05

- **GetCollectionOnlyHasValueAndNextLink**
This looks like a false positive. This is getting flagged for GET of extension resources here instead of LIST calls.
[Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224)
[Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578)
[Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720)

- **LroPostReturn**
The VM Start/Stop/Restart actions don't return any response body with 200 HTTP code. This is consistent with [Azure Compute VMs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json#L1311) as well. In fact, since all these actions are long running operations, 200 OK is never returned for these and we always trigger a LRO and return 202.

- **TopLevelResourcesListBySubscription**
Since VirtualMachineInstance is an ARM extension resource and not a top-level tracked resource, we have not added the List by Subscription call. Users can List VirtualMachineInstance resources at the parent resource level scope as per the below API:
https://github.com/Azure/azure-rest-api-specs/blob/aronip-connectedvmware-Microsoft.ConnectedVMwarevSphere-2023-03-01-preview/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4362

**Comment by ms-zhenhua** [comment]
>           },

LRO-Delete should define 202 and 204 only.
Refer to: [https://github.com/Azure/typespec-azure/issues/3167](https://github.com/Azure/typespec-azure/issues/3167)

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4337 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>       "get": {

Always add x-ms-pageable to LIST calls:
[https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi009-always-add-x-ms-pageable-to-list-calls](https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi009-always-add-x-ms-pageable-to-list-calls)

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4363 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           },

remove 200 or add schema:
[https://github.com/Azure/typespec-azure/issues/3167](https://github.com/Azure/typespec-azure/issues/3167)

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4437 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           },

remove 200 or add schema:
[https://github.com/Azure/typespec-azure/issues/3167](https://github.com/Azure/typespec-azure/issues/3167)

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4529 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           },

LRO-Delete should define 202 and 204 only.
Refer to: [https://github.com/Azure/typespec-azure/issues/3167](https://github.com/Azure/typespec-azure/issues/3167)

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4758 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "x-ms-identifiers": []

please follow [http://azure.github.io/autorest/extensions/#x-ms-identifiers](http://azure.github.io/autorest/extensions/#x-ms-identifiers) to add identifying properties

---
Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4950 in a7b6b3f. [](commit_id = a7b6b3fc36ef53bc96d9b3184a2511e143371bd0, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
> For the below lintDiff errors:
> 
> Rule	Message	Related RPC [For API reviewers]
> ❌ GetCollectionOnlyHasValueAndNextLink	Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224	 
> ❌ LroPostReturn	200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4403	RPC-Post-V1-03
> ❌ LroPostReturn	200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4460	RPC-Post-V1-03
> ❌ LroPostReturn	200 response for a LRO POST operation must have a response schema specified.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4506	RPC-Post-V1-03
> ❌ GetCollectionOnlyHasValueAndNextLink	Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578	 
> ❌ GetCollectionOnlyHasValueAndNextLink	Get endpoints for collections of resources must only have the value and nextLink properties in their model.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720	 
> ❌ TopLevelResourcesListBySubscription	The top-level resource 'VirtualMachineInstance' does not have list by subscription operation, please add it.Location: Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L6093	RPC-Get-V1-05
> * **GetCollectionOnlyHasValueAndNextLink**
>   This looks like a false positive. This is getting flagged for GET of extension resources here instead of LIST calls.
>   [Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4224)
>   [Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4578)
>   [Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720](https://github.com/Azure/azure-rest-api-specs/blob/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4720)
> * **LroPostReturn**
>   The VM Start/Stop/Restart actions don't return any response body with 200 HTTP code. This is consistent with [Azure Compute VMs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json#L1311) as well. In fact, since all these actions are long running operations, 200 OK is never returned for these and we always trigger a LRO and return 202.
> * **TopLevelResourcesListBySubscription**
>   Since VirtualMachineInstance is an ARM extension resource and not a top-level tracked resource, we have not added the List by Subscription call. Users can List VirtualMachineInstance resources at the parent resource level scope as per the below API:
>   https://github.com/Azure/azure-rest-api-specs/blob/aronip-connectedvmware-Microsoft.ConnectedVMwarevSphere-2023-03-01-preview/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json#L4362

Please follow  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process to suppress `GetCollectionOnlyHasValueAndNextLink `and `TopLevelResourcesListBySubscription`. For `LroPostReturn`, please add schema to 200, or remove 200.

**Comment by aronip** [comment]
> > ```
> >       },
> > ```
> 
> 
> remove 200 or add schema:
> [Azure/typespec-azure#3167](https://github.com/Azure/typespec-azure/issues/3167)
> 
> 
> 
> Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4529 in [a7b6b3f](https://github.com/Azure/azure-rest-api-specs/commit/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0). [](commit_id = [a7b6b3f](https://github.com/Azure/azure-rest-api-specs/commit/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0), deletion_comment = False)

@ms-zhenhua
I had tried removing 200 from LRO POST response, but that also leads to a failure of the LintDiff check. Let me know if we can ignore this failure and still remove 200.
https://github.com/Azure/azure-rest-api-specs/pull/25147/checks?check_run_id=15665484737

image

**Comment by ms-zhenhua** [comment]
> > > ```
> > >       },
> > > ```
> > 
> > 
> > remove 200 or add schema:
> > [Azure/typespec-azure#3167](https://github.com/Azure/typespec-azure/issues/3167)
> > Refers to: specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2023-03-01-preview/connectedvmware.json:4529 in [a7b6b3f](https://github.com/Azure/azure-rest-api-specs/commit/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0). [](commit_id = [a7b6b3f](https://github.com/Azure/azure-rest-api-specs/commit/a7b6b3fc36ef53bc96d9b3184a2511e143371bd0), deletion_comment = False)
> 
> @ms-zhenhua I had tried removing 200 from LRO POST response, but that also leads to a failure of the LintDiff check. Let me know if we can ignore this failure and still remove 200. https://github.com/Azure/azure-rest-api-specs/pull/25147/checks?check_run_id=15665484737
> 
> image

Hi @aronip, please remove 200 and also suppress this error. We will review the suppression. Thanks.

**Comment by kazrael2119** [comment]
this js breaking is caused by this pr

**Comment by aronip** [comment]
> this js breaking is caused by this pr

@kazrael2119 Our SDKs are not yet publicly available for customers. We should be ok with the breaking change here.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
