### PR TITLE
Dev machinelearningservices 2019 11 01 - Base API version update

### PR DESCRIPTION
**Pull request by vrushg-ms**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ravbhatnagar** [comment]
@vrushg-ms - have all the changed been made? It just looks like that api-version string has changed, From our conversation in office hours you mentioned adding more compute types. Have those changes been added?

**Comment by vrushg-ms** [comment]
@ravbhatnagar , My changes are in a different PR and I cannot merge that PR before November because it contains Ignite features. One of my team members need the version update ASAP. That is why we are coordinating on version update first and then merging the Ignite features a month later.

**Comment by vrushg-ms** [comment]
> @vrushg-ms - have all the changed been made? It just looks like that api-version string has changed, From our conversation in office hours you mentioned adding more compute types. Have those changes been added?

@ravbhatnagar , My changes are in a different PR and I cannot merge that PR before November because it contains Ignite features. One of my team members need the version update ASAP. That is why we are coordinating on version update first and then merging the Ignite features a month later.

**Comment by anuchandy** [comment]
@vrushg-ms are we planning to take these changes in the PR? if so could you address @ravbhatnagar  comments?

**Comment by ravbhatnagar** [comment]
very old PR removing ARM review labels.

**Comment by akning-ms** [comment]
Looks it is already in public repo. so close it

**Pull request closed without merging**
