### PR TITLE
[ACS - Chat] Data Retention Policy 2023-07-01-preview

### LINKED ISSUE #22880: [IC3 ACS Chat] API Review
**Service Name**: IC3 ACS Chat
**Review Created By**: Lu Chen
**Review Date**: 3/23/2023 4:00 PM PT
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/22858
**Hero Scenarios Link**: [here](https://microsoft-my.sharepoint-df.com/:w:/p/luc/EaxCNPlllvVEjt4o57O5XCkB_EjBEP8fO0ghSCzTC0_c9w?e=d9XdUW)
**Core Concepts Doc Link**: [here](https://microsoft-my.sharepoint-df.com/:w:/p/luc/EaxCNPlllvVEjt4o57O5XCkB_EjBEP8fO0ghSCzTC0_c9w?e=d9XdUW)

**Description**: ACS Chat is adding a RetentionPolicy property into Thread model. 
It is used to specify the retention policy for the thread. The retention policy specifies how long the thread should be retained. You can create a thread with a retention policy by setting the RetentionPolicy property of the Thread model to the desired retention policy. You can get the retention policy of a thread by reading the RetentionPolicy property of the Thread model. You can update the retention policy of a thread by setting the RetentionPolicy property of the Thread model to the new retention policy.

*Meeting moved to 4PM PST as requested by Mike Kistler*

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=0ea1528a-26b9-ed11-83fe-000d3a3418aa)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by LuChen-Microsoft**
ACS Chat is adding a `RetentionPolicy` property into Thread model. It is used to specify the retention policy for the thread. The retention policy specifies how long the thread should be retained. You can create a thread with a retention policy by setting the RetentionPolicy property of the Thread model to the desired retention policy. You can get the retention policy of a thread by reading the RetentionPolicy property of the Thread model. 

Due to the support from dependencies, RetentionPolicy property of the Thread model is not able to be updated during the preview stage.

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/LuChen-Microsoft-communication-Chat-2023-07-01-preview...main/).
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:https://github.com/Azure/azure-rest-api-specs/issues/22880

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document: [Data Retention Design Doc](https://microsoft-my.sharepoint-df.com/:w:/p/luc/EaxCNPlllvVEjt4o57O5XCkB_EjBEP8fO0ghSCzTC0_c9w?e=d9XdUW)
* Previous Open API Doc:
* Updated paths:

Differences: [Open API HUB Comparing Version](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvTHVDaGVuLU1pY3Jvc29mdC1jb21tdW5pY2F0aW9uLUNoYXQtMjAyMy0wNy0wMS1wcmV2aWV3L3NwZWNpZmljYXRpb24vY29tbXVuaWNhdGlvbi9kYXRhLXBsYW5lL0NoYXQvcmVhZG1lLm1kIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL0x1Q2hlbi1NaWNyb3NvZnQtY29tbXVuaWNhdGlvbi1DaGF0LTIwMjMtMDctMDEtcHJldmlldy9zcGVjaWZpY2F0aW9uL2NvbW11bmljYXRpb24vZGF0YS1wbGFuZS9DaGF0L3JlYWRtZS5tZCIsInNvdXJjZVRhZyI6InBhY2thZ2UtY2hhdC0yMDIzLTA0LTAxLXByZXZpZXciLCJ0YXJnZXRUYWciOiJwYWNrYWdlLWNoYXQtMjAyMy0wNy0wMS1wcmV2aWV3In0=)

Paths: 
Post: "/chat/threads"
Get: "/chat/threads" "/chat/threads/{chatThreadId}"
PATCH: "/chat/threads/{chatThreadId}"

Here are the detailed changes:

**1. Expose the Retention Policy Model**

```Json
 "RetentionPolicy": {
      "description": "Data retention policy for auto deletion.",
      "type": "object",
      "discriminator": "policyType",
      "properties": {
        "policyType": {
          "description": "Retention Policy Type",
          "enum": [
            "threadCreationDate"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "policyType",
            "modelAsString": true,
            "values": [
              {
                "value": "threadCreationDate",
                "description": "Thread retention policy based on thread creation date."
              }
            ]
          }
        }
      },
      "required": [
        "policyType"
      ]
    },
    "ThreadCreationDateRetentionPolicy": {
      "description": "Thread retention policy based on thread creation date.",
      "type": "object",
      "x-ms-discriminator-value": "threadCreationDate",
      "allOf": [
        {
          "$ref": "#/definitions/RetentionPolicy"
        }
      ],
      "properties": {
        "daysAfterCreation": {
          "type": "integer",
          "format": "int32",
          "description": "Indicates how many days after the thread creation the thread will be deleted. Only 90 is accepted for now."
        }
      },
      "required": [
        "daysAfterCreation"
      ]
    }
``` 

For the potential support in future, we might add the new policy type into RetentionPolicy. (This is not included in current version change)

``` Json
"BasedOnThreadLastActivityDateRetentionPolicy": {
      "description": "Thread retention policy based on thread last activity date.",
      "type": "object",
      "x-ms-discriminator-value": "basedOnThreadLastActivityDate",
      "allOf": [
        {
          "$ref": "#/definitions/RetentionPolicy"
        }
      ],
      "properties": {
        "daysAfterLastActivity": {
          "type": "integer",
          "format": "int32",
          "description": "Indicates how many days after the thread last activity the thread will be deleted. "
        }
      },
      "required": [
        "daysAfterLastActivity"
      ]
    }
``` 

**2. Add an optional property RententionPolicy in Create Chat Thread:**

```Json

"CreateChatThreadRequest": {
  "description": "Request payload for creating a chat thread.",
  "required": [
    "topic"
  ],
  "type": "object",
  "properties": {
    ...
    "retentionPolicy": {
      "$ref": "#/definitions/RetentionPolicy"
    }
  }
},
``` 

**3. Add an optional property RententionPolicy when Get Chat Thread**

```Json

"ChatThreadProperties": {
  "description": "Chat thread.",
  "required": [
    "createdByCommunicationIdentifier",
    "createdOn",
    "id",
    "topic"
  ],
  "type": "object",
  "properties": {
    ...
    "retentionPolicy": {
      "$ref": "#/definitions/RetentionPolicy"
    }
  }
}
```

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/22880

### CODE REVIEW

**Comment by LuChen-Microsoft** [comment]
> You have to tell me exaclty what you want reviewed here. You don't need the whole thing reviewed, right? Right away, I see POST /chat/threads/{chatThreadId}/typing doesn't look right. You want a colon before "typing" I think. I also see non-2xx status codes in the swagger; we don't put these in swagger.

Hi @JeffreyRichter , thanks for the comment. I added the description. Here's the Open API differences between the change with our current stable version:

[Open API HUB Comparing Version](https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvTHVDaGVuLU1pY3Jvc29mdC1jb21tdW5pY2F0aW9uLUNoYXQtMjAyMy0wNy0wMS1wcmV2aWV3L3NwZWNpZmljYXRpb24vY29tbXVuaWNhdGlvbi9kYXRhLXBsYW5lL0NoYXQvcmVhZG1lLm1kIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzL0x1Q2hlbi1NaWNyb3NvZnQtY29tbXVuaWNhdGlvbi1DaGF0LTIwMjMtMDctMDEtcHJldmlldy9zcGVjaWZpY2F0aW9uL2NvbW11bmljYXRpb24vZGF0YS1wbGFuZS9DaGF0L3JlYWRtZS5tZCIsInNvdXJjZVRhZyI6InBhY2thZ2UtY2hhdC0yMDIxLTA5LTA3IiwidGFyZ2V0VGFnIjoicGFja2FnZS1jaGF0LTIwMjMtMDctMDEtcHJldmlldyJ9)

Updated Paths: 
Post: "/chat/threads"
Get: "/chat/threads" "/chat/threads/{chatThreadId}"
PATCH: "/chat/threads/{chatThreadId}"

**Review by JeffreyRichter — APPROVED** [review]
Please remove all non-2xx codes from swagger

**Comment by LuChen-Microsoft** [comment]
> Please remove all non-2xx codes from swagger

Thanks! Created a separate item to remove them.

**Pull request merged**
