### PR TITLE
graphrbac - updating folder structure to be more consistent 

### PR DESCRIPTION
**Pull request by veronicagg**
Adding a folder to graphrbac to be more consistent with the rest of the repo, this helps supporting the service in OpenAPIHub - https://portal.azure-devex-tools.com/app/branch/veronicagg/azure-rest-api-specs/graphrbac-fix-folder

### CODE REVIEW

**Comment by nschonni** [comment]
Should it be Microsoft.GraphRbac instead of the plain GraphRbac?

**Comment by veronicagg** [comment]
ok, decided to update it, thanks!

**Comment by nschonni** [comment]
Just to be even more confusing :wink: the C# has Graph.RBAC, so maybe even Microsoft.Graph.Rbac

**Comment by veronicagg** [comment]
@nschonni thanks, but I'd prefer to leave it as is :)

**Review by praries880 — APPROVED** [review]

**Pull request merged**
