### PR TITLE
[DoNotMerge]Updated swagger to include isSftpEnabled property

### PR DESCRIPTION
**Pull request by dhanvia**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by blueww — APPROVED** [review]
Looks good from .net SDK side. 
Please share the rest API spec, and is there any server ready for this feature?
We should not merge it before server is ready.

**Review by Juliehzl — APPROVED** [review]
LGTM. @dhanvia If you still do not want to merge the PR, please add "Do not merge" label in the PR. If you are ready, feel free to let me know and I could help you merge it.

**Comment by Juliehzl** [comment]
Hi @dhanvia, is the PR ready to merge now?

**Comment by dhanvia** [comment]
HI Zunli,

I am waiting for the concerned internal team to run a successful test before I can merge the PR.
Currently, it looks like the testing is blocked.

Thanks
Dhanvi
________________________________

**Comment by dhanvia** [comment]
@Juliehzl / @blueww  I have recieved information from our internal team that the server side tests were successful. This PR can be merged now.

**Comment by dhanvia** [comment]
@Juliehzl  I am unable to merge this PR, because of the DoNotMerge label, and I am unable to edit that label aswell. Can you please check ?
Sorry for the delays on this PR, but the testing was unblocked just recently.

**Comment by blueww** [comment]
@dhanvia
Would you please confirm if the server is ready for the API change?
If it's ready, please share which region, and does it need any specific registration to using the feature?

If not, we should not merge the API change before server is ready.

**Review by pilor — APPROVED** [review]

**Comment by dhanvia** [comment]
@Wei Wei (AZURE)<mailto:weiwei@microsoft.com>

The server code that contains the isSFTPEnabled is rolledout everywhere. However, the feature is enabled only in stage and canary for now (eastus2.stage, eastus2euap, centraluseuap). In these regions, the user would have to register their subscription with the feature - "Microsoft.Storage/AllowSFTP, in order to be able to use this feature.

Thanks
Dhanvi
________________________________

**Comment by blueww** [comment]
@dhanvia 

I have tried to register AllowSFTP for my subscription, but get failure  "The feature 'AllowSFTP' does not support registration." See details below.
It seems the feature still no available for most customer. We might should not merge the swagger PR in this case, or the customer failed to use the feature will report issues.

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/{subscription ID}/providers/Microsoft.Features/providers/Microsoft.Storage/features/AllowSFTP/register?api-version=2015-12-01

Headers:
x-ms-client-request-id        : 11d7e4a3-a320-451a-8fba-eaaee0c21f9b
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-request-id               : southeastasia:955038e9-f1b3-4122-a911-e77c07d6990a
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 8052c24b-0a64-4c45-a5dd-31f12cf0057b
x-ms-routing-request-id       : SOUTHEASTASIA:20210128T020646Z:8052c24b-0a64-4c45-a5dd-31f12cf0057b
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 28 Jan 2021 02:06:45 GMT

Body:
{
  "error": {
    "code": "FeatureRegistrationUnsupported",
    "message": "The feature 'AllowSFTP' does not support registration."
  }
}
```

**Comment by dhanvia** [comment]
@blueww  The AFEC registration is open only for internal customers. It is not open for public yet.

**Comment by blueww** [comment]
@dhanvia
If it's only open to internal customer, we should not merge the change to public swagger, or all SDK/Tools might will include the change, and customer will report issue when find this not work.
And since I can't test this feature as no test server, we also can't start PSH work for it before we can get a test server.

**Comment by dhanvia** [comment]
@blueww / @pilor  I had to update June19 version aswell, as the server supports this feature in the June19 template.  Can you please review. This Need not be merged yet, but would later have to be merged when the property is opened for public

**Comment by evelyn-ys** [comment]
Hi @dhanvia, Is there any ETA from server side that open this feature for public?

**Pull request closed without merging**
