### PR TITLE
Add RunCommand resource spec

### PR DESCRIPTION
**Pull request by koralski**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by koralski** [comment]
Feature design doc: https://microsoft.sharepoint.com/teams/ComputeVM/Shared%20Documents/Managed%20Services%20Team/Run%20Command%20V2%20Design.docx?web=1

**Comment by fengzhou-msft** [comment]
Please fix the LintDiff error following [CI fix guide](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md).

**Comment by chiragg4u** [comment]
Changes looks good from ARM side, please resolve errors.

**Comment by koralski** [comment]
> Please fix the LintDiff error following [CI fix guide](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md).

All related Lint errors were fixed.
The only one new error reported is pre-existing and not part of this change:
specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json:7715
Please see the details.

**Comment by grizzlytheodore** [comment]
@fengzhou-msft  how did the pre-existing lintDiff in compute.json come about? how do we address that ?

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft how did the pre-existing lintDiff in compute.json come about? how do we address that ?

@jianyexi can you take a look at the lintDiff error in this PR and advise on the fix?

**Comment by grizzlytheodore** [comment]
for some reason, it looks like LintDiff is catching more in this PR than other PR's 
For example this PR: https://github.com/Azure/azure-rest-api-specs/pull/11069 contains all the same things that the LintDiff in this PR is catching (error and warning) however, other PRs do not get the errors and warning that this PR has.

**Comment by koralski** [comment]
I will close this PR and resubmit with freshly forked repo

**Comment by jianyexi** [comment]
> for some reason, it looks like LintDiff is catching more in this PR than other PR's
> For example this PR: #11069 contains all the same things that the LintDiff in this PR is catching (error and warning) however, other PRs do not get the errors and warning that this PR has.
> 
> please advise on the fix, @fengzhou-msft @jianyexi API owner @koralski needs to push this forward

It's an existing lint error , the CI  seems has  a bug , please ignore it

**Comment by fengzhou-msft** [comment]
> > for some reason, it looks like LintDiff is catching more in this PR than other PR's
> > For example this PR: #11069 contains all the same things that the LintDiff in this PR is catching (error and warning) however, other PRs do not get the errors and warning that this PR has.
> > please advise on the fix, @fengzhou-msft @jianyexi API owner @koralski needs to push this forward
> 
> It's an existing lint error , the CI seems has a bug , please ignore it

Thanks @jianyexi. 

@akning-ms can you help merge this PR?

**Review by fengzhou-msft — APPROVED** [review]

**Comment by grizzlytheodore** [comment]
@fengzhou-msft @jianyexi could it be that it was naming issue?  This PR was changing runCommand.json file, but we were getting LintDiff error from compute.json file that we hadn't see before. Maybe there were something being added in RunCommand.json that already exists in compute.json thus causing LintDiff error on compute.json?

**Pull request merged**
