### PR TITLE
Add Set Orchestration Service State API

### PR DESCRIPTION
**Pull request by cachuahu**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by cachuahu** [comment]
This change has already been reviewed and approved by ARM : https://github.com/Azure/azure-rest-api-specs-pr/pull/1078

**Comment by weidongxu-microsoft** [comment]
@cachuahu

It is not merging to master. Let me know if you need to loop in ARM in this PR.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by cachuahu** [comment]
> @cachuahu
> 
> It is not merging to master. Let me know if you need to loop in ARM in this PR.

@weidongxu-microsoft 

It has been approved by ARM already: https://github.com/Azure/azure-rest-api-specs-pr/pull/1078

**Comment by weidongxu-microsoft** [comment]
@cachuahu

Got it. I've already approved. If you still need other people to review, take you time. If you want to get it merged, leave a message.

**Comment by cachuahu** [comment]
@weidongxu-microsoft 
Thanks, we can merge this.

**Pull request merged**
