### PR TITLE
Add public certificates, Functions Admin Token and MSDeploy APIs

### PR DESCRIPTION
**Pull request by naveedaz**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sarangan12** [comment]
Started reviewing. Will update shortly

**Comment by sarangan12** [comment]
@naveedaz Errors reported in https://travis-ci.org/Azure/azure-rest-api-specs/jobs/257534770 Please fix them so I can review and merge

**Comment by naveedaz** [comment]
@sarangan12 They are already fixed. https://travis-ci.org/Azure/azure-rest-api-specs/builds/257836873?utm_source=github_status&utm_medium=notification

**Comment by sarangan12** [comment]
@naveedaz The following errors must be fixed:

R3006
=====
{
	"type": "Error",
	"code": "BodyTopLevelProperties",
	"message": "Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity. Model definition 'MSDeployStatus' has extra properties ['deployer,provisioningState,startTime,endTime,complete'].",
	"id": "R3006",
	"validationCategory": "RPCViolation",
	"providerNamespace": null,
	"resourceType": null,
	"sources": [
		"file:///home/travis/build/Azure/azure-rest-api-specs/specification/web/resource-manager/Microsoft.Web/2016-08-01/WebApps.json:13771:6 ($.definitions.MSDeployStatus.properties)"
	]
}

R3025
=====
{
	"type": "Error",
	"code": "TrackedResourceGetOperation",
	"message": "Tracked resource 'SnapshotRecoveryRequest' must have a get operation.",
	"id": "R3025",
	"validationCategory": "RPCViolation",
	"providerNamespace": null,
	"resourceType": null,
	"sources": [
		"file:///home/travis/build/Azure/azure-rest-api-specs/specification/web/resource-manager/Microsoft.Web/2016-08-01/WebApps.json:15825:4 ($.definitions.SnapshotRecoveryRequest)"
	]
}


R2020
=====
{
	"type": "Error",
	"code": "RequiredPropertiesMissingInResourceModel",
	"message": "Model definition 'SnapshotRecoveryRequest' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.",
	"id": "R2020",
	"validationCategory": "RPCViolation",
	"providerNamespace": null,
	"resourceType": null,
	"sources": [
		"file:///home/travis/build/Azure/azure-rest-api-specs/specification/web/resource-manager/Microsoft.Web/2016-08-01/WebApps.json:15825:4 ($.definitions.SnapshotRecoveryRequest)"
	]
}

{
	"type": "Error",
	"code": "RequiredPropertiesMissingInResourceModel",
	"message": "Model definition 'MSDeployStatus' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.",
	"id": "R2020",
	"validationCategory": "RPCViolation",
	"providerNamespace": null,
	"resourceType": null,
	"sources": [
		"file:///home/travis/build/Azure/azure-rest-api-specs/specification/web/resource-manager/Microsoft.Web/2016-08-01/WebApps.json:13768:4 ($.definitions.MSDeployStatus)"
	]
}

**Comment by jianghaolu** [comment]
Since `MSDeployStatus` is an arm resource, maybe it should have 
```json
"allOf": [
  {
     "$ref": "#/definitions/Resource"
  }
]
```
?

**Comment by jianghaolu** [comment]
@sarangan12 Thanks for helping reviewing. Do you think I can take over this since this is a request made from fluent sdk team?

**Review by jianghaolu — APPROVED** [review]

**Comment by naveedaz** [comment]
@sarangan12 @jianghaolu Are we good to go here?

**Comment by sarangan12** [comment]
Done

**Pull request merged**
