### PR TITLE
[DoNotMerge] Assessment metadata API (Azure Security Center)

### PR DESCRIPTION
**Pull request by tarosler**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by tarosler** [comment]
This PR already approved by ARM in previous PR (https://github.com/Azure/azure-rest-api-specs/pull/6445/files) that merged by mistake. The merge was reverted and I opened a new PR with the same code.

Thanks,
Tal

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
update from service team via email.
```
From: Chen Lahav <Chen.Lahav@microsoft.com> 
Sent: Sunday, September 1, 2019 3:48 PM
To: Catherine Zhu <yungez@microsoft.com>; Tal Rosler <Tal.Rosler@microsoft.com>
Subject: RE: about PR https://github.com/Azure/azure-rest-api-specs/pull/6621

Hi Catherine,
We are in a Private Preview processes, we will probably go public by end of month and complete the PR then
Currently private preview customers are using the files from the fork for documentation

Thanks,
Chen

```

**Comment by yungezz** [comment]
HI @tarosler   any update?

**Comment by tarosler** [comment]
> HI @tarosler any update?

+ @chlahav  who is the owner of this PR now

**Comment by yungezz** [comment]
HI @chlahav  what's next step of this PR? any update?

**Comment by yungezz** [comment]
HI @chlahav what's next step of this PR? any update?

**Pull request closed without merging**
