### PR TITLE
new CDN swagger version for 2016-04-02

### PR DESCRIPTION
**Pull request by csmengwan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@csmengwan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (qinwa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
The version is still `"version": "2016-04-02"`. It does not have -prerelease as mentioned in the filepath

**Comment by amarzavery** [comment]
Fix tabbing/indentation on line 253 for "200" response

**Comment by amarzavery** [comment]
Fix tabbing/indentation on 
- line  686, 739 for "schema" of 202 response
- line 1692 for "sku" in the required array
- line 1707, 1708

Remove the empty line on 2440

**Comment by amarzavery** [comment]
everything else LGTM

**Comment by amarzavery** [comment]
@csmengwan - Please make the fixes for the PR to be merged.

**Comment by csmengwan** [comment]
Hi, Amar. Thanks for reviewing this. I will fix the indentation issues. And since we are releasing at the end of this week. I will remove the pre-release tag there.

**Pull request merged**
