### PR TITLE
[SQL][V20180601] Updating LocationCapabilities spec

### PR DESCRIPTION
**Pull request by hotsnr**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [x] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ericshape** [comment]
@hotsnr 
can you let us know your PR link of the internal DSMainDev repo for these changes?

**Comment by hotsnr** [comment]
@ericshape
https://msdata.visualstudio.com/Database%20Systems/_git/DsMainDev/pullrequest/402510
https://msdata.visualstudio.com/Database%20Systems/_git/DsMainDev/pullrequest/437463
https://msdata.visualstudio.com/Database%20Systems/_git/DsMainDev/pullrequest/466943

**Comment by ericshape** [comment]
After offline discussion, @hotsnr will also update the same spec and example files in 2020-08-01-preview and 2020-02-02-preview in this PR.

**Comment by akning-ms** [comment]
Hi @hotsnr can I know why you have this PR? looks you are update a new feature in an old API version, as it may cause breaking change, Can we just put it in new API version 2020-08-01-preview?

**Review by ericshape — COMMENTED** [review]
#11840 is merged. Please rebase and update spec/example files in 2020-02-02-preview and 2020-08-01-preview

**Comment by hotsnr** [comment]
> Hi @hotsnr can I know why you have this PR? looks you are update a new feature in an old API version, as it may cause breaking change, Can we just put it in new API version 2020-08-01-preview?

This is the latest version where that controller is implemented, all consequent ones (2019, 2020-02, 2020-08) are going to change in the same way. Just added changes to 2020 versions, @ericshape is working on a massive change in 2019 which is going to include this one.

> it may cause breaking change

It won't in any way. From technical (syntax) perspective, this is read-only API and I'm only extending it. From semantics point of view, this feature is an extension, e.g. if customers don't want to use it they can just ignore this additional information I've added and nothing is going to change for them.

**Review by ericshape — APPROVED** [review]
for the breaking changes alert about " 1007 - RemovedClientParameter", it is expected and not a true breaking change. 
We actually replace the local inline parameters with a common type parameter reference in the spec file. And then we removed all unused local inline parameter defs.

**Review by bcham — APPROVED** [review]

**Comment by akning-ms** [comment]
According to discuss with @ericshape, Seems the change to 2018-06-01-preview is not required. you may use 2020-08-01-preview in V4 if need it in SDK as looks the 2 version is same swagger definition

**Pull request merged**
