### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version preview/2023-06-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/FumingZhang-containerservice-Microsoft.ContainerService-2023-06-02-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by FumingZhang** [comment]
./azp run

**Comment by FumingZhang** [comment]
Hey @tadelesh, could you please help fix the failed required CI [SDK azure-sdk-for-go](https://github.com/Azure/azure-rest-api-specs/pull/24922/checks?check_run_id=15224485794)? From [error log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2936712&view=logs&j=7abd2647-c1ae-5740-a200-88c01716493a&t=bf6e38a3-4325-5466-d842-a1ba6bbe8789&l=589)
> cmderr	[generator automation-v2] [ERROR] | error: @autorest/go@4.0.0-preview.53: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.1"

seems you need to upgrade node in the CI env.

**Comment by FumingZhang** [comment]
Hey @JeffreyRichter, could you please help approve the breaking change? The CI [Breaking Change(Cross-Version)](https://github.com/Azure/azure-rest-api-specs/pull/24922/checks?check_run_id=15224455668) is **mistakenly** comparing the change with latest **stable** API 2023-06-01. When comparing with latest **preview** API 2023-05-02-preview, there are only **3 unique  warnings**
image

The changed constraints are introduced in commit [#c2c231f](https://github.com/Azure/azure-rest-api-specs/pull/24922/commits/c2c231f353a96affc1014a5ae6c1ae0c7ac02512)
image
These restrictions have always existed on the server side, and this change only shows them explicitly, which would helps avoid users from providing invalid values. + feature owner @UtheMan
Thanks!

**Comment by visingla-ms** [comment]
>         "revision": {

Schema should have a description or title.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-06-02-preview/managedClusters.json:8185 in a8e7aaf. [](commit_id = a8e7aaf902f29171703d3f71fe0bb0b90e8817c2, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "CompatibleVersions": {

Schema should have a description or title.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-06-02-preview/managedClusters.json:8205 in a8e7aaf. [](commit_id = a8e7aaf902f29171703d3f71fe0bb0b90e8817c2, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "name": {

Schema should have a description or title.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-06-02-preview/managedClusters.json:8208 in a8e7aaf. [](commit_id = a8e7aaf902f29171703d3f71fe0bb0b90e8817c2, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "versions": {

Schema should have a description or title.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-06-02-preview/managedClusters.json:8211 in a8e7aaf. [](commit_id = a8e7aaf902f29171703d3f71fe0bb0b90e8817c2, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "items": {

Schema should have a description or title.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-06-02-preview/managedClusters.json:8191 in a8e7aaf. [](commit_id = a8e7aaf902f29171703d3f71fe0bb0b90e8817c2, deletion_comment = False)

**Comment by visingla-ms** [comment]
Please address the missing title/description comments before merging the PR, and also consider converting booleans to enums if possible, as highlighted in Linter Warnings.

**Comment by FumingZhang** [comment]
> Please address the missing title/description comments before merging the PR, and also consider converting booleans to enums if possible, as highlighted in Linter Warnings.

Hey @visingla-ms, the missing descriptions are added in commit [#df617e7](https://github.com/Azure/azure-rest-api-specs/pull/24922/commits/df617e72b92f5e56e9a9454858a4ac49586b4674).

**Comment by FumingZhang** [comment]
Hey @msyyc, could you please help approve the [Python SDK breaking change](https://github.com/Azure/azure-rest-api-specs/pull/24922/checks?check_run_id=15415814456)?
image

There are some differences on the model `ManagedClusterWorkloadAutoScalerProfileVerticalPodAutoscaler` between stable and preview API. Compared with the stable API, it has two additional fields in the preview API, but it also includes all the fields in the stable API. So I think this should be fine.

**Comment by msyyc** [comment]
> Hey @msyyc, could you please help approve the [Python SDK breaking change](https://github.com/Azure/azure-rest-api-specs/pull/24922/checks?check_run_id=15415814456)? image
> 
> There are some differences on the model `ManagedClusterWorkloadAutoScalerProfileVerticalPodAutoscaler` between stable and preview API. Compared with the stable API, it has two additional fields in the preview API, but it also includes all the fields in the stable API. So I think this should be fine.

Approved for python breaking.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
