### PR TITLE
Adding 7.2-preview version (#8397)

### PR DESCRIPTION
**Pull request by vasanthrajams**
* Adding 7.2-preview version

Signed-off-by: vasanthrajams <vasanthrajams@microsoft.com>

* Resolve PR feedback

* Fix output-folder for go code generation

Co-authored-by: Heath Stewart <heaths@outlook.com>

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by daviddesberg — APPROVED** [review]

**Review by msfcolombo — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@vasanthrajams what's the baseline here, 7.1-preview?  Something else?  Usually the PR is created with several commits, the first of which is the baseline copied over followed by changes for the new version.  Having everything in one commit makes it difficult to review just the delta.

**Comment by vasanthrajams** [comment]
> 
> 
> @vasanthrajams what's the baseline here, 7.1-preview? Something else? Usually the PR is created with several commits, the first of which is the baseline copied over followed by changes for the new version. Having everything in one commit makes it difficult to review just the delta.

@jhendrixMSFT  Yes, the baseline is 7.1-preview and we made a few changes to reflect the 7.2 preview. Please find the following semantic diff. The changes are very small.

[https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYXN0ZXIvc3BlY2lmaWNhdGlvbi9rZXl2YXVsdC9kYXRhLXBsYW5lL3JlYWRtZS5tZCIsInRhcmdldFVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9BenVyZS9henVyZS1yZXN0LWFwaS1zcGVjcy9ibG9iL2Rldi1rZXl2YXVsdC1NaWNyb3NvZnQuS2V5VmF1bHQtNy4yL3NwZWNpZmljYXRpb24va2V5dmF1bHQvZGF0YS1wbGFuZS9yZWFkbWUubWQiLCJzb3VyY2VUYWciOiJwYWNrYWdlLTcuMS1wcmV2aWV3IiwidGFyZ2V0VGFnIjoicGFja2FnZS03LjItcHJldmlldyJ9](url)

**Comment by jhendrixMSFT** [comment]
@vasanthrajams the changes look good.  Presumably the model validation failures are previous known issues, however I see that they're present in the new example files.  They look ok to me.  Is there a bug tracking this?

**Comment by vasanthrajams** [comment]
> 
> 
> @vasanthrajams the changes look good. Presumably the model validation failures are previous known issues, however I see that they're present in the new example files. They look ok to me. Is there a bug tracking this?

@jhendrixMSFT  The changed appearing here were removed from the 7.1 branch and added here in 7.2 branch. These are not new. I'm not aware if there exist any bug tracking these.
@heaths could you please mention if there a bug tracking the above ?

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by heaths** [comment]
@jhendrixMSFT  yes, there is a bug tracking ModelValidation errors that's supposed to be fixed this sprint, but I don't know any more than that. It's something I had to work through for weeks because a fix was not in place. I explained to Vasanth what I did (checking the log that all errors are MISSING_REQUIRED_PARAMETER errors, and fixing those that weren't) and he's been doing that.

The BreakingChange is also a known issue, though I know nothing more about that it's was told to ignore it anyway (also, hence the test name prefix).

**Comment by jhendrixMSFT** [comment]
@mayurid can you please merge this?

**Pull request merged**
