### PR TITLE
Add remoteBgpCommunities to VirtualNetworkPeering resource

### PR DESCRIPTION
**Pull request by jarango**
This pull request adds the remoteBgpCommunities property to the VirtualNetworkPeering resource. The value of this property is populated from the value of the bgpCommunities property of the remote VNET that is being peered to the local VNET.

This is an addition being done for important scalability reasons. ExpressRoute needs to read the BgpCommunities of all the spoke VNETs that are peered with a hub VNET. Performing GET operations on each peered VNET does not scale because the number of peered VNETs can be large.
The efficient way to obtain this information is from the VirtualNetworkPeering child resources of the hub VNET.

### Contribution checklist:
- [ x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
@jarango, could you check why NetworkValidation failed?

**Comment by number213** [comment]
@lirenhe please ignore it. Previous release cycle introduced breaking changes and powershel repo's master branch hasn't been updated yet to address that

**Review by anton-evseev — APPROVED** [review]

**Comment by jarango** [comment]
Thank you Anton for the review

**Comment by ravbhatnagar** [comment]
Removing ARM Feedback label since ARM review board will not be reviewing property level changes going forward.

**Comment by number213** [comment]
In this case, @lirenhe please merge

**Comment by jarango** [comment]
@lirenhe could you please merge

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
