### PR TITLE
Fix Microsoft.PolicyInsights linting errors

### PR DESCRIPTION
**Pull request by eladperets**
Added format to integer properties.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by eladperets** [comment]
Hi @yungezz!
These aren't really breaking changes, these properties are all read only and always returned int32 integers. We only update it because it came up in s360, please let me know how to proceed.

**Comment by yungezz** [comment]
> Hi @yungezz!
> These aren't really breaking changes, these properties are all read only and always returned int32 integers. We only update it because it came up in s360, please let me know how to proceed.

hi @akning-ms what's latest process for breaking change caused by fixing swagger issue :)

**Comment by akning-ms** [comment]
> > Hi @yungezz!
> > These aren't really breaking changes, these properties are all read only and always returned int32 integers. We only update it because it came up in s360, please let me know how to proceed.
> 
> hi @akning-ms what's latest process for breaking change caused by fixing swagger issue :)

I checked with some of SDK owners, looks SDK code gen will also take it as int32 by default if no format define. so it may not a really breaking change if service code also take it as int32 by default. @JeffreyRichter to confirm whether it is really breaking change in this case, if not, we can change our tool for the case to add format: int32.

**Comment by JeffreyRichter** [comment]
Yes, unfortunately, adding the int32 format later does break our SDKs. Without it, some languages use int32 but some use int64 or even float (like JavaScript which doesn't support integers at all). So, this PR is a breaking change  for customers and can't be approved.

**Comment by eladperets** [comment]
> Yes, unfortunately, adding the int32 format later does break our SDKs. Without it, some languages use int32 but some use int64 or even float (like JavaScript which doesn't support integers at all). So, this PR is a breaking change for customers and can't be approved.

In this specific case I don't think anything will break: all the changed properties are either readonly or a part of a resource that doesn't support PUT so we only have to worry about whether existing SDKs can deserialize the server responses. Also, there are no changes to the actual APIs, they were always returning int32, we're only changing the swagger because it came up in S360. Any existing tools calling these APIs won't see any changes.

**Comment by JeffreyRichter** [comment]
In Go (for example), you can't just assign an int32 to an int6. Here is proof: https://play.golang.org/p/4gu5BVpUkAS. When you run this, you get an error: ./prog.go:9:6: cannot use x (type int32) as type int64 in assignment.

So, without the int32 format in the swagger, Go defaulted to int64 and so customers used int64 variables. But, with the int32 format in the swagger, the customer's int64 variables can't have an int32 assigned to them unless the customer modifies their code and this is why this is a breaking change. This is what the customer would have to do to get their code to compile & run again: https://play.golang.org/p/Kk6wEOeadby

**Comment by eladperets** [comment]
> In Go (for example), you can't just assign an int32 to an int6. Here is proof: https://play.golang.org/p/4gu5BVpUkAS. When you run this, you get an error: ./prog.go:9:6: cannot use x (type int32) as type int64 in assignment.
> 
> So, without the int32 format in the swagger, Go defaulted to int64 and so customers used int64 variables. But, with the int32 format in the swagger, the customer's int64 variables can't have an int32 assigned to them unless the customer modifies their code and this is why this is a breaking change. This is what the customer would have to do to get their code to compile & run again: https://play.golang.org/p/Kk6wEOeadby

Thanks. Looks like our generated Go SDK is actually using int32, but your point is clear. I'll try and ask for exception for the s360 item.

Just an observation: it feels like there are 2 conflicting processes here- existing swaggers are scanned and flagged for violations but on the other hand changes to existing swaggers are scrutinized and many things are considered breaking changes. This makes it hard to 'fix' existing swaggers like I tried to do here. Maybe it's worth considering a less strict breaking changes policy when the API remains the same and it's just the swagger that's changed to better describe it.

**Comment by JeffreyRichter** [comment]
Yes, what we'd prefer is if there was more rigor applied to creating swaggers so that they don't have to be fixed later. The problem is that "just fixing a swagger" changes client libraries which affects all customers using them. And the Azure CLI uses client libraries too so it breaks Azure CLI customers as well. What I'd love is for service teams to create their swagger, then generate a library, and then write code to call the service via the library to verify that everything is available and working correctly. Ideally this would be done in all languages but just doing 1 language would get us very far. 

After all, we (Microsoft) offer the swagger and client libraries to customers and so we should fully test and support them.

**Pull request closed without merging**
