### PR TITLE
AzureSiteRecovery - Adding new properties for test failover and resource rename.

### PR DESCRIPTION
**Pull request by punit-bhatt**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by punit1396** [comment]
ModelValidation tests are failing due to older changes. Fixes are in a separate PR - [#7863](https://github.com/Azure/azure-rest-api-specs/pull/7863)
These changes don't cause any of them.

**Comment by punit1396** [comment]
All the changes in this PR are **non-mandatory**.  Thus, no breaking changes.
The customer can choose to pass them and in case they don't pass anything, service handles it.

**Review by erich-wang — CHANGES_REQUESTED** [review]
@punit1396 , please fix the model validation error https://dev.azure.com/azure-sdk/public/_build/results?buildId=218012&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

**Comment by punit1396** [comment]
> @punit1396 , please fix the model validation error https://dev.azure.com/azure-sdk/public/_build/results?buildId=218012&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

The changes for the modelValidation errors were in another PR. That PR has been merged now. All the essential checks are passing.

**Comment by punit1396** [comment]
All the changes in this PR are regarding non-mandatory parameters. Thus, no breaking changes.
The customer can choose to pass them and in case they don't pass anything, service handles it.

**Review by KrisBash — APPROVED** [review]
Signing off for arm

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
