### PR TITLE
Chaos Studios Experiment Tag Support

### PR DESCRIPTION
**Pull request by RenzoPrettoMS**
# ARM (Control Plane) API Specification Update Pull Request 

> Tip: overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] [ARM review queue] (for **merge** queues, see [2])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

</details>

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the Diagram Step 2, "ARM API changes Review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by visingla-ms** [comment]
Please get SDK breaking changes reviewed from SDK reviewers.

**Comment by RenzoPrettoMS** [comment]
Hello @rkmanda , I want to confirm that all the breaking changes here were addressed and approved when moving from preview version 10-27-2034-preview to stable version 11-01-2023 and we do not need to worry about those for this PR correct? Furthermore, if we can hold off on merging this after your approval I would appreciate it, I still want my team members to take a look.

**Comment by kazrael2119** [comment]
@RenzoPrettoMS , what's the difference between the api version 2024-01-01 and 2023-11-01? I'm reviewing JS sdk breaking change, and feel strange about these breaking change.

**Comment by RenzoPrettoMS** [comment]
@kazrael2119 We are updating our OpenAPI Spec to support Tagging for this resource. The base resource is a tracked resource so no change needed to be done there, however we did need to update our Patch model to support taking in Tags.

**Comment by kazrael2119** [comment]
> @kazrael2119 We are updating our OpenAPI Spec to support Tagging for this resource. The base resource is a tracked resource so no change needed to be done there, however we did need to update our Patch model to support taking in Tags.

Could you add below directive in your api version tag? That's why sdk generation got breaking change.
https://github.com/Azure/azure-rest-api-specs/pull/26942/files#diff-f8dc50ff04e40dd994969e5780b19c1c618016e82e1227aa75c9706547477426L47-L83

**Comment by RenzoPrettoMS** [comment]
Im sorry, what do you mean the directive?

**Comment by kazrael2119** [comment]
> Im sorry @kazrael2119 , what do you mean the directive?

@RenzoPrettoMS , in 2023-11-01, someone add [directive](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/chaos/resource-manager#tag-package-2023-11):
```
directive:
  - from: swagger-document
    where: "$.definitions.action"
    transform: >
      $["x-ms-client-name"] = "ChaosExperimentAction";
  - from: swagger-document
    where: "$.definitions.branch"
    transform: >
      $["x-ms-client-name"] = "ChaosExperimentBranch";
  - from: swagger-document
    where: "$.definitions.step"
    transform: >
      $["x-ms-client-name"] = "ChaosExperimentStep";
  - from: swagger-document
    where: "$.definitions.filter"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetFilter";
  - from: swagger-document
    where: "$.definitions.simpleFilter"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetSimpleFilter";
  - from: swagger-document
    where: "$.definitions.simpleFilterParameters"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetSimpleFilterParameters";
  - from: swagger-document
    where: "$.definitions.selector"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetSelector";
  - from: swagger-document
    where: "$.definitions.listSelector"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetListSelector";
  - from: swagger-document
    where: "$.definitions.querySelector"
    transform: >
      $["x-ms-client-name"] = "ChaosTargetQuerySelector";
```
in it in readme.md. And we have released that api version.
So if you don't add these directive in your api version 2024-01-01 in readme.md, we will have unnecessary breaking changes in sdk generation.

**Comment by RenzoPrettoMS** [comment]
Added it now! Thank you for explaining @kazrael2119 !

**Comment by RenzoPrettoMS** [comment]
Please hold this PR and do not merge yet until my team can also do a final review.

**Comment by brrusino** [comment]
@rkmanda We are trying to use `additionalProperties` for our current response model for successful async OperationResults (Location header pattern) but linting is saying that this is now disallowed for all cases other than tags and identities. We plan to pursue surfacing `operationResults` on a per-resource type basis in the future, which will better support the different response models for completed async operations, but can this get an approval exception in the near term?

**Comment by mentat9** [comment]
> @rkmanda We are trying to use `additionalProperties` for our current response model for successful async OperationResults (Location header pattern) but linting is saying that this is now disallowed for all cases other than tags and identities. We plan to pursue surfacing `operationResults` on a per-resource type basis in the future, which will better support the different response models for completed async operations, but can this get an approval exception in the near term?

@RenzoPrettoMS - This is not a model that will get an exception for the additionalProperties/empty object pattern. For your scenario, take a look at the discriminator pattern at https://swagger.io/specification/v2/ plus the x-ms-discriminator-value extension: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-discriminator-value.

**Comment by brrusino** [comment]
Removed `OperationResults` from this PR, will discuss further with ARM on how to move forward and will include in future PR with new API version.

**Review by mentat9 — APPROVED** [review]

**Pull request merged**
