### PR TITLE
[Cogs Face] Refine the documentation for Face API's new Snapshot features. 

### PR DESCRIPTION
**Pull request by lebronJ**
This is to further refine the documentation for Face API's new Snapshot features, added from #5074 .

Specifically, it is to add quota information and adjust the format (add new lines) for the [generated Snapshot API reference documentation](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/face/snapshot).

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by yangyuan — APPROVED** [review]
Suggestion:
Change `。` to `.`
Change `notstarted` to `notStarted` (not required)

**Comment by lebronJ** [comment]
> Suggestion:
> Change `。` to `.`
> Change `notstarted` to `notStarted` (not required)

Thanks Yuan, for the `notstarted` it is by design. The service does return that value.
For the `。` to `.`, yes this is our mistake but not involved in this PR. I think this is not a blocking issue but we will modify it if this pr is not merged by tomorrow.

**Comment by yangyuan** [comment]
@lebronJ cool,
For `notstarted`, I know the service is using `notstarted`.
But as it's an API design violation `enumeration values SHOULD use lowerCamelCase` https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md , we should have a plan to change it.
Of course it's not blocking this PR.

**Comment by lebronJ** [comment]
> @lebronJ cool,
> For `notstarted`, I know the service is using `notstarted`.
> But as it's an API design violation `enumeration values SHOULD use lowerCamelCase` https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md , we should have a plan to change it.
> Of course it's not blocking this PR.
> 
> BTW service returns `nonstarted` not `notstarted`

Understood. But I have double checked and am sure that Face service returns `notstarted` not `nonstarted`.

**Comment by yangyuan** [comment]
> > @lebronJ cool,
> > For `notstarted`, I know the service is using `notstarted`.
> > But as it's an API design violation `enumeration values SHOULD use lowerCamelCase` https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md , we should have a plan to change it.
> > Of course it's not blocking this PR.
> > BTW service returns `nonstarted` not `notstarted`
> 
> Understood. But I have double checked and am sure that Face service returns `notstarted` not `nonstarted`.

oh, then the value in `TrainingStatus` is wrong. `notstarted` makes more sense

**Comment by lebronJ** [comment]
> > > @lebronJ cool,
> > > For `notstarted`, I know the service is using `notstarted`.
> > > But as it's an API design violation `enumeration values SHOULD use lowerCamelCase` https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md , we should have a plan to change it.
> > > Of course it's not blocking this PR.
> > > BTW service returns `nonstarted` not `notstarted`
> > 
> > 
> > Understood. But I have double checked and am sure that Face service returns `notstarted` not `nonstarted`.
> 
> oh, then the value in `TrainingStatus` is wrong. `notstarted` makes more sense

Thanks a lot to point out this, we have not realized that bug (typo) before.
Any suggestion on fixing such kind of bug? If we rename this to `notstarted`, it may break customers' usage with the generated SDKs.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
