### PR TITLE
typo: Fix AppServiceCertificateOrders.json

### PR DESCRIPTION
**Pull request by nschonni**
- Double word "to"
- Successully -> Successfully
- certitificate -> certificate

These exist in the previous version but I guessed that the previous versions aren't patched. If that's not the case, I'll submit that too

### CODE REVIEW

**Review by hovsepm — APPROVED** [review]

**Comment by nschonni** [comment]
@hovsepm should https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.CertificateRegistration/stable/2015-08-01/AppServiceCertificateOrders.json be fixed at the same time or is it frozen for typo fixes?

**Comment by hovsepm** [comment]
@nschonni you can fix that one as well in this PR. Documentation fixes are non-breaking changes and can be done anytime.

**Comment by nschonni** [comment]
@hovsepm thanks, I've rebased to add the other file. There is a bunch of others like this, so I'll submit them as batches of the same API file versions

**Comment by hovsepm** [comment]
@naveedaz could you review this PR?

**Review by naveedaz — APPROVED** [review]

**Pull request merged**
