### PR TITLE
Adding resources for SourceControls and SourceControlSyncJobs

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
SourceControls is a resource to link an user source control with their Azure Automation (AA) account.

SourceControlSyncJob allows the user to sync their runbooks from their external source source control with their AA account.

----

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
@MiaRomero: Could you please follow-up with on this while I am on vacation? Thanks!

**Comment by Francisco-Gamino** [comment]
+ @vrdmr for FYI.

**Comment by vrdmr** [comment]
@MiaRomero @Francisco-Gamino - Hi, could you please fix the issues reported by the linter before you merge the changes - http://az-bot.azurewebsites.net/linter?fileName=2158_1513382035359.json

**Comment by vrdmr** [comment]
@Francisco-Gamino @MiaRomero Could you please take a look at the Job and fix the building issues - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/324210781

```
error:  Error: Unable to read the content or execute "JSON.parse()" on the content of file "specification/automation/resource-manager/Microsoft.Automation/2015-10-31/definitions.json". The error is:
Error: ENOENT: no such file or directory, open 'specification/automation/resource-manager/Microsoft.Automation/2015-10-31/definitions.json'
    at Object.parseJson (/home/travis/build/Azure/azure-rest-api-specs/node_modules/oav/lib/util/utils.js:79:15)
    at SpecResolver.resolveRelativeReference (/home/travis/build/Azure/azure-rest-api-specs/node_modules/oav/lib/validators/specResolver.js:263:18)
    at /home/travis/build/Azure/azure-rest-api-specs/node_modules/oav/lib/validators/specResolver.js:210:40
    at <anonymous>
```

**Comment by fearthecowboy** [comment]
(FYI, pull from  your branch, some reorganization of the repository happened over the break, and some files moved)

**Comment by fearthecowboy** [comment]
There are errors that need to be addressed:

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/324418857
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/324418858

**Comment by Francisco-Gamino** [comment]
Closing this PR as it is being replaced by https://github.com/Azure/azure-rest-api-specs/pull/2219.

**Pull request closed without merging**
