### PR TITLE
[Ready To Merge] SSH and Quota changes

### PR DESCRIPTION
**Pull request by akshataP**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by akshataP** [comment]
@yaohaizh Can you please add WaitDorAMLFeedback tag?

**Comment by akshataP** [comment]
Version change : commit b779d414924098fda9b89149f76e8eb18dbffef7
Properties added: commit 8f0af71c04c5a7306182cae6c3e2ab4ed5e5a305

Version change does not have any property related changes
Please review the Properties changes commit for the new properties added

**Comment by ravbhatnagar** [comment]
few read only properties have been added in this PR. looks fine. Signing off from ARM side.

**Comment by jhendrixMSFT** [comment]
Opened https://github.com/Azure/oav/issues/433 to track the OAV failure.  Since model validation is passing please ignore the OAV failure.

**Review by yaohaizh — APPROVED** [review]

**Comment by yaohaizh** [comment]
@akshataP when this PR ready for merge?

**Comment by akshataP** [comment]
@yaohaizh please merge the PR

**Pull request merged**
