### PR TITLE
Add AML skill to preview swagger for Search Service

### PR DESCRIPTION
**Pull request by mattgotteiner**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [X] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  Already available
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  December
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [X] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by Mohit-Chakraborty** [comment]
Why do we need to update older preview spec files?

**Review by Mohit-Chakraborty — APPROVED** [review]

**Comment by Mohit-Chakraborty** [comment]
@weshaggard, @pakrym - should we ignore failures caused due to the .NET 6 install issue? Trying to understand what is needed to safely merge the PR.

**Comment by weshaggard** [comment]
>@weshaggard, @pakrym - should we ignore failures caused due to the .NET 6 install issue? Trying to understand what is needed to safely merge the PR.

I think we can safely ignore those for the time being. Would you mind opening an issue up about the failure in the azure-sdk-for-net repo.

**Comment by weshaggard** [comment]
@zhenglaizhang any ideas on that failure? It looks like we install .NET 6.0 in the init step but it doesn't actually seem to be using that in the generate step. What is the recommended way to test out changes in this automation? Can we do a test PR in this repo pointing at a different branch in the sdk repo with changes so we can try them out?

**Comment by Mohit-Chakraborty** [comment]
> Would you mind opening an issue up about the failure in the azure-sdk-for-net repo.

I opened #25819.

**Comment by tjprescott** [comment]
@mattmsft is this PR ready to merge?

**Comment by mattmsft** [comment]
@tjprescott  yes it is but we seem to be blocked by a failing build for reasons unrelated to this change. Do you know if we can ignore this check?

**Comment by zhenglaizhang** [comment]
I workaround to add the dotnet task 6 for the pipeline run for this PR and now its good, https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1267265&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437  /cc @fengzhou-msft for awareness and in long term feng will add this step in init script 

and for staging model validation failure, better to fix it in this PR https://github.com/Azure/azure-rest-api-specs/pull/16910/checks?check_run_id=4451267965

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang any ideas on that failure? It looks like we install .NET 6.0 in the init step but it doesn't actually seem to be using that in the generate step. What is the recommended way to test out changes in this automation? Can we do a test PR in this repo pointing at a different branch in the sdk repo with changes so we can try them out?

usually we tested our changes in https://github.com/openapi-env-test/azure-rest-api-specs
@fengzhou-msft echo Wes's finding, it seems dotnet 6 is already installed but doesn't take effect https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1235643&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=43

**Comment by mattmsft** [comment]
> and for staging model validation failure, better to fix it in this PR https://github.com/Azure/azure-rest-api-specs/pull/16910/checks?check_run_id=4451267965
@zhenglaizhang , this failure doesn't have anything to do with this PR. Any way to deal with this in a separate PR as to keep the scope limited to adding the AML skill preview?

Thanks,
Matt

**Comment by tjprescott** [comment]
@mattmsft the failing checks you reference aren't required to pass to merge this PR. Otherwise, they'd be marked "Required". Would you like me to merge it?

**Comment by mattmsft** [comment]
Yes, please merge this

**Pull request merged**
