### PR TITLE
chore: jsonfmt azsadmin

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/azsadmin/**/*.json"`

### CODE REVIEW

**Review by tjprescott — CHANGES_REQUESTED** [review]
Please re-run with an indent of 4 spaces instead of 2.

**Comment by sergey-shandar** [comment]
@nschonni could you also add `/.vscode/settings.json` with 4 spaces for JSON?

**Comment by nschonni** [comment]
The editorconfig is currently set at 2 https://github.com/Azure/azure-rest-api-specs/blob/master/.editorconfig, and the previous PRs where run/merged with 2. It does look like the tool is able to change the indent if required though https://github.com/caarlos0/jsonfmt/blob/master/main.go#L22

**Comment by veronicagg** [comment]
@tjprescott @sergey-shandar we've been using 2 spaces for swagger files. Travis, if you're good with the PR just let me/Sergey know and we can merge it. Thanks!

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
