### PR TITLE
Add IPAM, VNV, AVNM Security Admin spec and change Vnet swagger spec

### PR DESCRIPTION
**Pull request by arjun-d-patel**
…ationPrefixes to vnet and subnet properties

# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [x] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by arjun-d-patel** [comment]
All the changes are from these 2 PRs which have been reviewed and approved:
https://github.com/Azure/azure-rest-api-specs-pr/pull/19000
https://github.com/Azure/azure-rest-api-specs-pr/pull/18922

**Comment by arjun-d-patel** [comment]
LintDiff errors are from this open issue: https://github.com/Azure/azure-openapi-validator/issues/722

**Comment by mentat9** [comment]
>         "networkIdentifier": {

Looks like this property was added after ARM signed off on previous PRs. Consider naming this property "networkResourceId" or similar, indicating it is a resource ID. Also consider changing it to string type with format: arm-id and the x-ms-arm-id-details extension. Ref: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details).

In current form, using the common definition object it violates the rule against duplicating ARM top-level properties (id) within the property bag. In addition, you couldn't add x-ms-arm-details, since the definition is most likely used many places and the details would vary depending on where it is used. You probably could add format: arm-id to the common definition, but with the size and complexity of NRP, it would be hard to verify how safe that is.

---
Refers to: specification/network/resource-manager/Microsoft.Network/stable/2024-03-01/virtualNetwork.json:1700 in 915d52d. [](commit_id = 915d52dd5c79485bbd56e768f8f5c2ecf3e11bca, deletion_comment = False)

**Comment by arjun-d-patel** [comment]
> > ```
> >     "networkIdentifier": {
> > ```
> 
> Looks like this property was added after ARM signed off on previous PRs. Consider naming this property "networkResourceId" or similar, indicating it is a resource ID. Also consider changing it to string type with format: arm-id and the x-ms-arm-id-details extension. Ref: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details.
> 
> In current form, using the common definition object it violates the rule against duplicating ARM top-level properties (id) within the property bag. In addition, you couldn't add x-ms-arm-details, since the definition is most likely used many places and the details would vary depending on where it is used. You probably could add format: arm-id to the common definition, but with the size and complexity of NRP, it would be hard to verify how safe that is.
> 
> Refers to: specification/network/resource-manager/Microsoft.Network/stable/2024-03-01/virtualNetwork.json:1700 in [915d52d](https://github.com/Azure/azure-rest-api-specs/commit/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca). [](commit_id = [915d52d](https://github.com/Azure/azure-rest-api-specs/commit/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca), deletion_comment = False)

Hi @mentat9, this last commit ([915d52d](https://github.com/Azure/azure-rest-api-specs/pull/30271/commits/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca)) was a merge with base branch commit that was done. I am not making these changes so don't have the context here of what should be the fix.

**Comment by mentat9** [comment]
> > > ```
> > >     "networkIdentifier": {
> > > ```
> > 
> > 
> > Looks like this property was added after ARM signed off on previous PRs. Consider naming this property "networkResourceId" or similar, indicating it is a resource ID. Also consider changing it to string type with format: arm-id and the x-ms-arm-id-details extension. Ref: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details.
> > In current form, using the common definition object it violates the rule against duplicating ARM top-level properties (id) within the property bag. In addition, you couldn't add x-ms-arm-details, since the definition is most likely used many places and the details would vary depending on where it is used. You probably could add format: arm-id to the common definition, but with the size and complexity of NRP, it would be hard to verify how safe that is.
> > Refers to: specification/network/resource-manager/Microsoft.Network/stable/2024-03-01/virtualNetwork.json:1700 in [915d52d](https://github.com/Azure/azure-rest-api-specs/commit/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca). [](commit_id = [915d52d](https://github.com/Azure/azure-rest-api-specs/commit/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca), deletion_comment = False)
> 
> Hi @mentat9, this last commit ([915d52d](https://github.com/Azure/azure-rest-api-specs/pull/30271/commits/915d52dd5c79485bbd56e768f8f5c2ecf3e11bca)) was a merge with base branch commit that was done. I am not making these changes so don't have the context here of what should be the fix.

I understand, but the change is in your PR. I've been asked to review it from the ARM perspective, and that's my feedback. I guess your choices are:
1. Remove that change from your PR
2. Address the feedback yourself
3. Contact the author of that change and have them address the feedback
4. Don't address the feedback and promote that change without the author's knowledge of the feedback

**Pull request closed without merging**
