### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to add version preview/2018-06-17-preview

### PR DESCRIPTION
**Pull request by yves-chan**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/yves-chan/azure-rest-api-specs/dev-applicationinsights-Microsoft.Insights-2018-06-17-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by yves-chan** [comment]
I mainly want to fix the typo on the paths on workbooks_API.json and workbookTemplates_API.json

**Comment by MyronFanQiu** [comment]
@yves-chan Hi. Could you share more context about this PR since it's a breaking change.

**Comment by yves-chan** [comment]
hi @MyronFanQiu , so the purpose of this PR is to change the paths so that it's correct. Before it was using a typo in `resourceGroup` when it should be `resourceGroups`. The breaking change seems to be complaining about this path change?

**Comment by yves-chan** [comment]
@MyronFanQiu what is your Microsoft alias? maybe we can discuss this over teams?

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu what is your Microsoft alias? maybe we can discuss this over teams?

Sorry!!! I miss the last response. Here is a general guideline for breaking change. We can discuss through Teams.

“As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ Breaking Change Process”

**Comment by yves-chan** [comment]
As of now, This change does not affect sdk, cli, or PS since the resource path is wrong to begin with so it never worked. The resource provider does not recognize `resourceGroup` in the path but only recognizes `resourceGroups`. In fact, of all the rest specs, these swaggers for workbooks_API.json and workbookTemplates_API.json are the only one which does not follow the normal convention.

**Review by mmyyrroonn — APPROVED** [review]

**Pull request merged**
