### PR TITLE
Remove AML Compute File Server

### PR DESCRIPTION
**Pull request by wzhang373**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify (Remove unsupported and undocumented APIs)
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet. 
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. (Asap since no major users)
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [] SDK of Python
      - [ ] SDK of Java
      - [] SDK of Js
      - [] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [x] Removing API(s) in stable version
- [x] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
@wzhang373, please note removing api from a stable api version will break all SDKs, please get this change reviewed by breaking change review board.

**Comment by wzhang373** [comment]
As we discussed, I only removed all APIs which are not in use any more. I left the List call in place until customers are notified and moved away.

**Comment by lirenhe** [comment]
Please follow http://aka.ms/bcforapi to go through the breaking change review process.

**Review by JeffreyRichter — APPROVED** [review]

**Review by itsmona25-zz — APPROVED** [review]

**Comment by wzhang373** [comment]
+ Jeffrey.  Jeffrey have approved this change.

Can anyone help me to complete my PRs? I don't have permission to merge into master. Feel free to let me know if there is any issue. Also please let me know the deployment process.  Is it region by region or goes to all regions in one shoot.

Thanks!

Scenario 9740746: Remove AML Compute File Server - Boards (visualstudio.com)<https://msazure.visualstudio.com/One/_workitems/edit/9740746>
Remove AML Compute File Server by wzhang373 * Pull Request #13944 * Azure/azure-rest-api-specs (github.com)<https://github.com/Azure/azure-rest-api-specs/pull/13944>
Remove AML Compute FileServer by wzhang373 * Pull Request #1581 * Azure/azure-resource-manager-schemas (github.com)<https://github.com/Azure/azure-resource-manager-schemas/pull/1581>

**Review by lirenhe — APPROVED** [review]

**Comment by wzhang373** [comment]
Can you also approve Remove AML Compute FileServer by wzhang373 * Pull Request #1581 * Azure/azure-resource-manager-schemas (github.com)<https://github.com/Azure/azure-resource-manager-schemas/pull/1581>? or you will handle the merge yourself?

Thanks for the help!

**Comment by wzhang373** [comment]
+ Tian for help. I can not merge the PR since I don't have the permission.

From: Weiguo Zhang
Sent: Tuesday, April 20, 2021 8:04 PM
To: Azure/azure-rest-api-specs ***@***.***>; Azure/azure-rest-api-specs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

Can you also approve Remove AML Compute FileServer by wzhang373 * Pull Request #1581 * Azure/azure-resource-manager-schemas (github.com)<https://github.com/Azure/azure-resource-manager-schemas/pull/1581>? or you will handle the merge yourself?

Thanks for the help!

**Comment by wzhang373** [comment]
I don’t seem to recognize changes in this PR. I guess I can’t help here ☹.

From: Weiguo Zhang ***@***.***>
Sent: Wednesday, April 21, 2021 9:28 AM
To: Azure/azure-rest-api-specs ***@***.***>; Azure/azure-rest-api-specs ***@***.***>; Tian Ouyang ***@***.***>; Tian Ouyang ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

+ Tian for help. I can not merge the PR since I don’t have the permission.

From: Weiguo Zhang
Sent: Tuesday, April 20, 2021 8:04 PM
To: Azure/azure-rest-api-specs ***@***.******@***.***>>; Azure/azure-rest-api-specs ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

Can you also approve Remove AML Compute FileServer by wzhang373 · Pull Request #1581 · Azure/azure-resource-manager-schemas (github.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-resource-manager-schemas%2Fpull%2F1581&data=04%7C01%7Ctiano%40microsoft.com%7C8739122f389b4c35db6108d904e27817%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637546193020001369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5pQYqax8%2FM2XW07FqTNgJL3oP4GMmYy0U6209XVz%2Bt8%3D&reserved=0>? or you will handle the merge yourself?

Thanks for the help!

**Comment by wzhang373** [comment]
Tian, thanks for your help.

+ Anthony Martin, can you help me to merge this PR and deploy to production?

For deployment, will it be region by region or affect all regions in one deployment?

Thanks!

Weiguo

From: Tian Ouyang ***@***.***>
Sent: Wednesday, April 21, 2021 10:38 AM
To: Weiguo Zhang ***@***.***>; Azure/azure-rest-api-specs ***@***.***>; Azure/azure-rest-api-specs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

I don’t seem to recognize changes in this PR. I guess I can’t help here ☹.

From: Weiguo Zhang ***@***.******@***.***>>
Sent: Wednesday, April 21, 2021 9:28 AM
To: Azure/azure-rest-api-specs ***@***.******@***.***>>; Azure/azure-rest-api-specs ***@***.******@***.***>>; Tian Ouyang ***@***.******@***.***>>; Tian Ouyang ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

+ Tian for help. I can not merge the PR since I don’t have the permission.

From: Weiguo Zhang
Sent: Tuesday, April 20, 2021 8:04 PM
To: Azure/azure-rest-api-specs ***@***.******@***.***>>; Azure/azure-rest-api-specs ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Azure/azure-rest-api-specs] Remove AML Compute File Server (#13944)

Can you also approve Remove AML Compute FileServer by wzhang373 · Pull Request #1581 · Azure/azure-resource-manager-schemas (github.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-resource-manager-schemas%2Fpull%2F1581&data=04%7C01%7Cwzhang%40exchange.microsoft.com%7C8456246654ab4d1b498908d904ec3dba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637546234952378557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mAQ9WgqCSZzfRCjyaHFvCuN1nGpU3u7JTO8U9r3KD1c%3D&reserved=0>? or you will handle the merge yourself?

Thanks for the help!

**Pull request merged**
