### PR TITLE
[Hub Generated] Review request for Microsoft.KeyVault to add version preview/2021-04-01-preview

### PR DESCRIPTION
**Pull request by susolank**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/susolank/azure-rest-api-specs/dev-keyvault-Microsoft.KeyVault-2021-04-01-preview...master/).

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by jlichwa — APPROVED** [review]

**Review by jkapil — APPROVED** [review]

**Review by jiacheng-L — APPROVED** [review]

**Review by heaths — APPROVED** [review]
What about export that is in 7.3-preview currently for data plane? /cc @herveyw-msft

**Comment by zhenglaizhang** [comment]
@allenjzhang is the .net sdk gen failure expected?

**Comment by susolank** [comment]
@lmazuel Can you please review this PR. Changes have already been approved by others but PR is blocked because .NET SDK check has been failing for so many days.

**Review by allenjzhang — DISMISSED** [review]
.NET build error was due to the 400 and 409 declarations in the Response section. Two options:
1. Remove 400 and 409
2. Leave 400 and 409 but remove the "schema" only leave the description.

I would prefer option 1 as these are common errors handled under "default". No need to specially call them out.

**Comment by heaths** [comment]
Agreed - just stick with the `default` error response.

**Comment by allenjzhang** [comment]
I approved the breaking change. Please fix the model validation and we can proceed.

**Comment by susolank** [comment]
@allenjzhang When you get a chance, can you merge this PR because I don't have permission to do it. No additional changes will be made in this PR.

**Pull request merged**
