### PR TITLE
[Monitor] Fixing linter issues and some documentation issues

### PR DESCRIPTION
**Pull request by gucalder**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [x] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

### CODE REVIEW

**Comment by anuchandy** [comment]
@vishrutshah can you please take a look as well? this PR basically addresses the issue you opened https://github.com/Azure/azure-rest-api-specs/issues/887

**Review by vishrutshah — CHANGES_REQUESTED** [review]
@gucalder PR description says "Making resource name readonly". I do not see that change in this PR or Did I miss something? 

Other changes LGTM!

**Comment by gucalder** [comment]
I have some other changes.

**Comment by gucalder** [comment]
Adding change to fix issue #1006

**Comment by gucalder** [comment]
Issue #982 is obsolete due to issue #1017.

**Comment by gucalder** [comment]
Issue #899 was a question. The caller in in that operation (ListTenantEvents) must have tenant level permissions. This is something the caller must discuss with ARM.

**Comment by gucalder** [comment]
Issue #998 (adding "default" responses to all operations) is also addressed in these changes.

**Comment by gucalder** [comment]
The integration process could not find the autorest dll, that seems to be the cause of the checking failures.

**Comment by gucalder** [comment]
The change to make resource name readonly is already included. Perhaps I added it in the title by mistake, but all my changes are pushed already.

**Comment by gucalder** [comment]
The change to  make resource name readonly is commit a213a7f2f16145e2ab68904ba4a30950ed9ca8a0 included in this PR some days ago.

**Comment by vishrutshah** [comment]
Closing and reopening PR to run travis with latest AutoRest nightly.

**Comment by gucalder** [comment]
The first check failed in arm-automation (composite file is invalid).
The second check, I am not sure where it failed or why.

**Comment by gucalder** [comment]
Arm-automation has a composite file with only one document referenced, the minimum is 2 documents.

**Comment by gucalder** [comment]
The one check that fails is Python. I do not know why it fails, but it does not seem to be an issue with a spec.

**Comment by anuchandy** [comment]
@gucalder team is working on resolving CI issue, we will restart the job once it is resolved.

**Comment by anuchandy** [comment]
This issue "Arm-automation has a composite file with only one document referenced, the minimum is 2 documents." is fixed in this PR https://github.com/Azure/autorest/pull/2009, let me close this PR and reopen so that travis re-run this with updated autorest.

**Comment by gucalder** [comment]
Great, it is working fine now.

**Comment by anuchandy** [comment]
@gucalder could you address @vishrutshah comment https://github.com/Azure/azure-rest-api-specs/pull/996#pullrequestreview-25373112?

**Comment by gucalder** [comment]
Sure. On [#996 (review)](https://github.com/Azure/azure-rest-api-specs/pull/996#pullrequestreview-25373112). The change to make resource name readonly is commit a213a7f included in this PR some days ago.

**Comment by vishrutshah** [comment]
@gucalder Could you please fix the model validation errors for [arm-monitor/2016-03-01/swagger/alertRules_API.json](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/211095331#L1014)

**Comment by gucalder** [comment]
RuleCondition is a polymorphic type, one of the derived types (ThresholdRuleCondition) contains 'timeAggregation', 'windowSize', and 'threshold'. The example looks correct.
RuleDataSource is also a polymorphic type, one of the derived type (RuleMetricDataSource) constains 'metricName'. Here too the example looks correct.

NOTE: I removed 'metricNamespace' from the examples for get and list. I removed it from put before.

**Comment by vishrutshah** [comment]
@gucalder You are right. Currently model validator is not resolving polymorphic object corrects. 

Although I see that the your example of [AlertRules_CreateOrUpdate](https://github.com/AuxMon/azure-rest-api-specs/blob/9d973ea74275f3402f81e293d21d9ae3bc9f6793/arm-monitor/2016-03-01/swagger/alertRules_API.json#L78) is missing `operator` which you have marked as required for the [ThresholdRuleCondition ](https://github.com/AuxMon/azure-rest-api-specs/blob/9d973ea74275f3402f81e293d21d9ae3bc9f6793/arm-monitor/2016-03-01/swagger/alertRules_API.json#L475)model. Is that an inconsistency?

**Comment by gucalder** [comment]
I checked the code and the objects returned by the server and I confirm that operator is both required and returned.
I do not know why  I do not have it in the examples since I capture them from actual responses from the servers. I added the "operator" to all the examples.

**Review by vishrutshah — APPROVED** [review]

**Comment by gucalder** [comment]
Thanks!

**Pull request merged**
