### PR TITLE
[NetAppFiles] Anf 8208 update swagger rest api to 2020 09 01

### PR DESCRIPTION
**Pull request by audunn**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>
Adds new properties 
- securityOperators to active directory. 
- smbEncryption and smbContinuouslyAvailable to volume properties
-  Fix error in description of Resync volume replication operation that would confuse users. Non functional change for documentation. 
- Fix error in example for throughputMibps value in VolumeProperties
- Added missing nextlink value to volumes

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.

 Adding new API(s)
 Adding a new API version
 Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by audunn** [comment]
note sure why pipeline is failing, permission issue?

**Comment by zhenglaizhang** [comment]
> note sure why pipeline is failing, permission issue?
> @zhenglaizhang Zhenglai Zhang FTE can you help?
SDK azure-sdk-for-net failed by known issue, and sdk owner is looking at this and will fix this next week

**Comment by audunn** [comment]
Now failing on go SDK another permission issue?
@zhenglaizhang can you help?

**Comment by zhenglaizhang** [comment]
> Now failing on go SDK another permission issue?
> @zhenglaizhang can you help?

go sdk owner is fixing the known issue, stay tuned please.

**Comment by audunn** [comment]
@zhenglaizhang @ArcturusZhang  Is there anything we can do about those errors in the pipeline?

`Error: Cannot find module '/home/vsts/work/1/s/scripts/momentOfTruth.js'`
`Error: Cannot find module '/home/vsts/work/1/s/scripts/modelValidation.js'`
`Error: Cannot find module '/home/vsts/work/1/s/scripts/semanticValidation.js'`

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang @ArcturusZhang Is there anything we can do about those errors in the pipeline?
> 
> `Error: Cannot find module '/home/vsts/work/1/s/scripts/momentOfTruth.js'`
> `Error: Cannot find module '/home/vsts/work/1/s/scripts/modelValidation.js'`
> `Error: Cannot find module '/home/vsts/work/1/s/scripts/semanticValidation.js'`

can you rebase from Azure:master to sync up your pipeline definition?

**Comment by audunn** [comment]
@zhenglaizhang can we get this looked at or is there something blocking?

**Comment by zhenglaizhang** [comment]
@audunn as you has checked the ARM API Review Checklist, we need wait for the ARM signed off.

**Comment by audunn** [comment]
yes I am trying to get them to look at this have sent several emails

**Review by pilor — APPROVED** [review]

**Comment by audunn** [comment]
@zhenglaizhang  ARMSignedOff we should be good to go ahead right?

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang Zhenglai Zhang FTE ARMSignedOff we should be good to go ahead right?

Hi @audunn , for validation warnings in https://github.com/Azure/azure-rest-api-specs/pull/11832#issuecomment-734190211

* can you help fix the warning for R2023 - SummaryAndDescriptionMustNotBeSame and R2029 - PageableOperation?
* can help help take look at the [Staging] Cross Version BreakingChange (Base on stable version): 57 Warnings? Compared to last stable versions, it looks like you are introduce many breaking changes, in this scenario, you need to get breaking change review board required reviewed and signed off.

**Comment by audunn** [comment]
@zhenglaizhang Those warnings are for things that are not touched in this update ( R2023 and R2029 ) but we do what we can.

1. R2023  updated
2. R2029 This would require a service side change that I think is out of scope for us here, I will create an internal ticket to address this.
3. Breaking changes list looks odd there are not that many change in this update, most of the findings are in areas have not changed at all. 
The one valid change that might be triggering is operation list volumes `SnapshotPolicies_ListVolumes ` that changes from being `/{snapshotPolicyName}/listVolumes ``.../{snapshotPolicyName}/volumes` . This change was made to address an older review finding on a previous API_Version PR. In fact  `listVolumes` will still honored by the service and will still work as before (both will work as the same operation).  We could revert back to `listVolumes` not sure what would be the preferred way forward.

**Comment by zhenglaizhang** [comment]
@audunn the default value changed is because of https://github.com/Azure/azure-rest-api-specs/blob/3a1ed3e7b32f3d480cce60e2d85597f55441c8a8/specification/netapp/resource-manager/Microsoft.NetApp/stable/2020-09-01/netapp.json#L4822 is changed, this is not consider a breaking change.
So far, all looks good.

**Pull request merged**
