### PR TITLE
Adding new api-version 2022-12-01 to Microsoft.DataProtection

### PR DESCRIPTION
**Pull request by chandrasekarendran**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by visingla-ms** [comment]
>           }

Given it is repeated in all CRUD operations, it's good to define as parameter in common and use it in all operations.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:2495 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           },

You should use common-types v4 going forward. See: [https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json).

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:2485 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "x-ms-long-running-operation": true,

It is good to define the "x-ms-long-running-operation-options", using "location" or "azure-async-operation". See: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options).

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:2562 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "#/definitions/DeletedBackupInstance",

Please check, if you need these properties, to avoid nesting "properties.properties.some-property". See: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-flatten](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-flatten).

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:5020 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             "SnapshotStore",

Removing SnapshotStore from enum values, looks like a breaking change for your existing customers. They will send/expect this. You should check with azbreakchangereview@microsoft.com to review and approval for this.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:6116 in ee9bd3f. [](commit_id = ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a, deletion_comment = True)

**Comment by visingla-ms** [comment]
>             "Updating"

ProvisioningState should have 3 required states including Canceled. See: [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#provisioningstate-property](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#provisioningstate-property).

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:4439 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "version": "2022-05-01",

There is another preview version 2022-10-01, which is more recent than current base version 2022-05-01 you have taken for new api version. Just confirming if you have right base version.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:4 in ee9bd3f. [](commit_id = ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a, deletion_comment = True)

**Comment by visingla-ms** [comment]
> {

Please check for must-fix linter error(s) mentioned in report.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:1 in 2266291. [](commit_id = 2266291787b8ff0b5dff68487ef6d8e77d651d06, deletion_comment = False)

**Comment by amchandn** [comment]
> 

We realized this breaking change

> > ```
> >         "SnapshotStore",
> > ```
> 
> Removing SnapshotStore from enum values, looks like a breaking change for your existing customers. They will send/expect this. You should check with [azbreakchangereview@microsoft.com](mailto:azbreakchangereview@microsoft.com) to review and approval for this.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:6116 in [ee9bd3f](https://github.com/Azure/azure-rest-api-specs/commit/ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a). [](commit_id = [ee9bd3f](https://github.com/Azure/azure-rest-api-specs/commit/ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a), deletion_comment = True)

Is this change being referred to
https://github.com/chandrasekarendran/azure-rest-api-specs/commit/57b5da8dcd87fed597572e6c05a4d264064dee35#diff-3b0cd99cc2429115d855dd0768c34f8a1fba9a7613d0caf0c97d4e8f8f585c40

This change was done in a separate PR for resolving a customer issue and breaking change approval was received

**Comment by amchandn** [comment]
> > ```
> > "version": "2022-05-01",
> > ```
> 
> There is another preview version 2022-10-01, which is more recent than current base version 2022-05-01 you have taken for new api version. Just confirming if you have right base version.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:4 in [ee9bd3f](https://github.com/Azure/azure-rest-api-specs/commit/ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a). [](commit_id = [ee9bd3f](https://github.com/Azure/azure-rest-api-specs/commit/ee9bd3f1e8d57ea26a93515d8536208fa26c4a9a), deletion_comment = True)

We have picked up the changes that were ready to be moved to stable from preview while keeping the last stable as base version

**Comment by amchandn** [comment]
> > ```
> >         "Updating"
> > ```
> 
> ProvisioningState should have 3 required states including Canceled. See: https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#provisioningstate-property.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:4439 in [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06). [](commit_id = [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06), deletion_comment = False)

this is one of our existing resources and APIs and currently our service doesn't support Canceled as a valid Provisioning state. Can we plan for it and add it in subsequent API versions?

**Comment by amchandn** [comment]
> > ```
> >       },
> > ```
> 
> You should use common-types v4 going forward. See: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/types.json.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:2485 in [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06). [](commit_id = [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06), deletion_comment = False)

thanks, done

**Comment by amchandn** [comment]
> > ```
> >       }
> > ```
> 
> Given it is repeated in all CRUD operations, it's good to define as parameter in common and use it in all operations.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:2495 in [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06). [](commit_id = [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06), deletion_comment = False)

thanks, done

**Comment by amchandn** [comment]
> > ```
> >       "$ref": "#/definitions/DeletedBackupInstance",
> > ```
> 
> Please check, if you need these properties, to avoid nesting "properties.properties.some-property". See: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-flatten.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-12-01/dataprotection.json:5020 in [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06). [](commit_id = [2266291](https://github.com/Azure/azure-rest-api-specs/commit/2266291787b8ff0b5dff68487ef6d8e77d651d06), deletion_comment = False)

Since DeletedBackupInstance is a derived class of BackupInstance which was existing in previous API versions, not changing the client side schema for this object so as to mantain parity between the 2 classes.
We appreciate the feedback and shall try to incorporate the same in new classes introduced.

**Review by sjanamma — APPROVED** [review]
Approving based on the comments added by the previous author and reviewer

**Comment by xiaoxuqi-ms** [comment]
@ArcturusZhang @msyyc please help to review the SDK breaking changes. Thanks

**Comment by chandrasekarendran** [comment]
While removing DoNotMerge label, also removed Approved-SdkBreakingChange-Python label added by msyyc by mistake. Readded same

**Comment by tadelesh** [comment]
Approved for Go breakings since they all have been approved by breaking arch board.

**Pull request merged**
