### PR TITLE
Network october release

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Review by MikhailTryakhov — APPROVED** [review]

**Comment by MikhailTryakhov** [comment]
@lmazuel LGTM, re-ran failed job, now looks ready to be merged

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
Need to wait until NRP 109 will be deployed in national clouds

**Review by jianghaolu — APPROVED** [review]

**Comment by jianghaolu** [comment]
@MikhailTryakhov Please let me know when this can be merged. Thanks!

**Review by MikhailTryakhov — APPROVED** [review]
can be merged

**Comment by MikhailTryakhov** [comment]
@jianghaolu please merge

**Comment by jianghaolu** [comment]
@AutorestCI regenerate azure-sdk-for-java

**Pull request merged**
