### PR TITLE
Adding Maintenance RP, Private Preview PR https://github.com/Azure/azure-rest-api-specs-pr/pull/482

### PR DESCRIPTION
**Pull request by abkmr**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by KrisBash** [comment]
Please schedule a meeting with arm api review for new RP

**Comment by sergey-shandar** [comment]
@abkmr any progress on ARM review?

**Comment by abkmr** [comment]
> @abkmr any progress on ARM review?

Hi Sergey, the Microsoft.Maintenance RP Manifest has already been reviewed in the Private spec repo. See PR https://github.com/Azure/azure-rest-api-specs-pr/pull/482. We have already had API spec review as well with API review board. We are now moving from Private Preview to Public preview and hence need to publish to the public ARM spec repo.

**Comment by yungezz** [comment]
Hi @abkmr could you pls get ARM team members lable the PR as `ARMSignedOff`, then we can merge it?

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
