### PR TITLE
[Hub Generated] Review request for Microsoft.DigitalTwins to add version preview/2020-03-01-preview

### PR DESCRIPTION
**Pull request by NateLehman**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/NateLehman/azure-rest-api-specs/dev-digitaltwins-Microsoft.DigitalTwins-remove-sku...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by allenjzhang** [comment]
- Please secure approval from feature area reviewer and ensure there are no check failures.
- Once all checks have passed (for breaking changes, see next point), please add label **`ReadyForSdkReview`** to trigger Swagger/SDK review.
- If there are breaking changes, please add `Breaking Change Review` label
     - For breaking changes on **Stable** api version, you must add **`WaitForARMReview`** and obtain approval
     - For intended breaking change on **Preview** api version, PR can be merged with SDK team.

Thanks!

**Comment by allenjzhang** [comment]
> * Please secure approval from feature area reviewer and ensure there are no check failures.
> * Once all checks have passed (for breaking changes, see next point), please add label **`ReadyForSdkReview`** to trigger Swagger/SDK review.
> * If there are breaking changes, please add `Breaking Change Review` label
>   
>   * For breaking changes on **Stable** api version, you must add **`WaitForARMReview`** and obtain approval
>   * For intended breaking change on **Preview** api version, PR can be merged with SDK team.
> 
> Thanks!

The PR looks fine. Once area/feature reviewer signs off, please add label and I will merge the PR. Thanks.

**Comment by NateLehman** [comment]
@allenjzhang Hi Allen, I've made some changes to the PR. This should no longer be a breaking change. Could you recheck? After, I will ping area/feature reviewer. Thanks!

**Comment by allenjzhang** [comment]
> @allenjzhang Hi Allen, I've made some changes to the PR. This should no longer be a breaking change. Could you recheck? After, I will ping area/feature reviewer. Thanks!

Looks good.  I will merge it for you once you have signoff. Thanks!

**Review by sup-s — APPROVED** [review]

**Comment by NateLehman** [comment]
@allenjzhang I think I have given this the right tag. Feature/area reviewer @sup-s has approved. Ready to merge :)

**Comment by allenjzhang** [comment]
Thank you! Merged.

**Pull request merged**
