### PR TITLE
Salesforce V2 Read property support pageSize

### PR DESCRIPTION
**Pull request by wenqibu**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by ruowan — APPROVED** [review]

**Comment by ms-bogdan-rotaru** [comment]
@wenqibu Next time please provide a PR description (by choosing the corresponding PR template), scope of changes and acknowledgement of due diligence checklist.

**Comment by wenqibu** [comment]
Thanks @ms-bogdan-rotaru . Will take care of it next time, thanks!

**Pull request merged**
