### PR TITLE
Update tspconfig.yaml to latest schema

### PR DESCRIPTION
**Pull request by raych1**
Applied latest schema of emitter options and parameters.

### CODE REVIEW

**Comment by raych1** [comment]
@weshaggard @lirenhe , can you review this PR?

**Review by mikeharder — APPROVED** [review]
I don't know much about these emitters, but this looks reasonable to me.

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
@raych1 what is the plan to update the other tspconfig files in the repo to match the new convention?

**Comment by raych1** [comment]
> @raych1 what is the plan to update the other tspconfig files in the repo to match the new convention?

@weshaggard , I walked thru all [DPG onboarded services](https://github.com/orgs/Azure/projects/407). For the typespecs which are checked in to main, I updated them including `anomalyDetector, azureloadingtesting, codesigning, and openapi`. For the remained ones, they are either not checked in to main or in very early stage. We should point them to the sample project when they're adding typespecs.

**Pull request merged**
