### PR TITLE
Renaming MPCNetwork to follow the typespec convention

### PR DESCRIPTION
**Pull request by ckairen**
blocking https://github.com/Azure/azure-rest-api-specs/pull/25712

### CODE REVIEW

**Comment by mikeharder** [comment]
@markcowl: Do you think the folder name should be `MPCNetworkFunction` or `MpcNetworkFunction`?  The namespace in the spec is `namespace MobilePacketCore`, if this is relevant.  Either casing of the folder name would pass our rule (since the first letter is capitalized), but we should have a standard for acronym casing.

**Comment by ckairen** [comment]
> @markcowl: Do you think the folder name should be `MPCNetworkFunction` or `MpcNetworkFunction`? The namespace in the spec is `namespace MobilePacketCore`, if this is relevant. Either casing of the folder name would pass our rule (since the first letter is capitalized), but we should have a standard for acronym casing.

I think MPC makes more sense because it's an acronym, unless you have other strong thoughts for this case.

**Comment by mikeharder** [comment]
> > @markcowl: Do you think the folder name should be `MPCNetworkFunction` or `MpcNetworkFunction`? The namespace in the spec is `namespace MobilePacketCore`, if this is relevant. Either casing of the folder name would pass our rule (since the first letter is capitalized), but we should have a standard for acronym casing.
> 
> I think MPC makes more sense because it's an acronym, unless you have other strong thoughts for this case.

Let's use `Mpc` to align with .NET naming guidelines (which only recommend special-casing two-letter acryonyms):

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers

**Review by mikeharder — CHANGES_REQUESTED** [review]
Change from `MPC` to `Mpc`.

**Review by mikeharder — APPROVED** [review]

**Pull request merged**
