### PR TITLE
Update Time Series Insights spec with GA features, including Operations. 

### PR DESCRIPTION
**Pull request by sandshadow**
Highlighted changes:

- Add a GA spec
- Fix the inheritance problems with EventSourceResource and its properties and parameters. This was based on the changes @mcardosos recently made, but in a way that kept the discriminator on the EventSourceCreateOrUpdateParameters.
- Add new GA features, including operations, to both spec.

Changes have been tested by generating a CSharp client using the latest version of autorest. 

There are no autorest linter errors.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sandshadow** [comment]
@olydis My build failed while installing autorest. 

> The command "npm install -g autorest" failed and exited with 1 during .
> Your build has been stopped.

Is there a way to trigger a new build, other than pushing a new commit?

Also, the way I submitted the PR includes the old commits from when we originally added the preview spec. If you want I can try to figure out how to squash the commits and resubmit the PR. But the link in the checklist "For information on cleaning up the commits in your pull request, see this page." is broken.

**Comment by olydis** [comment]
@ravbhatnagar new features

**Comment by sandshadow** [comment]
@ravbhatnagar These are the same features you signed off on earlier this week, + an Operations handler.

**Comment by olydis** [comment]
@sandshadow indeed, the age of your first commits makes Travis use a super old configuration (that installs an old version of Node.js but then `npm i -g autorest` will pull in recent AutoRest which requires newer Node...)

So yes, it would be super helpful if you could squash or rebase your PR against current `current` 🙂

**Comment by olydis** [comment]
I just realize, you actually opened the PR against `master`, please retarget against `current`

**Pull request closed without merging**
