### PR TITLE
update typescript.md in dataprotection

### PR DESCRIPTION
**Pull request by kazrael2119**
according to this https://github.com/Azure/sdk-release-request/issues/3629#issuecomment-1407346361

### CODE REVIEW

**Review by MaryGao — APPROVED** [review]
LGTM

**Review by qiaozha — APPROVED** [review]

**Review by xiaoxuqi-ms — APPROVED** [review]

**Comment by xiaoxuqi-ms** [comment]
Hi @tadelesh , could you help to take a look at the go generation failure?

**Comment by tadelesh** [comment]
> Hi @tadelesh , could you help to take a look at the go generation failure?

It seems the pipeline has some problems. Ruoxuan is working on it.

**Pull request merged**
