### PR TITLE
Added event grid filters read APIs for Microsoft.AppConfiguration.

### PR DESCRIPTION
**Pull request by jimmyca15**
The Microsoft.AppConfiguration supports sending to events to event grid. Thus we implement the standard /eventGridFilters API. These have been called out as undocumented by live validation.

Autorest validation results in no errors.

### CODE REVIEW

**Comment by PhoenixHe-msft** [comment]
@jimmyca15 Please fix the model validation error

**Comment by jimmyca15** [comment]
@PhoenixHe-msft fixed.

**Comment by jimmyca15** [comment]
@PhoenixHe-msft I'm thinking this should be good to merge now. Is anything else needed?

**Comment by jimmyca15** [comment]
Swagger live validation is going to exclude this operation so we don't need to document it.

**Pull request closed without merging**
