### PR TITLE
Fixing the spec for DSCConfigurations.

### PR DESCRIPTION
**Pull request by vrdmr**
### Description
The correct type was not being returned. This is in line with the fixes done in #3363.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by vrdmr** [comment]
The serialization issue in dotnet/Go SDK is mentioned in details here ([slack link](https://azuresdk.slack.com/archives/C0ZEZUEM7/p1530557366000053)), but tl;dr is that Autorest generates code which expects the output schema to be json and we return file. This causes serialization issues and is breaking out current SDK users (our SDK is still in the preview though).

FYI @vladbarosan @jhendrixMSFT

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
This is causing the linter to fail on the example.  See the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/421665373).  I think the body needs to be tweaked slightly, see https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/examples/getRunbookDraftContent.json which is very similar.

**Comment by vrdmr** [comment]
@jhendrixMSFT I'll take a look and send the fix asap.

**Comment by vrdmr** [comment]
@jhendrixMSFT The problem is with Autorest as well as our spec. We could have done better design and returned a JSON response. Also, autorest does not understand schema of `type:file` well.

When I run `oav validate-example Microsoft.Automation/stable/2015-10-31/runbook.json`, I get the same issue with runbook as well.

```
error: Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook draft content" in operation "RunbookDraft_GetContent".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message:
   'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook draft content" in operation "RunbookDraft_GetContent".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ] }
error:
{ code: 'RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE',
  id: 'OAV111',
  message:
   'Following response status codes "200" for operation "RunbookDraft_ReplaceContent" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.' }
error: Found errors in validating the response with statusCode "200" for x-ms-example "Create or update runbook draft" in operation "RunbookDraft_ReplaceContent".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message:
   'Found errors in validating the response with statusCode "200" for x-ms-example "Create or update runbook draft" in operation "RunbookDraft_ReplaceContent".',
  innerErrors:
   [ { code: 'RESPONSE_STATUS_CODE_NOT_IN_EXAMPLE',
       id: 'OAV111',
       message:
        'Following response status codes "200" for operation "RunbookDraft_ReplaceContent" were present in the swagger spec, however they were not present in x-ms-examples. Please provide them.' } ] }
error: Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook content" in operation "Runbook_GetContent".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message:
   'Found errors in validating the response with statusCode "200" for x-ms-example "Get runbook content" in operation "Runbook_GetContent".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ] }
```

For DSCConfiguration
```
$ oav validate-example Microsoft.Automation/stable/2015-10-31/dscConfiguration.json
error: Found errors in validating the response with statusCode "200" for x-ms-example "Get DSC Configuration content" in operation "DscConfiguration_GetContent".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message:
   'Found errors in validating the response with statusCode "200" for x-ms-example "Get DSC Configuration content" in operation "DscConfiguration_GetContent".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'file', 'string' ],
            message: 'Expected type file but found type string',
            path: [] } ],
       message: 'Invalid body: Expected type file but found type string',
       path: [] } ] }
```

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
