### PR TITLE
chore: jsonfmt logic

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/logic/**/*.json"`

### CODE REVIEW

**Comment by nschonni** [comment]
Adjusted the examples for the "MDN" and "NRR" casing to match the preview API, but since it's a preview api, maybe it's better to do the reverse

**Comment by nschonni** [comment]
@jhendrixMSFT I pulled out the example changes to make this easier to land. I can submit those later

**Comment by jhendrixMSFT** [comment]
@nschonni thanks I was gonna suggest that but have been sidetracked with other stuff.

**Comment by nschonni** [comment]
@jhendrixMSFT no worries, they didn't even resolve all the model validation issues 🤷‍♂

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
