### PR TITLE
Updating MFE April 2023

### PR DESCRIPTION
**Pull request by kseager**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
>             "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter"

note, latest version is v5/types.json

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:24 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>               "$ref": "#/definitions/CodeContainerResourceArmPaginatedResult"

I suggest it should NOT have ARM or Azure in the type name.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:53 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "$ref": "./examples/Registry/CodeContainer/list.json"

Use fuller file names so its clear what the example is listing

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:59 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>               }

nit, do we need to document it? Its a standard optional HTTP header. If you document it like this you're basically just adding an promise to keep returning it with values in this range, with 202 responses.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:127 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "description": "Container name.",

Why is this parameter called a 'codeName' if its really meaning a 'containerName'?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:173 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "description": "Container name.",

Maybe it'd be good to using the fuller 'codeContainerName'?

---
In reply to: [1470983872](https://github.com/Azure/azure-rest-api-specs/pull/23026#issuecomment-1470983872) [](http://example.com/codeflow?ancestors=1470983872)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:173 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>         ],

nit, I think you can just put these at the top level, with the implication that all your APIs produce these - unless you have some that don't?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:212 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "in": "path",

ultra-nit, when reading these, I like seeing 'name' above path, I tend to assume that 'name', as the identifier of a parameter, is going to be at the top.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:383 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "in": "path",

If you're using a code generator its really not worth fixing though.

---
In reply to: [1470985341](https://github.com/Azure/azure-rest-api-specs/pull/23026#issuecomment-1470985341) [](http://example.com/codeflow?ancestors=1470985341)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:383 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "in": "path",

If you're doing them manually you could do the common Parameter definitions section below, and just reference them all using $ref. That way you only have to define all these properties in one place.

---
In reply to: [1470985551](https://github.com/Azure/azure-rest-api-specs/pull/23026#issuecomment-1470985551) [](http://example.com/codeflow?ancestors=1470985551,1470985341)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:383 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/codes/{codeName}": {

More cognitive dissonance. Why are they called 'codes' here, code containers in docs, and 'containers' yet elsewhere? (Delete container). Is there any good reason not to just call the resource type codeContainers?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:67 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/codes/{codeName}": {

Or maybe you'd like to drop or deemphasize the 'container' naming??

---
In reply to: [1470986668](https://github.com/Azure/azure-rest-api-specs/pull/23026#issuecomment-1470986668) [](http://example.com/codeflow?ancestors=1470986668)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:67 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>               }

[On the other hand, maybe we should get more standard header definitions like this in common-types so they can be reused by everyone?]

---
In reply to: [1470983256](https://github.com/Azure/azure-rest-api-specs/pull/23026#issuecomment-1470983256) [](http://example.com/codeflow?ancestors=1470983256)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json:127 in c9204c6. [](commit_id = c9204c645aa1560566b3bddb0c6089223bdd1565, deletion_comment = False)

**Comment by kseager** [comment]
close in favor of https://github.com/Azure/azure-rest-api-specs/pull/23164

**Pull request closed without merging**
