### PR TITLE
Enable multiple partner servers and failover of read-only endpoint for SQL DB Failover Group in version 2023-02-01-preview.

### PR DESCRIPTION
**Pull request by lobashh**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month (August).
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ericshape** [comment]
we are asking exception for these resource name restriction rules; because SQL RP has not enabled this restriction feature


❌ ResourceNameRestriction | The resource name parameter 'serverName' should be defined with a 'pattern' restriction.Location: Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json#L403 | RPC-Uri-V1-05
-- | -- | --
❌ ResourceNameRestriction | The resource name parameter 'failoverGroupName' should be defined with a 'pattern' restriction.Location: Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json#L403 | RPC-Uri-V1-05

**Comment by v-xuto** [comment]
@lobash Please contact Breaking Change Board owner to review the `breaking change` in this PR, you can follow this [comments](https://github.com/Azure/azure-rest-api-specs/pull/24132#issuecomment-1560323238).
And, contact the ARM team to review the `lintdiff` error. If it's ok, let them to add label `Approved-LintDiff`.

**Comment by v-xuto** [comment]
@JeffreyRichter Please help review the breaking change in this PR.

**Comment by v-xuto** [comment]
@lobash Please contact the `ARM team` to review the lintdiff error. If it's ok, let them to add label `Approved-LintDiff`.

**Comment by SharanSingh** [comment]
> 

@v-xuto can you please paste the alias of ARM team or some point of contact from the ARM team to get the lint diff approved?

**Comment by v-xuto** [comment]
@mentat9 Could you help review the `LintDiff` error? If you feel okay, please add label `Approved-LintDiff`. Thanks a lot.

**Comment by lobashh** [comment]
> we are asking exception for these resource name restriction rules; because SQL RP has not enabled this restriction feature
> 
> ❌ ResourceNameRestriction	The resource name parameter 'serverName' should be defined with a 'pattern' restriction.Location: Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json#L403	RPC-Uri-V1-05
> ❌ ResourceNameRestriction	The resource name parameter 'failoverGroupName' should be defined with a 'pattern' restriction.Location: Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json#L403	RPC-Uri-V1-05

@mentat9 FYI for the `LintDiff` error.

**Comment by mentat9** [comment]
> @mentat9 Could you help review the `LintDiff` error? If you feel okay, please add label `Approved-LintDiff`. Thanks a lot.

@ms-zhenhua is oncall this week.

**Comment by mentat9** [comment]
> > @mentat9 Could you help review the `LintDiff` error? If you feel okay, please add label `Approved-LintDiff`. Thanks a lot.
> 
> @ms-zhenhua is oncall this week.

@v-xuto, @lobash - I just noticed nobody applied the WaitForARMFeedback label, so this PR won't be on ARM review's radar. I added the label for you.

**Comment by ms-zhenhua** [comment]
>             "pattern": "^[a-z][a-z0-9]*$",

The "pattern" property is required for a resource name:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/resource-name-restriction.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/resource-name-restriction.md)

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json:423 in aa09213. [](commit_id = aa09213a404735f49a49750d213c6209a347a118, deletion_comment = True)

**Comment by ericshape** [comment]
> > ```
> >         "pattern": "^[a-z][a-z0-9]*$",
> > ```
> 
> Why delete these properties? The "pattern" property is required for a resource name: https://github.com/Azure/azure-openapi-validator/blob/main/docs/resource-name-restriction.md
> 
> Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json:423 in [aa09213](https://github.com/Azure/azure-rest-api-specs/commit/aa09213a404735f49a49750d213c6209a347a118). [](commit_id = [aa09213](https://github.com/Azure/azure-rest-api-specs/commit/aa09213a404735f49a49750d213c6209a347a118), deletion_comment = True)

@ms-zhenhua  added you to an email thread.

**Comment by ms-zhenhua** [comment]
>             }

The location header is required for 202:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md)

---
Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json:450 in aa09213. [](commit_id = aa09213a404735f49a49750d213c6209a347a118, deletion_comment = True)

**Comment by ericshape** [comment]
> > ```
> >         }
> > ```
> 
> The location header is required for 202: https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md
> 
> Refers to: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/FailoverGroups.json:450 in [aa09213](https://github.com/Azure/azure-rest-api-specs/commit/aa09213a404735f49a49750d213c6209a347a118). [](commit_id = [aa09213](https://github.com/Azure/azure-rest-api-specs/commit/aa09213a404735f49a49750d213c6209a347a118), deletion_comment = True)

Can we ask for an exception for these newly added ARM rules (to pipeline)? All SQL RP's manifests are auto-generated via C# reflection. We are adding this location property in the next API version: 2023-05-01-preview. Thanks!

**Comment by lobashh** [comment]
> @mentat9 Could you help review the `LintDiff` error? If you feel okay, please add label `Approved-LintDiff`. Thanks a lot.

@v-xuto can we please get an approval for the PR now? The `Approved-LintDiff` label has been applied by the ARM team. Thanks.

**Review by ericshape — APPROVED** [review]
LGTM

**Comment by ericshape** [comment]
@lobashh please check why eaf29c4c7f8a0f0cc8487f8f558998b70aaa66ee introduced new broken pipeline

**Comment by lobashh** [comment]
> @lobashh please check why [eaf29c4](https://github.com/Azure/azure-rest-api-specs/commit/eaf29c4c7f8a0f0cc8487f8f558998b70aaa66ee) introduced new broken pipeline.
> 
> and normally, we do not manually edit any auto-generated swagger file. We just ask for exception from reviwers.

I think my manual edit introduced a whitespace character on the first line. I have pushed an update to fix the same in commit 5.

**Comment by v-xuto** [comment]
Same `azure-sdk-for-net-track2` error as PR [#23802](https://github.com/Azure/azure-rest-api-specs/pull/23802). We can ignore the failure of .NET track 2 automation for sql all the time.
For more details, check comments [#23802 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/23802#issuecomment-1553918082).

**Comment by v-xuto** [comment]
@qiaozha  Please help review JS breaking change.
@raych1  Please help review Go breaking change. 
@msyyc  Please help review Python breaking change.

**Review by v-xuto — APPROVED** [review]

**Pull request merged**
