### PR TITLE
Add Change Analysis API version from private repo

### PR DESCRIPTION
**Pull request by jewinkle**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. ASAP
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. ASAP
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jewinkle** [comment]
Here is the [branch ](https://github.com/Azure/azure-rest-api-specs-pr/tree/Azure-ChangeAnalysis/specification/changeanalysis/resource-manager) in the private repo. It is the same APIs, except one is removed since it is internal only (ComputeChanges). These changes were already reviewed by ARM

**Comment by mentat9** [comment]
@jewinkle, you need to do this part of the checklist:

Adding a new API version
-[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

This is required by ARM review in order to see the differences in REST layer. Please put your changes into a new PR that follows that requirement.

**Comment by jewinkle** [comment]
> @jewinkle, you need to do this part of the checklist:
> 
> Adding a new API version -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.
> 
> This is required by ARM review in order to see the differences in REST layer. Please put your changes into a new PR that follows that requirement.

Since I was copying over most of the APIs from the private repo, I thought it would be more useful to use that as a baseline since those were already reviewed. However I can copy the existing version first instead

**Comment by mentat9** [comment]
> > @jewinkle, you need to do this part of the checklist:
> > Adding a new API version -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.
> > This is required by ARM review in order to see the differences in REST layer. Please put your changes into a new PR that follows that requirement.
> 
> @mentat9 Since I was copying over most of the APIs from the private repo, I thought it would be more useful to use that as a baseline since those were already reviewed. However I can copy the existing version first instead

You should always add comments for the ARM reviewer if the changes have been previously reviewed with a link to the PR. We have no other reasonable way of knowing this. Can you provide a link to that PR and confirm that first commit in this PR is a copy of the files from the -pr repo with no changes?

**Comment by jewinkle** [comment]
> > > @jewinkle, you need to do this part of the checklist:
> > > Adding a new API version -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.
> > > This is required by ARM review in order to see the differences in REST layer. Please put your changes into a new PR that follows that requirement.
> > 
> > 
> > @mentat9 Since I was copying over most of the APIs from the private repo, I thought it would be more useful to use that as a baseline since those were already reviewed. However I can copy the existing version first instead
> 
> Can you provide a link to that PR and confirm that first commit in this PR is a copy of the files from the -pr repo with no changes?

@mentat9  I added a comment a few days ago with a link to the branch in -pr repo. I will also provide PR links:

Here was the [original PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/3453) in the -pr repo
Additional PRs for some small fixes:
https://github.com/Azure/azure-rest-api-specs-pr/pull/3862
https://github.com/Azure/azure-rest-api-specs-pr/pull/4348

I originally forgot to use the private repo as the first commit, but I did make sure to undo changes and have a commit with just the changes from the -pr repo. It's the most recent commit before the current one. Commit message = ["push manifest from private repo"](https://github.com/Azure/azure-rest-api-specs/pull/16160/commits/384d1358210e62e55752cc4f8a85f92bc0c40f07)

**Comment by mentat9** [comment]
OK, thanks. I can see the review and change history now. So this PR does two things: a) moves your current API version spec from private to public repo, and b) removes the computeChanges API. This is a breaking change, so I need to understand who is impacted by removing the computeChanges action. Who is using the 2021-04-01-preview API version now?

**Comment by jewinkle** [comment]
> OK, thanks @jewinkle. I can see the review and change history now. So this PR does two things: a) moves your current API version spec from private to public repo, and b) removes the computeChanges API. This is a breaking change, so I need to understand who is impacted by removing the computeChanges action. Who is using the 2021-04-01-preview API version now?

@mentat9 We aren't removing the computeChanges API, but we don't want it to be exposed to external users. This API is only to be GA compliant so that our Portal extension doesn't call our internal API directly. It is only called by our portal extension and no one else. So we marked it as InternalOnly in the swagger as referred in this wiki: [Onboarding and Updating Resource Type Metadata in Service Tree via ARM Manifest | ARM Wiki](https://armwiki.azurewebsites.net/faqs_howtos/howtos/onboard_resource_types_to_service_tree.html)

**Comment by mentat9** [comment]
> > OK, thanks @jewinkle. I can see the review and change history now. So this PR does two things: a) moves your current API version spec from private to public repo, and b) removes the computeChanges API. This is a breaking change, so I need to understand who is impacted by removing the computeChanges action. Who is using the 2021-04-01-preview API version now?
> 
> @mentat9 We aren't removing the computeChanges API, but we don't want it to be exposed to external users. This API is only to be GA compliant so that our Portal extension doesn't call our internal API directly. It is only called by our portal extension and no one else. So we marked it as InternalOnly in the swagger as referred in this wiki: [Onboarding and Updating Resource Type Metadata in Service Tree via ARM Manifest | ARM Wiki](https://armwiki.azurewebsites.net/faqs_howtos/howtos/onboard_resource_types_to_service_tree.html)

If your portal extension is calling it, then it's a public API and needs to be documented as such. Anyone can call it using REST anyway. If you want to limit access to it, you should use feature flags, not just remove it from the documentation/spec.

**Comment by jewinkle** [comment]
> > > OK, thanks @jewinkle. I can see the review and change history now. So this PR does two things: a) moves your current API version spec from private to public repo, and b) removes the computeChanges API. This is a breaking change, so I need to understand who is impacted by removing the computeChanges action. Who is using the 2021-04-01-preview API version now?
> > 
> > 
> > @mentat9 We aren't removing the computeChanges API, but we don't want it to be exposed to external users. This API is only to be GA compliant so that our Portal extension doesn't call our internal API directly. It is only called by our portal extension and no one else. So we marked it as InternalOnly in the swagger as referred in this wiki: [Onboarding and Updating Resource Type Metadata in Service Tree via ARM Manifest | ARM Wiki](https://armwiki.azurewebsites.net/faqs_howtos/howtos/onboard_resource_types_to_service_tree.html)
> 
> If your portal extension is calling it, then it's a public API and needs to be documented as such. Anyone can call it using REST anyway. If you want to limit access to it, you should use feature flags, not just remove it from the documentation/spec.

@mentat9 According to these [docs ](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/342/FAQ-and-Recommendations)
For service or feature are in Private Preview, or Limited Public Preview, suggest NOT to public swagger in the master branch of the public repo (azure-rest-api-specs ). Because these APIs are not stable, prone to breaking change (for updates to these APIs do not require break change review, or easy to get approval). API specs of service/feature/endpoint in Private Preview or Limited Public Preview are better to review and consolidate in the private repo (azure-rest-api-specs-pr ). To onboard Early Phase Live Validation may help to concrete Swagger & API quality.

I think this gives us reason to not publish this API

**Review by yantang-msft — APPROVED** [review]

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
