### PR TITLE
Storage: local user `PermissionScope` add enums for `service`

### PR DESCRIPTION
**Pull request by magodo**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by magodo** [comment]
Ping @JasonYang-MSFT

**Review by blueww — APPROVED** [review]
This change looks good.
However, it might will take SDK breaking change since the type change.

**Comment by blueww** [comment]
@magodo 
Please get the approve for the potential breaking change.
You can contact the PR assignee for more details.

@ArthurMa1978  
Do you have any comments for the potential SDK breaking change from the swagger change in the PR?

**Comment by magodo** [comment]
Ping @JasonYang-MSFT

**Comment by magodo** [comment]
Ping @jianyexi

**Comment by raych1** [comment]
@magodo , can you fix `ModelValidation` check errors and `PrettierCheck` errors? In addition, please follow above breaking change review actions to get the approval.

**Comment by tombuildsstuff** [comment]
@magodo any chance we could get this one reopened/fixed up so that we can get this merged/usable in the provider?

**Comment by magodo** [comment]
@raych1 I've updated the PR to pass the Prettier CI. Regarding the breaking change, I saw the service team has approved it: https://github.com/Azure/azure-rest-api-specs/pull/21845#issuecomment-1418421342. Meanwhile, AFAIK the breaking change review is managed by the internal review board, should I email Jefferey, or?

**Comment by raych1** [comment]
> Hi @magodo, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/21845&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.

@magodo , please follow above action to get breaking change review approval.

**Comment by raych1** [comment]
@mikekistler @JeffreyRichter , can you review the breaking change?

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
@magodo , let me know if this PR is ready to merge.

**Comment by magodo** [comment]
@raych1 I believe so as far as the service team confirms the API behaviors and adhere to not apply breaking changes..

**Comment by kazrael2119** [comment]
this js sdk breaking is caused by this pr

**Comment by tombuildsstuff** [comment]
@magodo have the service team replied yet?

**Comment by magodo** [comment]
@MaximeKjaer Would you please take a look at this PR, whether this aligns with the SRP API?

**Comment by magodo** [comment]
Kindly ping @MaximeKjaer

**Comment by magodo** [comment]
Kindly ping @MaximeKjaer

**Comment by magodo** [comment]
ping @MaximeKjaer

**Comment by MaximeKjaer** [comment]
Apologies for the delay on this. This looks fine to me, but I'm not the owner of this swagger definition. I'll forward this thread to the relevant SRP owners for a review

**Comment by magodo** [comment]
ping @MaximeKjaer

**Comment by magodo** [comment]
ping @MaximeKjaer

**Comment by tombuildsstuff** [comment]
@rkmanda any chance you could take a look/ping the Service Team?

**Comment by konrad-jamrozik** [comment]
@magodo I have removed the `Approved-BreakingChange` label because it is obsolete. Your PR will have to be re-approved. Please follow the instructions at https://aka.ms/brch. If you provide the reason why your PR was approved in the first place, this will speed up the process and help the Breaking Change Review Board apply appropriate new label. Apologies for the inconvenience!

**Pull request closed without merging**
