### PR TITLE
Use common Resource & Sku definitions in all Sql specs

### PR DESCRIPTION
**Pull request by jaredmoo**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
@lmazuel

**Comment by jaredmoo** [comment]
Hold up, we can't use the common definition of Sku. We need Tier to be a string, not this predefined SkuTier that doesn't have all our possible values. This common definition needs to be changed IMO. https://github.com/azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L184

**Comment by jaredmoo** [comment]
I also think these descriptions need to be changed. For example, this description makes no sense from an SDK user's point of view.

```
       "tier": {
        "type": "string",
        "description": "This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT."
       },
```

**Comment by jaredmoo** [comment]
Ok, latest commit is good for .net sdk. Ready to merge

**Comment by fearthecowboy** [comment]
I'm going to recommend that you copy the types that you use out of the common file and create a local `definitions.json` file locally here. when the common file is used, it's pulling in all the models, and extra stuff may be generated.

(Plus, make sure that the 'common' version is the same layout as you are expecting... some RPs had some variance in 'standard' models )

**Comment by jaredmoo** [comment]
Ok, I'll just reference my own common definitions. That's fine, I preferred them anyway ;)

**Comment by jaredmoo** [comment]
I believe there are no more regressions. Some pre-existing linter/model warnings that I am not going to fix in this change.

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Review by lmazuel — APPROVED** [review]
Looking at the Python code this is absolutely correct and I would encourage to merge asap

**Comment by marstr** [comment]
Chatted offline with Laurent, agreed that merging this post-haste is important. Deferring to his review.

**Pull request merged**
