### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version preview/2023-05-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/FumingZhang-containerservice-Microsoft.ContainerService-2023-05-02-preview...main/).
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. 06/08
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. 06/09
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
For CI failure [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915110127), it's **expected** as the reported missing API originates from two files
  - [aks/preview/2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a25bd8a7049b7a770859a965cfa53562fd25cf92/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2019-10-27-preview/openShiftManagedClusters.json), which is deprecated and replaced by [redhatopenshift](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/redhatopenshift/resource-manager).
  - [aks/preview/2022-09-02-preview/fleets.json](https://github.com/Azure/azure-rest-api-specs/blob/a25bd8a7049b7a770859a965cfa53562fd25cf92/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2022-09-02-preview/fleets.json), which has been split into an independent service with a separate SDK (package name [azure-mgmt-containerservicefleet](https://github.com/Azure/azure-rest-api-specs-pr/blob/ARMCoreRPDev/specification/containerservice/resource-manager/Microsoft.ContainerService/fleet/readme.md)).

**Comment by FumingZhang** [comment]
For [Breaking Change(Cross-Version)](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915109872), the violated rule [1011 - AddingResponseCode](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1011.md) is caused by the change in commit [a25bd8a](https://github.com/Azure/azure-rest-api-specs/pull/24245/commits/a25bd8a7049b7a770859a965cfa53562fd25cf92), which fixed the violated rule [PutResponseSchemaDescription](https://github.com/Azure/azure-openapi-validator/blob/main/docs/put-response-schema-description.md) in CI [Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13912371783) (based on commit 85209c2). Will seek approval from breaking change review board first and continue with the ARM review afterwards.

**Comment by zedy-wj** [comment]
> For CI failure [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915110127), it's **expected** as the reported missing API originates from two files
> 
> * [aks/preview/2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/a25bd8a7049b7a770859a965cfa53562fd25cf92/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2019-10-27-preview/openShiftManagedClusters.json), which is deprecated and replaced by [redhatopenshift](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/redhatopenshift/resource-manager).
> * [aks/preview/2022-09-02-preview/fleets.json](https://github.com/Azure/azure-rest-api-specs/blob/a25bd8a7049b7a770859a965cfa53562fd25cf92/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2022-09-02-preview/fleets.json), which has been split into an independent service with a separate SDK (package name [azure-mgmt-containerservicefleet](https://github.com/Azure/azure-rest-api-specs-pr/blob/ARMCoreRPDev/specification/containerservice/resource-manager/Microsoft.ContainerService/fleet/readme.md)).

Avocado errors are confirmed by the PR authors that's expected and can be ignored.

**Comment by zedy-wj** [comment]
@FumingZhang - The public main should only be merged when the service is ready. Please fix the API Readiness Check errors or provide a reason why we should ignore it.

**Comment by FumingZhang** [comment]
Hey @zedy-wj, thanks for reminding. Estimated service readiness is 06/10 (as written in PR description). I won't merge the PR before that.

As for failure in [API Readiness Check](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915110191), it seems that only [one](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2815293&view=logs&j=96f4fe09-332f-5c31-b35a-464007148e74&t=9d446b1b-8a8b-55a8-1c9a-5dad2d7193dd&l=365) operation (providers/Microsoft.ContainerService/operations) was tested, and this operation has not been taken seriously by server/manifest for a long time, I'll see if we could fix it.

**Comment by FumingZhang** [comment]
Hey @msyyc, could you please help check why CI [SDK azure-sdk-for-python-track2](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915196119) failed? From [pipeline log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2815293&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691&t=2e8ac267-e2ad-54ba-f9a7-b77ef1116f53&l=5324), the error message is
> 06:38:52.095 cmdout 	[automation_generate.sh] Exception: Found files that do not set api_version:

**Comment by msyyc** [comment]
> Hey @msyyc, could you please help check why CI [SDK azure-sdk-for-python-track2](https://github.com/Azure/azure-rest-api-specs/pull/24245/checks?check_run_id=13915196119) failed? From [pipeline log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2815293&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691&t=2e8ac267-e2ad-54ba-f9a7-b77ef1116f53&l=5324), the error message is
> 
> > 06:38:52.095 cmdout 	[automation_generate.sh] Exception: Found files that do not set api_version:

I commit https://github.com/Azure/azure-rest-api-specs/pull/24245/commits/ccbc48f77a2348e832edb4de4e55c909f5ab4946 which shall fix the failure.

**Comment by mentat9** [comment]
>         "enabled": {

ARM recommends string enum over boolean for many reasons. Consider something like activation: { Enabled, Disabled } (or similar with better names). Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review).

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-05-02-preview/managedClusters.json:7272 in ccbc48f. [](commit_id = ccbc48f77a2348e832edb4de4e55c909f5ab4946, deletion_comment = False)

**Comment by matthchr** [comment]
@mentat9 - I believe we considered using an enum for enabling this feature rather than a boolean. 

There were two reasons why we decided not to:
1. The plan is not to GA this feature. Once it's gone through preview and been vetted, we're planning to enable it by default for all clusters with no api opt-out.
2. AKS uses `enabled` booleans all over for enabling optional features (sometimes called Addons) and keeping this a boolean matches the pattern used in the rest of the API. Here are a few examples: [#1](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L4549), [#2](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5677), [#3](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L5727).

**Comment by zedy-wj** [comment]
@msyyc - Please check the Python Breaking changes. If there is no problem, please add the `Approved-SDKBreakingChange-Python` tag, thanks!

**Comment by FumingZhang** [comment]
> I commit [ccbc48f](https://github.com/Azure/azure-rest-api-specs/commit/ccbc48f77a2348e832edb4de4e55c909f5ab4946) which shall fix the failure.

The Python breaking change is caused by change https://github.com/Azure/azure-rest-api-specs/commit/ccbc48f77a2348e832edb4de4e55c909f5ab4946, the removed operations are deprecated.

**Comment by FumingZhang** [comment]
The service is ready now, please help merge the PR thanks!

**Review by live1206 — APPROVED** [review]

**Pull request merged**
