### PR TITLE
Add 2022-02-01-preview to Microsoft.MachineLearningServices

### PR DESCRIPTION
**Pull request by forteddyt**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. 
      March 1st, 2022
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
      End of March
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jorgecotillo** [comment]
>         "x-ms-long-running-operation": true

Noticed that your PUT calls seem to be async but you didn't add this property, is that intentional?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json:3337 in 3b1ac1f. [](commit_id = 3b1ac1f420a939a22e125869b16e6381001d291d, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>       "put": {

Here's an example of PUT that seems to be async without x-ms-long-running property

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json:3101 in a3e5550. [](commit_id = a3e55502b1488e7878a5faf00fa24d9b920bcb36, deletion_comment = False)

**Comment by forteddyt** [comment]
> > ```
> >   "put": {
> > ```
> 
> Here's an example of PUT that seems to be async without x-ms-long-running property
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json:3101 in [a3e5550](https://github.com/Azure/azure-rest-api-specs/commit/a3e55502b1488e7878a5faf00fa24d9b920bcb36). [](commit_id = [a3e5550](https://github.com/Azure/azure-rest-api-specs/commit/a3e55502b1488e7878a5faf00fa24d9b920bcb36), deletion_comment = False)

EnvironmentVersion is not async, and thus not decorated with the x-ms-long-running-operation property. as per [ARM (non-async) PUT guidelines](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#response):
> The resource provider should return 200 (OK) or 201 (Created) to indicate that the operation completed successfully synchronously.

where 200 means updated and 201 means created

**Comment by forteddyt** [comment]
> > ```
> >     "x-ms-long-running-operation": true
> > ```
> 
> Noticed that your PUT calls seem to be async but you didn't add this property, is that intentional?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json:3337 in [3b1ac1f](https://github.com/Azure/azure-rest-api-specs/commit/3b1ac1f420a939a22e125869b16e6381001d291d). [](commit_id = [3b1ac1f](https://github.com/Azure/azure-rest-api-specs/commit/3b1ac1f420a939a22e125869b16e6381001d291d), deletion_comment = False)

I think our async APIs are decorated properly... I'm not sure I understand which APIs you're referring to, specifically. or did my previous comment address this?

**Comment by jorgecotillo** [comment]
> > > ```
> > >     "x-ms-long-running-operation": true
> > > ```
> > 
> > 
> > Noticed that your PUT calls seem to be async but you didn't add this property, is that intentional?
> > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json:3337 in [3b1ac1f](https://github.com/Azure/azure-rest-api-specs/commit/3b1ac1f420a939a22e125869b16e6381001d291d). [](commit_id = [3b1ac1f](https://github.com/Azure/azure-rest-api-specs/commit/3b1ac1f420a939a22e125869b16e6381001d291d), deletion_comment = False)
> 
> I think our async APIs are decorated properly... I'm not sure I understand which APIs you're referring to, specifically. or did my previous comment address this?

Yes, I am making sure that your intention is to model a sync API and not async -> see here for async recommendation:
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put which specifies HTTP 201 or 200 for async as well.

**Comment by jorgecotillo** [comment]
Signing off with a small comment - the modeled POST API for now is sync but needs to be modeled as async in the upcoming api-version, reason to be async is because the API might exceed KPI/P99 of 2 seconds.

**Comment by ArcturusZhang** [comment]
Hey @forteddyt we have quite a few required CI failures, could we fix those first?

**Comment by forteddyt** [comment]
hey @ArcturusZhang - the remaining LintDiff (see https://github.com/Azure/azure-openapi-validator/issues/248) and ModelValidation failures are false negatives. I've looked into the azure-sdk-for-go gate failure and will fix the issue once I have some time. I haven't looked at the other, non-required, gates :)

Regarding the ModelValidation failures, the “secrets” property in the spec is both x-ms-secret and required. From the [x-ms-secret documentation](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-secret), this scenario should not have the property be present in responses.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
