### PR TITLE
[CDN] 2022-11-01-preview

### PR DESCRIPTION
**Pull request by ChenglongLiu**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
The contribution checklist for this draft PR is not yet complete. When the draft is ready, please complete it and send email to the current ARM API Review oncall when you are ready for ARM review.

**Comment by TimLovellSmith** [comment]
>             "description": "Ok and the operation will complete synchronously.",

isn't it completed already?

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/cdn.json:481 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             }

Why would 200 need location header? Normally only 202 does.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/cdn.json:486 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     },

Please refactor definitions from common-types/v4/managedidentity.json if possible

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/cdn.json:6887 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "ProfileChangeSkuWafMapping": {

'Waf' looks a bit funny, what is this, Windows Azure Firewall? Can we come up with a better name?

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:4027 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "description": "Waf mapping for the profile upgrade",

Whats a 'waf'?

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:4053 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     },

I think best practice is to remove all these definitions and reference the parameter definitions in common-types/v3/types.json instead

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:6070 in fa36b8a. [](commit_id = fa36b8a8545c01cb44145b9855a89c9b7428b5c7, deletion_comment = False)

**Comment by ChenglongLiu** [comment]
> > ```
> >       "description": "Waf mapping for the profile upgrade",
> > ```
> 
> Whats a 'waf'?
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:4053 in [fa36b8a](https://github.com/Azure/azure-rest-api-specs/commit/fa36b8a8545c01cb44145b9855a89c9b7428b5c7). [](commit_id = [fa36b8a](https://github.com/Azure/azure-rest-api-specs/commit/fa36b8a8545c01cb44145b9855a89c9b7428b5c7), deletion_comment = False)

**Comment by ChenglongLiu** [comment]
> > ```
> >       "description": "Waf mapping for the profile upgrade",
> > ```
> 
> Whats a 'waf'?
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:4053 in [fa36b8a](https://github.com/Azure/azure-rest-api-specs/commit/fa36b8a8545c01cb44145b9855a89c9b7428b5c7). [](commit_id = [fa36b8a](https://github.com/Azure/azure-rest-api-specs/commit/fa36b8a8545c01cb44145b9855a89c9b7428b5c7), deletion_comment = False)

Update the description.

**Comment by ChenglongLiu** [comment]
> Update the description.



> > ```
> > "ProfileChangeSkuWafMapping": {
> > ```
> 
> 'Waf' looks a bit funny, and overall the name feels hard to understand the intent, what is this, Windows Azure Firewall? Can we come up with a better name?
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:4027 in [50fc39d](https://github.com/Azure/azure-rest-api-specs/commit/50fc39dd34b21eed8e40b6de17d48facbcaa1a08). [](commit_id = [50fc39d](https://github.com/Azure/azure-rest-api-specs/commit/50fc39dd34b21eed8e40b6de17d48facbcaa1a08), deletion_comment = False)

Update the description. 'Waf' indicate web application firewall. We also use 'Waf' in our portal and in the old version of swagger, we should keep it consistent.

**Comment by TimLovellSmith** [comment]
>             "description": "Name of the Azure Front Door Standard or Azure Front Door Premium profile or CDN profile which is unique within the resource group.",

in this particular context, isn't it only going to be for CDN profiles? 

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/preview/2022-11-01-preview/afdx.json:104 in 570a6ea. [](commit_id = 570a6ea38aaa01551692320ffd945997616f23d5, deletion_comment = False)

**Review by NetRock — APPROVED** [review]

**Comment by raych1** [comment]
@chenglongliu, regard to `model validation` errors,  `id` is required field of a `resource`. Please add it to examples.

**Comment by live1206** [comment]
@fengzhou-msft could you help check the dotnet sdk generation failure?

**Comment by live1206** [comment]
@msyyc Could you help check the breaking change for python?

**Comment by live1206** [comment]
@tadelesh Could you help check the breaking change for go?

**Comment by live1206** [comment]
@qiaozha Could you help check the breaking change for js?

**Comment by tadelesh** [comment]
Approved for Go breaking changes, includes: `non-LRO` to `LRO`, add `x-ms-enum`, change model ref.

**Review by live1206 — APPROVED** [review]

**Pull request merged**
