### PR TITLE
split compute.json into multiple files

### PR DESCRIPTION
**Pull request by gatneil**

### CODE REVIEW

**Comment by gatneil** [comment]
DO NOT MERGE

**Comment by salameer** [comment]
@gatneil what's the request for this PR? is it only review?

I guess my question is what's the next step after reviewing?

**Comment by fearthecowboy** [comment]
Adding  @hyonholee and @huangpf (on the advice of @amarzavery )

**Comment by huangpf** [comment]
@gatneil @fearthecowboy 
Please close the PR for now, until we have sign-off from the service team. Thanks.

**Pull request closed without merging**
