### PR TITLE
Update readMe for CognitiveService

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Update ReadMe Path to match with updated Repo Structure

### CODE REVIEW

**Comment by chidozieononiwu** [comment]
cc @dsgouda
cc @weshaggard

**Comment by shahabhijeet** [comment]
@dsgouda can you take a look

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
NET sdk failures are expected. @shahabhijeet Please feel free to merge

**Comment by dsgouda** [comment]
@veronicagg the SDK failures (including C#) are unrelated, please merge the PR since we do not have the permissions

**Pull request merged**
