### PR TITLE
AzureDataShare: Adding version 2020-09-01 swagger.

### PR DESCRIPTION
**Pull request by ahermas**
Just duplicating the files of the previous stable version 2019 into the newly created folder for version 2020-09-01.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ahermas** [comment]
AzureDataShare: First Commit : Just duplicating the files of the previous stable version 2019 into the newly created folder for version 2020-09-01.

The upcoming second commit will be the real files for the new 2020-09-01. It will include the systemData property of azure resources.

**Comment by ahermas** [comment]
The second commit is the that actually add the 2020-09-01 files.

This is a branch new PR doine what was supposed to be done in this [PR](https://github.com/Azure/azure-rest-api-specs/pull/11532).
@pilor @j5lim @varunkumta Kindly review :)

**Comment by erich-wang** [comment]
Adding label `WaitForARMFeedback` as there's new API added for new version.

**Comment by ahermas** [comment]
> Adding label `WaitForARMFeedback` as there's new API added for new version.
> @ahermas , please fix CI error first, thanks.

Hi @erich-wang ,

Thanks for your comment.  I fixed the CI issue and now all checks have passed.

Thanks

**Comment by jorgecotillo** [comment]
Please mark the appropriate checkboxes from above, without marking them we cannot proceed to review your PR, we need to ensure that you reviewed our documentation repository and are following the standard.

**Comment by jorgecotillo** [comment]
>       "get": {

can the endpoint be called invitations instead of listInvitations? list* conflicts with our guidance around returning secrets:

[https://armwiki.azurewebsites.net/rp_onboarding/process/property_design_best_practices.html#secrets](https://armwiki.azurewebsites.net/rp_onboarding/process/property_design_best_practices.html#secrets)

---
Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:315 in 1128b45. [](commit_id = 1128b453365f8081814c65173da5ce1da1213c58, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>         "fillGapWithZero": {

Is this a boolean?

---
Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:5142 in 1128b45. [](commit_id = 1128b453365f8081814c65173da5ce1da1213c58, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>     "SystemData": {

If you are going to use your own definition please follow the one from common-type:
[https://github.com/Azure/azure-rest-api-specs/blob/56348ad232409e3266eaef220e88ae5d64f49ad7/specification/common-types/resource-management/v1/types.json#L441](https://github.com/Azure/azure-rest-api-specs/blob/56348ad232409e3266eaef220e88ae5d64f49ad7/specification/common-types/resource-management/v1/types.json#L441)

---
Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:6665 in 1128b45. [](commit_id = 1128b453365f8081814c65173da5ce1da1213c58, deletion_comment = False)

**Comment by ahermas** [comment]
> > ```
> >     "fillGapWithZero": {
> > ```
> 
> Is this a boolean?
> 
> Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:5142 in [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58). [](commit_id = [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58), deletion_comment = False)

@jorgecotillo  fillGapWithZero is a string but we set it to "true" in our code for eg.

**Comment by ahermas** [comment]
@jorgecotillo I updated the PR to address your comment about systemdata to follow the property types from common-type.

**Comment by sarajang** [comment]
> > ```
> >   "get": {
> > ```
> 
> Not a blocker since the endpoint seems that already exists for the previous version, but can it be called 'invitations' instead of listInvitations? list* conflicts with our guidance around returning secrets:
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/property_design_best_practices.html#secrets
> 
> Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:315 in [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58). [](commit_id = [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58), deletion_comment = False)

@jorgecotillo this is a tenant level fan out query that returns a list of items, we had clarified this in our initial review with ARM and went with their suggestion.

**Comment by sarajang** [comment]
> > ```
> >     "fillGapWithZero": {
> > ```
> 
> Is this a boolean?
> 
> Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:5142 in [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58). [](commit_id = [1128b45](https://github.com/Azure/azure-rest-api-specs/commit/1128b453365f8081814c65173da5ce1da1213c58), deletion_comment = False)

@jorgecotillo this is the schema to be integrated with diagnostics logging team.

**Comment by ahermas** [comment]
@jorgecotillo I know that a check is still in progress but please let me know if you're ok with the recent changes to system data and  Santosh's comments.

**Comment by jorgecotillo** [comment]
>       "post": {

just making sure, this is not an async operation right?

---
Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:1450 in c334ab5. [](commit_id = c334ab5dad84e094592a320a29d58bae85f93ad5, deletion_comment = False)

**Comment by jorgecotillo** [comment]
>         "fillGapWithZero": {

If this is a string with a value "true" I assume it can be set to "false" which makes this a boolean. Please update the type to ensure type consistency.

---
In reply to: [772095284](https://github.com/Azure/azure-rest-api-specs/pull/12745#issuecomment-772095284) [](ancestors = 772095284)

---
Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:5142 in 1128b45. [](commit_id = 1128b453365f8081814c65173da5ce1da1213c58, deletion_comment = False)

**Comment by jorgecotillo** [comment]
Address fillGapWithZero type inconsistency please.

**Comment by sarajang** [comment]
> > ```
> >   "post": {
> > ```
> 
> just making sure, this is not an async operation right?
> 
> Refers to: specification/datashare/resource-manager/Microsoft.DataShare/stable/2020-09-01/DataShare.json:1450 in [c334ab5](https://github.com/Azure/azure-rest-api-specs/commit/c334ab5dad84e094592a320a29d58bae85f93ad5). [](commit_id = [c334ab5](https://github.com/Azure/azure-rest-api-specs/commit/c334ab5dad84e094592a320a29d58bae85f93ad5), deletion_comment = False)

No, this is not an async operation. It returns 200.

**Comment by ahermas** [comment]
> Address fillGapWithZero type inconsistency please.

@jorgecotillo  I've addressed the "fillGapWithZero type inconsistency"
Thanks

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
