### PR TITLE
[Hub Generated] Review request for Microsoft.CostManagement to add version preview/2019-05-01-preview

### PR DESCRIPTION
**Pull request by gahorowi**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/gahorowi/azure-rest-api-specs/dev-cost-management-Microsoft.CostManagement-2019-05-01-preview...master).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6178 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6178/commits/eabc6010fbdd620b92c86b6d29436365294e7624

**Comment by praries880** [comment]
@azuresdkci re-test this please

**Comment by gahorowi** [comment]
@praries880 how can marge this PR ?

**Comment by ravbhatnagar** [comment]
@gahorowi - Cost management has a couple of PRs open to add new APIs/make changes to this RP. Views APIs are not present in this PR and similarly budget APis are not present in the other one. Can you please work with the owner of the APis in other PR and have a joint API review?
https://github.com/Azure/azure-rest-api-specs/pull/5895

**Comment by bgsky** [comment]
This PR introduces Budget API, and is part of another one merged and closed, https://github.com/Azure/azure-rest-api-specs/pull/5956.

**Pull request closed without merging**
