### PR TITLE
[Hub Generated] Review request for Microsoft.Marketplace to add version stable/2020-01-01

### PR DESCRIPTION
**Pull request by olrakovs-zz**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/olrakovs/azure-rest-api-specs/dev-marketplace-Microsoft.Marketplace-2020-01-01...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by NullMDR** [comment]
@olrakovs Please add swagger-to-sdk section in readme.md. You can find other service's readme.md for reference. They are related to SDK generation.

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by olrakovs** [comment]
Hey @NullMDR ,
Can you please advise how can I find the reason for BreakingChange error?

TypeError: Cannot read property 'split' of null
    at updateChangeProperties (/home/vsts/work/1/s/node_modules/@azure/oad/dist/lib/validators/openApiDiff.js:23:31)
    at /home/vsts/work/1/s/node_modules/@azure/oad/dist/lib/validators/openApiDiff.js:199:148
    at Array.map (<anonymous>)
    at OpenApiDiff.processViaOpenApiDiff (/home/vsts/work/1/s/node_modules/@azure/oad/dist/lib/validators/openApiDiff.js:199:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOad (/home/vsts/work/1/s/node_modules/@azure/rest-api-specs-scripts/dist/breaking-change.js:58:18)
    at async Object.runScript [as breakingChange] (/home/vsts/work/1/s/node_modules/@azure/rest-api-specs-scripts/dist/breaking-change.js:132:27)


doesnt tell me a lot, 

thank you for your help

**Comment by olrakovs** [comment]
@NullMDR ,can you please help or advise  with the BreakingChange faliure?

**Comment by akning-ms** [comment]
Hi @olrakovs, Can you give us more info for this PR? 1. what is the reason to rename the property name. e.g in Offer.  as it will cause breaking change in your stable version.
And what is the status of your stable version 2020-01-01, it is released/GA, and what SDK/CLI/PS will you plan to release or released base on this API?  these info is useful for us to make decide to by pass the breaking change error. Thanks

**Comment by olrakovs** [comment]
Hi @akning-ms ,the last changes were made to be adjusted to current stable version.
The version is not GA yet and was released only for JEDI.
I am planning to release .net sdk as soon as this merge will completed. Currently its pipeline fails, is it because of breakingChange pipeline?

**Pull request merged**
