### PR TITLE
Reduce duplication in generated SDKs

### PR DESCRIPTION
**Pull request by austintolani**
The following changes are to reduce duplication in generated Go SDK:
- Changed from using `common-types/resource-management/v5/types.json#/definitions/OperationStatusResult` to `common-types/resource-management/v3/types.json#/definitions/OperationStatusResult`.
- Removed `lenient-model-deduplication: true` property in `readme.go.md`. 
- Updated all references to `../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse` to `../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse`. This is to prevent the following error in the Go SDK pipeline: 
```
cmderr	[generator automation-v2] [ERROR] - properties.details.$ref: "#/components/schemas/schemas:237" => "#/components/schemas/schemas:335"; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
cmderr	[generator automation-v2] [ERROR] fatal   | Error: 1 errors occured -- cannot continue.
cmderr	[generator automation-v2] [ERROR] fatal   | Process() cancelled due to failure
cmderr	[generator automation-v2] [ERROR] error   |   Error: Plugin prechecker reported failure.
```

The result is 4 breaking changes, which I believe is expected as we are removing the auto-generated types:
```
info	[Changelog] ### Breaking Changes
info	[Changelog]
info	[Changelog] - Type of `OperationStatus.Error` has been changed from `*ErrorDetailAutoGenerated` to `*ErrorDetail`
info	[Changelog] - Type of `OperationStatusResult.Error` has been changed from `*ErrorDetailAutoGenerated` to `*ErrorDetail`
info	[Changelog] - Struct `ErrorDetailAutoGenerated` has been removed
info	[Changelog]
info	[Changelog] ### Features Added
info	[Changelog]
info	[Changelog] - New value `ProvisioningStateConfiguringAAD` added to enum type `ProvisioningState`
info	[Changelog] - New enum type `AccessPolicyAssignmentProvisioningState` with values `AccessPolicyAssignmentProvisioningStateCanceled`, `AccessPolicyAssignmentProvisioningStateDeleted`, `AccessPolicyAssignmentProvisioningStateDeleting`, `AccessPolicyAssignmentProvisioningStateFailed`, `AccessPolicyAssignmentProvisioningStateSucceeded`, `AccessPolicyAssignmentProvisioningStateUpdating`
info	[Changelog] - New enum type `AccessPolicyProvisioningState` with values `AccessPolicyProvisioningStateCanceled`, `AccessPolicyProvisioningStateDeleted`, `AccessPolicyProvisioningStateDeleting`, `AccessPolicyProvisioningStateFailed`, `AccessPolicyProvisioningStateSucceeded`, `AccessPolicyProvisioningStateUpdating`
info	[Changelog] - New enum type `AccessPolicyType` with values `AccessPolicyTypeBuiltIn`, `AccessPolicyTypeCustom`
info	[Changelog] - New enum type `UpdateChannel` with values `UpdateChannelPreview`, `UpdateChannelStable`
info	[Changelog] - New function `NewAccessPolicyAssignmentClient(string, azcore.TokenCredential, *arm.ClientOptions) (*AccessPolicyAssignmentClient, error)`
info	[Changelog] - New function `*AccessPolicyAssignmentClient.BeginCreateUpdate(context.Context, string, string, string, CacheAccessPolicyAssignment, *AccessPolicyAssignmentClientBeginCreateUpdateOptions) (*runtime.Poller[AccessPolicyAssignmentClientCreateUpdateResponse], error)`
info	[Changelog] - New function `*AccessPolicyAssignmentClient.BeginDelete(context.Context, string, string, string, *AccessPolicyAssignmentClientBeginDeleteOptions) (*runtime.Poller[AccessPolicyAssignmentClientDeleteResponse], error)`
info	[Changelog] - New function `*AccessPolicyAssignmentClient.Get(context.Context, string, string, string, *AccessPolicyAssignmentClientGetOptions) (AccessPolicyAssignmentClientGetResponse, error)`
info	[Changelog] - New function `*AccessPolicyAssignmentClient.NewListPager(string, string, *AccessPolicyAssignmentClientListOptions) *runtime.Pager[AccessPolicyAssignmentClientListResponse]`
info	[Changelog] - New function `NewAccessPolicyClient(string, azcore.TokenCredential, *arm.ClientOptions) (*AccessPolicyClient, error)`
info	[Changelog] - New function `*AccessPolicyClient.BeginCreateUpdate(context.Context, string, string, string, CacheAccessPolicy, *AccessPolicyClientBeginCreateUpdateOptions) (*runtime.Poller[AccessPolicyClientCreateUpdateResponse], error)`
info	[Changelog] - New function `*AccessPolicyClient.BeginDelete(context.Context, string, string, string, *AccessPolicyClientBeginDeleteOptions) (*runtime.Poller[AccessPolicyClientDeleteResponse], error)`
info	[Changelog] - New function `*AccessPolicyClient.Get(context.Context, string, string, string, *AccessPolicyClientGetOptions) (AccessPolicyClientGetResponse, error)`
info	[Changelog] - New function `*AccessPolicyClient.NewListPager(string, string, *AccessPolicyClientListOptions) *runtime.Pager[AccessPolicyClientListResponse]`
info	[Changelog] - New function `*Client.BeginFlushCache(context.Context, string, string, *ClientBeginFlushCacheOptions) (*runtime.Poller[ClientFlushCacheResponse], error)`
info	[Changelog] - New function `*ClientFactory.NewAccessPolicyAssignmentClient() *AccessPolicyAssignmentClient`
info	[Changelog] - New function `*ClientFactory.NewAccessPolicyClient() *AccessPolicyClient`
info	[Changelog] - New struct `CacheAccessPolicy`
info	[Changelog] - New struct `CacheAccessPolicyAssignment`
info	[Changelog] - New struct `CacheAccessPolicyAssignmentList`
info	[Changelog] - New struct `CacheAccessPolicyAssignmentProperties`
info	[Changelog] - New struct `CacheAccessPolicyList`
info	[Changelog] - New struct `CacheAccessPolicyProperties`
info	[Changelog] - New struct `ErrorDetail`
info	[Changelog] - New field `AADEnabled` in struct `CommonPropertiesRedisConfiguration`
info	[Changelog] - New field `UpdateChannel` in struct `CreateProperties`
info	[Changelog] - New field `UpdateChannel` in struct `Properties`
info	[Changelog] - New field `UpdateChannel` in struct `UpdateProperties`
info	[Changelog]
info	[Changelog] Total 4 breaking change(s), 52 additive change(s).
```
**This PR is into a dev branch, so does not need to be reviewed by ARM reviewers.**

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
This is a comment on the wrong PR but... I wonder did we really need 'ConfiguringAAD' provisioningState? What are you going to return to old clients who do GET on a cache in that state?

**Comment by TimLovellSmith** [comment]
I don't think these changes are actually breaking, and we probably reviewed them all before during the preview api version review, right? @austintolani

**Review by TimLovellSmith — APPROVED** [review]
Approving the PR *in my role as a redis reviewer*.

**Comment by TimLovellSmith** [comment]
I think the update is all fine from ARM POV also. Stamping it good for ARM. The main concern is SDKs right.

**Comment by koderjoker** [comment]
> This is really a comment on the wrong PR since you already made that change, but... I wonder did we really need 'ConfiguringAAD' provisioningState? What are you going to return to old clients who do GET on a cache in that state? Updating? Its probably fine as long as we do something like that.

@TimLovellSmith the ConfiguringAAD state would only be available for caches enabling/disabling AAD, which is only available from API version 2023-05-01-preview onwards. So I don't think there would be a case where old clients would have this provisioning state.

**Comment by TimLovellSmith** [comment]
> > This is really a comment on the wrong PR since you already made that change, but... I wonder did we really need 'ConfiguringAAD' provisioningState? What are you going to return to old clients who do GET on a cache in that state? Updating? Its probably fine as long as we do something like that.
> 
> @TimLovellSmith the ConfiguringAAD state would only be available for caches enabling/disabling AAD, which is only available from API version 2023-05-01-preview onwards. So I don't think there would be a case where old clients would have this provisioning state.

That assumption seems a little off-base because you could have someone e.g. configure AAD using the portal, then try to run a script against their cache... where the script still uses the old API version, so it will have to see a value that it understands.

**Review by koderjoker — APPROVED** [review]

**Pull request merged**
