### PR TITLE
Bring Back action UpdateHostname and UploadCertificate

### PR DESCRIPTION
**Pull request by solankisamir**
We need to support updatehostname and uploadcertificate actions for one more version, to avoid customers breaking change in powershell which is built on .NET client.

These actions will be deprecated in next apiversion

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by solankisamir** [comment]
@sarangan12 ping!

**Comment by sarangan12** [comment]
@solankisamir Please take a look at https://travis-ci.org/Azure/azure-rest-api-specs/jobs/287657498. Your changes have caused 2 new errors which must be fixed. Please fix them and update PR

**Comment by solankisamir** [comment]
@sarangan12 I will fix the description issue, but the other issue around certificate_password naming, we had to bring back, as we need that resource in our .NET Client, which gets integrated to powershell. To make a breaking change in powershell, we need it around for one more version.

**Comment by solankisamir** [comment]
Opened issue on self https://github.com/Azure/azure-rest-api-specs/issues/1881

**Comment by solankisamir** [comment]
@sarangan12 ping! on this. Let me know, if I am not clear.

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
