### PR TITLE
[Hub Generated] Review request for Microsoft.MachineLearningServices to add version preview/2023-06-01-preview

### PR DESCRIPTION
**Pull request by erjms**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/release-machinelearningservices-Microsoft.MachineLearningServices-2023-06-01-preview...main/).
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by erjms** [comment]
FYI breaking changes were approved via [PR 24249](https://github.com/Azure/azure-rest-api-specs/pull/24249) into this staging branch.

**Comment by erjms** [comment]
To the ARM reviewer:

**All changes in this PR have already been ARM reviewed and received ARM signoff, and all breaking changes have received approval via the following PRs into this staging branch:**

* https://github.com/Azure/azure-rest-api-specs/pull/24249
* https://github.com/Azure/azure-rest-api-specs/pull/24051
* https://github.com/Azure/azure-rest-api-specs/pull/24231
* https://github.com/Azure/azure-rest-api-specs/pull/24333

This PR was created using OpenAPI Hub following the guidelines here: [OpenAPI Hub: Adding new API version](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version); in particular, choosing the option `If you have multiple people working, Create branch and have swagger reviews on all PRs to this branch is recommended`.

**Comment by zizw123** [comment]
Hi @erjms, I understand the PRs has been signed off before, but please take a look at the lint error, we are trying to ask RPs to adopt the best practice and pattern. If anything could not be fixed, please see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process

**Comment by zizw123** [comment]
> Hi @erjms, I understand the PRs has been signed off before, but please take a look at the lint error, we are trying to ask RPs to adopt the best practice and pattern. If anything could not be fixed, please see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process

Please also ask BC team to add approved label on this

**Comment by erjms** [comment]
> Hi @erjms, I understand the PRs has been signed off before, but please take a look at the lint error, we are trying to ask RPs to adopt the best practice and pattern. If anything could not be fixed, please see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process

As discussed in the other reviews, our teams have committed to fixing these in the next API version:
[Product Backlog Item 1915864](https://msdata.visualstudio.com/Vienna/_workitems/edit/1915864): [Parent] Follow-up Tasks from 2022-06-01-preview ARM API Review

Instead of suppressing, we would like to keep the validation rules intact so that we can be sure we address them all in the future.

**Comment by mikekistler** [comment]
Breaking changes previously reviewed and approved in #24249 and #24333.

**Comment by zizw123** [comment]
> > Hi @erjms, I understand the PRs has been signed off before, but please take a look at the lint error, we are trying to ask RPs to adopt the best practice and pattern. If anything could not be fixed, please see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process
> 
> As discussed in the other reviews, our teams have committed to fixing these in the next API version:
> 
> * [Product Backlog Item 1915864](https://msdata.visualstudio.com/Vienna/_workitems/edit/1915864): [Parent] Follow-up Tasks from 2022-06-01-preview ARM API Review
> * [Update workspaceRP swagger with automation result #24333 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24333#issuecomment-1589816602)
> 
> Instead of suppressing, we would like to keep the validation rules intact so that we can be sure we address them all in the future.

Sounds good, there's a lot error in the lintDiff, you should still see if there's anything you can fix as of the current version, only for those you couldn't fix you can leave the fix and track them in next version

**Comment by erjms** [comment]
> > > Hi @erjms, I understand the PRs has been signed off before, but please take a look at the lint error, we are trying to ask RPs to adopt the best practice and pattern. If anything could not be fixed, please see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process
> > 
> > 
> > As discussed in the other reviews, our teams have committed to fixing these in the next API version:
> > 
> > * [Product Backlog Item 1915864](https://msdata.visualstudio.com/Vienna/_workitems/edit/1915864): [Parent] Follow-up Tasks from 2022-06-01-preview ARM API Review
> > * [Update workspaceRP swagger with automation result #24333 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24333#issuecomment-1589816602)
> > 
> > Instead of suppressing, we would like to keep the validation rules intact so that we can be sure we address them all in the future.
> 
> Sounds good, there's a lot error in the lintDiff, you should still see if there's anything you can fix as of the current version, only for those you couldn't fix you can leave the fix and track them in next version

Many of the errors are pre-existing from previous API versions and are not introduced by this PR. For example, the following `ResourceNameRestriction` error existed in previous API versions where it had already been evaluated and approved, and was correctly shown as not being introduced by this PR in the [machineLearningServices PR's](https://github.com/Azure/azure-rest-api-specs/pull/24231) [LintDiff report](https://github.com/Azure/azure-rest-api-specs/pull/24231/checks?check_run_id=14065667666):
> The resource name parameter 'computeName' should be defined with a 'pattern' restriction.
 Location: [Microsoft.MachineLearningServices/preview/2023-06-01-preview/machineLearningServices.json#L531](https://github.com/Azure/azure-rest-api-specs/blob/513739d8bc2eca64256957066a82c44caca4d639/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/machineLearningServices.json#L531)

We do not understand why it is getting flagged as a new error here. Nevertheless, we did evaluate all of the errors, and determined that the remaining ones cannot be fixed in this version, either because fixing would introduce unplanned breaking changes (as would be the case with the pre-existing errors) or would require significant changes to the service (e.g., to fix the url query parameter errors). This is why we have committed to fixing in the next API version instead of this one.

**Review by ms-henglu — APPROVED** [review]

**Comment by rkmanda** [comment]
Approving Avocado failure based on this comment from Erik

Roopesh Manda here is a comment from a previous API version detailing why some of the avocado errors were suppressed:
https://github.com/Azure/azure-rest-api-specs/pull/21014#issuecomment-1269123091
I checked, and in all cases, the API paths associated with all the avocado errors have been removed. So the correct path according to Konrad is to suppress, since the APIs are removed/deprecated.
However, given our tight timeline here, we need to avoid another round of PRs into the protected staging branch (additionally, the avocado gate was green in all PRs into this protected staging branch, so we wouldn't even be able to validate the change until the fix PR is merged, which would add considerable time to this review).
Instead, we would like to request to add the "Approved-Avocado" tag to this PR as a last resort as Konrad mentioned, and we have committed to adding the suppressions for all future reviews as a follow-up after this is merged.

**Pull request merged**
