### PR TITLE
Add new API version for databox 2022-10-01

### PR DESCRIPTION
**Pull request by utsrkr**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. - January 2023
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. - January 2023
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by utsrkr** [comment]
> 



> @utsrkr please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by utsrkr** [comment]
> @microsoft-github-policy-service agree company="your company"

@microsoft-github-policy-service agree company="Microsoft"

**Comment by utsrkr** [comment]
> Hi, @utsrkr, For review efficiency consideration, when creating a new api version, it is required to place API specs of the base version in the first commit, and push new version updates into successive commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Or you could onboard [API spec pipeline](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline)

The initial commit is marked as "[initial commit - copied files from previous api version](https://github.com/Azure/azure-rest-api-specs/pull/22049/commits/ac69d606ce857fd1fb3c12008323b85c29c099ef)"

**Comment by mentat9** [comment]
@utsrkr - I changed the label to get this PR off our radar until breaking change review is complete. When you are ready for ARM review, just remove the ARMChangesRequested label and the current oncall will pick up your PR for ARM review.

**Comment by utsrkr** [comment]
gh pr edit [<number> | <url> | <branch>] --add-label <name>

**Comment by utsrkr** [comment]
> @utsrkr - I changed the label to get this PR off our radar until breaking change review is complete. When you are ready for ARM review, just remove the ARMChangesRequested label and the current oncall will pick up your PR for ARM review.

@mentat9 Looks like I don't have approval to add/remove labels. The breaking change review is complete. PR is now ready for ARM review.

**Comment by mentat9** [comment]
>           "additionalProperties": {

ARM recommends against the use of the additionalProperties/empty/unschematized object pattern. ARM favors stronger typing wherever possible because it allows all consumers of your API to reason about it. This has benefits for everyone that interacts with your API including basic infrastructure, other Azure features, SDK owners, and customers. Unschematized objects are essentially API contracts that bypass Azure versioning infrastructure.

For example, customers will not be able to manage these objects using Azure Policy, or query them using ARG, both of which are standard Azure features. Customers expect to be able to use all common Azure features against all of their resources. 

Generally, this pattern should only be used when needed and the object properties are dynamic, unknown, or user defined. Ref: [https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined](https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined).

In this case, could you model the additionalProperties in an RPC-compliant way? Maybe an array of pairs (serial number and enum).

---
Refers to: specification/databox/resource-manager/Microsoft.DataBox/stable/2022-10-01/databox.json:4824 in be2d2a7. [](commit_id = be2d2a7975025e7da2a15ca2911175db181bf9cc, deletion_comment = False)

**Comment by utsrkr** [comment]
@mentat9 I had a discussion with my team regarding the comment on the PR to modify the ‘serialNumberCustomerResolutionMap’ in an RPC compliant way. 

We fully agree with the points mentioned – that keeping it in the current format (in the form of a dictionary with additional properties) is not ideal. However, in our use case, we require a dictionary, since we want the serial number to be non-duplicated. 

Also, currently our portal team has started using the API with the current contract. We fully agree that the contracts should have been reviewed before implementation and that this was an oversight on our part. However, currently, changing our contracts will lead to delay in our development cycle for the new feature and might lead to errors.

Considering the above points, will it be possible to go ahead with the swagger (and API) in its current format? If required, I can book some time during the ARM office hours to explain the scenario. Please let me know whatever suits your convenience.

**Comment by mentat9** [comment]
>           "additionalProperties": {

It looks like I misread this property as being added to an existing resource type, but I see it is only in the request body of the mitigate action, so my concerns about Azure Policy and Azure Resource Graph don't apply.

---
In reply to: [1374353780](https://github.com/Azure/azure-rest-api-specs/pull/22049#issuecomment-1374353780) [](http://example.com/codeflow?ancestors=1374353780,1374353780)

---
Refers to: specification/databox/resource-manager/Microsoft.DataBox/stable/2022-10-01/databox.json:4824 in be2d2a7. [](commit_id = be2d2a7975025e7da2a15ca2911175db181bf9cc, deletion_comment = False)

**Review by vaishnavi-janardhan — APPROVED** [review]

**Comment by qiaozha** [comment]
@msyyc @tadelesh Could you help take a look at the SDK breaking changes ? Thanks

**Comment by tadelesh** [comment]
The Go breaking change is from this [PR](https://github.com/Azure/azure-rest-api-specs/pull/20717) (accountName change to accountId), but it seems not have been reviewed. @utsrkr Do you know any context about this breaking change?

**Comment by msyyc** [comment]
Python breaking is not caused by this PR since the new api-version is not confiured in readme.python.md

**Comment by utsrkr** [comment]
@msyyc @tadelesh I missed the changes in the readme file, it was pointed out to me by a teammate. I have updated the PR with the changes in the readme file.

In that context, @msyyc you might want to review the 'Python-ApprovedBreakingChange' tag once more.

**Comment by utsrkr** [comment]
@tadelesh The change that you mentioned is approved by the following work item: https://msazure.visualstudio.com/One/_workitems/edit/15890768

**Review by qiaozha — APPROVED** [review]

**Pull request merged**
