### PR TITLE
Revert change "fix api-version from method property to client property" for Resources within 2019-08-01 and 2019-10-01

### PR DESCRIPTION
**Pull request by Grayer123**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by hamidtirmizi — APPROVED** [review]

**Review by Tiano2017 — APPROVED** [review]
:shipit:

**Comment by Grayer123** [comment]
Hello @ArcturusZhang, could you please help us merge this pr? Also, I noticed there was one task canceled, and one expected (has been in this status for a few days). Is there a way to re-trigger a new round of check or should I check in an empty commit to force it? Many thanks.

**Comment by ArcturusZhang** [comment]
> Hello @ArcturusZhang, could you please help us merge this pr? Also, I noticed there was one task canceled, and one expected (has been in this status for a few days). Is there a way to re-trigger a new round of check or should I check in an empty commit to force it? Many thanks.

That is the pipeline of SDK automation. To trigger it will require permission from the Azure organization on github. I have triggered it by leaving a comment. I will merge this once the CI passes.

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
