### PR TITLE
Search move GA swagger 2020-06-30 from preview to stable folder

### PR DESCRIPTION
**Pull request by sazeesha098**
# Search move GA swagger 2020-06-30 from preview to stable folder
This api version was originally incorrectly placed in the preview apis folder. This PR only aims to move it to the "stable" folder to align with the actual state of the api, which should be stable. This will unblock us to add our next new proposed stable api,

### CODE REVIEW

**Comment by robertklee** [comment]
providing context, this api version was originally incorrectly placed in the preview apis folder. This PR only aims to move it to the "stable" folder to align with the actual state of the api, which should be stable. This will unblock us to add our next new proposed stable api, so we would appreciate a quick review please. :)

**Comment by tjprescott** [comment]
What PR placed this in the wrong folder?

**Comment by BevLoh** [comment]
@tjprescott , I don't know how this happened, but this is the commit that I see. https://github.com/Azure/azure-rest-api-specs/commit/f487ebc93065fd42540aa422c04edd6a768a03e6

**Comment by mattmsft** [comment]
> What PR placed this in the wrong folder?

https://github.com/Azure/azure-rest-api-specs/pull/9857

**Comment by lmazuel** [comment]
Just folder update, nothing content based

**Pull request merged**
