### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerRegistry to add version preview/2022-02-01-preview

### PR DESCRIPTION
**Pull request by nelson-wu**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/nelson-wu/azure-rest-api-specs/dev-containerregistry-Microsoft.ContainerRegistry-2022-02-01-preview...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  April 2022
  
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  April 2022
  
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by rkmanda** [comment]
>             "$ref": "#/definitions/InnerErrorDescription"

pl work thru the error flags and ping on armapireview for further review.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2022-02-01-preview/containerregistry.json:6033 in cca3c5c. [](commit_id = cca3c5cd4f9a6562ee6fa5b1235ed72d73121c25, deletion_comment = False)

**Comment by nelson-wu** [comment]
> > ```
> >         "$ref": "#/definitions/InnerErrorDescription"
> > ```
> 
> pl work thru the error flags and ping on armapireview for further review.
> 

@Azure/arm-api-review-board Can someone please elaborate on what this means?

**Comment by cegraybl** [comment]
@rkmanda The "Swagger SDK Breaking Change" test is flagging API version that are not modified by this PR, and verifying those versions the types have not changed, those were always arrays, is there a suggestion on how to handle this?
https://github.com/Azure/azure-rest-api-specs/pull/18176/checks?check_run_id=6065938225

**Comment by mentat9** [comment]
>       "properties": {

Removing the virtualNetworkRules property is a cross-version breaking change, so breaking change review is needed. I've added the appropriate label: next step/instructions are added as a PR comment.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2022-02-01-preview/containerregistry.json:4485 in 562b5f7. [](commit_id = 562b5f769776810f4814160868353830b3830bda, deletion_comment = False)

**Comment by mentat9** [comment]
@nelson-wu - Will complete ARM review after breaking change label is resolved. If it happens after this week, please ping the current ARM on-call reviewer to be sure they pick up your PR.

**Comment by cegraybl** [comment]
@mentat9 the 'virtualNetworkRules' property was deprecated in our last GA API ([2021-09-01 PR](https://github.com/Azure/azure-rest-api-specs/pull/16481)) and we are just following with the same on this preview.
Do we still need to open a review for the breaking change?

**Comment by mentat9** [comment]
> @mentat9 the 'virtualNetworkRules' property was deprecated in our last GA API that has already been approved and merged ([2021-09-01 PR](https://github.com/Azure/azure-rest-api-specs/pull/16481)), we are just following with the same on this preview. Do we still need to open a review for the breaking change?

I see it was removed from 2021-09-01, but it shipped in 2021-12-01-preview, which is newer. Presumably that is why it's getting flagged here. This is really confusing, but I guess you don't need another breaking change review for this version.

**Comment by mentat9** [comment]
>         "id": {

Recommend not using id, which ARM uses at the top level. Consider storageAccountId, storageAccountResourceId, or resourceId, or similar.

---
Refers to: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2022-02-01-preview/containerregistry.json:4473 in 562b5f7. [](commit_id = 562b5f769776810f4814160868353830b3830bda, deletion_comment = False)

**Comment by mentat9** [comment]
Signed off from ARM with comments.

**Comment by cegraybl** [comment]
Thanks for the review.
@fengzhou-msft can you help us with a final review and merge?

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
