### PR TITLE
ExpressRouteCircuit: Use SubResource instead of creating new definition for RouteFilter reference

### PR DESCRIPTION
**Pull request by anton-evseev**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by number213** [comment]
@syfarogh please take a look

**Review by syfarogh — APPROVED** [review]

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@number123 There is an error in NetworkValidation job https://dev.azure.com/azure-sdk/public/_build/results?buildId=33181&view=logs&jobId=42359eb4-a1e0-5866-3e3d-e9c509ba5c90

**Comment by number213** [comment]
@sergey-shandar the failure is expected in this case since previous PR replaced reference to "RouteFilter" with a new definition "RouteFilterReference". This is a breaking change in SDK.

**Comment by number213** [comment]
@sergey-shandar I've tried forcing re-hashed commit to restart CI but for some reason it didn't. Could you please take a look?

**Comment by number123** [comment]
Wrong email alias, please opt out me!

**Pull request merged**
