### PR TITLE
{AzureCXP} fixes Azure/azure-sdk-for-python#24694

### LINKED ISSUE #24694: Additional "runbook_type" available, update the documentation please
I've detected new values available:

'GraphPowerShellWorkflow'
'PowerShell7'
'Script'
'PowerShell'
'Python3'
'GraphPowerShell'
'Python2'
'PowerShellWorkflow'

Update the description https://docs.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.models.runbook?view=azure-python#parameters -> runbook_type

thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a9351c-df68-0770-8ea5-3679fecef0ed
* Version Independent ID: 1343264c-4471-2af5-c7bc-03a266b103a8
* Content: [azure.mgmt.automation.models.Runbook class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.models.runbook?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-automation/azure.mgmt.automation.models.Runbook.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-automation/azure.mgmt.automation.models.Runbook.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

### PR DESCRIPTION
**Pull request by navba-MSFT**
Including the possible values for the enum of the runbook types

Docs Link: https://docs.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.models.runbook?view=azure-python#parameters

fixes Azure/azure-sdk-for-python#24694

In this PR  https://github.com/Azure/azure-sdk-for-python/pull/24745, we were asked to fix the REST API Specs before the changes are implemented in SDK.

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by raych1** [comment]
@msyyc , I assigned this PR to you as you're better person to review this.

**Review by msyyc — APPROVED** [review]

**Comment by msyyc** [comment]
Hi @navba-MSFT There are three versions for `runbook.json`. You update the one under `2019-06-01`. I am wondering if the other two also need to be updated:
image

**Comment by navba-MSFT** [comment]
@jaspkaur28 Could you please review this PR to avoid any breaking changes in the SDKs ?

**Comment by navba-MSFT** [comment]
> Hi @navba-MSFT There are three versions for `runbook.json`. You update the one under `2019-06-01`. I am wondering if the other two also need to be updated: image

@msyyc Updated for the remaining versions too.

**Review by jagpreetstamber — APPROVED** [review]

**Review by jaspkaur28 — APPROVED** [review]

**Comment by msyyc** [comment]
ModelValidation error is not related with this PR

**Pull request merged**
