### PR TITLE
[Resources] Update Microsoft.Resources swagger to match service behavior

### PR DESCRIPTION
**Pull request by filizt**
### Latest improvements:

This PR includes changes that will match the swagger with what service returns in the response body.

Changes are:
* Add missing properties
* Mark request payload properties as "readOnly"
* Remove "template" property

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by raych1** [comment]
@Tiano2017, can you please review the change if it matches with current service behavior?

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by raych1** [comment]
@NullMDR , there's compile error for SDK Java, can you please have a look?

**Comment by NullMDR** [comment]
@ChenTanyi Could you please help on the Java SDK?

**Comment by ChenTanyi** [comment]
@NullMDR It seems not the generation error. Compile error would be fixed manually in SDK release.

**Review by raych1 — APPROVED** [review]

**Review by raych1 — APPROVED** [review]

**Comment by raych1** [comment]
> @NullMDR It seems not the generation error. Compile error would be fixed manually in SDK release.

Thanks @ChenTanyi @NullMDR , I will merge this.

**Pull request merged**
