### PR TITLE
Apimanagement -  2020-06-01-preview version release

### PR DESCRIPTION
**Pull request by solankisamir**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

Merging the branch to master, as all the changes are in. Please refer to individual sign-off here

https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Apr+label%3A2020-06-01-preview+is%3Aclosed

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by KacieKK — APPROVED** [review]

**Comment by raych1** [comment]
@solankisamir , please fix the model validation failures that is about the secret annotated as `x-ms-secret` cannot be returned in response in the examples.

**Comment by solankisamir** [comment]
> @solankisamir , please fix the model validation failures that are about the secret annotated as `x-ms-secret` cannot be returned in response in the examples.

Please see PR https://github.com/Azure/azure-rest-api-specs/pull/11227 which fixes the issue. 

This api-version is a new api-version and no customers are using it. The contract was designed specifically for listing secrets.

**Comment by raych1** [comment]
> > @solankisamir , please fix the model validation failures that are about the secret annotated as `x-ms-secret` cannot be returned in response in the examples.
> 
> Please see PR #11227 which fixes the issue.
> 
> This api-version is a new api-version and no customers are using it. The contract was designed specifically for listing secrets.

Looks good to me, this PR can be merged after PR#11227 is merged.

**Comment by solankisamir** [comment]
Thanks, @raych1. 
One more nit change in an example - https://github.com/Azure/azure-rest-api-specs/pull/11249

**Comment by solankisamir** [comment]
@raych1 feel free to merge this. We will the example in the master branch

**Comment by solankisamir** [comment]
@raych1 please merge if things look good to you!

**Review by raych1 — APPROVED** [review]

**Review by mikebudzynski — APPROVED** [review]

**Review by promoisha — APPROVED** [review]

**Comment by solankisamir** [comment]
@raych1 feel free to merge it. We will fix the .NET sdk issues with breaking changes in the SDK as this is a new api-version.

**Comment by raych1** [comment]
> @raych1 feel free to merge it. We will fix the .NET sdk issues with breaking changes in the SDK as this is a new api-version.

OK.

**Pull request merged**
