### PR TITLE
Adding nested "properties":{ "properties": { for ARM template.

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
2. updating examples.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by rahuls-microsoft** [comment]
We are in private preview. Our internal customers need the .net SDK. Please expedite the SDK generation process.

Thanks.

**Review by mmyyrroonn — APPROVED** [review]
In my opinion, this should be a breaking change. It's in preview api version. LGTM in general.

**Comment by rahuls-microsoft** [comment]
HI @MyronFanQiu,
There was a difference between the .net SDK and Azure template data model.
I worked with @Anthony Martin<mailto:antmarti@microsoft.com>, who pointed out that I need to use nested “properties” to make it compatible with ARM template and Azure SDK.

We are in private preview, so correcting the data model.
Yes, it’s a breaking change, but no users have started using it. We want to deliver the right API and SDK to the users, that’s why, I fixed.

Are the changes merged to master?
I don’t see the changes in master - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-07-19/quota.json#L493

It should be like following:
"CurrentQuotaLimitBase": {
      "type": "object",
      "description": "Quota limits.",
      "x-ms-azure-resource": true,
      "properties": {
        "properties": {
          "description": "Quota properties for the resource.",
          "$ref": "#/definitions/QuotaProperties"
        }
      }
    },

We would like to share the new SDK with our private preview users.

Thanks.
Rahul.

**Comment by rahuls-microsoft** [comment]
Please merge the changes and release the .Net SDK.
Our partner teams are waiting for the latest SDK to onboard the preview APIs.
As, it' preview version, so changes are OK. Based partner usages and feature requests, the API may change again. We will lock down the changes by Public Preview.
Thanks.

**Comment by rahuls-microsoft** [comment]
@MyronFanQiu How do we merge it to master?
Thanks.
Rahul.

**Comment by MyronFanQiu** [comment]
@rahuls-microsoft Hello. This PR need ARM's approval.

**Comment by MyronFanQiu** [comment]
I think @anthony-c-martin can help you approve this PR.

**Comment by rahuls-microsoft** [comment]
Can we get a sign off from one of the  authorized users.
Thanks.

**Review by ryansbenson — COMMENTED** [review]
Approved from ARMs side.

**Pull request merged**
