### PR TITLE
[Hub Generated] Review request for Microsoft.CustomerLockbox to add version preview/2018-02-28-preview

### PR DESCRIPTION
**Pull request by jiayunge**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/jiayunge/azure-rest-api-specs/dev-customerlockbox-Microsoft.CustomerLockbox-2018-02-28-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jiayunge** [comment]
Here is the PR for the private branch with the same changes: https://github.com/Azure/azure-rest-api-specs-pr/pull/970

**Review by ryansbenson — APPROVED** [review]
Identical change reviewed in the private repo.

**Comment by jiayunge** [comment]
@MyronFanQiu HI, Can you take a look and sign off, not sure if it got blocked because it is missing one more approver

**Comment by MyronFanQiu** [comment]
@jiayunge The linked PR in the private repo has not been signed off. @lirenhe Hello. Have you signed off for the private PR?

**Comment by MyronFanQiu** [comment]
@lirenhe Thanks!

**Review by mmyyrroonn — APPROVED** [review]

**Review by mmyyrroonn — APPROVED** [review]

**Pull request merged**
