### PR TITLE
BatchAI. Remove API for list clusters and fileservers

### PR DESCRIPTION
**Pull request by AlexanderYukhanov**
We cannot have API to list clusters and fileservers on subscription/resource group level
because of conflict with the previous API version.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@AlexanderYukhanov sorry i'm bit lost here, so we are removing some operations from api-version`2018-05-01`. 

In the previous api version `2018-03-01` - I can see these removed operations along with other operations exists in `2018-05-01` swagger. 

Why we are saying these removed operations conflicts with previous api version while other operations doesn't?

**Comment by anuchandy** [comment]
@AlexanderYukhanov thank you clarifying, Yes, you are right, list by RG + Subscription are not a requirement for child resources. I was looking at the old api version where these resources are top level. 

I see `FileServers_ListByWorkspace` and `Clusters_ListByWorkspace`, so we are supporting required child list operation in parent resource scope.

Given we already published SDKs for `2018-05-01` with these obsolete methods, what will we return if customer try to use those methods? are they NOP until the old resources are drained?

**Comment by AlexanderYukhanov** [comment]
The 2018-05-01 was merged by mistake. We are still working on the API and never released SDKs for it and never updated the production for this version. So, from our side, it's API is still in work.

**Comment by anuchandy** [comment]
@AlexanderYukhanov thanks for the info. Just sync-ed with @lenala and learned that there are more changes coming. Please feel free to update this PR with new changes. Inorder to merge a swagger to public repo, it is required that service is in production. Hence i'm updating the title of this PR.

Do you have some rough time frame when new service will be published to production? (if so we can add that info as well in the title)

**Comment by AlexanderYukhanov** [comment]
it should go into prod by the end of the month

**Comment by anuchandy** [comment]
@AlexanderYukhanov thanks updated the title.

**Comment by anuchandy** [comment]
@AlexanderYukhanov seems you are working on the spec, just ping me when you want to take this PR

**Comment by AlexanderYukhanov** [comment]
Hi @anuchandy, we finished with the spec. Today we are rolling out the API to prod and on Monday we are making API available to everybody. 
So, can you please take a look at PR to be sure we will merge it ASAP after making API open?

**Comment by anuchandy** [comment]
@AlexanderYukhanov sure, will take another look today.

**Comment by AlexanderYukhanov** [comment]
Hello, @anuchandy. We want to merge it in on Monday. Do you have any open issues or questions?

**Comment by AlexanderYukhanov** [comment]
will keep it for several days. the api in production is currently under feature switch

**Comment by anuchandy** [comment]
@AlexanderYukhanov just sync-ed with team, the service needs to be publicly available (without feature flag) in-order to merge the spec. I've updated the title.

Otherwise the spec looks good. We can merge as soon as it meet above criteria.

**Comment by AlexanderYukhanov** [comment]
@anuchandy, we have removed feature switch from the production and updated the titles and descriptions in the swagger, please merge

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
