### PR TITLE
Release apimanagement 2022 09 01 preview

### PR DESCRIPTION
**Pull request by solankisamir**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
@solankisamir - Please complete the ARM API Review Checklist section of the submission form.

**Comment by solankisamir** [comment]
@weidongxu-microsoft 
Each individual commit in the PR has been arm signed off as it is created with a `release` branch prefix. Can you take a look at this?

**Comment by weidongxu-microsoft** [comment]
@solankisamir 

Please fix 2 required CI.

**Comment by sjanamma** [comment]
>         "count": {

We do not recommend returning the count in the paginated queries.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:8513 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>         "count": {

same comment as above

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:8564 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
@weidongxu-microsoft  The Swagger Avacode can be ignored as all these paths are deprecated in older api-versions

> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/api-version-sets is not in the default tag.
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/updatecertificate is not in the default tag 
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/policySnippets is not in the default tag
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/properties is not in the default tag. 
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/properties/{} is not in the default tag. 
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/tenant/{}/git is not in the default tag.
> API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/tenant/{}/git/listSecrets is not in the default tag

**Comment by sjanamma** [comment]
>         "operationId": "Workspace_ListByService",

Rename to GetByService

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:42 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
> > ```
> >     "count": {
> > ```
> 
> same comment as above
> 
> Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:8564 in [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71). [](commit_id = [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71), deletion_comment = False)

Here is the justification for `count` property @sjanamma https://github.com/Azure/azure-rest-api-specs/issues/21111#issuecomment-1516775223

We have got signoff from Vlad and the Api Review board.

**Comment by sjanamma** [comment]
>               "$ref": "./definitions.json#/definitions/WorkspaceContract"

We recommend creating just the required properties that would be updating with this patch operation. Patch may not change the name, location, or type of the resource. Hence, we recommend creation a model for Patch operations

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/un-supported-patch-properties.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/un-supported-patch-properties.md)

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:291 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
> > ```
> >           "$ref": "./definitions.json#/definitions/WorkspaceContract"
> > ```
> 
> We recommend creating just the required properties that would be updating with this patch operation. Patch may not change the name, location, or type of the resource. Hence, we recommend creation a model for Patch operations
> 
> https://github.com/Azure/azure-openapi-validator/blob/main/docs/un-supported-patch-properties.md
> 
> Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:291 in [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71). [](commit_id = [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71), deletion_comment = False)

@promoisha can you acknowledge this and open an issue for the next preview api-version spec?

**Comment by solankisamir** [comment]
> > > ```
> > >           "$ref": "./definitions.json#/definitions/WorkspaceContract"
> > > ```
> > 
> > 
> > We recommend creating just the required properties that would be updating with this patch operation. Patch may not change the name, location, or type of the resource. Hence, we recommend creation a model for Patch operations
> > https://github.com/Azure/azure-openapi-validator/blob/main/docs/un-supported-patch-properties.md
> > Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:291 in [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71). [](commit_id = [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71), deletion_comment = False)
> 
> @promoisha can you acknowledge this and open an issue for the next preview api-version spec?

@sjanamma based on the developer `displayName` is different from the `name` and can be updated for this `proxy resource`

**Comment by sjanamma** [comment]
>           "final-state-via": "location"

for PUT operations, final-state-via need not be mentioned. If it is mentioned, values needs to be set to original-uri

 

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:922 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>           "202": {

202 is not a valid response for PUT according to ARM guidelines. Please remove it.

[https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creating-or-updating-resources-asynchronously](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creating-or-updating-resources-asynchronously)





---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:881 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>               "$ref": "./definitions.json#/definitions/GroupCreateParameters"

PUT Request and Response must match with Get's response. In this case, Request object must be Group Contract

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:2597 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>               "$ref": "./definitions.json#/definitions/SubscriptionCreateParameters"

PUT Request/response objects must match. same applies everywhere in this PR.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:3171 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>           "202": {

202 is not a valid response for PUT
Are you indicating that this is a long running operation?

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:4085 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>               "$ref": "./definitions.json#/definitions/ApiReleaseContract"

Patch model must be different from response. name, location, or type properties should not be available in Patch rquest

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:4587 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>             "schema": {

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/repeated-path-info.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/repeated-path-info.md)

Please see this example to remove the repeated properties that are already in the path.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:4507 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>       "get": {

This is a list call. Consider adding Consider adding the x-ms-pageable extension.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:374 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>           "application/json",

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/non-application-json-type.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/non-application-json-type.md)

Only content-type 'application/json' is supported by ARM

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:480 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
I would recommend reviewing the linter errors and fixing them before sending the PR for ARM reviews.

https://github.com/Azure/azure-rest-api-specs/pull/22978/checks?check_run_id=12883721738
https://github.com/Azure/azure-rest-api-specs/pull/22978/checks?check_run_id=12883721803

**Comment by sjanamma** [comment]
>     "AccessInformationSecretsContract": {

All secrets must be annotated with x-ms-secret: true

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:96 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>           "type": "boolean",

ARM recommends enums over booleans for future proof APIs.

Standard guidance is: replace boolean/switch properties with a more meaningful enum whenever possible.
A boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated].
Note: do NOT define a 'boolean enum' with two values 'True and False'. This might be easier to 'extend' in terms of types, but semantically its cofusing, and no better than a boolean.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:576 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by sjanamma** [comment]
>       "put": {

PUT must always have a request body and it should match the Get's response.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:1577 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
>       "get": {

#fixed

---
In reply to: [1516973505](https://github.com/Azure/azure-rest-api-specs/pull/22978#issuecomment-1516973505) [](http://example.com/codeflow?ancestors=1516973505,1516973505)

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:374 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
> > ```
> >       "202": {
> > ```
> 
> 202 is not a valid response for PUT according to ARM guidelines. Please remove it.
> 
> https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creating-or-updating-resources-asynchronously
> 
> If this is async PUT add x-ms-long-running-operation": true
> 
> https://github.com/Azure/azure-openapi-validator/blob/main/docs/create-operation-async-response-validation.md
> 
> In reply to: [1516869711](https://github.com/Azure/azure-rest-api-specs/pull/22978#issuecomment-1516869711)
> 
> Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json:881 in [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71). [](commit_id = [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71), deletion_comment = False)

https://github.com/Azure/azure-rest-api-specs/issues/23419 Opened Issue to fix this

**Comment by solankisamir** [comment]
>           "type": "boolean",

acknowledged - [https://github.com/Azure/azure-rest-api-specs/issues/23702](https://github.com/Azure/azure-rest-api-specs/issues/23702)

---
In reply to: [1517001062](https://github.com/Azure/azure-rest-api-specs/pull/22978#issuecomment-1517001062) [](http://example.com/codeflow?ancestors=1517001062,1517001062)

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:576 in 0e480de. [](commit_id = 0e480dec3b723c65c0b55ed8c420560fb71eae71, deletion_comment = False)

**Comment by solankisamir** [comment]
> > ```
> > "AccessInformationSecretsContract": {
> > ```
> 
> All secrets must be annotated with x-ms-secret: true
> 
> In reply to: [1516995109](https://github.com/Azure/azure-rest-api-specs/pull/22978#issuecomment-1516995109)
> 
> Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json:96 in [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71). [](commit_id = [0e480de](https://github.com/Azure/azure-rest-api-specs/commit/0e480dec3b723c65c0b55ed8c420560fb71eae71), deletion_comment = False)

Fixed here - https://github.com/Azure/azure-rest-api-specs/pull/23706

**Comment by solankisamir** [comment]
@sjanamma I have created a PR to fix the linter errors https://github.com/Azure/azure-rest-api-specs/pull/23706. For other issues which require us to remodel the service side code I have opened the following issues on our team

https://github.com/Azure/azure-rest-api-specs/issues/21111
https://github.com/Azure/azure-rest-api-specs/issues/23702
https://github.com/Azure/azure-rest-api-specs/issues/23419

**Comment by pilor** [comment]
Please only put this back into WaitForARMFeedback when your linter error PR merges into the source branch

**Comment by solankisamir** [comment]
@pilor 
> Please only put this back into WaitForARMFeedback when your linter error PR merges into the source branch

Our fixes for linter errors went in. For other issues, we have created issues to track it for future api-release

**Comment by solankisamir** [comment]
I have opened the following bug on validation for the AutoRest team 
https://github.com/Azure/azure-rest-api-specs/issues/23737

**Comment by solankisamir** [comment]
@weidongxu-microsoft can you please take a look at this PR? I believe it is ready to merge.

I have some more fixed in the https://github.com/Azure/azure-rest-api-specs/pull/23739 which @live1206 is helping to merge.

**Comment by weidongxu-microsoft** [comment]
Please check Avocado and LintDiff CI failure.

**Comment by solankisamir** [comment]
> Please check Avocado and LintDiff CI failure.
> 
> The fix PR seems not able to solve Avocado.

Thanks @weidongxu-microsoft, I had done analysis of the Avacado failures 

https://github.com/Azure/azure-rest-api-specs/pull/22978#issuecomment-1516769261

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft The Swagger Avacode can be ignored as all these paths are deprecated in older api-versions
> 
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/api-version-sets is not in the default tag.
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/updatecertificate is not in the default tag
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/policySnippets is not in the default tag
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/properties is not in the default tag.
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/properties/{} is not in the default tag.
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/tenant/{}/git is not in the default tag.
> > API path /subscriptions/{}/resourceGroups/{}/providers/Microsoft.ApiManagement/service/{}/tenant/{}/git/listSecrets is not in the default tag

@josefree for any objection.

Currently there is no suppress for Avocado. Hence these will need to be confirmed and approved in every PR...

**Comment by weidongxu-microsoft** [comment]
There is some valid LintDiff, that would involve change in backend.

1. "count" should be removed from List response
2. PATCH may need to use a dedicated model, with only patchable properties
3. LRO PUT should use 201 and Azure-AsyncOperation header
4. "apiId" happen on path and body

These should be addressed before GA.

**Review by weidongxu-microsoft — APPROVED** [review]

**Pull request merged**
