### PR TITLE
Support for RHEL 7.4

### PR DESCRIPTION
**Pull request by cantorek**
Newest available version of RHEL in Azure is 7.4

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sarangan12** [comment]
@cantorek This file also need to be changed - https://github.com/cantorek/azure-rest-api-specs/blob/e2a218e49585cb0d483336529723139499ef1276/specification/compute/quickstart-templates/aliases.json#L41 before approval and merge

**Comment by yugangw-msft** [comment]
@gatneil, you okay with that? I cross checked PIR images, looks like the only offerring that has the SKU 7.4 is the `RHEL-SAP` which is not the mainline one.
I think we should stick to 7.3
```
(env) D:\sdk\azure-cli>az vm image list --all -p Redhat --offer RHEL --sku 7.4 -otable
Offer     Publisher      Sku  Urn                                 Version
--------  -----------  -----  ----------------------------------  --------------
RHEL-SAP  RedHat         7.4  RedHat:RHEL-SAP:7.4:7.4.2018031222  7.4.2018031222
```

**Comment by gatneil** [comment]
Yeah, I we should stick with the mainline one, which is only up to 7.3.

**Comment by cantorek** [comment]
@sarangan12 Sure, I can do that.
@gatneil @yugangw-msft are you positive about this?
I'm relatively new to Azure, but RHEL 7.4 is available in azure portal and when trying to list images using CLI - `az vm image list --all` I can see things like:

```
  {
    "offer": "rhel-byol",
    "publisher": "RedHat",
    "sku": "rhel74",
    "urn": "RedHat:rhel-byol:rhel74:7.4.0",
    "version": "7.4.0"
  },
  {
    "offer": "rhel-ocp-marketplace",
    "publisher": "RedHat",
    "sku": "rhel74",
    "urn": "RedHat:rhel-ocp-marketplace:rhel74:7.4.1",
    "version": "7.4.1"
  },
```

Indeed, `RHEL` offereing is only 7.3.
:-(

**Comment by sarangan12** [comment]
@johanste This is the PR that I was talking about. Please take a look as you have more expertise in this area.

**Comment by yugangw-msft** [comment]
@cantorek I don't know what you want to accomplish here. You can sure use the output of `az vm image --all` command to pick any newer RHEL image you like to create a vm, like `az vm create --image RedHat:RHEL-SAP:7.4:7.4.2018031222 -g myGroup -n myvm1`. 
It is unnecessary (not correct) to update this alias file which is designed as the shortcut to the most reliable/mainline PIR images available to all regions w/o extra costings.

**Comment by johanste** [comment]
Similarly, you can use the corresponding [imageReference](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#imagereference) in a Azure Resource Manager template to specify the image.

**Pull request closed without merging**
