### PR TITLE
Change transit flag for VR from enableVirtualRouterRoutePropogation t…

### PR DESCRIPTION
**Pull request by naveenchekuri**
…o allowBranchToBranchTraffic

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [x] Removing API(s) in stable version
- [x] Removing properties in stable version
- [x] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [x] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by mmyyrroonn — APPROVED** [review]
Is it just a naming change?

**Comment by naveenchekuri** [comment]
> Is it just a naming change?

Yes. This is just name change

**Comment by allenjzhang** [comment]
Please state the justification. This is a breaking change on both REST API AND SDK front, on stable version no less. Per breaking change policy. This is not allowed without explicit approval from Breaking Change board and may require CVP approval.

**Comment by naveenchekuri** [comment]
@allenjzhang The change here is renaming of the field. The old field name is not being referenced by backend NRP or any powershell commands. We decided to change name as there are no customers, no backend or powershell commands referencing this. Could you please elaborate what is the breaking change here ?

**Review by JeffreyRichter — APPROVED** [review]

**Comment by MyronFanQiu** [comment]
> Please state the justification. This is a breaking change on both REST API AND SDK front, on stable version no less. Per breaking change policy. This is not allowed without explicit approval from Breaking Change board and may require CVP approval.

This is a monthly release branch and 2020-07-01 has not been released yet. So it's not a real breaking change.

**Pull request merged**
