### PR TITLE
[Compute] Update readme.python.md

### PR DESCRIPTION
**Pull request by qwordy**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

https://github.com/Azure/azure-cli/issues/14899
https://github.com/Azure/azure-cli/pull/15031

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
hi @qwordy, is this PR ready to merge now?

**Comment by qwordy** [comment]
```
2020-09-03T02:37:22.391Z: [Azure/azure-sdk-for-net]Not deleting clone of AzureSDKAutomation/azure-sdk-for-net at folder /z/work/azure-sdk-for-net.
[
  '##[error]2020-09-03T02:37:23.647Z: Failed to run SDK Automation: Error: SDK Automation failed, {} '
]
Error: SDK Automation failed
    at SDKRepository.updateStatusAfterGeneration (/z/lib/sdkRepository.js:293:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDKRepository.generate (/z/lib/sdkRepository.js:146:13)
    at async SpecificationPullRequestGeneration.forEachSDKRepository (/z/lib/specificationPullRequestGeneration.js:214:17)
    at async SpecificationPullRequestGeneration.generateSDKRepositories (/z/lib/specificationPullRequestGeneration.js:54:9)
    at async SpecificationPullRequest.generateModifiedServices (/z/lib/specificationPullRequest.js:51:9)
    at async /z/lib/sdkAutomation.js:75:13
    at async executeAndLog (/z/lib/sdkAutomation.js:157:18)
    at async SDKAutomation.pipelineTriggered (/z/lib/sdkAutomation.js:68:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! openapi-sdk-automation@13.0.1-7.20200828.8 start: `node lib/cli/cli.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the openapi-sdk-automation@13.0.1-7.20200828.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sdk/.npm/_logs/2020-09-03T02_37_23_667Z-debug.log

##[error]Bash exited with code '255'.
```

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy, is this PR ready to merge now?

Yes

**Comment by qwordy** [comment]
@allenjzhang Does the .Net SDK error matter?

**Comment by qwordy** [comment]
@hyonholee I only updated readme.python.md. Can you review it? What happens in .Net SDK? It fails.

**Pull request merged**
