### PR TITLE
 Enhance linked services for MySQL, PostgreSQL, Teradata and DB2

### PR DESCRIPTION
**Pull request by gadongji**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by hvermis — APPROVED** [review]

**Comment by gadongji** [comment]
For MySQL and PostgreSQL, we are introducing a new property, connectionString, to replace all the previous properties.
For Teradata and DB2, the property, schema, is removed since it is already deprecated according to our docs.

**Comment by sarangan12** [comment]
Please fix the errors reported in https://travis-ci.org/Azure/azure-rest-api-specs/jobs/355678382 for approval

**Comment by gadongji** [comment]
Hi @sarangan12, the errors are not caused by my changes I think. Or could you please point out how I need to fix it.
BTW, please hold on a while before merge this PR into master, thanks.

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by sarangan12** [comment]
@gadongji  The changes look ok to me. Do you want this merged or should I still hold?

**Comment by hvermis** [comment]
@sarangan12 please go ahead and merge.

**Comment by gadongji** [comment]
@sarangan12 @hvermis please still hold, we want to wait until UX ready. Will let you know when we want to merge :) Thanks.

**Comment by sarangan12** [comment]
STill waiting

**Comment by gadongji** [comment]
Yes, please still hold. Thanks.

**Comment by sarangan12** [comment]
@gadongji Any Updates

**Comment by gadongji** [comment]
@sarangan12 please still hold :)

**Comment by gadongji** [comment]
@sarangan12 please help complete this PR now. Our UX is ready now and thanks for your patient. :)

**Comment by gadongji** [comment]
Hi @sarangan12, could you please help merge this PR now? Thanks very much.

**Comment by gadongji** [comment]
Hi @sarangan12, please merge this PR at your first convenience :)

**Pull request merged**
