### PR TITLE
Add 200 response code to import operation

### PR DESCRIPTION
**Pull request by jaredmoo**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
Details for historical interest: see https://github.com/Azure/msrestazure-for-python/issues/26

The python polling code at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L184 is setting the response code to 200 and then calling the import operation deserializer.

However the import operation doesn't expect to receive 200 so it's throwing an exception at https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-sql/azure/mgmt/sql/operations/databases_operations.py#L285

The ClientException is caught at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L187 , but then the async code sees the 200 ( at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L447 ) and thinks that the operation is done .

Since deserialization never succeeded, the logic at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L460 tries to GET the original request uri, however the import operation is weird and actually doesn't support GET on the URI that you PUT in order to start the operation in the first place.

This is obviously a crazy corner case, so my workaround is to update the operation documentation to allow 200 return code so that this crazy situation doesn't happen. This seems like an innocuous workaround that won't risk affecting any other APIs.

**Review by sergey-shandar — APPROVED** [review]

**Comment by lmazuel** [comment]
@sergey-shandar @jaredmoo Please hold on until I check if the Swagger needs to be fixed, or the Python SDK. For now, seems to be a Python bug.

**Comment by lmazuel** [comment]
Hi @jaredmoo, could you confirm your PUT *NEVER* return a 200, and you opened this PR just to workaround a Python issue?
If so, I strongly suggest to do not modify the Swagger and keep as close as possible to the RestAPI

**Comment by jaredmoo** [comment]
I mainly did this to workaround Python issue, let me double check whether 200 is possible.

**Comment by jaredmoo** [comment]
Looks like it always returns 202, and then after polling the poll result will always be 201. So 200 seems to never happened. I will close this so we can fix it in python.

**Pull request closed without merging**
