### PR TITLE
[Azure Search] New data plane specs for 2017-11-11-Preview

### PR DESCRIPTION
**Pull request by bitsforthought**
This introduces new Swagger specs for the upcoming preview version of the Azure Search data plane API, 2017-11-11-Preview.

Note that currently, these specs are exact copies of the specs for 2016-09-01-Preview (other than the api-version), which has already been approved. We'll add new features to these specs as those features become ready for public preview.

FYI @mhko @Yahnoosh @chaosrealm @natinimni 

----
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by Yahnoosh** [comment]
LGTM :metal:

**Comment by brjohnstmsft** [comment]
@jhendrixMSFT It's been a couple days -- Can we get this reviewed and merged please?

**Comment by jhendrixMSFT** [comment]
@brjohnstmsft from the description there is no new content here, is that correct?

**Comment by brjohnstmsft** [comment]
@jhendrixMSFT Correct. The new spec and examples are exact copies of the 2016-09-01-Preview specs/examples (except for the new api-version).

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
