### PR TITLE
Adding new preview API version 2022-10-preview

### PR DESCRIPTION
**Pull request by mayankagg9722**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mayankagg9722** [comment]
Please do not merge this PR for now as we are planning to add 1 more preview swagger with "2022-09 version"

**Comment by mentat9** [comment]
>       "discriminator": "objectType"

Recommend using a string enum rather than unconstrained string for discriminator. Also a less generic name would be better, e.g. backupType, datasourceType, backupDatasourceType, etc.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:4860 in 4bb5da8. [](commit_id = 4bb5da8d4619953496b53bd19b7060f10994603d, deletion_comment = False)

**Comment by mentat9** [comment]
>         "snapshotVolumes": {

ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review). They also allow adding values later without requiring a new API version (e.g. "Unknown", "Default", etc.), and allow values other than just true/false. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).

In this case you could have one enum: backupType: { "Basic", "BasicAndVolumes", "BasicAndScopeResources", "BasicVolumesAndScopeResources" }. Alternatively, you could keep two enums with two values each.

---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:4058 in 4bb5da8. [](commit_id = 4bb5da8d4619953496b53bd19b7060f10994603d, deletion_comment = False)

**Comment by mentat9** [comment]
>             "additionalProperties": {

Generally, this pattern should only be used when needed and the object properties are dynamic, unknown, or user defined. Ref: [https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined](https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined).

ARM favors stronger typing wherever possible because it allows all consumers of your API to reason about it. This has benefits for everyone that interacts with your API including basic infrastructure, other Azure features, SDK owners, and customers. Unschematized objects are essentially API contracts that bypass Azure versioning infrastructure.

For example, customers will not be able to manage these objects using Azure Policy, or query them using ARG, both of which are standard Azure features. Customers expect to be able to use all common Azure features against all of their resources.


---
Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:5835 in 4bb5da8. [](commit_id = 4bb5da8d4619953496b53bd19b7060f10994603d, deletion_comment = False)

**Comment by mayankagg9722** [comment]
> 4860
> > ```
> >   "discriminator": "objectType"
> > ```
> 
> Recommend using a string enum rather than unconstrained string for discriminator. Also a less generic name would be better, e.g. backupType, datasourceType, backupDatasourceType, etc.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:4860 in [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d). [](commit_id = [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d), deletion_comment = False)

Hi @mentat9, this is the base object and will be is very similar to other base objects. eg. "DataStoreParameters" #4818

**Comment by mayankagg9722** [comment]
> > ```
> >         "additionalProperties": {
> > ```
> 
> Generally, this pattern should only be used when needed and the object properties are dynamic, unknown, or user defined. Ref: https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined.
> 
> ARM favors stronger typing wherever possible because it allows all consumers of your API to reason about it. This has benefits for everyone that interacts with your API including basic infrastructure, other Azure features, SDK owners, and customers. Unschematized objects are essentially API contracts that bypass Azure versioning infrastructure.
> 
> For example, customers will not be able to manage these objects using Azure Policy, or query them using ARG, both of which are standard Azure features. Customers expect to be able to use all common Azure features against all of their resources.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:5835 in [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d). [](commit_id = [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d), deletion_comment = False)

Hi @mentat9, This property will be all three i.e. dynamic, unknown, and user defined. This is of format Dictionary<string,string> which user only will use to define the mappings.

**Comment by mayankagg9722** [comment]
> > ```
> >     "snapshotVolumes": {
> > ```
> 
> ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review. They also allow adding values later without requiring a new API version (e.g. "Unknown", "Default", etc.), and allow values other than just true/false. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.).
> 
> In this case you could have one enum: backupType: { "Basic", "BasicAndVolumes", "BasicAndScopeResources", "BasicVolumesAndScopeResources" }. Alternatively, you could keep two enums with two values each.
> 
> Refers to: specification/dataprotection/resource-manager/Microsoft.DataProtection/preview/2022-10-01-preview/dataprotection.json:4058 in [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d). [](commit_id = [4bb5da8](https://github.com/Azure/azure-rest-api-specs/commit/4bb5da8d4619953496b53bd19b7060f10994603d), deletion_comment = False)

Hi @mentat9, currently we need to only use this property as a booleen as there are not other types that needs to come up under this. This is very similar to other property in the payload we have added **"includeClusterResources"**.

**Pull request closed without merging**
