### PR TITLE
Updating databases for new read scale property

### PR DESCRIPTION
**Pull request by bradrich-msft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by jaredmoo — APPROVED** [review]

**Review by jaredmoo — CHANGES_REQUESTED** [review]
Need to update examples

**Comment by yaohaizh** [comment]
@bradrich-msft, could you help address the comments. Thanks.

**Review by jaredmoo — APPROVED** [review]

**Review by jaredmoo — APPROVED** [review]

**Comment by bradrich-msft** [comment]
I have addressed the comments.  Please have a look to approve.  Thank you.

**Review by nschonni — COMMENTED** [review]
You can add the words breaking the spellcheck to https://github.com/Azure/azure-rest-api-specs/blob/master/custom-words.txt if they're correct

**Comment by yaohaizh** [comment]
@bradrich-msft  model validation failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=94836&view=logs&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1&l=56

**Comment by bradrich-msft** [comment]
Hi Yaohai,

I addressed the issues and updated my pull request.  Now I’m seeing failures from OpenAPI validator that don’t make a lot of sense to me.  Is there an issue with the validator?

https://github.com/Azure/azure-rest-api-specs/pull/6902

2019-08-28T19:33:28.5996049Z scripts/multiapi.ts(95,40): error TS2345: Argument of type 'Set<string>' is not assignable to parameter of type 'Iterable<any>'.
2019-08-28T19:33:28.5998276Z   Types of property '[Symbol.iterator]' are incompatible.
2019-08-28T19:33:28.5999576Z     Type '() => IterableIterator<string>' is not assignable to type '() => Iterator<any>'.
2019-08-28T19:33:28.6000793Z       Type 'IterableIterator<string>' is not assignable to type 'Iterator<any>'.
2019-08-28T19:33:28.6001600Z         Types of property 'next' are incompatible.
2019-08-28T19:33:28.6002393Z           Type '(...args: [] | [undefined]) => IteratorResult<string, any>' is not assignable to type '() => IteratorResult<any>'.
2019-08-28T19:33:28.6003389Z             Type 'IteratorResult<string, any>' is not assignable to type 'IteratorResult<any>'.
2019-08-28T19:33:28.6004139Z               Type 'IteratorYieldResult<string>' is not assignable to type 'IteratorResult<any>'.
2019-08-28T19:33:28.6005088Z                 Types of property 'done' are incompatible.
2019-08-28T19:33:28.6006205Z                   Type 'false | undefined' is not assignable to type 'boolean'.
2019-08-28T19:33:28.6007869Z                     Type 'undefined' is not assignable to type 'boolean'.
2019-08-28T19:33:28.6148710Z npm ERR! Test failed.  See above for more details.

**Comment by yaohaizh** [comment]
@yungezz Could your team help take at this issue @bradrich-msft mentioned? Thanks.

**Comment by yungezz** [comment]
now previous error in CI is fixed. @bradrich-msft pls fix error in ModelValidation and Semantic validation.

**Comment by yungezz** [comment]
CI passed in azure pipeline https://dev.azure.com/azure-sdk/public/_build/results?buildId=97755&view=logs&jobId=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&j=f3286dd9-d358-5477-989b-528c7fafcb9a,  pls ping me for merge if review approved.

**Review by yaohaizh — APPROVED** [review]

**Pull request merged**
