### PR TITLE
Update dscNodeCounts.json

### PR DESCRIPTION
**Pull request by lmazuel**
Fixing an incorrect location of parameter introduced in:
https://github.com/Azure/azure-rest-api-specs/pull/3404

Ref:
https://github.com/Azure/azure-sdk-for-python/issues/4965

### CODE REVIEW

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-js

**Comment by lmazuel** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5992 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5992/commits/d2b560829757cec184c807e4533896b9f39e09f8

**Review by vrdmr — APPROVED** [review]

**Comment by vrdmr** [comment]
LGTM

**Comment by vrdmr** [comment]
FYI @avkaur

**Review by yuwzho — APPROVED** [review]

**Comment by yuwzho** [comment]
Is there any updates for this PR?

**Review by avkaur — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
