### PR TITLE
Event Hubs 2018-01-01: correction in the type of List API of VirtualNetwork

### PR DESCRIPTION
**Pull request by v-Ajnava**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
Thanks @v-Ajnava - are you able to please fix the failing model validation test?
I'm aware that the failing example is unrelated to your change - so I wont block on it - but it would be great if we could get the CI passing :)

The only change required is to [remove the "description" field from each of the response operation](https://github.com/Azure/azure-rest-api-specs/blob/45160436f44d3449f1959b1fc0b98ef313140d06/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/examples/Operations_List.json#L15) values - as you can see [in the definition, there's no "description" property](https://github.com/Azure/azure-rest-api-specs/blob/45160436f44d3449f1959b1fc0b98ef313140d06/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/EventHub-preview.json#L925).

Thanks!

**Comment by v-Ajnava** [comment]
@annatisch  removed the description filed from the response operation values.

**Comment by annatisch** [comment]
Thanks @v-Ajnava - isn't removing the Operations API an ARM violation?

**Comment by v-Ajnava** [comment]
@annatisch you are right, will add it back.

**Comment by v-Ajnava** [comment]
@annatisch, reverted remove the operation API commit.  the Modal validation is fixed in previous commit. so it should be good for review

**Review by annatisch — APPROVED** [review]

**Pull request merged**
