### PR TITLE
Azure Security Center - break-to-composite v1

### PR DESCRIPTION
**Pull request by eliagrady**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by chlahav** [comment]
@praries880 This is not a breaking change, this is only separation to different files, 
so AFAIK, ARM is not needed, right?

we did this after consulting to @sergey-shandar.

**Comment by praries880** [comment]
@chlahav / @eliagrady Thanks for updating me on the issue. I was not aware of the said split :), Will sync up with @sergey-shandar offline on this.

**Comment by sergey-shandar** [comment]
@praries880 I would still prefer to have a review from ARM, they may see something. I would like to minimize a risk of broken APIs and breaking changes.

**Comment by praries880** [comment]
@ravbhatnagar pinging for review on the PR

**Comment by ravbhatnagar** [comment]
All these are existing APIs. They are just been split into separate files per type. Signing off from ARM side.

**Comment by orparnes** [comment]
@orparnes is added to the review. #Closed

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
