### PR TITLE
[Hub Generated] Move private branch 'dev-healthcareapis-Microsoft.HealthcareApis-2020-03-15' to public

### PR DESCRIPTION
**Pull request by shmartel**
This PR moves the private branch that was created into public. The branch has already been reviewed, to view the status, please go to the [OpenAPI Hub](https://portal.azure-devex-tools.com/branch/shmartel/azure-rest-api-specs-pr/dev-healthcareapis-Microsoft.HealthcareApis-2020-03-15...master/).

### CODE REVIEW

**Comment by yungezz** [comment]
hi @shmartel  could you pls share PR link  in private repo? thanks.

**Comment by shmartel** [comment]
> hi @shmartel could you pls share PR link in private branch? thanks.
Hi, @yungezz , yes: https://github.com/Azure/azure-rest-api-specs-pr/pull/1679

**Comment by shmartel** [comment]
@yungezz , will the failing "automation - sdk (SDK Net)" check block this PR?  Per my conversation here https://teams.microsoft.com/l/message/19:02411a2d005b44f8903b6da2a7a31883@thread.skype/1599772582729?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=da8d67c5-f19d-4799-b158-5dbbef868d49&parentMessageId=1599772582729&teamName=Azure%20DevEx%20SDK%2C%20CLIs&channelName=Swagger%20reviewers&createdTime=1599772582729

... it sounds like this check should not block the PR.

**Comment by yungezz** [comment]
The PR is reviewed in private repo https://github.com/Azure/azure-rest-api-specs-pr/pull/1679. I diffed swagger file, they're identical. So remove "WaitForARMFeedback" label.

hi @shmartel ,  SDK Net task doesn't block PR merging. Is this PR ready to merge?

**Review by yungezz — APPROVED** [review]

**Comment by shmartel** [comment]
> The PR is reviewed in private repo [Azure/azure-rest-api-specs-pr#1679](https://github.com/Azure/azure-rest-api-specs-pr/pull/1679). I diffed swagger file, they're identical. So remove "WaitForARMFeedback" label.
> 
> hi @shmartel , SDK Net task doesn't block PR merging. Is this PR ready to merge?

Hi, @yungezz .  Thanks.  Good to know.  Yes, this PR is ready to merge.

**Pull request merged**
