### PR TITLE
add AVS 2022-05-01 API

### PR DESCRIPTION
**Pull request by cataggar**
A prior internal review was completed in https://github.com/Azure/azure-rest-api-specs-pr/pull/5032 .

## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>             "description": "The sku to check for trail availability",

trial

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:353 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter"

Recommend moving to v3 common types. Comment applies everywhere in added sections of this PR.

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:1075 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/workloadNetworks/default": {

Currently recommending using string enum parameter instead of hard-coding the path segment. Look here for an example: [https://github.com/Azure/azure-rest-api-specs/blob/fa581bd5f31cbc6f6882b254ce5b0f5c20d84648/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L66](https://github.com/Azure/azure-rest-api-specs/blob/fa581bd5f31cbc6f6882b254ce5b0f5c20d84648/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json#L66)

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:1959 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/WorkloadNetworkSegmentsList"

Looks like this should be WorkloadNetworkList.

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:2029 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>         "nsxPublicIpQuotaRaised": {

Consider easier/more discoverable enum values, maybe something more like: nsxPublicIpQuota: { Basic64 (or Default64?), Extended1024 }. This also allows adding different quota settings in future (e.g. Default, Standard, Large, Medium, ...).

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:6020 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>         "vCenter": {

vCenterResourceId?

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:6313 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>       "properties": {}

Don't include an empty property bag. If there are no RP properties, just leave it out.

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:6820 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>       "x-ms-enum": {

You can add per-member descriptions as part of this extension. Seems like it would be helpful for this one and AzureHybridBenefitType.

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:7882 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by mentat9** [comment]
>         "uri": {

supportUri or companySupportUri?

---
Refers to: specification/vmware/resource-manager/Microsoft.AVS/stable/2022-05-01/vmware.json:7918 in ba95e1b. [](commit_id = ba95e1be0317f6b2c74653f9d5037a9b3df23a6a, deletion_comment = False)

**Comment by cataggar** [comment]
@mentat9, thanks for the review. I fixed the majority of issues you brought up. I like the property rename suggestions for `nsxPublicIpQuotaRaised`, `vCenter` and `uri`, but would prefer not to delay shipping this API. 

A breaking change showed up today for "1047 - XmlEnumChanged" related to a646bc32442446f8319114b2f74aa7ffe1028213. I added them in the first place because an error saying they were needed. Should I keep those changes or revert them?

**Comment by mentat9** [comment]
> @mentat9, thanks for the review. I fixed the majority of issues you brought up. I like the property rename suggestions for nsxPublicIpQuotaRaised, vCenter and uri, but would prefer not to delay shipping this API.

OK, not blocking ARM signoff on those suggestions. Please consider the feedback for future Azure API specs.

> A breaking change showed up today for "1047 - XmlEnumChanged" related to https://github.com/Azure/azure-rest-api-specs/commit/a646bc32442446f8319114b2f74aa7ffe1028213. I added them in the first place because an error saying they were needed. Should I keep those changes or revert them?

Odd. I don't think that should be a breaking change, but the SDK team would be the ones that know about it. @qiaozha - Is any change required for this?

**Comment by qiaozha** [comment]
@tadelesh Can you help take a look at the Go SDK breaking change error ?

**Comment by qiaozha** [comment]
@msyyc Can you help take a look at the Python SDK breaking change ? Thanks

**Comment by qiaozha** [comment]
@jianyexi Can you help take a look at the staging lint diff error ?

**Comment by msyyc** [comment]
approved for python breaking

**Comment by jianyexi** [comment]
The  staging lintDiff error at https://github.com/Azure/azure-rest-api-specs/pull/20873/checks?check_run_id=8608952837 should also be fixed as many as possible if there would be no breaking change when fixing it

**Comment by cataggar** [comment]
When did Staging LintDiff errors become required? My approach will be to:

1. Update to use `suppressions` config.
2. Suppress all errors and warnings.
3. Fix one error code at a time.
4. Get a suppression review when complete.

This will take a few commits. Here are the error codes that I will need to work through:

  - code: ConsistentPatchProperties
  - code: DefinitionsPropertiesNamesCamelCase
  - code: DeleteOperationAsyncResponseValidation
  - code: IgnoredPropertyNextToRef
  - code: LroLocationHeader
  - code: LroPatch202
  - code: PatchSkuProperty
  - code: RequiredReadOnlySystemData
  - code: UnSupportedPatchProperties
  - code: XmsLongRunningOperationOptions

**Comment by cataggar** [comment]
I'm going to mark this as draft while I work on these changes.

**Comment by cataggar** [comment]
The `ConsistentPatchProperties` fix b88a2c064b31198844432c06142212ab8cd92d7d results in breaking changes, so will revert and suppress.

**Comment by cataggar** [comment]
I submitted a Swagger Suppression Request just now.

**Comment by cataggar** [comment]
> AFAICT, those are all flagging existing APIs, not APIs newly added in this PR. There appear to be many issues with this spec from ARM perspective, but the current review only covers the changes in this PR, not the entire API surface.

That is correct. These suppressions are for existing APIs, not newly added APIs. Most are documented at:
https://github.com/Azure/azure-openapi-validator/tree/develop/docs

**Comment by raosuhas** [comment]
Review has already been signed off from ARM. Please remove "ARMSignedOff" and add "WaitForARMFeedback" if you need us to take another look

**Comment by xiaoxuqi-ms** [comment]
@jianyexi @josefree could you help to take a look at the suppression request?

**Comment by cataggar** [comment]
@qiaozha, can you merge this now that suppression has been approved?

**Review by qiaozha — APPROVED** [review]

**Pull request merged**
