### PR TITLE
Add example with nested segmentation, fix number types, remove extraneous `produces`

### PR DESCRIPTION
**Pull request by alexeldeib**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
Thanks @alexeldeib - are you able to fix the two failing CI passes?
The Go SDK generation is still failing and there's a number of model validation errors:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/445374245

Thanks!

**Comment by alexeldeib** [comment]
@annatisch Fixed csv formatting for the example, but I have questions about the other issues.

1. Go SDK. I see: `FATAL: System.InvalidOperationException: codegen for preview swagger microsoft.insights/preview/v1/AppInsights.json must be under a preview subdirectory`, but the file is under a preview subdirectory? Any insight here?

2. Model validation is failing with an error that [this property](https://github.com/Azure/azure-rest-api-specs/blob/ee017b9a3d790471881dfe8ffd6c7a4322a1b55d/specification/applicationinsights/data-plane/microsoft.insights/preview/2018-04-20/swagger.json#L1084) doesn't exist, but it's in the swagger?
```
"message": 
  "Reference could not be resolved: 
    #/definitions/generated.nested.definitions.eventsResult.properties.%40ai.messages",
    "path" : [
      "definitions","eventsResult","properties","@ai.messages","$ref"],
      "error": "JSON Pointer points to missing location: 
      #/definitions/generated.nested.definitions.eventsResult.properties.%40ai.messages"
    ]
```

**Comment by alexeldeib** [comment]
Still addressing a model validation issue with additionalProperties.

**Comment by annatisch** [comment]
Hi @lmazuel - do you know if there have been changes to how XML data is represented in Swagger examples? Samples like this one are now failing:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/data-plane/microsoft.insights/preview/v1/examples/events-get-metadata.json

Error:
```
operationId: Events_GetOdataMetadata
scenario: eventMetadata
source: response
responseCode: '200'
errorDetails:
  code: INVALID_TYPE
  params:
    - object
    - string
  message: Expected type object but found type string
```

**Comment by marstr** [comment]
> @annatisch says:
> Hi @marstr - Do you know what would cause this error in the Go generator?
> ```
> codegen for preview swagger microsoft.insights/preview/v1/AppInsights.json must be under a preview subdirectory
> ```

Ah yeah, the output path configured for the Azure SDK for Go must be in the "services/preview" folder because this spec is in the `preview` folder in the specs repository.

**Comment by annatisch** [comment]
Thanks @marstr!

Additionally I've confirmed with @sergey-shandar that the model validation errors with regards to XML can be ignored for now.

**Comment by alexeldeib** [comment]
@marstr I think this is due to https://github.com/Azure/azure-rest-api-specs/pull/3084 creating the preview/stable folders. When the spec was originally introduced, there were no folders to differentiate stable/preview. What's the preferred solution for you? I can update the path here but you'll end up with a redundant version of the SDK in azure-sdk-for-go. 

@annatisch thanks for clarifying. I think I covered the other issues with examples, let me know if I missed anything.

**Review by annatisch — APPROVED** [review]

**Pull request merged**
