### PR TITLE
SharedAccessAuthorizationRule definition renamed and path property removed.

### PR DESCRIPTION
**Pull request by v-Ajnava**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by v-Ajnava** [comment]
These are not breaking changes as SDK is not shipped yet.

**Comment by anudeepsharma** [comment]
Thanks for the letting know that SDK is not published and these are not breaking changes. Please have a look at https://travis-ci.org/Azure/azure-rest-api-specs/jobs/216146805 and fix the build.

**Review by anudeepsharma — CHANGES_REQUESTED** [review]
Please fix the build issue
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/216146805

**Comment by v-Ajnava** [comment]
@anudeepsharma, one query, the builed error for TrackedResource, those are not tracked resources. can we ignore them? in last PR we have ignored them.

**Review by anudeepsharma — APPROVED** [review]

**Pull request merged**
