### PR TITLE
Add new Inbound Endpoint support in Azure Batch

### PR DESCRIPTION
**Pull request by matthchr**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by matthchr** [comment]
Reviewers: Please note that this is for a data plane REST API version. Look at the second commit (not the first which is just copying the old API version).

@smith1511

**Review by veronicagg — DISMISSED** [review]
Changes on top of the old version look good to me, thanks for suggesting to look at the 2nd commit.
Since it's data plane, have you looked at the errors/warnings detected by the linter and decided that those weren't applicable? 
Are you planning on updating x-ms-examples to include the added properties and update the api-version parameter value?

**Comment by matthchr** [comment]
Hey Veronica: I got confused by the AutoRest linter -- it said there were 0 warnings/errors so I didn't look at the build jobs. I will look now.

For examples I will definitely update the API version, and will look into seeing what it'd take to add this in one of the examples too.

**Comment by matthchr** [comment]
Okay I looked through the linter errors. They are almost all not applicable. It'd be great to reduce the noise here as it's super hard to scan through all of these errors. Is there a way to put a linter configuration file next to our Swagger specification that allows us to turn off some of these errors (either the specific ones or the whole category)?

I have some feedback for the errors... I can put this into a series of issues or you can point me at the ones that already exist if there are any:

**These errors are only applicable to ARM:**
`"code": "APIVersionPattern",`
`"code": "OperationsAPIImplementation",`
`"code": "LROStatusCodesReturnTypeSchema",` -- and I'm not sure why it's flagging this on our spec anyway...
`"code": "PatchInOperationName",` - we offer a PATCH _and_ and update, one has replace semantics and one has 
`"code": "PutInOperationName",` - this is the replace semantics as opposed to the patch semantics. Also the code is wrong? (My operation name has no put in it, it has UPDATE in it

**These errors/warnings are wrong/suggesting we do something silly:**
`"code": "ListInOperationName",` - The API this is flagged on is a bulk add API which returns a list of results (where each result corresponds to one entry in the bulk add). Just because it returns a collection of things doesn't _necessarily_ make it a list call, so I guess I disagree with the premise of this error.
`"code": "XmsClientNameParameter",` -- it's erroring because of casing differences which are allowed and actually have an impact... I think I filed a bug for this already [here](https://github.com/Azure/autorest/issues/2226) but it doesn't seem to have actually been fixed?
`"code": "OperationIdNounConflictingModelNames",` - This is trying to protect us, which I appreciate, but the problem is that it is trying to protect us from is more complex than "just append an s and be done" because in some languages (C# for example) the classes that are generated are called "FooOperations" so you end up with "FoosOperations" - which is wrong too. Really (IMO) all the languages should be appending "Operations" to the names of these classes, since the operation groups are just that, operation groups, and that gives the highest probability of success to Swagger authors who are naturally going to craft a resource `Foo` and an operation `Foo_Create`.

I am confused by:
```
{
  "type": "Warning",
  "code": "EnumInsteadOfBoolean",
  "message": "Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined. Enum Property: parameters",
  "id": "R3018",
  "validationCategory": "RPCViolation",
  "providerNamespace": null,
  "resourceType": null,
  "sources": [
    "file:///home/travis/build/Azure/azure-rest-api-specs/batch/2017-06-01.5.1/swagger/BatchService.json:4006:10 ($.paths[\"/jobs/{jobId}\"].delete.parameters[3])"
  ]
}
```
This is hard to read -- I have no idea what `parameters[3]` is. You should use the name of the actual parameter.

I am also confused by:
```
  "code": "DefinitionsPropertiesNamesCamelCase",
  "message": "Property named: 'odata.nextLink', for definition: 'AccountListNodeAgentSkusResult' must follow camelCase style. Example: 'odata.nextLink'.",
```

The recommendation is the same as the value, so I have no idea why there is an error here.

**Comment by vishrutshah** [comment]
@matthchr Having bot reporting `0` errors/warning is on me :) It's a bug that I am fixing. Thanks for letting us know. Appreciate it.

**Comment by matthchr** [comment]
I created a new issue [here](https://github.com/Azure/autorest/issues/2349) discussing linter configuration files which I think would be pretty nice.

**Comment by matthchr** [comment]
I have updated the examples REST API version.

@smith1511 - Can you take a look at adding a JSON snippet to `PoolAdd_VirtualMachineConfiguration` in the examples directory which demonstrates the use of the new stuff? If it's too esoteric and doesn't make sense to show in the create example then that's okay we can just omit it (I'll let you decide what is best since you know the feature best)

**Comment by matthchr** [comment]
The build job seems to have failed with a failure unrelated to this change, can somebody take a look?

**Comment by vishrutshah** [comment]
@matthchr As @veronicagg is OOF today, I am looking over this PR. The changes you have done in the swagger looks good. Here are the answers for your questions:

- As this is a data plane swagger, we are in the process of categorizing this into ARM v/s non-ARM linter rules. The PR https://github.com/Azure/autorest/pull/2334 is performing that changes. It's be great if you can help us out by just listing the names that you think should not affect data plane and then our team can leverage your knowledge in correct categorization.
- `"code": "ListInOperationName"` regarding this do you think, we agree with you and on permises of potential false positives we kept this as warning category. Feel free to suggest if you think better logic can be implanted here to improve this rule by opening issue :)
-  `"code": "XmsClientNameParameter"` I see that you have already commented on the issues. I am just reopening the issue to make sure we get this looked at. 
- `"code": "OperationIdNounConflictingModelNames"` Could you please comment your thoughts the issue https://github.com/Azure/autorest/issues/1950 so that we can think about this one. 
- `parameters[3]` I see your point is valid from readability perspective but we are using that sourceMaps to leverage intelliSense in the VS Code Extension.
- `DefinitionsPropertiesNamesCamelCase` This is strange. I'll comment on the issue https://github.com/Azure/autorest/issues/2064 to make sure if we missed something. 

Regarding bot delivering misleading information, I am fixing this. 

Lastly, regarding build failures @lmazuel has done recent changes into [swagger-to-sdk](https://github.com/lmazuel/swagger-to-sdk) that seems to be affecting this. @Imazuel could you please take a look.

**Comment by matthchr** [comment]
Hi @vishrutshah - I listed the ones I think are ARM specific above (see "These errors are only applicable to ARM")

> "code": "ListInOperationName" regarding this do you think, we agree with you and on permises of potential false positives we kept this as warning category. Feel free to suggest if you think better logic can be implanted here to improve this rule by opening issue :)

I filed a bug for this [here](https://github.com/Azure/autorest/issues/2352) - I'm okay-ish with warnings being more of an "FYI" but the way the output is ordered they get intermixed with the errors and it's hard to tell them apart. 

The others I responded to the linked issues.

**Comment by vishrutshah** [comment]
Closing and reopening to pick up new CI of `swagger-to-sdk`

**Comment by vishrutshah** [comment]
@smith1511 would include the example changes of reflecting new models into `PoolAdd_VirtualMachineConfiguration` file. 

cc:
@matthchr

**Review by vishrutshah — APPROVED** [review]
LGTM!

**Comment by vishrutshah** [comment]
Dismissing @veronicagg's review as she is OOF :)

**Pull request merged**
