### PR TITLE
fix: Example cognitiveservices\data-plane\ComputerVision

### PR DESCRIPTION
**Pull request by nschonni**
- details is an array
- visualFeatures is an array
- maxCandidates is an integer

### CODE REVIEW

**Comment by yangyuan** [comment]
This would need @cthrash to review.

**Comment by anuchandy** [comment]
Based on swagger, VisualFeatures property is a CSV string not array, so the current examples are correct.

**Comment by nschonni** [comment]
Is it a problem with `oav` since it is currently flagging it in the model validation? I see the CSV part, but it is also marked as an array https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/cognitiveservices/data-plane/ComputerVision/stable/v1.0/ComputerVision.json#L1386

**Comment by cthrash** [comment]
The meta question is how much we want to update v1.0 swagger when a proper superset is provided in v2.0.  Is it better to deprecate?

**Pull request closed without merging**
