### PR TITLE
Graph swagger specs for version 1.6-internal

### PR DESCRIPTION
**Pull request by shuagarw**
Swagger specs for Graph Version 1.6-internal

### CODE REVIEW

**Comment by stankovski** [comment]
I don't see SubscriptionIdParameter being used in the path. Why do you need this parameter?

**Comment by stankovski** [comment]
All "patch" operations should be called `Path` (e.g. Application_Path) to avoid ambiguity.

**Comment by stankovski** [comment]
Why is "post" called `Group_GetMemberGroups`

```
"/{tenantID}/groups/{objectId}/getMemberGroups": {
      "post": {
        "operationId": "Group_GetMemberGroups",
```

**Comment by amarzavery** [comment]
We don't support external docs. Please add the link as a part of description. This will generate better documentation
"externalDocs": { 
28           "url": "http://msdn.microsoft.com/en-us/library/azure/hh974476.aspx" 
29         },

**Comment by brjohnstmsft** [comment]
AutoRest should support externalDocs so that URLs can have special handling in the generated code: https://github.com/Azure/autorest/issues/288

**Comment by amarzavery** [comment]
Thanks Bruce, for filing the issue. We will support this very soon.

**Comment by shuagarw** [comment]
Fixed the review comments.

**Pull request merged**
