### PR TITLE
`securitycenter`: fix yaml

### PR DESCRIPTION
**Pull request by ziyeqf**
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - fix yaml error in `readme.md` file

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Review by eliagrady — APPROVED** [review]

**Comment by raosuhas** [comment]
ARM review not required. Removing label

**Comment by eliagrady** [comment]
If this type of change cannot be merged - nothing can be merged.

**Comment by weshaggard** [comment]
@ziyeqf have you investigated the CI failures? Even though this change might be simple there does still appear to be issues that need to be fixed with this readme.

**Comment by eliagrady** [comment]
@weshaggard what I'm saying is that the CI will fail even on "empty" PRs - this is what we're trying to fix here - there's a problem right now with the committed code on the `main` branch, this PR will get us closer to having confidence in the CI pipeline.

**Comment by weshaggard** [comment]
@eliagrady I would suggest trying to use this PR to get main to a green state. I understand this might be one step along the way but why not continue to get the others fixed so things are in a good state?

**Comment by eliagrady** [comment]
> @eliagrady I would suggest trying to use this PR to get main to a green state. I understand this might be one step along the way but why not continue to get the others fixed so things are in a good state?

If I thought there is a single commit that would make us green, I would have subscribed to this idea without skipping a beat. Unfortunately I don’t think it can be resolved within a single PR, and I am trying to make subtle non additive changes such that we will get to green again. If you disagree I’d be happy to hear your thoughts on this, goal being getting to green.

**Comment by weshaggard** [comment]
Definitely agree with the goal of getting green. However, what I'm not sure on is why we cannot keep iterating on this PR to get there? I don't think each of these incremental steps needs to be merged to main before we get them all fixed.

**Comment by kazrael2119** [comment]
this js sdk breaking is not caused by this pr

**Pull request merged**
