### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService/aks to add version stable/2023-08-01

### PR DESCRIPTION
**Pull request by FumingZhang**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/dev-containerservice-Microsoft.ContainerService-2023-08-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by rkmanda** [comment]
>     "/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/meshRevisionProfiles/{mode}": {

meshRevisionProfileName?

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json:2612 in cb71bd3. [](commit_id = cb71bd3f6a335067ebbf94519e39e2e853a9aef6, deletion_comment = False)

**Comment by rkmanda** [comment]
>         "resourceUID": {

resourceUniqueId ?

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json:4467 in cb71bd3. [](commit_id = cb71bd3f6a335067ebbf94519e39e2e853a9aef6, deletion_comment = False)

**Comment by rkmanda** [comment]
>           "x-ms-identifiers": []

fix empty identifiers everywhere

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json:6585 in cb71bd3. [](commit_id = cb71bd3f6a335067ebbf94519e39e2e853a9aef6, deletion_comment = False)

**Comment by serbrech** [comment]
> > ```
> >     "resourceUID": {
> > ```
> 
> resourceUniqueId ?
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json:4467 in [cb71bd3](https://github.com/Azure/azure-rest-api-specs/commit/cb71bd3f6a335067ebbf94519e39e2e853a9aef6). [](commit_id = [cb71bd3](https://github.com/Azure/azure-rest-api-specs/commit/cb71bd3f6a335067ebbf94519e39e2e853a9aef6), deletion_comment = False)

That property was introduced in 07-02-preview, doing this change would require us to change how we handle it in code, and would be seen as a breaking changes when moving from our preview to our stable.

Other RP have use this same naming pattern for internal id naming.

I would prefer keeping it as it is now.

**Comment by SanyaKochhar** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/meshRevisionProfiles/{mode}": {
> > ```
> 
> {meshRevisionProfileName} insntead of {mode} ?
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-08-01/managedClusters.json:2612 in [704697b](https://github.com/Azure/azure-rest-api-specs/commit/704697b4e9c9974243cb026b2c87f6b62ab97b37). [](commit_id = [704697b](https://github.com/Azure/azure-rest-api-specs/commit/704697b4e9c9974243cb026b2c87f6b62ab97b37), deletion_comment = False)

@rkmanda each meshRevisionProfile would be for a specific mesh `mode`, which directly corresponds to ServiceMeshProfile field `mode`. In the future, we may add new mesh modes other than Istio, in which case meshRevisionProfileName would really just be a duplication that refers to mode. We considered having this just be "name" but it did not seem as clear as using "mode" since that is terminology we already use for service mesh

**Comment by FumingZhang** [comment]
@msyyc could you please help approve the [SDK breaking change](https://github.com/Azure/azure-rest-api-specs/pull/25633/checks?check_run_id=16461163994)?

image

The breaking change happened in previous preview API version 2023-07-02-preview (added by commit [#32b6afe](https://github.com/Azure/azure-rest-api-specs/pull/25254/commits/32b6afe7f49ce95b8b3fcdc16b852df1ebcd9aef) in PR [#25254](https://github.com/Azure/azure-rest-api-specs/pull/25254)). And the latest preview API version included in the latest python SDK released is 2023-06-02-preview, so this breaking change was detected.

**Comment by visingla-ms** [comment]
@msyyc Is there still a concern related SDK breaking changes in this PR? Checking before merging it.

**Comment by visingla-ms** [comment]
@FumingZhang Please work with SDK Reviewers to see if SDK breaking changes are blocking to merge this PR.

**Comment by msyyc** [comment]
The PR looks good to me and approved for python breaking

**Review by visingla-ms — APPROVED** [review]

**Pull request merged**
