### PR TITLE
Add 2023-02-27-preview for DigitalTwins

### PR DESCRIPTION
**Pull request by abhinav-ghai**
# Data Plane API - Pull Request
Add new API version 2023-02-27-preview for data plane APIs of Azure Digital Twins

Private spec link: https://github.com/Azure/azure-rest-api-specs-pr/pull/10145

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue: https://github.com/Azure/azure-rest-api-specs-pr/pull/10145#:~:text=engagement%20record%20issue%3A-,%5BMCIGET%20%2D%20DigitalTwins%5D%20New%20Private%20Preview%20Data%20Plane%20Version%202023%2D02%2D28%2Dpreview%20for%20Event%20Handlers%20and%20Bulk%20Import%C2%A0%239749,-Is%20this%20review

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
Previous Open API Doc: [2022-05-31 stable](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2022-05-31/digitaltwins.json)
Updated paths: /jobs/imports

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Review by sjiherzig — APPROVED** [review]

**Review by weidongxu-microsoft — APPROVED** [review]
Approved as it is same as the pr one https://github.com/Azure/azure-rest-api-specs-pr/pull/10145 (which been approved)

**Comment by markweitzel** [comment]
@abhinav-ghai -- A couple of qq for you...
Have you run the [spectral linter](https://github.com/Azure/azure-api-style-guide/blob/main/README.md) on this? There are a few "cleanliness" things that should be addressed before GA, e.g. adding the `x-ms-error-code` header. 

Also... did you change `eventRoute` to be `"required":true` ? If so, keep in mind that this is a breaking change--any previous clients *may* now get errors if they are not sending it to you. 

We should look at trying to clean as much of this up as we can before GA.

**Review by markweitzel — APPROVED** [review]
This is approved for PREVIEW, but there are some issues that should be cleaned up before the API goes GA.

**Pull request merged**
