### PR TITLE
add Azure Container Registry policies api and update OperationDefinition

### PR DESCRIPTION
**Pull request by ankurkhemani**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by ankurkhemani** [comment]
@mnltejaswini  @sajayantony  @msyihchen @djyou

**Comment by ankurkhemani** [comment]
@marstr The CI complains when adding values to enum. Can you please take a look?

INFO:swaggertosdk.autorest_tools:TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by marstr** [comment]
@lmazuel, is adding enum properties categorically breaking, or is this something to do with the way that value was added?

**Comment by marstr** [comment]
@ravbhatnagar may be able to help shed some light here too.

**Comment by ravbhatnagar** [comment]
Yes adding values to an enum is a breaking change. The reason being a strongly typed SDK will not be able to deserialize a value it doesnt understand. To avoid this, enums need to be categorized as modelAsString:true.

**Comment by ankurkhemani** [comment]
@ravbhatnagar We have [set](https://github.com/AzureCR/azure-rest-api-specs/blob/a13586d2de88ce408741c6ecd2212ca7b5d2f278/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2017-10-01/containerregistry.json#L1648) `modelAsString: true` for the enums.

**Review by marstr — APPROVED** [review]

**Comment by marstr** [comment]
Let me know when you're ready to merge

**Comment by ravbhatnagar** [comment]
Looks good!

**Comment by marstr** [comment]
Ready for me to merge, @ankurkhemani ?

**Comment by ankurkhemani** [comment]
@marstr Let's wait for the ARM manifest change to be applied .. I will let you know. Thanks!

**Comment by marstr** [comment]
Any updates here, or an estimated time-line for when these changes should be applied?

**Comment by marstr** [comment]
Closing as stale. Feel free to ping this thread to have it re-opened.

**Pull request merged**
