### PR TITLE
ExpressRoute swagger examples

### PR DESCRIPTION
**Pull request by karthikananth**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by alvadb** [comment]
Please review the following errors and fix or comment on them.
breaking changes: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/347156842
model: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/347156841

**Comment by alvadb** [comment]
I haven't seen any activity for this PR in over a week.  Please let me know if this PR is still valid.

**Comment by karthikananth** [comment]
Hi Alva – This is an active PR. I was out of office sick for the past few days. Will close on this by Monday.

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by jhendrixMSFT** [comment]
@AutorestCI rebuild azure-sdk-for-go

**Comment by alvadb** [comment]
Hi, I know there was an issue with the examples.  Have those been checked in yet?

**Comment by karthikananth** [comment]
@vinayada can you please look into this ?

**Comment by lmazuel** [comment]
Hi @karthikananth ! I'm now working with you on that PR, since Alva is not in our team anymore.
There was several release of Network since the beginning of this PR, would it be possible for you to copy our examples to all api-versions, or maybe just move them from 2018-01 to the latest one?
Thanks!

**Comment by lmazuel** [comment]
@MikhailTryakhov for guidance please

**Comment by MikhailTryakhov** [comment]
@karthikananth I recommend to follow [documentation](https://microsoft.sharepoint.com/teams/WAG/AzureNetworking/_layouts/OneNote.aspx?id=%2Fteams%2FWAG%2FAzureNetworking%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2FSwagger%20-%20SDK%20-%20PowerShell%20contribution%20milestones%7CA21DA6B0-FCD4-4C63-AEDD-D2352254ECC5%2F%29) :)

**Comment by lmazuel** [comment]
Closing for inactivity. Please re-open the PR following guidance of @MikhailTryakhov. Thank you.

**Pull request closed without merging**
