### PR TITLE
Remove "s" from read/write/format settings

### PR DESCRIPTION
**Pull request by yuzhangyi**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by yuzhangyi** [comment]
+@KeynesY , @davidzhaoyue, @shawnxzq to help review this change.

**Comment by yuzhangyi** [comment]
Hi, @anuchandy , because the AUX of our product has been released to customers serval months ago, so we have to rollback before change (it was breaking change on existed customers) to keep backward compability here, that's why we remove the "s" from write/read/format settings. This change has been agreed by our product leaders team. Please help review and signoff this change, thanks.

**Comment by anuchandy** [comment]
@yuzhangyi this is a breaking change in the SDK level. Also usually we use `settings` for configuration properties not `setting`. Is this change necessary?

**Comment by anuchandy** [comment]
We released SDKs with `s` in the model names, e.g. .NET SDK

https://github.com/Azure/azure-sdk-for-net/blob/8a7d510c4f7dc88ad6a68bc77f859f0247a71089/sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Generated/Models/StoreReadSettings.cs#L22

Nuget packages here: https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory/

Trying to understand your message `so we have to rollback before change (it was breaking change on existed customers) to keep backward compability here`:

now that we already released it, what do we meant by `backward compatibility`? sorry if I'm missing some context here.

**Comment by yuzhangyi** [comment]
Hi, @anuchandy and @AutorestCI, based on newest information get from azure powershell team, our change with breaking change in public swagger has been released to customers. So we choose to let our product AUX handling both "setting" and "settings" to workaround now, so close this PR review, thanks for your help.

**Pull request closed without merging**
