### PR TITLE
Healthcareapis microsoft.healthcare apis 2022 01 31 preview

### PR DESCRIPTION
**Pull request by tongwu-sh**
Adding new API version for 2022-01-31 preview. This PR is taking the resources added in the 2021-11-01 and moving them to a preview version with some minor updates.

Change for 2021-11-01 is approved and wait for production deployment, PR request here: https://github.com/Azure/azure-rest-api-specs/pull/16108

The first iteration for this PR is 37th iteration with commit id: cf55c6135df9fbc54f5ba0c54698c406515aef04 

Changes include:

Add import configuration properties for fhirservices

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jorgecotillo** [comment]
You did not commit / push your base api as the first iteration, see here (first bullet point): 

https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html

Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:

1. Create your new api-version folder
2. Copy the contents of your base api-version as is
3. Commit & push
4. Make changes to your spec (or simply copy the contents from this PR)

This way we can diff your changes and will be able to review your PR.

**Comment by tongwu-msft** [comment]
> Member



> You did not commit / push your base api as the first iteration, see here (first bullet point):
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
> 
> Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:
> 
> 1. Create your new api-version folder
> 2. Copy the contents of your base api-version as is
> 3. Commit & push
> 4. Make changes to your spec (or simply copy the contents from this PR)
> 
> This way we can diff your changes and will be able to review your PR.

**Comment by tongwu-msft** [comment]
> You did not commit / push your base api as the first iteration, see here (first bullet point):
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
> 
> Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:
> 
> 1. Create your new api-version folder
> 2. Copy the contents of your base api-version as is
> 3. Commit & push
> 4. Make changes to your spec (or simply copy the contents from this PR)
> 
> This way we can diff your changes and will be able to review your PR.

Hello 

> You did not commit / push your base api as the first iteration, see here (first bullet point):
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
> 
> Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:
> 
> 1. Create your new api-version folder
> 2. Copy the contents of your base api-version as is
> 3. Commit & push
> 4. Make changes to your spec (or simply copy the contents from this PR)
> 
> This way we can diff your changes and will be able to review your PR.

hello Jorge Cotillo​, for the PR, [Healthcareapis microsoft.healthcare apis 2022 01 31 preview by tongwu-msft · Pull Request #17920 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/17920)



we have our base API pushed here: [Healthcareapis microsoft.healthcare apis 2022 01 31 preview by tongwu-msft · Pull Request #17920 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/17920/commits/cf55c6135df9fbc54f5ba0c54698c406515aef04) commit cf55c6135df9fbc54f5ba0c54698c406515aef04



This PR is based on previous version 2021-11-01, this base API version is approved but due to schedule it is delayed and not merged yet (PR [https://github.com/Azure/azure-rest-api-specs/pull/16108](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F16108&data=04%7C01%7Ctongwu%40microsoft.com%7Ca2747dce9ed7404f23ad08d9f2f424f7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637807952812193367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b2GAt2IBkipuLRG4ATE7Ried1xwfVtE%2B5r0juHLmO5Q%3D&reserved=0)), our new API version PR is based on that. commit cf55c6135df9fbc54f5ba0c54698c406515aef04 is the first commit for the new API 2022-01-31-preview.



Due to tight schedule we want to have this ARM review as soon as possible and merge right after previous version 2021-11-01 merge. Thanks!

**Comment by tongwu-msft** [comment]
> You did not commit / push your base api as the first iteration, see here (first bullet point):
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
> 
> Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:
> 
> 1. Create your new api-version folder
> 2. Copy the contents of your base api-version as is
> 3. Commit & push
> 4. Make changes to your spec (or simply copy the contents from this PR)
> 
> This way we can diff your changes and will be able to review your PR.

Hello 

> You did not commit / push your base api as the first iteration, see here (first bullet point):
> 
> https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
> 
> Failing to do so means that we won't be able to diff your changes and focus only on your updates. Please abandon this PR and follow these simple steps:
> 
> 1. Create your new api-version folder
> 2. Copy the contents of your base api-version as is
> 3. Commit & push
> 4. Make changes to your spec (or simply copy the contents from this PR)
> 
> This way we can diff your changes and will be able to review your PR.

hello Jorge Cotillo​, for the PR, [Healthcareapis microsoft.healthcare apis 2022 01 31 preview by tongwu-msft · Pull Request #17920 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/17920)



we have our base API pushed here: [Healthcareapis microsoft.healthcare apis 2022 01 31 preview by tongwu-msft · Pull Request #17920 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/17920/commits/cf55c6135df9fbc54f5ba0c54698c406515aef04) commit cf55c6135df9fbc54f5ba0c54698c406515aef04



This PR is based on previous version 2021-11-01, this base API version is approved but due to schedule it is delayed and not merged yet (PR [https://github.com/Azure/azure-rest-api-specs/pull/16108](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F16108&data=04%7C01%7Ctongwu%40microsoft.com%7Ca2747dce9ed7404f23ad08d9f2f424f7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637807952812193367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b2GAt2IBkipuLRG4ATE7Ried1xwfVtE%2B5r0juHLmO5Q%3D&reserved=0)), our new API version PR is based on that. commit cf55c6135df9fbc54f5ba0c54698c406515aef04 is the first commit for the new API 2022-01-31-preview.



Due to tight schedule we want to have this ARM review as soon as possible and merge right after previous version 2021-11-01 merge. Thanks!

**Review by jianyexi — APPROVED** [review]

**Comment by tongwu-msft** [comment]
Swagger SDK Breaking Change Tracking is approved in base API version PR which is not merged.

Wait for GA version 2021-11-01 merge.

**Pull request merged**
