### PR TITLE
Update workspaceRP swagger with automation result

### PR DESCRIPTION
**Pull request by ZhidaLiu**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ZhidaLiu** [comment]
The LintDiff Error seems wrong, I don't see any difference between the PUT body and 200 response schema.

**Comment by ms-zhenhua** [comment]
@ZhidaLiu Please reach out to Azure Breaking Changes Reviewers azbreakchangereview@microsoft.com to get a breaking changes approval and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

**Comment by ZhidaLiu** [comment]
@ms-zhenhua I got the breaking change approve, please help review again, thanks~

**Comment by ms-zhenhua** [comment]
>         "operationId": "outboundNetworkDependenciesEndpoints",

should be "outboundNetworkDependenciesEndpoints_ListByWorkspaceName

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:952 in b75c10e. [](commit_id = b75c10eb9fa1d12d00774292de60ae6d941c2c24, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>             "type": "boolean",

recommend use "enum" instead of "boolean"

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:184 in b75c10e. [](commit_id = b75c10eb9fa1d12d00774292de60ae6d941c2c24, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>             "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter"

please consider alway use the latest common type version, current latest is "v5". Please also replace other places

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:279 in b75c10e. [](commit_id = b75c10eb9fa1d12d00774292de60ae6d941c2c24, deletion_comment = False)

**Comment by ZhidaLiu** [comment]
> > ```
> >         "type": "boolean",
> > ```
> 
> recommend use "enum" instead of "boolean"
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:184 in [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24). [](commit_id = [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24), deletion_comment = False)

May I ask why? this is a boolean flag is used to indicate if this delete request wants to purge the resource or soft-delete it, any reason why we want to change to enum?

**Comment by ZhidaLiu** [comment]
> > ```
> >         "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter"
> > ```
> 
> please consider always use the latest common type version, current latest is "v5". Please also replace other places
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:279 in [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24). [](commit_id = [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24), deletion_comment = False)

I need to check the change between v3 and v5, I will make this change in a separate PR and also update the swagger generation tool we use to point to v5.

**Comment by ms-zhenhua** [comment]
> > > ```
> > >         "type": "boolean",
> > > ```
> > 
> > 
> > recommend use "enum" instead of "boolean"
> > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:184 in [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24). [](commit_id = [b75c10e](https://github.com/Azure/azure-rest-api-specs/commit/b75c10eb9fa1d12d00774292de60ae6d941c2c24), deletion_comment = False)
> 
> May I ask why? this is a boolean flag is used to indicate if this delete request wants to purge the resource or soft-delete it, any reason why we want to change to enum?

It explains. However, it's not required.
https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md#why-the-rule-is-important

**Comment by ms-zhenhua** [comment]
>     },

please expand it to a model:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/properties-type-object-no-definition.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/properties-type-object-no-definition.md)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1742 in 08e9740. [](commit_id = 08e974077ff4d3b0017b0de936feb7a3c5656e03, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "additionalProperties": {

additionalProperties is not allowed, please use array:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/avoid-additional-properties.md)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3017 in 08e9740. [](commit_id = 08e974077ff4d3b0017b0de936feb7a3c5656e03, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "description": "Lists all of the available Azure Machine Learning Services REST API operations.",

please add "description" back

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:42 in 08e9740. [](commit_id = 08e974077ff4d3b0017b0de936feb7a3c5656e03, deletion_comment = True)

**Comment by ms-zhenhua** [comment]
>           "final-state-via": "location"

LRO put should use 201 and "azure-async-operation", any reason to use "location" here?:
[https://armwiki.azurewebsites.net/api_contracts/guidelines/rpaas.html#rpaas001-rpaas-supports-201--provisioning-state--azure-asyncoperation-pattern-only-for-put-long-running-operations](https://armwiki.azurewebsites.net/api_contracts/guidelines/rpaas.html#rpaas001-rpaas-supports-201--provisioning-state--azure-asyncoperation-pattern-only-for-put-long-running-operations)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:384 in 08e9740. [](commit_id = 08e974077ff4d3b0017b0de936feb7a3c5656e03, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
@ZhidaLiu It seems you change the original paths order and operations order. Though I do not know why you did this, but it causes a huge diff. This diff generates many unnecessary lint error and warning and make review much harder. Could you revert the order to make the process easier?

**Comment by ZhidaLiu** [comment]
> @ZhidaLiu It seems you change the original paths order and operations order. Though I do not know why you did this, but it causes a huge diff. This diff generates many unnecessary lint error and warning and make review much harder. Could you revert the order to make the process easier?

The order change is because the previous swagger file is manually maintained and people put path and definition in random order, this time  the swagger is generated based on our server-side code automatically and this will prevent human errors in the future, so we would like to keep this new alphabet order.

**Comment by ZhidaLiu** [comment]
> > ```
> >       "final-state-via": "location"
> > ```
> 
> LRO put should use 201 and "azure-async-operation", any reason to use "location" here?: https://armwiki.azurewebsites.net/api_contracts/guidelines/rpaas.html#rpaas001-rpaas-supports-201--provisioning-state--azure-asyncoperation-pattern-only-for-put-long-running-operations
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:384 in [08e9740](https://github.com/Azure/azure-rest-api-specs/commit/08e974077ff4d3b0017b0de936feb7a3c5656e03). [](commit_id = [08e9740](https://github.com/Azure/azure-rest-api-specs/commit/08e974077ff4d3b0017b0de936feb7a3c5656e03), deletion_comment = False)

This is a existing API behavior, I can create a work item on reflect this in the future.

**Comment by ZhidaLiu** [comment]
All the comments are reflected, now the lint issue introduced is about boolean->enum, we will consider later which will require a server-side change.

@ms-zhenhua please help review again, sorry about the problem caused by reorder the path and definition, but this is needed as we are move to auto-gen swagger and things are in alphabetical order, this will prevent us many time and efforts also reduce human error.

**Comment by ZhidaLiu** [comment]
@ms-zhenhua  I added a commit with only re-order the path and definitions of the previous workspaceRP.json file, hope this will help your review process, we really need to reorder this file to leverage the automation tool, sorry for the inconvenience for your review process.

Now you can check my change compared to the previous workspaceRP.json based on this commit:[https://github.com/Azure/azure-rest-api-specs/pull/24333/commits/029efe4af92e0d703ee6ea47ef8db82cae1085b2](url)

**Comment by ms-zhenhua** [comment]
>       "put": {

why remove DELETE? DELETE is required with PUT:
Inconsistent or incomplete CRUD in [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html#common-issues-found-in-review)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1099 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "additionalProperties": {

additionalProperties is not allowed, please use array instead:
[https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined](https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined)


---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1766 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "cosmosDbResourceId": {

define "x-ms-secret" if it's a secret value:
[https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret)


---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2000 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "searchAccountResourceId": {

define "x-ms-secret" if it's a secret value:
[https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret)


---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2012 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "storageAccountResourceId": {

define "x-ms-secret" if it's a secret value:
[https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret)


---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2019 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "keyIdentifier": {

define "x-ms-secret" if it's a secret value:
[https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2178 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "isPrivateLinkEnabled": {

consider using enum:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md#why-the-rule-is-important](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md#why-the-rule-is-important)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2427 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "provider": {

is it enumerated?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2452 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "resource": {

is it enumerated?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:2456 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "id": {

consider using  arm-id: [http://azure.github.io/autorest/extensions/#x-ms-arm-id-details](http://azure.github.io/autorest/extensions/#x-ms-arm-id-details)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3207 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "subnetArmId": {

consider using  arm-id: [http://azure.github.io/autorest/extensions/#x-ms-arm-id-details](http://azure.github.io/autorest/extensions/#x-ms-arm-id-details)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3215 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "type": "boolean"

consider using enum:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3262 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         "v1LegacyMode": {

consider using enum:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)


---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3417 in 1fad5a0. [](commit_id = 1fad5a0285ba1cbdb39d3187d450902bb25d3ea8, deletion_comment = False)

**Comment by ZhidaLiu** [comment]
> > ```
> >       "type": "object"
> > ```
> 
> provide the schema or define it as string: https://github.com/Azure/azure-openapi-validator/blob/main/docs/properties-type-object-no-definition.md#propertiestypeobjectnodefinition
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3090 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)

This is a user-defined object we provide for partner service to store meta-data of this connection, we defined it as a Dictionary<string, IValue> where IValue can be string or another layer of Dictionary<string, IValue>, so in this case I guess it should be defined as an object without schema?

**Comment by ZhidaLiu** [comment]
> > ```
> >   "put": {
> > ```
> 
> why remove DELETE? DELETE is required with PUT: Inconsistent or incomplete CRUD in https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html#common-issues-found-in-review
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1099 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)

Good catch, this is caused by a code bug making the generation tool ignore this API, already fixed and added back

**Comment by ms-zhenhua** [comment]
> "additionalProperties"



> > > ```
> > >       "additionalProperties": {
> > > ```
> > 
> > 
> > additionalProperties is not allowed, please use array instead: https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined
> > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1766 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)
> 
> @ms-zhenhua What should be the correct schema for Dictionary<string,string>? according to this document this additionalProperties is used correctly: https://swagger.io/docs/specification/data-models/dictionaries/

@ZhidaLiu Could you define it as a model of array? The model may look like:
"CustomKey": {
      "type": "object",
      "properties": {
        "keyName": {
          "type": "string",
          ...
        },
        "keyValue": {
          "type": "string",
          ...
        },
      },
    }

**Comment by ms-zhenhua** [comment]
>           "202": {

202 must have a location header:
[https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md)

If it inherits from the previous version, it may be caused by the order change. Please follow this guidance to suppress it:
[https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:682 in 1b66d93. [](commit_id = 1b66d934fd01e7eb9edc5aa905eb65d15c2c1619, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>             "$ref": "./examples/ManagedNetwork/deleteRule.json"

This file is not found. Please check.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:697 in 1b66d93. [](commit_id = 1b66d934fd01e7eb9edc5aa905eb65d15c2c1619, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
> > > ```
> > >       "type": "object"
> > > ```
> > 
> > 
> > provide the schema or define it as string: https://github.com/Azure/azure-openapi-validator/blob/main/docs/properties-type-object-no-definition.md#propertiestypeobjectnodefinition
> > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3090 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)
> 
> This is a user-defined object we provide for partner service to store meta-data of this connection, we defined it as a Dictionary<string, IValue> where IValue can be string or another layer of Dictionary<string, IValue>, so in this case I guess it should be defined as an object without schema?

If the IValue has a schema, you can define it as a model of array. The model can contain the key and the flattened IValue.

**Comment by ZhidaLiu** [comment]
> > "additionalProperties"
> 
> > > > ```
> > > >       "additionalProperties": {
> > > > ```
> > > 
> > > 
> > > additionalProperties is not allowed, please use array instead: https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi032-only-use-additionalproperties-when-the-object-properties-are-dynamic-unknown-or-user-defined
> > > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1766 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)
> > 
> > 
> > @ms-zhenhua What should be the correct schema for Dictionary<string,string>? according to this document this additionalProperties is used correctly: https://swagger.io/docs/specification/data-models/dictionaries/
> 
> @ZhidaLiu Could you define it as a model of array? The model may look like: "CustomKey": { "type": "object", "properties": { "**keyName**": { "type": "string", ... }, "**keyValue**": { "type": "string", ... }, }, }

If it is defined as what you suggest then it's not a dictionary and it will remove the relation between keyName and keyValue right? I can see places in swagger using additionalProperties to define a Dictionary like [here ](https://github.com/Azure/azure-rest-api-specs/blob/ad1400c11c96093a433a51e641ca520b5b161a3b/specification/network/resource-manager/Microsoft.Network/stable/2022-11-01/network.json#L160), why do we want to prevent this?

**Comment by ZhidaLiu** [comment]
> > > > ```
> > > >       "type": "object"
> > > > ```
> > > 
> > > 
> > > provide the schema or define it as string: https://github.com/Azure/azure-openapi-validator/blob/main/docs/properties-type-object-no-definition.md#propertiestypeobjectnodefinition
> > > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:3090 in [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8). [](commit_id = [1fad5a0](https://github.com/Azure/azure-rest-api-specs/commit/1fad5a0285ba1cbdb39d3187d450902bb25d3ea8), deletion_comment = False)
> > 
> > 
> > This is a user-defined object we provide for partner service to store meta-data of this connection, we defined it as a Dictionary<string, IValue> where IValue can be string or another layer of Dictionary<string, IValue>, so in this case I guess it should be defined as an object without schema?
> 
> If the IValue has a schema, you can define it as a model of array. The model can contain the key and the flattened IValue.

The IValue don't have a schema and that's the point of letting it become a user-defined schema, so basically they can put as many layer as they want like this:

 "metadata" : {

            "object1" : "value1",

            "object2" : {

                "nestObject1" : "value1",

                "nestObject2" : "value2"

            }

        }

**Comment by ZhidaLiu** [comment]
> > ```
> >       "202": {
> > ```
> 
> 202 must have a location header: https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-location-header.md
> 
> If it inherits from the previous version, it may be caused by the order change. Please follow this guidance to suppress it: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:682 in [1b66d93](https://github.com/Azure/azure-rest-api-specs/commit/1b66d934fd01e7eb9edc5aa905eb65d15c2c1619). [](commit_id = [1b66d93](https://github.com/Azure/azure-rest-api-specs/commit/1b66d934fd01e7eb9edc5aa905eb65d15c2c1619), deletion_comment = False)

Update the suppression, thanks

**Comment by ZhidaLiu** [comment]
@ms-zhenhua I updated the swagger with your comment considered, but for the additionalProperties and the metadata schema, I think they are by design and reflect what we expected in our service-side code, unless you can provide a way to describe those types without changing our service-side design. Please help take a look and approve if it was fine.

**Comment by zizw123** [comment]
>       "delete": {

Is this added in this new API version only? You should fix the location header for 202. Also do you have a plan/workitem for fixing the bad pattern from existing API?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1053 in dea1aae. [](commit_id = dea1aae605caec154653c04349cda6c09a3d85be, deletion_comment = False)

**Comment by ZhidaLiu** [comment]
> > ```
> >   "delete": {
> > ```
> 
> Is this added in this new API version only? You should fix the location header for 202. Also do you have a plan/workitem for fixing the bad pattern from existing API?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json:1053 in [dea1aae](https://github.com/Azure/azure-rest-api-specs/commit/dea1aae605caec154653c04349cda6c09a3d85be). [](commit_id = [dea1aae](https://github.com/Azure/azure-rest-api-specs/commit/dea1aae605caec154653c04349cda6c09a3d85be), deletion_comment = False)

Nope this is already exist in the older API version, I will create a work item to update server side

**Comment by zizw123** [comment]
Remove suppression review tag as suppression is removed

**Comment by zizw123** [comment]
> @ms-zhenhua I updated the swagger with your comment considered, but for the additionalProperties and the metadata schema, I think they are by design and reflect what we expected in our service-side code, unless you can provide a way to describe those types without changing our service-side design. Please help take a look and approve if it was fine.

Please have a work item for future plan to make the change in future version, you should make back-comp update on service side and take the suggested changes for your API in next version.

**Comment by ZhidaLiu** [comment]
> > @ms-zhenhua I updated the swagger with your comment considered, but for the additionalProperties and the metadata schema, I think they are by design and reflect what we expected in our service-side code, unless you can provide a way to describe those types without changing our service-side design. Please help take a look and approve if it was fine.
> 
> Please have a work item for future plan to make the change in future version, you should make back-comp update on service side and take the suggested changes for your API in next version.

[Task 2470537](https://dev.azure.com/msdata/Vienna/_workitems/edit/2470537): Update Metadata and new connection credential to avoid additional properties

thanks, here is the work item to track on the additional property change on the server side

**Review by live1206 — APPROVED** [review]

**Pull request merged**
