### PR TITLE
Managed Services General API Fixes

### PR DESCRIPTION
**Pull request by skayani**
-For stable/2019-09-01 and preview/2020-02-01, added MarketplaceRegistration property and use it in place of RegistrationDefinition for MarketplaceRegistrationDefinitionsList
-Note for the above change, from the very beginning MarketplaceRegistrationDefinitionsList should have used MarketplaceRegistrationDefinition so this was a mistake fix.
-For preview/2020-02-01, added eligibleAuthorizations to GetMarketplaceRegistrationDefinition and GetMarketplaceRegistrationDefinitionsList examples

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by skayani** [comment]
Although those properties are being tagged as 'removed,' our API does not use those properties to begin with.

**Comment by erich-wang** [comment]
@skayani , could you please take a look the ModelValidation error in CI?

**Comment by skayani** [comment]
> @skayani , could you please take a look the ModelValidation error in CI?



> @skayani , could you please take a look the ModelValidation error in CI?

@erich-wang , Thanks for the heads up.  It seems the only failing tests now our the BreakingChanges, as to be expected.   Let me know if you need any other info.

**Comment by ravbhatnagar** [comment]
Removing ARM Feedback label since ARM review board will not be reviewing property level changes going forward.

**Comment by skayani** [comment]
@erich-wang Friendly ping, any update?

**Comment by erich-wang** [comment]
@skayani, you're introducing breaking change to stable version. What do you mean `mistake fix`? Do you mean the previous swagger spec never works?

**Comment by skayani** [comment]
@erich-wang The API contract is incorrectly stated.  For the GetMarketplaceRegistrationDefinition and GetMarketplaceRegistrationDefintions calls, a MarketplaceRegistrationDefinition object is returned not RegistrationDefinition.  This issue was found internally since we don't have consumers for these Swagger specs yet.

**Comment by erich-wang** [comment]
@akning-ms , could you please force merge this PR as service team confirms that there's no customers for the API with breaking change.

**Comment by erich-wang** [comment]
As identified in the automated checks there are breaking changes, Please follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by skayani** [comment]
@erich-wang Hi Erich, I just wanted to clarify before proceeding with that process.  As mentioned before, our Managed Services RP API contract has not changed at all, it's the Swagger specs that are incorrect, which is what this PR fixes.  For example, for retrieving Marketplace Registration Definitions, our API contract has always returned a Marketplace Registration Definition property.  In the Swagger specs currently however, it states a Registration Definition property is returned, which is incorrect.  Additionally, we don't have customers using the marketplace registration definitions currently (if we did it would be broken due to this mistake).  Knowing that, do we still need to fill out the breaking change approval form?

**Comment by erich-wang** [comment]
> @erich-wang Hi Erich, I just wanted to clarify before proceeding with that process. As mentioned before, our Managed Services RP API contract has not changed at all, it's the Swagger specs that are incorrect, which is what this PR fixes. For example, for retrieving Marketplace Registration Definitions, our API contract has always returned a Marketplace Registration Definition property. In the Swagger specs currently however, it states a Registration Definition property is returned, which is incorrect. Additionally, we don't have customers using the marketplace registration definitions currently (if we did it would be broken due to this mistake). Knowing that, do we still need to fill out the breaking change approval form?

@akning-ms, could you force merge this PR given the breaking change is bug fix?

**Pull request merged**
