### PR TITLE
fix: network model validation errors

### PR DESCRIPTION
**Pull request by nschonni**
- Add "body" for RESPONSE_BODY_NOT_IN_EXAMPLE errors
- Remove responses for 202s with no schema defined for RESPONSE_SCHEMA_NOT_IN_SPEC errors
- The OBJECT_ADDITIONAL_PROPERTIES are not addressed
- "Thumbprint" -> "thumbprint"

### CODE REVIEW

**Comment by nschonni** [comment]
@number213 @MikhailTryakhov I PR'd this to master since it's mostly related to older specs. I can try and rebase to the network release branch if you want

**Comment by number213** [comment]
@nschonni @MikhailTryakhov I think the latest API version should be fixed in release branch but the older ones – in master. That way release PR into master would have less changes that could stall it. Also, in release branch we run our validation scritps only for the latest API version.

**Comment by MikhailTryakhov** [comment]
@sergey-shandar  agree with Anton (previous comment) related to the changes in older APIs... Please confirm and review PR

**Comment by nschonni** [comment]
OK, so I should move the one change to 2019-06-01 or also the 2019-04-01 changes too?

**Comment by number213** [comment]
@nschonni in this case, 2019-04-01 and earlier should be merged into `master`, changes for 2019-06-01 should go to `network-july-release`

**Comment by nschonni** [comment]
OK, pulled out the 2019-06-01 change and will submit it separately

**Review by anton-evseev — APPROVED** [review]

**Pull request merged**
