### PR TITLE
[AKS Do Not Merge] fix regression in new 2019-02-01 spec

### PR DESCRIPTION
**Pull request by mboersma**
Adds a regex `pattern` to the 2019-02-01 spec that was missed. See #5324.

cc: @xizhamsft @praries880 

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by xizha162 — APPROVED** [review]

**Comment by xizhamsft** [comment]
@jianghaolu,@mboersma , should this change be merged to dev-containerservice-Microsoft.ContainerService-2019-02-01 branch instead of master? That dev-xx branch is where we merge all of our 2019-02-01 related changes. The merge to master always happens from the dev-xx branch. 

I am worried that if this is merged to master it will make the dev-xx and the master out of sync.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5466 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5466/commits/273dca6c431840d4deeacac00e170c34dd7cfe62

**Comment by dsgouda** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5492 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5492/commits/69d37e61c9b4fcfaf886795d1e815ebe56bee31a

**Comment by xizhamsft** [comment]
inlcuded in a later PR.

**Pull request closed without merging**
