### PR TITLE
Added move validation enum values & fix S360 linting issues

### PR DESCRIPTION
**Pull request by bradenwatkins**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify - **Update existing versions with new enum values.**
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet. - **Jan 2021**
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet. - **Jan 2021**
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [x] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by bradenwatkins** [comment]
@raych1 in this PR I have included updates to fix some validation errors that BillingRP is getting from "Swagger Linting." The [work item](https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8188205) requires that we add a "format" attribute to our integer values in existing versions. Based on my understanding of the linting rule [R403 IntegerTypeMustHaveFormat](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r4013), and [how AutoRest uses the integer type format](https://github.com/Azure/autorest/blob/master/docs/how-autorest-generates-code-from-swagger.md#byte-datetime-int-long) I have added a "format" of `int32` for all of our integer types. This change to "type format" has triggered a failure for the breaking changes pipeline. But based on my understanding of how AutoRest uses the integer type format, this change should not actually break anything since the default intepretation of an integer type without a format attribute is `int32`.

**Question**: Is this still considered a breaking change?
- If it is a breaking change:
  - Why?
  - What can I do to satisfy the Swagger Linting Work Item if I remove the breaking changes?
- If this is not a breaking change:
  - What do I need to do in order to make sure this PR can be merged?

**Comment by raych1** [comment]
@bradenwatkins , we have a window for `fix s360 issue with breaking change`. As your change is for this purpose, I selected this purpose in the first comment of this PR. Please follow breaking change review process and provide the S360 KPI work item to get approval. Thanks.

**Comment by bradenwatkins** [comment]
@raych1 I've created a [work item for the breaking change review][1] and included the S360 work item. Are there any other steps I need to take?

[1]: https://msazure.visualstudio.com/One/_workitems/edit/9058321

**Comment by raych1** [comment]
> Hi @bradenwatkins, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review.
> **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).
> If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/12275&days=5).
> If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ma/swaggerfeedback.

@bradenwatkins , please follow above *action* for breaking change review process.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by bradenwatkins** [comment]
@raych1 We have approval from the breaking changes team. Can you go ahead and merge once validations complete?

**Review by raych1 — APPROVED** [review]

**Pull request merged**
