### PR TITLE
Azure SignalR - Adding new api-version 2023-03-01-preview

### PR DESCRIPTION
**Pull request by bjqian**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/SubscriptionIdParameter"

Recommend SubscriptionIdParameter from v5 common types. Comment applies throughout this PR.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1260 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ResourceGroupParameter"

Recommend ResourceGroupNameParameter from v5 common types. Comment applies throughout this PR.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1263 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ApiVersionParameter"

Recommend ApiVersionParameter from v5 common types. Comment applies throughout this PR.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1269 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ResourceName"

resourceName is too generic. Recommend including the type in the name, e.g. signalRName. Comment applies throughout this PR.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1266 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse"

Move to current common types (v5).  Comment applies throughout this PR.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1282 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>           "$ref": "#/definitions/TrackedResource"

Should use TrackedResource from v5 common types.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2554 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>       }

You can get rid of this if you move to v5 common types for TrackedResource.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2569 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>           "201": {

Async status is 202.

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1734 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/SubscriptionIdParameter"

Get this from common types

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1480 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>             "$ref": "#/parameters/ResourceName"

Should use a more specific name than resourceName, e.g. webPubSubName.

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1486 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse"

Move to newer common types (v5)

---
Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1502 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by bjqian** [comment]
> > ```
> >         "$ref": "#/parameters/SubscriptionIdParameter"
> > ```
> 
> Recommend SubscriptionIdParameter from v5 common types. Comment applies throughout this PR.
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1260 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

The apiVersion, subscriptionId, resourceGroup are switched to use common types in V5 now

**Comment by bjqian** [comment]
> > ```
> >         "$ref": "#/parameters/ResourceName"
> > ```
> 
> resourceName is too generic. Recommend including the type in the name, e.g. signalRName. Comment applies throughout this PR.
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1266 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

Since the **resourceName** is used for the primary for all existing apis, we hope to keep consistent when adding a new replica api.  :smiley:

**Comment by bjqian** [comment]
> > ```
> >           "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse"
> > ```
> 
> Move to newer common types (v5)
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1502 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

The errorResponse in using **v5** now

**Comment by bjqian** [comment]
> > ```
> >         "description": "Created or updated. The response describes the new replica and contains a Location header to query the operation result.",
> > ```
> 
> 201 is created, 200 is updated.
> 
> Refers to: specification/webpubsub/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/webpubsub.json:1618 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

The description is updated according to comments

**Comment by bjqian** [comment]
> > ```
> >       "$ref": "#/definitions/TrackedResource"
> > ```
> 
> Should use TrackedResource from v5 common types.
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2554 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

Use trackedResource in common type v5 now. The one in the swagger file is deleted.

**Comment by bjqian** [comment]
> > ```
> >       "201": {
> > ```
> 
> Async response for PATCH is 202. Ref: https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#updating-using-patch.
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1514 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

Changed to 202 for patch as commented

**Comment by bjqian** [comment]
Hi @mentat9 . Looks the modification is targeted as a breaking change after I switched to use types defined in common v5. 
https://github.com/Azure/azure-rest-api-specs/pull/22948/checks?check_run_id=11950071162
Is it a false alarm :sweat_smile:

**Comment by TimLovellSmith** [comment]
There still seem to be a large number of RPC violation lintDiff errors, I assume these should all be fixed.
https://github.com/Azure/azure-rest-api-specs/pull/22948/checks?check_run_id=11950071397

**Comment by bjqian** [comment]
Hi @TimLovellSmith . Fixed the 202 issue and location header issue in LintDiff.
And according to @raych1 , the remaining issues in **LintDiff  for patch** operation could be skipped if they are from common types.

**Comment by TimLovellSmith** [comment]
>         "systemData": {

I forget but is systemData not already included in v5 ProxyResource definition? Probably the upgrade from v2-v5 types could be causing redundancy in the definition.

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1951 in d2ab42a. [](commit_id = d2ab42ad085584c707dd12894531174504f0f4b6, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>         "systemData": {

Same question about upgrading common types and systemData

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2029 in d2ab42a. [](commit_id = d2ab42ad085584c707dd12894531174504f0f4b6, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>         "systemData": {

Yes, its already inherited, from v5 'Resource' (ProxyResource inherits it)

---
In reply to: [1470955731](https://github.com/Azure/azure-rest-api-specs/pull/22948#issuecomment-1470955731) [](http://example.com/codeflow?ancestors=1470955731)

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1951 in 0a47055. [](commit_id = 0a4705500e4648dede8428e8b61627ca6fbf373a, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     },

Do you still need this, or are you now inheriting TrackedResource/ProxyResource everywhere instead?

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2696 in d2ab42a. [](commit_id = d2ab42ad085584c707dd12894531174504f0f4b6, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     },

Would you be able to use the definitions of these from common-types instead? (is it nonbreaking?)

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/privatelinks.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/privatelinks.json)

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:2492 in d2ab42a. [](commit_id = d2ab42ad085584c707dd12894531174504f0f4b6, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>             "name": "privateEndpointConnectionName",

Would you be able to use the definition of this from

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/privatelinks.json#Parameters](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/privatelinks.json#Parameters)

instead?

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1007 in d2ab42a. [](commit_id = d2ab42ad085584c707dd12894531174504f0f4b6, deletion_comment = False)

**Comment by bjqian** [comment]
Hi @TimLovellSmith . Looks replacing all modesl with common-types is a big change. Maybe I can submit a seperate PR to upgrade them and make this PR focus on the new Apis introduced by our **replica** feature?

**Comment by bjqian** [comment]
> Hi @TimLovellSmith . Looks replacing all modesl with common-types is a big change. Maybe I can submit a seperate PR to upgrade them and make this PR focus on the new Apis introduced by our **replica** feature?

Looks not that big. Let me do it in this PR

**Comment by TimLovellSmith** [comment]
Yes, to be clear, its ok to punt the common types changes if they are making it too hard. We are just trying to gently nudge people in that best pratices direction.

**Comment by bjqian** [comment]
Hi @TimLovellSmith . Now the `trackedResource, proxyResource, privateEndpointConnectionParameter` are using models from common.
Since our `privateEndpointConnection `model is different from the one in Common, I switched back to use our olde model.
The difference: https://github.com/Azure/azure-rest-api-specs/pull/22948/checks?check_run_id=12045568750
For remaining breaking changes, I assume they are false alarm.

**Comment by TimLovellSmith** [comment]
>           "202": {

don't you also have to spec the expected final status code of the operation after it stops returning 202, such as 200 or 204?

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1229 in 44cc5a9. [](commit_id = 44cc5a9ee17389b8e1bddea7497109b296d1c4ce, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "202": {

Don't you also have to spec the final '200' success response?

---
Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1511 in 44cc5a9. [](commit_id = 44cc5a9ee17389b8e1bddea7497109b296d1c4ce, deletion_comment = False)

**Comment by bjqian** [comment]
> > ```
> >       "202": {
> > ```
> 
> Don't you also have to spec the final '200' or '204' success response?
> 
> Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1511 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)

I didn't quite get the point. There is a 200 response for this api. Is there anything else that is missed?

**Comment by TimLovellSmith** [comment]
> > Don't you also have to spec the final '200' or '204' success response?
> > Refers to: specification/signalr/resource-manager/Microsoft.SignalRService/preview/2023-03-01-preview/signalr.json:1511 in [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a). [](commit_id = [0a47055](https://github.com/Azure/azure-rest-api-specs/commit/0a4705500e4648dede8428e8b61627ca6fbf373a), deletion_comment = False)
> 
> I didn't quite get the point. There is a 200 response for this api. Is there anything else that is missed?

Yes, my mistake, sorry!

**Comment by bjqian** [comment]
hi @raych1 , can we get merged now?

**Comment by raych1** [comment]
@live1206 , can you have a look at `dotnet sdk track2` error?

**Comment by bjqian** [comment]
Some clarifications about breaking changes:
1. We migrate to common models( The proxyResource, trackedResouce...). 
2. A pattern is added to resource name. This limit exists in server side too.

**Comment by live1206** [comment]
> @live1206 , can you have a look at `dotnet sdk track2` error?

There are two kinds of errors here:
- Breaking change due to migration to common types, which is expected
- In common types v5, subscription id is `Guid` instead of `string`, this is causing problem for many RPs we are looking into a proper solution, we can ignore them in this PR

**Comment by bjqian** [comment]
@live1206 @raych1 
So the breaking changes are false alarms. Can we move on ?

**Review by raych1 — APPROVED** [review]

**Pull request merged**
