### PR TITLE
add media track2 config

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by yonzhan** [comment]
@msyyc  @jsntcy  please take a look.

**Review by msyyc — APPROVED** [review]
it's better to extract content about python into a new file : readme.python.md

**Comment by jsntcy** [comment]
> it's better to extract content about python into a new file : readme.python.md

@00Kai0, as Yuchao mentioned, could you help move python configuration to a separate configuration file `readme.python.md` for better maintenance.

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
