### PR TITLE
[ACR] add regionEndpointEnabled to replication properties and replicationUpdateParameters

### PR DESCRIPTION
**Pull request by adewaleo**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adewaleo** [comment]
@fengzhou-msft will ARM feedback be placed here?

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by fengzhou-msft** [comment]
@adewaleo Can you take a look at the [breaking change](https://github.com/Azure/azure-rest-api-specs/pull/8840#issuecomment-604164997) in Python SDK? I do not have permission to merge the PR with failed required CI. You need to confirm the breaking changes are expected and wanted. Then I can ask someone with the permission to merge it.

**Comment by adewaleo** [comment]
@fengzhou-msft, thanks will do.

**Comment by adewaleo** [comment]
@fengzhou-msft these changes look good to me, the breaking changes are all in the latest preview api version and aren't particularly surprising

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft these changes look good to me, the breaking changes are all in the latest preview api version and aren't particularly surprising

@akning-ms can you help force merge the PR?

**Comment by adewaleo** [comment]
@fengzhou-msft @akning-ms thanks!

**Pull request merged**
