### PR TITLE
Release sentinel 2023 07 01 preview

### PR DESCRIPTION
**Pull request by xuhumsft**
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - _Updating an existing version by adding 2 more items to one of the Enums.

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

### CODE REVIEW

**Comment by xuhumsft** [comment]
please note, for dataConnectorDefinitions.json, it is already ARMSignedOff. Please check [this PR](https://github.com/Azure/azure-rest-api-specs/pull/24509) for more details.

**Comment by raosuhas** [comment]
Can you please fix the warnings specified in the swagger lint diff tests : https://github.com/Azure/azure-rest-api-specs/pull/24557/checks?check_run_id=14532301583 that are introduced by the current PR

**Comment by sagamzu** [comment]
> Can you please fix the warnings specified in the swagger lint diff tests : https://github.com/Azure/azure-rest-api-specs/pull/24557/checks?check_run_id=14532301583 that are introduced by the current PR


@raosuhas 
There are 3 kinds of warnings:
1. PageableOperation - This API doesn't support paging yet. for now it is not relevant.
In case we will add in the future support for paginating, I will add doc in the swagger as well.

2. parameterDescription - Fix in a new PR (with a few small changes),  that should be merged to this branch
Open PR - https://github.com/Azure/azure-rest-api-specs/pull/24759
Can you please take a look why i cant add the "waitingForArmFeedback"?

3. enumInsteadOfBoolean - 
These properties define as boolean in the API, and the customer use it as boolean.
In all our swagger team doc we are using boolean.
Can you please explain what is the different in this API? 
why cant it be Boolean here? Is it mandatory to change it?

For example:.
image

**Comment by sagamzu** [comment]
> Can you please fix the warnings specified in the swagger lint diff tests : https://github.com/Azure/azure-rest-api-specs/pull/24557/checks?check_run_id=14532301583 that are introduced by the current PR


@raosuhas 
There are 3 kinds of warnings:
1. PageableOperation - This API doesn't support paging yet. for now it is not relevant.
In case we will add in the future support for paginating, I will add doc in the swagger as well.

2. parameterDescription - Fix in a new PR (with a few small changes),  that should be merged to this branch
Open PR - https://github.com/Azure/azure-rest-api-specs/pull/24759
Can you please take a look why i cant add the "waitingForArmFeedback"?

3. enumInsteadOfBoolean - 
These properties define as boolean in the API, and the customer use it as boolean.
In all our swagger team doc we are using boolean.
Can you please explain what is the different in this API? 
why cant it be boolean here? Is it mandatory to change it?

For example:.
image

**Comment by visingla-ms** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/dataConnectorDefinitions": {

Based on the response model schema, operation 'DataConnectorDefinitions_List' should be pageable. Add the x-ms-pageable extension.

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:37 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "isPreview": {

It is better to make to this enum with values "preview", "public" for now, so that you can add more release stages later without causing breaking changes.

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:250 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "value": {

Shouldn't this be named as "queries"?

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:272 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
> // <auto-generated>

The ".cs" file should not be checked-in. Remove this file.

---
Refers to: CloudError.cs:1 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "DataConnectorDefinitionArmCollectionWrapper": {

The name can be simplified to "DataConnectorDefinitionCollection"?

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:335 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "isConnectivityCriteriasMatchSome": {

It is better to make to this enum connectivityCriteriaMatchStrategy with values "OR", "AND" (or maybe "Some", "All") instead of making it boolean.

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:495 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "tenant": {

It should be named as "tenantPermissions"?

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:594 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "resourceProvider": {

resourceProviderPermissions?

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:608 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "customs": {

customPermissions?

---
Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:616 in f5c3aff. [](commit_id = f5c3aff9271447af6422291b16458cab8abd230b, deletion_comment = False)

**Comment by sagamzu** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/dataConnectorDefinitions": {
> > ```
> 
> Based on the response model schema, operation 'DataConnectorDefinitions_List' should be pageable. Add the x-ms-pageable extension.
> 
> Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:37 in [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b). [](commit_id = [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b), deletion_comment = False)

We don't support pagination for this API.
Currently there is no need for pagination. we will add it in the future if needed.
It doesnt make sense to add it in the swagger, if it is not supported in our code

**Comment by sagamzu** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/dataConnectorDefinitions": {
> > ```
> 
> Based on the response model schema, operation 'DataConnectorDefinitions_List' should be pageable. Add the x-ms-pageable extension.
> 
> Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:37 in [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b). [](commit_id = [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b), deletion_comment = False)


We don't support pagination for this API.
Currently there is no need for pagination. we will add it in the future if needed.
It doesnt make sense to add it in the swagger, if it is not supported in our code

**Comment by sagamzu** [comment]
> > ```
> >     "isPreview": {
> > ```
> 
> It is better to make to this enum with values "preview", "public" for now, so that you can add more release stages later without causing breaking changes.
> 
> Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:250 in [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b). [](commit_id = [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b), deletion_comment = False)

not relevant here.
We have the current object in another API (dataConnectors)
This is a new API with the same object for backward compatibility to the old API.
in our next iteration, we plan to update the API property. but first our PM decistion was to go with this

**Comment by sagamzu** [comment]
> > ```
> >     "isPreview": {
> > ```
> 
> It is better to make to this enum with values "preview", "public" for now, so that you can add more release stages later without causing breaking changes.
> 
> Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:250 in [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b). [](commit_id = [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b), deletion_comment = False)

not relevant here.
We have the current object in another API (dataConnectors)
This is a new API with the same object for backowrd compatibility to the old API.
in our next iteration, we plan to remove this property


> > ```
> >     "value": {
> > ```
> 
> Shouldn't this be named as "queries"?
> 
> Refers to: specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-07-01-preview/dataConnectorDefinitions.json:272 in [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b). [](commit_id = [f5c3aff](https://github.com/Azure/azure-rest-api-specs/commit/f5c3aff9271447af6422291b16458cab8abd230b), deletion_comment = False)

Sameas i explained for prevoius comment

**Comment by sagamzu** [comment]
@visingla-ms please note that all your comments about the API property name are not relevant..

We had a dedicate PR for this API, that was approved by Arm team.
As i explained in that PR, We currently have this object in another API (dataConnectors)
The new API should be the same object as in dataConnector API for backward compatibility.
Please see PR: https://github.com/Azure/azure-rest-api-specs/pull/24509

In the future we have a plan to improve the API, but this will be in another API iteration and not in high prosperity.
I will take all your comments when we will be in the next step. 
But for now it should stay like this (PM and Manager decision)

**Comment by visingla-ms** [comment]
> @visingla-ms please note that all your comments about the API property names anf paginagion are not relevant..
> 
> We had a dedicate PR for this API, that was approved by Arm team. As i explained in that PR, We currently have this object in another API (dataConnectors) The new API should be the same object as in dataConnector API for backward compatibility. In addition, this API doesn't support pagination yet. i cant add document for paginagion if it is not relevant for the API Please see PR: #24509
> 
> In the future we have a plan to improve the API, but this will be in another API iteration and not in high prosperity. I will take all your comments when we will be in the next step. But for now it should stay like this (PM and Manager decision)

Just FYI, adding Pagination later is a breaking change for the customers, so it will require you to get approval from Breaking changes board to be able to add pagination later. Please confirm if that's fine with you, as that is strongly discouraged. Also, from the point of view, all Azure customers would assume all ARM LIST APIs will return paginated response. If they see any API returning non-paginated response, it is digress from ARM's contract with customers.

Azure Breaking changes policy screenshot:
image

**Comment by sagamzu** [comment]
> > @visingla-ms please note that all your comments about the API property names anf paginagion are not relevant..
> > We had a dedicate PR for this API, that was approved by Arm team. As i explained in that PR, We currently have this object in another API (dataConnectors) The new API should be the same object as in dataConnector API for backward compatibility. In addition, this API doesn't support pagination yet. i cant add document for paginagion if it is not relevant for the API Please see PR: #24509
> > In the future we have a plan to improve the API, but this will be in another API iteration and not in high prosperity. I will take all your comments when we will be in the next step. But for now it should stay like this (PM and Manager decision)
> 
> Just FYI, adding Pagination later is a breaking change for the customers, so it will require you to get approval from Breaking changes board to be able to add pagination later. Please confirm if that's fine with you, as that is strongly discouraged. Also, from the point of view, all Azure customers would assume all ARM LIST APIs will return paginated response. If they see any API returning non-paginated response, it is digressed from ARM's contract with customers.
> 
> Azure Breaking changes policy screenshot: image

Thanks for the explanations. 
I will add it (and return null for now, because we still font need the pagination)

**Comment by visingla-ms** [comment]
> > > @visingla-ms please note that all your comments about the API property names anf paginagion are not relevant..
> > > We had a dedicate PR for this API, that was approved by Arm team. As i explained in that PR, We currently have this object in another API (dataConnectors) The new API should be the same object as in dataConnector API for backward compatibility. In addition, this API doesn't support pagination yet. i cant add document for paginagion if it is not relevant for the API Please see PR: #24509
> > > In the future we have a plan to improve the API, but this will be in another API iteration and not in high prosperity. I will take all your comments when we will be in the next step. But for now it should stay like this (PM and Manager decision)
> > 
> > 
> > Just FYI, adding Pagination later is a breaking change for the customers, so it will require you to get approval from Breaking changes board to be able to add pagination later. Please confirm if that's fine with you, as that is strongly discouraged. Also, from the point of view, all Azure customers would assume all ARM LIST APIs will return paginated response. If they see any API returning non-paginated response, it is digressed from ARM's contract with customers.
> > Azure Breaking changes policy screenshot: image
> 
> Thanks for the explanations. I will add it (and return null for now, because we still font need the pagination) The changes are in another PR, and waiting for a merge to this PR #24986

Thank you.

**Comment by kazrael2119** [comment]
this js breaking is not caused by preview api version

**Comment by xuhumsft** [comment]
Hi @kazrael2119, please let us know if there is any action item for us.

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
