### PR TITLE
Split resources.json into resources.json & deployments.json as per team boundaries

### PR DESCRIPTION
**Pull request by anthony-c-martin**
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [x] Other, please clarify:
    - Refactor without any intended impact to APIs or generated SDKs

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Goal
Split existing swagger definition `resources.json` into `deployments.json` & `resources.json` with NO functional changes (no impact to APIs, SDKs, autorest, any other tooling).

See [here](https://github.com/Azure/azure-rest-api-specs/blob/14a1acbc547718bacccbd0fd9b2f68bb76097a9d/dev/deployments/convert/main.ts#L12-L51) for the full set of APIs that are being moved from `resources.json` into `deployments.json`.

Ultimately the intention is to allow my team (Azure Deployments) flexibility to migrate the APIs we own to TypeSpec. To avoid complicating the review process, this will happen via a follow-up PR.

## Notes
To make this PR simpler to review, I have not made any manual changes to the files - I have scripted the full conversion under https://github.com/Azure/azure-rest-api-specs/blob/ant/deployments/dev/deployments/convert/main.ts. It can be modified and re-run to replicate the changes if desired with the following steps:
```sh
# revert files to the latest from main
git checkout origin/main -- specification/resources/resource-manager/Microsoft.Resources
# install NPM packages
npm --prefix dev/deployments/convert ci
# run the generation script
npm --prefix dev/deployments/convert start
```

## Validation Errors
As far as I can tell, there are no new linting or validation errors introduced by this PR, but it is tricky to tell, because:
- There are a number of unsuppressed existing problems
- Moving APIs from one file to another triggers a bunch of incorrect validations (e.g. removal of an API, introduction of a new API)

Here's a breakdown of the failures I see along with an explanation:
- [SDK azure-resource-manager-schemas failed](https://github.com/Azure/azure-rest-api-specs/pull/27944/checks): This appears to be a pipeline infra issue that happens across many PRs.
- [SDK azure-sdk-for-net-track2 failed](https://github.com/Azure/azure-rest-api-specs/pull/27944/checks): I've confirmed by building locally that this just requires adding the new path to an allowlist ([here](https://github.com/azure-sdk/azure-sdk-for-net/blob/c5366543769d72663d3743e92e86573493b9b248/sdk/resources/Azure.ResourceManager.Resources/src/autorest.md?plain=1#L348-L354)). This will have to happen in a follow-up PR, once this one has been merged.
- [Swagger BreakingChange](https://github.com/Azure/azure-rest-api-specs/pull/27944/checks): These all appear to be false positives because the validation isn't taking into account both files when looking for added/removed APIs.
- [Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/27944/checks): These all appear to be pre-existing problems, and are only being flagged because the validation isn't taking into account the moved APIs.
- [Swagger ModelValidation](https://github.com/Azure/azure-rest-api-specs/pull/27944/checks): These all appear to be pre-existing problems.

### CODE REVIEW

**Comment by raosuhas** [comment]
Approving the suppressions since they were present from before

**Comment by raosuhas** [comment]
Is there actually any breaking change in this PR as the tag says could you please review and get the approval from breaking change board ?

**Comment by anthony-c-martin** [comment]
> Is there actually any breaking change in this PR as the tag says ? could you please review and get the approval from breaking change board ?

There are no real breaking changes here, it's just been misattributed. I've applied the label as per https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

**Comment by ms-henglu** [comment]
Please confirm with the approvers for the failed checks:
❌ Swagger PrettierCheck: This should be a format issue, it's easy to fix.
❌ Swagger LintDiff
❌ Swagger ModelValidation


[Approvers list](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750)

**Comment by anthony-c-martin** [comment]
Superseded by #28546

**Pull request closed without merging**
