### PR TITLE
A2A: Adding new properties and correcting few fields for zone to zone replication

### PR DESCRIPTION
**Pull request by ayfathim**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ayfathim** [comment]
@yungezz : Can you please review the PR

**Comment by yungezz** [comment]
hi @zikalino @qiaozha will it be sdk breaking change to change x-ms-disclaiminator?

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
pending on sdk confirmaiton on a potential breaking change

**Comment by qiaozha** [comment]
> hi @zikalino @qiaozha will it be sdk breaking change to change x-ms-disclaiminator?

Yes. For user who use the old subclass discriminator value now might be unavailable.

**Comment by ayfathim** [comment]
> > hi @zikalino @qiaozha will it be sdk breaking change to change x-ms-disclaiminator?
> 
> Yes. For user who use the old subclass discriminator value now might be unavailable.

We have added the class RecoveryPlanA2ADetails recently, for supporting zone to zone replication in azure site recovery. , as part of PR: https://github.com/Azure/azure-rest-api-specs/pull/7985/files
-We have not declared GA for the zone to zone feature. 
- So we dont have any current users who are using this field, and for whom this will be a breaking change.

**Comment by yungezz** [comment]
more info from @ayfathim about the change
```
[1:06 PM] Ayesha Fathima
    about the change in discriminator value
​[1:06 PM] Ayesha Fathima
    

We have added the class RecoveryPlanA2ADetails recently, for supporting zone to zone replication in azure site recovery. , as part of PR: https://github.com/Azure/azure-rest-api-specs/pull/7985/files
-We have not declared GA for the zone to zone feature.


	
So we dont have any current users who are using this field, and for whom this will be a breaking change.


```

**Comment by yungezz** [comment]
hi @NullMDR @isra-fel  could you pls help to look at the .NET CI task failure? thanks

**Pull request merged**
