### PR TITLE
DeploymentManager: Override client name for python SDK

### PR DESCRIPTION
**Pull request by deveshguha**
### Latest improvements:
Overriding client name for python SDK. 
No functional changes to API. 

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by deveshguha** [comment]
We don't have a ruby SDK yet. And don't want that published yet as we are in preview.

**Comment by sergey-shandar** [comment]
@netrock please, review

**Comment by deveshguha** [comment]
Updated with a small fix for C# sdk generation settings.

**Review by NetRock — APPROVED** [review]

**Comment by deveshguha** [comment]
@sergey-shandar I am retrying the azure-sdk-for-net build here, as I could not find any relevant changes that would have caused this. Please let me know if there is a specific error that needs fixing here.

**Comment by sergey-shandar** [comment]
@shahabhijeet @dsgouda could you have a look?

**Comment by dsgouda** [comment]
@sergey-shandar This is a new RP and we have a separate process to onboard them, please disregard this failure.

**Comment by deveshguha** [comment]
@sergey-shandar If there are no open issues, can you get this merged today? 
The .NET SDK is blocked on this being merged.

**Review by dsgouda — APPROVED** [review]
LGTM

**Review by sergey-shandar — APPROVED** [review]

**Comment by sergey-shandar** [comment]
@sarangan12 could you check ruby? https://dev.azure.com/azure-sdk/public/_build/results?buildId=14476

**Comment by deveshguha** [comment]
> @sarangan12 could you check ruby? https://dev.azure.com/azure-sdk/public/_build/results?buildId=14476
Just want to add some context regarding this, we don't have a ruby sdk presence and don't plan to publish with this change.

**Comment by sarangan12** [comment]
The Ruby error is ecpected and could be ignored.  Merging this

**Pull request merged**
