### PR TITLE
fix invalid container names in examples.

### PR DESCRIPTION
**Pull request by rikogeln-havok**
Azure Blob Storage container names are not allowed to have upper case letters

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify 
        - Fix for invalid example values
      
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  no api change - change only in example values
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  as soon as convenient 
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### CODE REVIEW

**Comment by rikogeln** [comment]
@anuchandy could you take a look?

**Comment by rikogeln** [comment]
@anuchandy could you please take a look?

**Comment by rikogeln** [comment]
@anuchandy could you please take a look?

**Review by JeffreyRichter — APPROVED** [review]

**Comment by rikogeln** [comment]
@JeffreyRichter - thanks for approving the PR. I am not authorized to merge the pull request - can you do so please?

**Comment by JeffreyRichter** [comment]
@anuchandy can merge

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
