### PR TITLE
applicationinsights: updating the swagger to match the breaking api change

### PR DESCRIPTION
**Pull request by tombuildsstuff**
As [per this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/16805#issuecomment-1128496426) the API now returns a 201 when it previously used to return a 200 - as such both a 200 and 201 should be documented in the Swagger to match the API definition.

The breaking API change should also be reverted, but that's a separate problem.

FYI @JeffreyRichter @jhendrixMSFT

### CODE REVIEW

**Comment by grlima** [comment]
Backend has been fixed and returning 200. I don't think existing versions of the API should be changed.

**Review by grlima — COMMENTED** [review]
Let's not change existing versions of the API (breaking change). Backend has been reverted to returning 200, so existing contract will remain.

**Comment by tombuildsstuff** [comment]
@grlima since this is the second time this breaking change has been unintentionally rolled out to this  particular API, whilst I agree it should only highlight a 200, is there any harm leaving this in incase this surfaces again?

**Comment by akning-ms** [comment]
consider breaking change and backend reverted to returning 200 and original issue closed, I will close this PR for now. pls re-open if need

**Pull request closed without merging**
