### PR TITLE
API Version 2019-09-01-preview Peering

### PR DESCRIPTION
**Pull request by rileymckenna**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@rileymckenna Hello. Since this PR add new property into the 2019-09-01-preview version. I will invite ARM team's review. Besides, I have a question, why do you remove the old api version like 2019-03-01 and 2019-06-01?

**Comment by rileymckenna** [comment]
i merged with master, those apis were deprecated in a previous PR.

**Review by ryansbenson — COMMENTED** [review]
This is primarily a description and operation id change. Aside from marking a few properties as readonly, the majority of the functional change is the readonly fields of PeeringServicePrefixProperties.

**Comment by zikalino** [comment]
the differences between 2019-09-01 and 2019-08-01 are minimal:
- renamed some operation ids
- additional enum values
- readonly value changes
… merging

**Review by zikalino — APPROVED** [review]

**Pull request merged**
