### PR TITLE
Move server service level objectives to servers.json

### PR DESCRIPTION
**Pull request by nathannfan**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/1223)

### CODE REVIEW

**Comment by balajikris** [comment]
Hey @nathannfan - so all commits to this PR are purely moving stuff from one spec to another? No other additions/deletions expected?

**Comment by nathannfan** [comment]
@balajikris yep, just doing this to rework the categories we're generating in docs.microsoft.com.  I did have to copy SubResource to servers.json as a dependency, but nothing new.

**Review by balajikris — APPROVED** [review]

**Comment by balajikris** [comment]
For existing warns/errors, there is a open workitem that we're tracking. This PR doesn't create any new violations. I've reviewed the changes and I'm okay with it. Merging in as is.

**Comment by nathannfan** [comment]
Thanks, @balajikris!

**Pull request merged**
