### PR TITLE
Fixing example for virtual wan supported security provider api.

### PR DESCRIPTION
**Pull request by nalinrajgupta**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by dsgouda** [comment]
@MikhailTryakhov please advise on what target branch should @nalinrajgupta use

**Comment by number213** [comment]
@dsgouda Since we just merged Network into master I think it should target master, but change should  be applied to 2018-12-01, not 2018-11-01
@nalinrajgupta please sync your branch with master and re-apply your changes to API version 2018-12-01

**Comment by dsgouda** [comment]
@veronicagg Running into linter diff failures for a couple of networking related PRs, who can we contact to take a look into it?

**Comment by veronicagg** [comment]
@dsgouda the error indicates an out of memory exception, we should investigate further. For now you can try running this one locally and see if it passes. This change seems small, so it should not be related. I'll open an issue on the linter. Thanks!

**Comment by dsgouda** [comment]
Thanks @veronicagg I will verify this locally

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@veronicagg  I can run the linter locally and did not see any obvious issues but I don't have the merge permissions, could you do the honors

**Pull request merged**
