### PR TITLE
chore: jsonfmt mediaservices

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/mediaservices/**/*.json"`

### CODE REVIEW

**Comment by nschonni** [comment]
@BrianBlum I adjusted some camelCase in the examples in separate commits from the formatting. I can pull that stuff out if you prefer

**Comment by nschonni** [comment]
I've pulled out the example changes to keep it cleaner

**Comment by nschonni** [comment]
@jhendrixMSFT any idea where to report the issue with the breaking change job? I looks like it's having trouble parsing an int64.Max value and reading it as larger than the value in the example (9223372036854776000 vs 9223372036854775807 actual)?
```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: JSON integer 9223372036854776000 is too large or small for an Int64. Path 'paths['/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaServices/{accountName}/accountFilters'].get.x-ms-examples['List all Account Filters'].responses.200.body.value[0].properties.presentationTimeRange.presentationWindowDuration', line 373, position 75.
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at AutoRest.Swagger.SwaggerParser.Parse(String swaggerDocument, String fileName) in D:\a\1\s\openapi-diff\src\modeler\AutoRest.Swagger\SwaggerParser.cs:line 16
   at AutoRest.Swagger.SwaggerModeler.Compare(String fileNameOld, String swaggerOld, String fileNameNew, String swaggerNew, Settings settings) in D:\a\1\s\openapi-diff\src\modeler\AutoRest.Swagger\SwaggerModeler.cs:line 29
```

**Comment by BrianBlum** [comment]
We hit that on another PR. The value is getting rounded up for some reason. I shrunk the value in the examples. FYI, I'm waiting for some issues in the java SDK autoPR to get resolved before I approve this PR.

**Comment by nschonni** [comment]
@BrianBlum thanks, do you know if there is an issue or internal bug tracking the int64.max thing already?

**Comment by BrianBlum** [comment]
@nschonni I don't know if there's a bug tracking it.

**Comment by jhendrixMSFT** [comment]
@sergey-shandar do you know about this failure in the breaking changes job?

**Comment by nschonni** [comment]
@BrianBlum I rebased this after your last PR landed

**Review by BrianBlum — APPROVED** [review]
@nschonni, Thanks

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
