### PR TITLE
Add sql subscription usages

### PR DESCRIPTION
**Pull request by jaredmoo**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jaredmoo** [comment]
.net sdk tests: https://github.com/jaredmoo/azure-sdk-for-net/tree/subscriptionUsages

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
There are a few modeler validation errors that need to be fixed, see the travis [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/296397121).

**Review by ravbhatnagar — DISMISSED** [review]
Please follow the contract as implemented here - https://docs.microsoft.com/en-us/rest/api/compute/usage/usage-get
A couple of things that need to be fixed are -
1. Add a "name" property
2. Remove display name
3. All properties are top level
4. Add id property which is missing in the above link I sent. type property is not needed.

**Comment by ravbhatnagar** [comment]
@jaredmoo - some feedback above. Thanks!

**Comment by jaredmoo** [comment]
@ravbhatnagar ack, thanks for the feedback but this API has been live for a few months already so I can't make changes :( we just missed adding it to Swagger . I'll log this feedback in the source code so we don't lose track of it.

**Comment by ravbhatnagar** [comment]
@jaredmoo - Thanks! Please do fix this since this contract will be enforced for all service teams and we should have consistency. 
@jhendrixMSFT  - ARM signs off. Please put the conditionally merge label when you merge this PR.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
