### PR TITLE
Add Java configuration for Swagger to SDK bot

### PR DESCRIPTION
**Pull request by ghost**
The Azure REST API Specs portion of onboarding the Java SDK to be generated by the `Swagger -> SDK` bot.

### CODE REVIEW

**Comment by daschult** [comment]
@lmazuel Merge conflicts resolved. Please take a look. Thanks!

**Comment by lmazuel** [comment]
@daschult Hum, conflicts are back :(
Should not prevent me to test it though, I do that asap!

**Comment by lmazuel** [comment]
@daschult LGTM, I merge it to avoid more conflicts, we can refine it later anyway. Thanks!!

**Comment by jianghaolu** [comment]
I appreciate the changes being done here for Java to catch up with Python but this has broken the code generation for the Java SDK. If I'm understanding it correctly, an extra required parameter is added here for Java code generation: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.md#java, while I think it will be nice to make `azure-libraries-for-java-folder` an optional parameter defaulted to the current folder.

As a matter of fact, I'm a little concerned about service teams that own their own data plane Java SDKs. Despite the vision we might want to bring them all together, which is another debate, most of them will want to specify `output-folder` explicitly instead of trying to guess which argument to provide for `azure-libraries-for-java-folder`. Hard-coding the output folder partially might be helpful for us in building 18, but introduces pain for anyone who wants to generate in a different folder.

Also, I'd recommend `fluent` argument to be removed too from the readme. The current default behavior for the Java generator is to not generate fluent code. Service teams are generating with that today. Some customers are actually generating non-fluent code from the latest Swagger specs like that today as well. Fluent is our special scenario actually, which we are already adding extra arguments for in our gulp files.

**Pull request merged**
