### PR TITLE
[Storage] Set the SignedResource as optional in ListServiceSAS

### PR DESCRIPTION
**Pull request by blueww**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

The rest spec set it as required before. But as feature team check on the Server, this should be optional.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
Heads up there are some troubles with the examples, you can see them enumerated here:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/406092205#L753

However, it's pretty clear to me that they weren't introduced by this PR, so I won't block on it.

**Review by marstr — APPROVED** [review]

**Comment by blueww** [comment]
@marstr 
I have added the description to fix the issue in example.
Not sure why this issue not reported before, as the code is not new.

Would you please help to review and merge?
I need to send hte SRP SDK PR after this PR is merged.

**Comment by blueww** [comment]
@marstr 

Let me know if anything blocks the merge, I need send the SDK PR after the swagger PR is merged.

**Comment by blueww** [comment]
@marstr 
Could you please help to merge this PR is no other comments?
The PR has last for several days.

**Comment by blueww** [comment]
@marstr 
Yes, I would appreciate it if you can merge it ASAP.

**Comment by jhendrixMSFT** [comment]
@AutorestCI regenerate azure-sdk-for-go

**Pull request merged**
