### PR TITLE
chore: jsonfmt botservice

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/botservice/**/*.json"`

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Can you fix the failing validation error.

**Comment by nschonni** [comment]
@shahabhijeet the validation error is pre-existing, so I think that would be something the product owner would need to address. Maybe @veronicagg can merge if the build failure is blocking

**Comment by nschonni** [comment]
@shahabhijeet i was able to fix the model validation in this case. Not sure if the API owner should approve or not

**Comment by nschonni** [comment]
@shahabhijeet ping. CI is happy now

**Comment by nschonni** [comment]
@shahabhijeet ping

**Comment by nschonni** [comment]
@jhendrixMSFT can you help land this?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
