### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by montgomp**
Update namespace per shahabhijeet for consistency and discoverability.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [n/a] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [n/a] My spec meets the review criteria:
  - [n/a] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [n/a] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [n/a] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by lmazuel** [comment]
Assigning to @shahabhijeet since I don't have the knowledge to review this one.

**Comment by shahabhijeet** [comment]
@montgomp please add this swagger in a directory as below
specification/DeviceProvisioningService/Resource-manager/Microsoft.Devices/

Currently the directory is called ProvisioningService which does not align with naming convention used rest of the places (docs.microsoft.com and .NET SDK)
Having it called DeviceProvisioningService will align with the rest of the naming convention.

**Comment by lmazuel** [comment]
@montgomp There is also a missing "stable" or "preview" folder, you have to choose between these two folders:
- specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2017-11-15/iotdps.json
- specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/preview/2017-11-15/iotdps.json

If you put it inside "stable", this means that immediately after this PR is merged, you give implicit a go to SDK owners (C#, Java, Python, Node, etc.) to generate and release SDK. Meaning too that the used ApiVersion is available on production for customers.
If you put it inside "preview", this means that no SDK should be released yet. SDK owners needs to wait a PR from you to move from "preview" to "stable" in order to ship anything.

Advantage of that is that "preview" folders implies faster review process and merging. The string review will be delayed until you move it to "stable".

**Comment by montgomp** [comment]
Closing review as concerns have been raised by team owning swagger spec.

**Pull request closed without merging**
