### PR TITLE
Make instance view readOnly

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

This makes instance view properties readonly. They are only applicable for retrieval operations as they represent the state of the compute and are not used on the service side when specified in the payload for the PUT/PATCH.

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by jianyunt — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Not sure what to do with the Go an .NET failures... they don't seem related.

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by njuCZ** [comment]
@TylerLeonhardt since this is stable version, making fields readonly is a breaking change, which would break existing customer's experience. Could we make this change in next stable api version ?

**Comment by TylerLeonhardt** [comment]
@njuCZ although at the spec level this is a breaking change, from a codgen perspective these APIs have never really been released and from the service perspective, if these properties were supplied in a request, they would be ignored so the impact is incredibly minimal/non-existent.

**Review by njuCZ — APPROVED** [review]

**Pull request merged**
