### PR TITLE
Web: Removed HostNameBinding properties.name

### PR DESCRIPTION
**Pull request by LukaszStem**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by fearthecowboy** [comment]
Hey @LukaszStem 

This appears to be a breaking change (property deleted) in `HostNameBinding`

`HostNameBinding` is used both as a result and a parameter object. 

Why does this need to be deleted? (this is going to cause breaking changes across all SDKs)

cc'ing @ravbhatnagar  for his feedback.

**Comment by LukaszStem** [comment]
@fearthecowboy it turns out in our backend we don't use properties.name within the hostnamebinding object at all, it is instead passed in alongside this object. We found this extra property to cause a bug in the recent python sdk update -> https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-web/azure/mgmt/web/models/host_name_binding.py#L69

**Comment by ravbhatnagar** [comment]
@LukaszStem - How would the customers have been using this or setting this today? This is definitely a breaking change and so requires a new API-version. @johanste  @NiklasGustafsson @salameer  as FYI.

**Comment by ravbhatnagar** [comment]
@LukaszStem - any updates on this.

**Comment by ravbhatnagar** [comment]
@fearthecowboy @salameer  - No update on this PR for a long time. not sure what needs to be done here.

**Comment by fearthecowboy** [comment]
Closing due to inactivity. Please file a new PR if you still want to make this change.

FYI; we're adding a feature into AutoRest to remove things from the OpenAPI doc (so they aren't in the wire-protocol) but still generate dummy properties so that changes like this can be corrective without incurring a breaking change in the SDK.

**Pull request closed without merging**
