### PR TITLE
Rename Firewall Policy child resource RuleGroup to RuleCollectionGroup

### PR DESCRIPTION
**Pull request by gimotwanMSFT**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by mmyyrroonn — APPROVED** [review]

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by number213** [comment]
Isn't this a breaking change?
Give change in URI and definition, I think you would also need to update old API versions

**Comment by gimotwanMSFT** [comment]
This feature is in preview. We don’t need to support the new names with older api versions

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gimotwanMSFT** [comment]
@number213 - based on offline discussions, we will only require this with versions 04/01 and beyond. Given this, would you kindly merge this PR? Its unclear if/how I should fix the validation failures in the sdk above

**Comment by MyronFanQiu** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=357086&view=logs&j=b6885ff5-5b63-57e7-07bc-9d8d90d734f1&t=edefe71f-a8fe-52c2-c45d-59609a33c1f2&l=3352
You can ignore the breaking change. Regarding to SDK Net, please check the error messages

**Comment by MyronFanQiu** [comment]
@number213 Once you approved this PR, I can help merge it.

**Review by anton-evseev — APPROVED** [review]

**Comment by number213** [comment]
@MyronFanQiu approved

**Pull request merged**
