### PR TITLE
[Backup] Adding Cross Region Restore flag to existing vault storage config API

### PR DESCRIPTION
**Pull request by gaalla**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
It looks this is the breaking change. Is it possible to use a new API version for it?
The new version has a new property 'crossRegionRestoreFlag' in response that was not found in the old version.

**Comment by lirenhe** [comment]
There are also some old issue related to Semantic check. Please take a look.

**Comment by gaalla** [comment]
> 
> 
> It looks this is the breaking change. Is it possible to use a new API version for it?
> The new version has a new property 'crossRegionRestoreFlag' in response that was not found in the old version.

Hi, so this new property is added to existing API. Also, this is not a required parameter so would this be a breaking change?

**Comment by lirenhe** [comment]
> > It looks this is the breaking change. Is it possible to use a new API version for it?
> > The new version has a new property 'crossRegionRestoreFlag' in response that was not found in the old version.
> 
> Hi, so this new property is added to existing API. Also, this is not a required parameter so would this be a breaking change?

I think so. Also add ARM review board for this PR.

**Comment by ravbhatnagar** [comment]
Removing ARM Feedback label since ARM review board will not be reviewing property level changes going forward.
ALso, as per the Azure API versioning guidelines, adding any property (required or optional) requires a new API-version. If you feel this is not a breaking change, please feel free to talk about the change with Azure api review board and get an exception. Folks who can help are - Adrian Hall, Jeffrey Richter, Johan Stenberg.

**Comment by lirenhe** [comment]
@gaalla, this PR has been there for a while, have you communicated with Azure api review board for this breaking change?

**Comment by gaalla** [comment]
> 
> 
> @gaalla, this PR has been there for a while, have you communicated with Azure api review board for this breaking change?

Hi, we have some more changes to be taken for this feature. Will be raising a new PR separately. Closing this for now. Thanks.

**Pull request closed without merging**
