### PR TITLE
Updated HybridNetwork Swaggers for October release.

### PR DESCRIPTION
**Pull request by congl-microsoft**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by congl-microsoft** [comment]
Hi @raych1 , since there are lots of breaking changes that complained by the pipeline, please refer to our last PR to RPSaaSMaster (https://github.com/Azure/azure-rest-api-specs-pr/pull/2142). Thanks!

**Comment by raych1** [comment]
@congl-microsoft , could you clarify the changes? From the title that says "October release", however it updated the current preview swagger(2020-01-01-preview). As identified in the check, this PR has breaking changes that needs review from breaking change review board.

**Comment by congl-microsoft** [comment]
Hi @raych1 , thank you very much for asking. Yes, this PR contains lots of breaking changes because the current Swaggers on Master is out-dated. It has been a long time that our team didn't update Swaggers to Master branch because our service was still under private preview. We didn't publish any SDK as well. So using the same version with breaking changes will not impact any customers. For the past months, we changed Swaggers a lot on RPSaaSMaster, and each time we followed the reviewers' feedback and got the changes approved. For now, this PR is exactly the same content as our current Swaggers on RPSaaSMaster which was updated a few days ago and merged by Allen Zhang. Before that PR, there was also a PR merged in August. I just share the two PR links here for your reference. [https://github.com/Azure/azure-rest-api-specs-pr/pull/1898] [https://github.com/Azure/azure-rest-api-specs-pr/pull/2142] Would you please let us know if we need to go through the same review process as we already had on RPSaaSMaster? Please feel free to reach out to me on Teams (congl) if you have any concerns.

**Comment by raych1** [comment]
> Hi @raych1 , thank you very much for asking. Yes, this PR contains lots of breaking changes because the current Swaggers on Master is out-dated. It has been a long time that our team didn't update Swaggers to Master branch because our service was still under private preview. We didn't publish any SDK as well. So using the same version with breaking changes will not impact any customers. For the past months, we changed Swaggers a lot on RPSaaSMaster, and each time we followed the reviewers' feedback and got the changes approved. For now, this PR is exactly the same content as our current Swaggers on RPSaaSMaster which was updated a few days ago and merged by Allen Zhang. Before that PR, there was also a PR merged in August. I just share the two PR links here for your reference. [https://github.com/[Azure/azure-rest-api-specs-pr/pull/1898](https://github.com/Azure/azure-rest-api-specs-pr/pull/1898)] [https://github.com/[Azure/azure-rest-api-specs-pr/pull/2142](https://github.com/Azure/azure-rest-api-specs-pr/pull/2142)] Would you please let us know if we need to go through the same review process as we already had on RPSaaSMaster? Please feel free to reach out to me on Teams (congl) if you have any concerns.

Breaking change approved as this is preview swagger with no published SDK.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
