### PR TITLE
Update QnAMaker.json - response code correction

### PR DESCRIPTION
**Pull request by sahithikkss-zz**
Correct PATCH EndpointSettings response code from 200 to 204
Not a breaking change but a correction in response code in docs.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by johanste** [comment]
This is not a Service API breaking change - it is fixing an incorrect description of the service. It may/will be a breaking change for client libraries. Teams may decide to update the return value using readme transforms to avoid new major version of the client library (if the library is not in preview)

**Comment by sahithikkss** [comment]
@johanste , could you please guide us on how to unblock merge for this PR?

**Comment by sahithikkss** [comment]
@yangyuan, could you please review, approve and merge this PR?

**Comment by sahithikkss** [comment]
@bingisbestest @johanste resolved model validation errors. Please review and merge as applicable. Thanks.

**Comment by sahithikkss** [comment]
> ### azure-sdk-for-python
> ###
> ```diff
> - Breaking Change detected in SDK
> ```
> 
> `⚠️` warning [[Logs](https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/azure-rest-api-specs/10828/azure-sdk-for-python/logs.txt)] [Expand Details]
> * `⚠️` Generate from [303c5ca](https://github.com/Azure/azure-rest-api-specs/commit/303c5ca05c7ec4377e67677f24270c3b43fa4c0e) with merge commit [a4e98cb](https://github.com/Azure/azure-rest-api-specs/commit/a4e98cb79c978014bc1e37a3223ebcbca4508344). SDK Automation 13.0.17.20200918.2
> * `⚠️`azure-cognitiveservices-knowledge-qnamaker
>             [[View full logs](https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/azure-rest-api-specs/10828/azure-sdk-for-python/azure-cognitiveservices-knowledge-qnamaker/logs.txt)] 
>             [[Preview SDK Changes](https://github.com/AzureSDKAutomation/azure-sdk-for-python/pull/2093)]
>             Breaking Change Detected* [azure-cognitiveservices-knowledge-qnamaker-0.2.0.zip](https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/azure-rest-api-specs/10828/azure-sdk-for-python/azure-cognitiveservices-knowledge-qnamaker/azure-cognitiveservices-knowledge-qnamaker-0.2.0.zip)* [azure_cognitiveservices_knowledge_qnamaker-0.2.0-py2.py3-none-any.whl](https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/azure-rest-api-specs/10828/azure-sdk-for-python/azure-cognitiveservices-knowledge-qnamaker/azure_cognitiveservices_knowledge_qnamaker-0.2.0-py2.py3-none-any.whl)[build_conf] INFO:packaging_tools:Building template azure-cognitiveservices-knowledge-qnamaker
>   [build_conf] INFO:packaging_tools.conf:Skipping default conf since the file exists
>   [build_conf] INFO:packaging_tools:Skipping CHANGELOG.md template, since a previous one was found
>   [build_conf] INFO:packaging_tools:Template done azure-cognitiveservices-knowledge-qnamaker
>   [build_package] /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
>   [build_package]   warnings.warn(msg)
>   [build_package] warning: no files found matching '*.py' under directory 'tests'
>   [build_package] warning: no files found matching '*.yaml' under directory 'tests'
>   [build_package] /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
>   [build_package]   warnings.warn(msg)
>   [build_package] warning: no files found matching '*.py' under directory 'tests'
>   [build_package] warning: no files found matching '*.yaml' under directory 'tests'
>   [breaking_change_setup] Ignoring mock: markers 'python_version <= "2.7"' don't match your environment
>   [ChangeLog] Size of delta 2.863% size of original (original: 20850 chars, delta: 597 chars)
>   [ChangeLog] **Features**
>   [ChangeLog] 
>   [ChangeLog]   - Model QueryDTO has a new parameter strict_filters_compound_operation_type
>   [ChangeLog] 
>   [ChangeLog] **Breaking changes**
>   [ChangeLog] 
>   [ChangeLog]   - Operation KnowledgebaseOperations.replace has a new signature
>   [ChangeLog]   - Model ReplaceKbDTO has a new signature

`strict_filters_compound_operation_type` is an optional parameter in QueryDTO
In `ReplaceKbDTO` , change is `qnAList` -> `qnaList` a correction to resolve model validation and to be consistent across examples. 
@johanste , could you please see if this can be labelled as "not a breaking change".

**Comment by sahithikkss** [comment]
@johanste  Resolved model validation error by changing the example. Please review.

**Review by johanste — APPROVED** [review]

**Comment by sahithikkss** [comment]
@yangyuan, Could you please merge this PR?

**Review by anuchandy — APPROVED** [review]

**Pull request merged**
