### PR TITLE
Adding pageable back to appliances list, since that is the correct way

### PR DESCRIPTION
**Pull request by vivsriaus**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by vivsriaus** [comment]
@balajikris Can you please review? We'll need this to be merged and new SDK to be published for my CLI PR by tomorrow.  Thanks

**Comment by balajikris** [comment]
hey @vivsriaus : so this PR is simply reverting https://github.com/Azure/azure-rest-api-specs/pull/1186 to add back in `pageable`?

**Comment by balajikris** [comment]
There are some validation failures, but looking at the history, i see this was recently added, reviewed and merged at https://github.com/Azure/azure-rest-api-specs/pull/1179 by @jianghaolu . 

Given the urgency, I have no objections to this change and will be pulling this in.

**Review by balajikris — APPROVED** [review]

**Comment by balajikris** [comment]
I'll merge this and we can address any concerns if they come up as a follow up. @jianghaolu - since you reviewed all the previous PRs for this, can you take a quick look at this change as well?

**Comment by jianghaolu** [comment]
@vivsriaus @balajikris 
Yes there are validation errors on examples. Those are my mistakes. I merged after Vivek added the examples and forgot to check validation results.

**Pull request merged**
