### PR TITLE
Add DeviceStreams properties to IoTHub and modify RoutingTwin object 

### PR DESCRIPTION
**Pull request by ankurkul**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ankurkul** [comment]
@hovsepm This PR can be merged if it clears all the gates.

**Comment by ankurkul** [comment]
@amarzavery  @hovsepm : Could one of your review this pr. would like to merge it soon.

**Comment by amarzavery** [comment]
There is a failure in example validation. Please take a look at the logs over [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/464736238#L604)

**Comment by amarzavery** [comment]
There are still some model validator issues. You can find them here https://travis-ci.org/Azure/azure-rest-api-specs/jobs/466121837#L604. Please fix them.

**Comment by ankurkul** [comment]
Yeah, I am looking into them.

**Comment by ankurkul** [comment]
@amarzavery : Can I run these validations jobs locally before pushing them to PR?

**Comment by amarzavery** [comment]
I think so.
Set these environment variables for model validator
```export MODE=model
export PR_ONLY=true
export CHECK_NAME="Model Validator"
```

Then from the root of the repo
- npm install
- node scripts/modelValidation.js

This should tell you if there are any model validation errors.

NOTE: make sure you have the latest LTS version of node.js installed on your system. You can get that from https://nodejs.org

**Comment by ankurkul** [comment]
There is still one Job that fails while validating models which we haven't changed in this PR (intune.json etc). Not sure how can we resolve them: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/466144309 @amarzavery

**Comment by ankurkul** [comment]
All the other jobs passed. Are we good to merge now?

**Review by amarzavery — APPROVED** [review]

**Pull request merged**
