### PR TITLE
[NetAppFiles] Anf 17315 net app files 2021 10 01

### PR DESCRIPTION
**Pull request by audunn**
Adds api-version 2021-10-01 for ANF 

- LdapSearchScope added to ActiveDirectory
- Minimum pools size changes
- Adds ForceDelete option to volume to force deletion of volumes that are "stuck" in broken replication relationships that prevents deletion.
- Adds unixPermissions to volumePatchProperties
- Adds restoreFiles Action for snapshots, Restore the specified files from the specified snapshot to the active filesystem
- Fix for the  MISSING_PATH_PARAMETER_DEFINITION validate check that was recently added
- Add missing systemData to tracked resource types, Pool, Volume, SnapshotPolicy and BackupPolicy

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by j5lim** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/listReplications": {

This should be POST.

[https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#resource-action-requests](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#resource-action-requests)

---
Refers to: specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json:1259 in 4ce2d03. [](commit_id = 4ce2d03a3ca0d75683957dafc1bc04c997ac38e2, deletion_comment = False)

**Comment by audunn** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/listReplications": {
> > ```
> 
> This should use POST.
> 
> https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#resource-action-requests
> 
> Refers to: specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json:1259 in [1aade10](https://github.com/Azure/azure-rest-api-specs/commit/1aade102188139d58ecdd8843b94d7547f8fd903). [](commit_id = [1aade10](https://github.com/Azure/azure-rest-api-specs/commit/1aade102188139d58ecdd8843b94d7547f8fd903), deletion_comment = False)

As this is not performing any action (change) on a resource but rather returning a list of resources (replication objects) is it not better modeled as a GET  ?

**Comment by j5lim** [comment]
> > > ```
> > > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/listReplications": {
> > > ```
> > 
> > 
> > This should use POST.
> > https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#resource-action-requests
> > Refers to: specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json:1259 in [1aade10](https://github.com/Azure/azure-rest-api-specs/commit/1aade102188139d58ecdd8843b94d7547f8fd903). [](commit_id = [1aade10](https://github.com/Azure/azure-rest-api-specs/commit/1aade102188139d58ecdd8843b94d7547f8fd903), deletion_comment = False)
> 
> As this is not performing any action (change) on a resource but rather returning a list of resources (replication objects) is it not better modeled as a GET ?

If you want to model it as a list of nested resources, the response should have the common fields required for ARM resource like id, name, and type.

https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#get-resource

**Comment by jorgecotillo** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/listReplications": {

Here's an example on how to model this API: [https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274](https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274)

list*** is used as a POST action, POST actions are not used to return a collection. In this case you'll need to create a resource type called `replications` which will return a list. Also you'll need to model a single GET call, something like:

/{volumeName}/replications -> collection GET
/{volumeName/replications/{replicationName} -> single GET

If you will only return one replication then you can model your single GET as a singleton -> /replications/default, but is up to you to decide.

In your example response, you'll need to include: id, type and name (this seems to be a proxy resource so the minimum attributes are these).

---
Refers to: specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json:1259 in 4ce2d03. [](commit_id = 4ce2d03a3ca0d75683957dafc1bc04c997ac38e2, deletion_comment = False)

**Comment by audunn** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/listReplications": {
> > ```
> 
> Here's an example on how to model this API:
> 
> https://github.com/Azure/azure-rest-api-specs/blob/9a19506631005d0ff1e3f394c86a9ce10cf51910/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json#L274
> 
> list*** is used as a POST action, POST actions are not used to return a collection. In this case you'll need to create a resource type called `replications` which will return a list. Also you'll need to model a single GET call, something like:
> 
> /{volumeName}/replications -> collection GET /{volumeName/replications/{replicationName} -> single GET
> 
> If you will only return one replication then you can model your single GET as a singleton -> /replications/default, but is up to you to decide.
> 
> In your example response, you'll need to include: id, type and name (this seems to be a proxy resource so the minimum attributes are these).
> 
> Refers to: specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json:1259 in [4ce2d03](https://github.com/Azure/azure-rest-api-specs/commit/4ce2d03a3ca0d75683957dafc1bc04c997ac38e2). [](commit_id = [4ce2d03](https://github.com/Azure/azure-rest-api-specs/commit/4ce2d03a3ca0d75683957dafc1bc04c997ac38e2), deletion_comment = False)

@jorgecotillo @j5lim  Thank you for your comments, we will remodel this. That means an service side code changes and given our timeline we will be removing this from the 2021-10-01 api version and introducing along with the fix in the next api-version.

**Review by j5lim — APPROVED** [review]
Approved from ARM side.

**Comment by audunn** [comment]
@leni-msft  ARMSignedOff can we move this along?

**Comment by audunn** [comment]
@leni-msft  ARMSignedOff Are we good to move on with this?

**Comment by audunn** [comment]
@leni-msft Hold off on merge for now we may need a change?

**Comment by audunn** [comment]
Note subvolume API was added, reviewed and ARMSignedOff in the private repo,  here
https://github.com/Azure/azure-rest-api-specs-pr/pull/4453

**Comment by audunn** [comment]
@leni-msft breaking change probably caused by changed operation id, reverted

**Comment by audunn** [comment]
@leni-msft Remaining breaking change probably caused attempt to fix staging validation error, `MISSING_PATH_PARAMETER_DEFINITION`,  we wanted to fix for sake of quality. 
Since that is flagged we wonder should we revert those changes or keep them and accept the breaking change flag.

**Comment by leni-msft** [comment]
@audunn Got it. I think it's fine to keep them, but please request breaking change review following Action in https://github.com/Azure/azure-rest-api-specs/pull/17296#issuecomment-1020766128 because there're quite several other "Cross-Version Breaking Changes"

**Comment by audunn** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/13106250

**Comment by jianyexi** [comment]
@audunn  looks some required parameters were removed from below 'path' , please confirm it:
https://github.com/Azure/azure-rest-api-specs/blob/243bb48ba6e5bea1f742492cfc6496d572103613/specification/netapp/resource-manager/Microsoft.NetApp/stable/2021-10-01/netapp.json#L1906

**Pull request merged**
