### PR TITLE
Creator readme

### PR DESCRIPTION
**Pull request by stevemunk**
# Data Plane API - Pull Request
Updates to readme for changes to the Azure Maps and Creator TOC

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

No API have been modified, just the readme.md files that will be used to create the TOC

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

<details>
  <summary>Checks stuck in `queued` state?</summary>
If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.  
</details>

### CODE REVIEW

**Comment by tejitpabari99** [comment]
More information regarding the supression on NOT_LATEST_API_VERSION_IN_DEFAULT_TAG:
We have a tag V2023-07, which is the latest GA version of our API, **not released to the public** (V2 Stable GA version is released). We were planning on releasing it and even prepared docs for it, however, ran into some issues. 
We don't want to delete the docs already created, and let all that effort go to waste. Hence, our latest stable version is V2, and we want to supress V2023-07 to when we ship it next year.

**Comment by tejitpabari99** [comment]
Regarding the Breaking change - spatial should not exist within Creator, but is part of Azure Maps. There is a separate spatial folder here, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/maps/data-plane/Spatial/readme.md, and that should be the version in public: https://learn.microsoft.com/en-us/rest/api/maps/operation-groups?view=rest-maps-2022-08-01
We have never shown spatial on Creator, even though it was part of the 2.0 tag, since we manually didn't display it. We are just removing it here, since it threw up validation errors if it isn't part of the readme.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Avocado may not be able to be suppressed in readme.

Add the label to unblock.

**Pull request merged**
