### PR TITLE
Updated README tag version

### PR DESCRIPTION
**Pull request by PakDLiu**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by erich-wang — APPROVED** [review]

**Review by erich-wang — CHANGES_REQUESTED** [review]
@PakDLiu , there is lint error [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=371954&view=logs&j=688669d0-441c-57c3-cf6d-f89a22ccfa5d&t=923b5a90-e462-5994-c166-86509c6bf5f2) in CI which blocks the merge, please follow the document https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md to fix the error, thx.

**Comment by PakDLiu** [comment]
I have fixed the lint errors.
The breaking change check shouldn't be a problem, the provisioning state is on a GET. We will update the backend according to the change

**Comment by erich-wang** [comment]
Added label "WaitForARMFeeback" since there're new operations added.

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Review by erich-wang — APPROVED** [review]

**Comment by erich-wang** [comment]
@akning-ms , could you help to force merge this PR? thx

**Pull request merged**
