### PR TITLE
added new resource to securityinsights- entityQueries

### PR DESCRIPTION
**Pull request by dosegal**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by praries880** [comment]
@dosegal Kindly fix all the [model validation errors](https://dev.azure.com/azure-sdk/public/_build/results?buildId=40151&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&taskId=43324f1f-6724-5d61-785f-f0ac9fd256a1&lineStart=28&lineEnd=28&colStart=1&colEnd=13).

**Comment by dosegal** [comment]
@praries880 fixed, please review

**Comment by KrisBash** [comment]
Could you please schedule a review meeting with arm api review ? Thanks

**Comment by dosegal** [comment]
@KrisBash I added a new resource (entityQuery) with two endpoints - get and get all. This is the main change in this PR.

The rest of the changes are fixes for the "ModelValidation" test errors that were caused mostly by small discrepancies between some of the api definitions (unrelated to the new resource) and the example files.

Please update if a review meeting is still required. Thanks

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by dosegal** [comment]
@praries880 please review, thanks

**Comment by praries880** [comment]
@dosegal can you kindly take care of the various merge conflicts?

**Comment by dosegal** [comment]
@praries880 fixed

**Review by praries880 — APPROVED** [review]

**Pull request merged**
