### PR TITLE
[HDInsight] Update swagger to support private link feature

### PR DESCRIPTION
**Pull request by aim-for-better**
Update swagger to support network isolation options

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by chiragg4u — CHANGES_REQUESTED** [review]
The changes in the GET part is breaking changes as per the [guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Please update the API version or follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by aim-for-better** [comment]
> The changes in the GET part is breaking changes as per the [guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Please update the API version or follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

Thanks your comments. I have sent email by following the wiki.

**Comment by ravbhatnagar** [comment]
Removing ARM Feedback label since ARM review board will not be reviewing property level changes going forward.

**Review by ArcturusZhang — APPROVED** [review]
Breaking changes should be OK since it is a preview API

**Pull request merged**
