### PR TITLE
Added addressPrefixes to subnet properties

### PR DESCRIPTION
**Pull request by Am018**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by number213** [comment]
FYI current API version is `2018-07-01` (https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager#basic-information)

**Comment by Am018** [comment]
@number213, I have moved the change to 2018-07-01. Let me know if you see any other issues.

**Comment by number213** [comment]
@Am018 I don't know which API version you should target but if you need to add it to 2018-06-01, please also add it to 2018-07-01

**Comment by Am018** [comment]
@number213 , the feature is available from API version  2018-07-01. So I think this should be fine. Is there anything else that I need to do before I can get the approval? Who can approve my PR?

**Review by jianghaolu — APPROVED** [review]

**Comment by jianghaolu** [comment]
@MikhailTryakhov Should this target master or September release?

**Comment by jianghaolu** [comment]
@MikhailTryakhov Can you please take a look at this if this PR should target `master` or `Network-September-Release`. Thanks!

**Comment by MikhailTryakhov** [comment]
It shouldn't be in both of branches specified.
Please use ```Network-October-Release``` branch to push changes

**Review by MikhailTryakhov — CHANGES_REQUESTED** [review]
re-target to the right branch

**Comment by jianghaolu** [comment]
@Am018 Can you retarget to the right branch please?

**Comment by Am018** [comment]
@MikhailTryakhov, @jianghaolu, I will retarget it to  Network-October-Release. However the related feature is already in powershell's network-september-release branch. Can that be an issue?

**Review by MikhailTryakhov — APPROVED** [review]
after branch retarget LGTM

**Review by chandrasekarsrinivasan — COMMENTED** [review]
do not merge

**Pull request closed without merging**
