### PR TITLE
Vwan hubeffectiveroute enhancement

### PR DESCRIPTION
**Pull request by azgcloudev**
### improve POST documentation

Improvement of POST 202 response description, to advise to perform a GET request to the **location** header

### CODE REVIEW

**Comment by dedhar** [comment]
1. We wanted to enhance examples and not original json

**Comment by dedhar** [comment]
2. If we changing json did we vlidate the change

**Comment by dedhar** [comment]
3. Please only change examples for effective routes, get inbound/outbound routes

**Comment by dedhar** [comment]
Please get it review from Katie Steinmeyer and Zayn chen from vwan team

**Comment by sjanamma** [comment]
Please fix the examples to resolve the model validation errors [https://github.com/Azure/azure-rest-api-specs/pull/25449/checks?check_run_id=16153429793](https://github.com/Azure/azure-rest-api-specs/pull/25449/checks?check_run_id=16153429793)

**Comment by azgcloudev** [comment]
@rkmanda I have validation errors that are not related to my changes and even if I run the check in the main branch without my changes I still get the same model validation errors

**Comment by azgcloudev** [comment]
@Joanna-Yang-Art I was able to fix all swagger model issues, but seems lintdiff errors were introduced. Need help to check this.

**Comment by azgcloudev** [comment]
@Joanna-Yang-Art this still need assistance as fatal lint diff checks are not related to files changed in this PR

**Comment by azgcloudev** [comment]
closing as no response from the team

**Pull request closed without merging**
