### PR TITLE
Adding usage id property to support usages by VM family, Workspace & Compute

### PR DESCRIPTION
**Pull request by leizhaoPS**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by dsgouda** [comment]
Please fix the model validation errors [here](https://github.com/Azure/azure-rest-api-specs/pull/6055/checks?check_run_id=133609879)

**Comment by leizhaoPS** [comment]
The modelvalidation failure is not related to my changes, it is related to a check-in by nschonni@gmail.com on MachineLearningCompute_Update

**Comment by leizhaoPS** [comment]
> Please fix the model validation errors [here](https://github.com/Azure/azure-rest-api-specs/pull/6055/checks?check_run_id=133609879)

The modelvalidation failure is not related to my changes, it is related to a check-in by nschonni@gmail.com on MachineLearningCompute_Update

**Comment by leizhaoPS** [comment]
@dsgouda dsgouda , any suggestion to skip the validation failure not related to my changes? Thanks a lot!

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@leizhaoPS @nschonni 's changes were only related to formatting and should not have introduced any errors. Please check if you can fix the example at your end.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by leizhaoPS** [comment]
@sergey-shandar quick question, why my PR was merged, this PR should hold until the feature code check-in

**Comment by dsgouda** [comment]
@leizhaoPS I wasn't aware this was not to be merged. Please open a PR to revert these changes and I will do the needful.
Please mark the title as [DO NOT MERGE] in future so we don't accidentally merge it.

**Comment by leizhaoPS** [comment]
@dsgouda , Thanks for explain, I will mark it in my new PR

**Comment by leizhaoPS** [comment]
@dsgouda , I  sent the revert PR, please help revert the changes: https://github.com/Azure/azure-rest-api-specs/pull/6171, one more question is how can I add reviewers and add label "WaitForARMFeedback"

**Comment by leizhaoPS** [comment]
@dsgouda , new PR created, please help add WaitForARMFeedback able and add Gaurav Bhatnagar <Gaurav.Bhatnagar@microsoft.com>; Sanjai Ganesh Jeenagiri <sanjaiga@microsoft.com> as review.
Thanks a lot for quick response and explain and revert the merge, I am really appropriate it!

**Pull request merged**
