### PR TITLE
[Hub Generated] Review request for Creator to add version stable/2023-07-01

### PR DESCRIPTION
**Pull request by yuqi2**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/yuqi2-maps-Creator-2023-07-01...main/).
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

<details>
  <summary>Checks stuck in `queued` state?</summary>
If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.  
</details>

### CODE REVIEW

**Comment by yuqi2** [comment]
@johanste @stewartadam This is not a breaking change, I only want to change the description, but somehow the module validation keeps failing complaining no "schema" defined for the response. However, if I remove the ref and copy the same thing over, it start complaining about the break change.

**Comment by johanste** [comment]
The reason for the breaking change notification is because client codegen can be impacted by the rename of the type (which is what inlining would mean). I'm pretty sure that our tooling allows you to put the description next to the $ref rather than inlining it - and if so, that is what I would recommend to avoid the breaking change.

**Comment by yuqi2** [comment]
> The reason for the breaking change notification is because client codegen can be impacted by the rename of the type (which is what inlining would mean). I'm pretty sure that our tooling allows you to put the description next to the $ref rather than inlining it - and if so, that is what I would recommend to avoid the breaking change.

Hi Johan, if I don't do it inline and left "ref" there, the ModelValidation will failed due to "missing schema in the response". What is your suggestion in this case?

**Comment by johanste** [comment]
Are you trying to affect the description (documentation) of the responses, or are you just trying to change the description of the `/conversions` action? If the latter, you should not have to make a change to the responses. If the former, you should also not copy the response over but put the updated description field next to the $ref. 

Can you provide a link to the error you are getting when not copying the responses over?

**Comment by yuqi2** [comment]
> Are you trying to affect the description (documentation) of the responses, or are you just trying to change the description of the `/conversions` action? If the latter, you should not have to make a change to the responses. If the former, you should also not copy the response over but put the updated description field next to the $ref.
> 
> Can you provide a link to the error you are getting when not copying the responses over?

Yes, if I keep the change only on the description, this is the ModelValidationError that appeared: https://github.com/Azure/azure-rest-api-specs/runs/18913067538

**Review by johanste — APPROVED** [review]

**Comment by johanste** [comment]
@konrad-jamrozik, I see no reason why this would introduce a model violation error. Can we override the check?

**Comment by konrad-jamrozik** [comment]
> @konrad-jamrozik, I see no reason why this would introduce a model violation error. Can we override the check?

@johanste this check is owned by @scbedd. Full list of owners [on Teams, here](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750).

**Comment by scbedd** [comment]
> > @konrad-jamrozik, I see no reason why this would introduce a model violation error. Can we override the check?
> 
> @johanste this check is owned by @scbedd. Full list of owners [on Teams, here](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750).

Ack notification. I'll check this today.

**Comment by scbedd** [comment]
This is definitely a bug with `oav`. [Here is the issue.](https://github.com/Azure/oav/issues/1021) My intent is to get to it this week. I will sign off for the model validation failure for now while I code a fix.

**Comment by scbedd** [comment]
[This is a failure that was discovered last week](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3323380&view=logs&j=9e7477d6-80c4-54a8-ebef-1e18da128ba0&t=f4a3c60c-600e-599b-d672-ffecbc71e09d&l=268)

I will sign off for the ModelValidation failure. They are false positives.

**Review by scbedd — APPROVED** [review]

**Comment by yuqi2** [comment]
Hi, @johanste @scbedd , thanks for helping on the approval and confirming the issue. Could you help me merge this PR? It shows on my side the merging is still blocked and I am not authorized to merge this PR.
image

**Comment by scbedd** [comment]
I believe that the APIView error may be resolved by an emitter upgrade. Merge wise, I need to find the right ARM contact.

**Comment by tjprescott** [comment]
@scbedd since you added the Approved-ModelValidation tag, why does it continue to block on this?

**Comment by scbedd** [comment]
> @scbedd since you added the Approved-ModelValidation tag, why does it continue to block on this?

The model validation is erroneous, it shouldn't be erroring. However, the check will still fail even if I add the approved-ModelValidation tag. There's no connection of the tags to model or semantic validation.

The two files being touched also don't have readmes associated with them, so there's no easy way to just add a suppression and ignore them.

**Comment by tjprescott** [comment]
> The model validation is erroneous, it shouldn't be erroring. However, the check will still fail even if I add the approved-ModelValidation tag. There's no connection of the tags to model or semantic validation.

That's weird because if the CI is blocked on BreakingChangeReviewRequired, then adding the BreakingChangeApproved tag actually satisfies the CI and causes it to pass. It would see that ModelValidation would do the same thing. So this needs a force merge?

@lmazuel can you do the honors?

**Comment by konrad-jamrozik** [comment]
@scbedd @tjprescott I'll have a look into the suppression-via-label not working:
- https://github.com/Azure/azure-sdk-tools/issues/7455

**Comment by konrad-jamrozik** [comment]
@scbedd @tjprescott running `/azp run` fixed the suppression via the label. Looks like it was just a flake.

**Pull request merged**
