### PR TITLE
add validate resource move 

### PR DESCRIPTION
**Pull request by tfitzmac**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by TimLovellSmith** [comment]
@balajikris /cc @tfitzmac 
LGTM.. I notice one linter warnings/errors that looks like it would be the new one:

```
{
  "type": "Warning",
  "code": "OperationIdNounVerb",
  "message": "Per the Noun_Verb convention for Operation Ids, the noun 'Resources' should not appear after the underscore. Note: If you have already shipped an SDK on top of this spec, fixing this warning may introduce a breaking change.",
  "id": "R1001",
  "validationCategory": "SDKViolation",
  "providerNamespace": null,
  "resourceType": null,
  "sources": [
    "file:///home/travis/build/Azure/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/2017-05-10/resources.json:972:8 ($.paths[\"/subscriptions/{subscriptionId}/resourceGroups/{sourceResourceGroupName}/validateMoveResources\"].post.operationId)"
  ]
}
```
which I interpret to mean 'call it "Resources_ValidateMove" instead of "Resources_ValidateMoveResources"' -

However, the proposed naming seems consistent with ' "operationId": "Resources_MoveResources",' of resource move...
What is more important, internal consistency, or fixing the warning?

**Comment by balajikris** [comment]
@TimLovellSmith -- thanks for taking a look :)
In response to your question, I view consistency as a desirable property among all services, than being constrained to each service. I'd prefer to do it right the first time than introduce a breaking change later. With that said, the change looks good to me as well. I still need to run some tools on the PR before I sign off.

**Comment by balajikris** [comment]
@tfitzmac - couple of things here.

1. The linter bot reports 47 errors (all existing and none newly added) on this spec, is there a plan or a work-item to address these?
2. regarding the 1 warning that's newly introduced, I've left my feedback above. would you be willing to fix the new warning now versus fixing it at a later stage as a bulk update?

**Comment by ravbhatnagar** [comment]
@balajikris - We have plan to fix the issues for existing APIs in [Ca]. We wont fix them at this time. 
As far as the naming is concerned, I think its fine, although I like Resources_ValidateMove better.

**Review by balajikris — APPROVED** [review]

**Pull request merged**
