### PR TITLE
[datafactory] Workaround for Azure Resource Schema

### PR DESCRIPTION
**Pull request by olydis**
@deata FYI - could you please check whether using this configuration file yields a working resource schema? 🙂

### CODE REVIEW

**Comment by olydis** [comment]
@deata did you get a chance to test this fix?

**Comment by deata** [comment]
Not yet. But soon I will ☺

-Dean

**Comment by veronicagg** [comment]
@deata @fearthecowboy should this PR get closed? it shows no activity for a long time. thanks.

**Comment by salameer** [comment]
Closing 

since this is pretty idle now

**Comment by JackTn** [comment]
Hi, @olydis. The PR has be closed for a long time and it's related branch still exist. If no further used for over 14 days, I will delete this related branch. Please tell me if you still need this branch.

**Comment by JackTn** [comment]
Hi, @olydis. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @olydis. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
