### PR TITLE
Service Bus: Revert PR 4245 from 2017

### PR DESCRIPTION
**Pull request by v-Ajnava**
**Note**: We have reverted the PR https://github.com/Azure/azure-rest-api-specs/pull/4245, as there are more service side changes, VNet team wants to standardize there APIs which will changes few VNet and IPFilter rules API. So we are reverting these API from the stable 2017 swagger.

No Clients were published with PR https://github.com/Azure/azure-rest-api-specs/pull/4245

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
Hi @v-Ajnava - a couple of questions:
- when PR #4245 was merged it was considered a deployed API version. Does this mean you are pulling down or breaking an existing API version?
- Is there any reason you cannot publish the API changes as a new API version?
- Additionally, are you aware that once the earlier PR was merged and the Go SDK was generated and merged it is already considered published?
- Do you know the status of other auto-generated SDKs like Ruby, NodeJs and Java?

Finally - you will also need to remove all the tags in the readme files that point to this version. This includes the language-specific tags added for those SDKs that support multi-API versions.

**Comment by annatisch** [comment]
@v-Ajnava - based on the offline email conversation, it sounds like this API version was never deployed.
In this case, please simply remove all the readme tags pointing to this spec.

Thanks!

**Comment by v-Ajnava** [comment]
@annatisch , the API version 2017 is stable version, the VNet and IPFilter features were not deployed in 2017, but unfortunately by our mistake these were added to 2017 API version.
correct me if I am wrong, the readme will have tags pointing to 2017 API version.

**Comment by annatisch** [comment]
Thanks @v-Ajnava - I see you're right, I misread the diff.
However the Java CI is still failing - which seem to be related to the readme parameters?

**Review by annatisch — APPROVED** [review]

**Pull request merged**
