### PR TITLE
Removing MobilePacketCore as service already decommissioned

### PR DESCRIPTION
**Pull request by khattartarun**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by khattartarun** [comment]
Hello Reviewers,

MobilePacketCore service is already decommissioned and same has been updated in [Manifest](https://armmanifest.visualstudio.com/One/_git/Manifest?path=/MICROSOFT.MOBILEPACKETCORE/PROD/MANIFEST.JSON&version=GBmaster&line=10&lineEnd=10&lineStartColumn=4&lineEndColumn=16&lineStyle=plain&_a=contents). Please provide exception for breakingchanges and approve the changes.

**Review by kunalhatkar — APPROVED** [review]

**Comment by khattartarun** [comment]
@suhasaraos can you please approve this PR for merging to main?

**Review by lakshaykaushik — APPROVED** [review]
Service is on deprecation, hence we are removing MobilePacketCore. Changes look good to me

**Pull request merged**
