### PR TITLE
[Hub Generated] Review request for Microsoft.VirtualMachineImages to add version stable/2020-02-14

### PR DESCRIPTION
**Pull request by feiyushi**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/feiyushi/azure-rest-api-specs/dev-imagebuilder-Microsoft.VirtualMachineImages-2020-02-14...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by feiyushi** [comment]
The api-version has not been released to public. No SDK has been released for this api-version.

**Review by yungezz — APPROVED** [review]

**Comment by feiyushi** [comment]
Service takes a hard dependency on the identity starting api-version 2020-02-14 and user must provide a user assigned identity to properly use the service. In this case, there'll be no valid case that `None` type identity is needed, since it'll break normal scenarios. Thus removing the `None` type in this api-version. As stated in an early comment, the api-version is behind a feature flag and no sdk is release for this api-version at this point. Thus please allow the breaking changes introduced in this PR. Thanks.

**Comment by yungezz** [comment]
need ARM feedback since `None` is required for MSI.

**Comment by chiragg4u** [comment]
@feiyushi Waiting for the checks to complete before review.
@yungezz please check why the checks have not been complete?

**Comment by feiyushi** [comment]
> @feiyushi Waiting for the checks to complete before review.
> @yungezz please check why the checks have not been complete?

The checks are complete. There's an issue with status sync. If you click on the `checks` tab, you'll see the results.

**Comment by chiragg4u** [comment]
Thanks for confirming, I will approve the change based on your comment.

---
In reply to: [627104519](https://github.com/Azure/azure-rest-api-specs/pull/9411#issuecomment-627104519) [](ancestors = 627104519)

**Review by chiragg4u — APPROVED** [review]
:shipit:

**Comment by yungezz** [comment]
in ADO https://github.com/Azure/azure-rest-api-specs/pull/9411/checks?check_run_id=669296180, all tasks passed except for BreakingChanges, which is caused by removing `None` in enum.

**Review by chiragg4u — APPROVED** [review]
:shipit:

**Pull request merged**
