### PR TITLE
Fix audience in AzureMetrics IngestMetrics

### PR DESCRIPTION
**Pull request by ad-m**
I believe there is a typo. I am not MSFT and I don't have any clue about release a new version of API & SDK which apply that change.

### CODE REVIEW

**Review by tjprescott — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang looks like a bug in the generation script/tool for Go.

**Comment by tjprescott** [comment]
@jhendrixMSFT thanks for confirming this is a bug. @lmazuel could we get this merged?

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@ad-m can you please sign the CLA?  There's a link above.

**Comment by ad-m** [comment]
@jhendrixMSFT of course.

**Pull request merged**
