### PR TITLE
Update site config and app setting APIs to be LRO

### PR DESCRIPTION
**Pull request by kamperiadis**
# Pull Request
For Centauri, the Microsoft.Web backend makes calls to the Microsoft.App RP, and we end up with long running operations. As such, we need to make adjustments to categorize those API calls as long running operations.

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by kamperiadis** [comment]
Hi team! We have three follow-up questions:
1. For regular function apps, the PUT request will still return a 200 but for Centauri function apps, the PUT request will return a 202. Do my PR changes correctly update the json to support both sync and async versions of the API?
2. Do my PR changes correctly update the json to ensure that the polling logic (LROPoller) would be added in the Python SDK?
3. When will this api version be released?

**Comment by weidongxu-microsoft** [comment]
For (1), I think SDK should be able to handle the case of a hybrid of LRO and non-LRO (I am mostly sure about Java).

I will loop in devs from other SDKs to double check.

Though I am not sure what's special about Centauri that needs an LRO?

**Comment by kamperiadis** [comment]
Thank you for your response @weidongxu-microsoft. For Centauri (function apps deployed in managed container app environments), the Microsoft.Web RP needs to make API calls to the Microsoft.App RP, which performs actions asynchronously. This is why Centauri needs LRO.

**Comment by kamperiadis** [comment]
Waiting for backend team to confirm if the "name" attribute under the "properties" attribute is necessary when creating Centauri function apps (as this is redundant with the PUT request URI)

**Comment by msyyc** [comment]
> d be able to handle the case of a hybrid of LRO and non-LRO (I am mostly sure about Java).

It looks fine for Python.

**Review by v-shenoy — APPROVED** [review]
Thanks for these changes, @kamperiadis. Looks good!

**Comment by zizw123** [comment]
> Hi @kamperiadis, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/23488&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.

Hi, is there breaking changes in this PR? If so please get them approved and come back for ARM review

**Comment by ihsanali01** [comment]
Thanks & Go ahead please.

**Review by ihsanali01 — APPROVED** [review]
Thanks & Go ahead please.

**Comment by ihsanali01** [comment]
Thanks & Go ahead please.

**Review by ihsanali01 — APPROVED** [review]
Thanks & Go ahead please.

**Review by ihsanali01 — APPROVED** [review]

**Review by ihsanali01 — APPROVED** [review]
Approved.

**Review by ihsanali01 — APPROVED** [review]
Approved.

**Review by ihsanali01 — APPROVED** [review]
Approved.

**Review by ihsanali01 — APPROVED** [review]
Approved.

**Pull request closed without merging**
