### PR TITLE
Add common v2/types.json to fix the ErrorResponse Schema 

### PR DESCRIPTION
**Pull request by jianyexi**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
This PR is for adding a default definition for error response which specify in Linter rule: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r4007-defaulterrorresponseschema

the definition of v1 and is not match with Linter rule, create a V2 to fix it in this PR.
file position in v1: https://github.com/Azure/azure-rest-api-specs/blob/7f1b65db7aa74b4668d000eb27c1c0ffd8d91334/specification/common-types/resource-management/v1/types.json#L272

**Comment by akning-ms** [comment]
Add ARM for confirm this approach to support new definition for common definition: @pilor  @ravbhatnagar

**Comment by pilor** [comment]
> Add ARM for confirm this approach to support new definition for common definition: @pilor @ravbhatnagar

@chiragg4u should be able to help

**Review by akning-ms — APPROVED** [review]

**Comment by akning-ms** [comment]
merged it first as some other PR pending on this PR to fix Lint R4007, Let me know if any comments for this approach. @ARM

**Pull request merged**
