### PR TITLE
Operationalinsights/data export v1/8/20 delete alltables

### PR DESCRIPTION
**Pull request by hohershk**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by hohershk** [comment]
Hey @kairu-ms 
The ticket of breaking change approved
https://msazure.visualstudio.com/One/_workitems/edit/8688210
Can you merge this PR?

**Comment by varunkumta** [comment]
please follow breaking change policy link in the PR description to request a review and exception for this breaking change.

**Review by varunkumta — CHANGES_REQUESTED** [review]
please follow breaking change policy link in the PR description to request a review and exception for this breaking change.

**Review by kairu-ms — APPROVED** [review]

**Comment by varunkumta** [comment]
> please follow breaking change policy link in the PR description to request a review and exception for this breaking change.

I see the breaking change has already been approved. Approving from ARM side

**Review by varunkumta — APPROVED** [review]
breaking changes approved as per https://msazure.visualstudio.com/One/_workitems/edit/8688210

**Comment by kairu-ms** [comment]
@varunkumta I am not authorized to merge this PR. What should I do?

**Comment by mikhailshilkov** [comment]
> breaking changes approved as per https://msazure.visualstudio.com/One/_workitems/edit/8688210

This is not publicly accessible. Could you please explain the breaking change in this PR?

**Comment by varunkumta** [comment]
> > breaking changes approved as per https://msazure.visualstudio.com/One/_workitems/edit/8688210
> 
> This is not publicly accessible. Could you please explain the breaking change in this PR?

@hohershk can provide more details. However, the linked work item mentions this is the removal of a feature in private preview.

**Comment by hohershk** [comment]
1.	The “allTables” property was used during the private preview period
2.	We communicated to private preview customers that “allTables” property is being removed before the public preview. There was about 6 customers in private preview period.
3.	No public preview customer could set export rule with “allTables” property and there is **no breaking experience to any PUBLIC PREVIEW customer.**
4.	Current state – users see the “allTables” property but can’t use it as we fail these operations

**Comment by mikhailshilkov** [comment]
Thank you for your response. Was the stable version 2020-08-01 also used for private preview?

**Comment by hohershk** [comment]
No.
only "2019-08-01-preview", "2020-03-01-preview" was in use

**Comment by mikhailshilkov** [comment]
So why has it changed too https://github.com/Azure/azure-rest-api-specs/pull/11429/files#diff-b66cdf5669ee614abd69e9812273ccfc95a2b083657cbf8fd6acbad091ac2696 ?

**Comment by hohershk** [comment]
Why to change the preview versions too?
While the private preview period , the "allTables" property caused many issues (like data lost etc.) so we decided to remove it from all version. All customers aware of that and using "tableNames" property instead.

**Pull request merged**
