### PR TITLE
[Batch] new data plane and mangement plane version 2019-08-01

### PR DESCRIPTION
**Pull request by xingwu1**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by daschult** [comment]
@openapibot sdkautomation rebuild

**Comment by daschult** [comment]
@openapibot sdkautomation rebuild

**Comment by NullMDR** [comment]
@openapibot sdkautomation rebuild

**Comment by xingwu1** [comment]
Can any from ARM team review it?

**Comment by majastrz** [comment]
>     "version": "2019-08-01.10.0",

This is not a valid API version format. You should set this to `2019-08-01` and also rename the folder to `2019-08-01`.

---
Refers to: specification/batch/data-plane/Microsoft.Batch/stable/2019-08-01.10.0/BatchService.json:5 in 4b9ce59. [](commit_id = 4b9ce59c5d971851a46d1fa96ccfb4851bf6c83c, deletion_comment = False)

**Comment by majastrz** [comment]
>     "version": "2019-08-01.10.0",

The valid format looks like YYYY-MM-DD with an optional suffix like -preview, -alpha, -beta, -rc, or -privatepreview. No other formats are allowed by ARM.

---
In reply to: [516665304](https://github.com/Azure/azure-rest-api-specs/pull/6723#issuecomment-516665304) [](ancestors = 516665304)

---
Refers to: specification/batch/data-plane/Microsoft.Batch/stable/2019-08-01.10.0/BatchService.json:5 in 0e07fef. [](commit_id = 0e07fef68540a9f41408d6645f771c1280b346ab, deletion_comment = False)

**Review by majastrz — CHANGES_REQUESTED** [review]
You are using an unsupported API version format. I added a comment around it. Please fix that. Everything else seems good from ARM side.

**Comment by majastrz** [comment]
>     "version": "2019-08-01.10.0",

Sorry I didn't realize this was a data plane API, which does not follow those rules. 

---
In reply to: [516665883](https://github.com/Azure/azure-rest-api-specs/pull/6723#issuecomment-516665883) [](ancestors = 516665883,516665304)

---
Refers to: specification/batch/data-plane/Microsoft.Batch/stable/2019-08-01.10.0/BatchService.json:5 in 4b9ce59. [](commit_id = 4b9ce59c5d971851a46d1fa96ccfb4851bf6c83c, deletion_comment = False)

**Review by majastrz — APPROVED** [review]
Looks good to me.

**Comment by xingwu1** [comment]
@amarzavery could you merge our spec?

**Review by amarzavery — APPROVED** [review]

**Pull request merged**
