### PR TITLE
Service fabric rest api spec

### PR DESCRIPTION
**Pull request by msjeffreychen**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@msjeffreychen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jefchen). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
Why do you have a $ in the path. For example at this [line](https://github.com/msjeffreychen/azure-rest-api-specs/blob/servicefabric/arm-servicefabric/2016-01-28/swagger/servicefabric.json#L9). What does it mean?

**Comment by amarzavery** [comment]
OperationIds should generally be of the form: {noun}_{verb}. Let's take the example at this [line](https://github.com/msjeffreychen/azure-rest-api-specs/blob/servicefabric/arm-servicefabric/2016-01-28/swagger/servicefabric.json#L11). 

GetClusterManifest  ==> ClusterManifest_Get
The noun will become an operation group (a logical grouping of all the operations on an artifact).
Then the API will look like this: client.clusterManifest.get().

It is ok to have one word for operationIds. That will translate to all the operations on the client itself.
client.getClusterManifest(). 
This could be a problem during intellisense when you have lot of methods. Hence grouping them logically  provides a better user experience.

**Comment by amarzavery** [comment]
Are you sure, you want the host to be this for your service: ` "host": "localhost:19007",`

**Comment by amarzavery** [comment]
You can define api-version as a global parameter one time and then refer it every where. Take a look at this example https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2015-06-15/swagger/storage.json#L39

**Comment by amarzavery** [comment]
[Line 27](https://github.com/msjeffreychen/azure-rest-api-specs/blob/servicefabric/arm-servicefabric/2016-01-28/swagger/servicefabric.json#L27) Is ClusterManifest a string ? Why are you not modeling you response in the definitions section. If you model it, then the generated code will deserialize it for you.

**Comment by amarzavery** [comment]
It is ok to have an inline body schema definition. The generator will give it a name and defined a model for it any ways. However, you can define this [body parameter](https://github.com/msjeffreychen/azure-rest-api-specs/blob/servicefabric/arm-servicefabric/2016-01-28/swagger/servicefabric.json#L46) in the definitions section and name it in a way that you prefer and then reference it in the operation. For [example](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2015-06-15/swagger/storage.json#L84).

**Comment by amarzavery** [comment]
Please provide description for your operations, parameters, model definitions and properties of the model definitions. These descriptions are converted into documentation of the generated code. There are teams that use this description and convert it into msdn documentation as well. Hence description is very important.

**Comment by amarzavery** [comment]
Otherwise the spec looks good.

**Comment by msjeffreychen** [comment]
1. Many of our APIs have "$" character. We use that to represent end of a token. For example, we use {appName}/{serviceName}. The appName and serviceName could have "/" in the middle, like app1/us/service1/test. In this case, we do not know what part is appName, and what part is serviceName. So, we had to use "$" is the middle to separate the two names.
3. Our commands will read a local config file to determine the hostname, we are not really using the hostname in the swagger file.
5. ClusterManifest is just a big XML string.

**Comment by amarzavery** [comment]
Makes sense for point 1 and 3.
For point 2: The generated code will be shipped as a package in different languages (C#, NodeJS, Java) and the source code will stay in the respective azure-sdk-for-(languageName*) github repository that developers can use to write scripts against your service. The default baseUri for the generated client would look like https://localhost:19007. If they want to access the servicefabric service, then what endpoint are they suppose to use ?

**Comment by msjeffreychen** [comment]
Currently, all of our commands are connecting to the actual cluster to manage the cluster. We do not have any command to connect to a central endpoint. Users will have to provide an endpoint to the client. This is the same for our powershell client. I have a cli command "azure servicefabric cluster connect [url]" to save the url to a config. All commands will use this config to know the endpoint location.

**Comment by amarzavery** [comment]
Please document this in the swagger description in the info section. Take a look at an example [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#info-object-example)

**Comment by msjeffreychen** [comment]
4. I noticed if I define api-version as global parameter, I will need to pass the value when I initialize the client, not when I make the API call. Assuming I am using this client for multiple APIs, and each with different api-version. This would not be possible?

**Comment by amarzavery** [comment]
The apiVersion is a property on the client and has a default value set. apiVersion is the contract between the server and the client. Changing the apiVersion means, breaking changes. It is not advisable to have multiple apiVersions in a single client.

**Comment by amarzavery** [comment]
Look over [here](https://github.com/Azure/azure-rest-api-specs/tree/master/arm-storage). There are different swagger specs for different api versions

**Comment by msjeffreychen** [comment]
Let's say the case is not api-version, it is one other field called Foo. It is also being passed as query for every API. Does that mean I need to define in definitions section instead of parameters? I noticed every model under parameters section would be treated as global value, and cannot be easily changed for an API.

**Comment by amarzavery** [comment]
Nope you don't need to do this for any other query parameter as such. ApiVersion and SubscriptionId are special for Azure. If you look at Apis of Twitter or FaceBook they have apiversion in their basepath.
For Example
/V1/users/friends/...
/V2/users/friends/..

Azure took a rather sucky approach to define api-version as a query parameter. However. less sucky compared to specifying it in the request header ..

We are planning to add an extension called ("x-ms-client-property": false) to be set on the global parameters, so that every global parameter need not be a property on the client.

**Comment by amarzavery** [comment]
@msjeffreychen - Any updates on changes mentioned in the feedback ?

**Comment by msjeffreychen** [comment]
Sorry, I am still adding more APIs to the spec. I will submit that soon.

**Comment by msjeffreychen** [comment]
I have fixed according to the code review. Please review. Thanks.

**Pull request merged**
