### PR TITLE
Eddelrio/network august release

### PR DESCRIPTION
**Pull request by ejdelrio**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by anton-evseev — CHANGES_REQUESTED** [review]

**Review by anton-evseev — CHANGES_REQUESTED** [review]

**Review by anton-evseev — CHANGES_REQUESTED** [review]

**Comment by number213** [comment]
Some CI jobs are failing with the same error. This seems like an issue with the tooling. @lirenhe @zikalino @yungezz could you please take a look?

```
scripts/multiapi.ts(95,40): error TS2345: Argument of type 'Set<string>' is not assignable to parameter of type 'Iterable<any>'.
  Types of property '[Symbol.iterator]' are incompatible.
    Type '() => IterableIterator<string>' is not assignable to type '() => Iterator<any>'.
      Type 'IterableIterator<string>' is not assignable to type 'Iterator<any>'.
        Types of property 'next' are incompatible.
          Type '(...args: [] | [undefined]) => IteratorResult<string, any>' is not assignable to type '() => IteratorResult<any>'.
            Type 'IteratorResult<string, any>' is not assignable to type 'IteratorResult<any>'.
              Type 'IteratorYieldResult<string>' is not assignable to type 'IteratorResult<any>'.
                Types of property 'done' are incompatible.
                  Type 'false | undefined' is not assignable to type 'boolean'.
                    Type 'undefined' is not assignable to type 'boolean'.
npm ERR! Test failed.  See above for more details.
```

**Review by anton-evseev — APPROVED** [review]

**Comment by number213** [comment]
@KrisBash could you please review this from ARM team's side?

**Review by KrisBash — APPROVED** [review]
LGTM

**Review by KrisBash — APPROVED** [review]
LGTM

**Comment by ejdelrio** [comment]
public.rest-api-specs (SDK java) is timing out causing public.rest-api-specs to fail

**Comment by number213** [comment]
Rebased PR to include fixes for CI that were merged into `network-august-branch` recently
I don't think we can do anything about SDK java right now. @yungezz, could you please merge this PR?

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
