### PR TITLE
Add 202 to operation checkPrivateLinkServiceVisibility

### PR DESCRIPTION
**Pull request by 00Kai0**
add code 202 to fix this operation.
https://github.com/Azure/azure-sdk-for-python/pull/11601

### CODE REVIEW

**Review by anton-evseev — APPROVED** [review]

**Review by allenjzhang — COMMENTED** [review]
Does this change go all the way back to 2019-04-01 stable version?

**Comment by MyronFanQiu** [comment]
@00Kai0 Please fix ModelValidation as well. Meanwhile, could you please share the context about this change? This api has been there for one year. Is it a bug fix or a new design?

**Comment by 00Kai0** [comment]
yeah, I tested with version 2019-04-01. It also retuened 202.
record:
```
- request:
    body: '{"privateLinkServiceAlias": "mypls.00000000-0000-0000-0000-000000000000.azure.privatelinkservice"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '98'
      Content-Type:
      - application/json
      User-Agent:
      - azsdk-python-azure-mgmt-network/11.0.0 Python/3.6.9 (Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic)
    method: POST
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/checkPrivateLinkServiceVisibility?api-version=2019-04-01
  response:
    body:
      string: 'null'
    headers:
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operations/ff6b7a60-4c12-40d4-b3e7-49335897b6ac?api-version=2019-04-01
      cache-control:
      - no-cache
      content-length:
      - '4'
      content-type:
      - application/json; charset=utf-8
      date:
      - Thu, 11 Jun 2020 03:03:24 GMT
      expires:
      - '-1'
      location:
      - https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operationResults/ff6b7a60-4c12-40d4-b3e7-49335897b6ac?api-version=2019-04-01
      pragma:
      - no-cache
      server:
      - Microsoft-HTTPAPI/2.0
      - Microsoft-HTTPAPI/2.0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      x-ms-arm-service-request-id:
      - ab41d052-34e6-40b0-a974-72249a6986dc
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
    status:
      code: 202
      message: Accepted
```

**Comment by number213** [comment]
Please also do this change in `network-june-release` for API version 2020-06-01

**Comment by MyronFanQiu** [comment]
@00Kai0 Please follow @number213 's instruction. I think the better way is to open a PR targeting at `network-june-release` branch

**Comment by 00Kai0** [comment]
it's ready. #9821

**Comment by MyronFanQiu** [comment]
Closed this PR since it's useless. #9821

**Comment by number213** [comment]
@MyronFanQiu I assumed since it's a bugfix it should update all versions. I think we sohuld also take this PR in

**Comment by MyronFanQiu** [comment]
@number213, I saw same changes in #9821. Do you mean we should open this PR and merge this one?

**Comment by number213** [comment]
@MyronFanQui yep, this PR fixes all API versions in master, while the other one introduces a fix only in upcoming API version

**Comment by number213** [comment]
@MyronFanQiu i yep, this PR fixes all API versions in master, while the other one introduces a fix only in upcoming API version

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu i yep, this PR fixes all API versions in master, while the other one introduces a fix only in upcoming API version

But in #9821, it also fixes 2020-04-01 version.

**Review by mmyyrroonn — APPROVED** [review]

**Comment by ravbhatnagar** [comment]
Adding a new response code to existing apis/versions is a breaking change.

**Comment by changlong-liu** [comment]
Hi @ravbhatnagar , this PR is to correct the response code in swagger so that it can match what service side actually return.   Shall it be a bug fix?

+ @number213 for confirmation.

**Comment by number213** [comment]
@changlong-liu it is suppossed to be a hotfix AFAIK

**Comment by qiaozha** [comment]
@ravbhatnagar Can you put this as high priority. Since it's a bugfix. The breakingchange failure should be ok. right? 
cc @allenjzhang

**Comment by ravbhatnagar** [comment]
Signing off from ARM side.

**Comment by MyronFanQiu** [comment]
@akning-ms Hello. Could you help us merge this PR since it's a bug fix.

**Pull request merged**
