### PR TITLE
Reservations RP 2018-06-01 Preview: Add new reserved resource enum type RedHat

### PR DESCRIPTION
**Pull request by luluRagdoll**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by luluRagdoll** [comment]
This is similar to what we have done before. We are accepting one more enum type in the reserved resource type. 
Previous PR link: https://github.com/Azure/azure-rest-api-specs/pull/3690 
I have validated the Yaml and update the python version. 
Please feel free to let me know if there is anything else.

**Comment by luluRagdoll** [comment]
@sergey-shandar  Looks like I am getting this error: 
  ```
Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4289/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4289)
   Including configuration file 'file:///tmp/tmpai3z3hi8/rest/specification/reservations/resource-manager/readme.go.md'
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.119->2.1.119)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
Processing batch task - {"tag":"package-2018-06"} .
   Including configuration file 'file:///tmp/tmpai3z3hi8/rest/specification/reservations/resource-manager/readme.go.md'
FATAL: Sy**stem.InvalidOperationException: codegen for preview swagger Microsoft.Capacity/preview/2018-06-01/reservations.json must be under a preview subdirectory**
```

**Comment by sergey-shandar** [comment]
@luluRagdoll I've restarted the Go SDK build.
@juhee0202 could you review the PR?

**Review by sergey-shandar — APPROVED** [review]

**Comment by luluRagdoll** [comment]
@sergey-shandar Looks like the Go is still failing. The error msg indicates I am not putting the preview under a preview subdirectory...But it is under preview director. Just wondering is that a valid check in the automation script?

**Comment by sergey-shandar** [comment]
Thank you @jhendrixMSFT.

**Review by juhee0202 — APPROVED** [review]

**Comment by veronicagg** [comment]
license/cla not running properly right now, but ran before and reported green, so merging PR.

**Pull request merged**
