### PR TITLE
[Linked to PR# 1045] Adding support for encryption key type

### PR DESCRIPTION
**Pull request by HimanshuChhabra**
…ices for table and queue)

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by erich-wang** [comment]
@HimanshuChhabra, could you let us know why do you add **Do Not Merge** in title?

**Comment by HimanshuChhabra** [comment]
> @HimanshuChhabra, could you let us know why do you add **Do Not Merge** in title?

@erich-wang the server side is currently deploying across regions and thus we want to pause the merge for now.

**Comment by HimanshuChhabra** [comment]
> Can one of the admins verify this patch?
This PR is approved in private repo PR# 1045

**Comment by HimanshuChhabra** [comment]
@erich-wang This PR was already approved in private repo# 1045

**Comment by anthony-c-martin** [comment]
> @erich-wang This PR was already approved in private repo# 1045

Signed off for ARM as this has already been signed off in private

**Comment by erich-wang** [comment]
@HimanshuChhabra, please remove **Do Not Merge** from title when this is PR is ready for merge.

**Comment by HimanshuChhabra** [comment]
> @HimanshuChhabra, please remove **Do Not Merge** from title when this is PR is ready for merge.

Yes, I will. Thank you

**Comment by HimanshuChhabra** [comment]
@erich-wang Kindly Initiate Merge for this PR. Thank you.

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
