### PR TITLE
Azure Red Hat OpenShift 2022-04-01 API

### PR DESCRIPTION
**Pull request by mbarnes**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mbarnes** [comment]
I could use some guidance from a reviewer on the failures here, please.

- **[SDK azure-sdk-for-python](https://github.com/Azure/azure-rest-api-specs/pull/18350/checks?check_run_id=5652541843)** : This appears to be an issue with the CI pipeline itself, correct?
 ```
 ModuleNotFoundError: No module named 'markupsafe'
 ```

- [**API Readiness Check**](https://github.com/Azure/azure-rest-api-specs/pull/18350/checks?check_run_id=5652518253) : This appears to be a new requirement since the [last version of the API in 2020](https://github.com/Azure/azure-rest-api-specs/pull/8795).
 Is there documentation for what exactly needs to be deployed for this check to pass?

- [**Swagger SDK Breaking Change Tracking**](https://github.com/Azure/azure-rest-api-specs/pull/18350/checks?check_run_id=5652518614) : In the diff output below I don't understand what "approved" and "base" are referring to, and can't find any supporting documentation.

**azure-sdk-for-go-track2 - armredhatopenshift - 0.3.0**
```
Diff with approved:
+	Const `VMSizeStandardD2SV3` has been removed
+	Const `VMSizeStandardD4SV3` has been removed
+	Const `VMSizeStandardD8SV3` has been removed
+	Function `CloudErrorBody.MarshalJSON` has been removed
+	Function `PossibleVMSizeValues` has been removed
+	Function `VMSize.ToPtr` has been removed
+	Struct `CloudErrorBody` has been removed
+	Struct `CloudError` has been removed
+	Type of `MasterProfile.VMSize` has been changed from `*VMSize` to `*string`
+	Type of `WorkerProfile.VMSize` has been changed from `*VMSize` to `*string`
Diff with base:
+	Const `VMSizeStandardD2SV3` has been removed
+	Const `VMSizeStandardD4SV3` has been removed
+	Const `VMSizeStandardD8SV3` has been removed
	Function `CloudErrorBody.MarshalJSON` has been removed
+	Function `PossibleVMSizeValues` has been removed
+	Function `VMSize.ToPtr` has been removed
	Struct `CloudErrorBody` has been removed
	Struct `CloudError` has been removed
+	Type of `MasterProfile.VMSize` has been changed from `*VMSize` to `*string`
+	Type of `WorkerProfile.VMSize` has been changed from `*VMSize` to `*string`
```

(cc: @bennerv)

**Comment by pilor** [comment]
Please ensure you follow this process when adding a new API version to make the diff against the old version easier to review:  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version

**Comment by mbarnes** [comment]
Thanks @pilor.  OpenAPI Hub was new to us, but we'll remember for the next iteration.

@leni-msft, per the [review workflow](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review), we'd like to proceed with the breaking changes to the Go SDK since it has no known consumers.  Generally customers interact with the service through the `az` Python CLI tool.

Still an open question around the **API Readiness Check** failure (see my previous comment).  Looking for clarification about what exactly needs deployed, as this seems like a "chicken and egg" problem.

**Comment by leni-msft** [comment]
@ArcturusZhang @tadelesh to help check Go SDK breaking changes.

@mbarnes After the PR is reviewed, we'll approve this PR. Then you can deploy your service. After it's deployed, we'll merge the PR. So the process is: review & approve swagger PR (not merge) -> deploy service -> merge PR

**Comment by mbarnes** [comment]
@leni-msft Thanks for the API Readiness clarification!  Makes sense now.

So that just leaves the **azure-sdk-for-python** failure.  Is this a known issue with `automation_init.sh`, and is it blocking approval?
```
cmderr	[automation_init.sh]   ModuleNotFoundError: No module named 'markupsafe'
```

**Comment by leni-msft** [comment]
@msyyc to help check the python sdk generation fail;ure

**Review by ross-bryan — APPROVED** [review]
LGTM!

**Comment by msyyc** [comment]
will fix python soon

**Comment by 25region** [comment]
@leni-msft - getting a similar issue to https://githubhot.com/repo/Azure/autorest/issues/4390 with 
```
ERROR: Schema violation: Additional properties not allowed: x-ms-identifiers
    - file:///swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json:692:8 ($.definitions.OperationList.properties.value)
```
The pass-thru option doesn't seem to work. See the Autorest params below:
```  
...  
    --go \
    --use=@microsoft.azure/autorest.go@~2.1.187 \
    --use=@microsoft.azure/autorest.modeler@~2.3.47 \
    --version=V2 \
    --license-header=MICROSOFT_APACHE_NO_VERSION \
    --namespace=redhatopenshift \
    --pass-thru:schema-validator-swagger \
...
```

**Comment by leni-msft** [comment]
@25region you can refer to the `SDK azure-sdk-for-go` or `SDK azure-sdk-for-go-track2` log in this PR. It contains the autorest params that works. But how is this issue related with this PR?

**Comment by msyyc** [comment]
Python has been fixed.

**Review by leniatgh — APPROVED** [review]

**Comment by mbarnes** [comment]
Bump, to see if this will remove **no-recent-activity**.

**Comment by mbarnes** [comment]
@leni-msft Can you please remove the **no-recent-activity** on this PR?
We're still working on deploying the 2022-04-01 API.

**Comment by 25region** [comment]
@leni-msft can we rerun the readiness check? The new RP version is deployed. We should be able to move on with this merge now.

**Review by ross-bryan — APPROVED** [review]

**Review by leniatgh — APPROVED** [review]

**Pull request merged**
