### PR TITLE
[Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-10-01

### PR DESCRIPTION
**Pull request by zachraMSFT**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/zachraMSFT/azure-rest-api-specs/dev-consumption-Microsoft.Consumption-2019-10-01-swaggermismatch...master/).

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by zachraMSFT** [comment]
I manually validated that all changes flagged as breaking change documentation to match actual established behavior of the api and represent documentation errors, not changes in the underlying API.

**Comment by zachraMSFT** [comment]
@PhoenixHe-msft As I mentioned in my original comment, all of these changes represent updating swagger to match current API behavior, so it represents fixing KPIs showing in S360 and documentation. This means that the full review process does not apply, and we want to make these changes quickly.

**Comment by zachraMSFT** [comment]
What steps do we need to take to make sure this review happens in a timely manner?

**Comment by PhoenixHe-msft** [comment]
@zachraMSFT In this case you still need to go through the process. We will have some other options for you during the review process but first you need to start the breaking change review.

**Comment by zachraMSFT** [comment]
@PhoenixHe-msft Ok, we can start looking into it.

But as I look at what's being flagged, none of them should actually be breaking. We don't generate an SDK for this, and all of the changes are only adding fields to the response. Requests are unchanged, and only one existing response property is changing at all (changing type from object to list). The errors about discriminator and properties being removed should be false positives unless there's an issue with the change. A discriminator was added to an object that did not have one, but that's just adding a "kind":"Legacy" property in what user sees. Similar with the allOf changes, it's just reorganizing and cleaning up the object organization, what is actually being generated for the user isn't changed.

**Comment by PhoenixHe-msft** [comment]
@zachraMSFT I know you have comments on your changes but please clarify it in the breaking change review meeting. Thanks.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by zachraMSFT** [comment]
@PhoenixHe-msft Can you merge this now?

**Pull request merged**
