### PR TITLE
Small correction to list handling

### PR DESCRIPTION
**Pull request by leonardbf**
Still preview - breaking changes not an issue

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5536 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5536/commits/d18bcd7e293530daf8af0760c3609b8bd8796ebb

**Comment by leonardbf** [comment]
This is just a small change and a quick turn around would be really appreciated. Many thanks.

**Comment by dsgouda** [comment]
@leonardbf could you clean up the commit history here (git rebase -i)

**Comment by leonardbf** [comment]
> @leonardbf could you clean up the commit history here (git rebase -i)

Thanks for a quick response. Can you give me the full steps for this? Do you mean simply clone my master branch, perform git rebase -i then push back to master? Note this commit history is from earlier commits that have already been merged. This last change was a single commit - does that make a difference? If not then I could perform this squash on my next commit. I was hoping this one could be merged quickly so the SDKs can be generated as soon as possible.

**Comment by dsgouda** [comment]
@leonardbf pull from latest Azure master to your master, if this doesn't work you can simply clone Azure master and copy over your changes in a new branch (hacky and you can skip if it's too much work)

**Comment by leonardbf** [comment]
> @leonardbf pull from latest Azure master to your master, if this doesn't work you can simply clone Azure master and copy over your changes in a new branch (hacky and you can skip if it's too much work)

Hmm, this was actually a clean branch that I pushed from a newly cloned repo. I did it that way because there were merge conflicts. I'm not really sure why this commit history is here.

**Comment by leonardbf** [comment]
@dsgouda hey, I see you tried to contact me on the devex teams channel. I've noticed previously that this is only accessible to me on my SAW machine which is in the office. Teams on my development laptop does not show this channel even when clicking through from the email to my b- account you triggered in Teams (I'm assuming you are on Pacific Time but I'm on UTC in Iceland and won't be in the office for 8 hours or so).

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
