### PR TITLE
Monitor: added tags for Java, created Java readme

### PR DESCRIPTION
**Pull request by iscai-msft**

### CODE REVIEW

**Review by tjprescott — CHANGES_REQUESTED** [review]
Failing CI and has merge conflicts.

**Comment by yungezz** [comment]
hi @iscai-msft  could  you pls resolve conflict so that we can go ahead for this PR?

**Comment by yungezz** [comment]
@iscai-msft is it ok to close the PR for now since you're not ready for merge, and the PR is over several months, there're  conflicts with latest code base already. Pls create new PR when you're ready for review and merge.

**Comment by yungezz** [comment]
close it for now since no response either from github or email.

**Pull request closed without merging**
