### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-04-02-preview

### PR DESCRIPTION
**Pull request by moreOver0**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by moreOver0** [comment]
@ArcturusZhang Could you help look into the error in the check "SDK azure-sdk-for-go". The enum "ResourceIdentityType" in swagger looks good to me. And I cannot repro this error locally. When I run `autorest readme.md --go` locally, it works well.

**Comment by moreOver0** [comment]
Dear review board, I would like to clarify the failures in the CI checks.

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/18900/checks?check_run_id=6285253791), I suppose this should be a known issue. According to the error log, the reason for the error is the permission problem when the pipeline is executed, which has nothing to do with this PR.

For [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/18900/checks?check_run_id=6285233931), The [2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/f66907c4e6fb10e826f318a9cd747bb275ca3f9f/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2019-10-27-preview/openShiftManagedClusters.json) mentioned in the error log is a deprecated swagger file, Currently, only managedCluster is supported by us, the rest such as containerService, openShiftManagedClusters, location, etc. are all deprecated. There was a similar issue in the previous [02-01 swagger PR](https://github.com/Azure/azure-rest-api-specs/pull/18324#issuecomment-1073500751).


For [Swagger SDK Breaking Change Tracking](https://github.com/Azure/azure-rest-api-specs/pull/18900/checks?check_run_id=6285234281).
The JS SDK check throws an error which is caused by last preview version [2022-03-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18633/checks?check_run_id=5984535318). This error has been clarified in [PR](https://github.com/Azure/azure-rest-api-specs/pull/18633#issuecomment-1094821697). I think it appears again because the [JS SDK release](https://github.com/Azure/sdk-release-request/issues/2705) hasn't finished. @qiaozha Is this right?

**Comment by moreOver0** [comment]
@jianyexi Can we bypass the azure-powershell check? We don't mean to update the powershell SDK.

**Comment by jianyexi** [comment]
> @jianyexi Can we bypass the azure-powershell check? We don't mean to update the powershell SDK.

I approved the avocado error , the others need SDK owner to confirm @ArcturusZhang

**Review by ArcturusZhang — APPROVED** [review]
Approve for the failure in azure-sdk-for-go, it could pass on local, but the pipeline has some issue which results in a failure

**Comment by zizw123** [comment]
>         }

Need pagination for list API

"x-ms-pageable"

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-04-02-preview/managedClusters.json:2608 in f66907c. [](commit_id = f66907c4e6fb10e826f318a9cd747bb275ca3f9f, deletion_comment = False)

**Comment by zizw123** [comment]
>       }

Same here, need pagination

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-04-02-preview/managedClusters.json:2651 in f66907c. [](commit_id = f66907c4e6fb10e826f318a9cd747bb275ca3f9f, deletion_comment = False)

**Comment by zizw123** [comment]
>           },

Is this put sync or async? Need "x-ms-long-running-operation" for aysnc operation. See: [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#creatingupdating-using-put) suggest to sue 200/201 + provisioning state for async call.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-04-02-preview/managedClusters.json:2735 in f66907c. [](commit_id = f66907c4e6fb10e826f318a9cd747bb275ca3f9f, deletion_comment = False)

**Comment by zizw123** [comment]
>         "enableCustomCATrust": {

Consider if this could be convert to enum, see "Replace boolean/switch properties with better enum" in [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-04-02-preview/managedClusters.json:3287 in f66907c. [](commit_id = f66907c4e6fb10e826f318a9cd747bb275ca3f9f, deletion_comment = False)

**Comment by zizw123** [comment]
>         "provisioningState": {

Use enum for this

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-04-02-preview/managedClusters.json:6553 in f66907c. [](commit_id = f66907c4e6fb10e826f318a9cd747bb275ca3f9f, deletion_comment = False)

**Comment by moreOver0** [comment]
@zizw123 Thanks for your comments! 

To summarize the comments:

We got 4 comments about Trusted access role @karataliu @matthchr:
* Pagination when list trustedAccessRoles;
* Pagination when list trustedAccessRoleBindings;
@karataliu @matthchr What do you think about the pagination? Do we have limit on the number of roles/roleBindings?
* Make PUT trustedAccessRoleBinding follow async operation design if it is async. 
As for this, I think this is a sync operation. @karataliu Right?
* Make provisioningState enum;
I found several string-type provisioningState in existing swagger. So this one follows our previous style. I prefer not to change.

We got 1 comment about enableCustomCATrust:
* Make enableCustomCATrust enum instead of boolean;
I prefer not to change because we have a lot of existing boolean-type "enableXXX". It's consistent to use boolean.

**Comment by matthchr** [comment]
> Pagination when list trustedAccessRoleBindings;
@karataliu @matthchr What do you think about the pagination? Do we have limit on the number of roles/roleBindings?

I agree we should _probably_ support pagination on this API, especially if there's any large number of these things (large is >10 or so?). I _believe_ that we can also define it as pageable in the API but then in the implementation just never return a `nextLink` for now. That eases implementation for now but gives us an out in the API as these things inevitably grow in number, we could just start returning pages and users existing code should continue working (because the SDKs, etc already all said this was pageable).

> I found several string-type provisioningState in existing swagger. So this one follows our previous style. I prefer not to change.

It would be nice to have a defined set of `provisioningState` states, so that users know what the set of possible states is... with that said, in reality we can sometimes add states which is technically allowed to `modelAsString` enums. I'd be ok seeing this as an enum but we would need to document on it that we reserve the right to return values that aren't in the list in the future as aka.ms/bcforapi table1 (`Changes not requiring a new api-version of the service`) says.

**Comment by moreOver0** [comment]
All comments addressed except the "enableCustomCATrust".

* Pagination when list trustedAccessRoles;
[Added pagination.]

* Pagination when list trustedAccessRoleBindings;
[Added pagination.]

* Make PUT trustedAccessRoleBinding follow async operation design if it is async. 
[Good catch! This is an async operation. We have made this return 200 with provisioningState.]

* Make provisioningState enum;
[Done.]

* Make enableCustomCATrust enum instead of boolean;
[Keep this as boolean to keep consistent to other similar "enableXXX".]



Thank @karataliu for quick reponse!
@matthchr @zizw123 Let take a final look! Please signoff if no more problems~

**Comment by moreOver0** [comment]
The PoliCheck failed due to term [whitelist]. The term [whitelist] has nothing to do with this PR.

@jianyexi We just ignore this failure?

**Comment by jianyexi** [comment]
> The PoliCheck failed due to term [whitelist]. The term [whitelist] has nothing to do with this PR.
> 
> @jianyexi We just ignore this failure?

Yes

**Comment by ArcturusZhang** [comment]
[This PR](https://github.com/Azure/azure-rest-api-specs/pull/18789) is the reason of the failure in azure-sdk-for-go.
I did an experiment locally to revert the changes made in that PR, and every generation could successfully generate code.

**Review by dolauli — APPROVED** [review]

**Review by jianyexi — APPROVED** [review]

**Pull request merged**
