### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to add version stable/2018-03-01

### PR DESCRIPTION
**Pull request by sivanguetta**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/sivanguetta/azure-rest-api-specs/dev-monitor-Microsoft.Insights-2018-03-01-fix-documentation...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by NullMDR** [comment]
@sivanguetta Ready for merge?

**Review by PhoenixHe-NV — APPROVED** [review]

**Review by harelbr — APPROVED** [review]

**Comment by sivanguetta** [comment]
> @sivanguetta Please try to fix or suppress the model validation failure

@NullMDR 
Model validation fails due to is a known issue with OAV tool (Azure/oav#468)
The PR is ready for marge from my side.

**Comment by NullMDR** [comment]
@akning-ms Please help to merge this PR as it's known issue in model validation.

**Comment by sivanguetta** [comment]
@akning-ms, can you please help to merge the PR? the merging is blocked due to a known issue in model validation.

**Comment by sivanguetta** [comment]
Hi  @akning-ms  and @raych1,
Can you please help me to copmlete this PR?

**Comment by raych1** [comment]
@sivanguetta , please fix this type of error `READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST` in model validation check. You could refer [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/Semantic-and-Model-Violations-Reference.md#READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST) for the fix.

**Comment by sivanguetta** [comment]
Hi @raych1
The PrettierCheck is failing.
I ran the command:
npm run prettier -- --write "specification/monitor/**/*.json" and push the fixes but the check is still failing.
Any idea what is wrong?

**Comment by raych1** [comment]
@NullMDR , please help with prettiercheck failure.

**Comment by NullMDR** [comment]
@sivanguetta Please rebase from latest master and try again

**Comment by NullMDR** [comment]
@sivanguetta Is this PR ready from your side?

**Comment by sivanguetta** [comment]
@NullMDR yes, the PR is ready from my side.
I tried to investigate why the 'automation-sdk' checks fails. But when I click on 'View more details on Azure Pipelines', I'm getting "build not found" error. Any idea why?

**Comment by NullMDR** [comment]
@sivanguetta Azure pipeline running result will expire to save space. Anyway this PR LGTM.

**Pull request merged**
