### PR TITLE
Update description for grace period and remove property from Automati…

### PR DESCRIPTION
**Pull request by hapandar**
…c repairs policy

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by anthony-c-martin — APPROVED** [review]
Approving - this feature already requires whitelisting, so it's essentially in private preview and won't be a generally breaking change.

**Review by hyonholee — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Please take a look at the Net SDK CI error and fix it.

**Comment by hapandar** [comment]
Hi @fengzhou-msft , 

So the failures occurred due to a test failure looking at the logs: 

[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>VMScaleSetTests/VMScaleSetScenarioTests.cs(300,29): error CS0117: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>VMScaleSetTests/VMScaleSetScenarioTests.cs(317,77): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>VMScaleSetTests/VMScaleSetTestsBase.cs(559,112): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>VMScaleSetTests/VMScaleSetTestsBase.cs(560,67): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (Build target(s)) -- FAILED.
[Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild]      3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (default targets) -- FAILED.

The test update is in this SDK PR which needs approval: https://github.com/Azure/azure-sdk-for-net/pull/9090/files

**Comment by hapandar** [comment]
Hi Feng,

So I have SDK PR open which would fix the test that’s causing the SDK error.

This is the error:

2019-12-10T00:01:12.032Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetScenarioTests.cs(300,29): error CS0117: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.037Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetScenarioTests.cs(317,77): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.038Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetTestsBase.cs(559,112): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.039Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetTestsBase.cs(560,67): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.042Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (Build target(s)) -- FAILED.
2019-12-10T00:01:12.043Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (default targets) -- FAILED.

This is the PR to address this error by modifying the test which is failing: ‘https://github.com/Azure/azure-sdk-for-net/pull/9090/files

Should I checkin the SDK PR first and then this PR?

Thanks,
Harini Pandari

**Comment by hapandar** [comment]
Hi Feng,

So apparently SDK test is not required to check-in swagger changes. The SDK test fix PR is already in progress.
Could you approve this swagger PR if you don’t see any other issues.

Since this is a chicken and an egg problem. This PR introduces a breaking change and therefore causes test to fail. However the fix is in SDK PR which can only be checked in if this PR gets merged to master.

Thanks,
Harini Pandari

From: Harini Pandari
Sent: Thursday, December 12, 2019 10:43 AM
To: 'Azure/azure-rest-api-specs' <reply@reply.github.com>; Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Azure/azure-rest-api-specs] Update description for grace period and remove property from Automati… (#7928)

Hi Feng,

So I have SDK PR open which would fix the test that’s causing the SDK error.

This is the error:

2019-12-10T00:01:12.032Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetScenarioTests.cs(300,29): error CS0117: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.037Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetScenarioTests.cs(317,77): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.038Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetTestsBase.cs(559,112): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.039Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>VMScaleSetTests/VMScaleSetTestsBase.cs(560,67): error CS1061: 'AutomaticRepairsPolicy' does not contain a definition for 'MaxInstanceRepairsPercent' and no accessible extension method 'MaxInstanceRepairsPercent' accepting a first argument of type 'AutomaticRepairsPolicy' could be found (are you missing a using directive or an assembly reference?) [/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj]
2019-12-10T00:01:12.042Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (Build target(s)) -- FAILED.
2019-12-10T00:01:12.043Z: [Azure/azure-sdk-for-net][Microsoft.Azure.Management.Compute][MSBuild] 3>Done Building Project "/z/work/azure-sdk-for-net/sdk/compute/Microsoft.Azure.Management.Compute/tests/Microsoft.Azure.Management.Compute.Tests.csproj" (default targets) -- FAILED.

This is the PR to address this error by modifying the test which is failing: ‘https://github.com/Azure/azure-sdk-for-net/pull/9090/files

Should I checkin the SDK PR first and then this PR?

Thanks,
Harini Pandari

**Comment by fengzhou-msft** [comment]
The [PR](https://github.com/Azure/azure-sdk-for-net/pull/9090)  to fix Net SDK CI error has been submitted.

**Pull request merged**
