### PR TITLE
[Hub Generated] Review request for Microsoft.Logic to add version stable/2019-05-01

### PR DESCRIPTION
**Pull request by rarayudu**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/rarayudu/azure-rest-api-specs/rarayudu-Microsoft.Logic-2019-05-01...master/).

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
Hi @rarayudu, can we know what is the purpose to add new property? as this is require a new API version base on below reason from Breaking change review board:
Adding an optional return property is not allowed without an api-version change for many reasons:
1. Some programming language deserializers throw if a new property comes across the wire that the client library has no field for it in the structure/class that you’re trying to deserialize into.
2.Some customer use schema validation tools to validate the data being sent across the wire complies with the schema. If the services sends data that doesn’t match the old schema, then the client’s validation fails.
3, If the service sends a new property to an old client, the old client discards the property and the client cannot send the new property back to the service later. Depending on the operation and the meaning of this property, this results in data loss/corruption.
4. A customer can’t look at a service version and know if they can expect the new property or not. For example, if a customer hits V1 of a service in the public cloud, the property may be there but if they hit V1 of the service in a government cloud or on an Azure Stack Hub system, then the property may not be there. So, there is no clear relationship between the service version and the new property which makes documentation invalid and also makes it hard for customers and Azure customer support to help customers diagnose issues.

**Comment by rarayudu** [comment]
Hi @akning-ms,

The purpose of the new property is to allow customers specify the encryption configuration when customer is creating the resource. The new property is mainly to help with CMK (encryption of data at rest using customer managed keys).
If customer didn't provide this property during creation time, they wont get this property during GET. So, we will not give this property for all the existing resource/customers who already created this resource.
Customer who starts providing this on new PUTs only will get this on GET of the resource.
And also, we have this property already available with this API-version for around 10 months and we have customers already using this with the api-version. The purpose of this update to get the swaggers in sync with what we have currently.

Let me know if you have any other questions/need clarifications.

**Comment by pilor** [comment]
If this is just bringing the swagger inline with an API that was released 10 months ago then there isn't anything to review from the ARM side as any changes would be breaking to the consumers.

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
