### PR TITLE
Add RunCommand to 2017-12-01 spec

### PR DESCRIPTION
**Pull request by koralski**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@koralski - We can iterate faster if the PR show us the diff between API versions thus both ARM and SDK reviewers can provide feedback quickly.  Could you follow below steps?

0.  Close this PR
1.	Copy over the `runCommand` file & examples from [2017-03-30](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-03-30) to `2017-12-01` directory.
2.	Commit this change as `git commit -n “Copying 2017-03-30 version of runCommand”
3.	Now make changes that are relevant for new api-version `2017-12-01`. In your case, you will have to simply overwrite the files with the changes that you made (since you would have them saved.)
4.	Now commit the changes “RuncCommand Changes for new API version `2017-12-01`”
5.	Push the changes to your fork (`git push origin <branch-name>`)
6.	Send a PR to `master` from your fork
7.    Assign the new PR to me. you can ping me

This way reviewers can go to second commit and see the update specific to new api-version.

This step is documented in our contribution guidelines (you can find this link is pasted in the checklist of every PR), see https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure

**Review by anuchandy — CHANGES_REQUESTED** [review]
See the last comment about splitting PR into two commits.

**Review by lmazuel — APPROVED** [review]
LGTM

**Comment by koralski** [comment]
@anuchandy I split the changes as requested and I am reusing the same PR.

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
Removing the `review for ARM` label since the api version is already there for a while, confirmed with @johanste.

**Pull request merged**
