### PR TITLE
Fixed error code typo

### PR DESCRIPTION
**Pull request by seanmcc-msft**

### CODE REVIEW

**Review by MushMal — APPROVED** [review]
The change itself is pretty straightforward. My only concern is back compat. I understand this is a preview and it's a very recent version but do you know how many of your customers are using this?

**Comment by seanmcc-msft** [comment]
> The change itself is pretty straightforward. My only concern is back compat. I understand this is a preview and it's a very recent version but do you know how many of your customers are using this?

The has been a long running typo in the storage swagger.  The service has been returning this error code spelled correctly this entire time.

**Comment by seanmcc-msft** [comment]
@tg-msft

**Comment by tg-msft** [comment]
Fixing the swagger to reflect the service is not a breaking change so I'm adding the Approved-BreakingChange label.

**Pull request merged**
