### PR TITLE
Dev deviceprovisioningservices microsoft.devices 2020 09 01 preview

### PR DESCRIPTION
**Pull request by mrohera**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ x ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ x ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ x ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mrohera** [comment]
For the benefit of the reviewers, this preview version was created from the 2020-03-01 (stable) version and the "encryption" CMK properties were added over and above the existing stable API.

**Comment by mrohera** [comment]
@xccc-msft, it appears that the failures in the gates seem unrelated to the changes and I am unsure how to proceed. Can you help with this?

**Comment by xccc-msft** [comment]
> @xccc-msft, it appears that the failures in the gates seem unrelated to the changes and I am unsure how to proceed. Can you help with this?

@NullMDR Can you please help? Thanks.

**Comment by NullMDR** [comment]
The SDK generation failure could be ignored.

**Review by xseeseesee — APPROVED** [review]

**Comment by mrohera** [comment]
Thanks for approving. How can I merge this PR? I am not authorized to merge.

**Comment by mrohera** [comment]
Added sample PTAL.

**Review by rajeevmv — APPROVED** [review]
:shipit:

**Comment by chiragg4u** [comment]
Thank you for keeping the previous version as first commit for easier find the changes.
Looked at the changes from the previous version and it looked fine. Will mark ARMSignoff.

**Comment by mrohera** [comment]
Thanks @chiragg4u for the sign off! What can I do to merge? All the required gate checkins are met.

**Comment by mrohera** [comment]
> The SDK generation failure could be ignored.

Hi @NullMDR , based on your comment above and since I have ARMSignedOff and all the required checks met, can this PR be merged. I cannot merge this since I am not authorized.

**Pull request merged**
