### PR TITLE
Update EventHub.json

### PR DESCRIPTION
**Pull request by basilhariri**
This is a single string update (adding a note in the description of an API), so I am not following the full API update workflow because it doesn't require a new version. Please let me know if I need to do this differently

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by xccc-msft** [comment]
@basilhariri Can you please fix the CI errors? Thanks.

**Comment by basilhariri** [comment]
@xccc-msft my change is just an addition to a description string. The failing CIs are caused by file format errors that are unrelated to this change. It seems to be an issue with the CI environment. Could you fix the CI environment or bypass the CIs since this PR isn't causing these issues?


Here is a sample of the errors that cause the Avocado run to fail:

error: 
code: NOT_AUTOREST_MARKDOWN
message: The `readme.md` is not an AutoRest markdown file.
readMeUrl: >-
  /home/vsts/work/1/s/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-04-01/README.md
level: Error
helpUrl: >-
  http://azure.github.io/autorest/user/literate-file-formats/configuration.html#the-file-format

**Comment by xccc-msft** [comment]
@NullMDR Can you help on this?

**Comment by NullMDR** [comment]
It's another known issue... It's OK to merge. I'll ask Arthur to do it later.

**Review by xseeseesee — APPROVED** [review]

**Comment by basilhariri** [comment]
@xccc-msft could you merge the PR when you get the chance? I am not authorized to merge it :(

**Comment by xccc-msft** [comment]
@basilhariri Even I don't have access to merge by this situation as the merge button keeps disabled when pipelines failed.

**Comment by xccc-msft** [comment]
@v-Ajnava Can you please review?

**Comment by basilhariri** [comment]
@v-Ajnava if you are not available or the right person to merge, can you please assign to someone else?

**Review by v-Ajnava — APPROVED** [review]

**Comment by v-Ajnava** [comment]
@basilhariri, I don't have the rights to merge the PR, @xccc-msft should be able to merge the PR. I have approved the changes.

**Pull request merged**
