### PR TITLE
[Hub Generated] Review request for Microsoft.ResourceGraph to add version preview/2021-06-01-preview

### PR DESCRIPTION
**Pull request by johnthcall**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/johnthcall/azure-rest-api-specs/dev-resourcegraph-Microsoft.ResourceGraph-2021-06-01-preview...master/).
### Latest improvements:
<br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by johnthcall** [comment]
@PhoenixHe-msft Is there anything you need from me on this PR? 
- The ConstraintChanged are matching the constraints that are in the stable version for these same properties. 
- For the RemovedProperty we are bringing forward the same change that was done as part of #13380 when this was considered a warning and not an error.
- DefaultValueChanged is also using the same default value as the latest stable version where it changed.

**Comment by PhoenixHe-msft** [comment]
@johnthcall ARM review is required for new api version

**Comment by chiragg4u** [comment]
Reviewed the version changes from ARM perspective. Marking ARMSignedOff.

**Review by chiragg4u — APPROVED** [review]

**Pull request merged**
