### PR TITLE
Add support for List Operation on global reach connections

### PR DESCRIPTION
**Pull request by dedhar**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [Y ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

### CODE REVIEW

**Comment by dedhar** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/3334271 -- Tracking workitem

**Comment by dedhar** [comment]
Tested the change using local NRP and ARM Client
D:\>armclient get "http://127.0.0.1/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_local526/peerings/AzurePrivatePeering/connections?api-version=2018-02-01"
{
  "value": [
    {
      "name": "circuitConnectionCktAToB",
      "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_local526/peerings/AzurePrivatePeering/connections/circuitConnectionCktAToB",
      "etag": "W/\"e7c5535a-40c8-4c47-810a-2a6f09b6c383\"",
      "properties": {
        "provisioningState": "Succeeded",
        "expressRouteCircuitPeering": {
          "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_local526/peerings/AzurePrivatePeering"
        },
        "peerExpressRouteCircuitPeering": {
          "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_peer526/peerings/AzurePrivatePeering"
        },
        "addressPrefix": "10.0.0.0/29",
        "circuitConnectionStatus": "Connected"
      },
      "type": "Microsoft.Network/expressRouteCircuits/peerings/connections"
    },
    {
      "name": "circuitConnectionCktAToC",
      "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_local526/peerings/AzurePrivatePeering/connections/circuitConnectionCktAToC",
      "etag": "W/\"e7c5535a-40c8-4c47-810a-2a6f09b6c383\"",
      "properties": {
        "provisioningState": "Succeeded",
        "expressRouteCircuitPeering": {
          "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_local526/peerings/AzurePrivatePeering"
        },
        "peerExpressRouteCircuitPeering": {
          "id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/rg1/providers/Microsoft.Network/expressRouteCircuits/circuit_third526/peerings/AzurePrivatePeering"
        },
        "addressPrefix": "20.0.0.0/29",
        "circuitConnectionStatus": "Connected"
      },
      "type": "Microsoft.Network/expressRouteCircuits/peerings/connections"
    }
  ]
}

**Review by syfarogh — COMMENTED** [review]
Thanks for the update

**Review by syfarogh — APPROVED** [review]

**Review by MikhailTryakhov — APPROVED** [review]

**Comment by MikhailTryakhov** [comment]
merge directly to master approved cause we haven't created new branch yet

**Comment by MikhailTryakhov** [comment]
@jianghaolu  please merge

**Pull request merged**
