### PR TITLE
Dev healthcareapis microsoft.healthcare apis 2021 06 01 preview changes

### PR DESCRIPTION
**Pull request by dustinburson**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dustinburson** [comment]
For the Cross Version Breaking changes, these are all differences between original service preview version 2018-08-20-preview and the GA version, 2021-01-01.  This is our first published preview version since we went GA hence the validation errors.  Requesting to ignore these errors for the old preview version since addressing them will cause breaking changes with our GA version.

**Comment by mentat9** [comment]
>         }

This was deprecated in 2021-01-11 version, but no longer? Looks like there are a bunch of these: why is that?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:76 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "Deprovisioned"

What does this state mean? How is it different from Deleted?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:2043 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Created - Put request accepted and an existing resource is being created asynchronously.",

201 is returned when the resource was created (synchronously).

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:801 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:806 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:862 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:909 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/Workspace"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:906 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/Workspace"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:912 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/DicomService"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1173 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "description": "Lists all DICOM Services for the given workspace",

If there's a non-abbreviated version of "dicom" it's worth considering switching to it. If this is a standard name that everyone uses, then it's fine. Generally ARM recommends not using acroynms or abbreviations, except for really well-known ones (e.g. Url).

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:932 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Created - Put request accepted and an existing resource is being created asynchronously.",

201 means the resource has already been created.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1062 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1067 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1126 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Updated - Patch request accepted and an existing resource is updated.",

completed/succeeded

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1121 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/DicomService"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1179 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1334 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Created - Put request accepted and an existing resource is being created asynchronously.",

201 means the resource has already been created.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1329 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Updated - Put request accepted and an existing resource is updated.",

Better to use "completed" or "succeeded" to avoid confusion with async responses.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1323 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Updated - Patch request accepted and an existing resource is updated.",

Better to use "completed" or "succeeded" to avoid confusion with async responses.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1388 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1393 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/IotConnector"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1440 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>               "$ref": "#/definitions/IotConnector"

Delete response should be empty.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1446 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Add the x-ms-long-running-operation: true tag to this operation.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1443 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "description": "Lists all FHIR destinations for the given IoT Connector",

Similar question about possible other names for this that aren't acronyms or abbreviations.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1466 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "acrConfiguration": {

Consider spelling out whatever ACR stands for.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3188 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "modelAsString": false

Generally modelAsString: true is recommended. Any reason this is false?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3150 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "smartProxyEnabled": {

ARM generally recommends against booleans in favor of string enums. Best option is to choose a better property (e.g. proxyType: { "Smart", "Fhir" }). This type of property is easier for customers to understand and use and more extensible. Next best option if you really want a True/False value is to use a string enum, e.g. "smartProxyEnabled": { "True", "False" }. Enums allow adding values later without requiring a new API version.

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3255 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "allowCredentials": {

Consider a string enum, e.g. credentialPolicy: { "Allowed", "Disallowed" }

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3298 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>         "content": {

Empty objects are not recommended. Can this object be spec'd?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3014 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
Nothing was flagged for ARM breaking changes, and I didn't see anything. Looks clean from that perspective, AFAICT.

**Comment by dustinburson** [comment]
>         "content": {

We discussed this at length as a team and decided we want to treat these objects as opaque in the API.  The mapping templates themselves are complex

We received CVP approval for an exemption on PLCY005 and have submitted to Gina Pultorak who is handling our PLR record for Public Preview.

---
In reply to: [879614043](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879614043) [](http://example.com/codeflow?ancestors=879614043,879614043)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3014 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>         "allowCredentials": {

See answer for the enable smart on fhir proxy.  For compatibility with definitions being migrated from the legacy services resource type.

---
In reply to: [879612876](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879612876) [](http://example.com/codeflow?ancestors=879612876,879612876)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3298 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>             "Deprovisioned"

Currently this is a final state our resources can go into before the metadata record is completely removed.

---
In reply to: [879589874](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879589874) [](http://example.com/codeflow?ancestors=879589874,879589874)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:2043 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>         }

It wasn't deprecated.  The 2021-01-11 version had "deprecated": false on a few resources which didn't seem necessary since it is the default.  I can add it back in if desired.

---
In reply to: [879579461](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879579461) [](http://example.com/codeflow?ancestors=879579461,879579461)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:76 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>         "acrConfiguration": {

Mirrors configuration in the legacy service.  It refers to the product, azure container repository.  I will update the description.

---
In reply to: [879609614](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879609614) [](http://example.com/codeflow?ancestors=879609614,879609614)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3188 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>         "acrConfiguration": {

Discussed with team, for our public preview we would like to keep as is for the 3 items pointed out (acr name and 2 bools that should be enum).  I will create work item for us to consider the change as part of our GA.

---
In reply to: [879959129](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879959129) [](http://example.com/codeflow?ancestors=879959129,879609614,879609614)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3188 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>               "$ref": "#/definitions/Workspace"

Removed

---
In reply to: [879594224](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879594224) [](http://example.com/codeflow?ancestors=879594224,879594224)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:906 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>         "description": "Lists all DICOM Services for the given workspace",

This is a standard healthcare term, same for FHIR

---
In reply to: [879598857](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879598857) [](http://example.com/codeflow?ancestors=879598857,879598857)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:932 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>               "$ref": "#/definitions/Workspace"

Removed

---
In reply to: [879596570](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879596570) [](http://example.com/codeflow?ancestors=879596570,879596570)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:912 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>               "$ref": "#/definitions/IotConnector"

Removed

---
In reply to: [879606123](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879606123) [](http://example.com/codeflow?ancestors=879606123,879606123)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1446 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>               "$ref": "#/definitions/IotConnector"

Removed

---
In reply to: [879605983](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879605983) [](http://example.com/codeflow?ancestors=879605983,879605983)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1440 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>           "202": {

The entire operation is marked with "x-ms-long-running-operation": true, (under operationId) do the individual responses need to annonated too?

---
In reply to: [879606225](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879606225) [](http://example.com/codeflow?ancestors=879606225,879606225)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1443 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>             "description": "Updated - Put request accepted and an existing resource is updated.",

Updated

---
In reply to: [879605377](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879605377) [](http://example.com/codeflow?ancestors=879605377,879605377)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1323 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>           "202": {

The operation has it, under the operationId property further up.  Line 1289 in this iteration.

---
In reply to: [879604582](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879604582) [](http://example.com/codeflow?ancestors=879604582,879604582)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1334 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>             "description": "Updated - Patch request accepted and an existing resource is updated.",

Updated

---
In reply to: [879605638](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879605638) [](http://example.com/codeflow?ancestors=879605638,879605638)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1388 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>           "202": {

It is above under the operation id.

---
In reply to: [879593322](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879593322) [](http://example.com/codeflow?ancestors=879593322,879593322)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:806 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
>             "description": "Created - Put request accepted and an existing resource is being created asynchronously.",

Right now we are using 200 for updates and 201 per create.  We use the RP SDK and the logic is dicated here: 
[https://msazure.visualstudio.com/One/_git/AzureUX-ResourceProviderSDK?path=%2Fsrc%2FResourceProvider%2FRouting%2FRouting%2FResourceManagement%2FOperationStatus.cs](https://msazure.visualstudio.com/One/_git/AzureUX-ResourceProviderSDK?path=%2Fsrc%2FResourceProvider%2FRouting%2FRouting%2FResourceManagement%2FOperationStatus.cs)

I was including 202 for future use since introducing a new response code for a new version is a backwards breaking change.  But if the logic in the RP SDK is still sound I can drop it.

---
In reply to: [879592690](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879592690) [](http://example.com/codeflow?ancestors=879592690,879592690)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:801 in f0b1bdb. [](commit_id = f0b1bdb1d4c962a6bec64617863333b86ee958d3, deletion_comment = False)

**Comment by dustinburson** [comment]
>             "description": "Updated - Put request accepted and an existing resource is updated.",

Actually after further review I reverted this change.  200 is returned during an update and 201 is returned during a create currently.  This is due to the RP SDK we use today [https://msazure.visualstudio.com/One/_git/AzureUX-ResourceProviderSDK?path=%2Fsrc%2FResourceProvider%2FRouting%2FRouting%2FResourceManagement%2FOperationStatus.cs](https://msazure.visualstudio.com/One/_git/AzureUX-ResourceProviderSDK?path=%2Fsrc%2FResourceProvider%2FRouting%2FRouting%2FResourceManagement%2FOperationStatus.cs) The 202 are there for future use with out triggering a breaking change if we add them in the future.  I can remove if prefered.

---
In reply to: [880227535](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-880227535) [](http://example.com/codeflow?ancestors=880227535,879605377)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1323 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by dustinburson** [comment]
@mentat9 I addressed or replied to the comments you made.  Please let me know if you have further questions/changes.

**Comment by dustinburson** [comment]
>             "modelAsString": false

Fixed.  It looks like it was that way in the services defintion, I am not sure why

---
In reply to: [879610008](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879610008) [](http://example.com/codeflow?ancestors=879610008,879610008)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:3150 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>           "202": {

Ah, missed it.

---
In reply to: [880229073](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-880229073) [](http://example.com/codeflow?ancestors=880229073,879593322)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:806 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
>             "description": "Updated - Put request accepted and an existing resource is updated.",

Right, I just meant replace the word "accepted" with "completed" or "succeeded" to avoid confusion with sync vs. async response.

---
In reply to: [880296294](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-880296294) [](http://example.com/codeflow?ancestors=880296294,879605377)

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:1323 in 32eea04. [](commit_id = 32eea0431e249ed0fd62feea6b5f0526c10da292, deletion_comment = False)

**Comment by mentat9** [comment]
> > ```
> >     }
> > ```
> 
> It wasn't deprecated. The 2021-01-11 version had "deprecated": false on a few resources which didn't seem necessary since it is the default. I can add it back in if desired.
> 
> In reply to: [879579461](https://github.com/Azure/azure-rest-api-specs/pull/15166#issuecomment-879579461)
> 
> Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2021-06-01-preview/healthcare-apis.json:76 in [32eea04](https://github.com/Azure/azure-rest-api-specs/commit/32eea0431e249ed0fd62feea6b5f0526c10da292). [](commit_id = [32eea04](https://github.com/Azure/azure-rest-api-specs/commit/32eea0431e249ed0fd62feea6b5f0526c10da292), deletion_comment = False)

Ugh. I've been reading too many PRs: no change needed.

**Comment by mentat9** [comment]
Left clarifying comment about my suggestion for description changes that I think still applies, but I'm not holding approval on it. Consider updating the descriptions in a future commit.

**Review by PhoenixHe-NV — APPROVED** [review]

**Pull request merged**
