### PR TITLE
[App Service] Update swagger spec for ANT80

### PR DESCRIPTION
**Pull request by nking-1**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by nschonni — COMMENTED** [review]
Looks like some spelling fixes are being reverted. Maybe they still need to be fixed in the source code

**Comment by Nking92** [comment]
> Looks like some spelling fixes are being reverted. Maybe they still need to be fixed in the source code

Oops, I tried not to copy those over, but it looks like a few got through. Yesterday I combed through the source code to clean up the typos that had been manually fixed in the swagger spec.

**Review by sergey-shandar — CHANGES_REQUESTED** [review]
What's the reason for breaking changes in stable API versions? Usually, we don't allow to do this.

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/486714248

**Comment by Nking92** [comment]
My previous commits removed the 2018-02-01 Certificates files but I have added them back and that seems to have fixed the breaking changes check.

There is one expected breaking change. There is a property called adminSiteName that's being hidden in this update. Per @suwatch - Admin Site Name feature never released. We should exclude that from rest api documentation as we might get more questions / affects other features.

**Review by naveedaz — APPROVED** [review]

**Comment by Nking92** [comment]
@sergey-shandar Is there an ARM team member added to review this PR? This PR has gone dark for about a week now.

**Comment by sergey-shandar** [comment]
@Nking92 because it's potential breaking changes, ARM should review it before I merge. @ravbhatnagar

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
