### PR TITLE
Break apart policy swagger specs

### PR DESCRIPTION
**Pull request by pilor**
Breaking apart the policy swagger specs so that resourceTypes with different api-versions can easily be included in the same generated code.  This change also introduces examples for policyAssignment operations.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ x] The title of the PR is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ x] My spec meets the review criteria:
  - [ x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by olydis** [comment]
@pilor this PR does more than just move stuff. Was this intended? At first glance, there seem to be some significant changes mixed into moving stuff from A to B - that's very complicated to review reliably. Could you please split these changes into multiple (appropriately named) PRs?

**Comment by pilor** [comment]
@olydis, its only splitting and resolving a few validation warnings/errors (readOnly name property and new example files).  The diff is more complex than it could be because I let git choose what file to base the "mv" command off of instead of explicitly specifying it.  I'll push a new change that should make it more clear

**Comment by pilor** [comment]
@olydis, nevermind this isn't actually fixable.  Git doesn't care whether you use mv or manually rename, the diffs are based off of similarity between files.  The diffs you are seeing in here are diffing between the 2016-12-01 policy.json and the new 2017-06-01-preview split out policyAssignments.json (and vice versa).  If you looked at the diffs in the same api-version folder they would be much cleaner

**Comment by olydis** [comment]
Thanks, that indeed makes reviewing easier!
But what about `notScopes` and `metadata` of `PolicyAssignmentProperties` and `PolicySku`? These I see removed in the `2016-12-01` Swagger and don't see any replacement.

**Review by olydis — APPROVED** [review]

**Pull request merged**
