### PR TITLE
microsoft.storagecache 2022-05-01

### PR DESCRIPTION
**Pull request by paujohn**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month. **May 2022**
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. **May 2022**
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by paujohn** [comment]
Hi @tadelesh 

**We are ready for review.**

Listed below are the explanations of why the above errors persist and why they can safely be ignored:

### API readiness check 
Failed since the service deployment has not started rolling out yet. Our team will start service deployment on May 16th and it will take 2 weeks to complete. We are just getting approval so that the new api-version can be merged once we are completely ready.

### SDK azure-sdk-for-net
A question about the same error message was asked on Azure API and Tools Support in the General channel and Ray Chen said that we ignore these failures
image

### Swagger ModelValidation
Failed since the required property primingManifestUrl is not present in GET or PUT responses. This is an issue with the validation checker since primingManifestUrl is labeled as both **required and x-ms-secret**. According to 
the [x-ms-secret autorest specs](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret), _"When a property is modeled as both "required" and "x-ms-secret": true, which means that this property must not exist in the response but has to be present in request."_ which is what we do in the examples.

"primingManifestUrl": {  
&emsp;"description": "The URL for the priming manifest file to download. This file must be readable from the HPC Cache. When the file is in Azure blob storage the URL should include a Shared Access Signature (SAS) granting read permissions on the blob.", 
&emsp;"$ref": "#/definitions/URLString",
&emsp;"x-ms-mutability": [
&emsp;&emsp;"create"
&emsp;],
&emsp;**"x-ms-secret": true**
},
"required": [
&emsp;"primingJobName",
&emsp;**"primingManifestUrl"**
],

### Swagger SDK Breaking Change Tracking 
The Swagger SDK Breaking Change Tracking failure is only for API version 2020-03-01, which I have not edited in this PR.

**Comment by raosuhas** [comment]
>         },

include return header definitions. For a POST it must include location header

---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1317 in 0d6131d. [](commit_id = 0d6131d4890e8390c405ae0f67c3237849404726, deletion_comment = False)

**Comment by raosuhas** [comment]
>       "post": {

this is incorrect. You cannot do a POST on a resource like this. POSTs are actions that can be done on resources. Please remodel this api and submit. 

---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1330 in 0d6131d. [](commit_id = 0d6131d4890e8390c405ae0f67c3237849404726, deletion_comment = False)

**Comment by raosuhas** [comment]
>         "operationId": "PrimingJobs_Resume{PrimingJobId}"

This PR is not ready for review. Please rework to correctly follow ARM semantics and re-submit. 

---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1482 in 0d6131d. [](commit_id = 0d6131d4890e8390c405ae0f67c3237849404726, deletion_comment = False)

**Review by raosuhas — CHANGES_REQUESTED** [review]
:clock1:

**Comment by paujohn** [comment]
> > ```
> >   "post": {
> > ```
> 
> this is incorrect. You cannot do a POST on a resource like this. POSTs are actions that can be done on resources. Please remodel this api and submit.
> 
> Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1330 in [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726). [](commit_id = [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726), deletion_comment = False)

@raosuhas Per your suggestion, we reworked the api to clarify that startPrimingJob, stopPrimingJob, pausePrimingJob, resumePrimingJob are all actions on the cache resource type. The priming jobs are _an attribute/field in the cache object_.

Once the customer initiates a primingJob, the job will run to completion and get removed by itself without any further interaction from the customer. This is why primingJob is suited better as a POST action rather than a full blow sub-resource of the cache resource type.

startPrimingJob is a valid action on the cache resource that prefills data into the cache. As for stopPrimingJob, its just another  action on the cache resource type that stops the prefilling of data into the cache. These actions are similar to other valid actions such as [_"e.g. getting the thumbnail of an image or rebooting a VM"_](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#performing-an-action)

**Comment by paujohn** [comment]
> > ```
> >     },
> > ```
> 
> include return header definitions. For a POST it must include location header
> 
> Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1317 in [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726). [](commit_id = [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726), deletion_comment = False)

@raosuhas  Thanks for pointing this out.

Fixed, by adding location & Azure-AsyncOperation headers to the response for POST action api requests we created for this api-release.

**Comment by paujohn** [comment]
> > ```
> >     "operationId": "PrimingJobs_Resume{PrimingJobId}"
> > ```
> 
> This PR is not ready for review. Please rework to correctly follow ARM semantics and re-submit.
> 
> Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1482 in [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726). [](commit_id = [0d6131d](https://github.com/Azure/azure-rest-api-specs/commit/0d6131d4890e8390c405ae0f67c3237849404726), deletion_comment = False)

@raosuhas We are ready for an ARM re-review. Thanks.

**Comment by zizw123** [comment]
>         "operationId": "StartPrimingJob"

nit: Looks like other operationId in this swagger is in capital snake case

---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1336 in 9f98f3a. [](commit_id = 9f98f3a8cbcfdc322dad016a9c709e82bddc639e, deletion_comment = False)

**Comment by zizw123** [comment]
>           },

Is the intend of the post to actually delete the resource? Should it be a resource API with DELETE or proxy API that uses POST. Same question goes to the startingJob


---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1382 in 9f98f3a. [](commit_id = 9f98f3a8cbcfdc322dad016a9c709e82bddc639e, deletion_comment = False)

**Comment by zizw123** [comment]
>     "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.StorageCache/caches/{cacheName}/startPrimingJob": {

Can you explain the use case a little here, are you going to support any API to get the PrimingJob?

---
Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1272 in 354311e. [](commit_id = 354311e6f4f9be6dca0f05ee0b8f88e49ee9bffb, deletion_comment = False)

**Comment by paujohn** [comment]
> > ```
> >       },
> > ```
> 
> Is the intend of the post to actually delete the resource? Should it be a resource API with DELETE or proxy API that uses POST. Same question goes to the startingJob
> 
> Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1382 in [9f98f3a](https://github.com/Azure/azure-rest-api-specs/commit/9f98f3a8cbcfdc322dad016a9c709e82bddc639e). [](commit_id = [9f98f3a](https://github.com/Azure/azure-rest-api-specs/commit/9f98f3a8cbcfdc322dad016a9c709e82bddc639e), deletion_comment = False)

@zizw123  The POST stopPrimingJob will prematurely remove the primingJob. Otherwise, by design, the job will run to completion and get removed by itself without any further interaction from the customer.

So generally, we see the primingJob more of a property of a cache than a full blown first-class resource. This is why primingJob is suited better as a POST action rather than a full blow sub-resource of the cache resource type.

**Comment by paujohn** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.StorageCache/caches/{cacheName}/startPrimingJob": {
> > ```
> 
> Can you explain the use case a little here, are you going to support any API to get the PrimingJob?
> 
> Refers to: specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2022-05-01/storagecache.json:1272 in [354311e](https://github.com/Azure/azure-rest-api-specs/commit/354311e6f4f9be6dca0f05ee0b8f88e49ee9bffb). [](commit_id = [354311e](https://github.com/Azure/azure-rest-api-specs/commit/354311e6f4f9be6dca0f05ee0b8f88e49ee9bffb), deletion_comment = False)

@zizw123 The API to get the Priming Jobs is in the GET Cache (under the "primingJobs" field). Since we see the primingJob as a property of the cache.

**Comment by paujohn** [comment]
Hi @tadelesh 

**We are ready for API review as ARM has signed off on our PR.**

Listed below are the explanations of why the above errors persist and why they can safely be ignored:

### API readiness check 
Failed since the service deployment has not started rolling out yet. Our team will start service deployment on May 16th and it will take 2 weeks to complete. We are just getting approval so that the new api-version can be merged once we are completely ready.

### SDK azure-sdk-for-net/SDK azure-powershell
We are only requesting an auto-generation of Python, Java, Js, Go. All the other language SDKs will be manually generated.

### Swagger ModelValidation
Failed since the required property primingManifestUrl is not present in GET or PUT responses. This is an issue with the validation checker since primingManifestUrl is labeled as both **required and x-ms-secret**. According to 
the [x-ms-secret autorest specs](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-secret), _"When a property is modeled as both "required" and "x-ms-secret": true, which means that this property must not exist in the response but has to be present in request."_ which is what we do in the examples.

"primingManifestUrl": {  
&emsp;"description": "The URL for the priming manifest file to download. This file must be readable from the HPC Cache. When the file is in Azure blob storage the URL should include a Shared Access Signature (SAS) granting read permissions on the blob.", 
&emsp;"$ref": "#/definitions/URLString",
&emsp;"x-ms-mutability": [
&emsp;&emsp;"create"
&emsp;],
&emsp;**"x-ms-secret": true**
},
"required": [
&emsp;"primingJobName",
&emsp;**"primingManifestUrl"**
],

### Swagger SDK Breaking Change Tracking 
The Swagger SDK Breaking Change Tracking failure is only for API version 2020-03-01, which I have not edited in this PR.

**Review by tadelesh — APPROVED** [review]

**Comment by paujohn** [comment]
@tadelesh Please merge this pull request.

We have rolled out the latest api release 2022-05-01 (both the RP and Manifest) have been rolled out to all regions. T

**Comment by paujohn** [comment]
> @raosuhas If there is no more question, could you please unblock the PR.

@raosuhas , @zizw123 has already reviewed and approved the PR. Could you please remove the 'change requested' block that is keeping this PR from getting merged?

**Comment by paujohn** [comment]
@tadelesh Could you now merge the PR now that @raosuhas has unblocked it.

**Comment by raosuhas** [comment]
> @raosuhas If there is no more question, could you please unblock the PR.

@tadelesh  How do I unblock it ? I have updated all the labels

**Comment by tadelesh** [comment]
> > @raosuhas If there is no more question, could you please unblock the PR.
> 
> @tadelesh How do I unblock it ? I have updated all the labels

@raosuhas You need to approve this PR.

**Review by raosuhas — APPROVED** [review]
:shipit:

**Comment by raosuhas** [comment]
> :shipit:

adding an approval to unblock based on zizhous review

**Comment by paujohn** [comment]
@zizw123 Can you please merge this PR, now that it has been approved by @raosuhas

**Pull request merged**
