### PR TITLE
Vulnerability Assessment APIs

### PR DESCRIPTION
**Pull request by yaakoviyun**
Merging Vulnerability Assessment APIs from private branch

### CODE REVIEW

**Comment by jaredmoo** [comment]
If/when this is publically available in production, please add to readme.md. Please add to all package-composite-v* and the appropriate package-pure-*

**Review by jaredmoo — APPROVED** [review]
Travis validation looks good

**Comment by jhendrixMSFT** [comment]
@jaredmoo Regarding your comment about adding to readme.md, who's tracking this?

**Comment by jaredmoo** [comment]
@yaakoviyun should take care of that :)

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
