### PR TITLE
[Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01

### PR DESCRIPTION
**Pull request by aditink**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/aditink/azure-rest-api-specs/dev-reservations-Microsoft.Capacity-2019-04-01...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
As identified in the automated checks there are breaking changes, please review [Policy for Breaking Changes](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes) and request an approval .

**Comment by adrianhall** [comment]
Exception for breaking change requirement granted - extensible enum with additional values added - allowed with no version change (cc: @JeffreyRichterMSFT)

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
@akning-ms The ModelValidation error doesn't seem to be caused by the changes in this PR. Can you take a look and merge if the change looks good to you?

**Comment by akning-ms** [comment]
@raych1 to check ModelValidation failure

**Comment by raych1** [comment]
> @raych1 to check ModelValidation failure

There're some legacy errors for the example files. It needs to be fixed in future.
```
{ message:
   'Validating "examples" and "x-ms-examples" in  d:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json:\n',
  level: '\u001b[32minfo\u001b[39m' }
{ code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message:
   'Found errors in validating the request for x-ms-example "AvailableScopes" in operation "Reservation_AvailableScopes".:\nFound errors in validating the request for x-ms-example "AvailableScopes" in operation "Reservation_AvailableScopes".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'array', 'object' ],
            message: 'Expected type array but found type object',
            path: [],
            title:
             '{"path":["parameters","ScopeParameter","schema"],"position":{"line":1650,"column":17},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}' } ],
       in: 'body',
       message:
        'Invalid parameter (body): Value failed JSON Schema validation',
       name: 'body',
       path: [ 'parameters', 'body' ],
       schemaPath:
        '#/paths/~1providers~1Microsoft.Capacity~1reservationOrders~1{reservationOrderId}~1reservations~1{reservationId}~1availableScopes/post/parameters/3',
       title:
        '{"path":["parameters","body"],"position":{"line":6,"column":13},"url":"d:/git/github/azure-rest-api-specs/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-04-01/examples/GetAvailableScope.json"}' } ],
  level: '\u001b[31merror\u001b[39m' }
{ message:
   'Response with statusCode "200" for x-ms-example "AvailableScopes" in operation "Reservation_AvailableScopes" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ message:
   'Request parameters for x-ms-example "Catalog" in operation "GetCatalog" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ '0':
   { code: 'RESPONSE_VALIDATION_ERROR',
     id: 'OAV108',
     message:
      'Found errors in validating the response with statusCode "200" for x-ms-example "Catalog" in operation "GetCatalog".',
     innerErrors:
      [ { code: 'INVALID_RESPONSE_BODY',
          errors:
           [ { code: 'ANY_OF_MISSING',
               params: [],
               message: 'Data does not match any schemas from \'anyOf\'',
               path: [ 2 ],
               title:
                '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Capacity~1catalogs/get/responses/200/schema/items',
               inner:
                [ { code: 'ANY_OF_MISSING',
                    params: [],
                    message: 'Data does not match any schemas from \'anyOf\'',
                    path: [ 2, 'billingPlans' ],
                    title: '#/definitions/Catalog/properties/billingPlans',
                    inner:
                     [ { code: 'INVALID_TYPE',
                         params: [ 'object', 'array' ],
                         message: 'Expected type object but found type array',
                         path: [ 'billingPlans' ],
                         title: '#/definitions/Catalog/properties/billingPlans',
                         description: 'The billing plan options available for this SKU.',
                         position: { line: 739, column: 25 },
                         url:
                          'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                         directives: {} },
                       { code: 'INVALID_TYPE',
                         params: [ 'null', 'array' ],
                         message: 'Expected type null but found type array',
                         path: [ 'billingPlans' ],
                         title: '#/definitions/Catalog/properties/billingPlans',
                         position: { line: 739, column: 25 },
                         url:
                          'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                         directives: {} } ],
                    position: { line: 739, column: 25 },
                    url:
                     'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                    directives: {} },
                  { code: 'INVALID_TYPE',
                    params: [ 'null', 'object' ],
                    message: 'Expected type null but found type object',
                    path: [ 2 ],
                    title:
                     '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Capacity~1catalogs/get/responses/200/schema/items',
                    position: { line: 105, column: 24 },
                    url:
                     'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                    directives: {} } ],
               position: { line: 105, column: 24 },
               url:
                'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
               directives: {} },
             { code: 'ANY_OF_MISSING',
               params: [],
               message: 'Data does not match any schemas from \'anyOf\'',
               path: [ 1 ],
               title:
                '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Capacity~1catalogs/get/responses/200/schema/items',
               inner:
                [ { code: 'ANY_OF_MISSING',
                    params: [],
                    message: 'Data does not match any schemas from \'anyOf\'',
                    path: [ 1, 'billingPlans' ],
                    title: '#/definitions/Catalog/properties/billingPlans',
                    inner:
                     [ { code: 'INVALID_TYPE',
                         params: [ 'object', 'array' ],
                         message: 'Expected type object but found type array',
                         path: [ 'billingPlans' ],
                         title: '#/definitions/Catalog/properties/billingPlans',
                         description: 'The billing plan options available for this SKU.',
                         position: { line: 739, column: 25 },
                         url:
                          'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                         directives: {} },
                       { code: 'INVALID_TYPE',
                         params: [ 'null', 'array' ],
                         message: 'Expected type null but found type array',
                         path: [ 'billingPlans' ],
                         title: '#/definitions/Catalog/properties/billingPlans',
                         position: { line: 739, column: 25 },
                         url:
                          'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                         directives: {} } ],
                    position: { line: 739, column: 25 },
                    url:
                     'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                    directives: {} },
                  { code: 'INVALID_TYPE',
                    params: [ 'null', 'object' ],
                    message: 'Expected type null but found type object',
                    path: [ 1 ],
                    title:
                     '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Capacity~1catalogs/get/responses/200/schema/items',
                    position: { line: 105, column: 24 },
                    url:
                     'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
                    directives: {} } ],
               position: { line: 105, column: 24 },
               url:
                'd:\\git\\github\\azure-rest-api-specs\\specification\\reservations\\resource-manager\\Microsoft.Capacity\\preview\\2019-04-01\\reservations.json',
               directives: {} } ],
          message: 'Invalid body: Value failed JSON Schema validation',
          path: [] } ] },
  level: '\u001b[31merror\u001b[39m',
  message:
   'Found errors in validating the response with statusCode "200" for x-ms-example "Catalog" in operation "GetCatalog".:\n' }
{ message:
   'Request parameters for x-ms-example "AppliedReservationList" in operation "GetAppliedReservationList" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ message:
   'Response with statusCode "200" for x-ms-example "AppliedReservationList" in operation "GetAppliedReservationList" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message:
   'Found errors in validating the request for x-ms-example "Purchase" in operation "ReservationOrder_Calculate".:\nFound errors in validating the request for x-ms-example "Purchase" in operation "ReservationOrder_Calculate".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'ANY_OF_MISSING',
            params: [],
            message: 'Data does not match any schemas from \'anyOf\'',
            path: [ 'properties' ],
            title:
             '{"path":["definitions","PurchaseRequest","properties","properties"],"position":{"line":1344,"column":23},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
            inner:
             [ { code: 'ANY_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'anyOf\'',
                 path: [ 'properties', 'quantity' ],
                 title:
                  '{"path":["definitions","PurchaseRequestProperties","properties","quantity"],"position":{"line":1239,"column":21},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                 inner:
                  [ { code: 'INVALID_FORMAT',
                      params: [ 'int32', '1' ],
                      message: 'Object didn\'t pass validation for format int32: 1',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","ReservationQuantity"],"position":{"line":1565,"column":28},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                      description:
                       'Quantity of the SKUs that are part of the Reservation. Must be greater than zero.' },
                    { code: 'INVALID_TYPE',
                      params: [ 'integer', 'string' ],
                      message: 'Expected type integer but found type string',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","ReservationQuantity"],"position":{"line":1565,"column":28},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                      description:
                       'Quantity of the SKUs that are part of the Reservation. Must be greater than zero.' },
                    { code: 'INVALID_TYPE',
                      params: [ 'null', 'string' ],
                      message: 'Expected type null but found type string',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","PurchaseRequestProperties","properties","quantity"],"position":{"line":1239,"column":21},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}' } ] },
               { code: 'INVALID_TYPE',
                 params: [ 'null', 'object' ],
                 message: 'Expected type null but found type object',
                 path: [ 'properties' ],
                 title:
                  '{"path":["definitions","PurchaseRequest","properties","properties"],"position":{"line":1344,"column":23},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}' } ] } ],
       in: 'body',
       message:
        'Invalid parameter (body): Value failed JSON Schema validation',
       name: 'body',
       path: [ 'parameters', 'body' ],
       schemaPath:
        '#/paths/~1providers~1Microsoft.Capacity~1calculatePrice/post/parameters/1',
       title:
        '{"path":["parameters","body"],"position":{"line":4,"column":13},"url":"d:/git/github/azure-rest-api-specs/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-04-01/examples/CalculateReservationOrder.json"}' } ],
  level: '\u001b[31merror\u001b[39m' }
{ message:
   'Response with statusCode "200" for x-ms-example "Purchase" in operation "ReservationOrder_Calculate" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ message:
   'Request parameters for x-ms-example "ReservationOrderList" in operation "ReservationOrder_List" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ message:
   'Response with statusCode "200" for x-ms-example "ReservationOrderList" in operation "ReservationOrder_List" is valid.',
  level: '\u001b[32minfo\u001b[39m' }
{ code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message:
   'Found errors in validating the request for x-ms-example "Purchase" in operation "ReservationOrder_Purchase".:\nFound errors in validating the request for x-ms-example "Purchase" in operation "ReservationOrder_Purchase".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'ANY_OF_MISSING',
            params: [],
            message: 'Data does not match any schemas from \'anyOf\'',
            path: [ 'properties' ],
            title:
             '{"path":["definitions","PurchaseRequest","properties","properties"],"position":{"line":1344,"column":23},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
            inner:
             [ { code: 'ANY_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'anyOf\'',
                 path: [ 'properties', 'quantity' ],
                 title:
                  '{"path":["definitions","PurchaseRequestProperties","properties","quantity"],"position":{"line":1239,"column":21},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                 inner:
                  [ { code: 'INVALID_FORMAT',
                      params: [ 'int32', '1' ],
                      message: 'Object didn\'t pass validation for format int32: 1',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","ReservationQuantity"],"position":{"line":1565,"column":28},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                      description:
                       'Quantity of the SKUs that are part of the Reservation. Must be greater than zero.' },
                    { code: 'INVALID_TYPE',
                      params: [ 'integer', 'string' ],
                      message: 'Expected type integer but found type string',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","ReservationQuantity"],"position":{"line":1565,"column":28},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}',
                      description:
                       'Quantity of the SKUs that are part of the Reservation. Must be greater than zero.' },
                    { code: 'INVALID_TYPE',
                      params: [ 'null', 'string' ],
                      message: 'Expected type null but found type string',
                      path: [ 'quantity' ],
                      title:
                       '{"path":["definitions","PurchaseRequestProperties","properties","quantity"],"position":{"line":1239,"column":21},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}' } ] },
               { code: 'INVALID_TYPE',
                 params: [ 'null', 'object' ],
                 message: 'Expected type null but found type object',
                 path: [ 'properties' ],
                 title:
                  '{"path":["definitions","PurchaseRequest","properties","properties"],"position":{"line":1344,"column":23},"url":"d:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\reservations\\\\resource-manager\\\\Microsoft.Capacity\\\\preview\\\\2019-04-01\\\\reservations.json","directives":{}}' } ] } ],
       in: 'body',
       message:
        'Invalid parameter (body): Value failed JSON Schema validation',
       name: 'body',
       path: [ 'parameters', 'body' ],
       schemaPath:
        '#/paths/~1providers~1Microsoft.Capacity~1reservationOrders~1{reservationOrderId}/put/parameters/2',
       title:
        '{"path":["parameters","body"],"position":{"line":5,"column":13},"url":"d:/git/github/azure-rest-api-specs/specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-04-01/examples/PurchaseReservationOrder.json"}' } ],
```

**Comment by akning-ms** [comment]
Hi @aditink, according to @fengzhou-msft , you are urgent to get this PR merge. so I will suppress modal validation error to help merge first. as example quality is also very important for our downstream CLI tool. pls submit another PR to fix above modal validation failure

**Pull request merged**
