### PR TITLE
Add contract changes to ARM repo for MFE inference group status

### PR DESCRIPTION
**Pull request by ritujhams**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [x] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Convert existing [OpenAPI spec to TypeSpec spec](https://aka.ms/typespec/conversion) (do not combine this with implementing changes for a new API version).
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories)
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Review by paledger — APPROVED** [review]

**Comment by ritujhams** [comment]
Justification for the change - 
This is a new product offering and we made changes to the status api to fit user needs and we want this change to go in before customers start using the status api heavily.

Also this "Get Group Status" api is not being actively used in prod right now. Attached below is the result for last one month for prod regions. There are 0 results.

https://dataexplorer.azure.com/clusters/viennaweu/databases/Vienna?query=H4sIAAAAAAAAA3VTa2%2FTMBT9vl%2Fh5Usb5K5dmAQUhrS1EZvY1tEHEkxVZZK71ii1PdvZqMSP5%2BbpdClf8ri%2B5%2Fj43OMELPmaGitHCT5Bk3PSeeYgBLNgbOfjUYINKxDxnG8BF2OsW%2FzsBoPgrHd62jv9MA%2BC4dm74eD9T79sN5Zpexgw6AVBC4D0SnJhV4LlmE6571rLVL0uKimT1zUNTynKXV3HZXEhuBSTx4skuZFr0%2FW%2B50fyKPGuxSNoEBGMQSVytwVhPf%2Bo3ydRYUC36YZ%2FgvLZL2agpvBPDjAg%2Fi952WCZhOL5DsUZxSIgx5EUlnFhiKfSJPGOqq57DRE3kHk0s2yryOema0zE7Y5P5%2FUcappRQZ%2BN7Zx4vBLWi2tlPaa42xZ1GbYGsmEmcyKSWy7WlXtkMb0Zut6F5uS4bLRersmVeLsUMcH07nV1dLAKzNjUBJAy1aJB0Zqh%2FfniATUxJJbdSnyZQ8v9LVjWb%2BstrXHO9DfAErtxnQV8DRb9RnWOfFr4g%2BHKezh%2F7DYCd4zOM5wtbaQQc9bzfOLGjZnNUpE3O2Kc71bZXXcv%2Fz6RGlNUVHJQHaK9vhZLfTFyhnrLGl2vt5DunuXQL9nvPtZ15FGHPxa1oDFGSWFghNPAi2czbV2jEl49y7zRzvCh4z%2B8XdLOEt%2BDpd9kGaeaWbyuyPB%2F7FmNRfWKaePC%2FMLthrwh3jSc3U%2FuZuFqNBmHwwdvX563JOPF9GJ%2BPbnL1upNsT4Nvy3C2Xx1FV6Mw%2BnMK8iK2uVk%2FKPgymd7KeNdASn32seURQcqBJSobPBKy98Q2db1pi5ltBoddZOge4mg5MpadQt2IzFq1VFo87y0IZg2dVCMOq28%2BwfK5CI4%2FgUAAA%3D%3D

let KustoCluster = 'viennatest';
let _endTime = datetime(2024-11-19T22:47:08Z);
let _startTime = datetime(2024-10-22T22:47:08Z);
let endpoint_name = '';
let group_name = '';
let pool_name = '';
let request_Id = '';
UnionOfAllLogs("Vienna", "InferenceDeployment")
// cluster(KustoCluster).database("Vienna").InferenceDeployment
//| where EnvNamespace !contains "pull"
| where PreciseTimeStamp > _startTime and PreciseTimeStamp <= _endTime
| where Container == "inference-deployment-api"
| where message has "Incoming request URL:"
| where Uri !has "Int" and Uri !has "int" and Uri !has "canary" and Uri !has "Canary" and Uri !has "eastus2euap" and Uri !has "centraluseuap"
| where Uri !has "deltaModels"
| where Uri !has "/meta/" and Uri !has "inferencedeployment/health" and Uri has "/getStatus"
| where RequestId  has iif(request_Id != "all", request_Id, "-") 
| where PoolName != ""
| where isempty(endpoint_name) or EndpointName contains endpoint_name
| where isempty(pool_name) or PoolName contains pool_name
| where isempty(group_name) or GroupName contains group_name
//| extend ResponseCode = toint(split(split(message,':[')[3],']')[0])
//| extend Duration = split(split(message,':[')[4],']')[0]
| parse message with * "RESPONSE_CODE:[" ResponseCode "] DURATION:[" Duration "] REQUEST_HEADERS" * "REQUEST_BODY:[" RequestBody "] RESPONSE_HEADERS" * "RESPONSE_BODY:[" ResponseBody "]"
| project PreciseTimeStamp, RequestId,PoolName, GroupName, EndpointName, HttpMethod, Duration,ResponseCode,RequestBody,ResponseBody,Uri, message

**Comment by ms-bogdan-rotaru** [comment]
Please get the breaking change approval first and after that put the PR back in the review queue.

**Comment by ms-bogdan-rotaru** [comment]
@ritujhams The breaking change label has to be added by someone in the Breaking Change approval board.
Please check - https://aka.ms/brch

**Review by rkmanda — APPROVED** [review]
:shipit:

**Pull request merged**
