### PR TITLE
Release keyvault microsoft.key vault 7.5 preview.1

### PR DESCRIPTION
**Pull request by jlichwa**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by heaths** [comment]
@JeffreyRichter @mikekistler because this required -> non-required change happens in a new version, it should be approved, correct?

image

@jlichwa do you need help resolving the other errors? The CredScan issues seem new, but should be easy enough to fix or, if you're sure they are randomly generated, we could probably ignore. The other issues about the base64 not being convertible to byte is concerning, though. But those samples didn't change from the last version. Still, maybe we should make them right to avoid this problem in the future.

**Comment by jlichwa** [comment]
> @JeffreyRichter @mikekistler because this required -> non-required change happens in a new version, it should be approved, correct?
> 
> image
> @jlichwa do you need help resolving the other errors? The CredScan issues seem new, but should be easy enough to fix or, if you're sure they are randomly generated, we could probably ignore. The other issues about the base64 not being convertible to byte is concerning, though. But those samples didn't change from the last version. Still, maybe we should make them right to avoid this problem in the future.

@riteshchitlangia1 can you help here

**Comment by heaths** [comment]
Talked to @JeffreyRichter and @mikekistler offline and they agree this is not a breaking change, per https://aka.ms/AzBreakingChangePolicy. Approved.

**Comment by heaths** [comment]
The ModelValidation errors `OBJECT_MISSING_REQUIRED_PROPERTY` are red herrings: there is a bug in the validator that, because "scope" is `/` any subsequent parameters are seemingly ignored. But if you change the order of the parameters, that generates a different error because they are out of order which, honestly, shouldn't matter. I already opened an [issue](https://github.com/Azure/azure-sdk-tools/issues/4420) for this that was purportedly fixed, but seems it has returned. /cc @konrad-jamrozik

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Comment by konrad-jamrozik** [comment]
> The ModelValidation errors `OBJECT_MISSING_REQUIRED_PROPERTY` are red herrings: there is a bug in the validator that, because "scope" is `/` any subsequent parameters are seemingly ignored. But if you change the order of the parameters, that generates a different error because they are out of order which, honestly, shouldn't matter. I already opened an [issue](https://github.com/Azure/azure-sdk-tools/issues/4420) for this that was purportedly fixed, but seems it has returned. /cc @konrad-jamrozik

Fwding to @scbedd as owner of ModelValidation. @heaths FYI: scbedd owns ModelValidation and SemanticValidation.

**Review by heaths — APPROVED** [review]
I previously diffed the JSON against 7.4 and found only the expected 2 added properties and change from a required to non-required for another property.

**Comment by heaths** [comment]
The ModelValidation error re: api-version is a validation bug. See previous comments for more details. I'm overriding.

**Comment by konrad-jamrozik** [comment]
@heaths I forced the stuck merging requirements check to pass by direct database edit and I merged the PR. Root-causing the problem proves to be a bit difficult. Possibly some kind of race condition to db writes.

**Pull request merged**
