### PR TITLE
Add resources for SourceControl and SourceControlSyncJob

### PR DESCRIPTION
**Pull request by MiaRomero**
Replacement for PR #2158 

SourceControl is a resource to link a user's source control with their Azure Automation (AA) account.

SourceControlSyncJob allows the user to sync their runbooks from their external source control with their AA account.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by marstr — CHANGES_REQUESTED** [review]
Howdy @MiaRomero,

Before we get started in earnest with the review of this PR, please take a look at the CI logs here:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/325642969#L734

I see in the PR Bot's comment above that you haven't added any new linter errors, but the model errors should be addressed if they are new because of your PR.

**Comment by marstr** [comment]
Feel free to reach out here, or offline, if you have questions about reading the CI output. :)

**Comment by MiaRomero** [comment]
Hi @marstr, Thank you for the CI logs.  I have made changes to correct the errors, but before I push them, can you tell me how I can see the logs or find out if there are any more errors?  I saw "All checks have passed" and thought that everything was ok.  Where do I look to see if there are any errors created by my PR?  Thanks!

**Comment by marstr** [comment]
Ah yeah, sorry about that! I know it's a confusing thing, and something we're trying to improve on our side.

If you click on "Show all checks" then "Details" for "continuous-integration/travis-ci/pr --- The Travis CI build passed" it'll bring you [here](https://travis-ci.org/Azure/azure-rest-api-specs/builds/325642958?utm_source=github_status&utm_medium=notification). From there you'll see that there are two sections: "Build Jobs" and "Allowed Failures". All of the "Build Jobs" must pass, and any of the "Allowed Failures" that are marked as "PR_ONLY=true".

You may very reasonably ask, "if there are things that are marked allowed failure, then why do I have to fix it?" Basically the answer is, for a handful of services we don't yet have all of their linter and model errors either fixed or suppressed. Until that time comes, we're stuck with this non-optimal solution.

Sorry for the inconvenience!

**Comment by MiaRomero** [comment]
@marstr, Thank you very much!  I"ll keep an eye on those when I push my changes.

**Comment by ravbhatnagar** [comment]
Looks good.

**Review by marstr — APPROVED** [review]

**Comment by marstr** [comment]
Let me know when you're ready for this to merge, @MiaRomero. The only assurances that we need are that the service will be live and ready to start receiving requests matching these additions.

**Comment by MiaRomero** [comment]
Hi @marstr, you can go ahead and merge.  Thank you!

**Pull request merged**
