### PR TITLE
SIP-Update formatting of security section

### PR DESCRIPTION
**Pull request by dzeliar**
# Data Plane API - Pull Request
Update formatting of security section to properly generate documentation. In documentation review process we discovered apiKey authentication has been missing. This PR updates the definition to include both user_impersonation & apiKey.

## API Info: The Basics

* Link to API Spec engagement record issue:
Ticket tracking documentation https://dev.azure.com/ceapex/Onboarding/_workitems/edit/815841

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [x] GA release

### Change Scope
No functional changes

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>

* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by JeffreyRichter** [comment]
- Do not put a slash in the trunks/health enum value - this won't be representable in language SDKs. Come up with another way of expressing this. An underscore would work or camel casing: trunksHealth.

- The default error must use Azure's default error JSON response. It looks like it's just a "string" right now.

- For testRoutesWithNumber. Some languages will have a problem with a plus sign (+) in front of the phone number as they treat + as space. See [example](https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20)

**Comment by dzeliar** [comment]
@Hello @JeffreyRichter, thank you for review, we'll keep your notes for the next iteration of preview of this API. 
This PR changes security section (latest stable&preview versions), which had to be modified as it generated incorrect documentation. Can we please get an approval for these changes as we need to go officially GA with already merged stable version? Thank you

**Comment by dzeliar** [comment]
Hello @JeffreyRichter, did you have a change to have a look at my previous comment? Is this change possible? Thank you

**Review by JeffreyRichter — APPROVED** [review]

**Comment by JeffreyRichter** [comment]
I approved this PR

**Pull request merged**
