### PR TITLE
fix: Microsoft.Solutions model validation errors

### PR DESCRIPTION
**Pull request by nschonni**
- applianceName -> applianceDefinitionName
- Add empty 404 declared responses
- Remove undefined resourceGroup property from responses
- Replace lockLevel = null with "None" to match non-nullable enum
- Duplicate 201 to 200 for missing responses for createOrUpdate examples
- managedApplicationDefinitionId -> applicationDefinitionId

### CODE REVIEW

**Comment by yungezz** [comment]
HI @Tiano2017  @rajshah11  could you pls review the changes on sample file?

**Comment by yungezz** [comment]
HI @Tiano2017 @rajshah11 could you pls review the changes on sample file?

**Comment by Tiano2017** [comment]
@dandanwang0320 can you take a look at this PR?

**Comment by dandanwang0320** [comment]
@nschonni Hi, I have a PR 6680, which is fixing these too.
Do you need these fixes in a hurry?

**Comment by nschonni** [comment]
@dandanwang0320 no rush, I just PR this stuff when I come across things trying out OAV. If you want to pull them into your PR, that's fine too

**Comment by yungezz** [comment]
@nschonni , @dandanwang0320 what's the conclusion here? close this one but merging a new PR or merge this one?

**Comment by nschonni** [comment]
@yungezz did you mean to close this with your comment?

**Comment by nschonni** [comment]
@yungezz this PR is fixing issues with previous examples, the other PR is introducing a new API so they don't overlap

**Pull request closed without merging**
