### PR TITLE
Redis API changes to support zones

### PR DESCRIPTION
**Pull request by hrishikeshpathak**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by veronicagg — CHANGES_REQUESTED** [review]
thanks @hrishikeshpathak 
1) Is this PR based on the previous API version?, if so, could you make a first commit with the previous version unchanged, then do your modification in subsequent commits (this makes the review more readable - see https://github.com/Azure/azure-rest-api-specs/blob/current/.github/CONTRIBUTING.md#filenames-and-folder-structure )
2) Please move your spec "redis.json" outside the swagger folder, placing it in the api-versioned folder and remove the "swagger" folder. Relative references in the file are not working due to this.
3) CLA check is failing, if you're a MS FTE, could you double check your account is linked to MS?

**Comment by veronicagg** [comment]
@mcardosos feel free to pick up this review, when @hrishikeshpathak makes the next update.

**Comment by veronicagg** [comment]
@hrishikeshpathak please take a look at the linter errors at https://travis-ci.org/Azure/azure-rest-api-specs/jobs/293400556#L771, they are both violations of ARM rules. 
@ravbhatnagar can comment further if needed. 
Also, please update readme.md at https://github.com/hrishikeshpathak/azure-rest-api-specs/blob/99773449126fadd14b13085e9dfb7df256e27d05/specification/redis/resource-manager/readme.md and if you'd like it to be use as the latest package, please update the label in the basic configuration section to refer to it. Thanks!

**Comment by ravbhatnagar** [comment]
For the first one, please plan on fixing it in an api-version update. This will be non-compliant with all the Azure platform. Why not just fix it in a new api-version?
For #2, it is fine. It is a tooling issue. @veronicagg @salameer  – The linter rule needs to be updated to include “zones” as an allowed top level property.
So looks good from ARM side.

**Comment by veronicagg** [comment]
@ravbhatnagar ok, on the linter rule update, I've logged an issue for it, we weren't aware of that allowed property.

**Comment by veronicagg** [comment]
@hrishikeshpathak for the linter error that will get fixed in the tool, you could add a suppression - see https://github.com/Azure/adx-documentation-pr/wiki/Swagger-Validation-Errors-Suppression.
Please address the "readme.md" comment I made above, as the files are not getting included in it. Feel free to let us know if you have questions about it. Thanks.

**Comment by veronicagg** [comment]
@hrishikeshpathak one more question, was the service side updated for camel casing of the property updated in your last commits?

**Review by veronicagg — APPROVED** [review]

**Pull request merged**
