### PR TITLE
[Hub Generated] Review request for Microsoft.KeyVault to add version preview/2020-04-01-preview

### PR DESCRIPTION
**Pull request by jiacheng-L**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/jiacheng-L/azure-rest-api-specs/dev-keyvault-Microsoft.KeyVault-2020-04-01-preview-LintingFix...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [x] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by raych1** [comment]
> Hi @jiacheng-L, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review.
> **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).
> If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/12477&days=5).
> If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback.

@jiacheng-L , can you take above **action** to kick off the breaking change review?  Also, please select the SDK/CLI to refresh in the first comment of this PR.

**Comment by heaths** [comment]
Why are breaking changes on a *preview* swaggers considered breaking? These add specifications that, by default, the standard Azure error is returned. That wouldn't even be considered breaking compared to a previous stable version.

**Comment by raych1** [comment]
> Why are breaking changes on a _preview_ swaggers considered breaking? These add specifications that, by default, the standard Azure error is returned. That wouldn't even be considered breaking compared to a previous stable version.

Even it's aligned with the service code, this is considered a breaking change to SDK which doesn't return as default error model.  There's an breaking change approval window before 1/31 to fix this kind of swagger s360 KPI issue. So, just request the breaking change review with this justification.

**Comment by jiacheng-L** [comment]
> > Why are breaking changes on a _preview_ swaggers considered breaking? These add specifications that, by default, the standard Azure error is returned. That wouldn't even be considered breaking compared to a previous stable version.
> 
> Even it's aligned with the service code, this is considered a breaking change to SDK which doesn't return as default error model. There's an breaking change approval window before 1/31 to fix this kind of swagger s360 KPI issue. So, just request the breaking change review with this justification.

This is considered as Swagger s360 KPI issue because it doesn't return the default error model. And I already submitted the breaking change review request. But actually, adding this default error back on a **_preview_** version should not be considered as a breaking change.
Compared to my another PR(https://github.com/Azure/azure-rest-api-specs/pull/12475), it is reasonable to consider that one as breaking change as it added the default error back on a **_stable_** version. But this one should not be. Am I correct?

**Comment by raych1** [comment]
> > > Why are breaking changes on a _preview_ swaggers considered breaking? These add specifications that, by default, the standard Azure error is returned. That wouldn't even be considered breaking compared to a previous stable version.
> > 
> > 
> > Even it's aligned with the service code, this is considered a breaking change to SDK which doesn't return as default error model. There's an breaking change approval window before 1/31 to fix this kind of swagger s360 KPI issue. So, just request the breaking change review with this justification.
> 
> This is considered as Swagger s360 KPI issue because it doesn't return the default error model. And I already submitted the breaking change review request. But actually, adding this default error back on a **_preview_** version should not be considered as a breaking change.
> Compared to my another PR(#12475), it is reasonable to consider that one as breaking change as it added the default error back on a **_stable_** version. But this one should not be. Am I correct?

Per the [policy](https://microsoft.sharepoint.com/teams/azureecosystem/servicerings/Shared%20Documents/Breaking%20Changes/Azure%20Breaking%20Changes%20Program%20Definition-%20V1.1.pdf), breaks to public preview version needs a new API version.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by raych1** [comment]
@ArcturusZhang @msyyc , can you check if there's any SDK breaking change? Thanks.

**Review by heaths — APPROVED** [review]

**Review by ArcturusZhang — APPROVED** [review]
The breaking changes do not come from this PR

**Review by jlichwa — APPROVED** [review]

**Comment by msyyc** [comment]
For python, the breaking changes do not come from this PR

**Review by raych1 — APPROVED** [review]

**Pull request merged**
