### PR TITLE
Reservations RP 2018-06-01 specs

### PR DESCRIPTION
**Pull request by juhee0202**
Link to private repo PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/467

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by juhee0202** [comment]
We are adding a new API version to Reservations API. We are planning to meet the following dates for SDK release. Please refer to the private PR which has been reviewed.
- 2018-06-19 for CLI
- 2018-06-15 for Powershell

**Comment by dsgouda** [comment]
Working on Network RP, reassigning

**Comment by lmazuel** [comment]
Hi @juhee0202 
Since I already reviewed the PR I'm fine the content, it's pre-approved. Just a last question before merging, is this API public already in all regions where the previous API was? If not, could you give a timeline?
Thanks!

**Comment by juhee0202** [comment]
Hi @lmazuel. The new API version is public but is only available to select users. It will be available for everyone on 6/18. Also, I would like to make one small renaming change before merging the PR. We added a new field called "autofit" in ReservationProperties object, but we would like to rename that. Currently pending on my team to decide the new property name.

**Comment by juhee0202** [comment]
@lmazuel just pushed the rename changes. please take another look!

**Comment by juhee0202** [comment]
I have made changes from stable to preview for 2018-06-01. Please let me know if any other changes should be made before PR is merged.

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
