### PR TITLE
[Hub Generated] Review request for Microsoft.Security to add version stable/2019-08-01

### PR DESCRIPTION
**Pull request by liranc**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/liranc/azure-rest-api-specs/dev-security-Microsoft.Security-2019-08-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by liranc** [comment]
@xccc-msft I believe the **public.rest-api-specs (BreakingChange)** gate failure is a false positive.
The latest version of the swagger results in an error when attempt to generate code using AutoRest.
The issue is that the `ruleType` field was defined both in `CustomAlertRule` (the base type) and `AllowlistCustomAlertRule` (deriving type). Also, it wasn't marked as a discriminator even though it behaved like one.
So the changes in the PR remove the duplicate definition of the property and declare it as a discriminator.
As far as I understand this change has no affect on the API itself, so there should be no reason to update the api-version.
Is that correct?

**Comment by xccc-msft** [comment]
@NullMDR Can you please advise for the CIs?

**Comment by NullMDR** [comment]
> @xccc-msft I believe the **public.rest-api-specs (BreakingChange)** gate failure is a false positive.
> The latest version of the swagger results in an error when attempt to generate code using AutoRest.
> The issue is that the `ruleType` field was defined both in `CustomAlertRule` (the base type) and `AllowlistCustomAlertRule` (deriving type). Also, it wasn't marked as a discriminator even though it behaved like one.
> So the changes in the PR remove the duplicate definition of the property and declare it as a discriminator.
> As far as I understand this change has no affect on the API itself, so there should be no reason to update the api-version.
> Is that correct?

@jianyexi Could you please help on the breaking change detection in CI?

**Comment by liranc** [comment]
@NullMDR @jianyexi Hi, any updates on this PR?

**Comment by jianyexi** [comment]
> @xccc-msft @NullMDR @jianyexi Hi, any updates on this PR?
seems make sense , currently we can go on reviewing , and ask @akning-ms to merge it  at last

**Comment by akning-ms** [comment]
Hi @liranc, Seems you are just fix duplicate RuleType issue in this PR. So removed ARM review request. agree it is not breaking change for api. but I am not sure for sdk. can you share me about what language sdk to be released for this PR? I may ask sdk owner to take a look.

**Comment by liranc** [comment]
> Hi @liranc, Seems you are just fix duplicate RuleType issue in this PR. So removed ARM review request. agree it is not breaking change for api. but I am not sure for sdk. can you share me about what language sdk to be released for this PR? I may ask sdk owner to take a look.

@akning-ms The released SDK is C#. The generated code will look a bit different and possibly break existing code, but is this an issue since the NuGet is always published using a different version? (so only those who would upgrade to the new version will need to make these few adjustments).
Thanks!

**Comment by akning-ms** [comment]
approved, but @isra-fel for awareness .Net sdk

**Pull request merged**
