### PR TITLE
chore: jsonfmt network 2017

### PR DESCRIPTION
**Pull request by nschonni**
Ran `jsonfmt -w "specification/network/**/stable/2017*/**/*.json"`

### CODE REVIEW

**Comment by dsgouda** [comment]
@sergey-shandar are these model validation errors expected?

**Comment by nschonni** [comment]
@MikhailTryakhov looks like the model validation is an existing issue. I can't tell which of the 3 examples for `PublicIPAddresses_CreateOrUpdate` is the one it's flagging to fix it

**Comment by EvgenyAgafonchikov** [comment]
Updated failing example.

@nschonni, if you are interested in, you may wish to review [available validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) that allow to localize root causes of some specs or examples failures quickly. For example `oav validate-example <path>` returns details on all the examples referenced in spec file.

To check large set of files locally (and avoid waiting for CI results then) you may also script it like this
```powershell
network\resource-manager\Microsoft.Network\stable>$(Get-ChildItem -Path . -Filter "2017*") | % { (Get-ChildItem $_.FullName | Where-Object { -not ($_ -is [System.IO.DirectoryInfo]) }) | % { & oav validate-example $_.FullName } }
```

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
