### PR TITLE
update GC Swagger spec to match with most recent service interface

### PR DESCRIPTION
**Pull request by gehuang-dut**
Validated with commands bellow:
autorest readme.md --azure-validator 1>warnings.txt 2>errors.txt
no new errors and warnings.

Generated new SDK and local test passed.

Followed Swagger update instruction/requirement at:

https://microsoft.sharepoint.com/teams/Operations_Management_Suite/_layouts/OneNote.aspx?id=%2Fteams%2FOperations_Management_Suite%2FShared%20Documents%2FAutomation%2FOaaS%20Workbook%2Fautomation%20workbook&wd=target%282%20-%20Team%20Guides%2FEngineering%20Guides%2FCmdlets%20and%20SDK.one%7CF9B2BF3A-9301-46D6-BB5B-102E163282FC%2FChanging%20swagger%20specifications%7CC338C564-33E1-450B-A9B8-467D332D833B%2F%29
onenote:https://microsoft.sharepoint.com/teams/Operations_Management_Suite/Shared%20Documents/Automation/OaaS%20Workbook/automation%20workbook/2%20-%20Team%20Guides/Engineering%20Guides/Cmdlets%20and%20SDK.one#Changing%20swagger%20specifications&section-id={F9B2BF3A-9301-46D6-BB5B-102E163282FC}&page-id={C338C564-33E1-450B-A9B8-467D332D833B}&end

------

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I have reviewed the [documentation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/202/Overall-Process-of-AME-Onboarding) for the workflow.
- [x] [Validation tools](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/84/Swagger-Validation-tools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/FAQ.md).

### ARM API Review Checklist
- [x] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process]( https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/212/Swagger-PR-Review).

### CODE REVIEW

**Comment by NullMDR** [comment]
@gehuang-dut Please fix the error in CI

**Comment by gehuang-dut** [comment]
"breaking change" triggered. Checked, tested and validated it's working normally. This is fine.

**Comment by gehuang-dut** [comment]
> 
> 
> @gehuang-dut Please fix the error in CI

All auto checks fixed.
It triggered a "breaking change" when fixing them. The "breaking change" is triggered by two things:
1, when fixing READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST
2, when fixing THE DEFAULT ERROR RESPONSE SCHEMA NOT COMPLY

These are supposed change. The original version's wrong.

Thanks,
Ge

**Review by KrisBash — APPROVED** [review]
New APIs look good to me

**Review by PhoenixHe-NV — APPROVED** [review]

**Comment by NullMDR** [comment]
@akning-ms Please help to merge this PR with breaking change approved

**Pull request merged**
