### PR TITLE
Update CommonDefinitions.json

### PR DESCRIPTION
**Pull request by PiDiBi**
added ftpsState enum to SiteConfig object

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by annatisch** [comment]
@PiDiBi - there is a linter error (TrackedResourcePatchOperation) for this service as well as lots of missing examples. Are you able to take a look?

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/379898643

**Comment by PiDiBi** [comment]
@annatisch I don't see any error related to ftpsState which I added, but it's possible that I don't understand the log, I don't know what is linter

**Comment by annatisch** [comment]
@PiDiBi - that's correct - the errors appear to be unrelated to this specific change.

However the TrackedResourcePatchOperation is an ARM violation for this spec and sooner or later it either needs to be resolved or suppressed. Could you please contact @ravbhatnagar in order to get a suppression approved for this error? It would be great if we could get this cleaned up in the CI.

Additionally we would love to see the examples added, though I appreciate that you may not be in a position to do so for this PR.

**Comment by naveedaz** [comment]
@annatisch The issues pointed out in the PR are not related to change. There is a separate thread about suppressing/resolving the trackedResourcePatchOperation issue and missing examples will be handled by the documentation team. @ravbhatnagar is aware of both of these issues. This PR should not be blocked on them.

**Comment by annatisch** [comment]
@naveedaz - great thanks for the context!

**Review by annatisch — APPROVED** [review]

**Pull request merged**
