### PR TITLE
remove some internal object

### PR DESCRIPTION
**Pull request by chingchenmsft**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sarangan12** [comment]
@chingchenmsft 

The following errors are showing up in linter:

ERROR: A body parameter must be named 'parameters'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ServiceFabric/clusters/{clusterName}/patch/parameters[4]
ERROR: A body parameter must be named 'parameters'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ServiceFabric/clusters/{clusterName}/put/parameters[4]
WARNING: 'properties' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterCodeVersionsResult/properties/properties
WARNING: 'value' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterCodeVersionsListResult/properties/value
WARNING: Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined: 'isPrimary'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/NodeTypeDescription
WARNING: Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined: 'isAdmin'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClientCertificateThumbprint
WARNING: Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined: 'isAdmin'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClientCertificateCommonName
WARNING: Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined: 'overrideUserUpgradePolicy'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterUpgradePolicy
WARNING: Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined: 'forceRestart'.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterUpgradePolicy
WARNING: 'properties' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterUpdateParameters/properties/properties
WARNING: 'properties' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/Cluster/properties/properties
WARNING: 'value' model/property lacks 'description' property. Consider adding a 'description' element. Accurate description is essential for maintaining reference documentation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-servicefabric/2016-09-01/swagger/servicefabric.json#/definitions/ClusterListResult/properties/value
ERROR: Errors found during Swagger validation

Could you please fix them?

**Comment by sarangan12** [comment]
no schema validation/example errors found

**Comment by sarangan12** [comment]
@chingchenmsft 

Could you please resolve the issues and respond?

**Review by salameer — DISMISSED** [review]
@chingchenmsft 

Kindly respond to the requested changes

**Comment by sarangan12** [comment]
Update: I have synched up with Ching Chen offline (IM) and confirmed that he will update the comments today.

**Comment by sarangan12** [comment]
Update: All errors seem to be fixed. One of the reported error seems to be issue with the linter and not related to the swagger. Approving this one.

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
