### PR TITLE
[ACR] Add "19-05-01" GA specification for Microsoft.ContainerRegistry

### PR DESCRIPTION
**Pull request by ankurkhemani**
### Latest improvements:
- Remove support for PUT/PATCH of registry resource with `Classic` SKU.
- Refactor Policy APIs: Policy is now part of `RegistryProperties` and hence managed by CRUD on registry resource.
- PUT on ARM resources now supports replace semantics (no swagger change). // cc @ravbhatnagar 
(**no new APIs added, two APIs deprecated**)

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6091 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6091/commits/73b56093bdf7173263027a790d636dd94d64a6ef

**Comment by ankurkhemani** [comment]
//cc @mnltejaswini  @djyou @sajayantony

**Comment by ravbhatnagar** [comment]
@ankurkhemani - The new api-version does not contain many of the APis in the previous API version. Not sure why is this. Typically, all older APis are present in the latest api-version along with any additions or updates to existing. That way customer can move to the latest api-version and use all the functionality offered by your service. Please feel free to schedule a 30 min sync to close on this review quicker.

**Comment by ankurkhemani** [comment]
@ravbhatnagar Those must be the [Tasks APIs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2019-04-01) which are not part of this API version?
// cc @mnltejaswini 

Anyways, I will schedule a meeting to review these changes.

**Comment by ankurkhemani** [comment]
@ravbhatnagar Can you help me understand why is the CI failing for `python` and `ruby` sdk here?

**Comment by dsgouda** [comment]
startbuild

**Comment by ankurkhemani** [comment]
@dsgouda @ravbhatnagar  Can you please help me understand the CI fail for `ruby` sdk? Also, not sure why the PR for `python-sdk` and `ruby-sdk` is not generated?

**Comment by dsgouda** [comment]
@sergey-shandar please take a look

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6370 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6370/commits/604a9e4ddec2d02a9e72b48ac10b42b70ed36bf6

**Comment by ravbhatnagar** [comment]
2 changes in this new api-version
1. PUT behavior changed to replace semantics for all resource types.
2. policies on registry was being set using actions. In this api-version, its a property on the registry. Discussed cross api-version scenarios. The outstanding action item on ACR team is to block update of policies on a registry from an older api-version if it was created using the newer api version.
another feedback was to make retentionPolicy status an enum
Signing off from ARM side since the team has agreed to make the recommended changes.

**Comment by ankurkhemani** [comment]
@ravbhatnagar @sergey-shandar As discussed, I have added the enum for retention policy status. Also, created a work item [#4672516](https://msazure.visualstudio.com/One/_workitems/edit/4672516) to track cross-api scenarios as mentioned by @ravbhatnagar 

Can you please help me with the CI here and get this PR merged? Also need to generate the python sdk. Thanks!

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
