### PR TITLE
[Stream Analytics] Add Azure Function and Blob Input MSI

### PR DESCRIPTION
**Pull request by roslynlu**
Changes in this PR include:
- add Azure Function output to 2017 preview, 2021 preview, and 2020 stable
   - add corresponding Azure Function example files, and add missing SQL DW example files
- add authenticationMode for blob input to 2017 preview, 2021 preview, and 2020 stable
   - before, we only supported authentication mode for blob output, which is why the authentication mode property used to be in outputs.json. these changes remove it from outputs.json and includes it in the BlobDataSourceProperties object, which is referenced by both blobinput and bloboutput
- fix api versions for example files in 2021 preview folder

Both Azure Function and MSI for blob input are available in versions 2017 preview, 2021 preview, and 2020 stable. Updating swagger to reflect that.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [X] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [x] SDK of Go
      - [x] PowerShell
      - [x] CLI
      - [x] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by roslynlu** [comment]
@weidongxu-microsoft I pushed a small fix (removed an extra property in some example files), but then the swagger validation bot started complaining about discriminator_value_not_found for the serialization property in inputs.json. I'm confused because this wasn't modified/touched in this PR, and it wasn't failing the first few commits either. Do you have insight on what the issue could be?

**Comment by weidongxu-microsoft** [comment]
@roslynlu 

Your example seems wrong.
E.g. https://github.com/Azure/azure-rest-api-specs/blob/6a2d393e781b1d0ec333fbece63126f43fc00d52/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2017-04-01-preview/examples/Output_Create_Blob_CSV.json

`serialization` property should be same level as `datasource`?

**Comment by roslynlu** [comment]
@weidongxu-microsoft yes, serialization and datasource are on the same level. you can see this in the object OutputProperties in outputs.json. and as far as I can tell, all the example files are consistent with this

**Comment by weidongxu-microsoft** [comment]
@roslynlu

I see. Yes, your example is correct.

I will rerun the CI. If it still fails I will loop-in tooling.

**Comment by weidongxu-microsoft** [comment]
ModelValidation seems not correct.
E.g. "Csv" "Avro" etc. is defined in the model
https://github.com/Azure/azure-rest-api-specs/blob/6a2d393e781b1d0ec333fbece63126f43fc00d52/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2017-04-01-preview/outputs.json#L514-L517
https://github.com/Azure/azure-rest-api-specs/blob/6a2d393e781b1d0ec333fbece63126f43fc00d52/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2017-04-01-preview/inputs.json#L872-L884
https://github.com/Azure/azure-rest-api-specs/blob/6a2d393e781b1d0ec333fbece63126f43fc00d52/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2017-04-01-preview/inputs.json#L1182-L1196

**Comment by weidongxu-microsoft** [comment]
@raych1 Hi Ray, would you double check whether ModelValidation result is correct or not, when you get time?

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by raych1** [comment]
> @raych1 Hi Ray, would you double check whether ModelValidation result is correct or not?

@weidongxu-microsoft , they are false alarm and were fixed in latest version of OAV. We will release it to pipeline this week.

**Pull request merged**
