### PR TITLE
Add missing entities

### PR DESCRIPTION
**Pull request by moranraz**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [X] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [X] PowerShell
      - [X] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by moranraz** [comment]
@leni-msft - this PR fixes the following issues:
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=38EF1232-6673-4942-ABFC-CB2EFD8BCDA9
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=1FC9C8F4-C940-48B1-B032-3C8CD1401284

**Comment by leni-msft** [comment]
@moranraz adding properties are potential breaking changes, please follow the **Action** in above comment to request approval. Also see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/405/Window-to-Fix-Broken

**Comment by moranraz** [comment]
> @moranraz adding properties are potential breaking changes, please follow the **Action** in above comment to request approval. Also see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/405/Window-to-Fix-Broken

Hi @leni-msft, the properties I added are properties that were missing, and their addition is in response to the bugs that I linked above. As you probably know, we were giving a window (until the end of January) to fix all of these bugs that ARM has found in our endpoints without having to release a new version. 

in the link you attached it says:
Process change: No change to PR Review process -- update(s) with breaking change detection still need to pass Breaking Change Board review, and get approval before merging to master branch. However, with clarification of "fixing broken" purpose, the update(s) is most likely to be approved, although it is to update a stable API version.

There have been multiple PRs from my team with the same changes that were approved in the past week.

Thanks!

**Comment by leni-msft** [comment]
@moranraz could you attach the workItem link in the PR comment?

**Comment by moranraz** [comment]
> @moranraz could you attach the workItem link in the PR comment?

this PR fixes the following issues:
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=38EF1232-6673-4942-ABFC-CB2EFD8BCDA9
https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=1FC9C8F4-C940-48B1-B032-3C8CD1401284

**Comment by leni-msft** [comment]
@moranraz Sorry, I meant the Intake ticket to request breaking changes. If not created yet, you need follow the breaking change policy to request approval.

**Comment by moranraz** [comment]
> @moranraz Sorry, I meant the Intake ticket to request breaking changes. If not created yet, you need follow the breaking change policy to request approval.

There is no intake ticket, and as far as we know there's no need for one. Like I said, the properties I added are properties that were missing, and their addition is in response to the bugs that I linked above. 
These changes are done within the window (until the end of January) that you guys gave to fix all of these bugs that you've found in our endpoints without having to release a new version.
So these changes are in fact not breaking changes, and there's no need for a ticket.
Thanks!

**Comment by moranraz** [comment]
@JeffreyRichter

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
