### PR TITLE
updating the descriptions in RecoveryServicesBackup.json

### PR DESCRIPTION
**Pull request by markgalioto**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/azure-rest-api-specs/721)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@markgalioto__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (markgal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@markgalioto  - Please look at the Travis CI logs. It has all the information. The CI is failing due to the mismatch in description for subscriptionId between two specs.
image

**Comment by markgalioto** [comment]
@amarzavery , thank you for the tip about Travis CI logs. Is there somewhere that explains how to use Travis CI logs? It's my first time working on this type of build, and though I can understand there is a mismatch (based on your graphic), I don't understand how to find the information that you've provided. I want to do the research, I just don't know how to find the data.

**Comment by markgalioto** [comment]
@amarzavery , I think I'm starting to figure it out. You don't need to respond to my previous comment.

**Comment by markgalioto** [comment]
@BryanLa, Can you merge this PR? My changes to the 2 .json files were only the description fields. And as others found out, I had inconsistent descriptions between the two files. These inconsistencies have been fixed.

**Comment by markgalioto** [comment]
#sign-off

**Comment by BryanLa** [comment]
@markgalioto - registeredIdentities.json looks good, but I can't get the diff to show on recoveryservicesbackup.json as GitHub is saying it's too large (438 deletions, 438 additions). Can you confirm that there were that many changes to the latter? Or is it possible the PR is picking this up by accident?

**Comment by markgalioto** [comment]
@BryanLa - recoveryservicesbackup.json probably had 438 deletions and additions, however those changes were checked in yesterday. I'll double check that the latest version of the recoveryservicesbackup.json is what is showing up.

**Comment by markgalioto** [comment]
@BryanLa - I verified that the recoveryservicesbackup.json is the version that I've been editing. It has 432 of the updates, and registeredIdentities.json has the other six. Don't know why these files continue to show as being 19 days and one month old in my fork. These are ready for merging.

**Comment by markgalioto** [comment]
#sign-off - adding again, just in case it's needed.

**Pull request merged**
