### PR TITLE
Remove providerhub package

### PR DESCRIPTION
**Pull request by timotheeguerin**
This package is now empty as of release 0.40.0 so we can remove it.

Closes https://github.com/Azure/typespec-azure-pr/issues/4039

### CODE REVIEW

**Review by mikeharder — CHANGES_REQUESTED** [review]
Need to update package-lock.json.  I will try to push to your PR.

**Review by mikeharder — APPROVED** [review]

**Comment by timotheeguerin** [comment]
oh I never pushed that, was left pending in my branch...

**Pull request merged**
