### PR TITLE
Service fabric

### PR DESCRIPTION
**Pull request by msjeffreychen**

### CODE REVIEW

**Comment by amarzavery** [comment]
>               "type": "object",

It would be nice if you can describe the inline body parameter definition as a model definition and reference it here. Please make sure to define the description for every property as that will be the client and msdn documentation 

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:43 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>                 "Description": {

Are all these properties actually in Pascal case on the wire? Usually properties are in camelCase based on my experience of reviewing swagger specs. I would recommend validating this with actual request using Fiddler

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:54 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetClusterManifest",

We are enforcing a Noun_Verb pattern for all the operations in swagger specs. Can you please follow that pattern? This should ideally be `ClusterManifest_Get`

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:11 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetNodeList",

Nodes_List -> translates to `client.nodes.list()` makes it a more usable client api and provides a better intellisense experience

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:85 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "name": "continuation-token",

What does the continuation token do over here? What value should the user put over here? Basically how can the user get this value?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:94 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetNode",

`Nodes_Get`

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:116 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "name": "continuation-token",

Is the continuation token actually required while getting more information about a particular entity?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:132 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The node",

Can we have more meaningful description? More info about the type of node.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:141 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by msjeffreychen** [comment]
As we mentioned in the earlier code review, the reason we use VerbNoun is because our users are familiar with powershell, and powershell is using this convention.

**Comment by amarzavery** [comment]
>             "description": "The node",

A more meaningful description. What kind of value should the user accept in the string type of the response?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:169 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The node of the disable",

"description": "The node ~~of the~~ **to** disable"

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:194 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>                   "type": "integer"

missing description. and please provide meaningful description. What value should the user provide? Is 10000 a valid value as it is an integer? How does an integer value translate to the intent for deactivation? It would be nice if that is described in the description to make this more user friendly.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:200 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
@msjeffreychen - Powershell has got nothing to do with the name of the operations in the swagger spec. We are generating an SDK from the swagger spec. That SDK/client should look more meaningful and sensible. This client is then consumed by Powershell and CLI where you can have a naming convention that makes sense in that paradigm. 

Does that make sense?

**Comment by amarzavery** [comment]
>         "operationId": "GetClusterManifest",

Please add a description for every operation. 

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:11 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
@msjeffreychen - General comment before I review further:

- Please follow the instructions and snapshots over [here](https://github.com/Azure/openapi-lint-extension#installation-instructions) to install the linter and make sure you resolve all the warnings and errors.
- Please read the good swagger patterns that we recommend from [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) and make sure that they are followed when you author the swagger

**Comment by amarzavery** [comment]
>         "operationId": "RemoveNodeState",

- missing description for every operation


---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:221 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The filter of the events health state",

Can you give an example over here? that will help the customer. You may want to look at [this extension](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-odata). It will generate better C# code.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:264 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetNodeHealth",

NodeHealth_Get

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:249 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedApplicationList",

DeployedApplications_List

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:284 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedApplication",

DeployedApplications_Get

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:315 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedApplicationHealth",

DeployedApplications_GetHealth

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:350 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "type": "string",

Shouldnt this parameter also have `"x-ms-skip-url-encoding": true` as mentioned for applicationName for GetDeployedApplicationHealth

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:331 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The filter of the deployed service packages health state",

Providing an example in the description and also letting them know what operators (and, or, eq )do you support would be helpful to the customer.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:380 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetNodeLoadInformation",

Node_GetLoadInformation

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:400 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedCodePackage",

DeployedCodePackage_Get

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:428 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedReplica",

DeployedReplica_List

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:467 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetDeployedReplicaDetail",

DeployedReplica_Get

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:506 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>                 "SourceId": {

same comment as in the first operation. A separate model definition and refernce it here and make sure **meaningful** description for all the properties is provided everywhere

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:697 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>                   "type": "string"

should this be an integer? Do you expect the user to provide "100000 ms"? Please clarify it in the description.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:710 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>                   "type": "string"

Should this be an integer  type?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:713 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "SendDeployedApplicationHealthReport",

DeployedApplicationHealthReport_Send

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:737 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>               "properties": {

same as above

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:764 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "SendDeployedServicePackageHealthReport",

same as above

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:805 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetApplicationTypeList",

ApplicationTypes_List

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:880 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The application type",

List of application types

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:891 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>               "type": "object",

same as above

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1068 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The application",

List of Applications

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1152 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "name": "continuation-token",

is this really required for getting info about a single application?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1182 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetServiceList",

Services_ListByApplication

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1201 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetApplication",

Application_Get

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1165 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetApplicationList",

Applications_List

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1134 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetService",

Service_GetByApplication

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1233 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>           "application/json"

ServiceGroupDescription_GetByService

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1272 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "GetServiceGroupMember",

ServiceGroupMember_GetByService

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1307 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>     "/Applications/{applicationName}/$/GetServices/{serviceName}/$/GetServiceGroupMembers": {

GetServiceGroupMembers -> Is this getting one or more?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1305 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>               "type": "object",

same as above.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1588 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "NewService",

Service_Create

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1519 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "operationId": "NewServiceFromTemplate",

Service_CreateFromTemplate

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:1569 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "description": "The type of the partition key",

Are there a finite set of values for the keytype? Should this be made an enum? 

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2107 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>               "type": "object",

same as above. I have seen this schema repeated n number of times as a body object in different operations. This could be defined once and referenced everywhere thereby reducing the number of models that are pretty much the same type

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2189 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "Name": {

Please provide the description for all the properties.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2813 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by msjeffreychen** [comment]
After I renamed GetApplication to Application_Get, I got a tons of this warning below. Is there anyway workaround it? I really would like to keep all the APIs consistent names, and not some with "Operations" at the end, some not.

WARNING: Client operation with name 'application' was renamed to 'applicationOperations' because it conflicts with following entities: 
application (already used in Schema definition)
Please consider changing your swagger specification to avoid naming conflicts.

**Comment by amarzavery** [comment]
>         "Type": {

If there is a large list which may still grow then please provide link to a doc in the description. If the set is a finite one then can this be made an enum (Also take a look at the x-ms-enum extension from the extensions page in the documentation folder of this repo?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2819 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
Name it Applications_Get (Noun in plural form). Please read the recommended patterns for designing swagger from the documentation folder and please run the swagger through the linter

**Comment by amarzavery** [comment]
>         "HealthState": {

Can this also have a finite set of values? Is this an enum candidate?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2834 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "NodeStatus": {

Enum candidate?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2828 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "NodeDeactivationInfo": {

Please define a complex object as a separate definition and refer it here. That keeps it cleaner

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2857 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>             "NodeDeactivationStatus": {

What could be the possible integer values for the above two properties? Can I say 74 and 98 and will they be valid? The intention over here is to provide as much information to the customer via description with examples (and making properties an enum, if possible) so that the customer does not have to do trial and error. Imagine yourself writing an app against this API the way it is currently described in the swagger doc. How easy it will be for you to write an app?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2863 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>           "type": "string"

should you add `"format": "date-time"`? By UTC do you mean in ISO8601 format? If so please clarify it in the description

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2895 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "LastOkTransitionAt": {

Looks like this will provide a timestamp value. If so then please refer to the comments made above.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2903 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "MaxPercentUnhealthyPartitionsPerService": {

Are there any constraints like the maximum value or minimum value, etc for "MaxPercentUnhealthyPartitionsPerService" and "TotalCount" that the service allows. If so then you should specify them. Please take a look at [this link](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-fields-2) and scroll a little up to see the supported constraints in swagger.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:2963 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>         "Status": {

enum candidate?

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:3353 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by amarzavery** [comment]
>       "properties": {

General comment: Are there any readOnly properties in your model definitions? If so then you need to accurately describe them with `"readOnly": true`.

---
Refers to: servicefabric/2016-01-28/swagger/servicefabric.json:4817 in 0baff2a. [](commit_id = 0baff2ae9330b47348159b43071b2ccd8f198564, deletion_comment = False)

**Comment by msjeffreychen** [comment]
I have adjusted the spec.
"description" is a actual field on the wire.
"continuation-token" is a field to support pagination. It is just a id.
Thanks.

**Comment by amarzavery** [comment]
@msjeffreychen - I understand that. "continutation-token" would make sense in a pageable list operation where the service is returning a list.
However, what sense would it make for a "get" operation where you are returning more information about an object. 
- [Applications_Get which returns information about an Application](https://github.com/msjeffreychen/azure-rest-api-specs/blob/ed07dc99cc0f41d4b5e5d7d38a689ac9a80b8a2e/servicefabric/2016-01-28/swagger/servicefabric.json#L1354)
- [ApplicationManifests_Get which returns information about an ApplicationManifest](https://github.com/msjeffreychen/azure-rest-api-specs/blob/ed07dc99cc0f41d4b5e5d7d38a689ac9a80b8a2e/servicefabric/2016-01-28/swagger/servicefabric.json#L1177)
- [Nodes_Get which returns information about a particular Node](https://github.com/msjeffreychen/azure-rest-api-specs/blob/ed07dc99cc0f41d4b5e5d7d38a689ac9a80b8a2e/servicefabric/2016-01-28/swagger/servicefabric.json#L135)

> How will the above 3 operations be pageable operations?

**Comment by amarzavery** [comment]
Can you also provide meaningful description for model properties?

**Comment by msjeffreychen** [comment]
I have removed the continuation-token you requested.
Could you make an exception to let me check-in as is on the description part? We have created a bug 7303649 to add detail description as tracking. We need component owners to add descriptions. We really need to get the CLI in by code complete date 9/21.

**Pull request merged**
