### PR TITLE
Swagger changes for App Gw Server Variables APIs

### PR DESCRIPTION
**Pull request by nirkum18**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
why we need this branch? If it has same functionality a 10-01? please revert in this case

**Comment by MikhailTryakhov** [comment]
do we need to create any examples?

**Comment by nirkum18** [comment]
> why we need this branch? it need to be able in 2018-11-01??

Yes the respective changes will be pushed in 2018-11-01 version. So created the branch with this version.

**Comment by nirkum18** [comment]
> do we need to create any examples?

I'm not aware of examples. What kind of examples do we need to create? Can you please point out any similar changeset with examples.

**Comment by nirkum18** [comment]
> do we need to create any examples?

Examples have been added. Waiting to merge these changes with network-november-branch.

**Review by KrisBash — COMMENTED** [review]
LGTM for ARM

**Comment by veronicagg** [comment]
@nirkum18 was this PR reviewed by ADX swagger reviewers? The ADX swaggers reviewers team is the one approving and merging PRs for the December-network-release branch, so I'm not sure how this one went through, the branch is usually protected. If you did not get a review from the SDK team, could you please sync with @MikhailTryakhov on this merge? FYI - @jianghaolu , @mzehgir @salameer

**Pull request merged**
