### PR TITLE
[Batch] Data plane: Update 2021-06-01.14.0 API to consistently use descriptions instead of titles

### PR DESCRIPTION
**Pull request by dpwatrous**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/dpwatrous/azure-rest-api-specs/dev-batch-Microsoft.Batch-2021-06-01.14.0...master/).

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by dpwatrous** [comment]
This is a documentation update only. We had been using the 'title' and 'description' fields inconsistently, which was causing some strange issues depending on where those values were used.

For example, the Python SDK generates docstrings on description only, while the doc site concatenates the title and description together.

This change also aligns with how other services use the field (I used the compute swagger for reference and spot checked a few others).

Related management plane PR: https://github.com/Azure/azure-rest-api-specs/pull/15243

**Comment by dpwatrous** [comment]
Note that the JS SDK failure isn't related to this PR. It's a pre-existing issue that we need to fix separately.

**Comment by matthchr** [comment]
> This is a documentation update only. We had been using the 'title' and 'description' fields inconsistently, which was causing some strange issues depending on where those values were used.
For example, the Python SDK generates docstrings on description only, while the doc site concatenates the title and description together.

FWIW, if that's what the Python SDK is doing it's doing it wrong IMO (@lmazuel, @annatisch). When we wrote it, it combined them like the other SDKs I'm pretty sure.

The [JSON reference says](https://json-schema.org/understanding-json-schema/reference/generic.html):
> The title and description keywords must be strings. A “title” will preferably be short, whereas a “description” will provide a more lengthy explanation about the purpose of the data described by the schema.

Which is exactly how Batch is using them I think?

**Comment by dpwatrous** [comment]
@matthchr First of all, thanks for taking a look at this PR on a weekend!

That's a good point about the summary and remark fields in C#, although looking at other C# SDKs that don't have title fields, I only see `<summary>`, not remarks. I'm guessing it's smart enough to map `<summary>` to description if a title doesn't exist.

The main thing that convinced me that we should change this, is I don't see any other service using the `title` field in quite the same way as Batch. ~30% of the results of doing a global search for `"title"` are for Batch, and most other services use the title field at the top of the file and nowhere else (or in very limited cases).

Azure Machine Learning and NetApp do have a lot of title fields as well, but they are much shorter. Just to pick a couple of examples:

Batch:
```
"id": {
  "type": "string",
  "title": "The ARM resource identifier of the Shared Image Gallery Image. Compute Nodes in the Pool will be created using this Image Id. This is of the form /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/galleries/{galleryName}/images/{imageDefinitionName}/versions/{versionId}.",
  "description": "This property is mutually exclusive with other properties. The Shared Image Gallery image must have replicas in the same region as the Azure Batch account. For information about the firewall settings for the Batch node agent to communicate with the Batch service see https://docs.microsoft.com/en-us/azure/batch/batch-api-basics#virtual-network-vnet-and-firewall-configuration."
}
```

Azure Machine Learning:
```
"userAccountCredentials": {
  "title": "User account credentials.",
  "description": "Credentials for an administrator user account that will be created on each compute node.",
  "$ref": "#/definitions/UserAccountCredentials"
},
```

The way I'm interpreting the title field is as more of a friendly name (`vmSize -> "Virtual Machine Size"`) than a short description (`vmSize -> "The virtual machine size to use across all nodes in the pool"`). I'd love to have the API/SDK teams weigh in on this, though, as it's not completely clear to me from the Swagger documentation.

PS: IMO this is mostly orthogonal to this PR and the 'right' way to use title and description, but there may be an autorest issue here as well, since it seems like the Python SDK generation previously did concatenate title & description. We are using an older version of autorest core to get around another regression with readme.md file processing, so it's possible it's been fixed in newer releases.

**Comment by matthchr** [comment]
Interesting -- yeah I saw them more as proxies for Swaggers `summary` and `description` on operations, which is summarized [here](https://swagger.io/specification/):
>summary | string | A short summary of what the operation does.
description | string | A verbose explanation of the operation behavior. CommonMark syntax MAY be used for rich text representation.

You said:
> I'd love to have the API/SDK teams weigh in on this, though, as it's not completely clear to me from the Swagger documentation.

The issue I think is that Swagger just says: "The definitions section adheres to the JSON schema" so it doesn't really speak to it that well. I agree though it would be good to have somebody from the SDK team who is in the know weigh in.

> since it seems like the Python SDK generation previously did concatenate title & description

Yes, every supported language either concatenated them or put each one into a separate "section" of the docs. If I recall correctly Python has the notion of the first line of a comment being a short form description and then the subsequent lines being "longer form", as you can see in the section on [multi-line doc strings](https://www.python.org/dev/peps/pep-0257/#id17). This again matches nicely to `title` + `description` and without such understanding in the Swagger there's not a good way to craft "correct" strings (because Python wants a single-line docstring to be short as per the PEP).

Full disclosure: I'm the one who added this handling into all the supported languages [back in 2016](https://github.com/Azure/autorest/pull/1163). The fact other services aren't making heavy use of `title` may just be because it hasn't been advertised well.

**Comment by matthchr** [comment]
I also just merged a PR in AKS making use of `title` in more places for what it's worth: #4957

**Comment by dpwatrous** [comment]
For what it's worth I can see the value in certain cases where it's useful to have a short description displayed separately from additional information. I'm fine keeping the split, but I'd like to get some official guidance from the current maintainers on support and usage (for example: should title and description be written so they can be displayed standalone, or should they be used like in Batch where they're written to be concatenated/displayed together?).

I'm just worried about defining our Swagger in a way that's different from common usage. The fact that nobody else has raised this issue yet, despite the fact that (from what I can tell at least) the Python generator has behaved like this for many months and many releases, says to me that we're an edge case here.

I did go ahead and open an issue with the Python autorest extension as well: https://github.com/Azure/autorest.python/issues/978

**Review by paterasMSFT — APPROVED** [review]

**Comment by dpwatrous** [comment]
So this is a pretty big issue with the Java SDK as well. Here's one example JavaDoc string, but there are plenty to choose from:

**Swagger**
```
"version": {
  "type": "string",
  "title": "The version of the application to deploy. If omitted, the default version is deployed.",
  "description": "If this is omitted on a Pool, and no default version is specified for this application, the request fails with the error code InvalidApplicationPackageReferences and HTTP status code 409. If this is omitted on a Task, and no default version is specified for this application, the Task fails with a pre-processing error."
}
```

**JavaDoc with title and description**
```
/**
 * Set if this is omitted on a Pool, and no default version is specified for this application, the request fails with the error code InvalidApplicationPackageReferences and HTTP status code 409. If this is omitted on a Task, and no default version is specified for this application, the Task fails with a pre-processing error.
```

**JavaDoc with only description**
```
/**
 * Set the version of the application to deploy. If omitted, the default version is deployed. If this is omitted on a Pool, and no default version is specified for this application, the request fails with the error code InvalidApplicationPackageReferences and HTTP status code 409. If this is omitted on a Task, and no default version is specified for this application, the Task fails with a pre-processing error.
```

While I don't mind using title and description like this, it's clearly not the common usage and it's not a battle I really want to fight. Unless this is the direction the SDK/API teams want us to go with Swagger, I'd rather adopt the common usage and improve the experience for our customers.

**Comment by dpwatrous** [comment]
Based on the results of the discussion in https://github.com/Azure/autorest.python/issues/978 I'm going to close this PR for now.

**Pull request closed without merging**
