### PR TITLE
[HDInsight] Fixed OMS operations to be marked as long-running.

### PR DESCRIPTION
**Pull request by wawon-msft**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by olydis — COMMENTED** [review]
@wawon-msft This is just a bugfix, i.e. the service has always implemented these operations as long running? What's the terminal status code for these operations? I'd have expected 200 or 201 for the PUT and 200 or 204 for the DELETE. Did you forget to model these? 🙂

**Comment by wawon-msft** [comment]
@olydis This is a bug fix, the service had implemented these operations as long-running. As of today, the terminal status for PUT and DELETE is 202 (Accepted).

**Comment by olydis** [comment]
> I've added 200 as a possible response to fix the violation for now, but I'll make the service fix as part of the next breaking change.

Note that this will influence generated code! If your service does not implement it like that, then it makes no sense to model it differently. Essentially the violation is of the *service*, so you didn't fix it but muted it, leading to possibly broken SDKs.

**Comment by wawon-msft** [comment]
That's a fair point. However, what's the recommended course of action in this case? Until the service is fixed, it seems like either the spec must be inaccurate or we'll have to live with the SDK violation.

**Comment by olydis** [comment]
Accurate Swagger is the first priority. You'll have to live with the violation until it's fixed (or request exception from ARM that your service is allowed to have this behavior forever). :)

**Comment by wawon-msft** [comment]
Sounds good. I also prefer an accurate spec over masked violations. I've updated the PR accordingly.

**Review by olydis — APPROVED** [review]

**Pull request merged**
