### PR TITLE
Add job suspend resume

### PR DESCRIPTION
**Pull request by scrappywyrm**
This PR has all changes from this closed one https://github.com/Azure/azure-rest-api-specs/pull/29788

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by mentat9** [comment]
@bgashirabake - Please select one of the templates to create/update your PR, then fill out the intake form.

**Comment by bgashirabake** [comment]
> @bgashirabake - Please select one of the templates to create/update your PR, then fill out the intake form.

@mentat9 thanks! I selected the Control Plane (ARM) API template but didn't see the page render with the flow diagram like the abandoned PR i linked at the top. additionally, i'm unable to find the intake form

is this the form:
image

any insights on how to proceed? thank you!

**Comment by bgashirabake** [comment]
pr/ WaitForArmFeedback

**Review by jijohn14 — APPROVED** [review]

**Pull request merged**
