### PR TITLE
appplatform stable API 2023-12-01

### PR DESCRIPTION
**Pull request by yuwzho**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - Commit features in previous Preview API version (https://github.com/Azure/azure-rest-api-specs/blob/main/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2023-11-01-preview/appplatform.json) into Stable API version. It doesn't introduce new features.

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by sjanamma** [comment]
>               "$ref": "#/definitions/ContainerRegistryResource"

Secrets cannot be returned via GET, PUT,PATCH operations.
[https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html#rpc012-secret-property-semantics-are-followed](https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html#rpc012-secret-property-semantics-are-followed)

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:2200 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by sjanamma** [comment]
>           "description": "Enable Single Sign-On in app level.",

ARM recommends enums over booleans for future proof APIs.

Standard guidance is: replace boolean/switch properties with a more meaningful enum whenever possible.
A boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated].

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:13484 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by sjanamma** [comment]
>     "AcceleratorBasicAuthSetting": {

This model is not being used anywhere?

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:14122 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by sjanamma** [comment]
>     "AcceleratorPublicSetting": {

not used?

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:14103 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by sjanamma** [comment]
PR has breaking changes that have not been approved yet. Please get a breaking changes approval from Azure Breaking Changes Reviewers <azbreakchangereview@microsoft.com> and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

**Comment by yuwzho** [comment]
> > ```
> >           "$ref": "#/definitions/ContainerRegistryResource"
> > ```
> 
> Secrets cannot be returned via GET, PUT,PATCH operations. They can only be retrived via POST actions https://armwiki.azurewebsites.net/api_contracts/guidelines/rpc.html#rpc012-secret-property-semantics-are-followed
> 
> This is a must fix
> 
> Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:2200 in [4782e8d](https://github.com/Azure/azure-rest-api-specs/commit/4782e8d8ea127c25273c0cc5fd9818175de8847b). [](commit_id = [4782e8d](https://github.com/Azure/azure-rest-api-specs/commit/4782e8d8ea127c25273c0cc5fd9818175de8847b), deletion_comment = False)

This is a defined nested resource with `provisioningState` and other properties. Currently, the Credential referenced here we only support Basic Auth. We marked the password as a secret https://github.com/Azure/azure-rest-api-specs/blob/b5b262b42eae83d77e90838479eae25662c8e736/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json#L8834-L8843

**Comment by yuwzho** [comment]
> > ```
> > "AcceleratorBasicAuthSetting": {
> > ```
> 
> This model is not being used anywhere?
> 
> Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:14122 in [b5b262b](https://github.com/Azure/azure-rest-api-specs/commit/b5b262b42eae83d77e90838479eae25662c8e736). [](commit_id = [b5b262b](https://github.com/Azure/azure-rest-api-specs/commit/b5b262b42eae83d77e90838479eae25662c8e736), deletion_comment = False)

All of `AcceleratorPublicSetting`, `AcceleratorBasicAuthSetting` and `AcceleratorSshSetting` are polymorphism of `AcceleratorAuthSetting` referenced by `AcceleratorGitRepository`.

**Comment by yuwzho** [comment]
> PR has breaking changes that have not been approved yet. Please get a breaking changes approval from Azure Breaking Changes Reviewers [azbreakchangereview@microsoft.com](mailto:azbreakchangereview@microsoft.com) and ARM can review the changes afterwards. Once you have the approval, please remove the "ARMChangesRequested" label from the PR to make the PR visible to the ARM reviewers.

We already got the approvement from the breaking change review board and Jeffrey added the `BreakingChangeApproved` label here

**Comment by visingla-ms** [comment]
>             "description": "Success."

[ARMBlockingComment]
Please add response schema here, as 200 response can't have empty response body.

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:522 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppPlatform/Spring/{serviceName}/DevToolPortals": {

It should be in camelCase i.e., devToolPortals here.

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:1929 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "AcceleratorBasicAuthSetting": {

Please address this.

---
In reply to: [1837283084](https://github.com/Azure/azure-rest-api-specs/pull/26770#issuecomment-1837283084) [](http://example.com/codeflow?ancestors=1837283084)

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:14122 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "AcceleratorPublicSetting": {

Please address this.

---
In reply to: [1837283161](https://github.com/Azure/azure-rest-api-specs/pull/26770#issuecomment-1837283161) [](http://example.com/codeflow?ancestors=1837283161)

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:14103 in b5b262b. [](commit_id = b5b262b42eae83d77e90838479eae25662c8e736, deletion_comment = False)

**Comment by yuwzho** [comment]
> > ```
> >       "type": "string"
> > ```
> 
> Is it secret?
> 
> Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:13050 in [b5b262b](https://github.com/Azure/azure-rest-api-specs/commit/b5b262b42eae83d77e90838479eae25662c8e736). [](commit_id = [b5b262b](https://github.com/Azure/azure-rest-api-specs/commit/b5b262b42eae83d77e90838479eae25662c8e736), deletion_comment = False)

Same above, it is not a secret but an ARM resource id

**Comment by yuwzho** [comment]
> Please get SDK Breaking changes reviewed from SDK Reviewers.

@msycc and the guideline told me I should get the ARM signoff first and then head for them.

**Comment by visingla-ms** [comment]
>             "description": "Success."

Yes, my bad earlier. If Async Post doesn't have any response body to return, just use 202, other response codes such as 200 or 204 are not needed, please remove 204 also from all newly added Async Post APIs. 

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:522 in 63b1c91. [](commit_id = 63b1c910400cb528233381a3fa5b78e84eb2f565, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "description": "Resource Id of the certificate",

If it is an ARM resource id, use this here: [https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details).

---
Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:13049 in 63b1c91. [](commit_id = 63b1c910400cb528233381a3fa5b78e84eb2f565, deletion_comment = False)

**Comment by yuwzho** [comment]
> > ```
> >     "caCertResourceId": {
> > ```
> 
> If it is an ARM resource id, use this here: https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-arm-id-details.
> 
> Refers to: specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2023-12-01/appplatform.json:9726 in [4782e8d](https://github.com/Azure/azure-rest-api-specs/commit/4782e8d8ea127c25273c0cc5fd9818175de8847b). [](commit_id = [4782e8d](https://github.com/Azure/azure-rest-api-specs/commit/4782e8d8ea127c25273c0cc5fd9818175de8847b), deletion_comment = False)

Thanks, updated.

**Comment by yuwzho** [comment]
I removed the SuppressionReviewRequired label because reverting the README change

**Review by ms-zhenhua — APPROVED** [review]

**Pull request merged**
