### PR TITLE
Review request for Microsoft.ContainerService/aks to add version preview/2024-04-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by razvanbadea-msft** [comment]
>       "description": "Defines access to special link local addresses (IMDS and wire server) for pods with hostNetwork=false. If not specified, the default is 'IMDS'.",

You should expand acronyms in descriptions

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4922 in 984bbe4. [](commit_id = 984bbe4e5c922b7e9f29849e76c504ef0f90d973, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "hasBreakingChanges": {

Replace boolean/switch properties with a more meaningful enum whenever possible. 

A boolean will forever have two valid values (true or false). Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated].

In this case for example you could have a upgradeChangeType with values that could be added apart from the [BreakingChanges, None] in the future if other type of changes could appear

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:10087 in 984bbe4. [](commit_id = 984bbe4e5c922b7e9f29849e76c504ef0f90d973, deletion_comment = False)

**Comment by razvanbadea-msft** [comment]
>         "autoscale": {

You should you use plural or rename the array properties fpr this properties to be more suggestive

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4188 in 984bbe4. [](commit_id = 984bbe4e5c922b7e9f29849e76c504ef0f90d973, deletion_comment = False)

**Comment by wenxuan0923** [comment]
> > ```
> >     "autoscale": {
> > ```
> 
> You should you use plural or rename the array properties fpr this properties to be more suggestive
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4188 in [984bbe4](https://github.com/Azure/azure-rest-api-specs/commit/984bbe4e5c922b7e9f29849e76c504ef0f90d973). [](commit_id = [984bbe4](https://github.com/Azure/azure-rest-api-specs/commit/984bbe4e5c922b7e9f29849e76c504ef0f90d973), deletion_comment = False)

Hi @razvanbadea-msft thanks for your review. 

Yes, I agree plural will be a better choice here. However, the new "autoscale" field is the counterpart to the existing "manual" property, which is also an array. (see code here: https://github.com/Azure/azure-rest-api-specs/blob/5506bda46d28441b272dacfd2009fad8d925f875/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json#L4180C7-L4187C11) I believe it's better to keep them consistent here.

**Comment by HuShaoRu** [comment]
> > ```
> >     "hasBreakingChanges": {
> > ```
> 
> Replace boolean/switch properties with a more meaningful enum whenever possible.
> 
> A boolean will forever have two valid values (true or false). Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [Enabled, Disabled, Suspended, Deallocated].
> 
> In this case for example you could have a upgradeChangeType with values that could be added apart from the [BreakingChanges, None] in the future if other type of changes could appear
> 

I think we only need true/false here, enum is vague and not necessary. If we indeed need more options in the future, we can add a new field. Now we have no idea of any other options except for BreakingChanges and NoBreakingChanges.

**Comment by FumingZhang** [comment]
> > ```
> >   "description": "Defines access to special link local addresses (IMDS and wire server) for pods with hostNetwork=false. If not specified, the default is 'IMDS'.",
> > ```
> 
> You should expand acronyms in descriptions
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4922 in [984bbe4](https://github.com/Azure/azure-rest-api-specs/commit/984bbe4e5c922b7e9f29849e76c504ef0f90d973). [](commit_id = [984bbe4](https://github.com/Azure/azure-rest-api-specs/commit/984bbe4e5c922b7e9f29849e76c504ef0f90d973), deletion_comment = False)

Suggestions applied in #29272

**Comment by gary-x-li** [comment]
>           "maximum": 1000,

Why are the limits removed? Is there any validation logic in place to reject requests with an extremely large number?

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4202 in fa06b45. [](commit_id = fa06b450bb7f69bf208149a3b6635d80d53421c9, deletion_comment = True)

**Comment by wenxuan0923** [comment]
> > ```
> >       "maximum": 1000,
> > ```
> 
> Why are the limits removed? Is there any validation logic in place to reject requests with an extremely large number?
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2024-04-02-preview/managedClusters.json:4202 in [fa06b45](https://github.com/Azure/azure-rest-api-specs/commit/fa06b450bb7f69bf208149a3b6635d80d53421c9). [](commit_id = [fa06b45](https://github.com/Azure/azure-rest-api-specs/commit/fa06b450bb7f69bf208149a3b6635d80d53421c9), deletion_comment = True)

Yes, we have validation on the server side to reject the request if count is larger than 1000. The reason we are removing it here is actually because of the `minimum` value - it can be `0` or `1` - depends on the agentpool type, putting `0` here isn't accurate so I'm removing it.

**Comment by FumingZhang** [comment]
Releasing the ARM manifest changes, which are expected to be completed this Saturday (06/08), this PR could be merged after that.

**Comment by FumingZhang** [comment]
> Releasing the ARM manifest changes, which are expected to be completed this Saturday (06/08), this PR could be merged after that.

Manifest release is completed.

**Review by razvanbadea-msft — APPROVED** [review]

**Pull request merged**
