### PR TITLE
extract SkuTier as seperate definition for common-types/v3.json

### PR DESCRIPTION
**Pull request by zhenglaizhang**
This is per request from service team (https://github.com/Azure/azure-rest-api-specs/issues/15662#issue-971839784) and I did a check on python track2 it's not a breaking change in PR https://github.com/Azure/azure-rest-api-specs/pull/15876. 

And need SDK owners review to check if it's a SDK breaking change

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@zhenglaizhang Do you need review from ARM?

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by zhenglaizhang** [comment]
@msyyc @qiaozha @fengzhou-msft @ArcturusZhang could you help take a look from SDK perspective?

**Comment by weidongxu-microsoft** [comment]
One question not related to this change.

Why use "allOf"?
https://github.com/Azure/azure-rest-api-specs/blob/474979838da076b498f0dedf3986b88a0d38ffe0/specification/common-types/resource-management/v3/types.json#L169-L189

**Review by ArcturusZhang — APPROVED** [review]

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang Do you need review from ARM?

no need to do ARM review,

**Comment by zhenglaizhang** [comment]
> One question not related to this change.
> 
> Why use "allOf"?
> https://github.com/Azure/azure-rest-api-specs/blob/474979838da076b498f0dedf3986b88a0d38ffe0/specification/common-types/resource-management/v3/types.json#L169-L189

good catch, ref should be better here.

**Review by dw511214992 — APPROVED** [review]

**Comment by zhenglaizhang** [comment]
.net/python sdk owners are also ok with this change.

**Comment by zhenglaizhang** [comment]
@forteddyt I merged the PR, so you can try to reference it in v3 common types.json

**Pull request merged**
