### PR TITLE
Compute semantic violation fixes

### PR DESCRIPTION
**Pull request by veronicagg**
Trying to clean semantic validation errors from compute specs. Let me know what you think about the changes, I'd like to make this non-invasive, if you have concerns, please let me know.
There were equivalent paths defined, mainly due to availabilitySetName and name used as variables, and vmScaleSetName and name used as variables, and defining a set of operations each. I put them together, using only one variable name, and included x-ms-client-name, so that the name of the variable in the wire keeps being "name" for the cases where it was that way.

### CODE REVIEW

**Comment by lmazuel** [comment]
@veronicagg So far so good for what I see :)
Python build fail, waiting for this https://github.com/Azure/azure-rest-api-specs/pull/1956

**Review by jianghaolu — APPROVED** [review]

**Comment by veronicagg** [comment]
@hyonholee could you take a look? are you ok with me merging this change?
FYI - @yugangw-msft

**Comment by hyonholee** [comment]
@veronicagg  Sorry for late reply.  Could you sync with Azure/current again and update the PR?  Thanks.

**Comment by veronicagg** [comment]
@hyonholee I don't see any merge conflicts being reported in Github, what updates would you need me to take?

**Comment by marstr** [comment]
When I resolved conflicts, there were no longer any changes represented in this PR. I assume they were already merged in via another PR. When I pushed, GitHub automatically closed this PR.

**Pull request closed without merging**
