### PR TITLE
Update some crypto documentation.

### PR DESCRIPTION
**Pull request by vcolin7**
Added a disclaimer about the use of CBC algorithms for decryption. Updated documentation to indicate initialization vectors should be cryptographically random and non-repeating.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [X] Other, please clarify: Update documentation.
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  N/A
  3. When do you expect to publish the swagger? Please provide date or, the date is not yet available, the month.
  N/A
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of JS
      - [X] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [X] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [X] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by heaths — APPROVED** [review]
Wouldn't you want the same text for `encrypt` as well?

**Comment by vcolin7** [comment]
> Wouldn't you want the same text for `encrypt` as well?

@heaths At first glance, I don't think so; it feels out of place to mention decryption when all of the above text has been talking about encryption.

**Comment by heaths** [comment]
Yes, you'd want to change the wording slightly, but you need a cryptographically random IV to encrypt and to supply the same IV to decrypt, so you really need to mention that for encryption first. 😉

**Comment by vcolin7** [comment]
> Yes, you'd want to change the wording slightly, but you need a cryptographically random IV to encrypt and to supply the same IV to decrypt, so you really need to mention that for encryption first. 😉

The IV docs got updated exclusively under `KeyOperationParameters`, which is operation agnostic. The update specific to decryption is about ensuring the integrity of the ciphertext.

**Pull request merged**
