### PR TITLE
[Microsoft.Advisor] Add metadata api

### PR DESCRIPTION
**Pull request by mudit794**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/6029 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/6029/commits/2872837e954708b45798665752deba038e01765a

**Comment by mudit794** [comment]
Can some one provide pointer on how to fix SDK node failure. Thanks

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
https://github.com/Azure/azure-rest-api-specs/pull/5826/files#diff-d0283661446defbd1a9caf436b028f0cR787
Have you considered having common error response align with what is documented on ARM guidelines
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content

**Comment by shahabhijeet** [comment]
@amarzavery is the Node failure of any concern here. Can you take look and confirm if this failure can be/cannot be ignored
https://dev.azure.com/azure-sdk/public/_build/results?buildId=26159

**Comment by amarzavery** [comment]
Please ignore the nodejs failure and move ahead.

**Comment by shahabhijeet** [comment]
@mudit794 I have not heard back from you regarding aligning to common schema for error response.

**Comment by mudit794** [comment]
> @mudit794 I have not heard back from you regarding aligning to common schema for error response.



> @mudit794 I have not heard back from you regarding aligning to common schema for error response.

Updated error response.

**Review by shahabhijeet — APPROVED** [review]

**Comment by shahabhijeet** [comment]
Node sdk is a know issue and we have travis wide issue. So this PR is ok to be merged.

**Pull request merged**
