### PR TITLE
MetricAlert swagger fix

### PR DESCRIPTION
**Pull request by hovsepm**
Since enum types **were not** declared as type=string generation on C# and Java side (checked in Fluent code) was producing object types instead of Enums or ExpandableStringEnum.

### CODE REVIEW

**Comment by hovsepm** [comment]
@jhendrixMSFT  waiting for the owner team sign-off.

**Comment by hovsepm** [comment]
@jhendrixMSFT yes we do. They are kind of slow.

**Comment by jhendrixMSFT** [comment]
@hovsepm Any update?  Do we need to tag somebody for the review?

**Comment by hovsepm** [comment]
@jhendrixMSFT I sent them couple of emails already. Please reassign it to me if you are ok with the changes (I was aware about breaking change issue that is why am waiting for the owner team to take actions).

**Comment by jhendrixMSFT** [comment]
@hovsepm The changes LGTM, but yeah I'll reassign to you since you're working with the owning team.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by hovsepm** [comment]
Closing due to 0 response from owner team.

**Pull request closed without merging**
