### PR TITLE
add cli.md and examples for compute

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by raych1** [comment]
Pipeline was not started.

**Comment by raych1** [comment]
@00Kai0 , please resolve the conflicts firstly.

**Comment by raych1** [comment]
@00Kai0 , please fix the CI check failures.

**Comment by raych1** [comment]
@00Kai0 , are you still working on this PR?

**Comment by 00Kai0** [comment]
@raych1 sorry, we are working on track2 sdk, maybe this pr needs more change.
You can add [DoNotMerge] tag for it. thx.

**Comment by raych1** [comment]
@00Kai0 , please remove `NotReadyForReview` label when it's ready for review.

**Comment by 00Kai0** [comment]
ok, thx

**Comment by raych1** [comment]
Hi @00Kai0 , it's been 2 months for this PR in opening state. I'm going to close this PR if you're not working on this.  You could re-open if it's ready for review.

**Comment by 00Kai0** [comment]
@raych1 yeah,ok. You can close it now. thx

**Pull request closed without merging**
