### PR TITLE
[Hub Generated] Review request for Microsoft.ContainerService to add version stable/2021-10-01

### PR DESCRIPTION
**Pull request by tyler-lloyd**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/tyler-lloyd/azure-rest-api-specs/dev-containerservice-Microsoft.ContainerService-2021-10-01...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? **Nov 2021**
  3. When do you expect to publish the swagger? **Nov 2021**
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by mentat9** [comment]
>         "ipFamilies": {

This seems better as an enum:
"ipFamilies": [ IPv4Only, IPv6Only, IPv4AndIPv6 ]. If you use modelAsString: true, you can add enum values in the future without moving to a new API version.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-10-01/managedClusters.json:3167 in 9283aee. [](commit_id = 9283aee8d32c7236adb1e51bf4a18c6a479f31cb, deletion_comment = False)

**Comment by tyler-lloyd** [comment]
> > ```
> >     "ipFamilies": {
> > ```
> 
> This seems better as an enum: "ipFamilies": [ IPv4Only, IPv6Only, IPv4AndIPv6 ]. If you use modelAsString: true, you can add enum values in the future without moving to a new API version.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-10-01/managedClusters.json:3167 in [9283aee](https://github.com/Azure/azure-rest-api-specs/commit/9283aee8d32c7236adb1e51bf4a18c6a479f31cb). [](commit_id = [9283aee](https://github.com/Azure/azure-rest-api-specs/commit/9283aee8d32c7236adb1e51bf4a18c6a479f31cb), deletion_comment = False)

Updated to enum but the expected values should be ["IPv4"] or ["IPv4", "IPv6"] or ["IPv6", "IPv4"]. So the parent type is still an array.

**Comment by zhenglaizhang** [comment]
Hi @tyler-lloyd  could you help fix the model validation errors https://github.com/Azure/azure-rest-api-specs/pull/16529/checks?check_run_id=4177966131 ?

**Comment by tyler-lloyd** [comment]
> Hi @tyler-lloyd could you help fix the model validation errors https://github.com/Azure/azure-rest-api-specs/pull/16529/checks?check_run_id=4177966131 ?

@zhenglaizhang are the validation rules more strict now? The 2 errors the ModelValidation check is reporting are not part of the changes I've made. The long running operation and the missing examples existed in previous versions (<= 2021-09-01).

**Comment by raych1** [comment]
> > Hi @tyler-lloyd could you help fix the model validation errors https://github.com/Azure/azure-rest-api-specs/pull/16529/checks?check_run_id=4177966131 ?
> 
> @zhenglaizhang are the validation rules more strict now? The 2 errors the ModelValidation check is reporting are not part of the changes I've made. The long running operation and the missing examples existed in previous versions (<= 2021-09-01).

@tyler-lloyd , yes, new rules added for model validation. Every operation needs to add examples and LRO header has to be returned per RPC spec.

**Review by zhenglaizhang — APPROVED** [review]

**Comment by zhenglaizhang** [comment]
Ignore the breaking change of go track1 as there is track2 result

**Pull request merged**
