### PR TITLE
Remove package-version from readme.nodejs.md and other small changes

### PR DESCRIPTION
**Pull request by ghost**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by RikkiGibson — APPROVED** [review]

**Comment by daschult** [comment]
@lmazuel Can you look at what is wrong with the python SDK generation? I haven't modified anything related to python in this PR, so I'm not sure why that would be causing a problem here.

**Review by lmazuel — APPROVED** [review]

**Comment by daschult** [comment]
@lmazuel I appreciate the approval, but I still can't merge my PR. Do you know how to fix the check or how to override the requirement?

**Comment by daschult** [comment]
@lmazuel Also, why does the push build pass but the pr build fail?

**Comment by lmazuel** [comment]
@daschult Timeout, you don't care in this context :)

**Comment by daschult** [comment]
@lmazuel The only reason I care is because it's blocking me from merging this PR.

**Comment by lmazuel** [comment]
@daschult Sorry, I thought you had admin right for force merge a PR, didn't realize this was blocking :(. Should read more closely.

**Pull request merged**
