### PR TITLE
modelerfour need the x-ms-api-version extention

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
modelerfour need the x-ms-api-version extention to notify it that this api-version does not need special handling (which happens for most api-version paramter),

https://github.com/Azure/autorest.modelerfour/issues/183

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Checking with Garrett on the ERROR in SDK build CI.

**Comment by weidongxu-microsoft** [comment]
Need to use latest v2 core 2.0.4417

**Comment by weidongxu-microsoft** [comment]
CI seems not getting correct version for autorest.core. It should be https://registry.npmjs.org/-/package/@microsoft.azure/autorest-core/dist-tags, not https://registry.npmjs.org/-/package/autorest/dist-tags

**Comment by NullMDR** [comment]
Known SDK Automation issue. Fix in progress.

**Comment by weidongxu-microsoft** [comment]
CI finally fixed `autorest --version=V2`

@Tiano2017 Would you help approve and merge? It is for codegen built on autorest core v3 and modelerfour.

**Comment by weidongxu-microsoft** [comment]
@njuCZ 

Should be ok to merge.

**Comment by weidongxu-microsoft** [comment]
@njuCZ

Any update?

**Comment by weidongxu-microsoft** [comment]
@njuCZ

Any update?

**Review by ChenTanyi — APPROVED** [review]

**Pull request merged**
