### PR TITLE
Add go config

### PR DESCRIPTION
**Pull request by marstr**
Batch two of adding Go SDK generation information. 

**Note:** Because this PR is not altering Swagger files, I've omitted the usual checklist that is included automatically in this repository.

### CODE REVIEW

**Comment by marstr** [comment]
To see what the generated code is, see https://github.com/Azure/azure-sdk-for-go/pull/812

**Comment by marstr** [comment]
@jhendrixMSFT / @mcardosos if one or both of you could take a look at this one quickly here, I'll get it merged in :)

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by mcardosos** [comment]
> ``` yaml $(tag) == 'schema-2014-04'

What are this tags?

---
Refers to: specification/sql/resource-manager/readme.md:162 in f8b9cb6. [](commit_id = f8b9cb65640d8058c027accbd0e0a559b1ed7eb9, deletion_comment = False)

**Comment by marstr** [comment]
Errr, digging a little I believe you are asking about the `schema` tags, @mcardosos? The short answer is I'm not sure, but we aren't generating from them today it seems, so I figured it was safe to wait to include them for another additive release.

**Pull request merged**
