### PR TITLE
fix AVS 2020-03-20 correctness errors for empty body and internet default

### PR DESCRIPTION
**Pull request by ctaggart**
## overview
- This fixes two [Swagger correctness](https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8187811/) errors.
- The 2020-03-20 API service is not changing.
- All existing generated SDKs will continue to work.

## details
1. It specifies the default value for `internet` as `Disabled`.
2. It removes a workaround for https://github.com/Azure/autorest.python/issues/653 that allowed an empty json body of `{}` to be sent using `@microsoft.azure/autorest.python@3`. Code generated with `@autorest/python@5` does not have that bug.  https://pypi.org/project/azure-mgmt-avs/ uses `@autorest/python@5` and does not have that bug. az-vmware-cli uses `@microsoft.azure/autorest.python@3` internally and will need to upgrade to `@autorest/python@5`. It can do so without changing the command-line interface.

---

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ctaggart** [comment]
I will review this with the breaking change board on Monday, November 9th.
https://msazure.visualstudio.com/One/_workitems/edit/8717220

**Comment by ctaggart** [comment]
The breaking change board has not yet approved this change. We will review again on Monday, November 16th.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by ctaggart** [comment]
Hi @leni-msft, this change was just approved from the breaking change board. Please merge.

**Pull request merged**
