### PR TITLE
remove legacy preview preview docs

### PR DESCRIPTION
**Pull request by datr93**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@datr93 

Any background? Is previous api-version not published, or depricated?

**Comment by datr93** [comment]
> @datr93
> 
> Any background? Is previous api-version not published, or depricated?

So we were developing the arm provider in private preview. We had to do breaking changes. So we updated the version with the changes. We haven't gone public with the older versions so It should be okay to remove. @allenjzhang suggested we should remove.

**Comment by datr93** [comment]
@weidongxu-microsoft whats the progress on this? Are we waiting on someone?

**Comment by datr93** [comment]
https://github.com/Azure/azure-resource-manager-schemas/blob/master/generator/README.md#onboarding-teams-to-autogeneration-pipeline

**Comment by majastrz** [comment]
>     "version": "2019-01-23-preview",

Are there any customers using this API version? Is it still supported on the backend? And I have the same question for the other API version you are removing.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2019-01-23-preview/desktopvirtualization.json:4 in ae0bb96. [](commit_id = ae0bb96704755e71b887ba72a5bf7412ebfc3520, deletion_comment = True)

**Comment by datr93** [comment]
canceling this pr. Will keep legacy swaggers

**Pull request closed without merging**
