### PR TITLE
[Hub Generated] Review request for Microsoft.Insights to add version preview/2020-10-05-preview

### PR DESCRIPTION
**Pull request by aarongas**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/aarongas/azure-rest-api-specs/dev-applicationinsights-Microsoft.Insights-2020-10-05-preview-fix...master/).
### Latest improvements:
<br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by aarongas** [comment]
These changes are necessary as the SWAGGER spec for 2020-10-05-preview was missing a validation grouping object and does not match the currently deployed API.  The changes reflected in this PR make the SWAGGER match the EXISTING deployment.

**Comment by aarongas** [comment]
@trask , @ramthi , @lzchen , and @hectorhdzg -  These changes are necessary as the SWAGGER spec for 2020-10-05-preview was missing a validation grouping object and does not match the currently deployed API. The changes reflected in this PR make the SWAGGER match the EXISTING deployment.  Please approve.

**Review by kairu-ms — COMMENTED** [review]
Please update related examples.

**Comment by kairu-ms** [comment]
This PR has breaking change.
**Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

**Comment by aarongas** [comment]
@kairu-ms - this is a preview version that was never exposed.  It is blocked behind a feature flag.  How is this a breaking change and not just a bug fix to code?  (i.e. why do I need to initiate an evaluation of the breaking change... if there is no one who could have relied on it?)

**Comment by kairu-ms** [comment]
> @kairu-ms - this is a preview version that was never exposed. It is blocked behind a feature flag. How is this a breaking change and not just a bug fix to code? (i.e. why do I need to initiate an evaluation of the breaking change... if there is no one who could have relied on it?)

The BreakingChange is a CI check and I'm not authorized to skip it. You can use above statement to pass BreakingChangeReview.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by aarongas** [comment]
> > @kairu-ms - this is a preview version that was never exposed. It is blocked behind a feature flag. How is this a breaking change and not just a bug fix to code? (i.e. why do I need to initiate an evaluation of the breaking change... if there is no one who could have relied on it?)
> 
> The BreakingChange is a CI check and I'm not authorized to skip it. You can use above statement to pass BreakingChangeReview.
@kairu-ms 
I have gone to the office hours meeting and Jeffrey Richter as approved and added the approved-breaking change label.  Can you merge?

**Comment by zakimaksyutov** [comment]
@kairu-ms, can you please outline next steps? Can we merge it?

**Pull request merged**
