### PR TITLE
Anf 7051 2020 03 01 api version swagger linting issues kpi

### PR DESCRIPTION
**Pull request by audunn**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>
This adds API version 2020-03-01 that is mentioned in NetAppFiles ARM Manifest but was not officially released and is therefore functionally the same as 2020-02-01. The PR addresses this Swagger Completeness issue
https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8188089
SDK will not need to be generated from this as all changes here are represented in the latest API version 2020-06-01 

Note 2020-05-01 API-Version will be in another PR.

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by audunn** [comment]
Not sure why swagger linting complains 
`Secret property "password", cannot be sent in the response.
Url: Microsoft.NetApp/stable/2020-06-01/netapp.json#L2886`

The property has a "x-ms-secret": true tag  and masked in response

Regarding BreakingChange this addresses a swagger linter finding.  Can we proceed with this or do we address this in a new API-Version?
If this is not acceptable here  not I will remove that change and do it in a separate PR on a new API-Version

**Comment by audunn** [comment]
@ jhendrixMSFT can we have this looked at

**Review by majastrz — APPROVED** [review]
Signed off from ARM side.

**Comment by jhendrixMSFT** [comment]
ping @yungezz

**Review by yungezz — APPROVED** [review]

**Pull request merged**
