### PR TITLE
Getting rid of redundant credential resources in dotnet sdk

### PR DESCRIPTION
**Pull request by saurabh-chugh2358**
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR
This PR is to get rid of redundant credential resources and unblock the dotnet sdk generation. 

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [X] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [X] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Review by ruowan — APPROVED** [review]

**Comment by ms-henglu** [comment]
Please get the breaking change approval.

**Comment by ruowan** [comment]
Add more context here. This fix is just remove the redundant credential resource model. The credential resource model is introduced one month ago. The model cause the downstream SDK and powershell, cli generation failure.  The root cause is the redundant credential resource, with this fix the downstream SDK generation pipeline will succeeded.  Since the downstream SDK/powershell/cli hasn't been released, we believe there are __no breaking chanage__ for customer.  This is purely a swagger fix.

@JeffreyRichter could you please approve?

**Comment by JeffreyRichter** [comment]
There is nothing for me to approve as there is no versioning or breaking change label applied to the PR.
By the way, just because no SDK/PowerShell/CLI was produced doesn't mean there is no breaking change. If the REST API ships with support for some new credential thing, then taking it away from customers using raw HTTP (without an SDK or tool) would be broken.

**Comment by ruowan** [comment]
@JeffreyRichter Thanks Jeffery.  This fix is remove the redundant model.  For customer who are using the REST api can be covered by another same model and it won't break any customer.  Btw, this just remove the model introduced 1 months ago and no customer impact.

**Comment by JeffreyRichter** [comment]
Sounds good but there is still nothing I need to do on this PR since there is no Versioning or Breaking Changee label applied to it.

**Comment by ruowan** [comment]
@scbedd Could you help to suppress the model validation issue. This PR is for fixing the swagger issue which cause our downstream .NET SDK generation block.

**Comment by scbedd** [comment]
> @scbedd Could you help to suppress the model validation issue. This PR is for fixing the swagger issue which cause our downstream .NET SDK generation block.

Suppressing on offline confirmation that there is a follow-up work item.

**Comment by konrad-jamrozik** [comment]
@JeffreyRichter re this:

> Sounds good but there is still nothing I need to do on this PR since there is no Versioning or Breaking Change label applied to it.

If the OpenAPI spec is malformed has incompatible properties, the breaking change detector tool cannot even do any analysis, hence it throws runtime exception, [as it happened here](https://github.com/Azure/azure-rest-api-specs/pull/29093/checks?check_run_id=25263057844). We still block PRs in such cases to ensure that no breaking changes slipped in just because the tool didn't run. But there will be no "breaking change / versioning review required" label, because the tool didn't run. It is OK to add an approval label in such case. Hence I would ask for you or @mikekistler  to approve. I am not sure what is the best label but @mikekistler will know. I suspect `BreakingChange-Approved-Benign`.

**Comment by ruowan** [comment]
@konrad-jamrozik As per jeffery comments. It's doesn't require any breaking change review. https://github.com/Azure/azure-rest-api-specs/pull/29093#issuecomment-2110472067

The PR is just for fixing swagger issue which doesn't released yet.  And we can make sure no customer impact. And this PR has been blocked for about 2 weeks. It has blocked our downstream SDK and powershell release. 

If it's a tooling issue, could you approve this?

**Pull request merged**
