### PR TITLE
Update lang v3.0 --> return single language instead of a list

### PR DESCRIPTION
**Pull request by HanLiMS**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@HanLiMS this is a breaking change in a swagger that's marked as stable.  Is this intentional?

**Comment by HanLiMS** [comment]
> @HanLiMS this is a breaking change in a swagger that's marked as stable. Is this intentional?

**Comment by HanLiMS** [comment]
> @HanLiMS this is a breaking change in a swagger that's marked as stable. Is this intentional?

@jhendrixMSFT Yes. We have not published this version v3.0 yet. This change is included in v3.0 version update.  Is this also the reason that "Breaking Changes" failed?  Could you give me some suggestions on moving forward? Thanks!

**Comment by jhendrixMSFT** [comment]
@HanLiMS can you please clarify what "have not published this version 3.0 yet" means?  Merging swagger changes into the public specs repo is a release event and signals to customers that the API is ready for consumption.

**Comment by HanLiMS** [comment]
> @HanLiMS can you please clarify what "have not published this version 3.0 yet" means? Merging swagger changes into the public specs repo is a release event and signals to customers that the API is ready for consumption.

@jhendrixMSFT  We have not released v3.0 yet. It will happen in the middle of April. We would like to have changes ready before the release.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@mayurid can you please merge this?  The breaking changes failure is expected.  Also note that the service hasn't yet been deployed.

**Pull request merged**
