### PR TITLE
Update LUIS Authoring v3.0-preview swagger

### PR DESCRIPTION
**Pull request by nebadr**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by yangyuan — APPROVED** [review]

**Review by erich-wang — COMMENTED** [review]
This is data plane Api, has the change been reviewed by API review board? Has it been deployed into Prod?

**Comment by nebadr** [comment]
@erich-wang  Yes it's been deployed to production  and we already have the API review board approval. The change here was just a missing field for this object in the swagger but it's been there in the api.

Here is the documentation for the api having this object:
https://westus.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9bff

**Comment by nebadr** [comment]
@erich-wang  Previous swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/7503/files

**Comment by erich-wang** [comment]
since service team confirmed that the API has been reviewed and approved by API review board, and has been deployed into PROD, merge it.

**Pull request merged**
