### PR TITLE
typo: servicefabric/resource-manager/Microsoft.ServiceFabric

### PR DESCRIPTION
**Pull request by nschonni**
- specificed -> specified
- sucessful -> successful
- resturns -> returns
- commited -> committed
- dataloss -> data loss
- Double word "with"
- applciation -> application
- ABRIC -> FABRIC
- resouce -> resource
- mininum -> minimum
- Double word "maximum"
- revent -> prevent
- empheral -> ephemeral
- exmaple -> example
- assgined -> assigned
- carefull -> careful
- primay -> primary
- Dispaly -> Display
- skus -> SKUs

If the values in `x-ms-examples` are breaking, I can rebase those out

### CODE REVIEW

**Comment by nschonni** [comment]
@anuchandy it seems like there is a problem with a duplicate model unrelated to these changes

```
ERROR (Fatal/DuplicateModelCollsion): Duplicated model name with non-identical definitions
    - file:///tmp/tmpntit_wvy/rest/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2017-07-01-preview/application.json:973:4 ($.definitions.ApplicationHealthPolicy)
    - file:///tmp/tmpntit_wvy/rest/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2018-02-01/cluster.json:534:4 ($.definitions.ApplicationHealthPolicy)
Process() cancelled due to exception : Cancellation requested.
  Cancellation requested.
```

**Comment by nschonni** [comment]
@juhacket  any idea why the build is failing?

**Comment by salameer** [comment]
Hi @anuchandy 

What's the status here? are these changes impacting the Main Swagger or is it only related to documentation

**Comment by salameer** [comment]
@vipul-modi 

@nschonni  is an awesome external contributer that provided these fixes to the swagger comments maily for Service fabric, would you kindly mind reviewing or tagging someone who can review?

**Comment by salameer** [comment]
@amanbha can you kindly review here?

**Review by amanbha — APPROVED** [review]

**Comment by nschonni** [comment]
@salameer this got approved. I rebased just to get the latest checks, but the failures are pre-existing

**Comment by nschonni** [comment]
@sergey-shandar is the "ReadOnly" rule in model validation expected to fail on older APIs?

**Comment by nschonni** [comment]
@jhendrixMSFT can you help land this?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
