### PR TITLE
Cdn Complete Json Swagger

### PR DESCRIPTION
**Pull request by injyzarif**
This doc covers operations on all CDN entities (Profile, Endpoint, CustomDomain, Origin) as well as CheckNameAvailability and Operations APIs.

CDN REST Documentation: https://msdn.microsoft.com/en-us/library/azure/mt634456.aspx

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@injyzarif__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (inzarif). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@injyzarif 
for operation: Profiles_ListProfiles, you should add the extension x-ms-pageable as described below.
```
"responses": { 
    "200": { 
        "description": "OK", 
        "schema": { 
            "$ref": "#/definitions/ProfileListResult" 
        } 
    } 
},
"x-ms-pageable": {
  "nextLinkName": null
}
```

**Comment by amarzavery** [comment]
@injyzarif - Please look at the CI failure  : https://travis-ci.org/Azure/azure-rest-api-specs/builds/95724176

**Comment by amarzavery** [comment]
why do you have this thing - "deprecated": false for every operation ? It is not required.

**Comment by injyzarif** [comment]
Thanks for your quick reply :)

1. As for the List operations, I will add the the extension x-ms-pageable. However, it is not a key piece for us since we have a limit of 4 profiles per resource group and 4 endpoints per profile. So list operations won't return massive lists of entities.

2. I didn't know "deprecated":false part is not required. I was just looking at examples of swaggers from other teams and they had it. I can remove it.

3. Thanks for pointing out the errors... Can you please help explain the failure a little more! It is too generic and swagger online editor doesn't give me any errors either.

Thanks,
Injy

**Comment by amarzavery** [comment]
The error in the CI says, For operationId : "Profile_UpdateProfile", the way you have specified body parameter for Patch operation is partially correct. The type of the body parameter must be wrapped inside schema {} . You should specify it like this:
```json
{
  "name": "tags",
  "in": "body",
  "description": "Profile tags to update",
  "required": true,
  "schema": {
    "type": "object",
    "additionalProperties": {
      "type": "string"
    }
  }
}
```

**Comment by amarzavery** [comment]
This is a good json schema validator:
https://json-schema-validator.herokuapp.com/ 
In the upper left box, paste the schema from here: https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json

In the lower left box paste your swagger json

Upon clicking the validate button you should either see errors or success.

**Comment by injyzarif** [comment]
I fixed all the issues and the schema now shows success in the json schema validator you sent me. That was very helpful, Thanks!

**Comment by amarzavery** [comment]
@injyzarif - I would also like to let you know the concept of resource flattening.
allof in swagger is treated as inheritance.
Resource flattening happens when 
- any model in the definitions section is having an allof on "Resource" or an allof on a child of "Resource".
**OR**
- an extension "x-ms-azure-resource"  is specified on the model definition
- or both of above

What is resource flattening:

When any model definition is having a complex property called "Properties" then all the sub properties defined inside "Properties" section are brought one level up that is they  are flattened. This helps developers to access things easily.
For example:
NewEndpointProperties.Properties.originHostHeader
**v/s** 
NewEndpointProperties.originHostHeader

I think this concept can be applied at lot of models in the definitions section. This will make the generated code much cleaner and will provide an ease of use to end user.

I would recommend you to take a look at the generated code using [this script](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Storage/Microsoft.Azure.Management.Storage/generate.cmd) with your current swagger. Then modify the models inside the definitions section for resource flattening and generate again. You will see the difference.

Note: specify the autorest version to the latest in script and then generate.
`set autoRestVersion=0.13.0-Nightly20151209`

**Comment by injyzarif** [comment]
Excellent explanation. Thanks Amar!

Initially, I kinda figured the idea that "All Of" means inheritance, so I modelled the objects similar to what we have in our code base. Profile and Endpoint entities are TrackedResources (having tags and location) and essentially Resources, while CustomDomain and Origin entities are untracked resources (just Resource). Is there something else we have to add here?

As for the NewEndpointProperties.Properties.originHostHeader v/s EndpointProperties.originHostHeader, I totally get your point! :) But this is intentionally designed because of the way Put and Patch payloads look like in our API.
For example, if you want to update the host header property on Endpoint, the pay load looks like this:
{
     "properties": {
            "originHostHeader" : "www.bing.com"
     }
}

So if I use the flattened structure EndpointProperties.originHostHeader, the generated payload will look like this, which doesn't work.
{
      "originHostHeader" : "www.bing.com"
}

I believe changing this part from our side to be flat is not easy, but I can double check...

**Comment by amarzavery** [comment]
I am sorry. I wasn't clear enough in penning everything. Resource Flattening is ease of use for the end user. However, it does not change the wire format.

So it will serialize the "NewEndpointProperties" model as:
```json
NewEndpointProperties: {
   "Properties" : {
        "originHostHeader" : "www.bing.com"
    }
}
```
And if this model was used as response, it will deserialize it (flatten properties) to this format for the end user - 
```json
NewEndpointProperties: {
  "originHostHeader" : "www.bing.com"
}
```
So the end user does not have to worry about this. The generated code takes care of it.

**Comment by injyzarif** [comment]
Yes, the purpose of using the extra level of properties in Json is serialization.
According to the ResourceProvider Doc here: http://goo.gl/Z6nmyH
The request body for a PUT request should look like this:
{ 
    "location": "North US", 
    "tags": { 
        "key": "value" 
    }, 
    "properties": { "comment: Resource defined structure" }, 
} 
And the response body to a GET request should look like this:
{ 
  “id”: “/subscriptions/{id}/resourceGroups/{group}/providers/{rpns}/{type}/{name}”, 
  “name”: “{name}”, 
  “type”: “{resourceProviderNamespace}/{resourceType}”, 
  "location": "North US", 
  "tags": { 
    "key1": "value 1", 
    "key2": "value 2" 
   }, 
  "properties": { "comment: "Resource defined structure" } 
} 

So the reason why we don't flatten our structure is serialization to generate the correct payloads and responses. At least on swagger editor, if I don't add this extra level, the generated operation payload is not correct.

So I would love to give the users a flattened structure in the code, but only if this actually works... If the generated SDK would serialize correctly when properties are flattened, we can do that.

**Comment by amarzavery** [comment]
@injyzarif - That is right. We have implemented this feature using an extension ```json {"x-ms-azure-resource" : true}```. Swagger Editor does not understand extensions.
The generated code will take care about putting right thing inside properties if that model definition is correctly marked with "x-ms-azure-resource". 
As suggested in my previous comment, I would recommend you to take a look at the generated code using [this script](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Storage/Microsoft.Azure.Management.Storage/generate.cmd) with your current swagger.

Based on the current swagger, the generated code will implement Resource Flattening for the following Definitions:
1. Profile (as it is a child of TrackedResource, which is a child of Resource)
2. Endpoint (same reason as above)

So doing it for other definitions will also help you.

**Comment by injyzarif** [comment]
Ok awesome, I will add this "x-ms-azure-resource" to Profile and Endpoint since the generated code will handle the correct properties.
But what about the untracked resources (Origin and CustomDomain), I assume these will need to stay the same? Or is it possible to mark them as azure-resource while they don't have basic properties like type, id, tags, and location?

**Comment by amarzavery** [comment]
Origin and CustomDomain are children of Resource. Hence they will be flattened as well.
Any model that is derived from Resource will be flattened.
```json
"Origin": {
            "description": "CDN Origin is the source of the content being delivered via CDN. When the edge nodes represented by an Endpoint do not have the requested content cached, they attempt to fetch it from one or more of the configured Origins.",
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/Resource"
                }
            ],
. . . 
```

```json
"CustomDomain": {
            "description": "CDN CustomDomain represents a mapping between a user specified domain name and an Endpoint. It is a common practice to use custom domain names to represent the URLs for branding purposes.",
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/Resource"
                }
            ],
. . .
```

Following models in the definitions sections should be marked  ```json "x-ms-azure-resource": true```. 
- DeepCreatedOrigin
- NewEndPointProperties
- EndpointUpdateProperties
- OriginParameters
- NewProfileProperties

**Comment by injyzarif** [comment]
Wait a minute, I guess the ones you listed are the ones that should NOT be marked as "x-ms-azure-resource": true !! The list should be:
- Endpoint
- Profile
- Origin
- CustomDomain

These are the ones that inherit from Resource.

**Comment by injyzarif** [comment]
Well, I am looking at the Storage swagger now, and I guess I am confused!

**Comment by injyzarif** [comment]
Thanks Aram for our conversation today. Very rich and helpful! :)
Will update the json schema as per our discussion and make a new pull request.

**Comment by amarzavery** [comment]
@injyzarif - Sorry for the delay. I did not notice that you made an update. Every operation should have a default response. Please take a look at the documentation over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#DefaultResponse). 

I noticed that you have described 409 as a response in some operations. I want to you to read the documentation for negative response status codes over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#negative-responses) and be sure of the behavior you want out of the generated code.

**Comment by injyzarif** [comment]
I fixed the responses, please review and let me know if there is anything else to fix. Thanks!

**Pull request merged**
