### PR TITLE
Fixed API versions for InfrastructureInsights

### PR DESCRIPTION
**Pull request by jecollet**
Changed API version to remove preview API (except for Alerts)

### CODE REVIEW

**Comment by nschonni** [comment]
Think you need to copy rather than rename the files to a new folder. I think it also needs to be under a "stable" folder instead of at the root

**Comment by jecollet** [comment]
These changes aren't in the product yet. Will re-open this PR when the changes are live.

**Comment by martabarillas** [comment]
adding @bganapa to the review

**Comment by martabarillas** [comment]
As we talked offline, move the files under the following folders:
preview/2016-05-01
preview/2016-06-01-preview

**Pull request closed without merging**
