### PR TITLE
Remove Microsoft.Backup.Admin 2016-05-01 API version

### PR DESCRIPTION
**Pull request by daozha**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @daozha, is it because this api-version is no longer supported for removing it?

**Comment by daozha** [comment]
> Hi @daozha, is it because this api-version is no longer supported for removing it?

Hi @ArcturusZhang. Yes, it's no longer supported and from Azure Stack Admin API team's guidance, all the Admin APIs of Azure Stack are still in preview state so we can deprecate and remove them. @bganapa to comment.

**Comment by daozha** [comment]
I've changed target branch to master according to suggestion from @bganapa. @ArcturusZhang, @bganapa, could you help review this PR, and let me know if there's any process we need to go through? Many thanks!

**Review by bganapa — APPROVED** [review]
We have deprecated this api version in the past release of AzureStack. Please note that this API surface is for AzureStack Operator. It is not applicable to Azure

**Review by ArcturusZhang — APPROVED** [review]

**Comment by BryanLa** [comment]
@daozha et al - whenever specs are deprecated and removed like this, we must also coordinate with the docs team. These specs are used to auto-generate API reference docs (in this case, the [Azure Stack Admin API](https://docs.microsoft.com/en-us/rest/api/azure-stack/) reference docs). When specs are deprecated, a [request](https://aka.ms/publish-on-docs/reference) must be filed to update our CI pipeline to pick up the new/replacement spec. The removal of the `stable/2016-05-01/` caused our CI builds to fail for Azure Stack Hub.

I'm the process of working with @troettinger to get all of the Azure Stack specs realigned with our CI config, so this is just a heads up for future changes. If you could pass this along to others that update the Azure Stack Hub swagger specs that would be much appreciated.

Thanks

**Comment by bganapa** [comment]
@BryanLa  Thanks and sorry for the hassles. I co-ordinate most of the azurestack admin api efforts. I will be sure to file a request when an  api is deprecated(which is a rare event)

**Comment by BryanLa** [comment]
Awesome, thanks @bganapa, and no worries. We I have several updates (including new APIs that our config doesn't know about yet, and new operations for existing APIs), so I hope to get everything updated soon.

**Comment by daozha** [comment]
Thank you @BryanLa and sorry for the break.

**Pull request merged**
