### PR TITLE
[Resources] Add extended locations in the /providers/resourceTypes API in 2020-08-01 version

### PR DESCRIPTION
**Pull request by Tiano2017**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by chiragg4u** [comment]
>         "capabilities": {

What are the possible capabilities?

---
Refers to: specification/resources/resource-manager/Microsoft.Resources/stable/2020-08-01/resources.json:4926 in 9335761. [](commit_id = 933576132c8641d736d6473f7f4a6a8f0fe38296, deletion_comment = False)

**Comment by chiragg4u** [comment]
Please go through the contribution checklist added as part of the review and mark them completed. This is a requirement before review can be continued.

**Comment by chiragg4u** [comment]
How the extendedLocations are defined? Is this subscription specific? Can I define it at MG level?

**Comment by chiragg4u** [comment]
Is extendedLocation being passed in register/unregister?

**Comment by Tiano2017** [comment]
done. 

---
In reply to: [704518544](https://github.com/Azure/azure-rest-api-specs/pull/10986#issuecomment-704518544) [](ancestors = 704518544)

**Comment by Tiano2017** [comment]
The extended locations are defined by the edge zone team. whenever a new edge zone is onboarded, it's going to be added to a centralized service. Right now in phase 1, the list is hard coded in ARM. 

---
In reply to: [705049358](https://github.com/Azure/azure-rest-api-specs/pull/10986#issuecomment-705049358) [](ancestors = 705049358)

**Comment by Tiano2017** [comment]
No it's not passed in register/unregister, but it may be returned since they share the response schema with /providers API. 

---
In reply to: [705049556](https://github.com/Azure/azure-rest-api-specs/pull/10986#issuecomment-705049556) [](ancestors = 705049556)

**Comment by Tiano2017** [comment]
>         "capabilities": {

This is a list of the possible values: CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SystemAssignedResourceIdentity, SupportsTags, SupportsLocation, SupportsExtension

---
In reply to: [704517650](https://github.com/Azure/azure-rest-api-specs/pull/10986#issuecomment-704517650) [](ancestors = 704517650)

---
Refers to: specification/resources/resource-manager/Microsoft.Resources/stable/2020-08-01/resources.json:4926 in 9335761. [](commit_id = 933576132c8641d736d6473f7f4a6a8f0fe38296, deletion_comment = False)

**Review by chiragg4u — APPROVED** [review]
Approved based on explanation provided by the author.

**Comment by xccc-msft** [comment]
> @xccc I'm getting linter error about "UNREFERENCED_JSON_FILE". The example file was indeed refereced by the swagger file. Is this a false alarm?

cc: @akning-ms @PhoenixHe-msft for the help

**Comment by PhoenixHe-msft** [comment]
@Tiano2017 Please update readme.md with the new version

**Review by xseeseesee — APPROVED** [review]

**Comment by xccc-msft** [comment]
@Tiano2017 Can you please try to fix the CI errors? Thanks.

**Comment by Tiano2017** [comment]
I've went through the CI errors. All them were on the old API versions which are not changed in the current PR, so I'll leave them for now. Can we run the CI checks only for the API version that is changed in a PR?

**Comment by raych1** [comment]
@Tiano2017 , there's a tag `package-2020-09` referenced in `basic information`. This tag doesn't exist. Please remove it.

**Comment by raych1** [comment]
@changlong-liu , could you help confirm if pythonT2 is a known issue?

**Comment by changlong-liu** [comment]
add @msyyc for Python issue.

**Comment by msyyc** [comment]
since you add package-resource-2020-08, so you need to edit readme.python.md and add something like:
image
    I help to edit it. Next time remember to edit it please.

[readme.python.zip](https://github.com/Azure/azure-rest-api-specs/files/5515238/readme.python.zip)

**Comment by raych1** [comment]
@qiaozha , can you have a look at the JS SDK failures? Does it need to add the new tag in readme.nodejs.md?

**Comment by colawwj** [comment]
Hi @raych1 ,
We found that the definition of  "x-ms-external" in [Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json#L122) does not follow the rules of  [a
utorest/docs/extensions/readme.md#x-ms-extermal](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-external)
Here are some correct examples: [Microsoft.Authorization\stable\2019-09-01\policyAssignments.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json#L585)
Because we don't have permission to change swagger file,we would like your help us to correct it.
if you have any concern,please let us know.thanks

**Comment by Tiano2017** [comment]
> Hi @Tiano2017 ,
> We found that the definition of "x-ms-external" in [Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json#L122) does not follow the rules of [autorest/docs/extensions/readme.md#x-ms-extermal](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-external)
> Here are some correct examples: [Microsoft.Authorization\stable\2019-09-01\policyAssignments.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json#L585)
> Because we don't have permission to change swagger file,we would like your help us to correct it.
> if you have any concern,please let us know.thanks

Hi @colawwj, for that I guess we'll need the Policy team to help on it. @feruilob can you please submit a separate PR to fix that?

**Comment by raych1** [comment]
@Tiano2017 , lintDiff warnings can be ignored. Other than JS SDK failures, the rest looks good. Btw, can you share me why the breaking change is expected? Per the new breaking change policy, adding path or adding property needs to bump API version.

**Comment by raych1** [comment]
@Tiano2017 , here's the guide for breaking change process.
**Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://msazure.visualstudio.com/One/_workitems/create/Scenario?templateId=d1c215ec-5d6a-4cb3-a193-95ddd0a1ba96&ownerId=85bb92fb-21fe-41ca-9309-47f2c5f57515). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

**Comment by raych1** [comment]
> > Hi @Tiano2017 ,
> > We found that the definition of "x-ms-external" in [Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/dataPolicyManifests.json#L122) does not follow the rules of [autorest/docs/extensions/readme.md#x-ms-extermal](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-external)
> > Here are some correct examples: [Microsoft.Authorization\stable\2019-09-01\policyAssignments.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json#L585)
> > Because we don't have permission to change swagger file,we would like your help us to correct it.
> > if you have any concern,please let us know.thanks
> 
> Hi @colawwj, for that I guess we can address in a separate PR since it's a different swagger file. @feruilob can you please submit a separate PR to fix that?

@Tiano2017 , can you follow up with @feruilob to fix this issue in separate PR? Thanks.

Regard to breaking change, adding a new path and adding a optional property is allowed in a new API version. So, this PR is ready to be merged.

**Pull request merged**
