### PR TITLE
Update RunCommand operation output as valid json object

### PR DESCRIPTION
**Pull request by koralski**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by koralski** [comment]
This is to address incidents reported the PowerShell run command returns empty result. This is due to the fact that operation output was reported as array instead of valid application/json object.  CRP changes are deployed and now the operation output is {value:[...]} instead of just array [...]
The fix is from api version 2018-04-01

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Comment by lmazuel** [comment]
@AutorestCI regenerate azure-sdk-for-python

**Review by jianghaolu — APPROVED** [review]

**Comment by jianghaolu** [comment]
Not related to this PR, but the link here is invalid - https://github.com/koralski/azure-rest-api-specs/blob/e3d9ca01eb41c555b03705a38e58173de2196194/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/examples/VirtualMachineRunCommandGet.json#L30.

Thought you might want to take a look.

**Pull request merged**
