### PR TITLE
[Hub Generated] Review request for Microsoft.CustomerLockbox to add version preview/2018-10-11-preview

### PR DESCRIPTION
**Pull request by jiayunge**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/jiayunge/azure-rest-api-specs/dev-customerlockbox-Microsoft.CustomerLockbox-2018-10-11-preview...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Is it a complete new service at first version?

**Comment by jiayunge** [comment]
we have ARM on-boarded already in terms of finishing discussion with ARM team and having our manifest and service endpoint deployed. 
This is lockbox service is already GA, but we just exposed our ARM API recently, this PR is for the first official swagger for our preview API

**Comment by jiayunge** [comment]
Looks like for preview version we have to start with private repo, if this is true, I will create a new PR against the private branch

**Comment by jiayunge** [comment]
I am closing this one since preview version should only be targeting private branch

**Pull request closed without merging**
