### PR TITLE
Adding Inference Pools, Groups and Endpoints recreated for https://github.com/Azure/azure-rest-api-specs/pull/25783 for rebased issue

### PR DESCRIPTION
**Pull request by raushan2016**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by sjanamma** [comment]
Please provide the purpose of the API and complete the due diligence checklist so that we can understand the changes better.

**Comment by sjanamma** [comment]
>             "description": "Create or update request is successful.",

200 is updated only

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8315 in 1fca1a3. [](commit_id = 1fca1a3a1190049682795960b3e91e3f6d38dada, deletion_comment = False)

**Comment by sjanamma** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/inferencePools/{name}": {

do you mean this is {inferencePoolName}

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8441 in 1fca1a3. [](commit_id = 1fca1a3a1190049682795960b3e91e3f6d38dada, deletion_comment = False)

**Comment by sjanamma** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/inferencePools/{name}/status": {

post action needs to have verb in the actionName, you could say fetchStatus instead of just status as the action name

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8803 in 1fca1a3. [](commit_id = 1fca1a3a1190049682795960b3e91e3f6d38dada, deletion_comment = False)

**Comment by sjanamma** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/inferencePools/{name}/status": {

having so many nested levels is discouraged. This can become an issue for RBAC

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8803 in 1fca1a3. [](commit_id = 1fca1a3a1190049682795960b3e91e3f6d38dada, deletion_comment = False)

**Comment by raushan2016** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/inferencePools/{name}/status": {
> > ```
> 
> post action needs to have verb in the actionName, you could say fetchStatus instead of just status as the action name
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8803 in [1fca1a3](https://github.com/Azure/azure-rest-api-specs/commit/1fca1a3a1190049682795960b3e91e3f6d38dada). [](commit_id = [1fca1a3](https://github.com/Azure/azure-rest-api-specs/commit/1fca1a3a1190049682795960b3e91e3f6d38dada), deletion_comment = False)

Updated

**Comment by raushan2016** [comment]
> Please provide the purpose of the API and complete the due diligence checklist so that we can understand the changes better.

These are new resources to support large fleet of compute running specific models.

**Comment by raushan2016** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/inferencePools/{name}/status": {
> > ```
> 
> having so many nested levels is discouraged. This can become an issue for RBAC
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:8803 in [1fca1a3](https://github.com/Azure/azure-rest-api-specs/commit/1fca1a3a1190049682795960b3e91e3f6d38dada). [](commit_id = [1fca1a3](https://github.com/Azure/azure-rest-api-specs/commit/1fca1a3a1190049682795960b3e91e3f6d38dada), deletion_comment = False)

These are child/sub resources within the InferencePool. Where each InferencePool can have many groups and each group can have many endpoints. We currently have OnlineEndpoint and OnlineDeployment resouces in similar way. Can you explain a bit more about the issue

**Comment by visingla-ms** [comment]
>             "type": "object"

Why is this a free-form object? Please define a schema for the model here, as users won't know how to read/parse this.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:19174 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "data": {

Rename data to metadata?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20367 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "InferenceGroupMinimalTrackedResourceWithSku": {

Same here: why not use TrackedResource from common types v3?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20389 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "$ref": "#/definitions/InferencePool"

Rename InferencePool to InferencePoolProperties?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20547 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "x-nullable": true

As long as the upper level definition calls out the "required" properties, this x-nullable is redundant, so it can skipped to define explicitly for all properties.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25218 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>         "properties": {

Can this not be named as additionalProperties? Properties inside Properties seems odd.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25507 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by raushan2016** [comment]
> additionalProperties

@visingla-ms we have the same structure for existing ARM resources like OnlineEndpoint and Deployment. We wanted to keep it consistent. 

> > ```
> >         "type": "object"
> > ```
> 
> Schema?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25309 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)

**Comment by raushan2016** [comment]
> > ```
> >       "x-nullable": true
> > ```
> 
> As long as the upper level definition calls out the "required" properties, this x-nullable is redundant, so it can skipped to define explicitly for all properties.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25218 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)

@visingla-ms this is coming from the common `Microsoft.MachineLearningServices` RP implementation and is there for all the resources in this RP. After talking to the RP owners it will have some side effects and would be better to avoid

**Comment by raushan2016** [comment]
> > ```
> >     "properties": {
> > ```
> 
> Can this not be named as additionalProperties? Properties inside Properties seems odd.
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25507 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)

@visingla-ms  we have the same structure for existing ARM resources like OnlineEndpoint and Deployment. We wanted to keep it consistent.

**Comment by raushan2016** [comment]
> > ```
> > "InferenceEndpointMinimalTrackedResource": {
> > ```
> 
> Why not derive it from common types v3 TrackedResource, and not define id, name, type etc. properties here?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20270 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)

@visingla-ms this is coming from the common Microsoft.MachineLearningServices RP implementation and is there for all the resources in this RP. After talking to the RP owners it will have some side effects and would be better to avoid

**Comment by raushan2016** [comment]
> > ```
> >       "$ref": "#/definitions/InferencePool"
> > ```
> 
> Rename InferencePool to InferencePoolProperties?
> 
> Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20547 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)

@visingla-ms All the ARM resources for this RP `Microsoft.MachineLearningServices` has the same structure and naming convention.

**Comment by visingla-ms** [comment]
>     "InferenceEndpointMinimalTrackedResource": {

But I see at line 24179, that the same swagger has been using definitions from common types, so why not for this resource also? Please use it from common types.

---
In reply to: [1725838784](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1725838784) [](http://example.com/codeflow?ancestors=1725838784)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20270 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
>     "InferenceGroupMinimalTrackedResourceWithSku": {

Same here, I can see many other resources in this same mfe.json using TrackedResource etc. from common types.

---
In reply to: [1725839943](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1725839943) [](http://example.com/codeflow?ancestors=1725839943)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20389 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by visingla-ms** [comment]
> > > ```
> > >       "x-nullable": true
> > > ```
> > 
> > 
> > As long as the upper level definition calls out the "required" properties, this x-nullable is redundant, so it can skipped to define explicitly for all properties.
> > Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25218 in [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e). [](commit_id = [afce89c](https://github.com/Azure/azure-rest-api-specs/commit/afce89cf3ee90a68ca8cf9c256737be82bb0ea4e), deletion_comment = False)
> 
> @visingla-ms this is coming from the common `Microsoft.MachineLearningServices` RP implementation and is there for all the resources in this RP. After talking to the RP owners it will have some side effects and would be better to avoid

What kind of side effects here?

**Comment by visingla-ms** [comment]
>           "description": "Description of the endpoint deployment.",

This being base for multiple other property bags, endpoint word is not right in each context, right?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25487 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Comment by visingla-ms** [comment]
>           "additionalProperties": {

The use of additionalProperties is not allowed, specifically, when getting it as input from users. What is the purpose of this field?

Even if it is being used in other resource types so far, it is no longer recommended for newer types.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25494 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Comment by raushan2016** [comment]
> TrackedResource

@visingla-ms 
TrackedResource has all properties like `identity`, `sku` which are not relevant for many resources. All resources just added it even if its not needed or supported. I refactored it so that `Identity` and `sku` are extended properties and resources can decide if they need them or not.

**Comment by raushan2016** [comment]
Discussed in the office hour about the API and models. cc @Suhas Rao

---
In reply to: [1722391994](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1722391994) [](http://example.com/codeflow?ancestors=1722391994)

**Comment by raushan2016** [comment]
>         "properties": {

For this RP all resources has properties.properties. For this RP to be consistent we need this for this resource as well

---
In reply to: [1725864070](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1725864070) [](http://example.com/codeflow?ancestors=1725864070)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25507 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by raushan2016** [comment]
>     "InferenceEndpointMinimalTrackedResource": {

Updated

---
In reply to: [1731945022](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1731945022) [](http://example.com/codeflow?ancestors=1731945022,1725838784)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20270 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by raushan2016** [comment]
>     "InferenceGroupMinimalTrackedResourceWithSku": {

Updated

---
In reply to: [1731946037](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1731946037) [](http://example.com/codeflow?ancestors=1731946037,1725839943)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:20389 in afce89c. [](commit_id = afce89cf3ee90a68ca8cf9c256737be82bb0ea4e, deletion_comment = False)

**Comment by raushan2016** [comment]
Discussed this in ARM office hours. RP owner has an active work to address this for all resources in the RP as its coming from the common swagger generation.

 cc @Suhas Rao

---
In reply to: [1731948783](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1731948783) [](http://example.com/codeflow?ancestors=1731948783)

**Comment by raushan2016** [comment]
>           "additionalProperties": {

@raosuhas we need a Dictionary<string,string> in our contract and swagger adds this during generation, is this something which can be omitted ?

---
In reply to: [1731954551](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1731954551) [](http://example.com/codeflow?ancestors=1731954551)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25494 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Comment by raushan2016** [comment]
>           "additionalProperties": {

This is similar to `environmentVariables`

---
In reply to: [1736366649](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1736366649) [](http://example.com/codeflow?ancestors=1736366649,1731954551)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25494 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Comment by raosuhas** [comment]
>           "additionalProperties": {

This is not recommended at all since these additional properties do not work well with the arm tooling since the schema is not defined. I see you have scheduled one more discussion in the office hours so we can discuss there. 

---
In reply to: [1736366649](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1736366649) [](http://example.com/codeflow?ancestors=1736366649,1731954551)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25494 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Comment by raushan2016** [comment]
>           "additionalProperties": {

As discussed in office hours we can go with this.

---
In reply to: [1738285112](https://github.com/Azure/azure-rest-api-specs/pull/25819#issuecomment-1738285112) [](http://example.com/codeflow?ancestors=1738285112,1731954551)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json:25494 in 907011c. [](commit_id = 907011ca3bd0ab6a38b7eb5abf38d42a427471c9, deletion_comment = False)

**Review by raosuhas — APPROVED** [review]

**Pull request merged**
