### PR TITLE
Add x-ms-arm-id-details extension to select resources

### PR DESCRIPTION
**Pull request by matthchr**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify: Document ARM ID references for a few key services:
  2. When are you targeting to deploy the new service/feature to public regions? **N/A**
  3. When do you expect to publish the swagger? **N/A**
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

This adds some new `x-ms-arm-id-details` extensions to various RPs Swagger for fields that are ARM references. This is _not_ comprehensive and may not cover all references in all Swaggers. The intent is to bootstrap some important references for some important resources. See https://github.com/Azure/autorest/pull/4150 and the [extension documentation](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-arm-id-details). Where there were multiple Swaggers for a service all less than ~1yr old, I made the update for all of the Swaggers within the last year, not just the latest.

I will be working with @leni-msft on linter rules that will help improve the quality of this annotation across all service Swaggers, this is just a starting point.

### CODE REVIEW

**Comment by matthchr** [comment]
It looks like may need to fix the model validator to understand this new format:
>  message: 'validateOperations - ErrorMessage:unknown format "arm-id" is used in schema at path "#/properties/storageAccountId".ErrorStack:Error: unknown format "arm-id" is used in schema at path "#/properties/storageAccountId"\n' +
    '    at Object.generate_format [as code] (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:50415:15)\n' +
Validating x-ms-examples in specification/batch/resource-manager/Microsoft.Batch/stable/2021-01-01/BatchManagement.json

**Comment by matthchr** [comment]
It also looks like the breaking change detector is thinking that [this format change is breaking](https://github.com/Azure/openapi-diff/blob/master/docs/rules/1023.md). AFAIK it is not.

**Comment by matthchr** [comment]
I will split this PR up into multiple PRs (per-service) once we've resolve the issues with the linters

**Comment by raych1** [comment]
Waiting for the UP deployment that resolves the check failures.

**Comment by matthchr** [comment]
This has been superceded by the PRs mentioned above

**Pull request closed without merging**
