### PR TITLE
[Relay] 2024-01-01

### PR DESCRIPTION
**Pull request by schaudhari6254888**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by gary-x-li** [comment]
@schaudhari6254888 There is no difference between the new version and the previous version. Is it intended?

**Comment by schaudhari6254888** [comment]
> @schaudhari6254888 There is no difference between the new version and the previous version. Is it intended?

Hey @gary-x-li, we have just introduced the new api with no changes. So that our all services (Eventhub/Servicebus/relay) will be on the same line

**Review by damodaravadhani — APPROVED** [review]

**Pull request merged**
