### PR TITLE
[FarmBeats] Use `x-ms-parameterized-host`

### PR DESCRIPTION
**Pull request by ellismg**
Use the `x-ms-parameterized-host` pattern, which our code generators
understand and generate better code for.

### CODE REVIEW

**Comment by ellismg** [comment]
Per a in person discussion with @iscai-msft, submitting this on her behalf.  Having this in the swagger is also helpful for the C# and Java SDKs.

**Review by iscai-msft — APPROVED** [review]
thanks so much @ellismg !

**Review by agniveshadhikari — APPROVED** [review]
Thanks Matt!

**Comment by agniveshadhikari** [comment]
Hey I think we want to merge to this branch:

https://github.com/Azure/azure-rest-api-specs/tree/dev-agfood-Microsoft.AgFoodPlatform-2021-03-31-preview

**Comment by agniveshadhikari** [comment]
Hey I changed the target branch to the one that we wanna merge, looks like you'll need to rebase your commit onto the new target branch.

**Pull request merged**
