### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-09-01

### PR DESCRIPTION
**Pull request by FumingZhang**
## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  Alread deployed to all global regions by 10/03.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  ASAP, 10/19.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[x] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Dear review board, I would like to clarify the failures in the CI checks.

For [SDK azure-powershell](https://github.com/Azure/azure-rest-api-specs/pull/21148/checks?check_run_id=8927386148), it happened in our previous PR [09-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/21038). From log it seems that the reason for the failure lies in the build tool `/home/cloudtest/.autorest/@autorest_powershell@3.0.491/node_modules/@autorest/powershell/dist/plugins/llcsharp-v2.js - TypeError: value.replace is not a function`. This CI used to be optional and is enabled recently.

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/21148/checks?check_run_id=8927382329), it happened in our previous PR [09-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/21038). I suppose this should be a known issue. Besides it has been replaced by track 2 SDK, released one month ago.

For [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/21148/checks?check_run_id=8927329703), all detected missing API tags are expected. Details in this [comment](https://github.com/Azure/azure-rest-api-specs/pull/18686#issuecomment-1099823292). These errors started appearing after [this update](https://github.com/Azure/avocado/pull/78) of Avocado. Would really appreciate if some mechanism could be provided to disable the alarms, cc owner @ruowan.

For [Swagger SDK Breaking Change Tracking](https://github.com/Azure/azure-rest-api-specs/pull/21148/checks?check_run_id=8927331158), confirming with Go SDK owner.

**Comment by rkmanda** [comment]
>           "204": {

you dont need a 204 for POST. Pl add a 200 with the definition of the response body

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-09-01/managedClusters.json:1405 in ac33a46. [](commit_id = ac33a465f3391037c8d81bceabcf8c1ada5cbae5, deletion_comment = False)

**Comment by karataliu** [comment]
> > ```
> >       "204": {
> > ```
> 
> you dont need a 204 for POST. Pl add a 200 with the definition of the response body
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-09-01/managedClusters.json:1405 in [ac33a46](https://github.com/Azure/azure-rest-api-specs/commit/ac33a465f3391037c8d81bceabcf8c1ada5cbae5). [](commit_id = [ac33a46](https://github.com/Azure/azure-rest-api-specs/commit/ac33a465f3391037c8d81bceabcf8c1ada5cbae5), deletion_comment = False)

@rkmanda This is an action/operation, not a resource. So there is no body to return, suppose 200 doesn't suit here?

**Comment by rkmanda** [comment]
> > > ```
> > >       "204": {
> > > ```
> > 
> > 
> > you dont need a 204 for POST. Pl add a 200 with the definition of the response body
> > Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-09-01/managedClusters.json:1405 in [ac33a46](https://github.com/Azure/azure-rest-api-specs/commit/ac33a465f3391037c8d81bceabcf8c1ada5cbae5). [](commit_id = [ac33a46](https://github.com/Azure/azure-rest-api-specs/commit/ac33a465f3391037c8d81bceabcf8c1ada5cbae5), deletion_comment = False)
> 
> @rkmanda This is an action/operation, not a resource. So there is no body to return, suppose 200 doesn't suit here?

200 with a response body is required to allow generated clients to know how to deserailize the final outcome of the long running operation. This is how the azure sdks generation logic is written up currently.

**Comment by matthchr** [comment]
> 200 with a response body is required to allow generated clients to know how to deserailize the final outcome of the long running operation. This is how the azure sdks generation logic is written up currently.

I'm a bit confused. If this were true, the existing operations that already follow this pattern would have this problem right?
```
POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}/rotateClusterCertificates`
POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}/start
POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}/stop
```

As far as I know, they do not have any issue in the existing SDKs.

The specification [specifically allows 204 NoContent](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#call-action-post-asynchronously) for async POST:

> If the POST completes successfully, the URL that was returned in the Location header MUST now return what would have been a successful response if the API completed (e.g. a response body / header / status code). It is acceptable for this to be a 200/204 NoContent if the action does not require a response (e.g. restarting a VM).

You can also see for example in the [Go SDK location poller](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/internal/pollers/loc/loc.go#L103) that it specifically allows any non-202 as success. AFAIK this is true with all of the SDKs (for example [Python here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2022_07_01/operations/_managed_clusters_operations.py#L2621)).

**Comment by andyzhangx** [comment]
hi folks, is there any way to accelerate merging this PR? the [cli command cutoff date is 10/26/2022](https://github.com/Azure/azure-cli/milestones), even this PR could be merged today, it's still **very** tight schedule for other cli commands (which depend on this aks sdk release) to get merged in cli command repo.
cc @palma21 @andyliuliming @olsenme

**Comment by rkmanda** [comment]
>           "204": {

Per offline conversation, there is no response being returned at the end of the polling of this API

---
In reply to: [1286377645](https://github.com/Azure/azure-rest-api-specs/pull/21148#issuecomment-1286377645) [](http://example.com/codeflow?ancestors=1286377645,1286377645)

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-09-01/managedClusters.json:1405 in ac33a46. [](commit_id = ac33a465f3391037c8d81bceabcf8c1ada5cbae5, deletion_comment = False)

**Comment by msyyc** [comment]
approved for Avocado since https://github.com/Azure/azure-rest-api-specs/pull/18686#issuecomment-1099823292

**Review by msyyc — APPROVED** [review]

**Pull request merged**
