### PR TITLE
adding Vulnerability Assessemnt APIs to readme

### PR DESCRIPTION
**Pull request by yaakoviyun**
adding Vulnerability Assessemnt APIs to readme

### CODE REVIEW

**Comment by anuchandy** [comment]
@jhendrixMSFT another [PR](https://github.com/Azure/azure-rest-api-specs/pull/3063) related to this was assigned to me, this PR is opened based on the feedback on other PR. This looks good.

**Review by anuchandy — APPROVED** [review]

**Review by jaredmoo — APPROVED** [review]

**Review by jaredmoo — CHANGES_REQUESTED** [review]
Please comment if/when this API is publicly available on at least 1 production cluster. Is ARM team signoff needed from @ravbhatnagar ?

**Comment by yaakoviyun** [comment]
Those APIs are publicly available around the world.
@ravbhatnagar  approved them in the PR for the private repo

**Review by jaredmoo — APPROVED** [review]
Thanks for confirmation.

**Comment by yaakoviyun** [comment]
@anuchandy , can you please merge?

**Pull request merged**
