### PR TITLE
Event Grid 2019-01-01 API Version: Swagger and related test examples

### PR DESCRIPTION
**Pull request by ahamad-MS**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by sarangan12** [comment]
Please fix the errors reported in https://travis-ci.org/Azure/azure-rest-api-specs/jobs/467369257

**Comment by sarangan12** [comment]
Also since this is a new version, This needs ARM Approval. Adding appropriate label

**Comment by kalyanaj** [comment]
@sarangan12 , @ahamad-MS :

This is regarding the four examples issues at https://portal.azure-devex-tools.com/app/branch/ahamad-MS/azure-rest-api-specs/master/static. 

This is a false positive. We have multiple EventSubscriptionDestination types (EventHubEventSubscriptionDestination, HybridConnectionEventSubscriptionDestination etc.) and each of them has corresponding property classes e.g. EventHubEventSubscriptionDestinationProperties and HybridConnectionEventSubscriptionDestinationProperties have both a property called resourceId which is why the validation appears to be flagging this. However, the discriminator value (endpointType) is separate for each of these destinations, hence based on the discriminator it will get deserialized into the appropriate type.

I tried to submit a suppression request from the OpenAPI hub portal, but it fails with "Sorry, something went wrong." (tried in all browsers), hence updating it here.

**Comment by ahamad-MS** [comment]
@kalyanaj @sarangan12  the suppression request finally went through and cleared the false alarm issue. I don't see any more validation issues yet Model validator task is still shown ad neutral. is this expected? anything to be addressed here?

**Comment by ahamad-MS** [comment]
@KrisBash @sarangan12 Can you please let us know if there is any feedback/comments to be addressed from our side. We would like to get this PR finalized today if possible. Thanks a lot.

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
