### PR TITLE
fix: adhybridhealthservice model validation issues

### PR DESCRIPTION
**Pull request by nschonni**
Ran through using oav to correct the examples that were flagged before

### CODE REVIEW

**Comment by nschonni** [comment]
@binilkk looks like you touched this last, so hope this makes sense

**Comment by yaohaizh** [comment]
@binilkk Could you help review this PR?

**Comment by binilkk** [comment]
I will after my oncall is over next week.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yaohaizh** [comment]
@binilkk Could you help review this? Thanks.

**Comment by yaohaizh** [comment]
@binilkk Could you help review this? Thanks.

**Review by yaohaizh — APPROVED** [review]

**Pull request merged**
