### PR TITLE
[Hub Generated] Review request for Microsoft.Devices to add version preview/2023-06-30-preview

### PR DESCRIPTION
**Pull request by MikalaiSavenka**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/MikalaiSavenka-iothub-Microsoft.Devices-2023-06-30-preview...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by pilor** [comment]
I don't know if these breaking changes are really necessary but according to the latest policy its allowed to make these changes from preview to preview version so approving.

**Comment by JackTn** [comment]
In my opinion , This pr added new version preview/2023-06-30-preview. These breaking change is not related to this pr. So that approved, @qiaozha  can you take a look on this pr. I'm approved.

**Review by JackTn — APPROVED** [review]

**Comment by MikalaiSavenka** [comment]
> 

this pr is new preview version with renamings of CosmosDB collections names to CosmosDB containers to adhere changed naming in CosmosDB side

**Comment by MikalaiSavenka** [comment]
@JackTn   @rkmanda could you also help me understand what this 3 failing checks mean?

overall are those 3 failed checks mandatory or optional? and in details:

https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084332535 - doe this mean the ARM manifest with this version should be rolled out first and then this check will pass? Who will merge then - reviewers or it is automerge? I see that I have no permissions to merge.

https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084427136 - is it some SDK related failure? I did not make any SDK changes, how it can be resolved then? Any tips?

https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084333617 - this is about field renaming that I did - so it may be treated just as a warning?

**Comment by MikalaiSavenka** [comment]
Hello I submitted some questions in PR some time ago [Hub Generated] Review request for Microsoft.Devices to add version preview/2023-06-30-preview by MikalaiSavenka * Pull Request #23758 * Azure/azure-rest-api-specs (github.com)<https://github.com/Azure/azure-rest-api-specs/pull/23758>

Can I get them answered?

**Comment by JackTn** [comment]
> @JackTn @rkmanda could you also help me understand what this 3 failing checks mean?
> 
> overall are those 3 failed checks mandatory or optional? and in details:
> 
> https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084332535 - it is clear that ARM manifest with version 2023-06-30-preview should be rolled out first but who will merge after this check pass - reviewers or it is automerge? I see that I have no permissions to merge.
> 
> https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084427136 - is it some SDK related failure? I did not make any SDK changes, how it can be resolved then? Any tips? Error says: Fatal error: SSL error: syscall failure: Broken pipe
> 
> https://github.com/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084333617 - this is about field renaming that I did - so it may be treated just as a warning?

@MikalaiSavenka  you can know more about this in https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md

**Comment by JackTn** [comment]
> In my opinion , This pr added new version preview/2023-06-30-preview. These breaking change is not related to this pr. So that approved, @qiaozha can you take a look on this pr. let me know if i'm wrong. I'm approved.

@qiaozha  can you take a look on this, it can be merged when you  approved

**Comment by MikalaiSavenka** [comment]
> **SDK azure-powershell ** Failing after 10m — SDK azure-powershell failed
> [Details](/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084427136)
> [ @openapi-pipeline-app ](/apps/openapi-pipeline-app)
> ** Swagger SDK Breaking Change Tracking **

thanks I looke and this does not exist in doc:

SDK azure-powershell

**Comment by JackTn** [comment]
> > **SDK azure-powershell ** Failing after 10m — SDK azure-powershell failed
> > [Details](/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084427136)
> > [ @openapi-pipeline-app ](/apps/openapi-pipeline-app)
> > ** Swagger SDK Breaking Change Tracking **
> 
> thanks I looke and this does not exist in doc:
> 
> SDK azure-powershell

@raych1 are there any docs about SDK-azure-powershell ?

**Comment by MikalaiSavenka** [comment]
@JackTn @qiaozha @rkmanda  could you coordinate and decide who should review next?

**Comment by MikalaiSavenka** [comment]
@qiaozha  as I understand you can merge it now but we cannot merge until ARM manifest is rolled out - please hold on

**Comment by qiaozha** [comment]
@tadelesh Can you help take a look at the Go SDK breaking change ? Thanks

**Review by qiaozha — APPROVED** [review]

**Comment by JackTn** [comment]
@MikalaiSavenka Pls let me know it's ready to merge. Thanks

**Comment by raych1** [comment]
> > > **SDK azure-powershell ** Failing after 10m — SDK azure-powershell failed
> > > [Details](/Azure/azure-rest-api-specs/pull/23758/checks?check_run_id=13084427136)
> > > [ @openapi-pipeline-app ](/apps/openapi-pipeline-app)
> > > ** Swagger SDK Breaking Change Tracking **
> > 
> > 
> > thanks I looke and this does not exist in doc:
> > SDK azure-powershell
> 
> @raych1 are there any docs about SDK-azure-powershell ?

@MikalaiSavenka @JackTn , SDK-azure-powershell check can be ignored.

**Comment by qiaozha** [comment]
I will merge it as this PR assigned to me before the ownership change. @rkmanda

**Pull request merged**
