### PR TITLE
[AgriFood] Adding 2021-07-31-preview API version

### PR DESCRIPTION
**Pull request by bhargav-kansagara**
# Data Plane API - Pull Request
Adding new 2021-07-31-preview API version

## API Info: The Basics
Private repo PR - https://github.com/Azure/azure-rest-api-specs-pr/pull/8244

* Link to engagement record issue:

Is this review for (select one):

- [x] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by mikekistler** [comment]
@bhargav-kansagara I believe this PR is simply establishing the basis for a public preview in the near future, and that the changes requested in the internal repo PR #8244 will be addressed in the PR for the public preview. Can you please confirm? 

If this understanding is correct I am fine with merging this PR and deferring a full review for the PR for public preview.

**Comment by bhargav-kansagara** [comment]
@mikekistler Yes that is correct, we will address all the comments as part of the next API version (Nov 2022) and schedule a new review as well.

**Review by mikekistler — APPROVED** [review]
This will be the basis for the changes needed to move to public preview.

**Comment by bhargav-kansagara** [comment]
Breaking change: Expected and already communicated to customers
LintDiff: Model is dependent on partner services' request & response and not controlled by us
SemanticValidation: Getting errors for form-data type, only getting reported in older version of oav, link to issue raised - https://github.com/Azure/azure-rest-api-specs-pr/issues/8678

**Review by tjprescott — APPROVED** [review]
@mikekistler your plan looks fine to me. However, I can't merge this with the failing checks. @lmazuel can you force merge this?

**Pull request merged**
