### PR TITLE
Reverting the schedule.json response code for Created to 201 as that …

### PR DESCRIPTION
**Pull request by DeveloperTommy**
…conforms with our Web Service API

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by vrdmr — APPROVED** [review]
LGTM

**Comment by annatisch** [comment]
Thanks @DeveloperTommy!
It seems to be unrelated to the PR, but it looks like the spec has a duplicate model definition for "JobStreamProperties".
Would it be possible to correct this? (i.e. make all three definitions identical, or separate it out into a common definition referenced by all three)
As you can see - this is preventing the autorest generation of the Go and Ruby SDKs as configured by the current readme.

**Comment by DeveloperTommy** [comment]
Hi Anna,

Thanks for pointing that out. This change is somewhat urgent as it is blocking a recent large refactoring that we have done for our Swagger spec. My team does own that asset; however, I'll note to our point of contact that we should fix this.

Thanks,
Tommy

**Comment by vrdmr** [comment]
Hi @annatisch  - To resolve the "duplicate model definition for "JobStreamProperties"", I recently did the whole refactoring of our specs - #3190.

> Would it be possible to correct this? (i.e. make all three definitions identical, or separate it out into a common definition referenced by all three)
If you go to out [specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/automation/resource-manager/Microsoft.Automation), you'll find common definitions for really common things and the individual definitions have been refactored.

> As you can see - this is preventing the autorest generation of the Go and Ruby SDKs as configured by the current readme.
How should we change our [readme.md](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/readme.md) to fix the issue with Go and Python?

**Comment by annatisch** [comment]
Thanks @vrdmr - I'm guessing in the earlier refactor the definitions for `"JobStreamProperties"` were probably only consolidated across particular API versions. However Go and Ruby will generate multiple-API-version-compatible SDKs.
This issue is with the [2015-10 API version](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/readme.md#tag-package-2015-10) (`--tag=package-2015-10`)
The package listing for 2015-10 will need to be either dropped from multi-API configuration (possibly breaking change for SDKs) or corrected (i.e. consistent JobStreamProperties between:
- 2015-10-31/runbook.json
- 2015-10-31/job.json
- 2015-10-31/dscCompilationJob

There are only two minor corrections that would be needed:
- In` dscCompilationJob.json` the `streamType` enum is missing the `debug` option. If this is actually valid and `debug` should not be an option, it needs to be removed from `job.json` and `runbook.json`.
- And finally `runbook.json` does not have the `x-ms-client-flatten: true` extension.

**Comment by vrdmr** [comment]
Thanks @annatisch. I'll take a look at the suggestions and do them. In the meantime, could you please approve this PR? This is urgent and is currently blocking our SDK release which we need for Powershell cmdlet work.

**Comment by annatisch** [comment]
@vrdmr - I can add the commit to this PR if you advise how to resolve the two conflicts identified above.
Would that be okay?

**Comment by lmazuel** [comment]
@vrdmr could you define more precisely "this is not being used". Do you say the endpoint does not exist anymore and is not reachable? Or do you say you don't recommend it anymore?
If the end-point is still reachable, do you have metrics that tells you it's not used anymore by no-one on earth?

The contract with multi-api versioning packages in Go, Ruby and Python (and soon more language by the way), is that we ship all Swagger that matches a real end-point. Meaning customers can decide *without installing an old version of SDK* what Api version they want. Not shipping an api-version already shipped is then not an option, since it might break customers.

If we merge this PR as-is, this means that you're telling Go/Ruby/Python SDK customers that they can't get the content of this PR and all latest fixes and updates, because you prioritized Powershell users. Being that the change needed is faster to implement that the time we spent to discuss it, I think we should consider making everybody happy and not just Powershell :)

**Review by annatisch — APPROVED** [review]

**Pull request merged**
