### PR TITLE
[key vault] make key-version path parameter required for get key

### PR DESCRIPTION
**Pull request by iscai-msft**
The fix that added this broke autorest generation. This is because path parameters need to be required [here's](https://swagger.io/specification/v2/#parameterObject) the swagger link describing this. Since `key-version` is required for all of the other calls in 7.0, and because `getKey` also has `key-version` as required in the other versions (i.e., [7.1-preview](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.1/keys.json#L248)), I'm switching it back to required

### CODE REVIEW

**Comment by daviwil** [comment]
Yep, this is invalid Swagger according to the OpenAPI v2 specification:

> Determines whether this parameter is mandatory. If the parameter is `in` "path", this property is **required** and its value MUST be `true`.

https://swagger.io/specification/v2/#parameterObject

**Comment by heaths** [comment]
But it's never actually been required. Our SDK even treats it as optional. If you don't specify it, the "latest" is assumed which is the correct behavior. This was changed to reflect reality.

**Comment by heaths** [comment]
Talking with @iscai-msft offline, I see this path parameters are required to be `required: true`, so maybe we just need to change this back and treat it as optional in our client SDKs anyway. @johanste, thoughts here?

**Comment by daviwil** [comment]
My interpretation is that if a path parameter is meant to optional, you should use a separate definiton for `/keys/{key-name}` which doesn't specify `{key-version}`.  Granted, this would require a new `operationId` since it's being defined under a different path than `GetKey`.

**Comment by johanste** [comment]
This should be two paths - one with version, one without. Path parameters are indeed required.

**Comment by jlichwa** [comment]
We need our REST API docs to represent reality. So customers know how to use our API. Today version is optional across REST API, SDKs.

**Comment by johanste** [comment]
But it is two different endpoints/routes:

`/keys/{key-name}`

and 

`/keys/{key-name}/{key-version}`

and should in reality be described as such in order to have a valid openapi document. 

Given that this invalid openapi document accidentally "worked" before, we do have a problem here in that we probably want to keep a single overload of the method in generated code. Ideally, we can correct the document so that it is actually valid without changing what code gets generated.

**Comment by heaths** [comment]
Given the alternative, making this `required: true` again and documenting it's actually optional is probably the best course of action. Adding a new path for generated languages would actually cause more churn than what we currently have.

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
@johanste @heaths if you are both satisfied with this change, @lmazuel will need to merge it. I don't have sufficient Github permissions to merge this.

**Comment by jlichwa** [comment]
Once we on it, can we just use the same comment across all types and propagate across future versions 7.1 and 7.2, so it is not lost.

**Comment by iscai-msft** [comment]
Will do. @jlichwa when you say "across all types", do you mean key-version is always optional across all operations?

**Comment by jlichwa** [comment]
@iscai-msft I meant that same logic applies for all types:operations: GetCertificate,GetSecret . So we can add this comment to those too:"Though listed as required following OpenAPI guidelines for path parameters, actually optional on the server, which assumes 'latest' if not provided."

If we can copy paste this comment to above types, that would be very beneficial

**Comment by iscai-msft** [comment]
@jlichwa added the clarifying comment to GetKey, GetSecret, and GetCertificate for API version 7.0, 7.1-preview, and 7.2-preview. Let me know if the fixes are good, thanks!

**Review by jlichwa — APPROVED** [review]

**Comment by jlichwa** [comment]
> @jlichwa added the clarifying comment to GetKey, GetSecret, and GetCertificate for API version 7.0, 7.1-preview, and 7.2-preview. Let me know if the fixes are good, thanks!

That is great. Thank you so much

**Comment by msfcolombo** [comment]
I have some reserves about using the following as documentation:

`Though listed as required following OpenAPI guidelines for path parameters, actually optional on the server, which assumes 'latest' if not provided.`

The vast majority of readers don't know or don't care about OpenAPI. When they read, they want to learn exact semantics of this API, regardless of standards. Therefore I think we should document as something like:

`This URI fragment is optional. If not specified, the latest version of the [certificate/key/secret] is returned`

**Comment by iscai-msft** [comment]
@msfcolombo I see where you're coming from, I'll change the comment to that for better customer readability. Thanks!

**Comment by iscai-msft** [comment]
@msfcolombo, implemented the changes you requested. lmk what you think!

**Review by heaths — APPROVED** [review]

**Review by msfcolombo — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]

**Pull request merged**
