### PR TITLE
Azure Language add scriptCode, and enums for script Language Detection Results

### LINKED ISSUE #26778: [Azure Cognitive service for language ] API Review
New API Review meeting has been requested.

**Service Name**: Azure Cognitive service for language 
**Review Created By**: Quentin Robinson
**Review Date**: 12/19/2023 01:00 PM PT
**Onboarding Record**: 
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/26777
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: Adding a new enum to show what the script input text is 

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=7083a0ea-f987-ee11-8179-000d3a340b2c)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by quentinRobinson**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
Adding a new enum scriptCode to Language Detection response to tell what script the input text was in.

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/Language/preview/2023-04-15-preview
* Updated paths: x.definitions.DetectedLanguage.properties.script, x.definitions.DetectedLanguage.properties.scriptCode

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/26778

### CODE REVIEW

**Review by heaths — COMMENTED** [review]
What's the purpose of having both the script and scriptCode in a response? If there's a standard for the name mapping, is there much point is providing both? Responses would be smaller, and we don't need to add a bunch of partial names to the `custom-words.txt` shared by every service?

**Comment by heaths** [comment]
Also, why is this targeting main? Main is for completed api-versions that should generally not be changed. If 2023-11-15-preview is in development, your team should be working in a feature branch - ideally created in https://aka.ms/openapihub so it gets a baseline commit (we are deprecating the dev/ folder).

**Comment by quentinRobinson** [comment]
> What's the purpose of having both the script and scriptCode in a response? If there's a standard for the name mapping, is there much point is providing both? Responses would be smaller, and we don't need to add a bunch of partial names to the `custom-words.txt` shared by every service?

`script` was added in a previous version, with some discussion with some of our customers it was determined that mapping the text script to a standard like we did with `iso6391Name` would be beneficial so we added the new `scriptCode`. We are keeping `script` as to not break a customers that want to use the latest preview version that were using the previous preview version.

**Comment by quentinRobinson** [comment]
> Also, why is this targeting main? Main is for completed api-versions that should generally not be changed. If 2023-11-15-preview is in development, your team should be working in a feature branch - ideally created in https://aka.ms/openapihub so it gets a baseline commit (we are deprecating the dev/ folder).

The development of this preview version was thought to be completed. This change was a last-minute request by some customers that we determined was important enough to push to this preview version.

**Review by heaths — APPROVED** [review]

**Review by johanste — APPROVED** [review]

**Comment by heaths** [comment]
@maririos should the `FalsePositive-BreakingChange` label effectively "unrequire" the `Swagger BreakingChange` check? I'll apply the approval label as a workaround for now.

**Comment by heaths** [comment]
Requested re-run of the `Automated merging requirements met` check but doesn't seem like it's kicking off yet. Set to auto-merge if/when it does.

**Pull request merged**
