### PR TITLE
Added new api version 2019-09-01, which changed the soft delete behavior

### PR DESCRIPTION
**Pull request by kerberous**
New behavior: new key vault will default to  soft-delete being on (or true), if not explicitly specified.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by yaohaizh** [comment]
@kerberous, for new version of API changes, please first commit the previous version that the change based on.   Then, make commits for the new changes.  In this way, we could focus on reviewing the diff.

**Review by yaohaizh — CHANGES_REQUESTED** [review]
Commit history is not suitable for review.

**Comment by kerberous** [comment]
> @kerberous, for new version of API changes, please first commit the previous version that the change based on. Then, make commits for the new changes. In this way, we could focus on reviewing the diff.

Made changes as suggested, please review again.

**Comment by yaohaizh** [comment]
@kerberous please fix the CI errors: https://dev.azure.com/azure-sdk/public/_build/results?buildId=171747&view=logs&j=f10f5372-40ed-54fc-caa4-b1cb5bd1252b&t=d3b2b841-a93b-5fa5-47c3-d8c4f6eae6e3&l=21

**Comment by kerberous** [comment]
> @kerberous please fix the CI errors: https://dev.azure.com/azure-sdk/public/_build/results?buildId=171747&view=logs&j=f10f5372-40ed-54fc-caa4-b1cb5bd1252b&t=d3b2b841-a93b-5fa5-47c3-d8c4f6eae6e3&l=21

I fixed referencing the new json files except the examples, please advise how to fix that

**Comment by yaohaizh** [comment]
@ruowan could you help about how to fix the example links? Thanks.

**Comment by ruowan** [comment]
Hi @kerberous. Avocado CI passed. Example JSON files are already referenced. You need to fix the ModelValidation error.

**Review by yaohaizh — APPROVED** [review]

**Pull request merged**
