### PR TITLE
[DO NOT MERGE] Add complex object limit to ServiceStats response

### PR DESCRIPTION
**Pull request by enjaimes**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by sarangan12 — APPROVED** [review]

**Review by bitsforthought — CHANGES_REQUESTED** [review]
The change looks good, but we should hold off merging this until the actual API change is deployed to our dogfood environment and we have validated it via the .NET SDK tests.

**Comment by enjaimes** [comment]
> The change looks good, but we should hold off merging this until the actual API change is deployed to our dogfood environment and we have validated it via the .NET SDK tests.

Ack, I'll keep it as a draft until the API change is in.

**Review by sarangan12 — APPROVED** [review]

**Review by sarangan12 — APPROVED** [review]

**Comment by brjohnstmsft** [comment]
@enjaimes Let's make sure the SDK changes are ready to go before we merge this.

Also, in the future, please do not push merge commits. As long as there are no conflicts, your PR should still be in a mergeable state.

Regarding reviewers: A lot of different teams work in this repo, so GitHub is not very good at suggesting reviewers. There is a process in place to automatically assign the right reviewer to PRs in this repo.

**Review by bitsforthought — CHANGES_REQUESTED** [review]
There are many, many changes here that don't belong. Please don't push merge commits. You will probably have to create a new branch and re-submit the PR, but please get your SDK PR ready first (azure-sdk-for-net repo).

**Comment by brjohnstmsft** [comment]
@enjaimes I'm closing this for now. Please re-create it with just your changes (no merge commits) once your SDK PR is ready. We can talk offline about what's required for that.

**Pull request closed without merging**
