### PR TITLE
Feature/room api2023

### LINKED ISSUE #22616: [ACS Rooms] API Review
**IMPORTANT: This is just a placeholder, we are still actively working on our swagger and it is not ready for Azure Board Review at the moment.**

General Information for Rooms API Review: 

- Service name: ACS Rooms
- Key contact for this review: Minnie Liu
- Link to previous API version: [azure-rest-api-specs/communicationservicesrooms.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Rooms/preview/2022-02-01-preview/communicationservicesrooms.json)
- Description of the material to be reviewed/changed: [Rooms GA Changes](https://microsoft-my.sharepoint.com/:x:/p/mikehang/EboOXi6h9MhLiSbl4F3XBUgBxn_j5j-_VjRyIb-bOcKyqA?e=Tu8hS0)
- Link to swagger: [azure-rest-api-specs/communicationservicesrooms.json at 211d16d9e08ad2e6b336b7db7d20280d7d70f3c6 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/211d16d9e08ad2e6b336b7db7d20280d7d70f3c6/specification/communication/data-plane/Rooms/preview/2023-01-01-preview/communicationservicesrooms.json)
- Champion scenarios that briefly explain how developers will use your API: [Rooms API Champion Scenarios.docx](https://microsoft-my.sharepoint-df.com/:w:/p/peiliu/EXK13I5e4e1JjKSiGXiwT-wBpkE79SzopDz6eO3NA6TciA?e=BECH80)

### PR DESCRIPTION
**Pull request by minnieliu**
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*engagement record*](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/271/Azure-REST-API-Stewardship?anchor=rest-api-stewardship-process).

* Link to engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [x] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document:
* Previous Open API Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azapi) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azapi).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

fix https://github.com/Azure/azure-rest-api-specs/issues/22616

### CODE REVIEW

**Comment by minnieliu** [comment]
@johanste and @tg-msft We are failing a violation for breaking change. But this is only a breaking change between preview versions only and the Rooms Service has not GAed yet.

**Comment by minnieliu** [comment]
Outstanding questions: 
**GA Requirement:**
1. Do we need to have AAD authentication as part of the Security definitions? Is it a requirement for GA?

**Preview Version Timeline:**
1. How long do we need to wait to deprecate an API version? From which point?

**Naming:**
1. PatchParticipantsRequest body property called "partipants", should be it "value" instead?
2. Shall we use CreatedAt or CreatedOn for Room CreatedDateTime?

**Design:**
1. For CREATE room, should we include participants as part of the request?
    - If the Azure board says up to you, stick with what we have.
    - If asked whether partial success is accepted - no it will either
2. For PATCH participants, should we return empty object in response or return the first page of the collection?
3. For PATCH participants dictionary, we are following System.Text.Json pattern for duplicates which respects the last entry. "Last value wins"
4. Should participant roles be required or optional? Keeping in mind that there is a possibility in the for clients to set what the default role should be - is this unusual design pattern?
Roles are extensible enum, in the future we will have custom roles as a separate custom role                 
property and a custom enum value "custom" to indicate custom role.
5. For PATCH participants: {"rawId": {}} where the object is empty, we are setting the role value to be default and continuing with PATCH. Is this the right behaviour?

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Review by anuchandy — APPROVED** [review]

**Comment by anuchandy** [comment]
Adding "Approved-ModelValidation", as this is identified as false positive and confirmed with Azure Board as well.

**Pull request merged**
