### PR TITLE
ApplicationInsights: Uses plural for operation group name

### PR DESCRIPTION
**Pull request by anuchandy**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by lmazuel — APPROVED** [review]
Fine on the Python side, package is still in preview and allow breaking change. I will just mention it in the ChangeLog

**Review by fearthecowboy — APPROVED** [review]

**Comment by fearthecowboy** [comment]
@ericc1103 -- Operation IDs are intended to be `<plural-noun>_<verb>` -- this corrects a glitch in the spec. Please review and approve.

@amarzavery  @vladbarosan  @dsgouda @shahabhijeet   -- FYI - this is technically a breaking change, but necessary to correct a bad API.

**Review by dsgouda — APPROVED** [review]
LGTM

**Review by jpiyali — APPROVED** [review]

**Review by ericc1103 — APPROVED** [review]

**Comment by vladbarosan** [comment]
@fearthecowboy are we good to merge here ?

**Pull request merged**
