### PR TITLE
Add new property for CORS settings

### PR DESCRIPTION
**Pull request by juniwang**
#### Changes:
Add new property for CORS settings which enables customers to configure Cross-Origin Resource Sharing.

#### Tests:
all validations documented on https://github.com/Azure/adx-documentation-pr/wiki/Swagger-Validation-Tools passed.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by daschult** [comment]
@openapi sdkautomation rebuild

**Comment by sanjaiganesh** [comment]
pls add this new property under new api version, to avoid confusion when client uses mix of new and old sdks. 
(one call to populate 'cors' property and one call with old sdk without 'cors' property)

**Comment by juniwang** [comment]
Do we have to add a new api-version? Our latest RP is compatible with older SDKs. It works fine with or  without the cors property

**Comment by KrisBash** [comment]
> Do we have to add a new api-version? Our latest RP is compatible with older SDKs. It works fine with or without the cors property

@juniwang The concern with adding a writable property in an existing API version is that there will be a mix of clients that are on older and newer versions. If the property is set by a latest version client, and the resource is then modified by a downlevel client, your service cannot know whether the property was intentionally removed or the result of a downlevel client.

**Comment by juniwang** [comment]
> @juniwang The concern with adding a writable property in an existing API version is that there will be a mix of clients that are on older and newer versions. If the property is set by a latest version client, and the resource is then modified by a downlevel client, your service cannot know whether the property was intentionally removed or the result of a downlevel client.

Thanks @KrisBash. We got the point. It's a good pattern to add new API version to avoid confusion. But for this perticular case, the `CORS` settings by design CANNOT be removed. Clients are only allowed to modify it by passsing in an non-empty value.  A value of `null` (either using older SDK or intentionally set in newer ones) results in remaining the current value unchanged. A default non-empty value will be set while creating(for both older clients and newer clients with `null` value). Does this make sense to keep using the same api-version?

**Comment by KrisBash** [comment]
> > @juniwang The concern with adding a writable property in an existing API version is that there will be a mix of clients that are on older and newer versions. If the property is set by a latest version client, and the resource is then modified by a downlevel client, your service cannot know whether the property was intentionally removed or the result of a downlevel client.
> 
> Thanks @KrisBash. We got the point. It's a good pattern to add new API version to avoid confusion. But for this perticular case, the `CORS` settings by design CANNOT be removed. Clients are only allowed to modify it by passsing in an non-empty value. A value of `null` (either using older SDK or intentionally set in newer ones) results in remaining the current value unchanged. A default non-empty value will be set while creating(for both older clients and newer clients with `null` value). Does this make sense to keep using the same api-version?

I think that's ok.

**Review by KrisBash — APPROVED** [review]
Approving for ARM

**Review by Juliehzl — APPROVED** [review]

**Pull request merged**
