### PR TITLE
Revert "[Hub Generated] Review request for Microsoft.Maps/Microsoft.Maps to add version preview/1.0"

### PR DESCRIPTION
**Pull request by chcmsft**
Reverts Azure/azure-rest-api-specs#14965

### CODE REVIEW

**Comment by chcmsft** [comment]
The implementation release is ongoing.
In case there is any issue, I'll remove the tag and merge this ASAP.
otherwise, we can close the PR.

**Comment by JackTn** [comment]
Hi, @chcmsft. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @chcmsft. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @chcmsft. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
