### PR TITLE
Sorted the original authoring swagger for 2023-04-15-preview and 2023-04-01

### PR DESCRIPTION
**Pull request by amber-ccc**
…rsations)

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Review by heaths — CHANGES_REQUESTED** [review]
Is this really necessary? It makes validation that nothing was broken very difficult for versions of the file to unnecessarily change. And sort order is insignificant so this seems to have no purpose. Please explain.

**Comment by allenjzhang** [comment]
> Is this really necessary? It makes validation that nothing was broken very difficult for versions of the file to unnecessarily change. And sort order is insignificant so this seems to have no purpose. Please explain.

This is needed as part of the TypeSpec migration. It sorts into same order as TypeSpec generated order for easier visual comparison.

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Please run prettier to format the swagger.

**Comment by heaths** [comment]
> This is needed as part of the TypeSpec migration. It sorts into same order as TypeSpec generated order for easier visual comparison.

@allenjzhang why is any comparison order-based? That seems very problematic. And by changing the order now, you're making it hard to compare with previous versions of itself as well. So why not ignore order and semantically compare? As I understand it, APIView is now capable of doing so. /cc @maririos

**Pull request closed without merging**
