### PR TITLE
Add import to the JSON Web Key Operations

### PR DESCRIPTION
**Pull request by vakkinep**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by amitbapat — APPROVED** [review]
Looks good.

**Review by msfcolombo — APPROVED** [review]

**Comment by schaabs** [comment]
@heaths could you take a look at this and see how it fits into your swagger refactoring?

**Comment by heaths** [comment]
I have a PR started in the private fork for preview-7.1 we should probably rebase this on. I can clean it up for public release, but is otherwise a split of services we wanted for maintainability.

**Comment by heaths** [comment]
I've also already included this in the aforementioned PR.

**Review by jkapil — APPROVED** [review]

**Comment by jkapil** [comment]
> I've also already included this in the aforementioned PR.

@heaths Does this PR needs to be abandoned if you are bringing this change with your PR ?

**Comment by heaths** [comment]
The timeline for my changes is not quite solidified. For now, I recommend changing your branch to target the new preview-7.1 branch and files (i.e. rebase, but also move the changes to preview/7.1/keyvault.json) and we can get it approved and merged. I'll just have to do a "manual rebase" later when I pull my split-files change in.

**Review by heaths — CHANGES_REQUESTED** [review]
Even if the swagger review board allows modifying a shipped version, 7.0 already shipped. This is the wrong file. You need to modify stable/7.0/keyvault.json. /cc @adrianhall @johanste

**Pull request closed without merging**
