### PR TITLE
typo: network/resource-manager/Microsoft.Network

### PR DESCRIPTION
**Pull request by nschonni**
- Maxium -> Maximum
- Double word "curcuit"
- Prodiver -> Provider
- Spepcified -> Specified
- Succeded -> Succeeded
- crossconnection -> cross connection
- retriving -> retrieving
- Etherype -> Ether type
- seperator -> separator
- asterix -> asterisk
- Aure -> Azure
- Prefx -> Prefix
- profilees -> profiles
- conatinaer -> container
- configruation -> configuration
- outcoming -> outgoing
- snaphots -> snapshots
- Traffice -> Traffic
- Policys -> Policies
- specificed -> specified
- VPNsite -> VPN site
- provisisoning -> provisioning
- Double word "for"
- vpnclients -> VPN clients
- Trim trailing spaces

### CODE REVIEW

**Review by hovsepm — APPROVED** [review]

**Comment by hovsepm** [comment]
@nschonni please rebase your PR.

**Comment by nschonni** [comment]
@hovsepm rebased

**Comment by hovsepm** [comment]
@nschonni metoo :)

**Comment by hovsepm** [comment]
@nschonni I still have the massage that "This branch is out-of-date with the base branch" could you rebase with `upstream/december-network-release`?

**Comment by nschonni** [comment]
@hovsepm fetched and ran `git pull --rebase upstream december-network-release` again

**Comment by hovsepm** [comment]
@MikhailTryakhov could you review and explicitly sign-off on this PR?

**Pull request closed without merging**
