### PR TITLE
[PostgreSQL] New api version 2023-03-01-preview - Migrations API property update, enum values update. Network property changes ported.

### PR DESCRIPTION
**Pull request by ambrahma**
### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [X ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [x] Other, please clarify

1. Added fix for network property update from the earlier version to new api version 2023-03-01-preview for which SDK is not yet published.
2. Migrations api enum property values are being updated from Enabled / Disabled to True / False.
3. Added 2 new string properties to SecretParameters object for Migrations api.

Added breaking change review => [Scenario 23568995](https://msazure.visualstudio.com/One/_workitems/edit/23568995): [PostgreSQL] Breaking changes - Add changes to new preview api version for which there is no SDK yet

  3. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month. **ASAP**
  5. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [X ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [X ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version). Note that this doesn't apply if you are trying to merge a PR that was previously in the private repository.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview_breakingchanges).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](http://aka.ms/aprwiki))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ambrahma** [comment]
> Hi @ambrahma, one or multiple breaking change(s) is detected in your PR. Please check out the breaking change(s), and provide business justification in the PR comment and @ PR assignee why you must have these change(s), and how external customer impact can be mitigated. Please ensure to follow [breaking change policy](https://aka.ms/AzBreakingChangesPolicy) to request breaking change review and approval before proceeding swagger PR review. **Action**: To initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes). If you want to know the production traffic statistic, please see [ARM Traffic statistic](https://portal.azure-devex-tools.com/api/pr/query-traffic?pr=Azure/azure-rest-api-specs/24087&days=5). If you think it is false positive breaking change, please provide the reasons in the PR comment, report to Swagger Tooling Team via https://aka.ms/swaggerfeedback. **Note**: To avoid breaking change, you can refer to [Shift Left Solution](https://aka.ms/shiftleft) for detecting breaking change in early phase at your service code repository.

Added breaking change review => [Scenario 23568995](https://msazure.visualstudio.com/One/_workitems/edit/23568995): [PostgreSQL] Breaking changes - Add changes to new preview api version for which there is no SDK yet

**Review by ankhyk — APPROVED** [review]

**Comment by keryul** [comment]
@konrad-jamrozik can we approve the Avocado error?

**Comment by konrad-jamrozik** [comment]
> @konrad-jamrozik Konrad Jamrozik FTE can we approve the Avocado error?

Avocado provides guidance how to address failures it reported, here:

- https://github.com/Azure/azure-rest-api-specs/pull/24087/checks?check_run_id=13682788071
- https://github.com/Azure/azure-rest-api-specs/pull/24087#issuecomment-1558618327

@ambrahma can you follow the guidance provided above and if you think it is incorrect or doesn't apply, clarify why? Thanks!

**Comment by ambrahma** [comment]
> > @konrad-jamrozik Konrad Jamrozik FTE can we approve the Avocado error?
> 
> Avocado provides guidance how to address failures it reported, here:
> 
> * https://github.com/Azure/azure-rest-api-specs/pull/24087/checks?check_run_id=13682788071
> * [[PostgreSQL] New api version 2023-03-01-preview - Migrations API property update, enum values update. Network property changes ported. #24087 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24087#issuecomment-1558618327)
> 
> @ambrahma can you follow the guidance provided above and if you think it is incorrect or doesn't apply, clarify why? Thanks!

Guidance says that I need to consult API review team (which is essentially a group I need to join and get approval) to take up this change. I am worried how long will this take overall for approval etc. The fixes in this PR are required for SDK release for api version 2023-03-01-preview and I do not want to miss current cycle. I am also checking with my team if this is ok and what will be implications for the end users who would already be using the same SDK for different services?

**Comment by ambrahma** [comment]
> > > @konrad-jamrozik Konrad Jamrozik FTE can we approve the Avocado error?
> > 
> > 
> > Avocado provides guidance how to address failures it reported, here:
> > 
> > * https://github.com/Azure/azure-rest-api-specs/pull/24087/checks?check_run_id=13682788071
> > * [[PostgreSQL] New api version 2023-03-01-preview - Migrations API property update, enum values update. Network property changes ported. #24087 (comment)](https://github.com/Azure/azure-rest-api-specs/pull/24087#issuecomment-1558618327)
> > 
> > @ambrahma can you follow the guidance provided above and if you think it is incorrect or doesn't apply, clarify why? Thanks!
> 
> Guidance says that I need to consult API review team (which is essentially a group I need to join and get approval) to take up this change. I am worried how long will this take overall for approval etc. The fixes in this PR are required for SDK release for api version 2023-03-01-preview and I do not want to miss current cycle. I am also checking with my team if this is ok and what will be implications for the end users who would already be using the same SDK for different services?

hi @konrad-jamrozik , I have started another PR for this folder structure change. Basically we want to make sure that same python SDK gets generated for both postgresql single server and postgresql flexible server. This is to avoid downstream issues like letting customers know that there is separate (python SDK) package created for postgresql flexible server vs single server. Also then we need to worry about consuming multiple packages for CLI as currently even our CLI releases are couple together. Moreover currently MySQL single server and MySQL flexible servers are also using same packages. This would be a bigger item. Hence requesting you to allow this current PR to be merged manually, while the issues get ironed out in another PR. Also this will ensure that we do not miss the deadline for the current SDK release and make packages and CLI available to our end users as per our commitments

**Comment by xiaoxuqi-ms** [comment]
Hi @konrad-jamrozik , thanks for reviewing this pr, however, the multiple tag is not introduced in this pr, we support both single server and flexible server so we have two tags for both scenario. Could you kindly help to approve this avocado errors? Many thanks.

**Comment by konrad-jamrozik** [comment]
@rkmanda @weshaggard can you advise with priority?

**Comment by weshaggard** [comment]
@ambrahma I'm going to merge your PR but please continue your work on fixing the errors otherwise this will continue to come up and eventually end up blocking you.

**Pull request merged**
