### PR TITLE
Review request for Microsoft.ContainerService to add version 2022-05-02-preview

### PR DESCRIPTION
**Pull request by FumingZhang**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
    Already deployed to all global regions by 2022-05-29. Plan to complete the deployment to sov clouds by 2022-06-03.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
    2022-06-01.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [x] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Dear review board, I would like to clarify the failures in the CI checks. For short, **all the errors are not relevant to the changes in this PR** and have happened in our previous PRs like [03-01](https://github.com/Azure/azure-rest-api-specs/pull/18686) and [04-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18900).

For [SDK azure-powershell](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647332428), it happened in our previous PR [04-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18900)/[04-01](https://github.com/Azure/azure-rest-api-specs/pull/18991). This used to be optional and is enabled recently. Confirmed with owner @dolauli, this would not work for some modules and could be ignored.

For [SDK azure-sdk-for-go](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647331081), this also happened in our previous PR [04-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18900)/[04-01](https://github.com/Azure/azure-rest-api-specs/pull/18991) and is caused by another PR [#18789](https://github.com/Azure/azure-rest-api-specs/pull/18789). cc Golang SDK owner @ArcturusZhang.

For [SDK azure-sdk-for-net](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647331709), it happened in our previous PR [04-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18900)/[04-01](https://github.com/Azure/azure-rest-api-specs/pull/18991). I suppose this should be a known issue. According to the error log, the reason for the error is the permission problem when the pipeline is executed, which has nothing to do with this PR.

For [Swagger Avocado](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647293877), it happened in our previous PR [04-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/18900). The [2019-10-27-preview/openShiftManagedClusters.json](https://github.com/Azure/azure-rest-api-specs/blob/c945c2816fb841df0367e559f3b831a6c733cd5e/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2019-10-27-preview/openShiftManagedClusters.json) mentioned in the error log is a deprecated swagger file, Currently, only managedCluster is supported by us, the rest such as containerService, openShiftManagedClusters, location, etc. are all deprecated. These errors started appearing after [this update](https://github.com/Azure/avocado/pull/78) of Avocado. Would really appreciate if some mechanism could be provided to disable the alarms, cc owner @ruowan.

For [Cross-Version Breaking Changes](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647294203) and [Swagger SDK Breaking Change Tracking](https://github.com/Azure/azure-rest-api-specs/pull/19262/checks?check_run_id=6647294444), it's caused by rebranding of Microsoft Defender. Feature owner @orparnes has got the approval from Breaking Change Review Board.

**Comment by orparnes** [comment]
As for the SecurityProfile breaking change:

Azure Defender product recently changed its name to **Microsoft Defender for Cloud** (or in short: defender).
Starting July 2021, this feature was in preview mode under a **feature flag**. It was also mentioned in all relevant documentations and references.
Towards GA, we wish to align and standardize this section to reflect the new product name as well as support future features, which was not planned when this feature first introduced.
The new API designed to support those future features and doesn't have the feature flag.
When we first added the feature, AKS didn't used the preview APIs approach, therefore it was added to the stable one. New defender features will begin as part of future preview APIs and will be migrated to stable one after it.

**Comment by mentat9** [comment]
@FumingZhang - Please create a new PR following this process (and check the box when you submit): 

**[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).**

Note: if you don't want to use OpenAPIHub to set up your new API version PR, please create it manually by copying the current API version files [unmodified] to the new API version folder and commit that as your first commit of the PR. Apply other changes in subsequent commits. This is required for ARM review. 

Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html#introduction.

**Comment by mentat9** [comment]
Corrected comment/labels.

**Comment by mentat9** [comment]
>           "readOnly": true,

It's a cross-version breaking change to change an existing read/write property to readOnly.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:3258 in c945c28. [](commit_id = c945c2816fb841df0367e559f3b831a6c733cd5e, deletion_comment = False)

**Comment by mentat9** [comment]
>         "enabled": {

ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review).

Best approach is to choose a better property (e.g. activationState: { "Active", "Disabled" }). This type of property is easier for customers to understand and use. 

This approach also allows adding new values in the future without adding a new API version. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.) values which is still better than boolean, since enums allow adding values later without requiring a new API version (e.g. "Unknown", "Default", etc.), and also allow values other than just true/false.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:6041 in c945c28. [](commit_id = c945c2816fb841df0367e559f3b831a6c733cd5e, deletion_comment = False)

**Comment by mentat9** [comment]
>           "description": "Whether to enable AzureBlob CSI Driver. The default value is false."

Suggest using the full name rather than the acronym.

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:6175 in c945c28. [](commit_id = c945c2816fb841df0367e559f3b831a6c733cd5e, deletion_comment = False)

**Comment by mentat9** [comment]
>         "enabled": {

Suggest enum instead of boolean (see earlier comment).

---
Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:6687 in c945c28. [](commit_id = c945c2816fb841df0367e559f3b831a6c733cd5e, deletion_comment = False)

**Comment by mentat9** [comment]
@FumingZhang - I added the breaking change review label due to breaking changes I discovered during review. ARM review will resume after the breaking change label is addressed. Please ping the current APR review oncall after that's been done.

**Comment by FumingZhang** [comment]
> > ```
> >       "readOnly": true,
> > ```
> 
> It's a cross-version breaking change to change an existing read/write property to readOnly.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:3258 in [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e). [](commit_id = [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e), deletion_comment = False)

Thanks for pointing this out. As early as [2022-03-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-03-02-preview/managedClusters.json#L3021) API version, we added this field, but the readonly attribute was not set at that time. Then in the latest stable API version [2022-04-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-04-01/managedClusters.json#L2673-L2674), this field was added with an additional readonly attribute, but feature owner forgot to update and add the readonly attribute in its corresponding preview API version 2022-04-02-preview. So we plan to align it with the stable API through this new preview API.

**Comment by cvvz** [comment]
> > ```
> >     "blobCSIDriver": {
> > ```
> 
> ARM recommends against using acronyms or abbreviations in property names. I see you've already gone through that door with CSI, so I don't expect you to change that and make it inconsistent with the other properties, but you should at least spell it out in the description.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:6063 in [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e). [](commit_id = [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e), deletion_comment = False)

Thanks for pointing this out. I understand the recommendation is helpful to avoid confusion for most circumstances, but actually the abbreviation `CSI Driver` is quite common and clear for those who are using AKS, since they must be familiar with the fundamental knowledge of Kubernetes, including the term `CSI Driver`. And also other CSIDrivers like `fileCSIDriver` and `DiskCSIDriver` already rolled out and none of our customers have question about what `CSI Driver` stands for.

**Comment by cvvz** [comment]
> > ```
> >     "enabled": {
> > ```
> 
> ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use. Ref: https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review.
> 
> Best approach is to choose a better property (e.g. activationState: { "Active", "Disabled" }). This type of property is easier for customers to understand and use.
> 
> This approach also allows adding new values in the future without adding a new API version. Even if you only ever want two values, you can have a string enum with True/False (or Enabled/Disabled, etc.) values which is still better than boolean, since enums allow adding values later without requiring a new API version (e.g. "Unknown", "Default", etc.), and also allow values other than just true/false.
> 
> Refers to: specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-05-02-preview/managedClusters.json:6041 in [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e). [](commit_id = [c945c28](https://github.com/Azure/azure-rest-api-specs/commit/c945c2816fb841df0367e559f3b831a6c733cd5e), deletion_comment = False)

Thanks for pointing this out. I've read the docs and agree that in some circumstances enum is better than boolean since enum is the superset of boolean. However here we use this field to act like a switch to enable/disable the`blobCSIDriver` addon, but not a state indicator(which maybe in the state of `Unknown`). Also I think we should keep consistent with other CSIDrivers.

**Comment by orparnes** [comment]
> Hi Chris. We're previously consulted about this change and noted that the breaking-change process is not required in this case.
image

**Comment by mentat9** [comment]
Thanks for the additional context re: breaking change review.

**Review by honghr — APPROVED** [review]

**Pull request merged**
