### PR TITLE
[Hub Generated] Publish private branch 'tarunkhattar/2024-02-01'

### PR DESCRIPTION
**Pull request by khattartarun**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/published%2FAzure%2Fazure-rest-api-specs-pr%2Ftarunkhattar%2F2024-02-01...main/).
# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- For help with Step 2 / "ARM review", see https://aka.ms/azsdk/pr-arm-review.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [x] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by khattartarun** [comment]
The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/16667](https://github.com/Azure/azure-rest-api-specs-pr/pull/16667)

**Review by sathiyan-sivathas — APPROVED** [review]

**Comment by khattartarun** [comment]
The pipeline reporting "Breaking Change(Cross-Version)" because its comparing against previous stable release (2023-09-01). The TagsObject was changed to IdentityandTagsObject in filemobileNetwork.json in the 2023-10-01-private release via PR https://github.com/Azure/azure-rest-api-specs-pr/pull/15883 and it was granted breaking change approval. Same change is being flagged again here.

**Comment by mentat9** [comment]
> The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/16667](https://github.com/Azure/azure-rest-api-specs-pr/pull/16667)

@khattartarun - Do you mean you are moving the entire API version unchanged from the private **repo** to public?

**Comment by khattartarun** [comment]
Yes, api version 2024-02-01 is recently added in RPSaaSMaster and want to add same here in public repo.

________________________________

**Comment by mentat9** [comment]
> The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/16667](https://github.com/Azure/azure-rest-api-specs-pr/pull/16667)

@khattartarun - With the conversion to typespec, it's not possible for reviewers to compare the new API version to the one that was signed off (written in swagger JSON). Can you elaborate on what "based on" means in this context? What is going into this new API version?

**Comment by khattartarun** [comment]
> > The PR is created based on the updates in the private branch. The updates in the PR has already been reviewed and approved with this PR [Azure/azure-rest-api-specs-pr/16667](https://github.com/Azure/azure-rest-api-specs-pr/pull/16667)
> 
> @khattartarun - With the conversion to typespec, it's not possible for reviewers to compare the new API version to the one that was signed off (written in swagger JSON). Can you elaborate on what "based on" means in this context? What is going into this new API version?

@mentat9 Sure, let me elaborate about this new api version 2024-02-01. This API version is next stable release after 2023-09-01 and it includes below two changes from preview releases:
1) https://github.com/Azure/azure-rest-api-specs-pr/pull/13388, commit https://github.com/Azure/azure-rest-api-specs-pr/pull/13388/commits/beccc0f07380cb2b47ff4bc8b1bb52dd180d8f67 (This was added to 2023-07-01-preview but not in 2023-09-01)
2)https://github.com/Azure/azure-rest-api-specs-pr/pull/15883 (This was added to 2023-10-01-preview)

This new stable release is added in private repo via https://github.com/Azure/azure-rest-api-specs-pr/pull/16667 

Please let me know if you need more details.

**Comment by khattartarun** [comment]
Hi @mentat9 I believe I have answered your query, let me know if anything you are waiting for any more clarification?
@visingla-ms - this is same PR you approved for private repo https://github.com/Azure/azure-rest-api-specs-pr/pull/16667.

**Comment by ms-henglu** [comment]
Hi @khattartarun , to get this PR merged, it still needs an approval for the GO SDK breaking change.

**Comment by khattartarun** [comment]
@Alancere Can I get approval for CI-BreakingChange-Go as you provided here https://github.com/Azure/azure-rest-api-specs-pr/pull/16667?

**Comment by khattartarun** [comment]
> Hi @khattartarun , to get this PR merged, it still needs an approval for the GO SDK breaking change.

@ms-henglu I have asked the person who provided CI-Breakingchange-Go approval for same changes in the private repo. But is it possible for you to provide and proceed with merge?

**Pull request merged**
