### PR TITLE
Add  Dynamic Compute mode

### PR DESCRIPTION
**Pull request by naveedaz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@naveedaz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (naveeda). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@naveedaz does this also solve #194?

**Comment by amarzavery** [comment]
@lmazuel - The CI is failing due to a weird reason. Can you please take a look at this ASAP?

**Comment by devigned** [comment]
It's based on the code generation in Python. It appears one of the expected specs is missing from the specs repo specified here: https://github.com/Azure/azure-sdk-for-python/blob/master/swagger_to_sdk_config.json

**Comment by hovsepm** [comment]
@devigned we cannot block this PR because of our infra issue.

**Pull request merged**
