### PR TITLE
Change storagecache name max length from 31 to 80

### PR DESCRIPTION
**Pull request by jsmartt**
Related to https://github.com/Azure/azure-sdk-for-ruby/issues/2759

This updates the storagecache name regex to support a maximum length of 80, not 31. This is consistent with the Azure console validation messages, and with my own experience creating caches with names up to 80 characters long. This confusion may have originated from cache storage target name restrictions of 31 characters, which is correct.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by njuCZ** [comment]
hello @jsmartt , becasue of the new CI rule, field with `discriminator` must be `required`. we should add `required` for field `StorageTarget`. Of course this is a problem of the original file, could you please fix this in your PR?

**Comment by jsmartt** [comment]
@njuCZ, I think I found where to add the `required` field... but please verify. If it's not correct, please let me know a line number.

**Comment by romahamu** [comment]
@jsmartt, @njuCZ 
There is a new version coming which has this change. 
https://github.com/Azure/azure-rest-api-specs/pull/8403

**Comment by jsmartt** [comment]
Great, thanks @romahamu. It looks like that PR has a new `2020-03-01` API version definition, but doesn't fix this one (`2019-11-01`). Unless I'm missing something...

**Comment by njuCZ** [comment]
@jsmartt May I know the status of current PR? It seems long time no update and there is still a Semantic CI error needs to be addressed. If this PR is oudate, I am going to close it

**Comment by jsmartt** [comment]
@njuCZ, yes, this is still valid. I can't speak to your testing process though. I see no reason that these changes would break any tests, so maybe there's an issue with the testing process, not this PR?

**Comment by jsmartt** [comment]
@njuCZ, I've tried a few different ways to fix the semantic check, I don't think it's something that this PR introduces, but rather an existing issue with the file, or a change to the testing process after this file was created. Feel free to add a commit to fix those issues if you'd like, but I don't have the time to figure out the intricacies of the expected format. That gets a bit outside of the purpose of this PR, which is to fix a different issue that is affecting validations in the SDKs.

**Comment by njuCZ** [comment]
@jsmartt just having a look at the pipeline, it says `targetType` in `StorageTarget` is a discriminator field, discriminator must be a required property, which cause this Semantic error. Could you please mark it as required in this swagger file?

**Comment by jsmartt** [comment]
@njuCZ, can you provide a line number and the code to do so? I've tried a few different times to no avail.

**Comment by njuCZ** [comment]
@jsmartt we could find error message here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=457263&view=logs&jobId=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a

which says
```
##[error]Semantically validating  specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2019-11-01/storagecache.json:

 error : 
code: OAV131
error: DISCRIMINATOR_NOT_REQUIRED
name: discriminator
params:
  - targetType
message: discriminator must be a required property.
path:
  - 'definitions,StorageTarget'
```

please check `targetType` field in this file, and mark it as `required`.

**Comment by jsmartt** [comment]
@njuCZ, I've added a commit, but it's clearly not the correct fix. As I mentioned above, I've tried a few different ways to fix the semantic check, but I can't figure it out. Feel free to add a commit to fix those issues if you'd like, but I don't have the time to figure out the intricacies of the expected format. If you would like me to add fixes to this PR for other issues, please include the code you'd like me to add and the line number to add it to. This all is outside of the purpose of this PR, which is to fix a different issue that is affecting validations in the SDKs.

**Comment by njuCZ** [comment]
@jsmartt please follow this example to mark it as required: https://github.com/azure/azure-rest-api-specs/blob/master/specification/cdn/resource-manager/Microsoft.Cdn/stable/2019-06-15/cdn.json#L2284

**Comment by jsmartt** [comment]
@njuCZ, ok, I've added the requested change, and the semantic check is passing now. I had to move the location of the discriminator because it was in the wrong location; this places it in the same location as the [updated spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2020-03-01/storagecache.json#L1526).

**Review by njuCZ — APPROVED** [review]

**Pull request merged**
