### PR TITLE
Notification Hubs RP: adding API version 2023-01-01-preview

### PR DESCRIPTION
**Pull request by kmiecikt**
This PR adds a new preview API version for Notification Hubs RP - `2023-01-01-preview`. This version includes:
1. New features, including:
    - Private Link & network-level access control
    - Supporting new PNS (Push Notification Service) types: Browser, Xiaomi
    - Availability Zones
    - Namespace-level PNS credentials
2. Fixes for many of the required ARM Open API / RPC compliance requirements, including:
    - Correctly modeling some of the properties as enums (instead of strings)
    - Adding `x-ms-secret` annotation
    - Annotating the read-only and immutable properties
    - Annotating pageable operations
    - Marking some of the properties as deprecated (they are still supported though)
    - Fixes some of the response / request types that were incorrect in the previous swagger version (i.e. did not match the content that the RP actually expected / produced).

The Pull Request all contains updated examples. All of the requests were invoked & verified.

### CODE REVIEW

**Comment by kmiecikt** [comment]
To all reviewers: I'm fixing the issues found by automatic checks. When I resolve all the fixable ones, I will update this PR with details about the reported breaking changes.

**Comment by pilor** [comment]
> To all reviewers: I'm fixing the issues found by automatic checks. When I resolve all the fixable ones, I will update this PR with details about the reported breaking changes.

Marking changes requested to take this out of the review queue.  Please clear the label once you are done

**Comment by kmiecikt** [comment]
This is almost ready for review - we are making the last set of cleanups.

The "Swagger Breaking Change" check reports only single error in the last build, but earlier today it used to fail with the errors listed below.

The biggest challenge is the time since the last Swagger was published - over 6 years. Most of the new Open API / RP / ... requirements were added during that time. We tried to be as close as possible to the previous APIs, but almost all of the changes marked as "breaking" were required to fix the compliance issues. Also, please note that they only (or almost) affect the Swagger definition - the actual JSON content of requests / responses should be fully compatible with the older version.

# Rationale for reported breaking changes

## Rule 1034: Added Required Property

Namespace Location and SKU were always required, but not annotated correctly in Swagger.
Others should be fixed now.


## Rule 1048: AddedXmsEnum

The following three properties were modelled as string in Swagger, while they should be enums:

- `NamespaceProperties.ProvisioningState`
- `NamespaceProperties.Status`
- `PolicyKeyResource.PolicyKey`

The implementation already accepted only values that are now defined in enum, and rejected the rest.

## Rule 1011: Adding Response Code

The new swagger adds "default" response code with common `ErrorResponse` schema.

## Rule 1042: ChangedParameterOrder

The old Swagger version was inconsistent: the query, header and body parameters were mixed together.
The new Swagger defines common parameters in the same, predicable order for all operations:

- Path (`subscriptionId`, `resourceGroup`, `namespaceName`, ...)
- Query (`apiVersion`)
- Body

## Rule 1036: ConstraintChanged

The old Swagger did not define `minLength`, `maxLength` and `pattern` constraints, although they were enforced in our service implementation.

## Rule 1029: ReadonlyPropertyChanged

All the properties were already read-only in the old implementation, but were not correctly annotated in the previous Swagger file.

## Rule 1023: TypeFormatChanged

- The old Swagger version used its own `subscriptionId` parameter, which `uuid` as a format. The new version uses the shared parameter from common types, which is defined without this format.
- One of the properties used to be defined as `int32`, now is defined as `integer`.

## Rule 1033: RemovedProperty

- `ErrorResponse` The old Swagger used custom `ErrorResponse` object, which was incorrect - the actual service implementation responded with the actual shared schema.
  The new Swagger file references the common type instead of defining its own.
- `sku`: this was incorrect definition in the previous Swagger. All response types used to derive from the common `Resource` schema, which defined `sku` property. It was never accepted in requests nor returned in responses for types other than `NamespaceResource`

## Rule 1006: RemovedDefinition

- `NamespaceCreateOrUpdateParameters`: this type represented a subset of not-readonly properties from the `NamespaceResource`.
  To be compliant with OAPI021 (PUT/PATCH shouldn't fail for readonly properties) and OAPI030 (Ignore unchanged immutable properties), the new Swagger accepts the full `NamespaceResource` object in requests. It is a superset of previous definition.
- `NotificationHubCreateOrupdateParameters`: same as above.
- `SharedAccessAuthorizationRuleCreateOrUpdateParameters`: same as above.
- `PolicykeyResource`: the name of the previous type was incorrect. It was renamed to `PolicyKeyResource` in the new Swagger.
- `DebugSendParameters`: to verify - the previous declaration was likely incorrect.

## Rule 1003: RequestBodyFormatNoLongerSupported

The previous Swagger defined global `consumes` and `produces` section, which was inherited by all operations. As a result, even `GET` operations were defined as accepting `application/json`.
The new Swagger correctly defines the `consumes` and `produces` on operation level, and only for correct HTTP methods.

## Rule 1005: RemovedPath

The paths still exist, but now we use correct camelCase names:

```
Old: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NotificationHubs/namespaces/{namespaceName}/AuthorizationRules/{authorizationRuleName}
New: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NotificationHubs/namespaces/{namespaceName}/authorizationRules/{authorizationRuleName}
```

## Rule 1025: RequiredStatusChange

The properties were already required, but didn't have correct annotation in the Swagger. All requests without those properties failed.

## Rule 1026: TypeChanged

- Two properties on the response type represent counts, but were defined as number (double) in the old Swagger. There is no change in the actual output - we only define the response type as more restrictive, but user code that expects any number will still be able to parse it.
- One of the properties was defined as a dynamic object, while our actual responses always returned arrays.

## Rule 1047: XmsEnumChanged

- `NamespaceType.modelAsString` used to be defined as false, but it was incorrect - the actual response used strings.
- `AccessRights` - the same. We already used strings in both requests and responses, the annotation was incorrect.

## Rule 1044: XmsLongRunningOperationChanged

- Deleting namespace used to be a long-running operation. Now it a synchronous one that responds with 204.

**Comment by raosuhas** [comment]
@kmiecikt  Please do not overwrite the standard comments on the pull request description with your own text , you need to carefully respond to the questions and update all the checkboxes in it otherwise automation will not work correctly. 

ALso For this PR have you added the previous version as a base commit as per the instructions ?

**Comment by kmiecikt** [comment]
Sorry, I did not follow the official guidelines and did not include the base version in the first commit - I discovered them after opening the PR.

I used the Open API Hub to create a new PR: https://github.com/Azure/azure-rest-api-specs/pull/24072. I'm closing this one.

**Pull request closed without merging**
