### PR TITLE
Estebanreyl/data plane 07 2019 blobs

### PR DESCRIPTION
**Pull request by estebanreyl**
This is a WIP PR for testing and feedback related to the addition of blob path's for the azure container registries runtime Swagger specification.

### CODE REVIEW

**Review by raych1 — COMMENTED** [review]
@estebanreyl , the CI is stuck in progress. Maybe you need to close this PR and re-create a new one make sure the commit# is different otherwise the new PR will also reference the old CI.

**Comment by estebanreyl** [comment]
@raych1 I can do that, what do you mean by the commit # though? This is a WIP anyway so its not a huge deal,

**Comment by raych1** [comment]
@estebanreyl , commit no is used to associate the CI run. Pls make it different to trigger a new CI run.

**Comment by estebanreyl** [comment]
Oh I think I see. I am guessing you are referring to the first from here then? How would I make it different?

**Comment by raych1** [comment]
Not the first commit no, you could push a new commit.

**Comment by estebanreyl** [comment]
...So just push a new commit?

**Comment by raych1** [comment]
That's correct.

**Pull request closed without merging**
