### PR TITLE
[ACS - Call Automation] [Beta2] Api spec for 2023-06-15-preview 

### LINKED ISSUE #24370: [IC3 ACS Server Calling ] API Review
New API Review meeting has been requested.

**Service Name**: IC3 ACS Server Calling 
**Review Created By**: Fariba Haghbin
**Review Date**: 07/19/2023 09:00 AM PT
**Onboarding Record**: 
**PR**: https://github.com/Azure/azure-rest-api-specs/pull/24482
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: 

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/e41c69de-ef96-44ba-b287-0e012e7c13ae?view=edit&event=f3b368af-ff05-ee11-8f6e-000d3a3418aa)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by fhaghbin-msft**
# Data Plane API - Pull Request
Azure Communication Services Call Automation provides developers the ability to build server-based, intelligent call workflows, and call recording for voice and PSTN channels.

Following features are already exist in GA ACS's Call Automation:

## API Info: The Basics
**CreateCall**: Allows you to create a new outbound call. Once given information (target of the call, such as their phone number), Call Automation service will call the target end try to establish a call.

**AnswerCall**: Answer incoming call. This is another way to establish a call. For example, you can purchase Direct Offering phone number from Azure Portal to answer incoming call with Call Automation for that phone number.

**CallConnectionId**: CallConnectionId is returned when you establish a call with either Create or Answer above. This Id is to be used to do subsequent actions for the call. For example, if I want to play a media file in the call, pass both CallConnectionId and media file endpoint. Call Automation service will play the media file in the call.

**Callback Events**: Because of nature of a phone call, during the call, Call Automation Service will send back asynchronous events to notify the state of the call. Such as CallConnected and ParticipantsUpdated event.

**PlayCompleted Events**: This is the event that being received when play audio file to participants is successful and completed.

**RecognizeCompleted Events**: This is the event that being received when the recognized dtmf tone is completed.

**Callback Uri**: Expanding above Callback events - here is an example. When you CreateCall, you will get response of 201 right after Call Automation service received the request. However, this does not mean the call is established. It is dialing. Once the target call receiver answers their phone, the call is established and CallConnected event is sent. This event is sent back as Webhook to CallbackURi provided in CreateCall/AnswerCall.

**Play Audio File**: Plays audio file to participants in the call.

**Recognize Dtmf**: Recognize Dtmf input tone from call.

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
This is Public Preview release. See previous GA Pull Request here: https://github.com/Azure/azure-rest-api-specs/pull/23091
* [Design Document](https://learn.microsoft.com/en-us/azure/communication-services/concepts/call-automation/call-automation)
* [Hero Scenarios](https://microsoft.sharepoint-df.com/teams/ACSRecording/_layouts/15/Doc.aspx?sourcedoc=%7bE270E316-E4A9-46F3-AFC9-28175C1565C6%7d&file=Continuous%20Dtmf%20and%20Send%20Dtmf%20Sample%20For%20SDK%20review1.docx&action=default&mobileredirect=true&share=IQEW43DiqeTzRq_JKBdcFWXGAVJrTfaftRU_LjoAqJWClMU&cid=bbcbbf8e-128d-4485-bea3-83c5cf76b512)
* [API Spec Document](https://review.learn.microsoft.com/en-us/rest/api/azure-rest-preview/?view=azure-rest-preview&branch=result_d25e53f7-7b93-41f8-83e3-78112fe167cb)
* [Previous Open API Doc](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/CallAutomation/stable/2023-03-06/communicationservicescallautomation.json)
* [Specs comparison of GA and Beta2](https://openapihub.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi83ZTE1ODlhNDk4MTYyMjZkNzc5ODkyMjc1N2JmZjQzNTcyODYyMTlkL3NwZWNpZmljYXRpb24vY29tbXVuaWNhdGlvbi9kYXRhLXBsYW5lL0NhbGxBdXRvbWF0aW9uL3N0YWJsZS8yMDIzLTAzLTA2L2NvbW11bmljYXRpb25zZXJ2aWNlc2NhbGxhdXRvbWF0aW9uLmpzb24iLCJ0YXJnZXRVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi83ZTE1ODlhNDk4MTYyMjZkNzc5ODkyMjc1N2JmZjQzNTcyODYyMTlkL3NwZWNpZmljYXRpb24vY29tbXVuaWNhdGlvbi9kYXRhLXBsYW5lL0NhbGxBdXRvbWF0aW9uL3ByZXZpZXcvMjAyMy0wNi0xNS1wcmV2aWV3L2NvbW11bmljYXRpb25zZXJ2aWNlc2NhbGxhdXRvbWF0aW9uLmpzb24ifQ==)
* **Updated paths:** BYO Cogsvc changes for Answer/CreateCall, Mute API, Recognize Choices, Recognize Speech/SpeechOrDtmf, Continuous Dtmf Subscription, SendDtmf, Play TTS(Text To Speech), Play SSML(Speech Synthesis Markup Language)

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

### CODE REVIEW

**Comment by mentat9** [comment]
Removing ARM labels. ARM review doesn't apply to DP specs.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by JeffreyRichter** [comment]
@mikekistler I just had a meeting with this team, and they need another approver ASAP. Can you please approve this now?

**Review by mikekistler — APPROVED** [review]
I'm willing to approve this for preview with the understanding that the team will address the concern raised by the API Stewardship board regarding proper description of the polymorphism in the Playsource schema before GA.

**Pull request merged**
