### PR TITLE
[CDN][2024-02-01] Refactor the inheritance hierarchy for rule actions and conditions to fix Pandora SDK const conflict

### PR DESCRIPTION
**Pull request by t-bzhan**
… and conditions to fix Pandora SDK const conflict

# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

spec_pr_review_workflow_diagram

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been created in adherence to [OpenAPI specs PR creation guidance](https://aka.ms/azsdkdocs/createopenapispec)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [x] Other, please clarify:
    - Our existing swagger definition does not follow the best practice of polymorphism to define class inheritance hierarchy, a hard-coded property (typeName) with a single ENUM value is used in a lot of places for deserialization purpose. It will break the Hashicorp Pandora SDK generation which will impact Terraform integration for Azure Front Door Standard/Premium service. In our case, with so many ENUMs with the same name “typeName”, it will complain about const name conflict when generating Golang SDK: https://github.com/hashicorp/pandora/issues/2831. Azure SDK Track2 for Golang does not have the problem as they did some workaround to add prefixes when the name is conflicting, which is not recommended by Pandora team. This PR aims to refactor the inheritance hierarchy for rule actions/conditions to fix Pandora SDK const conflict.

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://aka.ms/azurerpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories")
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with ARM review (PR workflow diagram Step 2), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

### CODE REVIEW

**Comment by mikekistler** [comment]
@t-bzhan I have reviewed the PR changes and it looks like this is just changing the way polymorphism is described to be more in-line with Azure conventions, so I'm willing to approve the breaking changes at the REST API level. But I think you need to work with the SDK teams for any languages that are affected to minimize the impact there.

**Comment by TimLovellSmith** [comment]
ModelValidation errors need fixing, would be great to get that done before further ARM review

**Comment by t-bzhan** [comment]
> ModelValidation errors need fixing, would be great to get that done before further ARM review

Hi @TimLovellSmith , the ModelValidation errors are not related to this PR. Can we skip this step for now? I’ll submit a separate PR to address them after this one.

**Comment by TimLovellSmith** [comment]
> > ModelValidation errors need fixing, would be great to get that done before further ARM review
> 
> Hi @TimLovellSmith , the ModelValidation errors are not related to this PR. Can we skip this step for now? I’ll submit a separate PR to address them after this one.

ModelValidation is required to fix before merge

**Comment by t-bzhan** [comment]
> > > ModelValidation errors need fixing, would be great to get that done before further ARM review
> > 
> > 
> > Hi @TimLovellSmith , the ModelValidation errors are not related to this PR. Can we skip this step for now? I’ll submit a separate PR to address them after this one.
> 
> ModelValidation is required to fix before merge

Hi @TimLovellSmith , I understand the importance of maintaining correct Swagger definitions. However, I find the model validation errors a bit confusing. Specifically, the first two errors seem contradictory. The first error indicates that I added an additional id field in the example because our Swagger doesn’t define it. On the other hand, the second error complains that I’m missing the id because the resource definition is marked as x-ms-azure-resource: true. I attempted to move the id into the properties, but that approach didn’t work either. Could you kindly suggest the next steps to resolve this?
image

**Comment by TimLovellSmith** [comment]
I think having 'id' at the top level is the way to go but there might be something a bit 'off' with the way you are using x-ms-azure-resource actually. Just tagging your resource type with that doesn't give it any properties like 'id'. Instead, you should inherit from ProxyResource (or else TrackedResource).

**Comment by TimLovellSmith** [comment]
>         },

POST operations shouldn't normally return resources.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:2977 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "description": "Resource ID.",

What resource is it returning the ID of? a 'can migrate result' is not an azure resource.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:2969 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

POST request bodies should not be marked as x-ms-azure-resource, except perhaps in the very UNusual case they're creating a new resource

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:3054 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

[ARMBlockingComment] POST operations shouldn't normally return resources. Do you really need to return these properties? Consider deprecating or removing them, if not.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:3122 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>           "description": "Resource ID.",

of?

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:3108 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

I assume your Origins are modeled as resources... and then you should ideally inherit ProxyResource instead of using this tag.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:5503 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

This tag shouldn't be on the 'properties' property bag!

Please remove it, even if its breaking I'm convinced its incorrect enough to be a bugfix, as in nobody should be depending on it.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:5579 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

If this is a proxy resource represented elsewhere in the API, then you can inherit ProxyResource.

Otherwise, I believe this tag shouldn't be there.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:5597 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>       "x-ms-azure-resource": true

Should be [ARMBlockingComment] if this were this a new API:

x-ms-azure-resource tag shouldn't be added on the 'properties' property bag deifnition!

Please remove it! ... Unless its too breaking.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:5632 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     },

Please remove these and everywhere you reference them, instead inherit "allOf", from ProxyResource, TrackedResource, or Resource in common-types' types.json

../../../../../common-types/resource-management/v6/types.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v6/types.json)

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:7082 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>     "PrivateEndpointStatus": {

I'd recommend you remove this and instead use the definition here....

[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v6/privatelinks.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v6/privatelinks.json)

BUT...
It does not define the "Timeout" or "Pending" statuses. Are you sure you really return those, and that its okay to? 

I think NRP depends on you using a known set of values.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:7097 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by TimLovellSmith** [comment]
>   },

Consider removing these and instead referencing the ErrorResponse definitions from common-types. 

This feedback is more like 'optional' at this point, in case its breaking.

---
Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:7225 in dafbb66. [](commit_id = dafbb66d086ca156bd0b5f23e7a946dd2ce41431, deletion_comment = False)

**Comment by Alancere** [comment]
Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.

**Comment by t-bzhan** [comment]
> > ```
> > }
> > ```
> 
> Optional, but since you're already making SDK breaking changes....
> 
> For sake of consistency with other RPs and reviewability, I would like to recommend removing these parameter definitions from your spec, and instead always referencing the ones from common-types.
> 
> e.g.
> 
> ../../../../../common-types/resource-management/v6/types.json#parameters/SubscriptionIdParameter
> 
> Refers to: specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json:7251 in [dafbb66](https://github.com/Azure/azure-rest-api-specs/commit/dafbb66d086ca156bd0b5f23e7a946dd2ce41431). [](commit_id = [dafbb66](https://github.com/Azure/azure-rest-api-specs/commit/dafbb66d086ca156bd0b5f23e7a946dd2ce41431), deletion_comment = False)



> Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.

Thank you, @TimLovellSmith! Your comments are well received. There are several aspects we need to improve in our existing Swagger:

1. Remove the incorrect usage of ‘x-ms-azure-resource,’ especially in POST body and response.
2. For true Azure resources, inherit properties from ‘ProxyResource’ instead of using this tag directly.
3. For common definitions (such as ‘Resources’, ‘ProxyReference' and 'PrivateEndpoint’), we should  refer to them from a common place rather than defining them in the Swagger.

Given the extensive changes required, I have to discuss them with the feature owners and defer these improvements to the next PR.

**Comment by t-bzhan** [comment]
> Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.

Hi @Alancer. Is there any specific reason for removing the prefix? In my opinion, keeping ‘cdn’ here is more appropriate. The ‘CdnCertificateSourceParameters’ is in contrast to ‘KeyVaultCertificateSourceParameters.’ While the former indicates that the certificate is managed by CDN itself, the latter implies that the certificate belongs to the customer’s key vault. Therefore, the prefix is not redundant. Is this prefix removal logic unique to Golang? Can we remove it?

**Comment by tadelesh** [comment]
> > Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.
> 
> Hi @alancer. Is there any specific reason for removing the prefix? In my opinion, keeping ‘cdn’ here is more appropriate. The ‘CdnCertificateSourceParameters’ is in contrast to ‘KeyVaultCertificateSourceParameters.’ While the former indicates that the certificate is managed by CDN itself, the latter implies that the certificate belongs to the customer’s key vault. Therefore, the prefix is not redundant. Is this prefix removal logic unique to Golang? Can we remove it?

go language has one trait that use type with namespace which means each type in go is used as `armcdn.CdnCertificateSourceParameters`. you could see the `cdn` part is duplicate, so we will remove it in our codegen.

**Comment by t-bzhan** [comment]
> > > Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.
> > 
> > 
> > Hi @alancer. Is there any specific reason for removing the prefix? In my opinion, keeping ‘cdn’ here is more appropriate. The ‘CdnCertificateSourceParameters’ is in contrast to ‘KeyVaultCertificateSourceParameters.’ While the former indicates that the certificate is managed by CDN itself, the latter implies that the certificate belongs to the customer’s key vault. Therefore, the prefix is not redundant. Is this prefix removal logic unique to Golang? Can we remove it?
> 
> go language has one trait that use type with namespace which means each type in go is used as `armcdn.CdnCertificateSourceParameters`. you could see the `cdn` part is duplicate, so we will remove it in our codegen.

Hi @tadelesh , I understand that removing the prefix would make the type name cleaner in most scenarios. However, in this specific example, `armcdn.CdnCertificateSourceParameters` conveys more than `armcdn.CertificateSourceParameters`. The latter doesn’t clearly indicate that the certificate is managed by CDN itself. To put it another way, we support multiple certificate sources: one from CDN (managed by CDN itself) and another from the customer’s key vault. I believe `armcdn.CdnCertificateSourceParameters` /`armcdn.KeyVaultCertificateSourceParameters` is more appropriate than `armcdn.CertificateSourceParameters`/`armcdn.KeyVaultCertificateSourceParameters`. The latter doesn’t fully convey the design intention.

Could we exclude this specific path from the prefix-removing logic?

**Comment by tadelesh** [comment]
> > > > Hi @t-bzhan, reasons for GO CI failure: `CdnCertificateSourceParameters` removes the service prefix (e: `cdn`) during the generation of the GO SDK, and it is generated as `CertificateSourceParameters`, so it conflicts with the newly defined [CertificateSourceParameters](https://github.com/Azure/azure-rest-api-specs/blob/dafbb66d086ca156bd0b5f23e7a946dd2ce41431/specification/cdn/resource-manager/Microsoft.Cdn/stable/2024-02-01/cdn.json#L3224), It is recommended that you rename it.
> > > 
> > > 
> > > Hi @alancer. Is there any specific reason for removing the prefix? In my opinion, keeping ‘cdn’ here is more appropriate. The ‘CdnCertificateSourceParameters’ is in contrast to ‘KeyVaultCertificateSourceParameters.’ While the former indicates that the certificate is managed by CDN itself, the latter implies that the certificate belongs to the customer’s key vault. Therefore, the prefix is not redundant. Is this prefix removal logic unique to Golang? Can we remove it?
> > 
> > 
> > go language has one trait that use type with namespace which means each type in go is used as `armcdn.CdnCertificateSourceParameters`. you could see the `cdn` part is duplicate, so we will remove it in our codegen.
> 
> Hi @tadelesh , I understand that removing the prefix would make the type name cleaner in most scenarios. However, in this specific example, `armcdn.CdnCertificateSourceParameters` conveys more than `armcdn.CertificateSourceParameters`. The latter doesn’t clearly indicate that the certificate is managed by CDN itself. To put it another way, we support multiple certificate sources: one from CDN (managed by CDN itself) and another from the customer’s key vault. I believe `armcdn.CdnCertificateSourceParameters` /`armcdn.KeyVaultCertificateSourceParameters` is more appropriate than `armcdn.CertificateSourceParameters`/`armcdn.KeyVaultCertificateSourceParameters`. The latter doesn’t fully convey the design intention.
> 
> Could we exclude this specific path from the prefix-removing logic?

@Alancere please add go directive to rename `CertificateSourceParameters` to `CertificateSourceParametersBase` to unblock the pr.

**Review by ChenglongLiu — APPROVED** [review]

**Comment by raosuhas** [comment]
Can you please check the model validation failures before requesting merge ?

Following required checks are failing:
❌ Swagger ModelValidation

**Comment by t-bzhan** [comment]
> Can you please check the model validation failures before requesting merge ?
> 
> Following required checks are failing: ❌ Swagger ModelValidation

Hi @raosuhas , as I mentioned in a previous comment reply, the model failures were not introduced by that change. Fully addressing them would require changes in multiple places, and there’s a chance that it could introduce breaking changes. I recommend resolving the issue in a separate PR. Does that make sense to you?
image

**Comment by t-bzhan** [comment]
@raosuhas , can you help merge the PR?

**Comment by t-bzhan** [comment]
Hi @razvanbadea-msft, Is there anything I need to follow up on to get the PR merged?

**Comment by razvanbadea-msft** [comment]
> Hi @razvanbadea-msft, Is there anything I need to follow up on to get the PR merged?

image

A required check is failing, it needs to be fixed before merging

**Comment by t-bzhan** [comment]
> > Hi @razvanbadea-msft, Is there anything I need to follow up on to get the PR merged?
> 
> image
> 
> A required check is failing, it needs to be fixed before merging

Hi  @razvanbadea-msft , I think the Golang SDK failure should already be resolved, as we have renamed one of the properties that previously caused a conflict. You can refer the historical comments. 
image

@Alancere @Alancere , can you help confirm?

**Comment by Alancere** [comment]
> > > Hi @razvanbadea-msft, Is there anything I need to follow up on to get the PR merged?
> > 
> > 
> > image
> > A required check is failing, it needs to be fixed before merging
> 
> Hi @razvanbadea-msft , I think the Golang SDK failure should already be resolved, as we have renamed one of the properties that previously caused a conflict. You can refer the historical comments. image
> 
> @Alancere @tadelesh , can you help confirm?

SDK azure-sdk-for-go CI passed

**Pull request merged**
