### PR TITLE
Dev keyvault microsoft.key vault 7.1

### PR DESCRIPTION
**Pull request by heaths**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs. Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by heaths** [comment]
Adding DoNotMerge because I'm working on another PR against this feature branch based on some validation issues that didn't come up before (new?) and some internal discussion with the Key Vault team.

**Comment by msfcolombo** [comment]
I'm OK with changes on `data-plane` directory.

For the `resource-manager` directory, beware that this is the current state of the service:

- Version `2019-09-01` already assumes default true for `enableSoftDelete`. It’s the first version where that happens.
- Version `2019-09-01` and many versions back are honoring `softDeleteRetentionInDays` and they already return this value in responses.
- The service is not ready interpreting `2020-01-23`. It will either return an error or provide some default implementation (I would have to dig further to find the exact outcome).

Based on the above, my recommendation is:

- Do not add version `2020-01-23` to management plane; delete that directory.
- Instead, modify existing version (`2019-09-01`) to be conforming to the service (i.e. your changes done at `2020-01-23` should be performed on `2019-09-01`).

Thanks

**Comment by heaths** [comment]
We need to split some features out into an upcoming 7.2-preview, making this PR smaller. We also need sign-off from both data and management planes.

**Comment by heaths** [comment]
I've verified all ModelValidation errors to this point are what's expected given the OpenAPI validation bug.

**Comment by heaths** [comment]
This is odd. GitHub is showing the previous commit failed, even though the PR passed completely: https://github.com/Azure/azure-rest-api-specs/pull/8405

**Comment by heaths** [comment]
@akning-ms why is management-plane code generation for Go looking at the data-plane? See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=261939&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=724. This is blocking.

**Comment by akning-ms** [comment]
@heaths For this PR, I have 2 feedbacks to you. First. can you split this PR into 2 PR? one for dataplane and one for management plane.   secondly: this PR looks too big which make PR review not easy, this is what we discussed previously.

**Comment by heaths** [comment]
I can split it, yes, but it will take time because of the default branch restrictions.

As for the size, that would be true of any new version. Instead, I recommended using the diffing tools in OpenAPI Hub. Specify the URL to the readme.md files and the versions package-7.0 and package-7.1-preview. You'll find the diff is much smaller. We've also verified the data plane has only expected differences via code generation and API diffing.

**Comment by ArcturusZhang** [comment]
> @akning-ms, @ArcturusZhang why is management-plane code generation for Go looking at the data-plane? See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=261939&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=724. This is blocking.

Hi @heaths I have just check the go SDK generation locally, everything goes fine on the new data-plane package 7.1-preview. There must be something wrong within the pipeline itself, maybe because currently it cannot handle data-plane mixed with mgmt-plane. Therefore please ignore the failure on go SDK generation. 
But I strongly recommend you to separate data-plane and mgmt-plane by create another PR for mgmt plane to make sure there is nothing wrong in the mgmt-plane.

**Comment by akning-ms** [comment]
> I can split it, yes, but it will take time because of the default branch restrictions.
> 
> As for the size, that would be true of any new version. Instead, I recommended using the diffing tools in OpenAPI Hub. Specify the URL to the readme.md files and the versions package-7.0 and package-7.1-preview. You'll find the diff is much smaller. We've also verified the data plane has only expected differences via code generation and API diffing.

Hi @heaths , Agree with file size, and looks it is small change for management plane. consider this change is required ARM review, and also ArcturusZhang suggested ,  Can you extract management plane as separate PR for review?
BTW, the label "ARMChangesRequested" normally used by ARM request service team make change for PR. :) and noticed there is some MV validation failure you may need to take a look.

**Comment by heaths** [comment]
@akning-ms the ModelValidation errors are the bug you acknowledged in OpenAPI validation that we cannot fix nor suppress. You told us to ignore them. With each build I've had to validate that all errors are *only* that error. It would be nice if that issue is resolved so we can trust the validation system.

**Comment by heaths** [comment]
Once again, I have verified that no ModelValidation errors are **not** `MISSING_REQUIRED_PARAMETER`, which is a known, acknowledged error.

**Comment by heaths** [comment]
JavaScript automation timed out and Go automation failed with no reason (the latter has happened several times and appears to just be flaky).

/azp run automation - sdk

**Comment by heaths** [comment]
Go SDK automation [is complaining](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=266537&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=771) there are no packages, but seems to be processing management plane when this only affects data plane. Who owns that build step and can investigate?

**Comment by ArcturusZhang** [comment]
> Go SDK automation [is complaining](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=266537&view=logs&j=fae805ed-8bde-5aa7-6387-2396f34533f9&t=c2e6587e-d03c-5fa9-0378-bc3c21e64d38&l=771) there are no packages, but seems to be processing management plane when this only affects data plane. Who owns that build step and can investigate?

Hi @heaths there are two files from mgmt-plane changed in this PR:
1. specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2018-02-14-preview/examples/deleteVault.json
2. specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2018-02-14-preview/examples/purgeDeletedVault.json
please revert those changes, and then the automation on go SDK should be fine.

**Comment by heaths** [comment]
@ArcturusZhang thanks for pointing that out. They are still there from a previous commit when we had both data- and management-plane changes in one PR. I had to make those to silence validation errors. But won't removing them now trigger validation errors again, at least in the PR targeting this feature branch? But if that then makes validation pass for this feature branch (sans the known ModelValidation error) I suppose it's worth it, right?

**Comment by heaths** [comment]
I again verified that all ModelValidation errors are expected because of the `MISSING_REQUIRED_PARAMETER` bug.

**Comment by ArcturusZhang** [comment]
Signing off from the go SDK side, since the pipeline reports no error now.

**Review by johanste — APPROVED** [review]

**Review by RandalliLama — APPROVED** [review]

**Comment by heaths** [comment]
@mayurid this is ready to merge with 'master'.

**Comment by heaths** [comment]
The ModelValidation errors are once again the known issue. The Go SDK issue also happens when I *fix* ModelValidation errors for samples that are wrong, i.e. they have a `body: ""` in the JSON but no body is defined for those response codes. I can't fix one without breaking the other. The validation needs to be fixed and is blocking merging.

**Pull request merged**
