### PR TITLE
[ADLA - ADLS] - [BUGFIX] - Fixing x-ms-odata parameters

### PR DESCRIPTION
**Pull request by ro-joowan**
* These x-ms-odata parameters were not updated in a prior PR

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by veronicagg — CHANGES_REQUESTED** [review]
thanks @ro-joowan . Is there an issue associated with this bug fix?
Change itself looks good to me.

**Comment by ro-joowan** [comment]
@veronicagg There is no issue associated with this.  Thank you!

**Comment by veronicagg** [comment]
@ro-joowan ok, how did you figure out there was an issue? Next time I'd recommend opening one.

**Comment by ro-joowan** [comment]
@veronicagg Good question :)  -- I was working on new APIs for catalog.json that involved x-ms-odata, and it occurred to me that this wasn't addressed in a previous/recent work for job.json/account.json

**Comment by ro-joowan** [comment]
@veronicagg I'll keep the idea of issues in mind next time

**Comment by veronicagg** [comment]
@ro-joowan ok, since the model is changing for the odata extension, it may cause a breaking change in some of the generated code, have you checked any of the SDKs? are you ok with that?

**Comment by ro-joowan** [comment]
@veronicagg Thanks for noting this.  I am okay with this breaking change because this is technically a bugfix.  That is, the server hasn't been returning the extra fields in JobInformation that are not in JobInformationBasic, and so I cannot imagine this having a considerable impact as a breaking change.

**Review by veronicagg — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
