### PR TITLE
[Hub Generated] Review request for Identity to add version preview/2021-10-31-preview

### PR DESCRIPTION
**Pull request by petrsvihlik**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/petrsvihlik/azure-rest-api-specs/dev-communication-Identity-2021-10-31-preview...main/).

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version **We are making changes to a feature called [Custom Teams Endpoint (CTE)](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/manage-teams-identity) in order to make the feature available in Public Preview. The swagger itself [does not contain any real changes](https://github.com/Azure/azure-rest-api-specs/pull/16014#issuecomment-919972296) compared to previously approved [Private Preview version 2021-03-31-preview1](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Identity/preview/2021-03-31-preview1/CommunicationIdentity.json) apart from a new version number and some sections being generated in a different order. It serves as a moniker to enable targeting a new (Public Preview) version of the `/:exchangeAccessToken` endpoint.**
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify: 
  2. When are you targeting to deploy the new ~~service~~/feature to public regions? Please provide the date or, if the date is not yet available, the month.
    - **Public preview is planned for 02/28/22 (detailed [timeline](https://skype.visualstudio.com/SPOOL/_dashboards/dashboard/66d7e1ac-a6a8-41b5-b93b-3ed2e1ce47ad))**
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
    - We are planning to update the SDKs with this feature in Q4/CY2021 so we would like to have the swagger ready by the **30th of September 2021**
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

**Comments:**
- **R4000 warnings to be fixed in https://skype.visualstudio.com/SPOOL/_workitems/edit/2581490**
- **R2063 warnings will probably be skipped to avoid a breaking change - any advice here?**

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ~~ARM API Review Checklist~~ N/A

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### ~~Breaking Change Review Checklist~~ N/A
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Evidence of no changes between versions:

https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL2dpdGh1Yi5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvYmxvYi9tYWluL3NwZWNpZmljYXRpb24vY29tbXVuaWNhdGlvbi9kYXRhLXBsYW5lL0lkZW50aXR5L3JlYWRtZS5tZCIsInRhcmdldFVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9wZXRyc3ZpaGxpay9henVyZS1yZXN0LWFwaS1zcGVjcy9ibG9iL2Rldi1jb21tdW5pY2F0aW9uLUlkZW50aXR5LTIwMjEtMTAtMzEtcHJldmlldy9zcGVjaWZpY2F0aW9uL2NvbW11bmljYXRpb24vZGF0YS1wbGFuZS9JZGVudGl0eS9yZWFkbWUubWQiLCJzb3VyY2VUYWciOiJwYWNrYWdlLTIwMjEtMDMtMzEtcHJldmlldzEiLCJ0YXJnZXRUYWciOiJwYWNrYWdlLXByZXZpZXctMjAyMS0xMCJ9

image

**Comment by petrsvihlik** [comment]
@RezaJooyandeh and @DominikMe started commenting on https://github.com/petrsvihlik/CommunicationIdentity/commit/66ffbaad0515564410940a5cf70a94e1e8ecaec6

**Comment by petrsvihlik** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/16014/commits/740e4d1bd3ac9d42dc6fe28b008f6db5b819513d fixes the following issues:
- @RezaJooyandeh's comments from https://github.com/petrsvihlik/CommunicationIdentity/commit/66ffbaad0515564410940a5cf70a94e1e8ecaec6#r56905550 regarding token naming
- R4000 warnings (missing param descriptions) - https://skype.visualstudio.com/SPOOL/_workitems/edit/2581490

**Comment by jhendrixMSFT** [comment]
@markweitzel has this been reviewed by the API board yet?

**Comment by petrsvihlik** [comment]
@jhendrixMSFT an internal review by the ACS team is scheduled for today (2021-10-05) and a review by the API board is scheduled for next Friday (2021-10-15)

**Comment by petrsvihlik** [comment]
@DominikMe I adjusted the description of the exchangeAccessToken endpoint as you requested yesterday. We should be ready to merge.
As we discussed with @JeffreyRichter and agreed with @jorgegarchirota, the API board review is not required when the public API surface hasn't changed.

**Review by DominikMe — APPROVED** [review]

**Comment by DominikMe** [comment]
@jhendrixMSFT Can you help us merge this?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
