### PR TITLE
[Visual Search API] Update parameters, operationId, descriptions

### PR DESCRIPTION
**Pull request by shakao**
Swagger updates per PM request, so that documentation can be regenerated with updated page title and descriptions.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by hovsepm** [comment]
@shakao please address model validation error
```
{ code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message: 'Found errors in validating the request for x-ms-example "Successful visual search" in operation "Bing_VisualSearchV7".',
  innerErrors: 
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors: 
        [ { code: 'ONE_OF_MISSING',
            params: [],
            message: 'Data does not match any schemas from \'oneOf\'',
            path: [],
            description: 'The form data is an image binary. The Content-Disposition header\'s filename parameter must be set to "image". You must specify an image binary if you do not use knowledgeRequest form data to specify the image; you may not use both forms to specify an image. You may specify knowledgeRequest form data and image form data in the same request only if knowledgeRequest form data specifies the cropArea field only  (it must not include an insights token or URL).',
            inner: 
             [ { code: 'INVALID_TYPE',
                 params: [ 'file', 'string' ],
                 message: 'Expected type file but found type string',
                 path: [] },
               { code: 'INVALID_TYPE',
                 params: [ 'null', 'string' ],
                 message: 'Expected type null but found type string',
                 path: [] } ] } ],
       in: 'formData',
       message: 'Invalid parameter (image): Value failed JSON Schema validation',
       name: 'image',
       path: [ 'paths', '/images/visualsearch', 'post', 'parameters', '10' ] } ] }
{ AssertionError [ERR_ASSERTION]: swagger "specification/cognitiveservices/data-plane/VisualSearch/preview/v1.0/VisualSearch.json" contains model validation errors.
```

**Comment by hovsepm** [comment]
@shakao also your PR have a breaking chage
```
{
  "id": "1008",
  "code": "ModifiedOperationId",
  "message": "The operation id has been changed from 'Images_VisualSearch' to 'Bing_VisualSearchV7'. This will impact generated code.",
  "jsonref": "#/paths/~1images~1visualsearch/post",
  "json-path": "#/paths/images/visualsearch/post",
  "type": "Error"
}
```

We strongly recommend moving all breaking changes to the next Api version.

**Comment by shakao** [comment]
@hovsepm I think the first issue is a [known bug](https://github.com/Azure/azure-rest-api-specs/pull/2872#issuecomment-382160477) where the example is expecting a "file" type. I'll check in with the PM about the breaking change to see if we can push it back. Thanks!

**Comment by shakao** [comment]
@hovsepm Hm okay, so based on discussion, I think I'm going to close this for now while we clarify what to do with the OperationId and I'll reopen/make a new PR once that's all resolved. Thank you!

**Pull request closed without merging**
