### PR TITLE
[NetAppFiles] Anf 13322 net app files api version 2021 06 01

### PR DESCRIPTION
**Pull request by audunn**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [x] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [x] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by lirenhe** [comment]
@audunn, there are a couple of breaking changes detected in the API version, could you follow the breaking change review process to get them approved?

**Comment by audunn** [comment]
> @audunn, there are a couple of breaking changes detected in the API version, could you follow the breaking change review process to get them approved?

@lirenhe I beloved at lest some of them to be false positives. For example DefaultValueChanged on Pool "serviceLevel" is that I saw it was the same enum used several times in the spec and changed to use one common.  The default has indeed not changed see below the first is the 2021-06-01 and then 2021-02-01 both have default of  `"default": "Premium"`

```
        "serviceLevel": {
          "title": "serviceLevel",
          "type": "string",
          "$ref": "#/definitions/serviceLevel",
          "example": "Ultra",
          "default": "Premium"
        },
```

```
        "serviceLevel": {
          "title": "serviceLevel",
          "type": "string",
          "description": "The service level of the file system",
          "enum": [
            "Standard",
            "Premium",
            "Ultra"
          ],
          "x-ms-enum": {
            "name": "ServiceLevel",
            "modelAsString": true,
            "values": [
              {
                "value": "Standard",
                "description": "Standard service level"
              },
              {
                "value": "Premium",
                "description": "Premium service level"
              },
              {
                "value": "Ultra",
                "description": "Ultra service level"
              }
            ]
          },
          "example": "Ultra",
          "default": "Premium"
        },
```

**Comment by audunn** [comment]
The other changes are needed, `yearlyBackupsToKeep `in `BackupPolicies `is not supported by the service and should not have been inthere in the first place. Using it will cause error for users. 

We are also correcting an omission by adding `readonly `tag on properties `volumesAssigned volumeBackups` that are indeed read only properties that the user cannot change directly.

@lirenhe Now that you have a bit of context can you please let be know if we need to go through the breaking changes process for those changes.

**Comment by lirenhe** [comment]
@audunn, thanks for providing the context but based on our policy, it is still required for the breaking change review as the review board is responsible for the approval.  Could you provide the above justification to them as well?  
@jianyexi, could you help with the one for 'Default Value changed'?

**Comment by jianyexi** [comment]
@audunn  In autorest, the default value next to the "$ref" will be ignored , it's not supported to add default value in your way. 
see https://github.com/Azure/autorest/blob/main/docs/openapi/howto/$ref-siblings.md

**Comment by audunn** [comment]
Thank you @lirenhe and @jianyexi  this has fixed the issue with the default on ServiceLevel.  Leaving the Backup Policies properties, 
Note that the Backup feature is in private preview still.

**Comment by ihsan-alikapahi** [comment]
Good to see

**Comment by lirenhe** [comment]
> Thank you @lirenhe and @jianyexi looks like this has fixed the issue with the default on `ServiceLevel`. Leaving the Backup Policies properties,
> Note that the Backup feature (including backup policies) is in private preview still.

As the breaking change comes from the latest stable version, I added the label of 'BreakingChangeReviewRequired'. Please help to follow the process which is required for this PR. Thanks

**Comment by audunn** [comment]
> > Thank you @lirenhe and @jianyexi looks like this has fixed the issue with the default on `ServiceLevel`. Leaving the Backup Policies properties,
> > Note that the Backup feature (including backup policies) is in private preview still.
> 
> As the breaking change comes from the latest stable version, I added the label of 'BreakingChangeReviewRequired'. Please help to follow the process which is required for this PR. Thanks

We have started the process  https://msazure.visualstudio.com/One/_workitems/edit/10295481

**Comment by ihsan-alikapahi** [comment]
😂

**Comment by ihsan-alikapahi** [comment]
👍

**Comment by ihsan-alikapahi** [comment]
🚀

**Comment by ihsan-alikapahi** [comment]
🎉

**Comment by ihsan-alikapahi** [comment]
😒

**Comment by ihsan-alikapahi** [comment]
😂

**Comment by ihsan-alikapahi** [comment]
🙏

**Comment by ihsan-alikapahi** [comment]
❤️

**Comment by ihsan-alikapahi** [comment]
👍

**Comment by ihsan-alikapahi** [comment]
👍

**Comment by ihsan-alikapahi** [comment]
👍

**Comment by ihsan-alikapahi** [comment]
image

**Comment by ihsan-alikapahi** [comment]
image

**Comment by ihsan-alikapahi** [comment]
image

**Comment by ihsan-alikapahi** [comment]
image

**Comment by audunn** [comment]
We are still waiting on breaking change review

**Comment by ihsan-alikapahi** [comment]
😂

IHSAN KAPAHI

**Comment by audunn** [comment]
> NewApiVersionRequired reason:

This is a new api-version NewApiVersionRequired reason

**Review by lirenhe — APPROVED** [review]

**Pull request merged**
