### PR TITLE
Notifications REST Api with Examples

### PR DESCRIPTION
**Pull request by solankisamir**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@ravbhatnagar new spec file apimanagement/resource-manager/Microsoft.ApiManagement/2017-03-01/apimnotifications.json

**Comment by solankisamir** [comment]
@ravbhatnagar a gentle ping!

**Comment by olydis** [comment]
@ravbhatnagar ping

**Comment by ravbhatnagar** [comment]
@olydis - I chatted about this with @solankisamir offline. There are a couple of issues with the way the apis are currently modeled. But this is already deployed on the service. So we may have to let the PR in. I am awaiting an email ACK from the team that they understand the concern and will fix it in the next api-version rev. @salameer as FYI.

**Comment by salameer** [comment]
Hi @ravbhatnagar ,

Do we have an ack  already on this? :)

**Comment by olydis** [comment]
@ravbhatnagar any news?

**Comment by ravbhatnagar** [comment]
@olydis @salameer - just added you to email thread. It has not been resolved yet.

**Comment by dsgouda** [comment]
@ravbhatnagar @salameer should we close this PR then?

**Comment by solankisamir** [comment]
Yes, close this PR. We need to make some service side changes as suggested by @ravbhatnagar .

**Comment by dsgouda** [comment]
Thank you for the response, please open a fresh PR when ready.

**Pull request closed without merging**
