### PR TITLE
Including the machine sizes that were missing

### PR DESCRIPTION
**Pull request by Nepomuceno**
Including machine sizes that are supported by azure but that were missing from the spec

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Nepomuceno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by Nepomuceno** [comment]
I have signed twice already the cla but apparently this is not being updated.

**Comment by devigned** [comment]
I'll see what's going on with the CLA. Sorry for the delay.

**Comment by devigned** [comment]
@mohitsriv can you approve this cla?

**Comment by mohitsriv** [comment]
Approved

**Comment by azurecla** [comment]
Hi __@Nepomuceno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
Thank you!

**Comment by devigned** [comment]
fixes #10

**Pull request merged**
