### PR TITLE
Above-Subscription Level Marketplace and Usage Detail, and Enrollment Level Balances

### PR DESCRIPTION
**Pull request by parisa-naeimi**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by marstr** [comment]
Howdy @parisa-naeimi,

Before we get started, it looks like there are numerous issues being flagged by our CI with this PR. Including some of these files not being valid JSON. Those issues will need to be fixed before the ARM team and I can get started with out reviews.

You can see detailed information about the errors in the CI Logs, here:
https://travis-ci.org/Azure/azure-rest-api-specs/builds/365454151?utm_source=github_status&utm_medium=notification

**Comment by parisa-naeimi** [comment]
@marstr Could you please take a look at my PR?

**Comment by parisa-naeimi** [comment]
@ms-premp Just for awareness.

**Comment by parisa-naeimi** [comment]
@marstr  Hello Martin, I was wondering if you could review this PR? Thank you very much.

**Comment by marstr** [comment]
Howdy @parisa-naeimi, sorry for the delay. I'll take another look at this PR and have comments in by EOD tomorrow.

**Comment by parisa-naeimi** [comment]
@marstr, Sure, thank you very much.

**Comment by marstr** [comment]
CI is still reporting a new model error: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/365866211#L756 Specifically it looks like there is an unknown property "value" in the examples. I'm not sure if it's [BalancesByBillingAccount.json#L31](https://github.com/Azure/azure-rest-api-specs/pull/2857/files#diff-d9690a93046712378fe2cacb82ef5164R31) or [BalancesByBillingAccount.json#L41](https://github.com/Azure/azure-rest-api-specs/pull/2857/files#diff-d9690a93046712378fe2cacb82ef5164R41), but one of the defintions will need to be tweaked to accommodate that property.

**Review by marstr — CHANGES_REQUESTED** [review]
CI is still reporting a new model error: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/365866211#L756 Specifically it looks like there is an unknown property "value" in the examples. I'm not sure if it's [BalancesByBillingAccount.json#L31](https://github.com/Azure/azure-rest-api-specs/pull/2857/files#diff-d9690a93046712378fe2cacb82ef5164R31) or [BalancesByBillingAccount.json#L41](https://github.com/Azure/azure-rest-api-specs/pull/2857/files#diff-d9690a93046712378fe2cacb82ef5164R41), but one of the defintions will need to be tweaked to accommodate that property.

**Comment by marstr** [comment]
Thanks for fixing up the syntax errors, I've white-listed this PR for ARM Feedback.

**Comment by parisa-naeimi** [comment]
@marstr Thank you very much for taking the time and looking at this PR. I already addressed your concern for BalancesByBillingAccount.Json, could you please take a look and let me know if I need to do more revision?

**Comment by ravbhatnagar** [comment]
@parisa-naeimi - please schedule a review with ARM and Azure API review board to go over these APIs. There are some new concepts like department etc which need little more clarity from a scenario pov.
@devigned @johanste @darrelmiller FYI

**Comment by marstr** [comment]
I'm going to wait to review further until the Azure API Review board has had a chance to look over these changes.

**Comment by ravbhatnagar** [comment]
Signing off! We did meet to go over these apis

**Comment by parisa-naeimi** [comment]
@marstr 
Hello Martin, 
Arm team already signed off this PR, Could you please take a look at this PR?

Thank You,
Parisa

**Comment by marstr** [comment]
I see that there are a lot of operations, that look to actually be going through the Microsoft.Billing RP, but targeting a Resource that you control in Consumption. See here for an example of what I'm talking about:
https://github.com/Azure/azure-rest-api-specs/pull/2857/files#diff-dca9b11ab859f276378213344e091b34R304

Could you explain quickly why these operations belong in your Swagger? is there a tight relationship between these two RPs? I'll have a chat with other Swagger reviewers to make sure this isn't just a knowledge gap of mine.

**Comment by ms-premp** [comment]
@marstr  .. unfortunately the diff tool suggest there are a lot of changes but its actually not.
I can schedule a meeting with you to go over it if that's needed.
In a nutshell, there are three APIs
UsageDetails
MarketPlaces
Balances
These already exist today and users call them under subscription scope.. like
/subscription/{subscriptionGuid}/providers/Microsoft.Consumption/usageDetails
also user can specify a billing period scope like
/subscription/{subscriptionGuid}/providers/Microsoft.Billing/billingperiods/{billingPeriodId}/providers/Microsoft.Consumption/usageDetails

These already exist today.
The new change here is that we want to provide same APIs but not at scope of subscription.. at a higher scope like billingAccounts, departments or enrollmentAccounts.
The response does not change at all. Its still the same. 
The change is the request scope.
A sample request will look like
/providers/Microsoft.Billing/billingAccounts/{EnrollmentNumber}/provider/Microsoft.Consumption/usageDetails.
So the scope here is "providers/Microsoft.Billing/billingAccounts/{EnrollmentNumber}" and not "/subscriptions/{subscriptionGuid}" as before.
The proxy resources such as billingAccounts, departments, enrollmentAccounts are defined and owned by Microsoft.Billing RP and so any scope or extension to those resources will have to include those in Request.
Our Consumption RP is registered to behave as an extension to any other RP resources, so that usage data can be scoped to a specific RP resource.
This Extension routing is supported in ARM since very beginning and is used by multiple teams
see extension at
http://sharepoint/sites/AzureUX/Sparta/SpartaWiki/Resource%20Provider%20Registration%20Routing%20Types.aspx
Hope, this answers your queries.

**Comment by marstr** [comment]
Thanks for that explanation, @ms-premp, that is much appreciated.

**Review by marstr — APPROVED** [review]

**Review by marstr — CHANGES_REQUESTED** [review]
Whoops, sorry for the false approval. Looks like there are couple of examples that don't match the operation's declaration.

Mind fixing those up quick?
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/371363427#L768

Other than that, this looks good to me.

**Comment by parisa-naeimi** [comment]
@marstr 

Hello Martin,

Thank you very much for taking the time and looking at this PR. I fixed those minor issues in examples and checked in the changes. Please let me know if there is any concerns. I appreciate if you take a look at PR.

Thank you again,
Parisa

**Review by marstr — APPROVED** [review]

**Comment by marstr** [comment]
@parisa-naeimi, are these changes deployed to at least one region and ready for me to merge them?

**Comment by parisa-naeimi** [comment]
@marstr Yes, those changes are in Prod. we deployed to Prod today. We should be good. Thank you.

**Comment by parisa-naeimi** [comment]
@marstr  Thank you Martin

**Pull request merged**
