### PR TITLE
update samples parameters

### PR DESCRIPTION
**Pull request by kazrael2119**
fix: https://github.com/Azure/azure-sdk-for-js/issues/25699

### CODE REVIEW

**Comment by kazrael2119** [comment]
@tadelesh ,please review go sdk breaking change,thanks

**Comment by kazrael2119** [comment]
Hi @MikhailTryakhov ,please review this pr,thanks

**Review by tadelesh — APPROVED** [review]

**Comment by MikhailTryakhov** [comment]
@kazrael2119 please don't deliver changes to the main branch directly. Read our official docs: https://microsoft.sharepoint.com/teams/Aznet/_layouts/OneNote.aspx?id=%2Fteams%2FAznet%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2F%5BNEWEST%5D%20Swagger-%3E%20SDK%20-%3E%20PowerShell%20Process%20Overview%7C71B816ED-DAE5-4907-94D8-DE7EE13278A0%2F%29
onenote:https://microsoft.sharepoint.com/teams/Aznet/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#%5bNEWEST%5d%20Swagger-%3e%20SDK%20-%3e%20PowerShell%20Process%20Overview&section-id={96F7B95B-A378-4CA5-903B-C88F894873EF}&page-id={71B816ED-DAE5-4907-94D8-DE7EE13278A0}&end

**Comment by kazrael2119** [comment]
> @kazrael2119 please don't deliver changes to the main branch directly. Read our official docs: https://microsoft.sharepoint.com/teams/Aznet/_layouts/OneNote.aspx?id=%2Fteams%2FAznet%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2F%5BNEWEST%5D%20Swagger-%3E%20SDK%20-%3E%20PowerShell%20Process%20Overview%7C71B816ED-DAE5-4907-94D8-DE7EE13278A0%2F%29 onenote:[https://microsoft.sharepoint.com/teams/Aznet/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#%5bNEWEST%5d%20Swagger-%3e%20SDK%20-%3e%20PowerShell%20Process%20Overview&section-id={96F7B95B-A378-4CA5-903B-C88F894873EF}&page-id={71B816ED-DAE5-4907-94D8-DE7EE13278A0}&end](https://microsoft.sharepoint.com/teams/Aznet/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#%5bNEWEST%5d%20Swagger-%3e%20SDK%20-%3e%20PowerShell%20Process%20Overview&section-id=%7B96F7B95B-A378-4CA5-903B-C88F894873EF%7D&page-id=%7B71B816ED-DAE5-4907-94D8-DE7EE13278A0%7D&end)

Hi @MikhailTryakhov , I 'm from js sdk team, and this pr is created according to this customer feedback:
https://github.com/Azure/azure-sdk-for-js/issues/25700
https://github.com/Azure/azure-sdk-for-js/issues/25699

I create a pr to fix them in js sdk repo:
https://github.com/Azure/azure-sdk-for-js/pull/25771

but I think that it will be better if I modify them in swagger, If you know the related service owner in network and graphservice, I can give them an issue and they can fix it themselves, thanks

**Comment by kazrael2119** [comment]
> > @kazrael2119 please don't deliver changes to the main branch directly. Read our official docs: https://microsoft.sharepoint.com/teams/Aznet/_layouts/OneNote.aspx?id=%2Fteams%2FAznet%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2F%5BNEWEST%5D%20Swagger-%3E%20SDK%20-%3E%20PowerShell%20Process%20Overview%7C71B816ED-DAE5-4907-94D8-DE7EE13278A0%2F%29 onenote:[https://microsoft.sharepoint.com/teams/Aznet/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#%5bNEWEST%5d%20Swagger-%3e%20SDK%20-%3e%20PowerShell%20Process%20Overview&section-id={96F7B95B-A378-4CA5-903B-C88F894873EF}&page-id={71B816ED-DAE5-4907-94D8-DE7EE13278A0}&end](https://microsoft.sharepoint.com/teams/Aznet/OneNotes/NRP%20migrated/Hydra%20+%20SDK.one#%5bNEWEST%5d%20Swagger-%3e%20SDK%20-%3e%20PowerShell%20Process%20Overview&section-id=%7B96F7B95B-A378-4CA5-903B-C88F894873EF%7D&page-id=%7B71B816ED-DAE5-4907-94D8-DE7EE13278A0%7D&end)
> 
> Hi @MikhailTryakhov , I 'm from js sdk team, and this pr is created according to this customer feedback: [Azure/azure-sdk-for-js#25700](https://github.com/Azure/azure-sdk-for-js/issues/25700) [Azure/azure-sdk-for-js#25699](https://github.com/Azure/azure-sdk-for-js/issues/25699)
> 
> I also create a pr to fix them in js sdk repo: [Azure/azure-sdk-for-js#25771](https://github.com/Azure/azure-sdk-for-js/pull/25771)
> 
> but I think that it will be better if I modify them in swagger, If you know the related service owner in network and graphservice, I can give them an issue and they can fix it themselves, thanks

Hi @MikhailTryakhov please take a look for this, thanks

**Pull request closed without merging**
