### PR TITLE
add tags type

### PR DESCRIPTION
**Pull request by changlong-liu**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by datr93** [comment]
lgtm

**Comment by datr93** [comment]
@changlong-liu lgtm

**Comment by changlong-liu** [comment]
Thanks @datr93 ,

Hi @leni-msft , would you help help to merge this PR? Thanks.

**Comment by leni-msft** [comment]
@changlong-liu Adding `additionalProperties` is considered as breaking change. Could you clarify if it's not causing breaking change error for the existing rest-api consumers?

**Comment by changlong-liu** [comment]
Hi @leni-msft , I think desktopvirtualization has not been released in any SDK, so we can fix issues in it no matter whether it's breaking?

+ @datr93 for confirmation.

**Comment by datr93** [comment]
yes its should not be in any sdk
its in powershell tho.

**Pull request merged**
