### PR TITLE
[IoTCentral] change error details definition

### PR DESCRIPTION
**Pull request by kawayiboy**
If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/kawayiboy/azure-rest-api-specs/telu%2Ferrdefs...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Review by emgarten — APPROVED** [review]
:shipit:

**Comment by kawayiboy** [comment]
@allenjzhang , if we only change error type, it only affects our SDKs, do we need to bump up the version? Thanks

**Review by ryansbenson — COMMENTED** [review]
Approved from ARMs side

**Review by zzcodework — APPROVED** [review]

**Review by poanchen — APPROVED** [review]

**Comment by zzcodework** [comment]
> @allenjzhang , if we only change error type, it only affects our SDKs, do we need to bump up the version? Thanks

From the other email conversation it seems like we don't need to align RP version with SDKs, so we decided to keep current RP version (2018-09-01), and go ahead to make this breaking change to SDKs only.

**Pull request merged**
