### PR TITLE
Dev batch microsoft.batch 2019 04 01- Fix swagger spec incorrect nullable property

### PR DESCRIPTION
**Pull request by jafreck**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Review by matthchr — APPROVED** [review]
Looks good to me, but probably worth fixing commits and also clarifying that while this Swagger has been merged, no SDKs have been generated from it yet?

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5878 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5878/commits/1aa99351d1c638a913d823eaab1e1b19ee4d42b1

**Comment by jafreck** [comment]
Adding @KrisBash and @RyanBensonMSFT for ARM review.

There was a bug in our swagger spec for a new API version. No SDKs for this API have been released. We would like to fix the API swagger specification before proceeding.

**Review by KrisBash — APPROVED** [review]
Discussed offline, LGTM

**Review by sarangan12 — APPROVED** [review]

**Pull request merged**
