### PR TITLE
remove VMwareVirtustream

### PR DESCRIPTION
**Pull request by ctaggart**
The public preview API became Microsoft.AVS in #9307. This pull request completes the rename by removing the old spec. This prevents people from looking at the wrong 2019-08-09 API.

### CODE REVIEW

**Comment by yungezz** [comment]
hi @ctaggart, before removing API, impact to downstream SDKs/client tools need to be confirmed. Has this rest API been released in any SDKs?

**Comment by yungezz** [comment]
hi @dingmeng-xue @arrownj could you pls help to confirm whether this API version used in Azure Powershell/Azure CLI? thanks.

**Comment by dingmeng-xue** [comment]
> hi @dingmeng-xue @arrownj could you pls help to confirm whether this API version used in Azure Powershell/Azure CLI? thanks.

No for Azure PowerShell. I didn't find its SDK for dotnet either.

**Comment by arrownj** [comment]
> hi @dingmeng-xue Dingmeng Xue FTE @arrownj Xiaojian Xu FTE could you pls help to confirm whether this API version used in Azure Powershell/Azure CLI? thanks.

No for both azure-cli and azure-cli-extensions. Even no python SDK found.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
