### PR TITLE
Release microsoft.sql 2021-11-01 Stable API version

### PR DESCRIPTION
**Pull request by ericshape**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

Release Microsoft.SQL 2021-11-01 stable API version.
- Move 2021-11-01-preview (released in prod over 6 months ago) to 2021-11-01 stable version
- all the changes are just adding 2021-11-01 swagger files into stable API folder: https://github.com/Azure/azure-rest-api-specs/pull/19863/files#diff-a9813225adad9c543578640d5522406a91874f99551b8ee8466925afb518abd3
- image

- Carry these four APIs from last stable API version: 2014-04-01
DataMaskingPolicies.json , DataMaskingRules.json, GeoBackupPolicies.json , RecoverableDatabases.json and ServerUsages.json
> Microsoft.Sql/stable/2014-04-01-legacy/backups_legacy.json
> Microsoft.Sql/stable/2014-04-01/dataMasking.json
> Microsoft.Sql/stable/2014-04-01/geoBackupPolicies.json
> Microsoft.Sql/stable/2014-04-01-legacy/usages_legacy.json

We directly copy the 2021-11-01-preview to this stable version. Thus, these exceptions are carried on. We still ask for exceptions for these failed checks: 

The List methods are Delete method are not needed based on SQL business justification. 

❌ DeleteOperationResponses | The delete operation is defined without a 200 or 204 error response implementation,please add it.'Location: Microsoft.Sql/stable/2021-11-01/DatabaseVulnerabilityAssessmentRuleBaselines.json#L252
-- | --
❌ NestedResourcesMustHaveListOperation | The nested resource 'DatabaseVulnerabilityAssessmentRuleBaseline' does not have list operation, please add it.Location: Microsoft.Sql/stable/2021-11-01/DatabaseVulnerabilityAssessmentRuleBaselines.json#L269
❌ NestedResourcesMustHaveListOperation | The nested resource 'DataMaskingPolicy' does not have list operation, please add it.Location: Microsoft.Sql/stable/2021-11-01/DataMaskingPolicies.json#L149
❌ NestedResourcesMustHaveListOperation | The nested resource 'DataMaskingRule' does not have list operation, please add it.Location: Microsoft.Sql/stable/2021-11-01/DataMaskingRules.json#L167

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [x] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by ericshape** [comment]
> Hi, @ericshape your PR are labelled with WaitForARMFeedback. A notification email will be sent out shortly afterwards to notify ARM review board([armapireview@microsoft.com](mailto:armapireview@microsoft.com)).

We asked ARM reviewer to sign off for ARM PROD manifest deployment.

**Comment by raosuhas** [comment]
@ericsharpe Looks like the following files : DataMaskingPolicies.json , DataMaskingRules.json, GeoBackupPolicies.json , RecoverableDatabases.json and ServerUsages.json do not have the previous version checked in the first iteration. Are these new files that need to be reviewed or are they also already reviewed in a previous version ?

**Comment by raosuhas** [comment]
Please respond to the comments and remove the "ARMChangesRequested" label when this PR is ready for review again .

**Comment by ericshape** [comment]
> @ericsharpe Looks like the following files : DataMaskingPolicies.json , DataMaskingRules.json, GeoBackupPolicies.json , RecoverableDatabases.json and ServerUsages.json do not have the previous version checked in the first iteration. Are these new files that need to be reviewed or are they also already reviewed in a previous version ?

@raosuhas thanks for the review. 
These four APIs groups are carried from the last stable APIs version: 2014-04-01 to this new stable API version. (they are also in the v5-SDK tag)

- Microsoft.Sql/stable/2014-04-01/dataMasking.json
- Microsoft.Sql/stable/2014-04-01/geoBackupPolicies.json
- Microsoft.Sql/stable/2014-04-01-legacy/usages_legacy.json

We did not change any of their API contracts. They are safe to add. 
I have updated the PR description.

**Comment by ericshape** [comment]
> Please respond to the comments and remove the "ARMChangesRequested" label when this PR is ready for review again .

@raosuhas I have addressed your comments. can we have your review again?

**Comment by raych1** [comment]
@jianyexi , can you assist what are duplicated model name?

**Comment by jianyexi** [comment]
The lintDiff error was caused by the duplicated model  'DatabaseVulnerabilityAssessmentRuleBaselineProperties' in 
stable/2021-11-01/ManagedDatabaseVulnerabilityAssessmentRuleBaselines.json
and stable/2021-11-01/DatabaseVulnerabilityAssessmentRuleBaselines.json , please unify it

**Comment by ericshape** [comment]
> The lintDiff error was caused by the duplicated model 'DatabaseVulnerabilityAssessmentRuleBaselineProperties' in stable/2021-11-01/ManagedDatabaseVulnerabilityAssessmentRuleBaselines.json and stable/2021-11-01/DatabaseVulnerabilityAssessmentRuleBaselines.json , please unify it

I have addressed this comment.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
