### PR TITLE
Adding AML Workspace ID Property

### PR DESCRIPTION
**Pull request by mvvsubbu**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by shafqatanwar — APPROVED** [review]
I thought we already had this parameter?  I guess it was missing form swagger, i assume?

**Comment by mvvsubbu** [comment]
> I thought we already had this parameter? I guess it was missing form swagger, i assume?

Yes this was not exposed, but now we are suggesting to unlink via ARM template deployment and hence this parameter should be visible in ARM template reference. So adding in swagger

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
As identified in the automated checks there are breaking changes, please follow Azure Breaking changes approval request form as defined @[Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

**Comment by mvvsubbu** [comment]
> As identified in the automated checks there are breaking changes, please follow Azure Breaking changes approval request form as defined @[Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

This change is not breaking change. The current property is already supported by our service and we are exposing it in swagger. This is an optional parameter which don't need to specify always. Let us know if we want to discuss further on this.

**Pull request merged**
