### PR TITLE
[Network] Version change for vmss to 2017-03-30

### PR DESCRIPTION
**Pull request by akshaysngupta**
Version change for vmss to 2017-03-30

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @akshaysngupta 
I'm sorry, but the problem is not only that the file is not consistent with multiple ApiVersion, but you put a file with a "2017-03-01" api version inside the 2016-06-01 folder :(
Can't you update this file as well in the 2017-03-01 folder?

**Comment by lmazuel** [comment]
Note too that the enum becomes overkill and error prone, if the whole file is using 2017-03-01

**Review by DeepakRajendranMsft — APPROVED** [review]

**Comment by salameer** [comment]
@lmazuel after chating with @DeepakRajendranMsft, is seems that this is required because other Networking swaggers under the new API version assume that this swagger is available in the same API version and take it for granted. @amarzavery deepak mentioned that this was the recommendation in the past any recommendations or thoughts on how to resolve this without having to copy and paste the swagger from the older API version?

**Comment by lmazuel** [comment]
@salameer I don't understand sorry :(. It seems to me that the "2017-03-30" file, should be under the "2017-03-30" folder. That's it... Nothing prevents to do a "mixed up apiversion composite file" if necessary (look at [SQL](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/compositeSql.json) for instance, or [monitor](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/compositeMonitorManagementClient.json)) to pick different API version.

We are not talking features or RestAPI here, but just folder structure (note that the [reorg follows the same concept](https://github.com/Azure/azure-rest-api-specs/tree/reorg/specification/network/resource-manager/Microsoft.Network)). It's totally not logical to find a good reason to put "2017-03-30" under the "2017-06-01" folder...

@olydis @fearthecowboy @amarzavery

**Comment by olydis** [comment]
agree with @lmazuel, copying this file to the wrong API version folder makes no sense. If it's `2017-03-30`, stick it in `2017-03-30`, if it's `2017-03-30`, create a corresponding folder `2017-03-30`, stick it in there and point to it from the composite.

**Review by olydis — CHANGES_REQUESTED** [review]
folder structure makes no sense - synced with team, understand why this has to happen 👍

**Comment by olydis** [comment]
talked to @salameer, awaiting further information

**Review by olydis — CHANGES_REQUESTED** [review]
*most importantly*: `vmssNetworkInterface.json` overrides the API version in all its methods to `2016-09-01`, so why claim something else in the `info`? Regardless of what we come up with regarding folder structure, the guidance is simple: One Swagger, one API version. Specify that api-version in the `info`. Do not contradict that value in any operation. So at the very least: In `vmssNetworkInterface.json`, either change the version in `info` to `2016-09-01` or change all the overrides to `2017-03-30`.

Anything else will mess with code generation and confuse readers.

**Comment by olydis** [comment]
Looking at https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-12-01/swagger/vmssNetworkInterface.json which also contains contradicting API versions in one Swagger file. 
 Can you explain why?

Back in https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/vmssNetworkInterface.json#L199 you had the api-version parameter factored out, which greatly improves readability, reduced redundancy and hence also lowers the risk of copy paste problems like the one (I assume) we're dealing with now. Why was this refactoring undone?

Don't get me wrong, I understand why VMSS has to version independently, but currently we are in a situation with *3* API versions involved in one file:
1) folder that the Swagger is in
2) `info` section
3) `api-version` overrides

I'd expect 2 and 3 to be the same for VMSS (and 1&2&3 to be the same for all others, but I think that's the case now).

**Comment by DeepakRajendranMsft** [comment]
Guys, i am actually confused here. Can i ask you guys to send a PR here instead of going back and forth? (it should be small right, if any with just files moved around)

**Comment by lmazuel** [comment]
@DeepakRajendranMsft I understand completely, I was in the fog myself until recently :)

@olydis @akshathapaik I think the conclusion of the email thread was it's ok for now to have duplicate files for VMSS in 2017-03-01 and 2017-06-01, to allow Autorest to share the models (but it's a workaround until better solution of model sharing).

So this PR is the correct workaround and shall be merged as it (in my humble opinion).

**Comment by salameer** [comment]
@deepakjangid-MSFT and @akshaysngupta please take a look at Johaness' comment above to get this resolved quick. There are still multiple API version mentioned in that file

**Comment by salameer** [comment]
@deepakjangid-MSFT  back to your request on the PR, we're not sure on our side why are there multiple values, we think that 2017-03-30 is the right value but we can't make that assumption. our only guidance is that there should be 1 api version referenced across the whole file :)

**Comment by deepakjangid-MSFT** [comment]
@DeepakRajendranMsft 
Adding correct Deepak to thread.

**Comment by lmazuel** [comment]
@salameer @DeepakRajendranMsft You're right, I take back what I said earlier: looking at the files removing all "enum" on api-version should be the right think to do.

**Comment by olydis** [comment]
@lmazuel I heard that adding all those `enum` overrides was recommended earlier (does anyone know why???), but still, I'd at least factor out the `api-version` parameter (as was done previously) so at least there are only 2 locations (`info` section, `parameters` section) where the api-version has to be checked/updated in the future... instead of 4! 😄

**Comment by DeepakRajendranMsft** [comment]
okay, just to confirm. you want us to remove the custom api version query parameter from the vmss swagger specs : https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2017-06-01/swagger/vmssNetworkInterface.json#L68

and replace it with 
{
            "$ref": "#/parameters/ApiVersionParameter"
          },
which is what we have done for other specs?

if that is the case. can we still merge this PR. i will send a following PR with this change

**Comment by olydis** [comment]
covered by https://github.com/Azure/azure-rest-api-specs/pull/1380, thanks @DeepakRajendranMsft!

**Pull request closed without merging**
