### PR TITLE
[Datashare]Add sorting query parameters

### PR DESCRIPTION
**Pull request by vnvaditya**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by akning-ms** [comment]
Hi @vnvaditya, can you give us change log for this PR? and help to adjust some order for operation to make diff tool more user friendly? it looks too many change in PR now

**Comment by vnvaditya** [comment]
Hello, here are the changes to the swagger that are included in this PR.

[905c134ab079714cbbc85428fdf0c81339c53e6e](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/905c134ab079714cbbc85428fdf0c81339c53e6e?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json)
[a7405c2d2ea24dbb8bda2ee2f6bc0354084e629d
](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/a7405c2d2ea24dbb8bda2ee2f6bc0354084e629d?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json)

[1227fe1fe951c6fbcb34522882cb8981e2733164](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/1227fe1fe951c6fbcb34522882cb8981e2733164?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json)

[1f903fcda5995e61a3b7b2f62b5a19258aa29c4c](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/1f903fcda5995e61a3b7b2f62b5a19258aa29c4c?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json)

[ab26c7adf2cf678889772e233948ded338533ac3](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/ab26c7adf2cf678889772e233948ded338533ac3?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json)

[39a0002fdf84927727f74b50c644a52c303cde9b ](https://msdata.visualstudio.com/AzureDataExchange/_git/AzureDataShare/commit/39a0002fdf84927727f74b50c644a52c303cde9b?refName=refs%2Fheads%2Fmaster&path=%2Fsrc%2Ftools%2FSwaggerValidator%2Fresource-manager%2FMicrosoft.DataShare%2Fstable%2F2019-11-01%2FDataShare.json&_a=compare)(Just Sorting)

**Comment by akning-ms** [comment]
Hi @vnvaditya, I mean the order of path/operation in swagger is different in new swagger. it caused me difficult to review which part is your really change. is this swagger  generated automatically?

**Comment by vnvaditya** [comment]
@akning-ms  - We are automatically generating the swagger and it was causing issues with reviews. So, we decided that we will order the operations and paths etc alphabetically for once. This will make reviews better going forward.

**Comment by vnvaditya** [comment]
I can create one PR with just the changes but will have to followup another PR for re-ordering.

**Comment by vnvaditya** [comment]
@akning-ms - I reverted the ordering of the API's . Once this is approved and merged, I'll create another PR for re-ordering.

**Comment by akning-ms** [comment]
Thanks @vnvaditya,  LGTM for API perspecitve, but FYI, your PR changed breaking change for python sdk as show here:
https://github.com/Azure/azure-rest-api-specs/pull/10209#issuecomment-661489205  @changlong-liu  for awareness (python SDK owner)   if you confirm it is expected. I will help you merged it

**Comment by vnvaditya** [comment]
@akning-ms - That was before when I added sorting. if you see after the latest commit, all 27 checks are succesfully passed. there are no breaking changes.

**Comment by vnvaditya** [comment]
@akning-ms - The python failure was for my first iteration. After I reverted the API ordering, all 27 checks are passed and I think there are no breaking changes.

**Comment by changlong-liu** [comment]
> @akning-ms Arthur Ning FTE - The python failure was for my first iteration. After I reverted the API ordering, all 27 checks are passed and I think there are no breaking changes.

Hi @vnvaditya , this change will bring breaking changes in Python SDK: https://github.com/Azure/azure-rest-api-specs/pull/10209#issuecomment-661489205  . It's because new parameters are added. Please make sure they are expected.

**Comment by vnvaditya** [comment]
@changlong-liu - We added query parameters for sorting and filtering. Any reason why they are breaking changes just for Python API only ?

My assumption is they should not be.

**Comment by vnvaditya** [comment]
@changlong-liu - We just added query parameters for filtering and sorting. I'm not sure if this should be considered as breaking changes. The industry standard is we should be ok with query parameters. Also, Java, .net and other sdk's seems fine. 

If Python restricts us by doing so, we are fine with this breaking change. We don't have any Python SDK customers based on the traffic and communicate if we have any. Please sign off. 

Thanks,
Aditya

**Review by akning-ms — APPROVED** [review]

**Comment by changlong-liu** [comment]
Hi @vnvaditya , adding query parameters is a breaking change in current Python SDK. 

You may refer to here to understand why it is breaking: https://github.com/AzureSDKAutomation/azure-sdk-for-python/commit/50af844d9eaef73bbd58343c07cbf4e18fc60894#diff-6602c76927522f9562221eff283c90ceR250

For other languages: if they don't have tail parameters like custom_headers and raw, then it's not a breaking change.

**Pull request merged**
