### PR TITLE
Add missing nextLink in authorization and intune

### PR DESCRIPTION
**Pull request by mcardosos**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mcardosos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mcardoso). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Review by tbombach — APPROVED** [review]
LGTM. I think we should change the descriptions for these files so that "Gets or sets" doesn't appear in the description, but we'll do that in a separate PR.

**Comment by tbombach** [comment]
(I'll merge it after the tests finish, I just wanted to try out Github's new "Approve changes" button)

**Comment by mcardosos** [comment]
I added those like that because other models in this file that included the nextLink did it that way.
Ohhh, shiny new button OwO

**Comment by lmazuel** [comment]
I confirm this fixes https://github.com/Azure/azure-rest-api-specs/issues/354
Thanks a lot!

**Pull request merged**
