### PR TITLE
Changed skill-related enums to strings for values that may change

### PR DESCRIPTION
**Pull request by jennifermarsman**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [X] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
@jennifermarsman These enums are defined by us, right? It's not like `LexicalAnalyzerName`, where they can introduce their own values at run-time? I'm not sure these enums really need to be extensible. Unless we want to be able to add new values without shipping new SDKs, I don't know that there's a strong justification for this change.

@heaths I remember we talked about this, and non-extensible enums can be changed in a backward-compatible way in each target language, right?

**Comment by heaths** [comment]
Yes, so long as changes are merely additive. Names and values (often the same thing) that have already shipped can't change - even for extensible enums (compilation errors will occur).

**Review by tjprescott — APPROVED** [review]

**Comment by jennifermarsman** [comment]
@brjohnstmsft @heaths "these enums are defined by us" - it depends if you mean us as Microsoft or us as the Cognitive Search team.  These enums define values used in the skills, which are really defined by the Cognitive Services team, and they can/do/will change as they change their APIs.

**Comment by brjohnstmsft** [comment]
@jennifermarsman I meant us as in not customers of the service. I think this change was unnecessary, but let's see what comes up in the API review board.

**Pull request merged**
