### PR TITLE
Microsoft.StorageSync: adding new API version 2019-02-01

### PR DESCRIPTION
**Pull request by anpint**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by anpint** [comment]
This PR simply contains a copy of our previous API version (2018-10-01) that was used to create the new API version.

**Comment by anpint** [comment]
@ankushbindlish2 Adding to review.

**Comment by ankushbindlish2** [comment]
>         "version": "2018-10-01",

change the api version. we can change example's api version in next PR

---
Refers to: specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2019-02-01/storagesync.json:6 in 8667b0a. [](commit_id = 8667b0a2b3ce9518659f3f883842bc5aa88cd6cb, deletion_comment = False)

**Comment by anpint** [comment]
Will open another PR using OpenAPIHub

**Pull request closed without merging**
