### PR TITLE
Temporarily remove examples

### PR DESCRIPTION
**Pull request by gatneil**
Temporarily removing examples I added in PR https://github.com/Azure/azure-rest-api-specs/pull/1575 for 2 reasons:

1) As indicated in issue https://github.com/Azure/azure-rest-api-specs/issues/1740, the current ones are invalid.
2) We are investigating a different process for creating and maintaining examples.

So I'll remove the examples I added for now, then add them back once we figure out the new process :). One might worry that by removing the examples I'm negatively impacting the REST API docs, but the REST API docs for Compute aren't using these examples yet, so this isn't a concern.

### CODE REVIEW

**Comment by olydis** [comment]
@salameer @veronicagg any concerns? Should be fine for the reasons @gatneil mentioned, but still it's a removal of files, so wanna make sure.

**Comment by olydis** [comment]
@salameer @veronicagg ping

**Comment by olydis** [comment]
@gatneil Please move ahead with this PR

**Comment by olydis** [comment]
@gatneil I will close this soon due to inactivity.

**Comment by gatneil** [comment]
@olydis This PR is ready to merge. I don't have merge access though :). Could you merge it?

**Comment by olydis** [comment]
> This PR is ready to merge.

Unfortunately I can't, it has merge conflicts! Please resolve. 🙂

**Comment by gatneil** [comment]
Ah, yes; my bad; it was easier to just redo the changes in a different PR here :): https://github.com/Azure/azure-rest-api-specs/pull/1885

**Comment by olydis** [comment]
moved to https://github.com/Azure/azure-rest-api-specs/pull/1885

**Pull request closed without merging**
