### PR TITLE
[DataFactory]Support Iceberg Format As Sink

### PR DESCRIPTION
**Pull request by Jingshu918**
# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

### CODE REVIEW

**Comment by ramoka178** [comment]
I dont see the newly added properties being used in these files. What is the scope of this PR ? 
Please fill https://github.com/Azure/azure-rest-api-specs/pull/30357#issue-2491514576 so that the reviewer can understand what this PR is for

**Comment by Jingshu918** [comment]
Seems I could not select the choices, this PR is for Control Plane (ARM) API

**Comment by ramoka178** [comment]
> @ramoka178 Seems I could not select the choices, this PR is for Control Plane (ARM) API

But why are the definitions added without being used ? example, I dont see IcebergSink and IcebergDataset being used in this PR

**Comment by Jingshu918** [comment]
@ramoka178  It is ADF by designed, customers could use IcebergSink and IcebergDataset directly, they are defined based “CopySink” and "Dataset", It sames with our existing feature "BinarySink" and "BinaryDataset".
https://learn.microsoft.com/en-us/azure/data-factory/format-binary

Customers will know how to use them in SDK or Rest api.

**Comment by ramoka178** [comment]
> BinaryDataset

Similar previous PR for context https://github.com/Azure/azure-rest-api-specs/pull/6631/files

**Review by ruowan — APPROVED** [review]

**Pull request merged**
