### PR TITLE
Removed unused fields from ActionType

### PR DESCRIPTION
**Pull request by sushantsingh**
Removed some unused fields from ActionType
Removed the following which we don't plan to support anymore for the preview release

- redirectUrl
- customBlockResponseStatusCode
- customBlockResponseBody
- customBlockResponseBody

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by yaohaizh** [comment]
@sushantsingh Just fix the json format first so that I can help review, thanks.

**Comment by sergey-shandar** [comment]
@csmengwan @injyzarif @prakharsharma10 please review.

**Comment by ravbhatnagar** [comment]
checked with @sushantsingh  and these APIs are not used by customers yet. Checked Kusto logs and the most of the traffic seems to be from MSFT tenant (and so internal testing). Since its preview and no customer usage, signing off on this change from ARM side.

**Comment by yaohaizh** [comment]
@sushantsingh please fix the errors about semantic check/model validation/lintdiff etc.: 
 https://dev.azure.com/azure-sdk/public/_build/results?buildId=56493&view=results

**Comment by yaohaizh** [comment]
@sushantsingh  Any update on this?

**Comment by yaohaizh** [comment]
@sushantsingh Could you help resolve this issue https://dev.azure.com/azure-sdk/public/_build/results?buildId=66427&view=logs&j=95dbed5b-845d-57ba-33d3-f6c5e69afcf4&t=44f1510e-a822-56b0-2e0b-241e0a387c6a&l=29

**Comment by MyronFanQiu** [comment]
@sushantsingh Hello. Several new checks are added into CI. Please resolve them.

**Comment by yungezz** [comment]
hi @sushantsingh could you pls address the comments? Or is it ok to close the PR? the PR is there over months. Pls create new PR when you're ready for updating and merge.

**Comment by yungezz** [comment]
hi @sushantsingh are you still on this PR? is it ok to close the PR if you're not planning to work on it?

**Pull request closed without merging**
