### PR TITLE
[Travis CI] Use new version of oad in the CI job

### PR DESCRIPTION
**Pull request by vladbarosan**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by jianghaolu** [comment]
@vladbarosan Can you share a little bit of context why is this change needed?

**Comment by vishrutshah** [comment]
@jianghaolu This is just regarding the bug we are having with breaking change tool in CI. I am assigning it to me :)

**Review by vishrutshah — DISMISSED** [review]
Seems like we are having the same issue that we saw on the local box:

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/289276075#L615

**Review by veronicagg — APPROVED** [review]
LGTM, thanks!
BTW, did you re-do the commits? I only see one, but also see a comment from Vishrut with a link to a failed Travis job. In the future, try not to remove old commits, so the review is easier to follow (unless there are so many commits that becomes worse :)). thanks!

**Comment by vladbarosan** [comment]
@veronicagg that one is from an old job where it was still failing. Yes I squashed the commits since it was messy. I saw know that I can squash them on complete PR so will do so in the future :) .

**Pull request merged**
