### PR TITLE
add kusto track2 config

### PR DESCRIPTION
**Pull request by 00Kai0**

### CODE REVIEW

**Comment by zhenglaizhang** [comment]
the python sdk looks generated successfully. 
@changlong-liu can you help double confirm it the update works well?

@ArcturusZhang only readme python track 2 section is updated, but sdk go breaking change detected, can you help take a look we i can ignore this?

**Comment by ArcturusZhang** [comment]
> the python sdk looks generated successfully.
> @changlong-liu can you help double confirm it the update works well?
> 
> @ArcturusZhang only readme python track 2 section is updated, but sdk go breaking change detected, can you help take a look we i can ignore this?

There is no swagger change, please ignore

**Comment by changlong-liu** [comment]
LGTM

**Comment by zhenglaizhang** [comment]
@00Kai0 
BTW for the java sdk failure, it looks like there is a wrong tag here https://github.com/00Kai0/azure-rest-api-specs/blob/kaihuis-track2-kusto/specification/azure-kusto/resource-manager/readme.java.md#java-multi-api

**Comment by zhenglaizhang** [comment]
@weidongxu-microsoft help take look at the java readme tag issue? If required, it's much better to fix the issue

**Comment by zhenglaizhang** [comment]
@msyyc @jsntcy Pls help review this to help unblock the merging. thanks!

**Review by msyyc — APPROVED** [review]

**Pull request merged**
