### PR TITLE
Swagger Linting Fix

### PR DESCRIPTION
**Pull request by david-msft**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [X] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [x] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [x] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by david-msft** [comment]
Not sure how to resolve the breaking change because it is required to resolve Swagger Linting issue that Swagger team requests us to fix. Please advise.
meanwhile, submitted breaking change review https://msazure.visualstudio.com/One/_dashboards/dashboard/f7db6895-7137-4695-b3f5-00dc4d36758f

**Comment by david-msft** [comment]
Hi @ruowan,
Can you please provide suggestion for getting green on Swagger BreakingChange and SwaggerModelValidation?
   - The current BreakingChange is needed to resolve Swagger Linting issue.
   - I am not sure why the Model Validation is failed because I did not make any change to it, we don't have a new update on the API version so that it should stay the same.
Thanks

**Comment by ruowan** [comment]
For breaking chanage, once your breaking change is approved by breaking change reivew board, I could merge it. For model validation, Why do you put readonly property provisioningState as parameter?

**Comment by david-msft** [comment]
@ruowan okay I see.
For the Model validation, I would need to check with my team. But, I did not touch any of those so they were there in the first place, and If we could go through the test previously, why not this time. (not really understand.... are there an alternative way I can fix them or bypass the test) I didn't change any of those since my task was to fix the Swagger Linting issue, so I only touched the relevant field. 
Thanks!

**Comment by ruowan** [comment]
Maybe there are some issues in previous check in PR. But you need to fix ModelValidation Error, since it's a required check. If no pass, I couldn't merge the PR. 

Here is your example: https://github.com/Azure/azure-rest-api-specs/blob/453f24ebec39d22b46e99abf5f31edb18fda7736/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/examples/createCapacity.json#L23. Seems provisoningState is in parameters. It's conflict with its readonly property.

**Comment by david-msft** [comment]
Yes, I  think you're right. I believe it is the example, which contains the Readonly parameter in the request, causes the problem. I fixed them by removing them from the request example

**Comment by ruowan** [comment]
Cool. Could you please paste your linting work item here? I want to have a look.

**Comment by david-msft** [comment]
Sure https://msazure.visualstudio.com/Swagger%20KPIs/_workitems/edit/8188301

**Comment by ruowan** [comment]
Ok. When you get breaking change approval, I will merge it.

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
