### PR TITLE
Marking the movestatus/moveresourcerror properties as readonly.

### PR DESCRIPTION
**Pull request by innosam**
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Review by karthik-mut — APPROVED** [review]

**Review by ajaygit158 — APPROVED** [review]

**Comment by innosam** [comment]
Breaking Change:
The service is in private preview, and we are doing this fixes/improvements as part of public preview that is tentatively planned on 23th September 2020.
Additionally our private preview customer do not use the API's directly instead rely on the portal for the usage.

We are also working on releasing auto generated PowerShell and SDK's so the swagger is being actively validated before public preview.

Breaking-change Reason:
The MoveResourceStatus and MoveResourceError are referred in the [MoveResourceProperties ](https://github.com/Azure/azure-rest-api-specs/blob/ac41d11e5195c9588faaf516d0f3707880ed6042/specification/regionmove/resource-manager/Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1153) and are referred as read only using the following pattern.

`        "moveStatus": {
          "description": "Defines the move resource status.",
          "allOf": [
            {
              "$ref": "#/definitions/MoveResourceStatus"
            }
          ],
          "readOnly": true
        },`

However, due to a bug in PowerShell auto generation, it is not respecting the readOnly field, so a workaround is suggested to mark the individual properties of the MoveResourceStatus and Errors as read-only as well.

Rule | Message
-- | --
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L932:5Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L932:5
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1543:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L983:5Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L982:5
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L999:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L997:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1002:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1000:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1013:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1010:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1002:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1000:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1543:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1552:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1557:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1551:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1562:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1555:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1552:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1557:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1551:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1562:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1555:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1562:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1555:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1022:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1019:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1543:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1552:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1547:9
❌ 1029 - ReadonlyPropertyChanged | The read only property has changed from 'false' to 'true'.New: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1557:9Old: Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json#L1551:9

**Comment by ArcturusZhang** [comment]
Approved breaking changes since this is a preview api-version within one year

**Comment by ArcturusZhang** [comment]
Hi @innosam this PR LGTM, please let me know if this is good to merge, thanks

**Comment by innosam** [comment]
> Hi @innosam this PR LGTM, please let me know if this is good to merge, thanks

Thanks, please go ahead and merge.

**Pull request merged**
