### PR TITLE
Removing reportconfig paths from stable version, as they are in previ…

### PR DESCRIPTION
**Pull request by ms-premp**
…ew version and in new version these are to be removed

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [Y] The title of the PR is clear and informative.
- [Y] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [Y] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [] If applicable, the PR references the bug/issue that it fixes.
- [Y] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [Y] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [Y] My spec meets the review criteria:
  - [Y] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [Y] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [Y] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by shalinved** [comment]
@ravbhatnagar @sergey-shandar  - We discussed splitting removal of Reports API from stable version and addition of a preview version earlier. Now that the preview version is available, this PR just removes Reports API from our stable version.

**Comment by ms-premp** [comment]
@hovsepm the swagger for the new version of this API was just merged in and it missed removal of these paths.. as discussed earlier with @sergey-shandar and @ravbhatnagar ... so It would be safe right now to get this change merged in before SDK generations are affected.

**Comment by hovsepm** [comment]
@sergey-shandar and @ravbhatnagar  please take a look and sign-off...

**Comment by hovsepm** [comment]
@ms-premp please remove all the type definitions that are not used anywhere. There is no need to keep them in this swagger file anymore.

**Comment by sergey-shandar** [comment]
@hovsepm I'm reassigning this one to @sarangan12

**Review by sarangan12 — APPROVED** [review]

**Review by sarangan12 — DISMISSED** [review]
There are items such as ReportConfigListResult which are not used anywhere. Please remove all of the unused items.

**Comment by ms-premp** [comment]
@sarangan12 and @hovsepm, I have removed the unused items. Please review.

**Review by hovsepm — APPROVED** [review]

**Comment by ravbhatnagar** [comment]
This was discussed over email and the apis have been renamed to /reports. There was no external usage and hence the team was ok to make this breaking change. Signing off from ARM.

**Comment by ms-premp** [comment]
@sarangan12 @hovsepm requesting to please merge it.

**Pull request merged**
