### PR TITLE
[Don't merge yet] ADHybridHealthService: "type" should be "array" when "items" is present.

### PR DESCRIPTION
**Pull request by sergey-shandar**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@gamitra could you review this?

**Comment by jianghaolu** [comment]
@sergey-shandar If "items" is present, the type is defaulted to array?

**Comment by sergey-shandar** [comment]
@jianghaolu good question. As far as I understood, if `"type"` is not present then it's became `any` type (which is union type of 'object', 'array', 'string', 'null', 'number', 'boolean', 'integer'). `"items"` are only applied if the type of instance is an array. So, current specs says that the `"type"` is `"object"` and specifies the array items. The type `object` can't have array items. Only the `array` type can have `items`. `any` type is a superset of `array`.

**Comment by sergey-shandar** [comment]
@jianghaolu in simple words, we need confirmation from owners what is the type of these models. Current type definitions make no sense.

**Comment by jianghaolu** [comment]
@sergey-shandar Thanks for explaining! I think this is okay - I'm not sure if this is a breaking change per every SDK. Some SDKs might be generating an array type before this change?

**Comment by hovsepm** [comment]
@sergey-shandar are you still working on this? no progress for 4 month. Time to close?

**Comment by salameer** [comment]
Closing since this has been idle for a while, reopen if required

**Comment by JackTn** [comment]
Hi, @sergey-shandar. The PR has be closed for a long time and it's related branch still exist. If no further used for over 14 days, I will delete this related branch. Please tell me if you still need this branch.

**Comment by JackTn** [comment]
Hi, @sergey-shandar. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @sergey-shandar. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Comment by JackTn** [comment]
Hi, @sergey-shandar. The PR has be closed for a long time and it's related branch still exist. Please tell me if you still need this branch or i will delete it in 14 days.

**Pull request closed without merging**
