### PR TITLE
Alec baird desktopvirtualization microsoft.desktop virtualization 2023 10 04 preview

### PR DESCRIPTION
**Pull request by alec-baird**
# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [x] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by alec-baird** [comment]
As with previous PR's, the LintDiff error on hostpoolName would cause breaking changes to customers who have had hostpools for years, can we get an exception for this please?

**Comment by ms-zhenhua** [comment]
>             "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter"

please always use the latest version v5. Please also confirm other places.

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:3269 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>         },

systemData should already exists in common-types/resource-management/v3/types.json#/definitions/TrackedResource ?

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5430 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "type": "boolean",

consider using enum instead of boolean:

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5548 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "type": "boolean",

consider using enum instead of boolean:

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5553 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>           "type": "boolean",

consider using enum instead of boolean:

[https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md](https://github.com/Azure/azure-openapi-validator/blob/main/docs/enum-instead-of-boolean.md)

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5598 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DesktopVirtualization/hostPools/{hostPoolName}/importAppAttachPackageInfo": {

seems it should be listAppAttachPackageInfo?

---
Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:3255 in 4d87c70. [](commit_id = 4d87c702e3b8092d6bc353c2186653f8f62b5836, deletion_comment = False)

**Comment by ms-zhenhua** [comment]
> Swagger-Suppression-Process

please follow [Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) to suppress this error.

**Comment by charleskorb** [comment]
> > ```
> > "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DesktopVirtualization/hostPools/{hostPoolName}/importAppAttachPackageInfo": {
> > ```
> 
> seems it should be listAppAttachPackageInfo?
> 
> https://stackoverflow.microsoft.com/questions/269397
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:3255 in [9527a6b](https://github.com/Azure/azure-rest-api-specs/commit/9527a6b5ff8330e73f783309f1f9891033225595). [](commit_id = [9527a6b](https://github.com/Azure/azure-rest-api-specs/commit/9527a6b5ff8330e73f783309f1f9891033225595), deletion_comment = False)

We don't feel list is appropriate in this case and that import would be the verb that makes the most sense. The package info is stored inside a VHD file that the customer provides the path to and this will get the information from that path without creating any objects (a provided vhd can contain multiple files that could be used to create app attach packages, while the customer may only want to create packages for some of them).

We chose import because it seemed like the best fit from this list https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.3

**Comment by charleskorb** [comment]
> > ```
> >     },
> > ```
> 
> systemData should already exists in common-types/resource-management/v3/types.json#/definitions/TrackedResource ?
> 
> Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5430 in [4d87c70](https://github.com/Azure/azure-rest-api-specs/commit/4d87c702e3b8092d6bc353c2186653f8f62b5836). [](commit_id = [4d87c70](https://github.com/Azure/azure-rest-api-specs/commit/4d87c702e3b8092d6bc353c2186653f8f62b5836), deletion_comment = False)

All of our other top level arm objects are ResourceModelWithAllowedPropertySet. Should we be using that for this top level object as well?

**Comment by ms-zhenhua** [comment]
> > > ```
> > >     },
> > > ```
> > 
> > 
> > systemData should already exists in common-types/resource-management/v3/types.json#/definitions/TrackedResource ?
> > Refers to: specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json:5430 in [4d87c70](https://github.com/Azure/azure-rest-api-specs/commit/4d87c702e3b8092d6bc353c2186653f8f62b5836). [](commit_id = [4d87c70](https://github.com/Azure/azure-rest-api-specs/commit/4d87c702e3b8092d6bc353c2186653f8f62b5836), deletion_comment = False)
> 
> All of our other top level arm objects are ResourceModelWithAllowedPropertySet. Should we be using that for this top level object as well?

You can use ResourceModelWithAllowedPropertySet in https://github.com/Azure/azure-rest-api-specs/blob/fe6e5b6e46f03c2c23f16029f25431bc90e07de2/specification/common-types/resource-management/v5/types.json#L101, which already contains the systemData

**Comment by rkmanda** [comment]
Please address the one failure called out here - [https://github.com/Azure/azure-rest-api-specs/pull/26142/checks?check_run_id=17848349322](https://github.com/Azure/azure-rest-api-specs/pull/26142/checks?check_run_id=17848349322)

**Comment by alec-baird** [comment]
Is this Patch Lint failure required? None of our other Patch calls have an identity, so I am wondering why we need this one to have a patch. If it does, what type of implementation is expected, we haven't added identity property before. Please answer before passing PR back to us :)

**Comment by ms-henglu** [comment]
> Is this Patch Lint failure required? None of our other Patch calls have an identity, so I am wondering why we need this one to have a patch. If it does, what type of implementation is expected, we haven't added identity property before. Please answer before passing PR back to us :)

Hi @alec-baird,

The AppAttachPackage defined [here](https://github.com/Azure/azure-rest-api-specs/blob/e85df9a391fe87816fd2bdf833cd0e5e69a8be3c/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2023-10-04-preview/desktopvirtualization.json#L5420), extends [ResourceModelWithAllowedPropertySet](https://github.com/Azure/azure-rest-api-specs/blob/e85df9a391fe87816fd2bdf833cd0e5e69a8be3c/specification/common-types/resource-management/v5/types.json#L102) which supports identity. The `identity` definition defined in the `common-types` supports update (x-ms-mutability is NOT [create, read]).

That's reason the linter failed, to fix it, please refer this doc: https://github.com/Azure/azure-openapi-validator/blob/main/docs/patch-identity-property.md

**Review by ms-henglu — APPROVED** [review]

**Comment by ms-henglu** [comment]
Hi @alec-baird ,

Please get a Go sdk breaking change approval, you could find the approvers list from https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750

**Comment by rkmanda** [comment]
> Hi @alec-baird ,
> 
> Please get a Go sdk breaking change approval, you could find the approvers list from https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750

This doesnt need a breaking change approval but needs the SDK check for go to succeed. So pl follow up with the owners Ray Chen

**Comment by rkmanda** [comment]
You may request a merge after the go sdk check goes green

**Comment by raych1** [comment]
@alec-baird , 
please resolve the duplicated schema issue for `Go` sdk generation failure.
```error

08:15:26.084 cmderr 	[generator automation-v2]   - properties.identity.$ref: "#/components/schemas/schemas:606" => "#/components/schemas/schemas:842"
08:15:26.084 cmderr 	[generator automation-v2]   - properties.sku.$ref: "#/components/schemas/schemas:607" => "#/components/schemas/schemas:843"
08:15:26.084 cmderr 	[generator automation-v2]   - allOf: <none> => [{"$ref":"#/components/schemas/schemas:833"}]; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
08:15:26.084 cmderr 	[generator automation-v2] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'ResourceModelWithAllowedPropertySet-identity' (1 differences):
08:15:26.084 cmderr 	[generator automation-v2]   - allOf.0.$ref: "#/components/schemas/schemas:615" => "#/components/schemas/schemas:851"; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
08:15:26.084 cmderr 	[generator automation-v2] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'ResourceModelWithAllowedPropertySet-sku' (1 differences):
08:15:26.085 cmderr 	[generator automation-v2]   - allOf.0.$ref: "#/components/schemas/schemas:609" => "#/components/schemas/schemas:846"; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
08:15:26.085 cmderr 	[generator automation-v2] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Sku' (3 differences):
08:15:26.085 cmderr 	[generator automation-v2]   - properties.name.description: "The name of the SKU. Ex - P3. It is typically a letter+number code" => "The name of the SKU. E.g. P3. It is typically a letter+number code"
08:15:26.085 cmderr 	[generator automation-v2]   - properties.tier.x-ms-enum: {"name":"SkuTier","modelAsString":false} => <none>
08:15:26.085 cmderr 	[generator automation-v2]   - properties.tier.description: "This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT." => <none>; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
08:15:26.085 cmderr 	[generator automation-v2] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Identity' (4 differences):
08:15:26.085 cmderr 	[generator automation-v2]   - properties.principalId.$ref: "#/components/schemas/schemas:616" => "#/components/schemas/schemas:852"
08:15:26.085 cmderr 	[generator automation-v2]   - properties.principalId.description: "The principal ID of resource identity." => "The principal ID of resource identity. The value must be an UUID."
08:15:26.085 cmderr 	[generator automation-v2]   - properties.tenantId.$ref: "#/components/schemas/schemas:617" => "#/components/schemas/schemas:853"
08:15:26.085 cmderr 	[generator automation-v2]   - properties.tenantId.description: "The tenant ID of resource." => "The tenant ID of resource. The value must be an UUID."; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
08:15:26.085 cmderr 	[generator automation-v2] fatal   | Error: 6 errors occured -- cannot continue.
08:15:26.085 cmderr 	[generator automation-v2] fatal   | Process() cancelled due to failure 
08:15:26.085 cmderr 	[generator automation-v2] error   |   Error: Plugin prechecker reported failure.
08:15:26.086 cmderr 	[generator automation-v2] error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
08:15:26.086 cmderr 	[generator automation-v2] ##[error]Error running autorest.go

```

**Comment by alec-baird** [comment]
Implementing the identity property that is causing the lintDiff error causing an go SDK error talking about duplicate schemas. What it seems like is adding Identity causes go error, keeping identity out causes lintDiff error. @raych1 and @ms-zhenhua , how should we proceed here?

**Comment by rkmanda** [comment]
> Implementing the identity property that is causing the lintDiff error causing an go SDK error talking about duplicate schemas. What it seems like is adding Identity causes go error, keeping identity out causes lintDiff error. @raych1 and @ms-zhenhua, how should we proceed here?

The issue is that you seem to be adding both a reference to ResourceModelWithAllowedPropertySet (which already has the identity property) and the identity property separately which is causing the duplicate property detection to fire. The linter error you are receiving states that the identity property must be added to the request body of the patch operation. The request of your patch operation only has tags as of now, so you need to modify that to support patch of the identity property

**Comment by alec-baird** [comment]
> > Implementing the identity property that is causing the lintDiff error causing an go SDK error talking about duplicate schemas. What it seems like is adding Identity causes go error, keeping identity out causes lintDiff error. @raych1 and @ms-zhenhua, how should we proceed here?
> 
> The issue is that you seem to be adding both a reference to ResourceModelWithAllowedPropertySet (which already has the identity property) and the identity property separately which is causing the duplicate property detection to fire. The linter error you are receiving states that the identity property must be added to the request body of the patch operation. The request of your patch operation only has tags as of now, so you need to modify that to support patch of the identity property

That makes sense, but we only want mutability on read and create for the identity property that is required in PATCH. How can we reference both ResourceModelWithAllowedPropertySet as well as make that identity property have those mutability atrributes without causing a duplicate error?

**Comment by raych1** [comment]
@alec-baird , there's only one duplicated error now.
```
ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-identity' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-sku' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-plan' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Identity' (4 differences):
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.principalId.$ref: "#/components/schemas/schemas:616" => "#/components/schemas/schemas:852"
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.principalId.description: "The principal ID of resource identity." => "The principal ID of resource identity. The value must be an UUID."
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.tenantId.$ref: "#/components/schemas/schemas:617" => "#/components/schemas/schemas:853"
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.tenantId.description: "The tenant ID of resource." => "The tenant ID of resource. The value must be an UUID."; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] fatal   | Error: 1 errors occured -- cannot continue.
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] fatal   | Process() cancelled due to failure
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   |   Error: Plugin prechecker reported failure.
12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] ##[error]Error running autorest.go
12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] build.go:5: running "pwsh": exit status 1
12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] ': exit status 1
12:57:43.409 cmderr 	[generator automation-v2] Error: total 1 error(s): 

```

**Comment by alec-baird** [comment]
> @alec-baird , there's only one duplicated error now.
> 
> ```
> ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-identity' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
> 12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-sku' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
> 12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/SchemaMissingType | The schema 'ResourceModelWithAllowedPropertySet-plan' with an undefined type and 'allOf'/'anyOf'/'oneOf' is a bit ambiguous. This has been auto-corrected to 'type:object'
> 12:57:43.407 cmderr E 	[generator automation-v2] [ERROR] warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Identity' (4 differences):
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.principalId.$ref: "#/components/schemas/schemas:616" => "#/components/schemas/schemas:852"
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.principalId.description: "The principal ID of resource identity." => "The principal ID of resource identity. The value must be an UUID."
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.tenantId.$ref: "#/components/schemas/schemas:617" => "#/components/schemas/schemas:853"
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] - properties.tenantId.description: "The tenant ID of resource." => "The tenant ID of resource. The value must be an UUID."; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] fatal   | Error: 1 errors occured -- cannot continue.
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] fatal   | Process() cancelled due to failure
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   |   Error: Plugin prechecker reported failure.
> 12:57:43.408 cmderr E 	[generator automation-v2] [ERROR] error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
> 12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] ##[error]Error running autorest.go
> 12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] build.go:5: running "pwsh": exit status 1
> 12:57:43.409 cmderr E 	[generator automation-v2] [ERROR] ': exit status 1
> 12:57:43.409 cmderr 	[generator automation-v2] Error: total 1 error(s): 
> ```

That is correct, but if I remove the identity property to fix the duplicate issue, it causes a LintDiff error stating that PATCH needs to have an identity property. I would assume it is supposed to be taking the property from ResourceModelWithAllowedPropertySet, but it doesn't seem to like that. So I am stuck with either solution causing an error, with or without the property.

**Comment by alec-baird** [comment]
With @rkmanda  approval, we added a suppression for PatchIdentityProperty and are ready for ARM Review/merge.

**Comment by rkmanda** [comment]
> With @rkmanda approval, we added a suppression for PatchIdentityProperty and are ready for ARM Review/merge.

You can address this with your next api version but lets start an email thread or Team chat with Ray Chen to resolve this deadlock

**Review by rkmanda — APPROVED** [review]
:shipit:

**Review by rkmanda — APPROVED** [review]

**Pull request merged**
