### PR TITLE
Adding 2018-01-22 version for ProvisioningServices, adding 2018-01-22 version for IotHubs, adding 2018-04-01 version for IotHubs

### PR DESCRIPTION
**Pull request by kvish**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by anuchandy** [comment]
@kvish It looks like this is a new api version "2018-01-22". Latest existing api version in the master is [2017-11-15](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2017-11-15).


Since this is a new API version both ARM team and SDK team will be reviewing this. 

In order to make the review effective and to ensure a clean repo commit history can you follow below steps? [This step is documented in our contribution guidelines, you can find this link is pasted in the checklist of every PR, see [this](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure) section of contribution guidline ]


0. Close this PR
1.	Copy over ALL the files from [2017-11-15](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2017-11-15) to `2018-01-22` directory.
2.	Commit this change as `git commit -n "Copying over 2017-11-15 files to 2018-01-22"`
3.	Now make changes that are relevant for new api-version `2018-01-22`. In your case, you will have to simply overwrite the files with the changes that you made (since you would have them saved.)
4.	Now commit the changes `git commit -m "Changes for new API version 2018-01-22"`
5.	Push the changes to your fork (`git push origin <branch-name>`)
6.	Send a PR to `master` from your fork. Also make it clear in the PR title & description that this is a new API version.

This way both ARM and SDK reviewers can go to second commit and see the update specific to new api-version. Just make sure the second commit shows the diff correctly.

**Review by anuchandy — CHANGES_REQUESTED** [review]
Please see the comment about restructuring the commits for efficient review.

**Comment by kvish** [comment]
Hi, Anu this PR actually contains 3 new API versions

ProvisioningServices/2018-01-22
IotHubs/2018-01-22
IotHubs/2018-04-01

please advise how to structure the PR for quick review

**Comment by kvish** [comment]
I have edited the title of the Pr for more clarity

**Comment by anuchandy** [comment]
@kvish  this is the first time we are seeing a single PR with multiple api version in it. This is a bit hard to review for both ARM & SDK team. Is there anyway we can split them into 2 PRs?

1. First PR for API version `IotHubs/2018-01-22`. Make sure this PR follows the guideline I mentioned in the above [comment](https://github.com/Azure/azure-rest-api-specs/pull/2518#issuecomment-367242810) that way we can see the diff. Then add one more commit with files for `ProvisioningServices/2018-01-22`. Make it clear in the PR title that it contains `2018-01-22` api version for `IotHubs` and `ProvisioningServices`.

2. It would be good to wait for the above PR to be merged before you open another PR for `IotHubs/2018-04-01`. When you open this PR you need to follow commit guideline I mentioned above but this time copy over the files from `IotHubs/2018-01-22`.

**Comment by kvish** [comment]
ok I will split these changes up and close this and send a new PR

**Pull request closed without merging**
