### PR TITLE
update config files for swagger to net sdk repo

### PR DESCRIPTION
**Pull request by erich-wang**
1. fix output-dir for csharp
2. add support for swagger to net sdk

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
@erich-wang Please request reviews from @tjacobhi for anything relating to the management SDK for Azure Search. I am still the point of contact for the data plane SDK.

**Comment by erich-wang** [comment]
> @erich-wang Please request reviews from @tjacobhi for anything relating to the management SDK for Azure Search. I am still the point of contact for the data plane SDK.

thank you @brjohnstmsft.  @tjacobhi, the change is only part of efforts for enabling swagger to .net sdk automation V2, it doesn't touch any spec files of Azure search management plane. Please let me know if any concern.

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
