### PR TITLE
Add package-2019-11 cost management in java readme

### PR DESCRIPTION
**Pull request by ChenTanyi**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by raych1** [comment]
@ChenTanyi , can you have a look at the detected [breaking change](https://github.com/Azure/azure-rest-api-specs/pull/8778#issuecomment-601509043) in python SDK automation?

**Comment by ChenTanyi** [comment]
@raych1 Is your CI error? I haven't changed anything about API, especially for python.

**Comment by raych1** [comment]
@ChenTanyi , this error is imported from python SDK generation. Is it expected change?
```
[ChangeLog] **Features**
[ChangeLog] 
[ChangeLog] - Added operation QueryOperations.usage
[ChangeLog] - Added operation DimensionsOperations.list
[ChangeLog] 
[ChangeLog] **Breaking changes**
[ChangeLog] 
[ChangeLog] - Model QueryDataset no longer has parameter sorting
[ChangeLog] - Removed operation QueryOperations.usage_by_scope
[ChangeLog] - Removed operation DimensionsOperations.list_by_subscription

**Comment by ChenTanyi** [comment]
@raych1 You can see the changed files, I have do nothing about python sdk. If there is breaking change, please ask the person who change the API. I don't know anything about the python sdk automation.

**Review by raych1 — APPROVED** [review]

**Pull request merged**
