### PR TITLE
[Management Plane][Azure Search] Introduce 2 new API versions for exposing shared private link management

### PR DESCRIPTION
**Pull request by arv100kri**
In this PR, based on consultation from ARM API review board, Azure Search will be officially "removing" `sharedPrivateLinkResources` from the existing API versions of `2019-10-01-preview` and `2020-03-13`. This is because we are introducing several improvements in those APIs, which necessitate breaking changes - and we currently gate those APIs and have 0 usage.

In addition 2 new API versions are introduced, which will ship the `sharedPrivateLinkResources` APIs in the "desired" state.
Also using the new API as an opportunity to utilize some of the common types instead of defining our own.

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [x] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [x] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [x] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [x] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by arv100kri** [comment]
2 diffs that should make things easier to review:

Difference between 2020-03-13 and 2020-08-01 swagger specs (introduction of sharedPrivateLinkResources)
https://www.diffchecker.com/drAZuOoA

Difference between the 2020-08-01 and 2020-08-01-Preview
https://www.diffchecker.com/VRVTwdpd

**Comment by tjacobhi** [comment]
Make sure you edit the file `Readme.md` to include the new tags for the new API version.
https://github.com/arv100kri/azure-rest-api-specs/blob/arv100kri/new-api-versions/specification/search/resource-manager/readme.md

**Comment by ravbhatnagar** [comment]
Signing off from ARM side, since it seems the APIs were gated and had no customer usage. PLease get sign off from azure api review board as well.

**Comment by ravbhatnagar** [comment]
@adrianhall @johanste @JeffreyRichter

**Comment by johanste** [comment]
Why was this ever merged into master if the features were gated? Were there ever any client libraries released with this support?

**Comment by markcowl** [comment]
@johanste @adrianhall @JeffreyRichter Can you please update the tag ('AzureApiBoardSigndoff') if this is signed off?

**Comment by arv100kri** [comment]
> Why was this ever merged into master if the features were gated? Were there ever any client libraries released with this support?

Why was it merged - oversight. We didn't have guidance back then.
There were no client libraries released with this support.

FYI, I have already discussed this issue with @adrianhall and am awaiting his official sign on on the pr.
I haven't published it yet because the deployment that lights up this api version is in progress

**Comment by adrianhall** [comment]
Sorry - thought I had done that already.

**Comment by arv100kri** [comment]
> Sorry - thought I had done that already.

No worries! Thank you. Btw, this will take atleast another couple of weeks to be check-in ready (it's "ready", but only awaiting the roll out to complete)

**Comment by timothyta12** [comment]
Prior discussion about my changes, https://github.com/Azure/azure-rest-api-specs/pull/10244

**Review by markcowl — APPROVED** [review]

**Comment by arv100kri** [comment]
NOTE: This is the .NET SDK PR that fixes the breaking change automation problem
https://github.com/Azure/azure-sdk-for-net/pull/14059

**Review by tjacobhi — APPROVED** [review]

**Review by timothyta12 — APPROVED** [review]

**Comment by akning-ms** [comment]
HI @arv100kri , can you fix linter and avocado validation failure? you should change Preview to preview in your version number to make consistent from others Microsoft.Search/preview/2020-08-01-preview/search.json#L6

**Comment by akning-ms** [comment]
@ArcturusZhang GO SDK and @changlong-liu to take a look potential impact for breaking change

**Comment by ArcturusZhang** [comment]
This will introduce breaking changes to go SDK - but I just checked in terraform, terraform is not using the paths that are removed in this PR, therefore these breaking changes do no impact to terraform

**Comment by changlong-liu** [comment]
Latest Python azure-mgmt-search is released with api-version '2015-08-19'.
The Breaking change comes from the difference between the api-version 2015-08-19 and 2020-08-01.

**Pull request merged**
