### PR TITLE
[ACR] Mark all endpoints as deprecated for 3 oldest preview API's

### PR DESCRIPTION
**Pull request by sindhuselvaraj**
These three API versions (2016-06-27-preview, 2017-06-01-preview, 2018-02-01-preview) will be [retired ](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-api-deprecation?toc=/azure/templates/toc.json) after October 16,2023

# ARM (Control Plane) API Specification Update Pull Request 

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

diagram

[1] [ARM review queue] (for **merge** queues, see [4])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.  
[2] https://aka.ms/azsdk/support/specreview-channel  
[3] [List of SDK breaking changes approvers] in pinned Teams announcement  
[4] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [x] Other, please clarify:
    - Mark all endpoints in oldest preview API versions as they are being retired soon.

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [x] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [x] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to Step 2, "ARM Review", for this PR.

### Breaking changes review (Step 1)

- If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
  - The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
  - You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

### ARM API changes review (Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

## Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

## Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process) 
to get approval.

## Getting help

- For general PR approval workflow, see the diagram at the top of this comment.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[List of SDK breaking changes approvers]: https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

### CODE REVIEW

**Comment by sindhuselvaraj** [comment]
@scbedd @isra-fel @msyyc can you please him with the failed checks? The three API versions updated are the oldest preview versions of ACR and are going to be retired after October 16, 2023

**Comment by msyyc** [comment]
Python failure of CI is fixed

**Comment by scbedd** [comment]
I am giving my signoff for the Model and Semantic validation failures.

- These are _already merged_. There are two possible ways we could have gotten here:
  - We determined we didn't care about those failures before, and approved/merged.
  - This is a new error that wasn't present in the version of the tool used to verify these old old API versions.

In either case, I think it's a bit mean/pointless to block this PR when the _only change_ is to DEPRECATE these API versions.

**Review by scbedd — APPROVED** [review]
Approving for `Model` and `Semantic` validation failures.

**Comment by dolauli** [comment]
@sindhuselvaraj 
CI for Azure PowerShell actually passed according to follow log for the CI.
```
{
  "packages": [
    {
      "artifacts": [
        "swaggerci/containerregistry.DefaultTag/bin/Az.ContainerRegistry.0.1.0.nupkg"
      ],
      "packageName": "Az.containerregistry.DefaultTag",
      "readmeMd": [
        "specification/containerregistry/resource-manager/readme.md"
      ],
      "path": [
        "swaggerci/containerregistry.DefaultTag"
      ],
      "installInstructions": {
        "full": "Please download the package through the curl command 'curl -L https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/25554/azure-powershell/Az.containerregistry.DefaultTag/Az.ContainerRegistry.0.1.0.nupkg -o Az.ContainerRegistry.0.1.0.nupkg', and then you could have a try locally."
      },
      "result": "succeeded"
    }
  ]
}
```
It seems the CI failed at trying to push the generated code to Azure PowerShell repo. Looks like a pipeline framework issue. CC: @raych1 
```
01:49:48.011 git 	Push main to azure-sdk/azure-powershell:main
01:50:43.150 error 	Fatal error: SSL error: syscall failure: Broken pipe
01:50:43.150 section 	Report status
01:50:43.150 error 	The following packages are still pending:
01:50:43.151 error 		Az.containerregistry.DefaultTag
01:50:43.151 info 	Main status [failed] hasBreakingChange [false]
01:50:43.192 info 	Rendered commentSubTitle: 
01:50:43.225 info 	Rendered commentBody: <ul>
  <li>
    <div>
      <code>❌</code>Pipeline Framework Failed [<a
        href="[https://openapistorageprod.blob.core.windows.net/sdkautomation/Azure/25554/azure-powershell/logs.txt?***"](https://openapistorageprod.blob.core.windows.net/sdkautomation/Azure/25554/azure-powershell/logs.txt?***%22)
        >Logs</a
      >] Generate from 1770900e78a0baeac9a6576df43e23424c3bbea0. SDK Automation
      14.0.0
    </div>
    <pre>
command	sh ./tools/SwaggerCI/init.sh ../azure-powershell_tmp/initInput.json ../azure-powershell_tmp/initOutput.json
command	pwsh ./tools/SwaggerCI/psci.ps1 ../azure-powershell_tmp/generateInput.json ../azure-powershell_tmp/generateOutput.json
SSL error: syscall failure: Broken pipe
Error: SSL error: syscall failure: Broken pipe</pre
    >
  </li>
```

**Comment by TimLovellSmith** [comment]
Signing off for ARM. Does not really appear to require an ARM API review, to deprecate API versions, but can rubber stamp it for now.

**Comment by TimLovellSmith** [comment]
@scbedd @msyyc who can look at the go-breaking-changes warning which is currently blocking merge?

**Comment by msyyc** [comment]
> @scbedd @msyyc who can look at the go-breaking-changes warning which is currently blocking merge?

Add Go owner @tadelesh for awareness

**Review by visingla-ms — APPROVED** [review]

**Pull request merged**
