### PR TITLE
typo: relay/resource-manager/Microsoft.Relay

### PR DESCRIPTION
**Pull request by nschonni**
- successfuly -> successfully
- Autorization -> Authorization
- Regenrate -> Regenerate
- retirve -> retrieve
- usermetadata -> userMetadata
- reponse -> response
- namespce -> namespace
- butthe -> but the
- neeeds -> needs

### CODE REVIEW

**Comment by nschonni** [comment]
@sethmanheim @v-ajnava is this a generated API or are these fixes OK?

**Comment by sethmanheim** [comment]
@nschonni I am not working on Relay anymore -- you might check with @spelluru who can confirm with the engineering team.

**Comment by spelluru** [comment]
Clemens is the architect and PM of this service. 

@clemensv - Please review when you get a chance. Thanks.

**Comment by salameer** [comment]
@anuchandy same question here I guess. if these are breaking changes on the generated SDKs, then we might have to abort these changes for now @nschonni :(

As sometime fixing these typose might acutally introduce breaking changes on the generated SDks for customers.

Changes on description are perfectly but it gets tricket with files names sometimes. @anu to verify

**Comment by nschonni** [comment]
Yup, in this case the file name changes are for example files, so I didn't think there should be anything client breaking.
Looks like the Avocado failures are from other example files in the repo, that aren't currently referenced by any specs, not a SDK failure

**Comment by nschonni** [comment]
@salameer I submitted #5621 to fix the Avocado failure. I can move the commit here if that's better

**Comment by nschonni** [comment]
@salameer @anuchandy I updated the example and now everything is green

**Comment by salameer** [comment]
Same for this PR, I would kindly request that we avoid changing the file names

**Comment by nschonni** [comment]
OK, I won't be resubmitting

**Pull request closed without merging**
