### PR TITLE
Adding EU compliance not to description

### PR DESCRIPTION
**Pull request by swhite-msft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by swhite-msft** [comment]
#sign-off

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
approved, but we need to fix (or disable as they are unrelated) ci errors

**Comment by swhite-msft** [comment]
thanks, how do we fix or disable those checks? FYI, there is some urgency to getting this published today to meet EU compliance requirements.

**Comment by zikalino** [comment]
@swhite-msft  html tags should be removed as it breaks doc generation, and then we should be able to force merge this pr

**Comment by swhite-msft** [comment]
@zikalino We need to be able to set off that note to make it visible. Is there a way to do what the HTML tags are trying to do? Also, I used the tags because they worked in https://editor.swagger.io, so I thought we'd support them. Is there a doc somewhere that spells out what we can use to format swagger content, so it doesn't look like one big long string? Thanks

**Comment by swhite-msft** [comment]
#sign-off

**Comment by swhite-msft** [comment]
@zikalino I removed the html tags. please force merge. thx

**Comment by swhite-msft** [comment]
@zikalino, what do I need to do to get this PR merged?

**Comment by zikalino** [comment]
I approved already

**Pull request merged**
