### PR TITLE
fix public swagger issues

### PR DESCRIPTION
**Pull request by Yiliu-microsoft**
### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

### CODE REVIEW

**Comment by hvermis** [comment]
All types being removed here are new, they have not been released in any of the SDKs yet. They are being removed as we found issues with them. Please help getting this PR in as soon as possible to expedite our SDK release.

**Comment by hvermis** [comment]
@shahabhijeet  FYI

**Comment by hvermis** [comment]
@sergey-shandar Can you please merge this as soon as you can? It's blocking our our SDK release.

**Comment by hvermis** [comment]
@sergey-shandar FYI, The types and properties being removed here have not been released in any SDKs yet.

**Comment by zhangyd2015** [comment]
@sergey-shandar This PR is actually a critical bugfix, which fixed the bugs introduced in previous PR, so basically it is not breaking change, and no customer is using it. The SDK build is blocked by this bug.

**Comment by hvermis** [comment]
@sergey-shandar  How can we expedite the review for this PR?

**Comment by nschonni** [comment]
@hvermis from the PR template
>     If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.
>       Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

**Comment by ravbhatnagar** [comment]
As per comment from @hvermis, the properties being removed were accidently added. They have not been released in any SDK. So, it will not be breaking change for any customer. Signing off from ARM side.

**Review by sergey-shandar — APPROVED** [review]

**Pull request merged**
