### PR TITLE
[Monitor] Add missing examples, adding config tag for Java code generation, fixing documentation typos

### PR DESCRIPTION
**Pull request by gucalder**
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

### CODE REVIEW

**Comment by gucalder** [comment]
To be honest I do not know why so many commits are included. Some of them are even merged already...

**Review by alvadb — APPROVED** [review]

**Review by alvadb — CHANGES_REQUESTED** [review]
There appear to be some linter and example errors.  The errors can be viewed here: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/277505580 and https://travis-ci.org/Azure/azure-rest-api-specs/jobs/277505578.  Please review and fix.

**Comment by gucalder** [comment]
I am fixing the errors in the new examples.
The missing example for GetUsageMetrics I included it, but it is empty since the operation is about to be deprecated and nobody is using it.

The errors of the type:
"type": "Error",
  "code": "DefinitionsPropertiesNamesCamelCase",
  "message": "Property named: 'odata.type', for definition: 'RuleCondition' must follow camelCase style. Example: 'odata.type'.",
  "id": "R3016",

Are out of my control. I files an incident

**Comment by gucalder** [comment]
Apparently the Python build job failed.

**Review by alvadb — APPROVED** [review]

**Review by alvadb — APPROVED** [review]

**Pull request merged**
