### PR TITLE
Rename Language 2023-05-01 to 2023-04-01

### PR DESCRIPTION
**Pull request by AhmedLeithy**

### CODE REVIEW

**Comment by JeffreyRichter** [comment]
What is the justification for all the breaking changes shown here: https://github.com/Azure/azure-rest-api-specs/pull/21990/checks?check_run_id=10305263109

**Comment by deyaaeldeen** [comment]
> What is the justification for all the breaking changes shown here: https://github.com/Azure/azure-rest-api-specs/pull/21990/checks?check_run_id=10305263109

@JeffreyRichter For context, the changes here are under the `dev` folder, which houses swaggers currently still in development and are not customer-facing yet.

**Review by deyaaeldeen — APPROVED** [review]

**Comment by kayousef** [comment]
> What is the justification for all the breaking changes shown here: https://github.com/Azure/azure-rest-api-specs/pull/21990/checks?check_run_id=10305263109

@JeffreyRichter As Deyaa mentioned, this is only in dev folder which is a WIP API version that is not released yet. Originally, we were planning for release in May 2023, but then decided to make it in April.
Can you help merge this?

**Comment by JeffreyRichter** [comment]
I don't understand. There was a path that shipped in the 2022-05-01 version and this new version is removing that path which is a breaking change. You say this new version is a WIP and not shipping yet - fair enough. But, when it does ship, it will then break customers. So, are we glad we caught this now so we do not break customers later? I'm afraid that if the Breaking Change Board approves this now, then it will eventually ship & break customers and we dont' want to do this.

**Comment by kayousef** [comment]
> I don't understand. There was a path that shipped in the 2022-05-01 version and this new version is removing that path which is a breaking change. You say this new version is a WIP and not shipping yet - fair enough. But, when it does ship, it will then break customers. So, are we glad we caught this now so we do not break customers later? I'm afraid that if the Breaking Change Board approves this now, then it will eventually ship & break customers and we dont' want to do this. 

@JeffreyRichter can you clarify how does this change remove 2022-05-01?
This PR changes 2023-05-01 to 2023-04-01 (not the year 2023 not 2022)

**Comment by johanste** [comment]
If I understand correctly, the change is to move the API version for a not-yet-shipped API version to an earlier value. Technically, we don't have to make the change. The only reason is to move the API version closer to the expected ship date. 

Our breaking change tools do get royally confused by this, though :).

**Comment by JeffreyRichter** [comment]
When I look at https://github.com/Azure/azure-rest-api-specs/pull/21990/checks?check_run_id=10305263109, see a table at the top with "new version" and "base version". In the table below, I see a "1005 - Removed Path" row saying that the path at https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering-authoring.json#L30:5 no longer exists in the new PR version. It is a breaking change to customer when a path is removed.

**Comment by kayousef** [comment]
> When I look at https://github.com/Azure/azure-rest-api-specs/pull/21990/checks?check_run_id=10305263109, see a table at the top with "new version" and "base version". In the table below, I see a "1005 - Removed Path" row saying that the path at https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering-authoring.json#L30:5 no longer exists in the new PR version. It is a breaking change to customer when a path is removed.

If you check the files changed, they are all in a "dev" folder that is used for under development API versions as per the policy we follow with the SDK crew. 
It seems the checks and validations get confused with this path, which is something we can discuss with @heaths to address with the tooling. But still, the change in this PR is not a breaking change as it was never released to customers.

**Comment by JeffreyRichter** [comment]
Azure's definition of a breaking change is any change that requires customers to change their code. While this version has not yet been released to customers, it will then break them when it is ultimately released and therefore should not ever be released. Your team should be glad that these breaks are being detected early so that your customers will not ultimately be upset with the breaks damaging the reputation of your service and azure overall.

**Comment by heaths** [comment]
What matters is that there are no breaking changes between GA versions under the specification/ folder. So if you're removing a path - even in the dev/ folder (same would be for a topic branch for specification/) - that was in GA and no longer is, that's a breaking change.

**Review by johanste — APPROVED** [review]

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
Please fix the model validation failure as it's blocking the merge.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
