### PR TITLE
fix: network/resource-manager/Microsoft.Network

### PR DESCRIPTION
**Pull request by nschonni**
Remove nextHopType as required because it is not a property. This build will likely fail because of other existing errors in the swagger file for duplicate paths
May be better handled by https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/readme.md#suppression but I'm not sure

### CODE REVIEW

**Comment by nschonni** [comment]
May be better handled by https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/readme.md#suppression but I'm not sure

**Review by jianghaolu — APPROVED** [review]

**Comment by MikhailTryakhov** [comment]
@nschonni please apply your fixes to our montly branchhttps://github.com/Azure/azure-rest-api-specs/tree/december-network-release/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01 to the latest api version ```2018-11-01```

**Comment by nschonni** [comment]
@MikhailTryakhov I've repointed this to the December branch. I'm assuming that will get merged back to master after the release. I'm also not sure this is the right fix , or if this should be a Suppression instead.

**Comment by nschonni** [comment]
@number213 I'm not sure about fixing the duplicate endpoints, since one has a different path with `/reset` at the end https://github.com/Azure/azure-rest-api-specs/pull/4518#issuecomment-447259813

**Comment by number213** [comment]
@nschonni you're right, I pointer to the wrong path. The error is in those two:
- `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{connectionSharedKeyName}/sharedkey`
- `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{virtualNetworkGatewayConnectionName}/sharedkey`

Even though they have different naming for the last parameter, they are essentialy one path.

Let's fix this by mirroring newer API versions (https://github.com/Azure/azure-rest-api-specs/blob/december-network-release/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetworkGateway.json#L1158):
- Move data under `get` from path with `connectionSharedKeyName` to path with `virtualNetworkGatewayConnectionName`
- In that data rename `connectionSharedKeyName` to `virtualNetworkGatewayConnectionName`
- Remove `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{connectionSharedKeyName}/sharedkey`

**Comment by number213** [comment]
@nschonni opened PR with fixes for those two errors: https://github.com/Azure/azure-rest-api-specs/pull/4940

**Pull request closed without merging**
