### PR TITLE
Review request for Microsoft.HealthcareApis to add version stable/2022-12-01

### PR DESCRIPTION
**Pull request by jnlycklama**
This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/release-healthcareapis-Microsoft.HealthcareApis-2022-12-01...main/).
## ARM API Information (Control Plane)

Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [x] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.

Target is early December.

  4. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.

Ideally ASAP, but also targeting early December

  6. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [x] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [x] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

### CODE REVIEW

**Comment by jnlycklama** [comment]
Looking to get an initial approval on this swagger before publishing the ARM spec.

There are a couple of failures that I believe are false positives:
Breaking Changes - RemovedClientParameter. This is because I replaced our own parameters for "subscriptionId" and "apiVerson" with a reference to the same parameter common-types
Swagger Model Validation - MISSING_RESOURCE_ID. This complains because "id" is not in the body in the example. However, "id" is in the body, just not in the properties bag.

**Comment by visingla-ms** [comment]
There are a bunch of breaking changes reported on this PR. Please get a breaking changes approval from Azure Breaking Changes Reviewers <azbreakchangereview@microsoft.com>.

**Comment by visingla-ms** [comment]
>             "$ref": "#/parameters/resourceGroupName"

Why not use ResourceGroupName also from common-types v3?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:2123 in 5642cfc. [](commit_id = 5642cfc94db63a01ca13f04ab1211ef52312b506, deletion_comment = False)

**Comment by visingla-ms** [comment]
>             "$ref": "#/parameters/locationName"

Why not use LocationParameter also from common-types v3?

---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:2258 in 5642cfc. [](commit_id = 5642cfc94db63a01ca13f04ab1211ef52312b506, deletion_comment = False)

**Comment by jnlycklama** [comment]
> > ```
> >         "$ref": "#/parameters/locationName"
> > ```
> 
> Why not use LocationParameter also from common-types v3?
> 
> Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:2258 in [5642cfc](https://github.com/Azure/azure-rest-api-specs/commit/5642cfc94db63a01ca13f04ab1211ef52312b506). [](commit_id = [5642cfc](https://github.com/Azure/azure-rest-api-specs/commit/5642cfc94db63a01ca13f04ab1211ef52312b506), deletion_comment = False)

I tried this before - locationParameter has a different name than ours, which introduces unnecessary breaking changes

**Comment by jnlycklama** [comment]
> > ```
> >         "$ref": "#/parameters/resourceGroupName"
> > ```
> 
> Why not use ResourceGroupNameParameter also from common-types v3?
> 
> Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:2123 in [f6c0cda](https://github.com/Azure/azure-rest-api-specs/commit/f6c0cdadfab85b73fcccbd753e45c815e1e88aa6). [](commit_id = [f6c0cda](https://github.com/Azure/azure-rest-api-specs/commit/f6c0cdadfab85b73fcccbd753e45c815e1e88aa6), deletion_comment = False)

I also tried this before. Our resourceGroupName has a `pattern` field, while common-types does not. Switching introduces unnecessary breaking changes

**Review by sjanamma — APPROVED** [review]
Approving the changes.

**Comment by raosuhas** [comment]
>       }

Not a blocking comment , but consider making this an enum as explained here : [https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices](https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices)


Replace boolean/switch properties with better enum
A Boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Even if you still believe [True, False] are the correct values for a property, you should use a string enum with values [True, False] instead of boolean. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [True, False, Unknown].



---
Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:3834 in 0960efa. [](commit_id = 0960efa139c7585c6b8ef5dcded6aced4f98dc66, deletion_comment = False)

**Comment by fhibf** [comment]
> > ```
> >   }
> > ```
> 
> Not a blocking comment , but consider making this an enum as explained here : https://eng.ms/docs/products/arm/rp_onboarding/process/api_review_best_practices
> 
> Replace boolean/switch properties with better enum A Boolean will forever have two valid values (true or false). A string enum type is always preferred. Also, properties should always provide better values just than True and False. For example two switches "isTypeA" and "isTypeB" should be replaced with one enum "type": [A, B, DefaultType]. Even if you still believe [True, False] are the correct values for a property, you should use a string enum with values [True, False] instead of boolean. Enums are always a more flexible and future proof option because they allow additional values to be added in the future in a non-breaking way, e.g. [True, False, Unknown].
> 
> Refers to: specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/stable/2022-12-01/healthcare-apis.json:3834 in [0960efa](https://github.com/Azure/azure-rest-api-specs/commit/0960efa139c7585c6b8ef5dcded6aced4f98dc66). [](commit_id = [0960efa](https://github.com/Azure/azure-rest-api-specs/commit/0960efa139c7585c6b8ef5dcded6aced4f98dc66), deletion_comment = False)

Thank you for the suggestion, @raosuhas. Using enums is something we'll consider in future changes.

**Comment by visingla-ms** [comment]
SigningOff the changes after last approval.

**Review by xiaoxuqi-ms — APPROVED** [review]

**Comment by xiaoxuqi-ms** [comment]
Hi @jnlycklama , Ishould not merge this pr with errors of API readiness check, it is great to fix this and could you create a pr to fix this?

**Pull request merged**
