### PR TITLE
Update readme.python.md

### PR DESCRIPTION
**Pull request by ChenxiJiang333**
https://github.com/Azure/sdk-release-request/issues/4765

### CODE REVIEW

**Review by msyyc — APPROVED** [review]

**Comment by salambashir** [comment]
Hi @msyyc , Thanks for approving.
I see you enabled auto-merge, but the sdk for go check is failing.
We are only interested in updating the python sdk. How can we address this from here?
Thanks for your help :)

**Comment by msyyc** [comment]
@raych1 Please help fix Go failure.

**Comment by raych1** [comment]
There is a known [autorest issue](https://github.com/Azure/autorest.go/issues/1028) that caused the Go generation failure. 
@ArthurMa1978 , please help force merge this PR.

**Comment by lirenhe** [comment]
> There is a known [autorest issue](https://github.com/Azure/autorest.go/issues/1028) that caused the Go generation failure. @lirenhe , please help force merge this PR.

I don't have the permission for force merge now.

**Pull request merged**
